### ISSUE TITLE
infinite redirect loop between two pages on $emit event

### ISSUE THREAD

**Issue by ArthurianX** [angular-ui/ui-router#1008]
Hey guys, I see many people are having this problem 

http://stackoverflow.com/questions/22887828/angular-ui-router-infinite-loop-on-state-or-location-change

Is this a ui.router bug ? or am I doing something wrong? I can't seem to find a resolution to that redirect loop in those circumstances.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
