### ISSUE TITLE
ngAnimate Won't Work in $stateChangeSuccess

### ISSUE THREAD

**Issue by joshdmiller** [angular-ui/ui-router#1011]
This seems to be a very strange problem. Here's a minimum reproducible scenario:

```js
mod.controller 'AppCtrl', ( $scope, $timeout, $animate ) ->
  $scope.$on "$stateChangeSuccess", () ->
    $animate.addClass theElement, 'my-class'
```

The `$animate` services adds the class, but does *not* do any animation. However, if I wrap the $animate call in a `$timeout`, it works:

```js
mod.controller 'AppCtrl', ( $scope, $timeout, $animate ) ->
  $scope.$on "$stateChangeSuccess", () ->
    $timeout () ->
       $animate.addClass theElement, 'my-class'
    , 1
```

So it seems like without the `$timeout` it's using the core `$animate` rather than the CSS animations module, though I can't imagine why. The same behavior occurs with `$viewContentLoaded`, too. 

Any ideas?

(might be related to #849)

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
