### ISSUE TITLE
Wildcard * parent state

### ISSUE THREAD

**Issue by shmatul** [angular-ui/ui-router#1014]
Each parent state on my app should be available to a child state named "deals/:dealId".
For instance:

state('parent.categories/:catId', {}) can load the 'deals' state:
/categories/clothing/deals/123

state('parent.search/:term', {}) can load the 'deals' state:
/search/nike/deals/123

and so on.

As for the current situation, I have to define the "deals" state for each and every available parent state:

state('parent.categories.deals')
state('parent.search.deals')

Now - maybe I'm not entirely focused on how ui-router works, 
but this case has to be available on my app and I couldn't find any proper solution for it.

If I could use a wildcard state parenting that would be simple awesome:
state('*.deals');

BTW
I tried using a dynamic variable for the state name (currentState+'.deals') but it only catches the default currentState var that has been declared.
If I change currentState the 'deals' state won't be effective on the new current parent state.

Thank you.

**Comment by kri5t** [comment]
+1

I could really use this for a login modal, that I need to apply on different states, so the parent state doesn't change when I open the modal.

**Comment by joaoreynolds** [comment]
+1

**Comment by nateabele** [comment]
Has anyone in need of this functionality taken a look at sticky states in UI Router Extras? https://christopherthielen.github.io/ui-router-extras/#/sticky

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
