### ISSUE TITLE
get $state info of toState in resolve

### ISSUE THREAD

**Issue by gruppjo** [angular-ui/ui-router#1018]
Hi,

I would like to access the state the app is trying to navigate to in a resolve. Apparently it's possible to get the state you're navigating away from by injecting $state, but not the state you're navigating to.
I don't know whether this is a bug or a feature request. But it would be great to be able to do so. I've been able to work around it (more details in link) but I think they're all messy.

I prepared a stackoverflow question for this:

http://stackoverflow.com/questions/22985988/angular-ui-router-get-state-name-in-resolve

**Comment by KobiSh** [comment]
+1

**Comment by gruppjo** [comment]
TaylorMac proposed a great workaround using a decorator - http://stackoverflow.com/a/27255909/1574201

**Comment by KobiSh** [comment]
this way also works..

angular.module('regions').factory('RegionsModalServices',['$modal', '$state',
    function($modal, $state) {
        return ({
            openCreateEditRegions: function (size, regionId, tableParamsList) {
                var modalInstance = $modal.open({
                    templateUrl: $state.get('createRegion').templateUrl,
                    controller: 'RegionsCreateEditController',
                    size: size,
                    backdrop: 'static',
                    windowClass: 'modal-edit-task',
                    resolve: {
                        regionId: function () {
                            return regionId;
                        },
                        tableParamsList: function () {
                            return tableParamsList;
                        }
                    }
                });

            }
        });
    }
]);

**Comment by kayhadrin** [comment]
+1 for this.
It's good to have a good workaround from SO, but it'd be better to have it there by default.

**Comment by nateabele** [comment]
This is slated for an upcoming release.

**Comment by jamesbrobb** [comment]
Did this feature ever get added? I can't find a reference to it in the docs. 

Is it now possible to access the state you're transitioning to in `resolve`?

**Comment by jamesbrobb** [comment]
Any idea when the release containing this feature will be available?

**Comment by nateabele** [comment]
@jamesbrobb It's Open Source, so nobody really knows. :smile: We did just get the sample app running on it this morning though, so an alpha is probably due out soon.

**Comment by nateabele** [comment]
Fixed in 1.0-alpha, which is shipping tomorrow.
