### ISSUE TITLE
enable fuzzy matching for $state.is

### ISSUE THREAD

**Issue by samccone** [angular-ui/ui-router#1019]
For example it would be quite nice to be able to do

``` js
if (!$state.is("foo.*")) {
}
```

instead of 

``` js
if (!$state.is("foo.tap") && !$state.is("foo.bar" )) {
}
```

I would be more than willing to PR this in, wanted to get your thoughts before I implemented.

**Comment by alexey-sh** [comment]
doesn't work when:
state: base (abstract)
state: base.auth (abstract)
state: base.auth.login (common state)

`$state.is('base.auth.*')` => `undefined`
`$state.is('base.auth')` => `false`
`$state.is('base')` => `false`
`$state.is('base.*')` => `undefined`
`$state.is('')` => `undefined`

;(
