### ISSUE TITLE
feat: throw warning when navigation doesn't resolve

### ISSUE THREAD

**Issue by morenoh149** [angular-ui/ui-router#1027]
I had a situation where I was passing a uri `file://path/to/img.png` in `$stateParams` like
```
        $state.go('crop-image', {imageURI:'file://path/to/img.png'});
```
Which would load my controller but wouldn't change the url or load the template
```
  .state('crop-image', {
    url: '/crop-image/:imageURI',
    templateUrl: 'templates/crop-image.html',
    controller: 'CropController'
  });
```
It took forever to realize I had to `encodeURIComponent()` the uri in order to pass the string around successfully. Would be nice to mention this in the docs and even nicer to provide feedback to the developer.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
