### ISSUE TITLE
Allow stateparams that are not in URL to be accessible if URL is declared

### ISSUE THREAD

**Issue by liomry** [angular-ui/ui-router#1030]
I have the following scenario - 

I have an abstract parent state and a dynamic child state which loads templateUrl based on stateParams provided by a factory.

 I wish to use this for multiple step forms (eg register.step1, register.step2) and the factory maps these steps to templates and data using the factories

I want to have the following url setup for the child state - /register/step1, register/step2 and also retrieve the template from the stateParams. Currently if I add it as a query parameter I end up with something like 

/register/step1/?%2Fpartials%2Fregister%2Fmy.template.html

I realise there must be a reason that the $stateParams are treated as they are currently, can someone enlighten me and is it possible to add another set of params to $state, call them configParams or something?

Just to provide reasoning for using this method - I'm going to have several forms which may re-use steps from other forms so I'm using a factory with a javascript object to map steps for forms to templates and data. Using the dynamic child state and stateParams I can re-use templates and other components in a very flexible manner and form discrete building blocks for the application

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
