### ISSUE TITLE
Refer to current state from ui-sref (e.g. for setting url parameters).

### ISSUE THREAD

**Issue by olegskl** [angular-ui/ui-router#1031]
The [documentation](http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.directive:ui-sref) explicitly states _"You can also use relative state paths within ui-sref, just like the relative paths passed to $state.go()."_ However, even though we are able to refer to the current state with `$state.go('.', {foo: 'bar'})` it doesn't seem to work when using `ui-sref` directive. I naively tried `ui-sref=".({foo:'bar'})"` which failed.

Of course it is possible to wire up `ng-click` and `$state.go`, but that leaves us with href-less anchors, which is not very useful from the user perspective.

I've [ventured a related question on stackoverflow](http://stackoverflow.com/questions/23106493/change-a-url-parameter-in-the-current-state-from-ui-sref-in-angular-ui-router) in case somebody had figured it out already. But it appears not to be the case.

Does this functionality exist already (maybe I just missed/misused it)? If not, should it be implemented?

**Comment by albertpeiro** [comment]
+1 on this. Pretty pressing for handling user-friendly async pagination.

**Comment by jaroslavrehorka** [comment]
+1

**Comment by conorgriffin** [comment]
+1

**Comment by demisx** [comment]
+1

**Comment by bennewton999** [comment]
+1

**Comment by zschiffelbein** [comment]
+1 using ui-sref="{foo: 'bar'}" renders the href tag on the first state and does not continue to update on state changes.

**Comment by nateabele** [comment]
Okay, so sounds like maybe the `$watch()` is wrong. If somebody can post me up a quick Plunkr I'll take a look at it.

**Comment by zschiffelbein** [comment]
Pretty sloppy, but it should give you an idea. The expected outcome is for it to stay on either the color or size route when you click on a different item. http://plnkr.co/edit/fARlus6UmokOsdRxbaoS

**Comment by p3rsist** [comment]
I just updated the plunk with AngularJS 1.3.15 and ui-router 0.3.14 and the href tag still does not get updated on state change. http://plnkr.co/edit/8jZCbEVuoO4srwU8fIY5?p=preview

**Comment by nateabele** [comment]
Okay, I see the issue. Should be able to patch it later today.

**Comment by zivc** [comment]
@nateabele any luck?

**Comment by darynmitchell** [comment]
Confirm I am able to switch between items in my current state by changing one param value using
```
<a ui-sref="{ itemId: myItem.id }">
```

angular 1.3.14, angular-ui-router 0.2.13

**Comment by ruleb** [comment]
This only works the first time.
```
<a ui-sref="{ itemId: myItem.id }">
```
On later changes, the itemId is correct, but the suffix part of the pageload URL is used.

Angular 1.3.15, angular-ui-router 0.2.15.

**Comment by spongessuck** [comment]
This seems to work for me:

    ui-sref='.({ id: theID })'

**Comment by darynmitchell** [comment]
@ruleb I later found what you said: I was mistaken, it only worked the first time, but not on later changes. Ended up with a workaround involving marking some states as needing reload using the data object (`data: { reload: true }`), and then a `$on('$stateChangeStart'` handler to see that and perform the reload.

Seems to be working as needed (~2 months use) but feels like a fragile workaround.

**Comment by shprota** [comment]
I would like to submit a possible solution this issue.
The proposed method is to treat the dot placeholder as current state name i.e.:

    ui-sref=".({locale: langCode})"

**Change details:**

In the ui-sref directive code:

      var update = function(val) {
        if (val) def.params = angular.copy(val);

        // If specified state is the "." placeholder, substitute it for the current state name:
        def.href = $state.href(ref.state === '.' ? $state.current.name : ref.state, def.params, def.options);

        if (active) active.$$addStateInfo(ref.state, def.params);
        if (def.href !== null) attrs.$set(type.attr, def.href);
      };

And then watch for the state change to update the href when current state changes:

      if (ref.state === '.') {
        scope.$on('$stateChangeSuccess', function (event, toState, toParams, fromState) {
          if (fromState.name !== toState.name) {
            update();
          }
        });
      }

**Comment by romain10009** [comment]
+1 for handling "."

**Comment by timricker** [comment]
+1 for an elegant notation such as "." to refer to the current state.

Has there been any further progress on this?

**Comment by burzum** [comment]
+1 for this

**Comment by netstyler** [comment]
+1  for handling "."

**Comment by matt-hernandez** [comment]
+1 for the dot proposal!

**Comment by gztomas** [comment]
+1

**Comment by vincentngthu** [comment]
+1

**Comment by mrova** [comment]
+1

**Comment by nateabele** [comment]
Anyone who would like to submit a PR to implement this is welcome to do so.

**Comment by shprota** [comment]
Submitted [my solution](https://github.com/angular-ui/ui-router/pull/2541)

**Comment by mrova** [comment]
@shprota works for me, thanks!

**Comment by Maximaximum** [comment]
It would be great if you could merge @shprota's PR.

**Comment by christopherthielen** [comment]
I've done some analysis on this. We can't use `"."` to mean "the current state" because it already has specific meaning, and it is context sensitive.   A relative link is relative to its context (the state that the ui-sref was created in).  This means that `ui-sref="."` (defined in the state called `home`)  always links to `home`, even if `home.foo` is the current active state.

"." cannot refer to the currently active state, and we already have syntax for parameter-only ui-srefs, but it is broken in some cases.  I am fixing the existing parameter-only ui-sref syntax so it updates when the state changes.  i.e., `ui-sref="{ id: 345 }"`

---

Here's an example which has two states: home and home.foo.  There are both styles of ui-sref links, and their equivalent ui-state links.  Note the difference in behavior (when the current state is home.foo) between links with a "." links without one.

http://plnkr.co/edit/JzuxiVezaAaW697JYE8o?p=preview
