### ISSUE TITLE
Infinite loop when doing a state transition from another state

### ISSUE THREAD

**Issue by phindmarsh** [angular-ui/ui-router#1040]
I've just run into an infinite loop when using `$state.go()` from within a state controller to navigate to another state.

A plunkr showing the problem is [here](http://plnkr.co/edit/2IzWdJNMhfbJUAfxzcWB?p=preview) (one using ui-router at `0.2.10` is [here](http://plnkr.co/edit/X5aCekR7NZC9IKovlnqU?p=preview))

The second one works as expected, and the first causes the ui-view to render loads of times, eventually exhausting the call-stack. (Open a console to see what I mean).

I spent some time digging into the cause, and it looks like its something to do with the `resolveState()` function around [line 1135 of state.js](https://github.com/angular-ui/ui-router/blob/master/src/state.js#L1135), but I'm not sure (basically thats as far down as I got)

Any thoughts?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
