### ISSUE TITLE
$stateProvider interferes with $httpProvider.interceptors when using $location

### ISSUE THREAD

**Issue by zam6ak** [angular-ui/ui-router#1041]
I have an interceptor that catches 401 response error and redirects to a login page.
All the examples I have seen so far suggest using `$location` in the interceptor to do the redirection. However, I noticed that instead of login page, I am always taken to my 404 page which is defined as 'otherwise' state via ui-router's `$stateProvider`....If I switch to using `$window.location` there are no problems...

Why is that? 
Am I doing something wrong? Should I be using `$location` in some other way with ui-router?

Below is commented config block from my app
```
.config([    '$urlRouterProvider', '$stateProvider', '$httpProvider', '$locationProvider',
	function ($urlRouterProvider, $stateProvider, $httpProvider, $locationProvider) {
		// Use $urlRouterProvider to configure any redirects (when) and invalid urls (otherwise).
		$urlRouterProvider
			.when('', '/')          // alias to 'home' state
			.otherwise('/404');     // 404 - Not Found
		// Use $stateProvider to configure your states.
		$stateProvider
			.state("404", {
				url: "/404",
				templateUrl: '/app/home/404.html',
				data: {
					title: '404 - Not Found'
				}
			});

		$locationProvider.html5Mode(true);

		$httpProvider.defaults.headers.common["X-Requested-With"] = "XMLHttpRequest";
		$httpProvider.interceptors.push(['$q', '$location', '$window', function ($q, $location, $window) {
			return {
				'response': function(response) {
					if (response.status === 401) {
						console.log("Response 401");
					}
					return response || $q.when(response);
				},
				'responseError': function(rejection) {
					if (rejection.status === 401) {
						console.log("Response Error 401! Redirecting to /signin...", rejection);
						
						// Using $location does not work, I get /404...
						// I event tried re-applying scope as suggested on the net but it didn't work...
						//$location.path('/signin');	
						//if (!$rootScope.$$phase) { $rootScope.$apply(); }
						
						// This works! Why?
						$window.location.pathname = '/signin';
					}
					return $q.reject(rejection);
				}
			};
		}]);

		
	}])
```

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by rogercoder** [comment]
Thanks, this helped me getting a working interceptor to send back to login page. In our case we also needed a querystring param indicating that the login was expired, which results in a "Your session has expired. Please login again" message to the user. In order to get this query param I had to do this:

`$window.location.pathname = '/aems/login.do';`
`$window.location.search = 'sessionExpired=true';`
