### ISSUE TITLE
Problem with the new typed variables and $urlRouterProvider.otherwise

### ISSUE THREAD

**Issue by kevinrenskers** [angular-ui/ui-router#1043]
I'm testing the changes introduced in #1032 but I seem to be having a hard time with the types in combination with `$urlRouterProvider.otherwise`.

This works: `url: '/channel/{channelId:[0-9]{1,8}}',`.

This doesn't: `url: '/channel/{channelId:int}',`, it always redirects to my 404 page. When I remove `$urlRouterProvider.otherwise('/404');` then it does work.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
