### ISSUE TITLE
TemplateUrl function execution and resolved dependencies

### ISSUE THREAD

**Issue by Shepless** [angular-ui/ui-router#1046]
I have an application where I am lazy loading pre-cached templates (along with a bunch of other script files). This loading is a resolve dependency in an abstract state. I have a child state that inherits from the abstract state and uses a dynamic templateUrl through a function. This templateUrl is points to one of the templates within the script files being lazy loaded. My issue is that the templateUrl function is executed before the promise has been resolved and it there for throws a 404 as it cannot find the template. Is this by design, and if so, what are the reasons? Is there a method of achieving this with a workaround?

If possible it would be a nice addition to have an option to determine if templateUrl functions are executed after resolving dependencies.

A code example:

```js
$stateProvider
    .state('foo', {
        abstract: true,
        url: '/foo/:name',
        controller: 'FooController',
        resolve: {
            foo: ['$stateParams', 'ScriptLoader', function ($stateParams, ScriptLoader) {
                return ScriptLoader.load($stateParams.name);
            }]
        }
    })
    .state('foo.bar', {
        url: '/bar',
        templateUrl: function (params) {
            // I EXECUTE BEFORE THE PARENT ABSTRACT STATE IS RESOLVED
            return params.name + '/' + 'cachedTemplate.html'
        }
    });
```

Thanks

**Comment by sid-papreja** [comment]
I am having same issues. Do you have a solution now?

**Comment by nateabele** [comment]
@sid-papreja Did you try my suggestion in my last comment?

**Comment by davidgaldon** [comment]
@nateabele Thank you so much! Your suggestion works perfectly for me. That's exactly what I was looking for.
