### ISSUE TITLE
What state did I land on?

### ISSUE THREAD

**Issue by Birowsky** [angular-ui/ui-router#1047]
How do I know the state name that I landed on?

When we change route we get $stateChangeSuccess and thats perfect, but we don't get that event when we land on a route directly (paste a url and enter).

I looked at the $state object, but the data there is faulty/empty/uninitialized.

Note:
I am including the ui-view element, but not directly in the body. Its being appended inside of a widget/directive.

**Comment by eddiemonge** [comment]
$state.current should provide the info you need.
