### ISSUE TITLE
Is this a nested view bug?

### ISSUE THREAD

**Issue by liverbool** [angular-ui/ui-router#1049]
### Example app
Parent view with same named by child view why still load.

**index.html**
```html
<html ng-app="foobarbaz">
<body>
    <div ui-view></div>
</body>
</html>
```

**url: /foo**
```javascript
$stateProvider.state('foo', {
    url: '/foo',
    templateUrl: '/view/foo.html'
});
```
/view/foo.html
```html
<div ui-view="content"></div> <!-- inject to index.html > ui-view -->
```

**url: /foo/bar**
```javascript
$stateProvider.state('foo.bar', {
    url: '/bar'
    views: {
        'content@foo': {
            templateUrl: '/view/bar.html'
        }
    }
});
```
/view/bar.html
```html
<strong>Bar</strong> <!-- inject to foo.html > ui-view="content" -->
```

**url: /foo/bar/baz**
```javascript
$stateProvider.state('foo.bar.baz', {
    url: '/baz'
    views: {
        'content@foo': {
            templateUrl: '/view/baz.html'
        }
    }
});
```

/view/baz.html
```html
<strong>Baz</strong> <!-- inject to foo.html > ui-view="content" -->
```

Views loded of this app structure.

**url: /foo**
- /view/foo.html [inject-to: ui-view]

**url: /foo/bar**
- /view/foo.html [inject-to: ui-view]
- /view/bar.html [inject-to: ui-view="content"]

**url: /foo/bar/baz**
- /view/foo.html [inject-to: ui-view]
- /view/bar.html [inject-to: ui-view="content"] **Why this view still load?**
- /view/baz.html[inject-to: ui-view="content"]

** from front-end everything properly work, but in the dev console parent view with same name of child still load and replaced by child when child loaded.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
