### ISSUE TITLE
ui-sref silently ignored invalid state references

### ISSUE THREAD

**Issue by mpolichette** [angular-ui/ui-router#1054]
Hey guys, I love your code,

I think it would be a good feature if the ui-sref directive would be loud and proud about failing when the state was invalid. This happens easily enough from typos, merges or state renames.

Currently the href just ends up null and the link doesn't get set, making it a dead link. 

With a fail early fail fast mentality I'd rather my code throw and error during development than later on when I'm showing it to someone. :) 

Thoughts?  I can probably get together  a pull request on this one if no one has a reason failing silently is good...

**Comment by eddiemonge** [comment]
closing do the reasons nate said. Handling the cases where the state doesn't exist could be done in the app. There really isn't a super reliable way that won't annoy other developers that depend on this functionality now. If you can come up with a good way of handling this, please open a new issue with your proposal.
