### ISSUE TITLE
An option to get the current state name (Child Route)

### ISSUE THREAD

**Issue by aamirshah** [angular-ui/ui-router#1056]
For example I'm in the state `parent.child.another-child`. Now if I do `$state.current.name` I'll get `parent.child.another-child`. 

There should be an option like `$state.current.subchild` which can return the lowest child  in the hierarchy (in my case `another-child`).

As of now I've resorted to do string manipulation of  `$state.current.name` but I think its not good and there should be an option from the router itself.

Btw, `ui-router` is far better that `ng-router`. Great Work :+1:

**Comment by eddiemonge** [comment]
You could change your state definition to be:

```
name: 'another-child'
parent: 'parent.child'.
```

If that doesn't work then let me know and we can figure out if this is something that should be added but my initial feeling is that it isnt and the way you are doing it is ok.
