### ISSUE TITLE
with Html5Mode(true), $state is not working as expect

### ISSUE THREAD

**Issue by chungwong** [angular-ui/ui-router#1057]
when **Html5Mode** is turned on, I found there are somethings are not normal.
Here is the [plunker](http://plnkr.co/edit/DzAr63AmEMkwT9hs011Q)

Before Html5Mode is turned on, $state.current returned the object correctly:
```json
{"url":"","views":{"header-wrapper": {"templateUrl":"header.html","controller":"HeaderCtrl"}},"name":"root"}
```
However, when it is turned on, it showed:
```json
{"name":"","url":"^","views":null,"abstract":true}
```
The problems are:
1. The state name was empty
2. the views was not loaded at all.
3. the url is different

I couldn't figure out what I have missed. 

Thanks.

**Comment by EnSabanNur** [comment]
I'm using an abstract parent state for application wide dependency resolution, and after a recent push to staging we're seeing this after the user is dropped off from a django login page. Funny thing is if we reload the page, or navigate to any link everything behaves correctly. The first landing state (when I grab the reference via: `angular.element(document.querySelector('html')).injector().get('$state')` shows the current state as:

``` js
current: Object
    abstract: true
    name: ""
    url: "^"
    views: null__proto__: Object
```

Most confusing. Our dev boxes that don't have the login have no issues whatsoever.

**Comment by nateabele** [comment]
Do you have a `<base />` tag in your app? It's probably just an issue with the URL not matching. Adding:

```javascript
app.run(function($state) {
  $state.go("root");
});
```

...makes it work fine.
