### ISSUE TITLE
Inconsistent $stateParams service using dynamic-params feature branch

### ISSUE THREAD

**Issue by charandas** [angular-ui/ui-router#1061]
First off, great feature for you guys to have worked on.

In trying to use it however, I am running into the issue where `$stateParams` is coming into one of my controllers as just an `Object` without the prototype that defines `$observe`. I have tried to narrow down what is causing that in that specific controller and haven't been able to determine any pattern.

I am attaching my JS: don't know if it will help. Any help would be great.

```js
.state('app.A', {
  abstract: true,
  url: '/listings',
  template: '<div class="well" ui-view></div>'
})
.state('app.A.layout', {
  abstract: true,
   url: '/:aName',
   controller: 'ACtrl',
   templateUrl: 'views/core/a/layout.html',
     resolve: {                    
      }
})
// In this state, I can access $stateParams.$observe
.state('app.A.layout.main', {
  url: '',
  templateUrl: 'views/core/a/main.html'
})
// In this state, I can't access $stateParams.$observe
.state('app.A.layout.B', {
  url: '/b/:BMode/:location',
  templateUrl: 'views/core/la/b.html',
  controller: 'BCtrl',
  params: {
    AName: {},
    BMode: { dynamic: true }
   }
})
```

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
