### ISSUE TITLE
Routing using $templateUrl with content put in cache with $templateCache does not seen to work

### ISSUE THREAD

**Issue by iwoogy** [angular-ui/ui-router#1063]
Hello,

Thanks for your amazing lib that shifted angular dev to another level. Dealing with states inside each component would have been so painful before.

So I'm refactoring my code from using the core angular routing to the angular ui router, and I have some issues with the $templateCache.

Step 1 : I declare my html code in $templateCache
![2014-05-06_14-15-28](https://cloud.githubusercontent.com/assets/479162/2886922/094bd272-d4f2-11e3-971f-bf641df59e44.png)

Step 2 : I check that the $template cache works with the core routing feature
![2014-05-06_14-15-42](https://cloud.githubusercontent.com/assets/479162/2886931/33a3d812-d4f2-11e3-8027-66dabb8d0d5b.png)

Step 3 : I create a new routing file and remove the core routing file and use the same template url
![2014-05-06_14-15-36](https://cloud.githubusercontent.com/assets/479162/2886937/55617f72-d4f2-11e3-8a3d-18f22f14e853.png)

Step 4 : I load the page to test, and in the console log, I see that angular is trying to load the url template without considering the cache version
![2014-05-06_14-37-29](https://cloud.githubusercontent.com/assets/479162/2886944/7e097934-d4f2-11e3-9e32-39eecc271cfe.png)

I'm pretty new to angular ui router, so maybe there is some obvious reason it does not work.

In reading the api, I found $templateFactory that may help, but I didn't get how to use it while declaring the states.

If anyone can help me understand, it would be so great.

Thanks

Best regards

Bobby

**Comment by wyzellak** [comment]
@guilbep @Crotery Thanks, saved me a lot of debugging effort. :+1:

**Comment by dellheng** [comment]
@Crotery Thanks :+1:

**Comment by nateabele** [comment]
Someone want to add this to the FAQ?

**Comment by Crotery** [comment]
Don't know what will be the question and the answer. The core problem is still hidden, at least for me.  We've just hardcoded absolute urls, so our production works nice. But ui-router still downloads all tpls on developer's machines, and there is no guarantee that other project will not have such issue. 

What about

Q. Trying to put ui-router templates to $templateCache by hand, but ui-router still downloads them.
A. Sometimes angular adds slashes, absolute paths or even absolute urls (http://...) to $templateCache. Make sure you also put same urls to cache.

?
