### ISSUE TITLE
$state.href() ignores 'inherit' option

### ISSUE THREAD

**Issue by derekrprice** [angular-ui/ui-router#1065]
'nuff said.  Visit this plunker http://plnkr.co/edit/JhJf5A?p=preview and notice that the foo.js:getDetailUrl() function generating the "Detail URL" text at the bottom of the page does not pass in the "b" query parameter to $state.href(), yet it is applied.

**Comment by gamebox** [comment]
Interesting.  I am noticing that $state.go() does not respect it when you set `{ inherit: false }`, and am thinking about opening a ticket on the issue.

**Comment by eddiemonge** [comment]
https://gist.github.com/christopherthielen/b3fc0304b737a4bf8ec9
