### ISSUE TITLE
Invisible nested views shouldn't be resolved 

### ISSUE THREAD

**Issue by xaka** [angular-ui/ui-router#1066]
Hello there,

Let's say we have the following states structure:

```javascript
.state('a', {
  views: {
    '': {
      templateUrl: 'a.html',
      controller:  '...'
    },

    'viewA@a': {
      templateUrl: '...',
      controller:  '...',
      resolve:     { ... }
    }
  }
})
.state('a.b', {
  templateUrl: 'b.html',
  controller:  '...'
})
```

And template `a.html` is:

```html
<div ui-view>
  <!-- default content -->
  <div ui-view="viewA"></div>
</div>
```

Now, if you go directly to state `a.b`, it'll override the default content of unnamed view of `a` state as expected. That means view `viewA@a` is invisible until users go to state `a`. The problem here is that being invisible, resolvers of view `viewA@a` are still being called. That leads to unfortunate HTTP requests to backend.

The workaround would be to mark state `a` as an abstract state, create another state `a.index` and move view `viewA@a` to that state. Personally I don't like it because from `a.index` you would have to use syntax like `^.b` go get to `a.b` state and there are some other thoughts.

My expectations that `ui-router` shouldn't do anything to those views that are invisible and somehow it should detect which one are and aren't.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
