### ISSUE TITLE
A child state that opens a $modal with "onEnter" has the $rootScope as parent scope

### ISSUE THREAD

**Issue by roberkules** [angular-ui/ui-router#1076]
I want to open some details in a modal, but can't get the parent's scope inside the modal.

``` javascript
.state("contacts.details", {
  url: '/:id',
  onEnter: function($modal) {
    $modal.open({
      templateUrl: 'contact-details.html',
      controller: 'ContactDetailsCtrl'
    });
  }
})
```

Then inside the `ContactDetailsCtrl` the `$scope.$parent === $rootScope`, but it should be the scope of the `contacts` state.

http://embed.plnkr.co/D4bSuD9YwfQpgokHWyW4/preview

**Comment by pbrain19** [comment]
Did you find the pattern that helped this work?

**Comment by roberkules** [comment]
@pbrain19 sorry, but can't even remember what project I was working on back than... didn't do much with angular since.
I'm not much of a help here. good luck
