### ISSUE TITLE
way to create optional parameter in url?

### ISSUE THREAD

**Issue by legomind** [angular-ui/ui-router#108]
I fiddled with some regex, but this is beyond me.

I need the last parameter in my state to be optional. In other words: capture it if it is there, but otherwise ignore it.

Something like:

``` livescript
$stateProvider
.state \user.page, {
  url: '/:username/:page?'
  template-url: '...'
  controller: [
  \$stateParams
  ($stateParams) ->
    # The page parameter should be optional.
    # This should activate on both '/legomind/dashboard' as well as '/legomind'
  ]
}
```

**Comment by niemyjski** [comment]
+1

**Comment by rwwagner90** [comment]
+1 I need support for an optional trailing slash

**Comment by niemyjski** [comment]
Same here

**Comment by YidingW** [comment]
+1

**Comment by juli3773** [comment]
Hey guys,

I just found the amazing **squash** parameter for the **params** optionnal object in ui-router.
At the bottom of this doc: https://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$stateProvider

So if we take the @AdamBuczynski example : 

```
$stateProvider.state('tutorials.view', {
        reloadOnSearch: false,
        url:            '/:tutorialAlias/:lessonAlias/:lessonSlide',
        controller:     'TutorialsViewCtrl',
        templateUrl:    'tutorials/view/view.html',
        params: {
            lessonAlias: {value: null},
            lessonSlide: {value: null, squash: true} //The parameter's default value is omitted from the URL
        }
    });
```

So it will produce url like if we only have lessonAlias:
**some/url/tutorial-alias/lesson-alias**


Another exemple here with no lessonAlias and a custom lessonSlide value

```
$stateProvider.state('tutorials.view', {
        reloadOnSearch: false,
        url:            '/:tutorialAlias/:lessonAlias/:lessonSlide',
        controller:     'TutorialsViewCtrl',
        templateUrl:    'tutorials/view/view.html',
        params: {
            lessonAlias: {value: null, squash: true},
            lessonSlide: {value: null, squash: 'foo'} 
        }
    });
```

So it will produce url like:
**some/url/tutorial-alias/foo**


I think the **squash** param is a way to avoid double slashes when parameters are missing.

**Comment by rwwagner90** [comment]
@juli3773 Thanks! I'll try that out tonight

**Comment by juli3773** [comment]
@rwwagner90 tell me if it's working ^^

**Comment by jshado1** [comment]
For everyone :+1: this issue, this is already released—you don't need to vote for it anymore. I'm using it in one of my projects and it's working.

**Comment by JohannesFerner** [comment]
@jshado1 could you link the docs for this feature. I couldn't find it. Which one of the notations is implemented?

**Comment by JohannesFerner** [comment]
Link is mentioned in the comment above.

**Comment by rwwagner90** [comment]
@juli3773 sorry for the late response, but it does work. Thanks!

**Comment by rwwagner90** [comment]
So, now I have a new problem. How can I make a parameter required?

**Comment by juli3773** [comment]
What behavior do you want on /profile ?

**Comment by rwwagner90** [comment]
/profile and /profile/ should both just not be valid. They should both be ignored and just go to a 404 page or whatever we decide to show when a route is not valid. Currently, without using ```squash: true``` if I go to /profile or /profile/ it ignores those because there is no id, but once I started using squash, it made /profile and /profile/ valid.

Essentially, what I could not do before was:
```/profile/id``` without a trailing slash.

id is a required param and slug is not. I need the following to all be valid:
```/profile/id```
```/profile/id/```
```/profile/id/slug```
```/profile/id/slug/```

**Comment by muthu07** [comment]
Hey guys, I am stuck on this dynamic parameter passing to my controller, 

template:
<a ui-sref="/single/{{ item.id }}"><img ng-src="{{ item.imageUrl }}"></a>

my state us is look like this,
.state("single", {
            url: "/single/:id",
	    controller: "single",
            templateUrl: "partials/single.html"
        })
controller:
.controller("single", ["ngCart", "$log", "$scope","$stateParams", function(a, b, c, d) {
	c.id = d.id;
        alert(c.id);
    }])

But I am not getting proper output on this. Please any one give me solution..!!

**Comment by towr** [comment]
@muthu07 
That ui-sref does not look valid. I think it should be `ui-sref="single({id : item.id})"`
A ui-sref should contain the (full) state name, not a url. If there are parent states, be sure to prepend them with periods.

NB, www.stackoverflow.com might be a better place for those kinds of questions, seeing as it does not seem to relate to this issue.

**Comment by jsancho** [comment]
@JohannesFerner as well as anyone else.
You can check the commit comments for some sort of interim documentation
https://github.com/angular-ui/ui-router/pull/1032

Then there's the comments from the squash pull, where the syntax seems to have changed ever so slightly https://github.com/angular-ui/ui-router/issues/1501

from <code> params: { foo: { value: null } }</code>

to <code> params: { foo: null }</code> 

But I'm not quite getting all of this to work.
It would be really neat if the official wiki could be updated - by someone in the know - with the current implementation as per the latest release 0.2.13

**Comment by jsancho** [comment]
Please disregard my previous comment, the documentation is here 
http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$stateProvider
(just browse to the <code>params</code> section at the bottom.

the <code>params: { foo: null }</code> format is a actually a shorthand when you only need to specify the value of the param.

And I just don't seem the get optional params to work as expected, which is also unrelated to the otherwise clause that

**Comment by ilbarzo** [comment]
+1

**Comment by nateabele** [comment]
Alright, closing this out. @rwwagner90 if you have a different problem, please post that in a new issue so I don't have to read a small novel to figure the status of it. :wink: :beers:

**Comment by rosinghal** [comment]
@juli3773 thanks a lot

**Comment by beeant** [comment]
+1

**Comment by slavafomin** [comment]
I want to have optional integer-type parameter like this: `url: '/sign-up/{partnerId:int}'`, is it possible?

**Comment by juli3773** [comment]
@slavafomin Yes it's possible! So you'll have:

```sh
url: '/sign-up/{partnerId:int}', 
params: { 
    partnerId: {value: null, squash: true}
}
```

**Comment by slavafomin** [comment]
Thank you @juli3773, I've finally managed to find a similar solution. Is `squash: true` is really necessary? I have the following code:

```javascript
params: { 
    partnerId: null
}
```

And it seems to work great )

**Comment by juli3773** [comment]
@slavafomin the ```  squash: true``` is necessary only if you want your parameter to be optional!

**Comment by DVassilev** [comment]
I tried /s/{param1}/{param2}/{param3} and so forth including 
`params` : { param1: {value : 'default'}, ... }

but it won't match /s/ and then auto populate the rest of the params with default value. It only works if I populate all params but the last one, then it will work but now show the default value in the URL. Any ideas on why @okendoken ?
