### ISSUE TITLE
ui-view duplicated temporarily during initial page load

### ISSUE THREAD

**Issue by jeffwhelpley** [angular-ui/ui-router#1080]
My server will fill in some content within the ui-view just so users see something while the  view is being loaded. I noticed that the ui-view div is being duplicated while the view is loaded and then once it is fully loaded one of the ui-view divs is destroyed. So, ultimately there is only one ui-view and it contains the right thing, but the issue is that by duplicating the ui-view div temporarily it causes a number of issues with some stuff I am trying to do with the initial load.

So, is there any way to use ui-views without this element duplication? Is it a bug or just the way the ui router works?

I am using 0.2.10. I tried downloading the latest from the github repo and using that to no avail. When I go back to use 0.2.7, there is no temporary ui-view duplication and things work fine.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by helzgate** [comment]
I resolved this by adding the following to my run config:
   $rootScope.$on('$stateChangeStart', function(event, toState, toParams, fromState, fromParams){
       $animate.enabled(false);
   });

**Comment by tienvx** [comment]
@helzgate It works for me, thanks you so much!

**Comment by SuperDuperPengu** [comment]
@helzgate Wow. This worked for me. Thank you, good sir.
