### ISSUE TITLE
In html5 mode $urlRouterProvider.rule() is ignored unless at least one ui-sref appears

### ISSUE THREAD

**Issue by jrief** [angular-ui/ui-router#1092]
I prefer to use ``<a href="a-real-url">...`` rather than ``<a ui-sref="state">...``, so that I can mix state changes with real page (re)loads.
I then use ``$urlRouterProvider.rule(function($injector, $location) {...})`` to check the current ``$location.path()`` and depending on that URL, make a state transition or load a different page.
This works fine so far, but only if there is at least one ``ui-sref`` directive in my HTML, say ``<div ui-sref="dummy"></div>``. This is somehow weird, because that directive is not good for anything.
Does adding that dummy directive to my HTML code, trigger some kind of initialization code during HTML compilation?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
