### ISSUE TITLE
Setting parent state as string not working

### ISSUE THREAD

**Issue by hellerstanislav** [angular-ui/ui-router#1093]
Hi,
I am not quite sure what am I doing wrong. Plunker with **not** working example: http://plnkr.co/edit/qCtoC5?p=preview (example forked from ui-router docs)

According to docs, this assignment of parent state to new state should work when parent state provided as string:
```
$stateProvider
  .state('route1', {})
  .state('list', {
    parent: 'route1'
  });
```
Notice that in `route1.html`, there is line: `<a ui-sref=".list">Show List</a>`. But when clicked on "Show List", this just throws exception
```
Error: Could not resolve '.list' from state 'route1'
```

I found that if i rewrite `route1.html` from:
`<a ui-sref=".list">Show List</a>` to `<a ui-sref="list">Show List</a>`, it works as expected. But if there in `ui-sref` is `route1.list`, this does not work either (same kind of exception)

The thing is: when I write the parent state into the name of new state, it works with the dot in ui-sref: `.list`:
```
.state('route1.list', {}) <-- this just works..
```
I tought that these definitions of state are identical and independent of what i write into the `ui-sref`, arent they? Is this expected behaviour or some kind of bug?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
