### ISSUE TITLE
Ability to remove states from $stateProvider

### ISSUE THREAD

**Issue by JensEger** [angular-ui/ui-router#1095]
We are perform lazy state binding. This brings the advantage, that a authenticated (or even a unauthenticated) User can "see" only his states / routes, which is also a security reason.

When a user logs out, i am not able to clear the lazy registered routes. I would like this to be implemented. This could be a really interessting feture, because i saw this lazy registration in other SPA's .

Suggested usage: 
```
$stateProviderService.removeState('statename')
```

**Comment by christopherthielen** [comment]
Closed by 44579ec
