### ISSUE TITLE
State change scrolls page to top

### ISSUE THREAD

**Issue by rynz** [angular-ui/ui-router#110]
If you create a scrollbar, eg by resizing the Sampe App. Whenever you change state, it scrolls to the top of the page.

If state changes, it shouldn't look like a browser refresh, rather change the nested elements accordingly and maintain where the scrollbar is set.

Eg:
Run Sample App.
Click Contacts.
Resize Sample App so you have a scrollbar.
Scroll to bottom
Click "Show random contact" or Email or Edit etc

The page will jump to the top.

Is this the desired effect?

**Comment by wkonkel** [comment]
Here is how I solved the scroll-to-top-on-new-page problem:

http://stackoverflow.com/questions/21055952/changing-route-doesnt-scroll-to-top-in-the-new-page/29153678#29153678

**Comment by JobaDiniz** [comment]
Hi, I want to enable *auto scroll* when the state changes... is that not possible anymore? What is the **not hacked** solution?

**Comment by zwacky** [comment]
the following solved my problem. maybe someone comes across the same.
```
if ('scrollRestoration' in history) {
    history.scrollRestoration = 'manual';
}
```

**Comment by rafaelune** [comment]
Tks a lot @gaelduplessix!!

**Comment by yaplas** [comment]
that is the solution zwacky, thanks
