### ISSUE TITLE
Adding custom previous property to the $state object

### ISSUE THREAD

**Issue by thak123** [angular-ui/ui-router#1100]
Ability to remember the previous state from which the current state was reached ...

Is there a way to add custom previous property to the $state object in the controller when i am changing the the State...

For ex i am on state A going to state B and i can go to state C from state B also from D i can go to State C ,

i want to remember from which state i jumped to state C ..i.e either B or D 

So may be we can have  a construct which takes in the custom properties and which can be used later when going back..

So i will just say $state.goBack()

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
