### ISSUE TITLE
How do you short-circuit route with empty required $stateParams?

### ISSUE THREAD

**Issue by kbiesbrock** [angular-ui/ui-router#1102]
I have two routes:
* _root_: "/"
* _dogs_: "dogs?name"

If the user navigates to `/dogs?name=` then I want to show an error on the screen and re-route to _root_. Because, in this contrived example, searching with an empty `name` could take 10 minutes to process on the back-end.

But that's not all.

This redirection should short-circuit anything else that would normally resolve in the route.

See the plunker: http://goo.gl/Q4AQG3
Fullscreen: http://goo.gl/dN02yD

In routes.js, line 13 (`$state.transitionTo("root");`) should be the last thing that happens. Otherwise, the resolution of `dogs` makes an invalid attempt to retrieve dogs by name.

So. Is this a clear example? Is there a way to short-circuit the dogs route?

Thank you,
Beez

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
