### ISSUE TITLE
Blue selection around Alice/Bob contact disappears when their Phonenumber is selected

### ISSUE THREAD

**Issue by bastienJS** [angular-ui/ui-router#1105]
When Alice on the left side is selected and on the right side appears Phone number and email and I click on Phone number, why does on the left side the selection disappear?

Or said in other words if this is not a bug, how can I make it stay selected?

![image](https://cloud.githubusercontent.com/assets/5945955/3103849/c6ad2196-e65d-11e3-9426-b5fd6114154c.png)

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
