### ISSUE TITLE
Add $stateChangeComplete event

### ISSUE THREAD

**Issue by donaldpipowitch** [angular-ui/ui-router#1112]
Small feature request: Could you add an `$stateChangeComplete` event, which is triggered after `$stateChangeSuccess` and `$stateChangeError`? Analogous to the promise API: `then`, `catch` and `finally`. Most APIs for async operations have a similar style.

Quick hack for now (in case anyone needs this):
````
angular.forEach([ '$stateChangeSuccess', '$stateChangeError'], function(event) {
  $rootScope.$on(event, function(event, toState, toParams, fromState, fromParams, error) {
    // do stuff here...
    // error param is undefined for $stateChangeSuccess
  });
});
````

**Comment by eddiemonge** [comment]
state events are going away in 1.0 so closing this.
