### ISSUE TITLE
Default values for stateParam

### ISSUE THREAD

**Issue by pdeva** [angular-ui/ui-router#1120]
while #436 proposed the same question a while back, it was closed with the context being a fix was in the works. However, while the said 'fix' is finished, there still isnt a way to provide default values to $stateParams.

The suggested method in that thread of using urlRouterProvider dont work when the url itself can contain stateparams and thus not be known in advance.

**Comment by jablesauce** [comment]
It seems that once a param is changed, it has to be changed back even if the parameter is untouched on the next time it is redirected to.

**Comment by christopherthielen** [comment]
@jablesauce you might be seeing the parameter inheriting behavior of `{ inherit: true }`

both the `ui-sref` and `$state.go()` inherit by default.

https://ui-router.github.io/ng1/docs/latest/interfaces/transition.transitionoptions.html#inherit
