### ISSUE TITLE
Add ability to specify scope values in state configuration

### ISSUE THREAD

**Issue by kbaltrinic** [angular-ui/ui-router#1121]
It would be nice if as part of the configuration object for a state, one could specify values that should be merged into the scope for that view (via angular.extend).  Currently I have to do something like the following:

```CoffeeScript
#contrived example
commonTemplate =  "<h1>{{heading}}</h1><div>{{text}}</div>"
commonController = ($state, $scope) -> angular.extend($scope, $state.current.scopeValues)
$stateProvider.state('page1',
    template: commonTemplate 
    controller: commonController
    scopeValues:
        heading: 'Page 1'
        text: 'Text for page 1.'
).state('page2',
    template: commonTemplate 
    controller: commonController
    scopeValues:
        heading: 'Page 2'
        text: 'Text for page 2.'
)
```
It would be nice to not need to include this boiler-plate angular.extend(...) code in all my controllers.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
