### ISSUE TITLE
Uncaught object when transitioning between states

### ISSUE THREAD

**Issue by tdekoning** [angular-ui/ui-router#1122]
I'm encountering an uncaught object error when moving from one childstate to the other.
This only occurs in the case that the target child state has the params-attribute filled, and the parent state has url-parameters. See example:

```
$stateProvider.state('parentstate', {
  url: '/parentstate/:firstparam/blaat',
  template: '<ui-view/>',
  controller: function( $state ) {
    $state.go('childstate');
  }
});

$stateProvider.state('secondChildstate', {
  params: ['secondparam'],
  parent: 'parentstate',
  template: '<p>Random words!</p>',
  controller: function( $stateParams ) {
    console.log('stateParams:', $stateParams);
  }
});

$stateProvider.state('childstate', {
  parent: 'parentstate',
  template: '<div ui-sref="secondChildstate({secondparam: \'hello\'})">Click to go to the second childstate</div>',
});
```

Then if i add 'firstparam' as an entry in the params-array of secondChildstate, the states work as they should. But it's not really nice to duplicate the parameters in all child states.

Why do we need to duplicate the parameters of the parent state and why is the error not understandable?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
