### ISSUE TITLE
state is not loaded if it's added after module creation

### ISSUE THREAD

**Issue by panuhorsmalahti** [angular-ui/ui-router#1123]
In this use case the active state is defined after an async ajax call. However, if the current url matches the state which has been defined at a later time, the view is not loaded or rendered correctly.

angular-ui works like this currently.
1. The browser loads /glob
2. AngularJS / ui-router is loaded and states are created, but not a state for /glob
3. A state "glob" for url "/glob" is created
4. The template for glob is not rendered
(Optional: 5. You can now load the glob state manually)

How angular-ui should work:
1. The browser loads /glob
2. AngularJS / ui-router is loaded and states are created, but not a state for /glob
3. A state "glob" for url "/glob" is created
4. ui-router notices that the new state corresponds with the current url, so the state is actived and the view is rendered

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
