### ISSUE TITLE
RFC: Detached state

### ISSUE THREAD

**Issue by sarunas** [angular-ui/ui-router#1133]
Hi,

just wanted to discuss how to solve one use case with ui-router.

Problem:
- Open modal dialog (base of solution as in FAQ)
- Modal background should be last state
- Then going to modal state (url) directly it should have default state in background 

To solve this issue, added few things in ui-router core:
- detached option
- needState option

Usage:
```js
    $stateProvider.state('modal', {
      url: '/modal',
      detached: true,
      needsState: true,
      needsStateDefault: 'defaultStateName',
      onEnter: ['$state', '$modal', function ($state, $modal) {
        var modal = $state.modal = $modal.open({
          template: '<div>Modal with state in background</div>'
        });

        modal.result.then(null, function () {
          $state.modal = null;
          return $state.transitionTo($state.$detached || 'defaultStateName', $state.$detachedStateParams);
        });
      }],
      onExit: ['$state', function ($state) {
        if ($state.modal) {
          $state.modal.close();
        }
      }]
    });
```

Changes (no tests yet):
https://github.com/sarunas/ui-router/compare/detached-states-pr

What stuff o I need to make in order these features to be part of ui-router?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
