### ISSUE TITLE
Optional query param defaults not being taken from params in state definition

### ISSUE THREAD

**Issue by charandas** [angular-ui/ui-router#1134]
I am running into this specific case, wherein the optional query parameters don't default from the `params` in state definition.

Replicated in this [plunkr](http://plnkr.co/edit/QRFwXYjPjG5UaICtR66s).

To replicate:
1. Click "Show Defaults": it captures all the optional params except the query params
2. Click the "... Override": it shows the respective overrides

Also, in this plunkr itself, there is weirdness related to a child controller persisting a parent-inherited param. Is this to be expected? To replicate this, click "Show Defaults" after the procedure noted above. It **doesn't** bring back the defaults in view.

Am I doing something incorrect? Is this valid behavior.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
