### ISSUE TITLE
Loading child of child into its parent view

### ISSUE THREAD

**Issue by suriyagp** [angular-ui/ui-router#1135]
is it possible to load a child of a child view into its parent view
PARENT
||
==== CHILD1
                  ||
                  ====== CHILD 2
 Here, parent is also inside a "ui-view" ,and child1 is also inside a"ui-view" of parent.
child2 wants to be placed in"ui-view"of parent from "the child1"

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by stryju** [comment]
also, what about named view of a parent?
