### ISSUE TITLE
Allow managing state transition asynchronously. 

### ISSUE THREAD

**Issue by petrukhnov** [angular-ui/ui-router#1139]
Idea is similar to one of the comments from https://github.com/angular-ui/ui-router/issues/618

pause()
resume()
halt()

E.g. now I adding service that watch forms, and show modal to user when user try to navigate away. Modal is async, so i need to do some tinkering. Can't say if it is correct solution, but it seems it works now. 

```
var initialTransition = true;
$rootScope.$on('$stateChangeStart', ... {
  if (!initialTransition) {
    return;
  }
  some async call().then(function() {
    if(stayOnCurrentState) {
      return;
    }
    initialTransition = false;
    $state.transitionTo(to, toParams);
    initialTransition = true;
  });
   event.preventDefault();
});

```

One way to solve it, could be some method that do these. Another option would be to add new option 'skipStart', that will allow to skip  only '$stateChangeStart' (similar to 'notify' option).

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
