### ISSUE TITLE
More scalable examples?

### ISSUE THREAD

**Issue by uberspeck** [angular-ui/ui-router#114]
First, thanks for the excellent resource! I'm looking forward to using it on a major application rebuild. Just trying to wrap my head around it now ;)

Wondering if someone could give examples demonstrating how ui-router might scale to much larger applications (than the sample app for example)? I'm fairly new to Angular and just started reading up on ui-router. The sample app demonstrates everything in a single JS file. How might I proceed if my JS is spread across separate files (appConfig.js, appController.js, usersControllers.js, accountControllers.js etc). Can I pass my controllers to _config_ using dependency injection? Defining them all inline isn't very feasible for a project of this size and I'm trying to keep things separated as much as possible for maintainability.

**Comment by lucassus** [comment]
Here you could find my proposal. The solution is based on ES6 modules
https://github.com/angular-ui/ui-router/issues/1051#issuecomment-255690491
