### ISSUE TITLE
$stateProvider and  $urlRouterProvider need better visibility in the doc

### ISSUE THREAD

**Issue by XrXr** [angular-ui/ui-router#1145]
~~The [new doc](http://angular-ui.github.io/ui-router/site/) is missing $stateProvider and  $urlRouterProvider. They are present in the [old doc](https://github.com/angular-ui/ui-router/wiki/Quick-Reference). Am I missing something?~~
The link to $stateProvider and  $urlRouterProvider in the [new doc](http://angular-ui.github.io/ui-router/site/) are not too visible. They should be normal text buttons instead of just a gear icon

**Comment by nateabele** [comment]
> The link to $stateProvider and $urlRouterProvider in the new doc are not too visible. They should be normal text buttons instead of just a gear icon

This is the way ngDocs works. I'm open to alternative (specific) suggestions of where else we can link them.

**Comment by XrXr** [comment]
Now that the gear icon has text next to it, it's pretty obvious. Thanks!
