### ISSUE TITLE
Browser refresh causes unexpected state change

### ISSUE THREAD

**Issue by jerrykur** [angular-ui/ui-router#1147]
Hi,

I am trying to determine why refreshing (ex. f5) the browser causes the state to change to first state before completing the controller that defines the stateProvider.  That is in the controllerA I have 

.config([$stateProvider", .....
$stateProvider 
            .state("leftNav", {
                url: "/leftnav",
                templateUrl: "MainPage/app/leftnav.html",
                controller: "leftNavController"
            })
            .state("leftNav.reports", {
                url: "/reports",
                templateUrl: "MainPage/app/nav.reports.html",
                controller: "navReportsController"
            }) , .....
.....
.controller('A', ..., function A() {

    ..  define variables ....
    $http('getdata' ). then {
       ... do some initial processing ...
       $state.go("leftNav")

This all works fine when I initially load the page.   As expected, it does not change to the "leftNav" state until the $state.go('leftNav') is hit.  

But when I press f5 the ... define variables ..  code executes as expected and then I am suddenly inside the controller for "leftNav".  I have not executed a $state.go.  

When I inspect the stack I see a number of calls inside angular-ui-router that start with function transitionTo(to, toParams, options) and end with the $ViewDirectiveFill() executing        
     if (locals.$$controller) {
          locals.$scope = scope;
          var controller = $controller(locals.$$controller, locals);
The last line seems to jump into the controller,
    
Could someone explain to me why this is occurring when I refresh the page?  And how I can prevent it from occurring.

Thanks!

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
