### ISSUE TITLE
query parameters

### ISSUE THREAD

**Issue by KBPratap** [angular-ui/ui-router#1148]
I am not able to get the query parameters from the URL.

for a sample URL: #\books\:categoryID?publisher=xyz (#\books\value?publisher=xyz).
This is the issue I am facing when using $location for programmatic navigation.

The $stateParams extracts the data as {categoryId:value?publisher=xyz} but I need to get it as {categoryId:"value", publisher:"xyz"}

I found reference to $urlMatcherFactory but there is not much documentation available.

Any help would be great!!!

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
