### ISSUE TITLE
Dynamic-params and Back button

### ISSUE THREAD

**Issue by websirnik** [angular-ui/ui-router#1150]
Testing out "dynamic-params" branch. 
My use-case is slideshow.
```js
.state('presentation', {
    url: '/:presentation_id',
    templateUrl: '/partials/presentation.html',
    controller: "PresentationCtrl"
})
.state('presentation.slide', {
    url: '/:slide_id',
    templateUrl: '/partials/slide.html',
    controller: "SlideCtrl",
    params: {
        slide_id: {
            value: null,
            dynamic: true
        },
        presentation_id: { // For some reason I need this here for dynamic params to work. It's fine, it's not the question
            value: null,
            dynamic: false
        },
    }
})
```
From `/presentation-id` I open `/presentation-id/slide-1`, 
then  `/presentation-id/slide-1` -> `/presentation-id/slide-2`
Then when I press the Back button in the browser from  `/presentation-id/slide-2` I get back to `/presentation-id`.
I would expect to go back to `/presentation-id/slide-1`.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
