### ISSUE TITLE
Ability to pass resolves to my state from a view

### ISSUE THREAD

**Issue by intellix** [angular-ui/ui-router#1154]
I think it would be amazing if you could (can you?) pass in a resolved object from a view.

```js
// Loop through properties and display summaries and <a ui-sref="properties.view({id: property.id})">View</a> links in my view
.state('properties', {
    url: '/properties',
    resolve: {
        properties: function(PropertyService) {
            return PropertyService.fetchAll();
        }
    }
})
// View property (detailed)
.state('properties.view', {
    url: '/properties/:id',
    resolve: {
        property: function(PropertyService, $stateParams) {
            return PropertyService.fetch($stateParams.id);
        }
    }
});
```

 - If you visit properties, it will fetch all Property entities from my API.
 - If you visit property.view, it will fetch that Property entity from my API.

Viewing a property is an extra API call if I'm already looking at a list. I think it would be real awesome if you could resolve from your view like:

`<a ui-sref="properties.view({id: property.id}, {property: property})">View</a>`

Then instead of calling my API for that property, it would be passed in straight from the view. Yeah this can be achieved using a Service and some magic, but it adds complexity and think it would be extremely convenient coming straight from a view as we already have that object there.

Also, if your `fetchAll()` API call returns an array of thousands of objects and you'd like to retrieve it from your cache instead of calling `fetch()`. Something like `_.findWhere(cache.objects, { id: item.id });` before making the extra call would be much more expensive than pushing your object straight to the state if you already have it.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
