### ISSUE TITLE
html5Mode appears not to work

### ISSUE THREAD

**Issue by laurelnaiad** [angular-ui/ui-router#116]
_(note I've edited this since I first posted it)_

I was happy to see from https://github.com/angular-ui/ui-router/issues/69 that html5Mode should just work.  It doesn't work for me with the sample in Chrome or Firefox.  I haven't tested any other browser.

Steps: 
- clone the repository
- npm install
- grunt
- npm install express
- node server.js (which just launches a server for me at port 3006 over the ui-router directory.

http://localhost:3006/sample

everything works.

change three lines in index.html (starting at line 50)

```
    [        '$stateProvider', '$routeProvider', '$urlRouterProvider', '$locationProvider',
    function ($stateProvider,   $routeProvider,   $urlRouterProvider, $locationProvider) {
      $locationProvider.html5Mode(true);
```

After that change, when I go to /sample the content for that page loads and displays properly and then I'm "location.replaced" to "/" and everything ceases to function.

I tried to figure out where things head south but I just don't know the code well enough.

Top level routes and their dynamic segments do work **if I copy the build and lib directories into the sample directory and change the paths to them**, but deeper routes do not (e.g. /contacts/1 works but /contacts/1/item/a does not).

**Comment by abhishekbhalani** [comment]
@christopherthielen I am getting same issue..
When we manually enter on browser after HTML5 Mode then it page not found error. otherwise it working..

**Comment by anil826** [comment]
Finally I got a way to to solve this issue by server side as it's more like an issue with AngularJs itself I am using 1.5 Angularjs and I got same issue on reload the page.
But after adding below code in my `server.js` file it is save my day ***but it's not a proper solution or not a good way .***

    app.use(function(req, res, next){
      var d = res.status(404);
         if(d){
         	res.sendfile('index.html');
         }
    });
