### ISSUE TITLE
Adding karma jasmine tests to the sample

### ISSUE THREAD

**Issue by OliverKK** [angular-ui/ui-router#1162]
It would be very nice to have a bunch of test's for the $stateProvider and $urlRouterProvider.

**Comment by kmthinkingrock** [comment]
I will second/third this request - I am trying to write my own tests, and being new to the Angular/Jasmine/UiRouter world, it is a challenge - I have looked at one of the test files, but I have not had a chance to digest any of it. So, anything that would help in the realm of providing patterns to users of angular-ui-router for tests, would be hugely appreciated.
