### ISSUE TITLE
uiSref does not update link

### ISSUE THREAD

**Issue by osimicek** [angular-ui/ui-router#1164]
I use uiSref to create link from state name and params.
The params contain id.
```
$scope.params = {id: 123}
```
I create link this way
```
<a ui-sref = "page(params)"> </a>
```
This creates link /page/123
When I change attribut of params (reference to the dict is same)
```
$scope.params.id = 9
```
the link doesn't change to /page/9.

I believe the bug is on this line https://github.com/angular-ui/ui-router/blob/master/src/stateDirectives.js#L120 where you compare references of newVal !== params. You should compare values of attributes too.

**Comment by nateabele** [comment]
This should be resolved now. If you're still having trouble, please open a new issue with a link to a plunkr that demonstrates it. Thanks.
