### ISSUE TITLE
<a href="#" /> crashing with ui-router

### ISSUE THREAD

**Issue by songyanho** [angular-ui/ui-router#1167]
I have a bootstrap template and wished to integrate AngularJS and ui-router.

However when the page having link

```
<a href="#">Example 1</a>
<a href="#goToExample2">Example 2</a>
```

the page will automatically jump back to the location which I set initially

```
$urlRouterProvider.otherwise("/home");
```

May I know how could I preserve the # link and integrate ui-router perfectly.

**Comment by patbi** [comment]
good evening here is my integration but I no longer have access to my application of not found css and js

var patrickBIYAGA = angular.module('SeeDocApp', ['ui.router']);
// 'firebase'

patrickBIYAGA.config(["$locationProvider",function($stateProvider, $urlRouterProvider, $locationProvider) {
    
    $locationProvider.hashPrefix('!');
    
    $urlRouterProvider.otherwise('/home');
    
    $stateProvider
        
        // Toutes mes routes donc déjà l'accueil ========================================
        .state('home', {
            url: '/home',
            templateUrl: 'templates/home.html'
        })
        
        // route pour aller sur aide
        .state('help', {
            url: '/help',
            templateUrl: 'templates/help.html'
        })
        }]);
