### ISSUE TITLE
$state.is should return false if state doesn't exist.

### ISSUE THREAD

**Issue by prettymuchbryce** [angular-ui/ui-router#1168]
The [documentation](http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$state#is) implies that $state.is returns false if the state doesn't exist. It actually returns undefined. Either the documentation should be updated, or the method should be changed to only return a boolean.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
