### ISSUE TITLE
not work Appended Routes

### ISSUE THREAD

**Issue by Avtonom** [angular-ui/ui-router#1172]
I did as shown in the documentation https://github.com/angular-ui/ui-router#nested-states--views - here is my code vieschs http://plnkr.co/edit/0DypwIajU7fOPvQGR5fg here it works.

But when I use it in my project template child is not called. Call always occurs only parent.

How can I find the problem?

My question is similar to this: http://stackoverflow.com/questions/22157357/angular-ui-ui-router-with-steroids

Clone issue http://stackoverflow.com/questions/24487382/angular-js-angular-ui-ui-router-not-work-appended-routes

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
