### ISSUE TITLE
Change url silently (without triggering initial route)

### ISSUE THREAD

**Issue by web2style** [angular-ui/ui-router#1181]
I'm rebuilding my single-page website from backbone to angular. I have several "pages", but actually they are just different sections of one page not visible all at once. When I open another "page" I just need to scroll the viewport to another section and change the url. I used backbone's [silent: true](http://backbonejs.org/#History-start) option, so that transition animation didn't intercept by DOM reload.

Is there any possibility to do this in ui-router?

Thank you!

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
