### ISSUE TITLE
Problem loading state config through folders hierarchy

### ISSUE THREAD

**Issue by TallineauJean** [angular-ui/ui-router#1186]
Hello,

I am developing an angular app using ui-router to handle different states.
I am encountering an issue while trying to reach a child state from its parent and it seems to me that it is related to the names of my different javascript files.

i've got a state 'lait' defined in lait.js file
its child state 'lait.details' is defined in details.js file

$state.go('lait.detail') => return an exception "could not reach state 'lait.detail' from 'lait'"

If i rename my lait.js file in alait.js (now the file containing my parent state is 1st in alphabetical order), lait.detail state is reachable.

Is there a way to configure ui-router's behaviour not depending on file names used to define the different states of an application?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
