### ISSUE TITLE
reloadOnSearch: false prevents state from reloading when path parameter changes

### ISSUE THREAD

**Issue by mattyork** [angular-ui/ui-router#1191]
`reloadOnSearch: false` should allow a user to change the query parameters without reloading the state, but changing path parameters should reload the state. 

In the plunk below, `reloadOnSearch` is `false`.

expected: changing the path parameter in the url reloads the state
actual: changing the path parameter does _not_ reload the state

plnkr: http://run.plnkr.co/plunks/0gsMeAaFMmEA0Nu0BNPl/#/param?key=query

**Comment by cgat** [comment]
Is this type of behaviour simply not supported until dynamic-params are introduced? Is there a work around?
