### ISSUE TITLE
regex validation of query string parameters

### ISSUE THREAD

**Issue by connorbode** [angular-ui/ui-router#1193]
It would nice to be able to validate [query parameters](https://github.com/angular-ui/ui-router/wiki/URL-Routing#query-parameters) using the same [regex methods available for basic parameters](https://github.com/angular-ui/ui-router/wiki/URL-Routing#query-parameters)

**Comment by avandendaele** [comment]
Hi, Is this 'future release' has been released ?

**Comment by benwells** [comment]
@timkindberg @avandendaele I'm also curious if this has been released.  I am having trouble finding the documentation on how to incorporate regexes into query parameters.

I am looking to define multiple routes that have the same query string parameters, except that the values of these parameters differ.

`url: "?c&p&g"` needs to be my query string across multiple routes, with the difference being that the value of `g` will differ from route to route.

What would be the best way to go about doing this?  Is something like this supported?

Thanks for your help.
