### ISSUE TITLE
Mobile safari blocks outbound links when using multiple absolute named views

### ISSUE THREAD

**Issue by matthewharwood** [angular-ui/ui-router#1199]
While using mobile safari through the IOS simulator:
Links that redirect you outside the application will not work but only inside of a absolutely named view.

It appears that links attempt to connect but instantly, redirects to the base app url via otherwise('/') but thats kind of a guess.

```javascript
.state('home', {
        url: '/',
        views: {
          '': {
            templateUrl: 'views/main.html',
            controller: 'MainCtrl'
          },
          'navigation@home': {
            templateUrl: 'views/partials/navigation.html',
            controller: 'NavigationCtrl'
          }
        }
      })
```

If I put an outbound link into main.html it works perfectly on IOS.
If I put an outbound link into navigation Ctrl it attempts to connect to outbound link then redirects to root.

```html
<a href="http://www.morningharwood.com/" target="_blank" >go to here</a>
```

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
