### ISSUE TITLE
wildcard matching: unknown state maps to a default controller - not resolving

### ISSUE THREAD

**Issue by rkoberg** [angular-ui/ui-router#1214]
(New to ui-router, so I am probably using incorrect terminology.) I recently converted over to ui-router from ngRoute. In the attached image you will see how I had my routes for ngRoute versus how I have them now for ui-router in my app.js with the module named 'app':
![screen shot 2014-07-21 at 11 40 00 am](https://cloud.githubusercontent.com/assets/83722/3648191/e384b97c-1106-11e4-8141-631c292dc02a.png)
My &lt;front&gt; page is resolving fine. States in other modules resolve fine. For example in a module named 'app.users.studentRegister' the following resolves as expected:

```
   $stateProvider.state('register/student', {
//      url:'/register/student',
      templateUrl: 'components/users/student-register/student-register.html',
      controller: 'StudentRegisterCtrl'
    })
```

The problems come from when I want to match something not explicitly defined as a state. The app is a front end to a CMS and states/paths not explicitly defined should just display the result of an $http.get() on that state/path. For example, a path could be 'node/27' or 'how-it-works' or 'foo/bar/baz/bat' or anything. This all worked fine with ngRoute.

With ui-router I get an error when try to go to a state/path not explicitly defined, for example 'node/38'. The error says:

```
Error: Could not resolve 'node/38' from state '<front>'
    at Object.transitionTo (http://0.0.0.0/app/bower_components/angular-ui-router/release/angular-ui-router.js:1971:39)
    at Object.go (http://0.0.0.0/app/bower_components/angular-ui-router/release/angular-ui-router.js:1854:19)
    at http://0.0.0.0/app/bower_components/angular-ui-router/release/angular-ui-router.js:2944:20
    at http://0.0.0.0/app/bower_components/angular/angular.js:13777:28
    at completeOutstandingRequest (http://0.0.0.0/app/bower_components/angular/angular.js:4236:10)
    at http://0.0.0.0/app/bower_components/angular/angular.js:4537:7 
```

Obviously I am doing something wrong, but not sure how to fix. I would like to have it the way I had it with ngRoute where any path not explicitly defined just gets routed to the MainCtrl for a GET request to the CMS. Any ideas?

**Comment by ashelley** [comment]
@rkoberg did you ever come up with a solution to this? I would like to do this type of dynamic routing as well.
