### ISSUE TITLE
urlMatcherFactory special types don't work.

### ISSUE THREAD

**Issue by tiwatson** [angular-ui/ui-router#1222]
Wasn't sure how to create a plunker using the master. 

The following does not work as urlMatcherFactory's $get method is what activates the new UrlMatchers. $get does not get called when injected into a config block. injecting via a run block comes too late. 

```
angular.module('rkmpp', ['ui.router'])
.config(['$stateProvider', '$urlRouterProvider', function($stateProvider, $urlRouterProvider) {
  $stateProvider.state('numbers', { url: '/{id:int}', controller: function() { console.log('passed'); } });
}]);
```

https://github.com/angular-ui/ui-router/blob/master/src/urlMatcherFactory.js#L694

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
