### ISSUE TITLE
How to deal with angular module's config function when unit testing?

### ISSUE THREAD

**Issue by jintoppy** [angular-ui/ui-router#1228]
I have got the same question. 

http://stackoverflow.com/questions/19287223/how-to-deal-with-angular-modules-config-function-when-unit-testing

In the config of my app module, I am creating the states and adding rules using $urlRouterProvider. So, when I am unit testing services which are using this states, I want to mock this config phase. How to do that?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
