### ISSUE TITLE
Dot notation in state name not working

### ISSUE THREAD

**Issue by davidnknight** [angular-ui/ui-router#1237]
Hi,

With the following config, state `restaurants.restaurant` doesn't work, attempting to access `/restaurants/something` simply falls back to `/restaurants` each time. Only if I comment out the `.otherwise` or change `restaurants.restaurant` to `restaurants_restaurant` or anything else as long as it doesn't contain a dot, does it work.

As far as I'm aware from documentation I've read, dot notation is certainly supported. Am I missing something? Perhaps it doesn't work with html5Mode or something?

<pre>
App
    .config(
        ['$locationProvider', '$stateProvider', '$urlRouterProvider',
            function( $locationProvider, $stateProvider, $urlRouterProvider ) {
                $locationProvider.html5Mode(true);
                $urlRouterProvider.otherwise('restaurants');
                $stateProvider
                    .state('restaurants', {
                        url: '/restaurants',
                        templateUrl: '/app/venues/index.html',
                        controller: 'venueIndexController'
                    })
                    .state('restaurants.restaurant', {
                        url: '/restaurants/{restaurant}',
                        templateUrl: '/app/venues/show.html',
                        controller: 'venueShowController'
                    });
            }
        ]
    );</pre>

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
