### ISSUE TITLE
ui-router keeps firing the `$stateChangeStart` when I try to go to an invalid AngularJS path and then block it.

### ISSUE THREAD

**Issue by RossRogers** [angular-ui/ui-router#1240]
Thanks for your hard work on the ui-router code base.

If I navigate to an invalid AngularJS path and then block the state transition with `event.preventDefault()` inside a `$stateChangeStart` callback, I get:

```
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [["fn: $locationWatch; newVal: 7; oldVal: 6"],["fn: $locationWatch; newVal: 8; oldVal: 7"],["fn: $locationWatch; newVal: 9; oldVal: 8"],["fn: $locationWatch; newVal: 10; oldVal: 9"],["fn: $locationWatch; newVal: 11; oldVal: 10"]]
```

Here is my SSCCE:

```
<!doctype html>
  <head>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.10/angular-ui-router.min.js"></script>
  </head>
  <body ng-app="clientApp">
    <div ui-view="" ></div>

    <script>
      var app = angular.module('clientApp', ['ui.router'])

      var myRouteProvider = [
                '$stateProvider', '$urlRouterProvider',
        function($stateProvider,   $urlRouterProvider) { 
          $urlRouterProvider.otherwise('/foo');
          $stateProvider.state('/foo', {
            url: '/foo',
            template: '<div>In Foo now</div>',
            reloadOnSearch: false
          })
        }]
      app.config(myRouteProvider)

      var authenticated = false
      app.run([
                 '$rootScope', '$log','$state','$timeout',
        function ($rootScope,   $log,  $state,  $timeout) {
          $rootScope.$on('$stateChangeStart', function (event, next, toParams) {
            if (!authenticated) {
              event.preventDefault()
              //following $timeout is emulating a backend $http.get('/auth/') request
              $timeout(function() {
                authenticated = true
                $state.go(next,toParams)
              },1000)
            }
          })
        }
      ])
    </script>
  </body>
</html>
```

 Serve it up with `python -m SimpleHTTPServer 7070` and go to `localhost:7070/test.html#/bar` to see it explode in your face. Whereas directly navigating to the only valid angularjs location does not blow up `localhost:7070/test.html#/foo`

**Comment by mladenp** [comment]
I got the same error, i thought i was doing something wrong but after seeing on several places that its not working as it should i am sure now that its a bug. It seems that urlRouterProvider.otherwise runs states several times or something like that.

**Comment by renanosf** [comment]
Same error here

**Comment by nottinhill** [comment]
What does `*path` do?

**Comment by RossRogers** [comment]
nottinhill,
If you put the `*path` URL last in your specified set of lists, it will only catch the paths that are not caught by the previous path specifications.

**Comment by alex-fernandez** [comment]
This one works for me, I got rid of the event.preventDefault() and made sure that there is a state to be executed.


      // Authorization Checking
      $rootScope.$on('$stateChangeStart', function (event, next) {
        if (Authentication.isAuthenticated()) {
          $state.go('app.dashboard-v1');
        } else {
          $state.go('access.signin1');
        }

      });
