### ISSUE TITLE
IE11 bookmark does not work when clicked twice

### ISSUE THREAD

**Issue by techmariner** [angular-ui/ui-router#1241]
On IE11 after you open application from bookmark, change state and open the same bookmark again than nothing happens. I'd like to attach very simple zip which demonstrates that but zip files are not supported, so here is example code and steps to reproduce:

1) First, create very simple application: index.html, state1.html, state2.html, app.js (routing configuration). Sources are provided at the end of description.

2) Create bookmark in IE11:
```javascript
http://localhost/ang_app/index.html#/1
```

3) Start new IE11 session, start application via bookmark created at step 2.
![step1](https://cloud.githubusercontent.com/assets/8329492/3778415/2ba009fa-1972-11e4-9e99-5836785f99ae.png)

4) Click on link 'State 2' and observe that application changes it's state as expected.

![step2](https://cloud.githubusercontent.com/assets/8329492/3778421/44469e9c-1972-11e4-903c-b29c688e5d91.png)

5) Click ON BOOKMARK that you created in step 2 again. Observe application behavior: **URL hash changed to '1' but application state does not reflect the change and stays in state '2'.**

![step3](https://cloud.githubusercontent.com/assets/8329492/3778424/4b18d186-1972-11e4-93ef-f24e32baf825.png)

index.html:

```javascript
<!DOCTYPE html>
<html ng-app="myApp">
<head>
<script src="angular.js"></script>
<script src="angular-ui-router.js"></script>
<script src="app.js"></script>
</head>
<body>
    <div ui-view></div>
    <a href="#/1">State 1</a>
    <a href="#/2">State 2</a>
</body>
</html>
```
state1.html:
```javascript
<h1>State 1</h1>
```
state2.html:
```javascript
<h1>State 2</h1>
```

app.js:
```javascript
var myApp = angular.module('myApp', ['ui.router']);

myApp.config(function($stateProvider, $urlRouterProvider) {
  //
  // For any unmatched url, redirect to /state1
  $urlRouterProvider.otherwise("/state1");
  //
  // Now set up the states
  $stateProvider
    .state('1', {
      url: "/1",
      templateUrl: "state1.html"
    })
    .state('2', {
      url: "/2",
      templateUrl: "state2.html"
    })
    });
```

Additional info:

angular: v1.2.19
ui-router: v0.2.10
Windows 8.1
IE11:

![ie_info](https://cloud.githubusercontent.com/assets/8329492/3778450/089a5342-1973-11e4-9838-4dfa99da875f.png)

Any help will be appreciated!

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
