### ISSUE TITLE
Named view not being cleared when empty template provided

### ISSUE THREAD

**Issue by migajek** [angular-ui/ui-router#1245]
I'm using the named view for displaying the global menu. There are however several sub-pages where I want the menu to be hidden. 
Thus the menu div has default content ``<div ui-view="menu"> ... some content ..</div>`` and the content is supposed to be overriden with empty only on those subpages where menu is hidden. 
I found out however that setting en empty string as the template content does not work, instead I have to use ``'&nbsp;' ``:

    'named@': {template: ''} // does not work
    'named@': {template: '&nbsp;'} // works

full example http://jsfiddle.net/ht8Ag/

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
