### ISSUE TITLE
Define a view by default, without having to define it for every state it could be. (Nearly like a Partial)

### ISSUE THREAD

**Issue by Acaspita** [angular-ui/ui-router#1246]
Ok, I know that I can have several views, and describe them for every state...
```html
<!-- index.html -->
<body>
  <div ui-view="filters"></div>
  <div ui-view="tabledata"></div>
  <div ui-view="graph"></div>
</body>
```
```javascript
$stateProvider
  .state('report', {
    views: {
      'filters': { ... templates and/or controllers ... },
      'tabledata': {},
      'graph': {},
    }
  })
```
But what I would like to do, and I've been wondering if there's a way... that I can load a template and a controller ALWAYS, or by default, for a ui-view, for every state I define (Nearly like a Partial), without having to specify it every time..., is there a way? : )

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
