### ISSUE TITLE
$location.search() params in resolve

### ISSUE THREAD

**Issue by Rauno56** [angular-ui/ui-router#1250]
I imagine that it is expected that when a `ui-sref` link is clicked, then the state of `$location` in resolver is at the new state already. Well it is not so with the `$location.search()`.

See console of [jsBin](http://jsbin.com/situd/2/) for reference.

After going to one of the views and clicking search you get different results:
* Clicking ui-sref link the `searchQuery` is still there in the resolver,
* Clicking plain href link the `searchQuery` is properly reset.

It should always behave like in the latter case imo.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
