### ISSUE TITLE
Bug in "How to: Set up a default/index child state"

### ISSUE THREAD

**Issue by wcandillon** [angular-ui/ui-router#1252]
https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-set-up-a-defaultindex-child-state

This solution doesn't appear to work with `ui-sref-active`. Going the default state will cause `ui-sref-active` to not highlight siblings of the default state. Going to the abstract state will cause an error.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
