### ISSUE TITLE
duplicate ui-view tags in 0.2.10

### ISSUE THREAD

**Issue by demetriusnunes** [angular-ui/ui-router#1253]
Still having the same issue described in https://github.com/angular-ui/ui-router/issues/958 with 0.2.10 and AngularJS 1.2.21.

![screenshot from 2014-08-05 15 03 47](https://cloud.githubusercontent.com/assets/4699/3816025/f6a6ad10-1cca-11e4-9f90-f660c0f1bbd2.png)

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
