### ISSUE TITLE
Feature Request: Get all states as hierarchical representation

### ISSUE THREAD

**Issue by donaldpipowitch** [angular-ui/ui-router#1264]
`$state.get()` returns all states as a 1-dimensional array. A similar API which gets them as a hierarchical representation would be really great.

E.g. given the states `user`, `settings` and `settings.detail` it would be nice to not just get 
````
// $state.get()
[
  { user state },
  { settings state },
  { settings.detail state}
]
````
but something like
````
// $state.getHierarchy()
[
  { user state },
  { settings state, 
    child states: [ 
      { settings.detail state}
    ]
  }
]
````
(Pseudo code...)

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
