### ISSUE TITLE
Dynamic states

### ISSUE THREAD

**Issue by vko-online** [angular-ui/ui-router#1266]
I have very unique object model, it has many dependencies, (which is retrived from webapi, on IIS server)
    `object {
        dependencies: [object Array]
    }`
So i want to configure or maybe dynamically change my state on object select, i mean i want to append to current url, but with different views, consider i have some attribute which shows me object type, and depend on object type i want to load special state, i can generate templates. But how can i make url? 
Object model is very nested, so each dependent array of objects should have generated views, where i can edit it, and also edit it's child dependent objects. Any ideas?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
