### ISSUE TITLE
Navigating to state does not initially show partial views. I have to refresh, why? 

### ISSUE THREAD

**Issue by courtneynguyen** [angular-ui/ui-router#1269]
I have the latest angularjs, as well as the latest angular-ui-router that is in the #master branch. I attempted to read up on the broken $location parser, but I am new to Angularjs and this framework, so a lot of it went over my head. Could someone explain to me like I am 5 what this issue is? 

For example, I have a state on initial signup localhost:3000/#!/ that will show a splash page for new users to sign up. Then after you register and then login, I keep that same url, and have a nested partial view inside that shows all of the user's information. Here is the code:

`<section data-ng-controller="IndexController">
    <h1 mean-token="'home-default'">Hello {{global.user.name}}</h1>
    <div data-ng-if="isLoggedOn() === true">
    <div ui-view="docTool"></div>
    </div>
</section>`

I read in some of the patches that I could use absolute urls to get to the state I want. In my IndexController, I've tried to say after they login, 
`$state.go('home');`
 and that does not work. I continue to have to refresh in order to get the desired views. Any information that could help me gain a better understanding of this problem is greatly appreciated, thanks!

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
