### ISSUE TITLE
IE9 query parameters lost at app initialization phase

### ISSUE THREAD

**Issue by sobolk** [angular-ui/ui-router#1270]
I have ui-router based app let's say under /store. My ui-router has html5mode set to true.

If I enter /store?param=value in non IE9 browser then param value might be found in $stateParams or using $location service.

The problem appears when ui-router falls back to hashbang in IE9. Then at the beginning I get redirection from /store?param=value to /store/#/ and my parameter is lost forever.

Could we rewrite query parameters during this redirection ?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
