### ISSUE TITLE
Directive link order.

### ISSUE THREAD

**Issue by drozv** [angular-ui/ui-router#1271]
On some nested routes the invocation of the directive link functions gets changed:

```html
<div directive1>
  <div directive2>
  </div>
</div>
```

The link function invocation for the above should be:

directive1.prelink
    directive2.prelink
        directive2.postlink
            directive1.postlink

However what happens is:

directive1.prelink
    directive1.postlink
        directive2.prelink
            directive2.postlink

This only happens when the template for the view is loaded from the server. For precompiled templates this issue does not exist, nor does it exist for the second loading of a view (when the template is in angular's cache).

I'm not exactly sure what causes this, as it does not happen in all of my views. The particular instance where this is happening currently is a 3-level nested view which is loaded by a ui-sref click. If I open this view directly by going to the route in the browser this problem does not exist.

A lot of directives and nested content depends on the link order so this is important. I have temporarily solved this problem for my code by precompiling the templates.

**Comment by JacobHTran** [comment]
I believe this is working as expected due to the async nature of templateUrl.  Essentially angular doesn't know when the template will be loaded so the compile/prelink/postlink process fundamentally changes.  See https://github.com/angular/angular.js/issues/8877#issuecomment-54129804.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
