### ISSUE TITLE
Render not found page and change the URL

### ISSUE THREAD

**Issue by sandro-csimas** [angular-ui/ui-router#1272]
Given the url 
````
http://localhost:3000/#/genre/pop
````
When i change to 
````
http://localhost:3000/#/genre/unknown
````
I want to render 404 page and stay with the latest url, but i could not make it work.
It displays 404 page, but the url changes to the first.
Here is my code:
````
.state('404', {
      url: '/404',
      templateUrl: '/app/partials/errors/404.html'
});
````
````
.run(['$rootScope', '$state', function ($rootScope, $state) {
    $rootScope.$on('$stateChangeError', function (event, toState, toParams, fromState, fromParams, error) {
        if(error.status === 404) {
            $state.go("404", null, {location: false});
        } else if(error.status === 500) {
            $state.go("500");
        }
    });
}]);
````
Which parameters i need to pass in state's go function to use the toState and toParams in URL ?
The result should be url http://localhost:3000/#/genre/unknown with 404 rendered.
Thanks in advance!

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
