### ISSUE TITLE
Add a facility to allow states to be defined at runtime.

### ISSUE THREAD

**Issue by atrauzzi** [angular-ui/ui-router#1274]
What I'd like to be able to do is give some portion of my app the ability to define states/routes at runtime:

    $stateService.add('somewhere.runtimeState', {
        url: '/runtime-state',
        controllerProvider: myControllerProvider,
        templateProvider: myTemplateProvider
    });

I know there's already been some discussion with regards to lazy loading.  Unfortunately they've suggested some fairly ugly APIs and introduce what I feel is an unnecessary level of complexity to something that should be as simple as gaining access to the `$stateProvider` API at runtime.  Ideally this is not the kind of thing I need another angular module dependency for.

In the name of keeping all the concerns nicely separated, I feel like this approach would allow one to pre-load routes (thereby gaining the ability to generate URIs to them) as well as optionally perform any visuals/processing while the controller and/or template is being resolved.  Unless I'm mistaken, it gives me enough control to integrate whatever mechanisms I see fit to produce the results ui router needs.  Any other parameters or schema involved with exposing runtime definition of states risks becoming too implementation specific.

On the off chance that there already is runtime access to this API, I apologize and definitely was not lead to believe such by the documentation.  I'd love to be directed to it and maybe I could then suggest here how it could be improved.

**Comment by christopherthielen** [comment]
Closed by 64879a2

`app.run(['$uiRouter', ($uiRouter) => $uiRouter.stateRegistry.register(state))])`

**Comment by CoderSquirrel** [comment]
@christopherthielen sorry to reopen, but i'm facing the same issue, in fact i'm using the latest uirouter (to date tday (13/10)) and when i try use 
$uiRouter.stateRegistry.register(state)
the state dont appears in the $uiRouter state array, or even is 'reconized' when i try to state.go to it
nedd to have another configuration?

**Comment by christopherthielen** [comment]
@CoderSquirrel the only thing I can think of is this: If a state `A.B.C.D` being registered has a parent state `A.B.C` which is *not* yet registered, the registration of `A.B.C.D` is queued until all parent states exist.  

For example when registering `app.parent.child`, the parent state `app.parent` has to exist before the child can be registered.  You might want to check if the state is in `$stateRegistry.stateQueue.queue`
