### ISSUE TITLE
$stateProvider requests template in templateURL with accept header as application/json which must be text/html 

### ISSUE THREAD

**Issue by defyjoy** [angular-ui/ui-router#1287]
when we are actually requesting for a template url . The accept header is always "application/json" instead of "text/html"

I am currently Using nancy for generating both template and api request based on the content request type on accept headers .

Something like this 

private dynamic Index(dynamic parameters)
        {
            List<Student> Students = NancyContext.Set<Student>().ToList();
            return Negotiate.WithView("Index").WithModel(Students);
        }

which basically when requested with 'application/json' returns json . And when requested with "text/html" then it returns the template with model . But since its requesting the template with 'application/json' . Its only returning json for the api request and not the template . Any workaround for  to change the accept header to text/html instead of application/json  for template url ?

**Comment by hecht-software** [comment]
In case you landed here due to a google search about this behavior:

In the current version, `$templateRequest` is used for loading templates and the fix in #1341 has no effect anymore. You have to configure the headers yourself in `$templateRequestProvider`:

    angular.module('MyApp', ['ui.router']).config(['$templateRequestProvider', function($templateRequestProvider) {
        $templateRequestProvider.httpOptions({
            headers: { Accept: 'text/html' }
        });
    }]);
