### ISSUE TITLE
RFC: Cascading decorators

### ISSUE THREAD

**Issue by emilbayes** [angular-ui/ui-router#1298]
It currently only seems possible to have a single custom decorator per property. Would it be possible to have multiple cascading?

**Comment by gregbty** [comment]
+1

I am now running into an issue with this as well. In my `parent` decorator I am forced to call the original decorator if one exists. If I don't add a dependency to the ui-router-extras for that module then I run into issues because ui-router-extras also decorates the `parent` function.
