### ISSUE TITLE
$state.parent, $state.root, $state.children

### ISSUE THREAD

**Issue by timkindberg** [angular-ui/ui-router#13]
It may be nice to be able to access the parent, root and children states of any given $state.

**Comment by kentcdodds** [comment]
Guessing this issue's pretty much dead? :-(

**Comment by uwconcept** [comment]
I don't know if it's available as yet, but it would also be nice to have like a path_to_root for the current state.

**Comment by christopherthielen** [comment]
@kentcdodds I wouldn't say dead, but not high priority.  If you want to do this yourself, you need access to the internal state objects, which have .parent on them.  Take lines 4-18 of ui-router-extras-core and add them to your project, then you will have a $$state() unwrapper function on each state that comes out of $state.get().  You can then build the tree yourself.

```
mod_core.config([ '$stateProvider', '$injector', function ($stateProvider, $injector) {
  // Decorate any state attribute in order to get access to the internal state representation.
  $stateProvider.decorator('parent', function (state, parentFn) {
    // Capture each internal UI-Router state representations as opposed to the user-defined state object.
    // The internal state is, e.g., the state returned by $state.$current as opposed to $state.current
    internalStates[state.self.name] = state;
    // Add an accessor for the internal state from the user defined state
    state.self.$$state = function () {
      return internalStates[state.self.name];
    };

    angular.forEach(stateRegisteredCallbacks, function(callback) { callback(state); });
    return parentFn(state);
  });
}]);
```

**Comment by kentcdodds** [comment]
@christopherthielen, understood. Thanks for the code snippet. :+1:

**Comment by YoungLua** [comment]
`sdfa`

**Comment by YoungLua** [comment]
谢谢，就是不太明白哈

**Comment by christopherthielen** [comment]
Each state is now decorated with `$$state()` in ui-router 1.0.  `$$state()` returns the internal [StateObject](https://ui-router.github.io/ng1/docs/latest/classes/state.stateobject.html) (internal, so API is subject to change)

`$state.get('foo').$$state().parent`
