### ISSUE TITLE
The example/demo application is slow, delays after clicking on a link for 500ms or so

### ISSUE THREAD

**Issue by neatcode** [angular-ui/ui-router#1305]
I'm using the latest Chrome on Windows 8.

I went ahead and tried the demo page on the latest Firefox, and I saw animations when clicking on links, which didn't show in Chrome. I suspect this (invisible) animation step is what is making the demo look slow on Chrome... how do I turn off the animation in the demo so I can see how fast ui-router really is?

Thanks in advance,
Austin

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
