### ISSUE TITLE
fire $stateChangeSuccess event when loading page

### ISSUE THREAD

**Issue by Archelyst** [angular-ui/ui-router#1307]
When loading a page the correct state and controller is loaded, but the $stateChangeSuccess event is not fired as it is when the state is changed after page load. At least I cannot receive it in the controller. It would be convenient and IMHO consistent to also have this event on page load.

**Comment by Gregoirevda** [comment]
Chrome and firefox have no problem to trigger the `$stateChangeStart` on load, but Internet Explorer 11 has.  
Tested in a parent controller that is set on `<body>`, in the `run` and in `resolve` of the root route. All on `$rootScope`.

Is there a solution for this?
