### ISSUE TITLE
'/' is not letting the state to pass to '/{username:[a-zA-Z0-9]{3,20}}'

### ISSUE THREAD

**Issue by ankitladhania** [angular-ui/ui-router#1309]
I have a `abstract root` state called `'site'` with empty url i.e. '' , which has two child state `'profile'` and `'home'` where the url for `home` is `'/'` and the url for `profile` is `'/{username:[a-zA-Z0-9]{3,20}}'`  inorder to test I tried many times to go to the `profile` state but it always reaches the `home` state.

But when i change the home state url with say '/home' then i'm able to go to the `profile` state. After searching the web i couldn't find this issue. Is it a bug? or i'm doing something wrong?

Here is the code for convenience:

```
     $stateProvider.
        state('site', {
            url: '',
            abstract: true,
            views: {
                '': {
                    templateUrl: 'views/site.html' //this is the base template
                },
                'navbar@site': {
                    templateUrl:'views/navbar.html'
                }
            },
            data:{
                access: access.public
            }
        }).
        state('site.home', {
            url: '/',
            templateProvider :['$rootScope','$http','$state',function($rootScope,$http,$state){
                //console.log($state);
                var template = 'views/main_new.html';
                if($rootScope.User.isLoggedIn()){
                    template = 'views/new_room_me.html'
                }
                return $http.get(template).then(function (resp) {
                    return resp.data;
                });
            }]
        }).
        state('site.profile',{
            url:'/{username:[a-z0-9A-Z]{3,20},strict:true}',
            templateUrl:'views/new_room_friend.html'
        });


       $urlRouterProvider.otherwise('/ankit');` 
```

**Comment by EnSabanNur** [comment]
@ankitladhania, can you confirm what your fix was? 

We're experiencing a similar issue to the one highlighted above. We're using an application wide abstract state to enforce app wide resolves. In our case we have a django login that's redirecting to our base url + tracking parameters. For some reason out development boxes (without the login state) work fine, but once the redirect from the login page fire, ui-router is attempting to render the abstract parent state (based on using `angular.element(document.querySelector('html')).injector().get('$state').current` when the page redirects).

Did you simply not enable `html5Mode`?

**Comment by ankitladhania** [comment]
@EnSabanBur can you please provide a plunker or url to the site, that way i will be able to help you more as i'm not able to understand you comment properly. Here is what i did:

1. In ui-router the states are rendered in the order they are written. so what i did was i  wrote the `/{username:[a-z0-9A-Z]{3,20}` part before the `/` part.

Hope this helps.

**Comment by EnSabanNur** [comment]
Gotcha, yeah that makes sense. Our issue is slightly different. 

For some reason, once we do a `302` redirect from out django login page, ui-router gets stuck of it's root state. Any action from there on in works fine (links, page refresh etc), but for some reason the initial load/redirect coming from django breaks everything for the first page load.

Thanks for the response @ankitladhania :+1: I'll probably open an issue in the next hour or so.
