### ISSUE TITLE
ui-view on an ng-app element will bug $rootElement

### ISSUE THREAD

**Issue by ocombe** [angular-ui/ui-router#1329]
If you ever happen to put an ui-view directive on an ng-app element, the reference to `$rootElement` gives back a comment element instead of the real element.

``` html
<!DOCTYPE html>
<html>
    <head></head>
    <body id="ng-app" ng-app="app" ui-view="lazyLoadView">
    </body>
</html>
```

Injecting `$rootElement` in my controller (or any other component) will give me:

``` js
console.log($rootElement);
> [comment, context: body#ng-app.ng-scope, jquery: "1.11.1", constructor: function, selector: "", toArray: function…]
```

But this will work:

``` html
<!DOCTYPE html>
<html>
    <head></head>
    <body id="ng-app" ng-app="app">
        <div ui-view="lazyLoadView"></div>
    </body>
</html>
```

``` js
console.log($rootElement);
> [body#ng-app.ng-scope, context: body#ng-app.ng-scope, jquery: "1.11.1", constructor: function, selector: "", toArray: function…]
```

As you can see, it's probably because ui-view replaces the body element, and `$rootElement` keeps a reference on a commented element instead of the real body element, but this is really problematic. I'm not sure whether the problem is in ui-router or in angular itself (that allows a directive to replace the ng-app element).

**Comment by eddiemonge** [comment]
Is this still something being planned for. Seems like an easy enough case to add it or not add it and document it. Either way seems fine
