### ISSUE TITLE
Expose an API for resolving relative state names

### ISSUE THREAD

**Issue by schmod** [angular-ui/ui-router#1334]
Currently, `ui-router` internally uses the [`findState`](https://github.com/angular-ui/ui-router/blob/deea695f5cacc55de351ab985144fd233c02a769/src/state.js#L131) function in `state.js` to resolve relative state paths, when processing commands such as  `$state.go('^.sibling')`

I propose exposing a variant of this function as a public API, so that 3rd-party developers can extend `ui-router`, while utilizing this built-in functionality.  

In my specific use-case, I lazy-load states and controllers by listening to the `$stateNotFound` event, utilizing the state path and parameters to determine what I need to load.  Unfortunately, if I encounter a `$stateNotFound` while transitioning to a relative path, ui-router does not expose a method to generate the full state path from the relative path passed to the event (as `unfoundState.to`)
## Proposed API

``` js
  /**
   * @ngdoc function
   * @name ui.router.util.$stateFactory#absoluteName
   * @methodOf ui.router.util.$stateFactory
   *
   * @description
   * Utility function to resolve a canonical state name from a path, relative to another state.
   * Does not check if state actually exists.
   *
   * @param {string} path Relative or absolute path to be resolved into an absolute path.  
   * @param {string|object=} relativeTo State or state name to act as a base if `path` is 
   * a relative path.  Defaults to `$state.$current`
   *
   * @return {string}  Absolute path of state.
   */
   $stateFactory.absoluteName = function(path, relativeTo){
     ...
   }
```

I'd be happy to provide a PR if this looks like a reasonable proposal...

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by schmod** [comment]
I think this is still a reasonable thing to keep on the table.

**Comment by floriangosse** [comment]
+1
