### ISSUE TITLE
$stateChangeSuccess fires multiple times after $state.transitionTo 

### ISSUE THREAD

**Issue by zackarychapple** [angular-ui/ui-router#1338]
I have a function that fires on $stateChangeSuccess.  When I transition states with $state.transitionTo I find that the function fires twice on the first transition.   I also found that going back and forth between child states and parent states causes the function to be fired more times.   Anyone have any thoughts?

```javascript
$rootScope.$on('$stateChangeSuccess' function() {
//my code
};
```

**Comment by chasys** [comment]
@christopherthielen I too was experiencing the same issue, but after following your comment to change from $rootscope to $scope, it works now without firing multiple times. Thank you for the solution.

**Comment by GinoF** [comment]
@christopherthielen  @chasys  Thanks! This solved MY issue.
