### ISSUE TITLE
Switching states does not properly clean up scope if using Controller As syntax

### ISSUE THREAD

**Issue by SamMaier** [angular-ui/ui-router#1340]
Using `controller as` angular syntax, you can register a `state`'s controller like so:

`controller: 'MainCtrl as main'`

However when using this syntax, when switching out of the state, MainCtrl is not destroyed like it would be if you were using the "standard" `$scope` syntax.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
