### ISSUE TITLE
Regex Parameters on state config URL

### ISSUE THREAD

**Issue by arnaudpourbaix** [angular-ui/ui-router#1347]
Hello, 

I am experiencing something really annoying and I'm not sure it is a bug.
I have defined a state with massive url regexp as follow:
```javascript
        $stateProvider.state('pubca.view', {
            url : [
                '/{temporalType:DATE|MONTH}',
                '/{periodType:JOUR|SEMAINE|MENSUEL|CUMULE|CUSTOM}',
                '/{currentStartDate:[0-9]{8}}',
                '/{currentEndDate:[0-9]{8}}',
                '/{previousStartDate:[0-9]{8}}',
                '/{previousEndDate:[0-9]{8}}',
                '/{companyId:[0-9]+}',
                '/{regionId:ALL|[0-9]+}',
                '/{siteId:ALL|[0-9]+}',
                '/{saleChannelId:ALL|[0-9]+}',
                '/{sectorId:ALL|[0-9]+}',
                '/{marketId:ALL|[0-9]+}',
                '/{categoryId:ALL|[0-9]+}',
                '/{familyId:ALL|[0-9]+}',
                '/{productId:ALL|[0-9]+}'
            ].join(''),
```

When I start my application on this state with some parameters that don't match regexp, it will not work. Good point, it is an expected behavior.

But when I use $state.go with these same parameters, it will work and my state is successfully loaded despite the fact that my parameters don't match url configuration.

Because these parameters are wrong, it will generate an error in a controller and after, for some unknown reason (yet), it will change state using otherwise config. I don't fully understand if this second behavior is due to ui-router or my own code.I'm still investigating this issue.

I have tried to debug ui-router code but it's not that easy. However, it seems clear that it does fire $stateChangeSuccess without beeing interrupted by an incorrect URL.
Maybe it is assumed that url should only be parsed when manipulated by user and should be correct in a $state.go access ?

**Comment by porjo** [comment]
I've hit a similar issue using 0.2.13. When I change state with `$state.go` or `ui-sref` the route gets matched incorrectly. Loading the page initially doesn't have this problem. 

For example, 
```
.state('show.specific', {
            url: 'show/{tid:[0-9]+}',
            templateUrl: 'show/show.html',
            controller: 'ShowCtrl'
        })
```

On page load, if I pass url with `show/` (i.e. no `tid` supplied) then it does not match, however if I change state after the page load and pass an empty string as the `tid` then it does match (even though no digits present)!?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
