### ISSUE TITLE
Using $urlRouterProvider.when() and $stateChangeSuccess/event.preventDefault() the same time lead to infinite loop

### ISSUE THREAD

**Issue by fubupc** [angular-ui/ui-router#1348]
At first I want to check authorization before state transition. So I use `$stateChangeSuccess` with `e.preventDefault` method to intercept transition, sample code:

``` javascript
$rootScope.$on('$stateChangeStart', function(e, toState, toParams, fromState, fromParams) {
        e.preventDefault();

        checkAuthorization().then(function() {
            $state.go(toState, toParams, {notify: false})
                .then(function() {
                    $rootScope.$broadcast('$stateChangeSuccess', toState, toParams, fromState, fromParams);
                 })
        });
})

```

It works fine until using $urlRouterProvider.when() for some url redirect:

``` javascript
$urlRouterProvider.when('/A', '/A/B');
```

Now if you visit url `/A`, then the browser would be trapped into an indefinite loop. I made a simple demo plunker here: http://plnkr.co/edit/lUkJx27HiaaNAJbF07n2?p=preview

Please open console and click 'A' link to see what I mean...

PS: This is an issue relative to https://github.com/angular-ui/ui-router/issues/178

**Comment by leonuh** [comment]
Maybe it can be relevant in this issue: https://github.com/leonuh/ui-router.redirect
