### ISSUE TITLE
Feature Request: state-based controller names

### ISSUE THREAD

**Issue by 34r7h** [angular-ui/ui-router#1354]
Is it already possible to access a state's controller from within another view's html without using a predefined named controller? i.e.
`<div ng-controller="state1CTRL"></div>`
If angular register's a state's controller, doesn't it have to have a name somewhere?

**Comment by irthos** [comment]
Thanks for the update and closure. My problem was that I'm dynamically building the states on load from data and so had to figure out $controllerProvider to also create controllers on the fly prior to stick them into the state config loops.

Cheers
