### ISSUE TITLE
$stateProvider.state runs before $urlRouterProvider.rule does.

### ISSUE THREAD

**Issue by mboudreau** [angular-ui/ui-router#1355]
This is seriously annoying me.  What's the point of adding a rule if your stateProvider doesn't listen to it?  I can find a workaround (the default state is under the '/list' or something, which I set once the rule is good), but I think the current way needs to be fixed.

If I set $urlRouterProvider.rule(function...) anywhere in the system, I would imagine that this has priority /precedence over any of the stateProvider based states since the rule can (and probably will) change the URL, making the original call to the state completely useless.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
