### ISSUE TITLE
$state.go to current state reloads controller with notify set to false (broken by 0.2.11)

### ISSUE THREAD

**Issue by mafredri** [angular-ui/ui-router#1387]
I'm unsure if this is the intended functionality, but commit https://github.com/angular-ui/ui-router/commit/7b78edeeb52a74abf4d3f00f79534033d5a08d1a breaks `$state.go($state.current.name, params, {notify: false});`

$state.go can be called one time without reloading the controller, but the second time it is called the controller also gets reloaded, reverting the commit fixes the issue.

I created a plunkr for good measure to demonstrate the issue. http://plnkr.co/edit/jvuPlkcGmYNwhptUvcHY?p=preview

**Comment by Hyzhak** [comment]
@christopherthielen @mafredri 
here is another case which break ui-router:
http://plnkr.co/edit/i32gBWblr3JaG2aNcnzg?p=preview
after you have something like:
``` javascript
$state.go('stateA', {param: newvalue}, notify: false);
```

any other command like:
``` javascript
$state.go('stateB');
```
or
``` javascript
$state.go('stateA.substate');
```
reload controller. 
Steps to reproduce: 
1) push 'Reload state'; 
2) push 'go to state.index1'; 
3) Controller reloads will update to 1; 
4) push 'Realod state'; 5) and so on...

**Comment by Gr33nM0nk** [comment]
Not working for me as well.
I have tried every idea I could find on the internet but the issue still persists.
When I try to update the current state parameters with notify set to false, it works fine, but when I try to switch to a different state, the previous state just seem to reload.
Any new ideas please?

**Comment by christopherthielen** [comment]
What are you trying to accomplish by setting notify to false?

**Comment by Gr33nM0nk** [comment]
I'm trying to update the parameters of the current state, in order to update the url

**Comment by hyzhak** [comment]
I have same use case - I need to reflect state of app to url (in my case they are current page of pagination and search query string). But this bugs prevent update without page reloading.

**Comment by mafredri** [comment]
What version are you using? This is still working for us in `0.2.13`. Maybe you should open a new issue?

**Comment by hyzhak** [comment]
@mafredri if you ask me - I'm using the last one `0.2.15` and nothing was changed till there here is my deeply explanation https://github.com/angular-ui/ui-router/issues/1758

**Comment by hyzhak** [comment]
@mafredri btw you have Perast and island Gospa, Montenegro at your avatar - I'm living near there :)

**Comment by mafredri** [comment]
@hyzhak yea looks like you have a valid bug in your issue, but it's unrelated to this one :).

Also, cool, I was just touristing there, but nice spot! :)

**Comment by not-only-code** [comment]
It happens to me exactly as @hyzhak explained. After changing the same state with different parameters and *notify: false* in order to don't reload the controller, if you want to go to another state it reloads the same state before to change to the next one.

**Comment by jabyrd3** [comment]
Any workaround for this? It's holding me up as well.

**Comment by jabyrd3** [comment]
Also, for the record, I'm seeing this issue (reload original state on state change event after path has been updated via notify: false) on both 2.13 and 2.15.

**Comment by natwallbank** [comment]
I just encountered this issue too (0.2.14).  Had to settle on a combination of $location.search and reloadOnSearch: false to achieve what I needed to.

**Comment by dhavyd** [comment]
I have the habe problem here, using v0.2.15.

I have this
```
$state.go('myState', $stateParams, {notify: false});
```
When I run $state.go() in a later context, then the entire "state tree", including the parents, are reloaded (view, controller, etc). The only way to work around that is using "reloadOnSearch: false" on the parent state. The problem is that I need to reload the parent state, in other contexts, so I can't set that for the entire state, but need to decide when not to reload the parent state, for ex using "notify: false".

**Comment by DannyRubenMA** [comment]
Test with $location.path(state); and $location.path().replace();  obviously using ui-router
