### ISSUE TITLE
Feature request: View defined filter

### ISSUE THREAD

**Issue by georeith** [angular-ui/ui-router#1393]
I currently have use case for this and was thinking that other developers may find it useful.

I would like to see a filter that can be used in directives such as `ng-if`, `ng-switch`, `ng-show`, .etc

The filter checks whether the named view is defined in the current state. Currently you can do something like `ng-if="$state.current.views.header"`, however this required additional checks for absolutely named views, views described in parent states, .etc

I would rather do something like `ng-if="'header' | viewInState"` which would be true when the view has a template at the current state (and it's progeny).

This is useful in cases where you have supporting elements around a view but want to limit what the view can alter, for example consider the following header:

    <header ng-if="'header' | viewInState">
        <span>Brought to you by:</span>
        <span ui-view="header"></span>
    </header>

Which a state can modify the second span but not the one next to it, perhaps I would like to conditionally show this entire header only if it's contained view is visible.

The filter would work the same way as view targeting already does where `'header'` refers to the ui-view only within the scope of the current view (based on filter's location) and `header@wizard` refers to the `header` view on the `wizard` state.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
