### ISSUE TITLE
Impossible to disable html5Mode with angular 1.3.0-rc.3

### ISSUE THREAD

**Issue by Yoshix** [angular-ui/ui-router#1397]
Due to:

https://github.com/angular/angular.js/commit/dc3de7fb7a14c38b5c3dc7decfafb0b51d422dd1

the html5mode-check in `urlRouter.js [line 383]` is no longer correct. And thus it's impossible to disable html5mode.

A quick fix could be:

```
var isHtml5 = $locationProvider.html5Mode();
if (angular.isObject(isHtml5)) {
  isHtml5 = isHtml5.enabled;
}
```

**Comment by rwwagner90** [comment]
I'm on Angular 1.4.4 and seeing issues with html5mode again. Anyone else?

**Comment by winnemucca** [comment]
Yeah,
I am seeing the same issue.  Let me know if you found a fix

**Comment by rwwagner90** [comment]
@winnemucca I believe the issue should be fixed now. Are you on the latest?
