### ISSUE TITLE
$stateChangeStart to wait for an ajax request (some manual promise to ressolve) without state.go()

### ISSUE THREAD

**Issue by syrys** [angular-ui/ui-router#1399]
Got a quick question for you guys.

I want to be able to execute a possible ajax request from a factory on "stateChangeStart" event (i check some state parameters). Seems like if i event.preventDefault(), then call the factoryMethod for the ajax request, then on resolve do a state.go() to continue into the state, it simply gets caught in the same conditions and ends in an infinite loop. Obviously i can set some other flags somewhere to prevent this, but is there a better way to do it than this? Some alternative to state.go()?

Also tried { notify: false }, but that skips "$stateChangeSuccess" also. I want "$stateChangeStart" called only once and "$stateChangeSuccess" called only once, unless you get redirected to another page on fail condition of the promise (then it should call "$stateChangeStart" for the new state as usual).

Note the stateChangeStart is on the root controller. 

Ps. im trying to check if a local user object exists and if not, it will check a rest api to see if a user session exists and fetches the user data. This is so i dont have to put ressolve methods on every state, instead a simple flag indicating that the user must be logged in to view this state.

Thanks in advance.

**Comment by paulflo150** [comment]
Any thoughts on when this feature will be available?

Thanks!

**Comment by ludovicMercier** [comment]
Does the new Transitionprovider give the possibility to customize the dialogbox by the use of $modal service  in place of a standard confirm("are your sure ?") ?

**Comment by lebster** [comment]
+1

**Comment by nateabele** [comment]
@paulflo150 Soon. :-)

**Comment by nateabele** [comment]
@ludovicMercier Sure, but you can do that with `onEnter`/`onExit` now.

**Comment by nsreevani** [comment]
+1

**Comment by arjunasuresh3** [comment]
+1

**Comment by DavidKk** [comment]
+1

**Comment by ProLoser** [comment]
Okay, why aren't you just using a resolve parent state?

**Comment by Guardiannw** [comment]
@ProLoser How would that manifest itself?

**Comment by gmsewell6** [comment]
+1
Any update on convergence & ETA?

**Comment by lvarayut** [comment]
+1 Any progress on this issue?

**Comment by nateabele** [comment]
https://github.com/angular-ui/ui-router/tree/feature-1.0

**Comment by arjunasuresh3** [comment]
+1

**Comment by leonuh** [comment]
I had similar problems, so made a flexible provider: https://github.com/leonuh/ui-router.redirect - I hope it can help you to handle the dependecies and chains more efficiently

**Comment by slavafomin** [comment]
Hello! I'm also looking for a way to do asynchronous operations inside of UI router's event handlers. I've tried to return promise from the event handler, but it's not respected by the router. Are there any features available right now in production, that I can use to achieve the similar result? Thank you!

**Comment by nateabele** [comment]
> I've tried to return promise from the event handler, but it's not respected by the router.

Correct, UI-Router's events are standard Angular events, and so do not support anything promise-related.

> Are there any features available right now in production

Not in production, but we're about to drop an alpha-quality version of 1.0, so, soon. :smile:

**Comment by slavafomin** [comment]
Thank you Nate! I will be looking forward for those features.

In the meantime, I've created a top-level non-abstract state and put my global initialization logic inside of it's `resolve` property. That way it will be executed before anything else happens. I.e., I can restore the session using cookie variable and load user data from the server, before proceeding to other states. Maybe this idea will be useful to someone else here.

Cheers! ;)

**Comment by slavafomin** [comment]
Looks like my solution is not working as expected. When I do `event.preventDefault()` in `$stateChangeStart` the topmost state is not resolved and initialization doesn't happen.

I've tried approach [mentioned](https://github.com/angular-ui/ui-router/issues/1399#issue-43828476) by @syrys, i.e. doing `event.preventDefault()`, then my async operation and then `$state.go`, but I'm getting into indefinite loop that way. I've tried to disable `notify` flag. That works, but state's view is not rendered that way (looks like it's using some event internally).

I've tried this approach:

```javascript
$rootScope.$on('$stateChangeStart', function (event, toState, toParams, fromState, fromParams) {

        if (toParams.skipAuthCheck) {
          return;
        }

        // We need to prevent navigation right now, in order to give time for
        // our asynchronous operations to proceed.
        event.preventDefault();

        doSomeAsync().finally(continueNavigation);

        function continueNavigation () {
          var params = angular.copy(toParams);
          params.skipAuthCheck = true;
          $state.go(toState.name, params);
        }

      });
```

But when `$stateChangeStart` event handler is called for the second time, I'm not getting `skipAuthCheck` param. Looks like router only passes pre-defined parameters.

@nateabele could you recommend some workaround please? How do I prevent second execution of my async logic and to break this indefinite loop?

**Comment by garhbod** [comment]
@slavafomin I was trying to do the same thing by adding a new param but realised that a state can only contain the params that are in it's url `url: "/edit/{id:[0-9]+}"`

So what I did was created a variable, set to false, outside of the on $stateChangeStart and changed it to true where required.

```javascript
var skipSomeAsync = false;
$rootScope.$on('$stateChangeStart', function (event, toState, toParams, fromState, fromParams) {

        if (skipSomeAsync) {
          return;
        }

        // We need to prevent navigation right now, in order to give time for
        // our asynchronous operations to proceed.
        event.preventDefault();

        doSomeAsync().finally(continueNavigation);

        function continueNavigation () {
          var params = angular.copy(toParams);
          skipSomeAsync = true;
          $state.go(toState.name, params);
        }
        skipSomeAsync = false;

      });
```

**Comment by garhbod** [comment]
Better yet instead of `var skipSomeAsync` make it `$rootScope.skipSomeAsync` so that it can be accessed elsewhere if required

**Comment by derekgreer** [comment]
It's been about 3 months since any talk of a release. Any update?

**Comment by nateabele** [comment]
https://github.com/angular-ui/ui-router/releases/tag/1.0.0alpha0

**Comment by derekgreer** [comment]
@garhbod Another approach that works:

```
$rootScope.$on('$stateChangeStart', function (event, toState, toParams, fromState, fromParams) {

        if (fromParams.skipSomeAsync) {
          return;
        }

        event.preventDefault();

        doSomeAsync().finally(continueNavigation);

        function continueNavigation () {
          fromParams.skipSomeAsync = true;
          $state.go(toState.name, toParams);
        }

      });
```

**Comment by slavafomin** [comment]
Be advised, that if you are using `preventDefault()` approach, the initial caller, e.g. `$state.go` will be rejected.

**Comment by tangorri** [comment]
@slavafomin that means there is no solution until version 1.0 ?

**Comment by slavafomin** [comment]
That's up to you and your app. It could be fine to use if you are not relying on the promise returned by "go".

**Comment by tangorri** [comment]
Well it seems the flag workaround works for me. thanks guys, when is 1.0.0 expected to be released ?

**Comment by jforjava1981** [comment]
I have a case where I have to load some configuration data from Back-End using http when anular app loads for the first time. What I have done right now is that I have created an abstract state which is inherited by all states. I load this configuration on parent state's resolve and provide the key to all states so that whenever a state is activated it first waits for parent's resolve to be satisfied even if user directly places a URL in browser. Is there a better way to do this? Can this feature solve my problem.

I have another case where I have to load some data from backend when I move from state a to state b or even if I directly place the b's URL in the browser. Depending on data I have to prevent the transition to state B. I believe this feature does exactly that. Correct?

**Comment by nirsmadar** [comment]
+1

**Comment by christopherthielen** [comment]
@jforjava1981 

>  I believe this feature does exactly that. Correct?

Yes, this feature allows you to implement all those cases without using `resolve:`.  In 1.0, we are going to recommend resolve is used *only for loading data*.

**Comment by jforjava1981** [comment]
@christopherthielen  Thanks. Waiting eagerly :)

**Comment by enriquevr** [comment]
@slavafomin In order to avoid the rejection of the promise caused by calling event.preventDefault I'm thinking in adding the async permission check into a factory method whose interface returns a promise and use that into both, the $stateChangeStart listener and in a decorated (using angular.decorator) version of $state.go which may or may not delegate to the original $state.go depending on the outcome of the check, I will report back on  how it goes

**Comment by schmod** [comment]
1.0 isn't quite out yet.  It's still marked as a beta.

**Comment by christopherthielen** [comment]
1.0 is in release candidate: https://ui-router.github.io/blog/angular-ui-router-1.0.0-rc.1/

Start using it!

**Comment by christopherthielen** [comment]
@stephengardner I spent quite a bit of effort cleaning up the docs.  I hid most of the internal API by default.  Hope they're easier to use now.

https://ui-router.github.io/ng1/docs/latest/index.html

**Comment by ProLoser** [comment]
@christopherthielen I think there's a typo in the first example: https://ui-router.github.io/ng1/docs/latest/modules/directives.html#uistate it should be `ui-state` not `ui-sref`?

**Comment by christopherthielen** [comment]
@ProLoser yep, thanks for pointing that out!

**Comment by ShurikAg** [comment]
> @garhbod Another approach that works:
> 
> ```
> $rootScope.$on('$stateChangeStart', function (event, toState, toParams, fromState, fromParams) {
> 
>         if (fromParams.skipSomeAsync) {
>           return;
>         }
> 
>         event.preventDefault();
> 
>         doSomeAsync().finally(continueNavigation);
> 
>         function continueNavigation () {
>           fromParams.skipSomeAsync = true;
>           $state.go(toState.name, toParams);
>         }
> 
>       });
> ```

Hi, this approach does not work (at least not anymore.
The `fromParams` are not extendible so in different browsers I am getting a different error.
For Safari:
```
TypeError: Attempted to assign to readonly property.
  at action(./app/features/checklist/checklist-ctrl.js:517:33)
  at fn(./app/features/message-box/confirm-ctrl.js:13:53)
  at expensiveCheckFn(./node_modules/angular/angular.js:16213:1)
  at $element(./node_modules/angular/angular.js:26592:1)
  at $apply(./node_modules/angular/angular.js:18094:1)
  at ? (./node_modules/angular/angular.js:26597:1)
  at dispatch(/npm/jquery/dist/jquery.min.js:2:41777)
  at s(/login:5:23562)
  at _a(./node_modules/@sentry/browser/dist/index.js:3257:1)
```

How can I work around it
