### ISSUE TITLE
TypeError: Object.keys called on non-object in angular 1.3.0 rc3

### ISSUE THREAD

**Issue by pranaydutta89** [angular-ui/ui-router#1400]
while using  $state.transitionTo i am getting the following typeerror

here's the ST

    TypeError: Object.keys called on non-object
    at Function.keys (native)
    at extend (http://localhost:8080/ExternalLibs/angular-1.3.0/angular.js:423:35)
    at Object.transitionTo (http://localhost:8080/ExternalLibs/angular-ui-router/angular-ui-router.js:2497:27)
    at http://localhost:8080/App/out.js:1330:28
    at Scope.$get.Scope.$broadcast (http://localhost:8080/ExternalLibs/angular-1.3.0/angular.js:13751:50)
    at http://localhost:8080/ExternalLibs/angular-ui-router/angular-ui-router.js:2689:38
    at processQueue (http://localhost:8080/ExternalLibs/angular-1.3.0/angular.js:12234:41)
    at http://localhost:8080/ExternalLibs/angular-1.3.0/angular.js:12250:35
    at Scope.$get.Scope.$eval (http://localhost:8080/ExternalLibs/angular-1.3.0/angular.js:13436:44)
    at Scope.$get.Scope.$digest (http://localhost:8080/ExternalLibs/angular-1.3.0/angular.js:13248:53) angular.js:10683(anonymous function)

**Comment by spacentime** [comment]
Here is a solution , 
the following JavaScript 
will define Object.keys if it's not defined (IE <9) also will return an empty array when calling Object.keys instead of throwing an error again for IE < 9.

see also
https://developer.mozilla.org/en-S/docs/Web/JavaScript/Reference/Global_Objects/Object/keys

(function () {   
    if (!Object.keys) {
        Object.keys = (function () {
            'use strict';
            var hasOwnProperty = Object.prototype.hasOwnProperty,
                hasDontEnumBug = !({ toString: null }).propertyIsEnumerable('toString'),
                dontEnums = [
                  'toString',
                  'toLocaleString',
                  'valueOf',
                  'hasOwnProperty',
                  'isPrototypeOf',
                  'propertyIsEnumerable',
                  'constructor'
                ],
                dontEnumsLength = dontEnums.length;

            return function (obj) {
                if (typeof obj !== 'object' && (typeof obj !== 'function' || obj === null)) {
                    throw new TypeError('Object.keys called on non-object');
                }

                var result = [], prop, i;

                for (prop in obj) {
                    if (hasOwnProperty.call(obj, prop)) {
                        result.push(prop);
                    }
                }

                if (hasDontEnumBug) {
                    for (i = 0; i < dontEnumsLength; i++) {
                        if (hasOwnProperty.call(obj, dontEnums[i])) {
                            result.push(dontEnums[i]);
                        }
                    }
                }
                return result;
            };
        }());
    } else {
        var _nativeKeys = Object.keys;

        Object.keys = (function () {
            'use strict';            

            return function (obj) {
                if (typeof obj !== 'object' && (typeof obj !== 'function' || obj === null)) {
                    return [];  // return empty array;
                }              
                return _nativeKeys(obj);
            };
        }());        
    }
})();

**Comment by pranaydutta89** [comment]
thnx :+1:
