### ISSUE TITLE
Issue with $dirty in angularJS with ui-router

### ISSUE THREAD

**Issue by erandika1986** [angular-ui/ui-router#1412]
if I use the the ng-view directive inside the form element I can checked the is dirty like this with ngRoute and it is working fine as expected way. 

http://plnkr.co/edit/fbq4VwwmUQBqsBPPu8S7?p=preview

But if I implement the same functionality with ui.router directive, it is unable to load to my main view.

http://plnkr.co/edit/HyuJtph8wuaNtecPxt1K?p=preview

 But if I replace the html from (which is in the index.html) with div then it began to work. But thing is if I use the div tag I'm unable to check the $dirty for that controller. if this bug in ui-router or is these any other method to check the $dirty for my controller?

Thanks,
Erandika

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
