### ISSUE TITLE
ENOTFOUND bower installing ui-router

### ISSUE THREAD

**Issue by dbclkclk** [angular-ui/ui-router#1425]
Hey Folks:

Having an issue running bower install and getting the ENOTFOUND error. I am not behind a proxy server and can't figure out what is causing this for a few days now. Below is my bower.json file:

```
 {
   "name": "angular-seed",
   "description": "A starter project for AngularJS",
  "version": "0.0.0",
  "homepage": "https://github.com/angular/angular-seed",
  "license": "MIT",
 "private": true,
 "dependencies": 
  {
     "angular": "1.2.x",
     "angular-mocks": "~1.2.x",
    "bootstrap": "~3.1.1",
     "angular-route": "~1.2.x",
     "angular-ui-router": "0.2.11"
  }
}
```

C:\Users\xxxxxxx\webapp\resources\js>bower install
bower ENOTFOUND     Request to https://bower.herokuapp.com/packages/angular-ui-router failed: getaddrinfo ENOTFOUND

This only fails when I have angular-ui-router in my dependency.

**Comment by moneytree-doug** [comment]
CircleCI is giving me this issue, and it seems to happen to me from time to time.

**Comment by dominikmank** [comment]
Same problem happened here. bower cache was cleaned & stuff, but nothing works. 

Since we need it, we just added the following line to the bower.json
```javascript
"angular-ui-router": "https://github.com/angular-ui/ui-router.git#0.2.18"
```

**Comment by roma86** [comment]
@dominikmank thank you

**Comment by overmailed** [comment]
@dominikmank Seems like bower renamed it to just 'ui-router' without 'angular'.

**Comment by dominikmank** [comment]
@overmailed thanks for response.

Works also with 
```javascript
"ui-router": "~0.2.18"
```

**Comment by overmailed** [comment]
@dominikmank And now I can see they fixed it. angular-ui-router is available again to me.
