### ISSUE TITLE
Using ng-app and ui-view on the same element causes jqLite injector() to fail

### ISSUE THREAD

**Issue by juliemr** [angular-ui/ui-router#1428]
If your template is something like `<div id="foo" ng-app="myApp" ui-view>`, then the jqLite injector method, `angular.element(document.getElementByID('foo')).injector()`, will return undefined.

This is because `ui-view` uses `transclude: 'element'` - I have a minimal test case showing this behavior at https://gist.github.com/juliemr/ffccf5bbe5b88a2d3da9

I think that this is all working as intended, but causes very hard to debug issues, especially with Protractor which relies on getting the injector (see https://github.com/angular/protractor/issues/1147).  Maybe it should be documented that `ui-view` shouldn't be used on your `ng-app` element?

**Comment by cdale77** [comment]
I ran into this issue today while using Ionic to package an app built with ui-router. The problem did not manifest itself before we tried Ionic

**Comment by nateabele** [comment]
I say we add it to the FAQ and move on with life. :smile:

**Comment by christopherthielen** [comment]
:+1:
