### ISSUE TITLE
TypeError when changing route and when the previous state childview element isn't on the DOM anymore 

### ISSUE THREAD

**Issue by heiso** [angular-ui/ui-router#1429]
AngularJS   v1.2.26
ui-router      v0.2.11

See this jsfiddle http://jsfiddle.net/heiso/Lxx3vL42/ using ui-router v0.2.11(context and bug) and this same jsfiddle http://jsfiddle.net/heiso/Ldedhuw8/ using ui-router v0.2.10 (same context, no bug).

## Context (4 states):
- otherwise
    - onEnter -> `$state.go('home')`;
- auth
    - abstract
    - mainView template: `<p>login page</p><div ui-view="childView"></div>`
- auth.index
    - childView template: `<p>login form</p>`
- home

## Steps :
Firsts, go to `auth.index` state then go to `otherwise` state, ui-router attempt to get the previous state element -> `TypeError: Cannot read property 'mainView@' of null`

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
