### ISSUE TITLE
Unable to inject ui-router's $state within jasmine unit-test

### ISSUE THREAD

**Issue by lu4** [angular-ui/ui-router#143]
I have an extended description of the problem written on stackoverflow (sorry for that, it just seems that I can't post images to github):

http://stackoverflow.com/questions/16723075/writing-a-unit-test-in-jasmine-for-a-controller-that-uses-ui-router

**Comment by smokinjoe** [comment]
And you fixed it by adding what, where?

I'm running into possibly the same issue, and simply adding `import uiRouter from 'angular-ui-router';
` to the top of the file didn't work.  Is there a spot to inject `uiRouter` as a dependency?
