### ISSUE TITLE
ui-sref-active not working correctly with abstract and child states

### ISSUE THREAD

**Issue by blah238** [angular-ui/ui-router#1431]
http://plnkr.co/edit/c7OS1pwI5IjAAs5cEi5s?p=preview

In the example above, clicking the Administration nav element shows a view with two tabs, Users and Roles.

These correspond to the states `admin.users` and `admin.roles`, while `admin` is an abstract state whose URL is inherited by `admin.users`. This all works fine except when setting the active class using `ui-sref-active`.

There are two problems in this scenario:

1. The Administration nav element is not made active when on the Roles tab
2. When refreshing the page (be sure to pop out the Plunker preview) while on the Roles tab, no elements get the active class set

I would like to avoid using `$state.includes` directly since `ui-sref-active` is supposed to work on child states since 0.2.11: https://github.com/angular-ui/ui-router/pull/927

Am I doing something wrong or is this a bug?

**Comment by rweng** [comment]
+1, also like the idea of linking to abstract state if it provides a default child

**Comment by tomwganem** [comment]
+1

**Comment by neaped** [comment]
I have got the similar problem, what I have done:

Don't use abstract within state, coz ui-sref-active support nest child state, so I use $state.go('child state') within the controller to force the parent state to go to it's child. But this will bring up the other problem, parent state's active class will never gone :( this ui-sref-active-eq won't work coz I don't give child state specific url.

**Comment by lucky7id** [comment]
:+1: +1

**Comment by f2net** [comment]
+1 for the proposed form: ui-sref-active="{class: 'active', state: 'admin'}"

**Comment by tristanz** [comment]
+1

**Comment by ghoullier** [comment]
:+1:

**Comment by jaman1020** [comment]
+1 on this, but in the meantime I've worked out a *somewhat* hacky solution that may or may not work for your use cases.
ui-sref-active works with child states, but not 'sister' states, such as when you have two tabs. What I've done is converted the second tab to a child state, but changed the same views by using absolute view targeting. 
So - 
    .state('user.home.main', {
       views: {
             view1@user.home: {}
             view2@user.home: {}
        }
    }
    .state('user.home.main.secondTab'. { // - because its part of user.home.main it retains state
      views: {
             view1@user.home: {}
             view2@user.home: {}
        }
    }

Again, depending on what you use your states for, this may or may not work for you, but at least it lets you preserve active state natively without having to create a directive or anything else.

**Comment by santyclaz** [comment]
+1

**Comment by ruchevits** [comment]
I use the following in my application:

```
$scope.menu = [
	{
		title: 'Home',
		state: 'home'
	},
	{
		title: 'Categories',
		state: 'category'
	},
	{
		title: 'Category One',
		state: 'category.one',
		root: 'category'
	},
	{
		title: 'Category Two',
		state: 'category.two',
		root: 'category'
	}
];
```

```
$scope.isActive = function(root) {
    return $state.includes(root);
};
```

```
<li ng-repeat="item in menu" ng-class="{active: isActive(item.root || item.state)}">
  <a ui-sref="{{item.state}}">{{item.title}}</a>
</li>
```

So, if `root` is not defined, we just fall back to default behaviour.

**Comment by almandot** [comment]
+1 for either specifying the state for ui-sref-active or linking to abstract states if a default child is set... or both!

**Comment by SignalDancer** [comment]
+1 Just hit this need myself in an application where I need to be "active" on an abstract parent. Reordering my hierarchy has other large implications that I can't back out of in a timely fashion right now.

**Comment by MichaelJCole** [comment]
+1 @blah238 thanks for a simple solution.

**Comment by uguryilmaz** [comment]
hi, i have this exect problem. i have a sidebar menu with 3 level deep.

**Comment by budkin76** [comment]
+1. I'm running into issues as my parent state is abstract but I need it to be active for all its children.

**Comment by budkin76** [comment]
Also, @blah238 thank you for that workaround! Using that for now.

**Comment by sharpmachine** [comment]
An easy workaround is just put your first view in the ui-view like so:

```html
<!-- list.html -->
<div ui-view class="animated fadeIn">
  <toolbar></toolbar>
  <child-layout>
    <charge-card ng-if="vm.charges" ng-repeat="charge in vm.charges" dynamic-popover="vm.dynamicPopover" charge="charge" show-confirm="vm.showConfirm"></charge-card>
    <div ng-show="!vm.charges.length">There are no charges for {{$parent.$parent.vm.subject.basicInfo.firstName}}. Add charges by clicking the plus button.</div>
  </child-layout>
</div>

<!-- edit.html -->
<toolbar></toolbar>
<child-layout>
  <formly-form model="vm.charge" fields="vm.chargeForm">
    <button class="btn btn-primary btn-raised" ng-click="vm.updateCharge()">Save Changes</button>
    <button class="btn btn-inverse btn-inverse-danger" back-button>Cancel</button>
    <button class="btn btn-sm btn-danger pull-right" ng-click="vm.showConfirm($event)"><i class="fa fa-trash"></i></button>
  </formly-form>
</child-layout>

<!-- link to charges list -->
<li role="presentation" ui-sref-active="active"><a ui-sref="subject.charges({subjectId: subject.id})">Charges <paper-ripple fit></paper-ripple></a></li>
```

```javascript
//Routing
// GET /subjects/1/charges
  .state('subject.charges', {
    url: '/charges',
    templateUrl: 'components/charges/list.html',
    controller: 'ChargesListCtrl',
    controllerAs: 'vm',
    resolve: {
      charges: function(Subjects, $stateParams) {
        return Subjects.one($stateParams.subjectId).getList('charges');
      },
      charge: function(Charges, $stateParams) {
        return Charges.one($stateParams.chargeId).get();
      }
    }
  })

  // GET /subjects/1/charges/1
  .state('subject.charges.edit', {
    url: '/:chargeId',
    templateUrl: 'components/charges/edit.html',
    controller: 'ChargeEditCtrl',
    controllerAs: 'vm',
    resolve: {
      charge: function(Charges, $stateParams) {
        return Charges.one($stateParams.chargeId).get();
      }
    }
  })
```

All your child views will still go through the original ui-view in the list.html file and your navigation actives will still be true whether you're on the parent or the child.

**Comment by nikshulipa** [comment]
+1. Also having thins issue

**Comment by eric-norcross** [comment]
+1. 

Building on  @stoykostanchev's solution; it would also be great if it could also support wildcards similar to  `$state.includes()`

    <a ui-sref='admin.users' ui-sref-active="{class: 'active', state: 'admin.*'}">Link</a>

Which, I feel would be more clear than writing:

     <a ui-sref='admin.users' ng-class=" $state.includes('admin.*') ? 'active' : null">Link</a>

**Comment by simmu** [comment]
+1. I like @eric-norcross  suggestion on the wildcards support.

**Comment by arkin-** [comment]
+1

**Comment by ailling** [comment]
Thanks @arkin; works perfectly for me

**Comment by domalak** [comment]
+1 to @arkin-

**Comment by jancel** [comment]
+1 @arkin Wonder if they could bring this in. Simple to integrate

**Comment by alonronin** [comment]
@jancel he injected it to the directive callback

**Comment by jancel** [comment]
Ah. Great. Thanks. I missed that one. Anyway, another +1.

On Monday, August 10, 2015, Alon Valadji <notifications@github.com> wrote:

> @jancel <https://github.com/jancel> he injected it to the directive
> callback
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-router/issues/1431#issuecomment-129599583>
> .
>


-- 
Jeff Ancel

(314) 703-8829 - Main

www.jeffancel.com

**Comment by hiquest** [comment]
@arkin- thanks! I was about to write something like myself, but you saved me the time!

**Comment by sharpmachine** [comment]
+1 @arkin- you're a genius. If I were a chick I'd show you my boobs!

**Comment by arkin-** [comment]
You are all welcome ^ :)

If this is something the ui-router team want to implement, I'll happily submit a pull request.

**Comment by Luddinus** [comment]
@arkin- great!

**Comment by celsomtrindade** [comment]
@arkin- Thanks!! =D

**Comment by jessicard** [comment]
@sharpmachine shit like that makes women not want to contribute to open source

**Comment by CoralineAda** [comment]
The statement by sharpmachine is disgusting.

**Comment by sharpmachine** [comment]
@jessicard @CoralineAda You're right. I'm sorry. I was just excited kuz it took me forever to find a solution. I've edited the comment.

**Comment by jessicard** [comment]
@sharpmachine thank you!

**Comment by CoralineAda** [comment]
https://github.com/angular-ui/ui-router/pull/2309

**Comment by Zensavona** [comment]
@sharpmachine maybe you can make reference to a beverage without privilege attached, it triggers me. 

I'd feel a lot safer if you said "I'd buy you a water"

**Comment by jaman1020** [comment]
@sharpmachine we don't have water in California

**Comment by nateabele** [comment]
@arkin- What about extending `uiSref` to also accept an object?

**Comment by nblasgen** [comment]
@arkin- Thank you so much for your working code example.  It was so simple that I had time to write this comment with my extra time.

**Comment by arkin-** [comment]
Ok @nateabele I'm not following, do you have an example?

**Comment by nateabele** [comment]
@arkin- Something similar to the example @eric-norcross posted, i.e. `ui-sref-active="{ activeClass: 'active', state: 'admin.*' }"` — then you'd just need to patch `uiSrefActive` to check whether the value is an object or string, and act accordingly. That probably just means appending the named state to `states`, and no-op'ing `$$addStateInfo()`.

**Comment by zloidemon** [comment]
+1

**Comment by andersonef** [comment]
@Grievoushead Thank you so much... You solution were awesome and simple! Thanks again

**Comment by Giovancruz** [comment]
Sorry i am new on angular, I think I'm doing something wrong. The solution from @arkin- dont works for me. Anybody can help me?
http://plnkr.co/edit/JmrZwbEJUjN3iKcrhiVl?p=preview

**Comment by jwuliger** [comment]
@Giovancruz and @arkin- This directive worked perfectly for me. Thanks you so much. I spent over 8 hours trying to find a working solution. I am sorry it is not working for you @Giovancruz.

**Comment by blunatic** [comment]
+1 @arkin

**Comment by basilinjoe** [comment]
+1 @arkin

**Comment by riteshjagga** [comment]
@Giovancruz 
I'm new to plunkr so didn't know how to modify your code. I made following changes:

- Changed parent from `dashboard` to `dashboard.payments`.

- and added `<div class="ui-view"></div>` in the `payments.html` file.
```
.state('dashboard.payments.paymentdetail', {
        parent: 'dashboard.payments',
        url:'/detail',
        templateUrl: 'paymentdetail.html',
        //controller: 'PaymentdetailCtrl',
        //controllerAs: 'paymentDetail',
        ncyBreadcrumb: {
          label: 'BILLINGDETAILS',
          parent: 'dashboard.payments'
        },
      })
```

**Comment by MaximilianLloyd** [comment]
@adamalbrecht  you are a saint, thanks

**Comment by axul** [comment]
I made a little change to @arkin directive

	.directive('uiSrefActiveIf', ['$state', '$parse', function($state, $attrs, $parse) {
	    return {
	        restrict: "A",
	        link: function(scope, element, attrs){
	        	var state = attrs.uiSrefActiveIf;	

	        	function update() {
	        	    if ( $state.includes(state) || $state.is(state) ) {
	        	        element.addClass("active");
	        	    } else {
	        	        element.removeClass("active");
	        	    }
	        	}

	        	scope.$on('$stateChangeSuccess', update);
	        	update();
	        }
	    };
	}])

All I did was to move the logic from the controller to the link function in the directive to be able to get the ui-sref-active-if attr from a scope instead of a literal string

**Comment by tgrant59** [comment]
It seems like people are still looking at this even though the solution is in at least the most recent version!
It is still undocumented, but just use an object (like with ng-class) and it will work.

This won't work right:
```html
<li ui-sref-active="active">
  <a ui-sref="admin.users">Administration Panel</a>
</li>
```

This will:
```html
<li ui-sref-active="{ 'active': 'admin' }">
  <a ui-sref="admin.users">Administration Panel</a>
</li>
```

**Comment by eddoliveira** [comment]
@tgrant59 That worked. Thanks!

My example: 

`<span ui-sref-active="{'active':'details.info.medical'}">
    <a href="" ui-sref="details.info.medical({param1: object1, param2: object2})">
        <span>MEDICAL INFO</span>
    </a> 
</span>`

**Comment by samuil4** [comment]
@tgrant59 Thanks for the example.

Notes: Angular developers are still workarounding integrated features like this one in this retarded framework. THE NEW INTEGRATED FEATURES ARE NOT DOCUMENTED AT ALL!!! Every developer must go first to the official documentation where he finds nothing useful, then he goes to stackoverflow where all solutions are outdated or bad practices, then he decides that he will either waste 2 more hours going in to the comments of a related issue and explore all pull request OR simply write a custom solution that in 100% of the cases simply overrides or workarounds core features of the framework. 

Thanks to the google marketing team frameworks like angular are well sold to end clients without even thinking if this framework will be a major drawback for the entire project. And that's how zillions of govnocode projects are born.

PS: wasted 3 hours to find an example of this feature and to determine if this feature is actually built in to the framework...

**Comment by dayachand** [comment]
I solve third level navigation issue in homer theme for angular js.

css for this: 
#side-menu li .nav-second-level li .nav-third-level li a{color:#6a6c6f; padding: 7px 10px 7px 53px;}
#side-menu li .nav-second-level li .nav-third-level li.active a{color:#3498db}

navigation for this: 
here admin and admin-setup are base state

 <li ng-class="{active: $state.includes('admin') || $state.includes('admin-setup')}">
                <a href="#"><i class="fa fa-cog" aria-hidden="true"></i><span class="nav-label">Admin Settings</span><span class="fa arrow"></span> </a>
                <ul class="nav nav-second-level" ng-class="{in: $state.includes('admin') || $state.includes('admin-setup')}">
                    <li ui-sref-active="active"><a ui-sref="admin.company-setup-profile">Company Setup / Profile</a></li>
                    <li ui-sref-active="active"><a ui-sref="admin.services-provided">Services Menu</a></li>
                    <li ui-sref-active="active"><a ui-sref="admin.manage-users">Manage Users</a></li>
                    <li ui-sref-active="active"><a ui-sref="admin.billing-items">Billing Items</a></li>
                    <li ng-class="{active: $state.includes('admin-setup')}">
                        <a href="#"><i class="fa fa-cog" aria-hidden="true"></i><span class="nav-level">Manage Category</span><span class="fa arrow"></span> </a>
                        <ul class="nav nav-third-level" ng-class="{in: $state.includes('admin-setup')}">
                            <li ng-class="{active: $state.includes('admin-setup.category-setup')}"><a ui-sref="admin-setup.category-setup">Expense Category</a></li>
                            <li ng-class="{active: $state.includes('admin-setup.device-types')}"><a ui-sref="admin-setup.device-types">Device Types</a></li>
                            <li ng-class="{active: $state.includes('admin-setup.designation-setup')}"><a ui-sref="admin-setup.designation-setup">Designation Setup</a></li>
                            <li ng-class="{active: $state.includes('admin-setup.ticket-classes')}"><a ui-sref="admin-setup.ticket-classes">Ticket Classes</a></li>
                        </ul>
                    </li>
                </ul>
            </li>

**Comment by phazei** [comment]
This is great:
```
<span ui-sref-active="{'active':'details.info.medical'}"> <a href="" ui-sref="details.info.medical({param1: object1, param2: object2})"> <span>MEDICAL INFO</span> </a> </span>
```

But what if you have a menu item that has two abstract items under it?
The code does a foreach but since the class is the key, you can't have two routes use the same class..
eg) `{'active':'details.info.medical', 'active':'details.records'}`
The unique thing here is going to be the state name, so that should be the key, or it should allow the value to be an array which wouldn't break BC.
eg) `{active':['details.info.medical','details.records']}`

**Comment by riteshjagga** [comment]
What if you have nested abstract states as in the following routes
`organizations.organization(abstract).list/add/edit` etc. and `organizations.organization(abstract).users(abstract).list/add/edit` etc.

but with a flattened menu like this:
```
<a class="list-group-item"
      ui-sref="home.organizations.organization.view({orgId: loggedInUser.organizationId})"
      ui-sref-active="{'active': 'home.organizations.organization', 'deactive': 'home.organizations.organization.users'}">
      Organization
</a>
<a class="list-group-item"
      ui-sref="home.organizations.organization.users.list({orgId: loggedInUser.organizationId})"
      ui-sref-active="{'active': 'home.organizations.organization.users'}">
      Users
</a>
```

When you are within the Users routes, both the menu items will be highlighted.

To prevent this, added another class `'deactive': 'home.organizations.organization.users'` and this `deactive` class can have the styles as in normal state of the menu item.

It might be helpful for someone.

**Comment by sarahsga** [comment]
I have solved it by overriding ui-sref-active ( well, not exactly):

`angular.module('app.layout')
    .directive('uiSrefActive2', StateRefActiveDirective);

  StateRefActiveDirective.$inject = ['$state', '$stateParams', '$interpolate'];

  function StateRefActiveDirective($state, $stateParams, $interpolate) {
    return {
      restrict: "A",
      priority: 1,
      controller: ['$scope', '$element', '$attrs', function ($scope, $element, $attrs) {
        var state, params, activeClassAndStateStr;

        activeClassAndStateStr = $interpolate($attrs.uiSrefActiveEq || $attrs.uiSrefActive2 || '', false)($scope);
        var jsonString = activeClassAndStateStr.replace(/'/g, '"');
        var activeClassAndStateObj = JSON.parse(jsonString);


        $scope.$on('$stateChangeSuccess', update);

        // Update route state
        function update(event, toState, toParams, fromState, fromParams, options) {

          if (toState.name.startsWith(activeClassAndStateObj.state)) {
            $element.addClass(activeClassAndStateObj.class);
          } else {
            $element.removeClass(activeClassAndStateObj.class);
          }

        };

      }]
    }
  }`

and then using this directive in the view:
`<ion-item menu-close2 ui-sref="app.facts" ui-sref-active2="{'class':'active','state':'app.facts'}">
         FACTS
        </ion-item>`

**Comment by ffradegrada** [comment]
@arkin- works perfectly! Thank you.

**Comment by nateabele** [comment]
@samuil4 Nobody on the UI Router project works for Google. We all do this in our spare time. If you don't like the situation, figure out the issue and submit a patch to the documentation. If everyone did that just once, you wouldn't need StackOverflow.

**Comment by arshabh** [comment]
we should have the default state for the abstract state - just like react router has index route - that will solve many problems.

**Comment by owenXin** [comment]
Finally I got a solution from the following issue:
https://github.com/angular-ui/ui-router/issues/2954
```
ui-sref-active="{'active': 'administration.**'}"
```

**Comment by marioleed** [comment]
Nice @owenXin! @christopherthielen's [solution](https://github.com/angular-ui/ui-router/issues/2954#issuecomment-244134910) did it for me as well.

**Comment by oscarr-reyes** [comment]
This doesn't work in `ui-sref-active-eq`

**Comment by cristianmeza** [comment]
@owenXin Thank you very much, it worked perfect.

**Comment by prashant-pokhriyal** [comment]
> It seems like people are still looking at this even though the solution is in at least the most recent version!
> It is still undocumented, but just use an object (like with ng-class) and it will work.
> 
> This won't work right:
> 
> ```
> <li ui-sref-active="active">
>   <a ui-sref="admin.users">Administration Panel</a>
> </li>
> ```
> 
> This will:
> 
> ```
> <li ui-sref-active="{ 'active': 'admin' }">
>   <a ui-sref="admin.users">Administration Panel</a>
> </li>
> ```

@tgrant59, how to dynamically set the `ui-sref-active` attribute. Actually I'm having it inside ng-repeat.

```html
        <li ng-repeat="menu in top_nav_bar.menu_options" class="{{ menu.class}}"
          ui-sref="{{menu.sref}}" ui-sref-active="{'active': menu.sref + '.**'}">
          <a class="text-capitalize">{{ menu.name }}</a>
        </li>
```

But `ui-sref-active="{'active': menu.sref + '.**'}"` is not working.
