### ISSUE TITLE
Global defaults for ui-sref / ui-sref-opts

### ISSUE THREAD

**Issue by TonyWilk** [angular-ui/ui-router#1473]
It would be useful to allow setting default options for ui-sref (currently hard-coded in $StateRefDirective).
I want to set a few pages to {location:true}, the majority to false. It is a bit of a pain to always add ui-sref-opts and it is useful in dev to switch all pages to location:true.
Currently I just patch the source.

**Comment by mort3za** [comment]
+1
Because i want to change component templates dynamically everywhere in app (in templateUrl), I need to set {reload: true} for all links, otherwise previous state template will be shown.

**Comment by AmirSavand** [comment]
It's 2019 why isn't this a feature yet...
