### ISSUE TITLE
Redirect before view is loaded

### ISSUE THREAD

**Issue by georeith** [angular-ui/ui-router#1474]
My use case for this, and I am sure there are others (have seen similar posts on StackOverflow) is that I have a wizard, and you have a basket of items. The first page of the wizard gives you the option of adding your items to an existing collection or creating a new one.

However when the user opens the wizard and they have no items in their basket, I would like it to redirect straight to the create screen. 

I can do this via a `$state.go()` inside the wizards controller. However, the issue with this is that the view is loaded first and I have some asynchronous resolves in most of my wizards states. Thus you see the initial screen until the create screens resolves are resolved.

Putting the `$state.go()` in a resolve just plain does not work... how does one redirect a $state.go from within the state before the view is loaded? If we can't can we push for this?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
