### ISSUE TITLE
Assume default url equal to the state name?

### ISSUE THREAD

**Issue by dandv** [angular-ui/ui-router#1481]
While migrating an ngRoute app to ui-router, I ended up with the following routing block:

```js
$stateProvider
      .state('/', {url: '/', templateUrl: 'login.html'})
      .state('signup-email',    {templateUrl: 'signup-email.html', controller: 'SignupEmailCtrl'})
      .state('signup-name',     {templateUrl: 'signup-name.html', controller: 'SignupNameCtrl' })
      .state('signup-payment',  {templateUrl: 'payment.html', controller: 'PaymentCtrl'})
      .state('update-payment',  {templateUrl: 'payment.html', controller: 'PaymentCtrl'})
      .state('require-payment', {templateUrl: 'payment.html', controller: 'PaymentCtrl'})
      .state('profile',         {templateUrl: 'profile.html'})
      .state('book',            {templateUrl: 'map.html'})
 ```

The app wouldn't route. `ui-sref` wouldn't work, nor would entering a URL in the address bar.

While not immediately obvious, it turns out that during the conversion, I had forgotten to add the `url` field to the `.state` options object.

Would it be a good idea to assume the URL to be equal to the state name? Meteor's [iron-router](https://github.com/EventedMind/iron-router) assumes the template name to be identical to the path name.

**Comment by eddiemonge** [comment]
No. Better to be explicit in this case.

https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
