### ISSUE TITLE
No url dependency possible for embedded app

### ISSUE THREAD

**Issue by yellowandy** [angular-ui/ui-router#1500]
Hi, I'm using Angular for a chrome plugin that resides or is injected into gmail.  I would like to use the state machine functionality with the ui-router but have it ignore window.location and not modify the url when transitioning into different states.  Is this possible?  Unfortunately gmail also listens to window.location changes and/or the History API and therefore very weird things happen.  Any other thoughts.  Thanks for the help.

**Comment by eddiemonge** [comment]
Better asked on SO.
