### ISSUE TITLE
ui-sref-active doesn't work with query parameters

### ISSUE THREAD

**Issue by felquis** [angular-ui/ui-router#1513]
I'm using ui-router `0.2.10`, and I'm trying to use [ui-sref-active](https://github.com/angular-ui/ui-router/wiki/Quick-Reference#ui-sref-active) with [query parameters](https://github.com/angular-ui/ui-router/wiki/URL-Routing#query-parameters). My state is like this:

``` js
.state('profile', {
            url: '/profile/:userName?backbutton',
            views: {
                'app-view': {
                    templateUrl: 'templates/profile/profile.html',
                    controller: 'PerfilCtrl'
                }
            }
        })
```

My markup is: 

``` html
<a class="menu-item" ui-sref="profile({ userName: me.username, backbutton: true })" ui-sref-active="active">Yo</a>
```

But, when I'm in `http://localhost/profile/name?backbutton=true` the ui-sref-active isn't activated.

**Comment by PauliJP** [comment]
I wonder why this issue is closed since its very much active bug. I'm using "0.2.15" but also tried with version "1.0.3". So, having a query parameter in the route will confuse ui-sref-active directive which won't trigger. Quite annoying since I have to add the class manually each time.

**Comment by christopherthielen** [comment]
It’s closed because no method was posted to reproduce the error. Would you like to do so?

**Comment by PauliJP** [comment]
I don't have standalone working example but here is pretty much it.

// Controller 1:
this.$state.go('app.workingSites.inventoryStatusesStorageAmounts.harvestingAreaPlots', {
                            previousUrl: '/workingSites/inventoryStatuses/storageAmounts'
                        });

// Controller 2:
@Route([
   {
        name: 'app.workingSites.inventoryStatusesStorageAmounts.harvestingAreaPlots',
        url: '/plots?:previousUrl',
        ...
    }, ...
]

// Template 2:
<div class="tab-nav">
        <div class="nav-container">
            <a class="nav-item" ui-sref={{haDetails.plotsPath}} ui-sref-active="current">{{"ts.figures"|translate}}</a>
...
  </div>
</div>

<ui-view></ui-view>
