### ISSUE TITLE
problem with nested routes

### ISSUE THREAD

**Issue by abods** [angular-ui/ui-router#152]
Hello there, 
Im trying to get my nested route working but it's giving me hard time for two days now :(
one level works fine
two levels works fine 
three levels is not working!
can anybody please help me out?
Thanks in advance

``` javascript
angular.module('HMS.settings', []).
config(['$stateProvider', '$routeProvider', '$urlRouterProvider', function($stateProvider, $routeProvider, $urlRouterProvider) {
    $stateProvider
    .state('settings', {
        url: '/settings',
       template:"Settings",
        controller: function(){
            console.log('settings');
        }
    }).
    state('settings.branch', {
        url: '/{branchId:[0-9]{1,8}}',
        template:"Branch",
        controller: function(){
            console.log('branch');
        }
    }).
    state('settings.branch.prop', {
        url: '/prop',
        template:"Property",
        controller: function(){
            console.log('property');
        }
    });
}]);
```

'/settings' is working
'/settings/1234' is working
'/settings/1234/prop'  is not working, always return the prevues state 'Branch'

**Comment by koga73** [comment]
@jeme 

"content@root" helped fix an issue I was having. I spent a good bit of time googling and in my case changing 'menuContent' to "menuContent@app" did the trick. Although I will say this is very obscure and not well documented... adding "@stateName" to the end of the string and poof it works.

```javascript
.state('app.locate', {
	url: '/locate',
	views: {
		'menuContent': {
			templateUrl: 'templates/locate/locate.html',
			controller: 'Locate'
		}
	}
})
.state('app.locate.map', {
	url: '/map',
	views: {
		'menuContent@app': {
			templateUrl: 'templates/locate/locate.map.html',
			controller: 'LocateMap'
		}
	}
})
```
