### ISSUE TITLE
preventDefault() on back button $stateChangeStart causes history to be overwritten

### ISSUE THREAD

**Issue by AngusHelm** [angular-ui/ui-router#1525]
Plunker: http://plnkr.co/edit/CmuEPKjRv0KMJYywm2wQ

I've got a linear series of states, and I'm trying to popup a confirmation dialog before the user moves backwards at a certain step with preventDefault() on $stateChangeStart. Maybe browsers don't allow this, but the preventDefault not only doesn't work but modifies the history stack so that what was a linear step1->step2->step3 becomes step1->step3->step3.

**Comment by mgrahamjo** [comment]
This is related to the issue I opened today: https://github.com/angular-ui/ui-router/issues/1780

You're seeing this behavior, as I am, because ui-router checks to see if default was prevented after the redirect happens instead of before (that's where the new history entry is coming from). If they see that you called preventDefault, then they cancel the transition and call $location.url(location) to send you back to the starting location.

The fix is to check for preventDefault before executing the redirect during transitionTo.

**Comment by arcanis** [comment]
That's something that I really would like to see solved. It makes impossible to have asynchronous state validation without breaking the back history (so it doesn't work with [angular-permission](), for example).

I've think about how to workaround it, but I can't see any real way. It would be great if the core allowed it.

**Comment by mgrahamjo** [comment]
The fix for my purposes was to add in a $beforeStateChange event and listen for that instead of $stateChangeStart. I have this in the run() block of app.js:

    var transitionTo = $state.transitionTo;
    $state.transitionTo = function(to, toParams, options) {
        var from = $state.$current,
            fromParams = $state.params;

        to = to.name ? to : $state.get(to);

        if (options.notify !== false && $rootScope.$broadcast('$beforeStateChange', to, toParams, from, fromParams).defaultPrevented) {
            return $q.reject(new Error('transition prevented'));
        } else {
            return transitionTo(to, toParams, options);
        }
    };

**Comment by txikito** [comment]
Hi,

New to this group, sorry for any inconvenience...

mgrahamjo: tried your solution in a simple example, and could not get it working, it still breaks when navigating with the back button and preventing that navigation in the beforeStateChange event. Please, see this plunker to observe strange behaviour in the history stack: 

http://embed.plnkr.co/M8IL5v/

If you navigate from index to page 1, then page 2, and try to naviagate back with explorer back button, you'll see that even though the state change is prevented, the change in the history stack still occurs (at least apparently).

Apparently, the app behaves differently in IE10 and Chrome (even though both get erroneous behaviour).

Maybe I am preventing in the wrong place? Any tips are welcome, thank you.

**Comment by wwarby** [comment]
mgrahamjo's solution worked perfectly for me - thanks!

**Comment by olibaron** [comment]
I wrote a fix after some hassle with sourcefiles. https://github.com/angular-ui/ui-router/pull/2835

**Comment by olibaron** [comment]
I hope that someone can take a look at the fix.

**Comment by olibaron** [comment]
Can anyone take a look? #2835

**Comment by olibaron** [comment]
Would be great if the pull request of #2835 got accepted

**Comment by ashconnell** [comment]
@airwave-development's fix works, but the changes look dirty - can core have a look at implementing this?

**Comment by nikhilchavan** [comment]
This solution worked for me
$rootScope.$on('$stateChangeStart',
            function(event, toState, toParams, fromState, fromParams) {
                if(Condition) {
                    event.preventDefault();
                    window.alert("Hello");
                    $state.go(fromState,{reload:false});
                } 
            })

**Comment by lobo-tuerto** [comment]
A workaround I found was to reinsert the state I was coming from when the transition is stopped. Like this:

```javascript
$rootScope.$on( '$stateChangeStart', function( event, toState, toParams, fromState, fromParams ) {
  var answer = window.confirm( 'You sure?' );
  if( !answer ) {
    event.preventDefault();
    $state.go( fromState, fromParams );
  }
}
```
