### ISSUE TITLE
parent resolve overiding child resolve in child state 

### ISSUE THREAD

**Issue by programming-kid** [angular-ui/ui-router#1534]
i am facing this issue since updating to `0.2.11` parent resolve overiding child resolve in child state  

i don't know how to explain this here in words so i have created a plunkr to explain my point
 http://plnkr.co/edit/fFhas7B1Ot3QNO1HXCOq?p=preview

Here i have an `analytics` which is parent state and another is `analytics.today` child state
each state has resolve object with data  property , parent state has resolve which returns fruits and child state resolve returns junk food 

but the resolve in child state doesn't work and `$scope.dataset` in `Analytic` controller doesn't update according to this https://github.com/angular-ui/ui-router/wiki/Nested-States-%26-Nested-Views#inherited-resolved-dependencies child can overwrite parent resolves , this works in `0.2.10` but not in `0.2.11`

Am i doing something wrong here

pls help

**Comment by fyyyyy** [comment]
Having the same issue with 0.2.15

**Comment by codeofsumit** [comment]
+1 in 0.2.15

**Comment by christopherthielen** [comment]
@codeofsumit can you post a plunker? As far as I can tell this is working as designed since 0.2.12
