### ISSUE TITLE
Resolve doesn't get checked when using $state.go("")or $location.path("..")

### ISSUE THREAD

**Issue by samvloeberghs** [angular-ui/ui-router#1536]
Context: 
- overview in CMS of newsitems -> state uses resolve to query the resource for all available newsitems ( state admin.news )
- click edit (state admin.news.edit) -> use a form to edit the newsitem,
- editing on success call `$state.go("admin.news", {reload : true});` so that we go back to the "admin.news" state

angularjs: v1.3.2
ui-router: v0.2.11

Module config:

```
  .state('admin.news', {
    url: '/news',
    templateUrl: 'app/admin/news/overview.html',
    controller: 'AdminNewsCtrl',
    ncyBreadcrumb: {
      label: 'News'
    },
    resolve: {
      newsitems: function (News) {
        return News.query().$promise;
      }
    }
  })
  .state('admin.news.edit', {
    url: '/edit/:id',
    templateUrl: 'app/admin/news/add.html',
    controller: 'AdminNewsitemCtrl',
    ncyBreadcrumb: {
      label: 'Edit newsitem'
    },
    resolve: {
      newsitem: function($stateParams, News){
        return News.get({id: $stateParams.id}).$promise;
      }
    }
  })
```

Problem:
The resolve in my "admin.news" state doesn't get called using `$state.go` or `$location.path` so that the newsitems dependency gets populated/resolved with the updated newsitems.

Any suggestions here? Or is this a bug perhaps? Possible extension/improvement?

**Comment by MischokNG** [comment]
For others who didn't understand what he meant by "2nd option": The call should have been `$state.go("admin.news", {}, {reload : true})`.
