### ISSUE TITLE
$stateProvider.decorator won't run if state definition is declared before decorator.

### ISSUE THREAD

**Issue by wawyed** [angular-ui/ui-router#1544]
Because of the way state are defined, unless you define the decorator in the same angular module the state configuration is defined or you ensure that your state configuration objects are in modules that depend on the module your decorator is defined; the decorators won't get called by ui-router since those states have already been resolved.

I don't think the order of definition should affect how the decorators are run. Possibly the states should be read at run block not at config block to avoid this issue.

Plunker reproducing the issue:
http://plnkr.co/edit/C1ze61?p=preview

You can see how the decorator that it's defined in a dependant module gets called but the one that it's defined in the same module doesn't (because it was called after the state definition).

This issue is not exclusive to 0.2.12 as it was happening in 0.2.11.

**Comment by andreialecu** [comment]
I had an incredibly hard to track bug in my app because of this with ui-router-extras.

I had my modules defined like this:

```javascript
var app = angular.module('app', [  'ct.ui.router.extras.dsr',
  'ct.ui.router.extras.sticky', 'app.submodule']);
```

I was then configuring routes on app.submodule. This was not properly running the decorator, and thus $$state wouldn't be added to the states, resulting in `toState.$$state` is not a function errors.

Explicitly adding 'ct.ui.router.extras.dsr', 'ct.ui.router.extras.sticky' as deps of app.submodule solved the problem in this case.

**Comment by crhistianramirez** [comment]
I'm running into this issue but a dependency from my submodule doesn't seem to be doing the trick. My app is defined like this:

```javascript
// app.js
var app = angular.module('app', ['submodule1', 'submodule2']);

//submodule.js
var submodule = angular.module('submodule1', []);
```
Tried to update it to:
```
```javascript
// app.js
var app = angular.module('app', ['submodule1', 'submodule2']);

//submodule.js
var submodule = angular.module('submodule1', ['app']);
```
I even tried this, but this won't register any states in submodule:
```javascript
// app.js
var app = angular.module('app', [ 'submodule2']);

//submodule.js
var submodule = angular.module('submodule1', ['app']);
```

Any ideas?
