### ISSUE TITLE
Handling DOT character in params

### ISSUE THREAD

**Issue by zyadsherif** [angular-ui/ui-router#1553]
Hello I have a problem that I tried to solve by going to StackOverflow but with no luck.

I am currently trying to login with Google I've set the route this way

``` javascript
      .state('/developer/auth/google', {
        url: '/developer/auth/google?code',
        templateUrl: 'views/developer/auth/google.html',
        controller: 'DeveloperAuthGoogleCtrl',
        resolve: {
          code: function($stateParams) {
            return $stateParams.code;
          }
        }
      })
```

And this is the url that is returned 

``` http
http://localhost:9000/developer/auth/google?code=4/SgzNx1eEC2d5MhlYg5QbwWPLas-65P78SNMiAxFqUWc.UjzcCfSjj6AdoiIBeO6P2m8CFLl8kwI
```

it breaks the angular routing and gives me the typical server error 

```
Cannot GET /developer/auth/google?code=4/SgzNx1eEC2d5MhlYg5QbwWPLas-65P78SNMiAxFqUWc.UjzcCfSjj6AdoiIBeO6P2m8CFLl8kwI
```

However when I remove the dot from the returned token it works just fine

**Comment by mkhatib** [comment]
@zyadsherif any idea if you figured out how to fix this for the grunt server? I can confirm that with a . in a query param grunt is not forwarding the request to the angular app.
