### ISSUE TITLE
RFC: default active class for ui-sref

### ISSUE THREAD

**Issue by pixelnix** [angular-ui/ui-router#1566]
My templates are getting littered with repetitions of the ui-sref-active directive; if I ever want to change the active-tab CSS class name, I'll have to change it in many places.  Is it possible to create a configuration setting that can be used to assign an active-state CSS class for every element that has ui-sref directive?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by pixelnix** [comment]
I still think this is a needed RFC.

**Comment by eddiemonge** [comment]
You could always do this as a 3rd party plugin but I don't think it should be in core since a lot of links aren't going to need the active class

**Comment by nateabele** [comment]
@pixelnix Then please see #1473, which is where this is being discussed.
