### ISSUE TITLE
Disabling ui-router for a single page

### ISSUE THREAD

**Issue by pawelgut** [angular-ui/ui-router#1578]
How would I go about disabling ui-router for a single page of my app, while not changing its behavior anywhere else?

**Comment by DinisCruz** [comment]
In case it helps others, I had the exact same question and here is how I solved it (note that the wasn't a similarly titled StackOverflow question)

I basically called ```$urlRouterProvider.deferIntercept();`` which seemed to do the trick

```jade
extends index.jade
append head
  //base(href='/angular/component/')
  script.
    angular.module('TM_App')      //disable routing
           .config(
              function($stateProvider, $urlRouterProvider, $locationProvider)
                {
                  $urlRouterProvider.deferIntercept();
                });


append body
  login_form
```
