### ISSUE TITLE
Due to fix in 0.2.13 .when('/parent', '/parent/child') is not working with ui-sref

### ISSUE THREAD

**Issue by Radim-Kohler** [angular-ui/ui-router#1584]
I would say, that the ***"fix"*** in 0.2.13, related to: [**Avoid re-synchronizing from url after .transitionTo**](https://github.com/angular-ui/ui-router/releases/tag/0.2.13), change: [19715d15](https://github.com/angular-ui/ui-router/commit/19715d15e3cbfff724519e9febedd05b49c75baa)  introduced a new issue. Or at least, the `.when('/parent', '/parent/child')` is not working for `ui-sref="parent"`

### Description of the "issue"

As documented here: [How to: Set up a default/index child state](https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-set-up-a-defaultindex-child-state) *small extract*:

> Or if you want the 'parent.index' url to be non-empty, then set up a redirect in your module.config using $urlRouterProvider:

    $urlRouterProvider.when('/parent', '/parent/index');
    $stateProvider
        .state('parent', {url: '/parent', abstract: true, template: '<ui-view/>'} )
        // url '/parent/index'
        .state('parent.index', {url: '/index'} )

*NOTE: in the above cite, I replaced the `home` in url with `parent` to make it more consistent*

This has stopped working. There are plunkers:

### Examples

There are examples of the issue with different versions:

- [working with version 0.2.12](http://plnkr.co/edit/zIrYJJjw2Ze7KUM5NvGR?p=preview)
- **not** [working with version 0.2.13](http://plnkr.co/edit/Mf0UUEQdI2gaLmvoCYEu?p=preview)
- working [with rolled back version 0.2.13](http://plnkr.co/edit/6nOT3w3wKyLiTCHFpzMu?p=preview) - if commented out the fix mentioned above

this is the change applied in "roll back" of a fix [19715d15](https://github.com/angular-ui/ui-router/commit/19715d15e3cbfff724519e9febedd05b49c75baa) 0.2.13 inside of the released angular-ui-router.js

    1988   ...
    1989   // RKö - rollback of a fix
    1990   // if (ignoreUpdate) return true;
    1991    ...

### Workaround without change of 0.2.13

I described how to go around here [Angular UI-Router $urlRouterProvider .when not working when I click `<a ui-sref=“…”>`](http://stackoverflow.com/a/27131114/1679310), we need eventing:

    var onChangeConfig = ['$rootScope', '$state',
     function ($rootScope, $state) {
    
      $rootScope.$on('$stateChangeStart', function (event, toState) {    
        if (toState.name === "parent") { 
          event.preventDefault();
          $state.go('parent.index');
        }
      });
      
    }]

Maybe this is the way to go (or please, give me better). But as mentioned below, not sure about consistency...

### Question, is it an issue? or not

I can imagine that this issue would be refuesd as proper behaviour. 

BUT, is it really what we want - if this will result in **2 different** states:

    <a ui-sref="parent">  // goes to parent
    <a href="#/parent">    // goes to parent.index

**Comment by Zacharias3690** [comment]
+1

**Comment by yahyaKacem** [comment]
@christopherthielen another use case besides the one presented by @yaru22 
3 main states `home`, `profile` and `settings` like this:
![qq](https://cloud.githubusercontent.com/assets/844900/5703011/e37d87a4-9a60-11e4-8e99-ab8d32a4d150.png)

The 2nd state `profile` have 2 nested states `profile.about` and `profile.main`
![qqq](https://cloud.githubusercontent.com/assets/844900/5703013/e932b516-9a60-11e4-9310-ae475e122aa6.png)

I need that the profile state clickable on the index page loads the profile view and redirects to the default nested state which is `profile.about` here
![qqqq](https://cloud.githubusercontent.com/assets/844900/5703014/ef758566-9a60-11e4-92ba-449ed9ef0d9a.png)

Here's a working [plunker](http://plnkr.co/edit/pUidlMhKlmQf9VFWRL16?p=preview) with what I got so far, with the fix mentioned by @Radim-Kohler.

**Comment by ehacke** [comment]
:+1:

**Comment by acollard** [comment]
+1

**Comment by michalszwed** [comment]
:+1:

**Comment by goddyZhao** [comment]
+1

**Comment by summer-liu** [comment]
+1

**Comment by gabrielmaldi** [comment]
In my case the underlying issue is in fact a feature request: we need a way to specify default child states.

Given:

```js
$stateProvider
    .state("settings", {
        abstract: true,
        url: "/settings"
    })
        .state("settings.general", {
            url: "/general"
        })
        .state("settings.notifications", {
            url: "/notifications"
        })
        .state("settings.advanced", {
            url: "/advanced"
        })
```

It would be nice if we could say something like:

```js
.state("settings.general", {
    url: "/general",
    isDefaultChild: true
})
```

So that when we navigate to the abstract parent state:

```js
$state.go("settings")
```

We would get redirected (or even better: go directly) to `settings.general`.

I used to do this using `when` but it would certainly be nicer to have a "`isDefaultChild`" property on each state.

What do you think?

Thanks

**Comment by yahyaKacem** [comment]
Also one more thing to be aware of when using the fix mentioned by @Radim-Kohler is that the order of defining the data object in the state change so when using this solution the child state's data gets defined before the parent state's data so the parent overwrite the child's data (a more detailed explanation could be found in this [bug report](https://github.com/manuelmazzuola/angular-ui-router-styles/issues/5)) so if you'r using something that require you to pass data to the child state with the data attribute in the state definition object you should be aware of this bug, for me I think the best solution here is to define all the data for children in the parent state until this gets fixed.  
@gabrielmaldi that's correct this is more of a feature request then a bug, and +1 for your suggestion also other possibility is to put the default child name in the parent so instead of having `isDefaultChild: true` on a child state we'll have a `defaultChild: "childname"` on the parent state, I think both are valid solutions.

**Comment by cs-NET** [comment]
@yahyaKacem I agree that @gabrielmaldi suggestion should be in the parent state and would like to expand on that idea by adding another option `childSticky: true` so that when navigation occurs to another parent the state provider will keep the previously active child as the default instead of resetting back to the `childDefault: "childName"`.

**Comment by gabrielmaldi** [comment]
I didn't really give the proposed syntax a lot of thought, just wanted to outline the idea of default child states. Perhaps it would be better to have it in the parent state, or maybe someone comes up with a better way.

@cs-NET I think you should look into [UI-Router Extras](http://christopherthielen.github.io/ui-router-extras) which has `Sticky States` and `Deep State Redirect`.

**Comment by violet-day** [comment]
+1

**Comment by killbirds** [comment]
+1

**Comment by getvega** [comment]
@yahyaKacem like these redirections defined on the parent - much cleaner than have it outside à-la-urlRouterProvider.
One problem though: state parameters. What if you had something like:
```
$stateProvider
    .state("posts", {
        url: "/posts",
        defaultChild: "posts.post"
    })
        .state("posts.post", {
            url: "/:id"
        })
```

Which `id` would we inject in `posts.post`?

That `defaultChild` would have to also specify which params, and maybe be an invokable similar to `controllers` :

```
$stateProvider
    .state("posts", {
        url: "/posts",
        defaultChild: "posts.post",
        defaultChildParams: ["posts", function(posts) {
                return {
                        id: posts[0].id
                };
        }]
    })
```

Not so clean anymore... What do you think?

**Comment by yahyaKacem** [comment]
@getvega I'm actually doing that differently, I just inject the posts service into the run function then get the posts[0].id from there and form the parameters object in the run function then when I call `$state.go` I pass the params there:

    var onChangeConfig = ['$rootScope', '$state', 'posts', function ($rootScope, $state, posts) {
       $rootScope.$on('$stateChangeStart', function (event, toState) {
         if (toState.name === "posts") {
           event.preventDefault();
           $state.go('posts.post', {id: posts[0].id});
        }
      });
    }];

as for the `defaultChildParams` as you said not so clean maybe the defaultChild should be a string with child name in case no route params are needed and in case of params, object like `{child: 'childName', params: {id: 0}}`, where params could be a simple variable or a function that takes some injectables and returns the params object.

**Comment by acollard** [comment]
@yahyaKacem This may make your code a little more reusable. This is how we handle redirects.

```javascript
.config(['$stateProvider', '$urlRouterProvider',function($stateProvider, $urlRouterProvider) {
    $stateProvider
        .state('Account.Security', {
          url: '/security',
          redirectTo: 'Account.Security.ChangePassword' // OR
          //redirectTo: function($state){ $state.go('Account.Security.ChangePassword', { id: 'some id' }); }
        });
});

.run(['$rootScope', '$state', function($rootScope, $state){
      $rootScope.$on('$stateChangeStart', function(event, toState) {
        var redirect = toState.redirectTo;
        if (redirect) {
          event.preventDefault();
          if(angular.isFunction(redirect))
              redirect.call($state);
          else
              $state.go(redirect);
        }
      });
    }]);
```
The redirectTo function could do whatever logic you needed. Ex. get the id for the last item the user was viewing.

**Comment by gabrielmaldi** [comment]
@getvega perhaps the redirection should just forward any parameters it got (e.g. from `$state.go()`) to the child state; that'd reduce the complexity.

**Comment by christopherthielen** [comment]
@gabrielmaldi @acollard  @yahyaKacem @getvega Great conversation.  Let's move the discussion to #1235  to keep this one about url-based redirects

**Comment by christopherthielen** [comment]
For 0.2.13, here is a very simple recipe you can use to redirect to a default substate:

```
  $stateProvider.state('profile' , {
      url: "/about",
      templateUrl: "profile.html",
      redirectTo: 'profile.about'
  });

 app.run($rootScope, $state) {
    $rootScope.$on('$stateChangeStart', function(evt, to, params) {
      if (to.redirectTo) {
        evt.preventDefault();
        $state.go(to.redirectTo, params)
      }
    });
  }
```
See it in action in a fork of the above plunkr that @yahyaKacem posted:

http://plnkr.co/edit/dcN7Qra6nY9ZTOGjgCvJ?p=preview

**Comment by LordWingZero** [comment]
@acollard 

How can I gain access to resolved items in my redirectTo function? It would make sense that id need to resolve an item from the database and the state of that item could effect what params or states I need to redirect to.

**Comment by acollard** [comment]
@LordWingZero 

Accessing parent resolves is a little difficult, the process of running the resolves happens inside the $state.transitionTo and are not accessible through the event. Accessing the toStates resolves will likely not be possible at all, since redirectTo is processed before the toStates resolves are run.

But if you can use a registered service instead of a parent resolve then below will work for you.

We've changed our method above to support dependency injection. My code above has been changed to:

```javascript
module.run(['$rootScope', '$state', '$injector', function ($rootScope, $state, $injector) {
    $rootScope.$on('$stateChangeStart',function (event, toState, toParams) {
      var redirect = toState.redirectTo;
      if (redirect) {
        if (angular.isString(redirect)) {
          event.preventDefault();
          $state.go(redirect, toParams);
        }
        else {
          var newState = $injector.invoke(redirect, null, { toState: toState, toParams: toParams });
          if (newState) {
            if (angular.isString(newState)) {
              event.preventDefault();
              $state.go(newState);
            }
            else if (newState.state) {
              event.preventDefault();
              $state.go(newState.state, newState.params);
            }
          }
        }
      }
    });
```

Here is a sample of using it:
```javascript
.config(['$stateProvider', '$urlRouterProvider',function($stateProvider, $urlRouterProvider) {
    $stateProvider
        .state('Account.Security', {
          url: '/security',
          redirectTo: ['auth', function(auth){ return auth.isLicensed() ? { state: 'Account.Security.ChangePassword', params: 'some id' } : 'AccessDenied';}]
        });
});
```

The ui-router team is looking to add this functionality natively #1235. My guess is parent resolves will still  be unavailable. RedirectTo will likely occur before any resolves are run. Thoughts @christopherthielen?

**Comment by LordWingZero** [comment]
@acollard 

How would you handle redirectTo if auth.isLicensed() returned a promise instead of a bool?

**Comment by acollard** [comment]
@LordWingZero 

I'm assuming the promise from your redirectTo would still return one of the two options: the state name, or { state, param } object.

I would probably change the listener to this:

```javascript
module.run(['$rootScope', '$state', '$injector','$q', function ($rootScope, $state, $injector,$q) {
    $rootScope.$on('$stateChangeStart',function (event, toState, toParams) {
      var redirect = toState.redirectTo;
      if (redirect) {
        if (angular.isString(redirect)) {
          event.preventDefault();
          $state.go(redirect, toParams);
        }
        else {
          var newState = $injector.invoke(redirect, null, { toState: toState, toParams: toParams });
          if (newState) {
             event.preventDefault();
             $q.when(newState).then(function(result){
              if (angular.isString(result)) {
                $state.go(result);
              }
              else if (result.state) {
                $state.go(result.state, result.params);
              }
           });
          }
        }
      }
    });
```

RedirectTo would look like this:

```javascript
redirectTo: ['auth', function(auth){ return auth.isLicensed().then(function(isLoggedIn){ return isLoggedIn ? { state: 'Account.Security.ChangePassword', params: 'some id' } : 'AccessDenied';});}]
        
```

Alternatively you could use a resolve to do the redirect. We do this as well, which already supports promises and injecting resolves (parents and self).

```javascript
$stateProvider.state({ 
    name: 'home', 
    url: '/home', 
    resolve: {
      loginRequired: ['$q','$state','auth', function($q, $state, auth){
       return auth.isLoggedIn()
        .then(function(isLoggedIn){
         if(!isLoggedIn) 
          {
             $state.go('login'); 
        }
       }
      }]
    }});
```

**Comment by LordWingZero** [comment]
@acollard 

What do you think of:

    else if(angular.isFunction(newState.then)){
        event.preventDefault();
        newState.then(function(newStateData){
            $state.go(newStateData.state);
         });
    }

**Comment by acollard** [comment]
@LordWingZero 

My option above supports promises, strings, and objects. $q.when() is used to wrap all three options and return a promise. If a non-promise is wrapped then it will run then() immediately.

Checking for a promise yourself may not work well, I find it is easier to leave it up to angular.

**Comment by gwin003** [comment]
Has this been resolved yet? I implemented @christopherthielen 's solution for now, but it would be great if this got fixed.

**Comment by LordWingZero** [comment]
@gwin003 it will be fixed with the next MAJOR release of ui-router. Almost everything will be different...

**Comment by gwin003** [comment]
Thanks @LordWingZero

**Comment by alpha-cast** [comment]
@acollard 

I'm liking your solution, but I added some code to support object literals like `redirectTo: { state: "a.b", params: { id: 0 } }`. Don't think it supported that case before?

```javascript
        //Redirect to string
        } else if (redirect.state) {
          event.preventDefault();
          $state.go(redirect.state, redirect.params);
        } else {
        //Redirect to injectable
```

**Comment by christopherthielen** [comment]
This missed 0.2.14, sorry.  I'll get this into 0.2.15 ASAP

**Comment by christopherthielen** [comment]
UI-Router 1.0 preview is available: https://github.com/angular-ui/ui-router/tree/feature-1.0

**Comment by Radim-Kohler** [comment]
I admire that... you are magicians. I have to touch it, start to test... upgrade... The idea about migrating to Typescript is MUST. We are on Typescript for 1,5 year... cannot imagine JS development without it anymore. Looking forward experience with the mighty 1.0 ;)
