### ISSUE TITLE
Query params with no value

### ISSUE THREAD

**Issue by kenborge** [angular-ui/ui-router#1586]
When a state has configured query params like this
```javascript
$stateProvider.state('name', {
  url: '/url?param',
});
```
is you open the url without assigning a value to param the stateParam value is the string "true", is it possible to make this value be ```undefined```, or at least something other then a string? So that ```/url?param``` and ```/url?param=true``` would give different results?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
