### ISSUE TITLE
No error if we try to load a unknown service from a resolve

### ISSUE THREAD

**Issue by dhoko** [angular-ui/ui-router#1587]
If we try to load a state with a resolve trying to load an Unknown service, we should have an error.
Angular give us an error, so why not ui.routeur ?

Trying to load  unknown service from a controller:

```
Error: [$injector:unpr] Unknown provider: templateAppDetailLoadeProvider <- templateAppDetailLoade
http://errors.angularjs.org/1.3.0/$injector/unpr?p0=templateAppDetailLoadeProvider%20%3C-%20templateAppDetailLoade
```

Trying to load  unknown service from a resolve _ui.routeur_ :
- Nothing in the console
- No application

Ui.routeur should log this.

**Comment by xelhark** [comment]
I just lost half a day because of this. I'm pretty sure that the $stateChangeError should be used for things like errors while retrieving the resolved data, timeouts, random 404 of remote resources, etc.. this is obviously a development error, and therefore it should at least be logged in console.
