### ISSUE TITLE
Using {location: 'replace'} to go back to the previous state should pop history instead of creating two identical entries

### ISSUE THREAD

**Issue by imgx64** [angular-ui/ui-router#1590]
Here's an [example plunker](http://plnkr.co/edit/0nGm2RKX1ccv5yT74H3s?p=preview) (launch the preview in a separate window to see the history).
1. The app starts at state0. History is `/state0`.
2. Press the button to go to state1. History is `/state0`, `/state0/state1`.
3. Press the button to go to state2.  History is `/state0`, `/state0/state1`, `/state0/state1/state2`.
4. Press the `Go back` button (which uses `{location: 'replace'}`) to go back to state1. History is now `/state0`, `/state0/state1`, `/state0/state1`, with duplicate `/state0/state1`.

I think a better behavior is to remove the duplicate state from history when this happens. The current behavior breaks the browser back button (now you have to click back twice to go back to state0).

**Comment by elitastic** [comment]
+1

**Comment by jvjvjv** [comment]
+2

**Comment by nateabele** [comment]
Our current handling of history is not very sophisticated. If you feel like working on a PR, let me know. Here, I already got you started: http://plnkr.co/edit/DJH6mQUCbTFfSbdCBYUo?p=preview

**Comment by julienmartin** [comment]
Any news on this ?

**Comment by IainCole** [comment]
Should a state transition ever assume a "back" operation?

**Comment by bbaia** [comment]
+1

**Comment by Clomo** [comment]
+ 1

**Comment by netsurferj** [comment]
:+1:
