### ISSUE TITLE
Query parameter with value "{foo}"

### ISSUE THREAD

**Issue by adrianhara** [angular-ui/ui-router#1593]
I'm experiencing some strange behavior when a query parameter has a value which is actually a json (url encoded) object. In this case the state which is navigated to and has such a parameter loads fine, but any subsequent navigation to other states doesn't work. More precisely I can see that the controllerProvider is invoked for the destination state first, but then the controllerProvider is invoked for the source state (the one with the {} query parameter value) and the net result is that I can't navigate "away" from the source state.

Also, this problem only manifests itself on Firefox. On Chrome and IE it works perfectly fine! (making it that much more difficult to debug, because firebug is slow as hell)

Are there any restrictions about using such query parameter values? I remember some discussion about adding support for complex parameters, maybe this was now implemented and we're somehow breaking it by using json objects in the querystring?

Thanks!

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
