### ISSUE TITLE
Don't watch ui-sref

### ISSUE THREAD

**Issue by sn0rcha** [angular-ui/ui-router#1599]
Hey guys,

I've been going through and optimizing a large angular project that uses ui.router. I've noticed that each time I use an ui-sref, it creates a watcher. Is there any way to generate a url using ui-sref that doesn't add a watcher?. In long lists it's creating a lot of watchers :(

**Comment by awerlang** [comment]
Wouldn't one-time binding provide greater value? 

e.g.

```
{{::item.property}}
```

In my use cases it made a huge difference. Although I agree that doesn't make a lot of sense to watch on sref, I believe there should be other places where you should look first.

**Comment by sn0rcha** [comment]
I've been using the one time binding, but sometimes you have to a lot of data with links off to an entity, and pagination is not really an option, so a lot watchers are made on the sref.

**Comment by awerlang** [comment]
Well, you could consider coding a directive then. That would be the way to go.

**Comment by mwarren2** [comment]
In my multi-language app, which I am still trying to get to play reasonably with ui-router, I need ui-sref to update the href when the I switch languages. 
Which incidentally at the moment it is not doing, for some reason.

**Comment by awerlang** [comment]
@mwarren2 have you tried sharing your issue http://stackoverflow.com/questions/ask?tags=angularjs,angular-ui-router

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by pbassut** [comment]
Just wanted to give a tip to searchers here: Look out cause the problem might not be ui-sref but the argument for it, instead. Like ```ui-sref="viewArticle({article_id: article.id})"```. In that case, the watcher is placed on ```article.id```.

And as @awerlang pointed out, this is resolved using bind-once ```ui-sref="viewArticle({article_id: ::article.id})"```

**Comment by mkelley82** [comment]
Or in my case, for a ui-sref generated inside an ng-repeat:
`<a ui-sref="default.districtdetails(::{districtid: item.Id})">{{::item.Name}}</a>`

**Comment by leonardobazico** [comment]
+1

**Comment by stefankatic** [comment]
+1

**Comment by stefankatic** [comment]
None of these methods above worked for me, so I created a small directive, as I have about 3k links (infinite scroll).
`    function aLinkDirective($state, $parse) {
        return {
            restrict: 'A',
            link: function (scope, element, attrs){
                var ref = parseStateRef(attrs.aLink, $state.current.name);
                element.attr('href', $state.href(ref.state, $parse(ref.paramExpr)()));
            }
        };
        function parseStateRef(ref, current) {
            var preparsed = ref.match(/^\s*({[^}]*})\s*$/), parsed;
            if (preparsed) ref = current + '(' + preparsed[1] + ')';
            parsed = ref.replace(/\n/g, " ").match(/^([^(]+?)\s*(\((.*)\))?$/);
            if (!parsed || parsed.length !== 4) throw new Error("Invalid state ref '" + ref + "'");
            return {state: parsed[1], paramExpr: parsed[3] || null};
        }
    }`
Usage: `< a directive-name="state.with({id: {{::item.id}}})" >{{::item.name}}</a>`
Hope it helps ;)

**Comment by jziggas** [comment]
+1
