### ISSUE TITLE
ui-sref disable the link until fully resolved

### ISSUE THREAD

**Issue by Ulterior** [angular-ui/ui-router#1600]
Wouldnt it be great to have a directive like ui-sref-lock, which would prevent the user to click the link until href is fully resolved by url builder?

OR maybe its a bug to allow the user to click an unresolved sref link at all?

Please have a look at the issue and solution here: http://stackoverflow.com/questions/27197596/angular-ui-sref-href-resolve-completion-callback

**Comment by nateabele** [comment]
This is out of scope. If you have data that your template depends on and should not render without, it should be in a resolve. If you need to load your data in some alternative way, feel free to put it in a custom module and we can publish it here.
