### ISSUE TITLE
Multiple siblings - load only one sibling and leave the other at the state he was

### ISSUE THREAD

**Issue by seinavco** [angular-ui/ui-router#1602]
Hi,

I have a parent which has two sub views (2 siblings).

I want to do 'state.go' and at that state change only one ui-view of sibling and the other sibling will have to stay at the same state he was before the 'state.go'.

Is it possible?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
