### ISSUE TITLE
QueryParameter crashes ui-router

### ISSUE THREAD

**Issue by Jakobovski** [angular-ui/ui-router#1608]
See the plunkr 

http://plnkr.co/edit/8mV1H5bBVJsFlh0MCwPh?p=preview

This query parameter will crash the application if it is used in a `ui-sref` or if it is in the url and the `$stateParams.messageId` is `$watched`

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
