### ISSUE TITLE
reload option in transitionTo reloads all states in a hierarchy. Unable to reload just the current nested state.

### ISSUE THREAD

**Issue by gfreeau** [angular-ui/ui-router#1612]
When using the `reload` option in `state.transitionTo` on a nested state, all of its parents are also reloaded. You should be able to reload only the current state.

My use case is a nested state with params. In some cases I have the same state and params and I simply wish to reload it (to refresh data from the server), however using the `reload` option also reloads it's parents, which resets templates and directives in parent states.

One workaround I found is to have some kind of random param in the nested state which is changed every time you wish to reload/refresh the current state. UI-Router seems to handle the case fine when a state has unique params every time, it just cannot reload a state with the exact same params since it believes there is no work to do.

Here is what happens:

* Nested state, no changes to params =  UI router does nothing, since it assumes it is already on the correct state
* Nested state, with an additional unique param assigned to a random value to uniquely identify every transitionTo call = works correctly, able to "refresh" nested states without reloading parents
* using the `reload` option, refreshes the nested state correctly but also reloads all parents

I can setup a plunk, I just wanted to see if this is worthwhile first.

**Comment by Astray-git** [comment]
I have a similar problem with the reload. I use resolves to update data in my state's controller.(when it's an active state)
I use the params work-around above, it does reload the resolves, but doesn't reinitialize the controller, the injected resolve is not updated. I also tried transition with options 
`{ reload: true, inherit: false, notify: true }` which didn't work neither.

**Comment by deanapeterson** [comment]
The ability to set the descendant depth of the reload is an excellent idea.

**Comment by oriweingart** [comment]
We implemented this feature for a private project.
PR was created: https://github.com/angular-ui/ui-router/pull/1795
Welcome to try it..

**Comment by christopherthielen** [comment]
I think this makes sense from a high level.  I'd to omit the second reloadState parameter, and overload the existing reload parameter. 

- ` { reload: true } `// reloads all,
- `{ reload: 'foo.bar' } // reloads top.bar, and any children
- `{ reload: stateObj } // reloads state found in stateObj, and any children

Squash your commits and set your commit message to match the contributor guidelines.  If @nateabele concurs, I think we'll merge this in.

**Comment by oriweingart** [comment]
Created a new PR according to your comments: https://github.com/angular-ui/ui-router/pull/1809

**Comment by nateabele** [comment]
Fixed in #1809.

**Comment by shyamal890** [comment]
+1 Was looking this since long back. Thank you.

**Comment by DumboJet** [comment]
Can `reload` accept a list of states to reload?
Or it is too much to ask?

{ reload: ['foo.bar','foo.bar.car.jar'] }

**Comment by ProLoser** [comment]
@dumbojet that doesn't make any sense since reloading a parent state reloads the descendents
