### ISSUE TITLE
Preload routes like instantclick.js

### ISSUE THREAD

**Issue by mrsweaters** [angular-ui/ui-router#1615]
Hey folks!

I am attempting to integrate the concepts behind Instantclick.js (http://instantclick.io/) into ui-router. This would allow a user to optionally configure hover events and touchstart events to preload controller dependencies. 

I've got it working (somewhat) but would love some feedback and help to make it stable:
https://github.com/mrsweaters/ui-router/commit/5f1df14ccf619ff66a35d3709ca81cd7c8c74340

Right now I'm seeing issues where `$state` locals are getting undefined and the `to` route doesn't properly load.

Todo:
- [ ] Fix undefined locals bug on `to.navigable`
- [ ] Make this feature opt-in with attribute
- [ ] Write tests
- [ ] Use $timeout to determine intent

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
