### ISSUE TITLE
Query parameter is ignored when page is loaded

### ISSUE THREAD

**Issue by tomgeek** [angular-ui/ui-router#1617]
Hi,
I have a problem with routing based on query parameter. If I visit my second state (`contests`) directly (#/contests?contestMasterId=1) it displays template for first state.

Steps to reproduce:
1) open [plnkr](http://plnkr.co/edit/OdG9fBsD5q1E5eipUbfJ?p=preview) in separate window (small blue icon in preview tab) (open developer tools so you can see log messages)
2) click `contest master 1` link (URL changes to #/contests?contestMasterId=1)
3) reload the page
4) notice that wrong content is displayed (`masters` state was selected)

I can overcome this behaviour by adding slash in front of question mark, but it doesn't fit how I structure URLs in my app.

It's quite possible that I'm doing something wrong but [documentation](https://github.com/angular-ui/ui-router/wiki/URL-Routing#query-parameters) says this should work so it seems like a bug to me.

I'm new to AJS and UIR so I'm sorry if I'm doing something wrong.
Thanks for any input.
Have a nice day

For quick overview this is how my $stateProvider is configured (plnkr is above)
```
$stateProvider
    .state("masters", {
        url: "/contests",
        template: "<a ui-sref='contests({contestMasterId: 1})'>contest master 1</a>"
    })
    .state("contests", {
        url: "/contests?contestMasterId",// works if changed to /contests/?contestMasterId
        template: "contests for master, <a ui-sref='contestDetail({contestId: 2})'>contest 2</a>"
    })
    .state("contestDetail", {
        url: "/contests/{contestId}",
        template: "contest detail"
    });
```

**Comment by nateabele** [comment]
In order for this to work your states need to be in a parent-child relationship, like so:

```javascript
    $stateProvider
            .state("masters", {
                url: "/contests",
                template: "<a ui-sref='masters.contests({contestMasterId: 1})'>contest master 1</a><br /><ui-view></ui-view>"
            })
            .state("masters.contests", {
                url: "?contestMasterId",// works if changed to /contests/?contestMasterId
                template: "contests for master, <a ui-sref='master.contestDetail({contestId: 2})'>contest 2</a>"
            })
            .state("masters.contestDetail", {
                url: "/{contestId}",
                template: "contest detail"
            });
```
