### ISSUE TITLE
Cannot Resolve State?

### ISSUE THREAD

**Issue by BobbieBarker** [angular-ui/ui-router#1618]
I'm on ui-router 0.2.13, and angularJS 1.3.6,  My code was working yesterday, and now I'm unable to navigate to a specific state. 
This is the error I receive:
Error: Could not resolve 'dashboard' from state 'sign-in'

This is the offending code:

    'use strict';

    angular.module('ebrokerTools.dashboard')
      .config(function ($stateProvider){
    $stateProvider
      .state('dashboard', {
        url: '/dashboard',
        templateUrl: 'app/dashboard/html/dashboard.html',
        controller: 'dashBoardCtrl',
        resolve: {
          currentAuth: function(fireBaseAuth){
            return fireBaseAuth.auth().$requireAuth();
          },
          currentUser: function($fireBaseUser, Session){
           return $fireBaseUser.user(Session.id).$asObject().$loaded().then(function(data){
                return data;
             });
          },
          userList: function($fireBaseUser){
            return $fireBaseUser.userList().$asArray().$loaded().then(function(data){
                return data;
             });
          },
          taskList: function($fireBaseTasks){
             return $fireBaseTasks.taskList().$asArray().$loaded().then(function(data){
                return data;
             });
          }
        }
      });
    });

I notice that when I console log $state.get() that this particular state isn't in the list of state objects anymore. I haven't made any changes to this file in days, I'm more or less at a loss as to what is going on here. I've never really had a problem with ui-router before.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
