### ISSUE TITLE
URL not populated with default value for query param on page loading

### ISSUE THREAD

**Issue by dtritus** [angular-ui/ui-router#1619]
I've state with query param and default value for it. When page loaded without query param, default value not added to URL. But if I go to other state, and then back to initial, param added to URL.
See plnkr for example: http://plnkr.co/edit/Fad6NrgGpefIXZ4U6rhe

**Comment by nateabele** [comment]
It is not intended for the default value to auto-populate the URL, only for the value to be supplied to your code if there is no value in the URL.
