### ISSUE TITLE
$stateChangeStart event is not providing the options

### ISSUE THREAD

**Issue by nielsboogaard** [angular-ui/ui-router#1620]
To check whether the user is authorized for a certain state, i implemented an interceptor which listens to the $stateChangeStart event. After checking the rights, I resume the transition with the following code:

```
$rootScope.$on('$stateChangeStart', function (event, toState, toParams, fromState, fromParams) {
    //Auth stuff checking here
    $state.go(toState, toParams, {notify: false}).then(() => {
        $rootScope.$broadcast('$stateChangeSuccess', toState, toParams, fromState, fromParams);
    });
});
```

I notify the stateChangeSucces by hand to prevent endless loops here. The problem is that state.go calls which provides optional options (like reload:true) are not provided by the $stateChangeStart event. This prevents resuming the started transition correctly (because the provided options as originally passed to the state.go method are lost).

Alternative would be to provide a method like $state.resume() which can be used to resume a prevented state transition which takes into account the passed params and options.

**Comment by mark-veenstra** [comment]
+1

**Comment by gustavohenke** [comment]
+1.
They should be passed to `$stateChangeSuccess` too.

**Comment by flyskyko** [comment]
+1

**Comment by SebastianM** [comment]
+1

**Comment by nielsboogaard** [comment]
Any updates on this from the angular-ui team? Is there a plan to solve this in a newer version?

**Comment by abhinandankothari** [comment]
Any Updates on this ? I am facing the same issue

**Comment by artmees** [comment]
+1

**Comment by JosephBuchma** [comment]
+1

**Comment by SinisterLight** [comment]
+1

**Comment by qpitlove** [comment]
:+1:

**Comment by nateabele** [comment]
The upcoming release will have new APIs that obviate this.

**Comment by karser** [comment]
+1

**Comment by abhinandankothari** [comment]
is this fixed in 0.2.15 ?

**Comment by asperling** [comment]
:+1:

**Comment by christopherthielen** [comment]
I think we can add `options` as a fifth (!!!) parameter to the $stateChange events.  Who has time to make a PR?

**Comment by mrtomrichy** [comment]
Any news on this?

**Comment by thomas3577** [comment]
+1

**Comment by jeroenlorrentop** [comment]
+1

**Comment by mambax** [comment]
+1

**Comment by nateabele** [comment]
> Any news on this?

@mrtomrichy https://github.com/angular-ui/ui-router/issues/1620#issuecomment-114477207

**Comment by zamrokk** [comment]
:+1:
