### ISSUE TITLE
UrlMatcher#type() is not being propagated to all children in hierarchy

### ISSUE THREAD

**Issue by v12** [angular-ui/ui-router#1621]
Hi,

Basically, the issue is about types created in root module configuration section using `urlMatcherFactoryProvider` are not accessible to any module that is dependency of modules current module depends on.

```
Root module (MyApp)
|__ Submodule (MyApp.module)
     |__ Another submodule (MyApp.module.submodule)
     |__ One more submodule (MyApp.module.submodule2)
|__ Yet another submodule (MyApp.module2)
```

So, if we define custom type for `UrlMatcher` in `MyApp` and then use it in state URLs in `MyApp`, `MyApp.module` and `MyApp.module2` - that works fine. But, trying to use it in `MyApp.module.submodule` or `MyApp.module.submodule`, it doesn't work at all for some reason. 

Defining this custom type in `MyApp.module` makes it work, however, it is not a solution at all because only first level child states inherit this custom type and there could many levels in hierarchy, what will obviously lead to stupid copy-paste and decreased code quality.

Here is the [Plunker](http://plnkr.co/edit/iOevXjaEb3uXuIQAQZqt?p=preview) demonstrating the issue.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
