### ISSUE TITLE
Chrome on iOS: When navigating between states, page title is replaced with URL

### ISSUE THREAD

**Issue by pixelnix** [angular-ui/ui-router#1622]
The easiest way to replicate this is to open the sample app in Chrome on iOS, then click Contacts.  The tab title "home - ui.router" is replaced with the current URL.
http://angular-ui.github.io/ui-router/sample

I was reticent to enter this as an issue here, but I don't see the same behavior in the sample app for ngRoute (http://angular.github.io/angular-phonecat/step-7).  This makes me think it's not, or at least not *only*, a bug in Chrome.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
