### ISSUE TITLE
$stateParams crash on a son template? 

### ISSUE THREAD

**Issue by tintorimatteo** [angular-ui/ui-router#1624]
I use ui-router and states with URL parameter, but when I want to access to a next template, $stateParams makes the template invisible, even if the URL is correct. 
Here's my code:

 $stateProvider
.state('elemento', {
        url: "/elemento/:idInfografica",
        templateUrl: "templates/elemento.html",
        controller: "CtrlInfografiche"
    }).state('infografiche', {
        url: "/infografiche",
        templateUrl: "templates/infografiche.html",
        controller: "CtrlInfografiche"
    })

     <div class="list card" style="margin-top:50px" ng-repeat="singular in infografiche">
    <div class="item item-body">
        <img class="full-image" ng-src="singular.allegatoCopertina">
        <p>
            <a ui-sref="elemento({idInfografica: singular.id})" >{{singular.name}}</a> 
        </p>
        <p>{{singular.description}}</p>
    </div>
...
</div>

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
