### ISSUE TITLE
$stateParams are empty in my resolve when it is instantiated as a service

### ISSUE THREAD

**Issue by tysoncadenhead** [angular-ui/ui-router#1625]
I am running into an interesting issue. When I pass in a function to the resolve object, like this:

```
$stateProvider
   .state('my-state', {
       url: '/:someId/route-name',
       controller: 'MyController',
       resolve: {
            resolverName: MyResolver
       }
   });

function MyResolver ($stateParams) {
    console.log($stateParams); // { someId: ... }
}
```

I am able to get access to the `$stateParams` like I would expect. However, when my resolve function is a service and I instantiate it as a string like this:

```
$stateProvider
   .state('my-state', {
       url: '/:someId/route-name',
       controller: 'MyController',
       resolve: {
            resolverName: 'MyResolver'
       }
   });

angular
    .module('myModue')
    .service('MyResolver', MyResolver)

function MyResolver ($stateParams) {
    console.log($stateParams); // {}
}
```

The `$stateParams` are an empty object. Is this a known issue, or am I possibly doing something wrong?

Thanks!

**Comment by jptannus** [comment]
If you add the dependency of the service using the array notation like this:
`angular.module('myModue').service('MyResolver', ['$statePatams', MyResolver])`
Works?

**Comment by nateabele** [comment]
@corps, thanks for the cogent explanation. Maybe it should be added to the FAQ...
