### ISSUE TITLE
Use template of parent state?

### ISSUE THREAD

**Issue by Busata** [angular-ui/ui-router#1628]
Hello,

Is it possible with ui-router to tell a child state to use the template of it's parent-state and not create one itself? For example:

.state('client', {
abstract: true
url: '/client/:client_id'
resolve: { client : function() { .. gets client .. })
.state('client.contract', {
abstract: true,
url: '/contract/:contract_id',
resolve: { contract: function(client) { ... gets contract with client id ... }
);
.state('client.contract.planning') {
url: '/planning',
templateUrl': '...'
}

The code above will not work without specifying a template (<ui-view) for client & client.contract,which produces code like:
```html
<body ui-view>
<ui-view>
<ui-view>
<div containing planning template>
</div>
</ui-view>
</ui-view>
</body>
```
Though I want  the planning to appear in the original <ui-view> as:
```html
<body ui-view>
<div containing planning template>
</body>
```
I find it strange that you do have abstract states, but force templates upon them.

**Comment by nateabele** [comment]
Setting `template: "<ui-view></ui-view>" in the parent (abstract) state fixes it.
