### ISSUE TITLE
Dead documentation link

### ISSUE THREAD

**Issue by lee-40square** [angular-ui/ui-router#1629]
The following links don't load anything:

http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$stateParams

**Comment by JobaDiniz** [comment]
+1

**Comment by nateabele** [comment]
Where is this linked?

**Comment by JobaDiniz** [comment]
http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$state has *Dependencies* and 4 of those links are dead...

**Comment by nateabele** [comment]
Well, 3 of them are in Angular core, and unfortunately I don't know if ng-docs is smart enough to handle cross-project dependencies.
