### ISSUE TITLE
Dynamically created template URL from $stateParams ?

### ISSUE THREAD

**Issue by iomico** [angular-ui/ui-router#163]
How can I _dynamically_ create template URL from **$stateParams** like shown below:

``` javascript
.state('contacts.detail', {
  url: '/{contactId}',
  views: {
    'menu': {
        templateUrlProvider:
            [ '$stateParams',
                 function ($stateParams){
                    return '/partials/contacts.detail' + $stateParams.contactId + '.html';
            }]
    }
  }
})
```

**Comment by t1mmen** [comment]
Am I right in assuming that this won't work with minification? My state (below) works well before minification, but attempts to load ```https://myapp/stateParams,function%20(a)%7Breturn%22templates/connection/%22+a.provider+%22.html%22%7D``` in production

```js

$stateProvider
// .... many states...
  .state('profile.connection.details', {
    url: '/:provider',
    templateUrl: function (stateParams){
        return 'templates/connection/' + stateParams.provider + '.html';
    },
    controller: 'ConnectionDetailsCtrl',
    controllerAs: 'cd',
  })
```

I'm using the latest ui-router & Angular 1.3.10.

Thanks for any assistance!

**Comment by alexandercastillo** [comment]
Hi @t1mmen 

Have your tried with the array syntax?
Also, don't forget the dollar sign ($stateParams)

```js
$stateProvider
// .... many states...
  .state('profile.connection.details', {
    url: '/:provider',
    templateUrl: ['$stateParams', function ($stateParams) {
        return 'templates/connection/' + stateParams.provider + '.html';
    }],
    controller: 'ConnectionDetailsCtrl',
    controllerAs: 'cd',
  })
```

**Comment by t1mmen** [comment]
Doh! Thanks for the suggestions @alexandercastillo. Turns out I made a blunder in my build script, so it wasn't working _because_ it compiled to the array syntax.

The minified code looks like this (after I reformated & indented for readability)

```js
.state("profile.connection.details",{
    url:"/:provider",
    templateUrl:function(a){
        return"templates/connection/"+a.provider+".html"
    },
    controller:"ConnectionDetailsCtrl",
    controllerAs:"cd"
})
```

Thanks for helping me realize my mistake!

**Comment by anarCHEist** [comment]
its my solution 
```
	url: '/product/edit:productId', 
	templateUrl: function($stateParams){
		return 'edit_product.php?edit='+ $stateParams.productId +'';
	},
```

**Comment by zealmurapa** [comment]
what am I missing here guys?

	  .state('app.single', {
		  url: "/playlists/:playlistId",
		  views: {
			  "details": {
				  controller: 'PlaylistCtrl',
				  templateUrl: function($stateParams) {
					  url = 'templates/' + $stateParams.playlistId + '.html'
					  return url;
				  },
			  }
		  }
	  })

**Comment by guilloche** [comment]
You forget 
'var' before 'url = 'templates/' + ...

**Comment by AitorAlejandro** [comment]
and is there a way to give a url to the templateProvider via ajax call? I'm trying but unsuccessfully.

**Comment by manar-mk** [comment]
Hi, I've got a typescript error: `property 'provider' does not exist on type 'IStateParamsService'`. How can I avoid this?

**Comment by pufffff** [comment]
$stateProvider.state("home", {
      url: "/",
      controller: 'LandingPageCtrl',
      templateUrl: function($rootScope) {
        return $rootScope.site_folder + "/views/landingpage.html";
      }
    })

hi guys, what am I missing ?

**Comment by rerodrigues** [comment]
```js
$stateProvider.state('internal', {
    url: '/subir/:page',
    controller: 'InternalController',
    templateUrl: ['$stateParams', function ($stateParams) {
        console.log('fired');
        return 'views/_' + $stateParams.page + '.html';
    }],
});
```
Hi,
I'm trying this but it's not even firing the function. There is something wrong or ui-router simply doesn't support it anymore?

ps. It works with the non-array notation.

angular: 1.6.2
angular-ui-router: 0.4.2

Thanks in advance!
