### ISSUE TITLE
0.2.13 creates double hash (##) on certain sub state links on IE9

### ISSUE THREAD

**Issue by larsgk** [angular-ui/ui-router#1631]
0.2.11 works.  We have not made a simple test reproducing the problem yet but it seems that links to substates (xx.yy.zz) generate links with double ## - breaking the link on IE9

**Comment by nateabele** [comment]
Plunkr?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
