### ISSUE TITLE
ui-sref does not generate href attribute if url is not provided

### ISSUE THREAD

**Issue by ilovett** [angular-ui/ui-router#1635]
Similarl to #1293 -- I saw that this was fixed in `0.2.13` 

However, I've noticed that `href` is not generated unless explicitly setting url to an empty string `url: ''`

Shouldn't `href` also be generated if `url` is undefined / not provided?  If not why?

      .state('settings', {
        templateUrl: 'views/settings.html',
        controller: 'SettingsCtrl'
      })

**Comment by ProLoser** [comment]
Because if you refresh the page it won't arrive at this state.
