### ISSUE TITLE
$stateChangeStart fired twice when interacting with confirm

### ISSUE THREAD

**Issue by bytenel** [angular-ui/ui-router#1637]
So I have some events setup around $stateChangeStart and $stateChangeSuccess to determine whether a page is loading or not. On certain sections of my application I have a confirm that appears to allow users to confirm they want to move on. These events work fine if the user hits ok. If they hit cancel another $stateChangeStart event is fired and my loading screen comes up again.

from my controller(s):
<pre>
<code>
$scope.$on('$stateChangeStart', function (event, next, state) {
    if( !_.include(next.name, 'new-report') && !_.include(next.name, 'complete')) {
      if (!confirm("Are you sure? Unsubmitted data will be lost.")) {
        event.preventDefault();
      }
    }
  });

  $scope.$on('$stateChangeSuccess', function (event, next, current) {
    vm.loading = false;
  });

    $scope.$on('$stateChangeStart', function () {
      vm.loading = true;
    });
</code>
</pre>

**Comment by nateabele** [comment]
Please post a Plunkr that demonstrates the issue.

**Comment by bytenel** [comment]
I'm not involved with the company the project was for anymore and no longer have access to the source code. Sorry!
