### ISSUE TITLE
Inconsistent API in state params that are functions

### ISSUE THREAD

**Issue by kvcrawford** [angular-ui/ui-router#1641]
When a state has a default parameter that is a function, the function is invoked, and the param is set to the return value of that function.

However, if you pass a function as a param like so

```js
$state.go('foobar', {
  myParam: function () { console.log('hello'); }
});
```

That function does not get invoked and its return assigned as the param value. Rather, it is available as a function on the `$stateParams` object. This is a powerful way to provide a state with a callback (see https://github.com/angular-ui/ui-router/issues/1640) when navigating to it from a certain context.

Both use-cases are valuable, but API consistency is desirable, and I wanted to confirm that it's not a bug. Perhaps an option could be added to the param config object?

Another possibility is to require an IIFE if you want a function that returns a value for setting on the param:

```
$stateProvider.state('foobar', {
  params: {
    myParam: (function(){ return 'foo'; })()
  }
```

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
