### ISSUE TITLE
Param slash decode problem

### ISSUE THREAD

**Issue by fundon** [angular-ui/ui-router#1642]
The image `id` is string type and mybe contains `/`,
likes `dockerboard/dockerboard:latest` and will be encoded in my template.
When clicking a link, will be redirected to root.
How to disable decode `#/images/dockerboard%2Fdockerboard%3Alatest` in `$location` or `$state`?

``` js
     $stateProvider.
        state('images', {
          url: '/images',
          templateUrl: '/js/modules/images/views/images.tpl.html'
        })
        .state('imageitem', {
          url: '/images/{id}',
          templateUrl: '/js/modules/images/views/image.tpl.html'
        });
...

    .filter('escape', ['$window', function ($window) {
      return function (url) {
        return $window.encodeURIComponent(url);
      }
    }])

```

``` jade
 a(ng-href="#/images/{{ container.Image | escape }}") {{ container.Image }}
```

**Comment by vlatkodrljin** [comment]
Same problem

**Comment by ptrussart** [comment]
Hello,

I have the same problem here. Did you find a workaround ?

**Comment by fundon** [comment]
See https://github.com/dockerboard/bluewhale/blob/master/src/js/filters/filters.js#L13

**Comment by ptrussart** [comment]
Thank you for the workaround.

Just to understand : is this encode issue a bug or do we need from now to encode the "/" character ?

**Comment by christopherthielen** [comment]
1.0 addresses this by introducing the `raw` flag for parameters that should not be encoded

```js
        .state('imageitem', {
          url: '/images/{id}',
          params: { id: { raw: true } },
          templateUrl: '/js/modules/images/views/image.tpl.html'
        });
```
