### ISSUE TITLE
$stateParams and $state.params discrepancy

### ISSUE THREAD

**Issue by adambuczynski** [angular-ui/ui-router#1644]
See the following plunkr: http://plnkr.co/edit/4lNF02CEcwXDOQDPfoMd?p=preview

When navigating to the specified child state (either via $state.go or via ui-sref, both are demonstrated) there is a visible discrepancy between the contents of $stateParams and $state.params.

The $stateParams object lacks some parameters, which are present in $state.params.

This can't be the intended behavior, since the child state is loaded and it should contain the child state specific parameter in $stateParams which is given.

**Comment by dubcanada** [comment]
Same as #136

**Comment by ilanbiala** [comment]
There is a new duplicate of this #2076.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by adambuczynski** [comment]
This is still affecting me in the latest 0.2.15 with angular 1.4.3

http://plnkr.co/edit/4lNF02CEcwXDOQDPfoMd?p=preview
