### ISSUE TITLE
ui-routes doesn't update parent views.

### ISSUE THREAD

**Issue by DumboJet** [angular-ui/ui-router#1646]
I have a huge issue updating the views of the parent states when the user clicks on a ui-sref link.

There is a description with details and my temporary solution here:

http://stackoverflow.com/questions/27486201/ui-router-renders-template-before-state-changes/27500463#27500463

The title is misleading, but if you read the whole question you will understand what goes on.

Any suggestions/ideas on what might be wrong?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
