### ISSUE TITLE
Pass complex object to ui-sref params

### ISSUE THREAD

**Issue by umbrella-anton-kramazin** [angular-ui/ui-router#1647]
I need build url: /list?filter[status]=1&filter[type]=2
I do:
link:
`<a ui-sref="list({filter: {status: 1, type:2}})">List</a>`

state:
`.state('list', {
            url:        '/list?filter',
            …
        })`

I get:
/list?filter=[object Object]

Demo: http://plnkr.co/edit/wV3ieKyc5WGnjqw42p7y?p=preview
How I can fix it?

**Comment by nateabele** [comment]
This is now supported through typed parameters.

**Comment by stduolc** [comment]
@nateabele Is there any example or document link for this typed parameters?
