### ISSUE TITLE
When injecting $stateParams into a function inside of onEnter the object contains previous state's params

### ISSUE THREAD

**Issue by antch** [angular-ui/ui-router#1649]
The ui-router lifecycle is exhibiting a behavior that, in my opinion, is unintuitive.  Inside of an `onEnter` function, if you try to inject `$stateParams` into a function you get the parameters from the previous state -- this is the same behavior you see if you try to inject `$stateParams` into a ui-bootstrap modal `resolve` function.  Wrapping the invocation in a `$timeout` will defer the execution until the state changes, but I don't think this should be necessary.  For example:

      onEnter: function($injector, $timeout) {
        
        $injector.invoke(function($stateParams){
          console.log('$stateParams WITHOUT $timeout:', $stateParams); //get "LAST" state's params
        });
        
        $timeout(function() {
          $injector.invoke(function($stateParams){
            console.log('$stateParams WITH $timeout:', $stateParams); //get "THIS" state's params
          });
        });
      }

I also created a [minimal Plunker](http://plnkr.co/edit/9cWHYJLIUrj8yNiqnLXy?p=preview) that exhibits this behavior.

I believe that the expected behavior would be when injecting `$stateParams` from within an `onEnter` callback, it would resolve to the params of the state being entered.  Is this something that can be accommodated?  The `$timeout` workaround seems kludgy to me and I'd rather not rely on it.

For background, I'm creating this issue as a follow-on to [my StackOverflow question](http://stackoverflow.com/questions/27576560/why-does-timeout-affect-how-stateparams-is-resolved-in-a-ui-bootstrap-modal).

**Comment by jturmel** [comment]
Are you talking about $stateParams from a parent state? If so I'd think we'd want access to those.

**Comment by antch** [comment]
No, the same behavior occurs with non-nested sibling states.

**Comment by jturmel** [comment]
Sorry I misread what you were describing, yes, I would think you should see the current state being entered into.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
