### ISSUE TITLE
Optional URL path params broken in 0.2.13.

### ISSUE THREAD

**Issue by resistdesign** [angular-ui/ui-router#1652]
In 0.2.13, setting a state url to `/somepath/{id}` and giving the `id` param a default value no longer works properly when navigating to `/somepath` on it's own. (It doesn't even try to load a template at all.) However, this used to work just fine in 0.2.11 and would load your view as if you had navigated to `/somepath/defaultval` directly.

**Comment by eddiemonge** [comment]
You need to add `squash: true`
