### ISSUE TITLE
Basic Routing Problem

### ISSUE THREAD

**Issue by jrsakizci** [angular-ui/ui-router#1658]
Hi.
I have
var myApp = angular.module("navmenu", ["ui.router"]);
myApp.config(function($stateProvider) {
  $stateProvider
  .state('root', {
    templateUrl: '/admin/template.html',
  })
    .state('root.sidebar', {
      url:'/admin/index.html',
      views: {
        'sidebar': {
          templateUrl: '/admin/sidebar.html',
        },
        'content': {
          templateUrl: '/admin/content.html',
        }
      }
  });
})
This code and it works perfectly. But it sets url to -> admin/#/admin/index.html (etc)
when im trying to do this;

var myApp = angular.module("navmenu", ["ui.router"]);
myApp.config(function($stateProvider) {
  $stateProvider
  .state('root', {
    url: '/',
    templateUrl: '/template.html',
  })
    .state('root.sidebar', {
      url:'/index.html',
      views: {
        'sidebar': {
          templateUrl: '/sidebar.html',
        },
        'content': {
          templateUrl: /content.html',
        }
      }
  });
})

This isnt work a bit! i edit index.html to -> / and it get template.html correctly but not views. And: $urlRouteProvider doesnt work either. Whats my problem in here? Its really simple code but it just doesnt work :/

**Comment by nateabele** [comment]
Please see StackOverflow for support questions, thanks. http://bit.ly/UIR-SOF
