### ISSUE TITLE
TypeError: Cannot read property 'insertBefore' of null

### ISSUE THREAD

**Issue by gailane** [angular-ui/ui-router#1661]
Received this error and tried a million things to get it to go away. Must be using JQLIte, not jQuery.

When you have a ui-view element with default content in it that contains an ng-repeat directive, the TypeError is thrown when changing to the child states. I was able to solve this problem by creating an abstract state for the parent and putting the default content into a new child state, with the parent's URL. That one took some real troubleshooting.

Plunkr here: http://plnkr.co/edit/6fSNgaifgVlAraHrPBgX?p=preview

**Comment by stryju** [comment]
confirmed - simplified example with `ng-if` and a temporary "workaround":
http://plnkr.co/edit/SB2Ic2YVgZTsIagjY0fP?p=preview

basically, the problem is that the controller is attaching to the content, that's being replaced with the "new" ui-view

the aforementioned "workaround" is a small variable that is state-dependant.

just uncomment the line 38:
```js
      // ctrl.showDefault = ( state.name === 'main' );
```

the error will be gone.

**Comment by gregbty** [comment]
Is this going to be corrected soon? I have this issue with any list view that has child edit states.

**Comment by gregbty** [comment]
This happens for me when I have a variable in both scopes and that variable is used in the template.

**Comment by wry791** [comment]
I am also running into this, will this be fixed?

**Comment by epelc** [comment]
I had this issue a while ago but it just came up again. I found out it only happens if `ng-repeat` is an immediate child of your `ui-view`. 

For example the following layout would cause this issue
```
<div ui-view>
   <div ng-repeat="...">
       <!-- content    -->
    </div>
</div>
```

But it works perfectly fine if you surround your `ng-repeat` with a parent div that doesn't have a `ui-view`

ie the following works fine
```
<div ui-view>
    <div>
        <div ng-repeat="...">
            <!-- content    -->
        </div>
    </div>
</div>
```

**Comment by ergo** [comment]
Yeah, I've got this with ng-if directive, and what @epelc suggested also fixed this for me, would be good if there is some explanation why this happens (i'm using angular 1.4-beta-6).

**Comment by gregbty** [comment]
After looking into it some more I think it has to be with scope inheritance. If you namespace your controller using controllerAs the problem goes away.

**Comment by sesamechicken** [comment]
I had a similar problem with using an ng-if on an ng-include to conditionally load UI assets if the user was/wasn't logged in. I ultimately went with this approach and the errors disappeared:

`<div ng-include src="variable ? 'partials/header.html' : null"></div>`

This answer explained what was happening, and a comment in it provided the above solution/workaround. http://stackoverflow.com/a/25674022

>Both ng-if and ng-include are queued up to execute, and ng-if has a higher priority so it runs first. If the expression is false, then ng-if removes the element, but doesn't cancel the ng-include from running. Since the element is removed, ng-include is unable to inject the loaded content into the element and you get this error.

**Comment by nateabele** [comment]
You'll likely run into the same thing whenever you try to combine multiple transcluded directives in an equivalent hierarchy. Please report the the issue against Angular core. If there's a fix that UI-Router can provide to mitigate it, I have yet to figure out what that would be and, as simple workarounds exist, it's not really a priority. As always, PRs are welcome.

**Comment by sesamechicken** [comment]
@nateabele Apologies, I'm not using angular-ui sp this would be a core issue.
Thanks!
