### ISSUE TITLE
Angular 1.3.8 runs on example with error

### ISSUE THREAD

**Issue by ipeisong** [angular-ui/ui-router#1662]
https://docs.angularjs.org/error/$interpolate/interr?p0=%20%20%20%20%20%20$state%20%3D%20%7B%7B$state.current.name%7D%7D%0A%20%20%20%20%20%20$stateParams%20%3D%20%7B%7B$stateParams%7D%7D%0A%20%20%20%20%20%20$state%20full%20url%20%3D%20%7B%7B%20$state.$current.url.source%20%7D%7D%0A%20%20%20%20&p1=TypeError:%20Converting%20circular%20structure%20to%20JSON

Can't interpolate:       $state = {{$state.current.name}}
      $stateParams = {{$stateParams}}
      $state full url = {{ $state.$current.url.source }}
    
TypeError: Converting circular structure to JSON
Seems the url source cannot be serialised.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
