### ISSUE TITLE
problem with state url:'/'

### ISSUE THREAD

**Issue by hamitogluh** [angular-ui/ui-router#1663]
Whenever I click on faq page link, it works as expected. However, when I clicked on home page link, state transition occurs but url does not change at first time. If I click on it again, the url changes.

html code
`<a ui-sref='home'>Home</a>`
`<a ui-sref='faq'>FAQ</a>`

javascript code
`$stateProvider.state('home', {`
        `url: '/',`
       ` views: {`
           ` 'mainContent': {`
                `templateUrl: 'app/home/home.html'`
           ` }`
       ` }`
  `  }).state('faq', {`
        `url: '/faq',`
       ` views: {`
           ` 'mainContent': {`
                `templateUrl: 'app/faq/faq.html'`
            `}`
        `}`
   ` });`

* State-based routing for AngularJS
 * @version v0.2.12

**Comment by Alos** [comment]
I have the exact same issue.

**Comment by nateabele** [comment]
Please post a plunkr that demonstrates the issue. Thanks.

**Comment by Zhouzi** [comment]
Try leaving the url parameter empty:

```
$stateProvider.state('home', {
    url: '',
    views: {
        'mainContent': {
            templateUrl: 'app/home/home.html'
        }
    }
});
```

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
