### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by ranjeetpatel77** [angular-ui/ui-router#1669]
Hello sir,

TypeError: Cannot read property 'active' of null
    at c:\bitcot\pencilblue\include\service\entities\section_service.js:211:38
    at c:\bitcot\pencilblue\node_modules\node-promise\promise.js:159:27
    at process._tickDomainCallback (node.js:463:13)

What's going wrong to get the error ....
Please help me.

**Comment by nateabele** [comment]
http://bit.ly/UIR-SOF
