### ISSUE TITLE
Regex parameters do not respect case insensitivity

### ISSUE THREAD

**Issue by MohammadYounes** [angular-ui/ui-router#1671]
I tried the `$urlMatcherFactoryProvider` config:

```javascript
app.config(function ($urlMatcherFactoryProvider) {
  $urlMatcherFactoryProvider.caseInsensitive(true);
  $urlMatcherFactoryProvider.strictMode(false);
});
```
http://plnkr.co/edit/zdHlfVHBpnwDD3W5iUOW?p=preview

I traced this down to [this line](https://github.com/angular-ui/ui-router/blob/master/src/urlMatcherFactory.js#L122),  not sure if this is the intended behavior or it should be like this:

 ```javascript
type = $$UMFP.type(regexp || "string") || inherit($$UMFP.type("string"), { pattern: new RegExp(regexp, config.caseInsensitive ? 'i' : undefined) });
 ```

Thanks.

**Comment by MohammadYounes** [comment]
Should I send a PR?

**Comment by nateabele** [comment]
> Should I send a PR?

Yes.

Good find, thanks.

**Comment by nateabele** [comment]
Be sure to check out and follow the contributor guidelines when submitting, thanks again.

**Comment by MohammadYounes** [comment]
Already submitted #1713 

Hope it conforms to the guidelines!
