### ISSUE TITLE
Force immediate url update when ui-sref clicked

### ISSUE THREAD

**Issue by alexstanbury** [angular-ui/ui-router#1675]
My situation is that I want the address bar in iOS 8 safari to expand (if it's been shrunk due to vertical scrolling) immediately when clicking on a ui-sref, as it does when clicking on an <a> tag that is only using href. I understand that with ui-sref the url is updated once the state has loaded including it's resolves, but for my use case I need it to update the url immediately, as I don't want this address bar expansion to happen when the state and view have loaded as it currently does, it looks wrong. 

Is there a way I can do this aside from removing all ui-sref and using plain href instead?

Thanks

**Comment by christopherthielen** [comment]
ui-sref uses $state.go.  $state.go does not update the url until the transition has completed, right before firing `$stateChangeSuccess`.

https://github.com/angular-ui/ui-router/blob/master/src/state.js#L1088

There is currently no support for your use case.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
