### ISSUE TITLE
Url decorator partially broken starting with v0.2.12

### ISSUE THREAD

**Issue by SirDarquan** [angular-ui/ui-router#1677]
When I initially started using ui-router, I'd define the url for each state using the UrlMatcherFactoryProvider so that I could set the caseInsensitivity to false. What I didn't realize was that this required absolute urls, so I went on a quest to find what I think is a better solution. 

__Decorators For The Win__

After perusing the API docs for awhile I stumbled upon the decorators of the $stateProvider. After a little trial and error, I came up with the following code:
```javascript
	$stateProvider.decorator('url', function (state, parent) {
		var matcher = parent(state)
		if (matcher && !state.abstract) {
			matcher = matcher.concat("", { caseInsensitive: true });
		}
		return matcher;
	});
```
For the uninitiated, this callback will receive all registered states. The 'parent' parameter is a function that will retrieve the UrlMatcher for the state passed in. The callback should return a UrlMatcher. Since some state don't have urls and/or are abstract, I weed those out. Once I have a proper UrlMatcher, I use the concat function to make it case-insensitive.

This code works for all states in v0.2.11 but the versions  up to 0.2.13 (as of this writing) causes any state with a url containing a queryString parameter to fail validating the ParamSet. Here's the offending code in ui-router:
```javascript
    $$validates: function $$validate(paramValues) {
      var result = true, isOptional, val, param, self = this;

      forEach(this.$$keys(), function(key) {
        param = self[key];
        val = paramValues[key];
        isOptional = !val && param.isOptional;
        result = result && (isOptional || !!param.type.is(val));
      });
      return result;
    },
```
The parameter paramValues has the keys I pass in but self doesn't. I understand that self is supposed to be the url ParamSet but I don't get why it doesn't pick up the parameters I placed in the state url property. I also understand that something may have gotten more strict in how things are done and now my url decorator callback may not be fully compliant. Either way, I'd like to know if this is a bug or what needs to be done to fix my decorator callback.

Thanks

**Comment by christopherthielen** [comment]
can you use `$urlMatcherFactory.caseInsensitive(true)` to make all your urls case insensitive?

http://angular-ui.github.io/ui-router/site/#/api/ui.router.util.$urlMatcherFactory

**Comment by SirDarquan** [comment]
Well I presumed that I have to do that in the .config() section which doesn't allow factories. I did notice that it is also available as $urlMatcherFactoryProvider and I tried using that but it didn't seem to have an effect, which is why I fell back on using the decorators.

I went back and tried it again and `$urlMatcherFactory.caseInsensitive(true)` did not work for v0.2.11 but I also then tried it for v0.2.13 and it does work.... partially. I don't know if you can do anything about it, but if you use a base tag and change the casing in it, the case insensitivity doesn't work. But I consider that extremely minor. Sorry for bothering you, keep up the good work! :)

**Comment by christopherthielen** [comment]
> I don't know if you can do anything about it, but if you use a base tag and change the casing in it, the case insensitivity doesn't work.

Can you give me some more details?

**Comment by SirDarquan** [comment]
Well I looked at the crash details and ui-router doesn't seem to be involved. Basically, I have an application in a folder instead of on the root of the domain. Let's say it's /MyApp and I have the base tag in the HTML set to href="/MyApp/". If I go to /myApp instead of /MyApp, the site doesn't load because of an exception: TypeError: Cannot read property 'replace' of undefined. The stack track is all angular.js so I believe ui-router is totally absolved of this issue.
