### ISSUE TITLE
Set view default

### ISSUE THREAD

**Issue by ga12ru12** [angular-ui/ui-router#1678]
I see the demo of ui-router in here (http://plnkr.co/edit/u18KQc?p=preview). And my problem is when I go to '/route1', i want the list of route1 will be display. I don't want to use the $state.go('route1.list'). 
Any one can help me? Thanks.

**Comment by zlegein** [comment]
doesn't sound like you need a nested route then, how about this: http://plnkr.co/edit/E8c0a3hfTDpLTvcjROSM?p=preview

**Comment by christopherthielen** [comment]
http://bit.ly/UIR-SOF
