### ISSUE TITLE
how to initialize all ui-view controller at angularjs bootstrap stage

### ISSUE THREAD

**Issue by reidlai** [angular-ui/ui-router#1679]
Dear All,

I have three state - A, A.B and A.B.C. 

State A defined three ui-view - view1, view2, view3 - and all views have templateUrl (no controller) definition, say template1.html, template2.html, template3.html.

At State A.B, I defined view name "view3@A" to load template4.html and associate controller called controller1.

At State A.B.C, I defined view name "view3@A to load template5.html and associate controller called controller2.

Up to this moment, everything works fine same as what i expected.

However, when I try to emit event from controller1 to controller 2 using $emit or $broadcast.  Controller2 cannot receive the event even how hard i tried.  During debugging process, I found that controller2 was not initiated until I go from state A.B to A.B.C.  Is there anyway, I can initiate all controller defined in ui-router during angularjs bootstrap stage?  Thanks for your advice.

Best Regards,

Reid Lai

**Comment by christopherthielen** [comment]
Controllers are a "view concern".  Therefore, they are not instantiated until the view is.  The view is not instantiated into the DOM until after the state they belong to has been activated.

You should use parameters and resolves to pass data between states, then to your controllers.

For more information, ask on StackOverflow http://bit.ly/UIR-SOF
