### ISSUE TITLE
Create an effective .npmignore

### ISSUE THREAD

**Issue by gustavohenke** [angular-ui/ui-router#1683]
Hey,
I just installed UI Router thru NPM, and it gave me a heavy (6.7 MB), bloated package:

![](http://i.imgur.com/mzmmbhn.png)

When I opened the `.npmignore`, I found that its contents aren't effective at all:

```
# master only
build
site

# common
node_modules
bower_components
.DS_Store
*~

# webstorm files
.idea
```

I suggest adding _at least_ the following directories to the list:
* config
* lib
* sample
* test

I wanted to send a PR with this modifications, but I couldn't find anywhere in this repo a file called `.npmignore`.

Guys, can we do this? It will make everyone's CI builds faster!

**Comment by christopherthielen** [comment]
thanks for the heads up

**Comment by ilanbiala** [comment]
@gustavohenke why don't you submit a PR and @christopherthielen will review it so that they can work on other more complicated things for 0.2.14?

**Comment by gustavohenke** [comment]
@ilanbiala Yes sir! See #1701

**Comment by americoneto1** [comment]
Could you please include bower_components folder in .npmignore? I had install today and it comes with almost 80 MB in DefinitelyTyped folder

**Comment by nateabele** [comment]
@americoneto1 Sure. It'll probably happen faster if you submit a PR. :smile:

**Comment by americoneto1** [comment]
Nice! I'll do it!
