### ISSUE TITLE
URL Param int interpretation broken

### ISSUE THREAD

**Issue by maruf89** [angular-ui/ui-router#1684]
I wish I had the time to throw a plunkr together but I have a deadline and no time.

Anyways based of [the documentation](https://github.com/angular-ui/ui-router/wiki/URL-Routing#url-parameters) using the URL: `example.com/events/2405` and this config, it will go the route, run the controller, but redirect to the app's $urlRouterProvider.otherwise('/404')

```coffee
{
    name: 'single'
    url: '/events/{eID:int}'      // <-- redirecting to apps $urlRouterProvider.otherwise
    controller: 'EventSingleCtrl as Event'
    templateUrl: 'views/events/single/Template'
}
```

if I change the url to `/events/:eID` or `/events/{eID:[0-9]+}` then it works fine without redirecting

Using **v0.2.10**

**Comment by zlegein** [comment]
@maruf89 Im not sure what the problem is here. if you use `/events/:eID` with that url you will have a `$stateParam.eID` available to you in the controller

**Comment by christopherthielen** [comment]
@maruf89 did you try with latest? 0.2.13 has the only working typed parameters code

**Comment by nateabele** [comment]
Closing due to no provided plunk and no response. Please open a new issue with a plunk and we'll get it looked at, thanks.
