### ISSUE TITLE
Cannot click on links when using Recaptcha

### ISSUE THREAD

**Issue by mirzali** [angular-ui/ui-router#1685]
Hello,

I'm using the latest Recaptcha plugin. The problem is that I cannot click on links (with ui-sref directive), after I have successfully entered the captcha code. Before entering the code the clicks work all right.

I have found the cause (well maybe) of this to be in the 

https://github.com/angular-ui/ui-router/blob/c3d543aae43d4600512520a0d70723ac31f2cb62/release/angular-ui-router.js#L4065

line 4065

where the $timeout that would run the state transition is canceled

```js

      element.bind("click", function(e) {
        var button = e.which || e.button;
        if ( !(button > 1 || e.ctrlKey || e.metaKey || e.shiftKey || element.attr('target')) ) {
          // HACK: This is to allow ng-clicks to be processed before the transition is initiated:
          var transition = $timeout(function() {
            $state.go(ref.state, params, options);
          });
          e.preventDefault();

          // if the state has no URL, ignore one preventDefault from the <a> directive.
          var ignorePreventDefaultCount = isAnchor && !newHref ? 1: 0;
          e.preventDefault = function() {
            if (ignorePreventDefaultCount-- <= 0)
              $timeout.cancel(transition);
          };
        }
      });
    }
```
So I wonder what is Recaptcha doing that might be causing this kind of behaviour

**Comment by mirzali** [comment]
After reviewing this function a little I think I've found a way to get it working for me. I don't have any combos of ui-sref + ng-click (and I really can't image why would someone?) so I removed the code that deals with it. 

```js
      element.bind("click", function(e) {
        var button = e.which || e.button;
        if ( !(button > 1 || e.ctrlKey || e.metaKey || e.shiftKey || element.attr('target')) ) {
          e.preventDefault();
          $state.go(ref.state, params, options);
        }
      });
```

Anyhow, I would really like if someone that is well introduced to this part of ui-router to review it, just in case I might have missed on some aspect or ui-router operation.

**Comment by christopherthielen** [comment]
seems fine to me, if it works for you.

What is calling event.preventDefault() on the click event?

**Comment by mirzali** [comment]
I'm not really sure why it is there.

**Comment by svi3c** [comment]
Is this going to be merged into master? We have the same issue.
