### ISSUE TITLE
Is it possible to one of the mutiple named views seperately ?

### ISSUE THREAD

**Issue by xiulunlin** [angular-ui/ui-router#1686]
I have checked issues list and I found that it is called orthogonal views but I failed to get a effective solution .

\<div ui-view="viewA">\</div>
\<div ui-view="viewB">\</div>

if viewA has M child views while viewB has N ones then it seems I have to define M*N states which will bring too many states . I just want to change them seperately like frames .

**Comment by mallowigi** [comment]
Why M * N? Rather M + N no ? Maybe the best at this point would be to not use the router but directives instead?

**Comment by christopherthielen** [comment]
@xiulunlin try ui-router-extras http://christopherthielen.github.io/ui-router-extras/#/sticky
