### ISSUE TITLE
Clear $stateParams

### ISSUE THREAD

**Issue by seinavco** [angular-ui/ui-router#1687]
Hello,

Is there a way to clear $stateparams?

When routing between states some the $stateParams stays there and causing me a big mess in the app. I there a way to clear stateParams?

Thanks!

**Comment by christopherthielen** [comment]
Hi, better to ask this sort of question on SOF

http://bit.ly/UIR-SOF

**Comment by srlmproductions** [comment]
You can clear the values by setting the key to `undefined` when you transition.

For example, to transition to the current state but clear the `time` parameter you can do:
```
$state.go('.', {time: undefined} );
```

**Comment by seinavco** [comment]
Thanks!
