### ISSUE TITLE
Squash on ui sref

### ISSUE THREAD

**Issue by noamokman** [angular-ui/ui-router#1688]
When referencing to a state with a parameter set to squash,
the default of ui sref is to create a link with a trailing slash

the state provider:
```js
    $stateProvider
      .state('signup', {
        url: '/signup/:data',
        params: {data: {value: null, squash: true}},
        templateUrl: 'app/signup/signup.html',
        controller: 'SignupCtrl'
      });
```

Both of these options doesn't work:
```html
<!-- href="/signup/" is being added instead of "/signup"-->
<button type="button" ui-sref="signup({data:null})"></button>
<button type="button" ui-sref="signup()"></button>
```

**Comment by christopherthielen** [comment]
That is how it is supposed to behave.  

> The parameter's default value is omitted from the URL. *If the parameter is preceeded and followed by slashes in the state's url declaration, then one of those slashes are omitted*. This can allow for cleaner looking URLs.

I understand the desire for `/signup`, but we currently do not support generating that href in that manner.

**Comment by van-nguyen** [comment]
+1 thanks!
