### ISSUE TITLE
Can't create simple application with 2 layouts, (nested ui-view)

### ISSUE THREAD

**Issue by liadlivnat** [angular-ui/ui-router#1689]
I have the following scenario:

Mobile application written in Angular.

1. Login page that has not  special layout - simple page.
2. home page that have a special layout including header and footer.
3. internal pages that also include header and footer.

So i want to be able to use two layouts 1- blank 2- with header and footer.

on my index.html page i added:
```
    <div ui-view class="app-content"></div>
```
This is how my state provider looks like:
```
        .state('layout', {
            templateUrl: 'partials/mobile/layout.html',
            reloadOnSearch: false
        })
        .state('homepage', {
            url: "/",
            templateUrl: 'partials/mobile/home.html',
            parent: 'layout',
        })
        .state('internal-page', {
            url: "/internal/:id",
            templateUrl: 'partials/mobile/internal.html',
            parent: 'layout',
            controller:'InternalController',
        })     
        .state('login', {
            url: "/login",
            templateUrl: 'partials/mobile/login.html',
            controller: 'MobileLoginController',

        })
```
in layout.html i have used the same ui-view again:

 
```
    <!-- App Body -->
        <div class="app-body" ng-class="{loading: loading}">
            <div class="app-content">
                <div ui-view></div>
            </div>
        </div>
```
The result is duplicate views, i get the same view twice when i'm using layouts.

**The question:**
Can someone explain what am i doing wrong, and how can i nested the ui-view one inside another without duplicate the page?

**Comment by christopherthielen** [comment]
dupe
