### ISSUE TITLE
Code runs two times

### ISSUE THREAD

**Issue by piernik** [angular-ui/ui-router#1690]
I've got ui-router 0.2.13 and angular 1.3.8
Problem is that code in ui-view runs two times. When I move the code outside ui-view everything runs only one time.
In that code I'm loading extra data with ajax so it's important to me that it runs only one time.

**Comment by christopherthielen** [comment]
Not nearly enough information to even guess.  Show us in a plunk.  Ask on stackoverflow.

http://bit.ly/UIR-Plunk http://bit.ly/URI-SOF

**Comment by octopepper** [comment]
Running on the same configuration as Piernik.

My problem seems to be the same.

For example :8ball: 
<blockquote>
<pre>
.state('example', {
  url: '/example/{id:int}',
  controller: 'ExampleCtrl as ctrl',
  templateUrl: 'components/example/views/example-index.html',
  resolve:{
    ...
  },
})
.state('example.photos', {
    url : '/photos',
    templateUrl: 'components/example/views/example-photos.html',
    controller: 'ExamplePhotosCtrl',
    resolve:{},
  })
</pre>
</blockquote>

I have a view example example/:id with some tabs /photos, /videos etc.

This parent view <code>example-index.html</code> contains <code> ui-view </code> </pre>element.

On each <code>ui-sref</code> or <code>$state.go</code> action, the controller of the child view is multiplied by 2.

On the first call of <code>example/1</code>,  when I click on the photo tab, there is one call of the api
On switch <code>example/2</code> : on photo tab click, the web-service is called 2 times.
On switch <code>example/3</code> : on photo tab click, the web-service is called 4 times.
etc..

Any ideas ?

**Comment by christopherthielen** [comment]
Not nearly enough information to even guess. Show us in a plunk. Ask on stackoverflow.

http://bit.ly/UIR-Plunk http://bit.ly/URI-SOF

**Comment by Nighthawk14** [comment]
Same behaviour, why the function inside the controller is running third time (check your console) ? I got the function launched eleven times on a more complex app.
 
http://plnkr.co/edit/Md0GPJ?p=preview

**Comment by atungare** [comment]
Would love to figure this out - I'm seeing the same behavior with angular 1.3.10 and ui-router 0.2.13.

I'll put this in a plunk when I get a chance.

**Comment by atungare** [comment]
Antoine, did you resolve this issue?  I don't see your comment on the
page.  Would love to figure this out - I'm seeing the same behavior w/
angular 1.3.10 and ui-router 0.2.13.

I'll put this in a plunk when I get a chance.

**Comment by christopherthielen** [comment]
Anotine's plunk demonstrated multiple $digest cycles, not the controller being doubly invoked.  

Once I see a plunk I'll get to the bottom of this.

**Comment by atungare** [comment]
I'm seeing this behavior when navigating to a nested state on page refresh - do you know how to simulate that in a plunk?  I've configured this one, and would like to navigate to a child state using the url: http://plnkr.co/edit/nuL1zhpuQpXoVgxvbZCf?p=preview

**Comment by christopherthielen** [comment]
@atungare 
In the plunkr preview pane, there are two buttons. One refreshes, the other (blue one) opens in a new window.  Click that.   

Once it's in a new window, copy the URL to clipboard, open another new window, and paste the URL.

It will look something like this: http://run.plnkr.co/Wfq0W1ggFNdjNAvx/#/home but those run URLs are temporary and will go away after some timeout.

**Comment by atungare** [comment]
Thanks so much for your help!  Here we go: http://run.plnkr.co/zZI2uDbqXo32Xrye/#/home/3/foo/3

If you wait a second for the timeout, you will see that the $stateChangeStart event gets called twice.

**Comment by Nighthawk14** [comment]
Hi ! I removed my comment because we figured out that it wasn't a bug coming from ui-router but multiple $digest cycle from angular itself :).

**Comment by christopherthielen** [comment]
@atungare Thanks for making a plunk.  You are explicitly cancelling the first transition, then transitioning a second time after 5 seconds, so this is expected behavior. Unless I'm missing something...

```
  $rootScope.$on('$stateChangeStart', function(evt, to, toP, from, fromP){
    
    if ((! to.data.authenticate) || (isAuthenticated)) {
      return;
    }
    
    evt.preventDefault();
    
    $timeout(function(){
      isAuthenticated = true;
    }, 5000).then(function(){
      $state.go(to.name, toP);
    });
    
  });
  ```

**Comment by atungare** [comment]
@christopherthielen Thanks, yes I guess that is what I'm doing!  I was initially running this code without the evt.preventDefault(), which causes the resolve blocks in parent states to run multiple times as multiplte state transitions are triggered.

But I'm now having the same error that I believe @Nighthawk14 was experiencing where there is an infinite digest occurring until the authentication promise is resolved for navigation to '/' : http://run.plnkr.co/EXmcBoHSVAkmmO33/

I would love to figure out how to debug that - perhaps this issue is the wrong venue for this discussion.

**Comment by christopherthielen** [comment]
@atungare you cannot link to run.plunkr.co  you'll have to link to the edit url

**Comment by atungare** [comment]
@christopherthielen 

Here you go: http://plnkr.co/edit/nuL1zhpuQpXoVgxvbZCf?p=preview

**Comment by christopherthielen** [comment]
@atungare basically, your code doesn't have any states that it can resolve to correctly.

- App bootstraps, there is no state loaded

**Comment by christopherthielen** [comment]
@atungare basically, your code doesn't have any states that it can resolve to correctly.

- App bootstraps, there is no state loaded
- The URL is synced with states
  - "" matches no state, so it invokes otherwise() function
  - The url is updated to "/home/1"
- The state requires authentication, so default is prevented
- The previous url is restored  ("")
- 50 GO TO 10

You should create a state that doesn't require authentication, and redirect the user there instead of simply cancelling the transition

**Comment by ProLoser** [comment]
@christopherthielen, I think you need a $stateChangeError label for people, or some ginormous h1 message saying please add the error handler first. Hell it should be justabout everywhere in the docs.

**Comment by christopherthielen** [comment]
@ProLoser hehe, yes indeed.  I've been considering a debug flag to $stateProvider which would log the events.
