### ISSUE TITLE
State catch all makes two calls for templaeUrl & resolve

### ISSUE THREAD

**Issue by Hubrus** [angular-ui/ui-router#1693]
Navigating to a state that is described by an url like: '/someAction/{id}/*params', makes two calls to the server for template and also the resolve statement is executed twice. 

LE: Apparently, also $locationChangeStart is fired twice, as mentioned here: https://github.com/angular-ui/ui-router/issues/733#issuecomment-50160768

**Comment by Hubrus** [comment]
Apparently the issue was present in 0.2.11. Update to 0.2.13 solved the problem.

**Comment by fvezzoso** [comment]
This is still happening to me in 0.2.15, anyone else?
