### ISSUE TITLE
Duplicate ui-view when using parenting

### ISSUE THREAD

**Issue by liadlivnat** [angular-ui/ui-router#1694]
I have the following scenario:

Mobile application written in Angular.

Login page that has not special layout - simple page.
home page that have a special layout including header and footer.
internal pages that also include header and footer.
So i want to be able to use two layouts 1- blank 2- with header and footer.

on my index.html page i added:

```
<div ui-view class="app-content"></div>
```

This is how my state provider looks like:
```
    .state('layout', {
        templateUrl: 'partials/mobile/layout.html',
        reloadOnSearch: false
    })
    .state('homepage', {
        url: "/",
        templateUrl: 'partials/mobile/home.html',
        parent: 'layout',
    })
    .state('internal-page', {
        url: "/internal/:id",
        templateUrl: 'partials/mobile/internal.html',
        parent: 'layout',
        controller:'InternalController',
    })     
    .state('login', {
        url: "/login",
        templateUrl: 'partials/mobile/login.html',
        controller: 'MobileLoginController',

    })
```
in layout.html i have used the same ui-view again:

```
<!-- App Body -->
    <div class="app-body" ng-class="{loading: loading}">
        <div class="app-content">
            <div ui-view></div>
        </div>
    </div>
```
The result is duplicate views, i get the same view twice when i'm using layouts.

The question: Can someone explain what am i doing wrong, and how can i nested the ui-view one inside another without duplicate the page?

This is the view after running the application:

![capture](https://cloud.githubusercontent.com/assets/2083527/5788566/52270002-9e46-11e4-9079-92fd17be3f80.PNG)

**Comment by christopherthielen** [comment]
can you reproduce this on the desktop and put it in a plunkr?

Nothing you have pasted looks wrong, at first glance.

**Comment by liadlivnat** [comment]
It's not reproduce with plunker, i suspect that it related to the fact i
used http://mobileangularui.com/

but i couldn't figure it out, if anyone can assume what cause it i will try
anything

Liad Livnat.

W: http://liadlivnat.com
IN: http://linkedin.com/in/liadl
F:https://www.facebook.com/liad.livnat
T: 054-4302040

**Comment by christopherthielen** [comment]
You might want to
 - ask on StackOverflow
 - post on the mobileangularui forums (if there are any)
 - figure out how to reproduce in plunkr
 - create an easily reproducible mobielangularui test case, with easy 1. 2. 3. instructions on how to deploy and test.  If you do this, I can at least tell you if ui-router is to blame.

**Comment by dancancro** [comment]
I'm having a problem that might be the same thing.  Navigating to some of my routes works fine, but when I go to other ones it is creating an additional section ui-view element and putting the content of the new route there.  I made [this screencast](https://www.youtube.com/watch?v=fr2MybRFC7E) to show you what's happening.

The problem seems to be in the updateView function of the ui-view directive wherein it creates a new clone node but does not set the original equal to it, so you end up with two of them.  However, for the properly functioning routes this assignment is happening.

**Comment by Joel-Kornbluh** [comment]
I'm experiencing the same issue, navigating to some states causes the ui-view to duplicate itself, afterwards when navigating to another state, the first ui-view element updates itself with the new controller/view, the other ui-views seem to be dead and are stuck with the old controller/view.

It only happens on specific routes and it only happened (or maybe i only realized it) after upgrading to angular 1.4.0-rc.1

There is only one unnamed ui-view in my application and all views are registered on the '@' view.

**Comment by eddiemonge** [comment]
unless someone can gives us a plnkr to work off of (if this is still happening), we can't really do much.
