### ISSUE TITLE
controllers and child states

### ISSUE THREAD

**Issue by bealtine** [angular-ui/ui-router#1696]
I think I'm misunderstanding the ideas here.
I'm trying to understand why the controller in the child state doesn't run here, it's in most of the docs it's shown as the "right" way so I must be doing something wrong...

This is a "chopped" to bits demo
http://plnkr.co/edit/cE9fs86yxUFRpCazBE8r?p=preview

I'm sure it's me or my misunderstanding:)

Thanks guys

**Comment by christopherthielen** [comment]
I'm answering this only because you provided a plunk (thanks).  Normally I would point you to stackoverflow ( http://bit.ly/UIR-SOF ) for help questions

you need another ui-view for your home.index view to go into.  Add it on the 'home' state.
```
              template: '<ui-view/>'
```
