### ISSUE TITLE
$location.search() not working

### ISSUE THREAD

**Issue by geminiyellow** [angular-ui/ui-router#1700]
hello every one.
i use angular-ui-router in my project. and i want to get search string from url,
like this: http://localhost:8080/?code=123456&state=auth#/api/oauth2_authorize
in app.config, i set:

    $stateProvider.state("oauth2_authorize", {
                url: "/api/oauth2_authorize?code&state",
                template: "",
                controller: function($location) {
                           var search = $location.search();
                }
            })

i think the search will be { code : 123456; state:auth} but no.
i try to change the url to : http://localhost:8080/#/api/oauth2_authorize?code=123456&state=auth
and it work. 

somebody could tell me why? the html5mode is false.
i check the angularjs's document, and $location's sample show that, i can get the search string from both url.
and i try to use $urlRouterProvider , but it still empty.

what can i do?

**Comment by christopherthielen** [comment]
This is a general help question, please ask on stackoverflow.
http://bit.ly/UIR-SOF

**Comment by geminiyellow** [comment]
got it, @christopherthielen thank you.

**Comment by anatoly314** [comment]
@geminiyellow , hi! Have you found solution for your issue?

**Comment by geminiyellow** [comment]
@anatoly314 i think i found it. and that is cause by my wrong way.  but i not use `ng` now, and i forgot what is my solution. so if you can record your answer, i think is very useful. thank you.
