### ISSUE TITLE
Return promise from uiViewScroll

### ISSUE THREAD

**Issue by mikef438** [angular-ui/ui-router#1702]
I'm asking for the uiViewScroll function to return the timeout promise so that additional processing can occur once that is complete. The use case I have is with an iOS 7 bug on iPads that cause the screen to be blank until it's moved. In order to fix this I need to wait until the scroll completes and then move the screen an additional one pixel to make the content appear. For the time being I've had to use the source code from uiViewScroll and make my own function. Thanks!

Usage after issue resolved:
    $uiViewScroll(element).then(function() { $window.scrollTo(0,1);});

**Comment by christopherthielen** [comment]
Seems fine, can you make a PR according to the contributor guidelines?

**Comment by dookie86** [comment]
Sure

On Thursday, January 22, 2015, Chris Thielen <notifications@github.com>
wrote:

> Seems fine, can you make a PR according to the contributor guidelines?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-router/issues/1702#issuecomment-71063137>
> .
>


-- 
Mike
