### ISSUE TITLE
Query parameters, how do you persist them in ui router?

### ISSUE THREAD

**Issue by moneytree-doug** [angular-ui/ui-router#1704]
How do I persist query parameters through each state? For example, let's say a user tries to access to link, but needs to login first before they could get back to that page, so how can I route the user back to the page as well as keep all the query parameters? I spent a few hours trying to figure this out, but couldn't get it to work.

I have looked briefly into UrlMatcher and am unclear if that is what I need given that the documentation is lacking. I tried passing the url params with transitionTo which isn't a great solution because I would have to duplicate support across all states.

**Comment by christopherthielen** [comment]
Hi, as this is a general help question, please ask on StackOverflow
http://bit.ly/UIR-SOF
