### ISSUE TITLE
Service injection in resolve silently fails

### ISSUE THREAD

**Issue by siannone** [angular-ui/ui-router#1705]
For some reasons I cannot inject my service into the resolve function.

This is the service definition:

    (function()
    {
        angular.module('main').factory('ResolveService', function($q, $rootScope, UserService, CompanyService)
        {
            return {
                resolveHome : function()
                {
                    var deferred = $q.defer();
    
                    UserService.find('me', function(data)
                    {
                        $rootScope.user = data;
                        CompanyService.find('me', function(data)
                        {
                            $rootScope.userCompany = data;
                            deferred.resolve({
                                user : $rootScope.user,
                                userCompany : $rootScope.userCompany
                            });
                        }, function()
                        {
                            deferred.reject();
                        });
                    }, function(data, status)
                    {
                        deferred.reject();
                    });
    
                    return deferred.promise;
                }
            }
        });
    })();

And this is the config section of the `main` module of my app:

    angular.module('main').config(function($stateProvider, $locationProvider, $logProvider, ConfigProvider)
    {
        $stateProvider
            .state('index',
            {
                url : '/',
                templateUrl : ConfigProvider.path.views + '/page/index.html'
            })
            .state('home',
            {
                url : '/home',
                templateUrl : ConfigProvider.path.views + '/page/home.html',
                controller : 'PageHomeCtrl',
                resolve : {
                    promise : ['ResolveService', function(ResolveService) {
                        console.log('executing resolve');
                        return ResolveService.resolveHome();
                    }]
                }
            })
            .state('home.company',
            {
                url : '/company',
                templateUrl : ConfigProvider.path.views + '/segment/home/company.html'
            }
        );

        $locationProvider.html5Mode(true);
        $logProvider.debugEnabled(true);
    });

Whenever I change the state by changing the path to `/home` nothing happens except for the url flashing to the new path and then reverting back to `/`.

I also noticed that if I remove `ResolveService` from the resolve function parameters, so that it's not injected, the function is actually executed and I'm reading the `executing resolve` message in the console.

**Comment by christopherthielen** [comment]
Add some transition logging:
```
app.run(function($rootScope) {
  function message(to, toP, from, fromP) { return from.name  + angular.toJson(fromP) + " -> " + to.name + angular.toJson(toP); }
  $rootScope.$on("$stateChangeStart", function(evt, to, toP, from, fromP) { console.log("Start:   " + message(to, toP, from, fromP)); });
  $rootScope.$on("$stateChangeSuccess", function(evt, to, toP, from, fromP) { console.log("Success: " + message(to, toP, from, fromP)); });
  $rootScope.$on("$stateChangeError", function(evt, to, toP, from, fromP, err) { console.log("Error:   " + message(to, toP, from, fromP), err); });
});
```

**Comment by christopherthielen** [comment]
http://bit.ly/UIR-SOF
