### ISSUE TITLE
ui-sref directive should throw error when on same element of another directive

### ISSUE THREAD

**Issue by ilovett** [angular-ui/ui-router#1707]
IE:

    <a my-button-anchor />

my-button-anchor.html:

    <a href ui-sref="some.page">
        ...
    </a>

my-button-anchor.js

    ...
    replace: true
    ...

Clicking on this anchor will not navigate to ui-sref... most likely the other directive is interfering.  An error should be thrown saying not to do this... I spent a couple hours trying to figure out why my `ui-sref` directive wasn't working.

**Comment by ProLoser** [comment]
This has nothing to do with `ui-sref`, using replace has the ability to break every other directive there is.
