### ISSUE TITLE
Different behaviour

### ISSUE THREAD

**Issue by marcelaraujo** [angular-ui/ui-router#1709]
When you access url directly, the loaded state is different than I use ui-shref directive

Try access the `http://run.plnkr.co/7XwNcfRA0e6Up12O/#/test` and after `http://run.plnkr.co/7XwNcfRA0e6Up12O/#/edit` using the link on navbar

After try access the last state only refreshing the page.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
