### ISSUE TITLE
ui-router fails to instantiate on Internet Explorer 9

### ISSUE THREAD

**Issue by Dev63** [angular-ui/ui-router#1710]
Does ui-router still work with Internet Explorer 9?  My app works fine in Chrome and IE11, but on a Vista system running IE9 it always fails to instantiate ui-router.  Any ideas?

**Comment by michaelcox** [comment]
I have an app successfully running Angular UI Router on IE9 (specifically we test WinXP/IE9). So it's probably not UI-Router specific. Maybe the issues you're having are more generic to known IE issues with Angular? (e.g. https://code.angularjs.org/1.2.28/docs/guide/ie)

**Comment by nicksloan** [comment]
@michaelcox @Dev63 Can you guys share what versions of AngularJS and UI-Router you are using?

@michaelcox Would it be possible to verify your code against the latest stable of each?

I'm encountering a strange issue where the state change is not starting in IE9. It seems like everything works right up until the state change begins, and then fails silently.

**Comment by Dev63** [comment]
@nicksloan : I am currently using AngularJS v1.3.10, although this issue likely occurred with earlier versions as well.  And ui-router v0.2.13.  

It's possible that my problems relate to the generic IE/Angular issues pointed out by @michaelcox , but I haven't explored those yet.

**Comment by nicksloan** [comment]
My issues was #576. You might want to give it a look.

**Comment by michaelcox** [comment]
I'm using Angular 1.3.2 and UI-Router 0.2.13. It could be, however, that I never ran into your issue because my entire app requires authentication. So I have an `$stateChangeStart` interrupt that may be masking an underlying issue with a blank url field in the `$stateProvider`.

**Comment by nicksloan** [comment]
@michaelcox Don't think so. The behavior in #576 results in $stateChangeStart never firing because ui-router can't find a matching route.

I can also say that ui-router is definitely instantiating in IE9. I suspect @Dev63 may have misdiagnosed their issue.

**Comment by jonricaurte** [comment]
Also, here is something relating to IE9:

https://github.com/angular/angular.js/issues/11439

another thing is to make sure to have this:

.run(['$state', '$stateParams', angular.noop]) to make sure when you refresh it instantiates.

**Comment by hasanfar** [comment]
Wierd.. I had similar issue when I used 
https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.13/angular-ui-router.js (same with /0.2.15) but problem solved when using http://angular-ui.github.io/ui-router/release/angular-ui-router.min.js

Don't no why..

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
