### ISSUE TITLE
How to not show containing div in named view?

### ISSUE THREAD

**Issue by thardy** [angular-ui/ui-router#1719]
Is there a way to not show the containing div of a named view?

I'd like this...

```
<div ui-view="navigation"></div>
```
to resolve to this...

```
<nav class="container navbar-default">
    <ul class="nav navbar-nav">
        <li ui-sref-active="active">
            <a ui-sref="root.home">Home</a>
        </li>
    </ul>
</nav>
```

instead of...

```
<div ui-view="navigation" class="ng-scope">    
    <nav class="container navbar-default">
        <ul class="nav navbar-nav">
            <li ui-sref-active="active">
                <a ui-sref="root.home">Home</a>
            </li>
        </ul>
    </nav>
</div>
```

Is this possible?

**Comment by thetutlage** [comment]
I am looking for same

**Comment by stlcubsfan** [comment]
Could you accomplish that by using the element instead of the attribute version of the directive?
```
<ui-view name="navigation"></ui-view>
```

**Comment by nateabele** [comment]
Can't really think of a way to do this, sorry. You could always put the `ui-view` on a non-block-level element, if that's your problem.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
