### ISSUE TITLE
tr/td tags stripped from child templates not in a table

### ISSUE THREAD

**Issue by BrianMcBrayer** [angular-ui/ui-router#1720]
Hello,
I am using this in production and have encountered an issue where tr/td tags are stripped from templates.
http://plnkr.co/edit/MmxhKyZ9ncb0ruOnVJoe?p=preview

This is because the loaded templates are compiled using jqLite (or jQuery's) .html() function, which removes 'invalid' html (including tr/td not inside a table). This is a problem because a child template, being a partial, might include a partial table. The plunker demonstrates code very similar to what should be used in production. The kendo-grid is part of the commercial Kendo UI toolset (http://www.telerik.com/kendo-ui#demo-grid), and its row templates are declared the way shown in the plunker (badTrTd.tmpl.html). ui-router breaks this, though, because in using the .html() function of jqLite the tags get stripped before the kendo directive even sees them.

What are the ramifications of not using .html() ? I see that you are creating the jQuery element to store some .data() (https://github.com/angular-ui/ui-router/blob/7e38adbcd8b1a557d3df3f99f692b788d1c12306/src/viewDirective.js#L270 ) right before creating the $element. Is there a different way of handling this? As a reference, ngRouter simply stores the html string in the templates cache ( https://github.com/angular/angular.js/blob/master/src/ngRoute/route.js#L596 ), which preserves the tr/td tags.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
