### ISSUE TITLE
2 states are shown in the same page

### ISSUE THREAD

**Issue by burakkilic** [angular-ui/ui-router#1721]
Hi;

Two states are shown like in the screenshot. 

![hbijl](https://cloud.githubusercontent.com/assets/123382/5973887/41c106e2-a876-11e4-8569-ed7ae6553db4.png)

State at the top is the new state, and state at the bottom is the old state. They are shown like that first, and then the state at the bottom goes off.

Where can be the problem?

**Comment by hppycoder** [comment]
Can you create a Plunkr that shows this happening? It would be good to see it in action to see it and then attempt to diagnose what it's doing.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
