### ISSUE TITLE
Loading third party libs in ui-view

### ISSUE THREAD

**Issue by arnauddri** [angular-ui/ui-router#1723]
Hi,

 am using some external libraries such as google maps in some of my views in my angular app.

As this is a relatively minor use case, I'd like to load google maps only when the views is called. So far, I've tried loading the js directly in my views template:

<div class='myView'>
    <script type'text="" javascript="type'text/javascript" src="http://maps.google.com/maps/api/js?sensor=false" class="ng-scope"></script>
</div>
I can see the javascript is requested an well received in the chrome dev tool Network tabs however it is not parsed as window.google remains undefined.

How can I compile it? Is there a better way to do it? Can it be done using the resolve function exposed by ui-router?

Many thanks

**Comment by hppycoder** [comment]
When it comes to one Google service working with a Google framework there's already a service out there that can do what you are looking for look at http://angular-ui.github.io/angular-google-maps/#!/

They are already up to 2.0+ so it's well beyond stable at this point.

**Comment by arnauddri** [comment]
Thanks, I am still interesting in the answer for the general case though :)

**Comment by nateabele** [comment]
Please see StackOverflow for general support questions, thanks. http://bit.ly/UIR-SOF
