### ISSUE TITLE
ui-router converts uri fragments to URLs

### ISSUE THREAD

**Issue by Francisc** [angular-ui/ui-router#1724]
Hello,

It seems that when using pushState, ui-router will translate `domain.com/#hello` to `domain.com/hello`.
Is that intentional? Can it be prevented or intercepted somehow?

I'm using a 3rd party OAuth service which, after login, redirects back to `domain.com` placing user data in the URL after the hash `#` sign for the JS code to consume.

**Comment by nateabele** [comment]
This could be Angular's built-in `$location` service, or it could be something with HTML5-mode. Either way, this sounds like a job for StackOverflow: http://bit.ly/UIR-SOF. Thanks.
