### ISSUE TITLE
State change on location search change

### ISSUE THREAD

**Issue by thebit4bit** [angular-ui/ui-router#1731]
Hi,

we have an urgent problem. I don't know if it is a bug, but please provide us a workaround.
We have a parent state with an url and a child state without an url.
Both states have reloadOnSearch set to false.
Inside the child state we change the search of the location and ui-router transitions to the parent state.
From our perspektiv this is unwanted behaviour.
Please help !

Regards,
Nick

**Comment by eddiemonge** [comment]
why not put the url on the child state instead?

https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
