### ISSUE TITLE
Angular-material input not rendering inside a ui-view

### ISSUE THREAD

**Issue by nitrog7** [angular-ui/ui-router#1732]
When a partial is loaded in the ui-view, the input is not being rendered. The md-input-container and the label directive functions seem to be getting called but not the input. When the snippet of code is placed outside the ui-view, it is rendered correctly. Can't figure out a solution.

Seems to be a conflict with ui-router and angular-material.

Below is the snippet of code that does not work in ui-router:

<md-input-container flex>
  <label>Username</label>
  <input id="username" ng-model="user.username" type="text"/>
</md-input-container>

**Comment by nitrog7** [comment]
Looks like it was an older version. Updated all the libraries and it worked.

**Comment by mbcooper** [comment]
I'm using angular material 0.7.1 and ui-router 0.2.13

I'm not able to put <md- items into a ui-view

**Comment by nitrog7** [comment]
Also try updating to the latest version of Angular. I think this is what did it for me. Mine was on 1.3.8 and I updated to 1.3.12.

**Comment by mbcooper** [comment]
Using angular 1.3.13
