### ISSUE TITLE
State change on application run doesn't work

### ISSUE THREAD

**Issue by antonioperic** [angular-ui/ui-router#1733]
Hi, 
I tried to use $state in .run but it seems that doesn't work. If I use $location instead then everything goes well.

    someApp.run(['$rootScope', '$state', 'identityService', function ($rootScope, $state, identityService) {

    $rootScope.$on('$stateChangeStart', function (event, next) {

        if (identityService.getIdentity() && next.publicAccess) {
            $state.go('dashboard');
        }
        else if (!identityService.getIdentity() && !next.publicAccess) {
            $state.go('index');
        }
    });
}]);

working code:
    someApp.run(['$rootScope', '$location', 'identityService', function ($rootScope, $location, identityService) {

    $rootScope.$on('$stateChangeStart', function (event, next) {

        if (identityService.getIdentity() && next.publicAccess) {
            $location.path('/dashboard');
        }
        else if (!identityService.getIdentity() && !next.publicAccess) {
            $location.path('/#');
        }
    });
}]);

**Comment by acollard** [comment]
$state in .run works fine for us. We use it to automatically redirect to different states. Check that your states don't have an issue. Try hooking up $stateChangeError event and see if you get an error after calling go.

```javascript
.run(['$rootScope', '$state', function ($rootScope, $state) {
            $rootScope.$on('$stateChangeStart', function (event, toState) {
                var redirect = toState.redirectTo;
                if (redirect) {
                    event.preventDefault();
                    $state.go(redirect);
                }
            });
        }]);
```

Also a plunkr reproducing your issue would help.

**Comment by antonioperic** [comment]
here is code

    'use strict';

var liveBoardApp = angular.module('liveBoardApp', ['ui.router', 'directive.g+signin', 'LocalStorageModule', 'helpers']);

liveBoardApp.constant('applicationSettings', {
    googleClientId: '26796268831-pukkdqlairaufeptpof7ov60n8jrlea0.apps.googleusercontent.com',
    applicationUrl: 'http://liveboard-dev.locastic.com/api/v1/',
    authenticationAPIUrl: 'http://liveboard-dev.locastic.com/api/v1/login',
    environment: 'development'
});


liveBoardApp.config(['$provide', '$stateProvider', '$urlRouterProvider', '$locationProvider', '$httpProvider', function ($provide, $stateProvider, $urlRouterProvider, $locationProvider, $httpProvider) {

    $urlRouterProvider.otherwise('/dashboard/');

    $stateProvider
        .state('index', {
            url: '/#',
            templateUrl: 'app/homepage/index.html',
            publicAccess: true
        })
        .state('dashboard', {
            url: '/dashboard',
            templateUrl: 'app/dashboard/account_list.html'
        }) ;

}]);

liveBoardApp.run(['$rootScope', '$state', 'identityService', function ($rootScope, $state, identityService) {

    $rootScope.$on('$stateChangeStart', function (event, next) {
        if (identityService.getIdentity() && next.publicAccess) {
            $state.go('dashboard');
        }
        else if (!identityService.getIdentity() && !next.publicAccess) {
            $state.go('index');
        }
    });

}]);

**Comment by acollard** [comment]
Create a plunkr to demonstrate your issue. http://bit.ly/UIR-Plunk

**Comment by antonioperic** [comment]
@acollard  I reduced dependencies but in general this also doesnt work
http://plnkr.co/edit/Cbzz3vT8nawowkDX4pnW?p=preview

it is always homepage

**Comment by acollard** [comment]
- You accidentally had $location instead of $state in the function.
- You need to use event.preventDefault() to stop the original navigation (to 'home' state).
- Then to stop the endless loop you should check that you are not already going to 'dashboard'.

Here is the fixed code.

```javasript
app.run(['$rootScope', '$state', function ($rootScope, $state) {
    $rootScope.$on('$stateChangeStart', function (event, next) {
        if (true) {
          if(next.name!='dashboard') {
            event.preventDefault();
            $state.go('dashboard');
          }
        }
    });
}]);
```

**Comment by antonioperic** [comment]
@acollard that was quick. Thnx for detailed explanation

**Comment by acollard** [comment]
@antonioperic Glad I could help.

**Comment by BurhanMughal** [comment]
Hi acollard, 
I am facing same issue here is my code snippet:

.run(['$rootScope','$state',function($rootScope,$state){
    
    //listens for $stateChangeError
    $rootScope.$on('$stateChangeError',function(event, toState, toParams, fromState, fromParams, error){
        event.preventDefault();

        if (toState.name === 'app' && !(error == 'AUTH_REQUIRED')){
          return;
        }else{
          $state.go('main.login');//redirect to login view if error
        }
    });
}])

And here is my state declaration:

 $stateProvider

    .state('main',{
        url : '/main',
        abstract : true,
        templateUrl : 'templates/main/main.html',
        controller : 'MainCtrl'
    })  

    .state('main.login',{
        url : '/login',
        views: {
        'main-view': {
          templateUrl: 'templates/main/login.html'
        }
      }
    })

It always shows black screen.

**Comment by JoseTadeuMarques** [comment]
@BurhanMughal it might not be your case, but check your ui-router version. If it is 1.0 or above, than your problem is most likely due to the fact that those events were removed and replaced by transitions as said here:

https://github.com/angular-ui/ui-router/wiki#state-change-events

_**NOTE: State change events are deprecated, DISABLED and replaced by Transition Hooks as of version 1.0 ([details](https://ui-router.github.io/guide/ng1/migrate-to-1_0#state-change-events) )**_
