### ISSUE TITLE
ui-sref not working on kendo ui template

### ISSUE THREAD

**Issue by sargin48** [angular-ui/ui-router#1734]
Hi. i use kendo ui template and this tamplate can exist some url.
i want make url from ui-sref in kendo ui template.

not working in kendo ui template.
now i making manual url with variables.

can you check angular ui router in kendo ui template

for example listview with kendo ui template.
you test in this post.   
http://demos.telerik.com/kendo-ui/listview/angular

**Comment by BrianMcBrayer** [comment]
Hi sargin48,
Are you using a table--any <tr> or <td> tags in your template?

ui-router does not currently support any invalid html in a template, even if that html will be valid when injected onto the page.

**Comment by nateabele** [comment]
Closing due to lack of response.
