### ISSUE TITLE
UI-router child resolves delays parent loading.

### ISSUE THREAD

**Issue by Valm1980** [angular-ui/ui-router#1739]
It appears that child state resolves are delaying the loading of the parent state. Original issue reported on Stackoverflow: http://stackoverflow.com/questions/26802696/ui-router-child-resolves-delays-parent-loading

Essentially, the entire parent view does not render until it's child resolve completes which doesn't make sense. 

Any workarounds for this issue?

**Comment by timlind** [comment]
+1

**Comment by eddiemonge** [comment]
https://gist.github.com/christopherthielen/b3fc0304b737a4bf8ec9
