### ISSUE TITLE
What is the default state?

### ISSUE THREAD

**Issue by Francisc** [angular-ui/ui-router#1740]
Hello,

In my code, I want to prevent state transition (`event.preventDefault()`).
I also have an `otherwise('/')` rule.

This causes an infinite loop because ui-router is changing from `""` to `/`.
That change doesn't happen because of the `preventDefault()` method, thus entering an infinite loop.

So, what is the purpose of the default state, named `""` with a url of `^`?

**Comment by Den-dp** [comment]
@Francisc as per https://github.com/angular-ui/ui-router/blob/master/src/state.js#L244 it seems that this is just a top/root point of state's graph, which is always active.
@/all BTW, can we somehow change this state (f.e. add named view and controller) ?

**Comment by Francisc** [comment]
Thanks for the link Den-dp.

Two things I noticed:
When ui-router starts up, the first route is always navigated from this default `''` route.
You cannot override this state with a custom one and there's no clean way of defining a custom controller or resolve for it.

**Comment by nateabele** [comment]
> You cannot override this state with a custom one and there's no clean way of defining a custom controller or resolve for it.

This is by design, as the initial page load should be a no-op from the perspective of the state machine. If you want to define a default top-level state that is immediately transitioned to, define a state with `url: ""`.
