### ISSUE TITLE
$urlRouterProvider rule() and minification problem

### ISSUE THREAD

**Issue by kentor** [angular-ui/ui-router#1742]
When using `rule` (https://github.com/angular-ui/ui-router/wiki/URL-Routing#rule-for-custom-url-handling) it doesn't seem like we can pass an array with annotated injections?

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module rescaleApp due to:
Error: 'rule' must be a function
```

Using ui-router version 0.2.11. Just tested on 0.2.13, doesn't work either.

**Comment by eddiemonge** [comment]
You shouldn't be passing an array with annotated injections because it only takes a function:

> handler Function A function that takes in the `$injector` and `$location` services as arguments. You are responsible for returning a valid path as a string.

Those are safe to mangle:

```javascript
$urlRouterProvider.rule(function( a, b ) {
  var $injector = a;
  var $location = b;
});
```

If you need to pass in other services, use $injector:

```javascript
$urlRouterProvider.rule(function( $injector, $location ) {
  $injector.invoke([ '$state', function( $state ) {
      $state.transitionTo( '404', {}, location: false );
   }]);
});
```
