### ISSUE TITLE
Load controllers and views dynamically

### ISSUE THREAD

**Issue by iamdriz** [angular-ui/ui-router#1743]
I've read this article that shows how you can use a routeResolver to dynamically load in controllers and views: http://weblogs.asp.net/dwahlin/dynamically-loading-controllers-and-views-with-angularjs-and-requirejs but it uses the ngRoute instead of the ui-router module.

However I read in the comments (http://weblogs.asp.net/dwahlin/dynamically-loading-controllers-and-views-with-angularjs-and-requirejs#comment-1469747973) that ui-router has its own resolve option, but can it do the same dynamic loading of controllers and views?

**Comment by iamdriz** [comment]
Anyone any ideas on this? Thanks

**Comment by nateabele** [comment]
Check out https://github.com/laurelnaiad/angular-couch-potato
