### ISSUE TITLE
Get resolved parameters via $injector

### ISSUE THREAD

**Issue by AlexYankee** [angular-ui/ui-router#1745]
Is there any way to get route resolved parameters via $injector?
I want to replace 
```
function(myResolvedParameter){
}
```
with
```
function($injector){
  var test = $injector.get('myResolvedParameter');
}
```

**Comment by aramalipoor** [comment]
+1 Same issue here?!

**Comment by AlexYankee** [comment]
Thanks, @aramalipoor. Will give it a try

**Comment by demisx** [comment]
Would be great if we could get them through `$injector` like others.

**Comment by nateabele** [comment]
> Would be great if we could get them through `$injector` like others.

That's not possible. `$injector` is global across the entire app, whereas resolve values are scoped to just the state transition. Exposing all of them arbitrarily would be bad practice and cause many issues.

**Comment by felixfbecker** [comment]
I guess it could work like this:
```js
function myFn($http, myResolve) {
  ...
}

$injector.invoke(myFn, null, $state.$current.locals.globals)
```
