### ISSUE TITLE
What is the most correct typescritp definition file?

### ISSUE THREAD

**Issue by nelsonmorais** [angular-ui/ui-router#1746]
Hi,

Is the typescript definition file available in this repository at the api folder (https://github.com/angular-ui/ui-router/tree/master/api) the most correct and up to date file, or is the one currently available in the DefinitelyTyped (https://github.com/borisyankov/DefinitelyTyped/tree/master/angular-ui)

If the one present on this repository if the most correct, can this one be pushed to the DefinitelyTyped repo, replacing the current one?

Thanks,
Nelson

**Comment by nateabele** [comment]
I don't use TypeScript, so I have no idea. If the TypeScript definition file in the repo needs to be updated, please submit a PR, thanks.
