### ISSUE TITLE
How to Obtain Parent State from a State Object

### ISSUE THREAD

**Issue by nkoterba** [angular-ui/ui-router#1748]
Perhaps I'm missing something, but in multiple locations in my application it would be extremely useful to walk the ancestor "tree" of states from an existing state.

E.g.:
```javascript
$state.current.parent.parent.parent
```

But the "parent" of state does not appear to be exposed on a state object.  Is there a design limitation that prevents this?

**Comment by jose-cieni-movile** [comment]
That would be really useful for me

**Comment by panstav** [comment]
Did you try `$state.$current.parent`?

**Comment by nkoterba** [comment]
@panstav Ugh...I didn't realize there was a `$current` object on the `$state` object.  I thought it was just `current`.  My own stupidity for not examining the object tree.

Thanks for pointing this out...I assumed there was an easy way.

I didn't see `$current` mentioned in any of the old or new documentation (aside from usages) so it didn't even dawn on me it existed.  It would be nice if it was added somewhere. The [guide](https://github.com/angular-ui/ui-router/wiki/Quick-Reference#statecurrent) describes the `$state.current` property but not this one.

Thanks again!
