### ISSUE TITLE
misleading "abstract state" exception under certain conditions

### ISSUE THREAD

**Issue by boneskull** [angular-ui/ui-router#1749]
When transitioning from a top-level state to its parent via `^`, this exception is thrown:

```
Error: Cannot transition to abstract state '^'
```

Of course, there is no parent state, so this is an error.  The exception messaging is misleading; should probably check for existence of a parent state, and if it doesn't exist, note that instead of calling it "abstract".

**Comment by nateabele** [comment]
The implicit root state is abstract. Perhaps it could be given a meaningful name so the error would make more sense.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
