### ISSUE TITLE
notify doesn't broadcast for the same routes using ui-sref-opts

### ISSUE THREAD

**Issue by moneytree-doug** [angular-ui/ui-router#1752]
Judging from this documentation ``notify - {boolean=true}, If true will broadcast $stateChangeStart and $stateChangeSuccess events.``, I would expect passing this option to broadcast the events regardless. 

http://plnkr.co/edit/elAF9VVjCLEEjEjkVQx7?p=preview

After going to a link and receiving an alert, if you try to go to the same state, it would not alert again even if you have notify set to true. Is there a way to force the broadcast even if its on the same state?

**Comment by nateabele** [comment]
> Is there a way to force the broadcast even if its on the same state?

No.

'Transitioning' to the same state you're already in isn't a transition. It's a no-op.

**Comment by eddiemonge** [comment]
You would have to add reload:true
