### ISSUE TITLE
Reload optional parameters into state params

### ISSUE THREAD

**Issue by jaulz** [angular-ui/ui-router#1754]
If the reloadOnSearch parameter is set to false in a state and a search parameter is changed by using $location.search I cannot see a possibility to update the stateParams with this new value. Especially if I want to trigger a navigation afterwards to a related state the old value of the parameter is passed.

**Comment by nateabele** [comment]
UI-Router listens for `$locationChangeStart` in order to update parameters. If you're making changes directly to `$location`, you may have to manually broadcast that event for UI-Router to pick it up.
