### ISSUE TITLE
reloadOnSearch false suppresses state change

### ISSUE THREAD

**Issue by georeith** [angular-ui/ui-router#1757]
If you have a defined route `item.page` with `reloadOnSearch: false` and a search parameter `pageNumber` on its parent. If you `$state.go('item.page', { pageNumber: 2 })` it will not go to `item.page` because of `reloadOnSearch:false`, even though you are currently on `item`.

I would expect the behaviour of `$state.go` would be to go to the state whether or not it is supposed to reload when a search parameter changes.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
