### ISSUE TITLE
State Params are added to ui-sref even if they aren't set

### ISSUE THREAD

**Issue by RavenHursT** [angular-ui/ui-router#1760]
If I set up a state in the following manner:

```javascript
$stateProvider.state('my-state', {
  url: '/my-state?foo',
  parent: 'main',
  views: {
    'main@' : {
      templateUrl: '/modules/foo/views/foo.html',
      controller: 'FooCtrl'
   },
});
```

And then I go to: localhost:90000/my-state?foo=bar

Which has the following link in the template:

```html
<a ui-sref="my-state()">Clear Params</a>
```

the URL that's generated for the link ends up being "http://localhost:9000/my-state?foo=bar"

But if I go to "localhost:9000/my-state" w/o parameters, the URL generated for the link seems to make perfect sense (no params).

Obviously, I could just create a state with a different path and have that be the "back" state w/o params.. but that's just duplicative.  Would be better IMHO to just have the URL only generate params if the ui-sref defines them explicitly.

**Comment by RavenHursT** [comment]
Interestingly enough.  Doing the following actually works as expected:
```html
<a ng-click="goToCleanState()">Clear Params</a>
```
```javascript
$scope.goToCleanState = function(){
  $state.transitionTo('my-state', {});
};
```

But.. ```$state.go('my-state', {})``` didn't work.

Takes me right to where I want to.  Why does .transitionTo() work but .go doesn't?  And even though this "works", it'd still be nice to have the URL actually generated accordingly for the link instead of having to manage yet another ng-click in my app...

**Comment by nateabele** [comment]
Try `ui-sref-opts="{ inherit: false }"`.

**Comment by jondea** [comment]
I found this answer useful, thank you
As an extension that others may find useful (and may have solved this specific issue) you can use ` ui-sref=".stateName({paramToReset:undefined})"` to reset specific parameters but leave others untouched.
