### ISSUE TITLE
UI-Router state change cancelled - UI not updated..

### ISSUE THREAD

**Issue by Drammy** [angular-ui/ui-router#1763]
I have an AngularJS app that uses UI-Router and has Authentication & Authorisation.

When changing $state I check authentication and authorisation and on failure I intend to redirect or request login.

My problem is that when on state 'app.dashboard' and attempting to navigate to a state on which I don't have permission or am not authenticated I see the state change (breadcrumbs change on view) but then the $stateChangeStart code above kicks in and should send the state back to 'app.dashboard' and it does... I can debug and see the state is indeed changed back to app.dashboard but because the state already was 'app.dashboard' a reload doesn't take place therefore my navigation ui-sref-active directives don't update and the view (breadcrumbs) doesn't update.

For more details I've included some code in my stackoverflow question here: http://stackoverflow.com/questions/28581937/ui-router-state-not-changing-as-intended

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
