### ISSUE TITLE
$state.go incorrectly suppressed by reloadOnSearch

### ISSUE THREAD

**Issue by leon13** [angular-ui/ui-router#1765]
I have a state with url params:
```javascript
$stateProvider.state('schedule.week', {
    url: '/:year/:week',
    controller: 'ScheduleWeekController',
    templateUrl: 'sections/schedule/week.html',
    reloadOnSearch: false
});
```

However, when I try to go to the same state with different url params, It's being suppressed. I think by this line: https://github.com/angular-ui/ui-router/blob/master/src/state.js#L993

```javascript
$state.go($state.current, {
    year: '2015',
    week: '09'
}, {reload: true});
```

I don't think that `reloadOnSearch: false` should prevent URL param changes, and should only affect query/search params as the name suggests

**Comment by christopherthielen** [comment]
Dupe #1079
Fixed in 0.2.15  commit 6ca0d7704cf7de9c6e6b7bb64df2f9c68fe081cc
