### ISSUE TITLE
ui-sref with nasted ng-repeat error k is null!

### ISSUE THREAD

**Issue by OwlJava** [angular-ui/ui-router#1769]
Dear, 

I am new to angularjs and consediring it as main framework for my project. 
in my project i have to draw a menu of (system functions aka links) which is provided via json server from the server in this format: 

```javascript
{menu:[{"OBJECT_ID":"13","OBJECT_PARENT":"4","OBJECT_NAME":"Test3","OBJECT_TYPE":2,"OBJECT_COMMAND":"test3.xhtml"},
 {"OBJECT_ID":"3","OBJECT_PARENT":"3","OBJECT_NAME":"Broadcast","OBJECT_TYPE":1,"OBJECT_COMMAND":"news.html"},
 {"OBJECT_ID":"6","OBJECT_PARENT":"1","OBJECT_NAME":"Users","OBJECT_TYPE":2,"OBJECT_COMMAND":"users.html"},
 {"OBJECT_ID":"2","OBJECT_PARENT":"2","OBJECT_NAME":"Search","OBJECT_TYPE":1,"OBJECT_COMMAND":"search.html"},
 {"OBJECT_ID":"5","OBJECT_PARENT":"1","OBJECT_NAME":"Modules","OBJECT_TYPE":2,"OBJECT_COMMAND":"modules.html"},
 {"OBJECT_ID":"4","OBJECT_PARENT":"4","OBJECT_NAME":"Printable Results":1,"OBJECT_COMMAND":"reports"},
 {"OBJECT_ID":"7","OBJECT_PARENT":"1","OBJECT_NAME":"Groups","OBJECT_TYPE":2,"OBJECT_COMMAND":"groups"},
 {"OBJECT_ID":"9","OBJECT_PARENT":"2","OBJECT_NAME":"Search Keywords","OBJECT_TYPE":2,"OBJECT_COMMAND":"KEYWORDS"},
 {"OBJECT_ID":"12","OBJECT_PARENT":"4","OBJECT_NAME":"Test2","OBJECT_TYPE":2,"OBJECT_COMMAND":"test2/servlet?test=true"},
 {"OBJECT_ID":"11","OBJECT_PARENT":"3","OBJECT_NAME":"Archives","OBJECT_TYPE":2,"OBJECT_COMMAND":"newsArchive"},
 {"OBJECT_ID":"8","OBJECT_PARENT":"2","OBJECT_NAME":"Repository","OBJECT_TYPE":2,"OBJECT_COMMAND":"searchSites"},
 {"OBJECT_ID":"10","OBJECT_PARENT":"3","OBJECT_NAME":"News","OBJECT_TYPE":2,"OBJECT_COMMAND":"news"},
 {"OBJECT_ID":"1","OBJECT_PARENT":"1","OBJECT_NAME":"Preferences","OBJECT_TYPE":1,"OBJECT_COMMAND":"sys"},
 {"OBJECT_ID":"14","OBJECT_PARENT":"4","OBJECT_NAME":"Test 4","OBJECT_TYPE":2,"OBJECT_COMMAND":"test4.jsf"}]}
```

and i have created a controller like this in my app: 
```javascript
angular.module('myappname').controller('populateMenu',function ($scope,$http){
    $http.get('MyServiceName?get_menu').
        success(function(data, status, headers, config) {
          // this callback will be called asynchronously
          // when the response is available
                $scope.menu = data.menu;
        }).
        error(function(data, status, headers, config) {
          // called asynchronously if an error occurs
          // or server returns response with an error status.
          console.log('error in populateMenu:'+data);
        });
});

```

and finally created a templated (based on bootstrap stylesheet) like this: 
```javascript
[html]
<li ui-serf-active="active" ng-repeat="row in menu| filter:{OBJECT_TYPE: 1}">
                <a ui-sref="{{row.OBJECT_COMMAND}}">
                    <i class="fa fa-desktop"></i>
                    <span class="nav-label">{{row.OBJECT_NAME}}-{{row.OBJECT_ID}}</span>
                </a>
                <ul class="nav nav-second-level">
                    <li ui-sref-active="active" ng-repeat="subRow in menu| filter:{OBJECT_TYPE: 2,OBJECT_PARENT: row.OBJECT_ID}">
                        <a ui-sref="{{subRow.OBJECT_COMMAND}}">{{subRow.OBJECT_NAME}}</a> 
                    </li>
                </ul>
            </li>
[/html]
```
and when i load the page it draws the menu correctly but in firebug it shows this error: 
Error: k is null
h@http://localhost/MyApp/js/ui-router/angular-ui-router.min.js:7:19232

where is the problem?! 
ps. if i remove the ui-serf="{{subRow.OBJECT_COMMAND}}"  (only the ui-serf part) it loads without error but it doesn't open the template required in to the ui-view  

i am new to this .. hope to find any help .. Thanks

**Comment by IGBSpeed** [comment]
if i replace the ui-serf with href everything works but not as expected to open in the ui-view , it opens the page and redirects the current page or opens in new tab if target set to _blank as usual behavior of the hyperlink ... the menu drawing is correct and as expected nasted and everything .. only this part is eluding me !!.. it would be grate if anyone can help shed a light to it 

hope to hear from you soon :)

**Comment by eddiemonge** [comment]
Seems to work fine to me: http://plnkr.co/edit/Zj6QTIfRCKmC4he2wCX5?p=preview
Your data was invalid though. Once I made it pass jsonlint.com it was good.

**Comment by OwlJava** [comment]
Thank you! 
I am using this template (http://wrapbootstrap.com/preview/WB0R5L90S)

it seems something else might be conflicting with this implementation but the error pointed me to js/ui-router/angular-ui-router.min.js:7:19232

**Comment by OwlJava** [comment]
i found the problem.. it seams my injection of the menu to $futureStateProvider  didn't take effect and the states defined in ui-serf are not found in $stateProvider and that was the cause of the bug .. i am still trying to figure out why $futureStateProvider  didn't work!
