### ISSUE TITLE
Applying a query parameter to all routes? or all child routes?

### ISSUE THREAD

**Issue by iq-dot** [angular-ui/ui-router#1770]
Is there a way to specify a query parameter that can exist for all routes? At the moment I have to add the same query parameter to each route individually, could I not specify a query parameter at a parent route or on the main root URL (/).

Is this possible?

**Comment by iq-dot** [comment]
Never mind, although didn't find any documentation, it seems simply adding it to the parent route works.

**Comment by davidtsuji** [comment]
@iq-dot do you have an example for how you solved this?
