### ISSUE TITLE
Resolve documentation error

### ISSUE THREAD

**Issue by EricLin2004** [angular-ui/ui-router#1771]
https://github.com/angular-ui/ui-router/wiki#resolve

this example:
```
         promiseObj:  function($http){
            // $http returns a promise for the url data
            return $http({method: 'GET', url: '/someUrl'});
         },  
```

When used at the bottom, I believe it should be:
```
          $scope.items = promiseObj.data.items;
```

to reflect https://github.com/angular-ui/ui-router/issues/77.

On the other hand, would it be feasible to have `ui-router` run angular `$http`'s `.success` if it exists instead of `.then` ?

I find myself having to do this:
```
         promiseObj:  function($http){
            // $http returns a promise for the url data
            return $http({method: 'GET', url: '/someUrl'})
                     .then(function(res) {
                        return res.data;
                      });
         },
```
all the time.

**Comment by eddiemonge** [comment]
that seems valid. in your controller you would have:
```javascript
promiseObj.then(function(response) {
  $scope.items = response.data.items;
});
```

**Comment by EricLin2004** [comment]
Right, the documentation shows
```
$scope.items = response.items;
````
right now.

**Comment by eddiemonge** [comment]
Updated. Its a wiki just so you know.

**Comment by EricLin2004** [comment]
Ah, thanks. Haven't contributed much to open source, didn't want to mess anything up ;p
