### ISSUE TITLE
StateName 'watch' firefox bug

### ISSUE THREAD

**Issue by al-mazrouai** [angular-ui/ui-router#1772]
in firefox browser, state can not named 'watch' this cause error. example below
```
.state('watch', {
      url: '/page2',
      templateUrl: '/page2.html'
})
```

ERROR
```
Failed to instantiate module myApp due to:
b.shift is not a function
o@http://localhost:8000/angular-ui-router.min.js:7:13135
p@http://localhost:8000/angular-ui-router.min.js:7:13776
t@http://localhost:8000/angular-ui-router.min.js:7:14295
@http://localhost:8000/#/page2:23:1
e@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular.min.js:37:94
d@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular.min.js:35:293
g/<@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular.min.js:35:425
s@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular.min.js:7:300
g@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular.min.js:35:202
Ob@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular.min.js:38:435
sc/d@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular.min.js:17:350
sc@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular.min.js:18:153
Jd@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular.min.js:16:483
@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular.min.js:249:429
a@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular.min.js:164:283
lf/c@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular.min.js:32:358
```

**Comment by astrism** [comment]
I have this same issue, for now a workaround is to rename the state.

**Comment by al-mazrouai** [comment]
Yes Astrism, I know that I posted this issue just to inform the developers about the existing bug

**Comment by nateabele** [comment]
Not really sure what to tell you. Add it to the FAQ?

**Comment by astrism** [comment]
I've added it [here](https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#issue-firefox-is-throwing-a-bshift-is-not-a-fuction-error-other-browsers-are-operating-normally). I put a fairly terse message, if you already know why it's happening I would be happy to add details.

**Comment by nateabele** [comment]
@astrism I don't, I just know this has come up before. You included a googleable error message, which is probably about the best thing you can do.

**Comment by steverob** [comment]
I faced this today. Googling did not help. Finally ended up finding it here :+1:

**Comment by nateabele** [comment]
> Finally ended up finding it here

Wait, how did you end up here if Googling didn't help? :wink:

**Comment by steverob** [comment]
Haha :D searched for "shift" on GitHub issues ;)

--
Regards
Steve Robinson
