### ISSUE TITLE
Issue with IE < 11

### ISSUE THREAD

**Issue by stlouisweb** [angular-ui/ui-router#1775]
In IE 10 and lower I get a blank screen, it looks like IE is changing 
```
<div ui-view>
```
to
```
<div ui-view="">
```
Is there an easy fix for this?

Thanks

**Comment by eddiemonge** [comment]
Is it IE doing that or something in your build/setup? You could always name your views but it shouldn't be required.

**Comment by stlouisweb** [comment]
I think the issue was unrelated to ui-router
```
<div ui-view="">
```
doesn't seem to be a problem.

**Comment by hhamalai** [comment]
@stlouisweb did you ever find out the cause for this?

**Comment by simplyeleza** [comment]
Please reply if you ever solved this problem

**Comment by stlouisweb** [comment]
No, I moved on to React
