### ISSUE TITLE
Getting data from a service resolved in the parent to inherit down to it's child state

### ISSUE THREAD

**Issue by bmwertman** [angular-ui/ui-router#1776]
I'm able to access data in my ManageCtrl that resolves in the app.manage state. But I need this to inherit down to my app.manage.hours state so I have access to it in my CalendarController. 

Right now if I try to pass shopService and shop into my Calendar Controller I get an unknown provider error on shop. If I don't pass in shop and reference it in the controller it says shop is undefined.

App.js

    var app = angular.module('myApp', [])
    .config(['$stateProvider', '$urlRouterProvider',  '$ionicConfigProvider', function ($stateProvider, $urlRouterProvider, $ionicConfigProvider) {
        $stateProvider.state('app', {
            url: "/app",
            abstract: true,
            templateUrl: "menu/templates/menu.html",
            controller: 'AppCtrl'
        });
        $stateProvider.state('app.manage', {
            url: "/manage",
            views: {
                'menuContent': {
                    templateUrl: "manage/templates/manage.html",
                    controller: 'ManageCtrl',
                    resolve: {
                       shop: function (shopService) {
                       return shopService.getShop();
                    }
                 }
              }
           }
        });
        $stateProvider.state('app.manage.hours', {
            url: "/manage/hours",
            resolve: {
                shop: function (shopService) {
                    return shopService.getShop();
                } 
            },
            views: {
                'hours': {
                    templateUrl: "lib/rcalendar/template/schedule.html",
                    controller: "CalendarController"
                }
            }
        }); 

Shop Service

    app.factory('shopService', function () {
      var service = {
        _shop: null,
        setShop: function (s) {
          if (s && !s.error) {
            service._shop = s;
            return service.getShop();
          } else {
            return s.error;
          }
        },
        getShop: function () {
          return service._shop;
        }
      };
      return service;
    });
Manage Controller (Resolves here)

    app.controller('ManageCtrl', function ($scope, 'shopService', 'shop',  function ($scope, shopService, shop) {
         $scope.shop = shop;
    }

Calendar Controller (Doesn't inherit here)

    Synchro.constant('calendarConfig', {
      //some settable constants
    })
    app.controller('CalendarController', ['$scope', 'shopService', 'shop',  function ($scope, shopService, shop) {
        $scope.shop = shop;
    });

**Comment by eddiemonge** [comment]
Your child is overwriting the shopService since it has the same name. If you want the child to use the same data, then you don't have to do anything with it in the child, I think.

**Comment by bmwertman** [comment]
@eddiemonge when you say it is using the same name what is it you're referring to?

**Comment by eddiemonge** [comment]
I mean your resolves in app.manage and app.manage.hours both have a resolve: **shop** name

**Comment by bmwertman** [comment]
So remove the resolve shop in the hours view. Do I need to pass shop or shopService to the hours controller?

**Comment by eddiemonge** [comment]
It should get it automatically

**Comment by bmwertman** [comment]
I'm seeing the same issues. I think this has something to do with the view names and/or as you mention the configuration of the resolve in the child view or removal thereof.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
