### ISSUE TITLE
$state.transitionTo('myStateName') inside "$stateChangeStart" handler looks like doing successful transition but visually not!

### ISSUE THREAD

**Issue by guilloche** [angular-ui/ui-router#178]
$state.transitionTo('myStateName') inside "$stateChangeStart" handler looks like doing successful transition but visually not!
 
After so-called successful transition current state shows expected value, but in reality my browser do not transitioned to it. Visually it's did't changed. What I doing wrong?
```javascript
app.run([
        '$rootScope',
        '$state',
        '$location',
        '$stateParams',
        '$couchPotato',
        function(
            $rootScope,
            $state,
            $location,
            $stateParams,
            $couchPotato) {
				app.couchPotato = $couchPotato;
				$rootScope.$state = $state;
				$rootScope.$stateParams = $stateParams;

                // here is my event handler
                $rootScope.$on("$stateChangeStart", function (ev, to, toParams, from, fromParams) { 
                    if (/* my conditional expression */) {
                         $state.transitionTo('MyIntendedStateName');
                    }
               });
        }
]);
 ```

**Comment by gabrielAnglada** [comment]
Hi all! any news?

**Comment by atul221282** [comment]
Well workaround didn't work for me ao is there any news on fix

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by darlanalves** [comment]
I ended up replacing the `transitionTo()` method in a decorator rather than preventing or refiring events. This way I could intercept any state transitions and deal with it in the way I need, only then calling the original method when it is allowed to continue.

**Comment by batteur** [comment]
Got same issue. My case was related to using the $urlRouterProvider.otherwise in combination with the  preventDefault and $state.go in a $stateChangeStart interceptor.

A workaround is found here: https://github.com/angular-ui/ui-router/issues/600
