### ISSUE TITLE
$stateChangeStart is fired after URL & history are already updated in browser

### ISSUE THREAD

**Issue by mgrahamjo** [angular-ui/ui-router#1780]
When preventing default on $stateChangeStart, doing some work, and then resuming the state change, everything works basically as expected. However, the URL in the address bar flickers back and forth, and what appears to be an extra history entry shows up in the back button history. This is because $stateChangeStart is broadcast after the transition has been executed, then it checks for defaultPrevented, in which case $urlRouter.update() is called to redirect back to the "current" location. 

I confirmed that I can get better behavior by broadcasting an event before redirecting, and actually canceling the transition before it happens.

**Comment by mgrahamjo** [comment]
For other folks trying to do this, here's what I did. I added in a $beforeStateChange event so that I can preventDefault without inserting the extra history entry. This is in my run() block in app.js:

    var transitionTo = $state.transitionTo;
        $state.transitionTo = function(to, toParams, options) {
            var from = $state.$current,
                fromParams = $state.params;
            
            to = to.name ? to : $state.get(to);

            if (options.notify !== false && $rootScope.$broadcast('$beforeStateChange', to, toParams, from, fromParams).defaultPrevented) {
                return $q.reject(new Error('transition prevented'));
            } else {
                return transitionTo(to, toParams, options);
            }
        };

**Comment by dmigliorisi** [comment]
@mgrahamjo Can you show me what your event listener looks like. I think what you're doing here is exactly what I need to do to fix an issue I'm having in my app.

Unfortunately for me, `$rootScope.$broadcast("$beforeStateChangeStart", to, toParams, from, fromParams).defaultPrevented` seems to always be false for me, so the transition continues through every time.

Would love to know how you go this to work.

**Comment by mgrahamjo** [comment]
@dmigliorisi sorry for the wait. Here's my listener, basically. This is in a directive that handles page transition animations as well as pop-ups that alert the user if they're about to lose unsaved work.
```
$scope.$on('$beforeStateChange', function(e, to, toParams, from, fromParams) {

    e.preventDefault();

    transition = {
      to: to,
      toParams: toParams,
      from: from,
      fromParams: fromParams
    };

    // ... 400 ms animation, then:

   $state.transitionTo(transition.to.name, transition.toParams, { notify: false });

});
```

**Comment by morgs32** [comment]
I found that using the option {location: 'replace'} did the job.

**Comment by maverick09** [comment]
@morgs32 : could you please elaborate more how have u used this  { location: 'replace' } to prevent back button rewriting history?

I m trying to do following in run block in app.js, however this is not working for me:
```

$rootScope.$on('$beforeStateChange', function (e, to, toParams, from, fromParams) {
            e.preventDefault();
            debugger;
            var transition = {
                to: to,
                toParams: toParams,
                from: from,
                fromParams: fromParams,
            };
            // ... 400 ms animation, then:
            $state.transitionTo(transition.to.name, transition.toParams, { notify: true });
        });

        var transitionTo = $state.transitionTo;
        $state.transitionTo = function (to, toParams, options) {
            debugger;
            var from       = $state.$current,
                fromParams = $state.params;

            to = to.name ? to : $state.get(to);

            $rootScope.$broadcast('$beforeStateChange', to, toParams, from, fromParams);
            if (options.notify !== false && res.defaultPrevented) {
                console.log('transition prevented');
                return $q.reject(new Error('transition prevented'));
            } else {
                return transitionTo(to, toParams, options);
            }
        };
```

**Comment by morgs32** [comment]
@maverick09 I believe location: replace was an option passed to $state.go or $state.transitionTo that would replace the fromState with the toState in the history. In other words, after the transition, hitting the back button would NOT take you to the fromState (from which you called the transition). The back button would go to state before that.

Is that clear? I'm not sure how it applies to your code. What isn't working?

**Comment by maverick09** [comment]
I have this exactly same issue where I can see that $stateChangeStart is
being called twice when Back button in browser pressed. That modifies
browser's last viewed page in history to current page from where I have
clicked back button. For example:

State1: setOne.Result
State2: setOne.Availability

State3: setTwo.Sim
State4: setTwo.Boost

Page sequence is : State1 > 2> 3 > 4

However suppose I am currently on setTwo.Boost ( last state ) & press
browser back button, address bar flicks, and browser loads State3.

After that if I press Back button again , then ideally it should go to
State2 however it goes to State4 again.

Does that make sense?

**Comment by whiterockerart** [comment]
I have similiar problem as @maverick09, but for me the sequence ends up like this:

State 4 > State3 (without params in url) > State 3 (with params in url) > state 2 > state 1

Also, when I go back from state 4 to state 3, I can't go forward to state 4 again.

**Comment by morgs32** [comment]
@whiterockerart @maverick09 are you making `$state.go` redirects in resolves or in `statechangestart`? or `transitionTo` - I've experienced odd things when I try redirecting or adding params during state changes.

**Comment by whiterockerart** [comment]
@morgs32, neither. Using ui-sref and updates the url with params with $location.url() and $location.search().

Our company are over one year into this development and has a lot of special cases, which isn't easy to change without breaking whole application.

**Comment by morgs32** [comment]
i think that might be it. i'd be very wary of using $location to do any setting - just getting. ui-router wants you to use $state.go and set params. http://stackoverflow.com/questions/29176566/location-search-setter-not-causing-reload-in-ui-router
perhaps...

**Comment by whiterockerart** [comment]
@morgs32 I did change $location.url() to $state.go('state'. params) and sure it works, but I can't traverse the application back or forward with the browser buttons.
history.state gives null all the time.

Running angular 1.5.8 and ui-router 0.31

**Comment by morgs32** [comment]
really... that comes out of the box. such as, if you compare your app to their sample app, do you notice any significant inconsistency? are you using $locationProvider in any weird way? or $urlMatcherFactoryProvider?

**Comment by morgs32** [comment]
actually. just checked. my history.state is also null but that doesn't prevent me from using the back/forward buttons.

**Comment by whiterockerart** [comment]
After using $state.go() I could use this solution: http://stackoverflow.com/a/22402285
It works, but for some reason I loose one parameter (that actually is set). But, I have to solve that on my own.

**Comment by whiterockerart** [comment]
Interesting, $state.go() messes up everything, one important part of the application stops working properly and it daosn't matter if I set options {location: false/true/"replace" } - it won't work!

The idea of this state is that it can take multiple params and updates itself depending on which params is used or set. think of a filetree in an explorer os something like that.

I have to use $location.url() - unfortunately.

**Comment by lobo-tuerto** [comment]
In case this helps anyone: A workaround I found was to reinsert the state I was coming from when the transition is stopped. Like this:

```javascript
$rootScope.$on( '$stateChangeStart', function( event, toState, toParams, fromState, fromParams ) {
  var answer = window.confirm( 'You sure?' );
  if( !answer ) {
    event.preventDefault();
    $state.go( fromState, fromParams );
  }
}
```

**Comment by sumitridhal** [comment]
@mgrahamjo Great suggestion appreciate very much. But can you elaborate this a bit. why 
`$state.transitionTo = function (to, toParams, options) `  is getting called before `stateChangeStart` and overriding exiting method.
