### ISSUE TITLE
ui-router Removing == on base64 query string values

### ISSUE THREAD

**Issue by lelandcope** [angular-ui/ui-router#1784]
We have noticed an issue when we have a url like the following `www.example.com/#/dashboard?key=sdfsdfsdfsdf==` that the query param value gets changed to `www.example.com/#/dashboard?key=sdfsdfsdfsdf`. The problem we are seeing is that the value is a base64 encoded string and we cannot decode the value without those `==` at the end.

Any help to get around this problem would be great. We are using ui-router v0.2.13.

**Comment by nateabele** [comment]
That's pretty odd. Sounds like it could be a `$location` issue. Try cutting UI-Router out of the equation and coding against `$location` directly and see what happens. And/or post a plunkr and I can try to figure it out.

**Comment by eddiemonge** [comment]
Also try updating to 0.2.15 although im not sure that will fix the problem. If you are still having the issue, please provide a plnkr example.
