### ISSUE TITLE
Confused about token authentication with ui-router

### ISSUE THREAD

**Issue by npearson72** [angular-ui/ui-router#1787]
With ngRouter I was using a an interceptor that would pass a cookie into the header of each server request.

 How can I do this with you ui router?

Thanks

**Comment by acollard** [comment]
There shouldn't be any changes needed to support http interceptors. They have nothing to do with ngRouter or ui-router.

**Comment by nateabele** [comment]
UI-Router does not directly make any HTTP requests. Your same interceptors should work.
