### ISSUE TITLE
Exception in state config.template function does not bubble up to user

### ISSUE THREAD

**Issue by danemacaulay** [angular-ui/ui-router#1788]
When an exception is thrown in a state's config template callback the exception is caught in [ui.router.util.$resolve](https://github.com/angular-ui/ui-router/blob/3e06565f5d5e1973c168116e905bd2fb569abcc6/src/resolve.js#L174) and not bubbled up to the user, causing the app to fail silently.

[Plunkr demonstration](http://plnkr.co/edit/kDWOdG)

I wonder if the [fail callback](https://github.com/angular-ui/ui-router/blob/3e06565f5d5e1973c168116e905bd2fb569abcc6/src/resolve.js#L111) should throw on a rejected promise, ie
```js
      function fail(reason) {
        result.$$failure = reason;
        resolution.reject(reason);
        throw new Error(reason);
      }
```

Not sure this makes sense for all failures, but i think this sort of failure should be visible in the case of ``reason`` being an exception.

**Comment by nateabele** [comment]
> I wonder if the fail callback should throw on a rejected promise [...]

No, because that would break the Promise abstraction. Just do this:

```javascript
app.run(function($rootScope) {
  $rootScope.$on("$stateChangeError", console.log.bind(console));
});
```
