### ISSUE TITLE
ui.router: ng-strict-di breaks templateProvider in $stateProvider.state

### ISSUE THREAD

**Issue by samy100** [angular-ui/ui-router#1789]
I've been trying to load my templates on '.run' and loading them via templateProvider. TemplateProvider never executes if 'ng-strict-di' is set on the application. Took me a long time to track this down to ng-strict-di. Currently unsure what's the problem and why ng-strict-di could affect templateProvider from running with no errors at all the console.

Here's a plunker to show it's not running when ng-strict-di is set:
http://plnkr.co/edit/YJDk8EAx5pM04lZpx4cj?p=preview

Another exact same plunker without ng-strict-di working:
http://plnkr.co/edit/HWC54bDeAa8dZdubMZdL?p=preview

Thanks and please correct me if I'm just horribly wrong.

**Comment by brutalcrozt** [comment]
ok i had the same issues, but it's seem not work in my project.
Removing the ng-strict-di, still break the templateProvider.
But the diferences is i am use angular 1.4.0 beta 1, and according to [this](http://stackoverflow.com/questions/27345020/angular-ui-router-templateprovider-never-called) i assume it's gonna work if returning a promise. If the issues goes when you and me returning a promise in templateProvider, i hope somebody will update the [documentation](http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$stateProvider) to should return a promise.

see you @samy100 , i will try to return promise first

**Comment by brutalcrozt** [comment]
hai @samy100 , this is to your issue. 
i assume the bug is gone when remove the dependency in the templateProvider
[here take a look](http://plnkr.co/edit/GWYHQP?p=preview)
but sadly it's not work in my project :disappointed: 
and maybe you should take a look on [templateFactory](http://angular-ui.github.io/ui-router/site/#/api/ui.router.util.$templateFactory) if you still need the injection.

**Comment by samy100** [comment]
Thanks @brutalcrozt 
The second plunker you added is using an angular version where ng-strict-di is not working as it does in newer versions.
Looking this again, the problem was that template provider also need ['depn', func(depen)..] annotation and it was missing. Usually strict di tells you about this, not silently fail as it's doing with templateProvider for some reason. See working plunker now: http://plnkr.co/edit/wzDsRvXNVuje1mThWFCS?p=preview
