### ISSUE TITLE
This is not an issue

### ISSUE THREAD

**Issue by pwnsdx** [angular-ui/ui-router#1790]
Hi there,

Just a big thanks for this plugin. And thanks to people who are working on it.

Keep up the good work :)
S.

**Comment by IainCole** [comment]
+1

**Comment by nateabele** [comment]
Ce ne est pas un problème?

Thanks! Glad to hear you're enjoying it.

**Comment by JobaDiniz** [comment]
+1

**Comment by syndicatedshannon** [comment]
hear, hear

**Comment by fabiosussetto** [comment]
![image](https://cloud.githubusercontent.com/assets/103664/6657356/b1da4dc4-cb41-11e4-9971-c99c6c7ceac0.png)

+1, thanks for your work!
