### ISSUE TITLE
Menu links don't change when changing url param: /{lang}/catalog

### ISSUE THREAD

**Issue by JobaDiniz** [angular-ui/ui-router#1793]
I've created a [plunker](http://plnkr.co/edit/yleNY6alvqsEZ9dJfYSh?p=preview).

The menu links do not change when I change the language, however `$state.href('catalog');` returns the correct link.

The `{lang}` parameter is not explicitly set, it is set by _params_ option when setting _state_:

```
$stateProvider.state('catalog', {
        url: '/{lang}/catalog',
        templateUrl: 'catalog/catalog.html',
        controller: 'CatalogController',
        params: {
            lang: {
                value: function($translate){
                    return $translate.use();
                }
            }
        }
    });
```

**Comment by nateabele** [comment]
I don't think it's really intended to work that way. `uiSref` has watchers for actual parameter values passed to it and that's it. Checking for updated values anywhere in the app on every digest cycle would be prohibitively expensive from a performance perspective.

I'll leave this open as a potential feature request, but realistically, this will probably not be supported.

**Comment by pascal-privax** [comment]
It's not very nice to add a global variable like language to every single ui-sref you have in your application.

In my project I solved this by patching ```$state``` through a decorator. All you have to do is overload the ```$state.href``` function and add your parameter to the parameters object.

Ofcourse it is an idea to patch this into ui-router in the future, in a way that allows you to register global variables or something :)

Example:
```javascript
var Foo = angular.module('Foo', []);

Foo.config([
    '$provide',
    function($provide) {
        $provide.decorator('$state', [
            '$delegate',
            function($delegate) {
                var href = $delegate.href;

                $delegate.href = function(stateOrName, params, options) {
                    params = params || {};
                    params.someGlobalParameter = 'somevalue';

                    return href.apply(this, [stateOrName, params, options]);
                };

                return $delegate;
            }
        ]);
    }
]);
```

**Comment by nateabele** [comment]
That might be a good example for the FAQ. :smile:
