### ISSUE TITLE
Handling browser history with reloadOnSearch: false;

### ISSUE THREAD

**Issue by raphdg** [angular-ui/ui-router#1799]
When transitioning from state1 to state2 (they have different urls), why is the state2's controller able to receive the $locationChangeStart event ?

In other terms, why is the $locationChangeStart event fired after the initialisation of the state 2's controller ?

My state2's controller needs to listen to $location changes (reloadOnSearch: false), but not when transitioning from another state.

In fact, I want 4 things:
* direct access (by url) to state with preset parameters (solved by enabling query params in state's url)
* prevent the reload of the controller when manipulating the $location (solved by setting reloadOnSearch to false)
* support browser's history buttons (solved by handling to $locationChange event)
* reach state2 from state1 with preset query params (initialise the controller **AND** enter the $locationChange handler, so solved by the following *ugly* piece of code in the controller of state2): 

```javascript    
// init the controller
init();
// handle browser's history buttons when reloadOnSearch is set to false
$scope.$on('$locationChangeStart', function (event, next, current) {
  // prevent double init when coming from another state (another url and another controller)
  if (next.split('?')[0] === current.split('?')[0]) {
    init();
  }
});
```

**Comment by christopherthielen** [comment]
hey, 0.2.15 has much improved reloadOnSearch support. We're now updating $stateParams and also updating the URL if you use `$state.go(".", { queryParam: 'newval' })`

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
