### ISSUE TITLE
$state.reload does not work if state have reloadOnSearch:false

### ISSUE THREAD

**Issue by JobaDiniz** [angular-ui/ui-router#1803]
My website has a header which contains a search field. This header is always shown, doesn't matter which state is the current state. When one submit the search form, they are redirected to *search* state with *term* param.

The *search* page (state) shows pagination widget, so when user clicks *page 2*, I change the query string but don't reload the state (that's why I use `reloadOnSearch:false`). However, the search form is still in the page. If user submits another search, only the *term* parameter will change and because of that, the page will not be reloaded. But I need to reload the page if user submits the search again.

I've created a simple [plunker](http://plnkr.co/edit/Ld7vxkUHHYof0qAdPVwd?p=preview) to demonstrate.

I think `$state.reload`should reload the state, even if it has `reloadOnSearch:false`.
I'm migrating from *ngRoute*, and `$route.reload()` reload the route even if it has `reloadOnSearch:false`.

**Comment by alexndlm** [comment]
+

**Comment by ptrussart** [comment]
Hello,

I have the same issue here. 
Did you find a workaround ? Is there a way to set reloadOnSearch:true with the $state object ?

**Comment by JobaDiniz** [comment]
Unfortunately, I had to reload the entire page... So not user friendly....

**Comment by the-darc** [comment]
I have the same issue here.

I think the problem cold be in the code below (called by the function ``$state.transitionTo``):

```
  function shouldTriggerReload(to, from, locals, options) {
    if (to === from && ((locals === from.locals && !options.reload) || (to.self.reloadOnSearch === false))) {
      return true;
    }
  }
```
https://github.com/angular-ui/ui-router/blob/master/src/state.js#L1375

Note that in the if, the value of options.reload is not considered if the reloadOnSearch is setted to false.

_When I have some time i pretend to do more tests and post a PR. If anyone want to do it before me, be free_

**Comment by mkaluzny** [comment]
+1

**Comment by minmur** [comment]
+1

**Comment by nateabele** [comment]
Looks like a valid issue, but `reloadOnSearch` is actually going away to be replaced with something much better. Y'all think you can hold out for a bit?

**Comment by minmur** [comment]
Is there any date when it will happen?

**Comment by nateabele** [comment]
As soon as possible. :wink: Trying for the middle of next week.

**Comment by JobaDiniz** [comment]
@nateabele can you elaborate? Is there any docs on this new implementation?

**Comment by nateabele** [comment]
> Is there any docs on this new implementation?

Not yet. The code isn't even finished.

**Comment by JobaDiniz** [comment]
Okay, looking forward to it :smile:

**Comment by wbreza** [comment]
+1

**Comment by ptrussart** [comment]
I will be out of the office from April 17th to April 28th with limited email access.

For a technical request, please send your message to support@c6.eu.

For other requests, please send your message to contact@c6.eu.



> From: Wallace Breza <notifications@github.com>
> Subject: Re: [ui-router] $state.reload does not work if state have
> Date: Mon, 20 Apr 2015 15:06:56 -0700

**Comment by j-walker23** [comment]
This is remove so much garbage from my app around reloadOnSearch and $state.reload not working. Thanks so much. Can't wait.

I know it hasn't been long but i am anxious to tear out all my crap code. Any update on time?
As always, thanks for the awesome tool!

**Comment by ptrussart** [comment]
I will be out of the office from April 17th to April 28th with limited email access.

For a technical request, please send your message to support@c6.eu.

For other requests, please send your message to contact@c6.eu.



> From: John Walker <notifications@github.com>
> Subject: Re: [ui-router] $state.reload does not work if state have
> Date: Mon, 27 Apr 2015 04:33:48 -0700

**Comment by nateabele** [comment]
Working on it this week.

**Comment by ptrussart** [comment]
I will be out of the office from April 17th to April 28th with limited email access.

For a technical request, please send your message to support@c6.eu.

For other requests, please send your message to contact@c6.eu.



> From: Nate Abele <notifications@github.com>
> Subject: Re: [ui-router] $state.reload does not work if state have
> Date: Mon, 27 Apr 2015 04:53:38 -0700

**Comment by ptrussart** [comment]
Hello @nateabele , did you make some progress on that topic ?

**Comment by j-hogue** [comment]
My workaround for this issue

```
            $state.current.reloadOnSearch = true;
            $state.reload($state.current, {year:  date.year(), month: date.month() + 1, day: date.date(), filter: 'day'}).then(function(){
              $state.current.reloadOnSearch = false;
            });
```

**Comment by j-walker23** [comment]
To anyone who sees this. My app is littered with garbage with work arounds which have evolved into worse workarounds because of this. What @j-hogue put is the idea i wish i had last year. Could have saved so much pain.

**Comment by christopherthielen** [comment]
Hi all, this should be fixed for 0.2.15.  Sorry for how long this bug has stood.  Huge props to @metamatt for the analysis and PR #1962.
Dupe #1079

**Comment by christopherthielen** [comment]
@JobaDiniz thanks for the plunker.   Here is your plunk updated to 0.2.15 code showing reloadOnSearch:
http://plnkr.co/edit/5OPoKUDnn98JiKFlyEYL?p=preview

**Comment by JobaDiniz** [comment]
Hi @christopherthielen 
I updated the plunker because it was not working... now it does (http://plnkr.co/edit/AUuOb3iDxrx75q7tBu0Q?p=preview)

cheers!

**Comment by JobaDiniz** [comment]
Big thanks! I've tested in my project and it works perfectly. :clap:

**Comment by j-walker23** [comment]
@christopherthielen you guys are kings! Thank you!
