### ISSUE TITLE
how to add dynamically value to Custom Data to State Objects

### ISSUE THREAD

**Issue by Rajafkvp** [angular-ui/ui-router#1805]
I have custom data for this i need to add roles dynamically from api (now values i have hardcoded but i need get from data base based on state name) how i can do this ?                                                example:- 
![image](https://cloud.githubusercontent.com/assets/10266752/6541406/3f11a6ba-c4f3-11e4-961e-055f6aac65cd.png)

**Comment by thak123** [comment]
yea it would be great if we can pass the collection of items /data to the state when we say #state.go('stateName',{'options'},data);

So main things would be not to pass the data via url, but they are passed as the state data

**Comment by RajMondaz** [comment]
how to add roles to the data object for each state from the  sql

**Comment by acollard** [comment]
@RajMondaz  Your example looks like a perfect place to use a resolve. Anywhere you need dynamic input to a state you should be using a resolve, not data.

```javascript
.state('app.state', {
    url: '/',
    resolve: {
        roles: ['myRoleService', function (myRoleService) {
            return myRoleService.getRoles(); // If you are calling some API this should return a promise with your roles array
        }]
    },
    views:{...}
}
```
These can be injected into your controller by asking for 'roles'.

@thak123 You can use params to pass dynamic data without them showing up in the url. Use the params option when registering the state.

Here is a quick example:
```javascript
.state('app.state', {
    url: '/',
    params: {
        someData: []
    }
}

$state.go('app.state', { someData:['Some', 'Array', 'Of', 'Data']});
```

@nateabele I really don't see the need to extend the Data feature. I would go so far as to ask if it is really needed. Considering we have resolves.

**Comment by nateabele** [comment]
> I really don't see the need to extend the Data feature.

@acollard I'm not sure yet. There may be cases where you already have the same data and don't want to reload it, but it might not make sense to build a whole separate service to broker and intercept redundant transactions.

Also, I could see case-specific situations where you might want to pass in data that would _override_ a resolve, etc., etc.

Needs more thought.

**Comment by acollard** [comment]
> There may be cases where you already have the same data and don't want to reload it, but it might not make sense to build a whole separate service to broker and intercept redundant transactions.

@nateabele The nice thing about resolves is you can do whatever you want. You can choose to load information from a service or just return some local information. 

```javascript
var someData = ['Hello', 'World'];
.state('app.state', {
    resolve: {
        justSomeData: function(){ return someData; }
    }
}
```

> Also, I could see case-specific situations where you might want to pass in data that would override a resolve, etc., etc.

Are you thinking it would prevent the resolve from running? I just think it would be simpler to just let the dev choose to do this logic in their resolve if they want it.

**Comment by nateabele** [comment]
> Are you thinking it would prevent the resolve from running?

Potentially, yeah.

> I just think it would be simpler to just let the dev choose to do this logic in their resolve if they want it.

The logic to define a state is centralized, whereas the logic to access a state is diffuse. Trying to override the one by the other would require tight coupling, or some form of in-band signaling (or a combination of the two), neither of which are clean or elegant solutions.
