### ISSUE TITLE
controller/view being shown for a second before failed resolve on back button

### ISSUE THREAD

**Issue by epelc** [angular-ui/ui-router#1806]
If you have a resolve that rejects the promise and you just load a new page it will not show the page or run the controller but if your on another page and hit the back button to go to a page which has a resolve it runs the controller and loads the page before the resolve. I don't think it should do this the docs say that controller aren't run until resolves return successfully so this seems like a bug.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
