### ISSUE TITLE
Animate a view with Angular/UI Router

### ISSUE THREAD

**Issue by Casti9l** [angular-ui/ui-router#1810]
Hi 

I'm newbie with UI Router. I tried to animate a ui-view in a ui-view.
http://plnkr.co/edit/Y0RGQXe1he1hQ9R0BhCY?p=preview

I have a class "view" for my effect, but this class don't work everywhere.
In my plnker exemple, i want animate build_txt.html with my css, but no effect.
If i tried add this class "view" in my index.html, it's work !

What's the problem ?
Thanks for the help ans sorry for my poor english.

**Comment by jforaker** [comment]
This is not an issue with UI Router. 
You need to add the "view" class to your `ui-view` element:

`<div ui-view class="view"></div>`

http://plnkr.co/edit/RYEnG5rTdEWf5X6PCmXQ?p=preview

**Comment by Casti9l** [comment]
Thank you for your reply.

But I don't want to apply this class has all my ui-view, but only ui-view page build.html
For apply this effect to build_txt.html content only

it's possible ?

**Comment by jforaker** [comment]
You probably need an `abstract` route and sub states. The below code sort of/kind works. best i could do in 2 minutes:

http://plnkr.co/edit/RYEnG5rTdEWf5X6PCmXQ?p=preview

I would suggest reading the docs a bit more and maybe github issues is not the best place to post questions about functional/working code.

**Comment by Casti9l** [comment]
sorry if this is not the right place to post, but it's difficult to find help about ui-router, I am beginner.

In your example, it works because you use a link to the effect.
But I wish that the effect is without <a> is possible?

**Comment by jforaker** [comment]
I don't really understand what you are trying to achieve. I am also not an expert on ui-router. Good luck friend.

**Comment by Casti9l** [comment]
When i click on "build", i want my div "My content" animates, only this div, not all ui-view.

thank you anyway.

**Comment by jforaker** [comment]
Seems like there is no need for ui-router in that case. you should refactor to NOT use ui-router, in my opinion.  this is a simple effect that can be achieved with minimal javascript/css. a few google searches should turn up an answer.

**Comment by Casti9l** [comment]
My structure is a little more complex than the plunker example, ui-router will help me.

But my class animation work on some ui-view (index.html) but not for others (build.html), I do not understand.

Anyway I thank you for allowing me to spend a little time, I continue my research.

**Comment by nateabele** [comment]
Yeah, sorry, the issue tracker is for bugs with UI-Router, not a support forum. Please take questions to StackOverflow, thanks: http://bit.ly/UIR-SOF

My suggestion for your issue would be to get it working without animation, then consult Angular's documentation for the `$animate` service, since that's really what you're looking for.

Best of luck.
