### ISSUE TITLE
Exceptions in DI resolve functions fail silently

### ISSUE THREAD

**Issue by Sequoia** [angular-ui/ui-router#1813]
:point_right: [Plnkr](http://plnkr.co/edit/eh3VJCi2HlvBpi6C285N?p=preview) :point_left:

## Setup
1. Configure a state that uses a controller & uses `resolve` to get some stuff before the controller is loaded
2. Throw an error from that `resolve` function

## Expected
Error is visible in console

## Actual
Error is suppressed, template doesn't load & the router seems to redirect to another route. This behavior is **baffling** when you encounter it during development.  There's *no* indication of where the problem is occurring, I just tried looked everything over 'til I caught it by chance.

**Comment by acollard** [comment]
I agree this is annoying, caught me a few times. This error is available through the $stateChangeError event.

During development I usually listen to this event and output the error to console.

**Comment by nateabele** [comment]
As posted in the other issue (just copying here to close it):

```
javascript
$rootScope.$on("$stateChangeError", console.log.bind(console));
```
