### ISSUE TITLE
Unable to run this application.

### ISSUE THREAD

**Issue by rajeshwar-fissionhq** [angular-ui/ui-router#1815]
I have cloned this repository and installed npm and bower dependencies with `npm install` and `bower install` and i tried to run this app using `grunt serve`, but it is saying 'Warning: Task "serve" not found. Use --force to continue.' I checked the `Gruntfile.js`, serve task is not there. Can some one please let me know how to run this application. If possible please provide the same information in the `README.md` file.

**Comment by nateabele** [comment]
There is no `serve` command configured. Use `grunt connect:sample` to view the sample application.
