### ISSUE TITLE
Make "/" and "" equal the same thing

### ISSUE THREAD

**Issue by timkindberg** [angular-ui/ui-router#182]
Sounds like everyone is on board with this. Make the use of "/" equivalent to using "" (empty quotes). See https://github.com/angular-ui/ui-router/issues/174#issuecomment-19330523

**Comment by moorthi07** [comment]
This will kill the HTML standard use of '#' navigation. Right now it is not working with #, every #identifier link is replaced to a #/identifier url. Can you guys stop messing html standards?!

**Comment by nateabele** [comment]
I'm pretty sure this is resolved (and, correctly) by the `$location` service.

**Comment by moorthi07** [comment]
are you saying, use $location instead of url like below?
 .state('contact', {
        url: '#contact-div',     // $location='#contact-div'

        templateUrl: ''
        
      })

**Comment by nateabele** [comment]
I'm saying that, under the hood, UI-Router uses the `$location` service.

**Comment by moorthi07** [comment]
I know. Just to make it easy,
How would you do this simple page with ng-ui when I DO NOT WANT TO or NEED TO chop all the <  div > into a separate .html file (I really don't understand why  should I have to have 100 .html files?)

http://www.codeply.com/render/DRBmOoChfM

**Comment by nateabele** [comment]
@eddiemonge Don't we basically have this now with being able to turn strict matching off?

**Comment by eddiemonge** [comment]
not sure. maybe? would need to test to verify
