### ISSUE TITLE
$state.go causing controller to instantiate twice

### ISSUE THREAD

**Issue by scriptsure** [angular-ui/ui-router#1821]
see this issue around on other cases.. but i am on 2.13 and stilll getting this issue. My code is very simple... $http request made then a transition is made to the view. During the process the controller gets hit twice.

              .state( 'dash', {
                  url: "/home/dashboard",
                  templateUrl: "/home/dashboard",
                  controller: "DashboardController",
                  controllerAs: "dash"
              } )

in the controller:

    var search = this;
    search.filter = "";
    search.results = [];
    search.showAll = true;
    search.searching = false;
    search.data = null;
    search.messageId = "";

    $state.go( 'dash' );

This is happening all over the application though... WHAT IS GOING ON???? 

And no i do not have the ng-controller attribute set...... There is a def bug because i did walk through the code and it hits the transitionto twice.....

seems to be getting called a second time here:

        if (locals.$$controller) {
          locals.$scope = scope;
          var controller = $controller(locals.$$controller, locals);
          if (locals.$$controllerAs) {
            scope[locals.$$controllerAs] = controller;
          }
          $element.data('$ngControllerController', controller);
          $element.children().data('$ngControllerController', controller);
        }

**Comment by daw451-duplicate** [comment]
just as a follow up... not sure why this is... but when i placed a name on the attribute then it works. For  example:

ui-view name="mainview"

Why is that? I thought we  did not have to name them unless we are using multiple views on the same page???!?!??!


Anyone??? Thanks in advance

**Comment by daw451-duplicate** [comment]
once i placed a name on the ui-view it no longer ran the code more than once....

aaron

**Comment by skeefo** [comment]
Probably I have the same problem.
In sign-in state controller I have
```
$rootScope.$broadcast(AUTH_EVENTS.loginSuccess);
$state.go('home');
````

And in router 
```
.state('home', {
   url: '/',
   templateUrl: 'states/home/home.html',
   controller: 'HomeController as Home'
});
```

I have no "ng-controller" in my home template, but controller instantiates twice.
Is it bug?

**Comment by mizrachiran** [comment]
Thank you for the workaround!

**Comment by christopherthielen** [comment]
I realize this issue is really old.  
If this is still a problem, try updating to 0.2.15 (and 0.2.16 will be out soon).  
Then, post a plunker that demonstrates how to get the controller to instantiate twice.  That's not expected.

http://bit.ly/UIR-Plunk
