### ISSUE TITLE
Redirect after URL changes on $stateChangeStart event?

### ISSUE THREAD

**Issue by Vayvala** [angular-ui/ui-router#1825]
Hello,
I have some logic on the `$stateChangeStart` event, to check if state with params (URL) is correct. If it is not I want to redirect it to the `404` view:

```
event.preventDefault();
$state.go('404');
```

But this solution is incorrect, because if you are moving between states, and `404` error occurs, it redirects to the `404` view, but URL is still of the working page, because it is a `$stateChangeStart` event (it did't move to the state with a problem and it didn't change the URL). **It is probably because of the `event.preventDefault()`.**

I can't use `$stateChangeSuccess` event.

So what should I use instead of `event.preventDefault()` to achive my goal?

**Comment by acollard** [comment]
@Vayvala Are you checking that you are not going to 404 before calling event.preventDefault() inside the $stateChangeStart event?

```javascript
if(newState.name!='404'){
 event.preventDefault();
 $state.go('404');
}
```

If you don't then you are preventing your own transition to 404.

**Comment by Vayvala** [comment]
@acollard `404` state has no URL, problem is, because of `$stateChangeStart` and `event.preventDefault()` user sees `404` page with the **working** URL. It is because `event.preventDefault()` didn't let the URL to change.

**Comment by acollard** [comment]
@Vayvala Now I understand what you are trying to accomplish. You want to transition to the 404 state but show the incorrect url.

Why not just have a catch all state like this. Just make sure it is last.
```javascript
app.config(function($stateProvider) {
  $stateProvider.state({ name: '404', 
    url: '/*location', 
    controller: ['$stateParams', function($stateParams) { this.location = $stateParams.location; }], 
    controllerAs: 'error',
    templateUrl: '404.html'});
});
```

Here is a full working plunker. http://plnkr.co/edit/zYl9Ekdoal3YrsdSqtfk

No need to use any state events.

**Comment by AntiFreez** [comment]
I have a similar problem. I want to create "404" state and "forbidden" state too. Also, the order of $stateProvider.state is important: all states after state with 
```javascript
url: '/*location' 
```
will be treated as "404" state. How can I solve this case?

**Comment by acollard** [comment]
@AntiFreez The 404 state is being used as a catch all. UI-Router processes the states in the order they are registered, so anything after our catch all state will not be accessible via the url. You will want to register the 404 state last. Forbidden would be treated like any normal state, although I wouldn't have it accessible via a url. You'll need to use some code to redirect the user to the forbidden state when the user is not authorized.

@Vayvala and @AntiFreez, these types of questions should be on StackOverflow. Github issues are reserved for actual issues with the framework and feature requests. Not user questions. Thanks.

**Comment by AntiFreez** [comment]
@acollard, I agree with you that this question looks like a StackOverflow question. But I found https://github.com/angular-ui/ui-router/pull/967. Therefore I decided to ask this question here. Сurrently, there is no way to prevent $stateChangeStart or $stateChangeError events, save url and go to specific state. May be it will be helpfull to have ability to change url and redirect to such kind of states (like forbidden).

**Comment by schmkr** [comment]
I recently found a solution for this by using a function for `$urlRouterProvider.otherwise`, like this:

```
angular.module("app.example", ["ui.router"])
.config(function($stateProvider, $urlRouterProvider) {
  
  $stateProvider.state("404", {
        templateUrl: "errors/notfound.tpl.html",
        data: {
            authorizationRequired: false,
            permissionsRequired: [],
            bodyClass: "error"
        }
    });
    
    // show a not found error if route is unknown, but keep the original url
    $urlRouterProvider.otherwise(function($injector) {
      $injector.invoke(function($state) {
          $state.transitionTo("404", {}, false);
      });
    });
});
```
