### ISSUE TITLE
Ui-route not working

### ISSUE THREAD

**Issue by maryampashmi** [angular-ui/ui-router#1826]
I got in trouble with ui-route. Any of my routing is not working. 

This is what i have in my application:
1) i defined it in my Index after angular version v1.3.13.
<script src="bower_components/angular/angular.min.js"></script>
<script src="bower_components/angular-ui-router/release/angular-ui-router.min.js"></script>
2)
angular.module('myApp', ['ng', 'ui.router', 'formly','ngRoute', 'formlyBootstrap'])
.config(function ($stateProvider,$urlRouterProvider) {
    $urlRouterProvider.otherwise("blank.html");
    $stateProvider
.state('poll.legal',{
            url:"/legal",
            templateUrl:"partials/poll.legal.html",
            controller: 'pollLegalCtrl as Form'
        })
        .state('poll.operational',{
            url:"/operational",
            templateUrl:"partials/poll.operational.html"
        });
});
3)in index i used  
-- div ui-view></div--

I have this error all the time:
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.13/$injector/modulerr?p0=myApp&p1=Error%3A%…%2FCSPcomparision%2Fbower_components%2Fangular%2Fangular.min.js%3A17%3A381)    angular.js:38

Please help me how i can rid of this error.

Thank you.

**Comment by nateabele** [comment]
http://bit.ly/UIR-SOF
