### ISSUE TITLE
alive multiple state in ui router

### ISSUE THREAD

**Issue by mdshohelrana** [angular-ui/ui-router#1828]
Hi, how can i maintain multiple state at a time, in the ui route I have seen that when one state is called by go or transitionTo then execute onEnter or onExit But my requirement is onExit method won't fire when I called second state. is it possible? I want to fire onExit method programmatically and manage popup window side by side. i.e multiple states will be alive not one by one.

Thanks.

**Comment by acollard** [comment]
@mdshohelrana Check out https://github.com/christopherthielen/ui-router-extras.

It supports sticky states which may get you what you need.

**Comment by mdshohelrana** [comment]
@acollard Thanks
