### ISSUE TITLE
<a > Link colors ui-sref strange behavior on load

### ISSUE THREAD

**Issue by onlyskyguy** [angular-ui/ui-router#1829]
I've been experiencing a weird issue and I wonder if anyone has seen something similar:

Seemingly at random, <a> links that use ui-sref will load without the correct css style color.

For example, I have a list with navigation links in it, sometimes on page load, some of the links will be black instead of white as they're supposed to be. If I click the links, or do some action on the page (like open an offcanvas panel etc) they'll usually switch over to the correct color. 

I think this is a UI-router issue because it's only happening on links with ui-sref. Elements like buttons that use ui-sref don't do this. 

Any insight would be appreciated!

**Comment by fabiosussetto** [comment]
try and set the href attr to an empty string, like so:

<a ui-sref="blah.bluh" href="">Yo!</a>

**Comment by seavor** [comment]
Reporting the same issue, and confirmation that @fabiosussetto's empty href-tag fix does seem to work.

Additionally, to anyone who ends up responsible for fixing this bug, it only seems to occur in Google Chrome, and only outside of the incognito window. Inside of the incognito window, the font colors render as expected.

**Comment by onlyskyguy** [comment]
That's definitely it. Adding href=" "  (an empty string) fixed this. Thanks.

**Comment by eddiemonge** [comment]
Its probably how the browser renders links with no href. How are you defining the CSS for the links?
