### ISSUE TITLE
Controller being called twice

### ISSUE THREAD

**Issue by btmdave** [angular-ui/ui-router#1830]
I'm running angular 1.3.15 and ui-router 1.2.13 and I'm getting controllers that are being called twice and I can't seem to nail down the cause, for example:

```
angular.module('App').config(function ($stateProvider, $urlRouterProvider, $locationProvider) { 
    $stateProvider
      .state('object_test', {
        url: '/test'
        , resolve: {
          auth : AppCtrl.authResolver(true),
          test: function() {
            console.log('resolve')
          }
        }
        , controller: 'ObjectListControllerTest'
      });

})
.controller('ObjectListControllerTest', function () { 
  console.log('test')
}) 
```
 The `test` function in the resolve is only being called once, however the controller is actually being called twice.  I've tried listening to the statechange and it's not changing without me knowing or anything.. it's loading up once, but controller is fired twice.  
Any ideas? or any idea how I can debug this?

Thank you

**Comment by ivanhosgood** [comment]
Can you include the HTML where the ui-view directive is used? Are you using the ng-controller directive in you view?
Do you actually have multiple ui-view directives? This is typical if you have used the directive within an ng-repeat.

**Comment by btmdave** [comment]
Yup! I found it... it as multiple ui-view's... thanks

**Comment by AlexZeitler** [comment]
Guys, you just saved my ass :+1:

**Comment by ivanhosgood** [comment]
Glad to be able to help :)
