### ISSUE TITLE
how to implement a parent state callback function when exiting child state modal ?

### ISSUE THREAD

**Issue by kbjp** [angular-ui/ui-router#1831]
Hi,

Following ui-router FAQ "open a dialog modal", I've implemented: 
1) a parent state which displays in a grid a collection of objects
2) a child state which allows to create a new object or to edit an existing object for that collection. 

Note: the reason for using nested states here is to guaranty that collection grid is still displayed in the background while editing one of the collection objects. 

Everything works fine except that ,when I exit the modal/child state through "$state.go('^');" (as per ui-route FAQ example) I want to let my parent state know that it should refresh the grid linked to the collection (i.e. I need some kind of callback on the parent state):

How can such parent state "callback" be achieved ?
(Is monitoring the "$stateChangeSucess" event in my parent controller the way to go ?)

Thank you very much in advance for your expertise.
Regards
kbjp

**Comment by acollard** [comment]
@kbjp I don't know if it is the best way, but we do this as well (exact same scenario). Just make sure you destroy the listener when you leave the parent state.

Put something like this in your parent controller. In the case below the Directory.Users state is the parent.
```javascript
  var remove = $rootScope.$on('$stateChangeSuccess', function(event, toState, toParams, fromState, fromParams) {
      if (toState.name == States.Directory.Users.name) {
          this.listUsers();
      }
  });
  $scope.$on('$destroy', function() {
      remove();
  });
```

**Comment by kbjp** [comment]
thanks a lot for your feedback.

**Comment by eddiemonge** [comment]
Closing since it seems resolved and its also old
