### ISSUE TITLE
TypeError: null is not an object (evaluating '$state.$current.locals[name]')

### ISSUE THREAD

**Issue by sabrehagen** [angular-ui/ui-router#1833]
We collect client side errors via stacktrace.js and log them to our server. Recently I have seen this error in our logs. I can't reproduce it in Chrome 41, IE 11, or Firefox 35. I'm reporting it here as it seems to be an error internal to ui-router, not my own error. We are using ui-router v0.2.13.

Here is the stack trace in its entirety.

"errorUrl": "https://ourwebsite.com/?org=bluecube",
   "errorMessage": "TypeError: null is not an object (evaluating '$state.$current.locals[name]')",
   "stackTrace": [
       "updateView@https://ourwebsite.com/js/angular-ui/angular-ui-router.js:485:159",
       "https://ourwebsite.com/js/angular-ui/angular-ui-router.js:482:584",
       "$broadcast@https://ourwebsite.com/js/angular/angular.min.js:114:332",
       "load@https://ourwebsite.com/js/angular-ui/angular-ui-router.js:474:49",
       "https://ourwebsite.com/js/angular-ui/angular-ui-router.js:469:1324",
       "d@https://ourwebsite.com/js/angular/angular.min.js:35:41",
       "proceed@https://ourwebsite.com/js/angular-ui/angular-ui-router.js:39:327",
       "invoke@https://ourwebsite.com/js/angular-ui/angular-ui-router.js:39:228",
       "https://ourwebsite.com/js/angular-ui/angular-ui-router.js:37:91",
       "resolve@https://ourwebsite.com/js/angular-ui/angular-ui-router.js:41:101",
       "https://ourwebsite.com/js/angular-ui/angular-ui-router.js:469:1436",
       "r@https://ourwebsite.com/js/angular/angular.min.js:7:396",
       "resolveState@https://ourwebsite.com/js/angular-ui/angular-ui-router.js:469:739",
       "transitionTo@https://ourwebsite.com/js/angular-ui/angular-ui-router.js:455:138",
       "go@https://ourwebsite.com/js/angular-ui/angular-ui-router.js:450:318",
       "https://ourwebsite.com/js/app.js:1:12871",
       "d@https://ourwebsite.com/js/angular/angular.min.js:35:41",
       "https://ourwebsite.com/js/angular-ui/angular-ui-router.js:458:122",
       "F@https://ourwebsite.com/js/angular/angular.min.js:100:187",
       "https://ourwebsite.com/js/angular/angular.min.js:101:351",
       "$eval@https://ourwebsite.com/js/angular/angular.min.js:112:68",
       "$digest@https://ourwebsite.com/js/angular/angular.min.js:109:173",
       "$apply@https://ourwebsite.com/js/angular/angular.min.js:112:405",
       "h@https://ourwebsite.com/js/angular/angular.min.js:72:460",
       "u@https://ourwebsite.com/js/angular/angular.min.js:77:796",
       "onreadystatechange@https://ourwebsite.com/js/angular/angular.min.js:79:25",
       "nrWrapper@https://ourwebsite.com/?org=bluecube:1:22757"
   ],
   "cause": ""
}

**Comment by Jaco-Pretorius** [comment]
:+1: We are getting the same issue, I also can't repro

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
