### ISSUE TITLE
Add $stateEnter and $stateExit events.

### ISSUE THREAD

**Issue by andreytkachenko64** [angular-ui/ui-router#1835]
Would be nice to have $stateEnter and $stateExit events. I have been needed it while implementing confirmDialog flag in routes which allows me to open the route in a popup.

**Comment by cdownie** [comment]
stateProvider has onEnter and onExit events

http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$stateProvider

**Comment by andreytkachenko** [comment]
I mean onExit and onEnter events broadcasting from scope up to $rootScope similar to $stateChangeStart event.

**Comment by nateabele** [comment]
There is a mechanism that will provide equivalent functionality in an upcoming release.

**Comment by christopherthielen** [comment]
We're not going to maintain any more `$rootScope` events. However, you can implement this yourself:

```js
app.run(($transitions, $rootScope) => {  
  $transitions.onEnter({ }, function(transition, state) {
    $rootScope.$broadcast("$stateEntering", state, transition);
  }

  $transitions.onExit({ }, function(transition, state) {
    $rootScope.$broadcast("$stateExiting", state, transition);
  }
});
```
