### ISSUE TITLE
Setting stateParams in state declaration

### ISSUE THREAD

**Issue by piernik** [angular-ui/ui-router#1836]
Can I set $stateParams in state decalration to use it in resolve?
Ex:
```
 .state('app.state', {
    url: '/',
	customStateParams: {
		param:'myParam',
	},
	resolve: {
		myResolve: ['$stateParams', function ($stateParams) {
			//here is my $stateParams.param=="myParam"
			return true;
		}]
	}
}
```
I'm using complex resolve function that is stateParams depenedent, and I need to set one param.

**Comment by acollard** [comment]
@piernik You can have stateParams that aren't defined in the url by adding them to the params option. Check out params here http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$stateProvider

Here is an example:

Registration
```javascript
.state('app.state', {
    url: '/',
    params: {
        message: 'Default Message'
    },
    resolve: {
        getMessage: ['$stateParams', function ($stateParams) {
            return $stateParams.message;
        }]
    }
}
```

Navigating
```javascript
$state.go('app.state', { message: 'Hello World' }
```

The getMessage resolve will return 'Hello World' in this example.

**Comment by piernik** [comment]
Thanks very much
