### ISSUE TITLE
Modal controllers instantiating multiple times

### ISSUE THREAD

**Issue by anthonyhoman** [angular-ui/ui-router#1837]
I have an issue across all of my bootstrap modals that I could really use some help with.  The controller code for the modal content is instantiating once for every time the modal is clicked.  The first time I open the modal, the controller runs once.  The second time it runs twice, the third time it runs three times, etc.

Here is a [Plunker] (http://plnkr.co/edit/ioDFh4d8c411vQjIGwqp?p=preview)  The issue IS NOT reproduced in this Plunker.  But the pattern you see is exactly like my real code.

I know without reproducing it you can't give me an exact fix.  I'm looking for any pointers.  Anything you can think of that might cause controller code in modals to sort of "accumulate" like this?  Thanks for any help.

**Comment by acollard** [comment]
@anthonyhoman Why not just put a break point in your controller then look at the stack trace. Your constructor will likely be getting called by the ui-view directive.

Hard to help without being able to repro.

**Comment by anthonyhoman** [comment]
Thanks for the fast reply.  The breakpoint isn't telling me much other than pointing to the same area of code that I see in a few other issue reports here.  It seems like the key is that this condition is not met because the "locals" do not match:

if (!firstTime && previousLocals === latestLocals) return; // nothing to do

That eventually causes this line to execute:

var controller = $controller(locals.$$controller, locals);

The "previousLocals" and "latestLocals" are large multi-field objects, so it's hard to see what exactly doesn't match.  I tried removing the dynamic stateParams and I still see the same behavior.  I'm running out of ideas.

**Comment by nateabele** [comment]
> The issue IS NOT reproduced in this Plunker.

Please let me know when it is.

**Comment by anthonyhoman** [comment]
I upgraded from angular-bootstrap v0.10.0 to v0.12.1 and the problem went away.

**Comment by nateabele** [comment]
:^5:

**Comment by 31piy** [comment]
I had a similar problem, but I was using Angular Strap instead of Bootstrap UI. My controller was instantiating multiple times because I was calling `modal.hide()`. As soon as I changed it to `modal.destroy()`, everything started working fine.
