### ISSUE TITLE
Add "Log All Errors" option

### ISSUE THREAD

**Issue by Sequoia** [angular-ui/ui-router#1839]
When you are working on your Angular application & you make some changes & all the sudden your page doesn't show anything and there's no error output anywhere, it's a good bet `ui-router` is unhappy about something. I understand you're upset, `ui-router`, but I need you to *talk to me!!* I'm not a mind-reader-- I'll do what I can to make things right for you but you've got to let me know what the problem is!

Anyway this scenario is frustrating as %(&*# and tracking down this sort of error is a royal PITA because you don't get any starting point for your search.

# Proposal

Add a devmode/"Log **All** Errors" option so if you hit this problem during development you can tell `ui-router` to STOP FAILING SILENTLY!!!! :smile: tia!

**Comment by nateabele** [comment]
`$rootScope.$on("$stateChangeError", console.log.bind(console));` ;-)

**Comment by Sequoia** [comment]
Ty nate. To clarify for anyone coming after me, the line of code nate posted should be added to the `run` block of your application, which runs after config but before controllers are loaded.

**Comment by aphelionz** [comment]
The master.
