### ISSUE TITLE
Bug: $watchers (on the $scope of the old controlelr) are still run while the user is navigating away

### ISSUE THREAD

**Issue by Wizek** [angular-ui/ui-router#1840]
Plunkr: http://plnkr.co/edit/uJSdaS0PzYyOX439Ng8q?p=preview

### Current faulty behaviour:
Given you have loaded up the plunker with preview
When you click the link with the text `#/b`
Then you see `$location.url() => /b?foo=fooDefault&bar=barDefault`

### Expected behaviour:
Given you have loaded up the plunker with preview
When you click the link with the text `#/b`
Then you should see `$location.url() => /b?bar=barDefault`

### Further details:
This is a narrowed-down example of something I am using in one of my apps to synchronize some values between the $scope of a controller and the query parameters. It works perfectly while the user stays in the same $state. But when they navigate away to another state, the $watchers responsible to keep the two state in sync run even after they have clicked the url to the other state, which results in an erroneous call to `$location.search(newVal)` which contaminates the new path the user navigated to.

### Possible fix:
Could you remove $scope.$watchers (e.g. through destroying the scope) when the user navigates away?

**Comment by nateabele** [comment]
> Could you remove $scope.$watchers (e.g. through destroying the scope) when the user navigates away?

I don't understand the question.

The only watcher in UI-Router is for `uiSref` parameters, which should not affect you here. Angular fires watchers on any change, and because you have 2 watchers reading and writing the same data, you've basically set up a race condition which is what's producing the results you're seeing.

You're better off setting some flag in `$stateChangeStart` and ignoring updates to `$location.search()` based on that.

This is not a UI-Router issue, sorry.

**Comment by Wizek** [comment]
I think you misunderstand.

Ui-Router is managing the lifecycle of `ctrl1` and `ctrl2`, wouldn't you aggree?

As specified here:
```
$stateProvider
  .state('a', {
    url:'/a',
    template:'<input ng-model="queryParams.foo"/>',
    controller: 'ctrl1',
  }) 
  .state('b', {
    url:'/b',
    template: '<input ng-model="queryParams.bar"/>',
    controller: 'ctrl2',
  })
```

So UI-Router decides when exactly these controllers get instantiated and/or destroyed, or is that not the case?

**Comment by nateabele** [comment]
> So UI-Router decides when exactly these controllers get instantiated and/or $destroyed, or is that not the case?

Yes and no; there's some necessary overlap during the transition. The actual lifecycle of the controllers & scopes is handled internally by Angular.

This is what happens when you use shared mutable state with nondeterministic event ordering. Not sure what else to tell you.

**Comment by Wizek** [comment]
Now you've made me curious. You are telling me that it is necessary for `ctrl2` to get instantiated before `ctrl1` gets destroyed? Why is that?

**Comment by nateabele** [comment]
Feel free to alter the source and observe which tests fail. I'll be happy to indulge your curiosity when I don't have a +150 unread notification queue to get through.

**Comment by Wizek** [comment]
Scratch my last question, there is no overlap between the controllers' lifecycle according to this quick test: http://plnkr.co/edit/y3MMCpimUID7LEC5xqpu?p=preview

**Comment by Wizek** [comment]
Would you be open to a pull request that passes all current tests and also passes my scenario?

**Comment by Wizek** [comment]
I've created a failing unit-test scenario too:

https://github.com/Wizek/ui-router/commit/e16075c9ef9de820e8f27eeffb2e46d4b1a4afd1

```
PhantomJS 1.9.8 (Mac OS X) state .reload() should not fire $watchers on old scope when navigation is under way FAILED
	Expected 'controller;$watchTriggered:initialValue;$watchTriggered:changedValue;destroyed;controller;'
	to be 'controller;$watchTriggered:initialValue;destroyed;controller;'.
```

I'm at the moment looking for a way I could make this pass without introducing any regressions.
@nateabele Do you think you would have some time soon to help me? Or if you think this is a bad direction maybe we could chat a bit so I could understand why you think that?

**Comment by nateabele** [comment]
> Would you be open to a pull request that passes all current tests and also passes my scenario?

I'm not opposed to it if whatever you come up with makes sense. Honestly though, I think the use of the `$animate` API in `uiView` requires at least some overlap between the two controllers.

The other thing you could try to validate this is attempting to reproduce your issue with `ngRoute` and `ngView`.

> Do you think you would have some time soon to help me? Or if you think this is a bad direction maybe we could chat a bit so I could understand why you think that?

At first blush the test seems fine (although if you want that merged, you should read the contributor guidelines and fix the commit message). Unfortunately my schedule is pretty packed at the moment, but I can point you in the direction of where to look: https://github.com/Wizek/ui-router/blob/master/src/viewDirective.js#L220 & https://github.com/Wizek/ui-router/blob/master/src/viewDirective.js#L278

Feel free to post back here with whatever progress you make and @ me, and I'll take a look.

**Comment by Wizek** [comment]
Yes, I am planning on changing the commit message, I just wanted to push something so I could link to it.

The strange thing is that there is no overlap whatsoever. 
If there was overlap, I would expect the log at the end of the spec to contain: 
`controller;$watchTriggered:initialValue;$watchTriggered:changedValue;controller;destroyed;`

but it instead contains:
`controller;$watchTriggered:initialValue;$watchTriggered:changedValue;destroyed;controller;`

so, by the time execution gets to
https://github.com/Wizek/ui-router/blob/master/src/viewDirective.js#L220
it is too late already, as at this point the log variable contains:
`controller;$watchTriggered:initialValue;$watchTriggered:changedValue;`

Right now I am trying to find a place where log only contains 
`controller;$watchTriggered:initialValue;` so I can try to
```
if (currentScope) {
  currentScope.$destroy();
  currentScope = null;
}
```
there.

**Comment by Wizek** [comment]
@nateabele Could it be that you handle the change of `$location.url('/S2');` asynchronously? E.g. `$evalAsync` or `$applyAsync`? I haven't found such calls in your code yet, but look at this:

So I tried to see the call stack for when `currentScope.$destroy()` is called:
![karma_debug_runner](https://cloud.githubusercontent.com/assets/491672/6858057/dc4fb3f0-d40b-11e4-9169-c7fe1d360b10.png)

To my surprise, it didn't originate from `$location.url('/S2');`, but rather `$rootScope.$apply();`
![karma_debug_runner](https://cloud.githubusercontent.com/assets/491672/6858067/f9b3729c-d40b-11e4-9069-e90417dd4a25.png)

Some more digging shows that that is because this function has been placed on the asyncQueue:
![karma_debug_runner_and_karma_debug_runner](https://cloud.githubusercontent.com/assets/491672/6858103/2c977f00-d40c-11e4-89ca-0f36615794eb.png)

@nateabele Do you know where is it being put to the async queue?

*Damn you mutable state that you can't be traced through the stack!*

**Comment by Wizek** [comment]
I think it is due to using $q. And $q pushes to async queue internally :(

**Comment by Wizek** [comment]
But I am still looking for where this happens, even if it is due to $q. I have an idea.

**Comment by Wizek** [comment]
found it, it is right here: https://github.com/Wizek/ui-router/blob/master/src/state.js#L1054

**Comment by Wizek** [comment]
Found a culprit and a possible solution.
It seems Angular handles any changes to location with a delay (puts the handler on the asyncQueue).
Possible workaround: 

```
$(window).on('hashchange', function () {
  $rootScope.$apply()
})
```
I wonder what the implications might be. It also might be a good idea to try to reproduce with `ng.router` and if reproducible, then try to solve the issue there.

**Comment by Wizek** [comment]
@nateabele Btw, before I go too far into the rabbit hole and solve an "XY problem", what is the ui-router-cannonical way for achieving what my intention was with the plunkr? That is to bind a $scope variable to  a queryParameter with two-way data binding?

```
/path/to/state?foo=hello
<input ng-model="queryParams.foo" />
```

**Comment by Wizek** [comment]
Asked on StackOverflow if there might be a better way:
http://stackoverflow.com/questions/29299823/is-there-a-canonical-way-to-sync-query-params-in-the-url-angular-ui-router-wit

**Comment by nateabele** [comment]
> [W]hat is the ui-router-cannonical way for achieving what my intention was with the plunkr? That is to bind a $scope variable to a queryParameter with two-way data binding?

The canonical way would be to bind to a value in `$stateParams`, since `$stateParams` is managed by synchronously by UI-Router.
