### ISSUE TITLE
Readme md file insight - please indicate versions of compatibility.

### ISSUE THREAD

**Issue by MatteoNY** [angular-ui/ui-router#1841]
It would be great if  the readme file in the .git repository could indicated the version(s) of AngularJS it is compatible with. The link to Download 0.2.13 is good to know for the local version of the source but does not help unless there is a notice of compatibility, for example, does version 0.2.13 support AngularJS 1.3 or above up-to 1.5?

NICE-TO-HAVE info: Typescript 1.4 supported.

This site is not alone, no blame here just insights that I hope will help the future as we move towards Angular2.

Best!

**Comment by eddiemonge** [comment]
The bower.json file has the required version: https://github.com/angular-ui/ui-router/blob/master/bower.json#L6

**Comment by eddiemonge** [comment]
What does TypeScript 1.4 support mean exactly?

**Comment by MatteoNY** [comment]
Greetings Eddie,

It was a general comment regarding compatibility with the future use of Typescript 1.5 for Angularjs 1.x. It would a nice to know what version works with 1.2 or if it makes no difference.

It's an old post.
Thanks for your response.

Best,
Matt
