### ISSUE TITLE
$state.go doesn't change the URL

### ISSUE THREAD

**Issue by gaui** [angular-ui/ui-router#1842]
I'm using v0.2.13. I have the following states:

	$stateProvider.state('home', {
			url: '/',
			templateUrl: 'home.html',
			controller: 'HomeController'
		})
		.state('shipments', {
			url: '/shipments',
			templateUrl: 'shipments.html',
			controller: 'ShipmentsController'
		})
		.state('shipments.search', {
			url: '/search/:query'
		});

When I call $state.go from HomeController it goes to ShipmentsController, like supposed to, but it doesn't change the URL.

	$state.go('shipments.search', { query: $scope.shipmentsQuery });

It switches to the correct state, but the URL remains `/`. Why doesn't it change the URL to `/shipments/search/:query` ?

Even if I try:

	$state.go('shipments.search', { query: $scope.shipmentsQuery }, { location: true });

It still doesn't change the URL. Is this a bug or am I doing something wrong?

**Comment by nateabele** [comment]
If you don't know whether you're doing something wrong, please post a question to StackOverflow (see http://bit.ly/UIR-SOF). If you're sure a behavior is unexpected, please post a link to a plunkr that reproduces the issue.

**Comment by gaui** [comment]
That's a bit orthodox and rude, don't you think? I'm reading the docs and it says location is default true in options object for $state.go. That means it should change the location/URL when called, but it doesn't. Doesn't that sound like a bug to you?

I'm sorry. I'll provide a plunkr.

**Comment by nateabele** [comment]
> That's a bit orthodox and rude, don't you think?

Not trying to be rude. Look at the issue queue and you'll see why that's the policy.

**Comment by gaui** [comment]
Ok I'm sorry. I'll try StackOverflow. :)

**Comment by gaui** [comment]
I created this plunkr. It works correctly in this example, so there is something different in my application.

http://plnkr.co/edit/JyJAEZy7zp8gi9e3ZqJ4?p=preview

**Comment by gaui** [comment]
The problem was logic in my code, I was calling `$state.go` from another controller, then calling `$state.go` again (accidentally) in that controller. This was not a bug in UI-Router. Closing this issue.

**Comment by manuelfernando** [comment]
I had the same issue, even this works well for Firefox and Safari but not for Chrome, this trip isn't angular but works very well 

window.location = '/path';
