### ISSUE TITLE
Link function of directive in default content is invoked triple times 

### ISSUE THREAD

**Issue by jacksky007** [angular-ui/ui-router#1843]
I have a very simple app and use ui-router to extract some params. So I put my template in `<ui-view></ui-view>` directly and provide neither `template` nor `templateUrl`. As a result, the link function of my own custom directive is invoked triple times which should be invoked once only. If I move the default content to a html file and add `templateUrl`, everything works fine. Can anyone help if I want to keep the default content in `<ui-view></ui-view>`.

This is plnkr.
http://plnkr.co/edit/R5Lei0dlpGXCdX6W8wnN?p=preview

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by jacksky007** [comment]
@eddiemonge Thanks. Maybe I will try 1.0 later.
