### ISSUE TITLE
Unable to render data after statechange to view

### ISSUE THREAD

**Issue by ganeshkbhat** [angular-ui/ui-router#1846]
I am using a search input in home and /search url (differ UI-views both with same search template[header]) and on hitting search it goes to /search/:parameter url. The controller for home/search and all views are same.

After changing states, I am able to catch the parameter and do ajax request (in $stateChangeSuccess). But the data assigned to scope variables in $stateChangeSuccess are not being rendered to view template(content) after .transitionTo/.go from /home header. I have seen onEnter of $state, but it doesnot seem to work right for me. Its a small function of 10 lines of code and am not using service for onEnter.

home/search route -> SEARCH -> CHANGE STATE -> RUN change state function (works) -> RENDER view(does not work?)

**Comment by ganeshkbhat** [comment]
On a simpler note, I am not able to pass (above issue) or keep previous state values intact when passing through different states. Is destroy called automatically? then I am sure there must be a render as well. Do I need to work around.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
