### ISSUE TITLE
RFC: directives for $state.is() and $state.includes() functionality

### ISSUE THREAD

**Issue by lukewestby** [angular-ui/ui-router#1847]
I've run into a couple situations where I'd like to conditionally add or remove some element in the DOM within a separate view based on the current state either being included by or equal to a particular state. Usually the area of the view I want to manipulate in this way is not large enough to justify creating a ui-view and managing its configurations. It would be really great for these cases to have something along the lines of `ui-state-is="some.state"` which defers to `$state.is()` and then transcludes content based on the result, as well as something similar for `$state.includes()`.

If anyone feels this would be beneficial I would be more than happy to implement. Thanks!

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
