### ISSUE TITLE
AngularJS UI Router data persists when navigating from grand-child to parent

### ISSUE THREAD

**Issue by budhrg** [angular-ui/ui-router#1848]
Please have a look at this question:

http://stackoverflow.com/questions/29366673/angularjs-ui-router-data-persists-when-navigating-from-grand-child-to-parent

**Comment by ganeshkbhat** [comment]
Right. I believe thats how its supposed to work, I guess, correct me if I am wrong. I am not able to keep that alive with parent or nested states within child states when using $state.go/transtitionTo for different child states using same data. Its lost when moving across states. I am trying to work around using a service and broadcast. Can you comment if this makes sense to you? It will save me lines of code. https://github.com/angular-ui/ui-router/issues/1846

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
