### ISSUE TITLE
how to test if a state's requested controller is actually instantiated?

### ISSUE THREAD

**Issue by jmcmichael** [angular-ui/ui-router#1850]
I'm writing unit tests for the various ui-router state configurations for an app. I would like to test if the controllers named in state configuration objects are actually instantiated and have the resolved dependencies successfully injected.

I have tried a variety of methods to obtain a reference to the controller within a karma/mocha unit test, but to no avail. I have found that

```javascript
$state.$current.controller
```
when used in a state containing a named function just returns a string of the name of the function requested. If a controller is directly defined on the state config object, it returns a reference to the function.

I've been through every ui-router testing doc/blog post/article that I can find, but none of them appear to address this problem. Basically I just want to get a reference to the requested controller and/or its scope object after the controller has been instantiated and injected with the state's resolved dependencies so I can test if everything is instantiated correctly.

I've implemented a solution that feels like a total kludge, by forcing a state change to the intended state (actually a child state b/c I'm testing an abstract state), getting the resolved deps from the globals object, and manually instantiating the controller using $controller:

```javascript
      // instantiate GenesViewController using resolved deps from event.genes state
      goFromState('initial').toState('events.genes.child', { geneId: 238 });
      expect($state.$current.name).to.equal('events.genes.child');
      var deps  = $state.$current.parent.locals.globals;
      scope = $rootScope.$new();
      GenesViewController = $controller('GenesViewController', {
        $scope: scope,
        Genes: deps.Genes,
        MyGeneInfo: deps.MyGeneInfo,
        gene: deps.gene,
        myGeneInfo: deps.myGeneInfo
      });
```
Is there a better way to do this?

**Comment by eddiemonge** [comment]
It should be enough to test the resolves, the current (not the lack of `$`) name and that the controller is a string or function. You could always move the controller to a named one to make it easier to test.

If you do come up with something better, write it up in a blog post because others will probably find that useful and we can tweet it or link it or something.
