### ISSUE TITLE
Dynamic states creating

### ISSUE THREAD

**Issue by Tallyb** [angular-ui/ui-router#1851]
Is there a way to get hold of the $stateProvider within a controller / service so I can generate states dynamically?

**Comment by nateabele** [comment]
Not currently. It's slated for a future release in a separate issue.

**Comment by synectiks** [comment]
How to create dynamic states in app config. like below
var statesList=[
					{
						name:'home',
						url: '/',
						templateUrl: 'public/templates/login.html',
						controller: 'aa'
					}, {
						name:'schedule',
						url: '/aaa',
						templateUrl: 'public/templates/aaa.html',
						controller: 'aaa'
					}];

angular.forEach(statesList, function(state) {
			   $stateProvider
                .state(state.name, {
                    url: state.url,
                    templateUrl: state.templateUrl,
                    controller: state.controller,
                    controllerAs: 'vm'
                });
			});

**Comment by synectiks** [comment]
How to create dynamic states in app config. like below
var statesList=[
					{
						name:'home',
						url: '/',
						templateUrl: 'public/templates/login.html',
						controller: 'aa'
					}, {
						name:'schedule',
						url: '/aaa',
						templateUrl: 'public/templates/aaa.html',
						controller: 'aaa'
					}];

angular.forEach(statesList, function(state) {
			   $stateProvider
                .state(state.name, {
                    url: state.url,
                    templateUrl: state.templateUrl,
                    controller: state.controller,
                    controllerAs: 'vm'
                });
			});

I wamnt to load statesList from json file. Can any one please suggest
