### ISSUE TITLE
Making scroll to work in a native manner (like with ordinary websites)

### ISSUE THREAD

**Issue by OnkelTem** [angular-ui/ui-router#1852]
With an angular app it's quite often case when your states translated to what user call pages. When the current state changes, a part of the DOM is rewritten by Angular. While this is ok and allows for visually quicker and smoother page loads, this also leads to the problem with scrolling. If the states changes when a page is scrolled, this scroll amount is preserved when a new stats reloads the current view, so you can find yourself on the middle of the "next page".

To fix this we can use ```autoscroll``` UI Router directive, which can trigger scroll on state changes. But to emulate native browser behavior we need something more then just triggering autoscroll on every page load/state change. Specifically:

* if we load a new page, scroll should be reset. This is already done by the directive.
* if we navigate back in the history, scroll position should be restored to the value it had when we last visited the page
* similarly if we navigate forward in the history, scroll position should be restored either.

Honestly, I haven't searched yet for a NG modules which probably solve this issue, but I think that the task is so common, that we can have this behavior implemented into UI Router.

Thoughts?

**Comment by andreialecu** [comment]
Were you able to resolve this in any way? I need it too.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

also, most likely a duplicate since I have seen a few tickets/prs with this
