### ISSUE TITLE
Question: includedByState multiple parameters?

### ISSUE THREAD

**Issue by captainclam** [angular-ui/ui-router#1854]
Is there any way to check multiple states with the `includedByState` filter? Currently, I have had to extend the filter like this:

```javascript
// <div ng-if="['a', 'b', 'c'] | anyIncludedByState">

app.filter('anyIncludedByState', [
  '$filter', function($filter) {
    return function(states) {
      var includedByState = $filter('includedByState');
      for (var i = 0, i < states.length; i++) {
        if (includedByState(states[i])) {
          return true;
        }
      }
      return false;
    };
  }
]);
```

I feel like I might be missing a simpler way to do this with the existing filter?

**Comment by captainclam** [comment]
did it using
```
<div ng-if="('a' | includedByState) || ('b' | includedByState) ||  ('c' | includedByState)">
```

**Comment by nateabele** [comment]
High-five. Yeah, currently the filters aren't great, and I've kind of come to hate them, because I think we can come up with a better, more composable approach. Anyway, I'm glad you've solved your problem.
