### ISSUE TITLE
Best Practice way to support URL aliases?

### ISSUE THREAD

**Issue by rwillmer** [angular-ui/ui-router#1857]
I need to support multiple URLs for the same state (reason: support for legacy code)

Is there an agreed best practice way to do this? I've seen this issue #185, but it doesn't seem to reach a conclusion about the right way to do it.

**Comment by nateabele** [comment]
Currently the only accepted convention for this is `$urlRouterProvider.when()`. There are no higher level APIs for multiple URLs at the moment.

**Comment by nateabele** [comment]
Oh, alternatively, you could implement a custom `UrlMatcher` that accepts multiple `UrlMatcher`s as arguments.

**Comment by fxck** [comment]
has anyone written such custom UrlMatcher yet?
