### ISSUE TITLE
View loads/flickers before re-routing when opening browser with bookmark/direct url

### ISSUE THREAD

**Issue by npearson72** [angular-ui/ui-router#1860]
First off, this is an amazing library and thank you guys for supporting it!

My issue is that I would like to force users to the login state/view unless they have an active session. I'm able to do this for the most part with `.run`  definitions. But the problem I can't get around is when the user bookmarks a page that represents an authenticated state, then closes the browser (killing his session), then hits that bookmark. For a moment, the screen flashes with the authenticated view before routing to the login.

Is there a built in mechanism to deal with this, or any other solution that might work?

Thanks.

**Comment by eddiemonge** [comment]
prevent default in stateChangeStart if they aren't authenticated
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
