### ISSUE TITLE
$scope.$destroy not being called on $stateChange

### ISSUE THREAD

**Issue by evankline** [angular-ui/ui-router#1861]
I noticed my initialization functions weren't being called on $stateChange so I verified $stateChange by listening for the $stateChangeSuccess event & for $scope.$destroy inside my controllers. The $stateChangeSuccess event is being fired, however, the $scope.$destroy event isn't being fired and my initialization functions aren't running.

**Comment by chandiwicky** [comment]
Observe the same scenario, but sometimes it get called..totally random behaviour
