### ISSUE TITLE
Is it possible for you to do more frequent releases following semver?

### ISSUE THREAD

**Issue by ChrisCinelli** [angular-ui/ui-router#1862]
This is the current difference between the last released version (0.2.13) and master: https://github.com/angular-ui/ui-router/compare/0.2.13...master

I notice that there is sometime more than 4 months of lag between merging pull requests and releases. 
It would not be a bad idea to make sure to follow http://semver.org/ and releasing a new patch version when bugs are fixed.
 
Is there a good reason not to have a task in the gruntfile that automatically does the release on bower and it is executed after some code is merged and tests pass?
If the core team cannot, can we find somebody among all the contributors that can and want to do it?

**Comment by nateabele** [comment]
Here are the short answers:

> Is it possible for you to do more frequent releases [...] ?

Yes.

> [...] [F]ollowing semver?

No.

_Slightly longer answer:_

Semver dictates a new major release with every BC-breaking change. There are a lot of things in the API that, even after all this time, are still very much evolving, and we plan to lock it down once 1.0 hits. So, for the moment those two things are in conflict. Post-1.0, however, we very much plan to follow semver.

Finally, I'll push a new release tonight or tomorrow. While doing a release certainly isn' a major project, it is still somewhat involved, as certain packaging systems (NPM for one, I think) still haven't been fully integrated into the build tooling. If this is something you'd like to help fix, I'd be happy to help point you in the right direction.

**Comment by nateabele** [comment]
[At long last, your moment of zen.](https://github.com/angular-ui/ui-router/releases/tag/0.2.14) Sorry about the wait.
