### ISSUE TITLE
Rule Ordering

### ISSUE THREAD

**Issue by bmorgan21** [angular-ui/ui-router#1868]
Right now rules are not ordered in any specific way except for the order they are defined (imported).

If ui-router could be smart enough to put non-variable routes at a particular url level before those that have variables it could better handle wildcard use-cases.

i.e. I have a url structure that looks like the following:

/
/page-a
/page-b
/&lt;name&gt;
/&lt;name&gt;/page-a
/&lt;name&gt;/page-b

in this case &lt;name&gt; can be anything (mapped to some data on the backend).  The problem comes into play when "/&lt;name&gt;" is defined before "/page-a", because the later matches the former rule and therefore we show the wrong content.

This can be solved by putting all these routes into a specific file and dictate the ordering, but when trying to keep things modular it breaks because order is not deterministic.  

If this is not a generally liked approach, having the ability to override the addition of the rules, so that I can dictate the ordering would be just as acceptable.

**Comment by nateabele** [comment]
Yeah, rule ordering is something we've considered, but the algorithms can get to be complicated, and it would have to be pluggable, to account for different use cases. Definitely desirable, but not really on the roadmap as yet.
