### ISSUE TITLE
Removing IRC Webhook

### ISSUE THREAD

**Issue by Foxandxss** [angular-ui/ui-router#1870]
Hey @nateabele and @christopherthielen, could you please remove the IRC webhook? People don't like it and I don't think it is of any use. I removed the ui-bootstrap ones and I asked the ng-grid guys to do the same.

Thank you.

**Comment by nateabele** [comment]
Hah, took me a minute to figure out what you were talking about, but I'm pretty sure I removed it just now. Let me know if it's still a problem.
