### ISSUE TITLE
More verbose logging to the console

### ISSUE THREAD

**Issue by ansonkao** [angular-ui/ui-router#1871]
Forgive me if there is already an existing thread but couldn't find one.

Every now and then I get a blank screen after making some changes, and there are NO errors in the console. The only way I've found to diagnose is using this trick:

```
// Credits: Adam's answer in http://stackoverflow.com/a/20786262/69362
// Paste this in browser's console
var $rootScope = angular.element(document.querySelectorAll("[ui-view]")[0]).injector().get('$rootScope');
 
$rootScope.$on('$stateChangeStart',function(event, toState, toParams, fromState, fromParams){
  console.log('$stateChangeStart to '+toState.to+'- fired when the transition begins. toState,toParams : \n',toState, toParams);
});
 
$rootScope.$on('$stateChangeError',function(event, toState, toParams, fromState, fromParams){
  console.log('$stateChangeError - fired when an error occurs during transition.');
  console.log(arguments);
});
 
$rootScope.$on('$stateChangeSuccess',function(event, toState, toParams, fromState, fromParams){
  console.log('$stateChangeSuccess to '+toState.name+'- fired once the state transition is complete.');
});
 
$rootScope.$on('$viewContentLoaded',function(event){
  console.log('$viewContentLoaded - fired after dom rendered',event);
});
 
$rootScope.$on('$stateNotFound',function(event, unfoundState, fromState, fromParams){
  console.log('$stateNotFound '+unfoundState.to+'  - fired when a state cannot be found by its name.');
  console.log(unfoundState, fromState, fromParams);
});
```

Surely it makes sense to make logging at least this verbose by default?

**Comment by ansonkao** [comment]
Okay found it... #469

+1000!!!

**Comment by nateabele** [comment]
Better yet:

```javascript
app.run(($rootScope) => {
  $rootScope.$on("$stateChangeError", console.log.bind(console));
});
```

**Comment by ansonkao** [comment]
Added FAQ to wiki with keywords that would've aided in Googling. Cheers
https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#issue-im-getting-a-blank-screen-and-there-are-no-errors

**Comment by nateabele** [comment]
Nice, thanks for that.

**Comment by yoshiokatsuneo** [comment]
Why does UI.Router *intentionally* does not log console debug errors ?
It is helpful if appropriate error message is available by default.

**Comment by kduhaime514** [comment]
> app.run(($rootScope) => {
  $rootScope.$on("$stateChangeError", console.log.bind(console));
});

@nateabele this solution may cause issues for IE 8 & 9, due to some funkiness with the console object http://stackoverflow.com/questions/5472938/does-ie9-support-console-log-and-is-it-a-real-function/5473193#5473193
