### ISSUE TITLE
RFC: Allow ui-view directive to used as a comment

### ISSUE THREAD

**Issue by malthejorgensen** [angular-ui/ui-router#1872]
The `ui-view`-directive is currently restricted to being used as an _attribute_, _element_, or _style_.  (`restrict: 'ECA'` [ref])
I propose that the directive should be allowed to be used as a comment as well (`restrict: 'ECAM'`)

That way it can be used via a named view to control the `<title>`, `<meta name="description">`, and other tags in `<head>`.

```html
<head>
  ...
  <!-- directive: ui-view metatags --> <!-- Result of proposal -->

  <ui-view name="metatags" /> <!-- Current solution -->
  <!-- Cannot be used in `head` as the `ui-view` tag is moved into `body` -->
  ...
</head>
```
with an exemplified state configuration
```javascript
$stateProvider
  .state('app', {
    abstract: true,
    views: {
      'meta': {
          templateUrl: 'meta.html',
      },
      'content': {}
    }
  })
  .state('frontpage', {
    parent: 'app'
    views: {
      'meta@': { template: '<title>Frontpage</title>' +
                           '<meta name="description" content="this is the frontpage">' },
      'content@': { ... }
    }
  })
  ...
```

For the Angular docs see: https://code.angularjs.org/1.3.7/docs/api/ng/service/$compile#-restrict-

[ref]: https://github.com/angular-ui/ui-router/blob/bc34b4597060f6288d13a19636996270347770b5/src/viewDirective.js#L169

**Comment by eddiemonge** [comment]
I am not sure how much benefit that would be since the metatags are mostly for search engines and they wouldn't normally render that specific view. For title, you could listen to stateChangeSuccess and change it there based on `$state.current.data.title` or something similar.

**Comment by malthejorgensen** [comment]
In our specific case we are using [prerender.io](https://prerender.io/) in order to render the Angular-driven pages to search engines and other non-javascript enabled web crawlers ([the Facebook crawler](https://developers.facebook.com/docs/sharing/webmasters/crawler)). In that case changing `<meta>` tags from Angular does make sense, albeit it is a special case.
