### ISSUE TITLE
Is it possible handle the dynamic URL parts

### ISSUE THREAD

**Issue by Mirodil** [angular-ui/ui-router#1873]
I have `SearchController` and dynamic urls for this controller which are depending from search filter for example: `/cars/bmw`, `cars/bmw/x6` and so on. I have 16 url parts/parameters like `bmw`, 'x6', and all this urls would be handle by `SearchController`. 

In addition, I have `DetailsController` with the a difference `id`, and URLs are: `/cars/bmw/12345fd6789`, `cars/bmw/x6/12345fd6789`, `cars/bmw/x6/12345fd6789/red` and so on.

Is it possible handle such type URL rules?

**Comment by nateabele** [comment]
Yep. With optional parameters and regular expression matching, you should have all kinds of flexibility to handle such cases. Try it out, and if you get stuck, head over to StackOverflow, where we handle these kinds of questions: http://bit.ly/UIR-SOF -- thanks.

**Comment by Mirodil** [comment]
If I create URL's with optional regex, strange issue appears during building URLs with `UrlMatcher.prototype.format`
For example:
```javascript
$stateProvider
            .state('details', {
                url: url: '/cars{make:(?:/[^/]+)?}{model:(?:/[^/]+)?}/{id:[0-9a-fA-F]{24}}{postcode:(?:/postcode\\-\\w+)?}{distance:(?:/\\d+miles)?}{minprice:(?:/min\\-\\d+)?}{maxprice:(?:/max\\-\\d+)?},
                templateUrl: 'scripts/angular/app/controllers/details/partials/index.html',
                controller: 'DetailsCtrl'
            })
```
cases:
```ui-sref="details({id:'123564879'})"``` - > ```/cars/123564879```
```ui-sref="details({id:'123564879'},make:'bmw')"``` - > ```/cars/123564879bmw```
```ui-sref="details({id:'123564879'},make:'/bmw')"``` - > ```/cars/123564879%252Fbmw```

as you can see URL parts cannot splitted by ```/```
