### ISSUE TITLE
state use resolve to load another js module file to complate a lazy-moudle-load,cant work

### ISSUE THREAD

**Issue by forfuns** [angular-ui/ui-router#1876]
I need lazy load a module to expansion my app
code like this : 
**state**
```
$stateProvider.state('plugin',{
  ....
  resolve : {
    loadModule : ['$q',function($q){
       var defer = $q.defer();
       $.getScript('js url',function(){defer.resolve();});
       return defer.promise;
    }]
  }
})
```
**js file**
```
!function(angular,undefined){
   var app = angular.module('a app name ');
   app.controller('app.ctrl.newXX',....);
}(angular);
```

but if I use $state.go(stateName,param);
this always show error : Argument 'app.ctrl.newXXX' is not aNaNunction, got undefined

**Comment by gynmi** [comment]
Have you solved the problem?

**Comment by forfuns** [comment]
yes

**Comment by vipulkumarsviit** [comment]
hay forfuns can I know How You hv resolved because i'm also having same problem but not able to find any solution
