### ISSUE TITLE
$urlMatcherFactory not handling default parameters in the same way as string url does

### ISSUE THREAD

**Issue by pascal-privax** [angular-ui/ui-router#1878]
I've come across the annoying issue where parameters with default values (with squash enabled) do not work with $urlMatcherFactory even though they work fine with a string url.

String (works, you can go to /foo and to /nl/foo without issues)
```Javascript
$stateProvider.state('foo', {
    url   : '/{language}/foo',
    params: {
        language: {
            value : 'en',
            squash: true
        }
    }
});
```

```$urlMatcherFactory``` (doesn't work, /foo 404's /nl/foo or /en/foo works without issues)
```Javascript
$stateProvider.state('foo', {
    url   : $urlMatcherFactoryProvider.compile('/{language}/foo'),
    params: {
        language: {
            value : 'en',
            squash: true
        }
    }
});
```

As an alternative option I've also tried setting an abstract state above foo. Annoyingly this doesn't work either. It seems like the UrlMatcher just doesn't inherit the parameter at all. 
```Javascript
$stateProvider.state('language', {
    abstract: true,
    url     : '/{language}',
    params  : {
        language: {
            value : 'en',
            squash: true
        }
    }
});

$stateProvider.state('language.foo', {
    url   : $urlMatcherFactoryProvider.compile('/foo'),
    params: {
        language: {
            value : 'en',
            squash: true
        }
    }
});
```

**Comment by eddiemonge** [comment]
Having the optional part before valid parts seems like it shouldn't work. That is sort of a weird thing even though I kind of see what you are going for. You could always try making that a query param.

https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by christopherthielen** [comment]
I think this should work. Reopening

**Comment by nateabele** [comment]
This actually doesn't make any sense. If you pass a string, The state builder will use `$urlMatcherFactory` to compile it to a `URLMatcher` for you, bringing in the parameter configuration you passed to the state definition, but if you're calling it manually, then passing the configuration is your own responsibility. The state builder isn't going to deconstruct the `URLMatcher` you're passing it and make you a new one.

Your code should look like this:
```javascript
$stateProvider.state('foo', {
    url: $urlMatcherFactoryProvider.compile('/{language}/foo', {
        params: {
            language: {
                value : 'en',
                squash: true
            }
        }
    })
});
```
