### ISSUE TITLE
$state.params empty in resolve

### ISSUE THREAD

**Issue by Morriz** [angular-ui/ui-router#1879]
Why is ui-router not ready populating $state.params before it enters resolvers? Too many people seem to  have issues with that, so I suggest to support the majority of use cases that rely on this assumption.

**Comment by nateabele** [comment]
See [my explanation here](https://github.com/angular-ui/ui-router/issues/1856#issuecomment-93025037). I believe this is already fairly well-documented, but feel free to add a bullet point to the FAQ if you feel strongly about it.
