### ISSUE TITLE
ui-sref directive breaks silently with Google's new reCaptcha

### ISSUE THREAD

**Issue by pjarts** [angular-ui/ui-router#1883]
When the reCaptcha is ticked the ui-sref directive does no longer switch states. I get no errors at all so it's hard to tell what is actually causing this issue. I have noticed though that I can get it to work by commenting out `$timeout.cancel(transition)` within the click binder in the ui-sref source, hence I suspect something might be canceling the timeout that triggers `$state.go`, which would explain why no errors are thrown. [See this plunker](http://plnkr.co/edit/JKXnt6vV5uaNYfYyoRRB?p=preview)

**Comment by nateabele** [comment]
Seems to work fine for me. I did the reCaptcha and clicked on the "Link with ui-sref" link, and it showed the text "another state" below the reCaptcha. Was something different supposed to happen?

Is this on a particular browser?

**Comment by purjon** [comment]
If i first click the reCaptcha, nothing happens when I click the ui-sref link. I've tested with:
* IE 11
* Firefox 28
* Firefox 35
* Chrome 40 
* Chrome 41
* Chromium 39
All fail. Seems to work in Safari on iPad 4 though..

**Comment by nateabele** [comment]
That's really bizarre. I'm on Chrome 41 on OSX. I can click all over the reCaptcha, reload it, verify it, etc., and the state link still works fine for me.

Can anyone else confirm/deny?

**Comment by IainCole** [comment]
Just tried FF 36 and Chrome 41 PC, can confirm doesn't work.

**Comment by nateabele** [comment]
Okay, so, in FF and Safari (where I _can_ reproduce the issue), the reCaptcha is just a checkbox, but in Chrome you have to enter text. Not sure what difference that makes. As you correctly identified, the issue seems to be around `ignorePreventDefaultCount` here: https://github.com/angular-ui/ui-router/blob/master/src/stateDirectives.js#L142, which was introduced at 656b5aab906e5749db9b5a080c6a83b95f50fd91.

@christopherthielen Do you remember what exactly that was introduced? Something with `<a />`'s that already had links that Angular core was messing with or something?

**Comment by purjon** [comment]
It doesn't really matter whether you have to write text or not in the reCaptcha. I've tested it so many times that I now have to identify wine bottles and sushi, but the ui-sref link still doesn't work :)

**Comment by christopherthielen** [comment]
@nateabele Here is what I remember:

The built-in AngularJS `a` directive (https://github.com/angular/angular.js/blob/v1.3.15/src/ng/directive/a.js#L28) calls `preventDefault` if the anchor tag does not have an href.  

The ui-sref directive replaces the preventDefault function on the click event with one that simply stops the transition.  If the ui-sref directive is on an `<a>` tag with no `href`, it waits for two calls to `preventDefault` before cancelling the transition such that when the `a` directive invokes `preventDefault()`, it is ignored. 

---

I wonder if this has to do with directive priority... if the `a` click handler is invoked first, then `preventDefault()` will already have been called, and the `uiSref` click handler will wait forever for it to be called again.
