### ISSUE TITLE
Using ui-sref-active on a <span>

### ISSUE THREAD

**Issue by JobaDiniz** [angular-ui/ui-router#1886]
Hi, I'd like to use `ui-sref-active` on a `<span>` tag, however, in order to `ui-sref-active` work, I need to add `ui-sref="my.state"`. Once I do, the span becomes clickable... I don't want clickable span. I just want to set _active_ class in the span. User will not navigate directly to a state, the system will manage this.

**Comment by dlukez** [comment]
You should be able to get the same functionality like this:

Controller
```
// put state on the scope
$scope.$state = $state;
```

Template
```
<span ng-class="{ 'active': $state.is('some.state') }">
```

**Comment by JobaDiniz** [comment]
I think `ui-sref-active` could accept an optional parameter: the state:

`<span ui-sref-active="active" ui-sref-active-state="my.state">`

**Comment by dmackerman** [comment]
The other solution is much more flexible, FWIW. I use it in nearly every application.

**Comment by alias1** [comment]
+1 @JobaDiniz

There are ways to do it, and ways to hack around it, but I think it would be a nice addition to make an already useful directive even more useful.

The hack I used:
```
<li ui-sref-active="active">
    <a ui-sref="layout.feedback">
      Feedback <span ui-sref-active="selected"><span ui-sref="layout.feedback"><!-- HACK --></span></span>
    </a>
  </li>
```

**Comment by nateabele** [comment]
`ui-sref-active` is a shorthand directive that is really only meant to be used in conjunction with `ui-sref`. There are other solutions that cover your use case.
