### ISSUE TITLE
Multiple Views get reloaded on param change

### ISSUE THREAD

**Issue by ZeeshanJawaid** [angular-ui/ui-router#1895]
I have a main container view which contains 2 sub views one is filter parameters and other for content. The issue is when I move to different state which only calls content view. The parameters view gets reloaded as well on state change. I need to persist filter parameters on state change.

        --main container view
         ui-view="container"

         --filter param view
          ui-view="param"
         --filter param view

          --content view
          ui-view="content"
          --content view

          --main container view

**Comment by ZeeshanJawaid** [comment]
To be specific in the content view I am using ng-click to move to another state which in turn must load new state and it is working but it reloads the complete ui-view as well. The reason is for this is that I need to pass additional params using custom HTML arguments which are added to navigated state for processing.

**Comment by eddiemonge** [comment]
notify false?

https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
