### ISSUE TITLE
Definitely file module 'ng' conflicts with angular definitely file module 'ng'

### ISSUE THREAD

**Issue by dhaval-patel** [angular-ui/ui-router#1899]
In api/angular-ui-router.d.ts, we declare module 'ng'. Which conflicts with another module which created by angular definitely type. Checkout  https://github.com/borisyankov/DefinitelyTyped/blob/master/angularjs/angular.d.ts

In definitely type repo, they have solved this problem in angular-ui-router definitely file. Checkout this https://github.com/borisyankov/DefinitelyTyped/blob/master/angular-ui-router/angular-ui-router.d.ts.
They have renamed module 'ng' with 'angular'.

Those changes in this repo will be very appreciated.

**Comment by nateabele** [comment]
Okay, you're saying I should just copy the ts file from DefinitelyTyped?

**Comment by dhaval-patel** [comment]
@nateabele  Yes, I think. Same issue was raised for definitely type and they have changed it too over there. I think we should change it here also.

**Comment by leandroshan** [comment]
hi guys, do we have a resolution for this ? how can I fix this problem ?  thanks for the help

**Comment by ruant** [comment]
Why have this file at all?
