### ISSUE TITLE
bug fix proposed

### ISSUE THREAD

**Issue by dolphinsd** [angular-ui/ui-router#1901]
sometime locals var in current state is null. the code below throws exception:

```
 function updateView(firstTime) {
          var newScope,
              name            = getUiViewName(scope, attrs, $element, $interpolate),
              previousLocals  = name && $state.$current && $state.$current.locals[name];
 if (!firstTime && previousLocals === latestLocals) return; // nothing to do
          newScope = scope.$new();
          latestLocals = $state.$current.locals[name];
```

PROPOSED CODE:
 // BUG FIX

```
            var newScope,
                name = getUiViewName(scope, attrs, $element, $interpolate);
            var previousLocals = null;
            if (name && $state.$current && $state.$current.locals)
                previousLocals = name && $state.$current && $state.$current.locals[name];

          if (!firstTime && previousLocals === latestLocals) return; // nothing to do
          newScope = scope.$new();
            // BUG FIX
          if ($state.$current.locals)
            latestLocals = $state.$current.locals[name];
```

another place where locals are referenced without checking for null is:

```
var current = $state.$current,
            name = getUiViewName(scope, attrs, $element, $interpolate),
            locals  = current && current.locals[name];
```

and fix 

```
        var current = $state.$current,
            name = getUiViewName(scope, attrs, $element, $interpolate);
        var locals = null;
        if (current && current.locals)
            locals = current && current.locals[name];

        if (! locals) {
          return;
        }
```

**Comment by nateabele** [comment]
Interesting, I don't think we've ever had this come up. Can you post an example that demonstrates how the issue is triggered? Thanks.

**Comment by vladsd** [comment]
Yep, I tried to isolate example, i can share in private code for entire file and do skype session, otherwise i have to put entire app project:)

**Comment by flc** [comment]
http://plnkr.co/edit/yXEWItLQBxSEKzOwLsfj?p=preview
what I did is only add this line:
```
$stateProvider.state({ name: 'redir', url: '/redir', controller: function() { }, onEnter: function($state) {$state.transitionTo("home");}});
```

choose 'home.foo' from the 'go to state' dropdown then choose "redir", result in chrome:
```
TypeError: Cannot read property 'globals' of null
```

firebug traceback:
```
Error: to.navigable.locals is null
transitionTo/$state.transition<@https://rawgit.com/angular-ui/ui-router/0.2.13/release/angular-ui-router.js:3198:11
qFactory/defer/deferred.promise.then/wrappedCallback@https://code.angularjs.org/1.2.25/angular.js:11572:31
qFactory/defer/deferred.promise.then/wrappedCallback@https://code.angularjs.org/1.2.25/angular.js:11572:31
qFactory/ref/<.then/<@https://code.angularjs.org/1.2.25/angular.js:11658:26
$RootScopeProvider/this.$get</Scope.prototype.$eval@https://code.angularjs.org/1.2.25/angular.js:12701:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@https://code.angularjs.org/1.2.25/angular.js:12513:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@https://code.angularjs.org/1.2.25/angular.js:12805:13
setupAsOptions/<@https://code.angularjs.org/1.2.25/angular.js:21683:11
createEventHandler/eventHandler/<@https://code.angularjs.org/1.2.25/angular.js:2853:7
forEach@https://code.angularjs.org/1.2.25/angular.js:325:9
createEventHandler/eventHandler@https://code.angularjs.org/1.2.25/angular.js:2852:5

https://code.angularjs.org/1.2.25/angular.js
Line 10071
```

or choose 'redir' and then 'home.foo', result in chrome:
```
TypeError: Cannot read property '@' of null
```

firebug traceback:
```
Error: $state.$current.locals is null
updateView@https://rawgit.com/angular-ui/ui-router/0.2.13/release/angular-ui-router.js:3833:15
$ViewDirective/directive.compile/</<@https://rawgit.com/angular-ui/ui-router/0.2.13/release/angular-ui-router.js:3804:11
$RootScopeProvider/this.$get</Scope.prototype.$broadcast@https://code.angularjs.org/1.2.25/angular.js:12980:15
load@https://rawgit.com/angular-ui/ui-router/0.2.13/release/angular-ui-router.js:3558:11
resolveState/</injectables.$template<@https://rawgit.com/angular-ui/ui-router/0.2.13/release/angular-ui-router.js:3458:18
invoke@https://code.angularjs.org/1.2.25/angular.js:3966:14
proceed@https://rawgit.com/angular-ui/ui-router/0.2.13/release/angular-ui-router.js:474:32
invoke@https://rawgit.com/angular-ui/ui-router/0.2.13/release/angular-ui-router.js:470:26
$Resolve/this.study/<@https://rawgit.com/angular-ui/ui-router/0.2.13/release/angular-ui-router.js:449:14
$Resolve/this.resolve@https://rawgit.com/angular-ui/ui-router/0.2.13/release/angular-ui-router.js:553:12
resolveState/<@https://rawgit.com/angular-ui/ui-router/0.2.13/release/angular-ui-router.js:3461:23
forEach@https://code.angularjs.org/1.2.25/angular.js:332:11
resolveState@https://rawgit.com/angular-ui/ui-router/0.2.13/release/angular-ui-router.js:3455:7
transitionTo@https://rawgit.com/angular-ui/ui-router/0.2.13/release/angular-ui-router.js:3157:20
go@https://rawgit.com/angular-ui/ui-router/0.2.13/release/angular-ui-router.js:3007:14
Parser.prototype.functionCall/<@https://code.angularjs.org/1.2.25/angular.js:10846:15
Parser.prototype.statements/<@https://code.angularjs.org/1.2.25/angular.js:10621:29
$RootScopeProvider/this.$get</Scope.prototype.$eval@https://code.angularjs.org/1.2.25/angular.js:12701:16
ngChangeDirective<.link/<@https://code.angularjs.org/1.2.25/angular.js:17974:7
NgModelController</this.$setViewValue/<@https://code.angularjs.org/1.2.25/angular.js:17752:11
forEach@https://code.angularjs.org/1.2.25/angular.js:325:9
NgModelController</this.$setViewValue@https://code.angularjs.org/1.2.25/angular.js:17750:7
setupAsOptions/</<@https://code.angularjs.org/1.2.25/angular.js:21735:13
$RootScopeProvider/this.$get</Scope.prototype.$eval@https://code.angularjs.org/1.2.25/angular.js:12701:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@https://code.angularjs.org/1.2.25/angular.js:12799:18
setupAsOptions/<@https://code.angularjs.org/1.2.25/angular.js:21683:11
createEventHandler/eventHandler/<@https://code.angularjs.org/1.2.25/angular.js:2853:7
forEach@https://code.angularjs.org/1.2.25/angular.js:325:9
createEventHandler/eventHandler@https://code.angularjs.org/1.2.25/angular.js:2852:5

https://code.angularjs.org/1.2.25/angular.js
Line 10071
```

the issue seems to exist with angular 1.4 and/or ui-router 0.2.14 as well

https://github.com/angular-ui/ui-router/issues/1833 looks similar

**Comment by flc** [comment]
i'm currently using a workaround something like this:

```javascript
$rootScope.$on('$stateChangeStart', function(event, toState, toParams, fromState, fromParams) {
  if (toState.name === "redir") {
    $state.transitionTo("home");
    event.preventDefault();
  }
});
```

**Comment by pocesar** [comment]
just stumbled upon this problem. I created a route that the sole purpose is to do a redirection, inside onEnter. always give the `$state.$current.locals is null`

**Comment by valistar** [comment]
@nateabele Here's a plunkr. I've experienced the same issue.
http://plnkr.co/edit/XjYN14oiBEu5cDVrnA2R?

I found some way to fix it, as well as what i believe is the cause of the issue, but I'm not very familiar with ui-router internals, so I haven't submitted a PR or anything.


    var transition = $state.transition = resolved.then(function () {
        var l, entering, exiting;
    
        if ($state.transition !== transition) return TransitionSuperseded;
    
        // Exit 'from' states not kept
        for (l = fromPath.length - 1; l >= keep; l--) {
            exiting = fromPath[l];
            if (exiting.self.onExit) {
                $injector.invoke(exiting.self.onExit, exiting.self, exiting.locals.globals);
            }
            exiting.locals = null; //THIS LINE
        }
    
        // Enter 'to' states not kept
        for (l = keep; l < toPath.length; l++) {
            entering = toPath[l];
            entering.locals = toLocals[l];
            if (entering.self.onEnter) {
                $injector.invoke(entering.self.onEnter, entering.self, entering.locals.globals);
            }
        }
    
        ....


If you then start another transition inside an onEnter callback, exiting locals have already been blown up, but weren't set to the values from the intermediate state yet, and I assume these are referenced by the global $state, because that then seems to get nulled.

Removing that line from the loop there and adding another loop over fromPath down immediately after all onEnter callbacks are fired, and nulling the exiting locals here, seems to fix this issue, but I wasn't sure what side effects this might have. Doesn't seem to have broken anything for my project though.

In the plunkr, I don't know why three clicks are required. I'd expect one to maybe work because I haven't initialized any state, and then the second click would trigger the error. It doesn't, and instead a third is required. In my project, every transition to a state after initialization/bootstrapping is done initiated from inside an onEnter callback causes the error to occur.

**Comment by pramodkks** [comment]
Any Update on this issue?
Facing same issue when I am using onEnter callback. Looks like $state.$current.locals is not initialized when '$viewContentLoading' event is triggered.

**Comment by rbnzdave** [comment]
Same here.
in the onEnter, getting $state.current doesn't give me the current state we are going to...

**Comment by eddiemonge** [comment]
Why are you trying to use `$state.$current` instead of `$state.current`?

**Comment by eddywashere** [comment]
@eddiemonge I could be wrong but I don't believe the issue is with end users using `$state.$current`,  not sure if you noticed the example to reproduce http://plnkr.co/edit/XjYN14oiBEu5cDVrnA2R?

**Comment by eddiemonge** [comment]
its not, but it was interesting to me all the same

**Comment by HadrienPierart** [comment]
Is there plans to fix this ? We have this issue multiple times on several routes/views in our app in production and we're a bit stuck...

**Comment by eldereal** [comment]
Is there any updates on this issue? I had face the same problem when trying to use `$state.go(...)` in `onEnter` callback. Now I use `$timeout` to workaround with this problem.
```javascript
onEnter: ["$state", "$timeout", function($state, $timeout){      
    $timeout(function(){
        $state.go(...);
    });
}]
```
It works but the code is not beautiful.

**Comment by Matrosskin** [comment]
I have same issue so I am interested in final solution too.

**Comment by azachar** [comment]
+1

**Comment by lloy0076** [comment]
I got the same issue with this code:

```
 86         $stateProvider.state('auth.logout', {
 87             url: '/logout',
 88             template: 'Logout!',
 89             onEnter: ['$state', '$auth', '$timeout', function($state, $authProvider) {
 90                     $authProvider.logout();
 91                     $state.go('app.index');
 92             }],
 93         });
````

Changing the "onEnter" to:

```
 89             onEnter: ['$state', '$auth', '$timeout', function($state, $authProvider, $timeout) {
 90                     $authProvider.logout();
 91                     $timeout(function() {
 92                         $state.go('app.index');
 93                     });
 94             }],
```

...stopped the error appearing.

As @eldereal has mentioned, it works but it's not entirely elegant (or obvious why the $timeout is there).

**Comment by christopherthielen** [comment]
This should be fixed by the redirect support in the 1.0 version

**Comment by neoadventist** [comment]
This issue was fixed for me, I had UI-router and another ui-router bundled in with ionic :/ removed ui-router and everything resolved!

**Comment by tmcgann** [comment]
I was experiencing the same issues mentioned here, but they went away after I upgraded from 0.2.15 to 0.2.18.

**Comment by azachar** [comment]
I have the same issue with ionic 1.3.2 and ui-router 0.3.2. I double check the config, and I am using only one ui-router.

Here is the stacktrace:

```js

angular.js:14110 TypeError: Cannot read property 'name' of null
    at getUiViewName (angular-ui-router.js:4152)
    at updateView (angular-ui-router.js:4035)
    at angular-ui-router.js:4005
    at Scope.$broadcast (angular.js:18239)
    at angular-ui-router.js:3369
    at processQueue (angular.js:16606)
    at angular.js:16622
    at Scope.$eval (angular.js:17913)
    at Scope.$digest (angular.js:17727)
    at Scope.$apply (angular.js:18021)
```

Thanks for your help!

**Comment by azachar** [comment]
It looks like it is related to ionic: 

  self.init = function() {
    var navViewName = $attrs.name || '';

   ```
 // Find the details of the parent view directive (if any) and use it
    // to derive our own qualified view name, then hang our own details
    // off the DOM so child directives can find it.
    var parent = $element.parent().inheritedData('$uiView');
    var parentViewName = ((parent && parent.state) ? parent.state.name : '');
    if (navViewName.indexOf('@') < 0) navViewName = navViewName + '@' + parentViewName;

    var viewData = { name: navViewName, state: null };
    $element.data('$uiView', viewData);
```
So I think it is cased by this line
https://github.com/driftyco/ionic/blob/1.x/js/angular/controller/navViewController.js#L44

Am I right?

Cheers,
Andrej

**Comment by azachar** [comment]
Any news here?
