### ISSUE TITLE
Slash is not removed for squash:true when optional param terminates the url

### ISSUE THREAD

**Issue by jshado1** [angular-ui/ui-router#1902]
In @christopherthielen's [plunkr](http://plnkr.co/edit/VMPc8D7oUG0B1R3QuiCE?p=preview) example from #1501, `:username`'s slash is not removed when it is squashed. The documented behaviour for `squash: true` is that the optional parameter plus a slash are removed.

Reprod:
 1. Open the plunkr
 1. Click on the purple `user({username: 'christopherthielen'})` button.

Observed output: `/user/`
Expect output: `/user`

**Comment by cmmcleod** [comment]
+1

**Comment by christopherthielen** [comment]
> The parameter's default value is omitted from the URL. If the parameter is preceeded and followed by slashes in the state's url declaration, then one of those slashes are omitted.

I think what you're seeing is correct behavior.  According to the docs, *only one of two* slashes is omitted.

**Comment by hworld** [comment]
Is it hard to make a setting to clean/trim the end of the URL with squashed params? It's frustrating when all your URLs are consistent with no trailing slash and then you hit one url with a trailing slash because it has a squashed parameter.

**Comment by jshado1** [comment]
@christopherthielen in my reprod steps, none are removed:

```js
false: '/user/christopherthielen'
// …
true: '/user/'
```

the slash preceding `christopherthielen` is not removed. It should be.

**Comment by jshado1** [comment]
bump.

Is anyone looking into this? If not, could someone point me to where this is in the code base and I'll take a stab at it.

**Comment by deepakpookkote** [comment]
@jshado1 :Hi, How to handle this issue ? i'm facing this issue right now in my development. how to remove trailing slashes in ui-sref using squash!
