### ISSUE TITLE
Suggestion to have a redirect defined in a state 

### ISSUE THREAD

**Issue by rajivramv** [angular-ui/ui-router#1905]
I have seen suggestions for redirect using .when()
but is it possible to define a redirect url/state in the $stateProvider.state definition itself. 
In my application, it is semantically appropriate that I navigate to parent state rather than parent.child. Also, if it is handled there then $state.go ('^') from parent.child should go to the grandparent state, if any. I have several such states in my application and I feel it's cleaner to have a feature than use .when ()

ps. Apologies for the spam

**Comment by nateabele** [comment]
This is being discussed in #1584 and #27. Please direct your comments there. Thanks.
