### ISSUE TITLE
how do i debug 

### ISSUE THREAD

**Issue by awebdeveloper** [angular-ui/ui-router#1906]
I have been facing a lot of ui router issues (due to my own silly mistakes) and having tough time debugging it.  

i have a module structure and set state form multiple files all added as dependency to app.js. Lot of times  due to some error(typos, missing dependency etc) it just redirects to default route. 

would appreciate any help / suggestion on how to debug

**Comment by nateabele** [comment]
This looks like a question for StackOverflow: http://bit.ly/UIR-SOF
