### ISSUE TITLE
Multiple child states in one view

### ISSUE THREAD

**Issue by bcersows** [angular-ui/ui-router#1907]
Hey guys,

first of all, thanks for this module; it's great.

I'm having an overview page with multiple sections; each of the sections contains a list of elements. The elements are shown depending on the selected section/area. And I want to be able to select an element and show its details.
This all works by using only one substate (the element detail view).
Further into developing I decided that the user might want to also see the currently selected section in the URL (and to deep-link into it, of course).
But I'm having trouble changing the URL without reloading (which looks ugly due to some CSS transitions), so I figured having multiple child states might solve the problem. Still, I am kinda clueless. Main thing is that I want the user to select an element, then switch the section and the current state is reflected in the URL.
- So user selects area 1:
```/overview/area1```
- User selects element 5 of area 1:
```/overview/area1/e5```
- User selects area 2
```/overview/area2/e5```

Has anyone an idea how to implement this, without declaring the element states as children of the section states?

Regards,
bcersows

**Comment by nateabele** [comment]
Please use the issue tracker for submitting bugs with UI-Router _only_: http://bit.ly/UIR-SOF -- thank you.
