### ISSUE TITLE
Exception in resolver never bubbles up

### ISSUE THREAD

**Issue by bblack** [angular-ui/ui-router#1909]
Given a resolve function for a state, if the returned promise is rejected, the controller is properly not loaded. However, no error ever bubbles up, so it can't be handled by e.g. `$exceptionHandler`.

See http://plnkr.co/edit/kq46Tj0ldBLjn7qdDba6?p=preview

**Comment by nateabele** [comment]
> However, no error ever bubbles up

Yup, because that would break the Promise abstraction. Please see the FAQ.
