### ISSUE TITLE
(Question) about $state.transitionTo

### ISSUE THREAD

**Issue by paveleremin** [angular-ui/ui-router#1916]
Is it possible to send query parameters with $state.transitionTo?
For example, I has a state with name login:
```
.state('login', {
  url: "/login",
  templateUrl: "user/login/login.html",
  controller: "LoginCtrl",
  controllerAs: 'ctrl'
})
```
and I want to send query parameter like backUrl, so I want redirect user to: /login?backUrl=some_url_here
How can I to do that?
For example:
$state.transitionTo('login', {
  backUrl: some_url_here
});
not work

**Comment by nateabele** [comment]
Whatever parameters you use need to be declared in the state, i.e. `url: "/login?backUrl"`. Please refer further support questions to StackOverflow, thanks: http://bit.ly/UIR-SOF
