### ISSUE TITLE
$setPristine() undefined when loading from a template

### ISSUE THREAD

**Issue by JustinLien** [angular-ui/ui-router#1917]
This threw me in a loop for about a week. I was trying to reset the state of my form using $setPristine(), but the console been telling me that the $setPristine() is not a function.

```html
<div ui-view="load_form"></div>
```
```js
$scope.form.$setPristine(); \\ undefined
```

```html
<form name="form">
    <div ui-view="load_form"></div>
</form>
```
```js
$scope.form.$setPristine(); \\ works!!!
```

**Comment by eddiemonge** [comment]
so you were setting it in the wrong controller?

**Comment by nateabele** [comment]
I'm not sure how this is a UI-Router issue.

**Comment by eddiemonge** [comment]
@JustinLien ???

**Comment by nateabele** [comment]
@eddiemonge I'll give him a week and then close it. Thanks for hopping in on these.

**Comment by eddiemonge** [comment]
np. seeing so many issues on any project makes me sad. I like being happy so I am trying to help out how I can.

**Comment by ruant** [comment]
This issue should be closed.
@JustinLien , this SO question explains it nicely. (The link to angularjs is broken, here is the correct link: https://docs.angularjs.org/guide/controller)
