### ISSUE TITLE
Loading controller only when route is selected

### ISSUE THREAD

**Issue by bgold0** [angular-ui/ui-router#1918]
Let's say I have two pages, **cloud** and **settings**. I have the following code set up:

    var routerApp = angular.module('APP', ['ui.router']);

    routerApp.config(function($stateProvider, $urlRouterProvider, $locationProvider) {
        
        $locationProvider.html5Mode(true);
        $urlRouterProvider.otherwise('/cloud');
        
        $stateProvider
            
            .state('cloud', {
                url: '/cloud',
                templateUrl: 'pages/templates/cloud.html',
                controller: 'cloud',
            })
           
            .state('settings', {
                url: '/settings',
                templateUrl: 'pages/templates/settings.html',
                controller: 'settings'  
            });

    });

    routerApp.controller('cloud', function($scope, $http, $state) {
        alert("cloud");
    });

    routerApp.controller('settings', function($scope, $http, $state) {
        alert("settings");
    });

Regardless of what page I load, settings or cloud, the each controller will run no matter what. Meaning I will get 2 alerts, regardless, when I reload the page.

Could anyone help explain what I need to do so that if I reload my website on `/settings`, only the code in my settings controller will run and vice versa?

**Comment by eddiemonge** [comment]
I'm not seeing that behavior so you probably have something else going on: http://run.plnkr.co/FWbuOm6AO2FH3WnX/

**Comment by bgold0** [comment]
I messed up, I actually had a `ng-controller="cloud"` in the html that made it load. Thanks for your help and testing it for me.
