### ISSUE TITLE
0.2.14 - another breaking change

### ISSUE THREAD

**Issue by larrybotha** [angular-ui/ui-router#1919]
Not sure if this is a bug, or something we need to reconfigure in our app (I assume bug since this is a patch), but https://github.com/angular-ui/ui-router/commit/da63b27b7bbd13d2633b68fa74606f977e6d4147#diff-6de0577dce2b7e2e060fb6f1b36a33e3R1628 ended up throwing errors on parameters that were previously working without issue.

We ended up locking ui-router to an older version.

As a noob I can't get too much into the details. The guru who would have dealt with this, @sdbondi, will be on leave until next week Monday.

**Comment by nateabele** [comment]
Okay, unfortunately I can't really help you, since you've provided no details about the problem you're having.

**Comment by larrybotha** [comment]
ye, will get on this in a week or so

**Comment by zacaj** [comment]
also experiencing this, will update once I figure out what on our end needed to be changed

**Comment by eddiemonge** [comment]
pretty sure this is probably a duplicate of the other breaking bug. I suggest closing as such until more information is provided that it is a different bug

**Comment by OtaK** [comment]
@larrybotha Doesn't this seem to be related to #1915 ?

**Comment by nateabele** [comment]
Alright, closing unless any more information is supplied.
