### ISSUE TITLE
There should be an "optional" int parameter type

### ISSUE THREAD

**Issue by court-jus** [angular-ui/ui-router#1920]
The new "int" type is great but it is now mandatory. There should be a parameter type that match "/200/" and also "//".

**Comment by court-jus** [comment]
I'm not sure my PR really solves the problem and I'm not sure this is already possible in ui-router to have an optional int parameter in a state.

My state definition looks like that :

```
      .state('statename', {
        url: "/{objectID:int}/",
        templateUrl: "partials/templatename.tpl.html",
        controller: 'ControlerNameCtrl',
      })
```

and I'd like it to match ```/200/``` (and give me ```200``` as an int in ```stateParams.objectID```) but also to match ```//``` (and give me ```stateParams.objectID === null```).

It does not work in the current version because the "int" type tests if the value is defined :

```
    int: {
      encode: valToString,
      decode: function(val) { return parseInt(val, 10); },
      is: function(val) { return isDefined(val) && this.decode(val.toString()) === val; },
      pattern: /\d+/
    },
```

**Comment by court-jus** [comment]
I've found a solution, using the ```params``` way :


My state definition looks like that :

```
      .state('statename', {
        url: "/{objectID:int}/",
        params: { objectID: { value: null, squash: true } },
        templateUrl: "partials/templatename.tpl.html",
        controller: 'ControlerNameCtrl',
      })
```

**Comment by nateabele** [comment]
@court-jus Looks perfect. Basically, what I was trying to explain in my comment on your PR is that describing the parameter's type is a separate _concern_ from that of making it optional.

If we took that approach, we'd have to double the number of types we define: `optionalstring`, `optionaldate`, `optionalboolean`, etc. Hopefully that makes sense.

**Comment by court-jus** [comment]
Yeah, I see what you mean, it's true it was not an elegant solution :)
