### ISSUE TITLE
stateParams - non existant param != empty param value

### ISSUE THREAD

**Issue by thecko** [angular-ui/ui-router#1922]
Sorry for the horrible title, did not know how to say it short.

I'm developing a project where I want to query a REST API to retrieve some data. One of the fields is "query", that will filter the database returning all the rows that contains the text inside the "query" var.

"query" value will be, if present, the value of the querystring var "query", if not present, the value stored in the local storage and finally, if not present, a default value. This is the code:

```
$scope.query = $stateParams.query ? $stateParams.query : localStorageService.get('ships.query');
$scope.query = $scope.query == null ? '' : $scope.query ;
```

My problem is that it seems its not possible to distinguish from "not present" and "empty" querystring cases:
Not present: http://myproject/myState
Empty: http://myproject/myState?query=

Do not confuse with http://myproject/myState?query because it's a boolean true value, not an empty value.

Thats the definition of my state:

```
.state('loggedin.ships', {
      url: "ships"
      , params : {
        page : 1
        , order : 'name'
        , query : null
      }
      , templateUrl: "partials/ship-list.html"
      , controller: 'ShipListCtrl'
    })
```

It's an error from my code or an issue?

**Comment by eddiemonge** [comment]
What version of ui-router are you using?

Also:

```javascript
$scope.query = $stateParams.query || localStorageService.get('ships.query');
$scope.query = $scope.query || ''; // this one might be different if you really want to check against null

// comma first ewww
.state('loggedin.ships', {
      url: "ships",
      params : {
        page : 1,
        order : 'name',
        query : null
      },
      templateUrl: "partials/ship-list.html",
      controller: 'ShipListCtrl'
    })
```

**Comment by thecko** [comment]
I'm using v0.2.13 you can find it on my github: https://github.com/thecko/starmadeadmin/tree/symfony/web

I was trying to default as null, but in stateParams I find "undefined" in both cases, when the param is not present and when it's empty.

**Comment by eddiemonge** [comment]
not present and empty should both return undefined. Maybe you could update your code explicitly use `http://myproject/myState?query=null` when you want it to be empty? Also, why doesn't your code simply remove the query string when it shouldn't be there?

**Comment by thecko** [comment]
I'm not agree. "Empty String" it's not the same as null. Let me present a few different scenarios that may help to understand the difference.

**Scenario 1: You enter the app for the first time**
URL: /ships
No querystring parameter
Result: Default value (empty), all data is retrieved and local storage is set to ""

**Scenario 2: You change the input value**
URL: /ships?query=XXX
Query string present
Result: XXX is the value of the var and local storage is set to "XXX"

**Scenario 3: You return to the app from another part**
URL: /ships
Query string not present
Result: XXX is the value of the var because is the value of the local storage

**Scenario 4: You empty the input value**
URL: /ships?query=
Query string present but empty
Result: "" is the value of the var because is from a conscious action of the user 


As you may know, it's like in PHP with the "isset" or isEmpty functions, that you can know if it exists or not.

**Comment by eddiemonge** [comment]
Scenario 1-3 I get. Scenario 4 is the one I question. Shouldn't emptying the value also remove the query string (and set the localStorage to ""? These are actions performed inside of your app and not by directly manipulating the URL right? Even if the user manually went to the location bar and typed `/ships?query=` or `/ships` shouldn't the end result be that they get the results from scenario 1?

**Comment by eddiemonge** [comment]
@thecko ^^

**Comment by thecko** [comment]
Ops sorry, I've been on holidays and I've not answered, sorry.

What you say works on some scenarios, but imagine you are using the app and the last time before closing you've searched "foo", the local storage will keep it. Then, imagine another person wants to send me a link to /ships without filtering. If I follow a link to /ships (without the query var), what the app will do is write "foo" because is what is in the local storage.

Sorry if I insist, "undefined" may be the value when the query is not present (/ships), "empty string" when it's present but without value (/ships?query=), and true when present without the "=" (/ships?query).

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
