### ISSUE TITLE
Using null for parameters breaks the type check

### ISSUE THREAD

**Issue by sz-alpar** [angular-ui/ui-router#1924]
My coworker used `null` for some parameters and since version `0.2.14` our production site stopped doing state changes as expected.

It took my quite a while to narrow down the problem. I think it is caused by the `isDefined(val)` check in 
```
function arrayWrap(val) { return isArray(val) ? val : (isDefined(val) ? [ val ] : []); }
```
If `val` is `null`, the resulting array will be a `[null]` array for which the type check doesn't work.

Maybe the problem lies somewhere else, because I find it strange that a `null` value is compared to an array...

Anyhow, the best practice is not to use `null` in such cases. Omitting the parameter or using `undefined` solves the issue.

**Comment by eddiemonge** [comment]
Duplicate of #1915 most likely.

**Comment by nateabele** [comment]
Yup, please follow the discussion there. Thanks.
