### ISSUE TITLE
Custom param type decode method no longer triggered in 0.2.14

### ISSUE THREAD

**Issue by anpsince83** [angular-ui/ui-router#1926]
It appears that the way custom param types handle encoding/decoding have changed or have been broken with the 0.2.14 release. The `decode` method no longer seems to be firing.

I have the following custom type:
```javascript
$urlMatcherFactoryProvider.type('PwsType', {
        encode: function(value) {
            console.log('value to encode', value);

            return 'with/' + value;
        },
        decode: function(value) {
            console.log('value to decode', value);

            var decodedValue = value.split('/');

            if (decodedValue.length > 1) {
                value = decodedValue[1];
            }

            return value;
        },
        is: function(value) {
            return true;
        },
        pattern: /(?:with\/)\w+/
    });
```

The purpose is to create a param that is something like 'with/value' where 'with/' is appended to the value of the param during encode, and removed during decode. This worked fine with 0.2.13. When the url contained 'with/value', the `decode` method would fire and return 'value' as the value of the state param. With 0.2.14 it simply does not ever get triggered.

Using the console logs on the param type above, and one on a state definition resolve to output the value of the param, here is what I see on page load for a url containing 'with/blah' in 0.2.13:

![screen shot 2015-04-28 at 11 41 00 am](https://cloud.githubusercontent.com/assets/967604/7377798/9c36cfdc-ed9d-11e4-87e2-ea9335516592.png)

In 0.2.14:

![screen shot 2015-04-28 at 11 44 01 am](https://cloud.githubusercontent.com/assets/967604/7377804/9f00fb7a-ed9d-11e4-8ab1-2e63811fd538.png)

Notice that the value is not decoded.

Am I not utilizing the custom type correctly, or did something change in 0.2.14 for custom types to cause this issue? Or is this in fact a bug? This recipe was working perfectly in 0.2.13.

**Comment by eddiemonge** [comment]
If i had to bet, I'd bet it is related to #1915

**Comment by anpsince83** [comment]
Is anyone looking into this? Anyone else experiencing this?

**Comment by eddiemonge** [comment]
yeah @nateabele I think is in issue #1915.

**Comment by eddiemonge** [comment]
Please try this fix in the related issue. If it doesn't fix it, report back and I'll reopen this. Thanks.

**Comment by anpsince83** [comment]
@eddiemonge I applied the fix in issue #1915: ba6ed61 on top of 0.2.14 and it had no effect. The `decode` method still is not getting triggered.

**Comment by eddiemonge** [comment]
Could you do a plunkr example?

**Comment by ckniffen** [comment]
I wonder if the issue is caused by the following code change b0c6aa2350fdd3ce8483144774adc12f5a72b7e9. Specifically urlMatcherFactory.js line 484 and 973.

**Comment by anpsince83** [comment]
@ckniffen, that change is precisely the cause. Thanks for finding that! If I change the `is` method to ensure the string value doesn't match the pattern, the `decode` method is then called:

```javascript
$urlMatcherFactoryProvider.type('PwsType', {
        encode: function(value) {
            console.log('value to encode', value);

            return 'with/' + value;
        },
        decode: function(value) {
            console.log('value to decode', value);

            var decodedValue = value.split('/');

            if (decodedValue.length > 1) {
                value = decodedValue[1];
            }

            return value;
        },
        is: function(value) {
            // ensure value is a string and does not match the pattern
            // if it does, the `decode` method will then be triggered
            return angular.isString(value) && !this.pattern.test(value);
        },
        pattern: /(?:with\/)\w+/
    });
```
I now see the purpose of the `is` method. The docs weren't the most clear on that. Anyhow, this appears to solve the issue, so I'm marking this as closed. Thanks @eddiemonge and @ckniffen for your assistance!
