### ISSUE TITLE
Regression: $location.replace() with changes only to stateParams using reloadOnSearch:false - still cause page reload

### ISSUE THREAD

**Issue by benbracha** [angular-ui/ui-router#1927]
Hey,

Doing the following:
$location.search('myParam', 'someValue');
$location.replace();

Seems to cause page reload, even when we use "reloadOnSearch:false" for our state.
We use angular 1.3.15 and angular-ui-router 0.2.14 (Chrome  42.0.2311.135 (64-bit) - latest)

The strange thing is, that it started to happen only on the following scenario:
- Since Chrome 42 version.
- When navigate to our app using Chrome's basic-authentication via URL, for example: 
http://username@email.com:password@127.0.0.1:9000

It doesn't happen if we use Chrome 41 or on Chrome 42 without the basic-authentication navigation feature.

So the flow is the following:
1. We navigate to our app as above.
2. Then click some element that causes navigation to a new state
3. The new state is doing $location.search('myParam','myValue') then $location.replace()
4. A page reload occurs.

(BTW, the reason we use the URL basic-authentication feature - is for selenium-testing for our app).

Any ideas what could cause this regression?

**Comment by nateabele** [comment]
We pushed 0.2.14 less than a week ago. Do your tests pass on 0.2.13?

**Comment by benbracha** [comment]
Nope. Actually we worked with 0.2.13, I wasn't sure if this is related - so I tried also 0.2.14.
It doesn't work on 0.2.13 as well

**Comment by nateabele** [comment]
Add `$rootScope.$on("$locationChangeSuccess", console.log.bind(console));`, and see if that displays anything. If yes, it's probably a UI-Router bug. If no, it's probably a Chrome or Angular bug.

**Comment by benbracha** [comment]
Interesting. It does print some stuff, but now I see it also prints this exception (which wasn't before):

Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.3.15/$rootScope/infdig?p0=10&p1=%5B%5D
    at REGEX_STRING_REGEXP (http://upitewta.balovgop%40ravellosystems.com:astadatifgefdek@127.0.0.1:9000/bower_components/angular/angular.js:63:12)
    at Scope.$get.Scope.$digest (http://upitewta.balovgop%40ravellosystems.com:astadatifgefdek@127.0.0.1:9000/bower_components/angular/angular.js:14346:19)
    at Scope.$get.Scope.$apply (http://upitewta.balovgop%40ravellosystems.com:astadatifgefdek@127.0.0.1:9000/bower_components/angular/angular.js:14571:24)
    at http://upitewta.balovgop%40ravellosystems.com:astadatifgefdek@127.0.0.1:9000/bower_components/angular/angular.js:16308:36
    at completeOutstandingRequest (http://upitewta.balovgop%40ravellosystems.com:astadatifgefdek@127.0.0.1:9000/bower_components/angular/angular.js:4924:10)
    at http://upitewta.balovgop%40ravellosystems.com:astadatifgefdek@127.0.0.1:9000/bower_components/angular/angular.js:5312:7 undefined

**Comment by benbracha** [comment]
Sorry - this one was before adding the console print, I just missed that. I wonder if this is related

**Comment by nateabele** [comment]
Unfortunately there's not enough information to say. If you can post a plunkr with a reproduction of the issue, I'll take a look.

**Comment by benbracha** [comment]
Ok, it is a bit tricky but here it is:
http://plnkr.co/edit/C1VFq5gP6VIZ9bNLPm64?p=preview

This a simple 2 states UI router app. "Home" and "Page1".
"Page1" also has a controller that changes (adds) a param to its state and do $location.replace(). It is also configured with "reloadOnSearch:false".

You should run the above using the separate window option (and not the embed version, which takes out the state params, not sure why):
(1) http://run.plnkr.co/FvFE87Kb51jHYlbI/#/home

Running the above - going through the 2 states, works fine.
Now, try to run it with Chrome's (42) URL basic-authentication feature. For example navigate to:
(2) ben:ben@http://run.plnkr.co/FvFE87Kb51jHYlbI/#/home
(if the plunker breaks, just start it again with (1) and change the URL again).
Then, navigate to home, and to page1. When navigating to page1, you'll get a console exception (and you'll see the page is reloading, keep the console.log preserved between navigation of course..)

**Comment by benbracha** [comment]
BTW - it seems you need to sign in into plunker for it to work well (tried it here on another machine, when using the ben:ben@ option the plunk stopped working until we signed in)

**Comment by benbracha** [comment]
Hey,
And updates on this item? Currently this seems to block us to do testing using chrome..

**Comment by christopherthielen** [comment]
@benbracha can you try with 0.2.15? See this updated plunk:
http://plnkr.co/edit/6MPpWqugEHi5Stf2r0wZ?p=preview

**Comment by benbracha** [comment]
Still cause a page refresh, and an error shown in the log.
You can try it according to the scenario I wrote above

**Comment by christopherthielen** [comment]
It happens without ui-router involved, this must be an angular bug related to the user/password and $location
http://plnkr.co/edit/6MPpWqugEHi5Stf2r0wZ?p=preview

**Comment by benbracha** [comment]
Thanks.
Where should I continue this thread? On angular repo?

**Comment by christopherthielen** [comment]
Yeah. I'd first try the most recent builds of both angular 1.3 and 1.4, then search the angular issues, then file a bug there.
