### ISSUE TITLE
is 'stateConfig.params' a must to use non-url parameters?

### ISSUE THREAD

**Issue by theGivingTree** [angular-ui/ui-router#1928]
For this `$stateProvider` setup,

```javascript
    $stateProvider
      .state('foo', {
        url: 'foo/:bar',
        templateUrl: 'template/foo-view.html',
        controller: controllerFn
     });
```

`<a ui-sref="foo({bar: 123, hello: someObj})">go</a>`
doesn't seem to pass `hello: someObj` to `controllerFn`. Only for `bar: 123` works as expected.
But when I add `params: {hello: null}` to stateConfig, everything works perfectly.

I wonder if this is an expected behavior.

I'm actually using ionic, which utilizes ui-router 0.2.13.

**Comment by eddiemonge** [comment]
Yes. Unless its in the actual URL, then it will get passed in as a param.

If you know you are going to pass it in like that, why not define it in the state config?

**Comment by theGivingTree** [comment]
I thought `stateConfig.params` is just for default-value setting.
But now it seems your suggestion more reasonable.
Thank you for answer.

**Comment by eddiemonge** [comment]
I don't mean you have to put it into .params. You could do:

```javascript
    $stateProvider
      .state('foo', {
        url: 'foo/:bar?hello',
        templateUrl: 'template/foo-view.html',
        controller: controllerFn
     });
```

To let `hello` by a query param that can then be paused in as a param

**Comment by theGivingTree** [comment]
What if `someObj` is not primitive? In which case the url will be,
`foo/123/[object Object]` (not escaped)
That is not what I want.
