### ISSUE TITLE
how to pass the query parameter with the othwerwise function

### ISSUE THREAD

**Issue by david-gang** [angular-ui/ui-router#1929]
Hi,

This is a cross post from stackoverflow: https://stackoverflow.com/questions/29947227/how-to-pass-the-query-parameter-with-the-othwerwise-function

Given the following javascript:
```javascript
$stateProvider
            .state('search', {
                url: '/search?query',
            })

        ;

        $urlRouterProvider.otherwise("search");
```

When i access the page in html5mode

base_url?query=x

I get redirected to

    base_url/search

but the query parameter gets lost.

When i access the page in not html5mode I get

base_url?query=x

I get redirected to

    base_url?query=x/#search
which is very ugly

Is there a way to pass the query parameter with the otherwise function in html5mode?

I looked already in the documentation and there is no explanation how to do this.

Thanks,
David

**Comment by eddiemonge** [comment]
This isn't like an Apache or nginx redirect. The URL you entered will not get passed in as the query. Your code is literally saying, if no url matches then go to the `search` state and use URL `/search`. It won't show query because you have not provided a value for it, either in the `otherwise` redirect or the state config.

**Comment by david-gang** [comment]
Hi,

Here is an answer according to 
https://stackoverflow.com/questions/29947227/how-to-pass-the-query-parameter-with-the-othwerwise-function/30010428#30010428
 by [Radim Köhler](https://stackoverflow.com/users/1679310/radim-k%C3%B6hler)

```javascript
$urlRouterProvider.otherwise(function($injector, $location){
    var state = $injector.get('$state');
    state.go("search", $location.search()); // here we get { query: ... }
    return $location.path();
});
```

So we can perform this by the existing ui-router code.
