### ISSUE TITLE
same page # id navigation is not working , more over messedup 

### ISSUE THREAD

**Issue by moorthi07** [angular-ui/ui-router#1930]
same page # id navigation is not working , more over messedup by adding a '/' in front of the '#identifier' like
'index.html#/section2'
This doesn't navigate and messing up regular html flow if used ui-router.js

**Comment by nateabele** [comment]
Okay, please set up a plunkr so we can see what's going on and try to find a workaround.

**Comment by moorthi07** [comment]
Here,
 to make it easy,
How would you do this simple page with ng-ui when I DO NOT WANT TO or NEED TO chop all the < div > into a separate .html file (I really don't understand why should I have to have 100 .html files?)

http://www.codeply.com/render/DRBmOoChfM

**Comment by eddiemonge** [comment]
This seems to work. If you think its not working properly now, please let me know which part isnt working
