### ISSUE TITLE
UI-View is not showing a default content before state takes effect

### ISSUE THREAD

**Issue by moorthi07** [angular-ui/ui-router#1931]
If I need a landing page, the default content between the the element is not showing until the link is clicked. *<  div ui-view   > This is my landing page. You will see this content changing  when you click on menu. This really sucks as this text is not showing up until a state is activated <   /div> " *

(update: Sorry the markdown feature didn't work. Hope you see 'DIV ' elements  now.)

**Comment by eddiemonge** [comment]
Did you mean to paste an example?

If you want a landing page then make a state with one in it and go to that first.

**Comment by moorthi07** [comment]
You might get this right,
How would you do this simple page with ng-ui when I DO NOT WANT TO or NEED TO chop all the < div > into a separate .html file (I really don't understand why should I have to have 100 .html files?)

http://www.codeply.com/render/DRBmOoChfM

**Comment by eddiemonge** [comment]
Thats really one page and you don't need states so much as a directive that looks to see what tab should be active (should be in the url somewhere) and then scrolls to it.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
