### ISSUE TITLE
menus from MySQL database

### ISSUE THREAD

**Issue by albanelshani** [angular-ui/ui-router#1935]
Hi everyone who sees this.

I am building a website for a friend of mine, that he wants to have some menu items/links now, but he might change them in the future, so i made a MySQL table for the primary links to be saved there, so in this case i don't know any state at all to start navigating, i was trying to figure out from this wiki, the example for ui-router and some other searches online but i can't still figure out how to do it.

What i tried is this: 
1. I modified the services from the example http://angular-ui.github.io/ui-router/sample/ so it will get the primary menu items from the database, 
2. In app.js to the stateProvider i added a default state for home page, there i included the resolve and controller, i used console.log to see if the service is getting the object/json data from the database (because i console.log doesn't print anything inside app.config in the resolve or controller objects) and it gets something like this " d {$$state: Object, success: function, error: function, then: function, catch: function…} " in which i know the $$state: Object is where my data are!

The problem is that i can't/(don't know how) to use the data i get from DB and make them as links. 

Example: the primary links might be news, sports, economy or something else, each of them will have articles that should have their own links, so basically it is a two level menu but all taken from database.

From the point number 2 i made i see a problem because it has to be on the home page to get the data right? what if someone was on the website and knows that sports category exists and he tries to go there directly, will the it take him/her there or will it take them on the home page even though i couldn't make that work either.

If there is a way can someone please help me with this problem i have.

Thank you very much.

**Comment by eddiemonge** [comment]
It sounds like you need to read a few more tutorials on getting started with Angular. This is a more appropriate question for stackoverflow as its not a bug in UI-Router. Maybe take a look at https://www.codementor.io/angularjs/tutorial/create-dropdown-control (not a recommendation just one of the first examples from a quick google search).
