### ISSUE TITLE
$stateParams is empty inside Interceptor when using resolve

### ISSUE THREAD

**Issue by sikko** [angular-ui/ui-router#1936]
## What I want to achieve:

Send a token that I get from the url stateParams with every request. For this i'm using an http Interceptor.

The interceptor looks like this:

    .factory('myInterceptor', function($stateParams){
        return {
            request: function(config){
                config.url = config.url + '?text=' + $stateParams.token;
                return config;
            }
        }
    })

## My problem

Inside the interceptor, the $stateParams is empty when $http is called inside the resolve. However when I call it from inside the controller, it works fine.

**Working example**:

> Using $http inside the controller: http://jsfiddle.net/sikko/drLg06w8/8/

    controller: function ($scope, $http) {
      $http.post('/echo/jsonp').success(function(response){
        $scope.text = response.text;
      });
    }

**Non Working example**:

> Using $http inside the resolve: http://jsfiddle.net/sikko/drLg06w8/7/

    resolve: {
      resolveVar: function($http){
        return $http.post('/echo/jsonp').success(function(response){
          return response.text;
        });
      }
    },
    controller: function ($scope, resolveVar) {
      $scope.text = resolveVar.data.text;
    }

I did console.log in both examples so you can see that $stateParams is empty when using resolve.

My Guess is that the resolve cycle is called before that $stateParams is made available by angular or something like that... But I have no clue how to fix it... Any help would be much appreciated!

**Comment by eddiemonge** [comment]
Store the token somewhere else like localStorage or in angular memory. Does the text change often? Why is it in a query string?

**Comment by sikko** [comment]
I want my users to click on a link that has been sent by email. Then read the token accordingly. That's why it is in the query string. I could try saving it somewhere else indeed, even though I'd prefer a cleaner solution.

**Comment by eddiemonge** [comment]
If they are browsing around do you really want to carry the token in every url?

**Comment by sikko** [comment]
Actually it's not about carrying the token around in every url. It's about getting it from the url the first time.

I ended up using a quick a dirty solution.

- Inside the resolve, store the token in a rootScope variable.
- Inside the interceptor, access the rootScope.

This works for some reason.
If anyone ever finds a cleaner alternative, i'll take it!
