### ISSUE TITLE
Problem with multiple nested views

### ISSUE THREAD

**Issue by nblaudez** [angular-ui/ui-router#1939]
Hi,

I try to setup ui-router with multiple nested views, but that seem doesn't work.
Does someone can help me ?

you can see code here

http://stackoverflow.com/questions/30017996/angular-ui-router-route-registration

and here :
http://plnkr.co/edit/5W8Ro2TnJvMx9CVEntkZ?p=preview

**Comment by eddiemonge** [comment]
It was answered on stackoverflow. It doesn't need to be opened here as well.
