### ISSUE TITLE
Default param not recognized

### ISSUE THREAD

**Issue by piernik** [angular-ui/ui-router#1946]
I've got problem with default param
Here is my state
```
.state('app.mail.add', {
	url: 'add/?id&email',
	params: {
		documents: true,
		id: null,
		email: null
	}
});
```
I want that `documents` be always `true`.
Problem is that when entering `add/?id=20&email=email@email.com` param `documents = undefined` :/
Why?

**Comment by eddiemonge** [comment]
What version of ui-router are you using?

**Comment by piernik** [comment]
0.2.14

**Comment by eddiemonge** [comment]
Its probably a duplicate of #1915 then. 

You might also want to do 
```params: {
  documents: {
    squash: false,
    value: true
  }
}
```

**Comment by piernik** [comment]
Thanks it works
