### ISSUE TITLE
$state.params and $stateParams are different during resolve phase of ui-router.

### ISSUE THREAD

**Issue by xueye** [angular-ui/ui-router#1948]
I made [this demo](http://plnkr.co/BXIBNlDcC6aKMigroDJJ) to demonstrate the issue; while resolving, `$state.params` is not populated, while `$stateParams` is populated. As far as I can tell, they should be the same thing.

**Comment by eddiemonge** [comment]
I agree they should be. Although if they are, what is the point of having two things that are the same?

**Comment by christopherthielen** [comment]
`$stateParams` is a "locals object" injected into states during a transition using `$injector.invoke()`.  It is specially filtered to only those params that are declared on the state it is being injected into.

`$state.params` is updated only once the transition promise has successfully resolved, like `$state.current`

Confusing, yes, but this is how it is supposed to work.
