### ISSUE TITLE
How to pass custom data in $state.go() in angular-ui-router?

### ISSUE THREAD

**Issue by victorwoo** [angular-ui/ui-router#1949]
I want to pass a custom object to another state via `$state.go()` in UI-Router.

    var obj = {
    	a: 1,
    	b: 2,
    	fun: function() {
    		console.log('fun');
    	}
    }
    $state.go('users', obj);

But I need to run `fun()` in target state, so I can't pass this object in URL parameter. In target controller, I tried to fetch the value of `obj` via `$stateParams` but got empty object `{}`:

    function UserCtrl($stateParams) {
    	conrole.log($stateParams); // empty
    }

So how to pass `obj` to state "users" correctly?

**Comment by zhdanovartur** [comment]
```js
$stateProvider.state('users', {
    url: '/users',
    controller: 'UsersCtrl',
    params: {
        obj: null
    }
})
```

```js
function UserCtrl($stateParams) {
    conrole.log($stateParams); // empty
}
```

```js
$state.go('users', obj);
```

**Comment by christopherthielen** [comment]
@zhdanovartur :+1:

**Comment by victorwoo** [comment]
Sorry but this approach produces the following error:

    Uncaught Error: [$injector:modulerr] Failed to instantiate module myapp due to:
    Error: Invalid params in state 'users.login'
        at Object.stateBuilder.params (http://localhost:9600/bower_components/angular-ui-router/release/angular-ui-router.js:1269:41)
        at registerState (http://localhost:9600/bower_components/angular-ui-router/release/angular-ui-router.js:1390:72)
        at $StateProvider.state (http://localhost:9600/bower_components/angular-ui-router/release/angular-ui-router.js:1702:5)
        at http://localhost:9600/components/users/users.js:10:4
        at Object.invoke (http://localhost:9600/bower_components/angular/angular.js:4203:17)
        at runInvokeQueue (http://localhost:9600/bower_components/angular/angular.js:4109:35)
        at http://localhost:9600/bower_components/angular/angular.js:4118:11
        at forEach (http://localhost:9600/bower_components/angular/angular.js:323:20)
        at loadModules (http://localhost:9600/bower_components/angular/angular.js:4099:5)
        at createInjector (http://localhost:9600/bower_components/angular/angular.js:4025:11)
    http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=ums.anypay&p1=Erro…F%2Flocalhost%3A9600%2Fbower_components%2Fangular%2Fangular.js%3A4025%3A11)

**Comment by christopherthielen** [comment]
@victorwoo that message comes from version of ui-router `0.2.10` and earlier, which don't support passing objects as parameters.

**Comment by victorwoo** [comment]
Yes, it works after upgrading to `0.2.14`.
Thank you @zhdanovartur @christopherthielen

**Comment by rroxysam** [comment]
@zhdanovartur  @christopherthielen, Thanks a lot !!!!!!. It also solved my problem which i am stuck for half an hour.

**Comment by godolatunji** [comment]
@zhdanovartur Thanks fam, you just saved me a headache.

**Comment by dptole** [comment]
+1 to @zhdanovartur even though it is kind of a weird solution.

**Comment by rajaneeshgit** [comment]
@zhdanovartur @christopherthielen, Thanks a lot..!!! It is really helpful.

**Comment by sasanazizi** [comment]
@zhdanovartur 
i have use your answer but when i'm change state :
Could not resolve 'undefined' from state 

what should i do?!

**Comment by iurynog** [comment]
Funcionou demais! :D

**Comment by iurynog** [comment]
Funcionou demais :D

**Comment by Ram-SR** [comment]
The values are changing on page refresh. How to prevent that?

**Comment by gtzinos** [comment]
@zhdanovartur  Thank you !!!

**Comment by MoatazGitHub** [comment]
@zhdanovartur  works but re correct      conrole.log($stateParams);

**Comment by zhdanovartur** [comment]
@MoatazGitHub fixed, thanks)

**Comment by jijishthomas** [comment]
$http.get('js/mockData.json')
        .then(function (res) {
          $scope.knowledgeBaseDetails = res.data.knowledgeBaseDetails
          $state.go('app.knowledgeBaseDetails');
          console.log($scope.knowledgeBaseDetails);
        });


i am having issue with the above code, 
the state is changing and data is there in console, but its not obtained in DOM

**Comment by chiptus** [comment]
@jijishthomas when you change the state, the $scope will change. you need to pass the data to the route and get it in the new route from $stateParams

**Comment by viT-1** [comment]
@zhdanovartur $stateParams is deprecated.
How can i send params to component controller nowadays within $state?

**Comment by Vortilion** [comment]
@viT-1 Exactly the same.
