### ISSUE TITLE
0.2.14 feature "multiple nested uiSref directives" does not seem to work

### ISSUE THREAD

**Issue by starf** [angular-ui/ui-router#1950]
It seems the "multiple" part does not work. This is the way it's supposed to work right?
There is always only one item "active", for menu 1 it's menu 1 and for menu 2 it's the parent li
```
<li class="dropdown" ui-sref-active="active" dropdown>
	<a class="dropdown-toggle" dropdown-toggle>main menu item <b class="caret"></b></a>
	<ul class="dropdown-menu">
		<li ui-sref-active="active"><a ui-sref="WeekPerformanceSheet">menu 1</a></li>
		<li><a ui-sref="WeekendDistribution">menu 2</a></li>
	</ul>
</li>
```

**Comment by starf** [comment]
added plunkr, seems obvious enough
http://plnkr.co/edit/Cp56i7lfCEFuNUraf7fv?p=preview

**Comment by eddiemonge** [comment]
Seems to be working fine. When menu 1 is active, the `<li ui-sref-active="active">` has `active` class. When menu 2 is active, `<li class="dropdown" ui-sref-active="active" dropdown>` has `active` class.

> The first ui-sref-active found at the same level or above the ui-sref will be used.

**Comment by starf** [comment]
Nevermind, my bad.
I was way too excited and thought the following new feature was for ui-sref-active.
```
uiSrefActive: Added support for multiple nested uiSref directives (b1844948)
```
