### ISSUE TITLE
$stateParams is not woking for more than 2 level depth?

### ISSUE THREAD

**Issue by maryampashmi** [angular-ui/ui-router#1952]
Hi, 

I have more than 2 level nested object. When i use console.log, i am getting only for 2 level and the other value for other parameter is empty. If somebody know solution.
This is my issue in stackover flow:
http://stackoverflow.com/questions/30186531/how-to-pass-parameter-with-ui-sref-between-deeply-nested-objects

Thank you.

**Comment by eddiemonge** [comment]
Commented on SO with a quesstion

**Comment by eddiemonge** [comment]
seems fixed on SO
