### ISSUE TITLE
Is it possible to get access to a service in myApp.config(function(MYSERVICE ?

### ISSUE THREAD

**Issue by LordWingZero** [angular-ui/ui-router#1953]
I have a SessionService that has data on the user, including their default state. Basically i need the code below to work. I understand that during the config portion of the life-cycle services are not created yet, only providers are. So maybe there is another way to do what I am trying to do?

```
function config($urlRouterProvider, stateHelperProvider, Session) {
    $urlRouterProvider.otherwise(function ($injector, $location) {
        var $state = $injector.get("$state");
        Session.data.then(function (sessionData) {            
            if (SessionData.HomeState) {
                $state.go(SessionData.HomeState);
            } else {
                $state.go("root.plans");
            }
        }).catch(function () {
            alert("Fatal error in retrieving session data.");
        });
    });

    // stateHelperProvider.state ...  Ect...

```

**Comment by marshall007** [comment]
I think you should just be able to inject `Session` the same way you got a reference to `$state`. Just do it within the `otherwise` rather than making it a dependency of the `config` block.

**Comment by eddiemonge** [comment]
@LordWingZero Does that solve your problem?

**Comment by LordWingZero** [comment]
Yes! Thank you!
