### ISSUE TITLE
Radio ng-model only works if model is an object

### ISSUE THREAD

**Issue by mattclough1** [angular-ui/ui-router#1954]
This is really strange, but maybe I'm misunderstanding something. In a template for a view in a nested state, which is the child of an abstract state, `ng-model` works fine for everything on the page except three radio buttons. The model was originally just a string to refer to a scope value, in this case, "dividers". If `$scope.dividers` was set equal to a value in the controller, the radios would be checked appropriately when the page loaded, but if the value was changed, the view would create a separate `dividers` value in its own scope. Instead I set `$scope.dividers` equal to an object literal and set the `ng-model` equal to a key in the object. Now it works fine. Shouldn't it be able to refer to a single string value?

**Comment by eddiemonge** [comment]
I feel like this has very little to do with ui-router, as in nothing at all. This might be better on stackoverflow

**Comment by eddiemonge** [comment]
If you can demonstrate an actual bug attributable to ui-router, I'll gladly reopen this. Otherwise I'm closing as outside of ui-router scope.
