### ISSUE TITLE
$viewContentLoaded and $viewContentLoading not trigger

### ISSUE THREAD

**Issue by gollodev** [angular-ui/ui-router#1955]

**Comment by eddiemonge** [comment]
Can you give some more information about this please? Version of ui-router, example code, etc

**Comment by gollodev** [comment]
I some confused with the doc de UI-Router https://github.com/angular-ui/ui-router/wiki

**Comment by gollodev** [comment]
$viewContentLoaded and $viewContentLoading should found with .run()

**Comment by gollodev** [comment]
ui-router version v0.2.14

**Comment by eddiemonge** [comment]
They aren't really "found" with `.run()`. You can assign event listeners to them in the in the run block that are then performed when the events are fired. If you have an example showing they aren't fired, please share it and I'll reopen the ticket.
