### ISSUE TITLE
Resolve is fired twice

### ISSUE THREAD

**Issue by piernik** [angular-ui/ui-router#1956]
I'm using ui-router 0.2.14 My state is
```
.state('app.mail.add', {
	url: 'dodaj/?firma_id&email&odpowiedz_na&dokumenty&emaile',
	params: {
		odpowiedz_na: {
			squash: false,
			value: null
		},
		dokumenty: {
			squash: true,
			value: true
		},
		emaile: {
			squash: true,
			value: true
		},
		firma_id: {
			squash: false,
			value: null
		},
		email: {
			squash: false,
			value: null
		}
	},
    resolve: myFunc()
});
```
If I triger `ui-sref="app.mail.dodaj({odpowiedz_na:210})"` my resolve func is fired twice - first time with params 
```
odpowiedz_na=210
dokumenty=undefined
emaile=undefined
...and so on
```
Second time with default values:
```
odpowiedz_na=210
dokumenty=true
emaile=true
...and so on
```
But when I enter url address `dodaj/?odpowiedz_na=210` resolve if fired once (with default params).

**Comment by eddiemonge** [comment]
Can you make a plunkr example demonstrating this?

**Comment by piernik** [comment]
It turns out that I was using v 0.12.1 I've updated and everything works fine - thanks
