### ISSUE TITLE
angular-animate master no longer allows callbacks.

### ISSUE THREAD

**Issue by robertbaker** [angular-ui/ui-router#1959]
Using the master branches of ui-router and angular (1.4.x).

Please fix asap.

```
Error: [$animate:nocb] Do not pass a callback to animate methods
http://errors.angularjs.org/1.3.16-build.111+sha.0515614/$animate/nocb
    at http://localhost:3000/bower_components/angular/angular.js:63:12
    at Object.$$assertNoCallback (http://localhost:3000/bower_components/angular/angular.js:4684:17)
    at parseAnimateOptions (http://localhost:3000/bower_components/angular-animate/angular-animate.js:558:21)
    at Object.enter (http://localhost:3000/bower_components/angular-animate/angular-animate.js:955:21)
    at Object.enter (http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:3855:34)
    at http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:3929:22
    at publicLinkFn (http://localhost:3000/bower_components/angular/angular.js:7039:29)
    at updateView (http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:3928:23)
    at http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:3896:9
    at invokeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8302:9) <!-- uiView: undefined --
```

**Comment by eddiemonge** [comment]
Can you make an example showing this?

**Comment by luzat** [comment]
I stumbled across this, too. Promises/thenables are already used by UI router, but unfortunately Angular now errors when passing a cb in the following lines:

    var promise = $animate.enter(element, null, target, cb);
    var promise = $animate.leave(element, cb);

Removing the cb suffices as a quick fix for current master it seems, but would not work for old versions.

**Comment by christopherthielen** [comment]
I thought we had some conditional code to support animating in both 1.2 and 1.3+

**Comment by luzat** [comment]
This code broke because of angular/angular.js@9bb4d6ccbe80b7704c6b7f53317ca8146bc103ca :-/

**Comment by jayharvey** [comment]
+1 Please fix! Thanks!

**Comment by leedavidr** [comment]
+1 I'm on angular 1.3.16 and getting the same error

**Comment by matsko** [comment]
This has been reverted for 1.3, but 1.4 is strict with the change.

Unfortunately you'll need to check the version in your code when using 1.4.

```js
var IS_14 = angular.version.major === 1 && angular.version.minor === 4;
if (IS_14) {
   $animate.enter(element, null, target).then(cb);
} else {
   $animate.enter(element, null, target, cb);
}
```

**Comment by eddiemonge** [comment]
that seems not ideal

**Comment by matsko** [comment]
Then perhaps we can have it so that it automatically converts it to be chained onto the promise. Let me get back to you guys on that once I get a confirmation on that.

**Comment by christopherthielen** [comment]
It's not ideal, but I'm OK with checking for specific angular versions.  The current logic passes the callback style in no matter what, then checks if a promise came out or not.  Checking for angular version isn't much worse, and is more explicit.  

@matsko I'd actually prefer if you didn't auto-add a callback (if present) to the promise chain.  If you did we'd have yet another thing to check for when run under 1.3.17+ (or 1.4.x) which would be different than what we check for between angular 1.3.0 < x < 1.3.17 (which is send in callback, check if a promise came out).

My vote is simply keep ignoring the callback in 1.3.x and do a hard error in 1.4.  I think we'll just check if version is 1.3+ and do an if/else like you posted above (I believe the API changed in 1.3.0?).
