### ISSUE TITLE
URL fragment doesn't get updated when browsing inside a current state

### ISSUE THREAD

**Issue by borodean** [angular-ui/ui-router#1961]
Nothing happens when an ui-sref pointing to an anchor on an already active state is clicked, so it cant really be used for browsing the portions of the current page.

Demo: http://plnkr.co/edit/6KM0DRXB38gcGjgYkgjd?p=preview
Switching from `beta` to any of `alpha` works; switching between `alpha` is not—hash stays the same.

**Comment by eddiemonge** [comment]
Duplicate of https://github.com/angular-ui/ui-router/issues/701

**Comment by nateabele** [comment]
Looks like this is actually a bug related to the patch that fixed #701.

**Comment by nutlike** [comment]
A (dirty) fix until this issue is addressed: Adding `data-ui-sref-opts="{reload: true}"` to the links makes the Plunkr work (but obviously reloads the state as a whole). Just mentioning it because some people might need it.
