### ISSUE TITLE
$state.go fails to transition to the same state

### ISSUE THREAD

**Issue by the-simian** [angular-ui/ui-router#1963]
If I am in a certain stay, such as `x.y` if I attempt to transition into the same state I am currently in, possibly with updated state params, the transition does not fire.

```
//in x.y
$state.go('x.y', { someParam: 'newvalue'}); //nothing happens
```
This occurs if `reloadOnSearch` is true (it should be by default anyways) and also if you set `{reload: true}`

```
//in x.y
$state.go('x.y', { someParam: 'newvalue'}, { reload: true}); //also nope
```

This occurs in `0.2.14`, but not `0.2.13`

**Comment by the-simian** [comment]
references #1933

**Comment by the-simian** [comment]
Ok I got it the bug repro working. It seems to be relates, specifically to `null` for params
Observe the behavior in these two plunkr:

[Version 0.2.13](http://embed.plnkr.co/zIZDLD/preview) - working
[Version 0.2.14](http://embed.plnkr.co/LhxOeSxYxp4VsNnSkNua/preview) -not working

In the past, setting a parm to null removed it, now it prevents a state change entirely.

**Comment by christopherthielen** [comment]
This is caused by the 'string' param Type .is() method changing from regexp test to `typeof(val) === 'string'`. I hadn't intended to change the behavior of string Type until a breaking change release.  Sorry about that. 0.2.15 will make string types optional once more.

**Comment by the-simian** [comment]
@christopherthielen Thanks for looking into this! Let me know if there's anything else I can do to help out!
