### ISSUE TITLE
Warning for not found views in state definition

### ISSUE THREAD

**Issue by tiagoroldao** [angular-ui/ui-router#1964]
I have noticed that the system doesn't throw any warnings when a view name is badly written in the state definitions. Lets say the view `subNav`was poorly written:

```javascript
$stateProvider.state('main.reseller.tlds.view', {
            url: '/:tldId',
            data: {
                title: TRANSLATE.SITE_TLD
            },
            views: {
                '@main.reseller': {
                    templateUrl: 'views/reseller/tlds/tld.html',
                    controller: 'TLDController'
                },
                'subNnav@': {
                    template:''
                }
            }
        })
```

This could result in a `view 'subNnav@' not found in the current context`, in a similar fashion to how ui-sref warnings are triggered. Would this be reasonable to add? I can have a go at it, but would like some input on whether it makes sense.

**Comment by christopherthielen** [comment]
it would make sense to me, but @nateabele is reworking how states and views interact, so it would likely be wasted effort at this point in time.

**Comment by tiagoroldao** [comment]
:+1:
