### ISSUE TITLE
search parameters - prevent reload if going to a child state

### ISSUE THREAD

**Issue by jahtalab** [angular-ui/ui-router#1967]
I have a parameter in parent state that shouldn't cause reload for the parent state if i'm going to any of its child states. (child states should be reloaded)

**Comment by eddiemonge** [comment]
Have you tried version 0.2.15 with `reloadOnSearch: false` ?

**Comment by jahtalab** [comment]
yes i have tried reloadOnSearch, it only works if I'm transitioning to the
same exact state, only with different parameters,
what i want is the ability to transition to a child state with different
parameter, without the parent state being reloaded.

**Comment by eddiemonge** [comment]
You could pass the param you want to the sibling: `$state.go('parent.sibling', {paramName: $stateParams.paramName}`

**Comment by jahtalab** [comment]
i could pass the parameter around but since that parameter is part of application's state that should be the same across all child states, it would be more convenient to define it once in the parent state and every child state would have access to it.

is this something you would consider adding in the future (like an option in parameter definition)?

**Comment by christopherthielen** [comment]
this won't work until dynamic params are implemented, sorry.  coming in 1.x
