### ISSUE TITLE
Named views lazy loading

### ISSUE THREAD

**Issue by skumarvenkat** [angular-ui/ui-router#1972]
Loading named views at run time(after loading state)  rather than loading at the time of state route access.

I tried to load view using below code but view is not showing up in UI.

```javascript
$view.load("viewName@stateName", { 
  view: { templateUrl:  'Test/Index' }, 
  locals: $state.myDst.globals, 
  params: $state.myStateParams, 
  notify: $state.myOptions.notify
})
```
After calling above code we are trying to add view to tab
```javascript
<tab ng-repeat="tab1 in tabs">
      <div>
        <div ui-view='{{tab.view}}'></div>
      </div>
 </tab>
```
Can we load named views dynamically after route access?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
