### ISSUE TITLE
Shared Controller betwen multiple views don`t sync $scope

### ISSUE THREAD

**Issue by Dryymoon** [angular-ui/ui-router#1976]
Here is example.
Go to state home, and next to state foo. And play with two inputs. In one case they syncs, in other not.
http://plnkr.co/edit/xAH4Dyui3mV2RzEe14YK

**Comment by eddiemonge** [comment]
I don't think they should sync `$scope`s

**Comment by Dryymoon** [comment]
In this  example state 'home' has controller,  state 'home.foo' hasn`t controller.
I think that 'home.foo' view should inherit parent controller with $scope if current state contoller undefined.
Now 'home.foo' inherit parent controller, but $scope-s is diffrent.
If state is 'home.foo' and we change value 'a' in parent state and ui, we see than in child sate ui this value dont synchronize.

**Comment by eddiemonge** [comment]
Yup, they shouldn't sync: https://github.com/angular-ui/ui-router/wiki/Nested-States-%26-Nested-Views#what-do-child-states-inherit-from-parent-states

**Comment by Dryymoon** [comment]
Very thanks.
One question: Is there a way to share one controller with common scope betwen multiple view in one state without services for share data?

**Comment by eddiemonge** [comment]
Use custom data properties maybe https://github.com/angular-ui/ui-router/wiki/Nested-States-%26-Nested-Views#inherited-custom-data

Why not use a service?
