### ISSUE TITLE
ngCloak removed prematurely

### ISSUE THREAD

**Issue by matteo-mosca** [angular-ui/ui-router#1979]
In a page like this:

    <html data-ng-app="mymodule">
	    <head>
		
		
		</head>
        <body data-ng-cloak="">
		    <div data-ui-view></div>
			<footer>
			    <div>My Footer Content</div>
			</footer>
		
        </body>
    </html>

When rendering in the browser, I first see the footer atop, unstyled, then the content of ui-view is loaded and page is fully rendered. I should not see the footer until everything is ready.

If I do the same without using ui-router (putting my template directly in the page) then everything works fine.

I have extensively searched online but found nothing that could help. Is this perhaps a bug or incompatibility of your library with the ngCloak directive?

**Comment by eddiemonge** [comment]
See https://github.com/angular-ui/ui-router/issues/487#issuecomment-27459619, and maybe http://stackoverflow.com/questions/21302344/ng-cloak-doesnt-help-for-angular-ui-router-for-hiding-elements-while-template-p
