### ISSUE TITLE
Lock state until object is updated

### ISSUE THREAD

**Issue by agjs** [angular-ui/ui-router#1982]
In my app, when user logs in he is automatically redirected to a default state in ui-router.

Now, what I need is something different. I want user not to be able to navigate or access any router before he updates his profile on profile state.

Basically, when user logs in / registers, companyDetails object which is where information about his company are stored is empty and I want to force user to first update his profile before he can access other pages.

Putting something like this in app.run works in its own way :

```
companyDetails.get(function(data) {
      if (!data) {
        $state.go('profile');
      }
```

but it doesn't really solve my problem since it only redirect the user to profile state and then user can still navigate from there etc.

Help really appreciated
Thanks in advance

**Comment by eddiemonge** [comment]
This is a question better suited for stackoverflow.

Here is something that might get you started though

```
  $rootScope.$on '$stateChangeStart', ( event, toState, toParams ) ->
    unless loggedIn
      event.preventDefault()
      $state.go '401'
```

**Comment by christopherthielen** [comment]
http://bit.ly/UIR-SOF
