### ISSUE TITLE
Feature: Route to Component Directive

### ISSUE THREAD

**Issue by timkindberg** [angular-ui/ui-router#1989]
Angular is fully heading to a component-driven architecture. The Angular 1.4 and 2.0 router (same router) will allow routing to components (aka directives with a template and controller). This was actually a great idea from the core team! It makes a lot of sense. I think ui-router would benefit from being able to route to a 'component' as well. With the new [angular.component proposal](https://github.com/angular/angular.js/issues/10007) it will be easier for the average developer to make components.

E.g.
```javascript
$stateProvider.state('home', {
    url: '/',
    component: 'home'
})

angular.directive('home', function(){
    return {
        template: `<h1>Home Sweet Home</h1>
                         <ui-view></ui-view>`,
        controller: function($state) {
        }
    }
})
```

Just an idea...

**Comment by eddiemonge** [comment]
Would this really be that much different than doing

```javascript
$stateProvider.state('home', {
    url: '/',
    template: '<home />'
})

angular.directive('home', function(){
    return {
        template: `<h1>Home Sweet Home</h1>
                         <ui-view></ui-view>`,
        controller: function($state) {
        }
    }
})
```

Or would that not work?

**Comment by christopherthielen** [comment]
@timkindberg nice to see ya!  

I agree we should provide a shorthand for components in both angular 1.x and 2.x, although that still seems to be a moving target at this point.   

@eddiemonge I don't know all the details, but if you look at the tutorials around ngNewRouter, there seem to be a few ways to define a component in 1.x and 2.x and they don't all seem to involve directives.  I'd say this should be an "open issue" and thanks Tim for bringing it up

**Comment by reppners** [comment]
With the introduction of (ng-forward)[https://github.com/ngUpgraders/ng-forward] I want to bring this issue back.

I started a corresponding issue https://github.com/ngUpgraders/ng-forward/issues/42 so we can start to discuss what can be done to make this happen.

**Comment by nateabele** [comment]
Yeah, sounds good. I've seen one or two `@State` implementations in different A1/ES6 projects. I skimmed the discussion in the other issue. Let me know what you guys need from us.

**Comment by peterjhart** [comment]
The Angular Core team introduced the `component` method in AngularJS 1.5.0.

@timkindberg's original post now makes even more sense.

**Comment by christopherthielen** [comment]
its definitely on my radar for 1.0+

**Comment by christopherthielen** [comment]
This landed a while ago, so closing
