### ISSUE TITLE
[Bug] get a blank page if a state without param.

### ISSUE THREAD

**Issue by PaoJiao** [angular-ui/ui-router#1992]
404 page:

```
$urlRouterProvider.otherwise("/not-found");
```

defined State:

```
$stateProvider.state("test", {
            "url": "/test/{page:[0-9]+}",
            "template": "<div>oh, test.</div>"
}).state("notFound", {
            "url": "/not-found",
            "template": "<div>oh, file not found.</div>"
});
```

now i'll got a blank window without any error in console if access http:localhost/index.html#/test/
as i don't want to use a default param, a 404 page should be shown in this situation.
i think it is a bug. or how to fix it... 
any ideas? plz help...

**Comment by JobaDiniz** [comment]
This is somewhat similar to what I'm experiencing in https://github.com/angular-ui/ui-router/issues/1988. I'm validating a parameter, and when this parameter is invalid, I get a blank page, however I should get a 404 page.

**Comment by imbubble** [comment]
after debugged, find this in the source.
https://github.com/angular-ui/ui-router/blob/master/src/urlMatcherFactory.js#L898
```
config.value = ""; // for 0.2.x; in 0.3.0+ do not automatically default to ""
```

this gonna cause the
```
state.url.regexp.source
```
to be
```
/^\/test\/([0-9]+)?$/
```
in https://github.com/angular-ui/ui-router/blob/master/src/state.js#L195

but it should be
```
/^\/test\/([0-9]+)$/
```

after changed to
```
config.value=undefined; // for 0.2.x; in 0.3.0+ do not automatically default to ""
```
it could get the right regexp. but not sure if has any side-effect?
plz reply, thanks.

**Comment by imbubble** [comment]
@JobaDiniz hi, u may check my last comment. it could be helpful. :smile:

**Comment by eddiemonge** [comment]
Have you tried making that change and running the test suite? If they all still pass, why not submit it as a pull request?

**Comment by imbubble** [comment]
@eddiemonge ive made the change and ran the test suite. all passed...
here is the git diff:
```
diff --git a/src/urlMatcherFactory.js b/src/urlMatcherFactory.js
index bf116f0..ed50760 100644
--- a/src/urlMatcherFactory.js
+++ b/src/urlMatcherFactory.js
@@ -897,6 +897,8 @@ function $UrlMatcherFactory() {
     if (type.name === "string" && !arrayMode && location === "path" && config.value === undefined)
       config.value = ""; // for 0.2.x; in 0.3.0+ do not automatically default to ""
     var isOptional = config.value !== undefined;
+    if(isObject(config.value) && config.value.optional===false)
+      isOptional = false;
     var squash = getSquashPolicy(config, isOptional);
     var replace = getReplace(config, arrayMode, isOptional, squash);
```

and an 'optional' should be added to params as below:
```
        $urlRouterProvider.otherwise("/not-found");
        $stateProvider.state("test", {
            url: "/test/{page:[0-9]+}",
            params: {
                page: {
                    optional: false
                }
            },
            "template": "<div>oh, test.</div>"
        }).state("notFound", {
            url: "/not-found",
            "template": "<div>oh, file not found.</div>"
        });
```

 plz help to push cauz i cant do that. many thanks.

**Comment by eddiemonge** [comment]
@christopherthielen what do you think about this change?

**Comment by christopherthielen** [comment]
After 0.2.x, all params without default values are considered required params.  I don't think I want to add another param config `optional` to work around this temporary backwards compat issue, primarily because `optional` would be ambiguous with the default value config `value` which is what currently specifies optional/non-optional.  

Instead, I think I'd test if "value" is *explicitly* set to `undefined` in the param declaration.  To do that, we should test if the value is `undefined` and the config object has a key of 'value'.  Conversely, the default value is set to empty string only if the type is 'string', the location is 'path', and the default value was not specified using `value: ` in the config block.

```
  this.Param = function Param(id, type, rawConfig, location) { // <-- change var name
    var self = this;
    config = unwrapShorthand(rawConfig); // <-- Used here
    type = getType(config, type, location);
    var arrayMode = getArrayMode();
    type = arrayMode ? type.$asArray(arrayMode, location === "search") : type;
    if (type.name === "string" && !arrayMode && location === "path" && config.value === undefined && !rawConfig.hasOwnProperty("value")) // <-- Check if the raw config specified "value: undefined"
      config.value = ""; // for 0.2.x; in 0.3.0+ do not automatically default to ""
```

That will allow end users to make a param `foo` required in 0.2.x by specifying:
```
params: {
  foo: { value: undefined }
} 
```

-------

Another approach for users wanting string params to be non-optional in 0.2.x is to define a custom string param type.   Something like this:
```
var stringType = $urlMatcherFactoryProvider.type("string"); // fetch existing string type
$urlMatcherFactoryProvider.type("str", stringType); // fetch existing string type

$stateProvider.state({
  name: 'foo',
  url: '/foo/{requiredParam:str}'
});
```

**Comment by imbubble** [comment]
okay, plz do it. 😀

**Comment by calnikita** [comment]
I'm getting hit by this issue as well. My regex is being evaluated as optional and therefore matching the state below rather than using my fallback url that I specified with "otherwise".
Is there a work around?

$urlRouterProvider.otherwise("/login");
.state("teamRoot", {
                    url: "^/{teamHandle:[0-9a-zA-Z_-]{4,40}}",
                    parent: sa.states.home.root,                    
                    views: {
                        "mainContent@": {
                            templateUrl: "teamTemplate",
                            controller: "TeamController"
                        }
                    }
}

**Comment by graingert** [comment]
@christopherthielen now that we're on 0.4.x shouldn't this default param overriding be gone now?

**Comment by graingert** [comment]
I fixed it with:



```js
class RequiredParam {
  get value() {
    return undefined;
  }

  set value(_) {
    // does nothing
  }
}

        $urlRouterProvider.otherwise("/not-found");
        $stateProvider.state("test", {
            url: "/test/{page:[0-9]+}",
            params: {
                page: new RequiredParam(),
            },
            "template": "<div>oh, test.</div>"
        }).state("notFound", {
            url: "/not-found",
            "template": "<div>oh, file not found.</div>"
        });
```
