### ISSUE TITLE
Prevent going to state using a promise that fetch remote data

### ISSUE THREAD

**Issue by JobaDiniz** [angular-ui/ui-router#1993]
There is always a need to prevent users going to some state depending on some logic. I've seen a lot of questions about this. Most answers tell to use *data* object when configuring the *state* and listen to *$stateChangeStart* event.

But how about when this logic depends on fetching data from remote server?
```
$scope.$on('$stateChangeStart', onStateChangeStart);

function onStateChangeStart(event, toState) {
  user.fetchLatest().then(function(current){
    if(!current.billing)
      event.preventDefault();
  });
}
```

If `user.fetchLatest()` takes too long, `event.preventDefault()` will not work.
:question:  With the current version of ui-router, how can I accomplish such scenario :question:

Wouldn't be better to support these scenarios when configuring the *state*?
Something like:
```
$stateProvider.state('myState', {
  url: '/myState',
  prevent: {
    goTo: 'anotherState',
    deny: preventUsersThatDontHaveBilling
  }
});

//injectable dependencies
function preventUsersThatDontHaveBilling($q, user){
  var deferred = $q.defer();

  user.fetchLatest().then(function(current){
    if(!current.billing)
      deferred.reject();
    else
      deferred.resolve();
  });

  return deferred.promise;
}
```
If *deny* promise is rejected, *state* configured in *goTo* would be activated instead of *myState*.

**Comment by eddiemonge** [comment]
You should probably do that fetch in your run block or do you really want it to run everytime they change the page. Also, changing the state shouldn't matter if your API blocks the user from accessing data if they need to be billed or something.
