### ISSUE TITLE
The resolve is not blocked

### ISSUE THREAD

**Issue by mfdev1** [angular-ui/ui-router#1995]
Hi, guys.

The state "first" and the state "first.second" has a view, the view of the state "first" has a "Display Second View" button to perform "ui-sref = '. second'".
In addition, the resolve of the state "second" has time consuming processes.

My Problem
"Display Second View" button while pressing continuously, does not display the view of the state "second". the resolve seems to have been executed many times.
Code, please refer to the following URL.
http://plnkr.co/edit/TO9RWXWPfu2IeXgh2lxZ?p=preview

 I think the resolve is not blocked. Is there a better way to block the resolve?

**Comment by eddiemonge** [comment]
Why do you want to?

**Comment by christopherthielen** [comment]
transition to 'second' doesn't happen until after its resolves have been resolved.  clicking the button while the first transition is in progress (waiting for resolve) supersedes the original transition with a new one.  

if you want to stop the user from superseding the current transition, traditionally, the UI is blocked with a spinner or some such.

**Comment by eddiemonge** [comment]
@mfdev1 Is that answer acceptable?

**Comment by mfdev1** [comment]
Thank you for your quick response and advice.
But we would like to keep our program simple.We would like to block resolve by only using ui-rooter.
Do you have any idea? If you have,please let us know.

**Comment by eddiemonge** [comment]
Add a listener to the stateChangeStart event that prevents it from being successful until the resolve has completed. You can ask on stackoverflow for specific details on how to accomplish that.

As this isn't a bug but an application-level requirement, I am going to close this.
