### ISSUE TITLE
Feature Request: conditional ui-views based on url parameters

### ISSUE THREAD

**Issue by jimmypoms** [angular-ui/ui-router#2001]
As of now it is not posible in a useful way to define ui-views inside ng-repeat. Imagine a list view where the list items expand to a detail view. In this case it would be nice to have conditional ui-views something like this:

```javascript
<div ng-repeat="item in list">
    <div ui-view="detail" condition="{slug:item.id}"></div>
</div>
```

**Comment by eddiemonge** [comment]
Child states would accomplish this

**Comment by jimmypoms** [comment]
True, but wouldn't you agree that this is way more comfortable then (possibly dynamically) defining all the child states needed in a list view of 2000 items with server side pagination? Especially considering the very low amount of additional code needed to accomplish this feature :)

**Comment by eddiemonge** [comment]
No. I feel like you are trying to accomplish something with ui-router that is better suited to something else, like a directive or a child state. If only one of those views is going to be active at a time then it seems like a child state is exactly what you want.

**Comment by christopherthielen** [comment]
Agree with Eddie. Ui router can only activate one state at a time and that active state can have one set of parameter values. 

However, once something like sticky states are used, then I can see how it would be useful. I've gotten this request a few times in ui router extras to allow something like MDI in a tabbed interface. Probably out of scope for ui router extras to hack in and definitely out of scope for stock ui router for now.

**Comment by jimmypoms** [comment]
For anyone stumbling upon this issue:
We ended up using a single ui-view with ng-if as a condition inside the repeat and defining the additional ui-views in an abstract state. In our case it worked quite well with the sticky states.

Thanks guys for the quick responses :)
