### ISSUE TITLE
How to make segment of index.html as template

### ISSUE THREAD

**Issue by kiransmk** [angular-ui/ui-router#2004]
Hi I am trying to create a form wizard with different views. I have different segments of form in a html file returned from the server with PHP which I want them to be display as different views on the front end. Very similar to http://plnkr.co/edit/M03tYgtfqNH09U4x5pHC?p=preview
How can I make a segment of form like template: '#segment' as a template instead of templateUrl: 'template.html'

**Comment by christopherthielen** [comment]
http://bit.ly/UIR-SOF
