### ISSUE TITLE
Nested ui-sref-active with Unrelated Links

### ISSUE THREAD

**Issue by devonzara** [angular-ui/ui-router#2006]
I often come across times where I'll need to build out a menu with links that may not share a parent state, in such cases - `ui-sref-active` doesn't work. There should be alternative means for detecting nested active links.

I've created a plunker to demonstrate this along with a few other issues. I'd appreciate it if someone could suggest an alternative means for handling active links.

<kbd>[View Plunker](http://plnkr.co/edit/iTLD10HR6IIfLMNLpfCW)</kbd>

**Comment by ProLoser** [comment]
Write your own version of ui-sref-active or just use `ng-class` and write your own checker function. You can then define in it what the conditions to be true or false are.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
