### ISSUE TITLE
How can I set an offset when clicking an anchor?

### ISSUE THREAD

**Issue by kikar** [angular-ui/ui-router#2007]
I have a page with a fixed navbar, and when I click an anchor with the new UI Router feature, the content goes underneath the navbar.
Is there a way to set an offset, like in [Angular $anchorScroll.yOffset](https://docs.angularjs.org/api/ng/service/$anchorScroll) ?

**Comment by eddiemonge** [comment]
You can use `$uiViewScrollProvider.useAnchorScroll()` to directly call AnchorScroll
