### ISSUE TITLE
Resolve var of child not being called in 0.2.15, it does in 0.2.14

### ISSUE THREAD

**Issue by deeweey** [angular-ui/ui-router#2008]
See http://jsbin.com/wocudotoqu/1/edit?html,js,console. In 0.2.14 it returns I am state:sub, in 0.2.15 I am state:master.

Not sure what the expected behaviour is but just to let you know that the behaviour changed in the latest release. It was a breaking change for our app.

**Comment by christopherthielen** [comment]
Dewey,

I think this is indeed a bug (although I'm unsure what would have caused this change).  However, if you move your resolve to the state instead of the view, the proper resolve is injected in 0.2.15.

```
      .state('main.sub', {
        url: '/sub',
        resolve: {
              myVar: function() {
                return 'I am state:sub';
              }
            },        
        views: {
          'content@': {
            controller: 'SubCtrl'        
          }
        }
```

**Comment by chris1705** [comment]
Can you check if my pull request (#1991) fix this? I had the same issue.

**Comment by rdpacheco** [comment]
Any progress on this?

**Comment by christopherthielen** [comment]
Move your resolves from the views to the state.  I don't think we ever explicitly supported resolves on a view, did we @nateabele?  I don't believe 1.0 implements resolves on a view.

**Comment by nateabele** [comment]
A long, long time ago we did. It inadvertently got dropped in a point release, but no one seemed to notice. I think hardly anyone ever used it.

**Comment by towu** [comment]
I used it, just because it made sense to resolve data "to" the view where it is needed and keep it away from views that need other data ...
