### ISSUE TITLE
Dynamic add route from controller

### ISSUE THREAD

**Issue by tushariscoolster** [angular-ui/ui-router#2009]
I should be able to dynamically add route from controller:
```
angular.forEach($state.get(), function (config) { 
  config.templateUrl="view1"
}});
```

**Comment by eddiemonge** [comment]
Why? What would be the point of it?

**Comment by ProLoser** [comment]
Closing this as poor design. You can dynamically add routes, just shouldn't be from a controller.

**Comment by tushariscoolster** [comment]
@ProLoser  I want to inject dynamic resolve to route
