### ISSUE TITLE
uiSref passes the state parameter of object type weirdly

### ISSUE THREAD

**Issue by theGivingTree** [angular-ui/ui-router#2010]
ui-sref seems to pass an `Object` parameter by 'deep-copying', not 'shallow-copying'

http://plnkr.co/edit/sPrZnx?p=info
Check this plunker out.

When transitioned by `uiSref`, the parameter belongs to `$stateParams` doesn't match the object it originates from(in the `$rootScope`)

Fortunately, `$state.go` works perfecly. It didn't raise an assertion failure.

https://github.com/angular-ui/ui-router/blob/master/src/stateDirectives.js#L126 seems related to this issue.

**Comment by eddiemonge** [comment]
Isn't a deep copy better?

**Comment by eddiemonge** [comment]
It works fine if you compare the objects using angular.equals: http://plnkr.co/edit/VqYSt6VKqcA1hCDqIvK1?p=preview

**Comment by theGivingTree** [comment]
In my project, shallow copy was what I needed because the object is mutated by underlying service.
deep copy won't reflect the object's final state, but previous state, which the service didn't touch.

But I think(or believe) deep copy should be the behavior done by the developer, not the library
Even if the library has the ability to deep-copy, the one who decides whether to deep-copy or not should be the developer. (like using `angular.copy` or `Scope.watch(..., ..., true)

If that is true ui-router's way, I'll admit it. I already have the proper work around. (a little, little bit worse)

Thanks for your answer.

**Comment by theGivingTree** [comment]
@eddiemonge 
By the way, why `$state.go` is 'shallow-copying'?
This is somewhat confusing
