### ISSUE TITLE
angular version 1.3.x doesn't seem to work with angular-ui-router 0.2.15  

### ISSUE THREAD

**Issue by praveen912** [angular-ui/ui-router#2011]
Here is the Plunker for the working version which uses angular 1.2.X 

http://plnkr.co/edit/nmTggEdWIcMW5bMRKiok?p=preview 

When I use the angular version 1.3.x .. It does not seem to work. I am using angular material so it would be nice to have angular-ui-router to work with angular version 1.3.x..

**Comment by eddiemonge** [comment]
What doesn't seem to work on it? This seems to work the same: http://plnkr.co/edit/AGifZPTGHEOc13rEGVGz?p=preview

**Comment by praveen912** [comment]
Sorry for being incomplete. 
When clicked on the right tab I don't see any changes to the view when you update it to the 1.3.x version.
But in the version 1.2.x you can see the changes when you click on the right tab.
In the left tab it says "Left Tab, index.viewA".
on the right tab it says "Right Tab, viewA". 

This update does not happen with version 1.3.x.

**Comment by eddiemonge** [comment]
There is something else wrong in your code. I'd suggest start with this and work up to find out what it is because ui-router itself is not the problem (at least in this simplified example).

1.2.9: http://plnkr.co/edit/ogcmy3Fo9A2JBbfMFRsc?p=preview
1.3.15: http://plnkr.co/edit/vX7g4oqk9LI3WAUmCNm6?p=preview

**Comment by praveen912** [comment]
Thank you for your time... 
I will look into it and will get back to you.

**Comment by eddiemonge** [comment]
I am going to close this and if you can pinpoint ui-router as the problem, let me know and I'll re-open this.
