### ISSUE TITLE
factory.all returns contacts before $http returns resp.data

### ISSUE THREAD

**Issue by Simpler1** [angular-ui/ui-router#2013]
There is a race condition where factory.all returns contacts before $http returns resp.data to set contacts.

This is in reference to:
ui-router/sample/app/contacts/contacts-service.js

**Comment by eddiemonge** [comment]
factory.all returns a promise, not actual contacts. Does that answer your question?

**Comment by Simpler1** [comment]
Hmm...  I'll need to read up on promises, but in my .run method for my ng-app, the first thing it does is execute factory.all to populate my contacts and the $http request hasn't completed.  How do I know when contacts has been been populated from the $http request?

**Comment by Simpler1** [comment]
Never mind.  After reading up on promises, I replaced:

    $rootScope.contacts = factory.all();

with

    factory.all().then(function(data) {
      $rootScope.contacts = data.data;
    });

and now it seems to be working correctly.

Thanks for the help.
