### ISSUE TITLE
Urls without a prefix of "/" fail quietly - could we make them fail noisily?

### ISSUE THREAD

**Issue by johnnyreilly** [angular-ui/ui-router#2014]
Hi,

I got burned yesterday when, purely because of a typo, I specified a URL for my state that **didn't** begin with a "/".  Whilst it seemed to work sometimes (my ui-sref's could navigate me to them) I learned that they were not "happy" urls.  

If I entered the URLs directly in a browser the state would not be navigated to - a redirection to the `otherwisePath` would take place instead.  The same behaviour would be experienced if you did a browser refresh (F5).

This is a [plunk which demonstrates the problem](http://plnkr.co/edit/ZB1n7w).  To create this I just forked the quick start plunk and changed this:

``` js
        .state('route2', {
            url: "/route2",
            templateUrl: "route2.html"
        })
```

to this:

``` js
        .state('route2', {
            url: "route2", // See here!
            templateUrl: "route2.html"
        })
```

Interestingly the problem seems even more severe in Plunker-land whereby you cannot even navigate to the state using `ui-sref`.  I'm not sure quite why.

However, it's clear that URLs that do not start with "/" are a bad, bad thing which will kick sand in your face and make you cry.  With the present implementation you won't even know why.  I didn't notice anything in the docs that stated that "/" was a necessary prefix although it clearly appears to be.

Would it be possible to raise an error when a user attempts to register a state with a URL that is not "/" prefix-ed?  I think this will probably save time and reduce confusion for users of the UI Router.

I'm not sure if this sort of change would be considered to be a "breaking change" or not (my feeling is perhaps not, given that people using routes without "/" prefixes won't be in a happy place).  But if it is perhaps this error could behind a feature flag (long the lines of Angular's [strict-di](https://docs.angularjs.org/api/ng/directive/ngApp#!)).

**Comment by eddiemonge** [comment]
Its not really an error you can catch. Without the slash means something different than with the slash.

**Comment by johnnyreilly** [comment]
So it sounds like there's a number of valid style URLs but unless I'm misunderstanding you, starting with an alpha character is always invalid. Is there any reason we shouldn't raise an error if an alpha-starting URL is specified? Catching the error is not really the intent - I just want to get UI Router to provide useful feedback to people using it so they don't make the mistake I made (and may make again).

**Comment by eddiemonge** [comment]
Starting with an alphanumeric is valid as well: http://plnkr.co/edit/ptwKGzs9w8gbBf7tJKc5?p=preview

I am inclined to close this as its not a bug. The url matcher matches what you put into it. It kind of sounds like you want a 404 catcher, which you could probably find tutorials on or a stackoverflow answer for. Would that work for you?

**Comment by johnnyreilly** [comment]
Hi @eddiemonge,

Just checked the plunk - I think you may misunderstand the issue I'm experiencing.  It's not the state names beginning with a "/" that I mean - it's the URLs.  Looking at your plunk all the URLs all seem to begin with a "/" whilst the state names start alphanumerically:

```
$stateProvider
    .state('home', {
      url: "/", // Starts with a "/"
      template: "<p>home</p>"
    })
    .state('left', {
      url: "/left", // Starts with a "/"
      template: "<p>left</p>"
    })
    .state('right', {
      url: "/right/", // Starts with a "/"
      template: "<div><p>right</p><div ui-view></div></div>"
    })
    .state('right.child', {
      url: "me", // Starts with a "/" inherited from parent
      template: "<p>Right Child</p>"
    });
```

If you look at my [plunk](http://plnkr.co/edit/ZB1n7w) you can see the problem in action.  

Do let me know if I'm missing something.

**Comment by eddiemonge** [comment]
It might be hard to do that since it'd have to check all parent and other factors.
