### ISSUE TITLE
Is there a way to create a state with an url which match the url only if no other state matches it?

### ISSUE THREAD

**Issue by ycmjason** [angular-ui/ui-router#2015]
Basically I want to make sure my state is declared after all the other states are declared. I want to do this because the "profile" state in my router would have url '/:username' while I might have other states with url '/abc', '/bcd'. I want to make sure they won't have conflicts by first checking the 'abc' and 'bcd' states before matching with :username. Is this possible?

**Comment by eddiemonge** [comment]
Why not have your "profile" state have a url of `/profile` ? Then you can still have 404 pages.

If you still really want to do this: http://plnkr.co/edit/09M523TtkmDByADv7Mf2?p=preview

**Comment by ycmjason** [comment]
well, i still need to check for user existence and return 404 pages even I have url /profile.

My app is vertically moduled. So each module will have its own state config. The modules are embedded in the html in alphabetical order. So unless I create a module called zzzzzzz and put the "profile" state inside that, I couldn't find another way to make sure the profile state is declared lastly. Well, this doesn't sound like a nice approach as this creates excess module which I don't actually need it. This is why I was wondering if there will be any methods that I could use to solve this.

**Comment by eddiemonge** [comment]
I showed one in the plnkr. You can change the profile url to be something thats actually valid like `/profile` and the code should still work

**Comment by ycmjason** [comment]
I see! How did that work? I changed the code a bit to this
```
    .state('home', {
      url: "/",
      template: "<p>home</p>"
    })
    .state('profile', {
      url: "/*",
      template: "<p>Profile</p>"
    })
    .state('left', {
      url: "/left",
      template: "<p>left</p>"
    })
    .state('right', {
      url: "/right",
      template: "<p>right</p>"
    });
```
and left and right are still working!
but if I have /:username, left and right will not work.

Can you explain a bit more please? How am I suppose to get the stateParams in my controller? 
Or is there any article for me to read on?

**Comment by eddiemonge** [comment]
You could use $location.

Would users really type `www.domain.com/myname` to edit their profile? I still think you should have an actual `/profile` url thats easier to remember and implement in your code

**Comment by ycmjason** [comment]
Hmm that route really is just for viewing. It looks really nice if I can have www.domain.com/username.
This is much better then www.domain.com/profile/username.

Well, github wouldn't have github.com/user/angular-ui right? instead github.com/angular-ui makes people easier to remember your url.

**Comment by jgentes** [comment]
I agree, I'm trying to do the same thing. $location.path('path', false) causes a reload of the controller.

Also we lose the ability to have child states automatically inherit the path of parents.

I'm still looking for a solution, will come back when I find one.
