### ISSUE TITLE
ui-router and jquery-mobile 

### ISSUE THREAD

**Issue by mlabarre** [angular-ui/ui-router#2017]
Hello
I use angualar with ui-router on some web and it works very fine.
New I develop a mobile application and I have a problem with ui-router usage.
I have the following apps.js (part):

```
        $stateProvider
            .state('main', {
                url: '/',
                views: {
                    "" : {
                        templateUrl: "views/main.html"
                    },
                    "header@main" : {
                        templateUrl: "components/header.html"
                    },
                     "body@main" : {
                        templateUrl: "components/body.html"
                    }
                }
            })
            .state('main.menu', {
                url: '/menu',
                views: {
                    "body@main" : {
                        templateUrl : "components/menu.html"
                    }
                }
            })
```

Access to the site is http://monsite.com and the main.html is displayed with no problem (header and body are displayed).
My header page is very simple:
&lt;div ng-app="myapp" class="menu" ng-controller="headerController"&gt;
    &lt;a ui-sref="main.menu"&gt;&lt;span class="glyphicons glyphicons-show-lines selector"&gt;&lt;/span&gt;&lt;/a&gt;
&lt;/div&gt;

The problem is when I click the selector icon above, I have the message 
Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'http://menu/' cannot be created in a document with origin 'http://monsite.com'.

I use jquery 2.14, jquery-mobile 1.4.1, angular-js 1.3.15 and angular-ui-router v0.2.13-dev-2015-04-23 (in this declaration order)
Is there something wrong ? ui-router has really no problems with my others sites (but without jquery-mobile...).
Many thanks

**Comment by mlabarre** [comment]
Sorry the error was I have not coded 
$locationProvider.html5Mode(true);

**Comment by eddiemonge** [comment]
This can be closed then right? If not let me know.
