### ISSUE TITLE
Default state param value from async

### ISSUE THREAD

**Issue by pavel-blagodov** [angular-ui/ui-router#2018]
Hi there!

I'm wondering, is there any way to do something like this?
```javascript
.state('state', {
      url: '/url?someParam',
      params: {
        someParam: {
          value: function (someService) {
            return someService.getValueFromPromise();
          }
        }
      }
    })
```
this document also contains something similar https://docs.google.com/document/d/1bQ4bDq7-2Uvj7QhKOxFm-L3R8Qe_BtWo0sZaOsqTtu8)

At this time I'm using following workaround
```javascript
.state('state', {
      url: '/url?someParam',
      resolve: {
        views: function (someService, $stateParams) {
          return someService.getValueFromPromise().then(function (object) {
            $stateParams.someParam = object.value;
          });
        }
      }
    })
```

**Comment by christopherthielen** [comment]
the way you're doing it the way I would do it.  There is no mechanism for async default params

**Comment by pavel-blagodov** [comment]
Do you have plan to add mechanism for async default params in future?

**Comment by christopherthielen** [comment]
No plans.  The params themselves currently must be synchronous, because they are used in synchronous tree calculations before the transition is started.  The resolves are obviously async, once the transition has begun.  If we did add something like this, it would likely be syntactic sugar that links params with resolves.

**Comment by pavel-blagodov** [comment]
Thanks for explaining. I guess issue could be closed.
