### ISSUE TITLE
How to set an arbitrary list of parameters

### ISSUE THREAD

**Issue by Claud** [angular-ui/ui-router#2019]
```
.state('ap.index', {
   url: '/index',
   controller: ImagesCtrl,
   controllerAs: 'PageCtrl',
...
$state.go('ap.index', {id: 111, test: 222, ........});
```
It is return url without query string.

**Comment by eddiemonge** [comment]
Like that. In your controller, use `$stateParams` to retrieve them. If you need additional help with that, try asking on stackoverflow. (https://github.com/angular-ui/ui-router/blob/master/CONTRIBUTING.md#report-an-issue)
