### ISSUE TITLE
Nested states with only params in url

### ISSUE THREAD

**Issue by pavel-blagodov** [angular-ui/ui-router#2020]
I have following configuration http://plnkr.co/edit/V1o5QhJinFbdg7iwO50k?p=preview. By opening console you will see that all controllers were initialized but templates weren't fully compiled. However this plunker works as expected http://plnkr.co/edit/D0IUAc8HU2nRyLffT0YS?p=preview. The only difference is in url of last state.

In short, the issue with following configuration
```javascript
.state('app', {
      url: '/page?firstParam' ...
.state('app.list', {
      url: '?secondParam' ...
.state('app.list.details', {
      url: '?thirdParam' ...
```

Is this a bug?

**Comment by eddiemonge** [comment]
You need to append the param like this I think http://plnkr.co/edit/8ShiZEEPEznOst9vusvh?p=preview
