### ISSUE TITLE
why do `$state.go` shallow-copy, while `uiSref` deep-copy

### ISSUE THREAD

**Issue by theGivingTree** [angular-ui/ui-router#2021]
issue #2010 tells that deep copy of `uiSref` is implemented on purpose. (and b5f7b59 also does)
This leaves me this further thought

I regard `ui-sref="..."` as `ng-click=$state.go(...)` (This is my premise)
If deep copy is intended for `uiSref`, why not for `$state.go` ?

Also I cannot get the point of that deep copy is better than shallow copy for `uiSref`.
(If preventing object mutation is the goal, why not leave it to us to deep copy explicitly?)
I have already read b5f7b59's message, but I couldn't understand.

plus, suggest reading my second-to-last comment at #2010

(I'm sorry if this issue is complete repetition of issue #2010. But I want to make sure)

**Comment by Elijen** [comment]
+1 I think the behaviour should be consistent. I created a small Plunker demonstrating the difference: http://plnkr.co/edit/YsEPOtDX2j2zOzJydP2N

**Comment by Elijen** [comment]
I also noticed that it also depends on from where you access the `$stateParams` object. For example if you access it from a `$modal`'s controller it always contains deep copies even if the state was reached using `$state.go`.

**Comment by eddiemonge** [comment]
https://gist.github.com/christopherthielen/b3fc0304b737a4bf8ec9

**Comment by Elijen** [comment]
@eddiemonge Can you please explain why is there the inconsistency? I don't think this is something that can/should be answered on StackOverflow.

**Comment by nateabele** [comment]
> If deep copy is intended for `uiSref`, why not for `$state.go`?

Is there some specific problem this is causing you?
