### ISSUE TITLE
Dynamic parameters

### ISSUE THREAD

**Issue by arcanis** [angular-ui/ui-router#2023]
Hi,

I've seen that the issues about dynamic parameters have been closed, stating that the problem was mostly solved thanks to `{ dynamic : true }`. However, it seems the branch has been sleeping since then. Is there any chance to see it merged in a close future? Is there more work required? Can we help?

**Comment by christopherthielen** [comment]
Dynamic params won't exist until the 1.0 preview, which we're actively working on.  I'll be making a 1.0 branch soon and merging in our commits.

**Comment by christopherthielen** [comment]
UI-Router 1.0 preview is available: https://github.com/angular-ui/ui-router/tree/feature-1.0

**Comment by shprink** [comment]
+1 for dynamic params!

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
