### ISSUE TITLE
Support animation of elements between pages' via ng-animate-ref

### ISSUE THREAD

**Issue by episodeyang** [angular-ui/ui-router#2024]
The new ngAnimate has the following directive that is quite nice:

https://docs.angularjs.org/api/ngAnimate#animation-anchoring-via-ng-animate-ref-

what does it take to support this?

**Comment by eddiemonge** [comment]
Have you tried following the directions on that page?

**Comment by windguimo** [comment]
@eddiemonge i've, indeed, followed the directions on the Angular doc and its not working.

Does anyone know if it will be supported by ui-router? Or maybe, is there a trick to make it work?

**Comment by FlawaCLV** [comment]
@eddiemonge i've, indeed, followed the directions on the Angular doc and its not working.

Does anyone know if it will be supported by ui-router? Or maybe, is there a trick to make it work?

**Comment by GabiGrin** [comment]
I just tested their animation anchoring example and migrated it to ui-router and it looks like it works well, see here - http://plnkr.co/edit/9Kqz5QD8lxeRexdlbHvo?p=preview

**Comment by dmackerman** [comment]
Thanks @GabiGrin. I've tried doing something similar in my app - albeit a real application is much more complex than you example and it just doesn't work. :frowning:

**Comment by nimaen** [comment]
A little precision.
Seems like it's only working with views at the same level.
But it is the logical behaviour while looking at the documentation.
If you try to match two elements while one belongs to a nested view, it won't work since the first element need to belong to a view that is being removed.

**Comment by Sithdown** [comment]
How could this be used with multiple views, were states are always nested?

Example:

```
        $stateProvider
        .state('app', {
          abstract: true,
          views: {
            '': {
                templateUrl: 'components/contentView.html',
                controller: 'ContentController',
                controllerAs: 'content'
            },
            header: {
                templateUrl: 'components/header/headerView.html',
                controller: 'HeaderController',
                controllerAs: 'header'
            },
            footer: {
                templateUrl: 'components/footer/footerView.html',
                controller: 'FooterController',
                controllerAs: 'footer'
            }
          }
        })

        .state('app.frontpage', {
            url: '/',
            templateUrl: 'components/frontpage/frontpageView.html',
            controller: 'FrontpageController',
            controllerAs: 'frontpage'
        })

        .state('app.detail', {
            url: '/detail/:id',
            templateUrl: 'componentsdetail/detailView.html',
            controller: 'DetailController',
            controllerAs: 'detail'
        })
```

If I want an element to transition from frontpage to detail, should something be changed? I couldn't make it work.
