### ISSUE TITLE
state definition - non-url params require url to be defined

### ISSUE THREAD

**Issue by Flo-G** [angular-ui/ui-router#2025]
Hi,

I am using the state **params** property to define non-url params as such:

```javascript
$stateProvider
        .state('site', {
          abstract: true,
          // url: '', // try uncommenting this line ----------------------------
          template: '<ui-view/>',
          params: {
            siteParam: null,
          },
        })
        .state('site.home', {
          url: '/home',
          templateUrl: 'tpl.html'
        })
        .state('site.page', {
          url: "/page",
          templateUrl: 'tpl.html'
        });
```

The problem is that the **siteParam** will only be populated, if the **url** is defined.

I don't know if this is by design. I can't really tell from reading the [doc](http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$stateProvider).

I've done a plunkr to illustrate:
http://plnkr.co/edit/o9ZfAAvF1eQBIcVa7BNg

**If you uncomment line 14 in script.js, you'll see the siteParam is populated.**

This is actually not a big deal for me, since setting:
```javascript
{
  ...
  abstract: true,
  url: '',
  ...
}
```
works fine for my needs.

Thanks,

**Comment by christopherthielen** [comment]
verified, thanks for the report
