### ISSUE TITLE
Auto capture stateChangeError

### ISSUE THREAD

**Issue by dimrsilva** [angular-ui/ui-router#2027]
When a route is changed and there is an error on any resolve function, the only way to catch the error is watching for `$stateChangeError` event.

```
 $stateProvider.state('home', {
        url: 'home',
        templateUrl: 'templates/home.html',
        controller: 'HomeController as vm',
        resolve: {
            test: function() {
                return nonExistentFunction() || aTypoInAFunctionName();
            }
        }
    });
```

I got stuck on a simple error like that just because I was not listening to it. I don't want to add a listener just to get development stage errors...
What do you think?

**Comment by eddiemonge** [comment]
This is by design https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#issue-im-getting-a-blank-screen-and-there-are-no-errors
