### ISSUE TITLE
.is does not work with relative state name

### ISSUE THREAD

**Issue by Elijen** [angular-ui/ui-router#2028]
If you define a child state using the dot notation like this:

```
$stateProvider.state({ name: 'home', url: '/home', templateUrl: 'home.html'});
$stateProvider.state({ name: 'home.foo', url: '/foo', templateUrl: 'foo.html'});
```

And then call `$state.is('.foo')` when the current state is `home.foo`, `undefined` is returned. According to the documentation it should return `true` as the `foo` is child of `home`.

http://embed.plnkr.co/mMZH0AvE23iBd52GPzN8/preview

**Comment by nateabele** [comment]
Targeting `'.foo'` from `'home.foo'` means, you're asking for `'home.foo.foo'`. Changing it to `$state.is('^.foo')` makes it work.

**Comment by JasonCust** [comment]
@nateabele Your solution does work but it is contrary to the documentation which is either incorrect or if it is correct then this was a bug.

See https://github.com/angular-ui/ui-router/blob/1e46c8d/src/state.js#L1227 and also for `$state.includes` https://github.com/angular-ui/ui-router/blob/1e46c8d/src/state.js#L1273

**Comment by nateabele** [comment]
The template example doesn't suggest that it's in the same context as the examples above it, but I can see how you could make that inference.

**Comment by JasonCust** [comment]
@nateabele Since we agree the documentation can create confusion should it be a bit more explicit or at least reference the relevant documentation that would clear it up?

**Comment by nateabele** [comment]
Sure. PRs welcome. 😄
