### ISSUE TITLE
CSS load after JS in Controller

### ISSUE THREAD

**Issue by jonatasfreitasv** [angular-ui/ui-router#2029]
Hello ,

have the following problem , I am using ui- router- style to load a css per route , for example:

```
$stateProvider
.state ( 'login' , {
url: ' / login '
templateUrl ' components / login / form.html '
date : { css : ' components / login / style.css '} ,
controller: ' LoginCtrl '
} ) ;
```

What is happening is that the CSS is loaded after the js within the controller runs , causing problems .

How can I fix this?

**Comment by eddiemonge** [comment]
You should ask this at ui-router-styles or stackoverflow.
