### ISSUE TITLE
inconsistent behaviour of ui-sref vs $state.href

### ISSUE THREAD

**Issue by fvelosa** [angular-ui/ui-router#2031]
The links generated with ui-sref work fine while the links generated with $state.href are causing the complete reload of the app with a page refresh.

I have a directive that generates the link using $state.href

    scope.href_total = $state.href('root.workspace.dam.list')

And then I compare the result generating the same link with ui-ref and they precisely the same:

    <a ng-href="/dam/object_types/pt_dam/list/companies?view=cards" href="/dam/object_types/pt_dam/list/companies?view=cards">

    <a ui-sref="root.workspace.dam.list" href="/dam/object_types/pt_dam/list/companies?view=cards">

The first reloads the app while the second works fine. I am doing something wrong or is this a bug?

**Comment by nateabele** [comment]
With `uiSref`, the `href` attribute is generated for consistency with browser behavior, but in normal operation isn't used. It applies a click handler that calls `$state.go()` and suppresses the default behavior.
