### ISSUE TITLE
$locationProvider.html5Mode(true) broken

### ISSUE THREAD

**Issue by kikar** [angular-ui/ui-router#2032]
I used Express with no parameters to generate a quick server that will serve these 2 files:

```javascript
angular.module('myApp', ['ui.router'])
.config(['$locationProvider', function($locationProvider) {

    $stateProvider
    .state('home', {
        url: '/',
        template: '<h1>Home</h1>'
    });

    $locationProvider.html5Mode(true);
}]);
```
```html
<!DOCTYPE html>
<html ng-app="myApp" ng-strict-di>
<head>
    <title>Lunr Test</title>
    <base href="./">
</head>
<body>
    <nav>
        <ul>
            <li><a ui-sref="home">Home</a></li>
        </ul>
    </nav>

    <div ui-view></div>

    <script src="lib/angular.min.1.3.js"></script>
    <script src="lib/angular-ui-router.min.js"></script>

    <script src="app.js"></script>
</body>
</html>
```
Using UIRouter 0.2.14 and AngularJS 1.3.16 and I get this error twice in console:
```
TypeError: Cannot read property 'replace' of undefined
    at Gb (angular.min.1.3.js:94)
    at Re.$get (angular.min.1.3.js:100)
    at Object.e [as invoke] (angular.min.1.3.js:36)
    at angular.min.1.3.js:38
    at d (angular.min.1.3.js:36)
    at Object.e [as invoke] (angular.min.1.3.js:36)
    at angular.min.1.3.js:38
    at d (angular.min.1.3.js:36)
    at Object.e [as invoke] (angular.min.1.3.js:36)
    at angular.min.1.3.js:38
```
Works normally when setting html5Mode to false, or when I comment that line.

**Comment by nateabele** [comment]
Seems like it should work. Pretty surprising since it's such a commonly-used feature.

Can anybody else confirm this?

**Comment by eddiemonge** [comment]
I can confirm this exists.

**Comment by sdarby2000** [comment]
I'm using angular 1.4 and was using v0.2.11 with the same issue. Updated to v0.2.15 and still having the same issue.

**Comment by jazzblue** [comment]
It is not only ui-router issue, I get it just by doing $locationProvider.html5Mode(true) without any ui-router.

**Comment by eddiemonge** [comment]
So if you take out all traces of ui-router its still happening?

**Comment by jazzblue** [comment]
Yes, I do not use ui-router at all.

**Comment by jazzblue** [comment]
I have just tried this workaround:
https://github.com/angular-ui/ui-router/issues/116
(ggoodman commented on May 6, 2013)

...and it seems to be working. Still checking...

**Comment by eddiemonge** [comment]
I am inclined to close this issue then. @kikar if you take out ui-router do you still have the bug?

**Comment by kikar** [comment]
Seems to be an Angular problem. Don't have bug anymore

**Comment by moander** [comment]
Still broken.

Quick fix:
```js
  app.run(function ($browser) {
    $browser.baseHref = function () { return "/" };
  });
```

**Comment by pavel06081991** [comment]
Yeah, still hava this problem

**Comment by cleechtech** [comment]
@moander's solution works but all you have to do is change `<base href="./">` to `<base href="/">`

More info on this SO post: http://stackoverflow.com/questions/17768814/ngroute-set-base-url-for-all-routes

**Comment by zhuhongyin** [comment]
thanks moander's solution ,fixed by
app.run(function ($browser) {
    $browser.baseHref = function () { return "/" };
  });

**Comment by brutalcrozt** [comment]
Thanks @cleechtech and @moander , you save my day. I prefer using this [solution](http://stackoverflow.com/questions/17768814/ngroute-set-base-url-for-all-routes) via template

**Comment by Parziphal** [comment]
@cleechtech is right. All you have to make sure is that the value for `href` in your `<base>` tag has a leading slash, or if it's root, it should be only a slash. Examples:

Wrong:
`<base href="foo/">`
`<base href="./foo/">`

Right:
`<base href="/foo/">`
`<base href="/">`

**Comment by aipirvu** [comment]
So I had this problem also. What I discovered was that I was using `<base href="/My.App.Web/">` and accessing it in the browser on `localhost/my.app.web/somepage/...` when the error occurs. Changing it to `<base href="/my.app.web/">` seems to do the trick but now I would get the error when requesting `localhost/My.App.Web/somepage/...`. So I asume something in the html5mode is checking case sesitive addresses.

**Comment by anil826** [comment]
Finally I got a way to to solve this issue by server side as it's more like an issue with AngularJs itself I am using 1.5 Angularjs and I got same issue on reload the page.
But after adding below code in my `server.js` file it is save my day ***but it's not a proper solution or not a good way .***

    app.use(function(req, res, next){
      var d = res.status(404);
         if(d){
         	res.sendfile('index.html');
         }
    });
