### ISSUE TITLE
Overriding default parameters

### ISSUE THREAD

**Issue by genu** [angular-ui/ui-router#2034]
When defining default parameters like so, shouldn't that `query` parameter override the defined parameter when passed in the url?

``` javascript
.state('app.issues.list', {
            url: '?query',
           ...
            params:{
                query: {
                    value: 'default value'
                }
            },
```

What is happening, if I go to `app/`, then the default parameter transoforms the url to `app/?query=default value`, however if I put in a parameter in the url like `app/?query=new parameter`, it gets reverted back to `app/?query=default parameter`

possible bug?

**Comment by christopherthielen** [comment]
Yes, possible bug.  Can you put this in a plunk for me?

**Comment by genu** [comment]
See: http://plnkr.co/edit/jHNx6haBY9vUFnnyY1ea?p=preview

I noticed that if I change:
```javascript
url: '?query'
````
to something like:
```javascript
url: '/search?query`
```
it will behave correctly. Is that supposed be by design?

-Eugen

**Comment by christopherthielen** [comment]
Interesting.  No, that is not by design.
