### ISSUE TITLE
$stateParams returns string value for params set

### ISSUE THREAD

**Issue by samvloeberghs** [angular-ui/ui-router#2036]
Hi,

Using the $stateParams I noticed that having a GET parameter set, for example:

http://example.com/state?a&b 

It returns true as a string value in the object:

```
  {
    a: "true",
    b: "true",
  }
```

$location.search() returns booleans by default:

```
  {
    a: true, 
    b: true    
  }
```

Shouldn't it be implemented like $location in the ngRoute module?
As I don't have the time at the moment to do a pull request I hope someone will pick this up :)

Grtz
Sam V.

**Comment by eddiemonge** [comment]
If the type isnt defined then its set to string. $location handles it differently
