### ISSUE TITLE
ui-sref should allow for empty value

### ISSUE THREAD

**Issue by jthibeaux** [angular-ui/ui-router#2037]
Currently a javascript error:
```
Error: Invalid state ref ''
```
Is fired whenever ui-sref=''

Angular does not make it easy to generate conditional attributes, so generating a list of items that contains both state and URL references becomes challenging, especially if you are trying to avoid generating the extra div/span blocks ng-if statements would require.  The workaround proposed in #371 does not address functionality provided by ui-sref-active, and that is pretty useful.

**Comment by eddiemonge** [comment]
Why should it allow for an empty value? Do you have a state with an empty name?

**Comment by jthibeaux** [comment]
Because i wanted to build a directive that generates a list of links. Some effecting state, some regular hrefs.  Not allowing an empty value to be passed in makes this harder. And there is no appreciable value in throwing an exception when an empty value should be clearly understood as a noop.

**Comment by eddiemonge** [comment]
But it shouldn't be understand as noop. It should be understand as transition to a state with a name of `''`.  

Are you saying you are building a directive that either has a ui-sref or an ng-href? If you, why not an ng-if that has either/or but not both

**Comment by jthibeaux** [comment]
It had not occurred to me that anyone would name a state '' and it would be valid.  Maybe that is the answer to why I will not get what I want.  There are workarounds, and I have since implemented one, just nothing as simple as if the empty string had been ignored.  What made it more complicated for my purpose the desire to avoid generating extra divs and avoiding bootstrap CSS breakage, so many conventional angular mechanisms that may pollute the DOM with extra divs were out.

**Comment by eddiemonge** [comment]
Can I close this then?

**Comment by jthibeaux** [comment]
It remains unfortunate that there is no way to make the attribute a noop as that requires additional complexity in the situation I just explained; however, my specific suggestion on how to resolve this may not be doable if '' is a valid state name.

**Comment by robertbaker** [comment]
@eddiemonge just allow this! Nobody is going to name a state ''.

It's not easy to have dynamic attributes either.

I propose allowing empty values in ui-sref, that do nothing and don't throw an error or warning.

In my case, I have a directive that uses ng-repeat and buttons. A button class that can either have a state or a onClick method. ng-click doesn't complain about null values!

This 'as intended by design' is a flaw in the design. Null values are OK in angular!

**Comment by mpetrovich** [comment]
+1 to allowing empty strings for `ui-sref`. Even just to be consistent with `ng-href`.

**Comment by nateabele** [comment]
This isn't an intended use case for `ui-sref`. See `ui-state`, which will be out in the next release.

**Comment by mpetrovich** [comment]
@nateabele I just saw `ui-state` in the upcoming release. Looks great, thanks!

**Comment by wap300** [comment]
Since the ```ui-state``` is still not in the latest release (when I'm writing this), just a reminder for anyone who is looking for a way around this, like me - remember you can use ng-attr in a following way (in Angular 1.3 and above):
```ng-attr-ui-sref="{{ state || undefined }}```

**Comment by kikocastro** [comment]
Not sure if this works for everyone, but it did the trick here:

`uisref="{{state || '.'}}"`

**Comment by nahueld** [comment]
that worked for me champ

**Comment by allnash** [comment]
I get cannot transition to abstract state '.' . Uh do I need to add a new state?
