### ISSUE TITLE
ngAnimate and ui-view as element

### ISSUE THREAD

**Issue by Ledragon** [angular-ui/ui-router#2038]
Hi. First of all, thanks for the amazing job, I totally love ui-router. Second, sorry if this is a duplicate issue.
While trying to animate transitions between states, I realized that using ui-view as element does not get animated via ng-animate, while it is working with ui-view as element. I set a plnkr demonstrating the problem: http://plnkr.co/edit/RH63TXBWt3O1LPsPvbde

**Comment by willhartman** [comment]
The problem is that your CSS is using the [ui-view] selector.  That is an attribute selector, which is why it only works when you use the ui-view attribute.

When you change to use ui-view as an element, you will need to use an element selector in your CSS.

    [ui-view].ng-enter, [ui-view].ng-leave {
      -webkit-transition:all .5s ease-in-out;
    	-moz-transition:all .5s ease-in-out;
    	-o-transition:all .5s ease-in-out;
    	transition:all .5s ease-in-out;
    }
    
    [ui-view].ng-enter {
      opacity: 0;
    }

    [ui-view].ng-enter-active {
      opacity: 1;
    }

    [ui-view].ng-leave {
      opacity: 1;
    }

    [ui-view].ng-leave-active {
      opacity: 0;
    }

**Comment by Ledragon** [comment]
Well... #shame #lameatcss
Sorry for wasting your time (／。＼)
