### ISSUE TITLE
Can't Open in new tab (Right click) on ui-sref

### ISSUE THREAD

**Issue by michnath** [angular-ui/ui-router#2039]
Hi All, 

I use ui-sref on my project and it works well when I click the element (<tr>).
But when I right-click on the rows, some options (Open link in new tab, Open link in new window, etc) didn't show up.

I use angular v1.3.0-rc.2 and I have upgraded angular-ui-router to the newest version.

Here is the code snippet:
```
<tr class="message-item" ng-repeat="message in messages track by message.id" ui-sref="message-detail({id: message.id})">
```

Any help would be much appeciated. Thank you

**Comment by willhartman** [comment]
ui-sref adds an href tag to an a element, and then the browser adds the extra options based on that href tag.

It won't work on a tr tag.  You should add an a tag inside the tr.

    <tr class="message-item" ng-repeat="message in messages track by message.id">
      <a ui-sref="message-detail({id: message.id})">
        Other markup in the tr goes here.
      </a>
    </tr>

**Comment by michnath** [comment]
Ah. It works. Thank you for your reply :)

**Comment by harryjoy** [comment]
@willhartman In my case I have sub states/routes and `ui-sref` points to sub routs so the href become `'//my-route'` which results in wrong url in new tab.

For example:

    <a ui-sref="base.user.route">My Route</a>

when rendered on browser it comes:

    <a ui-sref="base.user.route" href="//my-route">My Route</a>

State definition in code:

    $stateProvider.state('base', {
         url: '/:t',
         templateUrl: 'app/base/base.html',
         abstract: true
    }).state('base.user', {
         url: '',
         templateUrl: 'app/root/root.html',
         abstract: true
    }).state('base.user.route', {
         url: '/my-route',
         templateUrl: 'app/my-route.html'
    });

do you have any thought on this?

**Comment by willhartman** [comment]
The URL is constructed based on your route.  They are inherited from each other.

So -

    base: '/:uid'
    base.user: ''
    base.user.route: '/my-route'

Becomes -

    '/:uid/my-route'

But you haven't specified what ':uid' parameter is, so the URL becomes -

    '//my-route'

You need to specify what the :uid parameter is -

    <a ui-sref="base.user.route({uid: '123456'})">

And then the URL will be generated correctly -

    '/123456/my-route'

**Comment by harryjoy** [comment]
Ohh.. I see, so I need to pass uid for the routes.
Thanks for the help buddy.

**Comment by Thuzar-TS** [comment]
Hi,
I also use ui-sref and it works well when I click the link.
But when I right-click on the link and choose open in new tab, it tells object not found and it goes directly to localhost and not to my root project folder.
`<a ui-sref-active="active" ui-sref="dash.dashpage">Right Click</a>`

state in code

            `.state('dash', {
                url: '/dash',
                templateUrl : "dashboard.php",
                controller: 'dashController'
            }).state('dash.dashpage', {
                url: '/dashpage',
                templateUrl : "dashpage.php",
                controller: 'dashController'
            })`

Any help, please?
