### ISSUE TITLE
String typing does not work

### ISSUE THREAD

**Issue by RavenX447l** [angular-ui/ui-router#2040]
String typing on query parameters does not work. bool and int do. If you have an integer with leading zeros, you would need to strigify it to prevent the leading zeros from being removed. this does not happen.

**Comment by christopherthielen** [comment]
Can you put this in a plunk?  Thanks!

**Comment by ProLoser** [comment]
@christopherthielen this project has 400 issues open. I would just start closing issues (with labels if necessary) and reopen, let them reopen, or let them file new ones.
