### ISSUE TITLE
redirectTo state?

### ISSUE THREAD

**Issue by tlrobinson** [angular-ui/ui-router#2041]
It would be nice ui-router supported something like `redirectTo`, e.x. http://stackoverflow.com/a/30219547/113

```
.state('home', {
    url: '',
    redirectTo: 'home.list'
});
```

**Comment by inca** [comment]
This feature request has been around for quite a while, see #24 #1235 etc.

**Comment by christopherthielen** [comment]
Agreed. Let's pick one of the many redirectTo tickets and schedule it for a release in 0.2.16 and 1.0
