### ISSUE TITLE
Named ui-view directive does not hide when view is not defined

### ISSUE THREAD

**Issue by ulfryk** [angular-ui/ui-router#2042]
First: Great Work and thank you for that ;)

Consider such HTML:

```html
<body>
    <nav ui-view="navbar"></nav>
    <main ui-view="main"></main>
    <footer app-footer></footer>
</body>
```

and state config:

```javascript
$stateProvider

.state('home', {
    url: '/',
    views: {
        main: { … },
        navbar: { … }
    }
})

.state('login', {
    url: '/login',
    views: {
        main: { … }
    }
});
```

It was obvious to me that on `#/login` element `<nav ui-view="navbar"></nav>` would not enter DOM. I looked into source and found out, that it seems not a mistake. uiView always leaves old and enters new clone (if locals changed). 

Do you consider changing it to be more predictable ?

**Comment by eddiemonge** [comment]
`navbar` should be an empty container in the `login` state. Is that not what you are seeing?

**Comment by ulfryk** [comment]
@eddiemonge - that's exactly what I see. 

What I expected is hiding it from DOM.

**Comment by eddiemonge** [comment]
Why not add the style the content inside the navbar instead of the navbar itself?

**Comment by ulfryk** [comment]
In several (more complicated than pasted example) situations (also with z-index complications) it would be much easier if empty view was not there (like in ng-if or ng-include). This element is already transcluded so change does not seem to be huge.

**Comment by christopherthielen** [comment]
The clone element is for animating ui-view with ngAnimate when a ui view is being exited.

**Comment by shekspir55** [comment]
@ulfryk I don't know if this report is outdated or not but I found the solution.
I know this might be not perfect solution but this is at least something (hope this will help someone else).
    <nav ui-view="navbar" ng-if="$state.current.views.hasOwnProperty('navbar')"></nav>

**Comment by ulfryk** [comment]
Thanks @shekspir55 ;)

I actually made another `ui-view` directive that transcludes self out when no proper view available. But that's not perfect also.

@christopherthielen 
> The clone element is for animating ui-view with ngAnimate when a ui view is being exited.

I agree. Thats good. So why not animate it out when there is no corresponding view ?

**Comment by eddiemonge** [comment]
Because it has to be there to animate things back in when they are added.
