### ISSUE TITLE
$state.includes relative option does not work as expected

### ISSUE THREAD

**Issue by mwd410** [angular-ui/ui-router#2043]
Maybe I'm a bit confused by the API, but it doesn't seem like `$state.includes` properly obeys the relative option:

```
$state.$current.name
> dashboard
$state.includes('login', null, { relative : 'login' });
> false
```

I would expect the `$state.includes` call to return true -- am I missing something, or is this a bug?

**Comment by ProLoser** [comment]
Would have to see what your state tree looks like.
