### ISSUE TITLE
Reduce boilerplate for nested states which have a single view

### ISSUE THREAD

**Issue by tlrobinson** [angular-ui/ui-router#2044]
It can be very verbose to have to use the multiple views syntax when a child state only needs to fill in a single view somewhere up the view hierarchy, e.x.

```
.state('app', {
  url: '/',
  views: {
    'nav' : {
      templateUrl: 'navbar.html'
    },
    'content': {
       templateUrl: 'home.html'
    }
  }
})
.state('app.foo', {
  views: {
    'content@': {
      template: 'foo.html',
      controller: 'FooController'
    }
  }
})
```

I'm aware that states can simply have a template consisting of just `<ui-view/>`, however I don't like that this introduces useless DOM elements.

It would be nice if child states would just fill the first unnamed ui-view in their ancestor states. Then the app.foo state above would simply be:

```
.state('app.foo', {
  template: 'foo.html',
  controller: 'FooController'
})
```

Alternatively if we could specify a "view" property in a state rather than a whole "views":

```
.state('app.foo', {
  view: 'content@',
  template: 'foo.html',
  controller: 'FooController'
})
```

**Comment by eddiemonge** [comment]
The second proposal seems better than the first because the first is too ambiguous. What if people want to fill the last instead?

**Comment by DarkCow** [comment]
I would prefer the second proposal instead... In my application, all views use the top level unnamed ui-view (under app route). Currently my code looks like:

    state('app.displays.create', {
        url: '/create',
        views: { 
            '@app': {
                templateUrl: 'modules/displays/views/create-display.client.view.html',
                controller: 'DisplaysController'
            }
        },
    }).

would change to 

    state('app.displays.create', {
        url: '/create',
        view: '@app',
        templateUrl: 'modules/displays/views/create-display.client.view.html',
        controller: 'DisplaysController'
    }).
