### ISSUE TITLE
State transition occurring before resolving dependency

### ISSUE THREAD

**Issue by LeonanCarvalho** [angular-ui/ui-router#2048]
I think i'm getting a related issue than #2047, but the scenarios is different and I'm using a 3th-party plugin to resolve my dependencies.

The problem is the state transition is occurring before resolve dependencies. For this reason the controller isn't loaded on mudule.

```javascript
.state('app.config.params', {
                    url: '/params',
                    data: {
                        modulo: '00.000.00',
                        title: 'Params Config',
                        access: access.user
                    },
                    views: {
                        "content@app": {
                            templateUrl: 'app/modules/_admin/config/views/params/index.html',
                            controller: 'paramsController',
                            resolve: {
//At version 0.2.14 its works fine, in 0.2.15 does not.
                                deps: $couchPotatoProvider.resolveDependencies([
                                    'modules/_admin/config/controllers/paramsController'
                                ])
                            }
                        }
                    }
                })
```

$couchPotato is a component that  Lazy-Load and Register Components in AngularJS Applications

I'm using angular 1.4.1

**Comment by eddiemonge** [comment]
This could potentially be a bug but I'm not sure if it should be solved here or at $couchPotato. It would seem here since it works in one version and not the next.

**Comment by LeonanCarvalho** [comment]
$couchPotato returns a function, The goal should resolve this function, isn't it?

**Comment by cah-ricksuggs** [comment]
I've encountered a similar issue after upgrading to version `0.2.15`

When initially transitioning to a route, the dependencies are resolved and controller is executed. However when revisiting the same route after navigating away, the controller is executed, then dependencies are resolved, and the state transition finally occurs.

It appears to be a regression because after downgrading to version `0.2.14` the issue no longer occurs.

**Comment by christopherthielen** [comment]
Move the resolve out of the view, and into the state definition

**Comment by christopherthielen** [comment]
I believe the original reported issue is "not a bug" since `resolve: {}` is not supported on views; it is only supported on states definitions.

Please open a new issue if there is something else going on here, as @cah-ricksuggs  suggests.
