### ISSUE TITLE
URL Matcher treats trailing slash as distinct url

### ISSUE THREAD

**Issue by thegreenpizza** [angular-ui/ui-router#205]
I realize, based on the comments in urlMatcherFactory.js, that a URL with a trailing slash is purposely treated like a distinct url. This functionality differs from Angular's built-in functionality, where a trailing slash causes a redirect to the URL without the slash.

I am opening this issue to ask: is treating the slash as a distinct part of the URL a good idea? It definitely causes problems for users who are used to being able to enter it either way. Does it solve enough problems or add enough to the feature set to warrant performing the strange way it does?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
