### ISSUE TITLE
Lazyload template and controller with one request

### ISSUE THREAD

**Issue by RonB** [angular-ui/ui-router#2052]
I'm trying to load a template which has a script tag embedded containg the controller. I have created a plunker to demonstrate how I need to use it but it is a very uggly and anti-pattern solution. 

[Plunker](http://plnkr.co/edit/m3jbX4KVzDM8Osv7MJUB)

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
