### ISSUE TITLE
Pass data between multiple pages on the same level?

### ISSUE THREAD

**Issue by j4ques** [angular-ui/ui-router#2053]
Hi,

is it possible to enter a string value on one page using controller a, and passing this value to another page that uses controller b? I'm not talking about a nested views scenario.
Basically the workflow would look like this:
1) Enter value in page 1
2) Press link for page 2 (on page 1)
3) Read entered value on page 2

I'm struggling with getting this scenario work with ui.router's stateprovider. 
Is this even possible?

Thanks a lot

**Comment by ProLoser** [comment]
Use resolves on a state that's higher than both. If you do not have a state higher than both, create one for just such a purpose. Example: https://github.com/ProLoser/AngularJS-ORM/blob/c887e4f8ce4249b769fc3fb46f9ea620ffd7d826/modules/User/User.js#L28-L34
