### ISSUE TITLE
[feat] Provide API to access $state.$current.locals.globals and make that update the injection into a controller

### ISSUE THREAD

**Issue by lookfirst** [angular-ui/ui-router#2054]
Let's say I'm using `resolve` for a route. In my controller, I have a method for updating the database for the resolved value. In my single page app, if I click a link and move away from the view and then click back to the view, I see my controller executed again, but the resolved value isn't updated.

In order to get ui-router to re-resolve the value of the resolve after updating it, I use `$scope.reload()`, but this seems kind of heavy handed if there is multiple resolves and I only want to update one of them. Ideally, I'd just have a way to simply tell ui-router what the new object is that it should inject into my controller.

I tried doing something like this: `$state.$current.locals.globals.campaign = campaign` (where campaign is the updated object), but that didn't seem to have any effect. Maybe the API could be something like:

`$state.reload('foo.bar', {resolve: { campaign: newCampaign } });`

Apologies if this has been brought up already, I did search the existing issues and the interwebs.

**Comment by ProLoser** [comment]
We've been discussing (and I think this feature is now in the core) having the ability to specify how deeply to reload. This also works if you do `reload: true`. This way you can reload PART of the tree without reloading the ENTIRE tree. Although it's not quite as granular as picking exactly which resolves to rebuild, perhaps this solution will be a suitable compromise? Re-open this issue if it's not.

**Comment by lookfirst** [comment]
@ProLoser `reload:true` is part of navigation. What I'm talking about is just being able to tell ui-router to reload the resolves outside of the navigation scope. 

My use case is simple. I have a SPA that is mostly a crud app. The user can modify an entity that is returned from a resolve. I need to be able to tell ui-router that when the user navigates away from the page and back again (using any number of various links on the page), to give me the new object instead of the old object.

I don't really see how this use case is solved efficiently without a more granular ability to manage the resolve cache.

Please re-open.

**Comment by ProLoser** [comment]
Why aren't you just modifying the reference or storing it in a cache in a factory? 

Also, if you navigate away and come back out will re-fire your callback so you should have the ability to fire whatever cache recovery you want. 

What you are describing sounds like a path down bad design because you need to take into consideration the life cycle of all the states. 

I'm not sure I follow why you are having trouble accomplishing what you want, it sounds like things are being over complicated. Can you explain further
