### ISSUE TITLE
Dynamic templateUrl returned from $q promise results in empty view

### ISSUE THREAD

**Issue by iantanwx** [angular-ui/ui-router#2055]
Hello,

I'd first like to say thanks for all the great work - ui-router is a great module.

I recently ran into an issue where I tried to dynamically generate a templateUrl by querying an API with a $resource object, like so:

        .state('core.page.child', {
          url: '/:child',
          views: {
            'page_content@core': {
              templateUrl: function($stateParams) {
                var url;

                PageProvider
                  .$get() // $get() returns Page service
                  .findOne($stateParams.child)
                  .$promise
                  .then(function(data){
                    console.log(data.template.url);
                    return url = data.template.url;
                  });
              }
            }
          }
        });
      });

In developer tools, I was getting undefined as the return value of the function. Digging into the source, particularly ui.router.util.$templateFactory#fromUrl, it would appear that fromUrl does accept a promise being returned from the templateUrl function.

Please correct me if I'm wrong about this, or if there's a workaround that doesn't involve hacking ui-router core.

Thanks!

**Comment by iantanwx** [comment]
Chris very helpfully informed me that templateProvider now receives resolves. I am therefore closing this issue. For anyone else who may be wondering, just place any promisified values in the resolve block; they are immediately injected into templateProvider as an argument.

**Comment by dalelotts** [comment]
Do you mean the templateProvider now receives resolves from a Parent state?  

I don't see the resolves from the current state being available in templateProvider.

**Comment by christopherthielen** [comment]
Hey dale! Yes template provider should receive resolves, including those from a parent state
