### ISSUE TITLE
Full page URL not getting displayed in Windows 10 Edge browser

### ISSUE THREAD

**Issue by sreejithatlas** [angular-ui/ui-router#2056]
Hello,

Whenever I navigate to the pages in the application the view state url is not getting updated accordingly. This is happening when I use the Windows10 Edge browser and it is working fine in other browsers. I tried accessing the ui-router demo url as well and this is also having the same issue.

![test](https://cloud.githubusercontent.com/assets/12995062/8276231/56c30114-18d1-11e5-8f76-4716b19704c6.jpg)

The same page url should be coming as http://angular-ui.github.io/ui-router/sample/#/contacts/1 which is coming correctly in Chrome/FF/IE browsers.

Is it some compatibility problem in the ui-router library with the Edge browser?

Thanks in Advance!

**Comment by flybumtoo** [comment]
We have the same issue in the latest version of IE11 on Win8. We started noticing it a few days ago. The version is 11.0.9600.17842 pushed out by MS in the last week or so. The back button seems to go back from the displayed URL (which is wrong) and not from the page you were on.

**Comment by webmatrixxxl** [comment]
I tested IE on Windows 10 build 1024 and it is working.
<img width="1023" alt="screen shot 2015-07-21 at 13 16 03" src="https://cloud.githubusercontent.com/assets/3726238/8798414/bfd1185e-2faa-11e5-8a46-6315300b9741.png">

**Comment by eddiemonge** [comment]
https://gist.github.com/christopherthielen/b3fc0304b737a4bf8ec9
