### ISSUE TITLE
RFC: $state.go('^') should go to the next - non abstract - Parent-State

### ISSUE THREAD

**Issue by jannickfahlbusch** [angular-ui/ui-router#2057]
$state.go('^') should not go to the parent Element, without checking, if this state is an abstract state (Currently, it tries to transition to the state and throws an error, when the target state is abstract).

go() should check, if the parent state is abstract. When it is, it should go to the parent of the parent and check, if this state is abstract. 
This should be done until the first non-abstract state is found.

Here is some Code, to show what i mean:
```javascript
function goToNonAbstractParentState() {
	var states = $state.current.name.split('.');
	for (var i = states.length - 1; i > 0; i--) {
		var stateName = '';
		for (var j = 0; j < i; j++) {
			stateName += states[j] + (((j + 1) < i) ? '.' : '');
		}
		if (!$state.get(stateName).abstract) {
			$state.go(stateName);
			break;
		}
	}
}
```

**Comment by ProLoser** [comment]
We've been discussing having default children (or what-have-you) for abstract states. Potentially one solution would be that you could pass a callback function which would be executed when you land on an abstract state to decide where to bounce you to. This seems like it would be covered by such a feature, and the behavior you described I don't think is ubiquitous enough to make the standard behavior.

**Comment by styxiak** [comment]
What reason is for going to abstract state if this  throw error? I think like @jannickfahlbusch it should go to first non abstract parent in tree.

**Comment by eddiemonge** [comment]
https://gist.github.com/christopherthielen/b3fc0304b737a4bf8ec9

**Comment by DumboJet** [comment]
So, any hopes of us seeing these default states of abstract parent states in the near future?

Also, I am really disappointed that you do not allow us to retrieve information about that registered states.
E.g., I want a generic piece of code to know if a state is abstract or not without me repeating that information somewhere. But I cannot even retrieve a list of the available states out of the router, let alone check their type and other properties...

Anyways...

**Comment by christopherthielen** [comment]
[redirectTo](https://ui-router.github.io/ng1/docs/latest/interfaces/ng1.ng1statedeclaration.html#redirectto)

[StateRegistry.get](https://ui-router.github.io/ng1/docs/latest/classes/state.stateregistry.html#get)

**Comment by DumboJet** [comment]
Oh...!
Thanks.
I didn't know about that!
I am using an older version than that, but maybe I can upgrade sometime. :)
