### ISSUE TITLE
There is no event to catch when the search query changes

### ISSUE THREAD

**Issue by denislins** [angular-ui/ui-router#2067]
There are a lot of use cases when `reloadOnSearch: false` is very useful, like in my case, as I want to update the chart, but I don't want to update the entire page.

But, as I understand, there is no way to catch when the query string changes, so, while I can update the search query, I cannot know when.

The `$stateChangeSuccess` doesn't work, because the reloadOnSearch option blocks it. I think that the simplest solution would be to include a `$searchQueryChanged` event, maybe event passing the `$stateParams` service as a param in the event callback.

What do you guys think? Is this feasible? Am I missing something?

PS: I tried searching the open issues, so I'm sorry if I missed one similar to this one.

**Comment by eddiemonge** [comment]
seems like it should be related to https://github.com/angular-ui/ui-router/issues/2049

**Comment by georeith** [comment]
Can't you listen to the `$locationChangeSuccess` event on `$scope`? Since 0.2.15 `reloadOnSearch: false` causes the Url to update.

**Comment by denislins** [comment]
I'm using the `$locationChangeSuccess`, and it's working just fine until now. I'll post an update here when I finish the feature.

**Comment by thiagofelix** [comment]
Problems with locationChangeSuccess I believe is that you can't use stateParams at this point because the state didn't update yet, the you will need to retrieve params via location service or something like that.

**Comment by denislins** [comment]
@thiagofelix You can, just not in the first time. I worked around this issue by manually triggering the listener in the first time, and it worked just fine.

I don't think we need another event, but I do think that this information should be clearer to everyone. I can create a PR to do it, I just need to know where is the best place to show this.

**Comment by christopherthielen** [comment]
In ui-router 1.0 you can hook into transitions, and check if the transition was cancelled because it was ignored.  It's in alpha currently, so the API is subject to change before being finalized.  However, you can do something like this:

```
app.run(function ($transitions, $rootScope) {

  $transitions.onStart({}, function ($transition$) {
    $transition$.promise.catch(function(error) {
      if (error.type === 3) // ignored
        $rootScope.$broadcast("$stateChangeIgnored", $transition$.to(), $transition$.params("to"));

...
```

**Comment by christopherthielen** [comment]
This is the onStart hook shown above:
http://angular-ui.github.io/ui-router/feature-1.0/interfaces/transition.ihookregistry.html#onstart
