### ISSUE TITLE
Url params escaping is performed twice

### ISSUE THREAD

**Issue by zgmnkv** [angular-ui/ui-router#2069]
Create a state with url parameter
```
            .state('test', {
                url: 'test?param',
                ...
            })
```
open url with this parameter equal slash: "http://localhost:port/test?param=/"
Url is being changed to "http://localhost:port/test?param=%252F"
Url parameter is being escaped twice in UrlMatcher.prototype.format

This also leads to events firing and controller execution twice.

**Comment by eddiemonge** [comment]
this is a duplicate. i know this is bad but im not sure which issue but a quick search should turn it up

**Comment by zgmnkv** [comment]
Sorry, but I can't find a duplicating issue. Could you please give a link to it?

**Comment by eddiemonge** [comment]
I can't either. where did it go?

**Comment by eddiemonge** [comment]
Oh. I used #1645 as the main. #1973 is a direct duplicate
