### ISSUE TITLE
Is there a way to hook the state.resolve method for all states?

### ISSUE THREAD

**Issue by oriweingart** [angular-ui/ui-router#2072]
Hi,

Is there a way to hook all the state.resolve method invocations and inject them common code, lets say:
logResolveState = function(state){
  console.log("Entering resolve method for:" state.name");
  console.log("Trying to resolve: "+state.resolve.toString());
}
 Every time resolved method is invoked to I want to run logResolveState without to add it to each state.resolve method.
I can't use stateChangeStart/stateChangeSuccess events as they are only being fired once for fiew nested states.

Thanks,
Ori W

**Comment by christopherthielen** [comment]
nope, there is no hook like that

**Comment by oriweingart** [comment]
k, thanks..

**Comment by oriweingart** [comment]
.config(
    [            '$stateProvider',
        function ($stateProvider,    {

            $stateProvider.myState = function(name, obj){
                if (!obj.resolve){
                    obj.resolve = {}
                }
                obj.resolve.log = [ function () {

                    return lz.load(pack[name]);
                }]
                return $stateProvider.state(name, obj);
            }

**Comment by eddiemonge** [comment]
that seems like it might be good for debugging but not for very wide use probably. nice to see you found a way to make it work though
