### ISSUE TITLE
Clear all old state?

### ISSUE THREAD

**Issue by LuanNg** [angular-ui/ui-router#2073]
in the case permissions user: when I log-in with a permission user and responding to $states, then I log-out and log-in with other permission user. so i need to remove all old state and will add other state again. it seems $state just set and get method, i can't remove a state on it.

do anyone for me a way to remove all old state?

**Comment by nateabele** [comment]
At present the state tree is fixed. We plan to address this at some point in the future. Follow along with #1095.
