### ISSUE TITLE
Angular WordPress HTML5 mode true but url looking very bad and not work properly.

### ISSUE THREAD

**Issue by SuryaTripathi** [angular-ui/ui-router#2074]
Hey there,

I am suffering with # in url. I used HTML5 mode true statement but whole site is not working properly. After removing that statement this site is running well.

By Using of HTML5 mode true statement, when i click on any menu the url is showing something like this.
http://orangemantra.co.in/dummy#%2Fportfolio

and showing an error in angularjs, that is:
"Error: $rootScope is not defined".

how we can overcome this issues.

**Comment by eddiemonge** [comment]
This is better asked on stackoverflow since it looks like an implementation bug and not a bug in ui-router itself.

you are also probably trying to use $rootScope somewhere and you didn't include it in the dependency list
