### ISSUE TITLE
Nested named views

### ISSUE THREAD

**Issue by georeith** [angular-ui/ui-router#2075]
Is it possible to target nested named views? There is nothing in the docs I can find around this.

Given the following route definition:
```js
.state('root', {
    views: {
        '': {
            templateUrl: 'root.html'
        }
    }
})
.state('root.item', {
    views: {
        'item@root': {
            templateUrl: 'item.html'
        }
    }
})
```
How would I target a view within the `item@root` template in a child state of `root.item`? This is an overly simplified example where I realise `item@root` could probably be refactored to be the unnamed view, but in my actual use cases this is often required for complex view structures.

**Comment by eddiemonge** [comment]
you should be able to do that pretty much like that

**Comment by georeith** [comment]
@eddiemonge What do you mean? I didn't show an example of accessing a nested view inside `item@root` this requires an unnamed view as far as I am aware to make it targetable.

**Comment by thebearingedge** [comment]
Is this what you want to do? If I understand you, this is how I accomplish that.

```javascript
.state('root.item.substate', {
  views: {
    'subview@root.item': {
      templateUrl: 'sub-item.html'
    }
  }
});

**Comment by georeith** [comment]
@thebearingedge Thanks, you're right. There was nothing in the documentation about targetting a named view in anything but unnamed views. But using your style and with this [example](https://jsbin.com/jimedufaye/edit?html,js,output) it appears it is completely possible.

It looks for named views specified in the view.

**Comment by thebearingedge** [comment]
:beers:
