### ISSUE TITLE
Cycle error if template file not exists

### ISSUE THREAD

**Issue by lfelisiak** [angular-ui/ui-router#2078]
Hi everyone, so listen guys i have he following problem, when i go to a url lets say /clientes/create if template does not exists shows the admin.blade.php (which is rendered by laravel) template twice (one inside another) and throwing the warning message **"WARNING: Tried to load angular more than once. "** but if the template exists it gets rendered without problem. If there is no template how can i do to show a 404 or blank?
 
Here is an image showing the error. 
![capture](https://cloud.githubusercontent.com/assets/5983749/8504652/8e458ab6-21ab-11e5-8761-ef53585c9859.JPG)
This is my code
```javascript
app.config(function($stateProvider, $urlRouterProvider,$locationProvider) {
    
    $urlRouterProvider.otherwise('/inventario');
    
    $stateProvider
		.state('clientes', {
            url: '/clientes',
            templateUrl: 'templates/partials/clientes.html',
			controller: 'ClientesCtrl'
        })
			.state('clientes.create', {
				url: '/clientes/create',
				templateUrl: 'templates/partials/clientes.create.html',
				controller: 'ClientesCtrl'
			});
			
		.state('ingresos', {
            url: '/ingresos',
            templateUrl: 'templates/partials/ingresos.html'
        });
       .state('inventario', {
            url: '/inventario',
            templateUrl: 'templates/partials/inventario.html',
            controller: 'InventarioCtrl'
        });
		..state('inventario.create', {
			url: '/inventario/create',
			templateUrl: 'templates/partials/inventario.create.html',
			controller: 'InventarioCtrl'
		});
		.state('inventario.edit', {
			url: '/inventario/edit',
			templateUrl: 'templates/partials/inventario.edit.html',
			controller: 'InventarioCtrl'
		})
});
```

Thanks in advance.

**Comment by eddiemonge** [comment]
Your server is loading the whole app again most likely since you probably have everything (including 404s) redirect to index.html. Fix the template paths and you should be good.
