### ISSUE TITLE
'/' get replaced with %252F in url while reloading $state in angular

### ISSUE THREAD

**Issue by Ajeetlakhani** [angular-ui/ui-router#2080]
I have url something like this

www.example.com/variable1/variable2

but when i apply

$state.reload(); or 
$state.go($state.current,{},reload:true);

The forward slash get replaced with %252 and url becomes

www.example.com/variable1%252Fvariable2

why it is happening and what can be the solution for this?

**Comment by eddiemonge** [comment]
duplicate of #1645 most likely

**Comment by vejen001** [comment]
@Ajeetlakhani I face the same issue, Were you able to figure out the fix for this? BTW which version of ui-router are you using?
