### ISSUE TITLE
How to enable Hash Bang

### ISSUE THREAD

**Issue by flosky** [angular-ui/ui-router#2083]
Hi guys,

I would like to make my app SEO friendly and apparently the Google Bot is looking for #! and not # in order to replace that with _escaped_fragment_. How can I setup ui router to use #! instead of #.

Thanks,
Flosky

**Comment by bioball** [comment]
Use the `$locationProvider`service.

```js
module.config(function($locationProvider){
  $locationProvider.hashPrefix('!');
});
```

https://docs.angularjs.org/guide/$location
