### ISSUE TITLE
Change state after invocable resolution but before view rendering

### ISSUE THREAD

**Issue by oslo10e** [angular-ui/ui-router#2084]
I have two states, A and B that match to same URL.
But I want to go to A or B according to asynchronous Server answer.

I have created a third state, C, A and B sibling.
But if I do a $state.go() in it's controller, the screen blink when changing view.
And if I do a $state.go() in it's onEnter method, the parent's state resolve is run twice, 
and it triggers a "Error: null is not an object (evaluating '$state.$current.locals[name]')" when changing state (see http://jsfiddle.net/opeaucelle/6gqygkt7)

How can I do ?

**Comment by eddiemonge** [comment]
Try asking this on stackoverflow as it doesn't seem to be a bug in ui-router but in implementation.

Also, if its the same url how are you supposed to differentiate which it should go to?

**Comment by oslo10e** [comment]
We differentiate the state which it should go to with an asynchronous Server call using URL parameters.

**Comment by oslo10e** [comment]
I have ask on stackoverflow :
http://stackoverflow.com/questions/31287395/angularjs-ui-router-ability-to-change-state-during-resolve
