### ISSUE TITLE
event.preventDefault() not waiting till promise is resolved

### ISSUE THREAD

**Issue by mukulgupta2507** [angular-ui/ui-router#2088]
Hi,

I'm using event.preventDefault() technique to conditionally redirect user to an appropriate state based on a flag value which I'm fetching from backend. Eveything seems to be working fine except that sometimes the actual page is rendered and then redirection happens and that too in very few cases. This render of actual page is also for a very short duration. Following is the code snippet which I'm using:

```
    $rootScope.$on('$stateChangeStart', function(event, toState, toParams, fromState, fromParams){
      
      if (fromState.name === '' && toState.name === ''myState"){
        
        Auth.isLoggedInAsync(function(loggedIn) {
          if (!loggedIn) {
            event.preventDefault();
            $state.go('state1');
          } else {
              event.preventDefault();
              Auth.getNextStateForUser()
              .then(function(data) {
                console.log(data.nextState);
                $state.go(data.nextState);
              })
              .catch(function(err){
                  console.log(err);
                  $state.go(toState.name);
              });
          }
        });
```

The logic which I'm following is, check if a user is logged in, then redirect to state1, else redirect to next appropriate state based on nextstateValue fetched from backend. If some error occurs, open the actual page without any redirection.

I hope I make my myself clear with what I'm doing. Just want to know if the issue which I'm facing is a genuine issue or there is something wrong which I'm doing from my side.

Thanks

**Comment by crtlib** [comment]
You have to do event.preventDefault() synchronously. Good place is right before Auth.isLoggedInAsync() call

**Comment by mukulgupta2507** [comment]
Hi,

I tried using that but it goes in infinite loop. Below is my updated code.

```
    $rootScope.$on('$stateChangeStart', function(event, toState, toParams, fromState, fromParams){

      if (fromState.name === '' && toState.name === ''myState"){
        event.preventDefault();
        Auth.isLoggedInAsync(function(loggedIn) {
          if (!loggedIn) {
            $state.go('state1');
          } else {
              Auth.getNextStateForUser()
              .then(function(data) {
                console.log(data.nextState);
                $state.go(data.nextState);
              })
              .catch(function(err){
                  console.log(err);
                  $state.go(toState.name);
              });
          }
        });
```

**Comment by mukulgupta2507** [comment]
Can anyone please help me with this. I'm really stuck at this.

Thanks

**Comment by crtlib** [comment]
do you use .otherwise()? if so, try to start directly with 'myState' and see what comes. Could you please post a snippet of your logs.

**Comment by mukulgupta2507** [comment]
Yes, I'm using .otherwise, following is the code snippet:

```
.config( function($urlRouterProvider) {
$urlRouterProvider.otherwise('/error'); 
});
```

I see following api calls infinitely:
```
GET /api/users/getNextStateForUser 304 4ms
GET /api/users/getNextStateForUser 304 5ms
GET /api/users/getNextStateForUser 304 5ms
GET /api/users/getNextStateForUser 304 3ms
GET /api/users/getNextStateForUser 304 3ms
GET /api/users/getNextStateForUser 304 3ms
GET /api/users/getNextStateForUser 304 3ms
GET /api/users/getNextStateForUser 304 7ms
GET /api/users/getNextStateForUser 304 3ms
```

In the font-end, I can see promise getting resolved repeatedly. I tried removing the .otherwise and then again trying but it's also not working.

Any idea why is it so?

**Comment by crtlib** [comment]
Let's move this to stackoverflow, because it doesn't seem like an issue of ui-router. Please, post here the link to SO with newly created question and close this issue afterwards. You could also create a plunker (http://plnkr.co/), so it's easier for others to help you on SO. Cheers

**Comment by mukulgupta2507** [comment]
Hi,

I have posted this question on SO: http://stackoverflow.com/questions/31368338/event-preventdefault-not-waiting-till-promise-is-resolved

If anyone can help me, please post answer over there.

**Comment by mukulgupta2507** [comment]
Hi,

I have updated my code on SO: http://stackoverflow.com/questions/31368338/event-preventdefault-not-waiting-till-promise-is-resolved 

Can anyone please take a look at it ? I just want to cross-verify it's right ?

**Comment by eddiemonge** [comment]
Closing since this was opened on SO and marked as answered
