### ISSUE TITLE
Pass state to req.session 

### ISSUE THREAD

**Issue by estvmachine** [angular-ui/ui-router#2089]
Hi, im trying to pass the $state to req.session, im trying to make an implementation that combine passport with ui-router. The access to the page its doing with ui-router, but when a user enter a page and this page need info that require login, then i obtain the url, but for a 'real redirect' after login i need only the state or the url in the controller.

Well only i need know how to obtain the state from inside a controller i suppose..

help please? xd

**Comment by estvmachine** [comment]
For do this, im using ngResource, so i do use $window and $state. I prefer $window for the moment, because i obtain the full url with parameters like: /example/1230. When i use the $state, i obtain the url with parameters but in this form  "/example/exampleId", so no obtain the $stateParams. Any improvment i can obtain?.

angular.module('RANDOM').factory('Advances', ['$http','$resource','$window', '$state',
	function($http, $resource, $window, $state) {
		return $resource('advances/:advanceId', {
			advanceId: '@_id'
		}, {
			get:{
				method:'GET',
				params:{
					window: $window.location,
                                        state : $state.current
				}
			},

**Comment by eddiemonge** [comment]
Try asking this on stackoverflow since this isn't a bug report or feature request. You should also include what you expect the request URL to look like
