### ISSUE TITLE
Get "TypeError: Cannot read property 'match' of undefined" when using ng-attr-ui-sref

### ISSUE THREAD

**Issue by sharpmachine** [angular-ui/ui-router#2090]
Hi there,

I only want to add the `ui-sref` attribute IF `{{item.state}}` is defined.  That's what `ng-attr` is for.  But when I use it on on `ui-sref`, like so `ng-attr-ui-sref={{item.state}}`, it works great in the DOM but in the console I get `TypeError: Cannot read property 'match' of undefined`.  It only throws this error when I use `ng-attr` on `ui-sref`.

``` html
<div class="list-group">
  <a 
        ng-attr-ui-sref="{{item.state}}" 
        ng-repeat="item in dynamicPopover.items" 
        ng-attr-ng-click="item.click($event, object.id)" 
        class="list-group-item">
    <i class="fa fa-{{item.icon}}"></i>
    {{item.title}}
    <paper-ripple fit></paper-ripple>
  </a>
</div>
```

Full Error

```
TypeError: Cannot read property 'match' of undefined
    at parseStateRef (http://localhost:9000/bower_components/angular-ui-router/release/angular-ui-router.js:4015:22)
    at link (http://localhost:9000/bower_components/angular-ui-router/release/angular-ui-router.js:4100:17)
    at invokeLinkFn (http://localhost:9000/bower_components/angular/angular.js:8258:9)
    at nodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7768:11)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7117:13)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7120:13)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7120:13)
    at nodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7763:24)
    at delayedNodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:8016:11)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7117:13) <a ng-attr-ui-sref="{{stateName}}" class="card-header">
```

Any ideas?

**Comment by eddiemonge** [comment]
What versions are you using because I don't see that when I try it.

**Comment by sharpmachine** [comment]
v0.2.14

**Comment by eddiemonge** [comment]
can you upgrade to 0.2.15? Also what version of Angular?

**Comment by sharpmachine** [comment]
Yes I'll upgrade.  My angular versions is v1.3.15

**Comment by sharpmachine** [comment]
I just upgraded to the latest version of UI-Router and am still getting the error.

**Comment by eddiemonge** [comment]
can you post a plnkr showing this please?

**Comment by sharpmachine** [comment]
Sure.  Here ya go: http://embed.plnkr.co/pi8WcloKeXUOnOWUK8Th/preview

So if you look at the directive there's I can either pass in a click function using `clickFn` or pass in a state using `stateName`.  I'd only use one, and which I use depends on the situation.  That's why I'm using `ng-attr`.

Thanks for your help @eddiemonge

**Comment by eddiemonge** [comment]
thats an odd interaction. I can see whats causing the error but not entirely sure why

**Comment by sharpmachine** [comment]
What is an odd interaction? The way I coded it? I'm still learning Angular so if there's a better way to do what I'm trying to do can you point me in the right direction?

Thanks again!

**Comment by eddiemonge** [comment]
Not the way you coded it but the way the pieces are interacting. I can add ng-attr-ui-sref in my app and it works fine. I'd have to dig into your example more to find out why it doesnt work. One thing is that you arent passing the stateName into the directive in the example.

**Comment by sharpmachine** [comment]
Yeah, I want stateName to be optional.  So I always going to pass either a state OR a function, but the directive needs to be flexible enough to accommodate both scenarios based on the context that the directive is used in.  Does that make sense?

**Comment by eddiemonge** [comment]
in the link you could check to see if its defined and if not set it to false or an empty string but that doesn't sound ideal

**Comment by sharpmachine** [comment]
Hi @eddiemonge.   I tried that but it doesn't work.  Any progress with crushing this bug?  Thanks!

**Comment by sharpmachine** [comment]
Hey @eddiemonge. Wanted to follow up on this.  Any progress or anything I can do?

**Comment by eddiemonge** [comment]
if you want to figure out why its not working and/or add a failing test that would be helpful

**Comment by sharpmachine** [comment]
I can give it a shot. I'm a UX designer that's trying really hard to fill a void as a front-end developer at the company I work. I have no clue on how to write a failing test, but I seems like the issue has to do with the `parseStateRef` function on line 4046. I'm wondering if that regex is trying to match any attribute that contains `ui-sref`, so `ng-attr-ui-sref` is being matched incorrectly.

**Comment by sharpmachine** [comment]
@eddiemonge Any thing new on this? Not trying to be a bother.

**Comment by Ascarbek** [comment]
+1
I'm having the same problem.
my situation:
I have ng-repeated buttons, some of them should change state and some of them not (e.g., show modal window). It depends on item.sref property.
So I use ng-attr-ui-sref - it does what I want but throws error in console...(

**Comment by xr0master** [comment]
+1
I simple not understand, why uiRouter check ng-attr-ui-self? If value is exist then ngAttr build ui-self otherwise not. Easy? But not, I get this error.
So instead of the easy solution I need use ngIf and 2 elements...

**Comment by RolandHeath** [comment]
+1
@eddiemonge I think you might have found a bug in ng-attr. 
I am also having this problem, but it looks like undefined only shows up in this specific case and not, if you have ui-sref without a value. 
It might be possible to use that as a workaround, maybe throwing a warning instead of an error.

Alternatively, if you're using the latest, ui-state might be a better option.
