### ISSUE TITLE
api without $state.$current and $state.url.format

### ISSUE THREAD

**Issue by hxlniada** [angular-ui/ui-router#2092]
I find some where using $state.$current.path and $state.url.format, but in api doc, I can't find them. Did i miss something?

**Comment by hxlniada** [comment]
anyone knows? oh please...

**Comment by eddiemonge** [comment]
You should be able to find what you need at http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$state

**Comment by hxlniada** [comment]
@eddiemonge sorry, I can't find them in api doc

**Comment by eddiemonge** [comment]
What is in that doc is what is available. If something else is telling you about some "feature" thats not documented, you probably shouldn't use it since its not supposed to be used.
