### ISSUE TITLE
How can I configure my go (golang) server to support angularjs html5mode?

### ISSUE THREAD

**Issue by alexanderbaran** [angular-ui/ui-router#2093]
I see that there are alot of suggestion for other servers here:

https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-your-server-to-work-with-html5mode

How can I achive this in go (golang) ?

**Comment by eddiemonge** [comment]
This should be asked on serverfault.com

Its a matter of redirecting all requests to your main file. http://golang.org/pkg/net/http/

**Comment by Zeakk** [comment]
@alexanderbaran Were you able to successfully setup your Golang server to support ui-router's html5mode?

**Comment by nateabele** [comment]
Guys, feel free to post the answer to this to the FAQ. Thanks.
