### ISSUE TITLE
How to set route filters on ui.router states?

### ISSUE THREAD

**Issue by aligajani** [angular-ui/ui-router#2094]
In Laravel, setting route filters is quite easy. We use a beforeFilter([]) and specify which functions in the controller should be accessible on authentication, and also have except in exceptional scenarios.

Now, I just started using Angular's ui.router and the concept of states is certainly the way forward, but I am asking a asking a noob question here. How do I set route filters on my states. I definitely don't want to do it on individual routes using resolve.

Here's some code. This is what I use for my profile route. I use resolve to make sure it is only accessible when authenticated. But the problem is, my login and signup routes are still accessible when I am logged in. They shouldn't be. It should just redirect to home.

Now I could add resolves to states I don't want accessible when I am logged in, but is that the right way? What if there are many. That would be repeating code. Is there a 'ui.router` way to do this?

```
.state('profile', {
                url: '/profile',
                templateUrl: 'js/app/partials/profile.html',
                controller: 'ProfileCtrl',
                resolve: {
                    authenticated: function($q, $location, $auth) {
                        var deferred = $q.defer();

                        if (!$auth.isAuthenticated()) {
                            $location.path('/login');
                        } else {
                            deferred.resolve();
                        }

                        return deferred.promise;
                    }
                }
            })
```

**Comment by eddiemonge** [comment]
This is a good question for stackoverflow. Here is a page that might help you though (from a quick google search) http://brewhouse.io/blog/2014/12/09/authentication-made-simple-in-single-page-angularjs-applications.html

**Comment by aligajani** [comment]
I did post it there, but the answer was too complicated and didn't make use
of resolve. I think someone with more experience using ui.router would
guide me well.

I am at the noob stage but I make sure I am on the right track :-)

On Mon, Jul 13, 2015 at 8:21 PM, Eddie Monge <notifications@github.com>
wrote:

> This is a good question for stackoverflow. Here is a page that might help
> you though (from a quick google search)
> http://brewhouse.io/blog/2014/12/09/authentication-made-simple-in-single-page-angularjs-applications.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-router/issues/2094#issuecomment-121028679>
> .
>



-- 


Ali Gajani
Founder at Mr. Geek
www.mrgeek.me
www.aligajani.com

**Comment by eddiemonge** [comment]
Resolve is not a good place to do what you are describing. Try following the tutorial in the link I posted. It should help

**Comment by aligajani** [comment]
Okay I think I know .. The person who helped me on SO pointed out the same.
Resolve does seem a good solution for what then ?

On Monday, July 13, 2015, Eddie Monge <notifications@github.com> wrote:

> Resolve is not a good place to do what you are describing. Try following
> the tutorial in the link I posted. It should help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-router/issues/2094#issuecomment-121038519>
> .
>


-- 


Ali Gajani
Founder at Mr. Geek
www.mrgeek.me
www.aligajani.com

**Comment by eddiemonge** [comment]
Resolve if for loading data that the view will need. It is fetched before the view renders so you can show the view when the data is ready

**Comment by aligajani** [comment]
In Satellizer's client example, the author uses Resolve to check if the
user is authenticated, using a promise, and then returns the profile page.

Why is this not useful in state filtering?

On Mon, Jul 13, 2015 at 11:25 PM, Eddie Monge <notifications@github.com>
wrote:

> Resolve if for loading data that the view will need. It is fetched before
> the view renders so you can show the view when the data is ready
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-router/issues/2094#issuecomment-121079470>
> .
>



-- 


Ali Gajani
Founder at Mr. Geek
www.mrgeek.me
www.aligajani.com
