### ISSUE TITLE
onload expression evaluated within child scope

### ISSUE THREAD

**Issue by ouchxp** [angular-ui/ui-router#2097]
When using ui-view's onload expression, I found that this expression is acturally evaluated within child scope. 
If I use controller as syntax, set controller as 'vm', register a function to the 'vm' and put this function as onload expression. AND, I set child view controller as 'vm' also. the child view 'vm' will shadow the parent view 'vm'. 

```
<div ui-view onload="vm.printInVm()"></div>
```

```
routerApp
  .controller('HomeCtrl', 
    function($scope) {
      var vm = this;
      vm.printInVm = function() {
        console.log('printInVm');
      }
    }
  )
  .controller('HomeListCtrl',
    function($scope) {
      $scope.dogs = ['Bernese', 'Husky', 'Goldendoodle'];

      /** child view's vm shadowed parent view */
      // this.printInVm = function() {
      //   console.log('shadowed printInVm');
      // }
    }
  );
```

```
    $stateProvider

        // HOME STATES AND NESTED VIEWS ========================================
        .state('home', {
            url: '/home',
            templateUrl: 'partial-home.html',
            controller: 'HomeCtrl',
            controllerAs: 'vm'
        })

        // nested list with custom controller
        .state('home.list', {
            url: '/list',
            templateUrl: 'partial-home-list.html',
            controller: 'HomeListCtrl',
            controllerAs:'vm'
        })
```

Which means, the function I registered in parent controller will not be called, and no error shown.

I created a plunker to show this problem.
http://plnkr.co/edit/QzEIfuDmX3OE9bKbI6bO?p=preview
In this plunker you can see, click List link will not print anything in console.
Only click Paragraph link will print in console. because Paragraph view is not using controller as syntax

Is it the ideal behavior to evaluate onload within child scope? If not, please fix it, because it's really painful when using controller as syntax.
If it is the expected behavior. please add clear indication in the document.

**Comment by christopherthielen** [comment]
I didn't even know there was an `onload`, but now knowing so, I think it makes most sense evaluating in the same scope as the ui-view's controller.

**Comment by eddiemonge** [comment]
Me neither. Does it do the same thing as onEnter?

**Comment by ouchxp** [comment]
According to the document here http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.directive:ui-view
*onload, Expression to evaluate whenever the view updates.*

In the code, it will be evaluated right after emit the `$viewContentLoaded` event.
```
          currentScope.$emit('$viewContentLoaded');
          currentScope.$eval(onloadExp);
```
