### ISSUE TITLE
$location.search() is empty when $urlRouterProvider.otherwise is called

### ISSUE THREAD

**Issue by Baloobear** [angular-ui/ui-router#2099]
Hello.

I've defined some states and want to use a fallback state/url defined with <code>otherwise</code>. Because the states do not define the root url '/' (I have no view for this state) but the app may be started by this url with some optional query params, I tried to use the function call of <code>otherwise</code> to keep possibly given params.
But when the <code>otherwise</code> function is called, the <code>$location.search()</code> is empty, although the url looks like <code>http://localhost:9002/?ac=1</code>.

Maybe a side effect will be that the given url will be rewritten to <code>http://localhost:9002/?ac=1#/search</code> although I would expect the url to be rewritten to <code>http://localhost:9002/#/search?ac=1</code>.

<pre>
$urlRouterProvider.otherwise(function($injector, $location)
{
    var state = $injector.get('$state');
    console.log('location', $location, 'location.search()', $location.search());
    state.go('search', $location.search());
    return $location.path();
});

$stateProvider
    .state('search',
    {
        url: '/search',
        templateUrl: 'templates/search.html'
    })
    .state('displays',
    {
        url: '/displays',
        templateUrl: 'templates/displays.html'
    })
    .state('favorites',
    {
        url: '/favorites',
        templateUrl: 'templates/favorites.html'
    })
    .state('detail',
    {
        url: '/:id',
        templateUrl: 'templates/detail.html',
        controller: 'DetailController'
    });
</pre>

Is this a real error of the ui-router or am I just handling this use case the wrong way?

**Note** I'm not using the html5mode. Is this a "must have" for this use case?

I'm not sure if the topic fits the source of the problem, so please let me know if I'm wrong.

Thanks,
Dennis

**Comment by maxmarkus** [comment]
Hello, 
just a comment on your side effect. This is a correct behavior according to RFC (http://tools.ietf.org/html/rfc3986#section-3.4)  an url consists of .../path ?param #fragment (in this order). 
As you mentioned, html5 mode could help. 

Alternatively you can do magic inside your webserver configuration, e.g. redirecting on behalf of your parameters (if its only a bunch,  or even "if a parameter is set" you could forward all params to a extraction state. 
( localhost:9002/#/redir/paramname~value/paramname2~value ) which redirects to your desired state after saving the params. 

Regards, Max

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
