### ISSUE TITLE
Cannot navigate to URL-less child of abstract state in v0.2.15

### ISSUE THREAD

**Issue by edbentinck** [angular-ui/ui-router#2100]
First off, apologies if this issue has already been raised. I looked, but I couldn't find anything related.

Since upgrading to `v0.2.15` I'm having trouble with child states of `abstract` states when the child has no URL. e.g.:

```
$stateProvider
    .state('login', {
      url: '/login',
      templateUrl: 'views/login.html',
      controller: 'LoginCtrl'
    })
    .state('parentstate', {
      abstract: true,
      url: '/parent',
      templateUrl: 'views/parent.html',
      controller: 'ParentCtrl'
    })
    .state('parentstate.childstate', {
      views: {
        '@parentstate': {
          templateUrl: 'views/child.html',
          controller: 'ChildCtrl'
        }
      }
    });
```

I've tried using both `ui-sref="parentstate.childstate"` and `$state.go(parentstate.childstate)`, but neither works. It worked fine in my app previous to `v0.2.15`, so I'm a little confused.

Here are 2 plunker's demonstrating the issue:

Using `angular-ui-router v0.2.14` (works as I expected):
http://embed.plnkr.co/JCrLFLbgkkZQL4H0Ouk7/preview

Using `angular-ui-router v0.2.15` (doesn't work):
http://embed.plnkr.co/zDFET5taEIIq60MzKayf/preview

In the case of my app, the child state is displayed for less than a second before redirecting back to the fallback state.

Any ideas? Much appreciated.

**Comment by silviogutierrez** [comment]
I have the same issue now, all my e2e tests are failing because the state can't be accessed using $state.go.

**Comment by eddiemonge** [comment]
easy workaround is to set a url of `''`. not sure if this is a bug or not though. The behavior shouldn't have changed though.

**Comment by silviogutierrez** [comment]
Wouldn't that conflict with the other children that *do* have that URL?

So I have: abstract-parent-state, child-state-one-with-url, child-state-two-without-a-url.

Historically, child-state-two-without-a-url was a confirmation state that you arrived at from child-state-one-with-url using a non URL param that could *only* be built on the first page.

If I give both URLs (even if distinct), users will be able to directly get to the second state without the proper population.

Maybe I'm missing something, but I imagine this is the primary use case for url-less child states: states we purposely don't want with a direct URL.

**Comment by eddiemonge** [comment]
The parent states still do their thing before the child states do though.
