### ISSUE TITLE
$state.href omits params even when squash:false is set

### ISSUE THREAD

**Issue by jshado1** [angular-ui/ui-router#2101]
```js
{
  name: 'foo',
  params: {
    bar: {
      squash: false,
      value: 'qux'
    }
  },
  url: '/{bar:string}'
}
// -----
$state.href('foo');
```

In the above, I believe the output of $state.href should contain _qux_ because it is unsquashable (and the router injects it into the url when it is not present).

On a side note, it would be nice if $state.href supported passing a `policy` option similar to `$state.$current.url.$$format()`

**Comment by christopherthielen** [comment]
Huh. At first glance I agree. It probably needs a call to params.$$values()

**Comment by jshado1** [comment]
If you point me to where this is, I'll take a stab at it.

**Comment by christopherthielen** [comment]
I added a unit test for your scenario, and it works.  You might have to recreate this in a plunkr.

see: 17e7757dee3a8ff968f490a9d58b1766a8334703

**Comment by jshado1** [comment]
Sorry for the delay. Our code has been changed; I'll try to dig around to see if I can the old commit (and for possible lurking variables).

**Comment by eddiemonge** [comment]
@jshado1 any update? If so, I'll reopen this

**Comment by jshado1** [comment]
Sorry, I can't seem to find it.
