### ISSUE TITLE
States cannot be added in jasmine unit tests

### ISSUE THREAD

**Issue by gitnik** [angular-ui/ui-router#2105]
I am trying to test a component that needs some states. However defining them via `$stateProvider` doesn't seem to work, as it doesn't add any states. here's come code to illustrate the issue:

```javascript
beforeEach(module(function($stateProvider) {
    // add a bunch of states here        
    $stateProvider.state();
}));
```

```javascrpipt
it('should do something', function () {
    // if I do $state.get() here, it's empty and the code that depends on it doesn't work
});
```

**Comment by eddiemonge** [comment]
Did you do a state.go first?

**Comment by gitnik** [comment]
Yes inside the actual test. But that's when I get `Could not resolve 'foobar from state ''` because the states don't get added

**Comment by gitnik** [comment]
Ok I'm dumb. In the `beforeEach` I tried to define to routes for a parent state that didn't exist which means the states never go added. Although this is an error on my side, maybe you guys should think about throwing an exception in this case.
