### ISSUE TITLE
Interest in adding `$stateProvider.otherwise` to proxy `$urlRouterProvider.otherwise`...?

### ISSUE THREAD

**Issue by al-the-x** [angular-ui/ui-router#2106]
More of a niggling complaint with the API of `$stateProvider` and configuring routes, but I wanted to solicit some feedback before issuing a PR. I teach using UI Router and regularly forget to include `$urlRouteProvider` in my `config` callback to configure a default route. When I realize my mistake and correct it, I'm reminded of how unwieldy that pattern is to remember... and fit on a projector screen. 

Since [`$stateProvider` is dependent on `$urlRouterProvider`](https://github.com/angular-ui/ui-router/blob/master/src/state.js#L22), what about providing a proxy to `$urlRouteProvider.otherwise` as a part of that provider's API? For example, instead of:

```javascript
angular.module('demo', [ 'ui.router' ])
  .config(function($stateProvider, $urlRouterProvider){
    $stateProvider
      .state('home', { /* . . . */ })
      .state('items-list', { /* . . . */ })
      .state('items-new', { /* . . . */ })
      .state('items-detail', { /* . . . */ })
      .state('items-edit', { /* . . . */ })

    $urlRouterProvider.otherwise('/');
  })
```

With `$stateProvider.otherwise`:

```javascript
angular.module('demo', [ 'ui.router' ])
  .config(function($stateProvider){
    $stateProvider
      .state('home', { /* . . . */ })
      .state('items-list', { /* . . . */ })
      .state('items-new', { /* . . . */ })
      .state('items-detail', { /* . . . */ })
      .state('items-edit', { /* . . . */ })
    .otherwise('/');
  })
```

Ideally, `$stateProvider.otherwise` should accept a route name instead of a URL, I think, and that's also something that can be done. What are your thoughts on this approach? I'm happy to submit a PR with tests.

**Comment by nateabele** [comment]
This was brought up a long time ago. I'm not really for it as it breaks the abstraction boundary.

**Comment by al-the-x** [comment]
I can understand that concern, but I'm not proposing a migration of logic but a well-documented proxy method. Indisputable where the underlying logic belongs; worth consolidating the interface a developer consistently configures?

**Comment by al-the-x** [comment]
Any further discussion about this?
