### ISSUE TITLE
event.preventDefault() and multiple views

### ISSUE THREAD

**Issue by cupito** [angular-ui/ui-router#2107]
Maybe a question, maybe an issue.

I have an angular APP with multiple named views. These views are role restricted. If the role is not fulfilled the view should not geht loaded. To avoid this I listen to the stateChanged event. 

This will be thrown once and then the views can be evaluated. But if for one view the role is not correct and event.preventDefault() will be used and all independent of the other checks the state will not changed. 

Does this behaviour worked like designed or is there something wrong?

**Comment by eddiemonge** [comment]
Im not really sure what the question is. Can you make a plnkr example please?

**Comment by cupito** [comment]
For sure http://plnkr.co/edit/jXRunyBxMDkuY2BRHRTO?p=preview

**Comment by cupito** [comment]
Any news on this?

**Comment by eddiemonge** [comment]
You could try something like this: http://plnkr.co/edit/JWyYws0uxvo1ey7sUWic?p=preview

Also, maybe read http://jan.varwig.org/archive/how-to-do-nested-views-in-angularjs-hint-dont
