### ISSUE TITLE
Controller initialised after a $state.go with {notify: false}

### ISSUE THREAD

**Issue by caillou** [angular-ui/ui-router#2108]
## The Bug

When a `$state.go` is called with `{notify: false}` as follows, a bug occurred:

```javascript
$state.co('foo', {}, {notify: false})
```

On the **next state change**, the current controller will be initialised a second time.

## Plunker Link

Follow the steps to reproduce on Plunker:

http://plnkr.co/edit/wMiVOb?p=preview

**Comment by eddiemonge** [comment]
It does indeed look like a bug.

**Comment by PhiLhoSoft** [comment]
See #2087, looks similar. Very annoying when a controller loads data on initialization.

**Comment by RickWalker** [comment]
This is the same issue as [#1673](https://github.com/angular-ui/ui-router/issues/1673) which is apparently fixed by PR [#2003](https://github.com/angular-ui/ui-router/pull/2003), so hopefully it should be easy enough to solve.

**Comment by eddiemonge** [comment]
similar to #1673 but slightly different I think

**Comment by jessezhang91** [comment]
It's a little different from #1673 but should still be fixed by PR #2003. The actual issue I was having is described in this bug.

**Comment by eddiemonge** [comment]
marking as duplicate of #2087
