### ISSUE TITLE
How I can add script to template mode HTML

### ISSUE THREAD

**Issue by ialex90** [angular-ui/ui-router#2109]
Hi all,

I need (I know is not a good practice) to put all my partials written in my app.js, like this

         .state('q11', {
                template: "<h4>My title</h4>"+
                                "<p>lorem ipsum ..... </p>"

That is working, but the problem is when I need to put a script inside of html, for example:

        .state('q11', {
                template: "<h4>My title</h4>"+
                                "<p>lorem ipsum ..... </p>"+
                                "<script type="text/javascript"></script>"

That's not working, why? it should be the same, isn't it?

Thanks!

**Comment by eddiemonge** [comment]
No. Scripts dont get evaluated when added that way. What is in the scripts? Can you load them with your app files and then call the function in that states controller?

**Comment by eddiemonge** [comment]
This can/should also be asked on stackoverflow instead of here.

**Comment by ialex90** [comment]
I needed it because I'm using a controller for all partials with a global object and if I add another controller to this partial I will not able to use that object (I used $rootScope to share the object between controllers and now it's working perfectly)

Thanks
