### ISSUE TITLE
Cannot jump between links ... am I missing something?

### ISSUE THREAD

**Issue by CaledoniaProject** [angular-ui/ui-router#2112]
Hi,

I'm trying to jump between these, it doesn't work either ways, 

`#/pages/fp_test?id=xxx` to `#/pages/fp_test` (through a `<a href="#/pages/fp_test">` tag)

But nothing changes, I had to press F5 manually, is there a problem with the code below?

```
app.config(function($stateProvider, $urlRouterProvider) {
  $urlRouterProvider.otherwise('/pages/dashboard');

  $stateProvider.state('index', {
    url: '/pages/:name',
    reloadOnSearch: true,
    templateUrl: function($stateParams) {
      return 'templates/' + $stateParams.name + '.html';
    },
    controllerProvider: function(loader) {
      return loader;
    },
    resolve: {
      loader: ['$ocLazyLoad', '$stateParams', function($ocLazyLoad, $stateParams) {
        var url = 'templates/controllers/' + $stateParams.name + '.js';

        return $ocLazyLoad.load(url).then(function () {
          return $stateParams.name;
        });
      }]
    }
  });
});
```

**Comment by CaledoniaProject** [comment]
Ok added a child state

.state('index.id', {
   url: '?id'
});

Now jumping from `#/pages/fp_test` to `#/pages/fp_test?id=xxxx` works via `  $state.go('index.id', { id: res.data.id }, {reload: true});`

But jumping back won't do

**Comment by eddiemonge** [comment]
You should be using ui-sref to switch states.
