### ISSUE TITLE
$state.go should treat toParams optional but it does not

### ISSUE THREAD

**Issue by koorgoo** [angular-ui/ui-router#2114]
[Wiki](https://github.com/angular-ui/ui-router/wiki/Quick-Reference#state-1) says that `toParams` are optional. But they are not. I wrote [a failing test](https://github.com/koorgoo/ui-router/commit/6609826dfd000c4fc6be387673b908ef8af80572) proving it.
Please, review test and notify me to create a pull request.

**Comment by christopherthielen** [comment]
Options is the third parameter to go(). Try go("state", undefined, options)

**Comment by koorgoo** [comment]
That works of course. Just thought that `go(state, options)` is an available signature.

**Comment by christopherthielen** [comment]
Nope!
