### ISSUE TITLE
templateUrl not loading updated templates

### ISSUE THREAD

**Issue by mayuroks** [angular-ui/ui-router#2118]
I have a block
```javascript
$stateProvider.state('contacts', {
  templateUrl: 'contacts.html'
})
```
The template loads. After I make changes to contacts.html file, I dont see the changes reflecting in browser.

I open the same URL in incognito mode and all the changes show up. Its as if there is some cache holding templates.

Can someone tell how to get updated templates in browser as soon as I edit them.

**Comment by eddiemonge** [comment]
Thats an action of your server/build system, not ui-router.

**Comment by mayuroks** [comment]
I am not using any build server. The code which I showed you is the only thing thats there. I was hoping that it should get the html file everytime the state is called.
