### ISSUE TITLE
Karma test breaks after using ui-router.

### ISSUE THREAD

**Issue by wpoosanguansit** [angular-ui/ui-router#212]
Hi,

I just tested out ui-router and ran my tests.  It shows an error which didn't with normal router:

Error: Unexpected request: GET /views/templates/default-template.html
	No more request expected
	    at Error (<anonymous>)

Is there anything special needed to be setup to work with Karma tests?  Thanks for your help.

**Comment by christopherthielen** [comment]
Those of you experiencing this issue, please add `$urlRouterProvider.deferIntercept()` to your test initialization code and report back.

**Comment by danse** [comment]
That does not seem to help in my case

**Comment by christopherthielen** [comment]
@danse when you run $digest(), what url is requested?  Is it your app's default state's template?

**Comment by christopherthielen** [comment]
### Initial State

When the `$state` service is loaded, UI-Router tries to load the default route, and part of that process is fetching the default route's template.  If you are getting an unexpected GET for one of the templates of your default route, you should tell UI-Router to defer intercept of the URL:

```
beforeEach(module(function($urlRouterProvider) {
  $urlRouterProvider.deferIntercept();
})));
```

If your unit tests involve ui-router transitions, UI-Router will attempt to fetch the templates required for the transition.  You will need to either register each template fetch with the `$httpBackend` mock, or pre-load all your templates.  

To register a template fetch:
```
beforeEach(function($httpBackend) {
  $httpBackend.expectGET("templates/templateUrl.html").respond("<div>mock template</div>");
}));
```

To preload your templates, use a karma pre-loading tool such as the one @ghost linked in this comment: https://github.com/angular-ui/ui-router/issues/212#issuecomment-60781482

If the templates are preloaded into the template cache by such a tool, $httpBackend is never invoked by UI-Router when it requests the template, and your state can be transitioned to in a test-friendly synchronous manner.

### Ionic Users

I've recently discovered that ionic preloads all ui-router templates into their own template cache service.  Disable that in your tests by either preloading, as mentioned above, or by disabling the $ionicTemplateCache service.

To disable the $ionicTemplateCache service, set the maximum number of templates to `0`:
```
beforeEach(module(function($ionicConfigProvider) {
  $ionicConfigProvider.templates.maxPrefetch(0);
})));
```
If that doesn't work, nuke the $ionicTemplateCache service by stubbing it out:
```
  beforeEach(module(function($provide) {
    $provide.value('$ionicTemplateCache', function(){} );
  }));
```

**Comment by eve-amandine** [comment]
It's maybe because I'm a noob with unit tests but it still not working for me.

I've tried adding the code @christopherthielen commented but I've the same error:
`Error: Unexpected request: GET modules/onboarding/signup-A.html
No more request expected`
(it's the template linked with the controller I'm testing)

I use ionic with the ui-router and when I put a $scope.digest() (for testing promises), I've this error even if I quit the $state of the controller (and I don't have any action with ui-router in the controller). In addition, with the promise I don't use $httpBackend nor other things (the service mocked with promise doesn't call an Api).

The only thing it's working is when I add this in the inject function:
`$httpBackend = $injector.get('$httpBackend');
$httpBackend.expectGET('modules/onboarding/signup-A.html').respond(200);`

But I would like to find a solution that works "automatically" without adding these lines in each unit tests controllers. Any idea?

**Comment by ltowarek** [comment]
Let's try the following lines as they work for me (ionic v1.0.0-beta.14):
```
  beforeEach(module(function($provide) {
    $provide.value('$ionicTemplateCache', function(){} );
  }));

  beforeEach(module(function($urlRouterProvider) {
    $urlRouterProvider.deferIntercept();
  }));
```

**Comment by eve-amandine** [comment]
Thanks!!!! Finally it works! :D
I had been trying that but it was added in an incorrect order.
For the noobs like me, you need to put these lines in this order: beforeEach with your controller's module  - these lines commented by @ltowarek - beforeEach with the inject.

**Comment by thebigredgeek** [comment]
Seems a bit ridiculous that the Ionic team didn't even consider testing when writing that.  Only the nuking method worked for me.

**Comment by oriweingart** [comment]
We implemented this feature for a private project.
PR was created: https://github.com/angular-ui/ui-router/pull/1795
Welcome to try it..

**Comment by brentonmcs** [comment]
Thanks - @christopherthielen - your Ionic section fixed up the issues I was having!!!

**Comment by gruppjo** [comment]
@ghost, @christopherthielen thanks. That worked brilliantly!

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by dchacke** [comment]
+1 @christopherthielen 

```
beforeEach(module(function($urlRouterProvider) {
  $urlRouterProvider.deferIntercept();
}));
```

does the trick for me. Also, thanks for the explanation. It's good to know that `$state` attempts to load the default route's template, and that this is *why* you would get unexpected GET requests in your tests.

**Comment by jakub-g** [comment]
Ionic + ng-describe
==================

We're using `ionic` and `ng-describe` and nothing provided here so far worked directly for us, but I managed to find a solution based on @christopherthielen answer in https://github.com/angular-ui/ui-router/issues/212#issuecomment-69974072

When using `beforeEach(module(function(...)))` along the tests (`it`) we were getting `Injector already created, can not register a module!` error
(`beforeEach` alone works fine, but it seems you can not use `module` inside `tests` function defined by ng-describe, because this is too  late in the lifecycle).

This worked for us

    angular.module('IonicTemplateCacheDisabler', [])
      .config(function($provide) {
        $provide.value('$ionicTemplateCache', function() {});
      })
      .run(function($ionicConfig) {
        $ionicConfig.templates.maxPrefetch(0);
      });
    
    ngDescribe({
      name: '...',
      modules: [... 'IonicTemplateCacheDisabler'],
      inject: [...],
      tests: function(deps) {
        it('...', function(){...})
        it('...', function(){...})
        it('...', function(){...})
      }
    });

This way `IonicTemplateCacheDisabler`'s `config` and `run` are invoked before each of tests, just as if `beforeEach()` was declared.

**Comment by jdmichaud** [comment]
@christopherthielen's solution does not work for me. The GET request keeps coming are met with 404 continuously until a 5 seconds timeout occurs:

```
16 01 2016 19:55:49.350:WARN [web-server]: 404: /header.html
16 01 2016 19:55:49.355:WARN [web-server]: 404: /footer.html
16 01 2016 19:55:49.359:WARN [web-server]: 404: /header.html
16 01 2016 19:55:49.367:WARN [web-server]: 404: /footer.html
16 01 2016 19:55:49.367:WARN [web-server]: 404: /header.html
16 01 2016 19:55:49.451:WARN [web-server]: 404: /footer.html
16 01 2016 19:55:49.455:WARN [web-server]: 404: /header.html
PhantomJS 1.9.8 (Linux 0.0.0) LoginService shall call login on the server and resolve the promise FAILED
        Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
PhantomJS 1.9.8 (Linux 0.0.0): Executed 21 of 31 (1 FAILED) (0 secs / 5.176 secs)
16 01 2016 19:55:49.465:WARN [web-server]: 404: /header.html
16 01 2016 19:55:49.468:WARN [web-server]: 404: /footer.html
```

**Comment by LukeSkyw** [comment]
@christopherthielen's solution does not work for me. The GET request keeps coming are met with 404 continuously until a 5 seconds timeout occurs:

```
16 01 2016 19:55:49.350:WARN [web-server]: 404: /header.html
16 01 2016 19:55:49.355:WARN [web-server]: 404: /footer.html
16 01 2016 19:55:49.359:WARN [web-server]: 404: /header.html
16 01 2016 19:55:49.367:WARN [web-server]: 404: /footer.html
16 01 2016 19:55:49.367:WARN [web-server]: 404: /header.html
16 01 2016 19:55:49.451:WARN [web-server]: 404: /footer.html
16 01 2016 19:55:49.455:WARN [web-server]: 404: /header.html
PhantomJS 1.9.8 (Linux 0.0.0) LoginService shall call login on the server and resolve the promise FAILED
        Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
PhantomJS 1.9.8 (Linux 0.0.0): Executed 21 of 31 (1 FAILED) (0 secs / 5.176 secs)
16 01 2016 19:55:49.465:WARN [web-server]: 404: /header.html
16 01 2016 19:55:49.468:WARN [web-server]: 404: /footer.html
```

**Comment by ErikAGriffin** [comment]
While I am able to resolve the issue of GET requests via the nghtml2js preprocessor, I'm wondering, what is the best way to test state transitions?  Is using the stateMock above the only way?

The example code on this website [this website](http://angulartestingquickstart.com/) shows the use of $state.go and $state.current in a test, but for me this does not work. $state.go seems to have no effect and the $rootScope.$digest() always loads the default state into $state.current.

Code:
```javascript
    // Test whether our state activates correctly
    it('should activate the state', function() {
        $state.go('state');
        $rootScope.$digest();
        expect($state.current.name).toBe('state');
    });
```

**Comment by guylhermetabosa** [comment]
Thanks a lot @Vratislav. You saved my day.

**Comment by PRossetti** [comment]
Hello everybody! I solved it using @jdart  solution, but I'd like to implement @christopherthielen once since it's the one with more votes.
My problem is that I don't understand how to implement it in my code. When I literally copy & paste the next in my unit test code:

> beforeEach(module(function($urlRouterProvider) {
>   $urlRouterProvider.deferIntercept();
> }));

I get this error:

> Error: Injector already created, can not register a module! in www/lib/angular-mocks/angular-mocks.js (line 2256)
> workFn@www/lib/angular-mocks/angular-mocks.js:2256:80

And when I try to inject $urlRouterProvider in my working block:
```
beforeEach(inject(function('service1','service2', 'etc') {
  //myStaff
  $urlRouterProvider.deferIntercept();
}))

```
I get this other error:

> Error: [$injector:unpr] Unknown provider: $urlRouterProviderProvider <- $urlRouterProvider
> http://errors.angularjs.org/1.5.3/$injector/unpr?p0=%24urlRouterProviderProvider%20%3C-%20%24urlRouterProvider (line 17765)
> www/lib/ionic/js/ionic.bundle.js:17765:86
> getService@www/lib/ionic/js/ionic.bundle.js:17918:46
> www/lib/ionic/js/ionic.bundle.js:17770:48
> getService@www/lib/ionic/js/ionic.bundle.js:17918:46
> injectionArgs@www/lib/ionic/js/ionic.bundle.js:17942:68
> invoke@www/lib/ionic/js/ionic.bundle.js:17964:31
> workFn@www/lib/angular-mocks/angular-mocks.js:2404:26

Could you help me please? Thank you!!

**Comment by Atul-sac** [comment]
Hi,
I am using $routeProvider and i have started facing same issue from 10 days back. same test cases were working before approx 10 days, but when i did fresh installation of all dependencies mentioned in package.json. my all test cases started failing which are dependent on $http service call and also which are based on $watch (basically where $apply() is called manually).
I am getting basically these two types of error -

1. Error: Unexpected request: GET templates/home.html No more request expected
2. Error: Unexpected request: GET API_URL No more request expected

It seems that few wrong commits has been made recently on KARMA/JASMINE, which are causing these issues, as mine old code base is working fine, only after installing fresh dependencies these test cases are failing now.

I am using below dependencies -

```
"devDependencies": {
"angular": "^1.6.5",
"angular-mocks": "^1.6.5",
"angular-route": "^1.6.5",
"browserify-istanbul": "^2.0.0",
"grunt": "^1.0.1",
"grunt-browserify": "^5.0.0",
"grunt-contrib-connect": "^1.0.2",
"grunt-contrib-copy": "^1.0.0",
"grunt-contrib-jshint": "^1.1.0",
"grunt-karma": "^2.0.0",
"istanbul": "^0.4.5",
"jasmine-core": "^2.6.4",
"karma": "^1.7.0",
"karma-bro": "^0.11.1",
"karma-browserify": "^5.1.1",
"karma-chrome-launcher": "^2.2.0",
"karma-coverage": "^1.1.1",
"karma-jasmine": "^1.1.0",
"karma-phantomjs-launcher": "^1.0.4"
}
```

Please help me out.
Thanks!
