### ISSUE TITLE
event.preventDefault in $stateChangeStart does not return to correct state.

### ISSUE THREAD

**Issue by Guardiannw** [angular-ui/ui-router#2122]
When using two states that share the same URL, a subsequent request to a child state that is prevented in the ```$stateChangeStart``` event using ```event.preventDefault()``` causes the state to be determined by the url, and therefore resolved incorrectly.  Please see plunkr -> http://plnkr.co/edit/7Erec9wuntnIxdXOQFaA. In order to achieve the effect, navigate from the authenticate page, to the nav page, to the restricted state.  After attempting to navigate to the restricted state, the user is automatically redirected to the authenticate page instead of the nav page which is expected.

**Comment by eddiemonge** [comment]
Why are they sharing the same url? how does your application know which to load when that url is hit?

**Comment by Guardiannw** [comment]
My application uses both the order in which it is declared to server up the login page upon first access to the site.  I also have a redirect script inside of the ```$stateChangeStart``` event.  This will navigate to the home state when the user logs in appropriately.  From there, the user will never navigate back to the root direction through the ```$location``` or through the browser navigation.  If the user uses the browser to force a redirect to the root, then the login is shown again.  All navigation will navigate through the state names, therefore always navigation to the home state instead of the login state.  Unfortunately, the ```event.preventDefault()``` causes a ```$location``` change that then triggers a new state lookup and state transition.  Instead of reverting to the previous state, the browser now navigates to the first state that is returned by the url lookup.  This may be an off the wall scenario, but I still think it is the desired use case that event.preventDefault() would cancel the state transition, rather than take you to a new state.  It should be based upon the state name and not the url.  Unless I misunderstand the documents, which is possible, all state names are mutually exclusive, but url's are not.  Two plus states can have the same url, but no states can share a state name.  Therefore, I think this should always be reverted by the state name instead of the url pattern.

**Comment by eddiemonge** [comment]
> If the user uses the browser to force a redirect to the root, then the login is shown again

:( what if they open it in a new tab? They have to login again? This seems very hostile to users.

Also, event.preventDefault in $stateChangeStart does return to a state, it prevents the new state from being transitioned to, keeping them in the current state.

**Comment by Guardiannw** [comment]
Ya, it is sad, but I cannot help it unless I use a cookie or some client storage or server side sessions.  I believe you when you say it returns to the same state, but it also navigate to a state defined by the url as in the plunker above.

**Comment by eddiemonge** [comment]
sorry that should have said "does not return to a state". missed the "not" part.

Why not just do something like this: http://plnkr.co/edit/FEwo3Lr3TU9gfaIKKaKt?p=preview

This isn't a bug in the code. Its more of a bug in the implementation so I am closing this ticket. For more support like this, please ask on stackoverflow.

**Comment by Guardiannw** [comment]
Oh ok, well the plnkr doesn't do what I need it to because I need the login page to be the same url as the main application page.  I do think this is something that needs to be fixed however because the event.preventDefault() is not doing what is expected by the users.
