### ISSUE TITLE
HELP - Potentially infinitely nested states. Is it possible for me to do?

### ISSUE THREAD

**Issue by jerczu** [angular-ui/ui-router#2125]
Ok so here's my problem Imagine a photo feed that can be grouped by tags.

I have $stateProvider defined states feed, feed.photo and feed.photo.tags;

Now when you go to feed.photo.tags its meant to show you all tags that you tagged the photo with.

But from there I'd like to be able to click the tag and see the feed of photos grouped by this tag so dynamically go to feed.photo.tags.feed and from there deeper and deeper as much as linking allows me (feed.photo.tags.feed.photo.tags.feed.photo.tags....) potentially infinitely nested.

Can someone point me in the right direction whether it is possible to do without actually specifying the state nesting through the $stateProvider other than getting to lets say feed.photo.tags and from there going dynamically down whatever route user chooses?

**Comment by eddiemonge** [comment]
You probably want to rethink your states so you don't have this. Maybe you would rather have the photos and tags be parameters instead of child states?

**Comment by eddiemonge** [comment]
Also, this is a better question for Stackoverflow as it isn't a bug in ui-router and we are trying to keep it for bugs and feature enhancements and leave stackoverflow for support and implementation questions.

**Comment by Discmt** [comment]
For something like this I would suggest using a path as a single parameter
rather then splitting these states into three different things. Something
like XPath, that your state parses and then seeks out would work much
better for this kind of abstraction.
