### ISSUE TITLE
URLs with #fragments not jumping to correct element

### ISSUE THREAD

**Issue by vike27** [angular-ui/ui-router#2128]
Not working for me, goes to correct page with correct fragment but does not jump to anchor.

```
<a id="yoh">GOING HERE!<a> 
<a class="pull-right" ui-sref="reserve({ '#':'yoh' })"><strong>Edit</strong></a>
```

Saw this referenced in: https://github.com/angular-ui/ui-router/pull/1855 & here: https://github.com/angular-ui/ui-router/pull/1867

**Comment by bertonha** [comment]
Any workaround can be make?

**Comment by vike27** [comment]
@bertonha Hmm no, idk why this is not working. Did I make a mistake or something?

**Comment by bertonha** [comment]
@vike27 on my case the place here it should go, Is hidden and need to the show first. This way works Perfect.

**Comment by vike27** [comment]
@bertonha actually I just realized that it is working on initial page load since its done at the html level. As soon as the rest of the angular code gets injected and the rest of the angular template gets loaded it gets pushed down essentially eliminating the effect. I would need to create a timeout function or something so it works properly. Too much hastle, would think there would be a simpler way to get this to work.

**Comment by eddiemonge** [comment]
https://gist.github.com/christopherthielen/b3fc0304b737a4bf8ec9
