### ISSUE TITLE
Is there any way to assign template in resolve in state

### ISSUE THREAD

**Issue by pavankumarkatakam** [angular-ui/ui-router#2129]
currently my code is 

````
   .state('something', {
                    url: '/something',
                    //templateUrl: 'files/files.html',
                    controller: 'SomethingController',
                    resolve: {
                        async: ['$q', function ($q) {
                            var defer = $q.defer();
                            require([], function () {
                                module = require('source/controllers/something'); // it will return controller and template also
                                defer.resolve(app.register(module.controller))
                            });
                            return defer.promise;
                        }]
                    }
                })
```

Im using webpack so there is require's , what actuall code is im registering the controller asyncronusly at the same time also want to set template in `resolve` please tell me is there a way like this


````
   .state('something', {
                    url: '/something',
                    //templateUrl: 'files/files.html',
                    controller: 'SomethingController',
                    resolve: {
                        async: ['$q', function ($q) {
                            var defer = $q.defer();
                            require([], function () {
                                module = require('source/controllers/something'); // it will return controller and template also
                                defer.resolve(app.register(module.controller))

                                this.template=module.template; 
                            });
                            return defer.promise;
                        }]
                    }
                })
````

**Comment by eddiemonge** [comment]
Im slightly confused why you want to set the template in the resolve instead of in the state definition

**Comment by pavankumarkatakam** [comment]
> why you want to set template in the resolve instead of in the state definition?

As of now , when the user got to `Something` state then the respective controller will be downloaded and register with running angular module, at the same time template also be downloaded and register in cache, which makes two requests to the server, but i want to download the single file which consists of controller as well as template, and want to set them in `resolve`.

**Comment by pavankumarkatakam** [comment]
I'm digging in to this, so far the code look like
````
  .state('something', {
                    url: '/something',
                    templateUrl: 'something',
                    controller: 'SomethingController',
                    resolve: {
                        async: ['$q', function ($q) {
                            var defer = $q.defer();
                            require([], function () {
                                module = require('source/controllers/something'); // it will return controller and template also
                                defer.resolve(app.register(module.controller))

                                app.run(function($templateCache){
                                      console.log("template is going to be set");
                                       $templateCache.put("something",module.template);
                                 }); 
                            });
                            return defer.promise;
                        }]
                    }
                })
````
But it's not working , i don't know why the `console.log` statement not yielding anything.

**Comment by nateabele** [comment]
This is really an issue for StackOverflow, but if your template selection is based on dynamic data, return the data in a resolve and inject it in a `templateProvider`.

**Comment by pavankumarkatakam** [comment]
Thank you @nateabele , for suggesting the `templateProvider` thing, i don't know these thing exist up to now . It's working prefectly as im expected.

this is my code
````
  .state('something', {
                    url: '/something',
                    templateUrl: 'something',
                    controller: 'SomethingController',
                    resolve: {
                        module: ['$q', function ($q) {
                            var defer = $q.defer();
                            require([], function () {
                                module = require('source/controllers/something'); // it will return controller and template also
                                defer.resolve(module)

                            });
                            return defer.promise;
                        }],
                        controller: ['module', function (module) {
                          app.register(module.controller))
                        }],
                       view:['module',function(module){
                             return module.template;
                         }]
                    },
                  templateProvider: function (view) {
                        return view;
                    }
                })
````



Its work correctly as im expected, but is this right way

benefits:
 1) only one request to the server for controller javascript file and template file.
 2) once it downloaded, from next time it is under cache, so no duplicate request.
3) As im using webpack i can organize my files very cleary now.

**Comment by eddiemonge** [comment]
Seems ok
