### ISSUE TITLE
scope changed in nested view but not sync back to controller

### ISSUE THREAD

**Issue by reidlai** [angular-ui/ui-router#2131]
I have the following state signup.  In Main view, I have embed controller SignUpFormController in the template SignUpForm.html and this template has two nested view name SignUpCard and FabPanel.  

SignUpCard is only a form which has models refer $scope variables defined in SignUpFormController.  And FabPanel just two FAB button call function defined in SignUpFormController too.  When I enter data in SignUpCard and call FAB button function, I found 
all models entered in SignUpCard did not populate back to $scope.  Is there any implicit scope defined when I have nested view?  Thanks for your advice.

	.state("signup", {
		url: "/signup",
		views: {
			"@": {templateUrl: "app/views/templates/MainLayout.html"},
			"Toolbar@signup": {templateUrl: "app/views/templates/GeneralToolbar.html"},
			"Main@signup": {templateUrl: "app/views/templates/SignUpForm.html"},
			"SignUpCard@signup": {
				templateUrl: "app/views/cards/SignUpCard.html"
			},
			"FabPanel@signup": {templateUrl: "app/views/cards/FabPanel.html"}
		}
	})

**Comment by eddiemonge** [comment]
The scope is specific to the view it is on. If you want to talk to other scopes, you need to use a service or another implementation.

**Comment by reidlai** [comment]
OK , thx

**Comment by eddiemonge** [comment]
Closing this. If there is a bug let me know and I'll reopen it.
