### ISSUE TITLE
$window.open triggers state change error event 

### ISSUE THREAD

**Issue by chiruneeru** [angular-ui/ui-router#2132]
In my web application, i am navigating to "EmailLetter" state to generate email letters for my clients. In this page, i have two buttons "Generate" & "Preview". "Generate" button click events works fine without any problem but "Preview" button is triggering state change error event even though it received success response from ajax service call. I am using below code snippet for "Preview" button click event

```
function openPreview(isValid) {
        if (isValid && validateForm(true)) {    
            webApi.previewDocument(previewRequest)
                  .then(function (response) {
                    if (response && response.PreviewUrl) {
                        $window.open(response.PreviewUrl);
                    } else {
                        notification.error("Unable to generate preview!");
                    }
                });
```

In the above code snippet, i am able to open preview url in a new window successfully but this statement is triggering state change error event after opening preview url in new window. Kindly let me know if i can avoid this. Sample plunker code here http://plnkr.co/edit/iqKSXsmIb86qtXMFKDa9?p=preview

![error](https://cloud.githubusercontent.com/assets/13517667/8900929/27312d8e-3462-11e5-9d79-87513bd0f1a4.png)

**Comment by eddiemonge** [comment]
Using that link, I am not getting any errors. You should also probably use a full url including `http://`
