### ISSUE TITLE
Escape comma in array values

### ISSUE THREAD

**Issue by jinder** [angular-ui/ui-router#2133]
UI Router will automatically convert a route parameter with an array into a comma delimited list.  However, if any of the values contains a comma, it won't escape the values.

Should UI Router be using something a bit stricter here?  [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) lists a more stringent option for adhering to RFC 3986:

```
function fixedEncodeURIComponent (str) {
  return encodeURIComponent(str).replace(/[!'()*]/g, function(c) {
    return '%' + c.charCodeAt(0).toString(16);
  });
}
```

Should that be used instead?

**Comment by eddiemonge** [comment]
Why not add a failing test and see if that fixes it? If so, then yes.

**Comment by tommck** [comment]
Is this still an issue?  If so, I could probably tackle this if I get a little time
