### ISSUE TITLE
$urlMatcherFactory.type custom type

### ISSUE THREAD

**Issue by btm1** [angular-ui/ui-router#2136]
I've looked at this question http://stackoverflow.com/a/27182177/1679310

Which shows how to make a simple boolean type for ui-router but what about a more complicated use case such as:

Currently arrays are converted as such a = [1,2,3] -> ?a=1&a=2&a=3 I need to create a $urlMatcherFactory.type that will convert an array to a comma separated string and then back again when decoding i.e. a = [1,2,3] -> ?a=1,2,3 -> a=[1,2,3].

Anyone have any idea how to do this? The documentation is horrible and I've tried to start one:

```
$urlMatcherFactory.type('array',{
        name : 'arrayToString',
        decode: function(val) {
            console.log(val);
            if(_.contains(val,',')) {
                return val.split(',');
            } else {
                return [val];
            }
        },
        encode: function(val) {
            console.log(val);
            var v = angular.isArray(val) ? val : [val];
            return v.join(',');
        },
        equals: function(a, b) { return this.is(a) && a === b; },
        is: function(val) {
            return angular.isArray(val);
        },
        pattern: /\d+/
   });
```

This isn't clear to me:

```
$urlMatcherFactory.type('array'
```

can this be anything or does the value have to be 'array' 'string' etc....?

The decode and encode functions are self explanatory. The equals function isn't clear at all and I'm not sure what it's doing

The "is" function is checking for equals on which end? am I supposed to be determining whether or not it's a comma separated list or an array here?

Similarly pattern I'm guessing is looking for patterns on the url but i'm not sure why this is needed if when declare this on the route definition.

**Comment by zanettin** [comment]
+1

@btm1 just facing the same problem and found your issue.
I have not used the equals block so far, but the is. The "is" function just determines if the encode or decode section will be called. on true => encode on false => decode.

````
$urlMatcherFactory.type('array'
````
'array' can be anything. It's up to you how to name it. Just make sure, that you're using the same name in your route:
````
url : '/foo/{myVar:array} // <- array has to match your type
````

if you already found a solution for your problem, I would be realy happy to get a snippet or a hint.
thanks

**Comment by btm1** [comment]
@zanettin you certainly know more than I do ... I noticed the true false thing with is and it calling decode or encode respectively but I wasn't sure how everything was supposed to work together.

This is the part that I think got me before and I didn't realize you could do this to stop it from turning into an array:

```
url  : '/search?q&{filterType:filter}
params: {
    filterType : { array : false}
}
```

Thanks for all your help!

**Comment by zanettin** [comment]
I'm happy that it was helpful! uirouter is realy powerful and I still discover new possibilities :-)

**Comment by davincho** [comment]
@zanettin Is the above code sample still possible with release 0.2.18?

**Comment by zanettin** [comment]
@davincho I'm using this in a production env and have latest ui-router package installed via bower. so yes, it still works for me.

**Comment by christopherthielen** [comment]
Docs are here: https://ui-router.github.io/docs/latest/classes/url.urlmatcherfactory.html#type and here https://ui-router.github.io/docs/latest/interfaces/params.paramtypedefinition.html
