### ISSUE TITLE
Nested routing doesn't seem to work in ES6 apps

### ISSUE THREAD

**Issue by herve-odiard** [angular-ui/ui-router#2137]
It looks like nested states are not working in applications written in ES6.

This is a plunkr used to reproduce the problem: http://embed.plnkr.co/tOxlTvtGMLv875aL3j0Z/preview

(based on [angular-es6-seed](https://github.com/smaye81/angular-es6-seed))

By contrast the same app using flattened states works ok: http://embed.plnkr.co/lG10Myb4Yawr2GWS8ZyC/preview

**Comment by eddiemonge** [comment]
ES6 doesn't have widespread support for now so you need to feature test for the things you want to work. You can use something like babel to transpile the code so you can write in es6 and still have it work in es5 supported places.
