### ISSUE TITLE
Chainable state definition

### ISSUE THREAD

**Issue by jdiehl** [angular-ui/ui-router#2138]
Hi there,

thanks for this great AngularJS module!

I have written a module to make state definition (in my opinion) a bit easier. It allows defining states as command chains like this:

```javascript
$stateBuilderProvider

// main state
.state('main').url('').abstract().resolve('session', resolveSession)
  .state('home').default().done()
  .state('about').done()
.done()

// user state
.state('user').abstract()
  .state('profile').defaultChild().done()
  .state('friends').abstract()
    .state('list').url('').done()
    .state('show').url('/:id').done()
  .done()
.done();
```

You can find the module here: https://github.com/jdiehl/angular-state-builder

If you are interested, I would be happy to integrate this module into your project or follow any other advise you have to make it more accessible for the community.

Cheers,
  Jonathan

**Comment by eddiemonge** [comment]
Out of curiosity, why do you think this is easier than a config block?

**Comment by jdiehl** [comment]
I think it makes state hierarchies easier to define and clearer, and the generators for 'controller' and 'templateUrl' make it very easy to define states by convention (all state templates are placed in a specific folder with a specific name, etc.)

**Comment by erkanarslan** [comment]
I think a config blog is more clear than your suggestion.

**Comment by eddiemonge** [comment]
@jdiehl I think this should stay as a community plugin. I'm not sure if adding it to core adds a lot of value for most of the users. @nateabele what are your thoughts?

**Comment by eddiemonge** [comment]
Closing because of what I said in my last comment. You should write it up and release it to the community though

**Comment by nateabele** [comment]
I like the generators thing, but chaining just seems noisy to me.
