### ISSUE TITLE
Calling abstract state controller AND child state controller

### ISSUE THREAD

**Issue by jamesla** [angular-ui/ui-router#2141]
I am wanting to create nested states that call multiple controllers on their way through which I can hook into. I have defined the following states like this:

            .state('account', {
                url: '/account',
                abstract: true,
                controller: 'AccountCtrl'
            })

            .state('account.register', {
                url: '/register',
                templateUrl: 'templates/account/register.html',
                controller: 'RegistrationCtrl'
            })

            .state('account.login', {
                url: '/login',
                templateUrl: 'templates/account/login.html',
                controller: 'LoginCtrl'
            })

However when I visit /account/login or /account/register only the AccountCtrl is being called when I would expect AccountCtrl and then RegistrationCtrl or LoginCtrl. Is there something that is preventing me from doing this?

**Comment by erkanarslan** [comment]
How do you test if child controllers are called? If your child controllers depend on some data that is being fetch from server by parent controller, that data may not be available when child controllers are executed.

**Comment by eddiemonge** [comment]
put a console.log in each of the controllers and you'll see that they should be fired

**Comment by jamesla** [comment]
Hey thanks guys yeah I have a console.log in each controller and only the account controller is being called. If I change register or login to call the register or login controller directly it works fine. Should I set up a codepen example?

**Comment by erkanarslan** [comment]
Yeah, it would be great.

**Comment by dimw** [comment]
@jamesla: Recently had the same issue because I have defined an empty named _view_ within my abstract parent state without any controller. After adding _controller_ property to the view definition both (parent and child) controllers are called. Maybe it brings you further.
```javascript
$stateProvider
  .state('main', {
    abstract: true,
    controller: 'IgnoredMainCtrl', // This one is ignored!
    view: {
      '': {
        templateUrl: 'views/main.html',
        controller: 'MainCtrl' // This one is called
      },
      ...
    })
  .state('another', {
    parent: 'main',
    controller: 'AnotherCtrl' // This one is called as well
   });
```

**Comment by eddiemonge** [comment]
@jamesla can this be closed or do you have any further info?

**Comment by nabinca** [comment]
Hi, I just faced the same problem with the simple example from the post from jamesla.
Only the controller from the abstract state is getting called, but not the controller of the child.
Adding  
`template: "<ui-view />"`
to the abstract state solved the issue for me.
Because there isn't so much documentation on abstract states, I'm not sure if this is a bug or a feature. :)

**Comment by titocr** [comment]
Yes, the comment by @nabinca helped. It seems my unnamed state needed to have "template: '<ui-view />'" specified before it would work as expected.

**Comment by pencilcheck** [comment]
@nabinca thanks for your suggestion but your solution doesn't work for me.

I have the templateUrl for the abstract state with named views and such, and the child state almost mirrors the abstract state minus the abstract: true.

And this issue still persists for me, I put "debugger" in the child Controller and they are never called

**Comment by GustavoCostaW** [comment]
@nabinca thx for solution, why this bug continue today? exist any pull request to fix this? thx!

**Comment by ahgittin** [comment]
As hinted by @nabinca's comment, you need a `<ui-view />` in the parent state's template in order to trigger loading the child (else how will it know what to do with the template?).

Might be nice if an error was reported where a child state fires with a dedicated controller who isn't invoked because the `<ui-view/>` is missing in the parent...
