### ISSUE TITLE
reload option is not working as stated in documents

### ISSUE THREAD

**Issue by erkanarslan** [angular-ui/ui-router#2142]
In the documents, it says that if reload parameter is given as a string, it will reload the given state and all child states. However, it reloads all parents states as well and causes unintended flickers in the page.

I use this in html, it is repeated for all workspaces:

    ui-sref="app.workspace.feeds({name : workspace.name})" ui-sref-opts="{reload: 'workspace'}"

States are defined like this:

````javascript
.state('app.workspace', {
	abstract	: true,
	templateUrl	: 'modules/workspace/workspace.html'
})
.state('app.workspace.feeds', {
	url			: "/workspace/:name",
	templateUrl : "modules/workspace/feeds.html"
})
.state('other child states', {})
````

I have tried different values for reload option like:

    * 'app.workspace'
    * 'app.workspace.feeds'
    * 'workspace.feeds'
    * 'workspace'

But none of them works as expected. In my application, I want the workspace state and controller to be reloaded every time when a different workspace link is clicked to load workspace details. Without reload option, it will load the workspace controller for once and it won't be reloaded when another workspace is selected and will show the same page for all workspaces. I have to use reload. But it reloads parents states as well.

**Comment by eddiemonge** [comment]
> A method that force reloads the current state. All resolves are re-resolved, controllers reinstantiated, and events re-fired.

Sounds like its working to me. It does reload the current state (in your usage its `reload:true`) but that means all states get reloaded

**Comment by erkanarslan** [comment]
It seems that you didn't read my comment properly. I don't want all states to be reloaded. I just want the app.workspace state to be reloaded with its child states. But even if I use `reload : 'app.workspace` it reloads all these states including the parent `app` state and it causes flickers on the page.

Probably state name in reload is relative rather than absolute and I cannot reach the parent state.

I solved this problem by moving `/workspace/:name` url part to parent state. It reloads the app.workspace when parameter changes

**Comment by eddiemonge** [comment]
Your issue says its not working as stated in documents but it is. The docs say:

> A method that force reloads the current state. All resolves are re-resolved, controllers reinstantiated, and events re-fired.

And that is what is happening.

**Comment by erkanarslan** [comment]
As you see in my code, I don't use reload function. I use transitionTo in html. And in the documentation it says:

> reload (v0.2.5) - {boolean=false|string=|object=}, If true will force transition even if the state or params have not changed, aka a reload of the same state. It differs from reloadOnSearch because you'd use this when you want to force a reload when everything is the same, including search params. **if String, then will reload the state with the name given in reload, and any children.** if Object, then a stateObj is expected, will reload the state found in stateObj, and any children.

From that explanation if reload is given as a string (state name) then it should only reload that state and its children. It shouldn't reload parent states and shouldn't re-execute parent controllers. Otherwise it would be no different than `reload:true`.

What do you say about that?

**Comment by eddiemonge** [comment]
Can you paste your code into a plnkr showing it not working please?

**Comment by erkanarslan** [comment]
I couldn't reproduce it in plnkr. Probably the problem was in my code.
