### ISSUE TITLE
Reinitialization of the view in nested views on performing any action

### ISSUE THREAD

**Issue by mukulgupta2507** [angular-ui/ui-router#2144]
Hi,

I have created a question on StackOverflow http://stackoverflow.com/questions/31732258/view-is-getting-intialized-again-and-again. 

Can anyone from here please take a look at it ?

I think this can be related to using ui-router's ui-view in nested views.

Thanks

**Comment by mukulgupta2507** [comment]
Hi,

Just want to know, did anyone got a chance to take a look at this ?

Thanks

**Comment by eddiemonge** [comment]
This was answered on SO
