### ISSUE TITLE
bug: $state.go doesn't update the URL when used in a form ng-submit.

### ISSUE THREAD

**Issue by renesansz** [angular-ui/ui-router#2145]
**Type**: bug

<span ionic-description>I have a form with ng-submit functionality. **The problem is that upon form submit `$state.go` doesn't update the URL of the app but it transitions the page to the next page.**
But when being used by `ng-click` it works properly.

I know `ui-sref ` would do, but I'm kind of exploring other possible approach and another reason why I chose this approach is that I can make use of `required` attribute for form inputs.

Here's my [sample code](https://gist.github.com/renesansz/6e52fd4098771eb9d92d).</span>

**Comment by eddiemonge** [comment]
you might need `reload:true`

**Comment by renesansz** [comment]
cool, that helps! Thanks!
Going to close the issue now.
