### ISSUE TITLE
resolve is always called with notify:false

### ISSUE THREAD

**Issue by davideicardi** [angular-ui/ui-router#2146]
I want to change the state without reloading the controller. All seems to work fine except that my `resolve` function is always called.

To change state I use:

    $state.go("home", {param1:"changed" + changes++}, { notify : false});

Here my plnkr: http://plnkr.co/edit/jo3C56ZwkPE27FtRU1Y6

Basically I log each time the controller is loaded or the resolve is called, then I added a button to change the state. As you can see resolve is always called also with notify = false.

What do you think? My problem is that inside the resolve I load some resource and I want this code to be called only when really changing state, not when changing state using `notify=false`.

I use version ui-router 0.2.15 and angular 1.4.3.

**Comment by eddiemonge** [comment]
Does seem like a bug

**Comment by davideicardi** [comment]
Thinking more about this...`notify` is documented as: 

>  If true will broadcast $stateChangeStart and $stateChangeSuccess events

Documentation doesn't mention nothing about controller and resolve feature. 
My goal is to change the state (logically and also changing the location) without reloading the controller and without calling the resolve method again. Is the `notify:false` the right approach?

thanks

**Comment by davideicardi** [comment]
Looking at the code I have a possible solution, here my fork+commit: https://github.com/davideicardi/ui-router/commit/7198aa2b3618f11b376949a80e2b7c4c6640cd4c

Basically I have checked the notify options inside shouldSkipReload function. I have also added a unit test. (don't know why there are also other CRLF changes...).
If you want I can create a pull request.

Eventually I have also a workaround, [http://plnkr.co/edit/hz3f7qORaHFZyiwHDZo7?p=preview](plunkr). I have added a custom "resolve" params and use it as an option to check if calling or not the resolve functions. So I can call the $state.go like this:

    $state.go("home", {param1:"changed" + changes++, resolve: false}, { notify : false});

But I don't like this solution, seems to be just a workaround.

What do you think? I'm not sure what is the right approach...

**Comment by PhiLhoSoft** [comment]
Seems related to #2108 and #2087

**Comment by eddiemonge** [comment]
#2108 has the controller reinitialize when changing to a different state. This has the resolve fired but not the controller so its slightly different.

**Comment by nateabele** [comment]
> Documentation doesn't mention nothing about controller and resolve feature.

Right... that's because it's totally unrelated: `notify` is _only_ about events. Why is this confusing?

**Comment by davideicardi** [comment]
My final goal is to change the state and browser URL (actually I just need to change a state par) without reloading the controller or calling the resolve. What is the best solution for you? I just don't understand how to solve my problem.
Thanks!

**Comment by eddiemonge** [comment]
Why?

**Comment by davideicardi** [comment]
Basically I have backoffice application where the user can add new articles. So I have a state like "/stories/{id}".
When the user want to create a story I go to "/stories/new". He fills some fields and the using an autosave feature (more or less like Google doc) the story is saved and I assign it an I'd. So I want to change the state and go to "/stories/57543", but I don't actually need to reload anything.
Maybe there is another solution?

Thanks

**Comment by eddiemonge** [comment]
Plenty of ways to replace the url but the original issue is still valid: 

> resolve is always called also with notify = false

**Comment by davideicardi** [comment]
Thanks Eddie but what do you suggest for changing url? 

For me it should be some ui-router feature, something like:

    $state.go("mystate", { reload: false })

or

    $state.change("mystate")

In my opinion is a state change just like any other, the only problem is that the user is actually already in this state (all the required data are loaded) so I just don't want to reload anything.

**Comment by eddiemonge** [comment]
`$location.path()` with a $locationChangeStart set to preventDefault?

**Comment by nateabele** [comment]
Yeah, see the example with the `sync()` method here: https://angular-ui.github.io/ui-router/site/#/api/ui.router.router.$urlRouter

**Comment by orangesoup** [comment]
@nateabele Shouldn't the example use `$locationChangeStart` instead of `$locationChangeSuccess`?

Also, it's not helping regarding the url change imo. If I don't use `sync()` the url won't change, but if I use it, it will just open the state fully, not just updating the url.

**Comment by calebeno** [comment]
@nateabele I've been working on a project and having a similar issue as that discussed here.  This is my use case:  When transitioning to a state, a resolve block is completed.  Once in the new state, a component determines whether or not the url needs to be changed.  The goal is to remain in exactly the same state, but to modify the url.  However, when I make the url modification using something like this:

`$state.go($state.$current.self.name, {newparams}, {location: 'replace', reload: false, notify: false});`

The entire state remains the same and the url is updated.  However, the resolve block is the called again.  Is it not possible to prevent the resolve block from running?
