### ISSUE TITLE
TypeError: Cannot read property 'nodeName' of undefined

### ISSUE THREAD

**Issue by zeeshanjan82** [angular-ui/ui-router#2151]
I get this error on the following line in the ui-router library
   var isForm = element[0].nodeName === "FORM";

Actually I am using ui-sref="statename" on my anchor tag.

**Comment by eddiemonge** [comment]
Can you post an example of this to plnkr.co please?

**Comment by zeeshanjan82** [comment]
I am not sure about this issue, actually I am using dynamic states which are then lazy loaded and was getting this issue there. However I am not able to reproduce this issue. I have also noticed sometimes that when there is any issue or something is wrong with the module whether its in config or when defining routes using ui-router, I am not able to navigate to that state and also do not see any error in the console. This issue is more frustating for me as I have to then carefully look into each line of code in order to understand what am I doing wrong. I am not sure how to really make a plunk of this.

**Comment by eddiemonge** [comment]
```
$rootScope.$on('$stateChangeError', 
function(event, toState, toParams, fromState, fromParams, error){ ... })
```

**Comment by zeeshanjan82** [comment]
Ahh! Thank You. I really appreciate.
