### ISSUE TITLE
Version without urlRouter

### ISSUE THREAD

**Issue by paysdoc** [angular-ui/ui-router#2152]
Hi, I work for a client that has a number of angular components (maintained by different teams) running on their web page. Some projects (including the one I'm working on) would like to use ui-router but a concern is that if everybody starts using the urlRouter the routing will turn into chaos. The guys maintaining the build system (which makes libs available to projects) have therefore blocked ui-router even though they concede that the state machine offered would be very useful. 

Is there a way that the urlRouter can be disabled (or the use thereof prevented) in such a way that we could use the state machine and store the states in browser history without modifying the URL?

(I should note that yes, you could ask project teams nicely not to use the urlRouter, but confidence is low that that request will always be honored, especially in future when staff turnover dilutes internal company knowledge)

**Comment by eddiemonge** [comment]
You could always do a custom build but it sounds more like you need to work on your inhouse policies to me :grinning:
