### ISSUE TITLE
States with the same url doesn't work correctly

### ISSUE THREAD

**Issue by van-nguyen** [angular-ui/ui-router#2153]
States with the same url, in v0.2.14, it goes to the correct state as defined. However, in v0.2.15, it will only transition into the state that was defined first in the code. Hope this makes sense.

Cheers.

Edit:
Here is a quick plunker: http://plnkr.co/edit/vNF4BVFLieQfeNwQVn7F?p=preview

**Comment by ktulufrozen** [comment]
I have a similar situation. I just upgraded from v0.2.11 to v0.2.15 and the transition to a state with no url parameters does not work correctly anymore.

I have a state declared like this

    states.entityDetails = {
                name: 'Details',
                parent: states.entity,
                url: '/details/{entityName}/{entityId}?detailsParams',
                views: {}
    };

and a child state like this

    states.entityDetailsPicker = {
                name: 'entityDetailsPicker',
                parent: states.entityDetails,
                params: {
                    language: {},
                    companyName: {},
                    entityName: {},
                    entityId: {},
                    detailsParams: {},
                    params: {},
                    objectEntityId: {},
                    objectEntityType: {}
                },
                views: {}
    };

The child state does not have any url parameters, it declares all the parameters from its ancestors plus some additional ones. Until v0.2.11 transitioning from state `entityDetails` to `entityDetailsPicker` worked just fine. Now the transition goes to the same `entityDetails`.

Is this a new intended behavior?

Thanks!

**Comment by ktulufrozen** [comment]
I checked if this works in the versions in between and this doesn't work anymore on any version after v.0.2.11

**Comment by van-nguyen** [comment]
Here is a quick plunker: http://plnkr.co/edit/vNF4BVFLieQfeNwQVn7F?p=preview

If you click About, then click link it works okay because the state is defined first. However if you click contact and click link, it reverts back to the first parent state.

**Comment by van-nguyen** [comment]
@christopherthielen any progress on this? Thanks.

**Comment by christopherthielen** [comment]
@van-nguyen after further review, I don't think this is a bug.   States and URLs should be bi-directional. What do you expect to happen if a user refreshes the page while on the url "/popup"?

I think you have three options: 

* Declare your popups/modals with no URL: http://plnkr.co/edit/UUpg9mPc4GTHgFOsHBj2?p=preview
* Don't use an absolute url for the popups; use, e.g.,  "/about/popup" 
* If you want a "global popup/modal", you might use ui-router-extras sticky states http://plnkr.co/edit/qgt0RkEnXDPDTdMJPIfy?p=info

**Comment by christopherthielen** [comment]
@ktulufrozen I think your issue is different, but I'd need a plunk to play with.  Note that params have changed significantly since 0.2.11 (read all the release notes).  Also note that you should not re-declare params from parent states to attempt to gain access.  I usually share data with children states using a `resolve`.

**Comment by van-nguyen** [comment]
@christopherthielen Sorry I'm still not convinced.. why does it work for 0.2.14 and not 0.2.15? Is there a change overall or a check was missed somewhere?

Cheers,
Van

**Comment by christopherthielen** [comment]
@van-nguyen An assumption of ui-router is that a url should map to one and only one state, in a deterministic way (i.e., first one in wins). So we definitely don't explicitly support your state setup.  That said, if you can get this to work *cleanly* and without breaking anything else, I'd be happy to merge a PR

**Comment by van-nguyen** [comment]
Thanks @christopherthielen I will get right on it. In a real world scenario, I wouldn't have all of them as /popup, it would be /signup and /login etc. which I want them to deep-link, when the user refreshes it should open popup e.g. /signup with the homepage as the "base" parent state. Ideally I would want ui-router to be smart enough to "detect" the parent state when transitioning when dealing this behaviour to go into the right popup state.

**Comment by christopherthielen** [comment]
Did you follow my links?  Check out sticky states modal example from UI-Router Extras.

We've discussed having substates that can float (like /signup) but haven't gotten it implemented yet. Your scenario still has the problem that urls don't map cleanly to a state.  If a user deep links to /signup, what "base" state do you expect to load?  All you know is the url.

**Comment by van-nguyen** [comment]
It would be the first one defined, e.g. the home page.
