### ISSUE TITLE
Modular states?

### ISSUE THREAD

**Issue by EnigmaticCode** [angular-ui/ui-router#2155]
Hey,

Right now the code looks similar to the example below, except more states, params, and resolve definitions, in one big file.  I would like to modularize this so the code is more manageable ( and unit testable ).  Is there a suggested / supported approach to this problem?

According to the documentation, you can pass an alias for a service to each resolve property.  Unfortunately, it looks like it calls the service once and uses the returned value for every subsequent result.  Maybe i'm using it incorrectly?

Just FYI, I'm using babel.

```javascript
$stateProvider
    .state('catalog.details', {
        url: '/catalog/{id}',
        params: {
            id: [function () {
                // Returns default id
            },]
        }
        resolve: {
            categories: [function () {
                // Does stuff, returning promise
           }],
        }
    })
```

**Comment by nateabele** [comment]
This is a question for StackOverflow, but there's really nothing preventing you from breaking your state definitions out as plain objects and asserting against them directly. Otherwise, you can do `inject($state => { ... })`, do your transitions, and assert the results.

**Comment by EnigmaticCode** [comment]
Hey Nateabele,

You're right, maybe this is more for StackOverflow.  I posted it here specifically to ask about aliases for resolve.  It looks like the below is supported according to the documentation.  However, it seems to run the service and use the return results of the service as the value.  It doesn't do it everytime a transition happens.

It could also be a lack of understanding.  If you don't mind, could you further explain "inject($state => { ... })"?

```javascript
angular.module()
    .config(function () {
        $stateProvider.state('category.details', {
            resolve: {
                categories: 'categoriesService',
            }
        })
    })
```
