### ISSUE TITLE
Is there a way other than 'Dot' notation to define the state in Angular ui-router

### ISSUE THREAD

**Issue by KaushikDebsharma** [angular-ui/ui-router#2156]
Recently on of my client asked to use '#' notation instead of 'dot' notation to define states.
but i am not getting any documentation regarding the same.

**Comment by van-nguyen** [comment]
Make a function that replaces hashes with dots?

**Comment by KaushikDebsharma** [comment]
No,
$stateProvider
 .state("main.product", {
           controller: 'dataController',
           parent: 'main',
           url: "/product",
           templateUrl: '/product.html'
       })
actually is there anything as such that i can define the state name as 'main#product' or '#product' instead of 'dot' notation?
i am just curious to know as i came up with a requirement where it says how to use '#' notation in place of 'dot' notation while defining state name.

**Comment by eddiemonge** [comment]
Why do you want to do this?

**Comment by KaushikDebsharma** [comment]
Yeah tats true, but is there any way i can specify parent child relation with hash tag instead of dot.
actually client asked us to use hash notation instead of dot notation.
as of now i cant see anything exists.

**Comment by eddiemonge** [comment]
But why? Just say no and use the dot. There is no reason not to that I can see. If there is a valid, legitimate reason, please do share it.

**Comment by KaushikDebsharma** [comment]
Yeah sure. We are trying to figure out the reason.

**Comment by guogenfang** [comment]
I think it should be defined by the bottom layer.
