### ISSUE TITLE
Trailing slash being appended to urls on page load?

### ISSUE THREAD

**Issue by Findiglay** [angular-ui/ui-router#2158]
I was setting up a new project today and came across a strange problem I've not encountered previously.

When navigating between states, everything works as expected. The problem is encountered when refreshing a page at any given state. For some reason, ui-router is adding a trailing slash to every page reload so that, e.g.

**www.app.com/profile** *becomes* **www.app.com/profile/**

This will break my defined routes without trailing slashes, unless I add a rule similar to that given in the FAQ or a **.when('/profile/', '/profile')** condition. This resolves the problem, but I still always catch a glimpse of that trailing slash when I first refresh a page or enter the url, which is less than ideal.

I've worked on other projects with ui-router and have not encountered this problem before. I've cross checked the settings used on those and can't see any difference. I've found old issues here relating to urls breaking when either including or not including the trailing slash, but none referring directly to this behavior of a trailing slash being appended to the end of the url on page refreshes.

As it is now standard to not include a trailing slash at the end of pretty urls, I'm keen to find the source of this issue!

**Comment by eddiemonge** [comment]
How are your states defined? Are you using urlRouter?

**Comment by Findiglay** [comment]
Hi, I've uploaded a copy of my boilerplate code here.

https://github.com/Findiglay/ui-router-issue
https://github.com/Findiglay/ui-router-issue/blob/master/offers/offers.router.js

Here is a plunker using more or less the same setup - http://embed.plnkr.co/VIrrzhesZgIN7SZm7tWq/preview

**Comment by eddiemonge** [comment]
I can't see the trailing slash being added anywhere. Its probably your server adding it in. I would check its redirect rules.
