### ISSUE TITLE
Unable to use array statement with template and templateUrl

### ISSUE THREAD

**Issue by sebastianjonasson** [angular-ui/ui-router#2159]
The following statements below does not appear to work as expected. However, I did get it to work by using templateProvider.

```javascript
.state('app.tpl', {
    template: ['$stateProvider',function($stateProvider) {
        var param=$stateParam.myParam;
        return '<h1>'+param+'</h1>';
     }]
})
```

```javascript
.state('app.tpl', {
      templateUrl: ['$stateProvider',function($stateProvider) 
        var param=$stateParam.myParam;
        return param+'_template.html';
      }]
})
```

I did get it to work by using the templateProvider. But I still would want to be able to provide a dynamic template url for the state.
```javascript
.state('app.tpl', { 
    templateProvider:['$stateParams',function ($stateParams) {
      var templatePath='/public/partials/'+$stateParams.myParam+'.html';
      var element="<div ng-include=\"'"+templatePath+"'\"></div>";
       return element;
    }],
})
```

**Comment by eddiemonge** [comment]
Yes that is correct according to the docs: http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$stateProvider#methods_state

If you are only using params then use templateUrl as the function accepts `param` as its only arg.
