### ISSUE TITLE
UTF8 characters in url

### ISSUE THREAD

**Issue by RobertSasak** [angular-ui/ui-router#2161]
I would like to have a nicer urls by non-escaping all the special characters.
How can I make following url?
http://example.com/#/path/to/øæå 
or 
https://github.com/angular-ui/ui-router/issues?utf8=✓&q=is%3Aissue+is%3Aopen+utf8 
(note ✓  in url)

**Comment by eddiemonge** [comment]
This is more up to the browser. http://stackoverflow.com/questions/6625035/utf-8-characters-in-urls

> Modern browsers show the decoded url in the addressbar, but use the encoded version to send the request

so the encoded is there and its up to the browser to display it

**Comment by RobertSasak** [comment]
Thanks.
