### ISSUE TITLE
Window load

### ISSUE THREAD

**Issue by furyscript** [angular-ui/ui-router#2162]
Hi all,

I've a problem with my directive this is the code:
```javascript
MayApp.directive('scrolly', ['$rootScope', '$timeout', function($rootScope, $timeout) {  
    return {
        restrict: 'A',
        link: function($scope, $element, $attrs) {
            $(window).load(function() {
                $element.scrollToFixed({
                    marginTop: 55
                });
            });
            $rootScope.$on('$stateChangeSuccess', function(event, toState, toParams, fromState, fromParams) {
                event.targetScope.$watch("$viewContentLoaded", function() {
                    $element.scrollToFixed({
                        marginTop: 55
                    });
                });
            });
        }
    };
}]);
```
The problem is that: When I enter in the page  or I refresh it, the plugin (scrollToFixed) works fine. When I enter in the page from state the code not work (there isn't load event and also the $stateChangeSuccess not work, I see that event is fired but not apply scrollToFixed)

Have you a solution? 
Thanks

**Comment by eddiemonge** [comment]
Is this directive applied to the page and never removed? Or is it removed and added? Why dont you listen for $viewContentLoaded directly?

**Comment by eddiemonge** [comment]
@furyscript ^^

**Comment by furyscript** [comment]
Is applied to page and never removed.
The event $viewContentLoaded works fine, but unfortunately scrollToFixed isn't fired or it don't works (I don't know why), therefore with window.load works but if I enter in the page from state it don't work.

**Comment by eddiemonge** [comment]
I think this is better asked on stackoverflow https://gist.github.com/christopherthielen/b3fc0304b737a4bf8ec9
