### ISSUE TITLE
combining ui router, bootstrap carousel and ngAnimate cause carousel not to work

### ISSUE THREAD

**Issue by GenYCoder** [angular-ui/ui-router#2163]
There's seem to be an issue with adding ngAnimate, ui.bootstrap, and ui.router that makes the carousel not responsive. The template is in a separate html file loaded on ui router.

http://plnkr.co/edit/94au4nBDKZ8e6MsdJ8Fi

**Comment by chaitanyaVadlamudi** [comment]
ggfghjklgkl;
