### ISSUE TITLE
Verify state template bindings work in a unit test

### ISSUE THREAD

**Issue by lsiden** [angular-ui/ui-router#2164]
Given a simple state like:
```
 {
  template: '<div>{{ name }}</div>',
  controller: function($scope) {
    $scope.name = 'Fred';
  }
}
```

I'd like to write a Karma-Jasmine unit-test that verifies that when this state is current, the view is rendered as 
```
<div>Fred</div>
```
and not 
```
<div>{{ name }}</div>
```

I think the missing element is that I need a way for the test to provide a <ui-view> for the state to render the template into.  I guess I could do that if I ran such a test in a stand-alone page I wrote myself for that purpose, but I can't figure out how to do that when running the test with Karma.  

Nevertheless, I have not been able to find any example of this, and am wondering whether such a test is even possible.  I have already covered what I want with Protractor (end-to-end), but I still think that there should be a way to test that the controller and template bindings are working properly in a unit-test first.

**Comment by eddiemonge** [comment]
This is a better question for stackoverflow. Yes there should probably be examples for how to write tests for ui-router but there are quite a few guides out there already like this first one I found on google: http://nikas.praninskas.com/angular/2014/09/27/unit-testing-ui-router-configuration/

If you wanted to do a documentation pull request once you find a sufficient answer, we would gladly review and pull it in if its helpful

**Comment by lsiden** [comment]
Yeah, I'm already in communication with Nikas.  I'll try to post what I've
found out to Stackoverflow when I get a chance.  I might also post a PR for
the Readme or a Wiki page on this.

**Comment by pablovargasosorio** [comment]
Hey Isiden, did you find a way for doing that?
That's exactly what I'm trying to do, but my ui-view template is always empty when I compile the view from my UT...
Thanks!
