### ISSUE TITLE
Links on website are incorrect

### ISSUE THREAD

**Issue by jmeas** [angular-ui/ui-router#2165]
To reproduce:

1. Navigate to http://angular-ui.github.io/ui-router/site/#/api/ui.router.util.type:UrlMatcher
2. Click the "View source" button
3. Observe that you see a 404

Potential cause of problem:

Inclusion of `.git` in the URL.

There's probably some build step somewhere that's not differentiating between the location of the git repository itself and the routes to Github's interface to the repository.

p.s. not sure if www issues belong in this repository, or elsewhere. Sorry if this is in the wrong place!

**Comment by eddiemonge** [comment]
I don't get a 404 when viewing: view-source:http://angular-ui.github.io/ui-router/site/#/api/ui.router.util.type:UrlMatcher

**Comment by jmeas** [comment]
Here is a video showing that it is still a problem:

https://cloudup.com/cQOwfLXUKF1

**Comment by eddiemonge** [comment]
Opened an issue at https://github.com/m7r/grunt-ngdocs/issues/164

**Comment by eddiemonge** [comment]
fixed

**Comment by jmeas** [comment]
:+1:
