### ISSUE TITLE
Parse URL to get state

### ISSUE THREAD

**Issue by Deminetix** [angular-ui/ui-router#2166]
Is there a way to convert a url string (eg `/posts/123`) to a state (eg `{ stateName: 'app.posts', stateParams: { id: '123' } }`)

The API we need to interface with returns URLs instead of something more abstract such as states or type/identifier pairs

Simply calling `$location.url(apiUrl)` isn't feasible either as the Ionic Framework handles history internally.

It would be much cleaner to be able to go `$state.parseUrl(apiUrl)` to check if we even support the state before routing to it using `$state.go(...)`

**Comment by eddiemonge** [comment]
> Simply calling $location.url(apiUrl) isn't feasible either as the Ionic Framework handles history internally.

that sounds more like a bug in ionic that should be fixed. You could always use `$window.location = apiUrl`

**Comment by Deminetix** [comment]
Completely missed the mark! My question was whether UI Router makes its internal ability to resolve URLs into states public?

**Comment by nateabele** [comment]
> Is there a way to convert a url string (eg `/posts/123`) to a state (eg `{ stateName: 'app.posts', stateParams: { id: '123' } }`)

Nope, can't think of a way to do this, sorry (although it'll be possible in the new 1.0 version we're working on).

**Comment by christopherthielen** [comment]
#1651 

http://stackoverflow.com/questions/29892353/angular-ui-router-resolve-state-from-url/30926025#30926025

**Comment by nateabele** [comment]
Oh, nice. Totally forgot about that.

**Comment by johnib** [comment]
@nateabele , it's been a year since then.
Is there any stable version of this library that expose this functionality? map a url to a state? (for angular 1).

**Comment by graingert** [comment]
FYI you can get it with:

https://ui-router.github.io/ng1/docs/latest/classes/url.urlservice.html#match

```js
function foo($urlService) {
  const rule = $urlService.match({ path: '/', search: '...', hash: '...' });
}
```
