### ISSUE TITLE
Adding an undefined dependecy makes the app fail silently with no error or warning

### ISSUE THREAD

**Issue by Davidx7** [angular-ui/ui-router#2167]
```$stateProvider
                  .state('anyroute',{
                  	abstract: true,
                  	url: "/anyroute",
                  	templateUrl: "views/content.html",
                  	resolve: {
          		        loadMyService: ['$ocLazyLoad','$rootScope', '$xx', function($ocLazyLoad,$rootScope) {
          		            return $ocLazyLoad.load(defaultLibs)
                		      .then(function() { })
          		        }]
          		    }}
          		)```

$xx does not exist. The app hangs but doesn't fail or trigger angular error

**Comment by eddiemonge** [comment]
From the docs at https://github.com/angular-ui/ui-router/wiki:

> $stateChangeError - fired when an error occurs during transition. It's important to note that if you have any errors in your resolve functions (javascript errors, non-existent services, etc) they will not throw traditionally. You must listen for this $stateChangeError event to catch ALL errors. Use event.preventDefault() to prevent the $UrlRouter from reverting the URL to the previous valid location (in case of a URL navigation).

>  $rootScope.$on('$stateChangeError', 
  function(event, toState, toParams, fromState, fromParams, error){ ... })
