### ISSUE TITLE
Never compare two objects just with === or it will except on a certain moment

### ISSUE THREAD

**Issue by rvetere** [angular-ui/ui-router#2168]
I'm totally new to this project and even to angular. But i have to maintain now a large angular-app for my new job - and so i made my first experience with "ui-router".

The first thing i had to implement is a persistence layer for our own history-states management. So i moved along and just implement a simple localStorage approach to save our states array and load it back again when the user makes a hard-reload in the browser or re-opens the app in our PhoneGap build.

So imagine this case - you load the /home of your app, navigate through some states and - you make a hard-relod.

Now, during the reload, this whole states array will be loaded from localStorage and now - all objects in the array will have new memory addresses... Now i get to the point ;-)

Never compare two objects with just "objectA === objectB" - because internally, all that happens is that the JS interpretor will compare the memory addresses of those two objects.

If the objects are basically the same and you expect a "true" as returned value - it will only be true as long as you're working in the same "context/session".

As soon as something happens that will re-instantiate those objects (localStorage read-back is enough to get there ;)) - even if the object is still the same for you as a human, for the computer it's not anymore...

I'm a little bit concerned after a short search - because i find several points in the code of this project where objects are compared in that way.

You would better make your own compare-functionality, where you invent a kind of a UID for every object you want to compare and afterwards, you compare only those UID's of the object.

Or you ask yourself again "what do i really need to compare here? is there already a property in the involved objects which would be sufficient for comparison? Yes? So then use this instead the whole object...

For now, we're fixing the issue by explicitly passing only the string for the state, and not the whole state-object itself - just to workaround the problematic if in state.js:findState

    if (state && (isStr || (!isStr && (state === stateOrName || state.self === stateOrName)))) {
      return state;
    }

Keep up the good work! All the best!
my two cents..

**Comment by eddiemonge** [comment]
Angular has a solution for this already: [angular.equasls](https://docs.angularjs.org/api/ng/function/angular.equals)

But as for the code here, even though you "saved" the state, once you reload the page, the state is different. It may have the same properties but it is a different object.

Some of this may be gone anyway in the new 1.0 feature branch.

**Comment by rvetere** [comment]
> But as for the code here, even though you "saved" the state, once you reload the page, the state is different. It may have the same properties but it is a different object.

Yeah, that's exactly what i tried to say in my not-so-short issue-description :-)

If there is a solution with angular.equals, why you're not using it? At least we have a workaround so it's ok you closed the issue ;) But theoretically, the problem still exists
