### ISSUE TITLE
How to hide content in the parent view when the user goes to a nested state and show it again when the user backs to the parent state?

### ISSUE THREAD

**Issue by zhekaus** [angular-ui/ui-router#2171]
I’d like to hide some html-content in the parent view when the user goes to child state and show it again when the user backs to parent state. 
What is the right way to do that?

I think using root scope and state change events isn’t a good way, is it?

**Comment by eddiemonge** [comment]
https://gist.github.com/christopherthielen/b3fc0304b737a4bf8ec9
