### ISSUE TITLE
query params with '/' cause state to load twice

### ISSUE THREAD

**Issue by quoideneuf** [angular-ui/ui-router#2172]
This is an issue that appears to only affect 0.2.15.

When the ui-sref directive passes a query param containing a slash, the controller fires twice. The second time the stateParam has the slashes escaped.

Compare the "foo" and "bar" states in this plunker:

http://plnkr.co/edit/IbksnWfy6pY3ipl7S3Qp?p=preview

**Comment by billforward-alex** [comment]
I'll throw onto this issue some sample output from that plunkr.

I am in the Foo state. 
If I navigate to the Bar state… 
`stateChangeStart` and `stateChangeSuccess` fire twice.
```
Start:   home.foo{"param":"here_there"} -> home.bar{"param":"/here/there"}
Success: home.foo{"param":"here_there"} -> home.bar{"param":"/here/there"}
Start:   home.bar{"param":"/here/there"} -> home.bar{"param":"%2Fhere%2Fthere"}
Success: home.bar{"param":"/here/there"} -> home.bar{"param":"%2Fhere%2Fthere"}
```
Note that on the second attempt, it navigates to some URI-encoded version of the Bar state.

I am in the [URI-encoded version of the] Bar state.
If I navigate to the Foo state… 
`stateChangeStart` and `stateChangeSuccess` fire just once.
```
Start:   home.bar{"param":"%2Fhere%2Fthere"} -> home.bar{"param":"/here/there"}
Success: home.bar{"param":"%2Fhere%2Fthere"} -> home.bar{"param":"/here/there"}
```

Curiouser and curiouser.

**Comment by adematte** [comment]
I can confirm this issue appeared in 0.2.15. We had to revert to 0.2.14 for now.

**Comment by ebourgeois** [comment]
Is there an ETA for a fix on this issue?

**Comment by RichardM99** [comment]
I am also experiencing this issue.

**Comment by christopherthielen** [comment]
http://plnkr.co/edit/ET4Q8NpgcC2dTzWp24J3?p=preview
