### ISSUE TITLE
How to create a state that is rendered in the current named ui-view?

### ISSUE THREAD

**Issue by JobaDiniz** [angular-ui/ui-router#2173]
For example, I have tabs and each tab contains a named view:

```
<tabs>
  <tab title="Home">
    <div ui-view="tab-home"></div>
  </tab>

  <tab title="Offers">
    <div ui-view="tab-offers"></div>
  </tab>
</tabs>
```

One tab will always be selected.
Now, I want to define a **search state** such as that when I call `$state.go('search')` the *search template* will be rendered in the *current* tab. So, if my current tab is **home**, *search template* would be shown in the **home tab**. If my current tab is **offers**, *search template* would be shown in the **offers tab**.

Tried the bellow snippet, but when my current tab is *home* and I call `$state.go('search')`, *offers* tab is selected and *search template* is rendered there.
```
$stateProvider
			.state('search', {
				url: '/search',
				controller: 'SearchCtrl as vm',
				views: {
					'tab-home': {
						templateUrl: 'app/search/templates/search.html'
					},
					'tab-offers': {
						templateUrl: 'app/search/templates/search.html'
					}
				}
			});
```

**Comment by eddiemonge** [comment]
I think you need to do this as a directive. How would the browser/router know what tab to put it in if you went directly to `/search`?

https://gist.github.com/christopherthielen/b3fc0304b737a4bf8ec9

**Comment by JobaDiniz** [comment]
Hi... I asked stackoverflow some time ago: http://stackoverflow.com/questions/31977653/ionic-app-with-tabs-global-search-header

Even have a plunker: http://plnkr.co/edit/w7JwxNF140NCSAnGpfnQ?p=preview

Sorry to bother this repository with this issue, but I ran out of ideas... :cry:

**Comment by eddiemonge** [comment]
responded in SO
