### ISSUE TITLE
$stateParams not reset between tests

### ISSUE THREAD

**Issue by pkt-zer0** [angular-ui/ui-router#2174]
Currently, changes to the $stateParams object in one test are visible in another. Example Jasmine test suite to illustrate the issue:

	describe('stateparams', function () {
		var inject = angular.mock.inject;
		var module = angular.mock.module;
	
		beforeEach(module('ui.router'));
	
		it('should be empty', inject(function ($stateParams) {
			expect($stateParams.foo).toBeUndefined(); // WORKS
			$stateParams.foo = 'bar';
		}));
		it('should be cleared between tests', inject(function ($stateParams) {
			expect($stateParams.foo).toBeUndefined(); // FAILS
		}));
	});

Angular normally avoids problems like this one by re-initializing modules before every test case. However, in the case of $stateParams, that does nothing. The $stateParams service is defined as a value(), and will return the same object instance every time it's "initialized".

	angular.module('ui.router.state')
		.value('$stateParams', {});

	// ...should be...

	angular.module('ui.router.state')
		.factory('$stateParams', function () { return {}; });

Defining it as a factory() would solve the issue. Since Angular services are singletons, initialization would still only happen once when running your application normally. Test cases would no longer be forced to manually reset this object, however.

**Comment by pkt-zer0** [comment]
Okay, I created a pull review for this: https://github.com/angular-ui/ui-router/pull/2202

**Comment by wesleycho** [comment]
With #2202 merged, I believe this is now addressed.
