### ISSUE TITLE
controllerAs does not seam to work as expected

### ISSUE THREAD

**Issue by Unitiser** [angular-ui/ui-router#2176]
I was trying to use the controllerAs feature but it doesn't seam to work as expected. It looks like controllerAs is never used. I can access the variable directly.

Here's a simple plunker that illustrates the issue :
http://plnkr.co/edit/u3jaLnvUU25iNJ87Ly8I?p=preview

Did i miss anything?

**Comment by christopherthielen** [comment]
http://bit.ly/UIR-SOF
