### ISSUE TITLE
Cancel media download on page transition

### ISSUE THREAD

**Issue by mahadazad** [angular-ui/ui-router#2177]
Hello guys,
     I am creating a SPA using angular with ui-router, which is basically an audio library. Users can click on audio links and they are moved to a page where there is an audio player playing that file. I noticed that even if the user has transited from the page that playing the audio file to some other page e.g. about page. The browser keeps on downloading the file. Is there any way I can stop this behaviour? Otherwise, it will keep downloading all the files that the user visits.

**Comment by eddiemonge** [comment]
https://gist.github.com/christopherthielen/b3fc0304b737a4bf8ec9

**Comment by eddiemonge** [comment]
It really depends on how you are downloading the file
