### ISSUE TITLE
How to navigate the whole page?

### ISSUE THREAD

**Issue by sunphy** [angular-ui/ui-router#2178]
In my app most url/state are managed by ui-router except one `login`.
 I want the whole page navigated to `login.html` when ajax request got HTTP 401 response(caused by user session expires).
When I use `$location.path("login.html")`,the login page just loaded in `<ui-view/>` section.
How can I conditionally jump out of the ui-router system?
Thanks!

**Comment by eddiemonge** [comment]
Have you tried a hard page redirect, `$window.location = 'login.html`?

**Comment by eddiemonge** [comment]
https://gist.github.com/christopherthielen/b3fc0304b737a4bf8ec9

**Comment by sunphy** [comment]
Looks like not the solution,but still,Thanks a lot!
