### ISSUE TITLE
How to make href same url reload ?

### ISSUE THREAD

**Issue by Coralma** [angular-ui/ui-router#2181]
Hi All,
I'm using the html <a> href link url as menu navigation. But I want to reload the page by same link clicked. So I try the "ui-sref", it works. But all my solution is base on the defined URL to send different parameters. So I wish the href link to support the reload function. Can ui-router support below code ?

< a href="{{subMenuItem.menuUrl}}" ui-sref-opts="{reload: true}">Menu Name</ a>

or are there any other solution for the href URL link reload ? 

Thanks for any help.

**Comment by eddiemonge** [comment]
Use ui-sref with the same ui-sref-opts.

https://gist.github.com/christopherthielen/b3fc0304b737a4bf8ec9
