### ISSUE TITLE
if templateUrl not found, request repeatedly forever.

### ISSUE THREAD

**Issue by prugel** [angular-ui/ui-router#2182]
if templateUrl is not found, 
It request repeatedly forever.

```
  $locationProvider.html5Mode(true);

  $stateProvider
  .state('Home', {
    url: '/',
    templateUrl: 'home2.html',
    title: 'Home'
  });

  $urlRouterProvider.otherwise('/');
```

![request](https://cloud.githubusercontent.com/assets/5827473/9313031/84fa07a6-455b-11e5-8abb-ecd649939339.PNG)

**Comment by NayRia** [comment]
did you do changes for html5Mode in your server  https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-your-server-to-work-with-html5mode

**Comment by prugel** [comment]
Yes I do. I think that is not problem of server side. 
I expected that if templateUrl is not found, ui-router stop to request.
But not.

**Comment by eddiemonge** [comment]
Its probably because you are telling it to go to the home state if it cant go anywhere else and thats where your missing template is. Fix the missing template or add a 404 or something similar state.
