### ISSUE TITLE
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!

### ISSUE THREAD

**Issue by NayRia** [angular-ui/ui-router#2183]
Just yestarday got strange errors.  
Simple project. Route:
```javascript
  function routeConfig($stateProvider, $urlRouterProvider) {
    $stateProvider
      .state('home', {
        url: '/home',
        templateUrl: 'app/home/home.html',
        controller: 'HomeController',
        controllerAs: 'home',
        data: {
          requireLogin: true
        }
      })

      .state('main', {
        url: '/main',
        templateUrl: 'app/main/main.html',
        controller: 'MainController',
        controllerAs: 'main',
        data : {
          requireLogin: false
        }
      });

    $urlRouterProvider.otherwise('/home');
  }
```
and in block .run() : 
```javascript
  function runBlock($log, $rootScope, $state) {

    $rootScope.$on('$stateChangeStart', function (event, toState, toParams) {
      if ( toState.data.requireLogin ) {
        event.preventDefault();
        $state.go('main');
      }
    });

    $log.debug('runBlock end');
  }
```
when i started project with gulp serve, i got error:
```javascript
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.4.3/$rootScope/infdig?p0=10&p1=%5B%5D
    at angular.js:68
    at Scope.$digest (angular.js:15721)
    at Scope.$apply (angular.js:15951)
    at bootstrapApply (angular.js:1633)
    at Object.invoke (angular.js:4450)
    at doBootstrap (angular.js:1631)
    at bootstrap (angular.js:1651)
    at angularInit (angular.js:1545)
    at HTMLDocument.<anonymous> (angular.js:28359)
    at fire (jquery.js:3099)(anonymous function) @ angular.js:12330
angular.js:15954 Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.4.3/$rootScope/infdig?p0=10&p1=%5B%5D
```
But if i change 
```javascript
 $urlRouterProvider.otherwise('/home');
```
 to 
```javascript
 $urlRouterProvider.otherwise('/');
```
 and 
```javascript
url: '/home',
```
to
```javascript
url: '/',
```
the errors disappeared!
Could anyone explain me why this happens. And how to rid of this error ( i still want to use  $urlRouterProvider.otherwise('/home'); )
P.S.
previously i have never had such errors

**Comment by eddiemonge** [comment]
https://gist.github.com/christopherthielen/b3fc0304b737a4bf8ec9

I am not getting that so something else seems to be going on: http://plnkr.co/edit/WXAgql4amURzaKelAL1Y

**Comment by jasperkuperus** [comment]
I have the exact same issue. The solution proposed by @NayRia seems to work for me too. This has always worked properly, until the moment I needed an async check on `$stateChangeStart`, which introduced the need for `event.preventDefault()`.

Another observation: I only get this behaviour on the first (full!) page load. If the page is loaded and you perform a hashbang transition, it does not give this error. This might be why the plunker doesn't seem to show this issue? Same goes for starting in a state that does not trigger the `event.preventDefault()` and entering a state later on that does.

**Comment by tanhauhau** [comment]
After searching the web, the only hack around for this bug is to:  
  $urlRouterProvider.otherwise(function($injector, $location){
      var $state = $injector.get("$state");
      $state.go('home');
  });
Source: https://github.com/angular-ui/ui-router/issues/600#issuecomment-47228922

**Comment by mwangepatrick** [comment]
I had the same problem as tanhauhau above. The fix seems to have worked for me.

**Comment by arseneoaa** [comment]
Thanks @tanhauhau , it worked for me as well

**Comment by alejo8591** [comment]
Thanks! @tanhauhau , it worked for me as well :dart:

**Comment by deki** [comment]
For me too, thx!

**Comment by davequested** [comment]
Thanks @tanhauhau, fixed for me too.

**Comment by branblock** [comment]
Thanks @tanhauhau! Seems to be a good fix!

**Comment by daggeto** [comment]
👍 But still looks like hack. Do anybody have explanation why this happening?

**Comment by shezarsrpm** [comment]
Thanks @tanhauhau! It works fine.

**Comment by allencage** [comment]
Thanks @tanhauhau, I was pulling my hair over this thing! :+1:
