### ISSUE TITLE
is there a way to make the angular-ui-router directive load last

### ISSUE THREAD

**Issue by tawanda** [angular-ui/ui-router#2184]
i have a controller that is dynamically populating ui-sref parameters 

the url does not resolve and i think its because ui-router resolves urls before my controller has a chance to populate the params

after the page loads you can see the html in the end is correct, just that ui-router never got a chance to resolve it 

is it the loading order ? or something else

**Comment by eddiemonge** [comment]
https://gist.github.com/christopherthielen/b3fc0304b737a4bf8ec9
