### ISSUE TITLE
Default Content before Resolution

### ISSUE THREAD

**Issue by ehorodyski** [angular-ui/ui-router#2186]
I'm re-working a website that has a very nested interface requiring several child views. Think of a shopping site, with paging, results and filters. What I'd like to do is render default content for said children views while the results are being resolved from the back-end. However, I can't find a way to insert default content past the first `<ui-view>`, which of course, makes sense.

To get around this, we are currently using `$broadcast` in the child controllers. We moved the resolution out of the `resolve` event into the controller, which is working, but requires us to make all of our directives use `$broadcast` as well, or they don't work since the data isn't loaded before they are. It also seems like a very inelegant solution to the issue.

What's weird, is that when I move the `resolve` function into a child view, neither the parent nor it's siblings views load before the `results` child view loads. I can't understand that whereas I can understand children views not loading before the parent is resolved. 

Is there a way we can work around this? Building in broadcasting into all aspects of our code base seems like an extremely poor practice. Is there a way to show children default content before the parent is resolved, or even render child states' views before their controllers are instantiated?

**Comment by eddiemonge** [comment]
https://gist.github.com/christopherthielen/b3fc0304b737a4bf8ec9
