### ISSUE TITLE
templateUrl: "The content must be served over HTTPS"

### ISSUE THREAD

**Issue by Vayvala** [angular-ui/ui-router#2188]
I use HTTPS. I need to send a `templateUrl` request, **not for a static file**:

     /:lang/content/library/book/:bookId

Here is my `state`:

    .state('book', {
        url: '/:lang/library/book/:bookId',
        controller: 'BookCtrl',
        templateUrl: function(stateParams) {
          return stateParams.lang + '/content/library/book/' + stateParams.bookId;
          // or: 'https://dev.mysite.com/' +  stateParams.lang + '/content/library/book/' + stateParams.bookId;
        }
      });

When I run my app, I get the following error:

    Mixed Content: The page at 'https://dev.mysite.com/en/library/book/4985459864' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://dev.mysite.com/en/content/library/book/4985459864'. This request has been blocked; the content must be served over HTTPS.

How can I send a `HTTPS` request for the `templateUrl` with `ui-router`?

**Comment by scottseeker** [comment]
What was the solution?

**Comment by kumarStoryboard** [comment]
please help I am not able to solve this same problem. I am new to angularjs.

**Comment by scottseeker** [comment]
I ended up finding a gulp plugin that compiled the templates into .js files.  Don't remember the name exactly, but this removes the needs to make a http request to fetch the template.

**Comment by kumarStoryboard** [comment]
For me it was a server problem and once I reconfigured the apache server with new installation it worked fine. Thank you for your help @scottseeker.
