### ISSUE TITLE
Directive on ui-view is destroyed & re-linked on state-change

### ISSUE THREAD

**Issue by rubenswieringa** [angular-ui/ui-router#2189]
**In short:** When you have a directive on a named ui-view element, then the directive will be destroyed and re-linked when navigating to or from a state that absolute-references that named ui-view.

**Setup:**
- A html-file with two (sibling-) ui-views; one default, one named
- A custom directive on the named ui-view element
- Add 2 simple states that only use the default ui-view
- Add 1 state that uses the default ui-view _and_ absolute-references the named ui-view

**Steps to reproduction:**
- Navigate to one of the ‘simple’ states
- Navigate to the state that references the named ui-view
- Navigate back to one of the ‘simple’ states

**Expected behavior:**
**›** The custom directive on the named ui-view element should be linked at the start of the application, and in this scenario not be destroyed (ever)

**Actual behavior:**
**›** The custom directive is destroyed (eg its `$destroy` callback is called) and linked (`link()` is called) when navigating to or from a state that absolute-references the named ui-view. When navigating between the 2 simple states, this doesn't occur.

**Plunkr:** http://plnkr.co/edit/pFKLCnYPoRXbaAkPL4uM?p=preview _(let me know if you'd rather read normal, non-coffee javascript)_

**Comment by chilversc** [comment]
Another side-effect of this problem is that `jQuery.cleanData` is run after linking the second scope, but before any watches set up by the link have fired. This causes interesting errors if using things like jSignature if you try and use them in the watch.

http://plnkr.co/edit/1pbKhsDZtGaC4MNyFOJy?p=preview

**Comment by jiverson** [comment]
+1 This is odd behavior and can be nasty in some situations.

**Comment by demsey2** [comment]
+1

**Comment by tastycode** [comment]
+1 Also experiencing this..

**Comment by chrisfosterelli** [comment]
This is pretty counterintuitive to the idea that a link function should only run once. For anyone who is doing any sort of "one time setup" for a directive in their linking function they now have to implement some way of detecting if it's already been ran or not.

**Comment by dracula92107** [comment]
+1

**Comment by eduardolagares** [comment]
+1
