### ISSUE TITLE
$state.go not work on IE11

### ISSUE THREAD

**Issue by hjzheng** [angular-ui/ui-router#2190]
I want use $state.go method to redirect view, Chrome and firefox is fine, but not work on IE11.
![q -20150819163834](https://cloud.githubusercontent.com/assets/4166657/9352067/d53fd192-4690-11e5-90d0-b029036a9c81.png)

**Comment by hjzheng** [comment]
sorry for this

**Comment by aelshamy** [comment]
@hjzheng what was the problem and how you manage to fix it ?

**Comment by hjzheng** [comment]
give the simply code for the question:

**html**
```html
...
<a href="#"  ng-click="linkClick(label)">Resources</a>
...
```
**js**

```js
$scope.linkClick = function(label){
  ...
  //do something 
  ...
  $state.go(...);
}
```

In IE11, When I click link, I found aways go otherwise route path (`$urlRouterProvider.otherwise("/clusterView")`), but other browsers are fine. 

When I change html, It's OK on IE11.
```html
...
<a href="javascript:void(0)"  ng-click="linkClick(label)">Resources</a>
...
```

**Comment by manishkumar-dsi** [comment]
Hi.
We are also facing the same issue. But we have a form and on ng-form submit it redirecting properly in Chrome but not in IE 11. Please suggest.

**Comment by aleksandrmaksimoviclt** [comment]
$scope.linkClick = function(label){
  ...
  //do something 
  ...
  event.preventDefault(); <---- Have you tried to block default behaviour of clicking on link ?
  $state.go(...);
}
