### ISSUE TITLE
ui-router does not allow use of mixed template tags

### ISSUE THREAD

**Issue by derekrjones** [angular-ui/ui-router#2195]
We have an app that does server-side templating and client-side with angular. There was a conflict with templates that need both server-side and angular templating, so we changed the templated tags for angular templates using `$interpolateProvider.startSymbol` and `$interpolateProvider.endSymbol` .

For our other components we use the normal '{{' and '}}' form and this has worked fine because Angular internally uses denormalizeTemplate function which converts '{{' and '}}' into the provided startSymbol and endSymbol. This is essential otherwise third party angular components would not work. 

ui-router does not allow the use of '{{' and '}}' with templates that are set in a states template property, it must be missing this compile step.

the current workarounds are to 
(1) wrap the template and controller in a component ie. `template: '<my-component/>'` (a component property would be nice!)
(2) use the alternate template tags in our views, which we wish to avoid outside of server templated responses

**Comment by eddiemonge** [comment]
Kind of confused what you are asking for here. Can you post a plnkr example demonstrating please

**Comment by derekrjones** [comment]
http://plnkr.co/edit/Rhd8Am?p=preview

This appears to be an angular issue as only directives allow mixed template tags. So ui-router is behaving consistently. I never noticed this before since I don't use ng-include.

+1 for #1989 Feature: Route to Component Directive
