### ISSUE TITLE
History State Generator Injection

### ISSUE THREAD

**Issue by SirDarquan** [angular-ui/ui-router#2197]
Currently the urlRouter uses the $location service to deal with some of the ui-router state transitions. The replace property on the transition options object is used to determine if the $location.replace() method is called but we don't have a way to use the $location.state() method. I don't believe exposing that in the transition options object is a big deal and would allow us to better handle certain navigation situations. The problem with this approach is that we'd have to attempt to come up with a sane way of handling a variety of situations including how to make it dynamic while defined in the HTML.

A better approach would be to add a generator check. So what we'd do is create a function that will return a value that is to be inserted into the $location.state() method only when ui-router is used to invoke the transition. During the configuration phase we'd set the function to the urlRouter with a method something like urlRouterProvider.setStateGenerator(callback(toState){}). Then when ui-router goes to change the url, it can do something like this:

``` javascript
$location.url(url);
if(options.replace) $location.replace();
if(Html5Mode && _stateGenerator) $location.state(_stateGenerator(toState));
```

While I don't have a use for passing in the toState, I added incase others could find a use. In this overly simple use case, I would have an integer returned from the _stateGenerator function that would be incremented by 1 each time it's called. Going to the application on the first page would call the generator and place a '1' in the state. Clicking an ui-sref link would have the next page have a state of '2'. Clicking a button that then calls $state.go() would place a '3' in the state. I can click the browser back button and since the ui-router system did not initiate the location change the generator would not be called but the browser would retrieve the '2' placed in that state. Now I can see that this was a backwards navigation. If the browser forward button was pressed at this point, the '3' would be retrieved and I can see this is a forward navigation. Even if the user used the browser back dropdown and skipped multiple entries, I can still determine which direction the the navigation occured. Of course there are other more advanced scenarios where we can somehow use the state to keep track of how deep the user has gone into the application or whatever or even store the ui-router state in the history state and use that for animation purposes.

**Comment by eddiemonge** [comment]
Out of curiosity, have you looked at the feature-1.0 branch yet?

**Comment by nateabele** [comment]
> [W]e don't have a way to use the $location.state() method.

This method was added in 1.3.x. UI-Router currently supports Angular back to 1.0.x, so this would not be possible till post-1.0.

**Comment by SirDarquan** [comment]
@eddiemonge No I have not looked at the 1.0 branch yet. 
@nateabele So it's not possible to test if the $location service has the state method and don't use it if it's not there out even better to create a mock function and always execute that? For instance
```javascript
var locationStateFn = $location.state | function(){};
if(_stateGenerator){
    locationStateFn (_stateGenerator());
}
```

I accept I may be over simplifying this a bit and if I am, I'm sorry.

**Comment by nateabele** [comment]
@SirDarquan Might work. Sounds like a great opportunity for a community contribution.

**Comment by SirDarquan** [comment]
I had more time to think about it and realized it wouldn't work because the `$location.state` method is always defined. You would have to examine if the browser supported the history api rather that determine if that method existed
