### ISSUE TITLE
resolve freezes on a rejected promise

### ISSUE THREAD

**Issue by bingomanatee** [angular-ui/ui-router#2204]
it seems that if the resolve function returns a promise it waits for the resolution of the promise before executing the page. However, if the promise is rejected it hangs indefinitely. What is the expected behavior of a route with resolved promises that are rejected?

**Comment by nateabele** [comment]
If a resolve promise is rejected the transition is rejected. In does not hang indefinitely. Please see StackOverflow for help and support questions.

**Comment by bingomanatee** [comment]
What if there isn't any transition because it's the first page on the site?

**Comment by nateabele** [comment]
There's still a transition that's triggered from the root state to the initial state that matches the URL on page load.
