### ISSUE TITLE
Consider making onEnter fire even when moving up

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/ui-router#2205]
So due to my nightmare that is currently default children, and even with ui-router 1, I think there are still some frustrations I expect to encounter.

After discussing with a new eng at my company, he's pointed out that in a more traditional state-machine, if you go to a state (like going from `parent.child` to `parent`) you would traditionally execute all the logic on the `parent` state. However, since this is superfluous for a webapp, we currently have NOTHING re-firing on the state unless you explicitly do a reload: true OR if you use the new resolve policies.

I believe that this is still not addressing the problem. You don't actually want resolves to re-execute, because you want to retain the data you already have. However, you DO want to possibly re-evaluate entrance logic (using the resolved data).

My proposal is this:

Fire `onEnter` if you go directly to a state, even if you're going up. You can inject something about the $state or $transition to determine if you were directly accessing the state, or perhaps inject another flag that specifies if the state re-resolved or not (?). This would allow me to perform logic every time you visit a state, either the first time or subsequent times, even though it's already loaded.

The fact that you can transition to a state but cannot evaluate ANYTHING or execute ANYTHING within this state's definition simply does not conform to what a traditional state machine would entail.

Additionally, it would be nice if performing a `$state.go()` or some other redirect didn't just crash everything. Perhaps this then isn't suited in the `onEnter` callback, but it needs to be SOMEWHERE that has access to resolves, executes every time you open or re-visit a state, and can perform redirects.

Iunno, thoughts? I feel like this would fix a few problems.

**Comment by nateabele** [comment]
> [I]n a more traditional state-machine [...]

Traditional finite state machines are non-hierarchical directed graphs, so this is an apples-to-oranges comparison.

> You can inject something about the $state or $transition to determine if you were directly accessing the state [...]

This is already more than completely addressed by the `$transitionProvider` hooks API in 1.0.

> The fact that you can transition to a state but cannot evaluate ANYTHING or execute ANYTHING within this state's definition simply does not conform to what a traditional state machine would entail.

Again, this isn't a valid comparison per se, but this is already pretty much addressed regardless, even if the logic is not attached directly to the state itself (though there's no reason you couldn't wire something up).

**Comment by ProLoser** [comment]
@nateabele I just mean the controller, resolves and onEnter are not re-executed when moving up the heirarchy. Is there any possible way to do this in pre-1.0?

**Comment by nateabele** [comment]
>  I just mean the controller, resolves and onEnter are not re-executed when moving up the heirarchy. Is there any possible way to do this in pre-1.0?

You're describing a reload (which will take a specific state as a parameter and only reload that state). That's been like that for a while.

**Comment by ProLoser** [comment]
I do not want to reload the state, I merely want to execute a small sub-snippet of logic. I want to preserve my resolves, view and controller.

**Comment by kylewelsby** [comment]
I'm with @ProLoser here,  there are instances when i'm switching states, and I would like a hook to fire when a state has changed even without reloading.  I'm not sure if i have something wrong in my app that is not triggering this event, but I would assume if the view or URL has changed for any child a transition hook should be fired.

**Comment by sandyjoshi** [comment]
Guys any progress / workaround for this ?

**Comment by christopherthielen** [comment]
1.0 has a `onRetain` hook that is fired when a state remains active (not entered exited or reloaded)

**Comment by kylewelsby** [comment]
Transition hooks in 1.0 will solve this.   We upgraded to 1.0 to a load more functionality.
