### ISSUE TITLE
ui-sref-active with non-url parameters

### ISSUE THREAD

**Issue by lucaskerdoncuff** [angular-ui/ui-router#2207]
Hi everyone,

It seems that the ui-sref-active directive is not working when using a non-url parameters.
I have a state defined like this:
```javascript
.state('edit_adv.overview', {
            url: '/overview/:name',
            templateUrl: 'app/adv/overview/overview.html',
            controller: 'OverviewController',
            params: {campaign: null}
})
```
I'm calling it with:
```html
<button ui-sref="edit_adv.overview({ name: campaign.name, campaign: campaign })" ui-sref-active='button-active'>Overview</button>
```
If I remove 'campaign: campaign', the ui-sref-active is working, otherwise it's not ....

Any idea ?

**Comment by christopherthielen** [comment]
Put this in a plunker please

**Comment by eddiemonge** [comment]
@lucaskerdoncuff ^^

**Comment by Kordonme** [comment]
@christopherthielen Here you go: http://plnkr.co/edit/J0MOeu

**Comment by nateabele** [comment]
Yeah, we have at least one or two other issues that refer to the same problem(s).

**Comment by Kordonme** [comment]
Do you know how to fix this? I'd gladly give a hand if possible :)

**Comment by eddiemonge** [comment]
closing as duplicate.

@Kordonme can you try this in the feature-1.0 branch and see if its still occurring there? If so, we could use some help in that area

**Comment by Kordonme** [comment]
Well, I fetched and built the new 1.0 branch and added that js file to the plunkr. Still not working:

http://plnkr.co/edit/J0MOeu?p=preview

**Comment by ClementParis016** [comment]
For anyone still falling into this, you can workaround the issue by passing `$state` to your template and use `.includes()` on `ng-class` instead of `ui-sref-active`:

```js
// in your controller, pass $state to your scope or other view model:
function ($scope, $state) {
  $scope.$state = $state;
}

// in your template, use ng-class and $state.includes():
<a ui-sref="orders({ status: 'closed' })" ng-class="{ 'active' : $state.includes('orders') }">Orders</a>
```

**Comment by canbax** [comment]
Using `includes` function with params is most generic I guess. 

Documentation mentions `includes` 
This use case fits well for me [https://github.com/angular-ui/ui-router/wiki/Quick-Reference#params-v03](url)

**Comment by christopherthielen** [comment]
This seems to work with latest ui-router http://plnkr.co/edit/kUEEWE?p=preview

**Comment by bbuhler** [comment]
@christopherthielen It is not working when you load the "contact" state initially.

See http://run.plnkr.co/preview/cja14lypk0004315s1w9rjuh3/#/about/contact

**Comment by vikasjson** [comment]
Issue: ui-sref-active='active', always the first tab is active along with the selected tab

Code snippet:

uib-tabset(active='activeJustified', justified='true')
        uib-tab(ng-repeat='bucket in $ctrl.buckets' ui-sref-active="active" ui-sref='packages1.index1({ bucket: bucket })' heading='{{bucket}}')
          uib-tab-heading
            span(ng-bind='$ctrl.replaceCharWithSpace(bucket, "_")')
