### ISSUE TITLE
Error on $stateProvider decorator minification

### ISSUE THREAD

**Issue by Prim3591** [angular-ui/ui-router#2210]
Hello everybody,

I have this code :

```
$stateProvider.decorator('$state', function (state) {
    state.views = angular.extend(state.views, {
        'navbar@': {
            templateUrl: 'partials/navbar.html',
            controller: 'NavbarController'
        }
    });
});
```

This doesn't work after minification and I would like to have this code (as in angular $provider) : 

```
$stateProvider.decorator('$state', ['$delegate', function (state) {
    state.views = angular.extend(state.views, {
        'navbar@': {
            templateUrl: 'partials/navbar.html',
            controller: 'NavbarController'
        }
    });
}]);
```

As we can see in https://github.com/angular-ui/ui-router/blob/a7d25c6/src/state.js#L345, the decorator only allow a function as second parameter, it would be great to have an array like in : https://docs.angularjs.org/api/auto/service/$provide#decorator.

Or is there another way to do it ? 

Thank you a lot :heart:

**Comment by eddiemonge** [comment]
@christopherthielen is this rewritten in 1.0 or something that can be added?

**Comment by christopherthielen** [comment]
This is not any different in 1.0 AFAIK. This would be a breaking change

**Comment by wesleycho** [comment]
I think this would be an ok breaking change - what are the thoughts?

**Comment by nateabele** [comment]
The idea being, inject the parent function as `$delegate`?

**Comment by christopherthielen** [comment]
A couple things are surprising about this request. 

1. The first parameter "$state" isn't an existing state builder function. I didn't know we allowed "decoration" of undefined builder functions. I don't think that is actually supported. 

2. I can't see why the first example would fail after minification. We don't inject anything for decorators, the parameters (state and existing fn) are normal function call params. 

I don't think the proposed decorator mechanism is better than the existing one, unless additional services will be injected for use in the builder function. (Which the proposal example didn't demonstrate)

I would lean towards not changing this unless a better case is made. 


Can we get more details about why minification breaks the example?

**Comment by christopherthielen** [comment]
Also, if I understand the example's intent, it could be implemented by defining the one view on a parent state, which is simpler and less opaque.  Decoration of the state builder would not be necessary.

**Comment by nateabele** [comment]
Alright, I _thought_ this looked a little fishy. Glad it's not just me.
