### ISSUE TITLE
possible to replace/overwrite a state definition? (default state being "customized" by another module)

### ISSUE THREAD

**Issue by plong0** [angular-ui/ui-router#2213]
Hey, can't seem to find a clear answer to that question.  But is it possible to simply replace a state definition with a new one?

The use case I have is that one module defines the state, and I'd like to be able to replace that state definition from a different module.  Basically the initial definition is a "default" definition, and I'd like to have the possibility to customize the state from a different module.

I realize that doing this at config time could result in a race condition on which module defines it first.  I looked into the possibility of doing it at run-time, but couldn't get it working.

I can accomplish what I want by creating entirely new states, but I would like to use the same URL from the original state.

**Comment by eddiemonge** [comment]
probably with `$state.get` and then defining the new state. This should be a stackoverflow question though and is probably been answered there.
