### ISSUE TITLE
$stateParams over more instances of same module

### ISSUE THREAD

**Issue by mariolamacchia** [angular-ui/ui-router#2215]
Hi guys, I'm working on a project where there are several angular apps in the same pages, each of them using ui router for changing states.

I've noticed that, when I have two (or more) instances of the same angular app and I change state in one and then in the others, ui router uses the same $stateParams of the last state change over all the modules.

I've created a plunker to simulate that: http://plnkr.co/edit/eR3wcZVGSQsRDM8dSwUe

I solved the problem using an id that is stored inside the root state name in each app, so that $stateParams see them are different states at all. However I think it's worth to have a look at that.

**Comment by nateabele** [comment]
Although we've considered things along these lines in the past, this isn't really a supported use case. We'll keep this around for possible consideration as a feature, but I don't expect it to be addressed anytime soon.

Sounds like a good opportunity for a community-supported extension if others have the time & interest.

**Comment by eddiemonge** [comment]
This more sounds like a bug in Angular that its not separating its own modules
