### ISSUE TITLE
Known breaking changes from 0.2.x/0.3.x to 1.0

### ISSUE THREAD

**Issue by christopherthielen** [angular-ui/ui-router#2219]
# This list is not current.  Please see the [migration guide](https://ui-router.github.io/guide/ng1/migrate-to-1_0#breaking-changes)

#### Breaking changes from 0.2.x/0.3.x to 1.0
- The `$stateChange*` events are deprecated.  The `$transitions.on*` hooks are generally much more powerful.  The events are not included by default, but can be re-enabled by including the `stateEvents.js` file and depending on the angular module `ui.router.state.events` (the `stateEvents.js` was missing in 1.0.0-alpha.1 builds; see #2655)
- Errors thrown during transitions are printed to the console by default.  See `$transitions.defaultErrorHandler()` to customize
- A template is required for all views (we are probably going to revert this one)
- Resolves default to "LAZY" policy (they are invoked when a state is entered, not at the beginning of the transition)
- onEnter/onExit hooks return value is used to modify and/or cancel the transition
- Path parameters are no longer optional by default.
- URL matching is now ordered by most specific to least specific
- Dropping support for IE8 and angular `1.0.x`-`1.1.x`
- `this` no longer binds to the target state in resolves (#2548)
- We no longer export the angular module name `ui.router` as CommonJS default export. CommonJS users  should either `require('angular-ui-router').default`, or use ES6 `import` (#2506)
- Change to "/" handling? 
  - virtuwell app doesn't route with `.when("", "/")`

**Comment by nateabele** [comment]
Closing this since I don't think we're gonna have any other breaking changes. At least not in this release...

**Comment by christopherthielen** [comment]
reopening because I couldn't find this when looking for it.  I added the path parameters BC

**Comment by paol** [comment]
If I may, I would like to suggest you add commit c4fec8c to the list. Technically it was changed in 0.2.16, but it's a breaking change (#2631, #2812) that will affect people coming from 0.2.15 or earlier.

**Comment by christopherthielen** [comment]
agreed it's a breaking change, but it doesn't really belong on this list, does it?  This is also for people migrating from 0.3.1 to 1.0, for instance

**Comment by leosprikryl** [comment]
Is #3208 intentional breaking change? If so, it should be included in the documentation.

**Comment by christopherthielen** [comment]
# Closing this issue in favor of using the [migration guide](https://ui-router.github.io/guide/ng1/migrate-to-1_0#breaking-changes)
