### ISSUE TITLE
ui-router resolve state silently failing on error

### ISSUE THREAD

**Issue by SgtPooki** [angular-ui/ui-router#2220]
When passing invokables to the resolve property for states, if an error is thrown, it gets swallowed by this line: https://github.com/angular-ui/ui-router/blob/65654c3c0fab5fc123d752670841307a23d0f26a/src/state.js#L1429

You can see the simple addition I made to catch the error in this plunker: http://plnkr.co/edit/Vo9tpXIUIwY5Ct5qin4h?p=preview. 

Without the error handler (catch method) for the group of promises, the error is swallowed.

**Comment by eddiemonge** [comment]
This is not a bug but a design and has been discussed in the issue tracker numerous numerous time. tl;dr `$stateChangeError`

**Comment by SgtPooki** [comment]
ok thanks.
