### ISSUE TITLE
ui-sref, html5mode, angular 1.4.4, IE9 issue

### ISSUE THREAD

**Issue by rwwagner90** [angular-ui/ui-router#2221]
When I use ui-sref and html5mode, it does not correctly add in the hash, so the href is `/join` instead of `/#/join`.

It does appear to "try" to redirect to the correct page for the state, as my join page flashes up for a second, but it never actually changes the url, so it appears to redirect back to the root /.

Help?

**Comment by nateabele** [comment]
> When I use ui-sref and html5mode, it does not correctly add in the hash

![I do not think it means what you think it means](https://shoutsfromtheabyss.files.wordpress.com/2013/11/montoya.jpg).

:wink:

Do you mean when you turn HTML5-mode _off_?

**Comment by rwwagner90** [comment]
@nateabele no I meant what I said.

I set html5Mode(true). I'm talking about the fallback for IE9. It doesn't work.

**Comment by nateabele** [comment]
Oh, wow, I completely forgot that was a thing. Honestly I'm really not sure. Most of the hashbang/HTML5 logic is handled internally by `$location`.

**Comment by rwwagner90** [comment]
Well all I know if our original app using angular 1.2.28 and the normal ngRoute worked as expected. If ui-sref correctly calculated the href with the # in it, it would work.

**Comment by rwwagner90** [comment]
I just confirmed it's still an issue when using Angular 1.2.28. `isHtml5` seems to be logging as true for IE9, and it should not be, as it is supposed to fall back, right?

**Comment by nateabele** [comment]
`isHtml5` is set based on the value of `$locationProvider.html5Mode()`, which seems like it only returns whether you've _enabled_ HTML5-mode in your app, not actually whether or not it's _active_.

Unfortunately it doesn't look like the `$location` service exposes anything to even tell you whether you're in fallback mode, and worse yet, it appears to violate CQRS: you can't ask it to generate a URL, you can only ask it to update the URL in the browser.

I'm kind of at a loss as to how to move this forward. We might have to kick it up to the Angular team.

@christopherthielen @eddiemonge @wesleycho Can you guys think of anything I'm not thinking of here?

**Comment by wesleycho** [comment]
Yeah, this probably requires a hook from $locationProvider - maybe having Angular expose a private variable like `$$html5` that is set to a boolean depending on the browser & html5Mode?

**Comment by rwwagner90** [comment]
Could perhaps do a check for `window.history.pushState`?

**Comment by nateabele** [comment]
That's a pretty big worst-practice in Angular land since it's untestable.

**Comment by wesleycho** [comment]
Not only that, but it is sure to cause other defects if we were to monkeypatch that method since it is guaranteed to cause unexpected behavior.

**Comment by rwwagner90** [comment]
It's a better solution than using the wrong hrefs though

**Comment by wesleycho** [comment]
No it isn't, it would cause huge regressions.

**Comment by rwwagner90** [comment]
I don't see this being the huge deal you guys are making it out to be, but I'll take your word for it.

**Comment by nateabele** [comment]
I guess that's a matter of perspectives: you have to deal with your use cases; we have to deal with everyone's. And, frankly, this is the first time this has ever come up.

**Comment by rwwagner90** [comment]
Well most people probably don't care about IE8 or IE9 or, for that matter, IE in general.

**Comment by nateabele** [comment]
Actually, you'd be surprised. IE, and IE8 in particular, account for a nontrivial percentage of our bug reports.

**Comment by wesleycho** [comment]
It's a huge potential problem when talking about a library that is core to routing in many people's applications. Other people may be written code based around certain behavior with `pushState`, or even monkeypatched it themselves - this would be a breaking change of a bad nature for them.

Well-maintained libraries do their best to avoid changes of that nature if they can avoid it since libraries should be as flexible as possible.

**Comment by IainCole** [comment]
I used $sniffer.history, but it's not really supposed to be used "for real" (This is an undocumented "private" service) https://github.com/angular/angular.js/blob/291d7c467fba51a9cb89cbeee62202d51fe64b09/src/ng/sniffer.js

**Comment by nateabele** [comment]
Oh hey! Well that's better than nothing.

**Comment by rwwagner90** [comment]
@wesleycho I understand the concern, and the desire for having the library be flexible, but I would expect ui-sref calculating urls to work correctly for all browsers.

**Comment by nateabele** [comment]
Well yeah. We're not saying it's not a bug.

**Comment by wesleycho** [comment]
We agree it's a bug - the $sniffer approach sounds promising, and sounding likely html5Mode checking will be swapped out for it to fix this. If someone doesn't get to it by tonight, I can file a PR to fix this.

**Comment by rwwagner90** [comment]
Awesome. Thanks for your help guys :smile:

**Comment by rwwagner90** [comment]
I noticed that the release files are not updated with this fix, when might the next release be?

**Comment by nateabele** [comment]
When all these are closed: https://github.com/angular-ui/ui-router/milestones/0.2.16
