### ISSUE TITLE
URL array param with default empty value is left undefined

### ISSUE THREAD

**Issue by AdamSelene** [angular-ui/ui-router#2222]
I'm having an issue with an array state parameter with a default empty value:
- when the param is not declared in the URL pattern (param4 in the jsbin below), the default value is indeed []
- when the param is declared in the URL pattern (param3 and param5) AND when it's absent from the URL (allowed since it's supposed to be optional), then it's initialized to 'undefined' (even worse than being undefined: the parameter is present in the params object but has an undefined value, which prevents me from easily using angular.extend or angular.merge, for instance)

See https://jsbin.com/bebeheciju/edit?html,console,output for example

The problem comes from the arrayUnwrap function in the Type definition, which specifically returns 'undefined' for empty arrays.

**Comment by christopherthielen** [comment]
This does appear to be a bug

**Comment by driver-by** [comment]
I've found how to fix that:
```
// src/urlMatcherFactory.js
function arrayUnwrap(val) {
      switch(val.length) {
        // Was: 
        //case 0: return undefined;
        // Now:
        case 0: return mode === true ? [] : undefined;
        case 1: return mode === "auto" ? val[0] : val;
        default: return val;
      }
    }
```
But there is one test:
```expect(m.format({ param1: [] })).toBe("/foo");```
with the comment before the section
```// empty array [] is treated like "undefined"```

So if we need this behaviour, looks like we can't fix that bug.

**Comment by christopherthielen** [comment]
What happens if you specify a default value of []?

**Comment by driver-by** [comment]
@christopherthielen, I didn't get the point about default value
