### ISSUE TITLE
HAML templates rendered as HTML via ui-router.

### ISSUE THREAD

**Issue by alucardu** [angular-ui/ui-router#2225]
I'm trying to get my app ready for deployment so I'm running some tests with  `rails s -e production` and now I've hit an annoying problem. I use Angular as my JS Framework and I have this as my home state, and I've put my `_search.html.haml` file in the `public/templates` folder

    .config([
      '$stateProvider',
      '$urlRouterProvider',
      function($stateProvider, $urlRouterProvider) {

      $urlRouterProvider.otherwise('home');

      $stateProvider
        .state('home', {
          url: '',
          templateUrl: 'templates/_search.html.haml',
          controller: 'searchCtrl'
        })
      }
    ])

When I visit my homepage the template does get rendered but the output is HTML. My `views/layouts/application.html.haml` is also a HAML file but that gets redered as a HAML file and works as expected.

Also when I put this in my `layouts/application.html.haml`

    = render :partial => "layouts/search"

And put the `_search.html.haml` template file in the `layouts` folder the template gets rendered as HAML.

So it looks like when a template is being called through a Angular state it gets rendered as HTML, while when it's called through a HAML action it gets rendered as HAML.

Any ideas why this is happening?

**Comment by eddiemonge** [comment]
uh this sounds like an implementation problem with how you are rendering things. Should be asked on stackoverflow.

Why are you trying to deliver haml files to the front end though and not the html?
