### ISSUE TITLE
ui-view inside ui-view

### ISSUE THREAD

**Issue by emalherbi** [angular-ui/ui-router#2227]
It is possible to do something like this ?

```html
<div ui-view="others"></div>
<div ui-view="main">
  <p>Hello, World!</p>
  <div ui-view="main-container"></div>
</div>
```

If possible , please provide me an example.

[]'s

**Comment by eddiemonge** [comment]
Thats pretty much how child states work. Take a look at the docs on that. https://github.com/angular-ui/ui-router#nested-states--views

**Comment by emalherbi** [comment]
Tnks @eddiemonge, it's works.
