### ISSUE TITLE
Infinite $digest Loop on $stateChangeStart redirect if state has templateUrl

### ISSUE THREAD

**Issue by filipesilva** [angular-ui/ui-router#2229]
This is a weird error that I've been having on my production app, but found it very hard to accurately reproduce. For now the fix in https://github.com/angular-ui/ui-router/issues/600#issuecomment-47228922 works for me.

You can see the error happening on this plunkr: http://plnkr.co/edit/L8DhCNG7cyipBsBypWg3

The app has secure and unsecure states, defined by some extra data on the state definition. On `$stateChangeStart` I check if the state is marked as secure, and if so, if the current user is authenticated.

If an unauthenticated user is trying to access a secure resource, he gets redirected to the unsecured state.

Upon loading the app, the user is directed to a secured state by default (via `$urlRouterProvider.otherwise`) because he might already be logged previously.

The problem happens here. A user enters the app, the `$stateChangeStart` gets fired, I detect he is not authenticated, call `event.preventDefault()` and `$state.go('unsecure-state')`. This sends angular into a infinite digest loop bouncing back between the secure and unsecured states.

What makes this odd is that it seems to be dependent on the target state having a `templateUrl` instead of an inline template. On the plunker, change the template of the `secure` state from `templateUrl: "./unsecure.html"` to `template: "unsecure"` and infinite digest dissapears.

**Comment by eddiemonge** [comment]
You have to have a state with `url: '/'` defined. Its weird but documented at #2238 
See http://plnkr.co/edit/r6xPdrC7AncxyGGJ4z3K?p=preview

**Comment by christopherthielen** [comment]
Fix coming http://plnkr.co/edit/kXKWHJChSCVf9iBXFE0H?p=preview
