### ISSUE TITLE
Emit $stateChangeError when something bad in $stateParams

### ISSUE THREAD

**Issue by just-boris** [angular-ui/ui-router#2230]
I have a state with json expression in params: 

```js
$stateProvider.state('list', {
        url: '/list?{filters:json}'
});
```
Links with proper valid JSON, like this [/list?%7B"param":"A","param2":"B"%7D](), work well.
But something goes wrong sometimes, and here can be invalid JSON in params,  [/list?%7B%7B]().

I expect `$stateChangeError` event or something like this, but I got nothing, just empty `ui-view`

**Comment by eddiemonge** [comment]
can you provide a plnkr example please?

**Comment by just-boris** [comment]
Of course: http://plnkr.co/edit/oUCYFK?p=preview
When you click on the `good link` you will get proper view. When you click on the `bad link`, nothing happens. I expect some kind of event to handle that case.

**Comment by eddiemonge** [comment]
I get an error: `SyntaxError: Unexpected token b`
![error](https://cloud.githubusercontent.com/assets/127535/9745950/a70b2472-5629-11e5-9448-2d97a3a6ff20.png)

**Comment by eddiemonge** [comment]
that url format is looking for a regex that matches 'json'
http://plnkr.co/edit/k18iFwSL1CjJ8XpkIaPh?p=preview

**Comment by just-boris** [comment]
Well, how can I properly handle that error and don't let appear that in console? 
I expect some kind of `try-catch` while parsing url params in library. Url params is provided directly from user, so we cannot trust them.

**Comment by eddiemonge** [comment]
look at the code i changed in the state definition.

**Comment by just-boris** [comment]
So, the answer is get rid of `json` type and parse it on my land, in controller, for example.
But what the purpose of this type, if it is vulnerable for bad inputs from user?

**Comment by eddiemonge** [comment]
thats not how you define the type. if you want to define a type then you need a param definition. what you have defines a regex pattern
