### ISSUE TITLE
May you load "templateUrl" from $TemplatCache first?

### ISSUE THREAD

**Issue by lonyel** [angular-ui/ui-router#2231]
At fromURL,May you load "templateUrl" from $TemplatCache first? tks.

.like this:

this.fromUrl = function (url, params) {
if (isFunction(url)) url = url(params);
if (url == null) return null;
else {
var t = $templateCache.get(url);
if(t) return t;
return $http
.get(url, { cache: $templateCache, headers: { Accept: 'text/html' }})
.then(function(response) { return response.data; });
}
};

**Comment by lonyel** [comment]
for load temolate from js.

**Comment by eddiemonge** [comment]
If you define the templateUrl then it will pull it from templateCache if its in there.

**Comment by lonyel** [comment]
Oh,yes, thank you,eddiemonge.
