### ISSUE TITLE
re-update state

### ISSUE THREAD

**Issue by kelp404** [angular-ui/ui-router#2232]
Hello,

There are some issue about this commit:
https://github.com/angular-ui/ui-router/commit/48aeaff645baf3f42f5a8940ebd97563791ad9f8

My web has two states for the product page (same url but different templates and resolve).
1. the full page for the product.
2. the pop window at the index page.

I set the `app.product` before `app.index.product`.
If the user type the url enter my web, it will go to `app.product`.
If the user click the link on the index page, it will pop the window (go to `app.index.product`).

After https://github.com/angular-ui/ui-router/commit/48aeaff645baf3f42f5a8940ebd97563791ad9f8. When the user click the link on the index page, it will pop the window `app.index.product` then go to the product page `app.product`. ui-router re-update state again.

``` coffee
# the product page
$stateProvider.state 'app.product',
    url: '/{username:[\\w-]{2,16}}/products/{productId:[\\w-]{20}}'
    resolve:
        isInModal: -> no
    templateUrl: "/views/products/product.html"
    controller: 'ProductController'

# this route is for the pop window of the product page
$stateProvider.state 'app.index.product',
    url: '{username:[\\w-]{2,16}}/products/{productId:[\\w-]{20}}'
    resolve:
        isInModal: -> yes
    templateUrl: "/views/products/product-modal.html"
    controller: 'ProductController'
```

**Comment by eddiemonge** [comment]
Can you put this in a plnkr so we understand completely what you mean?

**Comment by kelp404** [comment]
Hi @eddiemonge 

Here you are http://plnkr.co/edit/GyhxUnWdPdB6PxYo686q?p=preview

When I click product-modal.html it will print this at console.
```
state change success to index.product
state change success to product
```

**Comment by eddiemonge** [comment]
You basically have two states with the same url. I'm not entirely sure what you expect to happen with that. @christopherthielen what do you think should happen here? Or should we not worry about it with 1.0?

**Comment by kelp404** [comment]
Thank you.
This is my website. https://soramarket.com/

Because I want to let the pop window at index page and the detail page have the same url.
But the pop window and the detail page have different template.

**Comment by eddiemonge** [comment]
why do they need the same url?

**Comment by kelp404** [comment]
For user experience.

If user click the product on index page. It will change url but it just pop the window (after the user close the window, he can continue scroll down to view other products).
Then user can copy the url to share.
If there are some on use this url to access, they can view the product.

**Comment by eddiemonge** [comment]
Then whats the popup window for? Why not hide the url on that?

**Comment by kelp404** [comment]
If the pop window has no url, the user can't copy or share the page.

**Comment by eddiemonge** [comment]
But if the url is the same below the popup then they can copy that.

**Comment by kelp404** [comment]
If the user us the url to access my web, it should display the detail page, not pop window.

**Comment by dracula92107** [comment]
+1
