### ISSUE TITLE
Add documentation section about ui router compatibility with angular versions

### ISSUE THREAD

**Issue by balteo** [angular-ui/ui-router#2234]
It would be nice to have a documentation section about the compatibility of the ui router with angular versions. Perhaps a couple of lines or a compatibility matrix...

As of now, it is difficult to figure out which of the angular versions are compatible with the ui router. Is the ui router compatible with angular 1.4 for instance?

**Comment by eddiemonge** [comment]
Its in the [bower.json](https://github.com/angular-ui/ui-router/blob/master/bower.json#L6). Other than that we strive to maintain compatibility with the latest version of angular, which users optimally should as well.
