### ISSUE TITLE
default path does not work when using regexp on google chrome

### ISSUE THREAD

**Issue by CxRes** [angular-ui/ui-router#2239]
When I use a regexp to define url in a state and provide no other state, on starting the application ui-router does not go to the default url (which satisfies the regexp) but instead the application starts at `#/`.

This bug only happens in Chrome or Chrome-like environments (read nwjs) and when one navigates to url of the page without client routing ie like `www.example.com` (It will not occur with `www.example.com#/foo`).

see plunkr http://plnkr.co/edit/XMYI9qxHMHVhDCpMkv2i?p=preview for the code: where it works. It also works perfectly in firefox.

**Comment by CxRes** [comment]
This seems to be a regression in 0.2.15. 

There are no issues in 0.2.13.

**Comment by eddiemonge** [comment]
This seems to work for me on your example
