### ISSUE TITLE
Prevent accessing to a branch instead of a single state

### ISSUE THREAD

**Issue by norbertpy** [angular-ui/ui-router#2240]
In the [documentation][1], you mention a way to prevent accessing a state. But how can I restrict a state and all of its children with that? Specifically, I want to have a `login` state with a lot of children. No children should be accessed if the login condition is not met but I don't want to duplicate the same code for all of them. How's that possible?

I asked a more thorough [question][2] on Stackoverflow. Thanks.

[1]: https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-create-rules-to-prevent-access-to-a-state
[2]: http://stackoverflow.com/q/32552073/4228942

**Comment by nateabele** [comment]
http://bit.ly/UIR-SOF
