### ISSUE TITLE
utm params disappear if not declared in every state's url

### ISSUE THREAD

**Issue by Navgeet** [angular-ui/ui-router#2248]
All kinds of url parameters that are not declared in a state's url simply disappear when we navigate to it.

It is possible to declare these in every state's url beforehand, but that is a very tedious solution. Is there any way to allow undeclared params to remain as it is.

**Comment by IainCole** [comment]
I had a similar issue that I had to do a hacky workaround for, would be nice to not have to do this.

**Comment by nateabele** [comment]
Implement a root state and declare the params on it?

**Comment by Navgeet** [comment]
Still a messy solution, requires me to declare params beforehand, that I've
no use for in my app. They are only used by tracking snippets.


On Wed, Sep 16, 2015 at 11:20 PM, Nate Abele <notifications@github.com>
wrote:

> Implement a root state and declare the params on it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-router/issues/2248#issuecomment-140818275>
> .
>



-- 
Navgeet Agrawal

**Comment by eddiemonge** [comment]
You could add a hook in the stateChange/locationChange events. This is more of an implementation issue than a bug. Try also asking or checking on stackoverflow

**Comment by Navgeet** [comment]
Yes, should have went to SO. Not really a bug.

But I guess many people would face this. Shouldn't this be configurable?

On Fri, Sep 18, 2015 at 12:40 AM, Eddie Monge <notifications@github.com>
wrote:

> You could add a hook in the stateChange/locationChange events. This is
> more of an implementation issue than a bug. Try also asking or checking on
> stackoverflow
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-router/issues/2248#issuecomment-141192152>
> .
>



-- 
Navgeet Agrawal

**Comment by glebmachine** [comment]
So, any news? it's a problem : /

I can't find the way to keep this params..

**Comment by glebmachine** [comment]
Or may you have workarounds for that case?
