### ISSUE TITLE
ui-view autoscrolling issues (again...)

### ISSUE THREAD

**Issue by wlingke** [angular-ui/ui-router#2249]
The behavior I'd like is that anytime a state is changed, the initial scroll position should be at the very top. From all the issues/support forums I've read, the proper solution is:

1) add `autoscroll="true"` to all `ui-view`
2) set `$uiViewScrollProvider.useAnchorScroll();`

However, even when I implement both of these, this only partially solves the problem. If the following sequence occurs:

1) Scroll down Page 1
2) Click link to Page 2
3) Click browser's back button to Page 1
4) Click on Page 3 from Page 1

The result is that Page 3 is scrolled down.

Here is an example: https://ovidlife.com/sell-my-policy - Scroll down to the orange buttons, click the first "Learn More", click browser back button, click second "Learn More". You will see the issue.

Any clue on how to fix this issue?

**Comment by jullian-chavez** [comment]
:+1:

**Comment by nateabele** [comment]
Your example seems to work okay for me. If you need extra flexibility, you can replace `$uiViewScroll` with a custom implementation using `$provide`. We try to keep the issue tracker reserved for bugs and features only. Please take support issues to StackOverflow. Thanks. http://bit.ly/UIR-SOF

**Comment by abbymrs** [comment]
i also encountered this issue, just works for some pages, not all, even i have added autoscroll="true" to all ui-view and set $uiViewScrollProvider.useAnchorScroll();
