### ISSUE TITLE
View naming scheme as it currently stands is pretty wicked

### ISSUE THREAD

**Issue by gsklee** [angular-ui/ui-router#225]
Consider this harmless simple example:

http://plnkr.co/edit/QpnJOECB4RXgrXHB5b69

Seems pretty straightforward right? Two unnamed views, one defined in the parent state and the other in the child state.

Now - let's throw in a third unnamed view. This view cannot be targeted relatively but "absolute name" is required:

http://plnkr.co/edit/Sq7xVAe5JDZkUjbSyJxZ

Okay, so why not specify all the view names in the absolute manner? Mixing relative names with absolute names is weird - just like mixing relative URLs and absolute URLs in your HTML or CSS code - it simply looks like bad code.

This leads us to:

http://plnkr.co/edit/6k4q6xVao0EKBjoRufZ2

Perfect. But now I've figured out that `h2.html` should be better put inside the abstract state, so let's move the definition up:

http://plnkr.co/edit/FgjdJGxKbm6LysLCl4ml

Kaboom - is that an infinite loop I am seeing? What happened?

========================================

There are some wickedness going on here:

* It should still work. If I am understanding it correctly, `'@'` is the outermost unnamed view, `'@h1'` is the outermost unnamed view inside `'@'` that appears under the `h1` state, and `'@h1.h2'` should be the outermost unamed view inside `'@h1'` that appears under the `h1.h2` state.

* If I am understanding it wrong - it means **absolute name** is not "absolute" at all! It's still dependent on which state the view definition resides in.

Either way, this shows that something is wrong with the current naming scheme IMHO. Real webapp contains many, many states and views, and with the naming scheme under this current design, I am encountering some real trouble mapping the states and views properly. And I am structuring my webapp this way because the library authors actively encouraging people to use nested unnamed views.

That being said, I dunno if there is any other way to target an unnamed view absolutely. Using template name is far more sensible to me, but I am not sure if this is possible.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
