### ISSUE TITLE
Minifiable controller definition

### ISSUE THREAD

**Issue by xenoterracide** [angular-ui/ui-router#2253]
I don't see this in the documentation, I'd like to be able to write

~~~
 .state( 'characters', {
            url: '/characters',
            templateUrl: 'partials/characters.html',
            controller: [ '$scope', '$log', function( $scope, $log ) { ... }],
        } )
~~~

**Comment by nateabele** [comment]
Yep, you can do that. What's the problem?

**Comment by xenoterracide** [comment]
I guess that i couldn't find an example in the documentation that specifies the controller like that, so I thought you could't.
