### ISSUE TITLE
Is a state name camelcase?

### ISSUE THREAD

**Issue by JFSolorzano** [angular-ui/ui-router#2256]
This is a question:

When i have the following route

```javascript
$stateProvider.state('contactsList', {
  template: '<h1>My Contacts</h1>'
})
```

Do i use sref like this
```html
<a ui-sref="contactsList">Contacts</a>
```
Or like this:
```html
<a ui-sref="contacts-list">Contacts</a>
```

Also i would like to know about Nested States or whatever the following is:
```javascript
$stateProvider.state('contacts.whatever', {//When do i use that Dot?
  ...
})
```

I would like a simple explanation and maybe a link to the docs that cover that topic.

**Comment by eddiemonge** [comment]
The state name and how you link to is what you type in the state definition. Read the wiki for more info about nested states: https://github.com/angular-ui/ui-router/wiki/Nested-States-and-Nested-Views

**Comment by dragantl** [comment]
The section on state naming doesn't answer the question whether it is recommended to use camel case or not. For example, take state that logically presents `test videos`. Should it be named `testVideos` or `test-videos`? Does ui-router care? Note, it cannot be broken into `videos.test` in this example. Thanks!

**Comment by windmaomao** [comment]
To be honest, in `0.4` version, you can't use `reportHistory` as a parent name, it won't register, but if you use a single word `main`. It works. I don't know if this ever get fixed. We are wondering the same quesiton.

**Comment by mjy78** [comment]
One problem with using dashes (kebab case) for naming your states is that if you wish to pass params to the state in ui-sref you'll hit troubles, because when you try to call a function with a dash in it, the interpreter treats it as a minus operator...

```<a ui-sref="multi-word-state({ param: value })">Clicking me wont won't work</a>```
