### ISSUE TITLE
$state.go with wildcard-states reloads state

### ISSUE THREAD

**Issue by filipbech** [angular-ui/ui-router#2258]
I have a root-state with a wildcard in it that turns the url into a stateparam 

``` js
$stateProvider.state('root', {
  url: '*path',
  ...
}
```

When I try to navigate to a given state with a given path, it loads twice. Looks like it reloads with update stateParams. However, no matter what I set as path in the params, it always reloads. (the controller initiates twice)

``` js
$state.go('root',{path:'/page1'});
```

A work-around is to use `$location.path('/page1')` instead, but I should be able go there with $state.go, right?

**Comment by eddiemonge** [comment]
What version are you using?
