### ISSUE TITLE
Don't generate href when uiSref is abstract

### ISSUE THREAD

**Issue by gligoran** [angular-ui/ui-router#2259]
Hello,

In my menu, I use ```uiSref``` and ```uiSrefActive``` to highlight the current state. Because I've got a multi-level menu, I'd like to be able to highlight the parents as well. The problem is that some of those parents are abstract. While highlighting works, I'm getting errors in the console ```Cannot transition to abstract state 'absState'```. I think ```uiSref``` should not generate any additional attributes if the state is abstract, but it should be available to use in combination with ```uiSrefActive```.

**Comment by wesleycho** [comment]
Couldn't you just expose `$state` on `$scope` and use `$state.includes(stateName)` in the view with ng-class to accomplish this?

**Comment by gligoran** [comment]
@wesleycho: sure I could. I actually do it using the ```includes``` function, but that's just a work-around. It would be nice to be able to just use the ui-sref functionality and not have to differentiate between abstract and normal links.

**Comment by eddiemonge** [comment]
You could always extend ui-sref-active to do this
