### ISSUE TITLE
Overriding previous declarated state

### ISSUE THREAD

**Issue by enapupe** [angular-ui/ui-router#2261]
Hello!
I'm facing a situation where I have a module which is being "extended" by another *app*.
The *app* needs to register a differente `templateUrl`, `controller` and `resolve`. Is this possible? Maybe de-registering a state and registering again?

I took a good look at the docs but couldn't find anything like this. Maybe I'm thinking the wrong way? How do you guys dead with such situations? I have these apps that share the same 'core' and one app needs to change some behaviour.. I'd like to not duplicate any code.
Thanks!

**Comment by wesleycho** [comment]
Perhaps this can be solved on your side by making your state tree configurable via app config.

**Comment by enapupe** [comment]
Yeah.. I guess you are right. I could override the object passed to $stateProvider.. Maybe I'm missing some angularjs dependency knowledge, how would you setup a config situation like this?
Considering that this core module may or may not be overridden..
Thanks a lot for your time.

**Comment by wesleycho** [comment]
I would maybe use an injectable value in both apps with the same name, but in the app that needs to override, have its injectable be the same name so that you overwrite the config completely. Another approach might be to create a provider that requires an object to be passed into a method where the method calls $stateProvider.state there instead of just calling the $stateProvider normally.

I'm closing the issue as a support ticket, but I'm happy to go into detail about this here still.

**Comment by enapupe** [comment]
I think I got it.. but this way I'd have to register a module dependency in the CORE module, right? Otherwise it would run after the CORE module and the state would already be registered. The ugly is that I'm not always having that override.
I'm thinking something like:

`angular.module("app.core", ["app.core.extension"])`

This way the *app.core.extension* `config()` process would run before the *app.core* `config()`, and that works. But I'm not always extending it.. So I'd have to register an empty module just to not break things..

I see this is not an ui-router issue. Thanks for helping anyway!

**Comment by wesleycho** [comment]
One could also use `$injector.has` and `$injector.get` to see the presence of a particular config and use that to extend the current one - there are a lot of options available to you :) .

**Comment by enapupe** [comment]
Well.. I guess I have to take another step into angular's crazy complex API.
Thanks
