### ISSUE TITLE
Can't use offset with anchor tag

### ISSUE THREAD

**Issue by petermikitsh** [angular-ui/ui-router#2263]
I need to navigate from one page to a different, but I need an offset due to a fixed navbar.

So I wrote this code:

```html
<a href ui-sref="theNewPage({'#': 'myAnchor'})" offset="60">Continue</a>
```

It goes to the anchor, but I still need the offset applied.

**Comment by wesleycho** [comment]
Why not write a custom directive that handles this? This is not really UI Router's responsibility.
