### ISSUE TITLE
Feature request: Use a service for entire resolve object

### ISSUE THREAD

**Issue by hackel** [angular-ui/ui-router#2271]
I am trying to keep logic out of my router file, including any dependency resolution logic.  It would be very convenient if I could specify an angular service (as a string) as the resolve value itself, and not just the individual dependency.  I re-use so many of these dependencies throughout my app, it seems redundant to have a bunch of e.g. `resolve: {user: 'userResolver', ...},` objects duplicated in many route definitions.  If I could just specify `resolve: 'userResolver',`, then I can move all of that logic into separate resolve classes that extend from a baseResolver that contains most of my shared resolution logic, or injects it from another service, etc.  It will also allow me to customise the returned resolve object based on $stateParams, which I'm using to decide which controller and template to use, for example.

I'm sure there must already exist some way to achieve this, but this wsa the way that seemed the most intuitive to me.

**Comment by nateabele** [comment]
That's a pretty interesting idea. Off-hand, you could probably add a state builder for resolves to pull something from configuration. In 1.0 there will be a system to build resolves dynamically, so you won't need to set one in configuration at all.
