### ISSUE TITLE
Child state with stateParams will load controller twice even if reloadOnSearch is false

### ISSUE THREAD

**Issue by shavo007** [angular-ui/ui-router#2272]
Hi all,

I have seen a related bug here #125 

Version of ui-router Im using is  "angular-ui-router": "~0.2.15"

Issue is I have two child states with the same url as the parent. When i transition, I want the url updated but i dont want the controller called twice. 

I added in the flag reloadOnSearch: false but still does not work.

```

  .state(STATES.PARENT, {
        url: '/track?id"',
        templateUrl: 'search/search.html',
        controller:'trackSearchController',
        controllerAs: 'trackSearchCtrl'
      })
      .state(STATES.SINGLE_ARTICLE_RESULTS, {
        templateUrl: 'results/results.html',
        reloadOnSearch: false,
        controller:'trackResultsController',
        controllerAs: 'trackResultsCtrl'
      })
      .state(STATES.MULTI_RESULTS, {
        templateUrl: 'results/multi/multi.results.html',
        reloadOnSearch: false,
        controller:'trackResultsController',
        controllerAs: 'trackResultsCtrl'
      })
```

So in the search controller, I transition to either single article or multi based on certain business rules.

Search controller:

```
if(blah){
   $state.go(STATES.SINGLE_ARTICLE_RESULTS);
   $location.search({'id': trackSearchCtrl.trackingId});
} else {
 $state.go(STATES.MULTI_RESULTS);
  $location.search({'id': trackSearchCtrl.trackingId});
}
```

Whats happening is if i search with a different input and the url updates, it calls the parent controller twice.

Any clue?

I attempted a plunker but does not work exactly as i had planned but has the same layout!

http://plnkr.co/edit/VLLGXZ?p=preview

All I want to achieve is to transition to the new state and update the url.

Thanks,
Shane.

**Comment by shavo007** [comment]
i have created a new plunker:
http://plnkr.co/edit/MXZaml?p=preview

i took this from @christopherthielen  plunker on reloadOnSearch.

Effectively, if i have two child states that share the same url as their parent, and update the url param the parent controller is called twice.

This is a major bug. The app i have to work on needs to be AA compliant. On JAWS screen reader, it is reading out the uncompiled template caused by this issue. Even with ng-cloak it still does not work.

This was all working seamlessly before i introduced browser navigation and updating url with each state transition.

**Comment by christopherthielen** [comment]
Targeting post 1.0
