### ISSUE TITLE
Unregister $stateChangeSuccess event listening on ui-sref-active and ui-sref-active-eq

### ISSUE THREAD

**Issue by evanliomain** [angular-ui/ui-router#2273]
[The event listenner](https://github.com/angular-ui/ui-router/blob/a7d25c6/src/stateDirectives.js#L252) on $stateChangeSuccess in `$StateRefActiveDirective` should unregister the event on destroy to prevent memory leak.

Just add this 
```javascript
var unregisterStateChangeEvent =  $scope.$on('$stateChangeSuccess', update);
scope.$on('$destroy', unregisterStateChangeEvent);
```

**Comment by phw** [comment]
Are you sure you have experienced memory leaking here? Destroying the scope should actually unregister all events attached to this scope with `$on`.

You solution would be correct, if instead of `$scope.$on` e.g. $rootScope.$on` would be used.

**Comment by nateabele** [comment]
Yup, scopes detach their own event listeners.
