### ISSUE TITLE
Infinite loop when handling a url that doesn't match a state

### ISSUE THREAD

**Issue by joaquimds** [angular-ui/ui-router#2275]
Here is code that intercepts all state changes and redirects to the state 'state1':

    myApp.run(function ($rootScope, $state) {
		$rootScope.$on('$stateChangeStart', function(event, toState) {
			if (toState.name!=='state1') {
				console.log('redirecting to state1');
                event.preventDefault();
				$state.go('state1');
			}
		});
	});

This works apart from one circumstance: when the app is loaded from a url that does not match a state, so 

      $urlRouterProvider.otherwise("/");

is used, which matches e.g. 'state2'. This then causes the app to loop from state2 to state1 and back again, until angular detects ten $digest iterations and breaks out of the loop.

Expected behaviour is for the app to initially redirect to state2 from the non-existent route, and then redirect to state1.

An example project with this setup is here: https://www.npmjs.com/package/ui-sref-test

**Comment by eddiemonge** [comment]
you shouldn't post those kinds of things to npm. better would be to plnkr

**Comment by joaquimds** [comment]
Sure, except the bug is to do with url-rewriting, which I don't *think* you can show with plnkr.

**Comment by eddiemonge** [comment]
You can. There is a thing to make it go full page so its like an actual site. Or you could just post it to github. No need to clutter up npm with more non-modules

**Comment by eddiemonge** [comment]
also for fun, try `return $state.go('state1')`

**Comment by wesleycho** [comment]
I would argue that one should not write code like this - this is potentially fragile code, and behavior that should likely be handled before even delegating to UI Router's $state transitions, or handled through rejected resolves and a $stateChangeError handler.

I've seen this type of code become unwieldy very quickly.

**Comment by joaquimds** [comment]
@eddiemonge I'm pretty sure it won't work even with full page plunker, as the 'bug' relies on html5mode and server side url rewriting - even in a full size plunker this is not possible, e.g. here is the angular template http://embed.plnkr.co/tVqwXUAbWrPj2vzexQNq/preview - if I visit e.g. http://embed.plnkr.co/tVqwXUAbWrPj2vzexQNq/preview/test I don't get redirected back to http://embed.plnkr.co/tVqwXUAbWrPj2vzexQNq/preview.

I will take it off npm and put it on github though.

@wesleycho Apologies I was not aware of $stateChangeError; that sounds like a better way to do things so will re-write.

**Comment by joaquimds** [comment]
@eddiemonge Unfortunately the bug only happens in html5mode - if I switch this off then the looping behaviour doesn't happen. I don't think you can get html5mode on plunker, but I will move the example over to Github.

@wesleycho I will try the rewrite, thanks.

**Comment by joaquimds** [comment]
Up on Github here: https://github.com/joaquimds/ui-router-test

**Comment by joaquimds** [comment]
@wesleycho Restructuring the code such that state2 has a:

    resolve: { test: function($q) {return $q.reject();} }

And redirecting to state1 in the $stateChangeError handler solves my issue.

(Obviously in real life I would never make an auto-redirect state).

**Comment by eddiemonge** [comment]
so is this resolved then or does it need investigation?
