### ISSUE TITLE
State dom ready

### ISSUE THREAD

**Issue by furyscript** [angular-ui/ui-router#2276]
How can I check in main module controller if the DOM (with image) is fully loaded when stateChangeStart??

What is the event that I should watch?

I need to make one operation only when the targetState is fully ready but in $stateChangeStart...
So when stateChangeStart I set a progress bar, when stateChangeSuccess I close progress bar...
If I test in $stateChangeStart if my div is ready, it isn't because DOM isn't load.

I test to debug this event https://github.com/angular-ui/ui-router/wiki#view-load-events

```javascript
$rootScope.$on('$viewContentLoaded', function(event, toState, toParams, fromState, fromParams) {
        console.log("EVENT");
        console.log(event);
        console.log("/EVENT");
});
```
But I see that is fired 3 times, maybe because I have nested view??
So I test with this
```javascript
$rootScope.$on('$stateChangeStart', function(event, toState, toParams, fromState, fromParams) {

        event.targetScope.$watch("$viewContentLoaded", function () {
            console.log("EVENT");
            console.log(event);
            console.log("/EVENT");
            console.log($(".mydivinsideview").length));
       });
});
```
But I check if my div inside view is found but I don't get it...

**Comment by eddiemonge** [comment]
Why not do it in a states onEnter/onExit functions?

**Comment by furyscript** [comment]
I don't make it because it's a loading bar, so when change start I start loading bar and when statechangesuccess I finish it

**Comment by eddiemonge** [comment]
What happens when the state change fails?

**Comment by furyscript** [comment]
State change don't fails...

**Comment by eddiemonge** [comment]
state changes can fail....

Try taking a look at how [angular-loading-bar](http://chieffancypants.github.io/angular-loading-bar/) does it. I know that works perfectly with ui-router
