### ISSUE TITLE
$state in service

### ISSUE THREAD

**Issue by Vatsov** [angular-ui/ui-router#2277]
I'm trying to migrate ng-route to ui-router, and I'm, facing an issue regarding usage a $state in my custom service. 

Is there some workaround to get access to the relevant for ui-router $route and $routeParams?

**Comment by rwwagner90** [comment]
@Vatsov why do you need $state in a service?

**Comment by eddiemonge** [comment]
`$state.go` is one case. 

@Vatsov what specifically are you looking to use? What isn't working? This is probably a better question for stackoverflow
