### ISSUE TITLE
ui-router not changing state when location.hash changes

### ISSUE THREAD

**Issue by Ir1sh** [angular-ui/ui-router#2278]
I am doing parent.top.location.hash = 'mynewhash' form within an iframe.  I see the browser windows url change in the url bar but ui-router does not change the state.  If I listen for $stateChangeStart that event is never triggered by ui-router.

if I type the new hash directly into the url bar and hit enter then ui-router changes state as expected.  Should ui-router change state when the location.hash is change programmatically like this?

**Comment by eddiemonge** [comment]
What happens with `$locationChangeStart`?

**Comment by Ir1sh** [comment]
Thanks for the reply.  $locationChangeStart fires and when I look at the old and new values they are as I would expect them to be

**Comment by Ir1sh** [comment]
I figured out the problem thanks for the hint towards looking at the $location events.  We have a custom listener running before ui-routers listeners that I forgot about.  Thanks a lot.
