### ISSUE TITLE
$stateChangeSuccess should expose locals

### ISSUE THREAD

**Issue by cburgdorf** [angular-ui/ui-router#228]
In the Angular default routing the `$routeChangeSuccess` gives access to `fromRoute.locals` and `toRoute.locals`.

The `locals` give access to the resolved promises of the configuration block of the `route`.

However, with the ui-router it seems there is no way to get access to the resolved promises from the state resolve configuration block.

Am I doing it wrong? Is there another way to access those without being forced to resolve them again?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by pawsong** [comment]
I access to `$state.$current.locals` in `$stateChangeSuccess` event handler.

**Comment by nateabele** [comment]
Yeah, we're not gonna add any more parameters to the current events (we're at 5 now), but this is addressed through a new hook system in 1.0.
