### ISSUE TITLE
Conflict with pushState

### ISSUE THREAD

**Issue by dwatkinsweb** [angular-ui/ui-router#2281]
I am trying to use ui.router in an older system that was originally built possibly before angular was that well known. It is using a system that behaves somewhat similar (although much simpler and functionally very different) to the ui.router to handle different "pagelets" on the screen that function and navigate independently of the rest of the page. This system use a pattern of `<doman>?<pagelent_name>=<pagelet_url>&<pagelet2_name>=<pagelet2_url>` to track the state of each pagelet independently and uses basic history.pushState to handle this. However, when that state changes, just the act of setting ui.router as a dependency causes an error. I don't even have to use $stateProvider or anything. It's comparing the previous value of `<pagelet_url>` with the new value of `<pagelet_url>` in `LocationHashbangUrl.$$parse`. I'm not sure if this is a known issue or if there is a way to avoid this.

```
Error: withoutBaseUrl is undefined
LocationHashbangUrl/this.$$parse@www.mytestapp.com/static/js/libs/angular/angular.js:10502:9
$LocationProvider/this.$get</</<@www.mytestapp.com/static/js/libs/angular/angular.js:11153:9
$RootScopeProvider/this.$get</Scope.prototype.$eval@www.mytestapp.com/static/js/libs/angular/angular.js:14123:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@www.mytestapp.com/static/js/libs/angular/angular.js:13939:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@www.mytestapp.com/static/js/libs/angular/angular.js:14227:13
done@www.mytestapp.com/static/js/libs/angular/angular.js:9493:36
completeRequest@www.mytestapp.com/static/js/libs/angular/angular.js:9678:7
requestLoaded@www.mytestapp.com/static/js/libs/angular/angular.js:9621:1

www.mytestapp.com/static/js/libs/angular/angular.js
Line 11358
```

**Comment by eddiemonge** [comment]
https://gist.github.com/christopherthielen/b3fc0304b737a4bf8ec9

Also, a plnkr would help since what you are describing is hard to understand
