### ISSUE TITLE
ui-sref and ng-click with promise

### ISSUE THREAD

**Issue by celsomarques** [angular-ui/ui-router#2285]
Hey guys,

I'm facing an issue using ui-sref, ui-sref-opts="{reload: true}" and ng-click with promise

`ui-sref-opts="{reload: true}"` and `ng-click="ctrl.save()"`

```
<a ui-sref="edit.location({ name: ctrl.data.name })"
  ui-sref-opts="{ reload: true }" ng-click="ctrl.save()" 
  class="btn btn-success">Save &amp; Continue</button>
```

```
this.save = function() {
  return Person.save(this.data).$promise;
}
```

When next state is opened, promise was not loaded yet. How can I avoid this?
Could you help me with that, please?

Thanks in advance,
Celso

**Comment by eddiemonge** [comment]
Instead of ui-sref you should probably be doing state.go inside the `this.save` method.

**Comment by celsomarques** [comment]
I did that but it's ugly isn't it?

I have only one save function for a wizard and I needed make a check if there is no id
I'm wondering if there is another way to solve that.

Thanks

**Comment by eddiemonge** [comment]
Try asking on stackoverflow
