### ISSUE TITLE
State is loaded again when leaving it after transitionTo+notify=false was used

### ISSUE THREAD

**Issue by agdevbridge** [angular-ui/ui-router#2287]
Hello,
i got controller which changes url parameters using transitionTo + notify=false. When leaving it uiRouter loads old state and then new one.
Here is example: http://plnkr.co/edit/8Q8yUKER4ZDYf1grGIDI?p=preview
Using uiRouter develop branch #6f723a599dfab

**Comment by eddiemonge** [comment]
Pretty sure this is a duplicate bug. Lets call it a duplicate of #2087 although there are others it could fall under
