### ISSUE TITLE
Nested states and relative paths

### ISSUE THREAD

**Issue by rwwagner90** [angular-ui/ui-router#2288]
I am using [generator-gulp-angular](https://github.com/Swiip/generator-gulp-angular) and I am having issues with loading css. I have nested states and when I load the app up and navigate to each state, everything is fine, but then if I refresh, it's unable to find the index.css file. It's referenced via relative path and upon refresh it seems to add the state url to the path and messes it up. No issues for single states, only with nested ones.

**Comment by eddiemonge** [comment]
sounds like a problem with HTML5mode. Ask over on the generator side if they have a solution for that as its an implementation detail.

**Comment by rwwagner90** [comment]
If anyone else encounters this issue, it is now solved. Discussion here: https://github.com/Swiip/generator-gulp-angular/issues/823
