### ISSUE TITLE
Suggest putting hashtag/html5mode situation into FAQs

### ISSUE THREAD

**Issue by jackwhit3** [angular-ui/ui-router#2290]
As a beginner, I kept getting `Cannot GET /state1` for trying out the examples myself. Spent hours running through the documents, FAQs and SOs and finally came across [this](http://stackoverflow.com/questions/29190321/cannot-understand-ui-router-behaviour-with-angular-js) and realised the root cause.

Well, one of the [FAQ](https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#issue-my-assets-and-templates-are-not-loading) did lightly address it, but since the Angular version is already 1.4.x (the FAQ mentioned only 1.1.5) I did not pay much attention. Also, Plunkr code did not include `.js` files so I had no idea about `$locationProvider.html5Mode(true)`.

I suggest to somehow update/add more information on this issue.

**Comment by eddiemonge** [comment]
Which examples were you following?

**Comment by jackwhit3** [comment]
@eddiemonge thanks for the quick reply. 
I tried both, the `ui-sref` worked fine. But since there was no default view when accessing `localhost:8000`, I tried typing `localhost:8000/stateurl` and it always leads to a `Cannot GET /stateurl`. I discovered I had to add a hashtag like `localhost:8000/#/stateurl` to make it work.

**Comment by eddiemonge** [comment]
its called HTML5mode. Single page apps need a server that supports rewrite rules to be able to use urls like /path instead of /#/path (which is just using HTMLs hash fragments to do almost routing like things.

**Comment by jackwhit3** [comment]
Thanks!
