### ISSUE TITLE
templateProvider does not get called for parent when switching child states

### ISSUE THREAD

**Issue by andidev** [angular-ui/ui-router#2295]
Maybe this is the expected behaviour and I am doing something wrong here?

I am trying to show different navbars based on the user type that is currently logged in.

**parent state**
```javascript
$stateProvider.state('site', {
    'abstract': true,
    views: {
        'navbar@': {
            templateProvider: function ($http, $templateCache, $q, Principal) {
                return Principal.getUserType().then(function(userType){
                    var url = 'navbar.html';
                    switch (userType) {
                        case 'ADMIN':
                            url = 'navbar-admin.html';
                            break;
                        case 'USER':
                            url = 'navbar-user.html';
                            break;
                    }
                    return $http.get(url, {cache: $templateCache}).then(function (response) {
                        return response.data;
                    });
                });
            },
            controllerProvider: function () {
                return 'NavbarController';
            }
        }
    }
});
```

**child state**
```javascript
$stateProvider
    .state('home', {
        parent: 'site',
        url: '/',
        views: {
            'content@': {
                templateUrl: 'home.html',
                controller: 'HomeController'
            }
        }
    });
```

**child state**
```javascript
$stateProvider
    .state('settings', {
        parent: 'site',
        url: '/settings',
        views: {
            'content@': {
                templateUrl: 'settings.html',
                controller: 'SettingsController'
            }
        }
    });
```

**index.html**
```html
<div ui-view="navbar"></div>

<div ui-view="content"></div>
```

**Comment by christopherthielen** [comment]
If I understand what you're asking, this is expected behavior.  


In the child state, you should override the definition of the names view.

**Comment by andidev** [comment]
Yes I think you understood me =) Okey so that would mean a lot of code duplication which would be really nasty in my case.

My use case is the following (a bit modified from my first comment):

- When a **admin user** is logged in ui-router should load `navbar-admin.html` in the `ui-view="navbar"` and `home-admin.html` view in `ui-view="content"`

- When a **normal user** user is logged in ui-router should load `navbar-user.html` in the `ui-view="navbar"` and `home-user.html` view in `ui-view="content"`

- When **no user** is logged in the ui-router should load `navbar.html` in the `ui-view="navbar"` and `home.html` view in `ui-view="content"`

To accomplish this behaviour I have a service that use a `$http.get('/current-user-type')` to receive the current user type. I use the templateProvider since I need to be able to inject the this service and decide which user type specific template to load. 
The templateProvider for the `ui-view="navbar"` will always look the same and therefore it is defined as an abstract parent state while the templateProvider/templates for the `ui-view="content"`is defined in child states.
However I am facing an issue when an user logs in and logs out. The parent state is actually never changed and therefore the `ui-view="navbar" is not reloaded with the new template.

Is there some way to force the templateProvider for the parent state to run again?

Maybe my problem could be solved by using an **url parameter** or **query parameter** but I would like to avoid this since it makes the url unnecessary verbose.

**Comment by andidev** [comment]
So I just found the solution to my issue.
Reload of parent state can be refreshed by `$state.go('state', {}, {reload: true, inherit: false});`
Doing that when logging in and out did the trick!

**Comment by christopherthielen** [comment]
$state.reload() will reload the whole state tree

**Comment by andidev** [comment]
Thanks that's even better.
