### ISSUE TITLE
Not working on IE7

### ISSUE THREAD

**Issue by artdias90** [angular-ui/ui-router#2298]
I'm trying to make ui router work on Internet Explorer 7, already got all necessary polyfills, json2 and es5-shim. No errors on console, and on IE8 I can load the app.

Here's body tag
```
< !-- [if lte IE 8]>
 < body id="myapp" ng-app="myapp" >
< ![endif]-- >
```

which is the one being chosen, I verified it.

otherwise also added xmlns on html tag
<html xmlns:ng="http://angularjs.org">

What else can be missing?
Using  AngularJS v1.2.29.

**Comment by eddiemonge** [comment]
Well considering Angular dropped IE8 support, I don't think this is supported.
