### ISSUE TITLE
Squash does not remove trailing slash in ui-sref

### ISSUE THREAD

**Issue by ritenv** [angular-ui/ui-router#2299]
If I define a state as below:

```
    $stateProvider.state('productsByCategory', {
        url: '/products/:catSlug/:subCatSlug?',
        controller: 'MyController',
        params: {subCatSlug: {value:null, squash: true}},
        templateUrl: '/app/products/list.html'
    })
```

I expect this to match the URL path `/products/watches`, which it does (no trailing slash). 

However, if I do the below methods, I get the URLs with the trailing slashes:

```
    <a ui-sref="productsByCategory({catSlug: 'watches'})">Go to Watches</a>
```

I get the below compiled tag:

```
    <a ui-sref="/products/watches/">Go to Watches</a>
```

(The slash is not squashed)

Is this an expected behavior? And if so, is there a way to retrieve the squashed version via `ui-sref`?

**Comment by wesleycho** [comment]
[Here](http://plnkr.co/edit/miUFnO?p=preview) is a reproduction - this appears to be a bug.

**Comment by eddiemonge** [comment]
is it because of the last `?` ?

**Comment by adambuczynski** [comment]
+1

@nateabele this was flagged as a bug on October 2015, it doesn't seem like a very complicated thing to fix. Any chance someone could have a look at it?

**Comment by wesleycho** [comment]
You could always file a PR :)

**Comment by adambuczynski** [comment]
This seems to be related to (or the same as) https://github.com/angular-ui/ui-router/issues/1902 which appears to have been fixed already.
