### ISSUE TITLE
New tab/window support for ui-sref on non-interactive elements

### ISSUE THREAD

**Issue by langdonx** [angular-ui/ui-router#2301]
I have a table and wanted each row to be navigable.  I figured I could use `<tr ui-sref="...">`, which works great, except it doesn't allow you to <kbd>ctrl</kbd>+<kbd>click</kbd> to open a new tab or <kbd>shift</kbd>+<kbd>click</kbd> to open a new window.

I found [this "extension"](http://stackoverflow.com/a/28873084/158502), which I adapted beyond just checking `metaKey` (non-standard in Windows) to open in a new tab/window:

		$state.navigate = function($event, to, params) {
			var url;

			if ($event.shiftKey || $event.ctrlKey || $event.metaKey) {
				url = $state.href(to, params, { absolute: true });

				// open in a new window (shift) or tab (ctrl/option)
				window.open(url, $event.shiftKey ? '_blank' : undefined);
			} else {
				$state.go(to, params);
			}
		};

This unfortunately feels like a hack since I can use the vanilla `ui-sref` attribute everywhere else (anchors, buttons, etc).

Is it possible that this logic can be baked into the framework for non-interactive elements (tr, div, etc)?

ETA:  ~~It's interesting to note that if you set a tabindex on your `tr` with `ui-sref` and tab over to it, <kbd>enter</kbd> navigates correctly, <kbd>shift</kbd>+<kbd>enter</kbd> opens the route in a new window, but <kbd>ctrl</kbd>+<kbd>enter</kbd> does not open in a new tab.~~  Oops, this is only true with my `ng-click` and `$state.navigate` hack.  It'd be awesome as well to get non-interactive elements working with the <kbd>enter </kbd> as well.

**Comment by eddiemonge** [comment]
You could use anchors and div to create the table and then style it in css with display: table and the related properties

**Comment by langdonx** [comment]
There are definitely a lot of ways to solve it.  I'd probably decide to use my `$state.navigate` approach over that though.

I'm seeing other issues now though with nesting `ui-sref` attributes (one of the cells in my row has an anchor -- the row's ui-sref takes priority, which it shouldn't).  This seems like a very solvable problem though.

**Comment by eddiemonge** [comment]
That approach still doesn't respect the browsers default. shift, meta, control all can do different things like new tab or new window. You are changing that default behavior. Same reason that ui-sref on a non-anchor doesn't dictate what to do. Closing this as it should be up to the user to decide what to do on non-standard implementations.
