### ISSUE TITLE
using $state.go with { notify: false } causing reloading of the same state when going to the other state

### ISSUE THREAD

**Issue by helios1138** [angular-ui/ui-router#2303]
Scenario is:

* I'm on **state A**
* I'm calling `$state.go($state.current, { some: params }, { notify: false, location: 'replace' })` to update url
* Now I'm calling `$state.go('state B')`
* Expected result: only **state B** controller is loaded
* Actual result: **state A** and **state B** controllers are loaded (**state A** then immediately destroyed)

**Comment by eddiemonge** [comment]
duplicate of another ticket

**Comment by helios1138** [comment]
@eddiemonge please reference that ticket here

**Comment by eddiemonge** [comment]
https://github.com/angular-ui/ui-router/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+notify+false

**Comment by arjuneyy** [comment]
I'm encountering the same issue, and I can't find the reference ticket. The link pointed to **any open** issue and I can't figure which is which :) 

Thanks for the help.

**Comment by suriyacs** [comment]
I'm also encountering the same issue.My router version is below then @version 1. So I can't able to make dynamic param (dynamic: true). Notify is the only option i have, to update the state param without page reloading.

Is there any update on this ticket.
