### ISSUE TITLE
Template flashes uncompied during ngAnimate transition

### ISSUE THREAD

**Issue by everythingspirals** [angular-ui/ui-router#2305]
I am using a slide up animation when switched between states. Sometimes as the next state is sliding up, the template is displaying uncomplied, i.e the double curlies are showing up like {{title}}. When the animation completes everything loads. When looking at the code it seems the duplicated ui-view is being added to the DOM before being compiled. Any ideas how to fix this?

**Comment by eddiemonge** [comment]
plnkr example would be helpful for this

**Comment by everythingspirals** [comment]
I fixed it by forcing a digest cycle after calling $state.go(...).
