### ISSUE TITLE
DOCS: ui-sref may be cancelled by calling event.preventDefault() in other handlers

### ISSUE THREAD

**Issue by miraage** [angular-ui/ui-router#2307]
This is very useful feature that I love to use sometimes, but I found it by browsing source code. :)

**Comment by eddiemonge** [comment]
want to submit a pull request to fix that?

**Comment by ctysingh** [comment]
any updates on this?

**Comment by nateabele** [comment]
@ctysingh Do you want to write a PR for the docs?

**Comment by ctysingh** [comment]
sure I can give a try.
