### ISSUE TITLE
.state using controller outside of module

### ISSUE THREAD

**Issue by PaddoSwam** [angular-ui/ui-router#2310]
It seems that .state looks at controllers on a global scope instead of a module scope.

Example of the problem:

http://plnkr.co/edit/UyFRbGpVnlA2KyMAYR2p?p=preview

**Comment by eddiemonge** [comment]
this is how angular works. Since you defined vehicles as the first dependency, it uses that.

**Comment by PaddoSwam** [comment]
Obviously this is how it (is it angular or ui-router?) works but it feels like it shouldn't work like this.

**Comment by eddiemonge** [comment]
its angular and its dependency injection/management. If you feel this is incorrect, then please open an issue with them although i think this is solved in angular 2
