### ISSUE TITLE
migrate from hashbang mode to html5 pushstate

### ISSUE THREAD

**Issue by jlmagee** [angular-ui/ui-router#2312]
I currently support a site in angularjs with ui-router. I'd like to switch from hashbang mode to html5mode pushstate. However, I'd need to support existing hashbang links to specific pages from existing sources over which I have no control. I've tried duplicate state/route definition with no success.

I posted on stackoverflow but no one responded. Any advice would be appreciated

**Comment by eddiemonge** [comment]
Maybe your stackoverflow should be reworded. Still an implementation detail but please do paste the link to the SO question here

**Comment by jlmagee** [comment]
http://stackoverflow.com/questions/33040380/migrate-from-hashbang-mode-to-html5-pushstate

Thanks for your help

**Comment by jlmagee** [comment]
UPDATE: Sorry if I wasted anyone's time. It works as I initially expected. just add $location.html5Mode(true); in front of $location.hashPrefix('!'); and everything worked fine.

I obviously had not properly configured the test environment initially.

This update has been added to the stackoverflow question.
