### ISSUE TITLE
Refresh lost stateparams

### ISSUE THREAD

**Issue by x-hovo-x** [angular-ui/ui-router#2313]
Hi guys,

Don't know whether this topic already discussed, but I could not find any similar one...
Also I was not able to find anything like this in Stackoverflow.
I have a state like 
```
        .state('member.edit', {
            url: '/member/edit/:id',
            views: {
                'content' : {
                    templateUrl: 'views/member/member_edit.html',
                    controller: 'MemberEditController as ctrl'
                }
            },
            data: {
                page : 'editmember'
            },
            reloadOnSearch: false,
            parent: 'guest'
```

when I reload page (Ctrl+F5/Cmd+R or simply click browser reload button) sometimes the id in url is missing, like this
http://localhost:9000/#/member/edit/:id/

it is not happening always, just every 5-6 attempt failed.

ui-router version @version v0.2.14

**Comment by eddiemonge** [comment]
Can you upgrade to 0.2.15 (though might not make a difference. Also can you make a plnkr showing the problem please?

**Comment by x-hovo-x** [comment]
eddiemonge,

thanks for comment...

I changed to 0.2.15 result the same.
Will create plnkr later, but didn't get how to simulate reload ...

**Comment by eddiemonge** [comment]
Closing due to inacitivty

**Comment by techbirds** [comment]
how to solve?

**Comment by spidergears** [comment]
Anyone got a solution for this?
