### ISSUE TITLE
Route with query params

### ISSUE THREAD

**Issue by mueees** [angular-ui/ui-router#2319]
Hi,
how can I set up url like
<code>/article?id=23&search=23...</code>

I have to get all query parameters, but I don't know exactly which I will get.
Thanks!

**Comment by eddiemonge** [comment]
Set them as variables in the url. If you want to check for all you could do something like `url: '/article?:params` but really you should know what params you are looking for since you will have to use them right?

https://gist.github.com/christopherthielen/b3fc0304b737a4bf8ec9
