### ISSUE TITLE
I have reloadOnSearch: false and state change/resolves are triggering anyway when I update $location.search()

### ISSUE THREAD

**Issue by demetriusnunes** [angular-ui/ui-router#2320]
All my states have reloadOnSearch: false.

When I try to remove a parameter from the querystring via:
$location.search('provider', null);

This modification of the $location.search is happening during the resolver function. So, reloadOnSearch is not preventing trigerring the resolver again when that happens.

**Comment by eddiemonge** [comment]
What version?
