### ISSUE TITLE
it it possible get a hold of the injector used to inject resolves into controllers?

### ISSUE THREAD

**Issue by mkoryak** [angular-ui/ui-router#2323]
Can you tell me if the injector used by ui-router to inject resolves into controllers is exposed somewhere? I would like to use it in a few other places that have access to scopes of the routes/controllers, but I have no idea how to do it. 

thank you

**Comment by nateabele** [comment]
AFAIK resolves aren't exposed anywhere currently. We plan to address this in 1.0.

**Comment by mkoryak** [comment]
not even in some hacky undocmented object? 

can you atleast point me in the source where the injector is created/invoked? I looked for it but could never find it

**Comment by christopherthielen** [comment]
The hacky undocumented please don't do this way might be to grab resolved data off $state.$current.locals.globals. The injector isn't something exposed anywhere.

**Comment by rinogo** [comment]
@nateabele or @christopherthielen, has this already been addressed in 1.0?

**Comment by astik** [comment]
I would be interested too ... i'd like to access some resolved data into some inner component without overriding a very generic controller =)

**Comment by christopherthielen** [comment]
@rinogo yes, see https://ui-router.github.io/docs/latest/classes/transition.transition-1.html#injector

**Comment by rinogo** [comment]
Thank you, @christopherthielen ! :)
