### ISSUE TITLE
urlRouter's sync method needs better/updated documentation and possibly fixed

### ISSUE THREAD

**Issue by jberk** [angular-ui/ui-router#2324]
this code does nothing, far as I can tell.  Even though I'm explicitly setting meetsRequirements to false, nothing is blocked and my next state loads.

I've done a ton of SO research and there are multiple posts regarding this method and how "broken" it is.  

The confusion stems from it's use of $locationChangeSuccess instead of a $stateXXXX event and the fact that it just doesn't seem to work at all, as the code block below shows.

At minimum, it seems like having this documentation out there is counter productive.

```
// straight from http://angular-ui.github.io/ui-router/site/#/api/ui.router.router.$urlRouter
// in my .run function......
$rootScope.$on('$locationChangeSuccess', function(evt) {
            // Halt state change from even starting
            evt.preventDefault();
            // Perform custom logic
            var meetsRequirement = false;
            // Continue with the update and state transition if logic allows...which *should* never happen
            if(meetsRequirement) $urlRouter.sync();
        });
```

**Comment by jberk** [comment]
http://stackoverflow.com/questions/22537311/angular-ui-router-login-authentication

```
The solutions posted so far are needlessly complicated, in my opinion. There's a simpler way. The documentation of ui-router says listen to $locationChangeSuccess and use $urlRouter.sync() to check a state transition, halt it, or resume it. But even that actually doesn't work.
```

**Comment by nateabele** [comment]
See https://angular-ui.github.io/ui-router/site/#/api/ui.router.router.$urlRouterProvider#methods_deferintercept
