### ISSUE TITLE
Can view set up its own resolve ?

### ISSUE THREAD

**Issue by lili21** [angular-ui/ui-router#2330]
```
$stateProvider
  .state('report', {
    views: {
      'filters': {
        controller: function() {},
        templateUrl: '**/**.html',
        resolve: {}
      }
    }
  })
```
It works well. I am just wandering does it supposed to work or what?

**Comment by nateabele** [comment]
Yup, it's supposed to work. :smile:

**Comment by lili21** [comment]
@nateabele ，thanks. Hope this can be mentioned in wiki or docs.

**Comment by nateabele** [comment]
You're more than welcome to update the wiki or submit a PR with API doc changes. Thanks.

**Comment by lili21** [comment]
I'd love to do that. But my english is pretty basic, I don't know how to organize the words.

**Comment by nateabele** [comment]
@lili21 Your English is good enough, believe me. :smile: Besides, docs with imperfect grammar are still better than no docs. Someone else can always clean it up (though I bet they won't need to).
