### ISSUE TITLE
lazy loading js script with resolve but get get an undefined $http error

### ISSUE THREAD

**Issue by Leo-G** [angular-ui/ui-router#2331]
I want to load a  js file only when a specific state is called. I wanted to use resolve as mentioned in the docs

        promiseObj:  function($http){
                // $http returns a promise for the url data
                return $http({method: 'GET', url: '/file.js'});
             },

However when I use this it gives me $http undefined error. I know you cannot inject $http inside module.config() so I am wondering how I should go about lazy loading my js file?

**Comment by nateabele** [comment]
This might help: http://laurelnaiad.github.io/angular-couch-potato/docs/#/guide

Otherwise we generally suggest taking these kinds of questions to StackOverflow. Thanks.

http://bit.ly/UIR-SOF
