### ISSUE TITLE
ui-sref needs two clicks after $state.go({notify false})

### ISSUE THREAD

**Issue by klmdb** [angular-ui/ui-router#2334]
Short:
  ui-sref needs two clicks after $state.go({notify false}). 

Long(er):
  I use $state.go('stateName', stateparams, {notify:false}); in my controller to update the url without reloading the entire page and its controller/dependencies. This seems to work fine. A side effect is that after the url was updated this way, when the user clicks a link on the page, it doesn't work the first click. When clicking the link a second time it does.

I'm not getting any exceptions or errors.

**Comment by eddiemonge** [comment]
please provide a plnkr example

**Comment by klmdb** [comment]
Okay so I tried to create a plunker to show this behaviour:

http://plnkr.co/edit/eCpU0RGXDZ4O1kZmg63I

HOWEVER - I didn't fully succeed. That is to say: clicking ui-sref elements does immediatly change pages. Some odd things that might be related though:

- when I am on state home.sub & I put a breakpoint in the beginning it's controller, it breaks when I click the link to go to home.sub2
- when I change the url on home.sub by typing in the input field, the stateParameter 'name' is preserved when I go to home.sub2

Does that help? If more info is required please let me know and I'll try to answer asap. g2g now :p

**Comment by eddiemonge** [comment]
There are a few bugs around notify. Your odd things 1 sounds like a known bug.

**Comment by plattfish** [comment]
I've also encountered this bug. With release 0.2.14 I can't reproduce it, so I will stick with that version until it is fixed.

**Comment by tchiloh** [comment]
I have also this problem.

**Comment by tchiloh** [comment]
Solution:
https://github.com/angular-ui/ui-router/pull/2003

**Comment by murli2308** [comment]
I am facing same issue ? any solution ?

**Comment by gattoo** [comment]
same for me

**Comment by ivanzvakoms** [comment]
same

**Comment by ivanzvakoms** [comment]
if I put {notify: false, reload: true} - this bug reproduce constantly

**Comment by rivaros** [comment]
@ivanzvakoms that helped thanks

**Comment by afgonzal** [comment]
Thanks Ivanzvakoms, that worked

**Comment by josholdham** [comment]
I have this issue, and the timeout fix didn't work for me. Upvote.

**Comment by aromanyukvakoms** [comment]
@josholdham ui-router contributors give all their effort to new version, so I think it would be better to find some workaround for this issue that waiting for fix.

**Comment by davidkaneda** [comment]
Just ran into this as well, and the timeout didn't work... For me this was happening with some links and not others and I realized the links/target states that were affected (requiring two clicks) all had `resolve`s on them whereas the links that worked immediately did not.

Removing the resolves (and moving their logic into the controllers) fixed it for us.

**Comment by alvarodms** [comment]
Same issue here. Tested with both 0.2.13 and 0.2.15. $timeout workaround didn't work.

**Comment by saumyapatel** [comment]
Same issue. any solution available?

**Comment by christopherthielen** [comment]
FYI, we no longer support `{notify: false}` in ui-router 1.0+ because the state events have been removed
