### ISSUE TITLE
Double state change after $state.go in $stateChangeStart

### ISSUE THREAD

**Issue by gligoran** [angular-ui/ui-router#2336]
Here's the [plunker](http://plnkr.co/edit/Zds0fulNOUHobjUOfMYv?p=preview). Click on the ```profile``` link and note the extra state change in the list:

    stateChanges = [
      " -> home",
      "home -> profile",
      "home -> signIn",
      "signIn -> signIn"
    ]

The problem is that last ```"signIn -> signIn"```, which, in my opinion, should not have happened.

I've done some debugging and it seems it's ui-router's reaction to ```$locationChangeSuccess``` via the ```afterLocationChange``` function.

I also don't understand why the parameter ```returnTo``` is double-encoded: ```/profile -> %2Fprofile -> %252Fprofile```.

**Comment by gligoran** [comment]
Tried playing around with previous versions and found out this only happens in 0.2.15. After looking at the change log, it seems that this commit is to blame: 48aeaff6. If I remove the code commented by that commit, the double transition goes away.

It seems this is connected to #1573.

**Comment by eddiemonge** [comment]
Is this fixed in a higher version?

**Comment by eddiemonge** [comment]
Yeah seems fixed in the latest versions. Also, why not use `returnTo: toState.name`?
