### ISSUE TITLE
'params' in parent state have to be defined in all child states

### ISSUE THREAD

**Issue by erkanarslan** [angular-ui/ui-router#2337]
Let's say I have a parent state : `parent` and two child states : `child1` and `child2`.

`parent` needs one parameter: `param1`.
`child1` needs one parameter : `param1`.
`child2` needs two parameters: `param1`, `param2`.

As `parent` needs `param1`, this parameter is defined in stated definition:
````
.state('parent', {
    params : {param1 : null},
    ....
}
````

However, `child2` also needs `param2` but `parent` filters this out. To prevent that, I add `param2` to state definition:
````
.state('parent', {
    params : {param1 : null, param2 : null},
    ....
}
````

But in this case, an error occurs:
````
Failed to instantiate module xxx due to:
Error: Missing required parameter 'param2' in state 'child1'
````

I can solve this problem by adding `param2` in state definition of `child1`. But I have lots of child states and it is not right to add parameters that are not needed to all children.

What is the solution?

**Comment by eddiemonge** [comment]
Only add the parameter in the child that needs it.

**Comment by eddiemonge** [comment]
https://gist.github.com/christopherthielen/b3fc0304b737a4bf8ec9

**Comment by erkanarslan** [comment]
If I add the parameter only in the child that needs it, an error occurs as I explained above. That is not a solution. Also, I don't think that I can find an answer to that question in StackOverflow because the library does not support that feature in the first place.

**Comment by eddiemonge** [comment]
Please provide a plnkr demonstrating this as I am pretty sure its something in the way you are writing your state definitions

**Comment by erkanarslan** [comment]
I have written a plnkr and it works fine. Then I switch back to my code and I cannot reproduce the error in there too, it works fine as well. Sorry for taking your time.

**Comment by eddiemonge** [comment]
as long as your issue is solved then its not a waste of time :)
