### ISSUE TITLE
Controller runs twice when activating a state with slash in the params

### ISSUE THREAD

**Issue by cvn** [angular-ui/ui-router#2339]
When activating a state with a slash in the params, it will call that state's controller twice.

    $state.go('myState',{previous:'/last/page'});

I wrote some tests to demonstrate:

http://plnkr.co/edit/WgBVFpArGhamZe5mVtWz?p=preview

Thanks to @kathygit for discovering this, as well as providing a workaround (url encoding the slashes) in the issue referenced below.

Tested with Angular 1.4.7 and UI-Router 0.2.15.

**Comment by uaoleg** [comment]
+

**Comment by cbfranca** [comment]
+1 I have the same issue

**Comment by anymos** [comment]
It s not like nobody is using a parameter as return path with / inside ...

How it s possible to have this bug if there is testing ?

**Comment by manishsingh2508** [comment]
Hello,

I am facing the similar issue. the controller is called twice which is causing a major problems.
I am using the 0.2.15 version.

I am surprised the issue still exists . Can anyone help me how can i resolve the issue. The parameter passed here is mandatory and it can be Y or N.

See the example.
Template
ui-sref=".newProject({fromTempl:fromTemplate})

Configuration
.state('home.projTypeView',{
url: '/projTypeView/:fromTempl',
views: {
'mainContainerView@': {
templateUrl: 'apps/views/projectTypeList.html',
controller:'projectTypeListController',

          }
     }
 })
Please help me out . I could not find any answer .
Regards,
Manish Singh

**Comment by cbfranca** [comment]
+1

**Comment by mrfatgoat** [comment]
+1
Exactly the same issue here

**Comment by PierrickMartos** [comment]
Same here.

**Comment by christopherthielen** [comment]
http://plnkr.co/edit/7sJQL9UEMlwiwYSqglvX?p=preview

**Comment by deathgaze** [comment]
This is happening again as of 0.3.1

**Comment by christopherthielen** [comment]
@deathgaze can you put this in a plunker ? http://bit.ly/UIR-Plunk
