### ISSUE TITLE
REST-like optional paramters

### ISSUE THREAD

**Issue by sebastian-zarzycki** [angular-ui/ui-router#2341]
I have an url: /test2/foo/{int}/bar/{int} and a state that it leads to.
I'm trying to figure out the best approach for making the parts after /test2/ optional. Obviously, it's easy to do with with squash for parameters themselves. But here, it's not only about the parameter, but also preceding part of the url. In other words, here are the valid urls I'd like to get:

/test2
/test2/foo/4
/test2/foo/4/bar/8
/test2/bar8

These are not valid:

/test2/meh/4/bah/8
/test2/foo
/test2/foo/bar
/test2/4
/test2/4/8

So far I have this:

        $stateProvider.state('test2', {
            url: '/test2/{slug1:foo}/{param1:[0-9]+}/{slug2:bar}/{param2:[0-9]+}',
            template: '<div><h1>Test2</h1><h2>Param1: {{ param1 }}</h2><h2>Param2: {{ param2 }}</h2></div>',
            controller: function($scope, $stateParams){
                $scope.param1 = $stateParams.param1;
                $scope.param2 = $stateParams.param2;
            },
            params: {
                slug1: { squash: true, value: null },
                slug2: { squash: true, value: null },
                param1: { squash: true, value: null },
                param2: { squash: true, value: null }
            }
        });

It works mostly fine, but the squash and/or matching can yield some funny results. I'm not sure if I'm doing something wrong, or there are some problems within. Basically, these urls seem to be also valid, and they resolve proper param1 and param2 values:

/test2/foo4/bar/8
/test2/foo/4/bar8
/test2/foo4/bar8
/test2/foo4bar8

Squash documentation says something about trimming the previous/next slash, so that might be it. But it's still weird. Also, apparently I cannot use the leading slash (/) in regex, so my hands are tied for the regex expressions.

Can this be improved? Any better way to solve this neatly?

(keep in mind that I don't want different states that answer to different url paths - that would kill the whole point).

**Comment by nateabele** [comment]
Please direct support issues to StackOverflow, thanks. http://bit.ly/UIR-SOF

**Comment by sebastian-zarzycki** [comment]
I did - http://stackoverflow.com/questions/33379844/rest-like-optional-paramters-in-angularjs-ui-router
Noone answered. While I understand this is kind of generic question, I'm still not sure, whether I've encountered a bug or not. Any additional help or pointing me into the right direction for this solution would be appreciated.
