### ISSUE TITLE
How to use $urlRouterProvider.rule 

### ISSUE THREAD

**Issue by kingsleywang** [angular-ui/ui-router#2342]
Code here is as an example:  address bar is changed but state2,html is not loaded

You just can see a empty page without throwing any errors

```js
(function(){
    'use strict';
    angular.module('myapp', [ 'ui.router' ])
            .config(function($stateProvider, $urlRouterProvider){
            $urlRouterProvider.otherwise("/state1");
            $urlRouterProvider.rule(function ($injector, $location) {
                return "/state2";
            });

            $stateProvider
                .state('state1', {
                    url: "/state1",
                    views: {
                        "mainview": { template: "state1.html" }
                    }
                })
                .state('state2', {
                    url: "/state2",
                    views: {
                        "mainview": { template: "state2.html" }
                    }
                });
        })
        
        .controller('AppCtrl', AppCtrl);
          function AppCtrl(){
        }
})();
```

**Comment by kingsleywang** [comment]
Here is my index.html 


<!doctype html>

<html ng-app="myapp">

    <head lang="en">

        <meta charset="UTF-8"/>

        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />

        <title>Test</title>

        <link rel="stylesheet" href="app.css">

    </head>

    <body ng-controller="AppCtrl as appCtrl">

        <div ui-view="mainview"></div>

        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js"></script>

        <script src="https://cdn.jsdelivr.net/angular.ui-router/0.2.15/angular-ui-router.min.js"></script>

        <script src="app.js"></script>

    </body>

</html>

**Comment by eddiemonge** [comment]
You have an infinite loop going on

http://plnkr.co/edit/EeA1lh59YGoy1EQG7ZLV?p=preview
