### ISSUE TITLE
Detect Failed Child Views 

### ISSUE THREAD

**Issue by impatient** [angular-ui/ui-router#2344]
When the child of a parent route fails, as far as I can tell, there isn't a good way to detect whether or not the child view succeeds.  I would expect that on the failure of the child view that state change fails.

Is there a way around this?  (If so, stop reading)

Would you be willing to include an event for a view failure?  

I recreated the issue in the following Plunkr, modified from the nested views sample: http://plnkr.co/edit/GtjXi5LbGLgquKjkxbUU?p=info

The issue occurs when loading details, because the controller errors.

Here's a sample of adding the event to notify:  https://github.com/impatient/ui-router/commit/b061cf986a1bd0090c8614ba477adfd527ad549e

It can re-throw after logging the event as well to preserve current behavior/keep from surprising people.

**Comment by eddiemonge** [comment]
The stateChangeError shouldn't fire because the state change was successful when you threw the error in contacts.detail

**Comment by impatient** [comment]
The real question was how do you catch/detect that error with ui-router.  It's just silently swallowed, but it could be trivially detected/easily notify the app.

Obviously, our fix is going to be to handle the constructor error and display some error text, but in the case of something that slips by there is no way to detect it.

**Comment by eddiemonge** [comment]
Thats not a ui-router error to catch but an Angular/JS error in general.

**Comment by impatient** [comment]
I see what you're saying.  Thanks for taking another look.
