### ISSUE TITLE
Cannot change query parameters WHILE state is stile loading...

### ISSUE THREAD

**Issue by CxRes** [angular-ui/ui-router#2345]
I believe this is a corner case:

There seems no way of changing query parameters while a state is still changing. I want to to be able to change values if a certain query cannot be met to next closest available option rather failing the query.

**Comment by eddiemonge** [comment]
you could redirect in the stateChangeStart and return false in it to prevent. This seems like more of an implementation issue than a bug

**Comment by CxRes** [comment]
@eddiemonge That is not adequate in my use case because the parent is an abstract state that fetches data (and then resolves) and the query parameters carries views type. If a view selected by the user is not available then I need to switch to the closest available view (rather than fail and reload). Correct me if I am wrong, but if I return false here, I will need to reload data (because the transition to the parent state would have failed as well) or to avoid that first create a service that caches that data. So I need either a an extra server call or have extra code. 
Simplest would be if I can just change query parameters while loading itself. It may be an implementation issue but implementations in general affect how downstream implementations are done.

**Comment by eddiemonge** [comment]
I'm saying its not a bug in ui-router but in implementation. A better place to ask this sort of question is on stackoverflow or similar. We try to keep the issues here limited to bugs, feature requests and documentation improvements: http://bit.ly/UIR-SOF

**Comment by CxRes** [comment]
@eddiemonge I did ask this on stackoverflow first: 
http://stackoverflow.com/questions/33250129/ui-router-is-it-possible-to-change-a-query-parameter-while-the-state-is-loading. 
Realizing that there was no happy workaround from the responses is why I came here. Its not clear from your responses, whos implementation is buggy in your opinion. Isn't asking for an implementation change that makes the life of downstream developers much easier a feature request??? or if I am doing it wrong in your opinion, I would invite you to answer my stackoverflow question.

**Comment by eddiemonge** [comment]
Use a child states and redirect to those so the main state isn't reloaded. Or don't load the data in the resolve, do it in the controller or in onEnter

**Comment by CxRes** [comment]
I am afraid both your suggestions are unhelpful. 

Your first suggestion is something I experimented quite a bit with. I am using child states for the views, but I am forced to wait for a child to resolve before I can redirect which means I momentarily get the bad child state (a bad view and/or data missing errors). Unfortunately `event.preventDefault()` acts on child and the parent together so if I use to stop loading midway without also having to reload my data.  Maybe  `event.preventDefault()` needs greater granularity (prevent child and keep parent).  Also this first suggestion would mess up the history because a previous will redirect to the bad view.
Not loading the data in resolve is a non starter, I don't even bother going to my views (see the problem I have described above), if there is no data. 

Please understand that I am making this request after some thought and consulting whatever help in the community I could find. Please, at least try to understand the issue before summarily dismissing it.
