### ISSUE TITLE
Which tool was used to create the StateGoExamples.png Image?

### ISSUE THREAD

**Issue by tobiashochguertel** [angular-ui/ui-router#2348]
Can someone tell me the name of the tool which was used to create this clean lookig state and transition diagram?

http://angular-ui.github.io/ui-router/ngdoc_assets/StateGoExamples.png

**Comment by nateabele** [comment]
I believe that's a @timkindberg question.

**Comment by timkindberg** [comment]
Photoshop :)

**Comment by tobiashochguertel** [comment]
hm okay :) 

Thanks :+1:
