### ISSUE TITLE
No event $stateNotFound is emmited when type validation failed

### ISSUE THREAD

**Issue by knuhol** [angular-ui/ui-router#2352]
I am using types in URLs of my state definition, e.g. `/example/{id:int}`.

When the URL matches the type, e.g. `/example/1`, all is right. However, when it doesn't, e.g. `/example/text`, no event `$stateNotFound` is emmited.  

Is it a bug or is there any other way how to resolve these wrong URLs? I have defined `$urlRouterProvider.otherwise()` rule to show them as error 404, however no state is resolved now and user is left on the previous state.

I have opened related [question on SO](http://stackoverflow.com/q/33481881/3780766) yesterday (I supposed it is related with custom types and today I found out the same problem is presented also for predefined types). I also made an playground on [CodePen](http://codepen.io/Akarienta/pen/JYBXLO?editors=101).

**Comment by nateabele** [comment]
I think we've addressed this before. IMO parameter validation failure isn't the same thing as the state not existing.

**Comment by akarienta** [comment]
@nateabele Hmm, I don't think so - when the validation fails <=> the state for which the validation runs isn't matched <=> if any other state isn't matched, no state is found. Doesn't it? Anyway, doesn't matter which event should be emitted but should. These cases cannot been detected now and we are not able to react on them.

**Comment by nateabele** [comment]
> when the validation fails => the state for which the validation runs isn't matched => if any other state isn't matched, no state is found.

Not exactly. URLs will only ever match one `UrlMatcher`, so the fact that it advances to the validation step at all means a matching state/matcher _was_, in fact, found.

**Comment by akarienta** [comment]
@nateabele So do you think it is ok we cannot react on this situation? Or is there any possibility to redirect user to 404 error page when validation fails?

**Comment by nateabele** [comment]
I think we may punt on this till 1.0, since the architecture is better equipped to deal with it. @christopherthielen Is there an existing `$transitionsProvider` hook that would address this?
