### ISSUE TITLE
UI Router resets/reloads all named ui views

### ISSUE THREAD

**Issue by meeran0823** [angular-ui/ui-router#2353]
Hello,

I have two named views like below
ui-view="wellbeingStatus"
ui-view="vitalSigns"

Below it the state provider configuration,

```
$stateProvider
            .state('vitalSignsDashboard', {
                url: '/',
                views: {
                    '': {
                        templateUrl: 'App/dashboard/views/vital-signs-dashboard.html'
                    },
                    'wellbeingStatus@vitalSignsDashboard': {
                        templateUrl: 'App/dashboard/views/select-wellbeing-status.html'
                    },
                    'vitalSigns@vitalSignsDashboard': {
                        templateUrl: 'App/dashboard/views/view-all-vital-signs.html'
                    }
                }
            })
            .state('vitalSignsDashboard.selectedWellbeingStatus', {
                url: 'SelectedWellbeingStatus',
                views: {
                    'wellbeingStatus@vitalSignsDashboard': {
                        templateUrl: 'App/dashboard/views/selected-wellbeing-status.html'
                    }
                }                
            })
             .state('vitalSignsDashboard.selectWellbeingStatus', {
                url: 'SelectWellbeingStatus',
                views: {
                    'wellbeingStatus@vitalSignsDashboard': {
                        templateUrl: 'App/dashboard/views/select-wellbeing-status.html'
                    }
                }
             })
             .state('vitalSignsDashboard.vitalSignGraph', {
                 url: 'VitalSignGraph',
                 views: {
                     'vitalSigns@vitalSignsDashboard': {
                         templateUrl: 'App/dashboard/views/vital-sign-graph.html'
                     }
                 }
             })
             .state('vitalSignsDashboard.viewAllVitalSigns', {
                 url: 'viewAllVitalSigns',
                 views: {
                     'vitalSigns@vitalSignsDashboard': {
                         templateUrl: 'App/dashboard/views/view-all-vital-signs.html'
                     }
                 }
             })
```

Everything loads fine initially. 
Problem description:
I have links in each individual child views, which loads other templates in each respective named ui-view. After the initial load when I click on the links, navigation also works fine. But it reset the other child states to the initial templates without staying on the page which it was.

is this is a bug or has to do some code change.

Any help would be greatly appreciated.

Thanks
Meeran

**Comment by meeran0823** [comment]
any update on this???

**Comment by meeran0823** [comment]
Please provide update on this, as we are unable to move forward without this!!

**Comment by eddiemonge** [comment]
Can you put this in a plunkr please?

**Comment by meeran0823** [comment]
[Plunkr](https://plnkr.co/edit/jkbDWPpc2kINGj9a5N4p?p=preview)

issue:
1. first click on link(any)
2. then click on the other link
issue : this will reset the other named view state

**Comment by christopherthielen** [comment]
Thanks for making the plunker.

I looked it over, and everything seems to be working normally.  In your plunker, you have a parent state and two child states.  Each child state overrides a named view which is defined in the parent state.  When a child state is entered, the views that it defines are activated (and the named view in the parent state is overridden).  When the child state is exited, those views are deactivated.

Nested states probably do not make sense for individual elements of a dashboard.  I think a single dashboard component that can be configured would be more appropriate.  Substates could still be used appropriately to configure the component.

You could also try ui-router-extras "Sticky States", but I do not think the state-per-dashboard-component is the right approach.

**Comment by meeran0823** [comment]
So, you mean we cannot have two named view in one container. even if we have, we should not have links to load other templates, then I believe this is something killing the concept of named views (Just load once and show "Don't do anything more than that"). 

I have already used "sticky states" to get out of this problem. 

I want each item on the dashboard to work as an individual component as these components (template, controller) will be used in other places in application.

I believe this is a clear issue with named views, when I am navigating to a specific state only that component needs to be loaded.

**Comment by christopherthielen** [comment]
> we should not have links to load other templates

Correct.  Named views aren't something to be loaded imperatively.  They are a declarative way to populate a ui-view with a component when a state is activated.

> I want each item on the dashboard to work as an individual component as these components (template, controller) will be used in other places in application

That's a good approach. Make a dashboard component that manages dashboard-item-components.  I just don't think that these concepts make sense as application states.

> I believe this is a clear issue with named views, when I am navigating to a specific state only that component needs to be loaded, it should work as an independent section of the page

I disagree.  Named views work quite well as they were designed to work.  I think you are making incorrect assumptions about how they should be used.  I suggest not using named views for this problem set.

**Comment by meeran0823** [comment]
Hello, 

It is up to you guys whether you accept it as a bug or not, but people are expecting ui-router will work in this way. below is the link someone has posted on stackoverflow with exact same query

http://stackoverflow.com/questions/24798447/angularjs-ui-router-how-to-prevent-other-named-views-from-reloading-resetting

I agree ui-router is working as designed as you said but I believe that design itself is not correct because its making developers to think it will work in such a way.

Question in simple terms: when I change a state of one named view, why it is disturbing the other named view on the same page, it shouldn't right!!?? 

Thanks
Meeran

**Comment by christopherthielen** [comment]
> Question in simple terms: when I change a state of one named view, why it is disturbing the other named view on the same page

Because when a state is entered, its view configurations (`views: {}`) are applied to any matching `ui-view` active in the DOM.  When a state is exited, its view configurations are unapplied from any `ui-views`

Also, views from child states take precedence over views from parent state.  If a child view config targets the same ui-view in the DOM as a parent config, the child view config takes it over.

**Comment by jozsefmorrissey** [comment]
Hi, 

This is an old thread but I have to agree with meeran0823. If updating one view changes/removes the state of another view. I fail to see the purpose of having named views in the first place.
