### ISSUE TITLE
Typescript definition error when installed via bower

### ISSUE THREAD

**Issue by tgcandido** [angular-ui/ui-router#2354]
I believe this issue is related with #1990. When installed via bower, the router has an api/angular-ui-router.d.ts that is outdated. I believe this was fixed by removing the definition file, but bower downloads the file. I'm using Visual Studio 2015, and given how it works, one wrong definition file messes up all angular and router related types, so I can't just ignore the file and keep using the definition that is on borisyankov/DefinitelyTyped. I'm using bower 1.6.5, npm 3.3.10.

**Comment by eddiemonge** [comment]
pr welcome

**Comment by eddiemonge** [comment]
What is your bower.json file? What version of ui-router are you using?

**Comment by tgcandido** [comment]
ui-router version 0.2.15
You can reproduce the problem just by creating a new project and installing ui-router. The api folder with the Typescript definition is downloaded. If you download the latest release available https://github.com/angular-ui/ui-router/releases, the api folder is there. I suspect that by adding the folder api to the ignore property of bower.json you can fix the problem.

**Comment by eddiemonge** [comment]
Its been removed since 0.2.15 but a new release hasn't been done since then because of work on 1.0.0
