### ISSUE TITLE
Unexpected behavior on ^/:username

### ISSUE THREAD

**Issue by sparshy** [angular-ui/ui-router#2358]
Ui router is malfunctioning when using absolute url immediately followed by variable, the states following the state containing url `^/:username` malfunction

^/:username --> causing unexpected behaviour

    ^/username                     -->works fine
    /:username                      -->works fine               
    ^/profile/:username          -->works fine

**Comment by eddiemonge** [comment]
whats the unexpected behavior? Please provide a plnkr showing this

**Comment by sparshy** [comment]
http://plnkr.co/edit/liA3VL7Jd4lJlDsIgqYQ

clicking on signup, the view injected is of `user.profile` actually i think its redirecting there. It works fine in other cases I have mentioned above.

**Comment by nateabele** [comment]
It works fine if you put the `^/:username` state last.

**Comment by sparshy** [comment]
thanks working now
