### ISSUE TITLE
Html5mode still doesn't work.

### ISSUE THREAD

**Issue by celsomtrindade** [angular-ui/ui-router#2359]
Hey guys.<br />
I've been trying it for days, but still didn't made it work. No matter what I do, I can't make my `html5mode` work.

__The problem__

The problem with the `html5mode` is only happening on child states. If I access the address `myapp.com/City` it works fine. If i reload the page, also works fine. But if I'm in the address `myapp.com/City/NewYork` I can make the first load just fine. But if I reload the page there or try to access direct in that address coming from an external link (let's say google adwords), the page doesn't load.

__What i already did__

- Tried to follow these steps: [Link here](https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#issue-my-assets-and-templates-are-not-loading) But it didn't worked.
- Tried to use a `base` [like this answer](http://stackoverflow.com/questions/17200231/how-to-set-default-url-route). Still the same problem.
- Tried to use a rewrite code (I'm using apache) like in [the docs](https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-your-server-to-work-with-html5mode). But still the same problem.

Maybe I can solve if I manage to check if the rewrite property is write correctly (since I don't understand alot about it), this is the .htaccess file I'm using right now (working without `html5mode`):

    <IfModule mod_rewrite.c>
    	RewriteEngine On

    	RewriteCond %{REQUEST_FILENAME} -f [OR]
    	RewriteCond %{REQUEST_FILENAME} -d
    	RewriteRule ^(.+) - [PT,L]

    	RewriteCond %{REQUEST_URI} !=/favicon.ico
    	RewriteRule ^(.*) index.html

    	RewriteCond %{HTTP:Authorization}  !^$
    	RewriteRule .* - [E=REMOTE_USER:%{HTTP:Authorization}]
    </IfModule>

Does anyone knows how to solve this? I've tried everything and didn't worked for me.

**Comment by eddiemonge** [comment]
try asking in stackoverflow or the server version of that as ui-router works fine for me with multiple levels under nginx.
