### ISSUE TITLE
otherwise() does not catch the path after a state did not match regex

### ISSUE THREAD

**Issue by gevgeny** [angular-ui/ui-router#2361]
ui-router does not react to a route which has unmatched param in a state with regexp. Neither `otherwise` nor `$stateChangeError` are fired in the this case. 

Here is the demo http://jsfiddle.net/c22vL0h4/3/. Try to click to "foo route with empty value" link. Expected result is to navigate to the `otherwise` state since the path with empty value is not matched the regexp, but nothing happened.

The issue is reproduced starting with  v0.2.14. Checked in Chrome and IE11

**Comment by masterLei** [comment]
I want to know what a difference ng-include+ng-if between ui-route

**Comment by MattiJarvinen-BA** [comment]
Found about it while making parameter validations with `$urlMatcherFactoryProvider`. Even though defined types returned false UI-router didn't proceed to try the next possible state or otherwise.

My use case was tree like multimatch path:

```
frontpage .state('app.root', {url: ''}...

all pages .state('app.pages',{url: "/{page:pageUrl}"...
store .state('app.store,{url: "/store"...
all categories (might be nested) .state('app.store.category',{url: "/{category:categoryUrl}"...
product in a categories .state('app.store.category.product',{url: "/{product:productName}"...

/* url tree structure 
frontpage
|-page1
|-page2
\-store
  |-categoryName1
  | \- categoryName2
  |    \- productName1
  \-categoryName3
*/
```

**Comment by dsmrs** [comment]
I confirm, I'm not able to catch any "error event" when a url don't match with my regex. Either the `$stateNotFound` is not triggered.

Here the JSfiddle update with `$stateNotFound` http://jsfiddle.net/c22vL0h4/4/

**Comment by michalc** [comment]
+1 for 0.2.15, Chrome 52
