### ISSUE TITLE
ui-router ui-view causing some issues with Angular Material mdContent

### ISSUE THREAD

**Issue by Todd-Werelius** [angular-ui/ui-router#2362]
Using angular material 1.0.0.rc1 

Setting up a toolbar to scroll out of the way requires a sibling md-content. 

If you add a ui-view directive the scrolling stops working, removing it reverts to the intended behavior. 

```html
  <md-toolbar md-scroll-shrink ng-if="true" class="md-whiteframe-6dp">
  </md-toolbar>

  <!-- Main Content Viewing area -->
  <md-content ui-view>
  </md-content>
```

This [Codepen](http://codepen.io/Mopholo/pen/yYEjNQ?editors=100) shows the problem.  

The easy fix is to use replace the md-content markup with  

```html
  

  <!-- Main Content Viewing area -->
  <md-content>
     <ui-view>
     </ui-view>
  </md-content>
```

Looks like ui-view is cloning and replacing the md-content element and md-toolbar is still watching the original element ( now missing ) for changes 

Not sure if anything can be easily be done about this, also opened and issue with Angular Material Team

**Comment by eddiemonge** [comment]
Thats how ui-view currently works. Its not entirely expected but there are workarounds as you have found. Closing since its not really a bug but more of an implementation issue (with maybe better docs needed).

**Comment by Todd-Werelius** [comment]
Yeah, documentation might help on the ui-router side, or be completely ignored ;-) probably better on the AM side, and I opened an issue there as well. 

Angular Material edge case race condition, not sure how that could be easily resolved without heavy coupling.

**Comment by obamarodrigue** [comment]
Hello,
I would like to know if there is any solution to this issue today?!
For my cas, when i write all the markup in the index it works fine; but when i insert a ui-view tag, layout=column does not work anymore.... Don't know what to do.

**Comment by asaf050** [comment]
:+1: Have the same issue... there is any workaround for this?

Thanks

**Comment by asaf050** [comment]
Adding the following css might be a good workaround
`ui-view {
    display: inherit;
    width: 100%;
}`

**Comment by queryquandary** [comment]
Here's how I worked around the layout problem:

Create a CSS class like this:
```css
.injected-layout {
	position: absolute;
	top: 0;
	bottom: 0;
	left: 0;
	width: 100%;
	overflow: auto;
}
```

In the view that will be injected into the ui-view, wrap its content in a div and decorate it with the above class:
```html
<div class="injected-layout">
    <div layout="column" layout-align="center center" layout-fill>...</div>
</div>
```

**Comment by raphox** [comment]
To work with me, I did:

```
# index.html
  <body ng-app="app" layout="row">
    <md-content id="main" layout="column" flex>
      <ui-view name="main"></ui-view>
    </md-content>
  </body>

# router.js
  $stateProvider
    .state('app', {
      url: '/',
      views: {
        'main@': {
          component: 'app'
        },
        'toolbar@app': {
          component: 'toolbar'
        },
        'content@app': {
          component: 'podcastList'
        }
      }

    });

# app.component.js
<md-content layout="column" layout-fill>
  <md-toolbar id="toolbar" ui-view="toolbar"></md-toolbar>
  <md-content id="content" ui-view="content" flex></md-content>
</md-content>

# app.component.css
ui-view { display: inherit; }
ui-view > * { width: 100%; }
```
