### ISSUE TITLE
Multiple localized urls for a same state

### ISSUE THREAD

**Issue by turbulence** [angular-ui/ui-router#2371]
Hi,

I'm wondering how I could achieve the following:

www.mydomain.com/about (EN link)
www.mydomain.com/a-propos (FR link)

Both url should point to the same state:

```
.state('home',
{
	url: '/about', // or '/a-propos'
	templateUrl: 'templates/views/about.html',
	controller: 'AboutController'
})
```
and ideally, based on url, could it be possible to set a specific data to the state, like this:

```
.state('home',
{
	url: '/about', // or '/a-propos'
	templateUrl: 'templates/views/about.html',
	controller: 'AboutController',
	data:
	{
		lang: url === '/a-propos' ? 'fr' : 'en'
	}
})
```

Any help would be really appreciated.

Steve

**Comment by eddiemonge** [comment]
You could use child states. This is a better question for stackoverflow though

**Comment by nmpribeiro** [comment]
I would love to know if you found something about that @turbulence 
did you posted it on stackoverflow?

**Comment by turbulence** [comment]
@nmpribeiro 

I ended up with something like this... not the ultimate solution but it's ok for my Angular project needs.

`$stateProvider 
.state('en', 
{ 
	abstract: true,
	url: '',
	template: '<ui-view/>'
})
.state('en.about',
{
	url: '/about',
	templateUrl: 'templates/views/about.html',
	controller: 'AboutController'
})
.state('fr',
{
	abstract: true,
	url: '/fr',
	template: '<ui-view/>'
})
.state('fr.about',
{
	url: '/a-propos',
	templateUrl: 'templates/views/about.html',
	controller: 'AboutController'
});`

So on state change, I can split the state name, and load the appropriate locale file using angular-translate.

Hope it will help you.
