### ISSUE TITLE
Assign one general controller to a state with views.

### ISSUE THREAD

**Issue by alucardu** [angular-ui/ui-router#2373]
I have this state,

```
.state('home', {
  url: '',
  controller: 'addMovieCtrl',
  views: {
    "frontpage": {
      templateUrl: '../assets/angular-app/templates/_frontpage.html',
      controller: 'searchCtrl'
    },
    "movieoverview": {
      templateUrl: '../assets/angular-app/templates/_movieTemplate.html',

    }
  }
})
```

I would like to assign the `addMovieCtrl` controller to both the frontpage and the movieoverview view. But when I assign views to a state I can't also assign a controller to that state.

Now I have to create a empty container div with the `addMovieCtrl` controller assigned to it, like so,

```
.container{"ng-controller" => "addMovieCtrl"}
  %div{"ui-view" => "frontpage"}
  %div{"ui-view" => "movieoverview"}
```

**Comment by eddiemonge** [comment]
What would be the purpose of the `addMovieCtrl`?

**Comment by christopherthielen** [comment]
Controllers are broadly used for putting things on $scope.  Each ui-view has its own position in the scope tree, and thus they don't share $scope.  Because of that, a controller "on the state" is an ambiguous idea.    Normally, when you assign a controller and template to a state (without a `views:` block), it creates an unnamed `view:` configuration behind the scenes.

I'm not sure how you imagine a controller on the state for multiple views should work.  It's unlikely that this will ever happen. 

You could potentially define a resolve object to hold any shared statey stuff, then inject it into the views.  You could use the onEnter hook to do "state-level logic" on the resolve before the controllers are instantiated.

```
.state('home', {
  url: '',
  resolve: { context: function() { return {}; } },
  onEnter: function(context, MyFancyService) {
    context.bar = MyFancyService.calculateBar();
  },
  views: {
    "frontpage": {
      templateUrl: '../assets/angular-app/templates/_frontpage.html',
      controller: 'searchCtrl' // function(context, $scope) { $scope.context = context; }
    },
    "movieoverview": {
      templateUrl: '../assets/angular-app/templates/_movieTemplate.html',

    }
  }
})
```

**Comment by alex88** [comment]
I'm probably trying to do the same thing

basically me route is:

```
angular.module('app.views.visualization', ['ui.router.state'])
  .config(['$stateProvider', ($stateProvider) => {
    $stateProvider.state('visualization', {
      url: '/visualization/:id',
      controller: 'VisualizationCtrl',
      views: {
        navbarContent: {
          templateUrl: navbarContentTemplate
        },
        '': {
          templateUrl: mainTemplate
        }
      },
      parent: 'layout'
    });
  }])
```

the parent state is an abstract state to just have navbar and content:

```
<nav>
  <div class="nav-wrapper">
    <a data-ui-sref="login" class="brand-logo">Project</a>
    <div data-ui-view="navbarContent"></div>
  </div>
</nav>
<div ui-view></div>
```

What I wanted is to add a template in the navbar (to have a customized navbar content for that page) and the main template in the layout's `ui-view`. Why I need the controller shared between the views would be to just be able to call controller scope functions within buttons in the header bar and to display the current entity title in the header bar.

At the moment with that state code, the controller is never activated and so there's no way to use its functions within the templates. Is there a solution for this?

I've read some issues and seems that the common controller for multiple views was being implemented but maybe it has been also removed.

**Comment by lucianogreiner** [comment]
I understand your need, and even believe it would be nice to have a
controller for all sub-views, although i think it's not possible since you
may not have a way to explicit set or know what is the parent element to
bind this controller to.

Luciano Greiner
(51) 82355437

**Comment by alex88** [comment]
I see, so what's that solution? Service is to share data, but to run actions? Broadcast?

**Comment by lucianogreiner** [comment]
I used to put another abstract state in the middle so i have this shared
controller.

Luciano Greiner
(51) 82355437

**Comment by alex88** [comment]
Yeah but that also won't work bottom-up, well I'll figure that out, thank you!

**Comment by Mior** [comment]
I have similar issue.
My problem is that I have map integrated and base on zoom level I need to change menu and options around map represented as header and footer.
`<div ui-view="header"></div>
<map></map>
<div ui-view="footer"></div>`
base on click/scroll event I want to change child state and so header/footer change for new context like this.
`.state('main.closeup', {
                ... ,
                views: {
                    'header@main': {
                        templateUrl: "header_template.html"
                    },
                    'footer@main': {
                        templateUrl: "footer_template.html"
                    }
                }
            })`

I have logic controlling map in abstract parent `main` controller but I also need logic controlling particular closeup on its own controller. I can't do it other way around (map as child of menu) as when state change base on zoom level, I would lose map state and need to re-initialize and re-render map which is not acceptable UX.

How can I achieve this? I need single controller for groups.subs and another for groups.subs2 See [plunkr](https://plnkr.co/edit/uhzP1zE8j9N8jSCVZedX?p=preview)
