### ISSUE TITLE
double instance on slash in data

### ISSUE THREAD

**Issue by anisimkov** [angular-ui/ui-router#2374]
http://plnkr.co/edit/czVg7DoKgKDsKXzpWc1P
There is a 3 buttons in sample "Send #", "Send &" and "Send /".
The problem is with a third one.
Click on that after the click on another button 
causing the controller in the secondary state instantiated twice.
First instance got a right data in $stateParams.pns, second instance got a HTTP encoded data.
In the browser address line we see the double encoded pns field.
Next click to the "Send /" cause the right data arrived into the secondary state instance, but the pns parameter in the address line still double HTTP encoded.
There is a $log.debug calls in code to show twice instantiation.

The problem is in the 0.2.15 version and absent in the 0.2.14.

Best regards,
Dmitriy Anisimkov.

**Comment by eddiemonge** [comment]
Yeah this is a duplicate of the encoding problem. #1973
