### ISSUE TITLE
Documentation not loading for $stateParams

### ISSUE THREAD

**Issue by egeland** [angular-ui/ui-router#2379]
I tried to view https://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$stateParams but it doesn't load.

Apart from the page title changing to `UI Router: Error: Page Not Found` and the page being blank, there's no indication of anything wrong; no errors in Chrome Developer Tools JS `Console`, nothing failing to load in the `Network` tab..

I'm viewing with Chrome `46.0.2490.86 (Official Build) (64-bit)` on Linux Mint `17.2 Rafaela`.
It fails the same way on Firefox `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0` on the same machine.

**Comment by eddiemonge** [comment]
Also:
- https://angular-ui.github.io/ui-router/site/#/api/ng.$rootScope
- https://angular-ui.github.io/ui-router/site/#/api/ng.$q
- https://angular-ui.github.io/ui-router/site/#/api/ng.$injector

**Comment by danielkman** [comment]
@eddiemonge  It seems that there is no `$stateParams` page, that is why we get the error.
As for the other links, they are not ui-router modules so maybe clicking them should open a separate tab to the angular docs?

I can do a PR for the angular doc links and maybe open another issue for creating a `$stateParams` page.

WDYT?
