### ISSUE TITLE
Nested and multiple resolve

### ISSUE THREAD

**Issue by antonellopasella** [angular-ui/ui-router#2382]
If I define a resolve in both parent and child state, is there a way to force check FIRST the parent resolves and THEN (if all are resolved) resolve child's ones?

Pick this example.
https://github.com/angular-ui/ui-router/wiki/Nested-States-%26-Nested-Views#inherited-resolved-dependencies

If resA will be rejected, I won't resB to be fired.

Is there any way?

**Comment by KyorCode** [comment]
This is currently my problem too. Across nested states, resolves containing promises are all fired at once instead of firing them each state level. 

As far as I can see there isn't a way to coerce this.

**Comment by eddiemonge** [comment]
If resA is rejected, then it won't go to resB because the stateChangeError event will be fired and no more states attempted. If you want to do resB on resA then use a defer in that resolve and resolve a different thing based on the .then and .catch
