### ISSUE TITLE
`$urlRouter.sync()` example doesn't work as suggested

### ISSUE THREAD

**Issue by Francisc** [angular-ui/ui-router#2384]
Hi,

The code [here](http://angular-ui.github.io/ui-router/site/#/api/ui.router.router.$urlRouter):

``` JavaScript
$rootScope.$on('$locationChangeSuccess', function(evt) {
    // Halt state change from even starting
    evt.preventDefault();
    // Perform custom logic
    var meetsRequirement = ...
    // Continue with the update and state transition if logic allows
    if (meetsRequirement) $urlRouter.sync();
});
```

Seems to indicate that by doing that, you can "halt state change from even starting".
However, that doesn't happen.

Using this:

``` JavaScript
$rootScope.$on('$locationChangeSuccess',function(event){
    event.preventDefault();
    console.log('$locationChangeSuccess');
});

$rootScope.$on('$stateChangeStart',function(event){
    console.log('$stateChangeStart');
});
```

The console output will be:

```
$locationChangeSuccess
$stateChangeStart
```

The order is correct, but shouldn't the `$stateChangeStart` event not be fired?
The controller for the view is also instantiated, which I would expect should not happen.

The example seems to indicate that this should not happen.
Am I reading it wrong?

**Comment by eddiemonge** [comment]
I think the docs may be misleading because locationChangeSuccess means it was already successfully changed. console.log the url in both events to see.

**Comment by Francisc** [comment]
It works if you call `$urlRouterProvider.deferIntercept(true);` in the config-block.
Still, the code snippet is wrong in the docs. It does not work as it says it does.

**Comment by nateabele** [comment]
There are cases in which the behavior is nondeterministic, because the userland `$locationChangeSuccess` hook is attached (thus, invoked) _after_ the one used by `$urlRouter`.

**Comment by dgreene1** [comment]
commenting just to get updates. thanks.
