### ISSUE TITLE
Why event.preventDefault() after $state.go('state-name')

### ISSUE THREAD

**Issue by TheSachin** [angular-ui/ui-router#2386]
Hi,
I am quite new to this angular so I don't have deep knowledge.
For authentication purposes I am using [plunker](http://plnkr.co/edit/3kImqU?p=preview)
Now in order to transition to state
```
     $state.go('auth');
          event.preventDefault();
          return;
```
Why is the need of last two function calls?

**Comment by eddiemonge** [comment]
The preventdefault prevents the original state from changing. The return prevents the rest of the code from happening.
