### ISSUE TITLE
$state.go isn't defined when injected in controller in the minified version

### ISSUE THREAD

**Issue by NoHomey** [angular-ui/ui-router#2388]
$state.go isn't defined when  injected in controller in the minify version. (It's defined when used inside run function even transfering it via $rootScope has alot of side efects like second view and deboncing.
It works in none-minify but this s*cks for production purposes.

What s*cks even more is that it was really hard to find where the problem came with our project ...

**Comment by eddiemonge** [comment]
Sounds like your minifier isn't ng-annotating things. Try doing that and see if it fixes it. If not, I can reopen and investigate more.

**Comment by NoHomey** [comment]
I'm using the .min.js file you provide and the issue is even stranger the same code has the wierd problems when embbeded in html but works fine when included with src attr.

**Comment by eddiemonge** [comment]
Not in the ui-router, in your code. Is your build system annotating your code or are you using the array version to define your resolves, controllers, etc?

**Comment by NoHomey** [comment]
I'm using project_folder/node_modules/ui-router/release/angular-ui-router.min.js and I'm just writing it in my final script. What I mean is that my build system only minis my code not the code my code depends on.

**Comment by eddiemonge** [comment]
I know. Thats what I am talking about. Your code. Are you ng-annotating it? It sounds like you aren't.

**Comment by NoHomey** [comment]
I'm. All my "components" are following https://github.com/johnpapa/angular-styleguide.
