### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by redhead** [angular-ui/ui-router#2390]
Hello,
I wanted to ask if a release is going to happen soon. We need some fixes done to the master, but there is no release since May. Is there any release plan or scheduled roadmap?

**Comment by nateabele** [comment]
Soon. :smile: You can always build from master if you need to. See the docs for instructions.

**Comment by redhead** [comment]
Well, we do not know what state it is in, and we would rather download it via bower.. But it would be great if you could release more often, if you know it is releasable :) :) (I know I know, I don't want to sound like a douche) ;)

**Comment by nateabele** [comment]
No worries. Seriously, we're pretty close.
