### ISSUE TITLE
Data from $rootElement lost when setting ui-view on it

### ISSUE THREAD

**Issue by matoilic** [angular-ui/ui-router#2398]
If you set a ui-view directive on the root element of an Angular application, then at some point it will be replaced with a comment node. The comment node then becomes $rootElement. The problem with this is that the data from the original $rootElement is lost, e.g. $injector. 

I think this is a bug, since it leads to issues with libraries like ocLazyLoad. If ui-view is set on the root node, the original data from that element should be transferred to the comment node.

**Comment by eddiemonge** [comment]
Correct. Set ui-view as a child. This is known feature/bug
