### ISSUE TITLE
Is there are way to not treat empty string query param as undefined?

### ISSUE THREAD

**Issue by xak2000** [angular-ui/ui-router#2399]
I want to make search request by some query string. There is default value for this string if no search is specified. But if user explicitly specified empty search string, then it shoud do search by this empty string and not by default value. So I need differentiate empty string param from undefined param.

For example my param is `query`.
If `$stateParams.query` is undefined -> set it to some default value (`is:open` for example) then in `resolve` function use it for make ajax request.
If `$stateParams.query` is emtpy string -> do nothing! Not set it to default value as empty string in my case is absolutely legitimate value. So resolve function should make ajax request with this empty value.

Can I do this with ui-router config?
With this config
```
        params: {
          query: 'is:open'
        }
```
The problem is that when I do `$state.go('statename', {query: ''})`, then `$stateParams.query` became `undefined`. So ui-router treat it as `no value` and thinks "Oh! There is no value for `query` so I must set it to default value!". And sets it to `is:open`. But I want it to be `is:open` **only** if `query === undefined || query === null`. But not if `query === ''`.

**Comment by xak2000** [comment]
I debugging a little through source code and found undocumented state params config parameter `replace` which is array of `{from: x, to: y}` objects. By default it is `[{from: '', to: undefined}, {from: null, to: undefined}]` for optional or array-type parameters. But if user pass parameter with given key to params config object, then it overrides default config value.
So I make:
```
        params: {
          query: {
            value: 'is:open',
            replace: [
              {from: '', to: ''}
            ]
          }
        }
```
and it works like a charm!

Maybe this `replace` parameter should be documented?

**Comment by revir** [comment]
This really works!
And btw the config of `value` must be set explicitly with `replace`.

**Comment by christopherthielen** [comment]
This is documented as internal api in `feature-1.0` branch  c319e287211764a533cbefd45e0f98cc04af10a0
