### ISSUE TITLE
Split out resolver mechanism

### ISSUE THREAD

**Issue by wesleycho** [angular-ui/ui-router#2400]
I believe I mentioned this at some point before, but I would absolutely love if the resolve logic for constructing the resolve tree was split out to a separate repository - we have a good need of it in UI Bootstrap for handling modal resolves, and other libraries could potentially use this as well.

**Comment by christopherthielen** [comment]
@wesleycho can we close this since ui-bootstrap is now that you got the `$resolve` service wired up for ui-bootstrap?

**Comment by wesleycho** [comment]
Yep
