### ISSUE TITLE
state.go to a child state with an empty url

### ISSUE THREAD

**Issue by ddetkovs** [angular-ui/ui-router#2404]
Hi, when I set up a child state with an empty string as a url, state.go to this state doesn't make any transition. It's working if I set url to null though.

http://codepen.io/ddetkovs/pen/VvoxBa

**Comment by ddetkovs** [comment]
aaaand it's working with 0.2.14
http://codepen.io/ddetkovs/pen/PPMexK

**Comment by eddiemonge** [comment]
It does seem to be a regression.

Personally, this is how I redirect to child states at the moment:

```
  .state 'admin',
    url: '/admin'
    onEnter: ( $rootScope, $state ) ->
      deregister = $rootScope.$on '$stateChangeSuccess', ->
        if $state.is 'admin'
          $state.go 'admin.child'
        deregister()

```

**Comment by luposung** [comment]
It seems back at 0.2.17.
Replace empty string with null works.

**Comment by andertun** [comment]
(0.2.16 and 0.2.17) Replacing empty string with null works in Chrome, but it does not work in Firefox or Safari.
I downgraded to 0.2.15.
