### ISSUE TITLE
Multiple Named Views + Destroy $scope

### ISSUE THREAD

**Issue by jkossis** [angular-ui/ui-router#2405]
If I am using a state with multiple views, how do I destroy one of the view's scopes? I tried the following and it did not work:

```html
<div ng-if='showFilters' ui-view="filters"></div>
<div ui-view="tabledata"></div>
<div ui-view="graph"></div>
```

Even when $scope.showFilters set to false, the scope for the 'filters' view still exists. I wonder if the ng-if is only destroying its child scope, but doesn't know about the ui-view's scope. I appreciate the help.

**Comment by zanettin** [comment]
Hi @jkossis 

Have you tried to set the controller as well as the template(url) to null on the state def? I thought thats the way to do this.

**Comment by jkossis** [comment]
How would I do that conditionally? If I set them to null in the stateDef, they will always be null.

**Comment by zanettin** [comment]
What I was thinking off is, that you not just toggle the visibility of the ui-view, but change the state. Say you have state A with all ui views defined. In state A.B you get all the settings from the parent A but you can remove the views you not want. B.views { 'filter@' : { controller : null, template : '' }} hope I understand you right

**Comment by jkossis** [comment]
I understand what you mean, but I guess I am saying where do I do this?
When I initially config the app, I need to put the correct template and
controller cause I do want it to work at some point. Can I change template
and controller after the config phase when I conditionally want to destroy
it?

**Comment by zanettin** [comment]
I'm not sure if you can get this without a reload of the state. but you can modify the template url and controller at any time. accessing the state over $state service. $state.current.views.<your view name>.templateUrl... once changed, you have to reload the state. But again - theres no reason in my opinion, why you should not perform e regular state change to a new substate, where the view is not defined. with the solution above you have to revert the template again and again....

**Comment by eddiemonge** [comment]
What are you trying to accomplish by "destroying" the scope?

**Comment by jkossis** [comment]
I am trying to remove the controller from being active. Basically, it appears that when the ng-if changes from true to false, the ui-view visually gets destroyed, however the controller is still active.

**Comment by christopherthielen** [comment]
> however the controller is still active.

What is meant by this? Controllers run, and then are done. The scopes are destroyed when the angular removes the element, including ng-if.

This plunker should convince you that `ng-if` will indeed destroy the scope:  http://plnkr.co/edit/qH3yT5a40iFAqWTgMF8R?p=preview

If you can provide a plunk or something that demonstrates the issue, feel free to post it!
