### ISSUE TITLE
Multiple mutually exclusive query parameters require "double clicking"

### ISSUE THREAD

**Issue by CBenni** [angular-ui/ui-router#2407]
See http://plnkr.co/edit/PFhd2jCRPjXNqc2u6vpR (Open the seperate window view to see the query parameters)

Making the base path unique (for example, url: "/g/?group" and url: "/u/?user") fixes the issue, but in an ugly way.

You have to click each user twice for it to show up. I don't know what causes the issue, and if its a mistake on my end, please do tell me what I did wrong.

**Comment by eddiemonge** [comment]
Hmm thats tricky. Normally its the same route with the handing of the params in the controller

**Comment by CBenni** [comment]
Its certainly an edge-case and if it is too much of a change to fix, I might just use a single route with both parameters and make them mutually exclusive in code. Template handling can be done via functions too, so I will have to resort to that. 
Thank you.

**Comment by eddiemonge** [comment]
Yeah I was trying a few different things and couldn't come up with a simple, elegant way to do. Probably with more thought I could but maybe it would be better to rework the templates themselves to be able to handle this?

**Comment by CBenni** [comment]
Yeah thats the way I went with, it makes the UI smoother too (changing the data instead of the view allows transition animations to play). Thanks for looking into it, I appreciate that! Feel free to close the issue if theres nothing to add (there isn't from my side).

For anyone else wondering what my solution looks like, this is an excerpt:


			.state("dashboard.people", {
				url: "/people?group&user",
				templateUrl: "pages/people.html"
				controller: function($scope, $stateParams) {
					if($stateParams.group) {
						$scope.selected_group = $stateParams.group;
						$scope.group = $scope.groups[$scope.selected_group];
						$scope.selected_user = null;
						$scope.user = null;
					}
					else if($stateParams.user) {
						$scope.selected_user = $stateParams.user;
						$scope.user = $scope.users[$scope.selected_user];
						$scope.selected_group = null;
						$scope.group = null;
					} else {
						$scope.selected_user = null;
						$scope.user = null;
						$scope.selected_group = null;
						$scope.group = null;
					}
				}
			})

and in the template:

		<div ng-include src="'pages/groupproperties.html'" ng-if="selected_group" class="accesslist"></div>
		<div ng-include src="'pages/userproperties.html'" ng-if="selected_user" class="accesslist"></div>

**Comment by eddiemonge** [comment]
what happens if both are passed in?

**Comment by CBenni** [comment]
The "group" property gets precedence. This should never happen, since my links are set to only choose one. If the user messes with the urls, thats not my fault.
