### ISSUE TITLE
$stateParams lost on use of $injector.invoke()

### ISSUE THREAD

**Issue by royaldark** [angular-ui/ui-router#2411]
We have a pretty complex series of routes, with many complicated resolves. In an effort to clean up our code, I refactored some common behavior out of the resolves. These helper methods need access to both Angular DI and arbitrary variables. So, they have a structure like the following:

```
var helper = function($stateParams) {
  return function(arbitraryVariable) {
    doSomethingWith($stateParams, arbitraryVariable);
  }
}
```

These are then invoked by resolve blocks like below:
```
.state('whatever', {
  resolve: {
    resolveA: function($injector, $stateParams) {
      $injector.invoke(helper)(arbitraryVariable);
    }
  }
})
```

In the `resolveA` block, the `$stateParams` are correctly populated. However, the helper function invoked via `$injector` shows `$stateParams` as the empty object.

I could pass `$stateParams` as a non-DI variable to the helper, but that sort of defeats the purpose of DI.

Why does this behavior happen? I have a hunch it's related to [this comment](https://github.com/angular-ui/ui-router/issues/1856#issuecomment-93025037). Is there a way around this?

**Comment by nateabele** [comment]
> Why does this behavior happen? I have a hunch it's related to this comment.

Correct. Also: https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#issue-what-is-the-difference-between-stateparams-and-stateparams

> Is there a way around this?

Yes.

```javascript
resolve: {
  resolveA: function($injector, $stateParams) {
    $injector.invoke(helper, null, { $stateParams })(arbitraryVariable);
  }
}
```
