### ISSUE TITLE
Typed routes configured before the custom type break the type

### ISSUE THREAD

**Issue by gggritso** [angular-ui/ui-router#2412]
Ran into an issue yesterday while trying to use `$urlMatcherFactoryProvider` to add a custom parameter type. I had two separate `config` blocks, one setting up the custom `type`, and one adding the actual routes. I discovered that if I tried to set up the routes before I declared the custom parameter type, the custom type wouldn't get declared correctly.

[This Fiddle](https://jsfiddle.net/gs7g2hua/2/) shows the issue. The route doesn't resolve correctly. If you change the order, and configure the custom type before the routes, the route resolves.

**Comment by eddiemonge** [comment]
Pretty sure the config blocks are order dependent. You could always make a module for the custom one that the main app relies on: https://jsfiddle.net/t0n4r7kq/

Yup confirmed on https://docs.angularjs.org/guide/module
> Then Angular applies configuration blocks in the same order they were registered
