### ISSUE TITLE
ui-router injects template in multiple views.

### ISSUE THREAD

**Issue by alucardu** [angular-ui/ui-router#2413]
I have multiple divs containing a `ui-view` element, all with the same name `container-big`. I've setup a ` ui-sref` so that when it's clicked router-ui injects a template into the `container-big` view. My problem is that it does so for every ui-view, also those who are outside the original div clicked. 

http://plnkr.co/edit/B7CRjvdQ9paytwl5csKi?p=preview

So I am wondering if it is possible to restric the inject action only on the ui-view inside the container that is clicked. Or maybe pass the `movie_id` to the state controller

**Comment by eddiemonge** [comment]
Not the way you have it setup. And that doesn't seem the best way to have that app setup.

**Comment by christopherthielen** [comment]
When a state is activated, ui-router finds all the matching `<ui-view/>` and fills them in, by design.
