### ISSUE TITLE
Contact service in sample code

### ISSUE THREAD

**Issue by zirho** [angular-ui/ui-router#2418]
I think it would be more clear if uiRouterSample.contacts.service is in uiRouterSample.contacts's dependency list, since contact.service is being used only in contacts module.

Also it is more clear and feels right because it's in the contacts folder.
If anyone wants to re-use this module in other projects, only thing they need to do is include contact module in their root app dependency list.

like this
```
angular.module('uiRouterSample', [
  'uiRouterSample.contacts',
  'uiRouterSample.utils.service',
  'ui.router',
  'ngAnimate'
])
```

```
angular.module('uiRouterSample.contacts', [
  'uiRouterSample.contacts.service',
  'ui.router'
])
```

**Comment by eddiemonge** [comment]
You could submit a pull request to change this. The sample was a quick example, not an indepth, best practices guide. There are probably a lot of things that could be improved on it.
