### ISSUE TITLE
$stateProvider documentation isn't obviously available

### ISSUE THREAD

**Issue by Microserf** [angular-ui/ui-router#2419]
`$stateProvider.state` is the most logical place to start learning about how `ui-router` can be configured, and yet, the documentation for this method is not easily viewable in the docs made available here: http://angular-ui.github.io/ui-router/site

The `$stateProvider` module is not listed in the Table of Contents/sidebar. When you access the `ui.router.$state` module, all you see is the documentation for `$state` itself (as expected).

If, however, you _search_ for `$stateProvider` first, _and then_ click on `ui.router.$state`, _only then_ will you see the documentation for `$stateProvider`.

The search also yields only two other documents containing references to `$stateProvider`, and in both cases, the text is found in a code example and is not hyperlinked.

**Comment by nateabele** [comment]
I'm not sure how it could be made any more obvious than this:
<img width="257" alt="ui_router__ui_router" src="https://cloud.githubusercontent.com/assets/18288/11786838/cafe1262-a256-11e5-969d-da833ae2f20b.png">

**Comment by Microserf** [comment]
Ah. I knew I was missing something. Thanks!

It's a bit of a confusing interface element, in my opinion. If you look at the rest of the ToC, the right column is used to group and qualify the elements in the left column:

![screen shot 2015-12-14 at 2 03 39 pm](https://cloud.githubusercontent.com/assets/4295636/11790877/1ae42ad6-a26c-11e5-8588-ce1c1749e1bd.png)

`ui.router.router` is a `module`
`$urlRouter` is a `service`
`ui-sref` is a `directive`, etc.

I saw the `Provider` label, but because it was in the right column, I read that as `$state` is a `Provider`. It didn't occur to me that this was a separate entry.

Also, the selected state doesn't distinguish between the main or the `Provider` entry, making it seem as one.

**Comment by eddiemonge** [comment]
They kind of are one.

The Provider *link* is differentiated from the grouping because of the different styling (color, size, casing, icon).

While I agree its not the most intuitive, its does work and after the first clicking it, it should be more clear. If you have a suggestion on how to improve it while still keeping things automated, please feel free to submit a pull request.

**Comment by nateabele** [comment]
It's a standard template for Angular projects, so it's kind of a wider 'issue', if you can call it that.
