### ISSUE TITLE
Redirect to state is not working

### ISSUE THREAD

**Issue by vkozyref** [angular-ui/ui-router#2421]
Hello all. I want to change url without reload the page. For it I use $state.go('main.someState', {/*some options*/}, {notify:false}). It works good. Also there is a link for the redirect to a home page. It calls a method with $state.go('main.home'). And there is no redirection to home state after clicking that link. When I click second time it works. Also it works correctly with default notify: true parameter.

**Comment by eddiemonge** [comment]
This is a known bug but not really a known workaround. A search for notify: false should bring up a couple of duplicates of this. 1.0.0 will have a better solution for this as notify false is problematic
