### ISSUE TITLE
State with negative int parameter fails to activate

### ISSUE THREAD

**Issue by jvisser** [angular-ui/ui-router#2422]
When a state with an int parameter /url/{id:int} is activated where the value of the parameter is negative (-1) the state does not activate and the default route is activated. 

This works in version 0.2.13 but fails in the latest version of 0.2.15.

**Comment by nateabele** [comment]
Please post a Plunkr that demonstrates the issue. Thanks.

**Comment by jvisser** [comment]
forgot to mention we use $state.go('state', {id: -1}) for this. ui-sref seems to work fine.

**Comment by nateabele** [comment]
Okay. Please post a Plunkr that demonstrates the issue.

**Comment by jvisser** [comment]
http://plnkr.co/edit/6JX9dqvgBeFkcMPCeQxR?p=preview

The state with negative int parameter is activated correctly then directly afterwards (from the same browser event) the url specified by $urlRouterProvider.otherwise() is activated.
Seems like the target state with negative id is not recognized properly so the default route url is activated. 

As said this problem only started showing after updating from 0.2.13 to 0.2.15.

**Comment by nateabele** [comment]
Fixed in 1.0 here: b1fb874a19160801c0bad2dac72d35dae5cf8ed8.

Please open a PR if you'd like to backport the fix to 0.2.x.
