### ISSUE TITLE
Dynamic TemplateUrl function written in array form is not working

### ISSUE THREAD

**Issue by InfinityOne** [angular-ui/ui-router#2430]
So i have 

```javascript
$stateProvider.
    //...many states...
  state('help', {
    url: '/help{params:.*}',
    templateUrl: ['$stateParams', function($stateParams) {
      return '/site/getHelpTemplate/name' + $stateParams.params;
    }],
    /*templateUrl: function($stateParams) {
      return '/site/getHelpTemplate/name' + $stateParams.params;
    },*/
    controller: 'HelpCtrl',
  });
```

if I write it in default form (commented), it works perfectly, but I'm minifying my code, so I need the array form, but it's not working, this is what I get

```
http://local/$stateParams,function%20($stateParams)%20%7B%20%20%20%20%20%20return%20'/site/getHelpTemplate/name'%20+%20$stateParams.params;%20%20%20%20%7D
```

instead of

```
http://local/site/getHelpTemplate/name/someParam
```

Not a big master in Angular, but I guess it's not evaluating something, or did I miss something?
I'm using AngularJS v1.4.7 & ui-router v0.2.15

**update**
I have found [this](http://stackoverflow.com/questions/29999499/ui-router-minification-of-templateurl) answer on stackoverflow, which works

**Comment by christopherthielen** [comment]
`templateUrl` is not an injected function.  It is always called with a single parameter: the `toParams`.  There is no need to annotate it or use array notation.
