### ISSUE TITLE
Controller is called twice with custom url parameter type

### ISSUE THREAD

**Issue by Jurigag** [angular-ui/ui-router#2431]
I have such a code:
http://pastebin.com/8sC7nAEp
If im using this parameter in:

```
url: "/{name:spaceReplace}",
```

Then my controller is called twice, if i change spaceReplace for string for example then its called only one time. Whats going on?

Also its called actually only when there are spaces in parameter, if not its called only one time.

Also its called like that only if i access url by ui-sref. If i access it manually then there is no problem.

**Comment by catk** [comment]
I had a similar problem with a custom type being used for prettifying dates in the URL; the route change would be called twice, and thus the controller would also be instantiated, destroyed and the instantiated again. I resolved it be providing an "equals" method for my custom type.

For example:

```JavaScript
var spaceReplace = {
    // original "encode", "decode", "is" methods
    equals: function(a,b) { return a === b; }
};
```

**Comment by atkinchris** [comment]
I had a similar problem with a custom type being used for prettifying dates in the URL; the route change would be called twice, and thus the controller would also be instantiated, destroyed and the instantiated again. I resolved it be providing an "equals" method for my custom type.

For example:

```JavaScript
var spaceReplace = {
    // original "encode", "decode", "is" methods
    equals: function(a,b) { return a === b; }
};
```

**Comment by Jurigag** [comment]
Well i will check it in work. I hope it works. I have one time bindings so from user side there is no diffrence, but it still had to do request for get something etc.

**Comment by atkinchris** [comment]
If you change equals to always return true, does the double loading go away (not suggesting this as a fix; just diagnostic)?

**Comment by Jurigag** [comment]
Yea it works with return true ! Also its working how it should be, whats the diffrence ?

**Comment by atkinchris** [comment]
Working how it should is a happy coincidence. :)

From the docks, the `equals` method:
>Determines whether two decoded values are equivalent.

From your code sample, I'd suggest that your `equals` method returned if, when both passed through the `decode` method, the outputs matched.

**Comment by christopherthielen** [comment]
Sounds like this was cleared up?
