### ISSUE TITLE
Not able to test with Selenium and Phantomjs

### ISSUE THREAD

**Issue by Leo-G** [angular-ui/ui-router#2432]
My code 

The problem is that since the elements are inside the ui-view , they are not detected, how do I solve this?

  from selenium import webdriver
        from selenium.webdriver.support.ui import WebDriverWait

        driver = webdriver.PhantomJS(service_args=['--ssl-protocol=any'])

        driver.get("http://scaffold-ubuntu/#/devs/new")
        print(driver.current_url)
        print(driver.page_source)

        name=driver.find_element_by_id('name')
        name.send_keys("Your Title text here")

        driver.close()

**Comment by eddiemonge** [comment]
Have you tried using protractor.js? If not, you have to query the page until that element becomes available.

also, this is outside of the scope of ui-router.
