### ISSUE TITLE
initial url routes are #/ instead of /#

### ISSUE THREAD

**Issue by Nosthertus** [angular-ui/ui-router#2434]
for some reason, the router sets this url format.. i am running the application by executing the html files.. i don't know if this could be the reason.. but it has given me plenty of headaches because when i try to access a different state, for example `calendar`, i would try to access it with `#/calendar`, although this didn't work, i had to create the url from the state just to see how it has to be. turns out it is like this `#//calendar`. i am going to provide the code i have set in the angular config, just if i missed something that makes this weird url format

```javascript
(function(angular){
	var app = angular.module('test', ['ngMaterial', 'ui.router']);

	app.config(['$stateProvider', '$urlRouterProvider', '$mdThemingProvider', function($stateProvider, $urlRouterProvider, $mdThemingProvider){
		$stateProvider.state('login', {
			url: '/login',
			templateUrl: 'views/site/login.html',
			controller: 'LoginController'
		});

		$stateProvider.state('site', {
			url: '/',
			views: {
				'@':{
					templateUrl: 'views/layout/index.html'
				}
			}
		});

		$stateProvider.state('site.calendar', {
			url: '/calendar',
			views: {
				'main@site': {
					template: 'views/calendar/index.html',
					controller: 'CalendarController'
				}
			}
		});
	}]);
})(angular);
```

**Comment by sahibjotsaggu** [comment]
It's because your urls are `/login` they only need to be `login` (without the forward slash).

**Comment by Nosthertus** [comment]
@sahibjotsaggu i understand that.. i just found this out because i was loading the page through html files.. although i used to use `ng-router` with `/login`..

**Comment by christopherthielen** [comment]
In http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$stateProvider, `url` is:
> A url fragment with optional parameters.
The url fragment (fragment, meaning partial url) is for the state being defined.  When computing the full url, it is concatenated to the parent urls.

Your `login` state doesn't have a parent, so its url is essentially absolute `/login`.  However, `site.calendar` has url `/calendar`, while `site` has url `/`.  So `/` + `/calendar` is `//calendar`
