### ISSUE TITLE
Wildcard support in $state.is() and $state.includes()

### ISSUE THREAD

**Issue by gsklee** [angular-ui/ui-router#244]
I am doing some app that given the following state hierarchy:

```
choose
choose.color
choose.size
(more choose.x)
choose.color.category
choose.size.category
(more choose.x.category)
```

I need to apply some CSS classes when the state is in the second hierarchy but not the third.

Currently the only way to do so seems to be hard-coding every possible state:

```javascript
$state.is('choose.color') && $state.is('choose.size') && ... // listing out all other second hierarchical states
```

It would be nice if we can simply do something like `$state.is('choose.*')`.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
