### ISSUE TITLE
How to show a view for (mostly) every state

### ISSUE THREAD

**Issue by crazyjat** [angular-ui/ui-router#2440]
My html has 3 views:

&lt;nav ui-view="navigation"&gt;&lt;/nav&gt;
&lt;section ui-view="content"&gt;&lt;/section&gt;
&lt;footer ui-view="footer"&gt;&lt;/footer&gt;

I want the contents of the nav element to always be my page navigation except when the user is on the login page (login state). How can I do this with ui-router?

**Comment by christopherthielen** [comment]
Define a parent state for your non-login states that has the views filled in

http://bit.ly/UIR-SOF
