### ISSUE TITLE
please remove!

### ISSUE THREAD

**Issue by mattiLeBlanc** [angular-ui/ui-router#2443]
I figured out the issue myself and I want this thread removed.
Sorry for that.

**Comment by Exlord** [comment]
You can do it yourself. There is a `Close Issue` button next to the `Comment` button.

**Comment by mattiLeBlanc** [comment]
Sorry, I couldn't find that option. I only have a comment button (however that might be because you already closed the issue). Thanks for closing.  Sorry for polluting your issue list.
