### ISSUE TITLE
Add on option to allow Reload html template when $state.reload() is called

### ISSUE THREAD

**Issue by Exlord** [angular-ui/ui-router#2444]
Hi,
Currently when i call `$state.reload()` only the controller file is reloaded from server, but it would be nice if the html template also would be reloaded from the sever.
This is very useful in development environments so that when we have some changes in the controller or html template we just reload the current state and not the hole page.
This would make development much faster.

**Comment by nateabele** [comment]
I don't think we're gonna address this through UI Router. What you actually want to look at is `$templateCache`. You could get fancy and try to integrate with LiveReload, or just poll your templates with `$http` every few seconds.
