### ISSUE TITLE
deep state doesn't seem to work

### ISSUE THREAD

**Issue by Nosthertus** [angular-ui/ui-router#2446]
I have made a question in `stackoverflow` about this and the link to the post is [here](http://stackoverflow.com/questions/34652603/angularjs-ui-router-deep-state-does-not-work)

the state i am trying to redirect is a 3rd nested stated `layout.projects.create` but the link renders as `#/projectsprojects/create`

please check the post in `stackoverflow` to see all details

**Comment by nateabele** [comment]
Please respect the sanctity of the issue tracker for bugs. Thanks!
