### ISSUE TITLE
is current scopes' destroy order reasonable?

### ISSUE THREAD

**Issue by e-cloud** [angular-ui/ui-router#2449]
All begin with a sample:
http://jsbin.com/wesugo/edit?html,js,console,output

* when the page initially loaded, child view loaded first, parent view loaded after.
* when the page is destroyed, parent scope destroy first and child scope destroy after.

*are all this kind of things reasonable?*

in my use case, when the whole parent view is destroy, i need to do some cache cleaning after child scope die and when parent scope is dying. Obviously, it seems to be impossible now.

Am i got the smelly programming philosophy? Or it's just something not perfect with ui-router?

**Comment by eddiemonge** [comment]
This is the order according to your example:
 - Parent is loaded then child is loaded.
 - Parent is destroyed then child is destroyed.

The destroy part is slightly odd but the load part is correct (the way I said it, not the way you said in your post).
You can see this in the simplified example: http://jsbin.com/cejaniyezi/edit?js,output

Not sure if the destroy order is right. Why can't you do the cache clean on the child $destroy scope event?

**Comment by e-cloud** [comment]
I walked through your bin, and found out what are different.
The load part you refer to is **the controller instances' initiation order**, 
and what I refer to is **the views' initiation order**.

The reason, that the cache clean need to be done on parent scope $destroy event, is some data are shared between child state which are required when switching between child state.

I got a bin(http://jsbin.com/vinizi/edit?js,console) with more details.

Another weird thing is **the parent view is loaded twice**(see the console)

**Comment by khaledosman** [comment]
having the same issue.. going all the way back to version 0.2.15 seems to fix the problem

**Comment by eddiemonge** [comment]
Have you tried 0.3.1 yet to see if it fixes this?

**Comment by christopherthielen** [comment]
Yes I think this was fixed in 0.3.0

**Comment by khaledosman** [comment]
seems to be fixed, thanks!
