### ISSUE TITLE
1.0 alpha redirectTo example not working

### ISSUE THREAD

**Issue by temka1234** [angular-ui/ui-router#2450]
I am using "1.0.0alpha0" version of ui-router and example with redirectTo not working.

Code inside config of base module:
```javascript
$transitionsProvider.onStart({
  to: function(state) {
    return state.redirectTo;
  }
}, function($transition$, $state) {
  var targetState = $state.target($transition$.to().redirectTo);
  return $transition$.redirect(targetState);
})
```
There is no errors in console, log inside callback function works.

If ```return $transition$.redirect(targetState);``` replace with ```return targetState;``` than transition works fine (without url changing).

**Comment by nateabele** [comment]
Can you post your state definition?

**Comment by temka1234** [comment]
Plunker example http://plnkr.co/edit/Jy7jQT?p=preview

**Comment by christopherthielen** [comment]
Hi @temka1234 
We made some last minute changes to redirect from transition hooks.  The `$transition$.redirect` function is no longer necessary, and will be removed in alpha 1. As you noted, you can simply return the `TargetState` from the transition hook to redirect the transition.

**Comment by temka1234** [comment]
@christopherthielen, Thanks for the reply!

Can you help with few questions related ui-router-extras
* How to get previous and rejected state after transition finish? Should i use $previousState from ui-router-extras? In code of ui-router-1.0 i see ```previous``` method but it used only with ```$transition$.redirect```
* What functionality from ui-router-extras will deprecated with ui-router 1.0?

**Comment by lucianogreiner** [comment]
Hello.

It does really work returning the target state directly, but it doesn't work retuning it through a promise:

$transitionsProvider.onStart({
			to: function(state) {
				return state.authenticated;
			} 
		}, function($state, LoginService) {
			return LoginService.loggedIn(function(loggedIn) {
				return $state.target('login');	//testing - not working
			});
		});

**Comment by nateabele** [comment]
If a transition is redirected, you can access it through `$transition$.previous()`. It also has `from()` and `to()`, and is available for injection in most (all?) hooks.

**Comment by christopherthielen** [comment]
@temka1234 can you explain to me in more detail what you mean about previous and rejected state after transition finish?

Using your example as as starting point, in which context do you mean "previous and rejected state after transition finish"?
```
$transitionsProvider.onStart({
  to: function(state) {
    return state.redirectTo;
  }
}, function($transition$, $state) {
  return $state.target($transition$.to().redirectTo);
})
```

**Comment by eddiemonge** [comment]
Closing as the original issue seems resolved and this is now just follow up questions on different things. If that is not correct, I can re-open this.
