### ISSUE TITLE
Allow to skip url parameter encoding for custom type

### ISSUE THREAD

**Issue by fracz** [angular-ui/ui-router#2452]
Currently, there is no way of using custom characters in URLs like [proposed here](http://stackoverflow.com/questions/34716650/how-to-use-tick-in-url-for-boolean-get-parameter) (using `✓` for true and `✖` for false values). Every value is passed through `encodeURIComponent()` call [here](https://github.com/angular-ui/ui-router/blob/a7d25c6/src/urlMatcherFactory.js#L347) and there is no way to skip it. Custom types should have an ability to skip URL encoding when desired.

This is somehow related to https://github.com/angular-ui/ui-router/issues/1119.

**Comment by nateabele** [comment]
This is implemented with raw types in 1.0.
