### ISSUE TITLE
$state is not defined

### ISSUE THREAD

**Issue by telbiyski** [angular-ui/ui-router#2453]
```
var app = angular.module('app', ['ui.router.router']);
 
app.config(function ($urlRouterProvider) {
  $urlRouterProvider.when($state.url, function ($match, $stateParams) {
    if ($state.$current.navigable !== state ||
        !equalForKeys($match, $stateParams) {
     $state.transitionTo(state, $match, false);
    }
  });
});
```
$state is not defined???

**Comment by eddiemonge** [comment]
That's correct. You have not defined `$state` there. It looks like you are trying to use the code from the wiki that it says it uses internally but you can't really do that. Instead look at the example https://github.com/angular-ui/ui-router/wiki/url-routing#rule-for-custom-url-handling
