### ISSUE TITLE
URL doesn't change after transition hooks is called.

### ISSUE THREAD

**Issue by tankiJong** [angular-ui/ui-router#2455]
I found this problem in my own work. I will explain this bug by the the [sample](https://github.com/christopherthielen/new-state-vis). 

The example is quite nice but i noticed that the URL didn't correctly changed. You may saw this bug by the following steps:
1. run the app (now you're still **unauthenticated**)
2. for convenience, you may directly visit this route.  http://localhost:xxxx/new-state-vis/#/mymessages/inbox/  (change xxxx to your port)

(chris edit: http://christopherthielen.github.io/new-state-vis/#/mymessages/inbox/5648b50cc586cac4aed6836f )

and the bug appears. you will find the page has already jump to the login page but the url kept unchanged.

PS.    In this example, **onBefore** hook is applied.

**Comment by christopherthielen** [comment]
Thanks for the bug report.

**Comment by christopherthielen** [comment]
Looks like "resync'ing the url when transition is cancelled" was something only done in the deprecated state events. We'll have to migrate that behavior to the TransitionManager, I believe.  

0.2.17: e00aa695e41ddc5ebd5d2b226aa0917a751b11aa

**Comment by christopherthielen** [comment]
minimal reproduction: http://plnkr.co/edit/7ZJEeUkAdEfiOFhvJiWH?p=preview

**Comment by christopherthielen** [comment]
@tankiJong were you doing a redirect in your `onBefore` hook, or something else?

The scenario in the plunker I posted one post up happens for the following reason:

The original transition occurs when ui-router checks the URL and transitions to the proper state.  When we sync the state to the URL like that, we use `location: false` in the transition options.  That option is used so the URL doesn't get re-pushed after the transition is complete.  When the redirect occurs, we re-use the previous transition's options, (including `location: false`).  

If your hook is doing a redirect, you can add `{ location: true}` to the options, i.e., `$state.target('foo', undefined, { location: true })` as a workaround.


---

I'm thinking about this and wondering what the correct behavior should be.  Should we propagate the redirected transition's options or not...

I'm also wondering if we need `location: false` for transitions that happen when when synchronizing *from* the url

**Comment by tankiJong** [comment]
@christopherthielen 
Regardless the code logic, I think the url should always maps the state name and be checked up at some key point.

In addition, is there any way to change the URL without reload the controller?
