### ISSUE TITLE
Using angular.copy for stateParams strips away some object properties.

### ISSUE THREAD

**Issue by andreisoare** [angular-ui/ui-router#2456]
I'm trying to pass a whole object to `ui-sref`, but it seems that it doesn't get sent to the destination route with all its properties.

This is because you use `angular.copy` for all `stateParams`. Anything that has been defined on the object using [defineProperty](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) does not work with `angular.copy` for example.

Am I doing something that isn't meant to be supported by ui-router?

Thanks!

**Comment by christopherthielen** [comment]
> Am I doing something that isn't meant to be supported by ui-router?

Yes, since we use angular.copy, we can't support your use case at this time, sorry.

There's a chance we can support it after 1.0.  $stateParams code is still changing in 1.0 alpha 0, specifically to support dynamic params.

**Comment by eddiemonge** [comment]
What are you trying to accomplish?

**Comment by nicmae** [comment]
Same problem here with beta 4, passing a Restangular object. The angular.copy made by the router strips some binding in the object. To copy a Restangular object we have to do a Restangular.copy. I did not have this problem with version 0.2.*.

https://github.com/mgonto/restangular#copying-elements
> Before modifying an object, we sometimes want to copy it and then modify the copied object. We can't use angular.copy for this because it'll not change the this binded in the functions we add to the object. In this cases, you must use Restangular.copy(fromElement).

**Comment by eddiemonge** [comment]
What is it you are trying to accomplish by passing an object in?

**Comment by nicmae** [comment]
I have a page type `product/:productId/edit` and uses the param to pass the clicked object to edit. Maybe not the best solution but I found it efficient.

**Comment by eddiemonge** [comment]
Why arent you just passing in the actual params needed instead of the whole object?

**Comment by nicmae** [comment]
I need the full Restangular object as I edit his properties in the edit form. The advantage is i only have to make a `.save()` on the object and as it's a Restangular object he knows the API endpoint for saving the object datas.
As all my objects are kepts by a service, I will use it to retrieve the object by his id. That way no need to pass the whole object.

**Comment by eddiemonge** [comment]
Yeah that seems like a better solution
