### ISSUE TITLE
$state.go with notify: false option error

### ISSUE THREAD

**Issue by k-one-o-two** [angular-ui/ui-router#2457]
I've got a controller ListCtrl and there is something like
`$state.go($state.current.name, {page: $scope.currentPage}, {reload: false, notify: false}); (used for the pagination).`
The problem is that ListCtrl controller is being called after changing the state to another (i.e. not $state.current).

Changing notify to true fixes an issue, but destroys my pagination logic.

I've found a temporary solution: set some var on `$stateChangeStart` to true and to false on `$stateChangeSuccess`, then use in a controller like `$rootScope.stateChanging || init();`. It works but seems strange to me.

Is there something I'm doing wrong or it's a bug?

**Comment by j1nX1988** [comment]
+1

**Comment by dougarp** [comment]
+1

**Comment by christopherthielen** [comment]
`notify: false` has so many side effects that it is deprecated.  We're replacing the functionality with something called dynamic parameters for final 1.0 release.

I apologize, but we're not going to be addressing any `notify: false` issues in 0.2.x

**Comment by Etheryte** [comment]
See https://github.com/angular-ui/ui-router/issues/1758
