### ISSUE TITLE
Integer/Float URL Parameters, Maintain Type

### ISSUE THREAD

**Issue by rynz** [angular-ui/ui-router#246]
Consider a state which has `url: '/example/{exampleId:[0-9]}'` and that we navigate our application to `/example/5`.

Inspecting `$stateParams` the result is `{exampleId: "0"}` and thus `exampleId` is a string. If we later use this result to perform ajax queries or other operations we may run into a few issues and have to convert the string at the client or server side.

Perhaps `$stateParams` could check if the value is an integer/float and store it as such, else store as string? Or have a an additional option within the `url:{}` param to determine if it is to be stored as a string or not?

**Comment by xDisfigure** [comment]
**FYI - Using Int params type with "offlimit number"**
Becareful using `int` as parameter type with than kind of number `116410000002753064`.

If you pass 116410000002753064 into Number/String like uirouter `int` params does.
```
Number(116410000002753064) // output: 116410000002753060
Number(116410000002753064123123912) // output: 116410000002753060000000000
```

Same using `String()`

I had to put [0-9]+ pattern on my param to make it work as expected.
