### ISSUE TITLE
ui-sref-opts allowedOptions error

### ISSUE THREAD

**Issue by ifokeev** [angular-ui/ui-router#2460]
https://github.com/angular-ui/ui-router/blob/4da7e5913d504e975a91fbb3d7efd57cbe472077/release/angular-ui-router.js#L4125

Something is wrong here. Why do we need these allowedOptions? It breaks ```{notify: false}``` for the directive ```ui-sref-opts```

**Comment by eddiemonge** [comment]
https://github.com/angular-ui/ui-router/issues/2457#issuecomment-173008225
