### ISSUE TITLE
Multilang Url navigations

### ISSUE THREAD

**Issue by diskomaxime** [angular-ui/ui-router#2461]
Hi, i'm tying to keep my selected language when i change my route.

Actually i'm failing every time, i don't understand what is missing or how to keep my :lang usable.

   //Set default route
    $urlRouterProvider.otherwise('/en/');

    $stateProvider
      .state('home', {
        url: "/:lang/",
        templateUrl: 'app/controllers/main/main.html',
        controller: 'MainController'
      })
      .state('routeBt', {
        url: "/:lang/directors-cut",
        templateUrl: 'app/controllers/routeb/routeb.html',
        controller: 'routeBCtrl'
      })
      ;

    $locationProvider.html5Mode(true).hashPrefix(':lang');

How i can i keep my :lang, and also trying to change language regarding the path.

Thx

**Comment by christopherthielen** [comment]
use nested states, and define the `:lang` parameter on the parent state.  For further help related questions, please use StackOverflow; this issue tracker is for bugs and feature requests.

http://bit.ly/UIR-SOF
