### ISSUE TITLE
Reload page for urls that don't match any state while avoiding infinite reload

### ISSUE THREAD

**Issue by mrahhal** [angular-ui/ui-router#2462]
My application is not spa in its entirety, so I'd like urls that don't match any rules to just cause a full reload. I know about `target="_self"` but having to watch for that is really painful and sometimes impossible in my situation. I spent a lot of time in the source of `$location` and `ui-router` and haven't figured out a way to do that yet.

The main problem is that ui-router doesn't expose the collection of rules and doesn't provide lower level api to check if a url matches a rule (as far as I know). So is there a way to accomplish what I want?

```
'/news/2' -> match -> load partial view according to the state that matched
`/about` -> no match -> let's do a full page reload on '/about'
```

There are a couple of things to watch for to avoid endless page reloads for example that kept me from finding a solution. I can accomplish what I want if I edit the code in `urlRouter`. If only the `oldUrl` param from the `$locationChangeSuccess` event was given to the `otherwise` (or more generally provided to the rule) function this would have been simple.

[Full so question.](http://stackoverflow.com/questions/34794387/reload-page-for-urls-that-dont-match-any-state)

**Comment by eddiemonge** [comment]
What do you mean by:

> having to watch for that

You add the tag and it opens the page.

You could also add a rule in the for `.otherwise()` in the $urlRouterProvider that does a $location.url('/url') or a window.location = 'url'
