### ISSUE TITLE
Unknown provider "eventProvider" when binding to event from $transitions object

### ISSUE THREAD

**Issue by jaandrews** [angular-ui/ui-router#2465]
I'm trying out the 1.0.0alpha0 release pulled down via npm, but I get an unknown provider error when I bind to the onEnter event from the $transitions object. The error message I get is
>Error: [$injector:unpr] Unknown provider: eventProvider <- event
http://errors.angularjs.org/1.4.8/$injector/unpr?p0=eventProvider%20%3C-%20event
    at https://code.angularjs.org/1.4.8/angular.js:68:12
    at https://code.angularjs.org/1.4.8/angular.js:4334:19
    at Object.getService [as get] (https://code.angularjs.org/1.4.8/angular.js:4482:39)
    at https://code.angularjs.org/1.4.8/angular.js:4339:45
    at getService (https://code.angularjs.org/1.4.8/angular.js:4482:39)
    at Object.invoke (https://code.angularjs.org/1.4.8/angular.js:4514:13)
    at ResolveContext.invokeNow (http://run.plnkr.co/xuY1Zy7zrSSoME2m/angular-ui-router.js:1431:51)
    at http://run.plnkr.co/xuY1Zy7zrSSoME2m/angular-ui-router.js:1419:31
    at processQueue (https://code.angularjs.org/1.4.8/angular.js:14792:28)
    at https://code.angularjs.org/1.4.8/angular.js:14808:27

I've set up a plunk at http://plnkr.co/edit/6BpHiphv3JbQKebo4ULn. The error message appears in the console.

I have confirmed that onEnter **does** work when it's part of a declared state's parameters.
```
$stateProvider.state('caseStudy', {
  url: '/portfolio/:project',
  onEnter: function() { ... }
}
```
Is this a bug, or is there a dependency I'm unaware of?

**Comment by nateabele** [comment]
The `onEnter` hook is an injectable function. You can inject `$transition$` or `$state$`. There is no event value.

**Comment by jaandrews** [comment]
I tried injecting $transition$ and $state into the test function, but I get unknown provider errors when I do that. I've updated the plunk to inject $transition$, so the error can be seen. I've been going off of the documentation at http://angular-ui.github.io/ui-router/feature-1.0/interfaces/transition.ihookregistry.html, but it's not clear where the $transitions object used in the examples comes from. I assume it's using '$transitions' to inject it, since that **does** returns a TransitionService, but that's not working for some reason.

**Comment by nateabele** [comment]
Again, the _`onEnter`_ function is injectable. _That_ is the one that can receive the special values noted above. See: http://plnkr.co/edit/remNys?p=preview

**Comment by jaandrews** [comment]
Ah, thanks for the clarification. I didn't realize that the parameters of the callback were being run through the injector.

**Comment by nateabele** [comment]
Yeah, no worries. I know we're still short on docs and examples.
