### ISSUE TITLE
In the template, how to use the variables defined in the controller

### ISSUE THREAD

**Issue by kevin1220** [angular-ui/ui-router#2466]
I'v definded a status like this :
`
.state('slider',{
        url:'/slider',
        templateUrl:'templates/slider.html',
        // template:'<span ng-bind="chong"></span>',
        controller:'sliderCtrl'
    })
`
and definded a variables as $scope.name=kevin, I want to use this variable in the template slider.html,
my way now like this：

`
{{names}}
`

but it doesn't work.
What should I do?

**Comment by blokfyuh** [comment]
Are you sure it's not a typo => `name` instead of `names` ?

**Comment by kevin1220** [comment]
After the correction it still is not working

app.js:
``
$scope.name = 'kevin';
``
slider.html:
``
{{name}}
``

**Comment by blokfyuh** [comment]
You need to provide more of your codebase (controller + template). We can't currently help you.

**Comment by kevin1220** [comment]
some codebase like these,is anything else shoud be provided?
config:
``
app.config(function($stateProvider, $urlRouterProvider) {
    // For any unmatched url, redirect to /state1
    $urlRouterProvider.otherwise("/");
    //
    // Now set up the states
    $stateProvider
    .state('home',{
        url:'/',
        templateUrl:'templates/pluginlist.html',
    })
    .state('slider',{
        url:'/slider',
        templateUrl:'templates/slider.html',
        controller:'sliderCtrl'
    })
});
``

controller:
``
app.controller('sliderCtrl', ['$scope', '$http', '$window', function($scope, $http, $window) {
    $scope.name = 'kevin';
}])
``

slider.html:
``
<div class="swiper-slide slide-red">{{name}}</div>
``

**Comment by blokfyuh** [comment]
Inside slider.html, try to wrap your `{{name}}` by `<div ui-view></div`.

**Comment by kevin1220** [comment]
Yes,my index.html is like this :
``
<body ng-app="app">
    <div ui-view=""></div>
</body>
``

It seems that I can get the template by `<div ui-view=""></div>`, but in the template,my `{{name}}` is not working.

**Comment by kevin1220** [comment]
I think I have known why my codebase does not work.
I should set the controller for the class called `swiper-slide` instead of the its parent element  when I use the swiper framework
