### ISSUE TITLE
at 1.0 alpha, $element not work

### ISSUE THREAD

**Issue by jeilsoft** [angular-ui/ui-router#2467]
I can't inject $element in Controller at ui-router 1.0.0alpha0

**Comment by nateabele** [comment]
Can't inject it where? Can you post a plunkr demonstrating the issue?

**Comment by christopherthielen** [comment]
I made the plunk https://plnkr.co/edit/IKTpSXDmlcgWsw93yZYq?p=preview

**Comment by christopherthielen** [comment]
Looks like in 0.2.15 we are doing this:
https://github.com/angular-ui/ui-router/blob/master/src/viewDirective.js#L308

but in 1.0.0 we are only doing this:
https://github.com/angular-ui/ui-router/blob/feature-1.0/src/ng1/viewDirective.ts#L292

I'm surprised we don't have a test for this.

**Comment by nateabele** [comment]
Yeah, seems like an easy fix though, fortunately. @jeilsoft Thanks for the report.
