### ISSUE TITLE
[q] are you still planning to release 0.2.16?

### ISSUE THREAD

**Issue by ZuBB** [angular-ui/ui-router#2469]
Hi there!

I noticed that you cooked an alpha version of 1.0 release. At reddit there was small thread on that and  someone asked about 0.2.16 release which is still present in your milestones page. there was not answer on that so I would like to know if it is still in your roadmap. I am really interested in https://github.com/angular-ui/ui-router/pull/2212 but not sure if I wanna move to 1.0 right now

Thanks in advance

**Comment by christopherthielen** [comment]
Yep, we want to release 0.2.16.  The main thing I wanted to fix before releasing 0.2.16 is consistent bidirectional encoding/decoding of slashes in parameter values.  I've seen a number of issues on the tracker that are related to this problem, e.g., #2172.  That's the blocker for 0.2.16 in my mind.

**Comment by ZuBB** [comment]
Do you have any approximate estimate for that?

**Comment by christopherthielen** [comment]
done.

**Comment by ZuBB** [comment]
thanks for notification
