### ISSUE TITLE
ui-view in Jade file doesn't work

### ISSUE THREAD

**Issue by robhicks** [angular-ui/ui-router#247]
This seems to follow the documentation for nested states.

http://plnkr.co/edit/fp09uXZ8xM2suQBwvXr7

EDIT: updated title for more clarity.

**Comment by jseminck** [comment]
Issue still exists and just ran into it. Spent quite some time trying to figure out what was wrong until I found this thread. Using .ui-view still works.

**Comment by deneboulton** [comment]
This has just bit me too, wasted a couple of hours on it until I noticed the diff in the html that was generated :<

**Comment by leandroz** [comment]
I solved it adding ```doctype html```

**Comment by hanaarena** [comment]
I defined the sub router in express router so solve the render jade template problem.

like below:

```javascript
$stateProvider
  .state('gallery-index', {
     url: '/index',
     templateUrl:  'temp/index'
  })
  .state('gallery-info', {
     url: '/info',
     templateUrl: 'temp/info'
  });

 $urlRouterProvider.otherwise("/index");
```

in express router file:

```javascript
router.get('/temp/index', function(req, res) {
  res.render('temp/index')
});

router.get('/temp/info', function(req, res) {
  res.render('temp/info')
});
```

hope that help others people...

**Comment by CJBrew** [comment]
@hanaarena are your template files called "temp/index.jade"? There's no file extension on the templateUrl in your example; when I've tried this I have to explicitly set `templateUrl: "path/filename.pug"`. Have you got some setting in the main app that interprets the filename?

Also I don't like having to set a route explicitly for every route. It's not very DRY. I wonder whether there's a way to use a wild-card...?

**Comment by hanaarena** [comment]
@CJBrew I have set `jade` as my app default view engine so I can just use `res.render(viewName)` and express know what view file I want.uh..I have not use `templateUrl` yet and not found in express.com api doc :(

yeah..jade work with ui-router is confused for me sometime. also never use wild-card
