### ISSUE TITLE
how to redirect url if add '/' to same state in ui router

### ISSUE THREAD

**Issue by naveencasp** [angular-ui/ui-router#2473]
Actually state url is http://localhost:3001/admin-login#/app/dashboard

new url : http://localhost:3001/admin-login#/app/dashboard/

if i add '/' to the url it has to redirect to same old url

how to redirect in ui router

**Comment by christopherthielen** [comment]
I think you are looking for `strictMode`
http://angular-ui.github.io/ui-router/site/#/api/ui.router.util.$urlMatcherFactory

http://bit.ly/UIR-SOF

**Comment by naveencasp** [comment]
Thank you so much
