### ISSUE TITLE
ui.router does not replace view

### ISSUE THREAD

**Issue by amlang** [angular-ui/ui-router#2476]
Hey everybody,
I have a small problem and do not understand where I made the mistake.
Here is a link to [Codepen](http://codepen.io/amlang/pen/OMQVvo/)
The initial view, as well as the first state to be displayed properly, but when I click on the link of the first reloaded view the next state does not appear. The URL is modified but the new content will not be reloaded.

Any idea?

**Comment by christopherthielen** [comment]
You're missing a `<div ui-view></div>` in your template for `new`

http://bit.ly/UIR-SOF
