### ISSUE TITLE
ui-router 1.0.0 external links

### ISSUE THREAD

**Issue by michaelwarren1106** [angular-ui/ui-router#2477]
Hey all,

First off, thanks for the GREAT product! We are currently using this for our angularJS apps across a very large organization, and its great.

The question I have is about a feature that was listed as an enhancement for 0.2.16 and whether or not it made it into 1.0.0

https://github.com/angular-ui/ui-router/issues/395

We currently have a library of angularJS components (directives + scss style) that we install in our apps as much as possible. We templatize these directives with config/content JSON objects so that our consuming applications can just configure them, instead of having to write them from scratch, so we have a situation like this:

```
<header our-header-directive="configObj"></header>


<!--   which turns into -->

<header>

    <nav>
        <ul>
            <li ng-repeat="item in navItems>
                 <a href="{{ item.url }}">{{ item.name }}</a>
                 <!-- in our example item.url could be 'http://www.google.com' or a state ref/internal relative url-->
            </li>
        </ul>
    </nav>

</header>

```

in 0.2.15, dynamic ui-srefs INSIDE of custom directives didnt work, so we have to use href instead of ui-sref. We'd like to be able to use ui-sref if possible. I dont see any documentation about this feature being added in 1.0.0. Can you please verify?

Thanks!

**Comment by nateabele** [comment]
Hasn't been merged in yet.

**Comment by michaelwarren1106** [comment]
thanks for the fast response. Any estimate for what milestone it might be? is development on the 0.2.x branch going to keep going in parallel to 1.0.0, or do you guys plan a cutover?

**Comment by nateabele** [comment]
Not sure yet. 0.2.x will still have at least one more release.

**Comment by michaelwarren1106** [comment]
ok thanks for the info! Is there at least a working approach for dynamic links in directives? if so, maybe I could look at a PR? I haven't explored much of the project, but this feature would be awesome for us, so if i could help it along in anyway, i'm game.

**Comment by christopherthielen** [comment]
Merging in the ui-state etc directives should be pretty easy if somebody wants to submit a PR. I'm juggling about a hundred other things and this took a back seat

**Comment by christopherthielen** [comment]
https://github.com/angular-ui/ui-router/issues/2223

This is the commit that needs merging in https://github.com/angular-ui/ui-router/commit/3831af1dc71b601351e6694af0665a77297f8f7f

**Comment by christopherthielen** [comment]
Merged ui-state directive
a428b2f209297979ae86b1dcaf9347b998b3aa2d
