### ISSUE TITLE
AngularJS and SEO clarification

### ISSUE THREAD

**Issue by jsantana90** [angular-ui/ui-router#2480]
I'm trying to figure out what's the best way it is to make an angularJS web app SEO friendly.

I've read this http://stackoverflow.com/questions/13499040/how-do-search-engines-deal-with-angularjs-applications

and it recommend using: `<meta name="fragment" content="!">` as my web app is using html5mode.

The website runs good when accessing the root url `/` and browse normally to the other areas, but as soon as I reload/refresh the website (when I'm not in the root url) it returns `url not found` `Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.`

Right now, what I understand is that using this trick, google will be able to crawl the website normally? I also added a tried creating a sitemap using this third party website https://www.xml-sitemaps.com/ but returned with only one url (the root url).

My website doesn't have a server like node, it's just plain angularJS.

What is the correct way to fix all this?

Thanks!

**Comment by nateabele** [comment]
I think this is a question for StackOverflow. This tracker is only for support with UI Router bugs and feature requests. Thanks. http://bit.ly/UIR-SOF

**Comment by mostafabarmshory** [comment]
I have the same problem
