### ISSUE TITLE
isOptional is always true

### ISSUE THREAD

**Issue by swisstofu** [angular-ui/ui-router#2483]
When checking this line of code (https://github.com/angular-ui/ui-router/blob/02e98660a80dfd1ca4b113dd24ee304af91e9f8c/src/urlMatcherFactory.js#L923)

```javascript
if (type.name === "string" && !arrayMode && location === "path" 
  && config.value === undefined)
  config.value = ""; // for 0.2.x; in 0.3.0+ do not automatically default to ""
var isOptional = config.value !== undefined;
```

i noticed that if you have a definition like `url: '/{language:(?:fr|en|de)}'`, language will be treated as an optional parameter because of code above

i didn't find any workaround for now, but would it be possible instead to write 

```javascript
if (type.name === "string" && !arrayMode && location === "path" 
  && config.value === undefined)
  config.value = ""; // for 0.2.x; in 0.3.0+ do not automatically default to ""
var isOptional = !!config.value;
```

any advice ? 

thanks

**Comment by swisstofu** [comment]
hello, a PR has been created https://github.com/angular-ui/ui-router/pull/2492 with a unit test regarding this bug.

**Comment by christopherthielen** [comment]
This code is only in `legacy` where path parameters are optional by default.  We can't change that behavior until version 1.0.  In the 1.0 code, this should be working as expected, with the parameter being non-optional.
