### ISSUE TITLE
Reset $state without using $state.go()

### ISSUE THREAD

**Issue by jml6m** [angular-ui/ui-router#2486]
First off, I think the overall issue here is that AngularJS still doesn't have a sensible, best practice way of "restarting" the app and all its components. So far, the best practice seems to be setting the path to a "default" view, and then reloading the window. We do this in our /logout state, as seen here:

    $stateProvider.state('logout', {
        onEnter: function($state, $window, store) {
            //Remove any session variables
            store.remove('varA');
            store.remove('varB');

            //"Logout" the user
            $state.go('login');
            $window.location.reload();
        }
    })

However, this is a bad user experience. The user can actually see the view change and the components on the page shift before the window reloads. It just seems very buggy overall.

Originally, we did not include `$state.go('login')`, and did not get the weird experience of seeing the view change before logout. However, when we started using $state handlers like `$rootScope.$on('$stateChangeStart', function (event, toState, toParams)`, we noticed that `toState` was not being reset after the window reload. So `$stateChangeStart` would trigger after the reload, and `toState` would still be set to whatever view the user was on before calling `/logout`. This isn't a true app reset!

**Possible Solution:** I think all of this can be solved if there was a way to "reset $state" without using the `$state.go()` method...something that happens behind the scenes instead.

**Comment by nateabele** [comment]
I'm pretty sure this is more of an app design issue, but if you can reduce it down and post a plunkr, we can possibly take a look.

**Comment by eddiemonge** [comment]
This seems like it should be a service that gets called to reset your store params and then $state.go to your home page.

**Comment by jml6m** [comment]
@nateabele I will post plunkr when I get a chance
@eddiemonge I am afraid of circumventing the window reload because there could be components in the inner workings of the Angular library that aren't reset unless window is reloaded. At least, from reading online, this seems to be a common method of "restarting" the app

**Comment by christopherthielen** [comment]
I don't think this is a ui-router concern (nor, really an angular concern).  In my opinion, it is the app developer's responsibility to reset application state. 

I'm not understanding this statement: 
> we noticed that toState was not being reset after the window reload. So $stateChangeStart would trigger after the reload, and toState would still be set to whatever view the user was on before calling /logout.

We don't (can't) maintain state across a browser reload... the only thing I can think of is that maybe the URL was still set to the old state, then we matched the url to the state on bootstrap?

**Comment by jml6m** [comment]
I've created a very basic plunk to experiment with: https://plnkr.co/edit/xoTMLsl1SYjjeA8cFFIJ?p=preview

As you can see, whenever "logout" is clicked at the top, it goes to `/logout`, calls `$window.location.reload()`, and returns as the same state. You can test this by clicking "Route 1" before clicking "Logout", and comparing the console logs to a scenario where you click "Home" before clicking "Logout".

I'd like to have the user land on `/index` whenever they logout, except in my _real life app_, redirecting to index _before_ calling `$window.location.reload()` creates a weird UX. Is there a way to tell "set the state" without using `$state.go()`, so after I do a window reload(), it loads a state of my choosing?

If this is not possible then I will just live with the current UX.

**Comment by christopherthielen** [comment]
You're reloading the browser before the state change has completed.

Wait for the transition to finish first, then reload the browser.
https://plnkr.co/edit/ixqRNG3xToOvC0HtLWOp?p=preview

**Comment by jml6m** [comment]
@christopherthielen This didn't address my problem at all...it's the exact same behavior

**Comment by christopherthielen** [comment]
@jml6m the behavior is quite different for me.  In my plunk, I am at `/index` after the page reloads.  What do you see?

I also added `{notify: false}` to the plunk to avoid the transition before refreshing

**Comment by jml6m** [comment]
@christopherthielen adding `{notify: false}` was exactly what I needed, thanks
