### ISSUE TITLE
ref is not defined using ui-sref-active with ui-state

### ISSUE THREAD

**Issue by arcxyz** [angular-ui/ui-router#2488]
When combining the new uiState directive with uiSrefActive I get an error. It is related with this line of code where `ref` is not defined:

https://github.com/angular-ui/ui-router/blob/87f10dfc9c4b0420ae6128bb46499deb75f3e705/src/stateDirectives.js#L181

**Comment by eddiemonge** [comment]
@nateabele Is that a typo?

**Comment by nateabele** [comment]
Weird... looks like yeah.

**Comment by christopherthielen** [comment]
Apparently we could use some more coverage for the new directive
