### ISSUE TITLE
path/ not matching path/:something now in 0.2.17

### ISSUE THREAD

**Issue by shadybones** [angular-ui/ui-router#2490]
code:
$urlRouterProvider.when('/project/:id','/project/:id/summary');

0.2.15 : matched "project/" and "project/1" ( "project/" forwarded to "project//summary")
0.2.17 : matches "project/1" only  ( "project/" stays where it is)

Is this the new expected behavior or a bug?

**Comment by eddiemonge** [comment]
I feel like this is a bug correction but it could also be a breaking change. @nateabele

**Comment by christopherthielen** [comment]
http://bit.ly/UIR-Plunk

**Comment by christopherthielen** [comment]
can you try moving the `$urlRouterProvider.when('/project/:id','/project/:id/summary');` to the top of your config block?

Are you trying to do a "default substate" of the `project` state?  There's a more state-machine way to do that:

If a transition is headed for 'project', cancel it and go to 'project.summary' instead.
```
$rootScope.$on("$stateChangeStart", function(evt, toState, toParams) {
  if (toState.name === 'project') {
    evt.preventDefault();
    $state.go('project.summary', toParams);
  }
}
```

That chunk of code can be generalized to:

```
$rootScope.$on("$stateChangeStart", function(evt, toState, toParams) {
  if (toState.redirectTo != null) {
    evt.preventDefault();
    $state.go(toState.redirectTo, toParams);
  }
}

...
$stateProvider.state('project', {
  url: '/project/:id',
  // declare a default substate, which the $stateChangeStart listener will notice
  redirectTo: 'project.summary'
  template: ...
  controller: ...
});
```

**Comment by christopherthielen** [comment]
Still waiting on a plunker, but I think this was related to #2501
