### ISSUE TITLE
Regression in 0.2.17: $stateChangeStart doesn't fire anymore

### ISSUE THREAD

**Issue by dsine-de** [angular-ui/ui-router#2491]
The ```$stateChangeStart``` is fired e.g. on page load or on state changes in 0.2.16 and down, but not anymore in 0.2.17.

**Comment by eddiemonge** [comment]
Can you do a plnkr demonstrating this?

**Comment by dsine-de** [comment]
So - the "build" directory contents (```node_modules\angular-ui-router\build```) apparently changed. I included ```angular-ui-router.js``` from there all the time, but with the 0.2.17 release, the npm package content changed.

When I'm using the correct file from ```node_modules\angular-ui-router\release```, it works.

**Comment by christopherthielen** [comment]
What changed?

**Comment by dsine-de** [comment]
The contents of the ```build``` directory when installing ui-router through npm. Before v0.2.17, the ```build``` and ```release``` directories inside the package contained exactly the same files (```angular-ui-router.js``` and ```angular-ui-router.min```), just a version comment was different between the files in these directories.

Since v0.2.17, the ```build``` directory seems to contain webpack versions of these files, so I had to replace the path in my build process.

**Comment by christopherthielen** [comment]
I see. We didn't intend to distribute the build dir at all.

**Comment by christopherthielen** [comment]
@nate I think you published a 1.0 alpha as part of the 0.2.17 release :p

**Comment by nateabele** [comment]
That's odd, the release process is supposed to overwrite the old version. `release` is the correct path anyway.

**Comment by christopherthielen** [comment]
I added build to npmignore

**Comment by nate** [comment]
@nate chiming in. I think you meant @nateabele

**Comment by nateabele** [comment]
Haha, yes. :-)
