### ISSUE TITLE
$state.go(path, params) not work when use it in app.run()

### ISSUE THREAD

**Issue by heimuya** [angular-ui/ui-router#2494]
I want to redirect to the 'login' state when someone is not login yet or the access token is expire, so I should watch the 'stateChangeState' event, and judge the status according some infomation from the api. If user is not login, I will use $state.go('login') to chage the state. However, $state.go is not working, and not show the login page. the code as following:

```javascript
angular.module('app')
  .run(
    ['$rootScope', '$state', '$stateParams', '$cookieStore',
      function($rootScope, $state, $stateParams, $cookieStore) {
        $rootScope.$state = $state;
        $rootScope.$stateParams = $stateParams;

        $rootScope.$on("$stateChangeStart", function(event, toState, toParams, fromState, fromParams) {
          if(toState.name === 'login') return;

          if (!$cookieStore.get('authInfo') || !$cookieStore.get('authInfo').access_token) {
            $state.go('login', {from: fromState.name, message: 'not login'});
          }
        });

        $rootScope.$on('tokenInterceptor', function(errorType) {
          $state.go('login', {from: $state.current.name, message: errorType});
        })
      }
    ]
  )
```
hope someone could help me, thx.

**Comment by christopherthielen** [comment]
Hi, thanks for your interest in ui-router. 

1) Are you sure $state.go is being called?  
2) You should call `event.preventDefault()` to stop the existing transition in its tracks.


This tracker is for bugs and feature requests.  Questions like this are best asked and answered by the community.

http://bit.ly/UIR-SOF
