### ISSUE TITLE
Separated ui-view 

### ISSUE THREAD

**Issue by nadien** [angular-ui/ui-router#2495]
Hi, i have an issue. I'm doing a page completely with angular, and it have 2 parts:

- Landing page for register and login (here are the first <ui-view>).
   *header only have 2 tabs and 2 views

- Admin page (here will be another <ui-view> separated from the first). Only users can see this part
  *header have 10 tabs and a lot of views

When i login success, the nav header seems equal in both parts and i can not show different nav header

How can i show separated nav headers and views?

Maybe i'm a little sleepy now, any help will be appreciated.

**Comment by christopherthielen** [comment]
Thanks for your interest in ui-router!

This tracker is for bugs and feature requests only.  Help or "how to" questions should be asked on a Q&A forum such as StackOverflow.

http://bit.ly/UIR-SOF
