### ISSUE TITLE
templateProvider not returning template

### ISSUE THREAD

**Issue by iamdriz** [angular-ui/ui-router#2499]
I have the following `templateProvider`:
~~~
templateProvider: function($timeout, $stateParams, templateService)
{
	return $timeout(function () {
		return templateService.getTemplate($stateParams, '/introduction/vision-for-health-and-wellbeing.html');
	}, 100);
}
~~~
and the service that gets the template:
~~~
.factory('templateService', ['$templateRequest', '$translate', function($templateRequest, $translate) {
	return {
		getTemplate: function(stateParams, url) {
			return $templateRequest( 'partials/' + ( $translate.use() ? $translate.use() : $translate.preferredLanguage ) + url); 
		}
	}
}]);
~~~

However the state never loads and I don't get any errors. What's wrong?

Also any links that reference this state don't do anything... so it's like the module is just bombing out but not reporting what the issue is.

**Comment by thuanitdn** [comment]
i also have the same problem with angular permission

**Comment by christopherthielen** [comment]
Can you post a plunker? 

http://bit.ly/UIR-Plunk

**Comment by iamdriz** [comment]
@christopherthielen Think this should show the issue: http://plnkr.co/edit/tgTddy6Y3xeJO2hgOACR?p=preview (I've removed the $translate from this example as I don't believe it's relevant to the issue and it looks to be still breaking.)

**Comment by iamdriz** [comment]
Okies, I have managed to fix this by upgrading to the latest versions of all scripts.
