### ISSUE TITLE
0.2.16 and 1.0.0alpha0: ui-sref-active has slight delay

### ISSUE THREAD

**Issue by pavel-blagodov** [angular-ui/ui-router#2503]
I noticed that ui-sref-active has slight delay that leads to flickering of elements with that directive. This is especially noticeable in case of reload: true, but that's not the issue if we are using ng-class="{selected: ('app.state' | includedByState)}

**Comment by nateabele** [comment]
Weird. Can you post a plunkr that demonstrates the issue?

**Comment by pavel-blagodov** [comment]
https://plnkr.co/edit/KYUqAvNWbGq5om6Qne11?p=preview

**Comment by christopherthielen** [comment]
I'll take a look at this before alpha.1

**Comment by christopherthielen** [comment]
This was introduced in 0.2.16 https://plnkr.co/edit/4gfShkbPt7tDHp4jBBNM?p=preview

Related: #1997 #2012

**Comment by christopherthielen** [comment]
cc: @nateabele @joshuahiggins

**Comment by joshuahiggins** [comment]
This is related to the application of the class being pushed into the next cycle to prevent the race condition found in #1997. Should be a pretty low hanging fix. Want a PR against 0.2 or 1.0.0?

**Comment by christopherthielen** [comment]
Would prefer against 1.0. It should cherry pick pretty smoothly to legacy. 

I'd love a test too.

**Comment by christopherthielen** [comment]
fixed by using `$evalAsync` 
https://plnkr.co/edit/D8eB4KDVjBSgAuQeRUX5?p=preview
