### ISSUE TITLE
Node module is 76 MB because of bower_components

### ISSUE THREAD

**Issue by dylang** [angular-ui/ui-router#2513]
Hi! 

Do we need to include  `bower_components` in the npm module? It's ballooning the size of this module 38x what it could be.

```bash
angular-ui-router ❯ du -sh
76M	.
```

````
angular-ui-router/bower_components ❯ du -sh
74M	.
```

Can we add it to the `.npmignore`? 

We could also probably consider . npmignoring `site`, `build`, and `src`.

**Comment by nateabele** [comment]
See #1683 and #2498. I think we should keep `src`, but I'm fine with the others. Feel free to check the [contributor guidelines](https://github.com/angular-ui/ui-router/blob/master/CONTRIBUTING.md#contribute) and drop us a PR.

**Comment by dylang** [comment]
Thanks for the quick reply @nateabele. Looks like #2498 does the deed. The other ignores are minor compared to the `bower_components` so I'm going to close this issue.
