### ISSUE TITLE
YUI Compressor fails when minifying the ui-router.js

### ISSUE THREAD

**Issue by royteeuwen** [angular-ui/ui-router#2515]
I am having a problem when using the yui compressor to compress the ui-router.js. 

The problem lies on line 1254 where the defaultTypes for the $UrlMatcherFactory are defined:

`    int: {
      encode: valToString,
      decode: function(val) { return parseInt(val, 10); },
      is: function(val) { return isDefined(val) && this.decode(val.toString()) === val; },
      pattern: /\d+/
    },`

The exception it throws is "invalid property id". When changing it from int: { } to "int" : {} the compressor doesn't seem to fail, so maybe this could be a solution?

It is an obligated step our currently used CMS, when enabling minification. You have to enable it for either all files or no files at all so we have to use it. So disabling it on production environment is not an option.

**Comment by christopherthielen** [comment]
https://github.com/yui/yuicompressor/issues/47

**Comment by royteeuwen** [comment]
Hmm ok, seeing as that ticket is already open since 2013 I don't suspect them fixing it any time ever... :( would have been nice if this easy fix would be integrated in ui-router (just changing it from int: to "int"  )

**Comment by nateabele** [comment]
You're welcome to submit a PR. Please be sure to review the contributor guidelines.

**Comment by royteeuwen** [comment]
Oke perfect, I will, thanks

**Comment by royteeuwen** [comment]
Hey @nateabele 

When trying to upload a branch, I get following error when using the github desktop client:
You may not have permission to access ui-router. Check Preferences to make sure you’re still logged in.

And the following when using command line git:
remote: Permission to angular-ui/ui-router.git denied to royteeuwen.
fatal: unable to access 'https://github.com/angular-ui/ui-router.git/': The requested URL returned error: 403

Do I need to have some permissions of some kind?

Greetings
Roy

**Comment by nateabele** [comment]
Yeah, you need to fork it to your own account and open a pull request.

**Comment by royteeuwen** [comment]
https://github.com/angular-ui/ui-router/pull/2521
PR has been submitted :)

**Comment by christopherthielen** [comment]
closed via #2521
