### ISSUE TITLE
iOS 7+ swipe back gesture conflict with stateChange animations

### ISSUE THREAD

**Issue by iamdriz** [angular-ui/ui-router#2516]
I'm not sure if this is a ui-router issue or more of an AngularJS animate issue... but in short when moving from one state to another in my application I use CSS animations to animate the view change. E.g. .`.ng-enter` and `.ng-leave`.

But in iOS 7+ you can transition from one page to another by swiping your finger off the screen left or right and it does a back or forward action the same as clicking the back and forward buttons on the toolbar. However because the OS does its own animation back to the previous page in the history stack, and then AngularJS fires the state change after and then does the CSS animation, you get double animations and a flicker as the content you can already see is then animated back into view... How can we prevent this? As it's a really crappy looking user experience and looks like a bug to end users.

I thought about detecting iOS 7+ then disabling the animations. But I'd only want to disable the animations when doing the slide off the edge with the finger and not for actual clicks or the browser buttons. As far as I can tell there is no way to detect this. But the UX really suffers.

Has anyone had this issue before? Worked around it?

**Comment by nateabele** [comment]
This is outside of UI Router's domain, but you could probably do it with history tracking. I know they address this in some way in Ionic. You could check there or try StackOverflow. http://bit.ly/UIR-SOF
