### ISSUE TITLE
Feature Request: Animation Classes

### ISSUE THREAD

**Issue by SirDarquan** [angular-ui/ui-router#2519]
Ui-Router is awesome because it hooks into the ngAnimate class and allows us to get things going quickly. After awhile though, you realize you want more dynamic animations so that certain tranisitions cause specific animations even though they're targeting the same ui-view element.

What I would like to propose is adding a new attribute to the ui-view directive that allows a developer to specify css classes to be added during transition. ngAnimate already provides a set of classes that define the state of the animation that are added to ui-view while in transition. Their documentation also suggests that we use classes to aid in targeting specific elements. To make this slightly more dynamic, I use ng-class to change which class will produce the animation I'd like. The problem with this approach is that I don't know when the animation has ended and the last class I used remains in place. This leads to  odd transitions when a child state is causing a change.

Anyway, the idea is that we can specify the css classes we'd like and the ui-view would take care of the lifespan of the class. It would only be on the view while the animation is occurring. This could be done just before you clone the element for the new entering view. by adding the class(es) to the ui-view element. This would ensure that it's on both the enter and leaving nodes. Since the leaving node is going to be destroyed, we don't have to worry about that one. But after the enter animation is over, the ui-router code needs to remove the class so that it's no longer there. $animate.enter is a promise, so we can add a success callback to handle the class removal.

Theoretically, this is not hard. I was looking at the code base while trying to figure out if it could be done but I'm not familiar enough with the code to know all the gotchas that may exist. I'm also not sure where the equivalent functionality in the feature-1.0 branch is so I don't know if you guys have designed something better there.

**Comment by christopherthielen** [comment]
could you come up with some possible syntaxes?

**Comment by nateabele** [comment]
Probably the most flexible thing to do here would be to expose the `$animate` promise on the view's scope. Then you could do whatever you want.

**Comment by SirDarquan** [comment]
In my view, there's no syntaxes to create but I'll show an example of how I think it'll look:
```html
<div ui-view ui-view-animtion-class="{{my.classProperty}}""></div>
```
I'm not set on the `ui-view-animation-class` name, just wanted express what I was trying to show. Also I used the interpolation syntax just to show that I control that in a controller.

@nateabele That sounds interesting but I'm not sure the timing would be right. Could you explain how you think that would be used?

**Comment by christopherthielen** [comment]
> I used the interpolation syntax just to show that I control that in a controller.

@SirDarquan in the parent controller? Do you always want the same class to be added, when a transition starts, or do you choose that class based on the pending transition?

**Comment by SirDarquan** [comment]
In my code, I generally use the stateChange events to determine the fromState and toState. Knowing this information I can tell if I want the animation to move from left to right or right to left or whatever direction I need. Therefor I need to choose the class to determine the transition. Then the view should use whatever classes are there at the start of the transition.

**Comment by nateabele** [comment]
Pretty sure Ionic already does this. We could take a look at whatever they're doing.

**Comment by SirDarquan** [comment]
I've never used Ionic but if it fits and provides the desired results, then I look forward to it. Thanks guys!

**Comment by mgamsjager** [comment]
Used Ionic for some time I tried to mimic the app like back and forth behavior. It's doable but Ionic uses a forked ui router which does it a lot better.
