### ISSUE TITLE
Inconsistent state transition

### ISSUE THREAD

**Issue by zaknuces** [angular-ui/ui-router#2522]
I am having inconsistency problems while moving between the two states (that has the same url and parameters).

For details, please see http://plnkr.co/xLA21CmQ32uklXOlnXMI

Note: Try going to state 2 and then go back to state 1. Try this couple of times, you will notice that i takes '2' clicks to move to state 2. 

This is a serious isssue, as this will be break the common routing scenario when you have child states (like item-view and item-edit) that share same url.

Reproducible in 2.0.15, 2.0.16 and 2.0.17
Works in 2.0.13

**Comment by nateabele** [comment]
Having two states with the same URL is not supported and has never been supported. The correct approach is to have a parent state with a URL, and 2 URL-less child states. Please see StackOverflow for further details, as I have already addressed this scenario there.

**Comment by zaknuces** [comment]
@nateabele thanks for the comment. 

But, if we create a parent state (with or without abstract), my scenario will only work if the template of the new parent template contains 'ui-view' directive.
Is there a way to avoid it? 
http://plnkr.co/edit/xLA21CmQ32uklXOlnXMI see updated plunker

**Comment by nateabele** [comment]
You can use a named `ui-view` in a parent state, and target it in the child state configuration.
