### ISSUE TITLE
Multiple conditions for ui-sref-active

### ISSUE THREAD

**Issue by Hypocrite** [angular-ui/ui-router#2524]
I am using version 0.2.17 of ui-router.

The problem is that I would like to use the possibility to have multiple rules for ui-sref-active. For example like this:
`ui-sref-active="{'active': 'videos.*', 'active': 'files.*'}`

Is this somehow possible? At the moment it only takes the last condition.

**Comment by BrianCerasuolo** [comment]
Having this same issue, thought maybe I was using the syntax incorrectly for multiple ones but not sure as I can't get anything to work. It always just applies the last rule like you say.

**Comment by fpipita** [comment]
Hi, when used with the object literal syntax, `ui-sref-active` parses its argument as a plain JavaScript object: keys should be unique.

That's why only one of the conditions applies.

**Comment by xkelnar** [comment]
`ui-sref-active="{'active': 'videos.*', 'active': 'files.*'}`

+1

**Comment by christopherthielen** [comment]
I'd consider `ui-sref-active="{'active': ['videos.*', 'files.*']}`

**Comment by scooper91** [comment]
Hi! Is there any update on this?  It's exactly what we need for our navbar!

**Comment by mishevski8** [comment]
+1

**Comment by jcugmas** [comment]
+1 no update for this for now, it will be useful !

**Comment by christopherthielen** [comment]
I'd be happy to merge a PR (please add tests to https://github.com/angular-ui/ui-router/blob/5b54cbf89db3a908fae55485d2796ce79f4dea2e/test/stateDirectivesSpec.js#L413)  

In the meantime, if your nav markup is structured in a certain way, you can accomplish this with a little bit of shenanigans by nesting hidden `ui-sref` inside a parent `ui-sref-active`.  See this example:  http://plnkr.co/edit/URTdcIWcIgUAqa15PoH2?p=preview
