### ISSUE TITLE
Update StateParams without reload

### ISSUE THREAD

**Issue by Mattchewone** [angular-ui/ui-router#2526]
Is there currently a way to `$state.go('state', { params: 'some' }, { notify: false })` without reloading the route.
Currently it reloads the route and the resolve is reloading so I am getting duplicate ajax. 

What I am currently doing is in my controller I send an action to a service which does a $http.get and on return it updates the $stateParam but then it reloads the route and the resolve gets triggered again which means the $http.get is called again.

Is there a way to tell in the resolve or the service that the route is only updating due to params so as to not re-run the ajax?

Thanks
Matt

**Comment by christopherthielen** [comment]
`notify: false` is broken and deprecated.  For now, you can use `reloadOnSearch: false` and then use a query parameter.

In 1.0, we provide dynamic parameters for this use case.  Dynamic parameters are not quite ready to use yet, but will be ready when 1.0 beta is released.

**Comment by Mattchewone** [comment]
Thank you. 

I am currently using `reloadOnSearch: false` 
So for now still using state.go to update the Params will trigger the route to reload. 

Does it make a difference with the routeParams to use in the URL:

`url: "/home/:params"`
Or
`url: "/home/?params"`

**Comment by christopherthielen** [comment]
@Mattchewone yes, reloadOnSearch only understand query (search) parameters, so it only works with the latter.  In 1.0, we're working on the ability to mark any parameter as "dynamic" which has similar semantics to `reloadOnSearch: false`
