### ISSUE TITLE
Query string not handled correctly at the top level

### ISSUE THREAD

**Issue by lookfirst** [angular-ui/ui-router#2527]
I have a url that I'm trying to hit:

http://localhost.com:8081/?pr=foo

In my controller, I have:
```
$location.absUrl()
"http://localhost.com:8081/?pr=foo"
$location.search()
Object {}
```

If I hit this url directly:

http://localhost.com:8081/#/?pr=foo

Everything works.

So, how to get ui-router setup so that I can get at my query string. =)

**Comment by christopherthielen** [comment]
Is the problem that `$location.search()` is returning empty object?  `$location` is an angular core service.  Have you checked the angularjs issue tracker?

**Comment by lookfirst** [comment]
$state and $stateParams are also missing the data.

**Comment by lookfirst** [comment]
My ugly workaround:

`let sq = Strings.parseQS($window.location.search.substring(1));`

parseQS is just the function from https://github.com/sindresorhus/query-string/blob/master/index.js

**Comment by eddiemonge** [comment]
This sounds like an angular bug if $location.search is misbehaving. If you can narrow it down to ui-router then I'll reopen.

**Comment by lookfirst** [comment]
@eddiemonge Please read the issue again and re-open.

**Comment by eddiemonge** [comment]
I did. Still looks like $location.search() is the problem. Thats core Angular, not ui-router

**Comment by lookfirst** [comment]
The data is not accessible within ui-router.

**Comment by eddiemonge** [comment]
Maybe you are doing it at the wrong time. Without any further information its hard to help troubleshoot. a plnkr example would be good

**Comment by lookfirst** [comment]
Wrong time? I specified that this is in my controller in the first comment. Where else would I do this?

**Comment by eddiemonge** [comment]
Oh you did. But still, $location is an core angular method

**Comment by lookfirst** [comment]
Forget $location for a moment and focus on the fact that the data isn't in ui-router.

**Comment by eddiemonge** [comment]
Well again, without a plunkr example, can't really do much.

**Comment by christopherthielen** [comment]
> Forget $location for a moment and focus on the fact that the data isn't in ui-router.

@lookfirst , ui-router _uses_ the `$location` service to access the URL including query parameters.
