### ISSUE TITLE
Minor Breaking Change in 0.2.16

### ISSUE THREAD

**Issue by abhishekbhardwaj** [angular-ui/ui-router#2528]
Talking specifically about the bug fix in the **$urlRouter** code in 0.2.16:

> [Sort URL rules by specificity. Potential minor BC if apps were relying on rule registration order.](https://github.com/angular-ui/ui-router/commit/b5c57c8ec2e14e17e75104c1424654f126ea40)

One of my application expects the states to be in a certain order I think? - (because I have 2 states for one url - 1 for authenticated users and 1 for unauthenticated users). 

This is what should happen - if user goes to _url_:

1. If unauthenticated, taken to state 1.
2. If authenticated, taken to state 2.

Order the states are registered in:

1. State 1
2. State 2

Now what happens is that it works perfectly fine on Chrome, but on Firefox it never goes to state 1 but keeps redirecting to state 2, which essentially redirects the user again to a login screen.

On moving _state 2_ above _state 1_ in the registration order: it works on Firefox as expected but doesn't on Chrome.

Reverting to 0.2.15 fixed it for me but I'd like to upgrade. Any help or pointers would be appreciated!

**Comment by christopherthielen** [comment]
> On moving state 2 above state 1 in the registration order: it works on Firefox as expected but doesn't on Chrome.

Sorry about that.  We're reverting that BC.  Wait for 0.2.18 which will not sort your routes.  dupe #2501

**Comment by abhishekbhardwaj** [comment]
@christopherthielen Thanks a lot! :+1:
