### ISSUE TITLE
why i keep getting uiView: undefined? 

### ISSUE THREAD

**Issue by sekai92id** [angular-ui/ui-router#2530]
I have been code like this:
**main.js**
```
var app = angular.module('app',['ui.router']);
app.config(function config($stateProvider) {
	$stateProvider.state('index', {
		url:'',
		controller: 'FirstCtrl as first',
		template: 'templates/first.html'
	});
});
app.controller('FirstCtrl', function FirstCtrl(){
	var first = this;
	first.greeting = 'test';
});
```

But when i try using ui-view on my index.html keep give me uiView: undefined, only show blank page
**index.html**
```
<!DOCTYPE html>
<html lang="en" ng-app="app">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" href="modules/bootstrap/css/bootstrap.css">
</head>
<body>
	
	<ui-view></ui-view>	

	<script src="modules/jquery/jquery-1.12.0.js"></script>
	<script src="modules/bootstrap/js/bootstrap.js"></script>
	<script src="modules/angular/angular.js"></script>
	<script src="modules/angular-ui-router/angular-ui-router.js"></script>
	<script src="main.js"></script>

</body>
</html>
```

This is my **first.html**:
```
<input type="text" ng-model="first.greeting">
<h1>{{first.greeting}}</h1>
```

Am i wrong? i already follow the instructions for 1 hours but still give me blank page. Pls help

**Comment by christopherthielen** [comment]
you have `template` and it should be `templateUrl`

http://plnkr.co/edit/qBmuKYjQ6i7RN06aCug7?p=preview

This issue tracker is for bug reports and feature requests. Please use Stackoverflow for help requests, thanks!

http://bit.ly/UIR-SOF

**Comment by sekai92id** [comment]
@christopherthielen Thanks sir. Stackoverflow block me sir, cant ask question anymore.
