### ISSUE TITLE
RFC: external links, template update?

### ISSUE THREAD

**Issue by dtaylorsam** [angular-ui/ui-router#2533]
I could not get external routes to work by default. 
So, I updated the template.  Maybe I did something wrong?  If not, you should update this template.

https://scc.samaritan.com/custom/501/#/parks

template change:
href="{{step.external?step.url:step.ncyBreadcrumbLink}}"

**Comment by christopherthielen** [comment]
I can't understand what you're asking or saying.

**Comment by dtaylorsam** [comment]
My mistake.  The article I was reading is a customization to ui-router.
