### ISSUE TITLE
$urlRouterProvider.otherwise breaks routes with tildes.

### ISSUE THREAD

**Issue by ddelemeny** [angular-ui/ui-router#2540]
Version : 0.2.18

Problem : using ui-sref, urls with tildes are wrongly redirected to the "default" state defined with $urlRouterProvider.otherwise, even if the correct route is resolved and executed.
Probably caused by 02e98660a80dfd1ca4b113dd24ee304af91e9f8c

[Plunkr example](http://plnkr.co/edit/FoomMkRLfuxGHcPa5VbX?p=preview)

**Comment by christopherthielen** [comment]
Confirmed; and thanks for the plunker.  A workaround if you'd like to use 0.2.16-0.2.18 is to change your regexp to `~~[a-z]+` for now.

- Path parameters auto-choose the 'string' type
- If a path params has a regular expression, we still auto-choose the 'string' type, but apply the regexp to it
- the 'string' type needs an escape character (not url-encoding) to specially encode/decode slashes.  tilde was chosen as that character

I thought we had put this issue to bed, but hadn't considered the interplay with regexp! 
Sorry for the troubles!

**Comment by ddelemeny** [comment]
No worries, thanks for the workaround !
