### ISSUE TITLE
Cannot register orphaned state

### ISSUE THREAD

**Issue by redhead** [angular-ui/ui-router#2546]
I'm trying out ui-router 1.0.0-alpha on our project, and once I start it, I get this message:

    Error: Cannot register orphaned state 'top.bottom'

I guess that is because we configure states in run phase according to the [papa guidelines](https://github.com/johnpapa/angular-styleguide#style-y270) and so the top state may have not been added before the child state.

Is it a bug or we should not use this approach and configure states only in config phase?

**Comment by christopherthielen** [comment]
is this behavior different than 0.2.x?

**Comment by redhead** [comment]
Yes, in 0.2.x it didn't care in what phase the states were added.

**Comment by christopherthielen** [comment]
thanks.  

I'm surprised, because I thought we straight up ported the registration code without changing our unit tests.

**Comment by spyro92** [comment]
Can I confirm whether this behaviour is a bug, or whether its best practise to configure states in the config phase?

**Comment by redhead** [comment]
My opinion: I think it should not be that restricted though as states could be added in later time (e.g. async loading modules). But lets see what devs will say.

**Comment by ramirezd42** [comment]
100% agree. This makes it impossible to define routes across modules as far as I can see which is limiting

**Comment by christopherthielen** [comment]
I agree, I will back the orphan check out.

**Comment by yconoclast** [comment]
Do you have any updates here?

**Comment by christopherthielen** [comment]
coming soon
