### ISSUE TITLE
Use Angular 1.5 components as routes

### ISSUE THREAD

**Issue by jonricaurte** [angular-ui/ui-router#2547]
Make ui-router have a similar feature as ngRoute does here using angular 1.5:

https://docs.angularjs.org/guide/component#components-as-route-templates

**Comment by jonricaurte** [comment]
Looks like the change was added to ngView here:

https://github.com/angular/angular.js/commit/983b0598121a8c5a3a51a30120e114d7e3085d4d

**Comment by jonricaurte** [comment]
Looks like it will need to be added here: 

https://github.com/angular-ui/ui-router/blob/master/src/viewDirective.js

**Comment by christopherthielen** [comment]
thanks, yes this is definitely on our radar.  Targeting 1.0-beta

**Comment by jonricaurte** [comment]
Looks like 1.0alpha was merged to master after I left the previous comment. Looks like the change would be here for angular 1:

https://github.com/angular-ui/ui-router/blob/master/src/ng1/viewDirective.ts

Was wondering if there was a timeframe for the beta? 

Thanks!

**Comment by jonricaurte** [comment]
Tried it out on the legacy branch on with this commit (https://github.com/jonricaurte/ui-router/commit/a4cab7d110fe597810e4a2ef8c249bd31cfc4125) and seems to work. Will work on a PR with tests. Does not seem like anything else needs to be added.

**Comment by felixfbecker** [comment]
This is possible, but it would be nice to have `$resolve` like ngRouter

**Comment by BrianCerasuolo** [comment]
Would love to have this sooner rather than later

**Comment by smajl** [comment]
Yes, please, `$resolve` and `resolveAs` much needed! So much boilerplate will go away for us who are adopting component routing.

**Comment by lucianogreiner** [comment]
+1

**Comment by mgamsjager** [comment]
+1 for $resolve

**Comment by felixfbecker** [comment]
Also, $resolve should not only be available in state templates, but also in UI Bootstrap modals :)

**Comment by christopherthielen** [comment]
UI-Router 0.2.18 routing to angular 1.5 `component`s: http://plnkr.co/edit/JDj7lFpKKsJBykrsZQGZ?p=info

The guts are here:
```
"use babel";

let module = angular.module('ui.router.components', ['ui.router']);

function bindResolves() {
  var names = controller.$inject = ['$scope'].concat(Array.prototype.slice.call(arguments));
  
  function controller($scope) {
    var values = Array.prototype.slice.call(arguments);
    for (var i = 1; i < values.length; i++) {
      $scope[names[i]] = values[i];
    }
  } 
  
  return controller;
}

let unnestR = (acc, array) => acc.concat(array);

function registerComponentDecorator($stateProvider) {
  $stateProvider.decorator('component', function(stateDef, parent) {
    
    if (stateDef.component) {
      let cmp = stateDef.component;
      console.log(`state ${stateDef.name} routes to a component: ${cmp}`)
      stateDef.controllerProvider = function($injector) {
        let directive = $injector.get(stateDef.component + "Directive")
        let keys = directive.map(d => Object.keys(d.bindToController)).reduce(unnestR, []);
        return bindResolves.apply(null, keys);
      }
      
      stateDef.templateProvider = function($injector) {
        let directive = $injector.get(stateDef.component + "Directive")
        let keys = directive.map(d => Object.keys(d.bindToController)).reduce(unnestR, []);
        let attrs = keys.map(key => `${key}="${key}"`).join(" ");
        return `<${cmp} ${attrs}></${cmp}>`
      }
    }
    
    
    return stateDef.component;
  })
}


module.config(registerComponentDecorator); 
module.constant('bindResolves', bindResolves);```

**Comment by bitflower** [comment]
I'm using 1.0.0 alpha 4 but the binding to .component does not work. The milestone of this issue was set to 1.0.0 alpha 1 though. Is this implemented or not?

**Comment by christopherthielen** [comment]
@bitflower yes 1.0.0-alpha.4 should route to component. Can I see your code?

**Comment by bitflower** [comment]
It works,  it was my mistake. Sorry but thanks!

**Comment by trashhalo** [comment]
Heads up to anyone else who finds this plunkr above :point_up: it has a bug. It needs to kebob the attribute keys `"myResolvedBinding" vs "my-resolved-binding".` or else it will fail to inject resolves with capital letters. Also it should have probably been an one way binding < instead of an =.

@christopherthielen hopefully you'll consider backporting the code here to legacy its super hard to convince people to let you install an 1.0 alpha version to get component routing.

**Comment by christopherthielen** [comment]
@trashhalo @Jared314 @fetters5

Use this polyfill for legacy branch: https://github.com/softsimon/ui-router-route-to-components
