### ISSUE TITLE
`this` backward compatibility of resolve function 

### ISSUE THREAD

**Issue by redhead** [angular-ui/ui-router#2548]
In 0.2.x the resolve function is called with `this` pointing to the state it is transitioning to. In 1.0.0 alpha there is nothing. I don't know if this was intentional BC break because of new transition system, but I rather reported it for you to consider.

**Comment by nateabele** [comment]
Added to the BC list, thanks for the report.

**Comment by christopherthielen** [comment]
I've been tossing around the idea of binding `this` to the path node object

**Comment by nateabele** [comment]
Yeah, I was trying to think about what would be the most sensible in terms of the API (or nothing). That's an option.
