### ISSUE TITLE
0.2.18 strange query param

### ISSUE THREAD

**Issue by stramel** [angular-ui/ui-router#2551]
Noticed that on `0.2.18` my `redirectUrl` query param is changed from `%2F` to `~2F` and causes my app to hit my 404 page. I'm not sure what is going on but did notice that `0.2.15` worked.

**Comment by christopherthielen** [comment]
@stramel slash encoding has been problematic due to browsers pre-decoding the %2F.  

In 0.2.16 we changed to using a proprietary encode/decode using `~`.  The state parameter value (from `$stateParams`) should have been decoded to a `/`.  Can you give me more details how this is causing your problem?  Is the 404 server-side?  What is `redirectUrl` being used for, and how?

**Comment by stramel** [comment]
@christopherthielen That clears up why it was using `~2F`. However, we are using the `redirectUrl` in our Express layer. Some of the major page changes we route through the Express layer.

`redirectUrl` is being used to store the original path the user wanted before we redirected to login/sso page. Upon login, the user should be redirected to the original path. The `redirectUrl` is picked up by the Express layer and just passes `~2F` through, which in turn causes the 404 redirect from our Express Layer.

**Comment by christopherthielen** [comment]
@stramel so this is a serverside concern?  Can you walk me through the steps that are occurring?

e.g., 
1) ui-router app loaded
2) state change to `#/foo?redirectUrl=/bar/baz`
3) url reflects `#/foo?redirectUrl=~2Fbar~2Fbaz`
4) ???
5) express handles url with redirectUrl query param containing tildes

The ~2F logic is encapsulated in the built-in "string" parameter type.  You can probably register a custom type, and assign that type to your query parameter to avoid this encoding.

For what it's worth, I'm going to take another stab at our encoding paths in the future.  I now have a clearer picture of some of edge cases people have.

**Comment by stramel** [comment]
@christopherthielen Many apologies for never getting back to you on this. However we ran into the issue again and figured I would try to get this resolved. 

Our setup uses fragmented SPA. We have multiple SPAs that make up the application. In particular we have a large login process so we broke that out from our main application. 

Our flow is as follows:

1.) User navigates to app SPA on `domain.com/foo/bar` but has not logged in and is redirected to the login SPA page
2.) User is now on login SPA on `domain.com/login?redirectUrl=~2Ffoo~2Fbar`
3.) User successfully logs in we want to send the user back to the intended destination

**Comment by stramel** [comment]
@christopherthielen Many apologies for never responding, I got pulled off onto other things and just did a manual replace on the custom encoding for an interim solution.

Our application is setup as an fragmented SPA so our login process is a separate SPA from the main application.

When an unauthenticated user tries to go to a authentication restricted page they are redirected to the login process. So the URL comes in as `/login?redirectUrl=/foo/bar` gets translated to `/login?redirectUrl=~2Ffoo~2Fbar` by UI Router.

Once the user authenticates, we redirect them back to their intended destination in the main application SPA. However, when we go to do that since they are separate SPAs, we use the `location.href = redirectUrl` but this will not be found since the `/`s are encoded.

**Comment by stramel** [comment]
Going to

**Comment by christopherthielen** [comment]
try using the `any` type in your `redirectUrl`

`url: '/login?{redirectUrl:any}'`

**Comment by stramel** [comment]
@christopherthielen Tested in 0.2.18 and that didn't work for me. Will continue testing with 1.x
