### ISSUE TITLE
resolve triggers a infinite digest if the injection is not found

### ISSUE THREAD

**Issue by Foxandxss** [angular-ui/ui-router#2552]
A missing injection on a resolve (service doesn't exist or it wasn't minification safe and the mangle changed it up) results on a loop.

Well, to be really honest I am not sure if it is a loop. The application is just one state, with an otherwise on that state and a resolve. As soon as you put a non existent injection on it, the state will load again and again until it throws the infinite digest thing.

**Comment by nateabele** [comment]
Is this 1.0 or 0.2.x?

**Comment by Foxandxss** [comment]
Ah sorry, 0.2.x

**Comment by eddiemonge** [comment]
can you provide a plunkr demonstration please?

**Comment by Foxandxss** [comment]
Both @christopherthielen and @nateabele understand the issue already.

We agreed that if a resolve fails (I guess that if it returns false / null / undefined) it will just go to the otherwise route and if that route is the one that has the failing resolve will try to go to it again and again and again until angular cries.

I will set a plunker later, not at the computer atm.
