### ISSUE TITLE
How can i add hash to url for scrolling?

### ISSUE THREAD

**Issue by smartameer** [angular-ui/ui-router#2553]
Hi,

I am using ui-router in my controller to navigate by using transition with stateParams. I want to include hash (i.e. id of a section to scroll after transition).

```
app.config($stateProvider, $locationProvider) {
   $locationProvider.html5Mode(true);
   $stateProvider
       .state('profile', {
            url: '/profile/:id'
       });
});

app.controller('xyz', function($state) {
    var vm = this;
    /* button click gives hash as 'about'/ 'prefrences' / 'location' */
    vm.navigate = function(id, hash) {
        $state.tranitionTo('profile', {id: id}, {location: true, inherit: true});
    };
});
```

Now in this situation my URL generates like `www.example.com/profile/MTIzNDU2`.
How can i generate URL for hash dynamically like
- `www.example.com/profile/MTIzNDU2#about`
- `www.example.com/profile/MTIzNDU2#prefrences`
- `www.example.com/profile/MTIzNDU2#location`

**Comment by nateabele** [comment]
This tracker is reserved for bug reports &c. Please take support questions to StackOverflow. Thanks. http://bit.ly/UIR-SOF
