### ISSUE TITLE
Problem with ui-sref-active and ui-grid

### ISSUE THREAD

**Issue by pgrm** [angular-ui/ui-router#2554]
I have following scenario (using angular 1.5):

- one long list with items. Can have up to ~a hundred items, implemented with ui-grid.
- each row in this list is a link to the details of the item, which show up as a nested view above that list
    - this means, each row has a `ui-sref=".details({id: row.entity.id})"` - and this part works great (as far as I could see / test it
    - additionally, each row also has `ui-sref-active="active-class-name"` - and this doesn't work

When I scroll inside a long grid, random rows start popping up as selected. 

I'm not entirely sure the bug is in ui-router and not angular-ui, this is just a feeling. Maybe somebody else had a similar setup and it worked? I'd like to hear about how to get it to work.

Thx

**Comment by nateabele** [comment]
Please post a plunkr that demonstrates the issue. Thanks.

**Comment by pgrm** [comment]
@nateabele I'm currently working on a plunkr - in the meanwhile I wanted to share some findings:

while I scroll through the grid, the states-array from [stateDirectives#L371](https://github.com/angular-ui/ui-router/blob/master/src/ng1/stateDirectives.ts#L371) becomes longer and longer. Eventually containing every possible state, which is, why they get marked as selected.

Does this sound valid to you?

Plunkr which reproduces that behavior will follow ASAP (hopefully)

**Comment by pgrm** [comment]
@nateabele plunkr is here: https://plnkr.co/edit/JNtNqMgcd4fGR01bnxZ8?p=preview

you need to scroll around for a while to start seeing the problem. you can also select different items. The faster you scroll around the sooner it will start to appear.

**Comment by christopherthielen** [comment]
> Does this sound valid to you? 
no

**Comment by christopherthielen** [comment]
fixed in 9698ec4
