### ISSUE TITLE
After queryparams dynamic ids not working

### ISSUE THREAD

**Issue by smartameer** [angular-ui/ui-router#2555]
Hi,

I found that after queryparam if a hash(#) is supplied with dynamic id its changing the dynamic id to query param.

```
app.config($stateProvider, $locationProvider) {
   $locationProvider.html5Mode(true);
   $stateProvider
       .state('profile', {
            url: '/profile/:id?ref&trk&token#:hash'
       });
});
```
```
<a ui-sref="profile({ id: 123, ref: 'home', trk: 145999000889, 'token': 'MTIzNDU2', hash: 'about'})" >About</a>
```

The href is giving o/p as `/profile/123?ref=home&trk=145999000889&token=MTIzNDU2&hash=about`.
Whereas it should have given `/profile/123?ref=home&trk=145999000889&token=MTIzNDU2#about`

**Comment by christopherthielen** [comment]
What version are you using? 
can you try: 
`<a ui-sref="profile({ id: 123, ...  '#': 'about'})"...` and remove the "#" from your profile state's url?

**Comment by smartameer** [comment]
Thanks. This worked. I am using ```v0.2.15```. I have removed ```#:hash``` and it worked.
