### ISSUE TITLE
Angular 1.4.9+ issue net_error -3 and -101

### ISSUE THREAD

**Issue by tinybigideas** [angular-ui/ui-router#2556]
https://github.com/angular/angular.js/issues/14042

I'll add this here too, as the linking is done by ui-sref and the further resources are called by $stateChangeSuccess. Potentially a ui-router bug introduced by angular 1.4.9?

**Comment by christopherthielen** [comment]
A couple observations:


1) I don't understand your bug report (14042).  It talks about $resource, but I see no usage of $resource in the provided code

2) The only network fetches ui-router does is for templates.  

3) Although ui-sref generates a href, the href is not used for navigation.  ui-sref handles the click event by calling `evt.preventDefault()`, then it calls `$state.transitionTo()` so the browser should never actually follow the `<a href>`.  

I'll echo Narretz's comment, that this should be put into a plunker.

**Comment by eddiemonge** [comment]
Like Narretz said:

> Closing due to lack of information. Feel free to reopen with more info.
