### ISSUE TITLE
What's the expected behavior with an unnamed parent ui-view with no template?

### ISSUE THREAD

**Issue by jongunter** [angular-ui/ui-router#2557]
I commented on an issue before because I was having problems with controllers and directives being loaded twice/three times in my views. Turns out I was using a premium template/framework that had its routing configured in a very strange way (pretty much to appease the ASP.net MVC framework it was working on top of). The behavior here doesn't seem quite right, and I'm not sure if this is the expected way ui-router is supposed to handle it (If it is, my bad, feel free to close this issue).

I'll try to explain below, but I have a plunker to show off what's going on (open the iframe in a new window so you can see the console.log messages): http://plnkr.co/edit/G3Fy6S?p=preview

1) There is a parent ui-view for the main page format/template for the single-page-app. If one goes to a different section of the SPA, the main template changes.
2) There are child ui-views under these main templates that hold the actual content of the pages. For example, one parent view could show a "store" state and a child would show a "product" state. 
3) The ui-views are all unnamed.
4) This one is very important: There's a main state loaded up by default but it has no templateUrl. The html is already hard-coded inside the ui-view. When another main state is loaded up, the content comes from a templateUrl.
See my plunker if any of this is confusing.

The result of this is that controllers are loading multiple times and directives are compiling multiple times. See the `console.log`s inside the plunker. 

I can see why ui-router is confused, because there are multiple unamed views, so it's probably having trouble figuring out where to load a template/controller. But if that was the case, wouldn't the main (parent) view content be getting replaced. Also intuitively, this behavior seems like it should work because the hierarchy of the states matches that of the `ui-view`s (it's not like there are two sibling `ui-view`s).

Thanks so much in advance for your help!

**Comment by christopherthielen** [comment]
Yes, this is basically expected. 

Views are targeted using absolute addressing `"viewname@statename"`.  The following two views have the same address of `"@"` (essentially `<unnamed>@<root>`):
```
      <div class="well" ui-view> <!-- "unnamed@root", i.e., "@"-->
        <h1>Route 1</h1>
        <hr/>
        <a ui-sref=".list">Show List</a>
        <div ui-view></div> <!-- "unnamed@root", i.e., "@"-->
      </div> 
```
When the child state is activated, its view configs are activated.  Each ui-view tag checks if a matching view config is active, and updates itself accordingly.  Since both ui-views have the same absolute address, they both update to the same view config.

**Comment by jongunter** [comment]
Great, thanks!
