### ISSUE TITLE
Navigation to state starts but doesn't end->probably resolves are too slow

### ISSUE THREAD

**Issue by Songissimo** [angular-ui/ui-router#2564]
Hi All,
   I'm facing an weird issue. I trigger a navigation to a state and the navigation start (i.e stateChangeStart event is triggered) but it doesn't complete (i.e. stateChangeSuccess event is not fired).

Is anybody aware of the reason why this happen? Can anybody advise where to look for in order to understand the problem?

Further investigating the issue I found out that disabling one of the promise in the resolve all starts working. Probably resolve is too slow, how can I cope with that? Is there a kind of timeout for executing a resolve???

Thanks everybody.

**Comment by eddiemonge** [comment]
It depends on what you are doing in the resolve.

This seems more like an implementation issue rather than a bug: http://bit.ly/UIR-SOF

**Comment by Songissimo** [comment]
Just running some promises, they can take some time. Does it mean navigation gets cancelled?

**Comment by eddiemonge** [comment]
Perhaps you should move them into the controller then as resolves are supposed to be resolved before the controller/view happen
