### ISSUE TITLE
Promise .catch() in resolve function prevents $stateChangeError from firing

### ISSUE THREAD

**Issue by uloco** [angular-ui/ui-router#2565]
I've been struggling for a while now to figure out the following behaviour.

I am using a resolve property in my state which is a factory. 
In this immediately invoked factory I initialize my project with a promise chain (get the configs, get initial data, connect websocket, etc.).
I read in the docs, that error handling is not working as normal in the resolve function and I should use `$rootScope.$on('stateChangeError', ...)`.
But this event is never fired at all, if a .catch() block is declared in this initalize promise I described above. The declaration alone is enough to prevent this event from firing.

Perhaps you should consider adding this information in your documentation. 
It was a real pain figuring it out.

Code description: 

```javascript
angular
    .module('app', [])
    .run(catchError)
    .config('routesConfig', routesConfig)
    .factory('initialize', initialize);

function catchError($log) {
    $rootScope.$on('$stateChangeError', function(event) {
        event.preventDefault(); 
        // no output if .catch() is present
        $log.warn('stateChangeError');
    });
}

function routesConfig($stateProvider, $urlRouterProvider) {
    $stateProvider
        .state('foo', {
            url: '/foo',
            templateUrl: 'foo/foo.html',
            resolve {
                initialize: 'initialize',
                init: function(initialize) {
                    return initialize();
                }
            }
        })
}

function initialize(argument) {
    return function() {
        return $http.get('appconfig.json')
            .then(function(response) {
                // get initial data
                // return promise
            })
            .then(function(initData) {
                // connect websocket
                // return promise
            })
            // this prevents $stateChangeError from firing completely and stays silent!
            .catch(function (e) {
                // some error handling
            });
    }
}
```

**Comment by joshrickert** [comment]
I just ran into something similar a few days ago. This is an Angular thing. If you catch an error in a promise, that rejection is not passed down the promise chain unless you return a new promise rejection in your handler.

**Comment by eddiemonge** [comment]
Right, what ^^ @joshrickert said
