### ISSUE TITLE
how to get handle event onRouteUpdate in ui-router, and how to get queryParams from the url

### ISSUE THREAD

**Issue by razam217** [angular-ui/ui-router#2566]
Is there any event which can handle any change in the route, e.g. if I add queryParam, and it should get triggered. One more thing, how to get that queryParam from the URL. I know how to handle all this in ngRouteProvider, but not sure how to do in ui-routerProvider.

I was handling the above scenario with ngRoute with this code:

```
function addQueryParam(){
   $location.search('p', 22);
}
$scope.$on('$routeUpdate', function(){
   console.log($routeParams.p);
}
```

**Comment by nateabele** [comment]
UI-Router does not have a `$routeUpdate` event. Please see the available events in [the docs](https://github.com/angular-ui/ui-router/wiki#state-change-events), as well as the docs on `$stateParams`. Please direct further support questions to StackOverflow, thanks. http://bit.ly/UIR-SOF
