### ISSUE TITLE
Views briefly showing translation ID's

### ISSUE THREAD

**Issue by nmpribeiro** [angular-ui/ui-router#2568]
Hi,

How can I avoid seeing the TRANSLATION_ID, even if for a brief time on the loading of the view?
I mean, in the ui-view side of things? Is there an option to timeout the view generation?

Thanks in advance,
NR

**Comment by nateabele** [comment]
This sounds like a support question, for which I would direct you to StackOverflow: http://bit.ly/UIR-SOF

If you have a specific issue that you think is a bug, please post a plunkr that we can look at to reproduce it on our end.

**Comment by nmpribeiro** [comment]
Well, it's not a bug. Only a simple question... 
when we change state into a new one, the view template will immediately change, according to normal behavior. 

My question is simple: 
'is there a way to delay the generation of that template?' say 0,5s, or 1s?
