### ISSUE TITLE
Why ui-view doesn't work into components template?

### ISSUE THREAD

**Issue by tamtakoe** [angular-ui/ui-router#2574]
http://plnkr.co/edit/SKYVVGWw2GqABPoQHg8E?p=preview

**Comment by kukac7** [comment]
@tamtakoe missing `$urlRouterProvider.otherwise('/');`

**Comment by tamtakoe** [comment]
@kukac7 I have updated my plnkr (added otherwise and templateUrl). It works good but only in plnkr. On local server it doesn't work

**Comment by kukac7** [comment]
@tamtakoe there's nothing wrong with it, works well.
i do not know that there is a local development environment set for you, but for me there is no problem.

**Comment by eddiemonge** [comment]
If it doesn't work locally but does work elsewhere then I would examine your local setup to see whats different. Closing as this doesn't seem like a ui-router issue.

**Comment by tamtakoe** [comment]
@eddiemonge, @kukac7 This problem occurs because of $location service. See example:
http://plnkr.co/edit/kXcik8znN5HMp6ohRuMA?p=preview

If you remove problem factory app will works good

**Comment by eddiemonge** [comment]
That looks like a core angular problem

**Comment by eddiemonge** [comment]
It doesn't matter what you put into the run argument list, even nothing in there breaks it.

**Comment by tamtakoe** [comment]
I created an issue in angular repository https://github.com/angular/angular.js/issues/14201

Investigate this problem, please. In what place and what time it appear. I or Angular team can not do it effectively, because we are not ui-router specialists.

**Comment by Narretz** [comment]
This might be a problem similar to https://github.com/angular/angular.js/issues/1213 (A fix for this was merged, but it's not in a release yet). But the exact problem is different. With uiRoute, injecting location breaks the state update. I would say that this is a uiRouter bug.

**Comment by tamtakoe** [comment]
It works if you add $state near $location dependency http://plnkr.co/edit/GlZgwMSJjuSt0AVjT2zc?p=preview

**Comment by gkalpak** [comment]
This was indeed an issue very similar to that one pointed out by @Narretz.
This seems to have been fixed in `v1.0.0alpha0`: [updated plnkr][1]

[1]: http://plnkr.co/edit/WnbOT5MpOqyqa0hpfXLk?p=preview

**Comment by gkalpak** [comment]
This is the original commit that fixed this if anyone is curious: [46cf53d][1]

[1]: https://github.com/angular-ui/ui-router/commit/46cf53d2bee622badddd5378a15d9a777d78eac4#diff-230fff7c0b3ed8f0d4f2443a246fc76aR1377

**Comment by tamtakoe** [comment]
:+1:

**Comment by christopherthielen** [comment]
Thanks all.  For others, the @tamtakoe workaround is simple: 
`app.run(['$state'], function($state) {}]);`

**Comment by christopherthielen** [comment]
Fixed in de3a04a7c676e05b5b868de4f65d03d9c588773c 
released as 0.3.0

**Comment by mickaeltr** [comment]
Hi @christopherthielen,

I am working on a legacy project with Angular 1.5 and ui-router 0.2. I am trying to upgrade it progressively to newer versions. Upgrading ui-router from 0.2 to 0.3 breaks the history.back() behaviour.

I figured out that replacing `.constant("$state.runtime", { autoinject: true })`
by `.constant("$state.runtime", { autoinject: false })` fixes it.

Any idea? Many thanks

**Comment by christopherthielen** [comment]
@mickaeltr  Not sure. I don't think the constant `$state.runtime` is used by either ui-router or angularjs.  I suspect your app might have custom code that uses that value?

**Comment by mickaeltr** [comment]
@christopherthielen More precisely, my problem actually comes from `$injector.get('$state');` (in the run block), which is executed when `$state.runtime.autoinject` is true. Sorry for my bad explanation!

**Comment by christopherthielen** [comment]
As for the back button, I'd try the latest version 1.0.10

**Comment by mickaeltr** [comment]
I'd like that but upgrading ui-router from 0.x to 1.x requires quite some work. So for now we'll have to stick to 0.2.18. Thanks @christopherthielen
