### ISSUE TITLE
controller tries to revalidate a form after exiting state

### ISSUE THREAD

**Issue by royair** [angular-ui/ui-router#2575]
hi, i have a dummy angular's blog project:
the state hierarchy goes like this:

- admin (abstract)
- |-admin.list (a list of all posts to admin)
- |-admin.edit (a single post edit)
- |-admin.add (for adding a new post)

under edit.html (state: admin.edit) i have a form named 'postForm' with some validation on it.
for some reason, when exiting the state using ui-sref="admin.list" - angular tries to digest the old state, with no success of course, since 'postForm' does no longer exists thus no validation can be performed.

have any idea why ui-router tries to digest old state when exiting?
![screenshot001](https://cloud.githubusercontent.com/assets/8818555/13217512/aafe3acc-d96b-11e5-9e3d-f08429a29cab.jpg)

p.s.
validation works fine.

the project can be found here:
https://github.com/royair/blog/
to install:
1) clone project
2) npm i
3) npm start

thanks in advance!

**Comment by eddiemonge** [comment]
Any chance you could boil it down to a smaller example as there is a lot of code to go through

**Comment by christopherthielen** [comment]
I went through the trouble of spinning up a vm and cloning this repo

@royair do I need credentials to login or something to even reproduce this?

**Comment by royair** [comment]
Hi @christopherthielen 
thanks for helping!

i have created a new branch to reflect the issue
please use: 'ui-router-bug'

regarding creds, you can use:
email: test@test.com
pwd: 123456

once installed (1. clone project 2. npm i  3. npm start)
go to http://localhost:8081/#/admin/add
and click  the admin link at the top.
you should be able to see some errors at the console.

**Comment by christopherthielen** [comment]
This is related to the code we added for #1643

I think we will be reverting that code in 0.2.19 in favor of exposing the animation promise: #2562

See also #2485

In the meantime, update to ui-router 0.2.18 and add `noanimation` to your ui-view tag
`<div ui-view noanimation></div>`

**Comment by christopherthielen** [comment]
dupe #2579
