### ISSUE TITLE
Facebook oauth redirection issue

### ISSUE THREAD

**Issue by ligadata-dhaval** [angular-ui/ui-router#2576]
Hi,

I have added Facebook oauth (Login using facebook) page as the home page. Once the authentication is done, I need to go to the dashboard. Once authentication is successful, facebook, calls a function. However, using ui-router, I am not able to reroute to the dashboard in that function. Is there any way to reroute?

**Comment by eddiemonge** [comment]
This is better asked on stackoverflow

**Comment by eddiemonge** [comment]
http://bit.ly/UIR-SOF

**Comment by vTodorov** [comment]
@eddiemonge Did you find any solution?
