### ISSUE TITLE
State based classes leaking between transitioning views

### ISSUE THREAD

**Issue by ns-ctruong** [angular-ui/ui-router#2579]
After updating to 0.2.18 (from 0.2.15), I noticed some strange behavior in one of our state transition animations.  I was using ng-class to apply state specific styles on a child view container.

In 0.2.15, at least, the state specific class was appropriately applied on the entering view only.

In 0.2.18, the view that was transitioning out also received this same class.  Here's a plunker.  Click on the link for 'Child 1'.  You'll see an empty div with a red outline animating out.  The red outline should only be applied to the incoming state view for 'Child 1.'

https://plnkr.co/edit/6GhZaOQV0lcO3kLLpjn0?p=preview

**Comment by christopherthielen** [comment]
I think this is very likely related to the code we added for #1643 

I think we will be reverting that code in 0.2.19 in favor of exposing the animation promise:  #2562 

See also #2485

**Comment by christopherthielen** [comment]
I'm leaving this open as a bug ticket, related to the #2562 feature ticket.

**Comment by ns-ctruong** [comment]
Great.  Thanks for looking into this.

**Comment by christopherthielen** [comment]
released 0.3.0
