### ISSUE TITLE
don't change state if tab is in parent state

### ISSUE THREAD

**Issue by GGeorgi** [angular-ui/ui-router#2581]
I have got a problem using tabs in nested views.

I have a two level tab bars:

| tab 1 || tab 2 || tab3 ||
|           ||___________
| tab1.1|| tab1.2 || 

tab1 state is "user({id:45})" tab1.1 state is "user.details"
I'm passing parameter to tab1 and loading that user data and stores in service before changing state to "user.detail". So it works good so far. But when I clicks on tab1 state has being changed to "user({id:45})" and from sub tabs no one is selected. But I wonders why it changes state in case of it is **already selected.**
so I wonder to know is where any way to prevent tab select if is it already selected ?
Here is how I creating tab: passing state url by ui-sref
`<tab ng-repeat="tab in tabs" heading="{{tab.title}}" active="tab.active" disabled="tab.disabled" ui-sref="{{tab.url}}" ui-sref-active="active">`

**Comment by christopherthielen** [comment]
If you are at `user.detail` and you click a link to `user`, it exits `user.detail`.

Have a look at ui-router-extras deep state redirect.

https://christopherthielen.github.io/ui-router-extras/example/dsr/index.html#/
https://christopherthielen.github.io/ui-router-extras/#/dsr

http://bit.ly/UIR-SOF

**Comment by GGeorgi** [comment]
thank you Chris. This is what I exactly looking for.
