### ISSUE TITLE
A small improvement on nested states documentation

### ISSUE THREAD

**Issue by MtDalPizzol** [angular-ui/ui-router#2584]
Hi! I was implementing nested states and needed to make a list on ```/courses``` and a display on ```/courses/:slug```. The docs on nested states are clear on how to make a ```/courses/list``` for the list state, but not on how to to simply stick to ```/courses```. My first guess was to use ```url: '/'``` but it didn't worked and it was redirecting me to my ```.otherwise()``` route. Then, I tried ```url: ''``` and it worked perfectly.

So... If nobody has suggested it yet or nobody wants to take care of it, I can make a PR with a small note on the docs about it.

**Comment by eddiemonge** [comment]
If you want to and it makes the docs better then yes please
