### ISSUE TITLE
named ui-view only works as attribute, not element

### ISSUE THREAD

**Issue by cnlevy** [angular-ui/ui-router#2585]
`<div ui-view="view1"></div>` => this works
`<ui-view="view1"></ui-view>` => this doesn't

here's a [jsfiddle](http://jsfiddle.net/v6azx3om/98) demonstrating it

**Comment by nateabele** [comment]
> `<ui-view="view1"></ui-view>` => this doesn't

Well, right. HTML doesn't work that way. What were you expecting?

**Comment by cnlevy** [comment]
You're right. It's just not coherent with the plain <ui-view></ui-view> tag which does work

**Comment by nateabele** [comment]
This follows the pattern of many Angular directives that can be used as a tag or an attribute, such as [`ng-include`](https://docs.angularjs.org/api/ng/directive/ngInclude). Users are expected to know the difference.
