### ISSUE TITLE
1.0.0-alpha0 Can't use named service as string for resolver

### ISSUE THREAD

**Issue by joshrickert** [angular-ui/ui-router#2588]
Trying out the new alpha build. I ran into this issue where I can't specify resolves by service name:
```
    resolve: {
      'test': 'testResolver',
    }
```

I get
```
Error: [ng:areq] Argument 'fn' is not a function, got string
```

[Here is a plunkr](http://plnkr.co/edit/7jV46gRSLTYthoFSBIeq?p=preview). Navigate to `home.foo`.

**Comment by christopherthielen** [comment]
Thanks. I'll get this fixed up before 1.0.0-beta.  In the meantime, the obvious workaround is:
```
resolve: {
      'test': testResolver => testResolver,
    }
```
