### ISSUE TITLE
Is 1.0 ready for use yet? 

### ISSUE THREAD

**Issue by yellow1912** [angular-ui/ui-router#2589]
Hello,

I wonder if 1.0 is ready for use, I would really love to try out those new features such as the dynamic parameters. However, I can't seem to find any solid documents on 1.0 especially the example code for the new features?

**Comment by joshrickert** [comment]
I have spent the last week trying it out. It's stable for the most part. The lack of documentation was the biggest issue. I ended up getting it to work using a combination of:

- The in-code documentation, which is fairly comprehensive
- The [TypeDoc-generated documentation](http://angular-ui.github.io/ui-router/feature-1.0/index.html) for the feature-1.0 branch
- Reading the unit tests for working code examples

**Comment by christopherthielen** [comment]
Follow this for the road to beta: #2223
