### ISSUE TITLE
Unexpected behavior when click on state with empty url?

### ISSUE THREAD

**Issue by yellow1912** [angular-ui/ui-router#2590]
Using the example found on this page in standalone mode:

http://plnkr.co/edit/SDOcGS?p=preview

1. Clicking on route 1 I can see the address bar changes to 
#/route1

2. Clicking on route 2 I can see the address bar changes to 
#/route2

3. Clicking on home I can see the content changes but now the address bar still shows: 
#/route2

I expect this to be back to some default empty hash?

**Comment by ThomsC** [comment]
+1

**Comment by eddiemonge** [comment]
Why? You are specifying the state can exist with no url. If you want it to clear out the url then use `url: "/"`
