### ISSUE TITLE
State with empty url & hashPrefix

### ISSUE THREAD

**Issue by r0b-** [angular-ui/ui-router#2591]
Hi,

I have default state (showing the homepage) that uses an empty url.
```
.state("HOME", {
  url: "",
  templateUrl: "home.html",
  ...
})
```
If I link to this state e.g. via ui-sref I always get an url with hash (and hash prefix if set) like "/mysite/#!".
I would expect just "/mysite" here.

Is there a setting or sth like this to get this behaviour?
Thx

**Comment by kegbuna** [comment]
Two things. I think you need to be using html5Mode in order to get rid of the hashbang. That is done by using the location provider

```js
configFunc.$inject = ['$locationProvider'];

function configFunc($locationProvider) {
  // sets the location provider to html5Mode
  $locationProvider.html5Mode(true);
}
```

Second, I might be mistake but I believe you'll need to use at least a slash there to define the url, e.g.

```js
url: "/"
```

**Comment by eddiemonge** [comment]
What ^^ said
