### ISSUE TITLE
bower ENOTFOUND     Package angular-ui-router not found

### ISSUE THREAD

**Issue by sashajo** [angular-ui/ui-router#2592]
As of today Mon Feb 29 2016, at 8:12 AM EST bower install angular-ui-router doesn't work. I get 

bower ENOTFOUND     Package angular-ui-router not found

**Comment by boazin** [comment]
Happens to me as well...

**Comment by laurent-le-graverend** [comment]
Same here, can't deploy my apps in prod :-/

**Comment by tolyo** [comment]
+1

**Comment by MichelSlot** [comment]
+1

**Comment by atte-backman** [comment]
+1

**Comment by arshadashrafi** [comment]
+1

**Comment by pgrzeszczak-neducatio** [comment]
+1

**Comment by QuentinFchx** [comment]
`bower info ui-router` seems to point to `angular-ui-router`

**Comment by zankevich** [comment]
:+1:

**Comment by atte-backman** [comment]
Is `bower install ui-router` long term preferable fix? Is this intentional?

**Comment by charlesdg** [comment]
change `angular-ui-router` by `ui-router` in your bower.json

**Comment by gvolkan** [comment]
:+1:

**Comment by krnlde** [comment]
Can the 3rd party issue be solved via the `resolutions` field somehow?

**Comment by gvolkan** [comment]
resolutions using for resolving of version conflict, right? it cant be help...

**Comment by krnlde** [comment]
Yes, but afaik they only apply to versions, not to repo pointers.

**Comment by jbaskeen** [comment]
+1

ಠ_ಠ

**Comment by sashajo** [comment]
Changing to ui-router fixed my issue.

**Comment by Hyzual** [comment]
+1

**Comment by bhlangonijr** [comment]
+1

**Comment by boazin** [comment]
Is it a final solution or an intermediate one?
(meaning - was it done on purpose or by mistake)

**Comment by gvolkan** [comment]
i think i solve it, any body try it again?

**Comment by bhlangonijr** [comment]
3rd party libraries are broken, even changing to ui-router

**Comment by gvolkan** [comment]
i just register it on bower.herokuapp.com, and its working right now. ui-router and angular-ui-router works at sametime... can you check it again?

**Comment by zankevich** [comment]
@gvolkan :+1:

**Comment by bSm1le** [comment]
it works now

**Comment by Triol19** [comment]
@gvolkan it works

**Comment by jbaskeen** [comment]
working again

**Comment by bschwind** [comment]
Anyone have a diagnosis or explanation on this? How does everyone deal with such horrible instability on these frontend tools?

**Comment by krnlde** [comment]
@bschwind npm and bower proxy via nexus.

**Comment by bschwind** [comment]
@krnlde Do you have a good link on the subject? I maintain some of the web builds for my team and it seems like every other week there's a silly issue with npm, bower, or gulp. It would be great to make things more robust if possible.

**Comment by krnlde** [comment]
@bschwind:
* https://books.sonatype.com/nexus-book/reference/npm-proxying-registries.html
* https://issues.sonatype.org/browse/NEXUS-6884

**Comment by bschwind** [comment]
@krnlde thanks!

**Comment by christopherthielen** [comment]
oh my.

**Comment by christopherthielen** [comment]
I'm (attempting to) transfer bower package support to a separate repo. 

Please do not re-publish to bower for me ;)

https://github.com/bower/registry/issues/179#issuecomment-190194465

**Comment by christopherthielen** [comment]
To address another few comments above: `angular-ui-router` is the official bower package; not `ui-router`.

**Comment by christopherthielen** [comment]
OK, I think it's moved to the new repo now.  Let me know if there are further issues installing with bower.
