### ISSUE TITLE
Previously working release cannot be resolved

### ISSUE THREAD

**Issue by rloehr** [angular-ui/ui-router#2594]
This appears to have broken sometime today:

loehrm1@usenloehrm1m1:~/code/tmp$ bower install --save angular-ui-router#0.2.8-bowratic-tedium

bower angular-ui-router#0.2.8-bowratic-tedium       not-cached git://github.com/angular-ui/angular-ui-router-bower.git#0.2.8-bowratic-tedium
bower angular-ui-router#0.2.8-bowratic-tedium          resolve git://github.com/angular-ui/angular-ui-router-bower.git#0.2.8-bowratic-tedium
bower angular-ui-router#0.2.8-bowratic-tedium     ENORESTARGET No tag found that was able to satisfy 0.2.8-bowratic-tedium

Additional error details:
Available versions: 0.2.18, 0.2.17, 0.2.16, 0.2.15, 0.2.14, 0.2.13, 0.2.12, 0.2.11, 0.2.10, 0.2.9, 0.2.8, 0.2.7, 0.2.6, 0.2.5, 0.2.0, 0.0.1

Is there a workaround for this?

**Comment by christopherthielen** [comment]
> Is there a workaround for this?

you could upgrade. 

That said, I just published the 0.2.8-bowratic-tedium tag to the bower repo.  try again.

**Comment by rloehr** [comment]
All set.  Thanks!
