### ISSUE TITLE
ui-router from NPM has had its 0.2.15-0.2.18 release seemingly removed

### ISSUE THREAD

**Issue by danpantry** [angular-ui/ui-router#2599]
We have a dependency on ui-router@^0.2.15 in our project. After running `npm i` prior to a release last night we noticed that we were unable to install that specific version as it had been removed and the only version on npm that as available was `ui-router@1.0.0-alpha0`.

I appreciate there is `npmjs.org/package/angular-ui-router`, but there does not appear to be any distinction between the two packages on the npm site. Was this removal made by mistake? Obviously, I know that the version we rely upon is deemed "legacy", but when the only alternative is a alpha/beta version that is being questioned if it is even ready for production it seems a bit silly to pull the other versions from `ui-router`'s npm package.

**Comment by christopherthielen** [comment]
We only publish `angular-ui-router`.  The `ui-router` npm package is rogue, published by (I don't know who), and we do not control it :(

I'd like to gain control over the npm `ui-router` package so we can direct people to use the real package `angular-ui-router`

**Comment by danpantry** [comment]
Okay, awesome, thanks for clarifying that. It was published by [@jesscold](https://www.npmjs.com/~jesscold). npm says their contact e-mail is jess@cold.co, though visiting http://cold.co indicates that the domain may not actually be theirs anymore.


Might be worth [reaching out to npm](https://www.npmjs.com/support)?

**Comment by eddiemonge** [comment]
Sent jess an email to see if we can resolve it there first
