### ISSUE TITLE
Difference between $routeProvider and $urlRouterProvider

### ISSUE THREAD

**Issue by timkindberg** [angular-ui/ui-router#26]
I see in the example there are two very similar services, $routeProvider and $urlRouterProvider. What is the difference between these and the purpose that each serves? I'm also asking for my overview documentation.

**Comment by jakekemple** [comment]
@ksperling I get frustrated reading comments with poor wording. Why use words like "shim" & "fudges"? I don't want to waste any time trying to figure out what you are explaining. Please just be straightforward and use proper terminology when explaining things, so someone trying to learn about these things 2 years later doesn't have to decrypt poor internet language. Please. Thanks

**Comment by nateabele** [comment]
LOL

![English](https://media.giphy.com/media/u5ANfLVooNVi8/giphy.gif)

**Comment by jayarajoffice** [comment]
I speak malayalam, my neighbouring state speaks tamil, my country speaks more than 1600 languages...... dare not to learn any one of those... or you will encouter ever harder **** words.... 
This 26 letter language is not our mother tongue, yet we have mastered it so well.. so respect that you MF

**Comment by rjmunro** [comment]
@jakekemple "Shim" and "Fudges" are the correct developer words. They make perfect sense to me. 

@ksperling, I am having trouble undestading [your comment](https://github.com/angular-ui/ui-router/issues/26#issuecomment-13987632) though.

It opens with:

> $routeProvider is a shim the implements ...

("the implements" should be "that implements")

Then it continues:

> Current AngularJS $routeProvider is also monolithic ...

So is it monolithic, or is it a shim (meaning a very thin layer mostly emulating something else)?

I think you may mean "$urlRouterProvider is a shim that implements the current AngularJS $route / $routeProvider API...".

So we should probably use neither and just stick to $stateProvider only if we are starting a new project.

**Comment by nateabele** [comment]
> So is it monolithic, or is it a shim (meaning a very thin layer mostly emulating something else)?

@rjmunro The comment refers to two different things. The former is the implementation in Angular core. The latter was UI Router's (no-longer-supported) compatibility layer for people migrating from ngRoute.

Since `$routeProvider` no longer ships with any supported version of UI Router, I think this thread is moot at this point.
