### ISSUE TITLE
Use a different parameter type for query parameters and path parameters

### ISSUE THREAD

**Issue by christopherthielen** [angular-ui/ui-router#2603]
Path parameters default to `string` type, which does the silly custom slash encoding from `/` to `~2F`.  

Query parameters don't need custom encoding because `$location` doesn't have special slash handling for query parameters.

We should have a different param type for "path" and "query" parameters.  Query parameter type should not do slash encoding, while path parameter type should.

**Comment by burzum** [comment]
+1

**Comment by brettjacobson** [comment]
:+1:

**Comment by alexb0011** [comment]
:+1:

**Comment by christopherthielen** [comment]
My perspective has shifted since I created this issue.

We delegate to `$location` to set the query string.  `$location` always calls `encodeURIComponent` (via [encodeUriQuery()](https://github.com/angular/angular.js/blob/v1.5.5/src/Angular.js#L1402).  Even if we create a non-path-encoded type, $location will still encode it.

Instead of `?param=~2Ffoo~2F` we end up with `?query=%2Ffoo%2F`.  While it's slightly better, I don't think it's that much of a difference.

This plunker shows how it would have been without special encoding: http://plnkr.co/edit/qEpsXGi1CBUpQt240e65?p=preview
