### ISSUE TITLE
pre 1.0.0-alpha0 versions no longer on npm?

### ISSUE THREAD

**Issue by weshardee** [angular-ui/ui-router#2607]
It seems like old versions have vanished from npm. Maybe this is related to the release of the 1.0.0-alpha0? I was using `"ui-router": "^0.2.15"`, but that appears to no longer be available and suddenly started breaking my CI build (first noticed: March 1).

**Comment by christopherthielen** [comment]
You should use the official package: `angular-ui-router`

**Comment by weshardee** [comment]
Doh. Thanks for the clarification.
