### ISSUE TITLE
Are dynamic-params branch features available elsewhere?

### ISSUE THREAD

**Issue by websirnik** [angular-ui/ui-router#2608]
I've been using `dynamic-params` branch(now deleted) for a long time, and it was working great for my use case. Looks like, it's time to upgrade, wondering if this functionality is available anywhere?

```javascript
.state('post.item', {
    url: '/:item_slug',
    params: {
        item_slug: {
            value: null,
            dynamic: true
            // This prevented the controller re-load after the route change 
            // Does anything like this is available in 2.18.0 or 1.0.0alpha?
        },
        post_slug: {
           value: null,
           dynamic: false
        }
    }
}
```

**Comment by christopherthielen** [comment]
dynamic params will be in `1.0.0-alpha.1`

**Comment by duncanmcdowell** [comment]
@christopherthielen will you be able to provide (basic) documentation on dynamic params when 1.0.0-alpha.1 is released?

**Comment by burzum** [comment]
Is there any way to make this work with 0.2.x? I'm messing around with this now for nearly three days. My goal is to make search filters persistent. I'm storing my query params in a cookie and read them from there and set them view $location.search(). I call my service that does that in the resolve. This works when I enter the page and it sets the params. When I go to another page the state changes, then I go back to my page where I want the filters to be applied they're gone. I really can't figure out a way to keep them there... It's a pain that there seems to be no sane way to simply merge optional query params or stored query params to the state that is being executed. Any ideas how to resolve this?

**Comment by christopherthielen** [comment]
@burzum Dynamic params are different than what you describe. Dynamic params are parameters that can change without their state being entered again.  When a normal param changes, the state is exited and re-entered.
