### ISSUE TITLE
$stateParams remove encode characters

### ISSUE THREAD

**Issue by lexyfeito** [angular-ui/ui-router#2613]
So, i have a webapi application where it generated a code for reseting a password. An email is sent to the user with link like http://mysite.com?code=thisisacode+with+specialcharacters, the characters like '+' get encode in the url and when it gets to the controller and i use $stateParams to get the code the characters like '+' are removed. Does anyone know of a way to get this url decoded. Thank you!

**Comment by eddiemonge** [comment]
Removed or encoded?

**Comment by lexyfeito** [comment]
So it seems like what it is happening is that the plus sign '+' is being change to an space %20, i am still havent figure out if this is being done by the browser or ui-router is doing it. Most likely it is being done by the browser because i did some debugging and the params where being receive with the plus sign changed to %20. i did some research and it seems like the browser treats plus signs in the uri as if spaces.

**Comment by eddiemonge** [comment]
easy enough to figure out. You can console log the window.location before anything else loads

**Comment by lexyfeito** [comment]
So yeah it is the browser doing it.

**Comment by eddiemonge** [comment]
Closing this as it doesn't seem to be ui-router bug then. Maybe try to not use + or encode them first?

**Comment by lexyfeito** [comment]
yes i have already apply a work around, where i just replace %20 with '+' since this specific uri its not supposed to have any space. thank you so much
