### ISSUE TITLE
Anchor Stuck With Non-interactive Appearance

### ISSUE THREAD

**Issue by kmccullough** [angular-ui/ui-router#2617]
If I use `ui-sref="someRoute({ someParam: someResource.someProp })"`, where _someResource_ is an object that will be populated asynchronously, then even after _someProp_ is set, the anchor remains in a non-interactive appearance, where cursor is an arrow rather than a pointer hand. I have to use an ngIf so that the expression isn't evaluated until after _someProp_ is set, but that forces me to have to hide such anchors, rather than just having them non-interactive until such time that they can properly be resolved.

**Comment by eddiemonge** [comment]
how are you populating it? seems like thats data that should be in a resolve

**Comment by kmccullough** [comment]
In my particular use case the link is one of many in a submenu under a main menu item. The main menu item is for a collection of things and once you select one of them the submenu opens (or remains open if an individual thing was already selected) to show further options for the individual thing. The param is a property of the thing in question, but is still being retrieved from the back-end at the time that the menu items are visible, and will change when another thing is selected. The parameter is passed to the link like this, so I  don't know how that goes into a resolve. My desire is that the menu not have to be hidden while  the new thing loads, but just be disabled, but I am not able to  get it to modify the link without using ng-IF. Failing some fix, perhaps something like ngAttr would be useful here to make sure the uiSref stays up to date.

**Comment by christopherthielen** [comment]
You should use `ui-state` and `ui-state-params` for dynamic srefs: 

http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.directive:ui-state
http://plnkr.co/edit/iwIDC8oNICBIb4OXFHrd?p=preview

**Comment by kmccullough** [comment]
@christopherthielen It looks like from your plunk that it would do what I want, and this ticket may be closed, but I am still having trouble downloading the correct version of the library to make this work simultaneously with the other things we've discussed, elsewhere. Perhaps you wouldn't mind helping me out with that? (subone "@at" subone ".dot" org).

**Comment by kmccullough** [comment]
Is this directive being replaced in 1.x? I can't seem to access it.

**Comment by christopherthielen** [comment]
@kmccullough looks like that got merged after the 1.0.0alpha0 

It's in master but wasn't in the released version.

I'm hoping to release alpha.1 in the next 1-2 weeks
