### ISSUE TITLE
Remove the ui-view wrapper element

### ISSUE THREAD

**Issue by devmarwen** [angular-ui/ui-router#2618]
Assuming that I have this:

```html
<div ui-view='layout'></div>
```
After hitting a route it become:

```html
<div ui-view='layout'>
  <div>Some other content</div>
</div>
```
What I'm trying to get is this, without the wrapper element containing the `ui-view`:

```html
<div>Some other content</div>
```
How can I achieve this?

**Comment by eddiemonge** [comment]
Why?

Closing this as it doesn't seem to be a bug or issue. If discussion does reveal something, will reopen it.
