### ISSUE TITLE
Support for promises in default params

### ISSUE THREAD

**Issue by jbmikk** [angular-ui/ui-router#2620]
I'm using version 0.2.8.

This is the error I'm getting: **Default value ([object Object]) for parameter 'timezone' is not an instance of Type (string)**.

        params: {
            timezone: ['userService', function(userService) {
                return userService.ready.then(function() {
                    return userService.getUser().timezone;
                });
            } ]
        },

Wouldn't be a good idea to have default params support promises?
I have a use case where the default param for a state depends on data brought from the server. This data may or may not be already available, depending on whether the service is done loading.

**Comment by christopherthielen** [comment]
Sorry, parameter handling must be synchronous.   It occurs _before_ a transition starts, and we synchronously reject invalid transitions.  I don't see async default parameters happening any time soon.

**Comment by christopherthielen** [comment]
in 1.0 you can do something like this: http://plnkr.co/edit/wxmpV1X8JP9dOgLR2wOO?p=preview to redirect the transition after fetching your parameter value async

**Comment by jbmikk** [comment]
I understand, that means that achieving the same thing 0.2 would require using the deprecated $stateChangeStart plus event.prevenDefault.
