### ISSUE TITLE
Controller not re-initialized when using named views and params

### ISSUE THREAD

**Issue by foote-Greg** [angular-ui/ui-router#2625]
Hello,

We have a an ionic app that has states configured as such:

```
 .state('app.insp-question', {
         url: '/inspection/question',
         params: { qaPackage: null, room: null },
         views: {
             'menuContent': {
                 templateUrl: 'templates/inspection/question/question.tmpl.html',
                 controller: 'questionsController',
                 controllerAs: 'vm'
             }
         }
     });
```

And code that navigates to the state as such:

```
var data = {
                qaPackage: vm.qaPackage,
                room: vm.room
            };
$state.go('app.insp-question', data, { reload: true });
```

However the controller only initialized one time, event though we are passing in the reload: true option...

Any Ideas on what we are doing wrong ?

Thanks 
Greg

**Comment by foote-Greg** [comment]
It appears that there is a bug that disregards the value true for the reload option...

If the state name is passed as a string it works:

$state.go('app.insp-question', data, { reload: 'app.insp-question' });

**Comment by foote-Greg** [comment]
Actually that did not work either....

I had to add a parameter (that is don't need or use) to the url alike so

.state('app.insp-question', {
url: '/inspection/question/:bs',
params: { qaPackage: null, room: null },
views: {
'menuContent': {
templateUrl: 'templates/inspection/question/question.tmpl.html',
controller: 'questionsController',
controllerAs: 'vm'
}
}
});

then pass in Date.now() as the value to the bs parameter so that it is always different

**Comment by christopherthielen** [comment]
Try adding `cache: false` to your state def to tell ionic not to cache

**Comment by foote-Greg** [comment]
Thanks !!  That worked !!!

**Comment by mhartington** [comment]
Just to chime in on this...

@foote-Greg the controller not being destroyed is part of Ionic's view caching mechanism. So once the view and controller have been created, they're never destroyed, but disconnected when they are no longer the active view. This is how we're able to do things like swipe-to-go-back.

Disabling caching in this case, while it may work, is not recommended approach you should be taking. Instead you can use `$ionicView` event. 

http://ionicframework.com/docs/api/directive/ionView/

This allow you to do

```
$scope.$on('$ionicView.enter', function(){
  console.log('call my dataService, or update scope data');
});
```

**Comment by foote-Greg** [comment]
Awesome !  Thanks !!!

**Comment by christopherthielen** [comment]
Thanks for the info @mhartington.  I'll definitely be pointing people to this issue in the future.
