### ISSUE TITLE
How to handle angularJS UI router with dot (.) character

### ISSUE THREAD

**Issue by phpjagadeesh** [angular-ui/ui-router#2629]
I have URL for state function as follows

`www.test.com/search.go?param=test`

The issue is handle dot(.) character in URL pattern. The URL with dot character not handling properly by angularjs UI router. Let me how handle this dot character.

` .state('testsearch', { 
url: '/test/search.go?:param=', 
views: { 
main: { templateUrl: 'testTemplate.html', 
controller: 'testcontroller' }
 } }) `

**Comment by christopherthielen** [comment]
http://plnkr.co/edit/YehKSecaHvbJKrG4Ypce?p=preview  Seems to work fine for me.

In the future, please use StackOverflow for support requests; this is an issue tracker to report bugs.  http://bit.ly/UIR-SOF
