### ISSUE TITLE
Error with unit testing

### ISSUE THREAD

**Issue by davitykale** [angular-ui/ui-router#263]
I'm working on an Angular app that uses Angular UI-Router for routing and maintaining state. I am having a hard time getting my unit test to even compile. I've checked out the other GitHub issues relating to ui-router and unit testing, and nothing seems to help. It seems that no matter what I do, I keep getting the following error:
```
Error: State '' is not navigable
```
I have the following states set up in my app, as well as the following redirects:
```
app.config(function($stateProvider, $urlRouterProvider) {

var paramList = '?beds&lat&lon&zoom';

$urlRouterProvider
    .when('', '/')
    .when('/', '/search')
    .when('/search', '/search/list')
    .otherwise('');

$stateProvider
    .state('search', {
        abstract: true,
        url: '/search',
        templateUrl: 'views/search.html',
        controller: 'SearchCtrl'
     })
        .state('search.list', {
            url: '/list' + paramList,
            templateUrl: 'views/search-list.html'
         })
        .state('search.map', {
            url: '/map' + paramList,
            templateUrl: 'views/search-map.html'
        })
    .state('search.listing', {
        url: '/listing/:id' + paramList,
        templateUrl: 'views/search-listing.html'
    })
    .state('favorites', {
        url: '/favorites',
        templateUrl: 'views/favorites.html'
    })
});
```
I've eaten up an entire day trying to get a single test to work, but no matter what approach I take, I always end up at this same error. I have an e2e test running just fine.

**Comment by LoganBarnett** [comment]
@Dovernh this is what I've done to get a working unit test with ui-router:

*Test*
```javascript
'use stict';

describe('generation', function() {
  var GenerationSetService, $q, $timeout;
  beforeEach(module('generation'));
  beforeEach(module('/app/generation/generation_set.list.tpl.html'));

  beforeEach(module(function($provide) {
    GenerationSetService = {
      query: function() {
        var deferred = $q.defer();
        $timeout(function() { deferred.resolve([]); });
        return deferred.promise;
      }
    };

    $provide.value('GenerationSetService', GenerationSetService);
  }));

  beforeEach(inject(function(_$q_, _$timeout_) {
    $q = _$q_;
    $timeout = _$timeout_;
  }));

  it('routes to a generation set list', function() {
    inject(function($state, $rootScope) {
      $state.go('generation_sets');
      $timeout.flush();
      expect($state.current.name).toEqual('generation_sets');
    });
  });
});
```


*Implementation*
```javascript
'use strict';

angular.module('generation', ['ui.router', 'generation.directive', 'generation.service'])
  .config(['$stateProvider', function($stateProvider) {
    $stateProvider.state('generation_sets', {
        url: '/generation_sets'
      , templateUrl: '/app/generation/generation_set.list.tpl.html'
      , controller: 'GenerationSetListCtrl'
      , resolve: {
          generationSets: ['GenerationSetService', function(GenerationSetService) {
          return GenerationSetService.query();
        }]
      }
    })
  }])
;
```

It uses the `$timeout` as described above. My resolved mock service depends on `$timeout` so it may be the culprit. I haven't tried testing a state without a resolve yet to see if `$timeout` is indeed required. I hope that helps!

**Comment by Dovernh** [comment]
Logan,

Thanks for the reply.  I took another approach using ng-html2js.

Paul

**Comment by nateabele** [comment]
So, can everybody confirm that this is triggered by template loading (i.e., that the problem goes away if you inline all your templates)?

If so, we may be able to get to a solution by finalizing the work on [this PR](https://github.com/angular-ui/ui-router/pull/1777) (you can ignore my comment about 1.2).

Basically, if we switched to `$templateRequest`, we could maybe ship something in the distro that would allow people to easily mock that out with a version that just returns a promise with an empty string or something.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
