### ISSUE TITLE
0.2.16 breaks state data inheritance

### ISSUE THREAD

**Issue by hackel** [angular-ui/ui-router#2631]
I believe this is a result of: $state: make state data inheritance prototypical (c4fec8c7).

In my code, I use `data.hasOwnProperty(someVar)` to check whether a requested value exists.  The switch to prototypical inheritance breaks this check and causes a lot of breakage on my site.  This is a major breaking change, thereby necessitating a 0.3.x version!  I've been able to fix this by simply changing my checks to `someVar in data`, but it took quite a bit of debug time to isolate the cause of the failure.

**Comment by eddiemonge** [comment]
You are probably right about this being a breaking change. It might be hard to roll it back now though since there have been a few version releases since then and most effort is going towards 1.0

@christopherthielen thoughts?

**Comment by paol** [comment]
We have recently tried to upgrade form 0.2.15 to 0.2.18 and ran into this problem. In our case we were iterating over the data object with angular.foreach(), which misses the inherited properties. It is indeed a breaking change.

**Comment by christopherthielen** [comment]
Unfortunately the cat is out of the bag.  I've noted this as a BC in the 1.0 upgrade notes.

**Comment by motin** [comment]
I came here from a google search on the subject, so for other users searching for more information on the subject including @christopherthielen's polyfill to get the old behavior back, read this: http://stackoverflow.com/questions/38676633/angular-ui-router-child-of-abstract-state-not-inheriting-data-in-statechanges/42107929#42107929

**Comment by christopherthielen** [comment]
@motin thanks for the nice writeup on the StackOverflow question.

I've updated the plunker demonstrating how to merge data on the child with the data on the parent: http://plnkr.co/edit/Wm9p13QRkxCjRKOwVvbQ?p=preview
