### ISSUE TITLE
Is it possible to defer the $viewContentLoaded event?

### ISSUE THREAD

**Issue by notbogdan** [angular-ui/ui-router#2638]
I'm building an app using Angular JS & Meteor which I hope to make spiderable. So far it's been going fairly well, with Meteor and Angular in conjunction with the [spiderable-ui-router][1] plugin handling google's spider pretty well up until the route returns a template which is populated by reactive data, in which case it serves all the HTML except that which is generated with the reactive data. 

Reading the plugin page I can see that it works based off the `$viewContentLoaded` event: 

> ...we need to wait until the page is fully rendered by ui-router, which is signaled by a '$viewContentLoaded' event.

So I was wondering, is it possible to switch off `$viewContentLoaded` for a route until I decide the route (and its corresponding template) are loaded myself? So perhaps I could do eventually do something like this: 

Route:

    .state('blog.singlePost', {
      url: '/article/:postId',
      template: '<single-post></single-post>',
      //This would theoretically let me defer the $viewContentLoaded 
      //event until a later time 
      emitContentLoaded: false
    })

And then in the controller for this route: 

    controller: function($scope, $rootScope, $stateParams, $reactive) {
    
      $reactive(this).attach($scope);
    
      //subscribe to posts
      this.subscribe('posts', '', {
        //This is where I know the data 
        //I need has been loaded
        onReady: function () {
          //Signal that the route view is complete and hopefully
          //the spiderable plugin will render the full template 
          //for Google's spider 
          $scope.$emit('$viewContentLoaded');
        }
      });
    }

  [1]: https://atmospherejs.com/greenydragonny/spiderable-ui-router

**Comment by eddiemonge** [comment]
This could probably be achieved in other ways but is better suited for stackoverflow.
