### ISSUE TITLE
$scope.$watch not disengaged in time, $state gone

### ISSUE THREAD

**Issue by phazei** [angular-ui/ui-router#2643]
This issue happens on 0.2.18, but started from 0.2.16, last worked on 0.2.15 and discovered it.

I have a controller with a $watch on a method that uses a $stateParams, when changing state away from the page, the $watch is called one last time that it hadn't ever been prior.  The new view is already loaded, and the $stateParams from the page with the controller aren't there.

```
$scope.$watch(function() { return myMethod($scope.$stateParams) }, function(response) {

});
```

I'm injecting $stateParams into the $rootScope in .run().  If I inject $stateParams directly into the controller its fine.

But why isn't the $watcher being cleared until after the view has changed?  What changed in 0.2.16 that leaves the $watcher that much longer?  Shouldn't it be cleared before the next view has been loaded?

**Comment by phazei** [comment]
Actually, it doesn't just effect $watch, but other items that are bound in the view.  I have a page with a
```
//template:
<button ng-disabled="myFunc()">
//controller:
$scope.myFunc = function() {
    return $scope.form.item == 'value';
}
```
Which on changing state away from the form page gives an error about $scope.form being undefined.

**Comment by christopherthielen** [comment]
dupe #2614
Recommend using 0.2.15 until we release 0.2.19
