### ISSUE TITLE
ui-router loads html using post request and post parameters

### ISSUE THREAD

**Issue by ptummuru** [angular-ui/ui-router#2646]
I have a requirement which i get post url and parameters in post body. when i tried with $stateprovider to get parameters in post body i am getting null values. Does post request with parameters in the body is supported in $stateprovider?

**Comment by christopherthielen** [comment]
Recommend asking on stackoverflow.  We don't have enough resources to offer support via the issues tracker. This tracker is for bugs and feature requests

http://bit.ly/UIR-SOF
