### ISSUE TITLE
double request!

### ISSUE THREAD

**Issue by fatefan** [angular-ui/ui-router#2652]
function ($stateProvider, $urlRouterProvider) {
    $stateProvider
      .state('list',{
        url:'/list',
        templateUrl:'/component/implementationShop/list.html',
        resolve: {
          infoListData:["$http",function ($http) {
            return $http.get('api/shopCustomer/implementList',{params:{page:1,size: 20}, withCredentials: false, data :"json"})
          }]
        },
        controller:'listCtrl'
      })
};

请求了两次！(double request!) 
where  hava problem?

![image](https://cloud.githubusercontent.com/assets/6036283/14096426/59d9fca2-f59b-11e5-9d0b-1f94e6a76858.png)

**Comment by christopherthielen** [comment]
I don't see anything obviously wrong with your state definition.  Can you recreate this in a plunker?

http://bit.ly/UIR-Plunk

**Comment by fatefan** [comment]
I am write $state.go('list') on my controller. now, I use $urlRouterProvider.when('', '/list') replace  $state.go('list') .  this is good work!

**Comment by christopherthielen** [comment]
ok
