### ISSUE TITLE
Dynamic params callback doc doesn't match code

### ISSUE THREAD

**Issue by briancmpbll** [angular-ui/ui-router#2653]
The [doc](https://angular-ui.github.io/ui-router/1.0.0-alpha.1/interfaces/ng1.ng1controller.html#uionparamsupdated) linked in the 1.0.0-alpha1 release notes give the wrong name for the callback. Your code uses uiOnParamsChanged but the doc gives uiOnParamsUpdated as the name.

**Comment by christopherthielen** [comment]
thanks; I will fix the docs
