### ISSUE TITLE
1.0.0-alpha.1: there is no dist/release folder and I unable to build project manually

### ISSUE THREAD

**Issue by pavel-blagodov** [angular-ui/ui-router#2656]

**Comment by christopherthielen** [comment]
hi @pavel-blagodov 


We no longer keep prebuilt files in the `/release` directory of the master branch of `angular-ui/ui-router`.  
We are publishing ui-router for ng1 to both npm and bower.   The released files are there in the bower release folder https://github.com/angular-ui/angular-ui-router-bower/tree/1.0.0-alpha.1 and in the npm package.

I'd like to hear your difficulties in building the project manually.

**Comment by pavel-blagodov** [comment]
hi @christopherthielen 

no difficulties in building the project manually. My bad. I didn't update/install necessary dependencies.
