### ISSUE TITLE
Quick switch between routes (memory leak in IE)

### ISSUE THREAD

**Issue by glibey** [angular-ui/ui-router#2658]
I am using Angular 1.5 and ui router 0.2.13.
In Internet Explorer 11 (EDGE too) quick switching between routes takes memory it grow up and up and never released.  

Any ideas?

**Comment by christopherthielen** [comment]
Make a plunker that reproduces this memory growing and we'll take a look.

**Comment by glibey** [comment]
Please look [here](https://embed.plnkr.co/gDDN9b0FDoqCmEFQZgh9/). 
I tried to reproduce and memory slowly grow up and not released in IE.
I switched 20 times between routes and get this memory chart:

![screenshot 2016-03-31 13 23 54](https://cloud.githubusercontent.com/assets/383555/14173000/03cd287a-f744-11e5-8cd2-fbb53b4e6dff.png)

I see the same issue when I use gmail while switching between email by pressing next mail button. Curious if it's a global IE issue.


Chrome seems to work well with this plunk.

**Comment by christopherthielen** [comment]
Thanks for the plunker...

**Comment by vdyakur** [comment]
Hi Christopher,

Did you have a chance to look at the issue? We have similar issue with Angular in IE

**Comment by christopherthielen** [comment]
I didn't have a chance... I need to download a VM just to get windows running and haven't had time to invest.  I suspect this behavior isn't the fault of ui-router, so I haven't made it a priority.

Can those of you who are experiencing this issue perhaps do some more diagnostics?  What tools are available for debugging IE and Edge?

**Comment by imorgoch** [comment]
Hi Christopher,
We did an update in test exapmle to adopt latest Plunker's changes. So, this link can be used again.
https://embed.plnkr.co/gDDN9b0FDoqCmEFQZgh9/

It works in Edge browser (Windows10 OS), and every time when you switch the tab - memorry sligtly grows and doesn't release.
We will provide you Plunker link soon, which will work in IE too. Aslo we will add automated script to show memory leak explicilty.

IE and Edge have inbuilt debugger tool (F12). Or did you ask any tool do debug browser itself?

**Comment by christopherthielen** [comment]
@imorgoch I ran your plunker in chrome, with heap allocations traced and it doesn't seem to be leaking any memory.

I ran [this version of your plunker](https://embed.plnkr.co/gDDN9b0FDoqCmEFQZgh9/) which switches between route1 and route2 rapdily for 2 minutes. 

![screen shot 2016-09-22 at 1 06 56 pm](https://cloud.githubusercontent.com/assets/2053478/18760181/9cb034fa-80c5-11e6-955a-be7f7daa12a4.png)

> Gray bars indicate objects that were allocated during the timeline, but have since been garbage collected
[reference](https://developers.google.com/web/tools/chrome-devtools/profile/memory-problems/allocation-profiler?hl=en)

I'm not sure the heap growth on Edge can be attributed to a ui-router bug, else we would also see it in other browsers.

> memorry sligtly grows and doesn't release.
Javascript engines use garbage collection. Are you sure the memory isn't ever garbage collected?

**Comment by christopherthielen** [comment]
I ran this a test on Edge:

![screen shot 2016-09-22 at 2 25 34 pm](https://cloud.githubusercontent.com/assets/2053478/18762879/769e7e10-80d0-11e6-8d88-5160ae126a7b.png)

It doesn't appear that the javascript objects increase significantly over the 2.5 minute run.   Total process usage increases while the routes change back/forth, but are garbage collected at around 2:40 back to about the same as the initial baseline snapshot.
