### ISSUE TITLE
Feature Request: Passing New Parameters in $state.go()

### ISSUE THREAD

**Issue by engemasa** [angular-ui/ui-router#2659]
From my studying it looks like you have to have the parameters defined in 'params' of the the state you're going to in order to receive them. It would be much easer to be able to pass what ever objects we would like in the params object when calling "$state.go(state, params)"

Documentation: [ui.router](http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$state)

From my understanding, this is how it's accomplished:
**route definition:**
```JavaScript
$stateProvider.state('destination', {
  url : '/destination',
  templateUrl : 'destination.html',
  params : { obj : null, someId : null } // properties MUST be defined in the to state
});
```

**my controller**
```JavaScript
var params = {
  obj : { name : 'Joe Smith', age : 27, married : true },
  someId : 123
};
$state.go('destination', params);
```

It would be easier to do this:

**route definition:**
```JavaScript
$stateProvider.state('destination', {
  url : '/destination',
  templateUrl : 'destination.html'
});
```

**my controller**
```JavaScript
var params = {
  someUser : { name : 'Joe Smith', age : 27, married : true },
  id : 12,
  date : '2016-03-30'
};
$state.go('destination', params);
```

**Comment by eddiemonge** [comment]
Have you tried doing that?

Seems more like you want dynamic parameters, which are coming in 1.x.x

**Comment by engemasa** [comment]
As per the documentation:

> Only parameters specified in the state definition can be overridden, new parameters will be ignored

I have found that if the parameter isn't defined in the definition of the state/route, new parameters are ignored and are not received by the destination route. My work around for now is we placed a "dummy object" in each route that we can put add additional parameters to.
