### ISSUE TITLE
1.0.0-alpha.1: $onInit() called twice whe routing to angular 1.5 component

### ISSUE THREAD

**Issue by christopherthielen** [angular-ui/ui-router#2660]

**Comment by mtpultz** [comment]
@christopherthielen this seems to occur in Angular 1.5.9 when routing using the component router.  I might be wrong, but it appears to occur on the default routes only.

**Comment by christopherthielen** [comment]
Component router or ui-router?  There was a bug in ui-router alpha.1 but it should have been fixed.

**Comment by mtpultz** [comment]
Sorry @christopherthielen it was unrelated.

**Comment by kikar** [comment]
Hey @mtpultz any idea which 1.5.x version start presenting this bug?
