### ISSUE TITLE
Content inside <ui-view> renders again when leaving the state

### ISSUE THREAD

**Issue by onlywei** [angular-ui/ui-router#2663]
In my default state, the HTML is like this:

``` html
<ui-view>STUFF</ui-view>
```

When I LEAVE the default state to go to another one, the contents inside (in this case, STUFF), gets double-rendered before I get to the new state.

See JSBin: http://jsbin.com/valusu/edit?html,js,console,output
Notice that "default-html" gets logged to console when changing to the "foo" state, or the "bar".
It also gets logged AGAIN when changing FROM "bar" to "foo" and vice versa.
This effectively re-triggers all directive link functions inside that default HTML.

**Comment by christopherthielen** [comment]
do you know if this is a regression?

**Comment by onlywei** [comment]
@christopherthielen this does not appear to be a regression as this happens in 0.2.15 as well.
