### ISSUE TITLE
Controller gets a cycle when using 1.0.0-alpha but ok with 0.2.18

### ISSUE THREAD

**Issue by trajano** [angular-ui/ui-router#2665]
To help with debugging I have a block that looks like this

```
<div ng-if="devUser">
  <pre>{{ ctrl | json }}</pre>
</div>

```
Where I do a dump of the current controller state.  However when I use the current alpha version of angular-ui-router, I get a cycle in the controller and JSON.stringify complains on both Firefox and Chrome.

**Comment by christopherthielen** [comment]
interesting.  I suspect it's the newly added `$scope.$resolve` (or `controllerAs.$resolve`)

```
app.filter('noresolve', function() {
  return function(input) {
    let copy = Object.assign({}, input)
    delete copy.$resolve;
    return copy;
  }
});
```

```
<div ng-if="devUser">
  <pre>{{ ctrl | noresolve | json }}</pre>
</div>
```

See this plunker: http://plnkr.co/edit/dfBRoIvyzbCelXGLsDU1?p=preview


note: `$scope.$resolve` is coming soon in 0.2.19 as well.

**Comment by trajano** [comment]
Can it be refactored to $$resolve? since $$ prefixed items are ignored by toJson() https://github.com/angular/angular.js/blob/master/src/Angular.js#L1166

**Comment by christopherthielen** [comment]
We are using `$resolve` to be consistent with what ngRoute does for "component templates": https://docs.angularjs.org/guide/component

Because of that I don't think we should rename it.
