### ISSUE TITLE
1.0.0-alpha.1: $state.params doesn't have initial params value in resolve

### ISSUE THREAD

**Issue by pavel-blagodov** [angular-ui/ui-router#2666]
```
.state('app.state', {
        url: '/url?param',
        params: {
          param: {
            value: 'value'
          }
        },
        resolve: {
          getParamsValue: function ($state) {
           console.log($state.params.param); // undefined
          }
        }
      })
```

**Comment by pavel-blagodov** [comment]
but $stateParams has those values. In some cases I need values from $stateParams but in others from $state.params. Is it by design?

**Comment by pavel-blagodov** [comment]
Also there is no way to get parent value in example like this
```
.state('app', {
        url: '/url?param1',
      })
.state('app.state', {
        url: '/url-2?param2',
        params: {
          param: {
            value: 'value'
          }
        },
        resolve: {
          getParamsValue: function ($state, $stateParams) {
           console.log($state.params.param1); // undefined
           console.log($stateParams.param1); // undefined
          }
        }
      })
```
$state.go('app.state', {param1: 1, param2: 2})

**Comment by pavel-blagodov** [comment]
I have figured out there is new $transition$.params() that guy has all I need.

**Comment by christopherthielen** [comment]
> I have figured out there is new $transition$.params() that guy has all I need.

That's correct. We're moving away from global state, such as `$state.current`, `$stateParams`.

**Comment by phazei** [comment]
$transitions.params() no longer exists, only in the "trans" for the callback.  Was it removed?

**Comment by christopherthielen** [comment]
@phazei it never existed on `$transitions` (the singleton `TransitionService` object).  It's always only been on `$transition$` (a `Transition` object)
