### ISSUE TITLE
Possibility to extend an existing state 

### ISSUE THREAD

**Issue by git4d** [angular-ui/ui-router#2667]
Hello,

Is there a way to extend an existing state in another module's config block? I'm working on an extremely modular application, some 3rd party modules must be abble to be plugged or removed from the core without breaking the main functionalities. And in my case I would need a 'plugin' module to be abble to register a view in a state defined by the core module. Something like this: 

```
angular
    .module('myApp', [])
    .config(function($stateProvider) {
        $stateProvider.state('myState', {
            views: {
                mainView: { templateUrl: 'mainTpl.html' }
            }
        });
    })
;

angular
    .module('myPlugin`, [])
    .config(function($stateProvider) {
        $stateProvider.extendState('myState', {
            views: {
                otherView: { templateUrl: 'otherTpl.html' }
            }
        });
    })
;
```
I've tried to achieve this by extending the given state in the run block, but as the state is already registered, it has no effect.

```
angular
    .module('myPlugin`, [])
    .run(function($state) {
        // this does not work...
        angular.merge($state.get('myState'), {
            views: {
                otherView: { templateUrl: 'otherTpl.html' }
            }
        });
    })
;
```

Thx

**Comment by eddiemonge** [comment]
Can you do it as a child state instead?

**Comment by git4d** [comment]
You're right, I've managed to obtain the expected behaviour with nested states and ui-router-extras sticky states. Thanx
