### ISSUE TITLE
latest NPM dist tag points to alpha version

### ISSUE THREAD

**Issue by felixfbecker** [angular-ui/ui-router#2668]
The `lastest` dist tag of angular-ui-router currently points to 1.0.0-alpha.3. That means running `npm install angular-ui-router` will install an unstable pre-release alpha version, which is bad. `latest` should point to 0.2.18, and maybe a `next` dist tag to the alpha.

**Comment by eddiemonge** [comment]
@christopherthielen

**Comment by christopherthielen** [comment]
I tagged 0.2.18 as latest. I didn't even know npm tags was a thing before this!
