### ISSUE TITLE
Angular UI-router parent state not active after changing to child state

### ISSUE THREAD

**Issue by ssuhat** [angular-ui/ui-router#2682]
I got a problem:

When I click home for the first time, it successfully add "active" class to Home and Submenu Flow.

But when I click the submenu Follow, the "active" class at it parent (Home) is gone. How can I fix that?

Here is the plnkr:

http://plnkr.co/edit/NJRx7RT0TRg04Wbw6kUO?p=preview

**Comment by ssuhat** [comment]
Solve it. by extending the class subdrop

**Comment by AlexisMagis** [comment]
Hello,
`<li class="top" ui-sref-active="heaader_active"><a ui-sref="home.flow"><i class="fa fa-cloud-upload"></i>&nbsp;Home</a></li>`
In this exemple the link 'home' can only be highlighted when you are in the 'home.flow' state or his children ('home.flow.john-doe' etc...). Try using another configuration with `ui-sref="home"`

**Comment by ssuhat** [comment]
Can you help me fix the plnkr? I don't really get what you mean.

Thanks.

**Comment by AlexisMagis** [comment]
http://plnkr.co/edit/TyTnoDKqy5Y8JV3jklFj?p=preview

Done :) `abstract: true` was not necessary. This way you can set `ui-sref="home"` as expected

**Comment by eddiemonge** [comment]
Sounds like this is fixed then

**Comment by ssuhat** [comment]
I'm sorry for the late reply. Got things to do. 

But I don't want ppl can access my abstract state. Like if they click home or they type it manually on url

**Comment by AlexisMagis** [comment]
Not at my office right now but then you could try to add a controller to your abstract state, Controller that makes a $state.go redirection to one of home's children.
Not sure if its the brightest solution tho...

**Comment by AlexisMagis** [comment]
Forget about my last solution ^^. It can't work cuz if the 'home' state is abstract you cannot transition to it.
See an alternative solution (the 'home' state isn't abstract but an automatic transition to a child is triggered when trying to access):
http://plnkr.co/edit/TyTnoDKqy5Y8JV3jklFj?p=preview

**Comment by ssuhat** [comment]
@AlexisMagis works perfectly. thanks a lot!

**Comment by ssuhat** [comment]
@AlexisMagis I need more suggestion. I just realize 2 days ago but still not found any solution. When using `redirectToChild` like in example, every time I reload the page, when I'm on child state (like detail page), it will redirect me back to `redirectToChild` page instead of stay at current state.

Any suggestion?
