### ISSUE TITLE
[Incompatibility] Nested state being build twice when using angular-material

### ISSUE THREAD

**Issue by cyrilgandon** [angular-ui/ui-router#2689]
I have tried to make the clearest [plunkr](http://plnkr.co/edit/pa1i1rSBtzjnFTzmJiO3).

You can see that on initialisation, the state is being build only once. When you change between state, each time the nested state is being built twice.
I reduce the problem to the inclusion of angular-material. It should, or not, be the reason, but the problem disappears if you don't use angular-material.

Is there a possible workaround. This is a big problem for us for performance point of view.

Thank you!

**Comment by cyrilgandon** [comment]
I just test with alpha version of the v1, it works fine. I'm a little worried to use the alpha version for production, is it safe enough?

**Comment by eddiemonge** [comment]
Things might break before the release candidate but it should be fine.
