### ISSUE TITLE
Combination of Required/Optional Query Parameters

### ISSUE THREAD

**Issue by jasteph** [angular-ui/ui-router#2690]
I am having some trouble defining a combination of required/optional parameters for a state.

Assume I have a state 'myPage' with three params - ```param1```, ```param2```, ```param3```.

To navigate to the state I would like to require that ```param1``` be defined in the url, while ```param2``` and ```param3``` can be optionally defined. If a user hits '/myPage' I want to handle the case using $urlRouterProvider.otherwise. 

```
$stateProvider
   ...
   .state('myPage', {
      url: '/myPage?param1&param2&param3',
      templateUrl: 'app/myPage.view.html',
   });

$urlRouterProvider.otherwise(function($injector, $location) {
   // handle routing for accessing unknown route
});
```

I've seen people talk about using a params object with squashing and setting a default value, but I have been unsuccessful in getting that to work.

I believe I could accomplish this using a regex, but this seems error prone.

I also have a requirement that my urls must use query parameters

**Comment by eddiemonge** [comment]
This is a better question to ask on stackoverflow as its an implementation detail and not a ui-router bug.
