### ISSUE TITLE
Child state is not resolved if parent state has resolve block with the same name.

### ISSUE THREAD

**Issue by metrophos** [angular-ui/ui-router#2695]
After adding this feature #1934 it is not possible to have resolve blocks with the same name as parent/child.

Here is an example:
[http://plnkr.co/edit/vR0mej?p=preview](http://plnkr.co/edit/vR0mej?p=preview)
If changing the plnkr ui-router lib version higher than 0.2.14 the second resolve block doesn't run anymore.

**Comment by christopherthielen** [comment]
Hi, I think this isn't a bug. Put your resolve on the state, not the view and it should work.  

http://plnkr.co/edit/0m7Uwq?p=preview
