### ISSUE TITLE
State change before destruction since 0.2.16 leading to leaks

### ISSUE THREAD

**Issue by ioncube** [angular-ui/ui-router#2697]
Perhaps due to 1be13795, since 0.2.16 it seems that a change of view may create the incoming view before the old one is destroyed. This showed up with directives on an outgoing view being destroyed after ones are created on the incoming view, leading to memory leaks in our application. I feel it shouldn't matter whether a new view is created before the previous one is destroyed, but it's certainly helpful if that's the case as it seemed to be previously, though whether that was by luck or design I'm unsure.

**Comment by eddiemonge** [comment]
Can you show an example of a memory leak occurring on a site?

**Comment by ioncube** [comment]
Hi Eddie, first I must clarify that the leak itself is not in ui-router itself, but a side effect of the creation/destruction order. I've attached an indication of the behaviour differences when switching between 3 views with router 0.2.15 and 0.2.18. I've not attached heap profiles but suffice to say, analysing retainers showed that the leak relates to Uniform, which is used by a directive that applies it to specific elements and reverses it for those elements on destruction. On the face of it creating a new view before destroying the old one shouldn't cause an issue, but does for some reason and I could imagine other applications needing order to be guaranteed. Also, whereas prior to 0.2.16 the destroy before create order seemed deterministic, it's non-deterministic since. The also issue also only emerged with concated minimised sources and not when the application js components are loaded individually.

Behaviour with 0.2.15
![uniform-ui-router-0 2 15](https://cloud.githubusercontent.com/assets/1902741/14702871/cfa9ed1e-07a4-11e6-9fde-acf81b89b57a.png)

Behaviour with 0.2.18
![uniform-ui-router-0 2 18](https://cloud.githubusercontent.com/assets/1902741/14702876/d5c6534a-07a4-11e6-803f-1df675162a0c.png)

**Comment by christopherthielen** [comment]
I think this was fixed in 0.3.0

@ioncube can you check?
