### ISSUE TITLE
Image in Nav Bar reload every time

### ISSUE THREAD

**Issue by cs0511** [angular-ui/ui-router#2698]
Dear ui-router

I am using angular-ui-router 1.0.0-alpha.1, and I create nav bar like this [answer](http://stackoverflow.com/a/29577344/2093825).

The different is that, I use an image in the nav bar. So each time I change the nav tab, the image will be reloaded each time, this only occur in Safari. Chrome and Firefox work fine.

Any answer here will be appreciate.

**Comment by eddiemonge** [comment]
Reloaded how? This should really be asked in that stackoverflow question as its an implementation bug, not a ui-router bug
