### ISSUE TITLE
Possibly unhandled rejection with ng 1.5.5

### ISSUE THREAD

**Issue by celsomtrindade** [angular-ui/ui-router#2699]
When using ui-router v-0.2.18 and angularjs v-1.5.5 I keep getting this error 4 times:

> Possibly unhandled rejection: {}

I reversed angular to v-1.5.3 and the error is gone. Any ideas why? I didn't found anything related to this issue.

I also noticed this error shows up as soon as I insert the `ui.router` module.

**Comment by christopherthielen** [comment]
Looks like this behavior came from this commit: https://github.com/angular/angular.js/commit/c9dffde1cb167660120753181cb6d01dc1d1b3d0

And they added an API method to disable that: https://docs.angularjs.org/api/ng/provider/$qProvider

I think the ui-router code may need to chain `catch()` off of various promises now 👎

**Comment by christopherthielen** [comment]
Actually, that code doesn't seem to have landed in ng 1.5.5: https://github.com/angular/angular.js/blob/v1.5.5/src/ng/q.js

Are you sure you're using the released version of angular 1.5.5?

**Comment by celsomtrindade** [comment]
@christopherthielen I updated my files with bower and it said version 1.5.5 (both on the prompt and on the actual file) and i had to go back to 1.5.3 because of this error.

**Comment by christopherthielen** [comment]
@celsomtrindade 

I just fetched 1.5.5 final version from bower, and it doesn't have "Possibly unhandled rejection" in the angular.js file.  

```
╭─ christhielen@lappy486  ~/t
╰─  rm -rf bower_components; bower install angular#1.5.5 > /dev/null && grep "Possibly unhandled" bower_components/angular/angular.js
```

The pre-release versions of 1.5.5 did seem to have the change to `$q`. 

Pre-release build 1.5.5-build.4756+sha.165a862
```bash
╭─ christhielen@lappy486  ~/t
╰─  rm -rf bower_components; bower install angular#1.5.5-build.4756+sha.165a862 > /dev/null && grep "Possibly unhandled" bower_components/angular/angular.js
        var errorMessage = 'Possibly unhandled rejection: ' + toDebugString(toCheck.value);
```

I suspect if you re-fetch 1.5.5 it will not exhibit the error message.  Clear your bower cache (if that's a thing) first.
