### ISSUE TITLE
Abstract States, Non-Abstract Parent States and Default Child States

### ISSUE THREAD

**Issue by timkindberg** [angular-ui/ui-router#27]
I know we went back and forth on this several times already, but I think I may have found a need for this feature again. 

It seems as though we are trying to get to a place where states can function completely on their own without any url routing (correct?). So how would we know which child state to load automatically without specifying a `url` of `''`? Seems like we would need a `default` boolean property or something similar. 

Let me also attempt to define abstract states, and non-abstract parent states. Please let me know if I'm on the right track.

**Abstract State**
* must be a parent state
* a state that cannot be activated directly (via `transitionTo` method) without activating one of its children.
* must have a default child state (either with empty `url` or `default` property)
* if no `default` child state is set, first child state found will be used as default
* can be navigated to via url, but this really just activates default child state

**Non-Abstract Parent State**
* a normal state which has child states
* can be activated and navigated to directly (via `transitionTo` method or url), though any view directives will not be populated until navigation to on of it's child state OR one of its child states is set as default child (either with empty `url` or `default` property)
* default child state is optional

**Comment by sricc** [comment]
I agree with @kbaltrinic and @timkindberg's original request!  I have hit this exact use case with list, add and edit.  +1

**Comment by nateabele** [comment]
I'm in favor of @ProLoser's proposed implementation. We can roll that in once `Transition` objects are fully integrated.

**Comment by acollard** [comment]
@nateabele  Hopefully we can support returning a string and (state, param) objects like the following:

```javascript
.state('Account.Security', {
          redirectTo: 'Account.Security.ChangePassword', // OR
          redirectTo: { state: 'Account.Security.ChangePassword', params: { id: 123} }, // OR
          redirectTo: ['$state', 'authenticationService', function($state, authenticationService){ 
                //Some logic
                return 'Account.Security.ChangePassword'; // OR
                return { state: 'Account.Security.ChangePassword', params: { id: 123} };
            }]
        });
```
Personally I prefer redirectTo over abstract since it better explains what is happening.

**Comment by ProLoser** [comment]
@acollard yes and no. I feel it makes sense of you read it as "on entering this state directly" but it's not as intuitive when you think about going directly to a child state. 

I would prefer documenting it as "the abstract key can be true or you can give it a redirectTo string or function"

**Comment by nateabele** [comment]
The `redirectTo` concept is definitely more general, especially if you think about it as a way of having one state encapsulate logic to dispatch to several other states. I'll have to think about it.

**Comment by jrabbe** [comment]
There are two things which would be nice to have out-of-the-box.

1. A start state, so if you have a abstract state `super` which has two child states, `child1` and `child2` and marking `child1` as default, then transitioning to `super` would automatically transition to `child1`.
2. A history state, so if you exit `super` from `child2`, transitioning to `super` again would automatically go to the child state that was previously active, i.e. `child2`.

It seems like both of these things are possible using the `redirectTo` functionality suggested by @acollard, but it would be nice to be able to do it explicitly.

**Comment by ProLoser** [comment]
I think allowing you to create a redirect callback will allow you to do the
"last state"  stuff yourself because I have worked with a lot of
implementations and I think it's outside the scope of this issue

**Comment by nateabele** [comment]
Probably so, but currently history management is weak bordering on non-existent, so that particular use case is part of a larger set of things that need to be considered.

**Comment by nonplus** [comment]
I think `redirectTo` might be useful for non-abstract states, too (during refactoring of state names, it might be useful to redirect the old state name to a new state name), but is really a more general case.

FWIW, it's pretty easy to add basic support for a `default` child state configuration by decorating the $stateProvider (see [angular-ui-router-default](https://github.com/nonplus/angular-ui-router-default)).  Adding support for specifying a `{state, params}` configuration would be easy as well.

BTW, one might also consider specifying the default child state configuration by assigning a string value to the `abstract`setting instead of using a `default` property, e.g.:
```javascript
.state({
  abstract: '.defaultChild'
})
```

**Comment by christopherthielen** [comment]
UI-Router 1.0 preview is available: https://github.com/angular-ui/ui-router/tree/feature-1.0

**Comment by ProLoser** [comment]
God I am going to have to review this thoroughly because I don't like the component router

**Comment by nateabele** [comment]
> I don't like the component router

We've been getting a lot of that.

**Comment by ProLoser** [comment]
Is there an elegant version of this: https://github.com/angular-ui/ui-router/issues/948#issuecomment-75342784 that includes using resolved data? I'm racking my brain trying to come up with a way on the current router to have a default child based on resolved values. I'm getting a bit of redirect-loop-complexity with my old implementation thus far.

**Comment by cScarlson** [comment]
I do like to think that something like the following could be implemented, native to UI-Router:
https://github.com/nonplus/angular-ui-router-default

**Comment by christopherthielen** [comment]
@cScarlson in 1.0 that is super easy: http://plnkr.co/edit/YskNwwmQPm6AA6PNj0Cz?p=preview

**Comment by maartenzwart** [comment]
@christopherthielen: sorry to comment on this old post, but I'm thinking this answer is just what I need. When I try your code though, $state is always null, so the `$state.target(val)`  results in an error. 

Can you maybe give me a hint what to look for in such a case?
