### ISSUE TITLE
Get previous state 1.0.0-alpha.3

### ISSUE THREAD

**Issue by Itrulia** [angular-ui/ui-router#2702]
So I am trying to scroll to top when I enter a new state group but not when I am in the same state parent.

Currently I scroll to top whenever I change a state but I can't figure out how to get the last state to check if I need to scroll to top or not.

`````
// scroll to top..
$transitions.onSuccess({}, [() => {
    $window.scrollTo(0, 0);
}]);
````

**Comment by christopherthielen** [comment]
```js
// scroll to top..
$transitions.onSuccess({}, ['$transition$', ($transition$) => {
    var fromState = $transition$.from();
    if (... ){ 
      $window.scrollTo(0, 0);
    }
}]);
```

Check out the other methods available on Transition: http://angular-ui.github.io/ui-router/1.0.0-alpha.3/classes/transition.transition-1.html#entering

**Comment by Itrulia** [comment]
Ty very much!
