### ISSUE TITLE
When i use $state.reload() i lose whatever i set using $location.hash()

### ISSUE THREAD

**Issue by ehutch79** [angular-ui/ui-router#2703]
When i use $state.reload() i lose whatever i set using $location.hash()

using html5 mode and state has reloadOnSearch: false;

Is there anything i should be looking for here?

**Comment by christopherthielen** [comment]
Try setting updating the "#" state parameter using `$state.go(".", { "#": newvalue });`


http://plnkr.co/edit/sYTNd7hJIh8XqTrQ8k4m?p=preview

**Comment by ehutch79** [comment]
Thank you. That when followed up with $state.reload makes everything work.
