### ISSUE TITLE
ui router reload only some directives

### ISSUE THREAD

**Issue by wandiong** [angular-ui/ui-router#2704]
hi guys
as I seen the documentation ... by right **$state.reload** can help me to reload something when executed and it will reload entire controller which had that code
but I want to made only some directives. not entire controller , is there any way to do it? thanks before also much appreciated for helping :smile:

**Comment by eddiemonge** [comment]
You need to implement a custom action to reload the directives. You can ask for help about doing that on stackoverflow.
