### ISSUE TITLE
Child not inherits from direct Parent State - 3 state levels

### ISSUE THREAD

**Issue by demege** [angular-ui/ui-router#2707]
Hi Guys,

I modeling an app with 3 levels:
```js
$stateProvider
  .state('main', {}) //abstract: define the general rules across the app in a controller and validate if the user is logged in, and defines the main template.
  .state('main.contacts', {}) //abstract: this defines the rules for the contacts module in a controller
  .state('main.contacts.list', {}); //This controller, should inherits from the 2 parents.
```

I've checked this plnkr, from the docs:
https://github.com/angular-ui/ui-router/wiki/Nested-States-and-Nested-Views

It works with 2 levels.
http://plnkr.co/edit/gmtcE2?p=preview

But if I add a 3rd level, it didn't work:
http://plnkr.co/edit/cX3ies?p=preview

There is a bug, it is not possible, or Im doing some wrong ?

**Comment by erikbaan** [comment]
I am experiencing the same problem since updating from 0.2.15 to 0.2.18

**Comment by christopherthielen** [comment]
Thanks for the plunker.  However, it has a couple problems.

1) your top level state `main` doesn't have a `ui-view` viewport, so there is no place to put the nested state's view.

2) When you added `main` state, it changed the URLs for the children states.  However, you did not update the links.  Change `"#/contacts/list"` to `"#/main/contacts/list" in `index.html`, and `"#/contacts/{{person.id}}"` to `"#/main/contacts/{{person.id}}"` in contacts.list.html.

Working plunker: http://plnkr.co/edit/W5kGwM?p=preview

---

To the rest of you who +1-ed, please create a new issue that shows a reproducible bug.  This plunker doesn't show a ui-router bug.
