### ISSUE TITLE
Support @ bindings when using 1.5 components

### ISSUE THREAD

**Issue by drummerboof** [angular-ui/ui-router#2708]
Currently, UI Router supports < and = parameters when routing using the component syntax. When the component contains a @ parameter binding, an error is thrown with the message `TypeError: Cannot read property '1' of null`

Plunkr showing the issue is here: http://embed.plnkr.co/mtNl3MgXrfTkv8NnrtqQ/ The error occurs can be seen in the console.

It seems to be an issue with the handling of the scope bindings in the ng1 viewsBuilder at https://github.com/angular-ui/ui-router/blob/1.0.0-alpha.4/src/ng1/viewsBuilder.ts#L74

**Comment by pdanpdan** [comment]
On the same topic, optional bindings do not work (<?name, =?name). It tries to create a ?name="::$resolve.?name"

**Comment by christopherthielen** [comment]
also, bindings that start with `UpperCase` letters are also broken and translate to `-upper-case="::$resolve.UpperCase"`

https://plnkr.co/edit/ttcFRmVp9StCTWkHeZbH?p=preview

**Comment by christopherthielen** [comment]
alpha.5 supports `@` bindings
