### ISSUE TITLE
Make state only accessible if the app itself sends a user there

### ISSUE THREAD

**Issue by jml6m** [angular-ui/ui-router#2710]
Let's say I have state:

```javascript
$stateProvider.state('test', {
	url: '/test',
	templateUrl: 'test.html',
	controller: 'TestCtrl'
})
```

I don't want the user to be able to go directly to http://hostname/#/test

I only want that state accessible if somewhere in the app it sends the user there with `$state.go('test');`

Is there a way to make this differentiation in a generalized way? Perhaps using ui-router library or AngularJS library. Otherwise, we can just create a series of custom logic (boolean flag) to determine if `$state.go()` was called or not.

**Comment by christopherthielen** [comment]
I've considered adding an "event source" for transitions to distinguish between them.  Basically they would be:

- ui-sref
- url parsed
- null (everything else)

Currently there is no way to tell the difference.

Programmatically you can tell if the user clicked a bookmark (or pressed refresh) by checking if the "from state" is the root state named `""`.

```js
$rootScope.$on("$stateChangeStart", function( evt,toState, toParams, fromState) {
  if (fromState.name === "" && toState.name === "test") {
    evt.preventDefault();
    $state.go("home");
  }
});
```

**Comment by jml6m** [comment]
@christopherthielen Big fan of the "event source" idea

**Comment by christopherthielen** [comment]
@jml6m 
https://github.com/angular-ui/ui-router/blob/70c7f07edce7aba412f75165ed9a29ae923ca079/src/transition/interface.ts#L85
