### ISSUE TITLE
Is there a way to reload specific instead of reloading all state?

### ISSUE THREAD

**Issue by lili21** [angular-ui/ui-router#2712]
Another reload parent state issue.

I just want the parent state reload, it's `resolve`, `controller` or something like that. I do not need a full reload .

Any ideals to achieve this ?

**Comment by christopherthielen** [comment]
Let's say you are on `foo.bar.baz` state and you want to reload `foo.bar` and `foo.bar.baz`.

`$state.go(".", null, { reload: 'foo.bar` });`
