### ISSUE TITLE
ui-router not working with multiple page application 

### ISSUE THREAD

**Issue by devLaaziz** [angular-ui/ui-router#2713]

**Comment by devLaaziz** [comment]
in main angular.module i use this configuration 

 $stateProvider
         .state('home', {
            url: '/',
            templateUrl: 'urlTemplate',
             abstract: true,
            controller: '',
            ncyBreadcrumb: {
                label: 'Home page'
            },
            data: {
                pageTitle: 'Home'
            }
        })
         .state('page1', {
            url: "/page1",
            ncyBreadcrumb: {
                label: 'page1',
                parent: 'home'
            },
            controller: function ($window) {
                $window.location.href = '/page1';
            },
            data: {
                pageTitle: 'page1'
            }
        });
and in the page 1 config 

    .state('call_center.reports', {
            url: "/test",
            controller: "testController",
            templateUrl: "url for view Template ",
            ncyBreadcrumb: {
                label: 'test',
                parent: 'page1'
            },
            data: {
                pageTitle: 'test'
            }
        })

but the template url not display

**Comment by christopherthielen** [comment]
Hi there! It looks like you're asking for ui-router support.  

This issue tracker is reserved for issues and feature requests only.  Please direct support/help requests to StackOverflow, a Q&A site.

http://bit.ly/UIR-SOF
