### ISSUE TITLE
$state.go with {location: 'replace', notify: false} replaces the last history entry on chrome but adds a  new one on Safari.

### ISSUE THREAD

**Issue by tim93422** [angular-ui/ui-router#2714]
$state.go with {location: 'replace', notify: false} replaces the last history entry on chrome but adds a  new one on Safari.

I have a plunker that shows this behavior:
http://plnkr.co/edit/BNv58mdgiS2wT3u9Hcsz

To reproduce:
Download.
Run.
Type several different strings into the input, press enter.

In Chrome you will see one history entry with the final string from the input box.
On Safari you will see as many history entries as the number of different strings typed in followed by pressing search. The attached screen-shot shows a list of searches where only one history entry was expected.

Sorry it is a clumsy UI to demonstrate the problem.
![screen shot 2016-04-26 at 4 28 20 pm](https://cloud.githubusercontent.com/assets/5104507/14837311/06428e28-0bcc-11e6-87cc-d2fcae431f9f.png)

My apologies in advance if I used the library wrong -- I read the docs but I may have missed something.

**Comment by VincentTang86** [comment]
I have this issue too.

**Comment by eddiemonge** [comment]
Marking it as a bug but probably wont be fixed since most effort is going into 1.x

**Comment by tim93422** [comment]
Okay. Thanks for update.

**Comment by AScripnic** [comment]
On Safari 9.1 having the same issue:
And when history.pushState is called 100+ times, Safari throws error:
```
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
```
and
```
Error: SecurityError: DOM Exception 18
pushState@[native code]
```
related issue on Apple Developer Forums:
https://forums.developer.apple.com/thread/36650
