### ISSUE TITLE
Link to source of sample application is broken

### ISSUE THREAD

**Issue by rogercoder** [angular-ui/ui-router#2716]
From the 0.2 main page (https://github.com/angular-ui/ui-router/tree/legacy) click on Sample > About > "Source for this sample" and you get a 404 error trying to get to "https://github.com/angular-ui/ui-router/tree/legacy".
The correct link is "https://github.com/angular-ui/ui-router/tree/gh-pages/sample"

**Comment by eddiemonge** [comment]
PR welcome
