### ISSUE TITLE
ng2 beta.16 onwards -TypeError: core_2.Injector.resolve is not a function 

### ISSUE THREAD

**Issue by gnanda17** [angular-ui/ui-router#2722]
Occurs from angular2@2.0.0-beta.16 onwards. 
Angular2@2.0.0-beta.15 loads successfully with no errors

Trace:
Transition #0 Digest #0: Started  -> "Transition#0( ''{} -> 'app'{} )"
trace.ts:272
$view.ViewConfig: -> Registering ui-view id#0, contextual name '$default@', fqn: '$default'
angular2.dev.js:384 
Transition #0 Digest #0: <- Success  "Transition#0( ''{} -> 'app'{} )", final state: app
trace.ts:266
$view.ViewConfig: -> Registering ViewConfig targeting ui-view: '$default@', context: 'app'
transitionHook.ts:98 
Swallowed exception during synchronous hook handler: TypeError: core_2.Injector.resolve is not a function

**Comment by christopherthielen** [comment]
ui-router-ng2 needs to account for angular 2 beta.16 breaking changes
