### ISSUE TITLE
Hash and view is not sync when pressing on back button

### ISSUE THREAD

**Issue by samithaf** [angular-ui/ui-router#2723]
Hi guys,
I have came across this issue while trying to create a auth interceptor. Here is the use case.
Flow:
1) User navigate to a screen which user does not have rights to view (Assume state1).
2) $transitions.onBefore hook detect the navigation and send the user back to the error page
3) User click the browser back button.

Expected behaviour:
User should not be able to navigate to the state 1
URL should not update to state 1 url.

What really happens:
User cannot navigate to state 1
URL has been update to state 1 url.

Here is a small App which replicate the issue. Please see the console log which output the current Hash
[Example](http://plnkr.co/edit/466fBhm0fSQj46niGwfu?p=preview )

**Comment by christopherthielen** [comment]
If we enable transition trace `.run($trace => $trace.enable(1))` we see this
```
Transition #0 Digest #2: Started  -> "Transition#0( ''{} -> 'app.state1'{} )"
VM1499 script.js:2 App Hash is  #/app/state1
VM1497 angular-ui-router.js:1665 Transition #1 Digest #4: Started  -> "Transition#1( ''{} -> 'error'{} )"
VM1497 angular-ui-router.js:1737 Transition #1 Digest #4: <- Success  "Transition#1( ''{} -> 'error'{} )", final state: error
VM1497 angular-ui-router.js:1730 Transition #0 Digest #4: <- Rejected "Transition#0( ''{} -> 'app.state1'{} )", reason: TransitionRejection(type: 2, message: The transition has been superseded by a different transition (see detail)., detail: Transition#1( ''{} -> 'error'{} ))
VM1499 script.js:2 App Hash is  #/error
VM1499 script.js:27 user pressing the back button
VM1497 angular-ui-router.js:1665 Transition #2 Digest #8: Started  -> "Transition#2( 'error'{} -> 'app.state1'{} )"
VM1499 script.js:2 App Hash is  #/app/state1
VM1497 angular-ui-router.js:1672 Transition #3 Digest #9: Ignored  <> "Transition#3( 'error'{} -> 'error'{} )"
VM1497 angular-ui-router.js:1730 Transition #2 Digest #9: <- Rejected "Transition#2( 'error'{} -> 'app.state1'{} )", reason: TransitionRejection(type: 2, message: The transition has been superseded by a different transition (see detail)., detail: Transition#3( 'error'{} -> 'error'{} ))
```

So here's what I think is happening:

1) Navigate to state 1 (Transition #1)
2) onBefore() Navigates to error (Transition #2)
3) Transition #1 cancelled because it was superseded
4) Transition #2 completed to `error`
5) Back button pressed, url changes to `/state/1`
6) onBefore() Navigate to error (Transition #3)
7) Transition #3 ignored because we're already on `error`
8) The URL reseting logic doesn't do anything when the transition is "ignored"

**Comment by xr** [comment]
hi, beta-1.0 still have this problems when change state inside $transition onStart hook function, any solutions?
