### ISSUE TITLE
Child state does not load when parent is an abstract state

### ISSUE THREAD

**Issue by divmgl** [angular-ui/ui-router#2724]
This is ridiculously frustrating. `angular@1.5.5`, `ui-router@0.2.18`

```
$stateProvider.state("base", {
    abstract: true
});

$stateProvider.state("workspace", {
    parent: "base",
    url: '/',
    controller: "WorkspaceController",
    templateUrl: "workspace.html"
});

$rootScope.$on('$stateChangeSuccess', function(event, state) {
    console.log(event, state); 
    // => Object {name: '$stateChangeSuccess'}
    // => Object {parent: "base", url: "/", controller: "WorkspaceController", templateUrl: "workspace.html", name: "workspace"}
});
```

The child controller refuses to load. Removing `parent: "base"` causes the controller to load as expected. Any ideas why? Is this a bug?

[Here's a Plunkr that recreates the problem.](https://embed.plnkr.co/Bu8eSB1XfpYDeqHOXQpN)

**Comment by divmgl** [comment]
To anyone who is viewing this in the future: you need `template: '<ui-view />'` on the parent state. The parent will load all children through its template.

**Comment by Shakthi88** [comment]
Hi,
Thanks for your comment... after searching for a day, your comments helps to solve my issue

**Comment by RisingStar1** [comment]
@divmgl  tnx for your comment!

**Comment by inanmadak** [comment]
"To anyone who is viewing this in the future: you need template: '<ui-view />' on the parent state. The parent will load all children through its template." - @divmgl 

This solution not working. I think nothing is ever working, I tried a lot of things, but no, child states not appearing if they have abstract parents. Does anyone know a real solution?

**Comment by divmgl** [comment]
@inanmadak we need more information than 

> Does anyone know a real solution?

I recommend locking this.

**Comment by inanmadak** [comment]
@divmgl  I have a FountainJS setup with AngularJs 1.6.6, Npm, Webpack and gulp. With ES6 babel.

I have 3 ui-views: 
<div ui-view=“header”></div>
<div ui-view=“body”></div>
<div ui-view=“footer”></div>

Every time I add a new state I use this:
```
state(‘workspace.new’, {
        url: '/workspace/new',
        views: {
          header: {
            templateUrl: header
          },
          body: {
            templateUrl: 'app/views/workspace/new.html',
            controller: 'WorkspaceController as vm'
          },
          footer:{
            templateUrl: footer
          }
        }
      });
```
So this is a normal state. However, what I would like to do, for example add an abstract state for this, and use a controller for some common work or apply url prepending.

So I have added it like this: (and I add this before creating child state)

```
 .state('workspace', {
        url: '/workspace/',
        abstract: true,
        template: '<ui-view />'  // this doesnt work as your solution
      });
```


Before doing your solution, I have tried it like this(and I know that method below working somewhere else, but it is not ES6):
I have an index.html
```
<body ng-app="myapp">
    <div ui-view=""></div> // this or below code both does not working
 <!-- <div ui-view="''"></div> --> //explicit single quote here
  </body>
```
And I have a template file (layout.html) like this:

```
 <header ui-view="header"></header>
  
  <div ui-view="body"></div>
  
  <footer ui-view="footer"></footer>
```
And my states are:
```
 .state('workspace', {
        url: '/workspace/',
        abstract: true,
        '': {
           templateUrl: 'app/views/layout.html'
         }
      })
 .state(‘workspace.new’, {
        url: '/workspace/new',
        views: {
          header: {
            templateUrl: header
          },
          body: {
            templateUrl: 'app/views/workspace/new.html',
            controller: 'WorkspaceController as vm'
          },
          footer:{
            templateUrl: footer
          }
        }
      });
```
Okay: Just tried the second solution, and it is working now, but, if I use it, for a resource like /users for example, I need to arrange my other state like above, and that is not a good way to do. Is not there a way to use 

```
 .state(‘workspace.new’, {
        url: '/workspace/new',
        views: {
          header: {
            templateUrl: header
          },
          body: {
            templateUrl: 'app/views/workspace/new.html',
            controller: 'WorkspaceController as vm'
          },
          footer:{
            templateUrl: footer
          }
        }
      });
```
code either way, I mean with or without abstract parent as we need it?

**Comment by divmgl** [comment]
Why not just do `<ui-view></ui-view>`?

**Comment by inanmadak** [comment]
I have fixed the problem in a similar way I think, thanks for the answer
