### ISSUE TITLE
ui-sref-opts="{absolute: true}" provides inconsistent URLs?

### ISSUE THREAD

**Issue by mjschultz** [angular-ui/ui-router#2729]
We have a site that is largely angular with ui-router but still have some legacy pages. The legacy pages have the angular app so we can use ui-router there but the links it provides seem inconsistent.

For example, we want all the angular pages mounted at `/`, so a contacts page would be at `/#/contacts`. But sometimes we'll link outside to a legacy page, e.g., `/people/me/`. On this page we'd have a link back to the contacts page which should result in the user going to `/#/contact` but when I do `<a ui-sref="contacts()" ui-sref-opt="{absolute: true}">` the resulting html is `<a ui-sref="contacts()"  ui-sref-opt="{absolute: true}" href="/#/contacts">` which is correct.

Hovering over the link and the browser shows the right location, right clicking or any browser navigation links to the right location, but clicking on the link on the same page lands me at `/people/me/#/contacts`. While this works, it provides an inconsistent URL for the user.

Am I missing something? I suspect there is a click handler that is overriding the default behavior but I'm not sure how to avoid this behavior.

(Also is there an easy way to set the global behavior to `{absolute: true}`, I don't see it in the docs.)

Thanks!

**Comment by christopherthielen** [comment]
What do you expect to happen?  Do you expect the browser to fully reload the page from the server and bootstrap ng again?

As you know, ui-sref *generates* a href (for link hovering, etc).  However, the act of clicking a ui-sref doesn't simply update the URL and trigger navigation (like a regular anchor tag).  When the ui-sref is clicked it calls evt.preventDefault() and then `$state.go()...`.  This is used to apply things like transition options, and non-url-parameters.


I can't remember exactly, but I think we honor `target`.  Try adding it to your link like `<a ui-sref="foo", ui-sref-opts="..." target="_self">foo</a>` and please respond back if it works or not.  If it does not work, can you make a plunker that

**Comment by mjschultz** [comment]
Ah, yes, you're right anything with a [`target`](https://github.com/angular-ui/ui-router/blob/3a1160d30cad275af9eb5c9e5142714b974123e6/src/ng1/stateDirectives.ts#L47) attribute ends up skipping the click handler. I looked at that but didn't read to the end of the line.

But yes, the behavior I am wanting here is that the page ends up getting fully reloaded and re-bootstrapped. I'm not a fan of that, but it'll end up providing users with more consistent URLs.

Thanks for pointing out the `target` trick!
