### ISSUE TITLE
History should not be changed until after route resolvers have completed

### ISSUE THREAD

**Issue by johnpapa** [angular-ui/ui-router#273]
#### My Request

Browser history should not be updated until it is clear that the route/state transition will NOT be cancelled.
#### My scenario

My states all have a resolve function. I use this to return a promise to let the state know if it should allow the state transition or not. (preventing users from leaving pages if attention to changed data is needed, for example). This works ... however the history does not.

The current route is getting replaced BEFORE the route resolves. i tried replacing the route with the current one (when we want to stay on screen), and that works but it does not help the fact that the previous route has ben removed. 
#### The Story

1) go to #/sessions 
2) choose a session ( #/sessiondetail/1 )
3) make a change to the data
4) press back button
5) answer NO to a modal that asks if they want to leave and cancel (so it stays on the sessiondetail view)
#### Actual outcome:

History has 
- sessiondetail
#### Desired outcome

history should have:
- sessiondetail
- sessions
#### Why?

The ui-router is popping the previous page off the history BEFORE all of this logic happens in the resolvers. It should not do that. 
#### My attack

But since it is, I am trying to patch it and get the history added back without actually navigating to it. However, this is problematic. I've tried $window.location.replace, but that replaces the "sessions" history with "sessiondetail", because the "sessions" history is already gone.

**Comment by atermenji** [comment]
having the same issue @itkach has described, any idea on how this can be fixed?

**Comment by davideanderson** [comment]
I am also having the same issue.  preventDefault() on $stateChangeStart cancels the state change, but the url has already been changed by the time $stateChangeStart fires, and it isn't changed back when preventDefault() is called.

**Comment by srgroves** [comment]
I'm also having the same issue @itkach described.

**Comment by sethflowers** [comment]
+1

**Comment by amatecha** [comment]
This is brutal, still open since 2013?  :(

**Comment by cmnajs** [comment]
I am also having the same issue reported by @itkach. I am using version 0.2.17.

**Comment by lobo-tuerto** [comment]
Any advances on this issue?

**Comment by lobo-tuerto** [comment]
A workaround I found was to reinsert the state I was coming from when the transition is stopped. Like this:

```javascript
$rootScope.$on( '$stateChangeStart', function( event, toState, toParams, fromState, fromParams ) {
  var answer = window.confirm( 'You sure?' );
  if( !answer ) {
    event.preventDefault();
    $state.go( fromState, fromParams );
  }
}
```
