### ISSUE TITLE
Should not urls of parent and child state be combined as path components?

### ISSUE THREAD

**Issue by voroninp** [angular-ui/ui-router#2736]
I have noted that urls of parent and child state are simply concatenated (ui-router 0.2.18).

For these states:

```javascript
.state('banksList',
{
    url: '/',
    ...
})
.state('banksList.bank',
{
    url: '/bank/{bankId}',
    ...             
})
```

I expect the url of  a child state `banksList.bank` to be the result of path combination, that is `<base-url>/bank/{bankId}`, but what I indeed get is a simple string concatenation: `<base-url>//bank/{bankId}`,  

This happens for any parent url having trailing slash. 

Is it by design?

**Comment by eddiemonge** [comment]
The url of the child is added to the parent. It doesn't do any rewriting of it.
