### ISSUE TITLE
Create shorthand syntax for optional url parameters

### ISSUE THREAD

**Issue by christopherthielen** [angular-ui/ui-router#2737]
Given a default parameter value of `null`

you can currently do this:

``` js
$stateProvider.state('search', {
      url: '/search/{id}',
      params: {
        id: {
          value: null
        }
      }
    });
```

or this:

``` js
$stateProvider.state('search', {
      url: '/search/{id}',
      params: {
        id: null
      }
    });
```

But how about something like this?

``` js
$stateProvider.state('search', {
      url: '/search/{id?}',
    });
```

or this

``` js
$stateProvider.state('search', {
      url: '/search/{id?:date}',
    });
```

**Comment by christopherthielen** [comment]
@nateabele @eddiemonge @wesleycho  what do you think?

**Comment by eddiemonge** [comment]
`url: '/search/{id?}'` I think is fine.

`url: '/search/{id?:date}'` Does this mean an optional param named id of type date? This syntax might be a bit more confusing but not terribly so

**Comment by nateabele** [comment]
Yeah, that makes sense. I think if we're doing `/{id?}`, we also have to do `{id?:date}` (unless that's what you already meant).

**Comment by micopiira** [comment]
Hey, what about only defining the parameters in the params property? I'm currently dealing with a project that involves dozens of url parameters, and having to define them in the string is ugly in my opinion. Would be nice to only have them in the params property, but I have no idea if that is possible/too hard to implement.

```
$stateProvider.state('search', {
      url: '/search',
      params: {
        id: null
      }
    });
```

**Comment by eddiemonge** [comment]
@micopiira there isn't anything that prevents you from doing that, but there also isn't anything that enforces that either.
