### ISSUE TITLE
Specifying allowed state transitions.

### ISSUE THREAD

**Issue by voroninp** [angular-ui/ui-router#2738]
State configuration code is indeed a good part of documentation because developer see which states exist in application. Unfortunately, for now we cannot constrain transitions, that is there's no way to declare which state transitions are allowed, and which are prohibited.<br/>

But if we were able to do this:

``` javascript
.state('a',
{
    allowedTransitions : ['b','c']
})
.state('b',
{
    allowedTransitions: ['c']
})
.state('c',
{
   allowedTransitions: ['b','c']
});
```

we could quickly draw a complete state diagram what is very helpful.<br/>
Sure, nobody stops us from adding this property now, but ui-router can enforce the rule throwing exception in case of prohibited transition.

**Comment by christopherthielen** [comment]
I don't think we need this as core ui-router code, but you can easily implement this using transition hooks in 1.0.  

```js
  $transitions.onStart({}, ($q, $transition$) => {
    let fromState = $transition$.from().name;
    let toState = $transition$.to().name;
    
    let allowed = $transition$.from().allowedTransitions;
    if (allowed && allowed.indexOf(toState) === -1) {
      return $q.reject(`Not allowed to transition from ${fromState} to ${toState}`);
    }
  })
```

http://plnkr.co/edit/ltcDZW18guGUGSIbfl7x?p=info
