### ISSUE TITLE
I want to load language before any UI is displayed with ui-router resolve

### ISSUE THREAD

**Issue by essivision** [angular-ui/ui-router#2747]
Hi

I use `angular-translate`. I want to load language before any UI is displayed. Everythings is ok just when I go to nested state (like `admin.user`), show me a error. This is my code:
 [https://plnkr.co/edit/YnQBUQfgQBoR39Q35p0d?p=preview](https://plnkr.co/edit/YnQBUQfgQBoR39Q35p0d?p=preview)

when run this code error me
>http://errors.angularjs.org/1.4.8/ng/areqp0=AdminCtrl&p1=not%20aNaNunction%2C%20got%20undefined

Thanks

**Comment by christopherthielen** [comment]
This plunker is a mess... 

I edited as best as I could guess, and it seems to be working: https://plnkr.co/edit/YeyzCqnPJ6C2lF48RWD0?p=preview
