### ISSUE TITLE
navbar-absolute-top|bottom not correctly padded

### ISSUE THREAD

**Issue by minawalphonce** [angular-ui/ui-router#2749]
I have 2 views each one of them have navbar-aboslute-top class,
when I navigate the from the first one to the second the class has-navbar-top is removed from the rootElement, because the scope.$distroy of the first view is called after the call to the link function of navbar-aboslute-top is called.

**Comment by christopherthielen** [comment]
This isn't enough information to act on.  However, this:

> scope.$distroy of the first view is called after the call to the link function of navbar-aboslute-top is called.
 
... sounds a bit like #2562 which was fixed in 0.3.0.   Can you try upgrading to 0.3.0?
