### ISSUE TITLE
Caching state/view 

### ISSUE THREAD

**Issue by ghost** [angular-ui/ui-router#2751]
Typically for most web application, user is served with a listing page (whether it is a infinite scroll, a paginated list, or something in between with "show more" button), then a item detail page. It is really unfriendly and annoying to re-scroll/ re-browse the list. 

Ionic can do it, since very very long time : http://ionicframework.com/docs/api/directive/ionNavView/

I know people have raised this issue before 
https://github.com/angular-ui/ui-router/issues/1800 
https://github.com/angular-ui/ui-router/issues/63

and I also know that ui team is very busy. So I played around with ui-router source code for a while but have no idea what to do.... I also browse ionic source code which is really complex. I think I need hints and suggestions to implement the features by myself 

For the moment, we desperately need to cache the listing page

**Comment by christopherthielen** [comment]
Have you looked into ui-router-extras "sticky states"?  
http://christopherthielen.github.io/ui-router-extras/#/sticky

If you have one or two views that you don't want to rebuild, you can use sticky states to keep them around in the DOM.  You show/hide as they're inactivated/reactivated.

---

As for your use case... 

>  It is really unfriendly and annoying to re-scroll/ re-browse the list.

I think that could be solved by saving and restoring the scroll position as states are entered/exited.  I don't know if  this is something ui-router should have in core, however.

**Comment by phuyem** [comment]
@christopherthielen : thank you for making it a feature. 

BTW, I am trying sticky view one more time, and  I got it. (I tried router-extra a year ago but failed to understand it). It actually make my code much cleaner, no more storing the listing in session. 

Thanks, you guys are so awesome

**Comment by dantaex** [comment]
+1
