### ISSUE TITLE
Maintaining state history?

### ISSUE THREAD

**Issue by atdiff** [angular-ui/ui-router#2754]
Is it possible to maintain the state history as a user navigates between states using a single page apps own nav buttons?  Or is there a recommended way to handle this?

In my single page app, I need to keep a state history to make it easier to navigate back and forth between states. I have my own forward and back buttons that I'm using on my pages and not going through the browser's buttons.
This is the following code I have which uses the service I've created to store the states in an array.

```
$rootScope.$on('$stateChangeStart', function (event, toState, toParams) {
    StateMgmtService.add(toState, toParams);
});
```

In the service, I have something to the effect of the following:

```
var history = [];

    return {
        previous: function () {
            if (history && history.length > 0) {
                return history[history.length - 1];
            }
        },
        add: function (state, params) {
            var historyItem = {
                state: state,
                parameters: params
            };

            history.push(historyItem);
        }
    };
```

The problem is that any time I go back to a prior state, the stateChangeStart is fired which basically pollutes my history. Consider the following example:
- starting from state a to b - b gets added to the history
- b to c - c gets added
- c back to b - b gets added again

This results in an endless looping of going from b to c to b to c... So I basically need to not allow prior items to be added to the history or to somehow know that it's going back in the history, but stateChangeStart doesn't allow any differentiation as such.  And unfortunately just comparing state isn't possible since they can be on the same state but with different parameters.

Help!

**Comment by eddiemonge** [comment]
Why can't you use the browsers forward/back/history management?

**Comment by whiterockerart** [comment]
Happens to mee to.
If b has params, it looses them when going back from c and also - c disappears from the history.

From the beginning the history looks lake this when I'm going from state to state:
a-b (with params)-c

When going back (using browser buttons) the history appears like this:
a-b (with params)-b (withour params)
