### ISSUE TITLE
Refresh named view by reloading resolve and controller.

### ISSUE THREAD

**Issue by WDShannon** [angular-ui/ui-router#2755]
Our application has a dashboard that is made up of 1 single state.  Our 1 state has the following structure: 

```
State: Dashboard
    Views:
        View 1
        View 2
            View 2.1
            View 2.2
            View 2.3
            View 2.4
            View 2.5
        View 3
        View 4
        View 5
        View 6
```

Every view has its own controller and own resolve.  Every view needs to be loaded when the page (state) has been transitioned to.  Changes in one view do not affect the content in another view with the exception that sometimes one view will need to be refreshed because of the action of another.

It stands to reason that there should be a way to reference and refresh the controller/resolve of a view without affecting other views.  If you are giving us the ability to give a view a controller and resolve data into a view, why not let those views reload independently? 

![dashboard routing example](https://cloud.githubusercontent.com/assets/88500/15365098/f7ab36c6-1cec-11e6-8fe2-b2e73748379d.png)

**Comment by christopherthielen** [comment]
Resolves actually belong to the state, not the view.  The resolve is tightly bound to the state lifecycle; they are fetched when the state is entered, and then that data is fed to the view controllers as they are instantiated.

You might have some luck with the "dynamic parameters" that are part of ui-router 1.0.

```
.state('dashboard', {
  params: {
    view1Id: { dynamic: true, value: null },
    view2id: { dynamic: true, value: null },
    ...
  },
  views: {
    view1: {
      controller: function($scope, $transition$, View1Service) {
        function updateView1Data(id) {
          View1Service.get($transition$.params().view1Id).then(function(data) {
            $scope.data = data;
          }
        }
        this.uiOnParamsChanged = function(changes) {
          if (changes.hasOwnProperty('view1Id') {
            updateView1Data(changes.view1Id);
          }
        }
        updateView1Data($transition$.params().view1Id);
      }
```

**Comment by christopherthielen** [comment]
alternatively, you could look into using something like ui-router-extras sticky states, and have a state+named view for each dashboard item. 

I realize neither of these are totally ideal, when dealing with resolve.  In your case for dashboard items, I might avoid resolve altogether, and manage the data right within each view component.

**Comment by WDShannon** [comment]
Thank you for this information.

Are the resolves that can be added to a named view just syntactical sugar then?  Based on the following state definition, I would expect to be able to reload a view on the fly:

```
.state('users', {
            url: '/users',
            views: {
                '': {
                    templateUrl: 'tmp1.html',
                    controller: 'userManagementCtrl',
                    controllerAs: 'vm',
                    caseInsensitiveMatch: true,
                    resolve: {
                        resolveOne: someFunction,
                        resolveTwo: anotherFunction
                    }
                },
                'usersHeader@users': {
                    templateUrl: 'header.html',
                    controller: 'userManagement_HeaderCtrl',
                    controllerAs: 'headerCtrl',
                    caseInsensitiveMatch: true
                }
            }
        })
```

Looking over sticky states, I have a question.  How would I configure the sticky states so that when I load the dashboard with a url of mysite.com/dashboard, every substate would load with it?  Is this possible?

**Comment by WDShannon** [comment]
I took your advice and am using sticky states, which is working well.  So if I want to reload states 2.3 and 2.4 and their resolves I give this command: 

```
$state.go('dashboard.2.3', null, { reload: 'dashboard.2.3' }).then(function () {
    $state.go('dashboard.2.4', null, { reload: 'dashboard.2.3' })
})
```

is that the correct way to handle a reload?

and to get all the states loaded on the screen for the initial load, the code gets very nested and looks like this:

```
$state.go('dashboard.1').then(function () {
    $state.go('dashboard.2').then(function () {
        $state.go('dashboard.2.1').then(function () {
            $state.go('dashboard.2.2').then(function () {
                $state.go('dashboard.2.3').then(function () {
                    $state.go('dashboard.2.4').then(function () {
                        $state.go('dashboard.3').then(function () {
                            $state.go('dashboard.4').then(function () {
                            });
                        });
                    });
                });
            });
        });
    });
});
```

Is that the correct and most efficient way to handle the load?  If so, can I somehow hide all the flickering and only show the screen when all states have been loaded?

Thanks for the help, I'll mark this as closed after your reply.

**Comment by eddiemonge** [comment]
I'm thinking you might want to switch from states/views to components. This probably should be one state and one view and then that view is made up of various components that handle fetching, displaying and reloading their own data. Would be far less complicated for you.

**Comment by christopherthielen** [comment]
@WDShannon  I think this may help you: https://github.com/christopherthielen/ui-router-extras/issues/297#issuecomment-196525501

**Comment by WDShannon** [comment]
@christopherthielen Thanks for that comment.  We actually implemented it a bit differently.  I created a service with a function that accepts a statename as a parameter, and this function will chain-load every substate. 

```
function loadAllChildren(stateName) {
        //Loaderbar start logic can go here.
        var stateChildren = _.filter(states, function (child) { return _.startsWith(child.name, stateName + '.') });

        return loadAllStates(stateChildren).then(function () {
            //Loaderbar complete logic can go here
        });
}

function loadAllStates(states) {
        return _.drop(states).reduce(function (promise, item) {
             return promise.then(function (result) {
                return $state.go(item);
            })
        }, $state.go(states[0]));
    }
}
```

In the controller for the state that is the parent of every other state on the page, we call to that service: 

`stickyLoader.LoadAllChildren('MainState').then(function (data) { MainState.loaded = true; });`

Thanks for all the help!
