### ISSUE TITLE
Loading route into dynamically named view.

### ISSUE THREAD

**Issue by notbogdan** [angular-ui/ui-router#2760]
This is more of a question and I apologise if it has no place here. [Here it is on SO.](http://stackoverflow.com/questions/37320446/loading-route-into-dynamically-named-view)

I was wondering if it's possible to do the following: 

I'm trying to build accordion style navigation for an app with Meteor and Angular JS. I have a list of articles like so: 

State:

      $stateProvider
        .state('articles', {
          url: '/articles',
          template: '<articles></articles>'
      });

`<articles>`:

      <div class="article-entry" ng-repeat="article in articles.list" slug="{{article.slug}}">
        <div class="inner">
          //...
          <div ui-view="{{article.slug}}"></div>
          <a ui-sref="article.content({slug: article.slug})">View article</a>
        </div>
      </div>

And then the article content:

      $stateProvider
        .state('articles.content', {
          url: '/:slug',
          template: '<content></content>'
      });

`<content>` is just, you guessed it, the article content. 

Is it possible to get `<content>` to show up in the `ui-view` associated with it when someone visits the `articles.content` state? How would I do this?

**Comment by christopherthielen** [comment]
oh, that's an interesting approach...

There's no built in way to change the targetted ui-view for a view.

Would this work?
```
  <div class="article-entry" ng-repeat="article in articles.list" slug="{{article.slug}}">
    <div class="inner">
      //...
      <div ng-if="article.slug === $stateParams.slug">
        <div ui-view="{{article.slug}}"></div>
      </div>
      <a ui-sref="article.content({slug: article.slug})">View article</a>
    </div>
  </div>
```

**Comment by eddiemonge** [comment]
@notbogdan ^^ does that fix your issue? If not, let us know
