### ISSUE TITLE
Hyperlink to the current page doesn't work (i.e. link which reloads the page)

### ISSUE THREAD

**Issue by Lexa1983** [angular-ui/ui-router#2762]
Let's say we're on page "/page1"
click on element `<a href="/page1">go</a>` doesn't reload page.

`isDefaultPrevented()=true` on click event

Doesn't work on version 0.2.18 when there is at least one ui-view directive
Doesn't work on version 0.3 even no usage of ui-router infrastructure on page.

Tell me if you need more info.

**Comment by eddiemonge** [comment]
Have you tried `<a ui-sref="page1" ui-sref-opts="{reload:true}">` ?

Closing as this is an implemention issue, not a core bug. If you need further help, check stackoverflow.
