### ISSUE TITLE
router unit tests fail after updating to 1.0.0-alpha.4 +

### ISSUE THREAD

**Issue by samithaf** [angular-ui/ui-router#2766]
Hi guys,

I have some unit tests which tests ui router configs and resolvers. All the tests are failing soon after upgrade to 1.0.0-alpha.4 and i tested with 1.0.0-alpha.5 and it's the same. Please see the following simple tests in fiddle. 

Using router 1.0.0-alpha.5 [tests failing]
http://jsfiddle.net/samitha/mygcsazm/1/

Using router 0.3.0 [test passing]
http://jsfiddle.net/samitha/ud1bz8q0/2/

@christopherthielen any thoughts on this?

**Comment by christopherthielen** [comment]
in 1.0, path parameters are non-optional by default.  If you check your console, you can see the message  `Error: Param values not valid for state 'myState'(…)`

Either supply a parameter `$state.go('myState', { id: 1 })` or define a default parameter value on the state itself
```js
      $stateProvider.state('myState', {
        url: '/state/:id',
        params: { id: null },
        templateUrl: 'template.html',
        controller: 'MyCtrl',
        resolve: {
          data: ['myService', function(service) {
            return service.findAll();
          }]
        }
      });
```

**Comment by samithaf** [comment]
@christopherthielen cheers thanks. I am going to close this issue.
