### ISSUE TITLE
ui-sref not working with data-toggle

### ISSUE THREAD

**Issue by wangshan** [angular-ui/ui-router#2767]
I have posted a question on stackoverflow [here](http://stackoverflow.com/questions/37411857/ui-sref-not-working-in-bootstrap-dropdown).

Basically, with code like this:

```
<ul class="dropdown-menu" data-toggle="collapse" aria-labelledby="userDropdown">
   <li><a ui-sref="app.profile">Your Profile</a></li>  
   <li><a ui-sref="app.settings">Settings</a></li>     
</ul> 
```

clicking on **Your Profile** won't work, by removing `data-toggle="collapse"` will fix it.

I'm using ui-router 0.2.15 and bootstrap 3.3.6

Is this a bug or a misuse by me?

**Comment by christopherthielen** [comment]
I'm guessing the bootstrap JS is preventing the ui-sref from handling the click.  If you put this in a plunker I can take a look.

**Comment by eddiemonge** [comment]
@wangshan ^^

**Comment by wangshan** [comment]
I messed with plunker a bit, but I can't even get the dropdown to work, i.e., it doesn't even show the menu item, any idea what I'm missing?

http://plnkr.co/edit/wgvwWLE54pDVTeJWPnzg?p=info

**Comment by christopherthielen** [comment]
I think you forgot to include the bootstrap js

    `<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
`

**Comment by wangshan** [comment]
You are totally right, I have since fixed the plunker: http://plnkr.co/edit/wdShLDHkg6kKnefPD5Kp?p=preview <http://plnkr.co/edit/wdShLDHkg6kKnefPD5Kp?p=preview>


The problem is reproducible only if I load the scripts in certain order, particularly if I load jquery after ui-router:
  <script src="//npmcdn.com/show-current-browser-url"></script>
  <script src="//npmcdn.com/angular/angular.js"></script>
  <script src="//npmcdn.com/angular-ui-router@latest/release/angular-ui-router.js"></script>
  <script data-require="jquery@2.2.0" data-semver="2.2.0" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
 
If I move jQuery to the beginning it works, is it generally a good idea to load jQuery first?


Thanks,
Shan

**Comment by eddiemonge** [comment]
Yes, you should be loading jquery first so angular uses that instead of its jqlite selector library.
