### ISSUE TITLE
SVG xlink:href not working with latest Chrome 

### ISSUE THREAD

**Issue by gromag** [angular-ui/ui-router#2768]
It seems there is a problem with SVG links since last Chrome update to Version 50.0.2661.102 m.

SVG links like `<svg><a xlink:href="/home"><text>SVG link to Home</text></a></svg>` no longer work.

The problem is only when using HTML5 Mode (i.e. no hashbang), here is an example where you can test the problem.

https://dl.dropboxusercontent.com/u/20105836/index.html

Source code:

https://github.com/gromag/angular-ui-router-chrome-test

Note: it used to work in Chrome until this latest update, as of current version of Firefox 46.0.1 and IE 11 .0.31 it works.

I'm happy to look into it further but I would need some guidance.

Thanks

Giuseppe

**Comment by christopherthielen** [comment]
I think this is a Chrome bug.



I tracked this down to [this global click handler](https://github.com/angular/angular.js/blob/a4e4feed909408ff837ac328371d0fad6ca49e9d/src/ng/location.js#L860-L883) in core angular.js.  When it finds an anchor tag which is an SVG element, it uses the `animVal` as the href.

In Chrome, the `animVal` is currently a passthrough to the `href` attribute.  Here's the relevant [chromium bug issue 606200](https://bugs.chromium.org/p/chromium/issues/detail?id=606200), filed April 24, 2016.  It looks like it has been fixed

### Note how `baseVal` has `"/home"` but `animVal` has `""`

![screen shot 2016-05-25 at 11 27 39 am](https://cloud.githubusercontent.com/assets/2053478/15548169/c9065c44-226c-11e6-92d6-cb0cf447a765.png)

If you add `href` to your svg element, then your link works again.

closing as not a ui-router bug

**Comment by gromag** [comment]
Thanks for the update Chris

I got the Chrome update and it fixes it.
