### ISSUE TITLE
content "shifty" on state change

### ISSUE THREAD

**Issue by wbarbee** [angular-ui/ui-router#2769]
this is likely an error in my own implementation of the ui-router, but the content on some (not all) of my states/views shifts on change. in some instances, the content will begin slightly off of where i intend it to be positioned on the page and jerk into the correct place when the page fully loads. in other instances, the entire view will shift right before it transitions to another view. 

off hand, does anyone know why this might be the case? i would be glad to offer examples of code but wanted to throw that out there, in case anyone else had noticed this.

**Comment by eddiemonge** [comment]
Try asking on stackoverflow. Some ideas though: are you using ngAnimate or have any CSS transitions defined? Are there images that shifting the page after they have already loaded? What about fonts?

**Comment by wbarbee** [comment]
thanks eddie, 
i do have some fade-in/out animations on the views that i'll look into. the images load fully and, for instance, will start without the margins that i have applied and will subsequently lock in place once the state has fully loaded.
