### ISSUE TITLE
ui-sref-active causes a lot of extra digest cycles

### ISSUE THREAD

**Issue by Ralf9977** [angular-ui/ui-router#2777]
The $timeout in ui-sref-active directive causes a lot extra digest cycles. In our case 12!

function addClass(el, className) { $timeout(function () { el.addClass(className); }); }

Do we really need $timeout? At least removeClass does not use $timeout.

**Comment by christopherthielen** [comment]
The $timeout is apparently a fix for https://github.com/angular-ui/ui-router/issues/1997

**Comment by eddiemonge** [comment]
Do you have 12 elements/classes that are being applied? I wonder if there is a way to queue them all to fire at the same time but I'm not sure. Also, I think the digest cycles might happen anyway without the timeout?

**Comment by Ralf9977** [comment]
Thanks for quick response!

I've created a Plunker with a very simple example:
https://plnkr.co/edit/7bM2fzRcvHK05CIE0nlD?p=preview

Just open the browser console and click on a, b, c or d. 6 Digest cycles are performed. 4 because of the timeout.

If you replace 
      function addClass(el, className) { $timeout(function () { console.log("timeout"); el.addClass(className); }); }

by
      function addClass(el, className) { el.addClass(className); }

in ui-router.js only 2 cycles are necessary.

**Comment by christopherthielen** [comment]
> Do we really need $timeout? At least removeClass does not use $timeout.

I think we *do* really need `$timeout`.  Removing it will cause a regression for a very common use case, ng-repeat over a list of ui-sref-active and ui-sref.

**Comment by christopherthielen** [comment]
I think we can use `applyAsync` when available, and fall back to `$timeout` otherwise.
Targeting 0.3.2 and 1.0 final

**Comment by christopherthielen** [comment]
Fixed by using `$applyAsync`
https://plnkr.co/edit/UbLQjuxS47YgR0OScpgK?p=preview
