### ISSUE TITLE
When change router open popup but not remove current content.

### ISSUE THREAD

**Issue by tamanhquyen** [angular-ui/ui-router#2778]
I have created modal when change router using angular bootstrap ui . But it is not strictly my required, i want open modal but not change content in ui-view attributes or any measures can create flags change content true or false. Please help me. 
Thanks a lot!

**Comment by eddiemonge** [comment]
This sounds like an implementation issue. You should be able to call the Modal.open method from your controller or an onEnter for the state.

If that doesn't solve your problem, please try asking on stackoverflow as this is more for bugs and feature requests.

**Comment by BKB503** [comment]
create nested state as below that will not remove and content and opens popup 

state({
               name: "parent.child",
               url: "/parentchild",
               onEnter: ['$stateParams', '$state', '$uibModal', function ($stateParams, $state, $uibModal) {
                   $uibModal.open({
                       templateUrl: "template url"
                       resolve: {
                       },
                       controller: "controllername",
                   }).result.finally(function () {
                      // $state.go('^');
                   });
               }]
