### ISSUE TITLE
Tab order in nested views

### ISSUE THREAD

**Issue by s0oft** [angular-ui/ui-router#2784]
Hi,
i have a problem with tabindex in nested views.
```
$stateProvider
        .state("Front", {
            templateUrl: "views/front.html"
        })
        .state("Front.Page", {
            url: "/page",
            templateUrl: "views/page.html"
        });
```
index.html
```
...
<div ui-view>
    <a ui-sref="Front.Page">go</a>
</div>
...
```
front.html has a link in footer
```
<div ui-view></div>
<a href="">Footer link</a>
```
page.html has links
```
<a href="">link</a>
<a href="">link</a>
```

when im'm going to page by link inside index.html and pressing tab the first focused element is Footer link. Why tab order starts from parent view?

**Comment by eddiemonge** [comment]
Do you have tabindex set on the html elements? And this is more of a browser thing and Im guessing its different behavior in different browsers. If the tab order starts from the parent view its probably because that is loaded first.

**Comment by s0oft** [comment]
@eddiemonge by default, tabiindex for <a> element is 0, so this must start from first element, doesn't matter what rendered first when I've changed the state. I don't know is this a browser thing or not. Tested in latest chrome and FF. Adding tabindex gives no result.
