### ISSUE TITLE
Dynamic query string

### ISSUE THREAD

**Issue by umair321** [angular-ui/ui-router#2785]
Is there any way to load state with query string without mention query string in state.url? For example,
I am writing routes like:

> state('advanced-search', {
>                     url: '/advanced-search?genre&length&instrumental&q&decade&searchInstrument&tempo'',
>                     templateUrl: 'partials/songs.html',
>                     controller: 'AdvancedSearchController'
>                 })

Is there anyway to use it like:
... 

> url: '/advanced-search?path*,

without loosing query string from url.

**Comment by christopherthielen** [comment]
At this time there is not a way to do that, sorry

**Comment by eddiemonge** [comment]
No but if you are just using those values in the controller you can use vanilla angular's `$location.search() ` to retrieve them.

If this doesn't solve your problem, can you please clarify what you are trying to do?
