### ISSUE TITLE
Redirect a user to a particular 'state' from a link in email sent using AngularJS

### ISSUE THREAD

**Issue by jayarajoffice** [angular-ui/ui-router#2786]
When a user clicks on a link, which is sent to his email from the application, I want the user to be redirected to a particular state in my application. [For instance, say the link is for redirecting the user to reset password screen on my application.]
Say a message like - click here to reset your password: http://my-ip/my_application_name/admin/reset?some_token_123456789

    mainApp.config(['$stateProvider', '$routeProvider', '$urlRouterProvider', '$httpProvider', '$locationProvider',
    function($stateProvider, $routeProvider, $urlRouterProvider, $httpProvider, $locationProvider) {

    $locationProvider.html5Mode({
      enabled: true,
      requireBase: false
    });

    $urlRouterProvider.otherwise('/');
    $stateProvider
    .state('page', {
        abstract: true,
        url: '/my_application_name/admin',
        views: {
            'home': {
            template:  '<div ui-view="body"></div>'
        }
    }
    })
    .state('page.login', {
    url: '',
    views: {
        'body@page': {
            templateUrl:  'mainApp/landingPage/login.html',
            controller:   'loginController'
        }
    }
    }).state('page.resetpassword', {
        url: '/reset',
        views: {
            'body@page': {
                templateUrl:  'admin/mainApp/landingPage/resetPage.html',
                controller:   'resetPasswordController'
            }
        }
    });

The redirection used to work, when I was using ng-route and but I dont know how to implement it using the ui-route. 
For ng route, the url sent to mail was like this :  http://my-ip/my_app_name/admin/#/reset?some_token_123456789

Later, when I changed the code and made use of ui-route, I changed the url to 
http://my-ip/my_app_name/admin/reset?some_token_123456789

For ngRoute, My code was like :

    $routeProvider
    .when('/', {
        // Navigate to login/home screen
        templateUrl: 'mainApp/landingPage/login.html'
    })
    .when('/reset', {
        // Navigate to password reset screen
        templateUrl: 'mainApp/landingPage/resetPage.html'
    })
    .otherwise({
        redirectTo: '/'
        });

I have gone through the [urlRouter](http://angular-ui.github.io/ui-router/site/#/api/ui.router.router.$urlRouter) pages in the angular documentation. But I couldnot make much out of it. Someone may please help me out. My apologies, I am sorry, that I have not put all my code up here for clear idea, that because, this is a company project, and I have limitations.

**Comment by christopherthielen** [comment]
Your states look fine.  What happens when the user clicks the link?

The one thing I notice is your ng-route example uses "hashbang" i.e., `#/reset` while it appears you have html5 mode enabled for your ui-router application.  Do you have rewrite rules enabled on your *server* to enable html5 mode?

**Comment by jayarajoffice** [comment]
While I was using ng-route, this is the email sent : http://my-ip/my_app_name/admin/#/reset?some_token_123456789

While I am using ui-route, this is the email sent : http://my-ip/my_app_name/admin/reset?some_token_123456789

I wish to switch from ngRoute to uiRoute. So, instead of 
.when('/reset', {
    // Navigate to password reset screen
    templateUrl: 'mainApp/landingPage/resetPage.html'
})

I wish to use ui-route 's $urlRouterProvider to implement the routing from external link. 

The problem is that, I am getting a 404 - Not Found error. I understand that, this is happening because, there is no index.html file at the location : my_app_name/admin/reset

I tried: 
 $urlRouterProvider
      .when('/reset', ['$state', function ($state) {
            $state.go('page.resetpassword');
    }]).otherwise('/');


and I have a state defined like this... 

$stateProvider.state('page.resetpassword', {
        url: '/reset',
        views: {
            'body@page': {
                templateUrl:  'admin/mainApp/landingPage/resetPage.html',
                controller:   'resetPasswordController'
            }
        }
    });

I also need the token from the url to be available in my resetPasswordController controller

**Comment by christopherthielen** [comment]
HTML5 mode requires server side support.  The 404 is a server message saying nothing found at the *_server route_* `/myapp/admin/reset`.  You need to configure url rewriting on the *server*.  No amount of angular or ui-router code can solve this because angular and ui-router aren't even loaded.

https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-your-server-to-work-with-html5mode
