### ISSUE TITLE
Is it possible to switch off inheritance in `resolve` load?

### ISSUE THREAD

**Issue by extempl** [angular-ui/ui-router#2787]
Imagine you have page with list of items, and nested page with item - in both of them there are data loading in resolve. And when you open item page - it will resolve list of items as well. Why? I do not want it to behave like this.

**Comment by christopherthielen** [comment]
By design, if a state is activated, its parent states are also activated. All resolve data for all activated states are fetched.

Perhaps you could use siblings states instead of nested states?

**Comment by christopherthielen** [comment]
closing because this is as design
