### ISSUE TITLE
$transitions.onBefore not called when minimized on 1.0.0-alpha.5

### ISSUE THREAD

**Issue by nicmae** [angular-ui/ui-router#2788]
I use onBefore hook during my run block to load additional data for my app.

I notice that when my code is minimized (works well not minimized), the onBefore hook is never called and my application does not load further than then run block. However my hook is added to the hooks as a $transitions.getHooks proves.

Below my minimized code (idented for better reading)
The first log display the $transitions object, the log inside the onBefore method is never called, and the last display 2 hooks: one with all matchCriteria to true, and mine.

As if the router is waiting for the promise of my onBefore callback, without calling it.

Any idea about this bug or how to resolve it?

```javascript
(...).run(["$transitions",function(a){
  console.log("run",a);
  a.onBefore({to:"*",from:""},function(a,b){console.log("$transitions.onBefore")},{priority:10});
  console.log("$transitions.getHooks",a.getHooks("onBefore"));
}])
```

**Comment by christopherthielen** [comment]
@nicmae you should annotate the hook function too, as it is also injected.

`['$transition$', 'MyService', function(a,b){console.log("$transitions.onBefore")} ],{priority:10});`

On the other hand, there's a breaking changing upcoming (probably in alpha .6) which eliminates DI injection for transition hooks.  Instead, the arguments will always be `(Transition, $injector)` so you can do `$injector.get('MyService')` to access DI services

**Comment by nicmae** [comment]
Thanks for your precious feedback @christopherthielen, it works perfectly with the annotation!
I will be aware to the upcoming breaking change.

Have a nice week end
