### ISSUE TITLE
Adding views in state crash it 

### ISSUE THREAD

**Issue by BjornMelgaard** [angular-ui/ui-router#2791]
All in main view stop displayed when I uncomment `views` in [application](https://github.com/BjornMelgaard/poller/blob/master/app/assets/javascripts/routes.coffee#L21)
```coffee
.state 'users.show',
  url: '/:id'
  controller: "UserController"
  templateUrl: 'users/show.html'
  # views:
  #   "poll_table":
  #     templateUrl: "users/poll_table.html"

```
`show.html.slim` code below

```slim
h2 {{user.email}}

div ui-view="poll_table"
```

**Comment by christopherthielen** [comment]
This code:

```
.state 'users.show',
  url: '/:id'
  controller: "UserController"
  templateUrl: 'users/show.html'
``` 

is sugar for this code:

```
.state 'users.show',
  url: '/:id'
  views:
    "": 
      controller: "UserController"
      templateUrl: 'users/show.html'
```

And you can't mix the sugar version with the non-sugar version.

Change your code like so:

```
.state 'users.show',
  url: '/:id'

  views:
    "": 
      controller: "UserController"
      templateUrl: 'users/show.html'
    "poll_table":
      templateUrl: "users/poll_table.html"
```

This wasn't well documented until recently in the 1.0 branch: http://angular-ui.github.io/ui-router/1.0.0-alpha.3/interfaces/ng1.ng1statedeclaration.html#views (at the very bottom)

**Comment by BjornMelgaard** [comment]
@christopherthielen, thank you :+1:
