### ISSUE TITLE
Help / Manual for Ui Router with Angular 1.5 Components ?

### ISSUE THREAD

**Issue by ianjohnspain** [angular-ui/ui-router#2793]
Hi,

Can anyone point me in the right direction for help in integrating ui router with angular 1.5 components. I can't seem to find any concrete info, it appears that some functionality is working but not too sure whats in and whats not.

Can anyone help ?

Just interested in working with the ui router and angular 1.5. I am about to undertake a migration from 1.3 to 1.5 and using components, the current app uses ui-router with states and child states.

Thanks in advance

**Comment by zzeniou86** [comment]
+1

**Comment by christopherthielen** [comment]
ui-router 0.3.0 binds `$resolve` to the `$scope`, so you can use "route to component template" style, such as 

```js
.state('foo', {
  resolve: { mydata: (Service) => Service.getData() }
  template: '<foo-component data="$resolve.mydata"></foo-component>'
});
```

ui-router 1.0 supports routing directly to components, with resolves feeding into component bindings of the same name

```js
.state('foo', {
  resolve: { mydata: (Service) => Service.getData() }
  component: 'fooComponent'
});

.component('fooComponent', {
  template: '<h1>{{$ctrl.data}}</h1>
  bindings: { mydata: '<' }
})
```

See the 1.0 docs for the `component:` property of a view (and also `bindings:` here http://angular-ui.github.io/ui-router/1.0.0-alpha.5/interfaces/ng1.ng1viewdeclaration.html#component


There are some real world-ish examples in the `angular-1.5-components` branch of the ui-router sample app

https://github.com/ui-router/sample-app/blob/angular-1.5-components/app/mymessages/mymessages.module.js

**Comment by ianjohnspain** [comment]
Great! Thanks. I presume we can still use abstract states and child states (dot notation) with component routing ?

**Comment by christopherthielen** [comment]
> I presume we can still use abstract states and child states (dot notation) with component routing ?

yes, definitely.

**Comment by ianjohnspain** [comment]
Great, Thanks for the prompt reply.

**Comment by karin-n** [comment]
```
            .state('parentState', {
                url: 'parent',
                abstract: true,
                views: {
                    main: 'parentComponent'
                }
            })
            .state('childState', {
                url: '/child',
                views: {
                    parent: 'childComponent'
                },
                resolve: {
                    parentObject: () => 'parentComponentControllerObject'
                }
            });

.component('childComponent', {
  template: '<div>{{parentObject.name}}</div>'
  bindings: {parentObject: '<'}
})
.
```

@christopherthielen Sorry if this is a silly question, but it would be awesome if you could explain how I can pass an object from my parent component controller to the child component controller.

I know how to inject data from a service, but not from the parent controller.  Or maybe I should just be using the 'require' attribute on my child component and gain access to the parent controller that way? 
Thanks in advance!

**Comment by vladimiry** [comment]
@karin-n The components way would look like passing callback method to the child component (surely if you don't go with events or another not angular specific data sharing approach):
```html
<parent on-update="$ctrl.updateUser($event);">
    <child>
        ...
        <a href ng-click="$ctrl.onUpdate({$event: {user: $ctrl.user}});">Update</a>
    </child>
</parent>
```
So this way requires `&` binding defined for the child component:
```javascript
{bindings:{onUpdate: '&'}}
```

I guess you can try to define your parent component as a string template (ui-router 0.3.0 approach):
```javascript
{template: '<parent data="$resolve.mydata" on-update="$ctrl.updateUser($event);"></parent>'}
```

**Comment by karin-n** [comment]
@vladimiry thanks for your answer! I was hoping that I didn't need to use the string template approach, but I guess it's still a good solution.

**Comment by michahell** [comment]
And how do we  access the resolved objects inside the component controller ?

**Comment by karin-n** [comment]
@michahell the resolved object will be bound to the controller, e.g. $ctrl.data in your html template, or this.data in your component controller.

**Comment by klausbert** [comment]
Do you plan to support bindings to callback (&) functions with the new state.component() syntax?
Sort of:
`.state('child', { url: '/child', component: 'child', resolve: { onUpdate: (param) =>{ console.log(param)} }})`

where child component is

`.component('child', {
bindings: { onUpdate: '&' },
...
})`?
It looks like 1.0.0 is only working with '<' or '=' bindings.
Thanks!

**Comment by freeman29** [comment]
Waiting for this^

**Comment by agupta-q4** [comment]
@christopherthielen this link https://github.com/ui-router/sample-app/blob/angular-1.5-components/app/mymessages/mymessages.module.js  is dead. Can you please point to working one ? or is it no longer exist ?

**Comment by christopherthielen** [comment]
@agupta-q4 

The route-to-component guide for ui-router for ng1: https://ui-router.github.io/guide/ng1/route-to-component

The sample app is now all 1.5 components: https://github.com/ui-router/sample-app-ng1

https://github.com/ui-router/sample-app-ng1/blob/master/app/mymessages/mymessages.states.js

**Comment by agupta-q4** [comment]
@christopherthielen Thank you ! :)

**Comment by OlivierBoucher** [comment]
@christopherthielen There is no notes on `&` bindings. I simply cannot route to whatever component with an `&` binding, even if I don't want to resolve anything to it.


For example, this will not work.

```
const TestComponent = {
    ...
    bindings: {
        data: '<',
        callback: '&'
    }
} 


.state('....', {
    ....
    component: 'testComponent',
    resolve: {
        data: function() { return 'whatever'}
    }
})
```

**Comment by wjonesy** [comment]
https://github.com/ui-router/sample-app-ng1/blob/master/app/mymessages/mymessages.states.js#L76

What would be the syntax for resolving dependent objects in ES5 javascript.

```javascript
resolve: {   
 // Fetch the current folder from the Folders service, using the folderId parameter
    folder: (Folders, $stateParams) => Folders.get($stateParams.folderId),
    // The resolved folder object (from the resolve above) is injected into this resolve
    // The list of message for the folder are fetched from the Messages service
    messages: (Messages, folder) => Messages.byFolder(folder)
  }
```

I have tried: 

```javascript
resolve: {
    viewModel: ['viewModelService', function (viewModelService) {
        return viewModelService.get().then(function (response) {
            return response.data;
        });
    }],
    anotherViewModel: this.viewModel.propertyName
}
```
However I get the error: "Cannot read property 'propertyName' of undefined"

**Comment by fakingfantastic** [comment]
@christopherthielen 

Same question: how do we pass a callback function into a component via the state

I'm trying to do something like...
```
.state('foo', {

    resolve: {
        onSomething: function (data) { MyService.doSomething(data); } 
    }
})
```
```
// fooComponent

{
    bindings: {
        onSomething: '&'
    },
    template: '<button ng-click='$ctrl.doSomething("foo");></button>'
}
```

@klausbert and @OlivierBoucher and @freeman29 all seem to have the same questions here...

anyone?

**Comment by guest73** [comment]
I have a similar question as @fakingfantastic . Anybody?

**Comment by guest73** [comment]
Also I was trying something similar suggested by @vladimiry but I have a problem as on page reload it does not work.

**Comment by christopherthielen** [comment]
You can bind the callback function using `<`. That's my best answer for
now. I hope to improve on that soon.

**Comment by xzegga** [comment]
@christopherthielen what about ui-router 0.2.18? your aproach for 0.3 not work for me

**Comment by christopherthielen** [comment]
@xzegga neither 0.2.18 nor 0.3.x (`legacy`) have route-to-component.  It's in the `master` branch (1.0.0-beta)

**Comment by guest73** [comment]
@christopherthielen Thank for your answer.

**Comment by christopherthielen** [comment]
route-to-component has been updated to allow "&" bindings between parent/child states: https://ui-router.github.io/guide/ng1/route-to-component#routed-parentchild-component-communication
