### ISSUE TITLE
when the first state is load, fire a function for once

### ISSUE THREAD

**Issue by ebrahim-tadbir** [angular-ui/ui-router#2794]
Hi,
I'm new at ui-router
I want to have a function to be run, when the first state of the application loaded,
sort of this is the function for managing some DOM controlling using jQuery

**Comment by ebrahim-tadbir** [comment]
I have founded this $viewContentLoaded,
but i want to run it only for the first load! not be repeated!

**Comment by eddiemonge** [comment]
Add a listener for that then remove the listener when you run it.
