### ISSUE TITLE
Feature Request: ui-router docset

### ISSUE THREAD

**Issue by genu** [angular-ui/ui-router#2795]
I realize this is out of scope for this project, but perhaps someone can consider contributing to a docset for the ui-router api to be used with [Dash](https://kapeli.com/dash) api browser or other similar tools.

**Comment by eddiemonge** [comment]
The API docs are already like this. Have you tried them?

**Comment by genu** [comment]
hmm. @eddiemonge What do you mean? As in they already exist in docset format?

**Comment by eddiemonge** [comment]
http://angular-ui.github.io/ui-router/site/#/api/ui.router

**Comment by genu** [comment]
I'm aware of the api site you mention. My question is not whether the api document exists, but whether a docset version of them exist.

**Comment by eddiemonge** [comment]
Maybe. If not, you can probably generate your own since the code already has good commenting to support something like that as shown by the api site
