### ISSUE TITLE
angular is not defined with Angular 2 + Typings errors

### ISSUE THREAD

**Issue by micaelmbagira** [angular-ui/ui-router#2797]
I am using `angular-ui-router` 1.0.0-alpha.5 with Angular 2 and I followed the quickstart example.
- When I run my app with ES6 I have this error 
>angular-ui-router.js?dfe8:107 Uncaught ReferenceError: angular is not defined

When I run my app with Typescript, even though I installed and referenced the typings, I have 
> ERROR in ./src/index.ts
(12,9): error TS2305: Module ''angular-ui-router'' has no exported member 'UIRouterConfig'.

> ERROR in ./src/index.ts
(12,25): error TS2305: Module ''angular-ui-router'' has no exported member 'UIROUTER_PROVIDERS'.
>ERROR in ./src/app/states.ts
(3,35): error TS2307: Cannot find module 'angular-ui-router/ng2/interface'.

>ERROR in ./src/routes.ts
(4,9): error TS2305: Module ''angular-ui-router'' has no exported member 'UIRouter'.

I think the solution is to use `ui-router-ng2` instead of `angular-ui-router` from npm, but why ? it's not documented.

**Comment by christopherthielen** [comment]
> I think the solution is to use ui-router-ng2 instead of angular-ui-router from npm,

Yes, use `ui-router-ng2` from npm

> but why ? it's not documented.

Both the ng1 and ng2 codebase is located in angular-ui/ui-router but they have different npm packages.  We're now publishing three npm packages from the single repository: 

- angular-ui-router for ng1
- ui-router-ng2 for ng2
- ui-router-core for third party frameworks to use (see https://github.com/elboman/ui-router-react )

**Comment by micaelmbagira** [comment]
Thanks, it makes more sense now!
