### ISSUE TITLE
Angular 2 support

### ISSUE THREAD

**Issue by mitorski** [angular-ui/ui-router#2801]
You plan rewrite your code for angular 2 support? If - when? Need some help?

**Comment by kukac7** [comment]
@mitorski https://github.com/angular-ui/ui-router/releases/tag/1.0.0-alpha.3 :neutral_face:

**Comment by mitorski** [comment]
made my day <3

**Comment by christopherthielen** [comment]
If anyone wants to help, contact me on gitter. We still have lots to do: code, web site, docs, examples, etc.

**Comment by demisx** [comment]
Would be interesting to hear more on Angular 2 support and how ng2 UI Router compares to Angular's own 3.0 router currently in alpha. I personally loved UI Router in Angular 1 apps and would love to use the state based routing in Angular 2, but I read that Chris has been helping Angular team with the 3.0 router rewrite. Thus, a little confused which router should I use right now with a new Angular 2 app. Any insight will be highly appreciated. Thank you.

**Comment by demisx** [comment]
I've added a diagram to the [quickstart-ng2 Wki page](https://github.com/ui-router/quickstart-ng2/wiki) that visually shows how the current `quickstart-ng2` app version is organized + the state diagram. I find that some people respond better to visual learning then parsing code. Hope this helps others to get started with ng2 router rather sooner.
