### ISSUE TITLE
Using .component (ng 1.5), Configuring routes inside component?

### ISSUE THREAD

**Issue by ianjohnspain** [angular-ui/ui-router#2804]
Hi,

I am currently using ui-router (latest) and its function component fro working with angular 1.5 components. I was wondering where its advisable to configure the routes for top level components (pages :-) ) ?  I recently saw an example where the $routeConfig was injected into the component and routes were configured there.

Is something similar available for ui-router ? Is there something special i need to inject or just the stateProvider?

Of course, whats got me thinking is if its a good idea to configure routes as part of the component ?

Or should this be done in the main .config of the main angular module ?

**Comment by ianjohnspain** [comment]
Taking a closer look at an example I found, there is an AppComponent that sets up all the standard routes i.e. HomeComponent. But child routes are also setup via the HomeComponent.

This is what I am using for reference. https://github.com/zombiQWERTY/angular-component-way-webpack-starter-kit/tree/master/src/components

Thanks in advance for any insight.

**Comment by Spadavecchia** [comment]
## Modular architecture
Each module in an Angular app is a module component. A module component is the root definition for that module that encapsulates the logic, templates, routing and child components.

[from Todd Motto Angular 1.x styleguide (es2015)](https://github.com/toddmotto/angular-styleguide)

**Comment by timothyswt** [comment]
@ianjohnspain the componentRouter in angular 1.5 is deprecated and slated to be removed from 1.6x 

ui router 1.0 alpha 5 you can route directly to a component which is much cleaner than the componentRouter.

**Comment by chihab** [comment]
I am also wondering if it would be possible to configure routes inside components (the smart ones) as it was proposed by the new router (which has then been deprecated).

**Comment by christopherthielen** [comment]
UI-Router doesn't support defining subroutes using a component.  

The UI-Router approach is to define states, which couple a route to a component.
