### ISSUE TITLE
stateChangeSuccess triggered before location.href changes

### ISSUE THREAD

**Issue by subpublic** [angular-ui/ui-router#2807]
Hi!

I'm using $stateChangeSuccess to send analytics data.
$state.current.name shows the correct page info, but window.location.href has not changed.
Therefore my analytics saves the wrong url.

Of course I could send data from $location.url() or other angular data, but it would be easier if there was an event after location was actually changed.

```
$rootScope.$on('$stateChangeSuccess', function() {
      console.log('href', window.location.href);
      $analytics.pageTrack($state.current.name);
});
```

console.logging the href here
http://plnkr.co/edit/sRNMdRWnPpoRBBujMF7n

**Comment by eddiemonge** [comment]
you mean like [`$locationChangeSuccess`](https://docs.angularjs.org/api/ng/service/$location#$locationChangeSuccess)?
