### ISSUE TITLE
Changes to accessing Custom Data 

### ISSUE THREAD

**Issue by yulin-dong** [angular-ui/ui-router#2812]
I have recently updated ui-route from ver 0.2.15 to 0.3.1 and I noticed that accessing to custom data has been changed. With ver 0.2.15, I could use `_.extend(newVar, $state.current.data)` to initiate newVar using lodash. However, in ver 0.3.1, the properties of `$state.current.data` are in` $state.current.data.__proto__ `. With this change, I have to do `_.extend(newVar, $state.current.data.__proto__)` to achieve the same result. Is this intended behavior?

Thanks,

**Comment by eddiemonge** [comment]
can you give a plnkr example?

**Comment by yulin-dong** [comment]
While trying to create an example in plnkr, it turned out that the plnkr worked fine with just including the ui-router and angular. Then I debugged my code again, and noticed that in the debugger that $state.current.data was shown as 'extend', not object (see screen shot below).
<img width="618" alt="screen shot 2016-06-17 at 5 02 25 pm" src="https://cloud.githubusercontent.com/assets/12171681/16167015/bb511d48-34ad-11e6-8df5-f1a31c57d1e7.png">

Maybe something is wrong with my code, or some libraries are incompatible with ui-router. I will continue debugging my code. If you someone has seen similar problem and could provide some hints, it will be greatly appreciated.

**Comment by yulin-dong** [comment]
Ok, I figured out the cause.

I have a state A.B.C which is abstract, with which I have the custom data associate. Also I define a controller for state A.B.C. Then I define non-abstract states such as A.B.C.1, A.B.C.2 etc. When A.B.C.1 is shown, it uses the controller associated with state A.B.C. The changes from ver 0.2.15 to 0.3.1 seems having  changed the way how the inherited custom data is packed. Instead of being an object, it is now an  'extend', which is created by the following code

```
	    // inherit 'data' from parent and override by own values (if any)
	    data: function(state) {
	      if (state.parent && state.parent.data) {
	        state.data = state.self.data = inherit(state.parent.data, state.data);
	      }
	      return state.data;
	    },

```
So to get around of this problem, I can do ` _.extend(this, $state.$current.parent.data);` and it works now.

However, I still question whether this is the intended behavior.

**Comment by paol** [comment]
FYI, this is related to bug  #2631

**Comment by yulin-dong** [comment]
Indeed. Thanks @paol

**Comment by eddiemonge** [comment]
Closing as a duplicate since it seems duplicated, not just related

**Comment by motin** [comment]
> So to get around of this problem, I can do _.extend(this, $state.$current.parent.data); and in some places, I have to do _.extend(this, $state.$current.parent.parent.data); which is not pretty at all.

A prettier way to get the old behavior back is found at https://github.com/angular-ui/ui-router/issues/3045#issuecomment-249991317
