### ISSUE TITLE
$stateChangeSuccess pass toParams null on iPad iOS 9.3.2

### ISSUE THREAD

**Issue by fantarama** [angular-ui/ui-router#2815]
Under some circumstances on iPad with iOS 9.3.2 the event $stateChangeSuccess fire with **toParams** argument set to null.

I'm using the 0.3.0 library version.

**Comment by eddiemonge** [comment]
Are there params actually being passed? Does the same code work on desktop browsers?

**Comment by christopherthielen** [comment]
You'll need to reproduce this in a plunker, otherwise we really can't do much about it.

**Comment by christopherthielen** [comment]
I do know that iOS 9.3 only allows 100 pushState when in html5 mode.

**Comment by fantarama** [comment]
The problem occur on a client device, I can't reproduce the problem in our test devices.

@eddiemonge the state params is passed

@christopherthielen we don't use the html5 mode.

**Comment by Gompje** [comment]
@fantarama I'm having an issue where the event $stateChangeSuccess is never triggered on iOS nor in the Chrome emulator. ui-router v0.3.1; but an older angular version 1.3.20. code works in chrome desktop. any ideas?

**Comment by christopherthielen** [comment]
@fantarama I'm sorry, but there's literally nothing I can do about this issue, unless you can provide details about reproducing.
