### ISSUE TITLE
Resolve trigger the same layout twice in the same page

### ISSUE THREAD

**Issue by Hadarg1** [angular-ui/ui-router#2817]
I'm using Angular 1.5.5, Angular-ui-router 0.2.18, angular-meteor-promiser 1.1.0 and meteor 1.3.3.
The ui-routing part that in question is

```
function routerConfig($stateProvider, $urlRouterProvider, $locationProvider) {
  $locationProvider.html5Mode(true);
  $stateProvider
  .state('auditionExtExec', {
    url: '/AuditionExtExecute/:id',
    templateUrl: 'client/auditions/auditionExtExec.html',
    resolve: {
      auditionsubs: function($promiser) {
        "use strict";
        console.log('in resolve');
        return $promiser.subscribe('auditions');
      },
    },
    controller: 'AuditionExtExecCtrl',
    controllerAs: 'vm'
  })
```

The respective controller is

```
angular.module('brgo')
.controller('AuditionExtExecCtrl', function (
  $state, $stateParams, $scope, $reactive, auditionsubs
) {
  var vm = this;
  $reactive(vm).attach($scope);
  vm.auditionId = $stateParams.id;

  vm.subscribe('auditions');

  vm.start = false;
  vm.auditionResults = {};
  var currentDate = new Date();

  vm.autorun(() => {
    vm.audition = Auditions.findOne({
      _id: vm.auditionId
    });
  });

  vm.addNewExecution = function() {
    vm.auditionResults.auditions = angular.copy(vm.audition.auditions);
    AuditionExecs.insert(vm.auditionResults);
  };

  vm.startaudition = function() {
    vm.start = true;
  };
});
```

The purpose of this page is to display the details of the record from audition MongoDb table and write results of updates to AuditionExec MongoDb table

When the application run, everything looks OK. However, when I manually take the URL of  the auditionExtExec state and I copy it to a new window, the view in the new window is presented twice (the same layout is shown twice, one after the other on the same window) . When I remove the $promiser from the resolve, it looks like it works fine

**Comment by eddiemonge** [comment]
*(three backticks signifies a code block)*

I don't think there is enough code to troubleshoot this. Could you make a plnkr example? 

I'm thinking this is an implementation issue though and not a bug.

**Comment by Hadarg1** [comment]
I agree it is probably a wrong implementation by me which I'm not able yet to identify
I will try to make a plnkr exampe
