### ISSUE TITLE
Error: DI can't find injectable: 'a' (ui-router 1.0-alpha.5 using Angular2)

### ISSUE THREAD

**Issue by wawyed** [angular-ui/ui-router#2818]
If I tried to load the app with the source minified I get this error. So I used strict DI annotation from angular1 (`['depName', (depName) => {}]`) in the resolve, which made the app load and the state got resolved. But unfortunately when I try to navigate to a new state I get the error again. I've double checked and all resolve blocks have the notation.

Is there something am I missing?

**Comment by wawyed** [comment]
Upon a bit more investigation it seems to be related to using:

``` javascript
  var builder = new Builder('', 'systemjs.config.js');
  builder.buildStatic('app/_bootstrap/bootstrap.js', 'dist/script.js', { minify: true })
```

When I'm building an SFX bundle and minifying the librares as well. I tried just minifying my compiled JS code (excluding any libraries) and it seems fine to work ok.

**Comment by christopherthielen** [comment]
Definitely a minification/annotation problem.  It's hard to tell the source of your minification problem without seeing the project.

However (BC Break warning)... resolves and transition hooks in ng2 are going to be changing pretty dramatically in the next release.

We'll be switching to ng2 "provider array" style for resolves:

```js
resolve: [
  { provide: 'myResolve', useFactory: (depName) => {}, deps: [DependencyClass] }
]
```

and are no longer injecting transition hooks, but rather supplying two parameters: `(trans; Transition, injector: Injector)`

**Comment by wawyed** [comment]
I think I'm going to try a different approach and use the angular2-seed project and try to integrate ui-router on it. Might have better look than trying to create a build process for production in the angular2 quickstart example.

**Comment by christopherthielen** [comment]
> angular2-seed

The main difference being Webpack vs SystemJS?  When you finish, would you want to contribute the ui-router seed to the project?  We could create a repo under  `http://github.com/ui-router/`

**Comment by wawyed** [comment]
I was going to use the SystemJS version of angular2-seed (https://github.com/mgechev/angular2-seed).

It's just that the angular2-seed project is ready for production whilst the angular-quickstart is just a basic dev build. So in theory it shouldn't be really difficult to add support for UI-router.

**Comment by wawyed** [comment]
I've created a fork of the angular-seed project that used ui-router instead of component router, it can be found here https://github.com/wawyed/angular2-seed. So far it seems to work fine with ` mangle: true`

**Comment by christopherthielen** [comment]
Nice!

**Comment by mckenzielong** [comment]
@christopherthielen 
> However (BC Break warning)... resolves and transition hooks in ng2 are going to be changing pretty dramatically in the next release.

Did this change for angular 1 as well in beta-1? A hook like 
```javascript
["$state$", ($state$) => { console.log($state$); }]
```
is now being swallowed when hookFn.call throws an exception.

**Comment by christopherthielen** [comment]
Exceptions in onBefore hooks should throw to the main console, and exceptions in async hooks will reject the promise and then pass to the default error handler on the state service.

**Comment by christopherthielen** [comment]
Closing because I think this was answered

@mckenzielong errors shouldn't be swallowed in 1.0.  Please open a new issue about errors being swallowed, if you're still seeing this issue.

**Comment by mckenzielong** [comment]
@christopherthielen haven't had a chance to get my hands on the newest versions - think it was the injector formatting that was screwing me up.  Basing off of this example:

```
$transitions.onBefore( { to: 'requireauth.**' }, function(trans) {
  var myAuthService = trans.injector().get('MyAuthService');
  // If isAuthenticated returns false, the transition is cancelled.
  return myAuthService.isAuthenticated();
});
```
I did see that this chagned for ui-router beta for ng1-- getting the $state$ (assuming this is still injectable)
```
(trans) => { trans.injector().get('$state$'); }
```

**Comment by christopherthielen** [comment]
@mckenzielong the `$state$` is the state being entered/exited/retained, so it only works for `onEnter/onExit/onRetain` hooks.  

You do something like: 

```
$transitions.onEnter({ entering: 'foo' }, (trans, state) => {
  console.log('entering ' + state.name);
  console.log('to state: ' + trans.to().name); // might be 'foo.child' for example
});
```

**Comment by mckenzielong** [comment]
@christopherthielen Oh, nice.  Thanks for clearing that up for me.
