### ISSUE TITLE
Preventing default on stateChangeStart when initial route is invalid causes infinite digest cycle issues

### ISSUE THREAD

**Issue by adambuczynski** [angular-ui/ui-router#2819]
I have a problem where I am getting an infinite digest cycle issue when I browse to a non-existing state.
My setup is as follows:

```js
//Default route goes to the state 'home'
$urlRouterProvider.otherwise('/');

//Home state definition (app is an abstract state)
$stateProvider.state('home', {
    parent: 'app',
    url: '/',
    auth: true,
    controller: 'HomeCtrl',
    templateUrl: 'home/home.html',
    resolve: {
      user($store) {
        return $store.user.get();
      }
    }
});
```

The state `home` requires authentication, which I handle using the `auth: true` parameter on the state definition. It is check in a `$stateChangeStart` event listener:

```js
$rootScope.$on('$stateChangeStart', function(event, toState, toParams) {

  //Authentication required for this state?
  if (toState.auth === true) {

    //Are we verifying authentication? Await the result, then try again
    if (Auth.isVerifying()) {
      event.preventDefault();
      $log.info(
        'State', toState.name,
        'requires authentication, awaiting server verify.'
      );
      return Auth.verify().finally(() => {
        $state.go(toState.name, toParams);
      });
    }

    //Not authenticated?
    if (!Auth.isAuthenticated()) {
      event.preventDefault();
      $log.info('State', toState.name, 'requires authentication.');
      return Login.now(toState.name, toParams);
    }
  }
});
```

The logic is that if we find that we need authentication for a certain state, we check first if we're verifying our token on the server. If that's in progress, we prevent the transition and once the promise is resolved, try transitioning into that state again.

If verifying is done and the user is (still) not authenticated, we prevent the transition and go to the login state (the Login service takes care of that).

Now, all of this works flawlessly when you're browsing to existing states, but when I enter the application via a URL which doesn't exist, the infinite digest cycle error happens, and from some debugging it looks like ui-router is constantly trying to go to the `home` state over and over and over again.

My guess is, that when Angular finds the unknown URL, it tries to send the user to the `home` state (e.g. `/` url), but then as ui-router prevents that, Angular flips out because it's told to stick with the unknown url, which it refuses, and then tries to navigate to the `home` state again. 

If this is the case, is there any way I could prevent this? I prefer to send the users to the `home` state when they enter an invalid url, rather than some dedicated `404` page. Thoughts?

**Comment by eddiemonge** [comment]
This is an implementation issue and not a bug in ui-router. Try asking on stackoverflow instead. You can link to this issue.

**Comment by adambuczynski** [comment]
@eddiemonge if you are so certain this is an implementation error, then can't you say why or at least give a clue as to what I'm doing wrong? I find that dismissing me to SO without a technical explanation/reason is a bit harsh. I'm not a junior developer, and I don't raise issues on GitHub lightly...

**Comment by eddiemonge** [comment]
I'm sorry if my reply came across as rude or not helpful. We get a lot of bug reports that aren't always bugs and so taking the time to answer each one with a lot of detail would take time. Time is the one thing most of us on the team don't have a lot of.

Your issue sounds like a lot of other auth issues that have been resolved in numerous blog posts/tutorials. Here's an example on SO: http://stackoverflow.com/questions/20094273/stop-angular-ui-router-navigation-until-promise-is-resolved (looks promising but didn't look to deeply)

One thing you could do is to try to make a request and intercept the error response. if response says the user isn't logged in, redirect them to a log in state.

This should also be handled in 1.0.0 if you want to use that

**Comment by adambuczynski** [comment]
@eddiemonge I understand you are busy and don't have much time to look into every bug report, but thanks for the additional details anyway. I will have another look and will investigate further. 

When a user is not authenticated I already redirect them to the login page, the problem occurs when a user lands on an unknown page. 

In that scenario, as I said my guess is that when Angular finds the unknown URL, it tries to send the user to the home state (e.g. / url), but then as ui-router prevents that, Angular flips out because it's told to stick with the unknown url, which it refuses, and then tries to navigate to the home state again.

I currently solved it by sending the user to a dedicated 404 page, rather than redirecting them to the home page. Since the 404 page doesn't need authentication, the user can safely be redirected there without side effects.

**Comment by eddiemonge** [comment]
You could add a rule that says if the toState.name === 'home' to do something else. Also seems odd that your home page is auth protected. you should have a non-auth landing page so people can authenticate to

**Comment by adambuczynski** [comment]
Well, it's a pretty common pattern. It's an authenticated app, so navigating to the app "home" URL requires you to be authenticated. This pattern is used by many sites/services that offer an authenticated section/app, e.g. [Harvest](adamnz.harvestapp.com), [Digital Ocean](cloud.digitalocean.com), etc. 

Accessing any of those (short) links to the "home" of the app while unauthenticated, results in you being redirected to the login page, so I don't find it that odd.

There will of course be a non-auth landing page, but that will be a separate app/website.

**Comment by eddiemonge** [comment]
Right, it doesn't redirect you to the home page but rather a login page. That login page could be a landing page with info about the app but usually isn't the home page itself.

**Comment by adambuczynski** [comment]
Yes, so all of that is happening in my app, but... we don't redirect to the login page when the user has an access token already in place. However, we need to wait until we've verified the access token on the server, so while it's being verified, I am wanting to prevent the transition.

But that leads to the infinite digest cycle and Angular trying to push the user back to the home page all the time.

As I said, it only happens in the particular scenario that a) the user *is* authenticated, and b) they land on an unknown page.

We don't want to send them to the login page just yet, because if their access token validates, they are good to go. And we can't show the home page, because they aren't logged in just yet. So it's kind of a limbo. Ideally, they'd just keep seeing the pre-loader until the access token is verified and we get their user details back from the server, at which point the transition could be retried and they would end up on the home page, logged on.

Unfortunately, something about angular's mechanics is preventing that from working correctly.
