### ISSUE TITLE
Child state won't render the selected view

### ISSUE THREAD

**Issue by bepi-roggiuzza** [angular-ui/ui-router#2823]
Hi,

I can't figure out why child states won't render the view, even if the state changes successfully.
This is just an example.

```
<body ng-app="app">
    <a ui-sref="categories">Go to cat</a>
    <a ui-sref="categories.add">Go to Add</a>
    <a ui-sref="categories.edit({ id: 'ciao' })">Go to cat 'ciao'</a>
    <ui-view></ui-view>
</body>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.3.1/angular-ui-router.min.js"></script>
<script type="text/javascript">
angular.module('app', ['ui.router'])
    .config(['$stateProvider', '$urlRouterProvider', function($stateProvider, $urlRouterProvider) {

        $urlRouterProvider.otherwise('/');

        $stateProvider
            .state('home', {

                url: '/',
                templateUrl: './views/home.html'

            })
            .state('categories', {

                url: '/categorie',
                templateUrl: './views/categories/list.html',
                controller: 'CategoriesListController'

            })
            .state('categories.add', {

                url: '/nuova',
                templateUrl: './views/categories/form.html',
                controller: 'CategoryFormController'

            })
            .state('categories.edit', {

                url: '/:id',
                templateUrl: './views/categories/form.html',
                controller: 'CategoryFormController'

            });

    }])
    .controller('CategoriesListController', function($scope) {})
    .controller('CategoryFormController', function($scope) {});
</script>
```

**Comment by christopherthielen** [comment]
I would need to see your templates.  Are you missing a ui-view viewport in your list.html?

http://plnkr.co/edit/4JXqylrfmRCAN3pgG8fJ?p=preview

Please post a plunker of your own.

**Comment by bepi-roggiuzza** [comment]
I've updated my code, but maybe I understood what is the problem, I cannot have child states without a nested ui-view inside parent html.
To accomplish what I want to do I have to set different base states, for example categoryAdd or categoryEdit.

**Comment by christopherthielen** [comment]
We have to put the child state's view somewhere.  We it inside the <ui-view> from the parent.

> To accomplish what I want to do I have to set different base states, for example categoryAdd or categoryEdit.

I don't understand, what is your point? 

Can you post as a plunker?

**Comment by bepi-roggiuzza** [comment]
I'm sorry, the problem was that I totally misunderstood the uses of ui.router nested states and nested views.
Don't need to post a plunker, you can close/delete/destroy this issue, I apologize for having wasted your precious time.

Thank you for your support and quick replies.
