### ISSUE TITLE
Routes configuration during runtime

### ISSUE THREAD

**Issue by InternalVoice** [angular-ui/ui-router#2825]
I have AngularJS app which builds it's UI according to API input data . All information about routes are inside my input data so I can't configure routes after/during building UI. I need a possibility to configure routes after/during UI building.

**Comment by christopherthielen** [comment]
You can hang onto the `$stateProvider` and register states on the fly.  If you fetch all the states before synchronizing with the URL, it's pretty easy.  If you want to register after the user logs in, for instance, there are some more subtle nuances that may cause difficulty.

## Easy mode:

```js
var stateProvider
app.config($stateProvider, $urlRouterProvider) {
  stateProvider = $stateProvider;
  $urlRouter.deferIntercept(); // Dont sync the URL yet
}

app.run(($http, $urlRouter) => {
  // get routes, then register them with the state provider
  $http.get('states.json').then(resp => resp.data.forEach(state => stateProvider.state(state)));
  // tell ui-router to sync the url and listen for changes
  $urlRouter.listen();
  $urlRouter.sync();
})
```

See also: https://christopherthielen.github.io/ui-router-extras/#/future

**Comment by christopherthielen** [comment]
Closing. this is on the radar, and I've provided a workaround

See also #2739 #2711 #146
