### ISSUE TITLE
abstract state cannot pass $stateParams to his children

### ISSUE THREAD

**Issue by Tibicenas** [angular-ui/ui-router#2826]
Hi
I'm trying to **pass a param through the URL and be able to store that value by the children states** controllers, everything works fine unless i use an **abstract parent state** to pass it, is a kind of limitation or have i some typo ?

```javascript
(function() {
  'use strict';

  angular
    .module('app', [])
    .config(config);


  function config( $stateProvider ) {

    $stateProvider
      .state('base', {
        url: '/{user_id:int}',
        abstract: true,
        resolve: {
          user_id: ['$stateParams', function( $stateParams ) {
            return $stateParams.user_id;
          }]
        },
        views: {
          'nav': { /* Non important stuff  */ }
        }
      })

      .state('base.index', {
        url: '/index',
        views: {
          'content@': { /* Non important stuff  */ }
        }
      })

      .state('base.account', {
        url: '/account',
        views: {
          'content@': { /* Non important stuff  */ }
        }
      })

  } // End config

})();
```

The goal here is to be able to go... for example    

_http://mydomain/55/index_ or  _http://mydomain/55/account_  and  see the two children states

but i don't want mydomain/55 to be navigable, in this case a redirect to 
_http://mydomain/55/index_ or to 
_http://mydomain/_

**Comment by christopherthielen** [comment]
looks fine to me.  The resolve `user_id` should be available for injection into `base.*` nested states. You can inject that value into a nested resolve on those states, the onEnter/onExit callback, or the view's controller.

**Comment by Tibicenas** [comment]
Hi @christopherthielen , thanks for your answer.

So need i another resolve for each nested state to pas the user_id ? i thought with the first one was enough 
Can you put a sample snippet of this?

**Comment by christopherthielen** [comment]
> Can you put a sample snippet of this?

```js
$stateProvider
      .state('base', {
        url: '/{user_id:int}',
        abstract: true,
        resolve: {
          user_id: ['$stateParams', function( $stateParams ) {
            return $stateParams.user_id;
          }]
        },
        views: {
          'nav': { /* Non important stuff  */ }
        }
      })


      .state('base.account', {
        url: '/account',
        views: {
          'content@': { 
           template: '<h1>{{ user_id }} </h1>',
           controller: function(user_id, $scope) { $scope.user_id = user_id; } 
          }
        }
      })
```

**Comment by Tibicenas** [comment]
Working !  i saw a typo ( missing the first slash / )   Thank you so much.
