### ISSUE TITLE
Inconsistent Angular 2 Names

### ISSUE THREAD

**Issue by demisx** [angular-ui/ui-router#2828]
There are currently inconsistencies in case naming of ng2 properties. For example, there is `UiView` and there is:

* `UIRouter` in https://github.com/angular-ui/ui-router/blob/3a1160d30cad275af9eb5c9e5142714b974123e6/src/router.ts#L21
* `UIRouterConfig` in https://github.com/angular-ui/ui-router/blob/e9f26f8f70b0e40ceac2e8ac438f426c914d18e8/src/ng2/uiRouterConfig.ts#L68

Shouldn't it be `UiView`, `UiRouter` and `UiRouterConfig` globally?

**Comment by christopherthielen** [comment]
yeah sure
