### ISSUE TITLE
Broken links in UI-Router documenation index

### ISSUE THREAD

**Issue by demisx** [angular-ui/ui-router#2830]
The first two bullets on http://angular-ui.github.io/ui-router/1.0.0-alpha.5/globals.html lead to 404 page:
- "ng2/componentUtil"
- "ng2/location"

**Comment by christopherthielen** [comment]
We now have https://ui-router.github.io/ng2/docs/latest/

Closing as `wontfix`. Thanks for the report, and sorry it took so long to reply
