### ISSUE TITLE
Expose property of object as part of the URL

### ISSUE THREAD

**Issue by kasperlewau** [angular-ui/ui-router#2832]
Hiya. Not sure if this has been asked before, searched high and low on the interwebs but could not find anything (yet). 

My question is this: Is it possible to pass an object as a _non-URL-exposed_ param, take a property out of the passed object(s) and expose the property onto the URL.

Like so: 
```js
.state('foo', {
  url: '/item.id/feed.id',
  params: {
    feed: { default: { id: 'fid' } },
    item: { default: { id: 'iid' } }
  }
})

// url: /iid/fiid

const params = { feed: { id: 'foo' }, item: { id: 'bar' } };
$state.go('foo', params);
// url: /bar/foo
```

Having tested it out, the first URL segment will now be interpreted as `"[object Object]"`.

For now, I'm passing four parameters to 'get around this': 

```js
.state('foo', {
  url: '/itemId/feedId',
  params: { /** same as previous example **/ }
}

const params = { feed, item, itemId: item.id, feedId: feed.id };
$state.go('foo', params);
// url: /item.id/feed.id
```

I'd love it if this was a possibility, but I'm not aware of the implications and restrictions in play.

**Comment by christopherthielen** [comment]
if you were at `/foo/1/2`and the user refreshed the browser, what would the parameter value be? simply `item: { id: 1 }` and `feed: { id: 2 }`? 

If so you can use typed parameters.  

```js
$urlMatcherFactoryProvider.type('objid', {
  encode: (obj) => "" + obj.id,
  decode: (str) => { id: parseInt(str, 10) },
  is: (obj) => obj && typeof obj.id === 'number',
  equals: (a, b) => a.id === b.id,
  pattern: /\d+/
});
```

**Comment by kasperlewau** [comment]
Thanks for the prompt reply @christopherthielen! Never had a go at typed parameters, total lack of awareness of their existence on my behalf. 

I'll give that a go and close down the issue for now, I'll head over to StackOverflow if I need more assistance with this. 

Many thanks! ❤️
