### ISSUE TITLE
Infinite 404 Loop if templateUrl is not found.

### ISSUE THREAD

**Issue by timelyxyz** [angular-ui/ui-router#2833]
Hi Team,
I got the infinite 404 loop when configured with wrong template url.

```
var initState = function() {
  $state.go('note');
};

$urlRouterProvider.otherwise('note');

$stateProvider
  .state('note', {
    url: '/note',
    templateUrl:"views/note.html",
    cache: true,
    controller: function($scope) {
      console.log('enter note');
    }
  })
  .state('page1', {
    url: '/page1',
    templateUrl:"views/partials/page1.html",
    cache: true,
    controller: function($scope) {
      console.log("enter page1");
    }
  });
```

The browser would go into an infinite 404 error. Later then it would crash. It may cause the memory leak. This issue is duplicate with [#2587](https://github.com/angular-ui/ui-router/issues/2587).

But when I change the otherwise route to another template exists url like 'page1', it works ok. So, my question is:
`$urlRouterProvider.otherwise` not only works for url not matched, but also for the template not found?

**Comment by whq731** [comment]
+1

**Comment by avral** [comment]
+1

**Comment by levipage** [comment]
same here
