### ISSUE TITLE
Simpler way to pass $stateParams to component?

### ISSUE THREAD

**Issue by martypdx** [angular-ui/ui-router#2842]
Loving the new component syntax (using `"angular-ui-router": "^1.0.0-alpha.5"`). 

I'm starting to get states that look like:

```js
.state( 'list', {
	url: 'lists/:listId',
	resolve: {
		listId: [ '$stateParams', p => p.listId ]
	},
	component: 'todos'
});
```

Is there a simpler way to pass the $stateParams to the component? Maybe something like:

```js
resolve: {
	listId: '='
},
```

Or maybe it already exists and I just missed it.

**Comment by christopherthielen** [comment]
there's nothing built in, but you could do something like: 

```const resolveParams = (...params: string[]) => 
    params.reduce((acc, param) => acc[param] = [ '$stateParams, params => params[param] ], {})```

Then

```js
.state( 'list', {
    url: 'lists/:listId',
    resolve: resolveParams('listId', 'someOtherId'),
    component: 'todos'
});
```

**Comment by christopherthielen** [comment]
for what it's worth, I usually convert a parameter to the object it represents in the resolve block, instead of feeding the params into the component.

**Comment by martypdx** [comment]
> for what it's worth, I usually convert a parameter to the object it represents in the resolve block, instead of feeding the params into the component.

I've gone back and forth, and what I don't like is when part of the access happens via the router but the rest happens in the component. I've used something like angular-resource, and in that case I can usually pass in the resource because it has a save method and a way to continue to do data service work.

Maybe there's a better pattern, so how do you handle the rest of the service access? So, for example, if the resolve is passing in a list of items, where would you handle adds and removes?

**Comment by martypdx** [comment]
> there's nothing built in, but you could do something like:
> 
> const resolveParams = (...params: string[]) => 
>     params.reduce((acc, param) => acc[param] = [ '$stateParams', params => params[param] ], {})
> Then
> 
> .state( 'list', {
>     url: 'lists/:listId',
>     resolve: resolveParams('listId', 'someOtherId'),
>     component: 'todos'
> });

Thx, that's a nice solution for forwarding state params

**Comment by reckter** [comment]
Does this work as well for states with multiple views? 
The resolved values are not getting injected into the controller of the component.
The resolve functions are getting called and getting the right value though.

This is my code for the state: 

```javaScript
angular.module('module')
    .config([
        '$stateProvider',
        config
    ])

function config($stateProvider) {
    $stateProvider.state('edit', {
        views: {
            content: 'edit'
        },
        resolve: resolveParams('id', 'nextState'),
        url: '/:id/edit?nextState'
    })
}



function resolveParams() {
    var ret = {}
    for(var arg in arguments) {
        var name = arguments[arg]
        ret[name] = [ '$stateParams',
            function binder($stateParams) {
                return $stateParams[ name ]
            }
        ]
    }
}
```

if you have any idea, any help would be appreciated. The only other option I see is not using components for states :/ (or using a template and injecting them via scope)
