### ISSUE TITLE
I can add another state after an id?

### ISSUE THREAD

**Issue by newmesiss** [angular-ui/ui-router#2843]
you can do the following?

`ui-sref="children.ficha({id:children.$id}).about"
`
to stay in my url

`/children/ficha/-kiksjelkksAsd/about`

this since I have a tab that contains two tab, and if I change to tab "timeline" do not miss the id

**Comment by Kindzoku** [comment]
There is no point in this. 
You should have route like "children.ficha.about" (child of "children.ficha", for example) with url like ":id/about/" to use ui-sref like ui-sref="children.ficha.about({id:children.$id})"
