### ISSUE TITLE
Can't install via bower?

### ISSUE THREAD

**Issue by SantoDE** [angular-ui/ui-router#2849]
Hey guys,

I'm currently creating a new SPA. However, I can't install ui-router properly. It is added to my bower.json and it's also installed.

`"dependencies": {
    "angular": "1.2.19",
    "angular-material": "^1.0.9",
    "angular-ui-router": "^0.3.1"
  },`

However, there is no compiled angular-ui-router.js inside the desired bower components folder. There is just the source and stuff. 

Any one got an idea? Thanks

**Comment by christopherthielen** [comment]
it should be in `/release/` directory

https://github.com/angular-ui/angular-ui-router-bower/tree/0.3.1/release
