### ISSUE TITLE
$location.replace is not implemented with Webpack

### ISSUE THREAD

**Issue by micaelmbagira** [angular-ui/ui-router#2850]
I just upgraded from `alpha-5` to `beta.1`.
I changed this 
```js
@Injectable()
export class MyUIRouterConfig {
  configure(uiRouter: UIRouter) {
    uiRouter.urlRouterProvider.otherwise(() => uiRouter.stateService.go('App', null, null)); // here
    uiRouter.stateRegistry.root();
    INITIAL_STATES.forEach(state => uiRouter.stateRegistry.register(state));
  }
}
```
into 
```js
@Injectable()
export class MyUIRouterConfig {
  configure(uiRouter: UIRouter) {
    uiRouter.urlRouterProvider.otherwise('/'); // here
    uiRouter.stateRegistry.root();
    INITIAL_STATES.forEach(state => uiRouter.stateRegistry.register(state));
  }
}
```
I am testing **default url redirection**.
It works perfectly with SystemJS. But when I use Webpack, the url is redirected to `/` but the page is not loaded and I have the following error: 
> Error: $location.replace() not impl
    at Object.loc.replace (eval at <anonymous> (http://localhost:3000/index.js:2747:2), <anonymous>:63:25)
    at check (eval at <anonymous> (http://localhost:3000/index.js:1134:2), <anonymous>:48:23)

**Comment by benjamincombes** [comment]
Same problem for me.

**Comment by christopherthielen** [comment]
I'll look into this for the next beta.

**Comment by hstarorg** [comment]
Same problem for me.
