### ISSUE TITLE
.state data undefined on page refresh 

### ISSUE THREAD

**Issue by zymr-keshav** [angular-ui/ui-router#2852]
as in new _angular-ui-router v1.0.0alpha0_ ,` $stateChangeStart` has been deprecated so using `$transitions.on*` hooks but not getting proper information  where it has to written in _.config_ block on in _.run_ block?

I have tried to check authentications of HOME page in **.config** with below code

```

$stateProvider
        .state("home", {
            url: '/home',
            templateUrl: './home/home.html',
            controller: 'HomeController',
            requiresAuth: true,
            data : { pageTitle : 'Home', authorizedRoles: [USER_ROLES.admin, USER_ROLES.editor] }
 });
$transitionsProvider.onBefore({to: function(state) { return state.requiresAuth; } },
        function($transition$, $state, AuthService) {
            console.log(arguments);
            var from = $transition$.to().name;
            console.log(from);
            if(!AuthService.isAuthenticated()) {
                return $state.go("login", {referral : from});
            } else {
                console.log('I m logged in');
                var roles = $state.current.data.authorizedRoles;
                if(AuthService.isAuthorized(roles)) {
                    console.log('Authorized');
                }
            }
    });
```
 it's working fine so far but when I refresh the same HOME page.. it gives error of undefined data property

see the [plunker](https://plnkr.co/edit/AcQk0Zrik1RjgXL4qLSm?p=preview) for the issue. when it asking for login, write anything in username and password

**Comment by christopherthielen** [comment]
`var roles = $state.current.data.authorizedRoles;`

should probably be

`var roles = $transition$.to().data.authorizedRoles;`

**Comment by zymr-keshav** [comment]
Thanks. I have one more confusion here 

when to use `.onBefore` and when to use `.onEnter` or `.onStart()`

suppose user is logged in but not authorized then where do we write that logic?  in resolve of .state ? or in `.onStart` or in `onEnter()`

**Comment by zymr-keshav** [comment]
see my problem described here [send back to requested url](http://stackoverflow.com/questions/38220151/send-back-to-requested-page-after-authentication-in-angular-js-need-better-app)
