### ISSUE TITLE
Trailing slash added in html5 mode

### ISSUE THREAD

**Issue by tsmith123** [angular-ui/ui-router#2853]
When in html5 mode, if I type in an address in the browser such as `myapp.com/login` a trailing slash will automatically be added for some reason - **is this behaviour expected**?

When I take my app out of html5 mode and use `myapp.com/#/login` then no trailing slashes are added when I type the address in manually.

I am aware of fixes such as removing the trailing slash by reading the URL and `$urlMatcherFactoryProvider.strictMode(false);` but these aren't desirable solutions for me.

**Comment by zachnagatani** [comment]
what was your fix for this?
