### ISSUE TITLE
What is current ability to DI in Transition Hooks?

### ISSUE THREAD

**Issue by martypdx** [angular-ui/ui-router#2854]
Using `"angular-ui-router": "^1.0.0-beta.1"` it doesn't seem possible to dependency inject:

```js
	$transitionsProvider.onStart({
		to: state => !!( state.data && state.data.requiresAuth )
	}, function(UserService){
		// UserService is always transition :(
	});
```

Given [this line](https://github.com/angular-ui/ui-router/blob/66c3ad1fba4598e4aca79dacad4d30ee7a2b64b7/src/transition/transitionHook.ts#L44) in looks like it's hard coded to only supply the transition (and the state context is `null`). I saw in some of the other issues that hook may be changing to supply `$inject`? 

Is there work around? Should I just wait for next release? :)

**Comment by christopherthielen** [comment]
Get the injector from the transition. 

`trans.injector()`

See #2 https://github.com/angular-ui/ui-router/releases

And https://ui-router.github.io/docs/latest/classes/transition.transition-1.html#injector

**Comment by martypdx** [comment]
Thanks @christopherthielen!
