### ISSUE TITLE
1.0.0 alpha 5 route to component resolves issue (with plunk)

### ISSUE THREAD

**Issue by orneryd** [angular-ui/ui-router#2858]
I am not able to get resolves working when specifying resolve specifically for 'component' in the "views" property. It has to be available on the state resolve itself which makes managing individual binding contracts a pain.

https://plnkr.co/edit/z8MRTfFkdvB30afwiIUv?p=preview

see script.js

**Comment by christopherthielen** [comment]
Resolves are state-level, not view-level.  At some point in the past (`0.2.something`), `resolve:` in a view definition would also be fetched (undocumented, not supported).  Even then, they were not scoped to the view or anything.  They were still processed at the state level.  Move your `resolve:` block up to the state level.

**Comment by timothyswt** [comment]
resolving at the view level would be extremely beneficial especially when routing to components. then you could match up the resolve to the bindings.

**Comment by christopherthielen** [comment]
@timothyswt I guess that would be fine, assuming it's just sugar for where the resolve is declared.

What I want to avoid is scoping resolve variables to specific views.  i.e., I don't want to support: 

```
state({
  name: 'foo'
  views: {
    main: {
      resolve: { data: () => getdata() }
    }, 
    header: {
      resolve: { data: () => getotherdata() }
    }
  }
});
```

**Comment by timothyswt** [comment]
That totally makes sense. The idea here is to marry up the
component-specific resolves on the state to the component bindings so
there's a clear distinction when reading that the component contract is
being fulfilled by the component-specific resolve block.
