### ISSUE TITLE
1.0.0-beta.1 Excess error log in stateService.ts

### ISSUE THREAD

**Issue by tianweiliu** [angular-ui/ui-router#2860]
1.0.0-beta.1
stateService.ts?6000:488

are the following console logs necessary?

```
/** @hidden */
  private _defaultErrorHandler: ((_error) => void) = function $defaultErrorHandler($error$) {
    if ($error$ instanceof Error && $error$.stack) {
      console.error($error$.stack);
    } else if ($error$ instanceof Rejection) {
      console.error($error$);
      if ($error$.detail && $error$.detail.stack)
        console.error($error$.detail.stack);
    } else {
      console.error($error$);
    }
  };
```

**Comment by christopherthielen** [comment]
The default error handler is there to handle any uncaught exceptions in transitions.  By default, it logs to the console.  You can provide a noop implementation by calling:

`StateService.defaultErrorHandler(function() {});`

See: https://ui-router.github.io/docs/latest/classes/state.stateservice.html#defaulterrorhandler

**Comment by tianweiliu** [comment]
@christopherthielen thanks for the explanation! I will mark this ticket as closed.
