### ISSUE TITLE
typescript compilation errors "Cannot find name 'Promise'"

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [angular-ui/ui-router#2861]
```sh
error TS2304: Cannot find name 'Promise'<project_root>/node_modules/angular-ui-router/commonjs/ng1/directives/viewDirective.d.ts
(8,17): error TS2304: Cannot find name 'Promise'<project_root>/node_modules/angular-ui-router/commonjs/ng1/statebuilders/views.d.ts
(40,66): error TS2304: Cannot find name 'Promise'<project_root>/node_modules/angular-ui-router/commonjs/state/stateService.d.ts
(74,39): error TS2304: Cannot find name 'Promise'<project_root>/node_modules/angular-ui-router/commonjs/transition/transitionHook.d.ts
(15,1919[31m): error TS2304: Cannot find name 'Promise'<project_root>/node_modules/angular-ui-router/commonjs/transition/transitionHook.d.ts
(21,40): error TS2304: Cannot find name 'Promise'<project_root>/node_modules/angular-ui-router/commonjs/transition/transitionHook.d.ts
(28,87): error TS2304: Cannot find name 'Promise'<project_root>/node_modules/angular-ui-router/commonjs/transition/interface.d.ts
(209,66): error TS2304: Cannot find name 'Promise'<project_root>/node_modules/angular-ui-router/commonjs/view/interface.d.ts
(48,13): error TS2304: Cannot find name 'Promise'<project_root>/node_modules/angular-ui-router/commonjs/resolve/resolveContext.d.ts
(76,57): error TS2304: Cannot find name 'Promise'<project_root>/node_modules/angular-ui-router/commonjs/resolve/resolvable.d.ts
(25,14): error TS2304: Cannot find name 'Promise'<project_root>/node_modules/angular-ui-router/commonjs/resolve/resolvable.d.ts
(66,62): error TS2304: Cannot find name 'Promise'<project_root>/node_modules/angular-ui-router/commonjs/state/interface.d.ts
(12,44): error TS2304: Cannot find name 'Promise'<project_root>/node_modules/angular-ui-router/commonjs/transition/transition.d.ts
(37,14): error TS2304: Cannot find name 'Promise'<project_root>/node_modules/angular-ui-router/commonjs/transition/transition.d.ts
(232,12): error TS2304: Cannot find name 'Promise'<project_root>/node_modules/angular-ui-router/commonjs/common/common.d.ts
(333,58): error TS2304: Cannot find name 'Promise'<project_root>/node_modules/angular-ui-router/commonjs/common/common.d.ts
(333,75): error TS2304: Cannot find name 'Promise'<project_root>/node_modules/angular-ui-router/commonjs/common/common.d.ts
```
package version 1.0.0-beta.1

**Comment by micaelmbagira** [comment]
Same for me with Webpack. Not happening if I use SystemJS or Bower

**Comment by micaelmbagira** [comment]
@ivanvoznyakovsky Fixed it by installing `es6-shim` typings

**Comment by ivanvoznyakovsky** [comment]
hm, I'll give it a try. I used `es6-promise` but that did not help.
thnx @micaelmbagira

**Comment by christopherthielen** [comment]
try `typings install --global dt~es6-shim`

Let me know if it works or not.

**Comment by ivanvoznyakovsky** [comment]
ok, `es6-promise` works perfect. I just did it wrong. I have globally installed `typings` v.1 but in progect we still use 0.3 so format is different and it was not taken into consideration when installed w/ `typings install`. adding it as `ambientDependencies` entry did the trick. 
thnx guys.

**Comment by micaelmbagira** [comment]
Can you close it ?

**Comment by ivanvoznyakovsky** [comment]
oh, sure :)

**Comment by jdthorpe** [comment]
For what it's worth, bluebird promises also work:

    > npm install tsd -g
    > tsd install bluebird

and then in your script, add 

    /// <reference path="./typings/bluebird/bluebird.d.ts" />

**Comment by christopherthielen** [comment]
I recommend using typescript 2.0+ and adding to your tsconfig.json:

```
{ 
  "compilerOptions": {
    "lib": ["es2015", "dom"]
  }
}
```

This tells typescript to use the .d.ts files from `/node_modules/typescript/lib/lib.<library>.d.ts`

**Comment by sandokanelcojo** [comment]
Or just include in your package.json @types/es6-promise (In typescript 2.x)

```javascript npm i --save @types/es6-promise ```

**Comment by teone** [comment]
Small note: remember to add a reference to your `index.d.ts` in your `index.ts` (otherwise this issue can drive you crazy!)
```
/// <reference path="../typings/index.d.ts" />
```

**Comment by aino-gautam** [comment]
I simply did - 
>typings install --global dt~es6-shim

then I added - "lib": ["es2015", "dom"] to compilerOptions . Now it builds fine without those errors.

**Comment by grayzero** [comment]
At file "tsconfig.json" try one of these options:
* if "target": "es5" add ,
"lib": [
      "es6"
    ]
* or change "target": "es5" to "target": "es6"

**Comment by ajanieniolasolomon** [comment]
node_modules/@types/selenium-webdriver/remote.d.ts(139,29): error TS2304: Cannot find name 'Map'.

i fix bt remove this in Map<string, string> | in  setEnvironment(env: Map<string, string> | {[name: string]: string} | null):

**Comment by yashwp** [comment]
I've done... everything that the above comments say...but nothing works for me.... 👎

**Comment by dasmeter** [comment]
This worked for me 

1. npm install typings --global

2. typings install --global dt~es6-shim

3. then I added - "lib": ["es2015", "dom"] to compilerOptions . Now it builds fine without those errors.

**Comment by asingh014** [comment]
Also, make sure your using a recent version of typescript-> `npm install -g typescript` (-g denotes global install)

**Comment by globad** [comment]
> This worked for me
> 
> 1. npm install typings --global
> 2. typings install --global dt~es6-shim
> 3. then I added - "lib": ["es2015", "dom"] to compilerOptions . Now it builds fine without those errors.

Only that halped me. Thanks!
