### ISSUE TITLE
Resolved data on $state.$current in 1.x?

### ISSUE THREAD

**Issue by bwegrzyn** [angular-ui/ui-router#2862]
In 0.x versions of ui-router, I had a breadcrumb component that would hook in to $stateChange* events and update the breadcrumbs based on custom data in $state.$current. It would use resolved data to generate breadcrumbs such as Users -> My User Name. On initial page load, it would just use the data available in $state.$current, and then subsequent state changes would trigger a refresh.

I'm upgrading this breadcrumb component to use the new $transitions service, and I can get the resolved data during a transition (using $transition$.getResolveValue()), but because the breadcrumb component doesn't init until after the initial transition, I'm unable to generate breadcrumbs from resolved data on initial page load. The resolved data seems to be missing from $state.$current. There's no getResolveValue() function available here.

Any tips on how to make this work?

**Comment by bypotatoes** [comment]
I have almost same problem, it seems that `$transition.onSuccess` doesn't run when we reload page.

**Comment by ahmedissa** [comment]
I hope this what are you looking for. 
```javascript
this.$transitions.onSuccess( { to: '*' }, (transition)  => {
      //the current state.
      console.log(transition.to())
})
```

**Comment by christopherthielen** [comment]
@bwegrzyn 
You can get the last successful transition by peeking on the `globals.successfulTransitions`

```
.component('breadcrumb', {
  templateUrl: '/breadcrumb.html',
  controller: ($uiRouter) => {
    this.transitionHistory = [$uiRouter.globals.successfulTransitions.peekTail()];
    this.deregister = $uiRouter.transitionService.onSuccess({}, (trans) => { 
      this.transitionHistory.push(trans));
    }
    this.$onDestroy = () => this.deregister(); 
  }
```

Be warned that the `globals` API might change in the future.

**Comment by bwegrzyn** [comment]
@christopherthielen 
I solved my problem a little differently by assigning the $transition$ object given to onSuccess() to $rootScope.$state.$current.$transition$. It works fine for my use case but it seems like a hack to me.

I will give your suggestion a try. Thanks for the tip!
