### ISSUE TITLE
1.0.0-beta.1 onEnter/onExit no longer injectable?

### ISSUE THREAD

**Issue by timothyswt** [angular-ui/ui-router#2863]
I would suggest that this change be reverted and allow dependencies to be injected into the onEnter/onExit hooks.

This allows services such as the $modal service from foundation/bootstrap to open/close modals based on states instead of managing that inside of a controller. it allows for much more dynamic behavior of states.

**Comment by christopherthielen** [comment]
Angular 1 only: onEnter/onExit on a state declaration is still injected, as before.

See the Note on the bottom of breaking change #2 in the  release notes: https://github.com/angular-ui/ui-router/releases/1.0.0-beta.1

What this means is that this is still injected:

```
.state('foo', {
  onEnter: [ '$modal', function($modal) { ... } ]
});
```

While this hook (not declared on a state declaration) is not injected:

```js
$transtionsProvider.onExit({ exiting: 'mystate' }, function($modal) { ... });
```

Instead, the first parameter for hooks is the current `Transition` object, which you can get the `injector()` from.  see docs https://ui-router.github.io/docs/latest/classes/transition.transition-1.html#injector

So for global onEnter/onExit hooks **not declared on the state**, you do something like so:

```js
$transtionsProvider.onExit({ exiting: 'mystate' }, function(trans) { 
  var $modal = trans.injector().get('$modal) ... 
});
```
