### ISSUE TITLE
accessing resolved data in $transition event hooks

### ISSUE THREAD

**Issue by timothyswt** [angular-ui/ui-router#2864]
Previous versions of ui-router you could access 
```javascript
  $state.$current.locals.globals 
```
which contained the resolved data items. is there a way to access the same data in the transition event hooks for 1.0?

**Comment by stephanbarrett** [comment]
+1

**Comment by bypotatoes** [comment]
There's a method `getResolveValue` on transtion, e.g. if `currentUser` was resolved for `app` and child states:
```
$transitions.onSuccess({to: 'app.*'}, (transition) => {
  this.currentUser = transition.getResolveValue('currentUser');
});
```
The only issue I've stuck is that hooks were not enabled for page reload

**Comment by christopherthielen** [comment]
> The only issue I've stuck is that hooks were not enabled for page reload 

@bypotatoes 
They should... where did you register the hook?

**Comment by christopherthielen** [comment]
Closing because @bypotatoes answered the question correctly.

As a side note, we're moving away from "global state" such as the undocumented `$state.$current` and encouraging state to be retrieved from a transition.

**Comment by esinek** [comment]
In my `$transitions.onSuccess`, I am trying to access an async resolve item using `transition.getResolveValue('title')` and getting `undefined` (i.e. not yet resolved). I thought the resolve items would be resolved by the time the `onSuccess` was fired.

**Comment by christopherthielen** [comment]
Hmm yes, they should be ready by then

**Comment by christopherthielen** [comment]
I've removed `getResolveValue()` in favor of `Transition.injector().get('title')`

See: https://github.com/angular-ui/ui-router/releases/tag/1.0.0-rc.1

**Comment by abelbarbosa** [comment]
@christopherthielen I've just tried to do:
```
$transitions.onSuccess({}, function (transition) {
    $rootScope.title = transition.injector().get('title');
});
```
And it returns '0'. What am I missing?
Thank you.

**Comment by maartenzwart** [comment]
@bypotatoes: Have you found a solution?

Having the same issue, but only when I'm reloading a state which does a redirect to a substate in the background. For states where this is not the case, I get the resolved value back from the transition object, even whith a page reload.

**Comment by arashsoft** [comment]
Transition.injector().get() works fine but how can we get resolved data of a state without transition ??

**Comment by spanitz** [comment]
It's been a while. But if you still depending on view controllers (instead of components) you could...

```javascript
// assuming the following state config
{
  views: {
    '@': {
      template: `<div>{{ctrl.foo}}</div>`,
      controller `MyController as ctrl`
    }
  },
  resolve: {
    foo: () => Promise.resolve('foo')
  }
}

// then hook into transition
$transitions.onSuccess({}, trans => {
  const toState = trans.$to();

  if (toState.resolvables.length) {
    toState.resolvedTokens = {};

    toState.resolvables.forEach(x => {
      toState.resolvedTokens[x.token] = trans.injector().get(x.token));
    }
  }
});

// in your controller
function MyController($state) {
  this.foo = $state.$current.resolvedTokens.foo
}
