### ISSUE TITLE
grunt build failing

### ISSUE THREAD

**Issue by gochinj** [angular-ui/ui-router#2865]
Trying make my own modification to stateRegistry.ts.  Even without my code change I am getting the following error after the tsc finishes compiling.

```
Running "ts:ng2" (ts) task
Compiling...
Cleared fast compile cache for target: ng2
### Fast Compile >>src/ng2.ts
### Fast Compile >>src/justjs.ts
### Fast Compile >>typings/es6-shim/es6-shim.d.ts
Using tsc v1.8.10



TypeScript compilation complete: 3.42s for 3 TypeScript files.

Running "bundles" task
Warning: Unable to read "build/es5/ng1/stateEvents.js" file (Error code: ENOENT)
```

**Comment by christopherthielen** [comment]
hi @gochinj 
The tooliing is in flux right now.  We're trying to move off Grunt and use mostly npm and shell scripts.

Try running `./scripts/bundle.sh ng1` or `./scripts/bundle.sh ng2` depending on what you're building.

See here: https://ui-router.github.io/ng1/#development
