### ISSUE TITLE
How to inject $error$ in 1.0.0-beta.1

### ISSUE THREAD

**Issue by spencersteers** [angular-ui/ui-router#2866]
In the last alpha I was able to access the error object in an onError hook through:

```js
var redirect = ['$error$', function($error$) {
    if ($error$ && $error$.status === 404) {
        $state.go('assets');
    }
}];
```

Now that injections are done through the `transition` parameter I tried:
```js
var redirect = function (transition) {
    var $error$ = transition.injector().get('$error$');
    if ($error$ && $error$.status === 404) {
        $state.go('assets');
    }
};
```

Which always produces unknown provider errors.

Is there a new way to get the error object?

**Comment by tianweiliu** [comment]
#2860

**Comment by fasfsfgs** [comment]
Not sure if this question belongs here, but I'll do it anyway.

How should I implement a default error handler?
I'm new to this transition concept. I (think I) did manage to fire onError events but I can't see how do I get the error thrown.

In my case I have a rejected promise in the resolve object that returns a string but I'm unable to get this string inside my $transitions.onError. Also tried $transitions.defaultErrorHandler with no luck.

Can you guys help me please?

Thanks!

**Comment by declspec** [comment]
+1 
I found the error embedded in `transition.promise.$$state.value` but it seems like there really should be a less hacky way of accessing an error in an `onError` method. Maybe I'm just setting up the error handler all wrong.

```
app.config(['$transitionsProvider', function($transitionsProvider) {
    $transitionsProvider.onError({...}, function(transition) {
        var error = transition.promise.$$state.value; // No idea if this is always going to be available at the time of invocation
        console.error(error);
    }
}]);
```

**Comment by christopherthielen** [comment]
I think this was an oversight in beta.1, sorry.  in beta.2 we will expose the error as  `transition.error()`.

**Comment by christopherthielen** [comment]
Note: a workaround:

```js
var redirect = function (transition) {
  transition.promise.catch(function($error$) {
    if ($error$ && $error$.status === 404) {
        $state.go('assets');
    }
  });
};
```
