### ISSUE TITLE
Feature Request: Rendering states for progressive apps

### ISSUE THREAD

**Issue by 34r7h** [angular-ui/ui-router#2867]
This is a request for a new feature. I'm thinking through the best way to get high performing seo with an angular app and think ui-router is a great place to start. It may get tricky using wildcard urls but it can also be the best place to make sitemaps from which to render the states into static html files until a non-bot client loads new resources and data.

The current problem with solutions, aside from cost, is that the prerender and seo.js style creates an additional server call to crawlers which makes web apps take a hit on load times. Another way is to use a headless browser on the server to render states on the fly but currently this is a tech headache.

Maybe we can discuss a smooth way to integrate PhantomJS with UI-Router in order to present a progressive experience for the client while still coming up cherry for the crawlers.

Thoughts?

**Comment by nateabele** [comment]
I think Angular Universal is what you want to look at for that: https://github.com/angular/universal

**Comment by irthos** [comment]
I think A-Universal is strictly for ng2 apps. Do you think it could work for 1.x, as well?
