### ISSUE TITLE
Any way to force Apache to detect $state changes?

### ISSUE THREAD

**Issue by jml6m** [angular-ui/ui-router#2868]
I am using `LocationMatch` Apache directive to apply some logic to an AngularJS app. To test, I have the regex cover just one state, http://my.ui.com/login

**Apache**

```
<LocationMatch "^/(login)(.*)">
    Redirect "/login" "/login2"
</LocationMatch>
```

This simple `Redirect` is used to check if the block has been triggered. When I got to the URL above directly (fake URL, sorry I can't share the real app), I can see the redirect working by observing the URL bar. However, if I navigate to this state using a `ui-sref` button, the LocationMatch block is never triggered. Here is the relevant AngularJS code:

**UI State**

```
$stateProvider.state('login', {
    url: '/login',
    templateUrl: 'login.html',
    controller: 'LoginCtrl'
});
```

**Button (clicking doesn't trigger Apache)**

`<button class="md-button" ui-sref="login">Login</button>`

I'm guessing because the AngularJS app is loaded all at once, there is no disk read made when a stateChange occurs. I'm hoping there's a way in ui-router, or maybe AngularJS in general, to force a disk read or something else that Apache would detect.

**Comment by danielneri-accesso** [comment]
Are you not using URL rewriting for your application? 

Typically, all requests are fed directly to the application, and you would create rewrite rules with UI Router to handle such conditions.

**Comment by jml6m** [comment]
We do have this block in our conf file:
```
<Directory>
    FalbackResource index.html
</Directory>
```
This is for html5Mode. I know there is a way to do it with RewriteRules but it seemed more complicated.

Regarding my OP, it seems Apache `<LocationMatch>` is only triggered on app load. So we actually hack around this by forcing a `$window.location.reload()` in code. It would still be nice to find a way for Apache to detect state changes though.

**Comment by krassx** [comment]
You seemed to mess two things here: single-page apps (SPA) and multi-page apps (MPA).

Angular and hence ui-router are parts of the first one. SPA implies that there are no page reloads made to update content, only ajax. All your state changes are made and handled client-side (via History API) and never reach server. If you need to redirect user somewhere do it by client-side logic.

If you need to notify server about changes happening client-side use ajax or jsonp (in case of cross origin calls).
