### ISSUE TITLE
Reload option doesn't accept relative path

### ISSUE THREAD

**Issue by geofreyflores** [angular-ui/ui-router#2869]
Reload option in $state.go doesn't recognize relative paths (in v0.2.x)

e.g. given current state is 'parent', and 'parent.child' state exists:

`$state.go(".child", {}, {reload: 'child' }) ` works, but
`$state.go(".child", {}, {reload: '.child' }) ` doesn't

and throws error - Error: No reference point given for path '.child'.

**Comment by geofreyflores** [comment]
Looking at built source (https://cdn.rawgit.com/angular-ui/ui-router/0.2.18/release/angular-ui-router.js) on line 3206, it looks like the call to findState is missing the base parameter (options.relative) to make it work (?)

`var reloadState = options.reload === true ? fromPath[0] : findState(options.reload, **options.relative**);`

**Comment by christopherthielen** [comment]
> e.g. given current state is 'parent', and 'parent.child' state exists:

What are you actually trying to do? If the state is currently `parent`, there is no need to reload `.child` since it's not currently entered

> `$state.go(".child", {}, {reload: '.child' })`
> `var reloadState = options.reload === true ? fromPath[0] : findState(options.reload, **options.relative**);`

Looks like we're doing that in 1.0: https://github.com/angular-ui/ui-router/blob/master/src/state/stateService.ts#L216

I'd merge a PR to `legacy` that includes a unit test

**Comment by geofreyflores** [comment]
Sorry, yeah, the example was a bit contrived and really didn't quite make sense. It was just simple enough to reproduce the problem.

The actual problem scenario for us was that we we're trying to refresh the child controller without refreshing the parent, and noticed that relative path to the child wasn't accepted. Since it's already fixed in 1.0, I'll mark this issue as closed.
