### ISSUE TITLE
Angular App - rewrite issue

### ISSUE THREAD

**Issue by rakeshreddysama** [angular-ui/ui-router#2872]
Have to remove # from angular app

1. I have 2 views (index.html and page1.html) in an angular application hosted on apache server
2. Created alias (apps-demo) pointing to the folder where the files are placed

url will be : https://servername/apps-demo
when i navigate to page1 it will be : https://servername/apps-demo/Page1
but when i reload page i get 404 not found
i have tried writing rewrite rule in .htaccess , ssl.conf (inside virtualhost)

![2016_07_13_16_31_19_c_users_rsama_desktop_sample_index html_notepad_administrator_](https://cloud.githubusercontent.com/assets/16396398/16801266/537fffe4-4917-11e6-87a3-ec7283ef81f9.png)

**Comment by danielneri-accesso** [comment]
Doesn't look like you are using UI Router, so this isn't the best place to post for help. Try StackOverflow for help setting up Angular URL rewriting.
