### ISSUE TITLE
ui-sref-active can only apply a class

### ISSUE THREAD

**Issue by thany** [angular-ui/ui-router#2878]
I'd like to be able to add/remove/alter an attribute as well. The use case is to add an `aria-selected` attribute and have it set to true/false depending on whether the view is selected or not. So, similar to `ui-sref-active` but for attributes.

This could perhaps work similar to `ng-attr-*`.

**Comment by dieguezz** [comment]
+1

**Comment by ronnyek** [comment]
I've too run into this problem today. I figured it'd be easy to model this directive off the existing UISrefActive, but its seeming like SrefStatus is something I cant inject into my external directive... has anyone been able to find a workaround for even if this element that has uiSref directive applied is current or anything like that?
