### ISSUE TITLE
redirectTo with state options.

### ISSUE THREAD

**Issue by wawyed** [angular-ui/ui-router#2881]
Reading through the documentation redirectTo allows you to pass a string with the state name, an object with state name and params and a TargetState. It would appear that in TargetState you can pass an options object but I don't really understand how to instantiate this class correctly. Could we get an example of it?

**Comment by wawyed** [comment]
I managed to achieve it by returning `transisiton.router.stateService.target(stateName, stateParams, stateOptions);` on the redirectTo function. It might be worth it adding this into the documentation.

**Comment by azharkhan** [comment]
@wawyed - this was very helpful! thank you for the initial direction. I was able to do it with the following syntax:

````
// from within redirectTo:

return { state: stateName, params: stateParams }
```
