### ISSUE TITLE
When two state URLs match, Angular tries to execute both

### ISSUE THREAD

**Issue by AndrewCraswell** [angular-ui/ui-router#2884]
I'm experiencing an odd issue. My team is using nested states to require a locale parameter on all states. However, what seems to be happening is that when we redirect the user to a 404 page using $state.go('404'), the 404 state executes, but then immediately after, Angular triggers the 'app.root' state as well. My belief is this is caused because the URL pattern for the 404 page technically matches the URL for the app.root state. But shouldn't it only execute one state?

```
$stateProvider
.state('app', {
    abstract: true,
    url: '/{locale}',
    template: '<ui-view/>',
    params: {
        locale: 'en-US'
    }
})

// Landing page
// https://example.com/en-US
.state('app.root', {
    url: '',
    templateUrl: '/Partials/Pages/Home',
})

// https://example.com/not-a-page
.state('404', {
    url: '*path',
    templateUrl: '/Partials/Pages/Error',
    controller: 'errorPageController',
});
```

**Comment by mbehjati** [comment]
May I ask what you did to solve this problem?
