### ISSUE TITLE
refreshing (F5) nested url not working

### ISSUE THREAD

**Issue by yaronmil** [angular-ui/ui-router#2885]
```
$urlRouterProvider.otherwise("/home");
		$stateProvider
			 state('page1',{
				url: "/page1",
				templateUrl: "page1.html"
			}).state('page1.subpage',{
				url: "/subpage",
				templateUrl: "SubPage.html"
			})
		 ;
		$locationProvider.html5Mode(true);
```

**Comment by imanzano** [comment]
Hi,

It happen the same to me with subpage and regular states. I just got a blank screen after refresh he page.

**Comment by christopherthielen** [comment]
If you're using html5 mode, make sure you have configured your *server* properly.

https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-your-server-to-work-with-html5mode

**Comment by yaronmil** [comment]
ok i find the solution
i replaced this line :
```
<head>
<script>document.write('<base href="'+document.location+'" />');</script>
</head>
```
with this
```
<head>
		<base href="@Url.Content("~")"/>
</head>
```
and my problam solved

**Comment by yaronmil** [comment]
ok i find the solution
i replaced this line :
```
<head>
<script>document.write('<base href="'+document.location+'" />');</script>
</head>
```
with this
```
<head>
		<base href="@Url.Content("~")"/>
</head>
```
and my problam solved

**Comment by kolkov** [comment]
@yaronmil is this correct tag?

`<base href="@Url.Content("~")"/>` I have a error with this!

**Comment by fcarvalllho** [comment]
I'm trying what @christopherthielen said. It's working perfectly when I don't use templateURL in my state, but when I use (and I will need it) I'm getting duplicate template.

With static template
`    var aboutState = {
        name: 'about',
        url: '/about',
        template: '<h3>Its the UI-Router hello world app!</h3>'
    }
    $stateProvider.state(aboutState);
`
https://imgur.com/sj9BpdN

With template URL

`
    var certificadoDeQualidade = {
        name: 'certificadoDeQualidade',
        url: '/certificadoDeQualidade',
        templateUrl: 'CertificadoDeQualidade/Index'
    }
    $stateProvider.state(certificadoDeQualidade);
`
https://imgur.com/PqKdYP1

full config:

```
var app = angular.module('app', [
    'ui.router'
]);


app.config(function ($stateProvider, $locationProvider) {
    $locationProvider.html5Mode(true);

    var certificadoDeQualidade = {
        name: 'certificadoDeQualidade',
        url: '/certificadoDeQualidade',
        templateUrl: 'CertificadoDeQualidade/Index'
    }

    var aboutState = {
        name: 'about',
        url: '/about',
        template: '<h3>Its the UI-Router hello world app!</h3>'
    }

    $stateProvider.state(certificadoDeQualidade);
    $stateProvider.state(aboutState);
});

```
