### ISSUE TITLE
Possibly unhandled rejection with Angular 1.5.9

### ISSUE THREAD

**Issue by skidvd** [angular-ui/ui-router#2889]
When using ui-router v-0.2.18 and angularjs v-1.5.9 I keep getting this error 4 times:

Possibly unhandled rejection: {}
I was not getting this error with 1.4.x angular verisons, but am now that I have upgraded.  Google searches are not turning up much related to this issue.

I also noticed this error shows up as soon as I insert the ui.router module.

**Comment by ave-sanket** [comment]
Same issue with me to using angular js v -1.5.9 and ui-router v-0.2.15.
Does reverting to 1.4.8 makes this go away?

**Comment by skidvd** [comment]
Yes, in my case I was a 1.4.2 before attempting the 1.5 upgrade.  Reverting to 1.4.x does make the error go away.

**Comment by lucax88x** [comment]
this can be linked to #2699 

anyway, a quick fix is to use this: 

https://docs.angularjs.org/api/ng/provider/$qProvider

in order to set errorOnUnhandledRejections to false

**Comment by skidvd** [comment]
@lucax88x, I attempting to apply the workaround you mentioned but not having any luck.  Likely, I'm not understanding what you intend for me to do.  Apologies if I am missing something obvious, but there does not appear to be useful examples of how to do this via google search.

I have modified my application's .run() function to call $q.errorOnUnhandledRejections(false);  However, it keeps telling me that errorOnUnhandledRejections is not a function.  Changing to .run() to literally set the value ($q.errorOnUnhandledRejections = false) succeeds (does not produce an error), but does not have any affect on the possibly unhandled rejection {} errors.  Is it nor possible to make this change globally in the application?  Do I need to do something to each and every time  I access $q?

TIA!

**Comment by DaniVarga** [comment]
try $qProvider.errorOnUnhandledRejections(false)

**Comment by skidvd** [comment]
@DaniVarga,

I'm sorry for the basic question, but I am missing something obvious.  I have tried to inject $qProvider in both the typical manner - `.run(['$qProvider', function($qProvider) {....}]);` as well as via the $injector

```
$injector.invoke(['$qProvider', function($qProvider) {
	$qProvider.errorOnUnhandledRejections(false);
}]);
```

Both approaches result in Unknown Provided $qProviderProvider errors.  Of course, without injecting a reference somehow, the $qProvider.errorOnUnhandledRejections(false) fails with an unknown $qProvider error.

I've also add 'ng' to my module list as well as attempted via the following approach, without success:

```
var $injector2 = window.angular.injector(['ng']);
$injector2.invoke(['$qProvider', function($qProvider) {
	$qProvider.errorOnUnhandledRejections(false);
}]);
```

How do I get a reference to this bad boy in my .run() function?

**Comment by christopherthielen** [comment]
Not .run(), but rather .config()

**Comment by skidvd** [comment]
@christopherthielen Of course, that makes more sense.  Thank you!

**Comment by didibanane** [comment]
Would like to know aswell if the 1.5.9 will have this error unless we don t set to false the errorOnUnhandledRejections

**Comment by akholodenko** [comment]
1.6.0-rc.0 has the same problem and is solved via the same workaround:

```
app.config(['$qProvider', function ($qProvider) {
	$qProvider.errorOnUnhandledRejections(false);
}]);
```

This error throwing should be off by default.

**Comment by christopherthielen** [comment]
This is fixed in 1.0 branch

**Comment by christopherthielen** [comment]
closed by 	66ab048

**Comment by cklemming** [comment]
I am getting this issue still with ui-router v-0.3.2 and angularjs v-1.6.0-rc.2. Specifically when closing modal dialogues.

**Comment by chmielciu** [comment]
Same here 1.6.0

**Comment by egamboa** [comment]
Same here 1.6.0

**Comment by gigmaps** [comment]
Same here 1.6.0

**Comment by yukw777** [comment]
Same here 1.6.0. Should be reopened.

**Comment by sirago** [comment]
1.6 - same issue

**Comment by amalleIntesens** [comment]
Same here 1.6.0

**Comment by brentlemons** [comment]
I just moved from 1.5.8 to 1.6.0 and ui-router#1.0.0-beta.3 resolves the issue.

**Comment by markkesty** [comment]
I am using 1.6.0 and ui-router#1.0.0-beta.3 but now whenever I go to a route, it urlencodes the route so instead of getting a#/b/c I get a#%2Fb%2Fc and the navigation fails

**Comment by arvindint** [comment]
[kkkk
]

**Comment by egamboa** [comment]
I got this error everytime I use .filter .forEach on some arrays.
`extraRiders = rider.riders.filter(function (extraRider) { return extraRider.check });`

as simple as this.

**Comment by zhangbg** [comment]
Same here 1.6.0

**Comment by freeman29** [comment]
Same here I'm using 1.6.0 and 1.0.0-beta.3. some of my modal are not working because of this issue.

**Comment by swlee60** [comment]
same here 1.6.0 and 0.3.2

**Comment by btk** [comment]
I had the same issue while using responsivevoice.js 3rd party app for those wants to track the problem.

https://gist.github.com/anchetaWern/ed6e841555602656e6ae

**Comment by arthurzwl** [comment]
Same here 1.6.0

**Comment by MrMonopol** [comment]
+1

**Comment by chaerf** [comment]
+1

**Comment by zakhttp** [comment]
+1 on  1.6.0, fixed it using the following workaround:
```
app.config(['$qProvider', function ($qProvider) {
            $qProvider.errorOnUnhandledRejections(false);
        }]);
```

**Comment by brentlemons** [comment]
To everyone still getting this error. If you are still getting this error, it is in your code or another module. Check @christopherthielen commit referenced above. ui-router is catching and silencing the rejection.

I ended up having more of these messages and ended up tracing them to errors in **my code**. Mainly trying to make an assignment to an array object that didn't exist. These are legit error messages. If you are using the method people are suggesting to turn off errorOnUnhandledRejections you are only masking a problem.

Do the right thing. Debug your code and find the root of the problem and fix it. Don't mask the problem.

**Comment by egamboa** [comment]
@brentlemons I got TY, that is how I was able to fix it, not really sure why it gave that error since the obj as initialize properly. I did a refactor of my .reduce and it work. So yeah maybe was something wrong. The big question is why is now starting to check this and is it something we should expect from now on? a linter in the ui-router? 😩

**Comment by markmssd** [comment]
@brentlemons You're right, my problem is that I was missing a catch() block on my promise, I've added it and the error is gone!

As a wise man once said: 

```
Do the right thing. Debug your code and find the root of the problem and fix it. Don't mask the problem.
  - Brent Lemons
```

Cheers!

**Comment by bradbird1990** [comment]
@zakhttp thanks for the fix, worked perfectly.

**Comment by christopherthielen** [comment]
@egamboa  
> The big question is why is now starting to check this and is it something we should expect from now on? a linter in the ui-router? 😩

This isn't a ui-router message.  This message appears any time a promise is rejected, and there was no `.catch()` handler.  

This is due to a change in angular's `$q` service which provides similar warnings as the native `Promise` implementation in most browsers: https://github.com/angular/angular.js/commit/c9dffde1cb167660120753181cb6d01dc1d1b3d0 It was merged into the 1.6 branch.


---

In ui-router 1.0 branch (`master`), I believe we've found and fixed all the uncaught(s).  The comment by @brentlemons suggests that moving to ui-router 1.0 eliminates the errors.  Because of that, I suspect there are yet uncaught promises created by ui-router legacy (0.3.2) that need to be found/caught.

> I just moved from 1.5.8 to 1.6.0 and ui-router#1.0.0-beta.3 resolves the issue.

**Comment by alejandroiglesias** [comment]
Just my 2 cents and not sure if this will help anybody, but I just incorrectly closed a bunch of HTML tags containing the `ui-view` directive and the error appeared.
Basically this caused the problem:
```
<div ui-view="viewName"></ui-view>
```
After fixing those occurrences, my app worked back and the "Possibly unhandled rejection" error disappeared.

**Comment by christopherthielen** [comment]
@alejandroiglesias thanks for the report.  I think you've discovered a different bug related to ui-view lifecycle (it's fixed in 1.0, IIRC).  Tracking at #3205

**Comment by rajeem** [comment]
I had this issue on version 1.6.0 when using $http and when there is an error in successCallback. For example is this code:

$http({
  method: 'GET',
  url: '/api/objects'
}).then(function successCallback(response) {
  $scope.data = data; //this will give error because 'data' is undefined, this should be 'response.data'
}, function errorCallback(response) {
});

**Comment by christopherthielen** [comment]
In case it's not clear: 
Any unhandled promise rejection will cause this error.  For example:

http://plnkr.co/edit/y0IWgSNOWP4WJmsWmfVF?p=preview

```html
<!DOCTYPE html>
<html>

  <head>
    <script src="//unpkg.com/angular@1.6.0/angular.js"></script>
  </head>

  <body ng-app="app">
    <h1>Hello Plunker!</h1>
    
    <script>
      angular.module('app', []).run(function($q) {
        $q.reject();
      })
    </script>
  
  </body>

</html>
```

**Comment by atom-morgan** [comment]
@christopherthielen What am I missing here? How should this rejection be handled? I'm seeing this in a project of mine as well (example [here](https://github.com/atom-morgan/scotch-angular-testing/blob/testing-part-two/app/components/profile/profile.spec.js#L112)) that was previously working but all instances of `$q.reject()` are now failing even though I'm catching the rejection.

**Comment by christopherthielen** [comment]
@atom-morgan here's how we're doing it in ui-router-core:
https://github.com/ui-router/core/blob/aa551e4252e784a49fda93865f1d1c03b4e36017/src/common/common.ts#L585-L588

```js
export const silenceUncaughtInPromise = (promise: Promise<any>) =>
    promise.catch(e => 0) && promise;
export const silentRejection = (error: any) =>
    silenceUncaughtInPromise(services.$q.reject(error));
```

To use: `silentRejection(RESPONSE_ERROR)` or `silentRejection($q.reject(RESPONSE_ERROR))`

**Comment by soorya02** [comment]
I have got the same error 'Possibly unhandled rejection' with Angular 1.5.8 and ui-router 0.2.18, fixed it  by adding .catch() block on my promise, the error is gone! thanks

**Comment by vip9** [comment]
ui-router 0.3.2, angular 1.6.0, "Possibly unhandled rejection" when using $resource (e.g. User.query().$promise) in resolve: state block.
How to fix it? "Where" to add .catch() block?

**Comment by markmssd** [comment]
```
var User = $resource('/user/:userId', {userId:'@id'});
User.get({userId:123}).$promise
    .then(function(user) {
      $scope.user = user;
    })
    .catch(function(error) {
      // handle error
    });
```

**Comment by christopherthielen** [comment]
http://plnkr.co/edit/bCjhJTTyw6yXuE4Ylr2C?p=preview

Reopening due to the question by @vip9 .  ui-router 0.3.2 needs to catch errors on rejected resolves.

**Comment by vinglfm** [comment]
ui-router 0.3.2, angular 1.6.0, "Possibly unhandled rejection" in unit tests, when using ngMock $interval.flush(). Due to using $urlRouterProvider.otherwise('/') in config. Without using otherwise, test pass.

**Comment by gabrielle-perez-movile** [comment]
+1 same issue here

**Comment by christopherthielen** [comment]
@vinglfm if you show me how to reproduce it, then I could fix it.

**Comment by egamboa** [comment]
@christopherthielen 
`var User = $resource('/user/:userId', {userId:'@id'});
User.get({userId:123}).$promise
    .then(function(user) {
      $scope.user = user;
    })
    .catch(function(error) {
      // handle error
    });`

to reproduce you basically skip the catch function, with that the 'errorOnUnhandledRejections' will thrown the exception. Which seems to me a little intrusive since maybe I don't want to handle the rejection and I don't want the UIRouter telling me to added.

For example the uiModal from bootstrap has promises to close and open and so on, these are also throwing the error if I don't handle the closing, which still very obvious not to handle it.

**Comment by christopherthielen** [comment]
> and I don't want the UIRouter telling me to added.

@egamboa Thanks for the example.  However, the message **is not coming from ui-router**.  It's a **core angular 1.6 message**.  

There are some places that ui-router should be calling `.catch()` on promises that are passed to it, but currently isn't.  The only place that I know of currently is that ui-router is at fault is in the resolve system.

**Comment by egamboa** [comment]
@christopherthielen ok even if is the core, is weird to have a check like that.
is like a Catch them all! idea.

**Comment by christopherthielen** [comment]
It's the new normal.  Even native promises in the browsers are doing this.

<img width="611" alt="screen shot 2016-12-23 at 11 59 23 am" src="https://cloud.githubusercontent.com/assets/2053478/21459818/5448118a-c907-11e6-912c-3dd11a4eea39.png">

**Comment by egamboa** [comment]
Well sounds good enough for me. Ty @christopherthielen 
... *flies away* ...

**Comment by alejandroiglesias** [comment]
I would suggest to all facing this issue to update to Angular 1.6.1 and see if you get errors that make more sense due to a change introduced in that version (`$q: Add traceback to unhandled promise rejections (174cb4 #14631)`).
I was getting many `Possibly unhandled rejection: {}` and after updating to 1.6.1 the errors changed and I could see the actual issue.

**Comment by lee-zhi** [comment]
angular 1.6.0  'Possibly unhandled rejection: {}' ,when using $http.jsonp(). 

<code>$http.jsonp('http://127.0.0.1:3030/vit', {jsonpCallbackParam: 'callback'}).then(function(res){})</code>

I have added $qProvider.errorOnUnhandledRejections(false), but it's just hide the message.

**Comment by christopherthielen** [comment]
Locked to avoid +1 noise

**Comment by christopherthielen** [comment]
> There are some places that ui-router should be calling .catch() on promises that are passed to it, but currently isn't. The only place that I currently know of (where ui-router is at fault) is in the resolve system.

In f2910e9 we're now calling `.catch(function() {})` on the transition promise.  I believe this will address all the remaining cases of "Possibly unhandled rejection" _that are UI-Router's fault_.

Will release 0.4.0 soon.

**Comment by christopherthielen** [comment]
Fixed by f2910e9b00ebcf652abab2af8a405b5b5fbca054 in 0.4.0

**Comment by christopherthielen** [comment]
# How to determine where an unhandled rejection comes from

In angular 1.6.0 any rejected promise that doesn't have an error handler (`.catch(handler)` or `.then(success, error)`) chained off it will print this error message (note: this isn't related to UI-Router code).  In Angular 1.6.1 the rejected promise message is properly printed to the console.  However, it can be difficult to follow the promise chains all the way through your app.

# Decorate `$q`

You can decorate the `$q` service (I recommend this for DEBUGING ONLY as this could reduce promise performance dramatically).  When a new promise is created, angular creates a `new Promise()` (where `Promise` is an internal angular object, not a native ES6 Promise).  The Promise constructor function [sets up some internal state](https://github.com/angular/angular.js/blob/eba7c28261ff9a80d68e4ddf82e9fad7a112eb1b/src/ng/q.js#L315-L317) which we can use to our benefit.

Whenever a new promise is created, add a stacktrace to it by hijacking the `$$state` initializer and replacing it with a setter:

```
// Decorate the $q service when app starts
app.decorator('$q', ["$delegate", function($delegate) {
  // Create a new promise object
  var promise = $delegate.when();

  // Access the `Promise` prototype (nonstandard, but works in Chrome)
  var proto = promise.__proto__;

  // Define a setter for `$$state` that creates a stacktrace 
  // (string) and assigns it as a property of the internal `$$state` object.
  Object.defineProperty(proto, '$$state', {
    enumerable: true,
    set: function(val) {
      val.stack = new Error().stack;
      this._$$state = val;
    },
    get: function() {
      return this._$$state;
    }
  });

  return $delegate;
}]);
```

Now, every promise will have a stack trace associated with it.  The stack trace is filled in when the promise is created (note: new `Promise`s are created when calling methods like `.then()`).  When angular complains about a possibly unhandled rejection, stick a breakpoint in the `angularjs` code that logs the error.

```js
  function processChecks() {
    // eslint-disable-next-line no-unmodified-loop-condition
    while (!queueSize && checkQueue.length) {
      var toCheck = checkQueue.shift();
      if (!toCheck.pur) { // PUT A BREAKPOINT HERE!
        toCheck.pur = true;
        var errorMessage = 'Possibly unhandled rejection: ' + toDebugString(toCheck.value);
        if (toCheck.value instanceof Error) {
          exceptionHandler(toCheck.value, errorMessage);
        } else {
          exceptionHandler(errorMessage);
        }
      }
    }
  }
```

While you are paused on the breakpoint, print out the value of `toCheck.stack` to find out where the promise with the unhandled rejection was created (in the example below, in the `conflictInterceptor`)

![screen shot 2017-01-19 at 6 44 36 pm](https://cloud.githubusercontent.com/assets/2053478/22131245/8492d796-de77-11e6-8341-9059f787b9fc.png)

**Comment by christopherthielen** [comment]
f73e551 fixes (in f73e551) another missed rejection that was ui-router's fault.
released version `0.4.1`

**Comment by coder477** [comment]
seeing the issue again with angular 1.6.3 and ui router 0.4.2

**Comment by AdrienDC** [comment]
same here

**Comment by gorakhargosh** [comment]
> Do the right thing. Debug your code and find the root of the problem and fix it. Don't mask the problem. 
> - Brent Lemons

rm -rf angular.js

**Comment by christopherthielen** [comment]
See also: https://github.com/angular-ui/ui-router/issues/3404

**Comment by christopherthielen** [comment]
1.0.4 is released

**Comment by AdrienDC** [comment]
Got some errors with 1.x.x: [object Object], <ion-nav-view class="view-container" nav-view-transition="none">

**Comment by divisble** [comment]
@christopherthielen 
I'm using Angular 1.6.1 and i updated angular-ui-router to 1.0.4 but I still have "possibly unhandled rejection". 

Could someone confirm that, 1.0.4 fix this problem ?
Hiding errors with errorOnUnhandledRejections() func isn't best solution....

**Comment by aphairpq** [comment]
We are seeing this issue Angular 1.6.4 and angular-ui-router 1.0.4. I've been trying to hunt down any unhandled rejections on our end, but it seems to be getting rejected somewhere in the transition.

See the following log/trace:
![image](https://user-images.githubusercontent.com/28264827/27647914-ea89c46e-5bfa-11e7-9d03-e3f1cda2b1d7.png)


Our onStart hook is basically checking if a user is authenticated or not. If not, it should redirect them to the login page (really simplified below):

```
$transitions.onStart({}, function(trans){
    if(needsAuthentication){
        return $state.target('login');
    }
});
```

**Comment by o-panikarovskiy** [comment]
`$provide.decorator("$exceptionHandler", ["$delegate", "$window", function ($delegate, $window) {
            return function (exception, cause) {
                if (!cause) return; //do nothing (ignore) exception in this case === 'Possibly unhandled rejection: undefined'               
               $delegate(exception, cause);
            };
}]);`

works for me.

**Comment by AnalyzePlatypus** [comment]
Getting hit by this on Angular 1.6.4 and UI-Router 1.0.4 when closing instances of `uib-modal`.
Specifically, I'm getting the error:
`Possibly unhandled rejection: backdrop click`
I'm investigating; will post results

**Comment by andreaslarssen** [comment]
Got the exact same issue as you, @aphairpq. Did you figure it out?

**Comment by andreaslarssen** [comment]
Got the same block as @aphairpq:

```
$transitions.onStart({to: 'authentication.login'}, function (trans) {
      var $auth = trans.injector().get('$auth');
      var $state = trans.router.stateService;

      if ($auth.isAuthenticated()) {
        return $state.target('user.settings.profile');
      }
    });
```

It throws the "Possibly unhandled rejection: {"$id":0,"type":2,"message":"The transition has been superseded by a different transition"...... error

Followed the q decorator tip above to get the trace, and toCheck.stack shows:

```
"Error
    at Promise.set [as $$state] (http://localhost:9000/scripts/qDecorator.js:17:21)
    at new Promise (http://localhost:9000/bower_components/angular/angular.js:16789:18)
    at Promise.then (http://localhost:9000/bower_components/angular/angular.js:16797:20)
    at Promise.finally (http://localhost:9000/bower_components/angular/angular.js:16811:19)
    at http://localhost:9000/scripts/config/ui-router.js:70:28
    at invokeCallback (http://localhost:9000/bower_components/angular-ui-router/release/angular-ui-router.js:1545:34)
    at TransitionHook.invokeHook (http://localhost:9000/bower_components/angular-ui-router/release/angular-ui-router.js:1557:26)
    at http://localhost:9000/bower_components/angular-ui-router/release/angular-ui-router.js:1649:60
    at processQueue (http://localhost:9000/bower_components/angular/angular.js:16832:37)
    at http://localhost:9000/bower_components/angular/angular.js:16876:27"
```

According to the [docs](https://ui-router.github.io/ng1/docs/latest/modules/transition.html#hookresult), returning a target state, the router should redirect, and it does. It's just that annoying error message floods the console every time. Even tried to return a promise, just for the hell of it. Same result:

```
$transitions.onStart({to: 'authentication.login'}, function (trans) {
      var $auth = trans.injector().get('$auth');
      var $state = trans.router.stateService;

      if ($auth.isAuthenticated()) {
        var $q = trans.injector().get('$q');
        var def = $q.defer();
        def.resolve($state.target('user.settings.profile'));
        return def.promise;
      }
    });
```

I can't see that there are other state's being initiated, no other hooks are in play and generally nothing to indicate that this should not work.

Silencing the errors is not an option. 

ui-router 1.0.6
angular 1.6.4

**Comment by tiagomsmagalhaes** [comment]
I think I also have a similar issue as @aphairpq and @andreaslarssen 
```
runtimeFunction.$inject = ['$transitions', '$trace', 'AuthService'];
  function runtimeFunction($transitions, $trace, AuthService) {
    $trace.enable('TRANSITION');
    $transitions.onStart( { to: 'dashboard' }, function(trans) {
      var $state      = trans.router.stateService;
      var AuthService = trans.injector().get('AuthService');

      AuthService.getUserStatus().then(function (res) {if (!res.data.status) $state.transitionTo("index")})
    });

  }
/*

Log
Transition #0-0: Started  -> "Transition#0( ''{} -> 'dashboard'{} )"
trace.ts:153 Transition #1-0: Started  -> "Transition#1( ''{} -> 'index'{} )"
trace.ts:192 Transition #0-0: <- Rejected "Transition#0( ''{} -> 'dashboard'{} )", reason: Transition Rejection($id: 0 type: 2, message: The transition has been superseded by a different transition, detail: Transition#1( ''{} -> 'index'{} ))
stateService.ts:525 Transition Rejection($id: 0 type: 2, message: The transition has been superseded by a different transition, detail: Transition#1( ''{} -> 'index'{} ))
_defaultErrorHandler @ stateService.ts:525
(anonymous) @ stateService.ts:365
processQueue @ angular.js:17000
(anonymous) @ angular.js:17044
$digest @ angular.js:18182
$apply @ angular.js:18480
done @ angular.js:12501
completeRequest @ angular.js:12727
requestLoaded @ angular.js:12655
XMLHttpRequest.send (async)
(anonymous) @ angular.js:12701
sendReq @ angular.js:12446
serverRequest @ angular.js:12198
processQueue @ angular.js:17000
(anonymous) @ angular.js:17044
$digest @ angular.js:18182
$apply @ angular.js:18480
bootstrapApply @ angular.js:1952
invoke @ angular.js:5040
doBootstrap @ angular.js:1950
bootstrap @ angular.js:1970
angularInit @ angular.js:1855
(anonymous) @ angular.js:33826
trigger @ angular.js:3468
trace.ts:198 Transition #1-0: <- Success  "Transition#1( ''{} -> 'index'{} )", final state: index
```


I enabled to trace with the decorator made by @christopherthielen I'm not seing the issue. 

I have angular 1.6.5 and ui-router 1.0.3

**Comment by andreaslarssen** [comment]
Do you have some wisdom to share, @christopherthielen?

**Comment by christopherthielen** [comment]
@aphairpq this is a very late response, but I was unable to reproduce your scenario as described:

http://plnkr.co/edit/JAuapA2wtq7vd72imizF?p=preview

**Comment by christopherthielen** [comment]
@andreaslarssen what is defined in the hook inside `http://localhost:9000/scripts/config/ui-router.js:70:28`?   

Your stack trace suggests that the `.catch` block should be added somewhere inside that finally handler. 

```
    at Promise.set [as $$state] (http://localhost:9000/scripts/qDecorator.js:17:21)
    at new Promise (http://localhost:9000/bower_components/angular/angular.js:16789:18)
    at Promise.then (http://localhost:9000/bower_components/angular/angular.js:16797:20)
    at Promise.finally (http://localhost:9000/bower_components/angular/angular.js:16811:19)
    at http://localhost:9000/scripts/config/ui-router.js:70:28
```

**Comment by christopherthielen** [comment]
@tiagomsmagalhaes try using a redirect instead:

```
  runtimeFunction.$inject = ['$transitions', '$trace', 'AuthService'];
  function runtimeFunction($transitions, $trace, AuthService) {
    $trace.enable('TRANSITION');
    $transitions.onStart( { to: 'dashboard' }, function(trans) {
      var $state      = trans.router.stateService;
      var AuthService = trans.injector().get('AuthService');

      return AuthService.getUserStatus()
        .then(function (res) {
          if (!res.data.status) 
            return $state.target("index");
         }})
    });
  }
```

**Comment by christopherthielen** [comment]
I updated the q decorator such that it prints out the unhandled rejections stack traces to the console.  It only works if you are *not using minification* (because it parses the stack traces).  Also I only tried it with Chrome.

```ts
// Decorate the $q service when app starts
.decorator('$q', ['$delegate', function($delegate: IQService) {
  // Create a sample promise.
  const promise = $delegate.when();

  // Access the `Promise` prototype (nonstandard, but works)
  const promisePrototoype = (promise as any).__proto__;
  const isPromisePrototype = typeof promisePrototoype === 'object' &&
    ['then', 'catch', 'finally'].every(key => !!promisePrototoype[key]);

  if (isPromisePrototype) {
    // The angular $q promise implementation sets `$$state` once in its Promise constructor:
    //
    // function Promise() {
    //   this.$$state = { status: 0 };
    // }
    //
    // Hijack the promise behavior by adding a setter for `$$state` on the Promise prototype.
    // The setter is run each time a promise is created (via any method: $q.when(), promise.then(), etc).
    //
    // The setter records the stack trace in which the promise was created.
    Object.defineProperty(promisePrototoype, '$$state', {
      set: function($$state) {
        this._$$state = $$state;

        if (typeof $$state._status === 'undefined') {
          this._value = this.value;

          // Define a getter for `Promise.$$state.value`
          // ('value' is the resolved or rejected value)
          Object.defineProperty($$state, 'value', {
            enumerable: true,
            set: function(val) {
              this._value = val;
            },
            get: function() {
              // Check if this is the "Possibly unhandled rejection" handler. return the stack trace instead
              if (this.status === 2 && this.pur && new Error().stack.includes('processChecks')) {
                return this._context;
              }
              return this._value;
            },
          });
        }

        // Create an Error object and use its stack trace
        $$state._context = new Error('Possibly unhandled rejection (promise creation stack)');
        // But skip the first two stack frames
        const [errMessage, , , ...stackframes] = $$state._context.stack.split(/[\r\n]/);
        $$state._context.stack = [errMessage, ...stackframes].join('\n');
      },
      get: function() {
        return this._$$state;
      },
      enumerable: true,
    });

    // Whenever promise.then() (or .catch or .finally) is called, a new promise is created.
    // Add the chained-from-promise's stack to the new promise's stack to allow analysis of the full promise chain
    const realThenFn = promisePrototoype.then;
    promisePrototoype.then = function() {
      const chainedPromise = realThenFn.apply(this, arguments);

      const prevContext = this.$$state && this.$$state._context;
      const chainedContext = chainedPromise.$$state && chainedPromise.$$state._context;

      if (chainedContext) {
        try {
          chainedContext.stack = chainedContext.stack + '\nPromise Chained from:\n' + prevContext.stack;
        } catch (ignored) {}
      }
      return chainedPromise;
    }
  }

  return $delegate;
}]);
```

**Comment by andreaslarssen** [comment]
@christopherthielen: Holy cow, you're right! Was using the finally handler to remove a loading screen. One error to go.

Good catch (pun intended), thanks!

**Comment by yosiasz** [comment]
This was my issue in case it helps someone else. It had nothing to do with ui-router, well at least as far as I can see, maybe a red herring.

```    angular
        .module('app.risk')
        .run(appRun);

    /* @ngInject */
    function appRun(routerHelper) {
        routerHelper.configureStates(getStates());
    }

    function getStates() {```

I had another method called getStates and there was collision with this getStates router. :(

**Comment by adamreisnz** [comment]
> // The angular $q promise implementation sets `$$state` once in its Promise **varructor**:

Just wanted to highlight this gem of a find & replace (`const` to `var`), _varructor_ 😆
