### ISSUE TITLE
Any way to remove the transition hook?

### ISSUE THREAD

**Issue by nightspirit** [angular-ui/ui-router#2893]
I call $transitions.onStart(...) in one component. Wondering if I can unregister the hook when component being destroyed. (Don't want to do this all in the run function)

**Comment by christopherthielen** [comment]
Yep, the return value of `onStart()` is a hook de-registration function

Its mentioned at the very bottom of https://ui-router.github.io/docs/latest/classes/transition.transitionservice.html#onstart

> Returns Function : a function which deregisters the hook.

**Comment by nightspirit** [comment]
Thank you very much :)

**Comment by ViieeS** [comment]
Also can use `invokeLimit` option

`onStart(matchCriteria: HookMatchCriteria, callback: TransitionHookFn, options?: HookRegOptions): Function`

https://ui-router.github.io/ng1/docs/latest/interfaces/transition.hookregoptions.html#invokelimit
