### ISSUE TITLE
路由嵌套引起的重复http请求

### ISSUE THREAD

**Issue by zilinxueyue** [angular-ui/ui-router#2895]
Hi，
    when I used the ui-router manage my pages. I encounter an issue. I have first page "home.html" put into the "indexview". in the homt.html page I have another "homecontentview". I configed "home.detail" in the router and put "detail.html"  into "homecontentview". 
    In one word detail page is the child page of home page. Now I use ui-serf="home.detail" link to detail page. But when I debug in chrome I found some of the http request have been send out(these request defind in the home page controller). 
     My question is "Is there any way can stop this?" I only want send the request which I defined at detail controller.(Don't send the home page contrller request )

   Thanks!

**Comment by zilinxueyue** [comment]
I found the issue caused by the one ui-view have 2 collateral controller. now I change delete one of them and conbine then in one controller issue solved.

**Comment by christopherthielen** [comment]
Looks like you figured it out.  

---

One other thing:

If you want to send HTTP requests when a state (for instance, `home.detail`) is activated, you might want to use a `resolve:` block.
