### ISSUE TITLE
Controller not instantiated if not defined inside views

### ISSUE THREAD

**Issue by antucg** [angular-ui/ui-router#2897]
Hi guys I have a question with regards to the state definition. If I create a state like this:

`.state('logout', {
      name: 'logout',
      url: '/logout',
      template: '<h1>logout</h1>',
      controller: function() {
          alert("bah");
      }
});`

The controller is not executed.

Whereas if I create it like this:

`.state('logout', {
      name: 'logout',
      url: '/logout',
      views: {
        'master': {
          template: '<h1>logout</h1>',
          controller: function() {
            alert("bah");
          }
        }
      }`

It seems to be ok. I am using the latest beta version of the ui-router. Is this a change on the library or am I doing something wrong?

**Comment by ian-gallagher** [comment]
My understanding is that a controller must be specified at the individual view level not at the state definition level.

**Comment by mattscherzer** [comment]
Any comment on this?
