### ISSUE TITLE
How to preserve the original href after the launch of the ui-router?

### ISSUE THREAD

**Issue by cawa-93** [angular-ui/ui-router#2899]
I create browser-based extension.
In the pop-up window there is a link:

``` html
<a ui-sref="list" href="https://example.com/list">List</a>
```

The problem is that if a user opens this link in a new tab will open my popup expansion in a new tab:

```
chrome-extension://ebapjgoekpb/PopupApp/popup.html#/list
```

There is a way to save the plugin functionality, and the original link, so that when you try to open a link in the same window breakdowns ui-router but when you try open a link in a new window opened my site?

**Comment by arjunnayak0705** [comment]
@cawa-93 Please read this documentation 
https://github.com/angular-ui/ui-router/wiki/Quick-Reference#ui-sref
