### ISSUE TITLE
Resolutions not being resolved in `controllerProvider` inside named view

### ISSUE THREAD

**Issue by msbit** [angular-ui/ui-router#2901]
When providing a resolution via `resolve` inside a named view, the injected argument to `controllerProvider` is the unresolved value.

For example, in the following code:

```
angular.module('angular-provider-resolve', ['ui.router'])

.config(function($stateProvider, $urlRouterProvider) {
  $stateProvider
  .state('default', {
    url: '/default',
    views: {
      'default': {
        resolve: {
          resolution: function($q) {
            return $q.when('resolution');
          }   
        },  
        controllerProvider: function(resolution) {
          console.log('controllerProvider', resolution);
          return function($scope) {
            $scope.resolution = resolution;
          };  
        },  
        template: 'Resolution is {{ resolution }}'
      }   
    }   
  }); 

  $urlRouterProvider.otherwise('/default');
});
```

I would expect to see `controllerProvider resolution` on the console, and `Resolution is resolution` displayed in the view.

Instead, I see:

```
controllerProvider function ($q) {
            return $q.when('resolution');
          }
```

on the console, and `Resolution is` on the view.

Plnkr at:

http://plnkr.co/edit/trzsGlp2n3v8Ta46Dbyh / http://run.plnkr.co/bdo8YTqYnFRRF4tM/#/default

**Comment by christopherthielen** [comment]
resolve is a property of `state`, not `view`.

See https://github.com/angular-ui/ui-router/issues/2902#issuecomment-238363998

http://plnkr.co/edit/QgvYZ5fq3zNuWJL3wcmG?p=preview
