### ISSUE TITLE
Resolutions not being injected in `templateProvider` inside named view

### ISSUE THREAD

**Issue by msbit** [angular-ui/ui-router#2902]
When providing a resolution via `resolve` inside a named view, the resolution is not injected into `templateProvider`.

For example, in the following:

```
var app = angular.module('demonstrateissue', ['ui.router']);

app.config(function($stateProvider, $urlRouterProvider) {
  $stateProvider
  .state('default', {
    url: '/default',
    views: {
      'default': {
        resolve: {
          resolution: function($q) {
            return $q.when('resolution');
          }   
        },  
        controller: function($scope, resolution) {
          $scope.resolution = resolution;
        },  
        templateProvider: function(resolution) {
          console.log('templateProvider', resolution);
          return 'Resolution is {{ resolution }}';
        }   
      }   
    }   
  }); 

  $urlRouterProvider.otherwise('/default');
})

.run(function($rootScope) {
  $rootScope.$on('$stateChangeError', function (event, toState, toParams, fromState, fromParams, error) {
    console.log('$stateChangeError', error);
  }); 
});
```

I would expect to see `templateProvider resolution` on the console. Instead, the state change fires an error and I get `$stateChangeError Error: [$injector:unpr] Unknown provider: resolutionProvider <- resolution(…)`

Plnkr showing this issue at http://plnkr.co/edit/IM91FsI47Gk2XAD7YTwO

**Comment by christopherthielen** [comment]
Hi, thanks for the plunker reproduction!

`resolve` is a property of a *state*, not the *views*

Here's the working plunker: http://plnkr.co/edit/cax4i16xgV0xdVPuwjnk?p=preview

**Comment by msbit** [comment]
@christopherthielen thanks for the clarification.

My use case is an attempt to get separate resolutions injected, each tailored to a specific view, reusing the same `controller`, (or `controllerProvider` as required).

Is there a mechanism to do this, in a view's configuration?
