### ISSUE TITLE
Issue with ui-sref-active and nested states

### ISSUE THREAD

**Issue by adamk33n3r** [angular-ui/ui-router#2908]
In the case of a state hierarchy like `parent -> child -> [grandchild1, grandchild2]` if you call `$state.go('.grandchild2')` in the child controller and you navigate directly to `parent.child` the `ui-sref-active` for the grandchild is NOT activated. If, however, you call `$state.go('.child.grandchild2')` in the parent controller and you navigate directly to `parent` the `ui-sref-active` for the grandchild IS activated.

This issue is not present in `v0.3.1`.

In the plunker you can test the different flows by commenting/uncommenting the `go` calls in the controllers and clicking on the appropriate links. I also included a commented out script reference in `index.html` to `v0.3.1` so you can see that it used to work.

One thing I found is that if you wrap the `$state.go` call in the child controller with a timeout it works as expected.

Plunker: http://plnkr.co/jQ5ynztNFTppQeUEkeoO/

**Comment by christopherthielen** [comment]
Thanks, definitely looks like a regression in 1.0
