### ISSUE TITLE
Parameter value with % is encoded with %25 in URL

### ISSUE THREAD

**Issue by Dhineshin** [angular-ui/ui-router#2911]
Lets say I have a parameter value "Hi&There".  
After doing encodeURIComponent("Hi&There") the value changes to "Hi%26There"

After doing $state.go(....), I find the in the URL like mydomain/app/blahblah/Hi%2526There.

Issue: the percentage sign (%) is auto encoded again while changing the state.

**Comment by christopherthielen** [comment]
can you post a plunker which reproduces this issue?

http://bit.ly/UIR-Plunk
