### ISSUE TITLE
ui-router-ng2: Injecting UIRouter into component seems to break routes

### ISSUE THREAD

**Issue by jspizziri** [angular-ui/ui-router#2913]
I had a component in which I desired to call `router.stateService.go('bar')` from a component method (this is my understanding of the correct way to do this with ui-router-ng2). However, whenever I inject UIRouter into my component all the routes break.

```ts
import {Component} from '@angular/core';
import {UIROUTER_DIRECTIVES, UIRouter} from 'ui-router-ng2';

@Component({
  selector: 'foo',
  template: `
    <a uiSref="bar">Bar Link</a> 
    <br/>
    <a (click)="goToFooBar()">Bar Click</a>
  `,
  directives: [UIROUTER_DIRECTIVES],
  providers: [UIRouter],
})
export default class FooComponent {

  constructor(private router: UIRouter) { }

  goToFooBar() {
      this.router.stateService.go('bar');
  }
}
```

The `bar` state [generates an `href` of `null`](https://github.com/angular-ui/ui-router/issues/2912). In the case of the `uiSref` link, upon clicking the link the app redirects to `http://localhost/null` rather than transitioning successfully to the correct route.

Additionally, the link which calls `stateService.go` generates the following error upon attempting to transition:

```
EXCEPTION: Error in ./FooComponent class FooComponent - inline template:0:260
2016-08-10 13:24:45.337 zone.js?fad3:260 Uncaught EXCEPTION: Error in ./FooComponent class FooComponent - inline template:0:260
ORIGINAL EXCEPTION: TypeError: Cannot read property 'map' of undefined
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'map' of undefined
    at new PathNode (eval at <anonymous> (http://localhost:3001/index.js:936:2), <anonymous>:27:49)
    at rootPath (eval at <anonymous> (http://localhost:3001/index.js:943:2), <anonymous>:285:46)
    at StateService.transitionTo (eval at <anonymous> (http://localhost:3001/index.js:943:2), <anonymous>:286:76)
    at StateService.go (eval at <anonymous> (http://localhost:3001/index.js:943:2), <anonymous>:219:21)
    at FooComponent.afterSubmit (eval at <anonymous> (http://localhost:3001/index.js:3577:2), <anonymous>:31:38)
    at DebugAppView._View_FooComponent0._handle_click_12_0 (FooComponent.template.js:143:28)
    at eval (eval at <anonymous> (http://localhost:3001/index.js:2780:2), <anonymous>:375:24)
    at eval (eval at <anonymous> (http://localhost:3001/index.js:887:2), <anonymous>:254:36)
    at eval (eval at <anonymous> (http://localhost:3001/index.js:1419:2), <anonymous>:27:111)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:3001/index.js:2374:2), <anonymous>:323:29)
ERROR CONTEXT:
[object Object]Zone.runTask @ zone.js?fad3:260ZoneTask.invoke @ zone.js?fad3:423
```

Is this a potential bug? Or am I simply doing something incorrectly?

Thanks in advance!

**Comment by christopherthielen** [comment]
The `UIRouter` instance is already provided, so your problem probably arises from this:

```js
  providers: [UIRouter],
```

Alternatively, you can inject the `StateService` directly:

```js
import {UIROUTER_DIRECTIVES, StateService} from 'ui-router-ng2';

...
  constructor(private stateService: StateService) { }
...
```

Or the `Transition`, which has the `router` instance on it:

```js
import {UIROUTER_DIRECTIVES, Transition} from 'ui-router-ng2';

...
  constructor(trans: Transition) { 
    this.$state = trans.router.stateService;
  }
...
```

**Comment by christopherthielen** [comment]
> The bar state generates an href of null. In the case of the uiSref link, upon clicking the link the app redirects to http://localhost/null rather than transitioning successfully to the correct route.

That's surprising.  The click handler of the `uiSref` should stop the 'href' from being processed.

**Comment by jspizziri** [comment]
You're right, double declaring a provider for UIRouter was causing the issue.

Thank you for clarifying!

**Comment by vivekamin** [comment]
`/** imports */

import {NgModule, Component} from '@angular/core';
import {UIRouterModule ,UIROUTER_DIRECTIVES, StateService} from "ui-router-ng2";
import {BrowserModule} from "@angular/platform-browser";
import {platformBrowserDynamic} from '@angular/platform-browser-dynamic';

/** Components */

@Component({
  selector: 'my-app',
  template: `
  <a  (click)="hello()" uiSrefActive="active">Hello</a>
  <a uiSref="about" uiSrefActive="active">About</a>
  
  <ui-view></ui-view>
  `
})
export class App { 
  
  hello(private stateService: StateService)
  {
    console.log("hello Clicked");
    StateService.go('hello');
    
  }
  
}

@Component({  
  template: '<h3>Hello world!</h3>' 
})
class Hello { }

@Component({ 
  template: '<h3>Its the UI-Router hello world app!</h3>' 
})
class About { }


/** States */

let helloState = { name: 'hello', url: '/hello',  component: Hello }; 
let aboutState = { name: 'about', url: '/about',  component: About };

/** Root Application NgModule */

@NgModule({
  imports: [ 
    BrowserModule,
    UIRouterModule.forRoot({ states: [ helloState, aboutState ], useHash: true })
  ],
  declarations: [ App, Hello, About ],
  bootstrap: [ App ]
})
class RootAppModule {}

/** Angular 2 bootstrap */

platformBrowserDynamic().bootstrapModule(RootAppModule);`


Giving me error : ui_router_ng2_1.StateService.go is not a function
