### ISSUE TITLE
Resolve for views returning functions instead of function return values

### ISSUE THREAD

**Issue by rahatarmanahmed** [angular-ui/ui-router#2916]
[Plunkr Example](http://embed.plnkr.co/v75IMRWxdB43PRjTo6mm/)

If you provide some thing in `resolve` for a particular view in a state, and you give a function to determine what that thing should resolve to, what actually gets injected is the function itself rather than what it returns. At least so i've tested in `controllerProvider`

``` javascript
$stateProvider
        .state('index', {
            url: "",
            views: {
                "viewA": {
                    resolve: {
                      thingy: function() {
                        return 'abc';
                      }
                    },
                    controllerProvider: function(thingy) {
                      // Expect thingy to be 'abc', but is the thingy function above instead
                      console.log(thingy);
                      debugger;
                    },
                    template: "index.viewA"
                },

            }
        })
    })
```

**Comment by bfricka** [comment]
Well, that's a `controllerProvider`. It'll work if you change to `controller` instead.

**Comment by rahatarmanahmed** [comment]
True but it'll also work if I move the resolve outside the view to the root
of the state object. It's just inconsistent and doesn't seem like intended
behavior, so I thought I'd report it.

**Comment by christopherthielen** [comment]
`resolve` is not a property of a view; it is only valid as a property of a state object.  

I believe in later versions of ui-router, we stopped processing view.resolve at all.  The correct thing to do is move the `resolve` definition up to the state object.

This is a common misconception, but I don't understand where it comes from. As far as I know,  `resolve` on a view is not documented anywhere.  To help me understand, why did you think `resolve` is valid on a view?

**Comment by rahatarmanahmed** [comment]
I put resolve on the view purely by accident. The fact that it did anything
at all made me assume it was supported, but yeah I didn't see any
documentation.

I guess the real bug here is that resolve on a view is incorrectly
injecting stuff.
