### ISSUE TITLE
uiCanExit: loops while rejecting with false

### ISSUE THREAD

**Issue by varnastadeus** [angular-ui/ui-router#2917]
I am using uiCanExit to notify user when he is leaving state with unsaved changes.

Prompt either resolves with true or rejects with false.
When resolving with true, everything works as expected.

Rejecting with false, triggers uiCanExit again, and if I keep rejecting it loops infinitely.

``` javascript
uiCanExit(transition): any {
       if (hasChanges) {
            return showPrompt().then(() => {
                return true;
            }, () => {
                return false;
            });
```

``` 
First transition with reject: 

Transition #4 Digest #83: Started  -> "Transition#4( 'app.log.list.details'{"query":"paid","ref":"DYPHEI6","tab":"price"} -> 'app.log.list.details'{"query":"paid","ref":"DYPGVU6","tab":"price"} )"

Transition #4 Digest #88: <- Rejected "Transition#4( 'app.log.list.details'{"query":"paid","ref":"DYPHEI6","tab":"price"} -> 'app.log.list.details'{"query":"paid","ref":"DYPGVU6","tab":"price"} )", reason: TransitionRejection(type: 3, message: The transition has been aborted., detail: Hook aborted transition)

Keeps looping here:

Transition #5 Digest #88: Started  -> "Transition#5( 'app.log.list.details'{"query":"paid","ref":"DYPHEI6","tab":"price"} -> 'app.log.list'{"query":"paid"} )"

Transition #6 Digest #88: Started  -> "Transition#6( 'app.log.list.details'{"query":"paid","ref":"DYPHEI6","tab":"price"} -> 'app.log.list'{"query":"paid"} )"

...
```

If I return false without promise, it stops the loop :
``` javascript
uiCanExit(transition): any {
       if (hasChanges) {

            if (transition loops) {
                return false; //transition loop stops
            }

            return showPrompt().then(() => {
                return true;
            }, () => {
                return false;
            });
```

**Comment by christopherthielen** [comment]
Interesting.  How did you trigger the transition? Was it with a ui-sref, $state.go(), or url synchronize?

**Comment by varnastadeus** [comment]
I am using $state.go()

**Comment by christopherthielen** [comment]
I'll need a plunker reproduction to diagnose this.  We're using `uiCanExit` returning false in the sample app and it seems to work fine.  

https://github.com/ui-router/sample-app-ng1/blob/master/app/contacts/editContact.component.js#L32-L40

You can also try to determine what code is invoking the subsequent `$state.transitionTo()` calls by placing a breakpoint [in these lines of code](https://github.com/angular-ui/ui-router/blob/master/src/state/stateService.ts#L265-L269)

**Comment by varnastadeus** [comment]
Found out that onError hook was causing the loop. OnError was redirecting to root state, which triggered uiCanExit all over again. Didn't knew that abort is treated as error thought.
