### ISSUE TITLE
Docs: onError description wrong

### ISSUE THREAD

**Issue by Kamshak** [angular-ui/ui-router#2918]
https://github.com/angular-ui/ui-router/blob/0769bc28da8bb266b4a4119261e0db05d140e11a/src/transition/interface.ts#L627

Description for ihookregistry.onerror says "Registers a [[TransitionHookFn]], called after a successful transition completed." seems like a C&P issue. Can't fix because i'm not entirely sure when it is called (hence looking it up :smile: )

**Comment by christopherthielen** [comment]
fyi, it's called after a transition has failed
