### ISSUE TITLE
How to disable html5 mode in ui-router-ng2?

### ISSUE THREAD

**Issue by kolkov** [angular-ui/ui-router#2919]
I did not find this in the manual (((

**Comment by christopherthielen** [comment]
https://github.com/ui-router/quickstart-ng2/blob/master/app/_bootstrap/bootstrap.ts#L17-L18

Short answer: provide the `HashLocationStrategy`

```js
import {HashLocationStrategy} from "@angular/common";

... 
bootstrap(/* stuff */
  [{ provide: LocationStrategy, useClass: HashLocationStrategy }, .......]
)
```

**Comment by kolkov** [comment]
Thanks a lot! I did it, but there was no change in the browser...
Now I understand my mistake. I did not setup TypeScript compiler in my IDEA))
