### ISSUE TITLE
Error in plunker for HellowWorld 2

### ISSUE THREAD

**Issue by kolkov** [angular-ui/ui-router#2921]
`(helloState))` - extra closing bracket
```
configure(router: UIRouter) {
    router.stateRegistry.register(helloState));
    router.stateRegistry.register(aboutState));
  }
```

`directives: [UIROUTER_DIRECTIVES],` - and missed a comma
https://plnkr.co/edit/emMpITE71x5kYrXmZ5Vw?p=preview

**Comment by christopherthielen** [comment]
Thanks!  Fixed
