### ISSUE TITLE
How to use @NgModule with ui-router-ng2 properly?

### ISSUE THREAD

**Issue by kolkov** [angular-ui/ui-router#2922]
Hi!
Please provide some examples!

**Comment by christopherthielen** [comment]
I'm working on it; examples coming soon.  

This is a breaking change for `beta.1`, so I'll need to add support in ui-router `1.0.0-beta.2`. 
This also changes a lot for bootstrapping a ui-router-ng2 app.

Look for an update in the next few days.

**Comment by kolkov** [comment]
Thanks!

**Comment by kolkov** [comment]
Good news!))  Thank you very much!

**Comment by kolkov** [comment]
Can't update package (
```
npm ERR! notarget No compatible version found: ui-router-ng2@'>=1.0.0-beta.2'
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.1.0-preview.0, 1.0.0-alpha.2, 1.0.0-alpha.3, 1.0.0-alpha.4, 1.0.0-alpha.5, 1.0.0-beta.1
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by christopherthielen** [comment]
The code is in master but beta.2 hasn't released yet. There are 2 open
issues I'm looking at for the beta 2 milestone.

**Comment by FlawaCLV** [comment]
@christopherthielen is it possible to have an example ? The doc is not updated yet.. Thanks !

**Comment by christopherthielen** [comment]
[UIRouterModule docs](https://ui-router.github.io/docs/latest/classes/ng2.uiroutermodule.html)

[Tutorial 1 - Hello World](https://ui-router.github.io/tutorial/ng2/helloworld)
[Tutorial 2 - Hello Solar System](https://ui-router.github.io/tutorial/ng2/hellosolarsystem)
[Tutorial 3 - Hello Galaxy](https://ui-router.github.io/tutorial/ng2/hellogalaxy)

Hope this helps.
