### ISSUE TITLE
Configuring a default state with templates from outside of ui-router?

### ISSUE THREAD

**Issue by raymondwang** [angular-ui/ui-router#2923]
I'm having a little trouble figuring out how to wire up an application on my website to use both ui-router along with a default template. Essentially, my initial template comes from Flask/Jinja, and I would like to load it by default upon landing on `/state`. This is pretty important to my product, for which server-side rendering for search engine optimization is necessary. Once some action is taken on the page, I want to hit a child state at `/state/#/child`. This all works more or less for free with the following setup:

```
Default template:
<ui-view>
  <some-default-content />
</ui-view>

Router:
$stateProvider.state('childState', {
  url: '/child',
  template: 'childTemplate',
  controller: 'childController'
});

Output after $state.go('childState'):
<ui-view>
  <child-template />
</ui-view>
```

The problem is that when I refresh the page on the child state, or directly route to it, I continue to land on the default state. I'm pretty confident that my router is not configured properly for this use case, and that my router doesn't really know how to handle the path on its own when I directly link to the page. However, the documentation I've poked around in all seems to support the notion that some parent up the tree, at some point, needs a `<ui-view>` template. How can I achieve this if this template comes from outside of the router?

Essentially, what I _think_ I want my router to look like is something like this:

```
$stateProvider.state('Parent', {
  abstract: true,
  url: '/'
});

$stateProvider.state('Parent.default', {
  url: ''
});

$stateProvider.state('Parent.child', {
  url: '/child',
  template: 'childTemplate',
  controller: 'childController'
});
```

But I'm pretty sure at least one of the first two states needs something that I'm missing.

**Comment by christopherthielen** [comment]
I'm having trouble understanding your scenario. Tell me if this is correct:

You have a serverside template that outputs:
```html
<ui-view>
  SEO CONTENT LOADED WHEN NO ROUTE IS ACTIVE
</ui-view>

<a href="#/child">Clicking this routes to the child state</a>
```

Clicking the link activates the `childState`. However, immediately refreshing the browser loads the page with the SEO CONTENT visible again?

---

1) Are you using `html5Mode()`?
2) Do you get any `$stateChangeStart` or `$stateChangeError` events fired?

**Comment by raymondwang** [comment]
This is exactly the scenario I am describing, sorry if it was confusing.

1. I am not using `html5Mode()`.
2. No, neither type of error fires at any point in this flow.

**Comment by christopherthielen** [comment]
That setup should be supported.  The states setup you originally posted should work:

```
Default template:
<ui-view>
  <some-default-content />
</ui-view>

Router:
$stateProvider.state('childState', {
  url: '/child',
  template: 'childTemplate',
  controller: 'childController'
});

Output after $state.go('childState'):
<ui-view>
  <child-template />
</ui-view>
```

I can't explain why it's not working with the information provided.

**Comment by raymondwang** [comment]
@christopherthielen: This setup works for simply navigating between states––my concern is that refreshing the page or direct linking to the child state does not seem to work. There really isn't much more to my setup beside that above snippet.

**Comment by christopherthielen** [comment]
> my concern is that refreshing the page or direct linking to the child state does not seem to work

I understand that your application isn't working for some reason and I'd like to help. However, the setup you describe works for me (and the other ui-router users). In order to further help you, you'll have to provide some way for me to recreate your problem (not just describe the problem)

> There really isn't much more to my setup beside that above snippet.

Then recreate it in a plunker for me to download, or upload to a github repository.  Include instructions for how to recreate your issue.
