### ISSUE TITLE
1.0: defaultErrorHandler not called when a transition is Cancelled

### ISSUE THREAD

**Issue by christopherthielen** [angular-ui/ui-router#2924]
If you return `false` from a hook, the defaultErrorHandler should be invoked.

**Comment by jonrimmer** [comment]
I just ran into this while upgrading to 1.0, and it seems like really bad API design. 

If I have written some code to intentionally cancel a transition, it's not an error. It's not exceptional behaviour. It's literally my application behaving as intended.

I know I can override the defaultErrorHandler to circumvent this behaviour, but this feels like a pretty ugly workaround. What if defaultErrorHandler is later enhanced with functionality I need in my app? Am I going to have to keep tracking the upstream implementation and merging the changes back into my copy?

Wouldn't it be better to at least have some way of silently cancelling a transition? Maybe by returning some token like Transition.CANCELLED?

**Comment by christopherthielen** [comment]
@jonrimmer After reading your comments, I'm reconsidering this change

**Comment by jonrimmer** [comment]
@christopherthielen Hey, reading this back and worried I came across a bit rude. I want to say that your work on 1.0 is totally awesome! I got the whole of our codebase upgraded from 0.2 in just a couple of hours. All the new stuff and documentation is fantastic :-) 👍

**Comment by christopherthielen** [comment]
New issue in core https://github.com/ui-router/core/issues/35 to revert this change
