### ISSUE TITLE
Endless state hierarchy support (repeatable states)

### ISSUE THREAD

**Issue by Maximaximum** [angular-ui/ui-router#2925]
In my angularjs app, there is a concept of 'project'. Each project can contain 0 or more folders, and each of those folders can contain 0 or more subfolders. Each of the subfolders, in turn, can contain 0 or more sub-subfolders and so on. There is no actual limit on the amount of folder levels in the hierarchy.

I want to map each of the folder levels to a UIRouter state level. Please consider an example:

<pre>URL                                                                        State name
http://localhost:8079/projects/1122024                                  -> _.projects.view
http://localhost:8079/projects/1122024/folders/123890                   -> _.projects.view.folder
http://localhost:8079/projects/1122024/folders/123890/547938            -> _.projects.view.folder.folder
http://localhost:8079/projects/1122024/folders/123890/547938/124890     -> _.projects.view.folder.folder.folder</pre>

It would be great if UI Router would allow for declaring something like 'repeatable' states so that when I declare _.projects.view.folder state, I can mark it as 'repeatable', and UI Router would handle that accordingly.

Thanks!

**Comment by christopherthielen** [comment]
This is something I've given thought to as well.  The ng2 router supports something like this and I think it's pretty cool.

**Comment by sarod** [comment]
It can also be useful to support repeating a sequence of states. This is typically useful when needing to browse a hierarchy and you want a state to display the details of the record and a state to display the list of children as a table for instance.

This can be the case for browsing an employee hierarchy you could have urls like these:
* http://host/employees/1122024/reports
* http://host/employees/1122024/reports/123890/reports/1542
