### ISSUE TITLE
Ability to ignore order of items in the array parameter

### ISSUE THREAD

**Issue by fracz** [angular-ui/ui-router#2929]
I have the following config:

```js
$urlMatcherFactoryProvider.defaultSquashPolicy(true);
$stateProvider.state('search', {
  url: '/search?{tags:int}',
  params: {
    tags: {
      array: true, 
      value: [1, 2]
    }
  }
});
```
The URLs for this state are generated as follows

\# | Method | URL
------------ | ------------- | -------------
1. | `$state.go('search')` | `/search`
2. | `$state.go('search', {tags: [1, 2]})` | `/search`
3. | `$state.go('search', {tags: [2, 1]})` | `/search?tags=2&tags=1`
4. | `$state.go('search', {tags: [1, 2, 3]})` | `/search?tags=1&tags=2&tags=3`

I would expect the 3rd example URL to be `/search`. I do not care about the order of the items in the array, so the `tags` parameter should be squashed. 

I dream about something like

```js
$stateProvider.state('search', {
  url: '/search?{tags:int}',
  params: {
    tags: {
      array: true,
      ignoreOrder: true,
      value: [1, 2]
    }
  }
});
```

**Comment by christopherthielen** [comment]
This isn't quite what you asked for, but you can write your own custom parameter type which ignores order when comparing:

http://plnkr.co/edit/vFqW9QToQxsqeDq021y7?p=preview

```js
  $urlMatcherFactoryProvider.type('set', {
    // Validate the object is an Array of numbers
    is: (val) => 
        Array.isArray(val) && val.reduce((acc, i) => acc && typeof i === 'number', true),
    encode: (array) => array.join('-'),
    decode: (string) => string.split('-').map(val => parseInt(val, 10)),
    equals: (a, b) => angular.equals(a.slice().sort(), b.slice().sort())
  });
  
  
  $stateProvider.state('search', {
    url: '/search?{tags:set}',
    params: {
      tags: {
        array: false,
        value: [1, 2]
      }
    }
  });
  
```

**Comment by fracz** [comment]
Thank you! I tried to write a custom type to handle this but it received every single element from the array, not the whole array at once. Ironically, the `array: false` is what I was missing.
