### ISSUE TITLE
Transition.transitionservice.onBefore called only once

### ISSUE THREAD

**Issue by ClementParis016** [angular-ui/ui-router#2930]
I'm having trouble trying to show a loader when state changes.

Currently I have  a Loader component and a controller that looks like this:

```js
class LoaderController {

  constructor($transitions, $timeout) {
    this.$transitions = $transitions;
    this.$timeout = $timeout;
    this.loading = true;
  }

  $onInit() {
    this.$transitions.onBefore({to: '*'}, () => {
      console.log('tr');
    });
  }

}

LoaderController.$inject = ['$transitions', '$timeout'];

export default LoaderController;
```

But the callback for `onBefore` gets executed only for the default state (that matches the `/` URL), each time it is called, but never for other states of the application.

What am I missing here? I'm not sure I'm using it correctly, though.

**Comment by christopherthielen** [comment]
I'll point out three things:

1) `'*'` is a glob pattern which matches any state at the root level, but it doesn't match child states.  Use double star `'**'` to match child states too.  The ui-router glob documentation is scattered and not very good, sorry.

Better yet, the default `to:` criteria already matches any state, so use `onBefore({}, ...)`.  
This is [documented here](https://ui-router.github.io/docs/latest/interfaces/transition.hookmatchcriteria.html) 

> All properties are optional. If any property is omitted, it is replaced with the value true, and always matches.

2) If you create a hook in a component, you should deregister that hook when the component is destroyed.

```
var deregisterFn = $transitions.onBefore(...)

$onDestroy() {
  deregisterFn()
}
```

3) If a transition is in progress before your component is initialized (and before your `onBefore` hook registers), the initial transition won't be captured.  You can get the in-progress transition promise from `$state.transition && $state.transition.promise`

**Comment by ClementParis016** [comment]
Thanks for your help Chris. I will not be able to test that before next
week but your explanations sound clear to me.

**Comment by christopherthielen** [comment]
closing for housekeeping.  feel free to ask to reopen if you still consider this  a bug
