### ISSUE TITLE
Removing a dynamic uib-tab created via state cause the state to transition to the $urlRouterProvider.otherwise case.

### ISSUE THREAD

**Issue by imranzunzani** [angular-ui/ui-router#2931]
There is an otherwise case that takes the user to a login page.
This is the default page where anyone will land in case of any routing issue.
If login is successful, the user goes to a landing page.
Here I have menus implemented using ui-router.
A click on the menu, causes a dynamic tab to be created via a state.
My problem is while closing a tab, the user gets transitioned to the login page.
This should not happen, and the view should remain the same, just the tab should be gone.
I have created a fiddle here: 
[https://jsfiddle.net/xdrovwsn/2/](https://jsfiddle.net/xdrovwsn/2/)
The 'Add Tab' button in that fiddle functions same as a menu item.
Could you please take a look and help me understand what is going wrong?
I applied the same logic for overlays and it is working:
 ```
 .state("overlay", {
			    		url: "/prompt",
			    		params: {action:null},
			    		onEnter: function($stateParams, $state, $uibModal) {
			    		$uibModal.open({
			    			templateUrl: "overlay.html",
			    		    controller: OverlayController
			    		})
```
This is not causing any transition to 'otherwise'.

**Comment by christopherthielen** [comment]
The generated markup contains an `<a href=""` which effectively sets the location to the empty string.  

Here's the DOM:

<img width="385" alt="screen shot 2016-08-19 at 2 12 07 pm" src="https://cloud.githubusercontent.com/assets/2053478/17821375/f5d4c128-6616-11e6-828e-b4130d5300fd.png">

In your handler, inject the `click` event and prevent the default behavior (of following the href).

```html
 <strong ng-click="removeTab($event, $index)">...
```

```js
  //Remove tabs
  $scope.removeTab = function(evt, index) {

    if (index < 0) {
      return;
    }
    $scope.tabs.splice(index, 1);
    evt.preventDefault();   // HERE
  };

```


https://jsfiddle.net/c69932e2/

**Comment by imranzunzani** [comment]
Thank you Christopher ... :)
Amazing analysis and solution.. :+1:
