### ISSUE TITLE
$stateChangeStart is not get trigged

### ISSUE THREAD

**Issue by sibelius** [angular-ui/ui-router#2932]
"angular-ui-router": "^1.0.0-beta.1"

```js
$rootScope.$on('$stateChangeStart', () => {
      console.loog('$stateChangeStart')
    });

    $rootScope.$on('$stateNotFound', () => {
      console.log('notFound');
    });

    $rootScope.$on('$stateChangeSuccess', () => {
       console.log('$stateChangeSuccess')
    });

    $rootScope.$on('$stateChangeError', (event, toState, toParams, fromState, fromParams, error) => {
             console.log('$stateChangeError')
    });
```

this hooks are not working on 1.0.0-beta.1

**Comment by aligajani** [comment]
Maybe it is not logging because of  `console.loog` with a double `o`.

**Comment by reppners** [comment]
Because in 1.x these events are deprecated:
https://ui-router.github.io/guide/ng1/migrate-to-1_0#state-change-events

If you cannot afford to migrate right now there is a polyfill for `$stateChange...` events:
https://ui-router.github.io/docs/latest/modules/ng1_state_events.html

**Comment by sibelius** [comment]
@reppners how can I import/require stateEvents.js from `angular-ui-router`?

**Comment by reppners** [comment]
This depends on the language and module system/module loader you use for your application. For SystemJS/JSPM and ES6/TypeScript I would try something like `import "angular-ui-router/stateEvents";`

**Comment by sibelius** [comment]
`import angular-ui-router/stateEvents` does not work on webpack, maybe u should export it on package.json

I've just copied stateEvents.js to my main project for now

really thanks :tada:

**Comment by scholtzm** [comment]
@sibelius Fairly old issue but somebody might run into this. This works for me:

`import '@uirouter/angularjs/lib/legacy/stateEvents.js';`

You can reference it like so afterwards:

`angular.module('myApp', ['ui.router.state.events']`

**Comment by rickstavares** [comment]
Thank you kind sir @scholtzm. This worked perfectly

**Comment by KeazDev** [comment]
Thank @sibelius, @reppners  and @scholtzm, We spend so much time on this issue when upgrading angular-ui-router version.
thanks all!
