### ISSUE TITLE
upgrade from 0.2.x to 1.0 - getting "Invalid resolve value"

### ISSUE THREAD

**Issue by 29er** [angular-ui/ui-router#2933]
Hi, am trying to upgrade from 0.2.8 to 1.0.0-beta.1 on ui-router and run into this error in any of my states that use 'resolve'. 
for example I get 'Invalid resolve value: "q" from the state below

```
state('myState', {
                url: '/myState?filter',
                component: 'myComponent',
                resolve: ['$q', '$ocLazyLoad', function ($q, $ocLazyLoad) {
                    var deferred = $q.defer()
                      .....
                }]
            })
```
Can someone point me in the right direction for using 'resolve' in ui-router 1.0 ?

Thanks!

**Comment by sibelius** [comment]
I think resolve is an object 

```js
resolve: {
    products: ($, $ocLazyLoad) => { 
          // load my products 
         // return a promise
   }
}
```

**Comment by christopherthielen** [comment]
Yes, @sibelius  is correct; resolve is an object (and it always has been, as far as I know)...  

I'm surprised your code worked with version 0.2.8!!

**Comment by 29er** [comment]
Im surprised too! we have that [] syntax all over our app :)  thanks for the info 👍

**Comment by N3mezis** [comment]
Just ran into the same problem. 2hrs of debugging later, I found the issue why, when built, my application didn't work. 
After thinking a bit about why it even worked before with the array notation, I came to the conclusion that of course angular's built in dependency injection works on argument names just fine. uiRouter ignored Strings as resolves and invoked merely the function. 
Maybe you guys could add an error for arrays that consist of n-1 strings and a function.

**Comment by christopherthielen** [comment]
interestingly, we now support "resolve as array of ResolveLiteral objects"

https://ui-router.github.io/ng1/docs/latest/interfaces/ng1.ng1statedeclaration.html#resolve
https://ui-router.github.io/ng1/docs/latest/interfaces/resolve.resolvableliteral.html
