### ISSUE TITLE
resolve variable do not update his value

### ISSUE THREAD

**Issue by jjgonver** [angular-ui/ui-router#2934]
I have a controller that I injected some variables through resolve that are associated with Data Model. When another user changes the Data Model all the users can see the changes. All works well except one that does not update his value. All resolve variable creates the same way.
This the resolve variable:

```
...
,
          _votesSurvey: [
                    '$stateParams',
                    'AnswersModel',
                    'VoteModel',
                    function resolve(
                      $stateParams,
                      AnswersModel,
                      VoteModel
                    ) {
                      return AnswersModel.load({survey: $stateParams.survey, populate: 'votes'});
                    }
          ]
...
```

What could be happening?
Thanks

**Comment by christopherthielen** [comment]
There isn't enough information to provide an answer.  Your resolve looks OK.

Can you reproduce the behavior in a plunker so I can take a look?  Have you tried asking on stackoverflow?

http://bit.ly/UIR-Plunk

**Comment by jjgonver** [comment]
It's very difficult to reproduce in a plunker. The data is injected from a Service that connects with my backend in localhost. Can you tell me what requirements are necessary for the resolve variable is updated automatically when another user change the data?
Meanwhile, I will try on stackoverflow.
Thanks.
