### ISSUE TITLE
Problem with @character in the params

### ISSUE THREAD

**Issue by corali89** [angular-ui/ui-router#2935]
Hello guys! I have this link, for example:
`<a ui-sref="layout.guestDetail({guestEmail: corali@as.as})"> Lets see the details</a>`
and this is not working because the '@'.... what i can do?
angular.js:13550 Error: [$parse:lexerr] Lexer Error: Unexpected next character  at columns 19-19 [@] in expression [{guestEmail: corali@as.as}].
http://errors.angularjs.org/1.5.5/$parse/lexerr?p0=Unexpected%20nextharacter%20&p1=s%2019-19%20%5B%40%5D&p2=%7BguestEmail%3A%corali%40as.as%7D

**Comment by christopherthielen** [comment]
ui-sref parameters are evaluated against the angular $scope and corali@as.as isn't a valid variable name.

If you want to use a literal string as a parameter value, enclose it in quotes.

`<a ui-sref="layout.guestDetail({guestEmail: 'corali@as.as'})"> Lets see the details</a>`
