### ISSUE TITLE
Why the first call $state.go() function does not pushState to the history?

### ISSUE THREAD

**Issue by cawa-93** [angular-ui/ui-router#2937]
In my application remembers the last open state. After starting controller I use the function $state.go() to load the saved state.

``` javascript
function SectionsCtrl(storage, Analytics, $state, $scope) {
    console.log(history);
    $state.go('user', { user_id: 1 }, { reload: true }).then(function () { return console.log(history); });
}
```

Before and after `history.length == 1`
By default, launches another state:

``` javascript
$urlRouterProvider.otherwise('/');

$stateProvider
    .state('home', {
        url: '/',
        templateUrl: "..."
    })
    .state('user', {
        url: '/user/{user_id}',
        templateUrl: "...",
    })
```

I expect that after the $state.go() function in the history of the two states will be, and I can use history.back() function to switch from the saved state to the default state.

**Comment by christopherthielen** [comment]
UI-Router doesn't interact directly with the `history` object.  The browser will add history entries when the URL changes.

Does the URL change between SectionsCtrl and the `user` state?

**Comment by christopherthielen** [comment]
Is this code running in HTML5 mode? Can you reproduce this as a plunker?

**Comment by cawa-93** [comment]
Sorry. I can not reproduce the algorithm as a plunker. Here is a [link to the source code](https://github.com/cawa-93/vknotice/blob/develop/src/SectionApp/js/SectionsCtrl.ts#L18). On [line 16](https://github.com/cawa-93/vknotice/blob/develop/src/SectionApp/js/SectionsCtrl.ts#L16), you can see that I have to manually add to the history of one state to be able to return to it.

**Comment by jaygauten** [comment]
@cawa-93 can you share your fix for this issue? thanks
