### ISSUE TITLE
Feature request: separate states for ui-sref and ui-sref-active

### ISSUE THREAD

**Issue by bblack** [angular-ui/ui-router#2938]
It would be really nice to have the ability to specify one state for ui-sref (the state to which the link sends the user) and one state for ui-sref-active (the state that causes, if the current state is a descendant, the active class to be applied).

A use case I commonly have is that I have an abstract state (e.g. `beers`), and a couple of child states (`beers.index`, `beers.show`), and I have a nav bar link to one of the child states (e.g. `beers.index`, though the visible text to user might say just "Beers"), but I want it to appear active if the user is in *any* child of that abstract state.

In this case, I'd want to show the active class if the current state includes the abstract (`beers`), but have the href point to the child (`beers.index`).

Alternately, I'd like to be able to tersely express that my abstract state should redirect to some child state—then I can use ui-sref as-is, to the abstract state.

**Comment by christopherthielen** [comment]
I'm not sure why the docs site isn't reflecting this, but we support the following mechanism for ui-sref-active:  https://github.com/angular-ui/ui-router/blob/master/src/ng1/directives/stateDirectives.ts#L289-L308

> Alternately, I'd like to be able to tersely express that my abstract state should redirect to some child state—then I can use ui-sref as-is, to the abstract state.

1.0 has `redirectTo` (don't use `abstract: true` with this one for now) https://ui-router.github.io/docs/latest/interfaces/state.statedeclaration.html#redirectto
