### ISSUE TITLE
Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by ben657** [angular-ui/ui-router#2941]
This seems like an odd issue, for the life of me I can't reproduce it on a plunkr so I assume it's some problem I've brought on myself, but haven't really got any idea where to start looking.

[This plunkr](http://codepen.io/ben657/pen/mEkyBp) shows roughly my layout, and when it gets compiled on my actual app, the error is here: 

```
$StateRefDirective.$inject = ['$state', '$timeout'];
    function $StateRefDirective($state, $timeout) {
      return {
        restrict: 'A',
        $__require: ['?^uiSrefActive', '?^uiSrefActiveEq'],
        link: function (scope, element, attrs, uiSrefActive) {
          var ref = parseStateRef(attrs.uiSref, $state.current.name);
          var def = { state: ref.state, href: null, params: null };
          var type = getTypeInfo(element);
          var active = uiSrefActive[1] || uiSrefActive[0];
          var unlinkInfoFn = null;
          var hookFn;
```

on the `var active =...` line, uiSrefActive is undefined.

As I said, more looking for ideas on what could cause this, since I assume I've caused it somehow.

**Comment by SeamusJ** [comment]
We just started seeing this too. This only happens when the app is bundled and minified.

**Comment by christopherthielen** [comment]
hrm, why does that DDO have `$__require`

**Comment by christopherthielen** [comment]
The source code is `require: `, not `$__require:`:

https://github.com/angular-ui/ui-router/blob/master/src/ng1/directives/stateDirectives.ts#L150

**Comment by christopherthielen** [comment]
What bundlers are you two using?  @SeamusJ  @ben657 
I suspect there's something going on with SystemJS here

**Comment by SeamusJ** [comment]
I am using jspm's bundler.

**Comment by SeamusJ** [comment]
I am going to drop back to an older release of jspm and see what happens.

**Comment by christopherthielen** [comment]
This looks to be a jspm or systemjs-builder bug, but is not a ui-router bug.  `jspm bundle` is mangling the source code.

steps to reproduce: 

```
npm i --global jspm
jspm init
jspm install angular-ui-router
jspm bundle angular-ui-router
grep "require.*uiSrefActive" build.js
```

I wonder if @guybedford would care to comment?

**Comment by guybedford** [comment]
@christopherthielen see https://github.com/jspm/jspm-cli/issues/2046.

**Comment by christopherthielen** [comment]
@guybedford 👍

**Comment by SeamusJ** [comment]
Thanks guys!

**Comment by christopherthielen** [comment]
Closing. Track this issue https://github.com/systemjs/babel-plugin-transform-cjs-system-wrapper/issues/8 instead
