### ISSUE TITLE
Question: can you intercept a url before the provider processes them?

### ISSUE THREAD

**Issue by eckersalld** [angular-ui/ui-router#2942]
I have an issue where a 3rd party redirect will pass a '#' in the uri, and I'd like to intercept that and strip it out before it hits the stateProvider.

e.g. Redirect goes to http://mysite/test.html/#value1=1&value1=2 and I want to extract #value1=1&value1=2 so ui-router sees http://mysite/test.html/.

Is this possible?

**Comment by christopherthielen** [comment]
You can use `$urlRouterProvider.deferIntercept()`

UI-Router won't monitor the URL until you later call `$urlRouter.listen(); $urlRouter.sync();`

https://ui-router.github.io/docs/latest/classes/url.urlrouterprovider.html#deferintercept
https://ui-router.github.io/docs/latest/classes/url.urlrouter.html#listen
https://ui-router.github.io/docs/latest/classes/url.urlrouter.html#sync
