### ISSUE TITLE
Problem with dynamic links

### ISSUE THREAD

**Issue by sebsebseb1982** [angular-ui/ui-router#2944]
Hi,

I'm using dynamic links in my app and I've encountered a problem. I've made [a Plunkr](https://plnkr.co/edit/Rdgj4kDtwHF2NHiaupn1?p=preview) to understand what's happening.

When I'm changing dynamically my state (represented here by the select), the ui-sref attribute's value is updated but not the href's one.

Bonus question : the static link B doesn't work either :-\

Thank you for your help,
Sébastien

**Comment by christopherthielen** [comment]
`ui-sref` doesn't watch the state expression for perf reasons.  
We added a `ui-state` and `ui-state-params` directives to allow dynamic links:

Docs are admittedly not good:
https://ui-router.github.io/docs/0.3.1/#/api/ui.router.state.directive:ui-state

```
      <a data-ui-state="selectedState.state" 
           data-ui-state-params="{'myParam':aMyParam}">
           Link to page {{selectedState.name}} with myParam = {{aMyParam}}
      </a>
```

https://plnkr.co/edit/hpdbHM5r3EDrpai1YVHI?p=preview

**Comment by sebsebseb1982** [comment]
You're my hero ;-)
Thank you
