### ISSUE TITLE
Apache Rewrites for HTML5 mode give server error

### ISSUE THREAD

**Issue by sharazam** [angular-ui/ui-router#2947]
I have copied the example app, running XAMPP. But for some reason Apache can't even find the index.html file.

What I did:

- I am using Angular 1.5.8 (the latest version)

- I have set a base tag. I am not on the root level, but on /my-application/, so I've set it like this:

`      <base href="/test/">
`

- I have added an .htaccess file in the /my-application/ directory, like the :

```
<VirtualHost *:80>
   #I don't know what ServerName actually means, so I just set it to "localhost"
    ServerName localhost

    DocumentRoot "D:\xampp\htdocs\test"

    <Directory "D:\xampp\htdocs\test">
        RewriteEngine on

        # Don't rewrite files or directories
        RewriteCond %{REQUEST_FILENAME} -f [OR]
        RewriteCond %{REQUEST_FILENAME} -d
        RewriteRule ^ - [L]

        # Rewrite everything else to index.html to allow html5 state links
        RewriteRule ^ index.html [L]
    </Directory>
</VirtualHost>
```

All I get is an "500 Internal Server Error!". I don't know what I am doing wrong. I have tried DocumentRoot with the slashes in the other direction, I've tried: 

```
Listen 85
<VirtualHost *:85>
```

... in case some port would be blocked, nothing. I don't know what to do.

The only thing that somehow worked, was this:

`FallbackResource /test/index.html`

BUT: The pages do not allow for bookmarking and they load very slow (I get an error about `Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING`). But at least Apache is finding the index.html

**Comment by eddiemonge** [comment]
Your base ref looks like it should be `"/"` since your docRoot is `/test`. 

This is a better question for stackoverflow since its apache (on Windows) and not a ui-router bug.
