### ISSUE TITLE
It's not reload when I change querystring parameters.

### ISSUE THREAD

**Issue by joenil** [angular-ui/ui-router#2948]
I am try to migrate from ng-route to ui-router these days, and I got this problem, like `$location.search('id', 111)` will reload the controller with ng-route, but now it's nothing to happen, how can I keep the reload behavior in ui-router?

**Comment by eddiemonge** [comment]
There are multiple ways to do that. That way should still work. You could also do something like:  `$state.go('.', {id: 111})`
