### ISSUE TITLE
Trouble with ui-router customization

### ISSUE THREAD

**Issue by moacir-selinger** [angular-ui/ui-router#2953]
Hello guys!

I am in trouble with a specific requirement here for our Application.

We a are setting-up an angular application inside a pre-existent Rails Application.

As a full refactor of our code-base is currently out-of-the-question we are dealing with some hard customization and hackings on both sides to allow a incremental introduction of Angular.

What we need for now is a way to tell the ui-router to bind only to the links we have the ng-sref attribute and do not bother with all the regular href links within our app.

Is there a way to achieve this behavior ?

Thank you very much in advance.

Best,
Moacir

**Comment by christopherthielen** [comment]
This is a core angular feature that UI-Router uses.   When clicking a link, core angular triggers a `$locationChangeStart` event which UI-Router responds to.  According to the [$location docs](https://docs.angularjs.org/guide/$location#html-link-rewriting) this can be customized.

I assume you're using html5Mode? 
Try `$locationProvider.html5Mode({ enabled: true, rewriteLinks: false });`

http://plnkr.co/edit/f8iql3wI3Q5P8JkcvUy8?p=info
