### ISSUE TITLE
ui-sref, abstract states and ui-sref-active

### ISSUE THREAD

**Issue by CSchulz** [angular-ui/ui-router#2954]
I am using an abstract state to define an URL hierarchy. The abstract state is used as parent of a drop-down menu and should route to some child page. Using ui-router 0.3.1.

My menu:

```
<li class="dropdown" ui-sref-active="active" ui-sref="administration">
    <a ui-sref="administration.user.list" class="dropdown-toggle" data-hover="dropdown">administration</a>
    <ul class="dropdown-menu">
        <li ui-sref-active="active"><a ui-sref="administration.user.list">users</a></li>
        <li ui-sref-active="active"><a ui-sref="administration.group.list">groups</a></li>
    </ul>
</li>
```

When I click on the administration entry, it shows me **Error: Cannot transition to abstract state 'administration'** and change to _administration.user.list_.

I can fix it with removing `ui-sref="administration"` for the first li, but then there is no hightlighting for the root entry anymore if I select **groups**.

![image](https://cloud.githubusercontent.com/assets/1520593/18122240/c0876e16-6f68-11e6-8fd2-ae379a4f1861.png)

Is there any way to use abstract states to highlight nav entries?

**Comment by christopherthielen** [comment]
interesting timing... I just implemented your feature request in the Angular 2 codebase for the `uiSrefStatus` directive.

In ng1, your options are to use the new `ui-sref-active="{ cssClass: 'globstring' }"` syntax.  It doesn't seem to be generated properly inthe docs, but read the JSDoc: https://github.com/angular-ui/ui-router/blob/6ac1c61/src/stateDirectives.js#L267-L279

**Comment by CSchulz** [comment]
Hum for ng1 it doesn't work:

```
<li class="dropdown" ui-sref-active="{'active': 'administration.*'}">
    <a ui-sref="administration.user.list" class="dropdown-toggle" data-hover="dropdown">administration</a>
    <ul class="dropdown-menu">
        <li ui-sref-active="active"><a ui-sref="administration.user.list">users</a></li>
        <li ui-sref-active="active"><a ui-sref="administration.group.list">groups</a></li>
    </ul>
</li>
```

**Comment by christopherthielen** [comment]
use `ui-sref-active="{'active': 'administration.**'}"`
With globs, a single star matches states at one level. Two stars match any nested states.

**Comment by CSchulz** [comment]
Thanks for your fast reply. I am not sure, but I think it wasn't covered in the doc.

**Comment by christopherthielen** [comment]
> I am not sure, but I think it wasn't covered in the doc.

Youre right, the docs for glob syntax are very very poor.

**Comment by christopherthielen** [comment]
Docs for glob are improved now 👍 https://ui-router.github.io/ng1/docs/latest/classes/core.glob.html

**Comment by pselden** [comment]
Can globs be applied to match multiple unrelated states? I want an "active" link if any of 3 statees match:

Ex: ui-sref-active={'active': 'store.**|cart.**'} where the link should become active when both store or cart routes are active.

**Comment by JewelsJLF** [comment]
+1  I also need to be able to match on multiple unrelated child states... can this be done?

**Comment by Cptcecil** [comment]
I am still having an issue with this.  I've used your solution and it works great.  However, when I try to do something like this:

ui-sref-active="{'active' : '{{$ctrl.section.routeParent}}.**'}"

it doesn't work.  $ctrl.section.routeParent is resolving correctly, I've checked the source.  When I type it in manually, it works.  The element looks exactly the same in the source after using both methods.

**Comment by petermcneely** [comment]
For anyone who runs into what @Cptcecil ran into:

move the logic to discern what the active route should be to your controller like so:
```
bindings: {
    section: '<' // assuming the section object has a routeParent property.
},
controller: function () {
    var self = this;
    ...
    self.getActiveCondition = function () {
        return {
            'active': self.section.routeParent + '.**'
        };
    }
    ...
}
```

And then your html should use `ui-sref-active="$ctrl.getActiveCondition()"`. ui-router should evaluate the function here using the values from the scope of your controller.
