### ISSUE TITLE
Identifier 'angular' must be imported from a module

### ISSUE THREAD

**Issue by jonrimmer** [angular-ui/ui-router#2955]
1.0.0-beta.1 gives a type error when used with TypeScript:

```
ERROR in [...]/node_modules/angular-ui-router/commonjs/ng1/services.d.ts
(2,27): error TS2686: Identifier 'angular' must be imported from a module
```

**Comment by jonrimmer** [comment]
Repro here: https://github.com/jonrimmer/typescript-bug

```
npm install
tsc bug.ts

node_modules/angular-ui-router/commonjs/ng1/services.d.ts(2,27): error TS2686: Identifier 'angular' must be imported from a module
```

**Comment by jonrimmer** [comment]
So, I was thinking this might be a TypeScript issue, so have raised it there as well: https://github.com/Microsoft/TypeScript/issues/10638#issuecomment-243788466

**Comment by Gugic** [comment]
I believe it's not just ui-router's error, because i'm getting that one on each my file where i using interfaces from angular.

**Comment by jonrimmer** [comment]
According to mhegazy:

> this is an issue in angular-ui-router declaration file. The compiler tries to ensure that a UMD module is used consistently, either as a module or as a global.

> File: node_modules\angular-ui-router\commonjs\ng1\services.d.ts

> should be:

```ts
import * as angular from "angular";
import IInjectorService = angular.auto.IInjectorService;
```

**Comment by christopherthielen** [comment]
thanks @jonrimmer

**Comment by christopherthielen** [comment]
This was fixed in beta.3 via 71bfaa0599f897f47418300d144de523f6232021
