### ISSUE TITLE
Trying new @UIRouterModule...

### ISSUE THREAD

**Issue by kolkov** [angular-ui/ui-router#2956]
Hi!
I cloned ui-router into local folder, and built it with `npm run build`
Then I removed old `ui-router-ng2` content in the `node_modules` folder and copied new content from `build_packages\ng2`.
Then I changed app.module.ts to:

```
var homeState = { name: 'home', url: '/home', component: HomeComponent };
var aboutState = { name: 'about', url: '/about', component: AboutComponent };

@UIRouterModule({
   imports: [BrowserModule],
   declarations: [AppComponent],
   states: [homeState, aboutState]
 }) 
export class AppModule {};
```

and got a error:
![image](https://cloud.githubusercontent.com/assets/3740898/18127029/9ade5396-6f86-11e6-9e2b-a5a3f4eb9b0f.png)
Whats wrong?

**Comment by kolkov** [comment]
After I added traceur manually:
![image](https://cloud.githubusercontent.com/assets/3740898/18129416/4d39fc14-6f93-11e6-9482-d43b7d6cab67.png)

**Comment by christopherthielen** [comment]
I suspect you're using systemjs? I saw this in quickstart-ng2 where SystemJS incorrectly detects `ui-router-ng2.js` as an ES6 module that needs transpiling.  I believe it's parsing something from one of the block comments in the unminified file.

Try one of these things:
- Point systemjs to the `ui-router-ng2.min.js` minified file
- Add a `meta:` block that says the bundle is `cjs`  https://github.com/ui-router/quickstart-ng2/blob/rc5compat/systemjs.config.js#L54

**Comment by kolkov** [comment]
Thanks! That worked!
But got another error:

![image](https://cloud.githubusercontent.com/assets/3740898/18138383/11bdce46-6fb5-11e6-961b-186b742e6780.png)

```
@UIRouterModule
({
  imports: [
    BrowserModule,
  ],
  declarations: [
   AppComponent
  ],
  states: [],
  providers: [
    {provide: LocationStrategy, useClass: HashLocationStrategy},
    {provide: UIRouterConfig, useClass: MyUIRouterConfig},

  ],
  bootstrap: [ UIView ]
})
```

**Comment by christopherthielen** [comment]
you need to declare it as an `entryComponent`

**Comment by kolkov** [comment]
Ho can I do this?

**Comment by christopherthielen** [comment]
```js
@UIRouterModule
({
  imports: [
    BrowserModule,
  ],
  declarations: [
   AppComponent
  ],
  entryComponents: [
    AppComponent
  ],
  states: [],
  providers: [
    {provide: LocationStrategy, useClass: HashLocationStrategy},
    {provide: UIRouterConfig, useClass: MyUIRouterConfig},

  ],
  bootstrap: [ UIView ]
})
```

**Comment by christopherthielen** [comment]
Also note: `@UIRouterModule` is a shortcut for creating a `NgModule` manually:  

https://github.com/angular-ui/ui-router/blob/f6741516a43a605ed7f8f3d1d96517e7e46ef54d/src/ng2/uiRouterNgModule.ts#L50-L66

**Comment by thegrid22593** [comment]
What is the official latest release of ui-router-ng2 for npm in order to start using @UIRouterModule? I am updating to RC5.

**Comment by kolkov** [comment]
@christopherthielen Yes! Thats helped!
And one more error from second module:

![image](https://cloud.githubusercontent.com/assets/3740898/18141035/9ff7b626-6fc0-11e6-93dc-23b90af806b7.png)

**Comment by kolkov** [comment]
@christopherthielen I fixed it by removing undefined states
```
uiSref="app.public.user.signup"
uiSref="app.public.user.login"
```

**Comment by thegrid22593** [comment]
@kolkov What is the latest release of ui-router to work with angular 2 rc5? Also, where are you importing UIRouterModule from?

**Comment by thegrid22593** [comment]
@kolkov @christopherthielen nvm I found the quickstart and that is all up to date. Thanks all!

**Comment by kolkov** [comment]
@thegrid22593 No, quickstart is not for UIRouterModule, it's for beta1. UIRouterModule is for future beta2.
If you want you can try to build beta2 by yourself as described above.

**Comment by christopherthielen** [comment]
@thegrid22593  ui-router 1.0.0-beta.2 will be out shortly and contains the `UIRouterModule` code being discussed, and full `NgModule` support.

**Comment by thegrid22593** [comment]
@christopherthielen Great to hear! Thanks!

**Comment by kolkov** [comment]
@christopherthielen What is preferable to use, UIRouterModule or NgModule?

**Comment by christopherthielen** [comment]
@kolkov `UIRouterModule` is easier to use (less boilerplate) but it's your own personal choice.  

If you use raw `NgModule` make sure your module provides the states as `UIROUTER_STATES_TOKEN` with `multi: true` and also imports the `UIRouterRootModule`

**Comment by kolkov** [comment]
Thanks! Now we can describe routes for modules separately in the modules themselves?
And we no longer need to use this construction in MyUIRouterConfig?
INITIAL_STATES.forEach(state => uiRouter.stateRegistry.register(state));

**Comment by christopherthielen** [comment]
>
Now we can describe routes for modules separately in the modules themselves?
And we no longer need to use this construction in MyUIRouterConfig?
INITIAL_STATES.forEach(state => uiRouter.stateRegistry.register(state));

^ correct.

**Comment by kolkov** [comment]
And what now we do with this function? It is still necessary?
```
@Injectable()
export class MyUIRouterConfig {
  constructor(private injector: Injector) {}

  configure(uiRouter: UIRouter) {
    // Register each state definition (from app.states.ts) with the StateRegistry   

    // Define a default behavior, for when the URL matched no routes
    uiRouter.urlRouterProvider.otherwise(() => uiRouter.stateService.go("app.public.home", null, null) && null);
  }
}
```
And do we need here injector still?

**Comment by christopherthielen** [comment]
You still need to provide a `MyUIRouterConfig` with a `.configure()` function.  The `private injector: Injector` isn't actually used, and is not necessary to inject.

**Comment by thegrid22593** [comment]
@christopherthielen any idea on what the time frame is for 1.0.0-beta.2?

**Comment by kolkov** [comment]
@christopherthielen Do we still need `bootstrap: [ UIView ]` in AppModule?

**Comment by kolkov** [comment]
Url: `mydomain/angular2#/public/home`
state is: `public.home`
And state is empty in Augury:
![image](https://cloud.githubusercontent.com/assets/3740898/18145225/ea4da570-6fd2-11e6-91a1-221a471d2f09.png)
Is it correct?
