### ISSUE TITLE
queued.shift is not a function error in Firefox Only 

### ISSUE THREAD

**Issue by StephenGrable1** [angular-ui/ui-router#2959]
So I am having trouble with my Angular app (version 1.5.7) in Firefox.

You can checkout the project files here  -> https://github.com/StephenGrable1/AngularJS-Single-Page

**Live deployment here** -> https://fathomless-scrubland-50887.herokuapp.com

It works perfectly in Chrome and in Safari. However, in Firefox the entire application breaks and I receive an error $injector:modulerr that reads: "Failed to instantiate module app due to: queued.shift is not a function"

I saw that that the queued.shift function is coming from ui-router. While troubleshooting I can make the error disappear in Firefox by taking the name attribute off of ng-app. 

From this:
`<html lang="en" ng-app="app">`

To this:
`<html lang="en" ng-app>`

But when I do that, the ui-view and route functionality breaks and only my ng-include's are displayed (which one would expect). 

This $injector:modulerr error does not happen to me in Chrome or Safari and is exclusive to Firefox. I'm having a lot of trouble trying to fix this issue and can't find many resources online so I thought it would be good to solve it here incase others run into this issue in the future.

**Comment by christopherthielen** [comment]
You're running into this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/watch

Apparently Firefox puts a `watch` function on the Object.prototype. When we check `queued[name]`, since your state's name is `watch` it's picking up Object.prototype.watch 👎

**Comment by StephenGrable1** [comment]
Thanks @christopherthielen ! Such a simple fix. Renamed "watch" to "watchHere" and it works. Hopefully this thread saves some poor, lost soul from this issue in the future
