### ISSUE TITLE
Go to sibling state with reload true

### ISSUE THREAD

**Issue by silentFred** [angular-ui/ui-router#2961]
Hi guys and gals,

We are sitting with a bit of a funny situation where we need to transition to a sibling state AND reload (execute resolves and controllers all the way from the top view down to the desired state).

The current ui-router implementation only allows a reload when going to the current/same state. (shouldTriggerReload method)

`    
if (to === from && ((locals === from.locals && !options.reload) || (to.self.reloadOnSearch === false))) {
    return true;
}
`

Can anyone advise how we can achieve a reload when transitioning to another state? We have very good reasons to do this but if you feel what we want to do is hacky please share your thoughts?

**Comment by christopherthielen** [comment]
> we need to transition to a sibling state AND reload (execute resolves and controllers all the way from the top view down to the desired state).

That's fully supported.  See this plunker http://plnkr.co/edit/fGdF6SPNF9DKMA50Flrb?p=preview

What version of ui-router are you using?  Try upgrading to 0.3.1 or 1.0.0-beta.1
