### ISSUE TITLE
ui-sref on a parent element breaks all ui-srefs on children

### ISSUE THREAD

**Issue by rluba** [angular-ui/ui-router#2962]
**Example use case:**
- There’s a table where each row links to a sub-state.
- For the user’s convenience the whole `<tr>` is made clickable by adding `ui-sref="A"` to it.
- Some of the table columns contain `<a>` links to _other_ states (implemented by using `ui-sref="B"` on those link tags).

When you click on any of those links – because you want to visit state `B` – the link to `A` on the `<tr>` elements takes precedence because [`ui-sref`’s click handler](https://github.com/angular-ui/ui-router/blob/c113b376300cfc5458fe573652ffb57ab9efbeae/src/ng1/directives/stateDirectives.ts#L68) does not call `e.stopPropagation()` when it handles the click event. So the transition to `B` gets superseded by a transition to `A` when the parent element processes the event. **Therefore, you always end up in state `A` – no matter where you click.**

Adding `e.stopPropagation()` [somewhere in the click handler](https://github.com/angular-ui/ui-router/blob/c113b376300cfc5458fe573652ffb57ab9efbeae/src/ng1/directives/stateDirectives.ts#L68) solves the problem.

Tested with `ui-router@1.0.0-beta.1` and `angular@1.5.5`

**Comment by rluba** [comment]
@christopherthielen, I just discovered a new problem that arises when `e.stopPropagation()` is added – which is probably why it wasn’t added originally:

When the link is part of a dropdown (eg. [angular-bootstrap’s one](http://angular-ui.github.io/bootstrap/#/dropdown)), calling `e.stopPropagation()` will prevent the dropdown from closing after the click. This seems to be a bigger issue than the nested `ui-sref` case, so we should  probably revert the patch.

A possible fix might be to let `ui-sref` check if a transition is in progress and don’t transition in that case, but I’m quite sure that this would have other side effects… 😕

Any better ideas?

**Comment by rluba** [comment]
Another way might be to share [the transition timeout variable](https://github.com/angular-ui/ui-router/blob/c113b376300cfc5458fe573652ffb57ab9efbeae/src/ng1/directives/stateDirectives.ts#L65) between all `ui-sref` clickhooks and set and clear it within the handler. Then any `ui-sref` could check if another `ui-sref` already initiated a transition _during this cycle_, so it won’t interfere with other transitions.

But that still feels a bit messy.

**Comment by christopherthielen** [comment]
what if you just wrote a stop-propagation directive for those ui-sref that are doubly nested?

```
.directive('stopPropagation', () => ({
  restrict: 'A',
  link: (s, elem) => elem.on('click', event => event.stopPropagation())
});
```

**Comment by christopherthielen** [comment]
@rluba I've reverted the commit for beta.3. Can you try the stopPropagation directive technique?

**Comment by rluba** [comment]
I'm currently using my "transition timeout as shared variable" fix in a local fork and it works great. I'll submit a PR as soon as I'm confident that there are not side effects.

**Comment by shql** [comment]
Thanks guys

**Comment by christopherthielen** [comment]
Here's a minimal reproduction: http://plnkr.co/edit/vp0aMZgYIuRK2fXvx96b?p=preview

Clicking 'home.foo' ui-sref in the `<td>` activates the ui-sref on the `<tr>`

**Comment by christopherthielen** [comment]
Here's a viable workaround (`<stop-propagation>` directive)
http://plnkr.co/edit/mxtjxiq3eVssYhfnKsSf?p=preview

**Comment by christopherthielen** [comment]
> I'll submit a PR as soon as I'm confident that there are no side effects.

I'd like to see your solution.  However, know that I'm wary of adding more code (and managing more state) for a case which I don't think is very common.
