### ISSUE TITLE
CanActivate analogue in ui-router-ng2 1.0.0?

### ISSUE THREAD

**Issue by kolkov** [angular-ui/ui-router#2964]
How can we create protected accsess in new ui-router-ng2 similar as in standard Angular 2 router?
http://blog.thoughtram.io/angular/2016/07/18/guards-in-angular-2.html#defining-guards

**Comment by christopherthielen** [comment]
If protecting a single state, use an `onEnter` hook:

```js
.state({
  name: 'foo',
  onEnter: (transition) => {
    let authSvc = transition.injector().get(AuthService);
    return authSvc.asyncCheck().catch(() => transition.router.stateService.target('login'));
  }
```

If protecting a set or class of states, use a global hook which queires metadata on a state:

```js
.state({
  name: 'foo',
  protectMe: true
});
```

```js
class MyUIRouterConfig {
  configure(router: UIRouter) {
    router.transitionService.onBefore({ entering: (state) => state.protectMe }, (transition) => {
      let authSvc = transition.injector().get(AuthService);
      return authSvc.asyncCheck().catch(() => transition.router.stateService.target('login'));
    });
  }
}
```

---

Some other options:

The previous example could instead use the `data` property (which is inherited) to protect a tree of states:

```js
.state({
  name: 'foo',
  data: { 
    protectMe: true
  }
});

.state({
  name: 'foo.bar',
   // also protected because it inherits `data`
});
```

```js
class MyUIRouterConfig {
  configure(router: UIRouter) {
    router.transitionService.onBefore({ to: (state) => state.data && state.data.protectMe }, (transition) => {
      let authSvc = transition.injector().get(AuthService);
      return authSvc.asyncCheck().catch(() => transition.router.stateService.target('login'));
    });
  }
}
```

---

The hook could use globbing:

```js
.state({
  name: 'authstates',
});

.state({
  name: 'authstates.bar',
   // also protected because it inherits `data`
});
```

```js
class MyUIRouterConfig {
  configure(router: UIRouter) {
    router.transitionService.onBefore({ to: 'authstates.**' }, (transition) => {
      let authSvc = transition.injector().get(AuthService);
      return authSvc.asyncCheck().catch(() => transition.router.stateService.target('login'));
    });
  }
}
```

---

Hope this helps

**Comment by kolkov** [comment]
Thank you for such a detailed answer!

**Comment by kolkov** [comment]
I have a little problem. When transition rejected and state changed to `public.user.login`, the url is not changed to `:8080/angular2/#/public/user/login`

![image](https://cloud.githubusercontent.com/assets/3740898/18217141/c1518e06-7163-11e6-81b3-58bcc58b5265.png)

**Comment by christopherthielen** [comment]
@kolkov please open a new issue.  that sounds familiar and I think I know what the problem is.

1) We track what triggers a transition [(the trigger source)](https://github.com/angular-ui/ui-router/blob/master/src/transition/interface.ts#L82-L83).  When triggered by a URL change, we don't update the URL.  
2) When we redirect a transition, we copy the `.options()` to the new `Transition`.  I think this is copying the transition trigger as "url change"
3) Your initial transition was triggered by a URL change (the initial call to `.sync()`).
4) I think the redirected transition optiions still has `"url"` as the source, but it should be something else like "redirect".

Can you try `stateService.target('public.user.login', null, Object.assign({}, transition.options(), { source: 'unknown' })` and see if the URL updates?

**Comment by kolkov** [comment]
`Can you try stateService.target('public.user.login', null, { source: 'unknown' }) and see if the URL updates?`
Yes! This worked!

**Comment by croeber** [comment]
Using this method. I cannot get ahold of the stateParam for the toTransition, only the from transition. 
Is the stateParams preresolved before onEnter is called

**Comment by pscanlon1** [comment]
return authSvc.checkAuthenticated().catch(() => $state.target('login'));

is this a promise? what do i need to return here...

**Comment by christopherthielen** [comment]
@pscanlon1 in the example, `authSvc.checkAuthenticated()` is a fictional service call that would return a promise for whether the user is authenticated or not.
