### ISSUE TITLE
Url not changes when transition to new state complete (ng2)

### ISSUE THREAD

**Issue by kolkov** [angular-ui/ui-router#2966]
`router.stateService.target(public.user.login')` not working
`router.stateService.target('public.user.login', null, { source: 'unknown' })` working perfect!

https://github.com/angular-ui/ui-router/issues/2964

**Comment by christopherthielen** [comment]
1) We track what triggers a transition (the trigger source). When triggered by a URL change, we don't update the URL.

2) When we redirect a transition, we copy the .options() to the new Transition. I think this is copying the transition trigger as "url change"

3) The initial transition was triggered by a URL change (the initial call to .sync()).

4) I think the redirected transition options still has "url" as the source, but it should be something else like "redirect".

Here's where we create the redirected transition options: https://github.com/angular-ui/ui-router/blob/master/src/transition/transition.ts#L374
