### ISSUE TITLE
`leave` is not triggered when switching between states when using ngAnimate

### ISSUE THREAD

**Issue by blueset** [angular-ui/ui-router#2969]
I'm trying to add page transition animation to my AngularJS page with UI router, but it seems no ng-leave class is added and the leave method is not triggered. Entering animation is working fine.

The view is attached on `body` tag, and navi links are defined with `ui-sref`.

Code used to test:

``` js
app.animation('.html-body', function(){
    return {
        enter: function(elem, done){
            console.log("enter");
            done();
        },
        leave: function(elem, done){
            console.log("leave");
            done();
        }
    }
});
```

In the console, there's only "enter" logged, but no "leave" when clicking on links.

Demo Plunk: http://embed.plnkr.co/82mXQqF0cie95RLCohNh/

**Comment by Den-dp** [comment]
Same here. Looks like this regression was introduced in [angular 1.4](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#breaking-changes-12), because plunkr above works fine with the latest `angular@1.3.20` and `angular-animate@1.3.20`.

Any thoughts?

**Comment by Den-dp** [comment]
@blueset 
Ok, I got it to work.

In your plnkr I just moved `ui-view` from `body` to the separate `div`.

And here is the changed one http://embed.plnkr.co/zK68883MuxTkVBqjuvZ5/

However I still have no idea why this code works without changes on `angular@1.3.20`.
