### ISSUE TITLE
The error message has little useful information

### ISSUE THREAD

**Issue by kolkov** [angular-ui/ui-router#2970]
My template has one route that is not defined, but an error message does not indicate which one route is not defined, and shows a lot of other useless information.

![image](https://cloud.githubusercontent.com/assets/3740898/18245266/ef6bffd2-736c-11e6-9daf-52ba2052103a.png)

**Comment by christopherthielen** [comment]
Your template has a uiSrefActive?  
Does this commit fix it?  https://github.com/angular-ui/ui-router/commit/c9b657040b3c0910d7f2ff76f5803135986ee03a

**Comment by kolkov** [comment]
Yes! uiSrefActive present.
After upgrading to rc.6 and beta.2 (without any changes in my project):

![image](https://cloud.githubusercontent.com/assets/3740898/18254357/9d4f067a-73a5-11e6-936b-71cf81872ec2.png)

**Comment by kolkov** [comment]
And our updated bootstrap app stop working to (

**Comment by kolkov** [comment]
All tests passed: \_(ツ)_/¯

**Comment by christopherthielen** [comment]
I changed bootstrap to be more flexible. You have to add `provideUIRouter()` to your root NgModule's `providers` now. 

This adds flexibility for tests and makes ng1-to-ng2 hybrid ui-router apps much easier to manage.

**Comment by kolkov** [comment]
Thanks! That worked!
No error messages now when I add undefined state to template!

**Comment by christopherthielen** [comment]
closed by c9b657040b3c0910d7f2ff76f5803135986ee03a
