### ISSUE TITLE
Release of UI 1.0.0 beta 2

### ISSUE THREAD

**Issue by sheniff** [angular-ui/ui-router#2974]
Hi guys, when are you planning to release next version `1.0.0-beta.2` with the latest changes to NG2 including support for RC6? I'm waiting for the new bundle to update my app and I'd really appreciate some more info about it :)

Thanks beforehand and great job with this truly amazing routing system!

**Comment by kolkov** [comment]
I see only one unclosed issue for 1.0.0-beta.2 
https://github.com/angular-ui/ui-router/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0-beta.2

**Comment by kolkov** [comment]
@christopherthielen Thanks so much for this very long-awaited release! )

**Comment by christopherthielen** [comment]
@sheniff it's released!

**Comment by sheniff** [comment]
Thanks so much, @christopherthielen!
