### ISSUE TITLE
Help with component resolve (update to 1.0)

### ISSUE THREAD

**Issue by Luddinus** [angular-ui/ui-router#2976]
Edit: Does not work with named ui-views? http://jsfiddle.net/789Ks/96/

Hi,

I'm using version 0.3.1 of angular-ui-router

I have a userProfile component and this works fine:

```
// some state definition
url: '/{user}',
abstract: true,
views: {
	'content@': {
		resolve: {
			qCurrentUser: (Manager, $stateParams) => {
			    // internally $http promise
				return Manager.users().show($stateParams.user);
			}
		},
		template: '<user-profile user="$resolve.qCurrentUser.data"></user-profile>',
	}
}
```

The component has "user" binding, and I can access in the component's controller using "this.user".

The problem is that I'm trying to use the same behaviour with 1.0 but it is not working. (I'm using "template" option because "component" didn't work.)

What am I missing?

Thx.

**Comment by christopherthielen** [comment]
`resolve` is a property of a state, not a property of a view.
Move the resolve to the state level and it works: http://jsfiddle.net/789Ks/97/
