### ISSUE TITLE
Best way to get uiParams in component?

### ISSUE THREAD

**Issue by kolkov** [angular-ui/ui-router#2981]
`<a uiSref="private.base.list.details" [uiParams] = "{id:list.Id}">`
How to get param `id` in the `DetailsComponent` properly (like in ng1 way)?

**Comment by christopherthielen** [comment]
option 1) inject the `Transition` into the component (most like the ng1 way)
option 2) expose the id as a `resolve:` and bind it to an `@Input`
option 3) inject the `UIRouter` and use the `router.globals.params$` observable from beta.2

**Comment by kolkov** [comment]
Thanks!

**Comment by kolkov** [comment]
> option 3) inject the UIRouter and use the router.globals.params$ observable from beta.2
are you sure that `router.globals.params$` not the `router.globals.params`?

![image](https://cloud.githubusercontent.com/assets/3740898/18383397/0d16546e-768e-11e6-8392-a88cf8bab4c7.png)


And how to use `Transition`?

**Comment by kolkov** [comment]
How to simplify `this.id = this.transition.router.globals.params.id;`?
![image](https://cloud.githubusercontent.com/assets/3740898/18388672/3b24ee7a-76ab-11e6-9d73-5747125a85d7.png)
and IDEA shows an error in this expression.((
