### ISSUE TITLE
Hash does not change if application inside iframe

### ISSUE THREAD

**Issue by vvsh** [angular-ui/ui-router#2983]
Hi,

I have application inside an iframe:

`<iframe src="/apps/test/0.1">`
`... application with ui-router`
`</iframe>`

I open this application with such url: /apps/test.
And when I click on buttons with ui-sref, URL does not change.

Is there any way to fix it?

Thanks.

**Comment by vvsh** [comment]
P.S. When I open application directly (via /apps/test/0.1) everything works fine.

**Comment by christopherthielen** [comment]
sorry, there's no easy way to do this.  an app inside an iframe shouldn't even be able to access the parent window.  You may be able to implement some hacks that write some custom clue for your app, but ui-router will never be able to provide a general solution to this setup.

I would suggest looking into message passing between iframe and the parent document.  In your ui-router app, you could send a message to the parent document on `$locationChangeSuccess`.  In the parent document you could update the browser hash.
