### ISSUE TITLE
Back Button: canceled transition removes a history entry

### ISSUE THREAD

**Issue by shawnlan** [angular-ui/ui-router#2986]
Here is what I have:

```
              $transitions.onBefore({to:'*'}, function($transition$) {
                    if ($scope.editMode){
                        if($window.confirm("are you sure to leave?"))
                            return true;
                        else
                            return false;
                    }
                });
```

Now if I click the "back" button, the url changes before I answer the dialog. If I choose "cancel," the url changes back. However, the previous history is gone. Next time I click the "back" button, it tries to go to the previous previous url. How do I fix it?

Also, with {to:'*'}, the callback is called from 'parent.child' to 'parent'. I want it to be called only when going to a different parent. For example, from 'parent.child' to 'anotherParent'. How do I do it?

Thanks.

**Comment by christopherthielen** [comment]
> However, the previous history is gone. Next time I click the "back" button, it tries to go to the previous previous url. 

That might be a bug.  Can you make a plunker reproduction?  http://bit.ly/UIR-Plunk

> Also, with {to:'*'}, the callback is called from 'parent.child' to 'parent'. I want it to be called only when going to a different parent. For example, from 'parent.child' to 'anotherParent'. How do I do it?

that sounds more like `{ exiting: 'parent' }` 

... but I suspect you really want to use  [uiCanExit](https://ui-router.github.io/docs/latest/interfaces/ng1.ng1controller.html#uicanexit) on a view controller for user confirmation

**Comment by shawnlan** [comment]
I created a directive:

```
directive('confirmOnExit', function($window) {
        return {
            link: function($scope) {
                $window.onbeforeunload = function(){
                        return 'Are you sure to leave?';
                };
                $scope.$on('$destroy',function(){
                	$window.onbeforeunload = null;
                });
            },
            controller:function(){
            	this.uiCanExit = function(){
                		return $window.confirm('Are you sure to leave?');
            	};
            }
        };
    })
```

Inside the state's view template I added: `<confirmOnExit></confirmOnExit>`.

It doesn't work. But if I attach `this.uiCanExit` directly to the state's controller, it works. Why?

**Comment by shawnlan** [comment]
Plunker for the history bug: http://plnkr.co/edit/W9xqx6R2h9JjSwT99HbZ?p=info

To reproduce:

1. Go to /foo.
2. Go to /contact.
3. Click "Back" and cancel the dialog.
4. Click "Back again and confirm the dialog. Now it goes back to /home instead of /foo.

**Comment by christopherthielen** [comment]
>  But if I attach this.uiCanExit directly to the state's controller,

We can only process `uiCanExit` if its on the state controller.  There's no other way hook into an arbitrary directive controller like you tried.

If you want a directive like that, you can write one, but you have to create your own `$transitions.onExit` hook (and don't forget to deregister it when the directive is destroyed)

**Comment by christopherthielen** [comment]
> Plunker for the history bug: http://plnkr.co/edit/W9xqx6R2h9JjSwT99HbZ?p=info

Thanks for the plunker reproduction.

**Comment by christopherthielen** [comment]
> TransitionRejection(type: 3, message: The transition has been aborted, detail: Hook aborted transition). Is it normal?

Yes, it's normal: https://github.com/angular-ui/ui-router/blob/master/src/state/stateService.ts#L306-L313

You can customize the `defaultErrorHandler` though if you want.

https://ui-router.github.io/docs/latest/classes/state.stateservice.html#defaulterrorhandler

**Comment by christopherthielen** [comment]
https://github.com/angular-ui/ui-router/pull/2835 seems to attempt to address this problem.  I'm not sure about the approach though.

**Comment by shawnlan** [comment]
To customize the `defaultErrorHandler`, do I do `$state.defaultErrorHandler` in any controller or in a `run` block? Or should I do it in the `config` block?

**Comment by christopherthielen** [comment]
@shawnlan do it in the run block

```js
app.run(function ($state) { 
  $state.defaultErrorHandler(function(error) {});
});
```

**Comment by karensg** [comment]
Just discovered the same issue. Looking forward for a fix :)
But until then switching back to stateEvents and `$locationChangeStart`.

**Comment by zxjon22** [comment]
Any movement on this? I see the issue has been closed but the bug still exists. Thanks.

**Comment by snehal4it** [comment]
I am still facing the same issue.

I used following work around when user cancelled the transition on back button.
```
let href = this.stateService.href(transition.from().name, transition.from().params);
window.history.pushState(null, 'Back button: History Fix', href);
```
