### ISSUE TITLE
crashed when used with <base href="/any-base/">

### ISSUE THREAD

**Issue by prasgema** [angular-ui/ui-router#2988]
Wasn't sure if I have to post this in `ui.bootstrap` or `ui.router`
But it happens when you are using `<base href="/any-base/">` altogether with `ui.router` and `ui.bootstrap` I can't seem to get out of the problem. At first, I thought this is a problem with `ui.router`; turns out when you comment the ui.bootstrap in angular dependencies, the problem stops.

The problem it caused is a continuous loop to load the required js files
![continuous](https://cloud.githubusercontent.com/assets/11336579/18436202/452fdd8a-7921-11e6-9f29-6778329b3487.png)

The problem does not happen when you are using `<base href="/">` or `<base href="/any-base">` but this doesn't produce wanted result. the use case is that: like to make a multiple-angular-UI application (suppose `https://host` is where I store the primary application), I need to make a separate angular application by heading to `https://hosts/admin`, using the same API as frontend. Using a <base href="/any-base"> will result all `ui-sref="..."` routes the link to `https://hosts/admi/path/to/route` instead of `https://hosts/admin/path/to/route`

Here's the example of code where it loads js infinitely
https://embed.plnkr.co/Nw4fPlELncOPoWdB2ehe/
although it won't work if not hosted on a single host

Angular: 1.5.8
UIBS: 2.1.3
UIR: 0.3.1
Bootstrap: 3.3.7

**Comment by eddiemonge** [comment]
@christopherthielen wasn't this fixed (where the last character in base was getting stripped) or did we punt it off to the angular team since it was a bug in ng core?

**Comment by christopherthielen** [comment]
@eddiemonge I honestly don't recall...  #2357 maybe?
