### ISSUE TITLE
Default params not loaded on nested state change

### ISSUE THREAD

**Issue by hackel** [angular-ui/ui-router#2989]
FYI I'm still using ui.router 0.3.1

When changing between child states, the default params defined in the new state are not being loaded.  I have these three states:
```js
.state('article.show.page', {
    url:   '^/pages/{id}?preview',
    views: {
        '@': {
            templateUrl: 'page.html',
            controller:  $stateParams => {
                console.log($stateParams); // not called when nativating to 'advertisers' state
            },
        },
    },
})
.state('static', {
    parent: 'article.show.page',
    url:    '^/{id:privacy-policy|reprints|unsubscribe-successful}',
})
.state('advertisers', {
    parent: 'article.show.page',
    url:    '^/advertisers',
    params: {id: 'advertisers'},
    data:   {},
})
```

If I am on the 'static' state and click on a link to 'advertisers', the URL changes, but the new id does not get set, so the content of the page remains that of the previous 'static' state.  The controller also never fires.

The reason I'm doing this is that I need to add some custom data to the 'advertisers' state.  I discovered that I can make it work if I change the url to `'^/{id:advertisers}'`, but then I have to link to it with `ui-sref=advertisers({id:'advertisers'})` which seems redundant.

Any ideas?

**Comment by christopherthielen** [comment]
the `params: {}` block defines the parameters **for the same state**.  It can't be used to set a default value for a parameter that is defined on a parent state.

In fact, I'm surprised that your `static` state works.  We never supported multiple parameters using the same name (`id`) on parent/child states.

I think the best you can get in 0.3.1 is a `$stateChangeStart` handler that checks for an empty `id`, then cancels the transition and starts a new one with the `advertisers` value.

**Comment by hackel** [comment]
Hmm, I guess it is only working for the static state because I am (re-)defining {id} in the URL, but not in the advertisers state?

Basically all I need is a way to specify that at a particular URL, the state should look exactly like this other state (same views/controller/resolves, etc.), but with this specific id parameter value, and this extra data.  Would it make more sense to simply have give the advertisers state a small controller that changed to the desired state with location=false?

It seems like coding an exception in $stateChangeStart would basically be like writing my own routing implementation that runs on every request.

**Comment by christopherthielen** [comment]
> Hmm, I guess it is only working for the static state because I am (re-)defining {id} in the URL, but not in the advertisers state?

That seems plausible.

> Would it make more sense to simply have give the advertisers state a small controller that changed to the desired state with location=false?

That would probably work but seems like a kludge to me

> It seems like coding an exception in $stateChangeStart would basically be like writing my own routing implementation that runs on every request.

It's more akin to the transition hooks in 1.0 and I think it's an ok level abstraction.  In 1.0: 

```js
const advertisersHook = transition => 
    !transition.params().id && $state.target('advertisers', { id: 'advertisers'})
$transitions.onStart({ to: 'advertisers' }, advertisersHook);
```

or, more generally:

```js
const fancyHook = transition => 
    !transition.params().id && $state.target(transition.to(), { id: transition.to().data.pageId })
$transitions.onStart({ to: (state) => !!state.data.pageId }, fancyHook);

...

.state('advertisers', {
    parent: 'article.show.page',
    url:    '^/advertisers',
    data:   { pageId: 'advertisers' },
})
```

**Comment by hackel** [comment]
Aha, of course it makes sense to put the pageId in the state data.  Thanks for that!  I hope I can cobble together some extra hours to upgrade this project to 1.0 soon.

**Comment by christopherthielen** [comment]
The state change start event should be able to do the trick in 0.3.1, if
you can't upgrade.
