### ISSUE TITLE
1.0 How to reload parent when transitioning from child to parent?

### ISSUE THREAD

**Issue by shawnlan** [angular-ui/ui-router#2992]
Suppose I have the following states:

'parent'
'parent.child'

Is it possible to reload 'parent' every time transitioning from 'parent.child' back to 'parent'? Or is it possible to make a state always reload? Ex. a back button click.

I thought I can use 'uiOnParamsChanged' from 'parent' since my 'parent.child' has some parameters. However, 'uiOnParamsChanged' isn't called when transitioning from 'parent.child' to 'parent'.

**Comment by christopherthielen** [comment]
`uiOnParamsChanged` is called when a parameter value change
You want `$state.go("parent", undefined, { reload: true })` or even `$state.go("parent", undefined, { reload: 'parent' })` if you want to get fancy

With ui-sref it would be `<a ui-sref="parent" ui-sref-opts="{ reload: true }">parent</a>`

**Comment by shawnlan** [comment]
I know, but when a user click "back" button, I still don't get the parent reloaded.

**Comment by christopherthielen** [comment]
Oh, I see what you are asking now, sorry about that.

```js
$transitions.on({ to: 'parent' }, trans => 
    !trans.options.reload && $state.target('parent', undefined, { reload: true }));
```

**Comment by shawnlan** [comment]
Thanks.

BTW, an earlier comment you used `reload:'parent'`. What does it do? The docs says it only takes boolean, right?

**Comment by christopherthielen** [comment]
> What does it do?

It reloads starting at the given state (and all its active child states)

https://ui-router.github.io/docs/latest/interfaces/transition.transitionoptions.html#reload

**Comment by shui91** [comment]
@christopherthielen is this still the best way to handle the case where a user moves from `parent.child` to `parent` via a 'back' button click?

I understand that a parent state's resolves are not called again when moving from the child to parent state. But I would like to force a reload and I'm not sure what the current implementation looks like as it seems `$transitions.on` is no longer supported. Thanks
