### ISSUE TITLE
How to avoid controller re-initializing while tab changes ?

### ISSUE THREAD

**Issue by fireworkstudio** [angular-ui/ui-router#2993]
Take this example: I have two tabs: tabA and tabB,  both contain some text input and datatable component.  First fill some data in tabA and then press tabA's search button, tabA's datatable will present data sent from server. Then switch to tabB and return to tabA. The data in text input and datatable disappeared as the tabA's controller reinitialized.

I tried some methods , such as 
$state.transitionTo(tab.route, tab.params, { reload: false,  inherit: false, notify: true  });

but still not resolved. 
BTW, I am using AngularJS 1.3.9,  UI-Router  0.2.18

Thanks

**Comment by christopherthielen** [comment]
That sounds a lot like [ui-router-extras sticky states](http://christopherthielen.github.io/ui-router-extras/#/sticky)

There is no other built in way to keep two _*states*_ active.  However, you could possibly also combine your tabA and tabB into a single state, but then you'd have to manage the components inside them yourself.
