### ISSUE TITLE
1.0 $scope.$watch('$destroy') is called when the state is loaded. Why?

### ISSUE THREAD

**Issue by shawnlan** [angular-ui/ui-router#2998]
Check the plunker here: http://plnkr.co/edit/HclyeeDmJKrXSnlweDsS?p=preview

$scope.$watch('$destroy') should be called when $scope is about to be destroyed, right? Why is it called when the state is just loaded?

**Comment by christopherthielen** [comment]
`$scope.$on` 👍

**Comment by shawnlan** [comment]
Yeah I realized.... Thanks!
