### ISSUE TITLE
Angular module load errors are suppressed when they occur as part of UI-Router resolution

### ISSUE THREAD

**Issue by fluffynuts** [angular-ui/ui-router#2999]
I've spent about 2 hours trying to track this down -- the first hour mainly scratching my head, trying to figure out what "suddenly changed" in my app to break it.

The short version is that I inadvertently named a service differently from the name I used to attempt to inject said service. There is a bit of a dependency chain, but at the top is a login service which I'm pulling into the (default) abstract state:
```
  $stateProvider.state('app', {
    abstract: true,
    resolve: {
      auth: ['login', function () {
         console.log('start..?');
      }]
    },
    views: {
      header: {
        template: '<header></header>'
      },
      footer: {
        template: '<footer></footer>'
      }
    }
  });
```
Angular fails to resolve the `login` service (because of a misnamed dependency) but the error is suppressed (does not appear in the console). In addition, because this service is not resolved, UI Router fails to initialize and I just end up staring at a blank page -- no console output, no error.

A work-around (found from StackOverflow) is to listen for $stateChangeError events:
```
  $rootScope.$on('$stateChangeError', function (ev, toState, toParams, fromState, fromParams, error) {
    if (error) {
      console.error(error);
    }
  });
```
Obviously this has to be done early on, otherwise the error still doesn't show. The workaround I'm using at the moment is a service which does this and then I request resolution of that service before resolution of the login service:
```
...
resolve: {
   auth: ['logRouteErrors', 'login', function() {
   }
}
...
```

But this is fragile as any error which potentially happens before this is still suppressed.

Not having a full knowledge of the internals of UI Router at this point, I'd like to suggest that, at the very least, the above handler be added by default -- suppressing errors just leads to hours of frustration on the part of the hapless developer (read: me), trying to find the source of a problem which was actually trivial to fix. Probably better would be finding the cause of the suppression and eliminating it.

**Comment by fluffynuts** [comment]
Eh, wait, I think I may need more info here. The problem is real, but my solution may not be (the subscription). Will re-submit when I can confirm a work-around.

**Comment by christopherthielen** [comment]
> above handler be added by default

1.0 has a [`defaultErrorHandler`](https://ui-router.github.io/docs/latest/classes/state.stateservice.html#defaulterrorhandler)

**Comment by fluffynuts** [comment]
That's great -- except a developer has to activate this just to get back errors that they would have gotten from angular core. If they don't know that ui-router can suppress errors, then they waste time trying to figure this out -- in my case, around 2 hours. And the SO thread I got the idea from was answered by someone with exactly the same frustrations. Please consider this for a fix in ui-router: libraries should not suppress each others' messages.

**Comment by christopherthielen** [comment]
1.0 has `defaultErrorHandler` which is enabled *by default*

**Comment by fluffynuts** [comment]
That's great -- how do I get it? The angular-ui-router package at npmjs.com is at version 0.3.1. So anyone using 
```npm install angular-ui-router``
(such as most people packing with webpack, for example) will get this apparently quite outdated version. 

I also don't know (perhaps you could elucidate) if 1.0 supports Angular 1? Angular 2 is great and all, but the RCs are still churning a little too much for production work, imo.

Side-note: if the default was working for me, surely I wouldn't have bothered with opening a ticket? Did it occur to perhaps ask why, when this has been fixed in 1.0, I would raise a ticket about it? Or did you just assume I was being a dumbass? The point of raising a ticket is not just to whine about it -- for someone not already embedded in the code, reporting bugs is the next best thing to creating a PR.

**Comment by christopherthielen** [comment]
> [0.3.1] apparently quite outdated version

0.3.1 is still the latest _stable_ release.  1.0 is in beta, rapidly approaching final release. You can get 1.0 from npm like so: 

`npm install angular-ui-router@1.0.0-beta.2` or even `npm install angular-ui-router@next`

> you should expect reports of errors already fixed upstream when you haven't updated the package, no?

Yes definitely... there's no problem with bug reports like this.  I closed this issue because the fix is complete, and already merged to `master`.

>  if 1.0 supports Angular 1?

1.0 supports both angular 1 (as `angular-ui-router`) and angular 2 (as `ui-router-ng2`).  This [migration guide](https://ui-router.github.io/guide/ng1/migrate-to-1_0) has details about 1.0 (and the default error handler in particular.

**Comment by fluffynuts** [comment]
Thanks kindly for the response. It really is appreciated. 

At the risk of sounding like a spoilt, pushy user, is there an eta (no matter how rough) on a final release for 1.0? Knowing a timescale would help me decide whether to use vnext or leave my kludgy workaround in place. I'm just trying to make the best decision for a project barely started, but which should run for a while henceforth, bearing other (less experienced) team members in mind. In other words, I'd like to leave the code with the least "wat", should I mysteriously disappear. 
I'd like to reiterate appreciation for your time spent on this ticket and apologize if I came off abrasively. It's been one of those days :/

**Comment by fluffynuts** [comment]
BTW, "it will be ready when it's ready" is also an acceptable answer (:

**Comment by christopherthielen** [comment]
If it takes longer than a month to get 1.0 final out the door, I'll be very disappointed.

**Comment by fluffynuts** [comment]
Excellent! The kludge remains, with a TODO to remove it in preference of updating to 1.0, when released. Thanks again for the prompt response.
