### ISSUE TITLE
UI Router transitions back to the previous state

### ISSUE THREAD

**Issue by guranjanpsingh** [angular-ui/ui-router#3003]
I have an application that contains multiple SPAs. I use MVC routing to serve each SPA and withing each SPA I use angular ui router to handle the routing. 

Here's how my route config:

```
     angular.module('settings').config(routeConfig);

    routeConfig.$inject = ["$stateProvider", "$urlRouterProvider"];
    function routeConfig($stateProvider, $urlRouterProvider) {

    // default route
    $urlRouterProvider.when('', 'Tab1');

    $stateProvider.state('Tab1',
    {
        url: '/Tab1',
        templateUrl: '/link/To/template.html',
        controller: 'tab1controller as ctrl'
    });

    $stateProvider.state('Tab2',
    {
        url: '/Tab2',
        templateUrl: '/link/To/template.html',
        controller: 'tab2controller as ctrl'
    });
    $stateProvider.state('Tab3',
    {
        url: '/Tab3',
        templateUrl: '/link/To/template.html',
        controller: 'tab3controller as ctrl'
    });
```

If i'm not on Tab1 and I click the link, created by ASP.NET MVC to go to the same page. I end up on the Tabs 1 because of `$urlRouterProvider.when('', 'Tab1');` however if I then click on any other tab, ui-router will transition to the tab I just clicked but it will transition be back to `Tab1` right away.

One solution I found was to change `location: true` to `location: false` in the transitionTo function. But that could effect other functionality.

I haven't been able to recreate it on plnkr but [here](http://stackoverflow.com/questions/39501862/angular-ui-router-transitions-back-to-the-previous-state) is a link to the stackoverflow question I posted

**Comment by eddiemonge** [comment]
Closing as you have this open on SO. This doesn't seem like a bug but rather maybe something wrong with your server since it seems to work on plnkr
