### ISSUE TITLE
1.0 uiView inside conditional ngInclude causes "Cannot read property '$$animLeave' of undefined"

### ISSUE THREAD

**Issue by shawnlan** [angular-ui/ui-router#3004]
Here is the test case: http://plnkr.co/edit/EuWGIKcyXCTY1vHiQXMj?p=preview

The error happens when:

1. uiView inside a conditional ngInclude
2. Switch ngInclude from On to Off and then back to On
3. Go to a different root state

Any workaround before a fix?

Here is what I'm trying to do:

A not-logged-in user can go to any url, but he/she will see a login form. Once he/she logs in, he'll see that url's corresponded state view.

Should I go with a different approach? lazyLoad/future states that register after a user logs in? I'm not quite sure how that works.

**Comment by christopherthielen** [comment]
Thanks for the bug report.  This is definitely something we should support.  

Targeting 1.0-final.

**Comment by christopherthielen** [comment]
It was an off-by-one error.  Fix should be coming tonight in beta.3

http://plnkr.co/edit/AELsuLBrGi73XTldkZgY?p=preview

**Comment by shawnlan** [comment]
Nice. Thanks!

**Comment by abbymrs** [comment]
@christopherthielen 
Hi, I also got this error after i updated my application from angular version 1.5.0 to 1.6.5 with @uirouter/angularjs version 1.0.5.
It only happens with the sub-router with params, like "/demo/lists/:id", could you pls kindly give me some help? 
Thanks a lot!

**Comment by hani647** [comment]
@christopherthielen 
Same problem with me. In addition inside my ui-view container I can see 2 ui-view i.e. 
```
<div ui-view>

    </div >
```
now when I call a state then I can see in my element inspector
```
<div ui-view>

    </div >
<div ui-view>

    </div >
```
Any help would be appreciated !

**Comment by JamesPJ** [comment]
The error still reproducible when using `uiRouter` with `ui-bootstrap-tpls.js`
