### ISSUE TITLE
error: 'Right-hand side of 'instanceof' is not an object' after updating to 2.0.0

### ISSUE THREAD

**Issue by kolkov** [angular-ui/ui-router#3006]
Hi! After upgrading to 2.0.0 I got a error:

![image](https://cloud.githubusercontent.com/assets/3740898/18595717/9663eb8a-7c4e-11e6-979f-af64da2858ec.png)

and in the:
```
@UIRouterModule({
  imports: [
    CommonModule,
    NgbModule,
    FormsModule,
  ], 
```
![image](https://cloud.githubusercontent.com/assets/3740898/18595957/b57d98d0-7c4f-11e6-9fb8-874fa4045065.png)

![image](https://cloud.githubusercontent.com/assets/3740898/18595885/5476a266-7c4f-11e6-9b88-94e6f04fc30b.png)

**Comment by christopherthielen** [comment]
Hey thanks for this.  

I'm reworking the approach to `NgModule` support.  My original approach wouldn't work with AoT compile.  We'll be nuking the `UIRouterModule` decorator in favor of an approach like the v3 router with `forRoot()` and `forChild()` factory methods.

Once that lands, I'll take a closer look at this PR.

**Comment by christopherthielen** [comment]
I think this was fixed by 7c54b751bf25f3f07250bc9769917d58b1d30934

**Comment by erik-ropez** [comment]
Getting same error with 1.0.0-beta.2 .

**Comment by erik-ropez** [comment]
Is there workaround for this? Cannot find what exactly in my app is causing this issue. Commented out almost everything in my app but still getting this error. Is this error happens to everyone using 1.0.0-beta.2 or there is something specific in configuration, etc.?

**Comment by kolkov** [comment]
@erik-rope, what version of typescript you are using?

**Comment by erik-ropez** [comment]
@kolkov I'm actually not using TS. Using ES6 instead. How is it related?

**Comment by christopherthielen** [comment]
Angular 2.0.0 removed all the `*MetaData` classes.  We were checking `instanceof ComponentMetadata`, but ComponentMetadata is `undefined` in 2.0.0.

https://github.com/angular-ui/ui-router/commit/7c54b751bf25f3f07250bc9769917d58b1d30934#commitcomment-19100421

This hasn't been released, but will be as beta.3 (later this week, probably)

**Comment by christopherthielen** [comment]
@erik-ropez you can either:

- wait for beta.3 and stay on angular 2.0.0-rc.6
- build ui-router-ng2 off `master` today

**Comment by erik-ropez** [comment]
@christopherthielen, tried to build but failed with #3025.

**Comment by kolkov** [comment]
Thanks! Fixed with new version.

**Comment by christopherthielen** [comment]
@erik-ropez if you're still having trouble building, I built latest master: 

https://rawgit.com/christopherthielen/4170db48d3cafd3dc5948042fdaa7312/raw/54f4910fdca5c9c6afb5eddee3d6fc2476d73c4c/ui-router-ng2.js

**Comment by ravind996** [comment]
in Angular6 am getting below error
![image](https://user-images.githubusercontent.com/8157574/43836501-2d78b21c-9b33-11e8-9568-02990c8c5bb5.png)
