### ISSUE TITLE
core.umd.js:3462 EXCEPTION: Error in ./UIView class UIView_Host - inline template:0:0 caused by: No provider for Token UIRouter Module Options!

### ISSUE THREAD

**Issue by kolkov** [angular-ui/ui-router#3009]
Hi!
After updating my project for compatibility ui-router-ng2 1.0.0-beta.3 according quickstart-ng2 rules, I got an error:
![image](https://cloud.githubusercontent.com/assets/3740898/18607710/8c778fac-7cdd-11e6-802d-fa23ee227f84.png)
`core.umd.js:3464 ORIGINAL EXCEPTION: No provider for Token UIRouter Module Options!`
What this?

**Comment by kolkov** [comment]
Why all apps must contain RootModule and at least one ChildModule?
![image](https://cloud.githubusercontent.com/assets/3740898/18608467/c7877a34-7cf2-11e6-84c7-a92efbfc1418.png)
After I uncommented one child module in `imports` error has disappeared. (((

**Comment by christopherthielen** [comment]
> Why all apps must contain RootModule and at least one ChildModule?

That wasn't intentional.  I'll work on a fix

**Comment by kolkov** [comment]
Thanks! For a long time could not understand why the most simple configuration does not work...))
