### ISSUE TITLE
Multiple views as one list structure

### ISSUE THREAD

**Issue by golaod** [angular-ui/ui-router#3011]
From what I was able to read in the doc and all examples I could find with google and stackoverflow, there is way to have many NAMED views, but there is no list type view which can let to display many dynamic list of views with one directive.

I mean, I understand to have structure like:

```
ui-view="head"
ui-view="body"
ui-view="footer"
```

but I would also like to have something like

```
ui-view="widgets"
addView('widgets', {template:'firstWidget.html', controller: A})
addView('widgets', {template:'secondWidget.html', controller: B})
```

and I can set as many elements as I want. I don't know if anyone is familiar with magento layout xml pattern where classes and views are divided by layout xml files which can let developer to structure everything how they want. I can add elements to elements, move them, remove etc. Of course I'm not asking about such flexibility, but just wanted to know if there is a way to have one ui-view which can display dynamic LIST of views.

**Comment by christopherthielen** [comment]
I recommend orchestrating this sort of thing in a single component (where a "component" is *either* an angular `.component()` or a template/controller combo).  

Use that single component as the state's view.  In the component, compose your other components however you need to.


```
.component('widget', {
 template: '<first-widget></first-widget>' +
   '<second-widget></second-widget>'
});
```

**Comment by golaod** [comment]
But it's the same 'precomposed' view. I can't change the template and I was rather wanted to achieve something like `template: viewService.getViewsFor('widgets')` and modules can do `viewService.registerViewFor('widgets', '<my-view>')`

I'm thinking about solution where modules can be enabled/disabled installed/removed etc.

**Comment by christopherthielen** [comment]
The views paradigm is already confusing enough to many users, and there are other ways to compose multiple views together.  I'm afraid I'm going to have to say no to the "array of views" syntax.

>  I can't change the template and I was rather wanted to achieve something like template: viewService.getViewsFor('widgets')

You can use a `templateProvider` (https://ui-router.github.io/docs/latest/interfaces/ng1.ng1viewdeclaration.html#templateprovider) to generate a template on the fly.

**Comment by golaod** [comment]
Damn, I forgot to answer. Deeply sorry for that.
Thanks for the help, it worked. I didn't know there is template and controller Provider available.
