### ISSUE TITLE
How can I pass dependencies to $transitions::onStart?

### ISSUE THREAD

**Issue by langdonx** [angular-ui/ui-router#3013]
Checked documentation and searched previous issues but can't really seem to get it working.  Check console:

http://plnkr.co/edit/d7QByg1eDuNtPK0SrpUk?p=preview

**Comment by langdonx** [comment]
Half the story: https://github.com/angular-ui/ui-router/commit/ca45957901d53a77f69074d15ea87baf1b78a48c

The other half: https://github.com/angular-ui/ui-router/commit/421bca7b8013b4c20b1a558e55245305a18c69f5

And documentation I couldn't find before: https://ui-router.github.io/docs/latest/classes/transition.transitionservice.html#onstart

:)

**Comment by christopherthielen** [comment]
You got it!  I know its more difficult to find the "important stuff" in the new docs.  I'm trying to figure out what to do about that.  We've got plans for more freform "guides" (for instance, one on Transitions is in the works).

I'd also highly recommend reading over: https://ui-router.github.io/guide/ng1/migrate-to-1_0
