### ISSUE TITLE
$stateChangeSuccess fires before url is updated

### ISSUE THREAD

**Issue by ThomasJuhasz** [angular-ui/ui-router#3015]
I wanted to use this event with google analytics, like so:

`function stateChangeGA() {
        $rootScope.$on("$stateChangeSuccess", function ($currentRoute, $previousRoute) {
                window.ga('send', {
                    hitType: 'pageview',
                    page: location.pathname + location.search + location.hash,
                    title: document.title
                });
        });
}`

but it was always the last url that got sent to GA, turns out the $stateChangeSuccess event fires just before the url is updated.
I used a $timeout as a workaround:
`$timeout(stateChangeGA, 0);`

**Comment by zeusdeux** [comment]
This might have to do with the fact that the url is updated post notify as you can see here: https://github.com/angular-ui/ui-router/blob/legacy/src/state.js#L1170

You can try switching up locally and seeing if that fixes your usecase.

PS: That the legacy code base as my assumption is that you are on version 0.x.x

**Comment by michelalbers** [comment]
+1
