### ISSUE TITLE
Option to remove hash in URL on state change.

### ISSUE THREAD

**Issue by jeffrey-ng** [angular-ui/ui-router#3017]
Is there a way of removing the hash from the URL on state change?

There are some situations where the a hash value may be used on multiple pages and having it stay within the URL on stage change may cause some issues.

Example: Going from `https://example.com/page1#bottomsection` to `https://example.com/page2#bottomsection` is undesired.

**Comment by christopherthielen** [comment]
Hash is tracked using a parameter named '#'.

You can clear out the hash by clearing out that parameter:
`$state.go('foo', { "#": undefined })`

Note that browsers may keep the "#" in the URL even though it's empty.  See this comment: https://github.com/angular-ui/ui-router/issues/2900#issuecomment-239493266

I think this answers the question, so closing.

**Comment by christopherthielen** [comment]
Reopening to track this.

I'm making the hash not-inherited by default.  It seems likely that most people would expect the hash to be cleared out upon subsequent navigations.

**Comment by christopherthielen** [comment]
Closed by 849f84f7c35530b01d3ebae1a2fd500c2eebda21 in rc.1
