### ISSUE TITLE
Detect state name that served component inside of component

### ISSUE THREAD

**Issue by langdonx** [angular-ui/ui-router#3022]
I'm using nested views and `angular.component`.  Basically:

	// /jobs
	$stateProvider
		.state({
			name: 'ctk.job',
			url: '/jobs',
			component: 'jobList'
		});

	// /jobs/#
	$stateProvider
		.state({
			name: 'ctk.job.detail',
			url: '/:jobId',
			component: 'jobDetail'
		});

If I inject `$state` into both my jobList and jobDetail components, I can determine that `$state.$current` is `'ctk.job.detail'`, but I want to determine which state loaded the particular component.  In this case it would be:

 - jobList: `'ctk.job'`
 - jobDetail: `'ctk.job.detail'`

Is it possible to derive this information from `$state` or is there something else I can inject?

**Comment by christopherthielen** [comment]
It's undocumented, but you can get the `$uiView` information off the **element**.
I think you can inject `$element` into the component controller, then inspect `$element.inheritedData('$uiView')`

Note: this $uiView API  is not documented and is subject to change.

**Comment by christopherthielen** [comment]
Closing because I think the question is answered
