### ISSUE TITLE
[ng2] content inside <ui-view> not rendred

### ISSUE THREAD

**Issue by aitboudad** [angular-ui/ui-router#3023]
https://plnkr.co/edit/crZsgXbryYqZUKEKfloB?p=preview

``` ts
@Component({  
  template: '<ui-view><h3>Hello world!</h3></ui-view>' 
})
class Hello { }
```

**Comment by christopherthielen** [comment]
Thanks for the plunker.

This isn't something we've attempted to implement yet.  I'll look into doing it in the future, or accept a PR that implements it.

**Comment by Kamshak** [comment]
Don't really understand what this would do. Would this be displayed until the initial state's template is loaded? Or would it stay and the content would be inserted somewhere (but you could do that easily with abstract states)?

**Comment by christopherthielen** [comment]
@Kamshak the request is to display something while the ui-view isn't being "filled" by a view from a state.  Imagine something like: 
```
// Inbox
<messagelist></messagelist>
<ui-view>No message loaded</ui-view>
```

```js
{ name: 'inbox', url: '/' component: Inbox },
{ name: 'inbox.message' url: '/message/:id', component: Message }
```
When `inbox` state is active, there is nothing loaded in the uiview.
When `inbox.message` is active, the ui-view is filled by the Message component
