### ISSUE TITLE
NPM angular2

### ISSUE THREAD

**Issue by kluevandrew** [angular-ui/ui-router#3024]
Please update npm package https://www.npmjs.com/package/ui-router-ng2
At  this moment i can't install a latest version of ui-router for using with angular2 release

**Comment by christopherthielen** [comment]
beta.3 should be ready in the next couple of days

**Comment by kluevandrew** [comment]
> beta.3 should be ready in the next couple of days

Many thanks for your quick reply. We use ui-router in production and it is very important to us.
