### ISSUE TITLE
Missing scripts/package.sh file for building a package

### ISSUE THREAD

**Issue by erik-ropez** [angular-ui/ui-router#3025]
https://ui-router.github.io/ng2/ indicates to run `./scripts/package.sh ng2` but such file doesn't exist. How can I build a package?

**Comment by kolkov** [comment]
https://github.com/angular-ui/ui-router/blob/master/CONTRIBUTING.md

**Comment by christopherthielen** [comment]
Oh, I think that's a typo. It should be `.js`. Run using `node scripts/package.js`. I don't know if it works on Windows, sorry. 

I'm hoping to release beta.3 in the next couple days by the way.

**Comment by christopherthielen** [comment]
I've updated the https://ui-router.github.io/ng2/ site, thanks!
