### ISSUE TITLE
$stateParams = { #: null } after target with param args returned from transition

### ISSUE THREAD

**Issue by garywgentry** [angular-ui/ui-router#3030]
Using 1.0-beta.1, I'm trying to follow the pattern to hook the onStart transition, check for authentication then return a Target to redirect to my login form state.  I want to pass along the originally requested state name /params as parameters to the target login form state.  

My hook looks like this:

```
    $transitions.onStart({}, (trans) => {

        var toState = trans.$to();
        var toStateName = toState.name;
        var toStateParams = toState.params;
        if (!(toStateName == 'app.login')) {
            return authenticationService.verifyAuthenticated().catch(() => {
                var target = trans.router.stateService.target('app.login', { redirectToStateName: toStateName, redirectToStateParams: toStateParams });
                return target;
            });
        }

    });
```
I confirmed the arguments to target are proper.  This gets called a second time for app.login state (and hits the conditional block returns nothing).  app.login is then called and the params that make it to the controller is {#:null}.  Same value on $stateParams and $state.router.globals.params.

```
constructor(private $stateParams: ng.ui.IStateParamsService, private $state: ng.ui.IStateService) {
        // $stateParams = { #: null }
        // $state.router.globals.params = { #: null }
    }
```
Am I mis-understanding how this should work?  My understanding from the docs is returning the target with a params argument should pass those params to the target state.

**Comment by christopherthielen** [comment]
@garywgentry can I see the `app.login` state? It should have parameters defined for `redirectToStateName` and `redirectToStateParams`

```
.state('app.login', {
  url: '/login',
  params: {
    redirectToStateName: null, // non-url parameters
    redirectToStateParams: null
  }
});
```

Alternatively, when redirecting to 'login', the  `$transition$` contains the information about where you came from.  Check out how we did it in the sample app:

https://github.com/ui-router/sample-app-ng1/blob/master/app/main/app.states.js#L44-L83

**Comment by garygentry** [comment]
Doh!  That was it, did not have the params.. 

Looking at the $transition$ approach, is that the latest api in the sample? $transition$.redirectedFrom() doesn't seem to exist, and looking through the object in the debugger not seeing where the originally requested state data is.

Thanks!

**Comment by christopherthielen** [comment]
In beta.2 , `$transition$.previous()` was renamed to `$transition$.redirectedFrom()`

Make sure you're on beta.2  or higher (releasing beta.3 tonight)
