### ISSUE TITLE
element.bind is not a function with jquery.slim version

### ISSUE THREAD

**Issue by navarroaxel** [angular-ui/ui-router#3035]
The ```.bind()``` method has been deprecaten in [version 3.0+](http://api.jquery.com/bind/).

But in the **slim build** of jQuery the method has been removed directly. So, the uiSref directive fails when tries to attach a handler to the click event.

Plunker with the error in the console: https://plnkr.co/edit/2dceELuWmG2wq3027gwD

This only occurs with the slim build. This is not failing with jqLite or jQuery full build.

Can we add support to the slim build? jqLite also supports the ```.on()```` method. We just need to replace the bind with the on and this issue is resolved.

**Comment by christopherthielen** [comment]
Closed by #3036
