### ISSUE TITLE
Help~~how to save prev scope on back

### ISSUE THREAD

**Issue by jiw0220** [angular-ui/ui-router#3041]
from "ListPage" go "DetailPage"
from "DetailPage" back "ListPage" restore search conditions by "ListPage" scope
～
pls help me～～

**Comment by christopherthielen** [comment]
Hi, thanks for your interest in UI-Router!

It sounds like you should save your search conditions as parameters.

For further support and how-to requests, please use StackOverflow, a fantastic community site for questions and answers:  http://bit.ly/UIR-SOF
