### ISSUE TITLE
StateProvider.onInvalid - ignoring depending on filter and having more than 1?

### ISSUE THREAD

**Issue by ianjohnspain** [angular-ui/ui-router#3042]
Hi,

I have an external service that is being loaded via ocLazyLoad and I am checking for onInvalid but I need to an additional check inside to ensure they are trying to go to a specific router.

If I find they are not going to a specific route, can i just ignore it ? I have tried using 'return', is this sufficient to ignore the onInvalid ?

here is what I am doing

```
    $stateProvider.onInvalid(($to$, $from$, $state, $ocLazyLoad) => {
      'ngInject';
      if (!_.startsWith($to$._identifier, 'external.module')) {
            return;
      }

      // Continue loading module and rerouting to state using $state.go($to$)
```

Also is it possible to setup more than 1 onInvalid ? As long as I filter each one ?

Any ideas really helpful

Thanks

**Comment by christopherthielen** [comment]
> If I find they are not going to a specific route, can i just ignore it ?

Yep.  If onInvalid returns a HookResult, we will process it.  Everything else is a noop.

> Also is it possible to setup more than 1 onInvalid ? As long as I filter each one ?

Yep, you can register multiple

It looks like you're trying to lazy load a module.  Have you tried `lazyLoad` from beta.3?
https://ui-router.github.io/docs/latest/interfaces/state.statedeclaration.html#lazyload

**Comment by christopherthielen** [comment]
Closing because no response and I believe the question is answered.
