### ISSUE TITLE
controllerProvider on Ng1ViewDeclaration should be of type IInjectable instead of Function

### ISSUE THREAD

**Issue by ciddan** [angular-ui/ui-router#3044]
I would expect this state definition to still be valid:

    .state("product.store.live", {
        url: "/live"
        views: {
            "storeView@product": {
                controllerProvider: ["options", storeControllerProvider], // <--- compilation fail
                templateUrl: "app/components/product/detail/shared/StoreView.html"
            }
        }
    })

Looking at the code in `ng1/statebuilders/views.ts#getController` the code looks for an ng1 array-notation-style array/function.

**Comment by christopherthielen** [comment]
yep, thanks for the report!
