### ISSUE TITLE
Nested state does not work without ui-view on the parent

### ISSUE THREAD

**Issue by svpace** [angular-ui/ui-router#3049]
Given the state below, "child" does not render

```
$stateProvider
.state({
    name:` 'parent',
    abstract: true
})
.state({
    name:` 'child',
    parent: 'parent',
    templateUrl: 'template.html',
    controller: controller
});
```

Everything works fine if I add a dummy template ('<ui-view></ui-view>') on the parent.

**Comment by christopherthielen** [comment]
did you add a dummy template '' or a dummy template `<ui-view></ui-view>`?  I would expect it to work only with the latter.

UI-Router views are placed into a `ui-view` that was created by the parent state. You must create a `ui-view` for the child to be placed into, or you can use view targeting to target the `ui-view` created in the root template.

You can read the gory details about view targeting here: https://ui-router.github.io/docs/latest/interfaces/ng1.ng1statedeclaration.html#views
