### ISSUE TITLE
Hook redirect does not update `transition.to().params`

### ISSUE THREAD

**Issue by csvn** [angular-ui/ui-router#3052]
I want to be able to navigate to a state, where a param may not yet be known:

```javascript
$stateProvider.state({
  name: 'foo',
  url: '/:value/foo',
  params: {
    value: null
  }
});
```

So when `value === null`, I want to redirect to a new state in a hook. The problem is, after the hook has run the first time, the `value` is still null the next time the `onBefore` hook runs:

```javascript
$transitionsProvider.onBefore({}, t => {
  let params = t.to().params;
  
  if (params.value === null) { // will still be `null` the second time this hook runs!
    let $state = t.router.stateService;
    return $state.target(t.to().name, { value: '123' });
  }
});
```

Is there something I am missing about using redirects, or is this a bug?

See codepen for example: http://codepen.io/csvn/pen/ALoJAo?editors=1010

**Comment by christopherthielen** [comment]
The thing you get out of `.to()` is the state definiution that you registered, i.e., the object literal:

```js
{
  name: 'foo',
  url: '/:value/foo',
  params: {
    value: null
  }
}
```

to get the parameter *VALUES* for a transition, use `transtion.params()`

http://codepen.io/anon/pen/LRzEJZ?editors=1010

Hope this helps!

**Comment by csvn** [comment]
Ahh... thanks for the clarification. I thought 'to()' was kinda like an object version of 'toState' and 'toParams' in the previous event syntax. I havent yet managed to get up to speed on all 1.0.0 changes yet.
