### ISSUE TITLE
Undefined params in transition hook

### ISSUE THREAD

**Issue by csvn** [angular-ui/ui-router#3053]
If a state does not have any params, `transition.to().params` will be undefined. This can make working with global hooks a bit awkward.

```javascript
$transitionsProvider.onBefore({}, t => {
  let params = t.to().params;
  
  if (params.value === null) { // params can be undefined => error!
    // do something
  }
});
```

This may be working as intended and I'm just doing things the wrong way, but it feels annoying if I need `Object.assign({}, t.to().params)` everywhere.

**Edit**
Codepen here: http://codepen.io/csvn/pen/vXJQLG?editors=1010

**Comment by christopherthielen** [comment]
Same issue as #3052

You want `t.params()` not `t.to().params`.

The `transition.to()` function returns the state definition object, as passed to `$stateProvider.state()`. The state definition is not mutated by ui-router.  Parameters are stored on the transition, not the state definition.

**Comment by csvn** [comment]
Yeah, sorry for this. I misunderstood the usage of `transition.to()`
