### ISSUE TITLE
$viewContentLoaded fired too early

### ISSUE THREAD

**Issue by thany** [angular-ui/ui-router#3055]
The `$viewContentLoaded` is fired too early. In the docs it says

> Fired once the view is loaded, _after_ the DOM is rendered.

This is not true, as far as I can tell. I'm trying to reference an element I know is going to be there, getting it by doing a simple `document.getElementById` on it, and it returns null. So the DOM hasn't been rendered yet.

When I delay that by 1 arbitrary millisecond, using a plain vanilla `setTimeout`, it gives me the element I wanted. So I'm doing it right, and this proves to me that the `$viewContentLoaded` is fired **while** the DOM is being rendered - not after it has been.

This is found at least with Angular 1.5.8, ui-router 0.3.1, and Firefox 49.

**Comment by mackelito** [comment]
Could you add your code so that we can see how you use it?

**Comment by thany** [comment]
It's too long ago, I've probably already put a worakround in place. Will post back when I re-encounter this problem.
