### ISSUE TITLE
About versions

### ISSUE THREAD

**Issue by rafakwolf** [angular-ui/ui-router#3058]
Hi, i'm a little confuse about the versions...

I'm using angular 1 and jspm, 0.3.1 is the latest stable version?

via jspm i'm installing like this   `jspm install angular-ui/ui-router=github:angular-ui/ui-router`

but 0.2.18 is installed always

thanks!

**Comment by christopherthielen** [comment]
we publish the angular 1 code to npm as `angular-ui-router`.  0.3.1 is the latest stable version. 1.0.0-beta.3 is the latest unstable version.  

With jspm you should use `jspm install angular-ui-router` which will fetch 0.3.1 from npm.

We tag the source code for each release, but no longer publish the bundles in the repository.  Tools like bower rely on the bundled files and github tags.  For that reason, we have a separate repo https://github.com/angular-ui/angular-ui-router-bower/ but we recommend people switch to `npm` and use the `angular-ui-router` package.

**Comment by rafakwolf** [comment]
@christopherthielen Thanks!
