### ISSUE TITLE
The proper approach to generate components based on data

### ISSUE THREAD

**Issue by archasek** [angular-ui/ui-router#3061]
Hi.

I have a structure in my project that is something like this :
![image](https://cloud.githubusercontent.com/assets/2247211/19081162/9737e1c4-8a59-11e6-92c9-8e97119382e8.png)

Footer and header are nested views.

`index.html`:
```
            <div data-ui-view="header"></div>
             <div data-ui-view="main"></div>
            <div data-ui-view="footer"></div>
```
routing:
```    $stateProvider
        .state('index', {
            abstract: true,
            views: {
                'header': {
                    component: 'headerComponent'
                },
                'footer': {
                    component: 'footerComponent'
                }
            }
        })

        .state('index.home', {
            url: '/',
            views: {
                'main@': {
                    templateUrl: 'boxesTemplate.html'
                }
            }
        });
```
The main section should include boxes (that are probably components?), as you can see at the screenshot. But the number of boxes and their content (like box heading) should be generated by data that is pulled from the backend using $http. 
Can I achieve this somehow?

Thanks

**Comment by christopherthielen** [comment]
I can't answer what is the "Proper approach", but here's what I'd do ;)

1) Decide what is responsible for fetching the backend data: Resolve or the component itself?

2) Use a parent component to orchestrate the remaining child components (boxes)


Something like this: 
```js
.component('boxesComponent', {
  bindings: { 'boxes': '<' },
  template: `
  <box-component ng-repeat="box in boxes" box-data="box">
  </box-component>
`
})
.component('boxComponent', {
  bindings: { 'boxData': '<' },
  template: `
      <ng-switch on="$ctrl.boxData.type">
          <foo-box  ng-switch-when="foo" box-data="$ctrl.boxData"></foo-box>
          <bar-box  ng-switch-when="bar" box-data="$ctrl.boxData"></bar-box>
          <baz-box  ng-switch-when="baz" box-data="$ctrl.boxData"></baz-box>
          
          <div ng-switch-default>
              <h5>Unknown {{$ctrl.boxData.type}} component type</h5>
          </div>
      </ng-switch>`
});
```

```js
        .state('index.home', {
            url: '/',
            resolve: {
              boxes: $http =>$http.get('/api/boxes').then(resp => resp.data)
            },
            views: {
                'main@': {
                    component: 'boxesComponent'
                }
            }
        });
```



Closing because I think I've answered the question.

**Comment by archasek** [comment]
@christopherthielen thank you very much for the help. 

I don't understand the `box-data="box"` part.
What if the response from API will be like this example?:
```
{
    boxes: [
        {
            name: 'foo',
            value: 'val1'
        },
        {
            name: 'bar',
            value: 'val2'
        }
    ]
}
```

> 1) Decide what is responsible for fetching the backend data: Resolve or the component itself?

What if I decided that it should be in the component instead of resolve?

Thanks

**Comment by christopherthielen** [comment]
> I don't understand the box-data="box" part.

I was showing an example of how you might write *your own* api.  I arbitrarily chose `box-data` as a component input to pass the data for a single box.

> What if I decided that it should be in the component instead of resolve?

Then you'd fetch the data from the component (probably in the constructor). 


But these questions aren't really ui-router related, they're just general ng 1.5 component questions.
