### ISSUE TITLE
[Resolve] async ResolvePolicy "RXWAIT" does not behave as expected

### ISSUE THREAD

**Issue by Kamshak** [angular-ui/ui-router#3066]
When returning an errored observable from a resolve factory the state transition never happens (state home.observable-that-throws). Furthermore, the items that are emitted after the first item don't seem to be passed on to the stream that is resolved (home.observable).

Plunker: http://plnkr.co/edit/x2mTrhH3RQuNV4fcXSrO?p=preview
Expected: http://plnkr.co/edit/MXMAAWLDD6jGUz99SDlG?p=preview

**Comment by christopherthielen** [comment]
Moved to https://github.com/ui-router/ng2/issues/20
