### ISSUE TITLE
$state is always null in $transitions.onBefore({}, function(transition, $state){})

### ISSUE THREAD

**Issue by ansorensen** [angular-ui/ui-router#3071]
Updated from 0.2.7 to 1.0.0-beta.2. In the old code I checked the auth token on every state change by using the $rootScope.on listing in the app.run function:

`app.run(['$rootScope', '$state', function ($rootScope, $state) {
    $rootScope.on('$stateChangeStart', function(event, ...) {
      // conditionals removed for simplicity
      event.preventDefault();
      $state.go('login');
    }); 
}]);`

In order to do the same thing in 1.0.0 the [docs](http://angular-ui.github.io/ui-router/feature-1.0/interfaces/transition.ihookregistry.html#data-driven-default-substate) give an example along these lines:
`
app.run(['$transitions', function($transitions) {
    $transitions.onBefore({}, function($transition$, $state) {
         // conditionals removed for simplicity
        return $state.target('login');
    });
}]);`

However, $state is _always_ null, resulting in a JS error "cannot read 'target' of null." [Plunkr here](https://plnkr.co/edit/FxpZyD2tf99HJdLgl3tw).

I've try using $transitions.onStart... same results. 

 I notice that [examples are inconsistent](http://angular-ui.github.io/ui-router/feature-1.0/interfaces/transition.ihookregistry.html#default-substate) with what params actually get fed into the call back (in this example, $state is the first param). However, with $state as the first param returns the error ($state.target is not a function), because it looks like the transition object is, in fact, the first param.

I found a [closed issue on the repo here](https://github.com/angular-ui/ui-router/issues/3030) that provides an alternate to 'return $state.target();'

`return $transition$.router.stateService.target('login')'`

This alternate form seems to work in the Plunkr (for all it's unsightliness). So is the null $state parameter a bug, or simply a case of out-of-date documentation?

**Comment by ansorensen** [comment]
Looks like old docs, found in [this](https://github.com/angular-ui/ui-router/releases/tag/1.0.0-beta.1) release notes.

**Comment by christopherthielen** [comment]
https://ui-router.github.io/docs/latest/classes/transition.transitionservice.html

**Comment by christopherthielen** [comment]
I'm going to try to set up some redirects where the old docs were

**Comment by christopherthielen** [comment]
The old docs are all redirecting to the new site at https://ui-router.github.io

**Comment by christopherthielen** [comment]
```
app.run(['$transitions', '$state', function ($transitions, $state) {
    $transitions.onStart({}, function(transition) {
      // conditionals removed for simplicity
      var to = transition.to();
      var params = transition.params();
      if (something) {
        return $state.target('login');
      }
    }); 
}]);
```
