### ISSUE TITLE
Transaction documentation has gone missing.

### ISSUE THREAD

**Issue by geoidesic** [angular-ui/ui-router#3073]
The link to this documentation is found on this page:
https://ui-router.github.io/guide/states

At the bottom of that page is a broken link: 
https://docs/latest/classes/transition.transitionservice.html

**Comment by christopherthielen** [comment]
Fixed, thanks!

**Comment by christopherthielen** [comment]
We've got a guide on Transitions in the pipeline. Stay tuned.
