### ISSUE TITLE
param with '~'(tilda) gets encoded as '~~' by $urlMatcherFactory.format

### ISSUE THREAD

**Issue by lucibit** [angular-ui/ui-router#3080]
As the title describes:

Tested with angularjs 1.5.8 and ui.router 1.0.0.beta3

See
https://plnkr.co/edit/00Ffv7TqsRh3vrfa4ZO5?p=preview

**Comment by christopherthielen** [comment]
Thanks for the plunker.

This is a known issue.  Hopefully we can address it in a future release.  For now, you can declare your parameter as `any` type and it will not specially encode slashes/tildes.

```js
  const url = '/url?{param:any}'
```

https://plnkr.co/edit/zlUprCzPYxVqX6rLWiGg?p=preview

---

For more details about why this occurs, see #2598
