### ISSUE TITLE
$state.go() params error

### ISSUE THREAD

**Issue by antonioaltamura** [angular-ui/ui-router#3084]
I noticed a link like
`<a ui-sref="root.question({id:'1'})">next</a>`
works, but if in my controller there is a:
`$state.transitionTo("root.question({id:'1'})");`

I get the error:
`No such state 'root.question({id:'1'})'`

what am I doing wrong?

**Comment by antonioaltamura** [comment]
I guess I figure it out
`$state.transitionTo('root.question', { id: '1' });
`

**Comment by christopherthielen** [comment]
you got it!  I recommend using `$state.go()` instead of `transitionTo()`
