### ISSUE TITLE
Ng1ViewDeclaration controller should be IInjectable

### ISSUE THREAD

**Issue by FraserKillip** [angular-ui/ui-router#3089]
Hey,

This is similar to #3044 but seems to have been missed when applying this particular fix.

At this position https://github.com/angular-ui/ui-router/blob/master/src/ng1/interface.ts#L326 Should be IInjectible but alas, it is not.

Cheers

**Comment by christopherthielen** [comment]
I'm fascinated by how many people are using typescript with ng1! 

Thanks for the bug report.
