### ISSUE TITLE
Refresh issue on child states and html5Mode

### ISSUE THREAD

**Issue by JWallaceDev** [angular-ui/ui-router#3090]
Hi Guys

My routing is breaking when I refresh or paste the URL of a page containing child states.

I've had a good look around and seen discussions relating to the routing not working in general with html5Mode, but my routing is working, it's just the child ones that don't seem to work. Additionally, I seem to have most of the suggested solutions already in place, so I think I must be missing something, hence my post on here.

It's worth noting that when the routing breaks, all of my JS files seem to be replaced with the contents of my index.html - and as a result I get lots of errors in Dev Tools, as you may expect. I'm not quite savvy enough at this yet to understand why that may happen.

In the following, singleState works fine when I refresh, but wordPressBlog.list and wordPressBlog.post do not.

This is my routing setup:

```
var homeState = {
            name: 'home',
            url: '/',
            templateUrl: 'home-view.html'
        },
            singleState = {
                name: 'singleState',
                url: '/single-state',
                templateUrl: 'single-state-view.html'
            },
            blogParentState = {
                name: 'wordPressBlog',
                abstract: true,
                url: '/blog',
                templateUrl: 'WordPressBlog/wpParentView.html',
                controller: 'WpParentCtrl'
            },
            blogPostListState = {
                name: 'wordPressBlog.list',
                url: '/posts/:categoryId',
                templateUrl: 'WordPressBlog/wpPostListView.html',
                controller: 'WpPostListCtrl'
            },
            blogPostItemState = {
                name: 'wordPressBlog.post',
                url: '/post/:postId',
                templateUrl: 'WordPressBlog/wpPostItemView.html',
                controller: 'WpPostItemCtrl'
            };
        
        $urlRouterProvider.otherwise('/');

        $stateProvider.state(homeState);
        $stateProvider.state(singleState);
        $stateProvider.state(blogParentState);
        $stateProvider.state(blogPostListState);
        $stateProvider.state(blogPostItemState);

        $locationProvider.html5Mode(true);
```

In wpParentView.html I have:

`<div ui-view></div>`

I'm working from the root and have this in my index.html <head>:

`<base href="/">`

And this is the rewrite I have in htaccess:

```
RewriteEngine on

# Don't rewrite files or directories
RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [L]

# Rewrite everything else to index.html to allow html5 state links
RewriteRule ^ index.html [L]
```

And so, 

mywebsite/single-state 

works fine if pasted into the browser, or refreshed.

But 

mywebsite/blog/post/4

Does not.

Any help or suggestions would be much appreciated.

Many Thanks
Jamie

**Comment by JWallaceDev** [comment]
Any ideas on what may cause this?

I can provide more details if needed.

**Comment by christopherthielen** [comment]
I can offer this suggestion: start with the devtools' "network tab".  Look at the requests being sent to the server and the responses coming back.  Understanding your own server rewrite rules is critical.  

> all of my JS files seem to be replaced with the contents of my index.html

This leads me to believe you might be using relative paths somehow.  Look at the URLs being fetched from the network tab for those JS files.  They should match exactly the path on your server. 

Unfortunately we can't provide support for server-side configuration (there's just too many setups out there, and we're a tiny team).   Because of that, I have to close this issue.  If it's a problem with UI-Router we'd of course be glad to help.

**Comment by JWallaceDev** [comment]
Thank you Christopher - you were exactly right and I was using relative paths to my JS. Changed that and it is working perfectly.

**Comment by chaitanyavadapalli** [comment]
Hey I am facing Same issue i.e all JS Files replaced by index.html but I am not passing Relative Paths.Do you have any idea how to resolve...
Thanks in advance
