### ISSUE TITLE
Synchronous `onBefore` result handling

### ISSUE THREAD

**Issue by csvn** [angular-ui/ui-router#3091]
Hello,

I am trying to understand how the `onBefore` hooks act when synchronous. [The documentation](https://ui-router.github.io/docs/latest/classes/transition.transitionservice.html#onbefore) says:

> If any hook modifies the transition synchronously (by throwing, returning false, or returning a TargetState), the remainder of the hooks are skipped.

To me, this means that if a hook returns a modification (throw, false, targetState), the remainder of the hooks will not run at all. But it seems that currently, the hooks will run, but their result is ignored. [See plunkr](https://plnkr.co/edit/FLEvyQG6AB06Z74dofMD?p=preview) (logs to console).

Have I misunderstood something? Is this as intended, or is it possible to change this so only the hooks that needs to run, will be run? Because currently, one `onBefore` hook can run multiple times unnecessarily. Lets say we have 3 `onBefore` hooks (A, B, C), each modifying the transition by returning new `targetState`:

**Currently**
1. A (new target) => B => C
2. A => B (new target) => C
3. A => B => C (new target)

**Proposed**
1. A (new target)
2. A => B (new target)
3. A => B => C (new target)

I am trying to do something similar to the above example with my Authorization hook, Organization hook (redirects if param is `null`) and a hook which needs to be async. I don't want the last async hook to run if not needed (i.e. Auth or Org hooks already handle it).

**Comment by christopherthielen** [comment]
> But it seems that currently, the hooks will run, but their result is ignored. Have I misunderstood something? Is this as intended,

@csvn you haven't misunderstood, and not it's not as intended.  Thanks for the bug report.  If you are interested in fixing it, the relevant code is here: 

https://github.com/ui-router/core/blob/master/src/transition/transitionHook.ts#L104-L120

**Comment by csvn** [comment]
@christopherthielen I just created a pull request for this. :)

**Comment by csvn** [comment]
Closing, this has been fixed by ui-router/core@8a45d049e1d17a9c50f29834bf35d90715978157
