### ISSUE TITLE
Ability to cancel/redirect the initial state load

### ISSUE THREAD

**Issue by connormlewis** [angular-ui/ui-router#3092]
In the 0.3.x releases and before, I had seen some discussion of ways that people had hacked together to catch the event of the initial state loading and potentially cancel or redirect it for use case such as checking if a user is authenticated. 

I thought the `$transition` feature was going to add the functionality in some way, but as far as I can tell, there is still no way to do it.  There has to be some state stuff happening when the page initially loads to get the view on the screen, and it would be awesome if we could attach events to it somehow.  Something like `$transition.onBegin` being called or even `$transition.onInitialLoad`. I know this would help me a lot and I'm sure it would clean up some other people's code as well.

**Comment by christopherthielen** [comment]
here are some ideas:

Check if the transition is coming from the "root" state?
```js
$transitions.on({ from: "" })
```

Check the transition id (incremented counter)
https://ui-router.github.io/docs/latest/classes/transition.transition-1.html#_id
https://github.com/ui-router/core/blob/master/src/transition/transition.ts#L124
```js
$transitions.on({}, ($transition$) => {
  if ($transition$.$id === 0) 
    ///
});
```

Wait to synchronize the url (which generally triggers the intiial transition) until you know the answers to the async questions
```js

.config($urlRouterProvider => $urlRouterProvider.deferIntercept())
.run(($http, $urlRouter, $state) => {
  $http.get('/check')
     .then(resp => doSomethingWith(resp.data))
     .catch(() => $state.go('login'))
     .then(() => {
       $urlRouter.listen();
       $urlRouter.sync();
     }).catch(() => ;
});
```

**Comment by connormlewis** [comment]
@christopherthielen Thanks for the reply. I tried the first two suggestions (although I had to change `$transitions.on()` to `$transitions.onBefore()` or `$transitions.onStart()` because the `.on()` function didn't exist.  When using any of those, the event never gets fired.  The first suggestion seems like a really elegant way of solving the problem though, and it would be awesome if the team working on UI Router could add that.

**Comment by christopherthielen** [comment]
All three solutions work right now.  Here's a plunker that shows both option 1 and option 2: http://plnkr.co/edit/03aCSBrHoPa5wco5y1yh?p=preview

Since these solutions exist, work, and seem to satisfy your request, I'm closing this issue

**Comment by connormlewis** [comment]
Ah, I ended up getting it working. I had a progress bar being initialized before I registered the onBefore event, and the state change must have been triggered before it made it that far into the function. Thanks for the help!
