### ISSUE TITLE
Docs: Migration Guide: State Change Events: Error in code snippet

### ISSUE THREAD

**Issue by tmcgann** [angular-ui/ui-router#3095]
Under "Migration example 2", the full code snippet is:

```js
// Migrate to: UI-Router 1.0 Transition Hook
app.run(function($transitions) {
  $transitions.onStart({ }, function(trans) {
    var SpinnerService = trans.injector.get('SpinnerService');
    SpinnerService.transitionStart();
    trans.promise.finally(SpinnerService.transitionEnd);
  });
})
```

The problematic line is:

```js
    var SpinnerService = trans.injector.get('SpinnerService');
```

It's missing the parenthesis after `injector` and should be:

```js
    var SpinnerService = trans.injector().get('SpinnerService');
```

As I'm going through the migration process, I'd like to help update the documentation as needed. How can I help update the documentation?

**Comment by christopherthielen** [comment]
@tmcgann much appreciated!  That file can be found here: https://github.com/ui-router/ui-router.github.io/tree/master/_guide

**Comment by tmcgann** [comment]
Pull request made: https://github.com/ui-router/ui-router.github.io/pull/4

Let me know if there's something I should do differently.
