### ISSUE TITLE
[Question] Is it possible to access parent component from nested component?

### ISSUE THREAD

**Issue by erik-ropez** [angular-ui/ui-router#3097]
I have something like following in my states:
```
{name: 'main.campaign', url: 'campaign-', component: CampaignComponent},
{name: 'main.campaign.create', url: 'create', component: CampaignCreateComponent},
{name: 'main.campaign.step-1-target', url: 'step-1-target', component: CampaignStep1TargetComponent},
```
As you can see first state is parent of next ones.

Is it possible to access parent component from child or pass some attributes from parent to child?

I've tried to use @Input in child and attribute in parent like `<ui-view [campaign]="campaign">Loading...</ui-view>` but it doesn't work as _campaign_ is not valid attribute of _ui-view_.

Is it accepted approach or I shall switch to use service for data sharing between views?

**Comment by adharris** [comment]
The right way to do this varies based on what you are trying to do.

If you need access to `CampaignComponent`'s data, maybe consider moving that data to a resolve on the `main-campaign` state.  Child state's can inject their parent's resolve data.

If the connection between the two is more than data sharing, then you probably want a service that manages that interaction.

If you really don't want a service, you can always inject `CampaignComponent` into the child components just like you would any service.

**Comment by eddiemonge** [comment]
^^ like that

**Comment by erik-ropez** [comment]
@adharris Didn't know it's possible to inject parent component. Great suggestion. Thanks!
