### ISSUE TITLE
Optional parameter doesn't work

### ISSUE THREAD

**Issue by archasek** [angular-ui/ui-router#3098]
I have something like this:

```
.state('test', {
    url: '/',
    params: {
        param1: null
    },
   (...)
}
```
```
<a ui-sref="test">
    test1
</a>
<a ui-sref="test({ param1: 'abc' })">
    test2
</a>
```

Test2 works well.
Test1 doesn't load anything.
I tried also with:

```
params: {
    param1: {
        value: null,
        squash: true
    }
},
```
Doesn't work unfortunately.

What is the proper way to add optional parameters?

**EDIT:**

I recognized that it's because of that I am actually on the same state and url. When I am on the test state with param specified, the sref to state without params doesn't work. Is there any option to force reload when changing the state to one witout params? Something like:
`ui-sref="test({ reload: true })`
When I use `ui-sref="test" ui-sref-opts="{ reload: true }"` it reloads, but the param is not cleared to defaults (param1: null), it's always set to 'abc', which is weird :(.

The only thing that works is:
`ui-sref="test({ param1: null })"`, that's ok, but it would be great if I could use just `ui-sref="test"` and it should load the test state without any parameters.

**Comment by adharris** [comment]
Unspecified parameters will by default inherit from the active state.  You can disable that by setting the inherit option to false: `ui-sref-opts="{inherit: false}"`

https://ui-router.github.io/docs/latest/interfaces/transition.transitionoptions.html#inherit

**Comment by archasek** [comment]
@adharris great, thank you very much. Can I set it globally, not in opts? Because there will be many opts using this method.

**Comment by adharris** [comment]
I do not know of a way to set the default options like that.  Really, much of the convenience of working with nested states relies on a child state not having to know about it's parent's parameters.  It's possible that if you need to `inherit=false` all the time that you are nesting your states inefficiently.  Why do you need to do this many times?

**Comment by archasek** [comment]
This was my hypothesis as I am starting a new project. Hope that I can manage it and use it as you described. Thanks for helping!

**Comment by Almar** [comment]
I have the same problem. I was checking out version 1.0 because of the 'route to component' feature. Our application uses optional parameters on many routes, so I hope this gets resolved.

**Comment by archasek** [comment]
I would also like to have a possibility to globally set e.g. `location: false` for the state, not by using ` [[$state.go]], [[$state.transitionTo]], [[ui-sref-opts]]`.

**Comment by christopherthielen** [comment]
you could write a transition hook to force the `inherit` option to false on certain states.

http://plnkr.co/edit/js5RGT7BMxWZf9Vn1hQz?p=info

```js

app.run($transitions => {
  let inheritFalseCriteria = { to: (state) => state.inherit === false };
  
  $transitions.onBefore(inheritFalseCriteria, (trans) => {
    let orig = trans.targetState();
    if (orig.options().inherit === true) {
      var options = Object.assign({}, orig.options(), { inherit: false });
      return trans.router.stateService.target(orig.state(), orig.params(), options);
    }
  })
})
```

Closing because I think the why is answered, and a workable solution provided.

**Comment by sajangurung2015** [comment]
Please pass the issue to Andy ..
