### ISSUE TITLE
ng2: 2.1.0 compatibility?

### ISSUE THREAD

**Issue by ybrodsky** [angular-ui/ui-router#3100]
Is it possible that the examples, like [Hello solar system](https://ui-router.github.io/tutorial/ng2/hellosolarsystem), which are using angular's version 2.0.0 do not work with angular release 2.1.0?

**Comment by christopherthielen** [comment]
The `package.json` file for ui-router-ng2 needs a bump, but they should be compatible.  

For example, in the [Hello solar system plunker](https://plnkr.co/edit/Dx5v6xwvQGssNsL59cHJ?p=info), find `config/system.config.js` and change from
```js
var ng2Ver = '2.0.0';
```
to
```js
var ng2Ver = '2.1.0';
```
and it still works. 


I'm reorganizing the code (moving ng2 to its own repository).  When that's done I'll fix the package.json and release a new version which explicitly supports 2.1.0

**Comment by ybrodsky** [comment]
Ok, after lots of struggling I managed to make it work.
Thanks for the help.

**Comment by christopherthielen** [comment]
I'm adding to the 1.0.0-beta.4 target: 

- update package.json for 2.x compatibility

**Comment by christopherthielen** [comment]
I have updated the Quickstart and the three tutorials to angular to version 2.1.2

**Comment by christopherthielen** [comment]
For posterity: the package.json already specified `^2.0.0` which allows any 2.x.x version of ng2
