### ISSUE TITLE
TargetState.name() returns string | StateDeclaration | State

### ISSUE THREAD

**Issue by dsebastien** [angular-ui/ui-router#3106]
Currently, calling .name() on a TargetState object returns either a string, a StateDeclaration or a State.
Is this by design? Shouldn't it just return the string?

IMO:
- even if the target state does not exist (e.g., as could happen in an onInvalid callback function?), I guess that we can still get the name of the state the user tried to reach
- if API user wants to retrieve the State or StateDeclaration, then he should rather use a dedicated method (e.g., getState, getStateDeclaration)

In my case I just want to log the name of the invalid target state for debugging purposes..

**Comment by christopherthielen** [comment]
agreed.  The [code itself can only return a string](https://github.com/ui-router/core/blob/master/src/state/targetState.ts#L63-L65), unless somebody has done something really weird like asking for a `$state.target(stateObject)` for a `stateObject` that hasn't actually been registered.
