### ISSUE TITLE
How to get resolved resolves from a parent state in 1.0.0 Beta 3

### ISSUE THREAD

**Issue by christophercr** [angular-ui/ui-router#3107]
Hi,

Similar to the issue described in #3105 I want to also get the resolved resolves from a parent state. According to the docs, there is a resolvables[] array in State where I can see the resolves defined but I can't get the resolved value of those.

Any ideas how can I get such resolved values?

**Comment by christopherthielen** [comment]
Much like the answer given in #3105 you can access the resolve values for the whole transition using [`Transition.getResolveValue()`](https://ui-router.github.io/docs/latest/classes/transition.transition-1.html#getresolvevalue) but that does not provide the "by state"  context.

For the resolves by state, do something like
```
var path = transition.treeChanges().to;
var resolves = path.map(pathnode => [pathnode.state.name, pathnode.resolvables])
```

The data for each resolvable  can be found on [`Resolvable.data`](https://ui-router.github.io/docs/latest/classes/resolve.resolvable.html#data)

**Comment by christopherthielen** [comment]
I'm changing my advice to use [[injector()]](https://ui-router.github.io/docs/latest/classes/transition.transition-1.html#injector)

```js
trans.injector('state').get('resolvetoken');
```
