### ISSUE TITLE
$state.go() for Angular 2

### ISSUE THREAD

**Issue by ybrodsky** [angular-ui/ui-router#3108]
Back in the day one could do from a controller:

`$state.go('foo', {param1: 'bar'})`

Couldn't find anywhere how to do that with ui-router ng2.

**Comment by asurinov** [comment]
You can inject [StateService](https://ui-router.github.io/docs/latest/classes/state.stateservice.html) in constructor of your component's class. This service has method 'go' with the same parameters as in angular1 version.

**Comment by ybrodsky** [comment]
Great then.
Is this somewhere in the docs I missed?

**Comment by christopherthielen** [comment]
@asurinov linked the relevant `StateService` docs.  

However, I admit the new typescript docs are challenging to dig through.  I'm working on slimming down what is shown in the docs by default, as well as splitting the ng1 and ng2 docs apart.

**Comment by vivekamin** [comment]
`/** imports */

import {NgModule, Component} from '@angular/core';
import {UIRouterModule ,UIROUTER_DIRECTIVES, StateService} from "ui-router-ng2";
import {BrowserModule} from "@angular/platform-browser";
import {platformBrowserDynamic} from '@angular/platform-browser-dynamic';

/** Components */

@Component({
  selector: 'my-app',
  template: `
  <a  (click)="hello()" uiSrefActive="active">Hello</a>
  <a uiSref="about" uiSrefActive="active">About</a>
  
  <ui-view></ui-view>
  `
})
export class App { 
  
  hello(private stateService: StateService)
  {
    console.log("hello Clicked");
    StateService.go('hello');
    
  }
  
}

@Component({  
  template: '<h3>Hello world!</h3>' 
})
class Hello { }

@Component({ 
  template: '<h3>Its the UI-Router hello world app!</h3>' 
})
class About { }


/** States */

let helloState = { name: 'hello', url: '/hello',  component: Hello }; 
let aboutState = { name: 'about', url: '/about',  component: About };

/** Root Application NgModule */

@NgModule({
  imports: [ 
    BrowserModule,
    UIRouterModule.forRoot({ states: [ helloState, aboutState ], useHash: true })
  ],
  declarations: [ App, Hello, About ],
  bootstrap: [ App ]
})
class RootAppModule {}

/** Angular 2 bootstrap */

platformBrowserDynamic().bootstrapModule(RootAppModule);
`



Giving me error : ui_router_ng2_1.StateService.go is not a function

**Comment by vivekamin** [comment]
`/** imports */

import {NgModule, Component} from '@angular/core';
import {UIRouterModule ,UIROUTER_DIRECTIVES, StateService} from "ui-router-ng2";
import {BrowserModule} from "@angular/platform-browser";
import {platformBrowserDynamic} from '@angular/platform-browser-dynamic';

/** Components */

@Component({
  selector: 'my-app',
  template: `
  <a  (click)="hello()" uiSrefActive="active">Hello</a>
  <a uiSref="about" uiSrefActive="active">About</a>
  
  <ui-view></ui-view>
  `
})
export class App { 
  
  hello(private stateService: StateService)
  {
    console.log("hello Clicked");
    StateService.go('hello');
    
  }
  
}

@Component({  
  template: '<h3>Hello world!</h3>' 
})
class Hello { }

@Component({ 
  template: '<h3>Its the UI-Router hello world app!</h3>' 
})
class About { }


/** States */

let helloState = { name: 'hello', url: '/hello',  component: Hello }; 
let aboutState = { name: 'about', url: '/about',  component: About };

/** Root Application NgModule */

@NgModule({
  imports: [ 
    BrowserModule,
    UIRouterModule.forRoot({ states: [ helloState, aboutState ], useHash: true })
  ],
  declarations: [ App, Hello, About ],
  bootstrap: [ App ]
})
class RootAppModule {}

/** Angular 2 bootstrap */

platformBrowserDynamic().bootstrapModule(RootAppModule);
`


Giving me error : ui_router_ng2_1.StateService.go is not a function
