### ISSUE TITLE
$state.go not working on single click 

### ISSUE THREAD

**Issue by phanivaranasi** [angular-ui/ui-router#3109]
Hi,
I have "Login" button in my form.
When User is authenticated $state.go('dashboard') is used and not authenticated $state.go('login').
when  button is clicked, user is successfully authenticated $state.go('dashboard') not working, but again when login button is clicked $state.go is working.

Could any one help me in solving this issue.

Thanks
Krishna

**Comment by christopherthielen** [comment]
Hi, thank you for using ui-router!  This tracker is reserved for bug reports and feature reqeusts.  Support can be found on the [StackOverflow community](http://stackoverflow.com/questions/ask?tags=angularjs,angular-ui-router) site.

http://bit.ly/UIR-SOF

However, if you can reproduce your error in a plunker I'd be happy to take a look.  http://bit.ly/UIR-Plunk
