### ISSUE TITLE
$transitions not triggered when navigating directly to a state via URL (mysite/someState)

### ISSUE THREAD

**Issue by mharper418** [angular-ui/ui-router#3112]
I'm using $transitions to detect state changes and take some action based on the difference between some data defined in the 'from' and 'to' states. This is working great for me, but this code is not hit when the user navigates directly to a state via url. For example, browsing to mysite/search does not trigger this, but navigating within the site from the home page to the search page triggers this.

Is this a bug?  I would expect a transition from an empty state to the new state. If so, is there any know fix or workaround?  Maybe a way to detect that the state was directly navigated to? That would allow me to execute the logic that I need to.

```
$transitions.onSuccess({}, trans => {
  myFunc(trans.$from().data, trans.$to().data);
  return true;
});
```

**Comment by christopherthielen** [comment]
it should work by url too.

When do you register your `$transitions` hook?  It should be before the url is synchronized.

Here's a plunker that shows how it works:  http://plnkr.co/edit/SxRrYxWFZUsUiHaAMMfE?p=preview

The hook is registered in a `.run()` block.  Navigate to `home.foo`, open the console, click the "reload" button.  Notice that the transition is logged to the console.

**Comment by mharper418** [comment]
Thank you - you've caught my problem exactly.  My transition was not registered early enough in the application.  Thanks again.
