### ISSUE TITLE
How to highlight dropdown parent state when child state selected?

### ISSUE THREAD

**Issue by kolkov** [angular-ui/ui-router#3114]
When I add uiSref="private.base" and click on dropdown this state is selected, but I do not want this behavior. I want only highlight this item.

```
<li class="nav-item btn-group" ngbDropdown>
          <a class="dropdown-toggle nav-link" role="button" uiSref="private.base" uiSrefActive="active" ngbDropdownToggle>Base</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" (click)='isCollapsed = true' uiSref="private.base.actor.list" uiSrefActive="active">Actor base</a> 
```

**Comment by christopherthielen** [comment]
remove the `uiSref="private.base" ` and let me know what happens

**Comment by kolkov** [comment]
![image](https://cloud.githubusercontent.com/assets/3740898/19739000/149d3cf8-9bc2-11e6-96ee-752067c988b9.png)

![image](https://cloud.githubusercontent.com/assets/3740898/19739021/2800382c-9bc2-11e6-8fdc-d863b7b1b752.png)

**Comment by christopherthielen** [comment]
@kolkov interesting. Does ng-bootstrap  remove the child components (the `<div class="dropdown-menu">` from the component tree, or just hide them from the DOM?  As of beta.2, the ng2 `uiSrefActive` will monitor all its children for any `uiSref`.  This should highlight the `dropdown-toggle nav-link` when any of the child components `uiSref` are active.

**Comment by kolkov** [comment]
I see only this:
![image](https://cloud.githubusercontent.com/assets/3740898/19739282/0f117e74-9bc3-11e6-9be3-efadccd604e5.png)

**Comment by christopherthielen** [comment]
hmm that looks like it should be adding the active class on the `ngbdropdowntoggle`.  You're using beta.3?

**Comment by kolkov** [comment]
I using ng2-router beta3 and v1.0.0-alpha.9 https://ng-bootstrap.github.io/#/home

**Comment by kolkov** [comment]
I try to reinstall ui-router-ng2. Is this correct?
![image](https://cloud.githubusercontent.com/assets/3740898/19741538/b7c4d6dc-9bc9-11e6-8cba-24ae1a9c20a6.png)
