### ISSUE TITLE
How to remove dynamically created states?

### ISSUE THREAD

**Issue by achenge07** [angular-ui/ui-router#3115]
Hi guys, I used $stateProvider in angularJS 1.5.8  to create dynamic states but I don't know how to remove these states. 

I know this question has been discussed several times, here the links: 
    https://github.com/angular-ui/ui-router/issues/1095
    https://github.com/angular-ui/ui-router/issues/2265
    https://github.com/angular-ui/ui-router/issues/2711
However, I didn't find a easy way in these posts. 

It seems that the remove states feature has been added, link:  
   https://github.com/angular-ui/ui-router/commit/44579ecbafe15ad587dc341ba4a80af78b62bdaa
But I'm a newbie so it's too difficult for me to find the right way to remove states.

Is there anyone kindly give me some instructions about how to remove states?  Any suggestions would be appreciated. 

Thanks
yorven

**Comment by christopherthielen** [comment]
Deregistration is only possible in 1.0 beta version.  https://ui-router.github.io/docs/latest/classes/state.stateregistry.html#deregister

You can [access the registry](https://ui-router.github.io/docs/latest/classes/core.uirouter.html#stateregistry) by injecting `$uiRouter`
```js
app.run( function($uiRouter) {
  $uiRouter.stateRegistry.deregister('foo');
});
```

**Comment by RonakShah** [comment]
Thanks @christopherthielen. But does the latest version of UI-Router includes this feat? https://github.com/angular-ui/ui-router/pull/1809 

How can I reload named nested view only (not sure if possible in latest version) and also dynamically update state registry (possible in latest version) in single UI-Router ng1 library?
