### ISSUE TITLE
StateDeclaration component misssing in d.ts file 

### ISSUE THREAD

**Issue by bunny1985** [angular-ui/ui-router#3116]
commonjs/state/interface.d.ts

cannot find component?: string;

**Comment by christopherthielen** [comment]
Thats on the `Ng1StateDeclaration` interface: https://ui-router.github.io/docs/latest/interfaces/ng1.ng1statedeclaration.html#component which extends `StateDeclaration`

Since each framework (ng1/2/react) has its own definition of what a component.

You can declare your definition like so:

```js
var state: Ng1StateDeclaration = {
  name: 'foo',
  component: 'foo'
};
```
