### ISSUE TITLE
Transition hook criteria issue

### ISSUE THREAD

**Issue by cadilhac** [angular-ui/ui-router#3119]
I have encountered a problem when using $transitions and declaring the to and from parameters.
(using 1.0 beta 3, NG1)

Here is the states tree:
A -> B
B -> C
B -> D

When I use to:C, from:D, it works well.
If I replace by to:B.C, from:D it doesn't work anymore.
Same issue with to:B.**, from:D or if I modify from:D with same kind of alternatives.

Note: in your doc about globs, for the exact match, you could add for glob 'A' if it matches or not 'B.A' i.e. if ancestors have to be specified or if the glob tries to match a leaf of the tree or a group of segments at the leaf of the tree.

**Comment by christopherthielen** [comment]
Sorry, I don't really understand what you're trying to explain here.  
Are your states named `A`, `B`, `C`, and `D`,
or `A`, `A.B`, `A.B.C`, and `A.B.D`?

Glob matches are based only on the name of the state, not on their position in the tree.

**Comment by cadilhac** [comment]
Yes the states are A, B, C and D. The arrows help represent the tree. So B is the child of A.

**Comment by cadilhac** [comment]
> Glob matches are based only on the name of the state, not on their position in the tree.

@christopherthielen Are you saying that globs with the dot notation only work if I define state names with the exact same dot notation? What if I use the parent property when defining states? Can't I use 'B.**' for any B descendant?

**Comment by christopherthielen** [comment]
Yes, that is a limitation of working with globs: the only match on the name of the state. 

You can work around this by creating your own helper predicate function.  The predicate function should take a state object as a parameter and return true if the condition matches.  

The [internal state object representation]() has an [`includes` map](https://ui-router.github.io/docs/latest/classes/state.state-1.html#includes) that you can leverage.

```js
function isChildOf(parentStateName) {
  return function(state) {
    return state.$$state().includes(parentStateName);
  }
}
```
then:
```
$transitions.onStart({ to: isChildOf('B') }, ...);
```

or inline:
```
$transitions.onStart({ to: (state) => state.$$state().includes['B'] }, ...);
```

**Comment by cadilhac** [comment]
> Yes, that is a limitation of working with globs: the only match on the name of the state.

It's a pity. It would have been so intuitive.

I tried to use $$state in my 'to' function, but it seems to be non existent on the state object...

**Comment by christopherthielen** [comment]
I forget which object is provided… the state definition, or the internal state object.  

Try this one:
```
(state) => state.includes['B']
```

**Comment by cadilhac** [comment]
Ah, this works. Thanks.

**Comment by christopherthielen** [comment]
I'm closing this issue in favor of tracking it at the core repository
https://github.com/ui-router/core/issues/5
