### ISSUE TITLE
updating url only without any other actions

### ISSUE THREAD

**Issue by mackelito** [angular-ui/ui-router#3122]
I have a component with 200+ items and want to update the url to be something like 'category/3#24-MB01' when scrolling.

When a item comes in view I update the url using this code:
```javascript
$state.go($state.current.name, param, {
    notify: false,
    reload: false,
    location: 'replace'
});
```

Url is updated but the browser navigates to the item with id "#24-MB01"...

Have been searching both StackOverflow and the issues and now I´m kind of lost.. Any guidance is much appreciated!

Note: Using 1.0 beta3

**Comment by mackelito** [comment]
Looks like I found the solution after all.. setting dynamic: true on the param seems to work..

**Comment by mackelito** [comment]
I spoke to soon... still having this problem..

**Comment by christopherthielen** [comment]
I'm assuming you're using some sort of scroll spy.  The router manages the URL hash as a state parameter.  You should be able to update it by changing the parameter `#` to whatever you want it to be.

```js
$state.go(".", { #: '24-WB06'}, { location: 'replace' });
```

**Comment by mackelito** [comment]
Yes I have a scroll spy (using https://github.com/camwiegert/in-view) thx to your reply I figured out how to get it working better but still not flawless ;)

the problem right now is that when I update url it jumps to top if that item creating a sort of page flickering.. but this is just a matter of implementation pattern.. 

Thx for you help and keep up the awesome work on the module! it´s truly a gem!

**Comment by mackelito** [comment]
Spoke to soon.. again... so the .go will trigger a transition but I just want to update the location?

**Comment by christopherthielen** [comment]
`$state.go(".", { #: '24-WB06'}, { location: 'replace' });` triggers a transition, yes, but the transition is `dynamic`, and all it does is update the URL.

**Comment by mackelito** [comment]
And also triggers the view to scroll to the id!(?)

**Comment by christopherthielen** [comment]
@mackelito that's native browser behavior, right?  How does other scrollspy implementations update the browser hash without triggering scrolling?

**Comment by mackelito** [comment]
I guess it should prevent the "bubble" event.. perhaps by using stopPropagation?

**Comment by christopherthielen** [comment]
I think that's your homework :) Figure out how other scrollspy implementations do it (then do that). 


If you find that you can't implement it without some specific support from ui-router, feel free to re-open this issue and we can discuss the ramifications.  Otherwise, I'm closing because I think ui-router is doing what it should be doing.
