### ISSUE TITLE
Accessing some resolve data of a child state in a parent state, when it is resolved?

### ISSUE THREAD

**Issue by cadilhac** [angular-ui/ui-router#3125]
I have a root state that handles a map for the whole app. A descendant state is linked to a specific url like /user/:userid and the user is a resolve data of this child state. When loading the user, the map must select the corresponding marker for this user and be centered on it. 

Of course, I could have a common service that stores a current user (by the substate controller) and the parent controller would watch it. But I'm wondering if there is a ui-router specific solution for that. I tried to register a hook in the parent controller to know when the child state is started and get the resolve, but it seems it is too late and it is never triggered. Another way to do that?

Thanks

**Comment by christopherthielen** [comment]
There is not any ui router construct to accomplish this.  In ui router, all data flows downwards.  If you need to communicate back up, you can do that (like you currently are)  using a service.  Another option is to expose an API as part of a resolve on the parent state.  The child can inject that resolve an call a method on it which updates the parent data.

A third option, more uirouter centric, would be to define a dynamic parameter on the root state which does not appear in the URL.  After the child state is loaded, it can update that state parameter by calling `$state.go`.   Because the parameter is marked as `dynamic: true`, the states do not reload. You would have to respond to the parameter changes in your root states template using something like [uiOnParamsChanged](https://ui-router.github.io/docs/latest/interfaces/ng1.ng1controller.html#uionparamschanged)

**Comment by christopherthielen** [comment]
Closing this issue because I believe I've answer the question. If you have follow-ups feel free to respond.

**Comment by cadilhac** [comment]
Thank you.

Option 2: could you elaborate a bit more abotu defining an api as a resolve and injecting it?

Option 3: do you mean that the child state would call go with its own state name, but different params?

**Comment by christopherthielen** [comment]
#### Option 2:
An api as a resolve.  Basically "a service", but locally scoped (not a global singleton).

```js
function mapApi() {
   var api = {
    coords: { x: 1, y: 2 }, // some default, perhaps
    listeners: [],
    setCoords: function(coords) {
      api.coords = coords;
      listeners.forEach(callback => callback(api.coords));
    },
    onCoordsChanged: function($scope, callback) {
      api.listeners.push(callback);
      const deregister = () => {
        let idx = api.listeners.indexOf(callback);
        if (idx !== -1) api.splice(idx, 1);
      }
      $scope.$on('$destroy', deregister);
    }
  };

  return api;
}

... resolve: {
    mapApi: makeApi
  }  
```

The parent's component injects `mapApi` and adds a listener which updates the map
```
mapApi.onCoordsChanged($scope, componentCallbackFunction);
```
while the child injects the resolve and triggers the setCoords api
```js
resolve: {
  user: ($transition$, userApi, mapApi) =>
    userApi.get($transition$.params.userId).then(user => mapApi.setCoords(user.coords));
}
```

#### Option 2:
The parent has a dynamic parameter. The child, when entered, redirects the transition with the proper coords params.
```js
.state('parent', {
  params: {
    coords: { dynamic: true, value: { x: 1, y: 2 } }
  }
})
.state('child', {
  url: '/user/:userId',
  resolve: { 
    user: (userApi, $transition$) => userApi.get($transition$.params.userId) 
  },
  onEnter: (user, $transition$) {
    if ($transition$.params().coords !== user.coords) {
      // redirect the transition with proper coordinates
      $transition$.router.stateService.target(".", { coords: user.coords });
    }
    // or this could work in a different way by starting a new transition just to update the  coords
    // $transition$.promise.then(() => $state.go(".", { coords: user.coords });
  }
}
```

**Comment by cadilhac** [comment]
This is fantastic Chris. Thank you.

Two short questions though:
1. What does "." mean in target or go? Does it mean "same state"?
2. What is the difference between go and target? In the docs I see for target a mere "Factory method for creating a TargetState".

Thanks

**Comment by christopherthielen** [comment]
@cadilhac 

> 1. What does "." mean in target or go? Does it mean "same state"?

It means "current state" in the same sense as "." means "current working directory" when working with paths. 

 _(note however, it is relative to `options.base`.  When using relative paths with `ui-sref`, it is always relative to the state that the `ui-sref` was created in. That means `ui-sref="."` created in `home` always links back to `home`, even if the current state is `home.foo`)_

2. What is the difference between go and target? In the docs I see for target a mere "Factory method for creating a TargetState".

Click `TargetState` to get a better description: https://ui-router.github.io/docs/latest/classes/state.targetstate.html  . In the public API, a target state is primarily used as a [return value from a transition hook](https://ui-router.github.io/docs/latest/modules/transition.html#hookresult)

The difference between `.go()` and `.target()` is that the former abruptly clobbers the existing transition (`"Transition Superseded"`), while the latter returns a value which the transition inspects, and then redirects nicely.  `$state.go()` creates and runs a transition IMMEDIATELY while returning a `TargetState` allows the old transition to clean itself up and run the new transition.  There are other benefits to redirecting via TargetState, like redirect loop detection and not re-fetching resolves on the second transition that were already fetched on the first one.

**Comment by cadilhac** [comment]
Many thanks Chris. This makes a nice thread to learn a lot!

**Comment by cadilhac** [comment]
Jsut one thing, I tried to call target() in onEnter() and I get this message:

> No reference point given for path '.'

**Comment by christopherthielen** [comment]
@cadilhac interesting! 
Yes, it makes sense to me now.  The `"."` is actually ambiguous in an onEnter.  Does it mean relative to the *current state*, to the *destination state*, or to the state *being entered*.  I think in this case I would do 
```js
var $state = $transition$.router.stateService;
return $state.target($transition$.to(), { coords: user.coords });
```

**Comment by cadilhac** [comment]
Great. Thanks.

**Comment by paolosanchi** [comment]
@christopherthielen I'm going with the solution 3, I'm using in UI-Router for Angular 2+.
I'm stuck on detecting the parameter change.  
The function is fired only when I navigate from another state. It is fired after the .target() but the new parameter value is not set (it's undefined). This is what I have:

parent state:

```
{
    name: 'root.settings.profile',
    url: "/profile",
    params: {
      operativeHeadquarter$: {
        dynamic: true
      }
    },
    views: {
      '': {
        component: ProfileSettingsComponent
      },
      'extra@root': {
        component: ProfileSettingsPanelsComponent
      },
    }, resolve: [
      {
         ... // omitted for clearness
      }
    ]
}
```

child state:
```
 {
    name: 'root.settings.profile.operative-headquarters.edit',
    url: "/{idx:int}",
    resolve: [{
      token: 'operativeHeadquarter$',
      ... // omitted for clearness
    }],
    onEnter: (transition: Transition, state: StateDeclaration) => {
      const operativeHeadquarter$ = transition.injector().get('operativeHeadquarter$');
      if (transition.params().operativeHeadquarter$ !== operativeHeadquarter$) {
        transition.router.stateService.target(transition.to(), { operativeHeadquarter$: operativeHeadquarter$ });
      }
    }
  },
```

handler in ProfileSettingsPanelsComponent (extra@root view component in parent state)
```
  uiOnParamsChanged(newParams, trans: Transition) {
    if (trans.to().name === 'root.settings.profile.operative-headquarters.edit') {
      this.operativeHeadquarter$ = trans.params().operativeHeadquarter$;
    }
  }
```
trans.params().operativeHeadquarter$ is undefined (the default value), newParams has no operativeHeadquarter$ field

**Comment by paolosanchi** [comment]
Damn... I forgot to return the transition created with target(). I also had to merge the current parameters.
Now if I go land directly to the leaf routing (root.settings.profile.operative-headquarters.edit), the uiOnParamsChanged doesn't trigger (the first time)

```
    onEnter: (transition: Transition, state: StateDeclaration) => {
      const operativeHeadquarter$ = transition.injector().get('operativeHeadquarter$');
      if (transition.params().operativeHeadquarter$ !== operativeHeadquarter$) {
        const params = {
          ...transition.params(),
          operativeHeadquarter$: operativeHeadquarter$
        };
        return transition.router.stateService.target(transition.to(), params);
      }
    }
```
