### ISSUE TITLE
$state.go() has inconsistent inherit option when visiting the same state

### ISSUE THREAD

**Issue by joelpoloney** [angular-ui/ui-router#3126]
I noticed a potential bug with the angular router where calling $state.go to the same state removes URL params even when it should be preserving them by default.

Specifically looking at these docs: https://github.com/angular-ui/ui-router/wiki/Quick-Reference#stategoto--toparams--options

Here's a plunker showing my issue: https://plnkr.co/edit/MlY89tokHR9ziVPCAQZF?p=preview

In order to trigger the behavior, you'll need to open the preview in windowed mode so you can view the URL. If you first click on foo2, it will set ?foo=bar in the URL. Then if you click foo1 or foo3, they will remain.

However, if you first click on foo1, then foo2, then foo1/foo3, it will clear the params each time.

**Comment by christopherthielen** [comment]
Yep, looks like a bug in legacy code base.

This works as expected in 1.0: https://plnkr.co/edit/AsbaZbRczUcBxEpn5Dpn?p=preview

**Comment by christopherthielen** [comment]
Oops, I missed something about your plunker.  The `foo` state isn't declaring the `foo` param.  In ui-router, even query params must be declared to check if a state should be reloaded or not.

change your state definition like this:
```js   
    .state('foo', {
      url: '/foo?foo',
      template: '<h1>foo</h1>',
    })
```

https://plnkr.co/edit/2yHDfq1YZytJhL2jlxQG?p=preview

**Comment by joelpoloney** [comment]
Makes sense. How would one handle global params that need to exist on every state?

**Comment by christopherthielen** [comment]
option 1) redeclare them EVERYWHERE


option 2) declare on a parent state: https://plnkr.co/edit/LfHkx1zz7p4QNgSqN0YK?p=preview

**Comment by joelpoloney** [comment]
Ok makes sense. Thanks!
