### ISSUE TITLE
ui-router in angular1.5, if parent route component includes another component, child route component doesn't show

### ISSUE THREAD

**Issue by beiduo** [angular-ui/ui-router#3127]
recently i start working in a project which is using angular 1.x, but i prefer component based framework like react and angular 2. also i want to progressively transform this project from controller to component style which provided in angular 1.5.

i'm using ui-router in angular1.5 for component routing, but i found a little problem. if parent route component includes another component (writing directly in the template using "<some-component />" etc.), child route component doesn't show. if parent component doesn't include any other component, the child routes work well.

that might not be a major problem, but i'm just wondering if there are other solutions or i'm doing incorrectly...

for example: this is my states:

```
const states = [
    {
        name: 'index',
        url: '/index',
        component: 'indexComponent',
        resolve: {
            title: () => 'this is a title'
        }
    },
    {
        parent: 'index',
        name: 'list',
        url: '/list',
        component: 'listComponent',
        resolve: {
            text: () => '356345654364'
        }
    }
];
```

and i have three components, which are: 

ListComponent:

```
<div>
    List: {{data.text}}
    <input ng-model="data.text" />
</div>
```

```
import tpl from '../views/listComponent.html';

const ListComponent = {
    bindings: {
        text: '<'
    },
    template: tpl,
    controller: Controller,
    controllerAs: 'data'
};

function Controller () {
    console.log(this);
}

export default ListComponent;
```

NavComponent

```
<nav>
    <ul>
        <li ng-repeat="el in data.navigation">
            <a ui-sref="{{el.name}}">{{el.name}}</a>
        </li>
    </ul>
</nav>
```

```
import tpl from '../views/navComponent.html';
import states from '../constants/states';

const NavComponent = {
    template: tpl,
    controller: Controller,
    controllerAs: 'data'
};

function Controller () {
    this.navigation = states.filter(el => 
        (el.name === 'index' || el.parent === 'index')
    );
}

export default NavComponent;
```

IndexComponent

```
<div>
    <h1>{{data.title}}</h1>
    <nav-component />
    <ui-view />
</div>
```

```
import tpl from '../views/indexComponent.html';

const IndexComponent = {
    bindings: {
        title: '<'
    },
    template: tpl,
    controller: Controller,
    controllerAs: 'data'
};

function Controller () {
    console.log(this);
}

export default IndexComponent;
```

when i add <nav-component /> into IndexComponent, the <ui-view /> stop working.

thanks for your reading and hopefully there are ways to solve this...

**Comment by christopherthielen** [comment]
When angular parses templates, it does not expect components tags to be self closing.  

Replace with this and it works:
```js
    <nav-component></nav-component>
    <ui-view></ui-view>
```

http://plnkr.co/edit/zfedBHd2vTjMFePzNSRY?p=preview

**Comment by beiduo** [comment]
because both <nav-component /> and <ui-view /> work properly separately, so i never thought that. i tried and it works! thanks a lot.
