### ISSUE TITLE
How to load a component using Webpack + ocLazyLoad ? 

### ISSUE THREAD

**Issue by kevincaradant** [angular-ui/ui-router#3130]
Hi 

I have a problem using ui-router 1.0.0 + angular 1.5 components + webpack + ocLazyLoad.

I don't know where can I ask this question, here, or Webpack ? So I come here in the hope to find an answer. 

To avoid to replicate everytime the same question, I link my initial question from Stackoverflow. 

If you need some additionals informatons, tell me :)

Thank you in advance for your help. 

[LINK QUESTION](http://stackoverflow.com/questions/40412500/webpack-angular-1-5-component-ui-router-1-0-0-oclazyload)

**Comment by christopherthielen** [comment]
I can help you with this. Can you make your code available is a get hub repository that I can fetch and run? Or possibly just put in a punker or a zip file.

**Comment by kevincaradant** [comment]
Yes of course. Thank you to look it :)
I created a branch "LazyLoading" in this repository:
https://github.com/kevincaradant/web-template-webpack

So, you have to do:
1 - `git checkout lazyloading`
2 - `npm install --no-optional`
3 - `npm run dev`
I'm running with nodejs 6

Let me know if you have any problem to install or execute this project :)

**Comment by christopherthielen** [comment]
PR and comments:

https://github.com/kevincaradant/web-template-webpack/pull/19/files

**Comment by kevincaradant** [comment]
Great ! , thank you very much for this PR very detailed. 
Just one thing, I tried to get your fork and execute it in the lazyloading branch but I didn't have the template of page 1 when I click on "page1" on the navbar , I see just the url on the left. Do you have an idea why ?

**Comment by christopherthielen** [comment]
Yes, I did see hello world.

I will fetch my fork cleanly, reinstall the NPM libraries, and let you know what i see.

**Comment by christopherthielen** [comment]
Yes, the hello page one component is loading fine for me when I click the page 1 link.
Make sure you have fetched from my fork.

<img width="600" alt="screen shot 2016-11-07 at 12 17 20 pm" src="https://cloud.githubusercontent.com/assets/2053478/20069945/379f5148-a4e4-11e6-99d2-840c620c473e.png">

**Comment by kevincaradant** [comment]
![image](https://cloud.githubusercontent.com/assets/6093175/20072589/4494a6ce-a529-11e6-9f2f-85491edff04e.png)

![image](https://cloud.githubusercontent.com/assets/6093175/20072619/5cf08206-a529-11e6-8bb6-9bdcb8a3ba6e.png)

![image](https://cloud.githubusercontent.com/assets/6093175/20072668/8dd5e6a4-a529-11e6-80d4-9be4ebde1f62.png)

It's your repository , I don't understand :/

**Comment by christopherthielen** [comment]
I was going to point out that I only updated your development configuration file in the PR. However it appears as though you are indeed running the command `npm run dev` in your screenshot

**Comment by kevincaradant** [comment]
Yes I run `npm run dev`. Even `npm run prod` and `npm run serve:prod`. Everytime,I get only the URL. I don't understand why. I forked your repository. `git checkout lazyloading` again and I do that on two different computers. 
Computer 1: Nodejs 6.4   Windows Pro 7 64 Bits 
Computer 2: Nodejs 6.9 Windows Pro 10 64 bits

I see your are on Ubuntu 16.04 or 16.10. But I don't know if that can be a reason

**Comment by christopherthielen** [comment]
```
╭─ christhielen@lappy486  ~/projects/t
╰─  git clone https://github.com/christopherthielen/web-template-webpack.git                                                                                   [ 1:25PM ]
Cloning into 'web-template-webpack'...
remote: Counting objects: 582, done.
remote: Total 582 (delta 0), reused 0 (delta 0), pack-reused 582
Receiving objects: 100% (582/582), 200.05 KiB | 163.00 KiB/s, done.
Resolving deltas: 100% (335/335), done.
╭─ christhielen@lappy486  ~/projects/t
╰─  cd web-template-webpack
╭─ christhielen@lappy486  ~/projects/t/web-template-webpack
╰─ git:[master]  git checkout lazyloading
Branch lazyloading set up to track remote branch lazyloading from origin.
Switched to a new branch 'lazyloading'
╭─ christhielen@lappy486  ~/projects/t/web-template-webpack
╰─ git:[lazyloading]  npm i >/dev/null ; npm run dev
```

Ran this on my mac and it works fine for me

**Comment by kevincaradant** [comment]
OK, It's really weird. 
That's work for my Ubuntu 16.10 64 bits ....
Why under Windows, it  doesn't work :/

**Comment by christopherthielen** [comment]
I launched a windows VM. The problem is in the webpack configuration. Because of windows backslash path separators, the html-loader rule wasn't triggering.  Then, the ngtemplate-loader was processing the file.

<img width="817" alt="screen shot 2016-11-15 at 6 59 20 pm" src="https://cloud.githubusercontent.com/assets/2053478/20332372/cce93d4e-ab70-11e6-8d15-d885566526dd.png">

Works if you change the regular expressions from `\/page1` to `[\/\\]page1`

<img width="489" alt="screen shot 2016-11-15 at 8 19 49 pm" src="https://cloud.githubusercontent.com/assets/2053478/20332394/fc05deac-ab70-11e6-9450-13c0b3cecc0c.png">

I pushed an update to that branch

**Comment by kevincaradant** [comment]
Oh I totally forgot the path with regex in the configuration file...  That's seems so logic.  Sorry for that.  And a big thank you to edit and fix this problem :).  I look it in the day.
