### ISSUE TITLE
ng1-to-ng2 still supported?

### ISSUE THREAD

**Issue by squadwuschel** [angular-ui/ui-router#3132]
Hi,

I can't find any link to the "ng1-to-ng2" repository anymore on your UI-Router landing page. So is there a better solution for this approach? And is this still supported?

https://github.com/ui-router/ng1-to-ng2

thx
 squadWuschel

**Comment by christopherthielen** [comment]
yes, its still supported

**Comment by squadwuschel** [comment]
thx :-)
