### ISSUE TITLE
Layouts

### ISSUE THREAD

**Issue by phanivaranasi** [angular-ui/ui-router#3135]
Hi Team,
I'm using ui-router in my angularjs application, below is my layout
![image](https://cloud.githubusercontent.com/assets/6230353/20049893/00968f7e-a4ec-11e6-9571-427907355f0b.png)
![image](https://cloud.githubusercontent.com/assets/6230353/20050031/ee139148-a4ec-11e6-9f4b-25b24a6c8300.png)

In the above layout, left side all links will be resided and top school banner is kept. 
![image](https://cloud.githubusercontent.com/assets/6230353/20049953/75f61af0-a4ec-11e6-9284-cd67a1950528.png)
I'm facing below issues
1. I have a angularjs directive for school banner, inside directive couple of services are used.
2. Left Menu is angularjs directive,  which has Teacher & Student links
I need only content area to be refreshed, but my entire layout is getting refreshed when navigating between links.

Scenario:
When I click on Student > Personal Info, banner service is executed
When I click on Teacher > Reports, banner service is executed.
**Kindly let me know, how can I fix it**

Thanks
Krishna

**Comment by christopherthielen** [comment]
Can you show your state/view structure?  Its very crucial to understanding a question like this.  

please ask this question on StackOverflow:  http://bit.ly/UIR-Plunk
