### ISSUE TITLE
ui-router Dynamic routing issue

### ISSUE THREAD

**Issue by mnaouali** [angular-ui/ui-router#3136]
is there using angularJS 1.5 and ui.router to define State and routes dynamically? I mean getting the data from a backend sever and then populate the ui-router param such as state, URL ... I tried to use the put them in the run part but it's not working as the data retrieved from the server wasn't available when needed. here is what I'm doing
`
    
    run(
				function run(Idle, $http, $q, $state, $rootScope) {
				
	       Idle.watch();
                                               $urlRouterProviderRef.otherwise('/login');
						$urlRouterProviderRef.when("", "/login");
						$http.get(_contextPath + '/routing', {})
					    .success(function(data)
					    {
					    	$rootScope.LOGIN_PAGE_CONTROLLER_NAME = data.LOGIN_PAGE_CONTROLLER_NAME;
					    	$rootScope.LOGIN_PAGE_PAGE_TITLE = data.LOGIN_PAGE_PAGE_TITLE;
					    	$rootScope.LOGIN_PAGE_STATE = data.LOGIN_PAGE_STATE;
					    	$rootScope.LOGIN_PAGE_TEMPLATE_URL = data.LOGIN_PAGE_TEMPLATE_URL;
					    	$rootScope.LOGIN_PAGE_URL = data.LOGIN_PAGE_URL;
					    	
					    	
					    });
						
						var test = $rootScope.LOGIN_PAGE_STATE;
							
					    	$stateProviderRef.state($rootScope.LOGIN_PAGE_STATE, {
					    		url : $rootScope.LOGIN_PAGE_URL,
					    		views : {
					    			"mainbody" : {
					    				templateUrl : $rootScope.LOGIN_PAGE_TEMPLATE_URL
					    			},

					    		},
					    		controller : $rootScope.LOGIN_PAGE_CONTROLLER_NAME,
					    		data : {
					    			pageTitle : $rootScope.LOGIN_PAGE_PAGE_TITLE,
					    			authenticate : false
					    		}
					    	});
				})`
any help is really apreciated

**Comment by christopherthielen** [comment]
You should use [deferIntercept](https://ui-router.github.io/docs/latest/classes/url.urlrouterprovider.html#deferintercept) to pause the router while loading from the backend.

If you're using the legacy version (0.x) then you will have to save a reference to the `$stateProvider` from the config phase.
