### ISSUE TITLE
$scope controllerAs bug

### ISSUE THREAD

**Issue by holtc** [angular-ui/ui-router#3140]
In version 0.3.1, there is a bug where injecting $scope into a controller leads to an 'Unknown Provider' error when the controller is defined in a separate js file.  Migrating to 0.3.2 fixed this error for me

**Comment by christopherthielen** [comment]
0.3.1 seems to be working fine with controllerAs:  https://plnkr.co/edit/Fa6CD6n3DZJERvhqUo16?p=preview

Since there doesn't seem to be an issue, I can close this?

**Comment by holtc** [comment]
very weird, I was using the minified version and it would not work until I switched to 0.3.2

**Comment by christopherthielen** [comment]
that is weird.  I'll update the plunker to match those versions and see if it changes

**Comment by christopherthielen** [comment]
Still seems to work.  ¯\_(ツ)_/¯

https://plnkr.co/edit/Fa6CD6n3DZJERvhqUo16?p=preview

**Comment by holtc** [comment]
yeah I changed it too and it still works on the plunker.  Who knows why it wasn't working, but it seems to only have been an issue for me that got fixed once I updated to the new version.  Thanks for looking into that!
