### ISSUE TITLE
$stateChangeStart doesn't fire in release 1.0

### ISSUE THREAD

**Issue by achernykh** [angular-ui/ui-router#3141]
Trying to route to component and test some function for my project.
$stateChangeStart doesn't fire in run function. Plnkr example - http://plnkr.co/edit/tPjwXm52XJwgAEOe5rS2?p=preview

If you change lib from **<script src="//npmcdn.com/angular-ui-router@1.0.0-alpha.4/release/angular-ui-router.js"></script>** to **<script src="//angular-ui.github.io/ui-router/release/angular-ui-router.js"></script>** $stateChangeStart works well.

This is bug, or new version doesn't support state change events?

**Comment by kukac7** [comment]
@achernykh check docs: https://ui-router.github.io/docs/latest/modules/ng1_state_events.html

**Comment by achernykh** [comment]
@kukac7 thanks for link.
It made its task through service $transition. Great!
```
$transitions.onBefore(
      { to: '*', from: '*' },
      (trans) => console.log('$stateChangeStart ', trans, trans.$to(), trans.$from())
    )

$transitions.onSuccess(
      { to: '*', from: '*' },
      (trans) => console.log('$stateChangeSuccess ', trans, trans.$to(), trans.$from())
    )
```

**Comment by christopherthielen** [comment]
@achernykh you probably want to either use two stars `**` or just use an empty criteria object `{}`, which matches all transitions.

See the [docs for transition match criteria](https://ui-router.github.io/docs/latest/interfaces/transition.hookmatchcriteria.html) and [globs](https://ui-router.github.io/docs/latest/classes/common.glob.html#double-star-)

**Comment by achernykh** [comment]
@christopherthielen thanks, great solution and doc

**Comment by orm81zp** [comment]
Thanks a lot! This example (http://plnkr.co/edit/KRyQN2Pvg23Qc5d7HImq?p=preview) helped very much!

I just needed to add a stateEvents.js file into a project.
