### ISSUE TITLE
Unclear what type is used for $locationProvider

### ISSUE THREAD

**Issue by nwp** [angular-ui/ui-router#3143]
I'm attempting to upgrade to the 1.0 branch in an Angular 1.5 application using TypeScript. In setting up the routes, we typically like to type the arguments like is shown for `$stateProvider` and `$urlRouterProvider` below. However, we have not been able to identify the proper type for `$locationProvider`. What class and/or interface can we import to correctly type it?

```typescript
import uiRouter, {StateProvider, UrlRouterProvider} from 'angular-ui-router';

.config(($stateProvider: StateProvider, $urlRouterProvider: UrlRouterProvider, $locationProvider: any) => {

        $urlRouterProvider.otherwise('/');
})
```

**Comment by christopherthielen** [comment]
`$locationProvider` not ui-router, it's an angular service.  If you have `@types/angular` installed, you should be able to 

```js
import { ILocationProvider } from "angular";
```
