### ISSUE TITLE
ui-router with commonjs

### ISSUE THREAD

**Issue by rafakwolf** [angular-ui/ui-router#3145]
Hi, first of all, great work here...

Until today i was using jspm with systemjs, and everithing was working fine, but jspm have some problems with typescript ..

migrating to webpack with commonjs ... and so my routes have stopped working... 

need i change something for ui-router and commonjs ?

Thanks!

**Comment by christopherthielen** [comment]
ui-router is written using ES6 modules. There is known interop issues with commonjs.  
You probably need to do `import uiRouter from "ui-router"` then use `uiRouter.default` to get the default export.

Please see the [migration document](https://ui-router.github.io/guide/ng1/migrate-to-1_0#commonjs-module-name) for details.

Let me know if this solves your problem.

**Comment by rafakwolf** [comment]
@christopherthielen ok, thanks
