### ISSUE TITLE
onBefore hook callback swallow errors

### ISSUE THREAD

**Issue by samithaf** [angular-ui/ui-router#3149]
Looks like onBefore hook callback swallow errors. Instead it should throw the errors. Please see the Plunker example. oops method is never defined. But there is no error. 

https://plnkr.co/edit/aGByYaXxW9RhPaadDxcc?p=preview

**Comment by christopherthielen** [comment]
I think this was fixed in 1.0.0-beta.1. 

I updated your plunker from alpha.5 to beta.3 and the default error handler reports the error to the console:  https://plnkr.co/edit/BGPyfryBhhQ7H0uG6Krb?p=preview
