### ISSUE TITLE
ng2: Lazy Loading webpack

### ISSUE THREAD

**Issue by Jordan-Hall** [angular-ui/ui-router#3151]
Does anyone know an example of how you get ui-router-ng2 to lazy load modules when using webpack. I've tried everything

**Comment by christopherthielen** [comment]
@Jordan-Hall are you using webpack 1.x or 2.x?

**Comment by christopherthielen** [comment]
I thought we had already released the code necessary for webpack lazy loading, but apparently it's coming in the next release 1.0.0-beta.4

See these comments for more details: https://github.com/angular-ui/ui-router/issues/3079#issuecomment-258035826
https://github.com/angular-ui/ui-router/pull/3037

I plan to write an example starting from the angular-cli

**Comment by Jordan-Hall** [comment]
I'm using Web pack 2

**Comment by aitboudad** [comment]
I did a try and seems work only for simple state :(, 
@christopherthielen is there any chance to support nested states too ?

**Comment by wpitallo** [comment]
Hi @christopherthielen, any idea when 1.0.0-beta.4 will be released with the support for Lazy Loading with webpack2?

Thanks for the help!

**Comment by wpitallo** [comment]
Ok cool, thanks so much! Been using beta.3 and it's great, just missing the Lazy Loading, thanks so much!

**Comment by christopherthielen** [comment]
It looks like we can't (yet) do AoT + lazy load with the angular-cli.  The AoT code and ngtools have related code to 1) code split with webpack and 2) rewrite `System.import()` to import the `ngfactory`.  It's currently hard coded to process ng router lazy loaded child routes.  Don't worry. We'll get there soon enough.

As of `beta.4`, we will be able to:

- Lazy Load routes in (with or without CLI) using JIT mode. 
- Run in AoT mode (with the CLI) without any lazy loaded routes.  
- Both AoT compile with Lazy Loading (without the CLI) by manually changing lazy loading to `System.import('../aot/foo/foo.module.ngfactory').then(x => x.FooModule)`.

To streamline support in the CLI, I'm changing the API to:

JIT:
```js
{ name: 'foo.**', url: '/foo',
  loadChildren: () => System.import('./foo/foo.module').then(x => x.FooModule) }
```

JIT shorthand (and future syntax for CLI support):
```js
{ name: 'foo.**', url: '/foo',
  loadChildren: './foo/foo.module#FooModule' }
```

AoT:
```js
{ name: 'foo.**', url: '/foo',
  loadChildren: () => System.import('../../aot/app/foo/foo.module.ngfactory').then(x => x.FooModule) }
```

**Comment by christopherthielen** [comment]
This issue was moved to ui-router/ng2#27
