### ISSUE TITLE
Root state parameter values not available

### ISSUE THREAD

**Issue by adrianhara** [angular-ui/ui-router#3152]
I have a very similar scenario to the demo app: whenever the user tries to access a state that requires auth, there's a hook which redirects him to the login state. The additional requirement is that someone might want to access a state via URL with an additional querystring parameter: `username` which should be auto-populated in the login page's corresponding input.

My states structure is like so:

- there is a `shell` abstract state which is parent to all other states similar to the `app` state in the demo app
- this `shell` state has `url: '?username'` (if I understand correctly this parameter should then be inherited by all other states)
- my `login` component has a binding `username: '<'`
- the `login` state has a `resolve` like so ` username: $transition$ => $transition$.params().username`

The whole login/redirect mechanism works perfectly. The only problem is that in the `login`'s state `resolve` the `params().username` is undefined even if in the browser I go to a link like `http://mysite/#/somestate?username=foo`.

Any idea what I'm doing wrong or how I can achieve what I'm after?

Thanks!

p.s.: I'm not sure if posting here or on stackoverflow is best, so I posted on both (http://stackoverflow.com/questions/40594472/angular-ui-router-state-query-string-parameter-not-working). Please close this issue if stackoverflow's the way to go.

**Comment by adrianhara** [comment]
I'm going to answer my own question: the problem was actually in the login redirect hook. There I was redirecting to the login state with `state.target('login', params, {location: false})` and I was getting the `params` from `transition.router.stateService.params` which never had valid values. 

Just trying stuff out I found that actually `transition.params()` gives me the correct parameter values, so I can now redirect with those params and it works fine.

I do have one issue still though: I would ideally like that after login I redirect back to the originally requested state and clear these params from the querystring. Is that possible/supported?

**Comment by christopherthielen** [comment]
In the sample app, the [return to state and parameters are captured as a resolve](https://github.com/ui-router/sample-app-ng1/blob/master/app/main/app.states.js#L59-L83) 

If the user was redirected to /login, it sends them back to the state/params from the original transition (which they got redirected from).

```
  if ($transition$.redirectedFrom() != null) {
    return $transition$.redirectedFrom().targetState();
  }
```

This can easily be modified to return a target with the `username` parameter cleared out:
```js
  if ($transition$.redirectedFrom() != null) {
    var $state = $transition$.router.stateService;
    var orig = $transition$.redirectedFrom()
    var params = Object.assign({}, orig.params());
    delete params.username;
    return $state.target(orig.state(), params);
  }
```

hope this is helpful!

**Comment by adrianhara** [comment]
Thanks for the answer!

I tried it however I get `orig.state` is not a function. What am I missing?
