### ISSUE TITLE
Better way to pass params to component?

### ISSUE THREAD

**Issue by jam13** [angular-ui/ui-router#3157]
Before 1.0 we were using the following to define a view:

      .state('foo', {
        url: '/foo',
        views: {
          '': {
            template: '<foo></foo>'
          },
          'menu@layout-default': {
            template: '<menu menu-type="foo"></menu>'
          }
        }
      })

This still works in 1.0, but to transition to using component syntax I have to do:

      .state('foo', {
        url: '/foo',
        resolve: {
          menuType: function() { return 'foo'; }
        },        
        views: {
          '': {
            component: 'foo'
          },
          'menu@layout-default': {
            component: 'menu'
          }
        }
      })

which doesn't feel like an improvement.

Is there a better way to pass literals through to the component, or should I just stick to the template syntax?

**Comment by christopherthielen** [comment]
You can clean this up a bit.  Use the [named views component shorthand](https://ui-router.github.io/docs/latest/interfaces/ng1.ng1statedeclaration.html#component)
```
  .state('foo', {
    url: '/foo',
    resolve: {
      menuType: function() { return 'foo'; }
    },        
    views: {
      '': 'foo'
      'menu@layout-default': 'menu'
    }
  })
```

ES6 sugar could also shorten this a bit 

```js
  .state('foo', {
    url: '/foo',
    resolve: {
      menuType: () => 'foo'
    },        
    views: {
      '': 'foo'
      'menu@layout-default': 'menu'
    }
  })
```

or in ES5, a helper method

```js
  function literal(str) {
    return function() { return str; }
  }

  $stateProvider.state('foo', {
    url: '/foo',
    resolve: {
      menuType: literal('foo')
    },        
    views: {
      '': 'foo'
      'menu@layout-default': 'menu'
    }
  })
```

Or, of course, you can continue to use a template :)

**Comment by jam13** [comment]
Thank you, that's useful to know.

The main thing I wasn't happy with was the separation of the menuType and the view to which it applied. Although in this case it's not a problem, I can see a case where you might want to use the same component multiple times with different arguments. I don't suppose supporting something like resolve _inside_ the named views is a practical option is it?

**Comment by christopherthielen** [comment]
Unfortunately, providing different "resolve" to each views isn't something we support, nor is it something I'm comfortable implementing.

We do offer [`bindings` mapping on a per-view basis](https://ui-router.github.io/docs/latest/interfaces/ng1.ng1viewdeclaration.html#bindings).  This is going to make your configuration a little bloatier though.


```js
.state('foo', {
    url: '/foo',
    resolve: {
      resolveData: () => 'foo'
    },        
    views: {
      '': {
        component: 'foo',
        bindings: { resolveData: 'fooInput' }
      },
      'menu@layout-default': {
        component: 'menu',
        bindings: { resolveData: 'menuType' }
      }
    }
  })
```

**Comment by jam13** [comment]
I think that covers it, thank you.
