### ISSUE TITLE
Wiki and guides for angular2?

### ISSUE THREAD

**Issue by kennyjacob** [angular-ui/ui-router#3158]
I checked out the wiki at https://github.com/angular-ui/ui-router/wiki and I couldn't find the wiki for angular2. Could you provide the correct link for it? Thanks!

**Comment by christopherthielen** [comment]
Start at http://ui-router.github.io/ng2

There isn't currently a wiki for ng2, but if should go here: https://github.com/ui-router/ng2/wiki

Thanks for your interest!
