### ISSUE TITLE
Angular 1: 0.3.x to 1.0.0-beta-3

### ISSUE THREAD

**Issue by jasonbodily** [angular-ui/ui-router#3159]
First off, I love ui-router. It has some extraordinary features that other routing services don't, and it's why I haven't been able to get away from Angular. 1.0.0-beta-3 has some great features, specifically the route to component feature, where you don't have a template (Binding the resolve object directly to the component bindings = genius. Love it).

**QUESTION**: I'm on an Angular 1 app. I've been trying to keep my payload sizes down and noticed that version 0.3.2 is ~35K, while 1.0.0-beta-3 is ~100K. If I'm just using Angular 1 and want simple upgrades like the route-to-component feature, what's the extra 60K for? Are there a lot of provisions for Angular 2? I suspect there's not much that can be done here, but wanted to understand.

(Side Note: If I had my perfect world, someone would make a light version Angular 1.5.8 with only modern components and ui-Router. And I feel like you could do it under a payload size 100K. Vuejs can do this, but I love ui-router's fx so much more because it's easily component-izable, and brief code. Anybody else feel this way?)

**Comment by christopherthielen** [comment]
Hi @jasonbodily 

I share your concern about file size increasing.  UI-Router 0.4.0 is currently at 12306 bytes minified/gzipped, while 1.0.0-beta.4 weighs in at 29650 bytes.  That's a increase of 17344 bytes (2.4x larger). 

I think 1.0 brings a lot more to the table than the legacy branch:
- transition api
- view api
- future states
- route to component
- dynamic parameters
- resolve policy
- rewrite/modular design/plugin api (enables ng2, react, sticky states, deep state redirect, etc)

I've wondered myself what has contributed the most to the file size increase.  I don't think there's any one thing that is responsible for the growth, although I do know that ES6 modules and webpack bundling has been a contributor (10% maybe?).  After 1.0 I am planning to investigate using rollup to build the bundles. 
For legacy branch, there's a route to component polyfill you could check out:  https://github.com/softsimon/ui-router-route-to-components

---

I appreciate the feedback.  Bundle size is important to me.   However, I don't think bundle size will shrink much going forward. I'm closing this ticket, but feel free to respond.
