### ISSUE TITLE
memory is growing too fast

### ISSUE THREAD

**Issue by Lijie-Gao** [angular-ui/ui-router#3160]
hi ui-router team,
i have a question: when i use ui-router, change label(state),Memory is growing too fast, i think is there pre-controller destroy unsuccessful, please help me~

this is my code, and every controller is big:
app.config(['$stateProvider', '$urlRouterProvider', function ($stateProvider, $urlRouterProvider) {
        $urlRouterProvider.otherwise('/inspect');
        $stateProvider
            .state('inspect', {
                url: '/inspect',
                templateUrl: 'inspect/inspect.html',
                controllerUrl: 'inspect/inspectCtrl',
                controller: 'inspectCtrl'
            })
            .state('check', {
                url: '/check',
                templateUrl: 'check/check.html',
                controllerUrl: 'check/checkCtrl',
                controller: 'checkCtrl'
            })
            .state('query', {
                url: '/query',
                templateUrl: 'query/query.html',
                controllerUrl: 'query/queryCtrl',
                controller: 'queryCtrl'
            })
            .state('statistics', {
                url: '/statistics',
                templateUrl: 'statistics/statistics.html',
                controllerUrl: 'statistics/statisticsCtrl',
                controller: 'statisticsCtrl'
            });
    }]);

**Comment by christopherthielen** [comment]
I'm afraid there isn't enough information here to help.  If you can make a sample app in a plunker that reproduces the problem ( http://bit.ly/UIR-Plunk ) then we could take a look.
