### ISSUE TITLE
1.0 : Get toState values in onStart transitions

### ISSUE THREAD

**Issue by benjhoo** [angular-ui/ui-router#3161]
Hi,

I'm looking for how to get the raw value of state parameters during a "onStart" transition.

I'm using "$transition$.$to().params" which returns an object {myParam: Param} but then, I can't get the value of my param within the Param Object.

Here's a plunk : [plnkr.co](http://plnkr.co/edit/I6ozUMhKc9E3MQxpzUQe)

Thank you.

**Comment by benjhoo** [comment]
I finally found a solution using the targetState() function instead of the $to() function.
But I still have a strange behavior. On abstract state, params are well updated but the state name and template seem not to refresh, unless you click a second time on the state url.

[plnkr.co](http://plnkr.co/edit/I6ozUMhKc9E3MQxpzUQe)

Any idea ? Is this a bug ?
Thanks

**Comment by benjhoo** [comment]
Obviously, the reason seems to be because I have the same url for my 2 substates 'index' and 'other'.
If I set 2 distinct urls, everything seems to work fine.

But in my project I would have the same url (the abstract one) for all my substates.
Is this possible without having this state problem ?
Thanks

**Comment by mrohr** [comment]
Have you tried:
```
$transitions.onStart({}, function(transition){
    let toParams = transition.params('to');
    ...
});
```


>

**Comment by christopherthielen** [comment]
Hi @benjhoo 
As @mrohr  commented, you want `$transition$.params()`

I've updated your plunker: http://plnkr.co/edit/gBgH4f2oHGkfiQ5LE6B7?p=preview

> But in my project I would have the same url (the abstract one) for all my substates.

Remove the url from the substates

---

hope this helps!

**Comment by benjhoo** [comment]
Hi, 
thank you for your answers.

But if I remove the 'url' param from my substates, the url seems not to be displayed on the plunker, when you click on links (only show /home).
