### ISSUE TITLE
State open modal dialog not working on second time.

### ISSUE THREAD

**Issue by lbngoc** [angular-ui/ui-router#3162]
I'm not sure this is bug of ui-router or my code, I have an abstract state called 'guestModal' to open modal, then base on child-state, I continue showing the form (in my case is: login/register).
I use `Angular 1.5.6`, `UI Router 1.0.0-beta-3`.
Below is my code:
```
app
  .config(function ($stateProvider) {
    var states = [
      {
        name: 'guestModal',
        url: '/guest',
        abstract: true,
        resolve: {
          onenter: function($uibModal) {
            console.log('on enter modal');
            $uibModal.open({
              component: "loginModal",
              size: 'lg'
            });
          }
        }
      },
      {
        name: 'login',
        url: '/login',
        parent: 'guestModal',
        views: {
          "modalBody@": {
            component: "loginForm"
          }
        }
      },
      {
        name: 'register',
        url: '/register',
        parent: 'guestModal',
        views: {
          "modalBody@": {
            component: "registerForm"
          }
        },
      }
    ];
    angular.forEach(states, function(state) {
      $stateProvider.state(state);
    });
  })
  .component('loginModal', {
    templateUrl: 'login/modal.html',
    bindings: {
      modalInstance: "<",
      resolve: "<",
      close: '&',
      dismiss: '&'
    }
  })
  .component('loginForm', {
    templateUrl: 'login/form-login.html',
    bindings: {
      title: "@",
    },
    controller: function() {
      ...
    }
  })
  .component('registerForm', {
    templateUrl: 'login/form-register.html',
    controller: function() {
      ...
    }
  })
;
```

modal.html

```
<div class="modal-header">
  <a href="#" class="close" data-dismiss="modal" aria-hidden="true" ng-click="$ctrl.close()">
    &times;
  </a>
  <h4 class="modal-title">
    My modal
  </h4>
</div>
<div class="modal-body" ui-view="modalBody">
</div>
```

index.html
```
<a ui-sref="login">Login</a>
```
At currently, it just working on the first time I click Login on `index.html`. But when I close modal login and click it again, nothing was happended. :(
A small additional question that is how can I pass a param from loginForm and registerForm to `modal.html`, I want to replace `My modal` title with name form loginForm, registerForm component.

Thanks all for support !!!

**Comment by christopherthielen** [comment]
@lbngoc This is a bug in your app logic.
When the `guestModal.login` state is activated, the resolve/onEnter for guestModal causes the modal to activate.  After closing the modal, you're still in the `guestModal.login` state.  Because of this, the second time you click the `guestModal.login` link, the state is already entered, so the resolve doesn't fire a second time.


> A small additional question that is how can I pass a param from loginForm and registerForm to modal.html, I want to replace My modal title with name form loginForm, registerForm component.

You can bind the Title to a resolve object on the parent, then upate that object on the child:


```js
     {
        name: 'guestModal',
        resolve: {
         title: function() { return { text: "Default title text" } }
        }
      },
      {
        name: 'login',
        parent: 'guestModal',
        onEnter: function(title) { title.text = "LOGIN TITLE TEXT" }
        }
      },
```

Hope this helps!

**Comment by lbngoc** [comment]
@christopherthielen  thank you so much
