### ISSUE TITLE
url pattern that Matches on several state issue

### ISSUE THREAD

**Issue by mackelito** [angular-ui/ui-router#3167]
First off.. so sorry for posting this question here but I have spent several days trying to figure this out :/

Also I have already asked the question on SO (http://stackoverflow.com/questions/40741143/how-to-structure-my-states-and-routing-in-ui-router) but not much action there 👎 

I have a plunkr to illustrate the problem I have: http://plnkr.co/edit/gXzDO5j3arP8QCrpwL9k?p=preview

Note: I´m using 1.0.0.beta.3

In short the problem is url patterns.
I have 4 states: 
home,
home.category,
home.category.product
home.router

The issue is that I need to match a list (urlRewrites) for the router state.
some of the navigation is via ui-sref and then it´s fine.. but all links that comes from the CMS needs to be resolved somehow as they can be either a category, productpage or a cms-page.

Once again I´m sorry for posting a question here but I´m out of ideas.. :(

**Comment by christopherthielen** [comment]
You can add a hook that determines the correct substate.  Add the hook as onEnter for each substate.  The hook redirects if the other substate was about to be activated. 

http://plnkr.co/edit/gFn7i0DBPsOQoX236LWI?p=preview

```js
  const figureItOut = ($transition$) => {
    console.log('figuring it out')
    let url = $transition$.params().url;
    let stateForParam = url === '/gear' ? 'home.category' : 'home.router';
    if ($transition$.to().name !== stateForParam) {
      return $transition$.router.stateService.target(stateForParam, $transition$.params());
    }
  }

  $stateProvider.state({ 
    name: 'home.category', 
    url: '/{url:any}',
    onEnter: figureItOut,
    controller: function() { }, 
    template: '<h1>category state loaded</h1> ' +
              '<div ui-view></div>'
  });

  $stateProvider.state({ 
    name: 'home.router', 
    url: '/{url:any}', 
    onEnter: figureItOut,
    controller: function() { }, 
    template: '<h1>router state loaded</h1> ' +
              '<div ui-view></div>'
  });
  
```

hope this helps
