### ISSUE TITLE
Bind ui-sref to DOM events other than click

### ISSUE THREAD

**Issue by Thrilleratplay** [angular-ui/ui-router#3169]
There are occasions when `ui-sref` will not work as intended as when bound to the click event.  A common example is when a navigation menu that will hide when the blur event is triggered.  Blur is triggered before click so a `ui-sref` link will do nothing.  The [work around](http://stackoverflow.com/questions/27514036/using-ng-blur-and-ui-sref-doesnt-work-as-expected) is to execute `$state.go` on mousedown.  Other times, I want to highlight on a single click and go to a state on doubleclick.   

Could there be an option to override the default binding where mousedown and dblClick are possible   triggers for `ui-sref`?

**Comment by christopherthielen** [comment]
hmm, interesting idea.  I think your argument is sound.

I would accept a PR which adds this capability using `ui-sref-opts="{ event: ['click', 'mousedown'] }"`

**Comment by gcca** [comment]
Currently I am working on this feature for legacy version in https://github.com/gcca/ui-router/commit/c3551198aa16ee5e5c4b8dcb1a9b884fa209b030
@christopherthielen, are you consider this feature to UI-Router for Angular 2?

**Comment by christopherthielen** [comment]
@gcca if you make a PR for ng1 or ng2 I'll review and merge it.
