### ISSUE TITLE
Optional query parameter issue

### ISSUE THREAD

**Issue by musay** [angular-ui/ui-router#3171]
I'm not sure whether it is a bug. May be it's a wrong usage of query parameters. The issue can be seen here: https://stackoverflow.com/questions/40807767/weird-ui-sref-behaviour-old-params-still-remain-at-url-although-trying-to-chang

**Comment by christopherthielen** [comment]
http://plnkr.co/edit/uvjihugRJQFVUsLpsWL6?p=preview

By default ui-sref 'inherits' parameter values.  This means when clicking the second link, it merges the parameters with the current parameter values.

I updated your plunker with `ui-sref-opts="{ inherit: false }"`

Hope this helps
