### ISSUE TITLE
Angular-ui-router 1.0.0xx $stateChangeError not firing

### ISSUE THREAD

**Issue by ArthurianX** [angular-ui/ui-router#3172]
Hey guys, love ui-router, but I'm a bit of a bind.

So, at this point I'm using `1.0.0xx`-s route to component feature, and I'm really stuck on a `$stateChangeError` not firing when I reject a route resolve, I tested it with `1.0.0-beta2`, `1.0.0-beta3` and `0.3.2`. The state change error event is caught only in `0.3.2`, but there I don't have the route to component feature and a dozen or so components depend on that.

Is this issue known, or is a deprecated feature etc ?

**Comment by ArthurianX** [comment]
Looking through the code & documentation I see a new service, `$transition`, is there a real world example of its usage somewhere ?

**Comment by briced** [comment]
With 1.0.0-beta.3, I use
`
angular.module(...)
.run(($transitions, $state) => {
	$transitions.onError({}, ($transition$) => {
    	if ($transition$.$to().name !== 'init' && $transition$.$from().name !== 'error') {
            $state.go('error);
        }
    });
});
`

**Comment by ArthurianX** [comment]
Yes.
I ended up using the transitions services. 

But it still feels a bit Hackish as I am accessing a _ property to get the toState.

**Comment by SenHeng** [comment]
@ArthurianX 

I'm attempting to update from 0.2 to beta-3 too.
From the docs, it looks like `$from()` and `$to()` replace the old `fromState` and `toState`.
https://ui-router.github.io/docs/1.0.0-beta.3/classes/transition.transition-1.html

```
$transitions.onStart({}, (trans) => {
   let to = trans.$to();
  console.log(to); // {url: UrlMatcher, templateUrl: "test.html", controller: "testController", resolve: Object, data: Object…}
});
```

**Comment by christopherthielen** [comment]
> I see a new service, $transition, is there a real world example of its usage somewhere ?

Read the docs for [`$transition$` (a `Transition`)](https://ui-router.github.io/docs/latest/classes/transition.transition-1.html)  

Then read the docs for [`$transitions` (the `TransitionService`)](https://ui-router.github.io/docs/latest/classes/transition.transitionservice.html)

The sample app [has some examples](https://github.com/ui-router/sample-app-ng1/blob/8604ca2c7c7d5ac4db8ed3a96c1f3b8825b722dd/app/global/requiresAuth.hook.js#L27)

> But it still feels a bit Hackish as I am accessing a _ property to get the toState.

You should not need use a _ property to get the toState.  Use `$transition$.to()`

```js
$transitions.onError({}, ($transition$) => {
  var toState = $transition$.to().name;
});
```

Hope this helps!

**Comment by christopherthielen** [comment]
oh, one more thing... there is a polyfill for the  $stateChange* events.  

See https://ui-router.github.io/guide/ng1/migrate-to-1_0#state-change-events and https://ui-router.github.io/docs/latest/modules/ng1_state_events.html

**Comment by devotis** [comment]
In the [migration guide](https://ui-router.github.io/guide/ng1/migrate-to-1_0#default-error-handler) I read about using this approach

```
app.run(function($state) {
  $state.defaultErrorHandler(function(error) {
    // make noise
  });
})
```

I guess that would be useful too to migrate from the `$stateChangeError` event as a less configurable option to `$transitions.onError`.
