### ISSUE TITLE
ngAnimate donsen't works with angular 1.5.x

### ISSUE THREAD

**Issue by HectorRPL** [angular-ui/ui-router#3173]
Problem with versions.

Try with your self
http://plnkr.co/edit/EmNvz8?p=preview

here the last version angular

<script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.9/angular.js"></script>

**Comment by christopherthielen** [comment]
The linked plunker animates fine for me.  Closing, but feel free to respond with more in formation.

https://gfycat.com/AppropriateIlliterateJackal
