### ISSUE TITLE
TypeScript error: '...node_modules/ui-router-ng2/state/stateService.d.ts(16,14): Error TS1005: '=' expected.

### ISSUE THREAD

**Issue by mryarbles** [angular-ui/ui-router#3175]
I just tried installing and configuring 1.0.0-beta.3. Getting error in typings file:

TypeScript error: '...node_modules/ui-router-ng2/state/stateService.d.ts(16,14): Error TS1005: '=' expected.

I took a look and don't have the foggiest why it would throw it...

**Comment by christopherthielen** [comment]
What version of typescript are you using?

**Comment by christopherthielen** [comment]
This is closed by https://github.com/ui-router/core/commit/65badf4f85cec2408c655b8f0033234191766ec5
