### ISSUE TITLE
Does using $stateProvide.state passing an state definition loses the chance of using dot syntax to access child states?

### ISSUE THREAD

**Issue by mfidemraizer** [angular-ui/ui-router#3181]
See this [Q&A that I've published on StackOverflow](http://stackoverflow.com/questions/40907333/whats-wrong-with-my-code-to-go-to-a-child-state-in-ui-router#40907725).

I've developed a modular application framework which defines child states using state definitions:

```
$stateProvider.state({
      parent: "modules/whatever-module/main",
      name: "results"
      url: ""
});
```

My concern is that I'm not able to go to a state using `$state.go("modules/whatever-module/main.results")` but I'm forced to do this: `$state.go("results")`.

What's wrong in my approach?

**Comment by christopherthielen** [comment]
This seems wrong to me: `"modules/whatever-module/main"`

It's odd that a state name has slashes in it, although I can't think why that would cause it to fail.

**Comment by christopherthielen** [comment]
@mfidemraizer I totally missed your point last week.  

Currently you have to use "results".  In the future, we may change that.

Here is the issue to watch/comment on: https://github.com/ui-router/core/issues/5

**Comment by mfidemraizer** [comment]
Hi, @christopherthielen 

Sorry for my delay on following your answers. I'll look forward for the issue on the mentioned referenced issue!
