### ISSUE TITLE
event.preventDefault() doesn't work in an abstract state controller

### ISSUE THREAD

**Issue by benjhoo** [angular-ui/ui-router#3183]
Hi,
I have an abstract state with some substates in my router.
A controller is attached to the abstract state in which I'm using the $stateChangeStart event, to alert the user if he's leaving one of the substates.

`$scope.$on("$stateChangeStart", (event, toState, toParams, fromState) => {
  if (!toState.name.match(/^page\./)) { // my abstract state and all substates name begin with page.
    event.preventDefault();
    console.log(event);
  }
}
`

The event is well fired, and the program enters in the "if" block, but the transition is never prevented.

console.log(event) displays :
`
Object
  currentScope  : null
  defaultPrevented : true
  name : "$stateChangeStart"
  preventDefault : ()
  targetScope : Scope
`

Any ideas of why ?

Thanks

**Comment by christopherthielen** [comment]
seems like it should work.  Can you provide a reproduction?

**Comment by benjhoo** [comment]
I'm not able to reproduce the problem again... weird.
I don't know what changes I made that solved the problem.

Ticket can be closed.
Thank you.
