### ISSUE TITLE
Access previous state params

### ISSUE THREAD

**Issue by VamsiVempati** [angular-ui/ui-router#3186]
I have a search refine process where I only want to change the url before actually changing the state and the triggering of the search itself depends on whether there is a particular change in the parameters in the url - meaning I need to compare the previous and current state params. So, I was looking at the parameters in `uiOnParamsChanged `function but it doesn't seem like I can access previous state params. So, I am after something like `$state.previous.params. `

Using #0.2.13.

I also see another issue (feature) raised for the similar problem - https://github.com/angular-ui/ui-router/issues/92

Couldn't comment on that thread. Any help/update is very much appreciated, thanks.

**Comment by christopherthielen** [comment]
I think you want to inject the Transition then get `Transition.params('from')`

See: https://ui-router.github.io/docs/latest/classes/transition.transition-1.html#params

Hope this helps

**Comment by VamsiVempati** [comment]
Hi @christopherthielen I have injected $transition but the from and to params, both have the same state details of the destination. It does not have the previous state params information.

**Comment by SaadeMotion** [comment]
@VamsiVempati Same here, did you get it?

**Comment by christopherthielen** [comment]
Here's a plunker that demonstrates `$transition$.params('from');`

http://plnkr.co/edit/A9bWz3v7IsTAcurJJgmF?p=info

**Comment by SaadeMotion** [comment]
@christopherthielen yes! I already get it, thanks bro! ✌️
