### ISSUE TITLE
Unable to transition to child state without url

### ISSUE THREAD

**Issue by headly48** [angular-ui/ui-router#3192]
Currently experiencing an issue when trying to change to a state that doesn't have a url

Below are the states that I am trying to use
apps
apps.create (url: /create)
apps.detail (abstract: true, url: '/view/:appId')
apps.detail.view (url: '')
apps.detail.credentails (abstract)
apps.detail.credentials.apiSelect

I'm trying to transition from apps.create to apps.detail.credentials.apiSelect however this results in it going to the apps.detail.view state instead. If i add a url to the 'apps.detail.credentials.apiSelect' then it works as expected

Plnkr can be found here:
http://plnkr.co/edit/J3oNuqGIXUfDNtpeDPRn

Current workaround I'm using is to pass a redirectToCreds param when transitioning from 'apps.create' to 'apps.detail.credentials.apiSelect'. This is then picked up by the apps.detail.view controller and then transitions to 'apps.detail.credentials.apiSelect' which then succeeds. 

This seems slightly hacky and sometimes results in a less smooth experience for the user.

**Comment by christopherthielen** [comment]
Fixed in RC.1: http://plnkr.co/edit/IMTuMftbiCjFgjVacq7F?p=preview
