### ISSUE TITLE
Change URL (without state change) in onExit

### ISSUE THREAD

**Issue by felixruponen** [angular-ui/ui-router#3194]
My use case is as follows. I need to alter the url just before the current state has exited.

I have tried using the regular $state.go without luck (it will just give me an exception saying "The transition has been superseded by a different transition")

Is it possible to perform a state change in a transition hook?

PS. I'm using ui-router 1.0

**Comment by felixruponen** [comment]
So I found a way:

Use "onBefore" hook instead of onExit, return false and do a series of $state.go using promises.

**Comment by felixruponen** [comment]
So I've, done some searching and found #2977 were someone suggests using $state.target for simply redirecting to another state. But this won't work for me since I need to first update the current state and then continue with the original transition.

**Comment by felixruponen** [comment]
Ok, so this can be "fixed" by returning false in the onExit and starting a new $state.go inside a $timeout allowing the original transition to finish. Not sure if there is a better way to do this though.

**Comment by christopherthielen** [comment]
Can you create a state that has the temporary url?  

If so, you can redirect to that in `onExit`.  Pass the current transitions' , then tell that state where to go in the end.

http://plnkr.co/edit/o3q5bc7sX4oWADKupIBA?p=preview
