### ISSUE TITLE
Extending state declaration interface to work with 3rd party modules

### ISSUE THREAD

**Issue by 19majkel94** [angular-ui/ui-router#3195]
I am using `ui-router` v1.0.0-beta.3 and I use [angular-breadcrumb](/ncuillery/angular-breadcrumb) in my app. The problem is when I try to add breadcrumb label to my state definitions:

    {
        name,
        url: "/login",
        component: "cgLogin",
        ...
        ncyBreadcrumb: {
            label: "Login page"
        }
    }

I have an error:
```typescript
Argument of type '{ name: string; url: string; component: string; onEnter: any; ncyBreadcrumb: { label: string; }; }' is not assignable to parameter of type 'Ng1StateDeclaration'.
Object literal may only specify known properties, and 'ncyBreadcrumb' does not exist in type 'Ng1StateDeclaration'
```
I tried to extend and merge the definition by adding:
```typescript
declare module "angular-ui-router" {
    export interface Ng1StateDeclaration {
        ncyBreadcrumb?: {
            label?: string;
        }
    } 
}
```
or even just
```typescript
interface Ng1StateDeclaration {
    ncyBreadcrumb?: {
        label?: string;
    }
}
```
But the error is still there and I don't know how to extend module typings. Could you tell me what I'm doing wrong?

**Comment by christopherthielen** [comment]
Sticky states does something similar. 
https://github.com/ui-router/sticky-states/blob/master/src/stickyStates.ts


Ui router core 2.0 also introduces a plugin API you might want to use. See sticky states example.

**Comment by 19majkel94** [comment]
1) Sticky states does something different that I want.
2) I'm not asking for help in finding the lib/package/module for breadcrumb because I've already [found it](/ncuillery/angular-breadcrumb).
3) I just need an info how to write TypeScript definition for module merging - I can do it with [express.js](/expressjs/express) but I'm unable to do it in ui-router because it has compilcated import/export tree and I don't know how do it 😉

**Comment by christopherthielen** [comment]
Did you look at the source code I linked? It shows exactly "how to write
TypeScript definition for module merging"

**Comment by 19majkel94** [comment]
Of course, I've tried all of this `declare` but obviously no success because I don't even have installed ui-router-core. The npm@next version `1.0.0-beta.3` doesn't have it as a package dependency.

Do you know how to do this declaration merging on the old version before refactoring?

**Comment by christopherthielen** [comment]
Use `angular-ui-router/commonjs` instead of `ui-router-core/lib`

```js
declare module "angular-ui-router/commonjs/state/interface" {
  interface StateDeclaration {
    sticky?: boolean;
    onInactivate?: TransitionStateHookFn;
    onReactivate?: TransitionStateHookFn;
  }
}
```
