### ISSUE TITLE
Roadmap of the library

### ISSUE THREAD

**Issue by karensg** [angular-ui/ui-router#3198]
Hi guys,

First of all, lots of credits for an excellent work on the library. I use it in my Angular 1 website and it rocks!
At this moment I am using beta3 version in order to do component routing. Although it all looks and works good, I am a bit scared to take it in production because it is still in beta.

Could you update us a bit on the short-term future plans until the release of the 1.0 version?

Karens

**Comment by JWess** [comment]
My team has been planning for many months to migrate to the component-based UI-Router as soon as it makes it out of beta. Every couple weeks during sprint-planning we check to see if it has been released so that we know if we can start the migration process. Having some sort of ballpark projected release date would be handy.

**Comment by christopherthielen** [comment]
Expect a release candidate within the week.

**Comment by karensg** [comment]
All right! Thanks for the update. Looking forward to it.

**Comment by christopherthielen** [comment]
FYI I'm a little behind on this.  I'm going to release as beta.4 instead of RC.

**Comment by karensg** [comment]
No problem!

**Comment by karensg** [comment]
Would be great to have a fresh release, even if it is beta.4. I think that the whole active Angular 1 community is waiting for it :)

**Comment by christopherthielen** [comment]
Agreed! Trying to get all my ducks in a row.

**Comment by karensg** [comment]
Thanks! Updated today without any issues. Keep up the good work!

**Comment by christopherthielen** [comment]
Great to know!  Hope the [new docs](https://ui-router.github.io/ng1/docs/latest/index.html) are easier to use as well.
