### ISSUE TITLE
[ui-sref] Reload current state with parameter - not tracking current state?

### ISSUE THREAD

**Issue by MathewWoodhall** [angular-ui/ui-router#3199]
Hi,

I have an app that has a location setting. When a different location is clicked the app should reload the current state with the new location as a parameter. I'm trying to do this through the ui-sref directive, rather than $state.go, so the hrefs remain in the html.

Here's my ui-sref..

`<a ui-sref="{location: 'UK'}">UK</a>`

and the generated html..

`<a ui-sref="{location: 'UK'}" href="#/UK/home">UK</a>`

This works fine initially, but when I navigate to a different state and then change the location - the app jumps back to the homepage. As if ui-router isn't tracking what the current state is in ui-sref.

Is my implementation of 'ui-sref="{location: 'UK'}"' at fault? 

The generated href also doesn't update when I navigate to a different state, but I don't know if this is intentional.

**Comment by MathewWoodhall** [comment]
Found my issue..

> You can also use relative state paths within ui-sref, just like the relative
> paths passed to `$state.go()`. You just need to be aware that the path is relative
> to the state that the link lives in, in other words the state that loaded the
> template containing the link.

Which is what was causing my problem. Using the below is working for me...

` <a
                                                  data-ui-state="currentState.name"
                                                  data-ui-state-params="{location: 'UK'}" >
                                                    UK
                                                </a>`

**Comment by christopherthielen** [comment]
@MathewWoodhall what version are you using?

See #3139 #1031

In legacy branch (0.3.2) there's [code to use the current state](https://github.com/angular-ui/ui-router/blob/legacy/src/stateDirectives.js#L122) but it is only processed once, when the `ui-sref` is linked.  In 1.0 we [explicitly document that your original style should change params](https://github.com/angular-ui/ui-router/blob/master/src/ng1/directives/stateDirectives.ts#L201-L207) and we implement that by [updating the ui-sref after every state change](https://github.com/angular-ui/ui-router/blob/master/src/ng1/directives/stateDirectives.ts#L251-L252)

So, in 0.3.2, the link gets `$state.current` at the time it was linked, while in 1.0, `ui-sref="{ location: 'UK' }"` will work as you desired.

**Comment by romanzoller** [comment]
I found this issue because I wanted to do a similar thing: Change a language state param, but stay in the same state (where same means current, i.e. it can change after the page header has been loaded).
[The relevant doc says](https://github.com/angular-ui/ui-router/blob/master/src/directives/stateDirectives.ts#L216-L217):
- Unlike the parameter values expression, the state name is not `$watch`ed (for performance reasons). If you need to dynamically update the state being linked to, use the fully dynamic [[uiState]] directive.

The solution suggested by @MathewWoodhall did the trick!
