### ISSUE TITLE
How to make a login check before opening any page and add new page and controller in this template

### ISSUE THREAD

**Issue by vishad-jain** [angular-ui/ui-router#3202]
Hi everyone
I am very new to angular js and need some urgent help for my work
I am hitting api for sign in and my code is as follows

```js
'use strict';

/* Controllers */
  // signin controller
app.controller('SigninFormController', ['$scope', '$http', '$cookieStore' , '$state','$window', function($scope, $http, $cookieStore, $state,$window) {
    $scope.user = {};
    $scope.authError = null;
    $scope.login = function() {
      $scope.authError = null;
      // Try to login
      //console.log($scope.user.number);
	  
	  var data = $.param({
                username: $scope.user.number, password: $scope.user.password
            });
        
            var config = {
                headers : {
                    'Content-Type': 'application/x-www-form-urlencoded;charset=utf-8;'
                }
            }

      $http.post('http://someApi/login', data, config)
      .then(function(response) {
        if ( !response.data.rs ) {
          $scope.authError = 'Username or Password not right';
        }else{
			$cookieStore.put('session',response.data.rs);
			//var sessionUser = $cookieStore.get('session');
			// $cookieStore.remove('session');
			// var sessionUser = $cookieStore.get('session');
		   //console.log(sessionUser);
          $state.go('app.dashboard-v1');
        }
      }, function(x) {
        $scope.authError = 'Server Error';
      });
    };
  }]);
```

I want to block access of all pages if not signed in and redirect to sign in page
moreover, I want to create some more pages and get data from api on them
so for this, I need to create a new page and its controller

any help would be appreciated
thanks in advance

**Comment by Josh68** [comment]
For an auth pattern, see [the sample app](https://ui-router.github.io/resources/sampleapp/), requiresAuth.hook.js

**Comment by christopherthielen** [comment]
Either use an auth hook (in 1.0) like @Josh68 mentioned, or use `deferIntercept()` to perform your checks before the router even starts: 

- 1.0: https://ui-router.github.io/ng1/docs/latest/classes/url.urlservice.html#deferintercept
- 0.4.2: https://ui-router.github.io/ng1/docs/0.4.2/#/api/ui.router.router.$urlRouterProvider

**Comment by dvdvck** [comment]
@vishad-jain there is an example of how could use deferintercept at https://github.com/Narzerus/angular-permission/wiki/Controlling-access-in-views#async-calls-for-permissions-in-initial-states
