### ISSUE TITLE
Encoding url (Angular 1.6.0)

### ISSUE THREAD

**Issue by RSamaium** [angular-ui/ui-router#3203]
With Angular 1.6.0 (only)

The path `/#/login` is transformed by `#!#%2Flogin`

**Comment by christopherthielen** [comment]
can you show exactly what you mean in a plunker?  http://bit.ly/UIR-Plunk

**Comment by niusha-paks** [comment]
Same for us, roll backed to angular 1.5.8 and angular router to 0.3.1. What a waste of time... if only we had fixed our package.json dependencies versions...

**Comment by mbarakaja** [comment]
Anguar 1.6.0 is prefixing the URL hash part with a `!` character. I not sure, but I guess, this is making a wrong URL encoding. The solution so far If you want to use `angular@1.6.0` with `ui-router@0.3.2` is removing the prefix in the config block with **`$locationProvider`**.

```js
angular.module('app', ['ui.router'])
    .config(function($stateProvider, $locationProvider) {

      // remove ! hash prefix
      $locationProvider.hashPrefix('');

     // ui-router code ...
    });
``` 

This is working for me right now.

**Comment by christopherthielen** [comment]
This is a breaking change introduced in Angular 1.6.0.  See: https://docs.angularjs.org/guide/migration#migrating-from-1-5-to-1-6

> Changing the default $location hash-prefix to '!', as the previous empty string default was unconventional and confusing.

Revert to previous behavior using the instructions provided by @mbarakaja
