### ISSUE TITLE
State parent property should override state name

### ISSUE THREAD

**Issue by hackel** [angular-ui/ui-router#3214]
I'm working on upgrading to ui-router 1.0 and am having to correct many routes that include a . but explicitly define the parent state.  I understand why this is currently ambiguous, but couldn't it simply be define as a part of the definition?  Any time the parent property is present, the state name will be ignored.  Or are states accessed in such a way that this is not possible?

My use case is, I "namespace" all of my states per module.  So each module has a parent abstract state with the same name as the module it is contained in.

One example:
module: job, parent abstract state: job
child abstract state: job.editable
grandchild state 1: job.create (parent: job.editable)
grandchild state 2: job.edit (parent: job.editable)

In this case, both job.create and job.edit inherit their controller, template, etc. from the parent, the edit child state adds an additional resolve to load the particular job and sets a different page title.

I realize I could just refer to these as "job.editable.edit" instead, but this isn't as clear to me.  Is there a better solution to this problem that I am missing?  Should I just use a different character to namespace third-level includes? (definitely less ideal)

**Comment by christopherthielen** [comment]
@hackel interesting approach to naming states. 

Yes, I'd say you should use a different character to namespace.  I think you could use a slash `/` or hash `#` instead.  The dot `.` is definitely reserved for implicit parent naming.  

This will become even more important if we implement [fully qualified naming for states with `parent:`](https://github.com/ui-router/core/issues/5) which I'm warming up to very quickly.

**Comment by hackel** [comment]
That makes sense.  Would an adding a state alias property be valuable enough to add?  That way I could name _all_ my states with / separators.  I get the feeling this might be overkill.  I guess the other option would be to change my other states like "job.show" into "job/show" with parent: job.  Of course none of this would matter if fully qualified naming is implemented, so perhaps I should just give up now and use the full name now in preparation!

**Comment by christopherthielen** [comment]
For backwards compatibility, the state's name will continue to be treated like a unique "id" (no two states can be named 'show', even if they have different parents).  

The fully qualified name will be calculated based on `parent` properties and will be treated much like an alias.  You could access "job/show" using "job/show" (like an id) or "job.job/show".
