### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by thany** [angular-ui/ui-router#3215]
The documentation has gone weird. For example, I can't find something as simple as `$state`.

I just click on "API Docs" and get redirected [here](https://ui-router.github.io/docs/latest/). That's fine, but almost none of the providers and services from ui-router are in there. Looks like it's for a very different module?...

Where can we find the documentation for real? And can you please update the link to it, so other folks can find it, too?

**Comment by christopherthielen** [comment]
Those are the "real" docs for ui-router 1.0.

If you're looking for the legacy docs, there's a version selector you can click.  Here's the docs for 0.3.1: 

https://ui-router.github.io/docs/0.3.1/index.html#/api/ui.router

**Comment by thany** [comment]
Shouldn't it default to the latest stable version?...
