### ISSUE TITLE
ui router not showing 3rd level nodes in tree

### ISSUE THREAD

**Issue by ashwinthakre91** [angular-ui/ui-router#3220]
using 
angular 1.5.8
angular-ui-router 0.3.2

`My project is single page  #application divided into components each component defines its config file.

1. root component html contains
`<div ui-view></div>`

2. parent state contains following code in html and js files for the state:
html file
```
<div ui-view="menuContent"></div>
```
.js file
```js
function config($locationProvider, $urlRouterProvider, $stateProvider) {
    'ngInject';
    $stateProvider
        .state('startupWants', {
            abstract: true,
            `template: '<startup-wants></startup-wants>'`
        });
    $locationProvider.html5Mode(true);
    $urlRouterProvider.otherwise('/post_article');
}
```

3. child state contains following code in html and js files for the state:
html file
```
<div ui-view="xxContent"></div>
```
js file
```js
function config($stateProvider) {
    'ngInject';
    $stateProvider
        .state('startupWants.postArticle', {
            url: '/post_article',
            views:{
                'menuContent':{
                    `template: '<post-article></post-article>'`
                }
            }
        });
}
```
4. sub child state contains following code in html and js files for the state:
html file:
```
<h1>from checkone component</h1>
```
.js file
```js
function config($stateProvider) {
    'ngInject';
    $stateProvider
        .state('startupWants.postArticle.checkOne', {
            views:{
                'xxContent':{
                    `template: '<check-one></check-one>'`
                }
            }
        });
}
```
I am unable to get xxContent view in `<div ui-view="xxContent"></div>`. I have tried parent: in .state function too.
Do i need any thing extra or something am i missing.
`

**Comment by ashwinthakre91** [comment]
`My project is divided into components each component defines its config file.

1. root component html contains
<div ui-view></div>

2. parent state contains following code in html and js files for the state:
html file
<div ui-view="menuContent"></div>
.js file
function config($locationProvider, $urlRouterProvider, $stateProvider) {
    'ngInject';
    $stateProvider
        .state('startupWants', {
            abstract: true,
            template: '<startup-wants></startup-wants>'
        });
    $locationProvider.html5Mode(true);
    $urlRouterProvider.otherwise('/post_article');
}

3. child state contains following code in html and js files for the state:
html file
<div ui-view="xxContent"></div>
js file
function config($stateProvider) {
    'ngInject';
    $stateProvider
        .state('startupWants.postArticle', {
            url: '/post_article',
            views:{
                'menuContent':{
                    template: '<post-article></post-article>'
                }
            }
        });
}

4. sub child state contains following code in html and js files for the state:
html file:
<h1>from checkone component</h1>
.js file
function config($stateProvider) {
    'ngInject';
    $stateProvider
        .state('startupWants.postArticle.checkOne', {
            views:{
                'xxContent':{
                    template: '<check-one></check-one>'
                }
            }
        });
}

I am unable to get xxContent view in <div ui-view="xxContent"></div>. I have tried parent: in .state function too.
Do i need any thing extra or something am i missing.
`

**Comment by ashwinthakre91** [comment]
xzcc

**Comment by christopherthielen** [comment]
I'm going to assume all the backticks "`" in your post are typos?...

Targeting ui-views can admittedly be tricky.  Here's docs for 1.0 that describe in gory detail how it works: https://ui-router.github.io/ng1/docs/latest/interfaces/ng1.ng1statedeclaration.html#views

I don't see anything obviously wrong with your code (besides the backticks).  The `xxContent` view targets the `<div ui-view="xxContent"></div>` that is in the parent state's (`startupWants.postArticle`) template, i.e., inside the `<post-article>` directive.  

Here's a plunker demonstrating: http://plnkr.co/edit/OW6lE7PJBTywLb62sKTo?p=preview
