### ISSUE TITLE
Not Showing Page source code

### ISSUE THREAD

**Issue by jksenthilraja** [angular-ui/ui-router#3221]
Hi All

I am using **UI Router** version **v0.2.13**. Not showing page source code when i click **Ctrl+U**.This is Need for  **SEO**.

**Comment by christopherthielen** [comment]
This isn't ui-router's responsibility.  Since you chose a javascript SPA framework (angular), you are responsible for managing SEO on your own.

I highly recommend looking into a SPA SEO service like http://prerender.io
