### ISSUE TITLE
NG1 $urlRouteProvider.when with strings not triggering route change

### ISSUE THREAD

**Issue by dustinsmith1024** [angular-ui/ui-router#3225]
We are migrating to 1.0 beta 3 and noticing the `$urlRouterProvider.when` config's that we have are not working like they did. They DO change the URL but the pages are not loading and controllers are not hit.

Could be something with the controllers as we are updating to Angular 1.6 at the same time. 

Maybe something to do with the abstract route and child route not having a controller?

```js
$stateProvider.state('market-settings', {
        abstract: true,
        url: '/market/settings',
        templateUrl: '/admin/market/settings/marketSettings-view.html',
        controller: 'MarketSettingsController',
        resolve: {
            markets: MarketsResolve
        }
    })
    .state('market-settings.general', {
        url: '/general',
        templateUrl: '/admin/market/settings/generalSettings-view.html',
})
```

Original `when` working with ui-router 0.2.
```js
$urlRouterProvider.when(/^\/market\/settings(\/.*)?$/, '/market/settings/general')
```

I was able to just use the function callback and transition it manually though.
```js
$urlRouterProvider.when(/^\/insights\/offers(\/.*)?$/, function () {
    return $stateProvider.stateService.go('insights.offers.high');
})
```

**Comment by christopherthielen** [comment]
This wasn't due to an intentional change

**Comment by christopherthielen** [comment]
This is due to [delaying registration of states until we enter runtime](https://github.com/angular-ui/ui-router/blob/1.0.0-beta.3/src/ng1/services.ts#L260-L264).  I don't recall why we made that change, but it's been reverted in latest master, for beta.4.

**Comment by christopherthielen** [comment]
A workaround (for beta.3) would be capturing the `$urlRouterProvider` to a variable, then adding your `.when()` rules in a run block.

here's a beta.3 plunker with the workaround: http://plnkr.co/edit/m8rkTor6l7P7aNhYzLMq?p=preview

**Comment by dustinsmith1024** [comment]
The change in beta 4 is working for me.  Thanks!

**Comment by christopherthielen** [comment]
Note that `rc.1` introduces a breaking change related to this issue:  https://github.com/angular-ui/ui-router/releases/tag/1.0.0-rc.1

Search "Order URL Matching Rules"
