### ISSUE TITLE
Angular2 - otherwise is not working the first time

### ISSUE THREAD

**Issue by danicomas** [angular-ui/ui-router#3227]
The first time I do ```http://<domain>``` is not loaded the first component(UsersComponent), only the AppComponent. If I do ```http://<domain>/#/``` it works well.

I attach the plunkr below:
http://plnkr.co/edit/9UM8TMjf1xCj5nEsdDmR

@christopherthielen

P.S:
_I relate other issue I opened: https://github.com/angular-ui/ui-router/issues/3223#issuecomment-268965109_

**Comment by christopherthielen** [comment]
At first glance, this does appear to be a bug, thanks for the report (and also for the great plunkers! so very nice to get plunkers right away!)

For now you can use `otherwise: { state: 'users' }`

http://plnkr.co/edit/2B9wb1GNNK3k8qrBQbFr?p=preview

**Comment by christopherthielen** [comment]
Moving this bug to the ng2 repository: https://github.com/ui-router/ng2/issues/17
