### ISSUE TITLE
ui-router html5Mode doesn't like hrefs to static html files

### ISSUE THREAD

**Issue by esinek** [angular-ui/ui-router#3228]
Posted to SO.
http://stackoverflow.com/q/41291374/156611

Plunker here.
http://plnkr.co/edit/nFtjHX?p=preview

When using ui-router without html5Mode, anchor tags that do a full page refresh to other pages (or static html content) using hrefs are working properly. As soon as I enabled html5Mode, the hrefs are updating the URL in the browser, but no server request is made.

I was under the impression that html5Mode would work like non-html5Mode in that it would respect hrefs vs ui-sref.

I've created a plunker where, if you set it to html5Mode(true), you can't navigate to the static html file. If you set html5Mode(false), you can navigate to the static html file. In both cases, all the other routing works fine.

**Comment by christopherthielen** [comment]
you can use `<a href="/external.html" target="_self">external</a>` to perform a full page load.

We process normal `href` so developers can choose to use either/or normal href/ui-sref
