### ISSUE TITLE
someone changed wiki . and I am confused.

### ISSUE THREAD

**Issue by lili21** [angular-ui/ui-router#3229]
https://github.com/angular-ui/ui-router/wiki/Nested-States-and-Nested-Views/_compare/ec5f02dd30f0de1ec2d119fc4cba95c00b5d0425...0279d28c2cedf3fb7b3dda58d6eda9fda4a08fa4

which one is true ? and which version ?

**Comment by christopherthielen** [comment]
The phrasing has always been confusing.

I changed it to: 

>If you want a child resolve to wait for a parent resolve, you should injected the parent resolve keys into the child.

Hope this helps.

**Comment by lili21** [comment]
Thanks.
