### ISSUE TITLE
Named Views: ng-model properties in template are not visible inside the respective controller.

### ISSUE THREAD

**Issue by daggubativ** [angular-ui/ui-router#3234]
index.html
------------
`1) <div ui-view="hello" ng-controller="helloCtrl"></div>`

My template for view 'hello'

`2)<input type="text" ng-model="testModel"/>
`

testModel is not visible inside helloCtrl on the $scope if we declare controller using 'ng-controller' as shown in step1.

It work's fine if we declare controller in the $stateProvider.state() as named view.

**Comment by christopherthielen** [comment]
What you're trying to do is simply not the right way.  The controller can't be defined on the ui-view.  Putting the controller in the state definition is the correct way.


I recommend avoiding `ng-controller` altogether.
