### ISSUE TITLE
crash on reload with some url names

### ISSUE THREAD

**Issue by NodeJoSe** [angular-ui/ui-router#3236]
Im having a strange problem, some routes will get frozen when i click the reload button. 

For example, a route with a exact name **"url: '/celulas'"**, ill try to explain it:

This is my route on the browser "**...localhost:8080/celulas**", when i click the reload button a slash **"/"** will appear at the end of the route like this **...localhost:8080/celulas/** then it goes back to **...localhost:8080** then it get frozen and blank screen never goes away, i cant even reload the page again, i have to close the tab because it get frozen. 

It happens with **"url: '/ce-juvenil'"**, **"/ce"**, and any **url** with a slash like **"/my/route"** 

It stop happening when i changed the urls to **"/células"** (note the accent), and **"/CeJuvenil"**

Im using **"angular-ui-router": "1.0.0-beta.3"**

**Comment by christopherthielen** [comment]
html5 mode? Do you have a base tag?  Can you update to 1.0.0-rc.1 and report back?

To diagnose your problem I will need a reproduction.  Start here: http://bit.ly/UIR-Plunk1
