### ISSUE TITLE
$stateParams vs $transition$.params()

### ISSUE THREAD

**Issue by jwickens** [angular-ui/ui-router#3237]
I was following https://ui-router.github.io/tutorial/ng1/hellosolarsystem and trying to get state params working. However, on trying to load a state with a resolve using $transition$ there was an unlogged error and nothing loaded.

I found in the hello universe docs @stateParams and that works fine.

What is the difference or do the docs need updating?

**Comment by NeoGenet1c** [comment]
Related question (that might get answered by answering @jwickens' question about the difference between those two): 

**What is the best practice to access parameters inside Services**? 

Sometimes, I find it very cumbersome to obtain `$transition$` inside a service, but documentation clearly states that `$stateParams` service should NOT be used anymore.

Is `$state.params` better option?

**Comment by christopherthielen** [comment]
> I found in the hello universe docs $stateParams and that works fine.

> do the docs need updating?

Yes, since `$stateParams` are deprecated, the tutorial needs to be updated.  Thanks for noting this!

> What is the difference

The difference is [documented in the migration guide](https://ui-router.github.io/guide/ng1/migrate-to-1_0#breaking-changes) and in the [`$stateParams docs](https://ui-router.github.io/ng1/docs/latest/modules/injectables.html#_stateparams)  for 1.0.0-rc.1

The `$stateParams` that gets injected into routed controllers is the same as `$transition$.params()` which can be seen [in the source code](https://github.com/ui-router/core/blob/master/src/transition/transition.ts#L176-L177), where it is literally an alias for `this.params()`.

**Comment by christopherthielen** [comment]
@NeoGenet1c 

> What is the best practice to access parameters inside Services?

The [`$stateParams` docs](https://ui-router.github.io/ng1/docs/latest/modules/injectables.html#instead-of-using-the-global-stateparams-service-object-) for `1.0.0-rc.1` give the suggested practice as follows: 

> inject `$uiRouterGlobals` and use `UIRouterGlobals.params`

**Comment by theatrain** [comment]
I am trying to use $transition$ in my controller instead of $stateParams but get the following runtime error: Unknown provider: $transition$Provider <- $transition$.

I am using typescript with angular 1 and a webpack build with ng-annotate, my constructor code is below:

```
constructor(private $transition$: Transition) {
   'ngInject';
}
```

**Comment by christopherthielen** [comment]
@theatrain check out https://ui-router.github.io/guide/ng1/route-to-component#accessing-transition

**Comment by theatrain** [comment]
Perfect, that works. Thanks!

**Comment by harrylincoln** [comment]
@christopherthielen , I think I'm having a similar problem where I need a $stateParams reset for parent state when sharing a single controller in child states:

http://stackoverflow.com/questions/41860680/angular-ui-router-state-params-reset-for-parent-when-sharing-controller-in-chi

If you could advise as I've researched the hell out of it and running out of ideas!

**Comment by archasek** [comment]
@harrylincoln did you come up with something?

**Comment by harrylincoln** [comment]
Yes I did! Workaround that's a little messy but safe. I basically introduced an 'init' state that inits the detail states. I will post an answer to my own questions sometime today on stackoverflow, if you're interested :)

**Comment by samiraguiar** [comment]
@christopherthielen was there any change to this? I'm using the legacy `template` style with Angular 1.2 and I get the provider error when injecting $transition$.

**Comment by harrylincoln** [comment]
@samiraguiar this may help:
https://github.com/angular-ui/ui-router/issues/3309

**Comment by samiraguiar** [comment]
@harrylincoln Thanks, Harry, but I think my problem is different.
I have a directive defined as:
```javascript
angular.module('app').directive('myDirective', function($transition$) {});
```

And my route defined as follows:
```javascript
{
    name: 'someRoute',
    url: '/path/to/route',
    template: '<my-directive></my-directive>'
}
```

But this gives me the "Unknown provider: $transition$Provider <- $transition$" error.

Here's a [plunker](https://plnkr.co/edit/UjTnbIYGlRQQHbHQoO1g?p=preview) showing the problem.

What am I doing wrong?

**Comment by harrylincoln** [comment]
@samiraguiar pretty sure you've missing a step there. Your routing won't have access to your directives since it's bound to the app.config which (I believe) is instantiated before your directives/controllers. 

Basically this won't work:
```
{
    name: 'someRoute',
    url: '/path/to/route',
    template: '<my-directive></my-directive>'
}
```
You need something like this:

1. Make sure your app knows what your directive is when initing the app:

```
angular
    .module(app, ['ui.router', require('angular-sanitize'), require('angular-animate')])
    .service('someService', requiredService)
    .config(routesConfig)
    .directive('myDirective', require('./app/directives/myDirective')) ...
```

2. Routing:

```
{
    name: 'someRoute',
    url: '/path/to/route',
    template: './template-that-uses-the-directive'
}
```

3. HTML itself:

```
<div class="container">
<my-directive></my-directive>
</div>
```

This is all in the [ui router docs](https://github.com/angular-ui/ui-router/wiki)

**Comment by samiraguiar** [comment]
@harrylincoln Thanks, Harry.

Indeed, apparently `$transition$` is only injected as local when constructing the route's controller, but not when constructing the controllers for any directive within the template.

Got it working by chaning my directive code to:
```javascript
angular.module('app').directive('myDirective', function($scope) {
    var id = $scope.$resolve.$transition$.param().id;
});
```

Though I don't find it pretty.

**Comment by harrylincoln** [comment]
Makes sense. There are many ways to skin a cat in Angular ;)

**Comment by christopherthielen** [comment]
If you are routing to a directive template, bind the transition object as an attribute like so:

```
    template: '<my-directive trans="$resolve.$transition$"></my-directive>'
```

If you are using route-to-component, you can use an input binding

```
.component('myCmp', {
  bindings: { '$transition$': '<' }
  controller: function() {
    this.$onInit = function() {
      this.$transition$.params()
    }
  }
});
```

then route to component:

```
.state({
  name: 'someRoute',
  component: 'myCmp'
});
```
