### ISSUE TITLE
ResolvePolicy NOWAIT does not behave as expected

### ISSUE THREAD

**Issue by aj-dev** [angular-ui/ui-router#3243]
According to the [API docs](https://ui-router.github.io/docs/1.0.0-beta.3/interfaces/resolve.resolvepolicy.html#async), NOWAIT should not wait for promise and should not unwrap it. This is not the case as you can see in this [plunker](https://plnkr.co/edit/1mKEYjOTOqw8leapgG6M?p=preview).

`data` is already resolved in `onEnter` hook where a resolved value is injected and not a promise. The same with the bound value in a template - it doesn't render until the `data` is resolved and promise unwrapped.

It contradicts the API docs stating that for resolve policy async: NOWAIT "The promise will not be unwrapped. The promise itself will be provided when the resolve is injected or bound elsewhere."

Related to https://github.com/angular-ui/ui-router/issues/2691

**Comment by christopherthielen** [comment]
Agreed, this needs to be fixed.

**Comment by christopherthielen** [comment]
Will be fixed in rc.1: https://plnkr.co/edit/2kOzXARHMEi1PQfPnLHK?p=preview

**Comment by christopherthielen** [comment]
Fixed  by https://github.com/ui-router/core/commit/05d4c7348c171f31a83e2c5d1f3ef6ee0751e024 
and https://github.com/angular-ui/ui-router/commit/cb57ce96a4b0d96ef123589495c3209b800d1016
