### ISSUE TITLE
ui router 1.0b3 hashes in urls propagate to other pages

### ISSUE THREAD

**Issue by phazei** [angular-ui/ui-router#3245]
I'm using html5Mode.  The hashes aren't for the routes.  I'm using them for placeholders on the page.
eg: http://site.com/angular-app/section/page#tab3

When the person switches tabs on the page, it reflects it in the url, though it doesn't add anything to the history, just a `$location.hash(newTab).replace();`.  That way when the page is reloaded, it still maintains the tab.

I came from 0.3.1 where this wasn't an issue.  Now it always propagates the hash when changing routes.  If I ui-sref or $state.go to another page, it keeps the hash.  I don't think it should, is this a bug?

http://stackoverflow.com/questions/41474457/how-to-clear-ui-router-hash-on-page-change

**Comment by phazei** [comment]
Even if I don't go to a page that uses hashes at all, if you add a # to the url anywhere, it sticks around while navigating.

**Comment by christopherthielen** [comment]
> Doesn't appear to be able to modify the params like so either:

Correct, .params() is not mutable.  The way you could handle this is by returning a new `target()` without the "#" in the params.

---

The next release of ui-router will not retain the hash parameter during subsequent transitions.

**Comment by christopherthielen** [comment]
See also: https://github.com/angular-ui/ui-router/issues/3218#issuecomment-268894949

**Comment by christopherthielen** [comment]
Closed by 849f84f7c35530b01d3ebae1a2fd500c2eebda21 in rc.1
