### ISSUE TITLE
Preventing Multiple $stateChangeStart to be called if first cancels

### ISSUE THREAD

**Issue by sebadom** [angular-ui/ui-router#3247]
Couldn't find an answer for this one...

Lets say i have two or more listeners for $rootScope.('$stateChangeStart')... Now lets say the first listeners makes an event.preventDefault and makes a redirection. Is there a way i can prevent the next listeners to be called for the original navigation?. Something like this

listenterA() - transition to ROUTE X  canceled
                  - redirect to ROUTE Y

listenerB() - transition to ROUTE Y

is there a built in solution for this? (i'm using version 2.15)

**Comment by sebadom** [comment]
I guess i could use event.defaultPrevented check in the listeners, i wanted to know if there was a solution that directly avoids  the call of the listener

**Comment by christopherthielen** [comment]
> directly avoids the call of the listener

`$on()` is core angular code, so unless angular itself has a mechanism, there's not much that can be done.  Check `event.defaultPrevented` like you mentioned.

1.0 branch uses Transition Hooks which behave the way you would expect (if a transition redirect is returned, subsequent hooks are not invoked)
