### ISSUE TITLE
Empty links by ng2 `uiSref` directive

### ISSUE THREAD

**Issue by artaommahe** [angular-ui/ui-router#3248]
`uiSref` directives binds `'null'` string to `href` on provided `null` or empty string `''` state.

current behavior
```html
<!-- template -->
<a [uiSref]="null">smth</a>
<a [uiSref]="''">smth</a>

<!-- result -->
<a href="null">smth</a>
```

expected no `href` attribute (null property value?)
```html
<!-- result -->
<a>smth</a>
```

It's required for dynamic links when for some cases `href` should be empty and link clicks does not trigger any state changes (access rights check e.x.)

**Comment by artaommahe** [comment]
Fixed expected result html, due to empty href forced to reload page

**Comment by christopherthielen** [comment]
This issue was moved to ui-router/ng2#26
