### ISSUE TITLE
Missing release 1.0.0-rc.1

### ISSUE THREAD

**Issue by jesperronn** [angular-ui/ui-router#3249]
Seems like the updated code in https://github.com/angular-ui/ui-router/commit/2f3455e650d20953b3266f8556ebe104cf4df81c

is missing two things:

1. the released package in npm
2. the tag in github

Could you please add this so that we can start using the package?

PS quick workaround to consume github repositories directly:

```
npm install --save angular-ui/ui-router#2f3455e
```

**Comment by jesperronn** [comment]
PPS. the workaround in the previous PS does not work at all. Missing release files in this repository.

**Comment by PatrickWatzlawik** [comment]
Should be done now. I could just install the rc.1 from npm directly

**Comment by christopherthielen** [comment]
Yes, I hadn't gotten around to publishing the release yet. I published it this morning. I will update the documentation site later today.

**Comment by jesperronn** [comment]
Awesome! Thanks!
