### ISSUE TITLE
Default <ui-view /> for abstract states without template?

### ISSUE THREAD

**Issue by vegardlarsen** [angular-ui/ui-router#325]
Would it make sense to implement a default template containing a single `<ui-view />` for abstract states? Consider the following setup:

``` js
$stateProvider
    .state("sub", { url: '/sub', abstract: true, template: '<ui-view />' })
    .state("sub.home", { url: '', templateUrl: 'subHome.html' })
    .state("sub.details", { url: '/:id', templateUrl: 'subDetails.html'})
```

It would allow you to drop the `template` on the abstract state, something which tripped me up for a while trying to create a hierarchy just like this.

**Comment by omeid** [comment]
Throwing an exception would be nice.

**Comment by keithl8041** [comment]
+1 for an exception when no templateUrl is specified, I just wasted 30 minutes on this error (which in hindsight is glaringly obvious, but I'd made a load of changes so it was difficult to pin down).

**Comment by preaction** [comment]
I, too, just spent an hour trying to figure out why my nested states weren't displaying anything. I'd prefer it to DWIM: If I don't specify a template, it means that layer doesn't have any content at the moment. But, barring that, an exception would be really helpful.

**Comment by dalgard** [comment]
In many a lot of contexts within programming, when something is "abstract", it means that its properties is simply inherited – like an abstract class.

I don't understand why there has to be a template in an abstract state at all. There are other interesting properties to inherit, such as `data` and `url`.

**Comment by noyg** [comment]
Another issue here is that when creating an abstract parent state just for grouping url parts and resolves, another $scope is created, thus turning $scope.$parent to $scope.$parent.$parent for meaningful parent access.

**Comment by mnewmedia** [comment]
It also feels a lot faster without the `<ui-view>` at least in ionic. Didn't test it but I anyway don't wanna have this crappy feeling.

Nothing feels really correct with inheritance, so i just do it like:
```js
onEnter: function(customerService, $stateParams) {
    customerService.init($stateParams.customerId);
}
```
Then all my cusotmer child controllers are accesssing the customerService, if they need something instead of inheritance.

Good enough for now and at least when changing to ng2, the problem is anyway gone.
