### ISSUE TITLE
Have anyone using $state.go('statename', {location: replace}) in android mobile(version < 5)?

### ISSUE THREAD

**Issue by louiszhu2zgf** [angular-ui/ui-router#3250]
Well, I am working on a project for mobile webapp. 
And I used **$state.go('statename', {location: replace})** in some pages. Everything runs good except the situation in android mobile(version < 5).
_Details:_
1. someone visit a page name  **A**
2. page **A** using $state.go('statename', {location: replace}) redirect to page **B**
3. click some links on page **B** can go to page **C**
4. but when user click back button to go to the previous page, in the machine (android mobile version < 5), it will go the page **A** instead of page **B**.

Any solution? @christopherthielen

**Comment by christopherthielen** [comment]
Does it work as expected in a Desktop browser like chrome?

**Comment by louiszhu2zgf** [comment]
@christopherthielen YES. IOS / desktop / android(high version) are all ok except the situation I mention above; Using the android(version < 5) webview can review the issue

**Comment by christopherthielen** [comment]
So is there an issue with replaceState on android?  Or is this an issue in Angular's location.replace()?  Either way, do you believe there's a bug in ui-router itself?

**Comment by louiszhu2zgf** [comment]
@christopherthielen absolute. Method location.replace() behaves bug, I also do a test in just using location.replace() to do the same thing in the same machine, and it happens.

As ui-router uses the location.replace() method when the options contain {location: replace} (for example: $state.go('statename', {location: replace}) ), and the bug happens. relative code:

push: function (urlMatcher, params, options) {
    $location.url(urlMatcher.format(params || {}));
    if (options && options.replace)
        **$location.replace();**
},

**Comment by christopherthielen** [comment]
Yes, ui-router uses `$location.replace()`, but how do you propose ui-router fixes it?  I think you need to file a bug with angular.js or android

**Comment by louiszhu2zgf** [comment]
@christopherthielen well, maybe I have to find a solution to work around.
Can't wait so long.
