### ISSUE TITLE
$state.go reload=true does not work second time. 

### ISSUE THREAD

**Issue by nsonic001** [angular-ui/ui-router#3252]
When we trigger $state.go($state.current, $stateParams, {reload:true}) for once, it's working fine;
but again triggering the same with changed stateParams don't reloads the view.
Can't understand what is wrong.

**Comment by christopherthielen** [comment]
It should reload.  Post a plunker that reproduces the issue and we can see if there's a bug.  Re-open after you've done so.

http://bit.ly/UIR-Plunk
