### ISSUE TITLE
Using external js file method

### ISSUE THREAD

**Issue by ShyamVashista** [angular-ui/ui-router#3258]
Hi I am using external.js having a method globalCheck(val, val1) in this method performing some jquery manipulation now want to use same method in my global-validate.component.ts or global-validate.service.ts file, can you suggest how to use that method 
external.js - 
```
(function () {
    'use strict';
    var ary = [];
    window.external = {  globalCheck: function(val, val1){ } };
})();
```

**Comment by eddiemonge** [comment]
umm did you maybe open this in wrong place?
