### ISSUE TITLE
Bind resolve sub resource to component shouldn't be possible ?

### ISSUE THREAD

**Issue by sebastienvermeille** [angular-ui/ui-router#3259]
Hello,
I use ui-router for a while now and we migrate to 1.0.X. with components (angular 1.5.8) 

BTW: thank you for this great library !

But there is a major problem for us. Until now, we had some promises like that in resolve (with a $q.all) :
`resolve: {

               pageInfo: function($q, $state, FirstService, STATES_ERRORS){
                        // some code
                        deferred.resolve({
                           'news': arrayOfResults[0].data,
                           'newsComments': arrayOfResults[1].data
                        });

                }
            },`

And now we a component I would like to give 2 inputs : 

<news-page-component news="pageInfo.news" news-comments="pageInfo.newsComments"

I cannot do 2 resolves because the second one depend on the first one for some reasons. That's why I suggest this feature :

Allow a special binding:

> news : 'pageInfo.news' 
> comments: 'pageInfos.comments'

Is that possible ? Or do you have another solution ? 

Thank you in advance

**Comment by christopherthielen** [comment]
It's not possible to bind nested properties to inputs.  It's an interesting request though, I'll keep it in mind for the future.

For now you can do 

```js
resolve: {
           pageInfo: function($q, $state, FirstService, STATES_ERRORS){
                    // some code
                    deferred.resolve({
                       'news': arrayOfResults[0].data,
                       'newsComments': arrayOfResults[1].data
                    });
            },
            news: function(pageInfo) { return pageInfo.news },
            newsComments: function(pageInfo) { return pageInfo.newsComments },
        },
```

happy routing!

**Comment by sebastienvermeille** [comment]
Great ! Thank you very much @christopherthielen ! I really appreciate your work on this project. I hope I could submit some PR in the future with more skill ^^

Have a nice day ;)
