### ISSUE TITLE
Migrating from DefinitelyTyped angular-ui-router to 1.0.0-rc.1 typings

### ISSUE THREAD

**Issue by httpete** [angular-ui/ui-router#3261]
Hi,

My project used 0.3.2 and the typings shipped via [@types/angular-ui-router ](https://www.npmjs.com/package/@types/angular-ui-router)

Now I am migrating to 1.0.0, and I had a collision right away with the old Typing. I annotated $stateProvider:  angular.ui.IStateProvider  all over my code. 

Has the signature of the typing changed completely? I want to use the typing you ship. I don't see the namespace exported as it was before.

If so, what is the proper way to configure tsconfig.json in order to use the typing within node_modules/angular-ui-router/lib? Most often we exclude the entire node_modules directory. This is the first time I am using a project that ships a typing through npm.

**Comment by christopherthielen** [comment]
If you are using typescript 2.0+ it should pick up the typings found in node_modules/angular-ui-router by default. 

The typings on DefinitelyTyped are maintained by a third party and so are not "official"

I'm not sure how excluding node_modules interacts with type defs

**Comment by christopherthielen** [comment]
To use types:

```js
Import { StateProvider } from "angular-ui-router";

$stateProvider: StateProvider;
```

**Comment by httpete** [comment]
Thank you Christopher, 

Before the types just magically appeared so if I did ( $stateProvider: angular.ui.IStateProvider ). I know this is not really an angular-ui-router issue, but why do I need to import the Type to leverage it?

**Comment by httpete** [comment]
I guess this is because they were "Ambient" declarations in the old typing. Is there a reason why they are not done this way in the new typing shipped with the project?

**Comment by christopherthielen** [comment]
> Is there a reason why they are not done this way in the new typing shipped with the project?

@httpete yes. the "old typings" were created and maintained by some third party (ui-router project is not involved in the typings on DefinitelyTyped)

Since ui-router 1.0 is written in typescript and uses ES6 modules, it's the natural way to publish the types as well.

**Comment by httpete** [comment]
Thank you Chris. For others in the same boat, I am simply ripping off all the old angular.ui.* references in my code in favor of the new one. 
I also had to make sure that my tsconfig.json file did exclude the entire node_modules directory because if it wasn't done, the typings would collide.

**Comment by squadwuschel** [comment]
Hi, my current Problem is, that I am using NG1 without npm just with NuGet and I have currently no chance to migrate to npm with all my older projects. But It would be cool if I there would be one big d.ts file with all Typings that I could load into my project with the ui-router-rc1

**Comment by pablorsk** [comment]
With typescript 2 and migration from `angular-ui-router` to `@uirouter/angularjs`, you need something like this:

```javascript
import { UrlService, StateProvider } from '@uirouter/angularjs';
import * as angular from 'angular';

/** @ngInject */
function routesConfig(
    $stateProvider: StateProvider,
    $urlServiceProvider: UrlService,
    $locationProvider: angular.ILocationProvider
) {
}
```
Also, remove
* `angular-ui-router` from `tsconfig.json` types.
* any `angular-ui-router` from `pacakge.json` (package and @types)

**Comment by dietergeerts** [comment]
When not using TS, how do we need to define types in jsdocs? It used to work, but not anymore.
