### ISSUE TITLE
transitions and on enter not provided?

### ISSUE THREAD

**Issue by surfjedi** [angular-ui/ui-router#3264]
I am trying to use the simple transitions hooks and onenter..

but it gives me the errors:
TransitionRejection(type: 6, message: The transition errored, detail: Error: [$injector:unpr] Unknown provider: transProvider <- trans

Error: [$injector:unpr] Unknown provider: transProvider <- trans

angular.js:14328 Possibly unhandled rejection: {"type":6,"message":"The transition errored","detail":{}}

I am using angular 1.6.1 ui-router 1.0.0-rc.1

`
function config  ($stateProvider, $urlRouterProvider, $locationProvider) {
  var helloState = {
    name: 'hello',
    url: '/hello',
    component: 'hello',
  };

  var aboutState = {
    name: 'about',
    url: '/about',
    template: '<h3>Its the UI-Router hello world app!</h3>'
  };
  var tableViewState = {
    name: 'tableview',
    url: '/table',
    component: 'tableView'
  };
  var protectedState = {
    name: 'protected',
    url: '/protected',
    template: `<h1>protected</h1>`,
    onEnter: function (trans, state) {
      console.log("Entering " + state.name);
    }
  };

  $stateProvider
    .state(helloState)
    .state(aboutState)
    .state(protectedState)
    .state(tableViewState);
  $urlRouterProvider.otherwise('/hello');
  // $transitions.onBefore( { to: 'requireauth.**' }, function(trans) {
  //   var myAuthService = trans.injector().get('MyAuthService');
  //   // If isAuthenticated returns false, the transition is cancelled.
  //   return myAuthService.isAuthenticated();
  // });
  // use the HTML5 History API
  $locationProvider.html5Mode(true);
}
config.$inject = ['$stateProvider', '$urlRouterProvider', '$locationProvider'];
export default config;
`

**Comment by surfjedi** [comment]
any ideas? I have tried injecting $transitions too but still same errors?

**Comment by httpete** [comment]
$transition$  (note the last $)

**Comment by surfjedi** [comment]
Sorted - realized since I was trying to do it in my config block it had to be $transitionProvider, as opposed to a controller or run block its $transitions.. And how does $transition$ vary from $transitions?

**Comment by christopherthielen** [comment]
[`$transition$`](https://ui-router.github.io/ng1/docs/latest/modules/injectables.html#_transition_)

[`$transitions`](https://ui-router.github.io/ng1/docs/latest/modules/injectables.html#_transitions)
