### ISSUE TITLE
ng2 uiSref ignores link `target="_blank"`

### ISSUE THREAD

**Issue by artaommahe** [angular-ui/ui-router#3266]
```html
<a target="_blank"
   [uiSref]="'someState">
</a>
```

Will open state in current tab instead of new one.

**Comment by Troy1b4** [comment]
I may be wrong about this but is the [uiSref] supposed to be [ui-sref] in stead of the previous?  Maybe that is you issue.  I am fairly new to ui-router but you may want to try that.

**Comment by artaommahe** [comment]
@Troy1b4 `[uiSref]` is Angular 2 directive

**Comment by Troy1b4** [comment]
Okay, thanks for the clarification.

**Comment by christopherthielen** [comment]
Moving to https://github.com/ui-router/ng2/issues/25
