### ISSUE TITLE
Scope inheritance from abstract state controller not binded to child state component

### ISSUE THREAD

**Issue by octasimo** [angular-ui/ui-router#3268]
First, I would like to thank you for the amazing work you've been doing on ui-router!

##### Bug description
A scope value defined in the controller of an abstract state it's not inherited/binded by child state components.

[This plunkr](https://plnkr.co/edit/Q6JOQu) demonstrates this issue. In the example link please observe that ```{{$ctrl.rootControllerMessage}}``` from ```hello.html``` doesn't have any value.

**Comment by christopherthielen** [comment]
Components use an isolated scope, so there shouldn't be any scope bleed from the parent.  (This is sort of the point of component based architecture).

If you want to abuse the scope inheritance, you can do so by using `$parent` (this isn't a ui-router thing, this is just normal ng 1.5 component comment).

See here: https://plnkr.co/edit/FaHRhx?p=preview

**Comment by octasimo** [comment]
Ok, definitely makes sense now! Thank you for the time you took to go through this!
