### ISSUE TITLE
Question: why promise from the first .then() method in the chain resolves a state, but second isn't?

### ISSUE THREAD

**Issue by mr-moon** [angular-ui/ui-router#3271]
From wiki:
```
promiseObj2:  function($http){
    return $http({method: 'GET', url: '/someUrl'})
        .then (function (data) {
            return doSomeStuffFirst(data);
        });
}   
```

Which works perfectly fine, unless you add second then to the chain:
```
promiseObj2:  function($http){
    return $http({method: 'GET', url: '/someUrl'})
        .then (function (data) {
            return doSomeStuffFirst(data);
        })
        .then(function(processedData) {
            return doSomeMoreWith(processedData);
        });
}
```

I checked, both `.then()` methods return promises. What I don't understand why then stop state from resolution?

I'm asking because my service does the processing, so my code looks more like:

```
// MyService#fetchData
myService.fetchData: function () {
    return $http({method: 'GET', url: '/someUrl'})
        .then (function (data) {
            return doSomeStuffFirst(data);
        })
}
...
promiseObj2:  function($http, myService){
    return myService.fetchData()
        .then(function(processedData) {
            return doSomeMoreWith(processedData);
        });
}
```

**Comment by christopherthielen** [comment]
Chained promises *should* cause the resolve to wait until all the chains have returned.

Here's an example:  http://plnkr.co/edit/dCE4mrMp5Owaeb8YUGKU?p=info

Are you seeing different behavior?  I suspect there's a bug in your promise handling code.

**Comment by mr-moon** [comment]
Hey. Thanks for an example, really appreciate that. Please take a look a this one: http://plnkr.co/edit/o7YdBppPWHkpOg1Ja7qa?p=preview It's closer to the real use case. It looks like it resolves the state, but doesn't update the view.

**Comment by mr-moon** [comment]
Ok, looks like I have to specify the views explicitly:
```
views: {
    '@': {
        ....
    }
}
```

Thank you.
