### ISSUE TITLE
uiCanExit and window close event

### ISSUE THREAD

**Issue by karensg** [angular-ui/ui-router#3272]
I have a suggestion to improve the `uiCanExit` functionality. It would be really nice if it also would catch the window close event because I believe that users will always need this functionality as well.

I think that this is additional code:
```
$window.onbeforeunload = function(e) {
  if ($scope.confirmOnExit()) {
    e.returnValue = $scope.confirmMessage;
    return $scope.confirmMessage;
  }
  return undefined;
};

$scope.$on('$destroy', function() {
  $window.onbeforeunload = null;
});
```

Do you see possibility to integrate it into the library?

**Comment by christopherthielen** [comment]
It's an interesting idea and it seems reasonable.  I'd like others to chime in about possible problems this could cause.

**Comment by N0NamedGuy** [comment]
I would like to have this feature available, in some way.

The only immediate problem I see with this is the use of "beautiful" modals, since the native confirmation box has to appear, and showing them twice would suck...

**Comment by christopherthielen** [comment]
@N0NamedGuy that's a good point.  Does anyone have an idea for how this should ideally work?

**Comment by N0NamedGuy** [comment]
@christopherthielen If somehow a flag, or an "indicator" is made available on the state definition, say:
```
.state('my.state', {
 url: '/state',
 // message to display on the confirm dialog on supported browsers
 uiCanExitMessage: 'You are leaving MyApp. Are you sure?',
 component: 'myComponent
});
```
This way, you can defined the dialog message, whenever the window is closed, and use it (by default) to display a window.alert() with the message (so if we have to use "ugly" modals, let's keep it consistent).

I am still not entirely sure on how to handle promises with the uiCanExit hook. But here's an idea on how to integrate the onbeforeunload event.

Cheers.

**Comment by christopherthielen** [comment]
@N0NamedGuy 

The uiCanExit hook is a component level (view) hook, which only takes effect if the view is currently activated.  

Defining the unload behavior on the state object is certainly possible (like your proposed  `uiCanExitMessage`) and is IMO a very reasonable approach, but it's a rather *different* approach.

---

The onbeforeunload event and a transition hook are implemented in completely different ways.  Makes me think the onbeforeunload implementation should not really be tied to the existing `uiCanExit` hook.

**Comment by christopherthielen** [comment]
Here's a simple implementation of onbeforeunload that checks for metadata on the state:

```js
app.run($uiRouterGlobals => {
  window.addEventListener("beforeunload", function (e) {
    let hasBeforeUnload =  $uiRouterGlobals.current && 
        $uiRouterGlobals.current.data && 
        $uiRouterGlobals.current.data.onbeforeunload;
        
    if (hasBeforeUnload) {
      return e.returnValue = true;
    }
  });
});
```

Then you can simply add metadata on a state (or state tree, using inherited `data` property) that will cause the user to be warned:

```js
  $stateProvider.state({ 
    name: 'home', 
    url: '/home', 
    component: 'home',
    resolve: { homeData: () => 'home data' },
    data: {
      onbeforeunload: true
    }
  });
```
http://plnkr.co/edit/ffLMzSKZutmj6b4Xd0iY?p=preview
