### ISSUE TITLE
Slow Karma unit tests?

### ISSUE THREAD

**Issue by jziggas** [angular-ui/ui-router#3274]
I'm wondering if anyone else has noticed something like this? We migrated our app recently from 0.2.x to ^1.0.0-rc.1 and have noticed that our unit tests are running super slow now.  Our ~350 tests that took about 7 seconds to run before now takes 70 seconds and receives 'Slow' warnings from PhantomJS.

Going to see if upgrading PhantomJS from 2.1.1 helps.

PhantomJS 2.1.1
Karma 1.2
Jasmine 2.4.1

**Comment by justinbwarner** [comment]
Yes, I am seeing something similar. It appears to be related to how many states are in your app. Mine has ~50 states, the tests used to take about 3 seconds, now it takes more than 30. I noticed it because it exceeds the default timeouts for karma. If I comment-out a large number of the states then the tests run quickly.

**Comment by towu** [comment]
Maybe related to https://github.com/ui-router/core/issues/27 (Performance of new Order URL Matching Rules by priority, not registration order)

**Comment by aj-dev** [comment]
Also noticed the same. Unit tests take 10x longer to run after migration from v0.3.2 to v1.0.0-rc.1. 

Has something to do with state transitions. If I remove state definitions from the tests suite, it's back to normal.

**Comment by christopherthielen** [comment]
I've noticed this as well. When I have time I will do some profiling to see where the most time is spent.

I would appreciate it somebody would profile it first and find the hot spots.

**Comment by justinbwarner** [comment]
Based on my limited profiling, it looks like one of the hot spots is in UrlRouter.prototype.sort (line 3736). This method seems to take 10 to 20 milliseconds for each state is created, so if you have a lot of states, loading them can take more than a second to process.

**Comment by christopherthielen** [comment]
Great, thanks. That's low hanging fruit. I'll optimize that in next ui-router-core

**Comment by timothyswt** [comment]
I think the easiest way to do this is to not invoke the sort fn until the $get is called for the $stateProvider
That way it gets called one time after all are registered up front. then on the Serivce instance side of the API call it when further states get registered (if needed)

**Comment by timothyswt** [comment]
for now, what I did was what it says in the CHANGELOG.md

```javacsript
    //TODO: remove once the .sort is optimized in ui-router > 1.0.0-rc.1
    $urlServiceProvider.rules.sort(function(a, b) {
      return a.$id - b.$id;
    });
```

**Comment by jziggas** [comment]
😄

**Comment by christopherthielen** [comment]
please report back whether or not these optimizations sped up your unit tests

**Comment by jziggas** [comment]
Not 100% sure if related but I just upgraded to `"@uirouter/angularjs": "^1.0.5"` recently and unit tests are crawling again. Roughly 2 minutes for ~400 tests.

**Comment by thwefl** [comment]
I have the same problem with v1.0.13 :/ Does anyone know a solution?
