### ISSUE TITLE
cfg.getTemplate is undefined when using angular global

### ISSUE THREAD

**Issue by milo-** [angular-ui/ui-router#3275]
Looks like the angular global isn't being used on this line https://github.com/angular-ui/angular-ui-router-bower/blob/1.0.0-rc.1/release/angular-ui-router.js#L8742

This results in cfg.getTemplate being undefined when using the angular (bower installed) global. 

The break was introduced in: https://github.com/angular-ui/ui-router/commit/af95206035f83517798c33719a81bed32440b294#diff-a9f6de4806aaa114899aac7111e5235fR360

This is related to https://github.com/angular-ui/ui-router/commit/298261382f4ad0134c070caefcce859e2b693891

**Comment by christopherthielen** [comment]
Thanks for the report

**Comment by hoeni** [comment]
https://github.com/angular-ui/ui-router/pull/3410/files fixes the error in my case.

**Comment by noway** [comment]
This is pretty annoying as because it renders angular-ui-extras impossible to use with the latest (1.0) ui-router. 

And angular-ui-extras provides pretty essential features like future states...

Would be nice to get that fixed. angular-ui-extras+1.0 ui-router will be a very powerful combination (having components routing and dynamic module loading is huge).

**Comment by senthanal** [comment]
👍 
I do get the same annoying error. I can't proceed to deploy my application. Am waiting for this fix. Is there a plan to merge this pull request anytime soon? Pls. Thanks :)

**Comment by noway** [comment]
Because of this, it is impossible to route dynamically loaded components with AngularJS. IMHO this is pretty high priority.

**Comment by christopherthielen** [comment]
I'd like to fix this. The linked PR is a band aid and doesn't address the root issue (with angular global).  Can anyone post a link to a reproduction of this error?
