### ISSUE TITLE
Is this possible to call child state directly from html without any click operation? 

### ISSUE THREAD

**Issue by udayky372** [angular-ui/ui-router#3278]
In  my application I have parent and many child states. In order to trigger parent view I used ui-view in main page and it's working fine, at the same time I want to load child state without any click operation on html (parent state). because my child view is a summary page so there is no need of user to click child state to see summary, it should load by default. 

How can I trigger child view directly from html?

**Comment by christopherthielen** [comment]
I think you want  to [use `redirectTo`](https://ui-router.github.io/ng1/docs/latest/interfaces/ng1.ng1statedeclaration.html#redirectto) in the parent state to redirect to the default child state.

```js
.state('parent', {
  redirectTo: 'parent.defaultchild',
})
.state('parent.defaultchild', {
})
```

Just to be clear, this is a feature of 1.0 branch, so you should be on `1.0.0-rc.1`
