### ISSUE TITLE
Why $transition$?

### ISSUE THREAD

**Issue by adamreisnz** [angular-ui/ui-router#3281]
Sorry, I tried to ignore it, but I just have to ask... ;)

Why the trailing `$` in `$transition$`?
I get there is already the transition service which is called `$transition`, but why not simply call the transition instance `transition` or if you must use a dollar sign, the more common `$$transition`? Or reserve `$transition` for the transition and call the service `$transitionService`?

Having the `$` at the end is really weird. It stands out because it isn't used anywhere else, not in Angular nor in ui-router I believe, and every time I see it, it reads to me as $transition_s_. It just keeps tripping me up.

Would you be able and willing to create an alias for the service with a different name, or simply rename it since 1.0.0 hasn't been released yet? I can't be the only one thinking it's an odd name and that it reads funny?

**Comment by nateabele** [comment]
Standing out was precisely the point, so clearly it seems to have worked. 😄 This and a number of other injectables are contextual, rather than global.

Because we had so much trouble with people being confused by `$stateParams` having different values in different contexts, we decided to create a convention.

Because the `$$` convention was already used by Angular for 'private' APIs, we decided to go with this. Sorry if it bothers you.

**Comment by adamreisnz** [comment]
It did yes ;)
Well I suppose it's a matter of getting used to, thanks for providing the reasoning behind the choice.

Angular uses `$$` for private vars yes, but Angular also recommends not to prefix any services with `$` as that is reserved for Angular's use and might in the future conflict with Angular's own services.

I have also blatantly disregarded that recommendation for my own services because, well, it's nice to have some consistency right? But seeing how you've also decided to use `$` prefix against Angular's recommendation, you might as well disregard the other convention and use `$$` instead for contextual injectables, no? :)

**Comment by nateabele** [comment]
> Angular uses $$ for private vars yes, but Angular also recommends not to prefix any services with $ as that is reserved for Angular's use and might in the future conflict with Angular's own services.

Projects in this org have used it broadly because it's always been semi-official. 😄

**Comment by adamreisnz** [comment]
Yes, fair point

**Comment by christopherthielen** [comment]
@adamreisnz 

You can create an alias for your own apps:
```js
app.run(function ($transitions) {
  $transitions.onBefore({}, trans =>
    trans.addResolvable({ token: 'trans', resolveFn: () => trans });
});
```

**Comment by adamreisnz** [comment]
Excellent thanks!

**Comment by christopherthielen** [comment]
You may be interested in [how we create these built-in tokens](https://github.com/ui-router/core/blob/7f078c4db78166845a302ea54cb7d1c7af0ac712/src/hooks/coreResolvables.ts#L6-L18) ourselves:

```js
function addCoreResolvables(trans: Transition) {
  trans.addResolvable({ token: UIRouter,       deps: [], resolveFn: () => trans.router,   data: trans.router },   "");
  trans.addResolvable({ token: Transition,     deps: [], resolveFn: () => trans,          data: trans },          "");
  trans.addResolvable({ token: '$transition$', deps: [], resolveFn: () => trans,          data: trans },          "");
  trans.addResolvable({ token: '$stateParams', deps: [], resolveFn: () => trans.params(), data: trans.params() }, "");

  trans.entering().forEach(state => {
    trans.addResolvable({ token: '$state$',    deps: [], resolveFn: () => state,          data: state },       state);
  });
}

export const registerAddCoreResolvables= (transitionService: TransitionService) =>
    transitionService.onCreate({}, addCoreResolvables);
```

**Comment by adamreisnz** [comment]
That's neat, thanks for sharing
