### ISSUE TITLE
Transition hook criteria `from` not respecting empty string

### ISSUE THREAD

**Issue by adamreisnz** [angular-ui/ui-router#3285]
I want to trigger a transition hook which only fires if the user enters a specific state *without having a from state*, e.g. they land on the page by typing in the URL or following a direct link.

I assumed this would be accomplished via:

```js
$transitionsProvider.onBefore({
    from: '',
    to: 'welcome.*',
  }, transition => { ... });
```

However, that seems to capture any transition to any `welcome.*` route, as I suspect the empty `from` value is being ignored.

Is there another way to have hook criteria match only when there isn't any `from` state?
If not, can it be implemented so that an empty string (as opposed to `undefined` / `null`) triggers this check?

The [docs](https://ui-router.github.io/ng1/docs/latest/interfaces/transition.hookmatchcriteria.html) don't document this use case either.

**Comment by christopherthielen** [comment]
This issue was moved to ui-router/core#32
