### ISSUE TITLE
TypeError: g.get is not a function

### ISSUE THREAD

**Issue by psaunders** [angular-ui/ui-router#3287]
I've been finding this error caused by the ui-sref directive when minimizing the already minified code using uglify. Just thought I would leave this here in case anyone else spends a few hours on this.

**Comment by christopherthielen** [comment]
What version

**Comment by nikshik** [comment]
have same error with bundle from bower. ui-sref or ui-sref-active directive

**Comment by WebMex** [comment]
Have the same problem. Minification of non-minified file works fine.
"angular": "~1.6.1",
"angular-ui-router": "1.0.0-rc.1"

"gulp-uglify": "1.5.1"

**Comment by christopherthielen** [comment]
I minified the pre-minified code and cannot reproduce the problem.

```
bower install angular-ui-router#1.0.0-rc.1
cd bower_components/angular-ui-router/release
uglifyjs angular-ui-router.min.js --mangle --compress > double-minified.min.js
```

https://plnkr.co/edit/finjvA?p=info

Please post detailed instructions on how to reproduce.

**Comment by nikshik** [comment]
this seems relates to uglifier
tried gulp-uglify 1.5.1 => reproducible
tried gulp-uglify 2.1.0 => non-reproducible

**Comment by christopherthielen** [comment]
@nikshik thank you for testing and reporting back.  I think this can be closed then!  🎉
