### ISSUE TITLE
Query params containing slashes encode to ~2F rather than %2F

### ISSUE THREAD

**Issue by tstriker** [angular-ui/ui-router#3288]
While #2598 talks about slashes in path params, looks like the tildiness also extends to query params. That makes it impossible to pass the proper value to server using ui-router.

So for a state "/some_path?tag&author" values containing slashes in params will convert them to ~2F which isn't exactly what one would expect.

**Comment by christopherthielen** [comment]
What version of ui-router?  Check the [release notes for 1.0.0-rc.1](https://github.com/angular-ui/ui-router/releases/tag/1.0.0-rc.1): 

> Query parameters no longer encode slashes as ~2F

**Comment by tstriker** [comment]
oh sorry, didn't feel like putting something that has alpha or rc in their version tag in prod :)
good to know this is fixed, will keep an eye open for the 1.0 final!
