### ISSUE TITLE
How to register services/factories in lazy loading modules?

### ISSUE THREAD

**Issue by weareoutman** [angular-ui/ui-router#3290]
Hi, I am trying the lazy loading states of ui-router. But I don't know how to register services/factories during lazy loading runtime.
For example: `angular.module('app').factory('myService', ...)`. It doesn't work.
Can anyone help me? Thanks.

**Comment by christopherthielen** [comment]
You need to use a [tool like `$ocLazyLoad`](https://oclazyload.readme.io/) to lazy load angular modules.

```js
angular.module('myLazyModule', []).factory('myService', ...)
```

Then you call 
```js
$ocLazyLoad('./path/to/myLazyModule.js');
```

If you're using a module loader (systemjs) you can chain off the promise like this:
```js
function loadit() {
  return System.import('./path/to/myLazyModule').then(result => $ocLazyLoad(result));
}
```
