### ISSUE TITLE
Sequential transition errors in minified version 0.4.2

### ISSUE THREAD

**Issue by DiamondeX** [angular-ui/ui-router#3291]
I'm getting sequential transition errors: "transition superseded", then "transition prevented", then "transition aborted" and finally "transition failed" only in minified version 0.4.2
Looks like the order of errors follows the order of definition of this errors in minified code:
```
var A = e.reject(new Error("transition superseded"))
              , C = e.reject(new Error("transition prevented"))
              , D = e.reject(new Error("transition aborted"))
              , E = e.reject(new Error("transition failed"));
```
The same code in uncompressed code looks like this:
```
    var TransitionSupersededError = new Error('transition superseded');

    var TransitionSuperseded = silenceUncaughtInPromise($q.reject(TransitionSupersededError));
    var TransitionPrevented = silenceUncaughtInPromise($q.reject(new Error('transition prevented')));
    var TransitionAborted = silenceUncaughtInPromise($q.reject(new Error('transition aborted')));
    var TransitionFailed = silenceUncaughtInPromise($q.reject(new Error('transition failed')));
```
I think that wrapping to `silenceUncaughtInPromise()` somehow disappeared in minified variant

**Comment by DiamondeX** [comment]
By the way, I'd decided to minify uncompressed version myself with uglify.js. I've got resulting file free of the above errors

**Comment by christopherthielen** [comment]
WEIRD!  I'll take a look 👍

**Comment by christopherthielen** [comment]
@DiamondeX Where did you get your bundles from?

Npm?  unpkg.com? bower?

**Comment by christopherthielen** [comment]
Pulling 0.4.2 from npm (unpkg.com) and beautifying, I get:

```js
      var w = new Error("transition superseded"), 
          B = p(e.reject(w)), 
          D = p(e.reject(new Error("transition prevented"))), 
          E = p(e.reject(new Error("transition aborted"))), 
          F = p(e.reject(new Error("transition failed")));
 ```

**Comment by christopherthielen** [comment]
[Same with bower](https://raw.githubusercontent.com/angular-ui/angular-ui-router-bower/0.4.2/release/angular-ui-router.min.js):

```js
 w=new Error("transition superseded"),B=p(e.reject(w)),D=p(e.reject(new Error("transition prevented"))),E=p(e.reject(new Error("transition aborted"))),F=p(e.reject(new Error("transition failed")));
```

**Comment by christopherthielen** [comment]
Closing because I don't think this was a botched release.  All the usual places seem OK.

If you can show where you got the botched .min.js files we can reopen this if necessary
