### ISSUE TITLE
Clearing hash in url without loosing history

### ISSUE THREAD

**Issue by cakeinpanic** [angular-ui/ui-router#3294]
Hello!
I have some file grid and want to have additional ability to scroll to selected item using link of format
`/folderId#fileId`

But as soon as i have scrolled to it, i need to remove id from url.
If i do it using `$location.hash('')`, i loose previous history (and get a lot of [strange ignored transitions](https://www.dropbox.com/s/70xarz39yww0iky/Screenshot%202017-01-25%2013.30.34.png?dl=0) in my log).

If i use honest `$state.go` without `#` param, all files if grid are reloaded and i obviously don't want to do it

Is there any way to do it legally using ui-router api?

**Comment by christopherthielen** [comment]
http://plnkr.co/edit/sEy1VxklggL68SeEN6Cs?p=preview

```
  $state.go($state.current, { '#': hash })
      .then(() => $timeout(500))
      .then(() => $state.go($state.current, { '#': '_' }));
```

http://stackoverflow.com/questions/2295845/how-can-i-remove-the-location-hash-without-causing-the-page-to-scroll

Setting the hash can be finicky.
