### ISSUE TITLE
'UrlRouterProvider' missing from typings in RC1

### ISSUE THREAD

**Issue by theatrain** [angular-ui/ui-router#3296]
I am getting the following typescript compilation error

Module '"/%path%/node_modules/angular-ui-router/lib/index"' has no exported member 'UrlRouterProvider'.

This is my imports to get it working:

```
import {StateProvider} from 'angular-ui-router';
import {UrlRouterProvider} from "../../../../node_modules/angular-ui-router/lib/urlRouterProvider";
```

I think `export * from "./urlRouterProvider";` is missing from index.d.ts?

**Comment by christopherthielen** [comment]
Will fix for rc.2, but recommend you migrate to `$urlService` and/or `$urlServiceProvider`.

https://github.com/angular-ui/ui-router/releases/tag/1.0.0-rc.1

https://ui-router.github.io/ng1/docs/latest/modules/injectables.html#_urlserviceprovider
