### ISSUE TITLE
Parent view/component reloaded when going to child state

### ISSUE THREAD

**Issue by cadilhac** [angular-ui/ui-router#3297]
Hi,

Using 1.0rc1.
I can't understand the following situation. game is the child state of the map state. map shows a side panel with a list of entities related to markers on a map. When I click on one entry of the list I go to the child state to display data related to the clicked entity (this is made with a ui-sref). In this child state, I still want to display the entities list in the panel. What is strange is that when going to the child state, the exploremap component (the one that handles the list in the side panel) is reloaded (I see it visually because of an animation for the view, and also because of a console.log in its controller). If I go back to map, then again to the same entity in the list, this time it's not reloaded. If I go back to map and then select another entity (i.e. a different id), the panel is reloaded. Why and how can I prevent the parent to be reloaded?

Thanks

```
        var mapState = {
            name: 'map',
            parent: 'explore',
            url: '',
            views: {
                'panel-content@platform': {
                    component: 'exploremap'
                }
            },
            data: { showPanel: true }
        }

        var gameState = {
            name: 'game',
            parent: 'map',
            url: '/game/:id',
            resolve: {
                // Some resolve here
            },
            views: {
                'wood@platform': {
                    component: 'game'
                }
            },
            data: { showWood: true, showPanel: true }
        };

```

**Comment by cadilhac** [comment]
Solved, but not sure why. I had a params: { game: null } in an ancestor state and game is also one of the resolves in gameState. If I remove the params section in the ancestor, it works fine.

**Comment by christopherthielen** [comment]
> I had a params: { game: null } in an ancestor state and game is also one of the resolves in gameState. If I remove the params section in the ancestor, it works fine. If I move it to gameState it also works

That's strange, I can't explain that.  Did your ui-sref modify the `game` parameter value?  ui-sref by default uses `inherit: true` so all the current parameters which aren't updated are used when activating the linked state.

I guess you figured it out, so closing.  If you want to post a way to reproduce the original issue, I can always look at it later.
