### ISSUE TITLE
Broken image link in documation

### ISSUE THREAD

**Issue by fcostarodrigo** [angular-ui/ui-router#3298]
There used to be a nice diagram at https://ui-router.github.io/ng1/docs/0.3.1/index.html#/api/ui.router.state.$state but now the link to the image https://ui-router.github.io/ng1/docs/ngdoc_assets/StateGoExamples.png is broken.

**Comment by christopherthielen** [comment]
Fixed by https://github.com/ui-router/ui-router.github.io/commit/58f3b701c677a25529e39b8a1ec3c823298558e8
