### ISSUE TITLE
Unable to inject templateProvider with resolved values 

### ISSUE THREAD

**Issue by sqs** [angular-ui/ui-router#330]
A view's `templateProvider` is unable to be injected with resolved values. The following will fail with an error like `Error: [$injector:unpr] Unknown provider: barProvider <- bar`.

```javascript
$stateProvider.state('foo', {
  resolve: {bar: function() { return 123; }},
  views: {
    foo: {
      templateProvider: function(bar) { /* ... */ },
    }
  },
})
```

I see in `resolveState` that `$view.load` only gets some locals to inject. Is there any technical reason why `templateProvider` couldn't be injected with all of the resolve values in the same way that `controller` is?

(This is on git master, and I remember seeing the same limitation a couple of months ago.)

**Comment by hrajchert** [comment]
This issue still persists. I have a route that defines a resource that can be of 3 different types, I don't know the type until I resolve getting data from the db and then I can select which is the correct view and controller.

Is this planned for fixing?

**Comment by manar007** [comment]
Guys please fix that, its very important part

**Comment by NecoleYu** [comment]
+1

**Comment by BogdanDamianC** [comment]
+1

**Comment by nateabele** [comment]
I'l fix it when I have time. In the meantime, you're welcome to submit a PR.

**Comment by webgago** [comment]
Hey guys,
Have a look at ^^^ please.
Maybe I've missed something, but seems it works

**Comment by lalunamel** [comment]
+ 1

**Comment by mkoryak** [comment]
this would be great if this was fixed. this bug has been around for at least a year now and it makes it much harder to do what should be a simple thing.

**Comment by nateabele** [comment]
@mkoryak Does the patch in #1934 (which went out in the 0.2.15 release) not work for you?

**Comment by mkoryak** [comment]
are you suggesting that I stop using `onEnter` and use `templateProvider` instead as a workaround for this issue?

**Comment by CosmoScriv** [comment]
Works like a charm thanks for improving on this.  #1934
