### ISSUE TITLE
$state.is() is not working as expected from v0.4.0

### ISSUE THREAD

**Issue by Pmyl** [angular-ui/ui-router#3300]
$state.is() when provided with the correct state and the _params_ parameter it will wrongly return **true** as long as the last _param_ matches even if the others are different.

This test should work but it fails:
```
it('should return false when the current state is passed with non matching parameters', inject(function ($state, $q) {
  $state.transitionTo(D, {x: 'foo', y: 'qux'});
  $q.flush();

  expect($state.is(D, {x: 'bar', y: 'qux'})).toBe(false);
}));
```

**Comment by christopherthielen** [comment]
Thanks for the broken test!
I'll take a look and release 0.4.3 when it's fixed.

**Comment by seavor** [comment]
Any update on when this will get patched?

**Comment by pearcemerritt** [comment]
My team also ran into this issue, so I created a PR: https://github.com/angular-ui/ui-router/pull/3530

**Comment by pearcemerritt** [comment]
@christopherthielen
