### ISSUE TITLE
how to stop TransitionRejection errors in console

### ISSUE THREAD

**Issue by 29er** [angular-ui/ui-router#3302]
I purposely stop transitions in my app but don't want to see the TransitionRejection in the console.
How can I take this out ?
Thanks!

**Comment by avilao** [comment]
+1

**Comment by christopherthielen** [comment]
you can indeed replace the entire `defaultErrorHandler`, but I think we should change the default error handler's built-in behavior for "cancelled transition" not to log.

**Comment by christopherthielen** [comment]
Closing in favor of https://github.com/ui-router/core/issues/35

**Comment by ranst91** [comment]
I cannot see how this is closed. As this issue is not resolved for Angularjs
