### ISSUE TITLE
Angular JS URL encoding issue

### ISSUE THREAD

**Issue by amrfayad** [angular-ui/ui-router#3304]
I am working on an AngularJS app and some pages the url contain arabic characters.

when I use $locatoin.url('/ar/brand/علوم-الحاسب') it works great. Now the url is :

/ar/brand/علوم-الحاسب

But when I refresh the page via browser reload button the url encoded and become /ar/brand/%25D8%25B9%25D9%2584%25D9%2588%25D9%2585-%25D8%25A7%25D9%2584%25D8%25AD%25D8%25A7%25D8%25B3%25D8%25A8

my questions:

1- Is this browser related issue, server related issue or Angular JS related issue?

2- How can I disable url encoding?

Note: I am using ngRoute module for routing.

Note: I am using Laravel framework as back-end API and the bootstrapping of Angular app is starting from index.blade.php file

Thanks in advance!

**Comment by christopherthielen** [comment]
this project is ui-router, not ngRoute.
