### ISSUE TITLE
Redirecting with $urlRouterProvider occurs error when target state is Future

### ISSUE THREAD

**Issue by cheerun** [angular-ui/ui-router#3305]
Hello. Let's see Example.

```javascript
// route.js
export const ModuleLazyLoader = modulePath => transition => transition.injector().get('$ocLazyLoad').load(modulePath)

export default function routesConfig($urlRouterProvider, $stateProvider) {
  $urlRouterProvider.otherwise('/')
...
  $stateProvider.state({
      name: 'event.**',
      url: '/event',
      lazyLoad: ModuleLazyLoader('./event.module.js'),
    })
...
}
```

When I go to `/invalid`, just invalid URL, I will redirect to '/' rightly.

Otherwise, When I enter `/event/invalid`, future state's invalid child, redirect to '/' likewise but next Error occured together: `stateService.js:39 TransitionRejection(type: 2, message: The transition has been superseded by a different transition, detail: Transition#1( ''{} -> 'home'{} ))`
(home is '/')

I think there are some collision between $urlRouterProvider and UI-router.
My ui-router's version is 1.0.0-rc.1.

Please check this issue. Thank you.

**Comment by cheerun** [comment]
@christopherthielen Please look at this issue.

**Comment by cheerun** [comment]
@christopherthielen hello~?

**Comment by christopherthielen** [comment]
@cheerun Can you reproduce the issue?

http://plnkr.co/edit/SxLQHpWzVw0Nfov7mZIe?p=preview

**Comment by cheerun** [comment]
I cannot reproduce yet about this issue on plunker, but I can give to you 2 more information.

## 1
I added app.run($trace => $trace.enable(1)), and went to '/event/invalid' directly via browser url bar.
Then, I could see logs about this issue.
```text
Transition #0 r1: Started  -> "Transition#0( ''{} -> 'event.**'{"remainder":"/invalid"} )"
angular-ui-router.min.js:7
Transition #1 r1: Started  -> "Transition#1( ''{} -> 'home'{} )"
angular-ui-router.min.js:7
Transition #1 r1: <- Success  "Transition#1( ''{} -> 'home'{} )", final state: home
angular-ui-router.min.js:7
Transition #0 r1: <- Rejected "Transition#0( ''{} -> 'event.**'{"remainder":"/invalid"} )", reason: TransitionRejection(type: 2, message: The transition has been superseded by a different transition, detail: Transition#1( ''{} -> 'home'{} ))
angular-ui-router.min.js:9
TransitionRejection(type: 2, message: The transition has been superseded by a different transition, detail: Transition#1( ''{} -> 'home'{} ))
```

## 2
http://plnkr.co/edit/OsBv3s?p=preview

On above plunker, click 'event/invalid/' directly.
Then you can see error although it's different from this issue.


Thank you for your response!
