### ISSUE TITLE
Idea: allow transition to abstract state when they have a redirectTo property

### ISSUE THREAD

**Issue by cyrilchapon** [angular-ui/ui-router#3306]

**Comment by christopherthielen** [comment]
I don't have a problem with this conceptually.  As long as it doesn't cause .  I think `abstract` states overall are confusing to a lot of users.  The term `abstract` makes people assume all sorts of incorrect things about what abstract states do.

**Comment by cyrilchapon** [comment]
Yeah. I personaly usualy use this feature for "parent" states that doesn't need to have a dedicated view. I think this is a real use case.

Eg: /admin beeing an abstract (i don't want an admin menu page on it's own), and /admin/users or /admin/stuffs actual routes. Though, I sometimes want to resirect to /admin/stuffs by defaut when I click on /admin
