### ISSUE TITLE
State param not passed by reference when using ui-sref?

### ISSUE THREAD

**Issue by cadilhac** [angular-ui/ui-router#3310]
Hi,

I am used, when using angular 1.5 components, to be able to modify a property of a one-way binding in a child component and get the value also modified in the parent since the binding is passed by reference. So I was expecting the same when passing an object as the param of a target state.

`<a ng-repeat="game in $ctrl.games" ui-sref="myState({ game: game})">Go</a>`

Unfortunately, when I modify a property of game in the controller of MyState, it doesn't change it in parts of the page that also reference the game object. Is it possible that the object is cloned when passed as a param?

Thanks

**Comment by vladimiry** [comment]
I'm using `1.0.0-rc.1` version and I pass promise instance as a parameter. I take this parameter, but no promise resolving happens. The probably reason that specified parameter are not passed by the reference.

````

**Comment by christopherthielen** [comment]
Thanks for the report. 
I believe this will be fixed by https://github.com/angular-ui/ui-router/pull/3330
