### ISSUE TITLE
Param values not valid for state (1.0.0-rc.1)

### ISSUE THREAD

**Issue by rupi42** [angular-ui/ui-router#3311]
I'am beginner 
and i edited
https://github.com/couchbaselabs/pouchdb-angularjs-app to an component method app.

With 
        `<script src="//npmcdn.com/angular-ui-router@1.0.0-rc.1/release/angular-ui-router.js"></script>`
i recognized the error message below,  with
      `<!-- <script src="js/angular-ui-router.js"></script>-->` the script runs (version 0.4.2), but I can't use the component method. Is it a bug,  or is the development still open?

> stateService.ts:538 Error: Param values not valid for state 'item'(…)$defaultErrorHandler @ stateService.ts:538(anonymous function) @ stateService.ts:374(anonymous function) @ angular.min.js:133$eval @ angular.min.js:147$digest @ angular.min.js:144$apply @ angular.min.js:148(anonymous function) @ angular.min.js:161f @ angular.min.js:47(anonymous function) @ angular.min.js:50
> stateService.ts:539 Error: Param values not valid for state 'item'
>     at Transition.run (transition.ts:648)
>     at StateService.transitionTo (stateService.ts:380)
>     at StateService.go (stateService.ts:272)
>     at stateDirectives.ts:75
>     at angular.min.js:160
>     at f (angular.min.js:47)
>     at angular.min.js:50$defaultErrorHandler @ stateService.ts:539(anonymous function) @ stateService.ts:374(anonymous function) @ angular.min.js:133$eval @ angular.min.js:147$digest @ angular.min.js:144$apply @ angular.min.js:148(anonymous function) @ angular.min.js:161f @ angular.min.js:47(anonymous function) @ angular.min.js:50
> stateService.ts:538 Error: Param values not valid for state 'item'(…)$defaultErrorHandler @ stateService.ts:538(anonymous function) @ stateService.ts:374(anonymous function) @ angular.min.js:133$eval @ angular.min.js:147$digest @ angular.min.js:144$apply @ angular.min.js:148(anonymous function) @ angular.min.js:161f @ angular.min.js:47(anonymous function) @ angular.min.js:50
> stateService.ts:539 Error: Param values not valid for state 'item'
>     at Transition.run (transition.ts:648)
>     at StateService.transitionTo (stateService.ts:380)
>     at StateService.go (stateService.ts:272)
>     at stateDirectives.ts:75
>     at angular.min.js:160
>     at f (angular.min.js:47)
>     at angular.min.js:50$defaultErrorHandler @ stateService.ts:539(anonymous function) @ stateService.ts:374(anonymous function) @ angular.min.js:133$eval @ angular.min.js:147$digest @ angular.min.js:144$apply @ angular.min.js:148(anonymous function) @ angular.min.js:161f @ angular.min.js:47(anonymous function) @ angular.min.js:50
> stateService.ts:538 Error: Param values not valid for state 'item'(…)$defaultErrorHandler @ stateService.ts:538(anonymous function) @ stateService.ts:374(anonymous function) @ angular.min.js:133$eval @ angular.min.js:147$digest @ angular.min.js:144$apply @ angular.min.js:148(anonymous function) @ angular.min.js:161f @ angular.min.js:47(anonymous function) @ angular.min.js:50
> stateService.ts:539 Error: Param values not valid for state 'item'
>     at Transition.run (transition.ts:648)
>     at StateService.transitionTo (stateService.ts:380)
>     at StateService.go (stateService.ts:272)
>     at stateDirectives.ts:75
>     at angular.min.js:160
>     at f (angular.min.js:47)
>     at angular.min.js:50

**Comment by karensg** [comment]
The error message means that you did not supply the correct parameters for the state you want to go to. Print out the parameters you are passing, maybe some of them is undefined.

**Comment by rupi42** [comment]
Thank you for your reply. After I have changed the ui-route version it runs. I can't say why, but the my script only runs with the older versions. 

My state definition looks like :
```
        .state("item", {
            "url": "/item/:documentId/:documentRevision",
            "templateUrl": "templates/item.html",
            "controller": "MainController"
        });
```

**Comment by christopherthielen** [comment]
The error is due to `documentId` and `documentRevision` being undefined.  You can provide default values, if you want:

```js
   .state("item", {
            "url": "/item/:documentId/:documentRevision",
            "templateUrl": "templates/item.html",
            "controller": "MainController",
            params: { documentId: null, documentRevision: null },
        });
```

Hope this is helpful.

**Comment by smitalm** [comment]
I would definitely appreciate, if there was an option to globally configure default value for url params to keep backward compatibility. We are currently migrating enterprise solution to new version of ui-router and this (change configuration for 50+ routes) is the only problem in otherwise seamless migration process...

**Comment by douglasg14b** [comment]
@christopherthielen  Same issue as OP except defining the default param values doesn't actually fix the problem.

**Comment by nateslo** [comment]
I had this issue as well. In my case I can calling `$state.go('login')` from inside a `$transitions.onError` hook. I solved the issue by explicitly passing a params object:  `$state.go('login', params)`.

**Comment by luncheon** [comment]
Don't let me hack like this.

```javascript
const paramFactory_fromPath = $urlMatcherFactoryProvider.paramFactory.fromPath;
$urlMatcherFactoryProvider.paramFactory.fromPath = function () {
    const param = paramFactory_fromPath.apply(this, arguments);
    param.isOptional = true;
    return param;
}
```
