### ISSUE TITLE
stateEvents polyfill causes browser not to change URL on browser properly

### ISSUE THREAD

**Issue by brenolf** [angular-ui/ui-router#3313]
When I use the polyfill provided with `v1.0.0-rc.1` my URL does not seem to change, even though the state itself changes (the ui gets updated). If I remove the script from the code, then it works as expected.

Moreover, when the script is on, I can't change the URL directly through the browser - it "flashes" the target state and gets back to where I was -, even though changing states by the visualizer project works properly. All my URLs are computed by using `$state.href` on a `ng-href`, and those do not change the URL either, only if I click on them for several times.

I do need this polyfill since angular-permission does not provide support for rc.1 yet, and thus, rely on using `$stateChangeStart`.

**Comment by mbenedettini** [comment]
I ended up with ui-router `0.4.2` (I've run into some problems with 1.0) and angular-permission `5.2.0`. No states polyfill, only `ui-router-route-to-components` which is required to route to components (Angular 1.5+). Feel free to ping me via email for more details that are not pertinent to ui-router.

**Comment by brenolf** [comment]
Good to know @mbenedettini. What I ended up doing was watching `$transitions.onStart` and calling directly `PermStateAuthorization` from angular-permission.

Not the best to be done, but it did the job as a workaround.
