### ISSUE TITLE
Unhandled rejection when doing event.preventDefault()

### ISSUE THREAD

**Issue by rostislavprovodenko** [angular-ui/ui-router#3314]
Using ui-router 1.0.0 rc1 and stateEvents.js with angular 1.56. 
Code:
`$scope.$on('$stateChangeStart', (event) => event.preventDefault())`
causes error messages to be written to console: 'TransactionRejection(type 3, message: The transition has been aborted, detail: Hook aborted transition)'. I have provided a custom error handler to $state.defaultErrorHandler() that ignores type 3 transition rejections. However, it'd be nice if the built in handler itself ignored type 3 errors.  

Regards,
Rostislav.

**Comment by christopherthielen** [comment]
Should be fixed in rc.2 by b07a24b992aaeb8062e52e32f72f4f70a1e38d98

**Comment by MatissJanis** [comment]
What's the expected release date for rc.2?

**Comment by christopherthielen** [comment]
I no longer provide expected release dates because I'm always wrong.
