### ISSUE TITLE
Redirecting to state with no URL in transition hook ignores location=false

### ISSUE THREAD

**Issue by smhc** [angular-ui/ui-router#3317]
I have a login state with no URL specified. The idea is when navigating to a given state they will be redirected to the login state if they aren't logged in. The URL shouldn't be updated in this case - it should reflect the intended state. If they login, the state is synced with the url via $urlRouter.sync().

However what is happening is:

```js
redirect to login
transition login Object {
    location: "replace", 
    relative: null, 
    inherit: true, 
    notify: false, 
    current:
    custom:
    inherit: true
    location: "replace"
    notify: false
    redirectedFrom: Transition
    relative: null
    reload: false
    reloadState: undefined
    source: "redirect"
passing through 
transition home Object {
    location: true,
    relative: null,
    inherit: true,
    notify: true,
    current: 
    custom: 
    inherit: true
    location: true
    notify: true
    relative: null
    reload: false
    reloadState: undefined
    source: "url"
redirect to login
transition login Object {
    location: "replace", 
    relative: null,
    inherit: true,
    notify: false,
    current:
    custom:
    inherit: true
    location: "replace"
    notify: false
    redirectedFrom: Transition
    relative: null
    reload: false
    reloadState: undefined
    source: "redirect"
passing through 
```

The redirect is using code similar to:

```js
return $state.target('login', [], { custom: { xx: 'asdf'} , notify: false, location: false });
```

But location is being set to 'replace'. Because the login state doesn't have a URL, it is being set to '/', which modifies the URL, losing the intended url and causing extra state redirects (intended -> login -> / -> login)

(ui router v1.0.0-rc.1, angular 1.6.1)

**Comment by smhc** [comment]
I made the following change and got the behaviour I wanted. Not sure if it is correct however:

```js
        var rejectedTransitionHandler = function (transition) { return function (error) {
            if (error instanceof Rejection) {
                if (error.type === exports.RejectType.IGNORED) {
                    // Consider ignored `Transition.run()` as a successful `transitionTo`
                    if (transition._targetState._options.location) {
                        router.urlRouter.update();
                    }
                    return services.$q.when(globals.current);
                }
```

**Comment by christopherthielen** [comment]
> I have a login state with no URL specified. The idea is when navigating to a given state they will be redirected to the login state if they aren't logged in. The URL shouldn't be updated in this case - it should reflect the intended state. If they login, the state is synced with the url via $urlRouter.sync().


Sounds like what we're doing in the sample app: 
https://ui-router.github.io/sample-app-ng1/#/mymessages/inbox/5648b50cc586cac4aed6836f

https://github.com/ui-router/sample-app-ng1/blob/8604ca2c7c7d5ac4db8ed3a96c1f3b8825b722dd/app/global/requiresAuth.hook.js#L18-L24

```js
  // Function that returns a redirect for the current transition to the login state
  // if the user is not currently authenticated (according to the AuthService)

  let redirectToLogin = (transition) => {
    let AuthService = transition.injector().get('AuthService');
    let $state = transition.router.stateService;
    if (!AuthService.isAuthenticated()) {
      return $state.target('login', undefined, { location: false });
    }
  };
```

**Comment by christopherthielen** [comment]
@smhc Do you notice anything missing in this block of code? ;)

https://github.com/ui-router/core/blob/afdeec286b68a5df5d74b7093f682354c40e26ef/src/transition/transition.ts#L518-L523

```js
    // If the original transition was caused by URL sync, then use { location: 'replace' }
    // on the new transition (unless  the target state explicitly specifies location)
    if (this.options().source === 'url') {
      redirectOpts.location = 'replace';
    }
```

**Comment by smhc** [comment]
I think this ended up being a problem on my end. I was navigating to "#/" instead of "#!/". I believe this changed with angular 1.6.

This caused extra redirects and URL syncs. I'm not sure if it's still a bug, but I have worked around it by using #! in the URLs. Of course anyone that has an old bookmark with the '#/xx' style URL will get bounced back to '#!/'  if they tried to use it while not logged in.

**Comment by christopherthielen** [comment]
>  '#/xx' style URL will get bounced back to '#!/' if they tried to use it while not logged in.

You could have changed the location prefix back to empty string

```
$locationProvider.hashPrefix("")
```

Your bug report is valid, the sample app `location: false` is not being respected with rc.1

**Comment by smhc** [comment]
I have a strong suspicion this fix is causing state transitions via url changes to result in the url to be modified despite the state transition being rejected. (https://github.com/angular-ui/ui-router/issues/3416)

**Comment by christopherthielen** [comment]
@smhc can you elaborate? The url isn't being reset to the previous when the transition is rejected?

**Comment by smhc** [comment]
Yes that's right. When changing the URL via the address bar or a bookmark and the state transition is rejected via UiCanExit() returning false.  In this scenario the URL does not get restored to the original. I suppose it could also happen when hitting 'back' or 'forward' in the browser.

It works ok when changing state via the application. But in this case the URL never gets a chance to change.

**Comment by smhc** [comment]
Looks like a similar issue to : https://github.com/angular-ui/ui-router/issues/3403
It seems to occur when uiCanExit returns a promise that either rejects or resolves to false.

**Comment by mikerandall** [comment]
This is also happening for me. It appears that when I redirect using the following code: `
        $transitions.onBefore(
            {
                to: (state) => {
                    return state.name.includes('private.secondary.first-path') ||
                        state.name.includes('private.secondary.second-path') ||
                        state.name.includes('private.secondary.third-path');
                },
                from: (state) => {
                    return state.name.includes('private.primary.first-path') ||
                        state.name.includes('private.primary.second-path') ||
                        state.name.includes('private.primary.third-path');
                }
            },
            (transition) => {
                return false;
            }
        );`

Clicking the back button will cancel the route change, but the URL will still change to that contained in private.secondary.**.
