### ISSUE TITLE
[0.X] Misleading documentation for `$state.go`

### ISSUE THREAD

**Issue by nmccready** [angular-ui/ui-router#3319]
Apologies first if the assumptions below are incorrect.

The following is on the wiki and current website
Some examples:
* `$state.go('^')` will go to a parent state.
* `$state.go('^.sibling')` will go to a sibling state.
* `$state.go('.child')` will go to a child state.
* `$state.go('.child.grandchild')` will go to a grandchild state.

To keep things simple let's just focus on `.child` . The language above to me makes one think that the following will happen:

routes defined in the following order:
- 'dashboard'
- 'dashboard.a'
- 'dashboard.b'

Assume, I am already in parent route 'dashboard' . Thus the assumption is that $state.go('.child') would go to 'dashboard.a'. However in inspecting the code it appears that the intent is actually only using the explicit child name.

Where only `$state.go('.a')` will work. 

The same can be said for sibling and for grandchild.  I also assume this is why this decorator / extension exists in the first place. https://github.com/marklagendijk/ui-router.stateHelper

Anyway It would be nice to update the documentation to be more explicit to avoid the above confusion.

Relevant code https://github.com/angular-ui/ui-router/blob/0.4.2/src/state.js#L124-L145

**Comment by christopherthielen** [comment]
Took me a long time to understand your interpretation of the docs!  I'll update the 1.0 branch with some clarifications.
