### ISSUE TITLE
ResolvePolicy NOWAIT - rejected promise handling

### ISSUE THREAD

**Issue by aj-dev** [angular-ui/ui-router#3320]
I couldn't find any  example of handling rejected `resolve` promises globally with ResolvePolicy `async:NOWAIT`. I understand that in this case transition successfully completes because `resolve` promise is not unwrapped and its rejection doesn't affect the transition, but I would like to handle the rejection and redirect to a different state. Handling rejection in every controller or service is not DRY.

With ResolvePolicy `async:WAIT` I can use global `$transitions.onError()` hook in run block to handle all rejections - https://plnkr.co/edit/QHUi0x?p=preview.

For obvious reasons, the same doesn't work when policy is `async:NOWAIT` - https://plnkr.co/edit/pdXU6c?p=preview.

What would be the recommended way of handling all `resolve` promise rejections globally? Can we tap into current transition's resolvables in run block and attach a `catch()` handler to all `async:NOWAIT` resolvables?

According to the docs https://ui-router.github.io/ng1/docs/latest/classes/resolve.resolvable.html, we can use `Resolvable.get(resolveContext, transition)` which returns either a resolvable promise or resolved data so my initial thought was to do something like the this:
```javascript
        $transitions.onStart({
            to: function (state) {
                var resolvable = state.resolvables[0];
                var resolvablePromise = resolvable.get(resolveContext);

                resolvablePromise.catch(function onRejected() {
                    // Handle rejected resolve
                });
            }
        }, onStartHook);
```
but how can I get hold of `resolveContext`? Is it a feature that's available in internal API only?

**Comment by christopherthielen** [comment]
> but how can I get hold of resolveContext? Is it a feature that's available in internal API only?

yes, I believe its internal api only.  You can use [`Transition.getResolveTokens`](https://ui-router.github.io/ng1/docs/latest/classes/transition.transition-1.html#getresolvetokens) and  [`Transition.injector()`](https://ui-router.github.io/ng1/docs/latest/classes/transition.transition-1.html#injector) to find resolves that are returned as promises (i.e., NOWAIT resolves)

Here's a plunker: https://plnkr.co/edit/DKiKqi?p=preview

```js
  $transitions.onStart({}, function(transition) {
      let tokens = transition.getResolveTokens();
      let injector = transition.injector();
      const isPromise = obj => obj && typeof obj.then === 'function';
      let promises = tokens.map(tok => injector.get(tok)).filter(isPromise);
      
      Promise.all(promises).catch(err => console.log("Hey, the promise broke: " + err))
    });
```
