### ISSUE TITLE
1.0.0x fires $onInit, $destroy, ... on route change even with notify: false

### ISSUE THREAD

**Issue by Head** [angular-ui/ui-router#3321]
Whenever I change the state with:
`$state.transitionTo("app", {filter_text: nv}, {notify: false});`

All 1.0.0x versions call all init and destroy events on the controller. 0.4.2 is not doing this.
See: http://plnkr.co/edit/OdEBP3Ik7pv2j3NsloeF?p=preview

Maybe related to #1674 - which was using version 0.2.13? - But this one do not trigger init, onInit, destroy.

**Comment by pootzko** [comment]
So is this fixed or? I believe I'm experiencing the same issue.
