### ISSUE TITLE
$templateFactory should allow to ignore http error by passing option for the $templateRequest

### ISSUE THREAD

**Issue by anantanandgupta** [angular-ui/ui-router#3322]
`$templateRequest` has an additional parameter which is used to indicate if the http errors should be reported or ignored. There seems no option to configure this in the `$templateFactory` so that this can be turned off or on. I have modified the provider locally and is now working as expected. Please let me know if you think that this should be required feature and need the PR for that.

**Comment by christopherthielen** [comment]
Help me understand.  Why would you want to ignore a failed template fetch?
