### ISSUE TITLE
transitionTo resolved state does not have params

### ISSUE THREAD

**Issue by kkoo95** [angular-ui/ui-router#3327]
I am in the case where my transition is ignored because it's same state than the current one (name + params). But still I would like to trigger some operations. Here is a very simplified version:

```javascript
function Controller($transitions, $state) {
    $transitions.onSuccess({to: 'home'}, function(transition) {
      // transition.params().filter !== null (=== filterType) :)
      doFilter(transition.params().filter);
    });

   this.onClick = function(filterType) {
      $state.go('home', {filter: filterType)
        .then(function(state) {
          // state.params.filter === null :(
          doFilter(state.params.filter);
        });
    }

   function doFilter(filterType) {
     // ...
   }
}
```

Shouldn't the state contains this information ? Shouldn't you resolve some other data in StateService#transitionTo > rejectedTransitionHandler ?
I am using beta 3

**Comment by christopherthielen** [comment]
> Shouldn't the state contains this information ?

No, `state.params` is the state declaration object's params list. It's the static definition that you registered, and does not change.

I suggest injecting `$uiRouter` and checking `$uiRouter.globals.params`

>  Shouldn't you resolve some other data in StateService#transitionTo > rejectedTransitionHandler ? 

I do not understand the question.


```js
function Controller($transitions, $state) {
    $transitions.onSuccess({to: 'home'}, function(transition) {
      // transition.params().filter !== null (=== filterType) :)
      doFilter(transition.params().filter);
    });
```

If you register a transition hook in a controller, don't forget to deregister it when the controller is destroyed.
