### ISSUE TITLE
$state.is() does not immediately return try when app is initialised on the route provided

### ISSUE THREAD

**Issue by tyronedougherty** [angular-ui/ui-router#3328]
(title correction: $state.is() does not immediately return **_true_** when app is initialised on the route provided)

On our application we have a check to determine if the current page is the login page. It is used to hide certain elements of the page with an `ng-if` directive.

```
...
    isLogin() {
        return this._$state.is('login');
    }
...
```

This works great, except for the first second or so when the page is reloaded, in which case it appears as though the state is not properly loaded, and this function returns false despite it being on the `login` state. However `$state.is('')` returns true.

What's going on here and is there a fix?

This occurs on `1.0.0-beta.3` and `1.0.0-rc.1`.

**Comment by GSTVAC** [comment]
I faced a problem similar to yours some time ago. In my case I was reading the properties before my controller was fully initialized.
My problem was solved putting my initialization code inside the controller's `$onInit` hook.
Read more here: https://docs.angularjs.org/api/ng/service/$compile

**Comment by tyronedougherty** [comment]
Annoyingly because the function is called by the `ng-if` directive, it seems to be run before initialization 😢.

The solution I rested on was to simply make the element be hidden with CSS by default and replace the `ng-if` with an `ng-show` instead, this quickly shows the element without the user impact being too noticeable.

Thanks anyway @GSTVAC !
I'd still be interested to know if anyone else has any other solutions though! 😄

**Comment by christopherthielen** [comment]
You might try  ng-cloak

**Comment by christopherthielen** [comment]
@tyronedougherty its because the state is not `login` until after the initial transition succeeds.  The current state is technically the "root state" (it is named empty string: `""`).  

Closing because I don't think this is a bug
