### ISSUE TITLE
Handling both a default starting state and 404 errors.

### ISSUE THREAD

**Issue by superciccio14** [angular-ui/ui-router#3336]
Hi there. I'd like to handle both a default state for the first page get and show a 404 error template if a url does not exist. I'm trying with

`$urlRouterProvider.otherwise("/");`

That solve my first problem but, of course, anytime an incorrect url is typed, ui-router load the starting state. Is there a way to handle those two cases separately?

**Comment by ricardovigatti** [comment]
+1

**Comment by christopherthielen** [comment]
We will add an API for this soon. 

In the meantime you should be able to use a function for otherwise that picks the URL to redirect to. It can check the ui router globals transition history to see if it is before any transitions have started
