### ISSUE TITLE
Issue with UI-Grid Angular 1.6.1 with Big JSON

### ISSUE THREAD

**Issue by akprasadyadla** [angular-ui/ui-router#3337]
Hi,
I am using UI-Grid with angular 1.6.1 version. i have a JSON to bind the grid. Actually this JSON contains data of 17000 records. when i bind this jSON to the grid, i am facing Stats: 500, Inetrnal server error. 
If i remove some data from the JSON for ex: keep only 100 records. it is working as expcted. Can you please help me how to resolve this.

**Error message:
------------------------
Possibly unhandled rejection: {"data":{"Message":"There was an error processing the request.","StackTrace":"","ExceptionType":""},"status":500,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"Test.aspx/GetData","data":{"data":{},"params":{"pageSize":5,"pageNumber":1}},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"}},"statusText":"Internal Server Error"}(anonymous function) @ angular.js:14328**

**Comment by mirajehossain** [comment]
i have same problem

**Comment by christopherthielen** [comment]
Server error means the error is on the server.  This probably isn't a ui-router problem.
