### ISSUE TITLE
ui-sref-opts desn't work when states are defined dynamically

### ISSUE THREAD

**Issue by GSTVAC** [angular-ui/ui-router#3338]
I've been trying to set my states dynamically, based on data returned by the backend. Everything works fine, except when I need to reload the current state. I am setting `ui-sref-opts="{reload: true}"`.

Plunkr here: http://plnkr.co/edit/KBRFkZATp1dXbUrsqWMZ

Is this a bug or am I doing something wrong??

Thanks

**Comment by christopherthielen** [comment]
The root state is "special"; by removing it you've broken some other code that checks for object equality.


https://github.com/ui-router/core/blob/612d2e1e9bfa00e6bdfe9e34fc473684bc7ac33e/src/state/stateService.ts#L282
https://github.com/ui-router/core/blob/612d2e1e9bfa00e6bdfe9e34fc473684bc7ac33e/src/path/pathFactory.ts#L103-L112

Deregister the children of root (top level states) instead and your plunker works:  http://plnkr.co/edit/r94ADY4wkZxHd4ClcbG1?p=preview
