### ISSUE TITLE
?parameter (get) in substate is null

### ISSUE THREAD

**Issue by nvomedia** [angular-ui/ui-router#3339]
Currently I have this state structure:
```
.state("shop", {
	abstract: true,
	url: '/shop/:nameSlug',
	templateUrl: '/views/shop/index.html',
	controller: 'shopController',
	params: {
		nameSlug: null,
	}
})
.state('shop.payment-success', {
	url: '/payment-success?transactionid',
	templateUrl: '/views/payment-success.html',
	resolve: {
		transactionid: ['$stateParams', function($stateParams){
			console.log($stateParams);
			return $stateParams.transactionid				
		}]
	},
	controller: 'checkoutController'
})
```

From a external payment provider I get this url:
website.com/shop/[nameSlug]/payment-succes?transactionid=[someid]

With this code the transactionid is null. With all the methods I found on the internet I can't get this to work. 
I tried:
```
url: 'payment-success:transactionid
url: 'payment-success[:transactionid] / [?transactionid]
url: 'payment-success{transactionid}
params: {
       transactionid: null
}
squash: true/false
```

but transactionid in the $stateparams is still undefined. I also tried $state.params, but no difference.

**Comment by christopherthielen** [comment]
are you saying you want the query parameter `transactionid` to have square brackets around it like 
```
website.com/shop/name/payment-succes?transactionid=[123]
```

or are you saying that the simple query parameter 123 is never parsed into state params?
```
website.com/shop/name/payment-succes?transactionid=123
```

**Comment by christopherthielen** [comment]
here's a plunker demonstrating that your state defs should work: http://plnkr.co/edit/01G7YwA58BR6AD3gX7HK?p=info

**Comment by nvomedia** [comment]
Ah! Thank you for your code! 
After viewing and testing it, i was able to find our problem:

We have code to remove the trailing slash to avoid conflicts with other pages and after disabling it, it was working.

` $urlRouterProvider.rule(function($injector, $location) {
		 	var path = $location.path();
		 	var hasTrailingSlash = path[path.length-1] === '/';

			if(hasTrailingSlash) {
				//if last charcter is a slash, return the same url without the slash  
				var newPath = path.substr(0, path.length - 1); 
				return newPath; 
			}
		});`

**Comment by nvomedia** [comment]
Fixed! Added an `&& !location.search` in the` if(hasTrailingSlash) check!`
