### ISSUE TITLE
ES5 output of version 1.x (ng1)

### ISSUE THREAD

**Issue by emonhaider** [angular-ui/ui-router#3341]
I am using the 1.0.0-rc.1 and having issues with IE11 because it doesn't support ES5. Is there an ES5 output available? Or how would I go about transpiling the typescript to ES5?

**Comment by christopherthielen** [comment]
The bundles we provide are already transpiled to ES5. We also provide the individual commonJS transpiled files in the NPM package. 


What problems are you having in IE 11?

**Comment by emonhaider** [comment]
I am getting the following error:
![image](https://cloud.githubusercontent.com/assets/1793646/23075864/0d3d5738-f50c-11e6-8cf0-2326753e6c81.png)
which points to this line in the code:
![image](https://cloud.githubusercontent.com/assets/1793646/23075835/f5fb20aa-f50b-11e6-8bf2-381ec394ff4f.png)

Thats look like a ES6 syntax.

**Comment by emonhaider** [comment]
Changing the IE11 render mode helped solved the issue. I just added the following in the head section of index.html

<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
