### ISSUE TITLE
$stateParams are not reset when transitioning back to current state

### ISSUE THREAD

**Issue by gscoppino** [angular-ui/ui-router#3342]
Hello,

I am having an issue with the `$stateParams` service, when using in conjunction with non-URL state parameters.

## Background:
Essentially, I have a state `foo` with a URL of `/foo`. This state takes a non-URL parameter, which we will just call `testParam`, which defaults to a value of `null`.

## Problem:
If I navigate to this state using the non-URL parameter, then click a link in this state that is to the same state (without the non-URL parameter specified), the non-URL parameter is still present in the `$stateParams`, with the value from the last transition. This happens even if I pass an empty params object to the transition e.g. `<a ui-sref="foo({})></a>`

## What did I expect?
I expected the `$stateParams` to be reset since the transition is not to a child state. In both the legacy and 1.0 docs for `$state.go` (which `ui-sref` uses internally), it is stated that when transitioning, unspecified parameters will be inherited only from ancestor states.

Legacy: https://ui-router.github.io/ng1/docs/0.4.2/#/api/ui.router.state.$state
1.0: https://ui-router.github.io/ng1/docs/latest/classes/state.stateservice.html#go

## What happened?
The `$stateParams` were not reset and contained a parameter from the previous transition, which was the same state as the current transition.

## How can it be replicated?
Run this plunker: http://plnkr.co/edit/NC0OT6x925kk8S8mtXLl
1. Click the "Load state foo with non-URL param" link in the navigation. This will go to state foo, passing it a non-url parameter.
2. Click the "Load foo again with no params" link in the new view. This will go to the same state, but passing an empty object as parameters to the state.
3. Notice that the `$stateParams.testParam` value is still the same from step 1.

As a side note, the same problem can be seen if editing the URL manually. If there exists a state with URL `/foo/{id}`, and you transition to this state, passing a non-URL parameter as well as the id, then change the id manually in the address bar, the state will re-resolve itself, but the non-URL parameter from the previous transition will be present.

## Other Notes
The behavior is correct (to me, based on my expectation) when using `ui-sref-opts={inherit: false}` on my link, but the issue still manifests when manually changing the URL as noted above.

**Comment by christopherthielen** [comment]
First off, I really appreciate the very detailed and well researched bug report.  

This is definitely a docs issue.  It's also somewhat difficult to describe, which is probably why the docs are ambiguous.

During a transition with `inherit: true`, all of the current parameter values are inherited and added to the new transition.  For many users, it's very important that non-url parameters in particular are inherited.  This allows links (to the current state) to be used which only update a single parameter value.  

The appropriate fix is (as you noted) to use `inherit: false` where appropriate.  That might be on the individual link (ui-sref-opts), or you might want to disable `inherit` on a param-by-param basis: https://ui-router.github.io/ng1/docs/latest/interfaces/params.paramdeclaration.html#inherit

I'll try to get the docs for `inherit` updated to be less ambiguous.
