### ISSUE TITLE
binding state params

### ISSUE THREAD

**Issue by svpace** [angular-ui/ui-router#3344]
It would be great if state params could be binded to components like resolves. It would reduce the code used to lookup $transition$.params() and would allow dynamic params to be treated with $onChange instead of uiOnParamsChanged.

**Comment by christopherthielen** [comment]
That's an interesting idea and might make a lot of sense if we allow components to be re-used sometime in the future.  However, today there is no way to update the bindings of routed components (not even for resolves -- it's a one-time binding that is rebuilt when the component is re-rendered).

It will require some re-work in the view management to allow component reuse.  If we implement reuse, we can reconsider this feature request.  For now, I'm closing as wontfix.

---

Note: You can also inject `$uiRouterGlobals` and `$watch` the `$uiRouterGlobals.params` object.

I also feel that Observables and dynamic parameters are a great combination.

**Comment by adamreisnz** [comment]
I second this feature 👍
