### ISSUE TITLE
Make resolvables available in param declaration 

### ISSUE THREAD

**Issue by bogdanalexe90** [angular-ui/ui-router#3346]
Hi as a quick feedback,
It will be really nice if resolvables will be available to be used in param declaration when passing a function to compute default param value. That function is already injectable but it throws an error when you try to use a resolvable dependency.

**Comment by christopherthielen** [comment]
I appreciate the feedback.  However, param values must be synchronous.  We compute and compare parameter values synchronously to tell if any states are being exited/entered, so they fundamentally cannot depend on asynchronous code.

if you tell me what you're trying to accomplish, I might be able to offer some other approach.
