### ISSUE TITLE
unable to get a custom attribute on $state

### ISSUE THREAD

**Issue by CMiworld** [angular-ui/ui-router#3347]
I found a problem about routing verification :
```
$stateProvider.state('main',{
        requiresLogin: true,
        url: "/main",
        templateUrl : "./view/main.html",
        controller: "mainCtr",
})

.run(['$rootScope','$state', function($rootScope,$state){
     $rootScope.$on('$stateChangeStart',function(){        
        console.log($state.current.requiresLogin);
         if($state.current.requiresLogin){
               // Verify the login or check TokenExpired 
          }
     });
}]);
```

But `$state.current.requiresLogin` is undefine

**Comment by christopherthielen** [comment]
You need to check the event parameters for the toState.  `.current` isn't updated until AFTER the transition to the new state is complete.

```
     $rootScope.$on('$stateChangeStart',function(evt, toState, toParams){        
        console.log(toState.requiresLogin);
         if(toState.requiresLogin){
               // Verify the login or check TokenExpired 
          }
     });

```

Please also read about migrating to ui-router 1.0, which is nearly complete: https://ui-router.github.io/guide/ng1/migrate-to-1_0


There's a section in there about how `$stateChange*` [are now deprecated and removed](https://ui-router.github.io/guide/ng1/migrate-to-1_0#state-change-events)
