### ISSUE TITLE
Distinct and non-overlapping ui-views for different routes

### ISSUE THREAD

**Issue by rishighan** [angular-ui/ui-router#3348]
My application has a bunch of states defined using `ui-router`

`home.js`
    
    //.... 
    .config(($stateProvider, $urlRouterProvider) => {
      $urlRouterProvider.otherwise('/');
      $stateProvider
        .state('home', {
            url: '/',
            template: '<home></home>',
            access: {restricted: false}
        })
        .state('single',{
            url: '/post/:slug',
            params: {id: undefined},
            template: '<single></single>',
            access: {restricted: false}
        })
    })
    // ... some other stuff

At the same time, I have my CMS routes defined in `admin.js` like so:

    import createTemplate from './create/create.post.html';
    import adminLayout from './admin.layout.html';

    .config(($stateProvider, $urlRouterProvider) => {
        $stateProvider
            .state('admin', {
                abstract: true,
                url: '/admin',
                template: adminLayout
            })

            .state('admin.create', {
                url: '/create',
                template: createTemplate,
                access: {restricted: true}
            })
            .state('admin.posts', {
                url: '/posts',
                template: '<allposts></allposts>',
                access: {restricted: true}
            })
            .state('admin.edit', {
                url: '/edit/:id',
                template: '<editpost></editpost>',
                access: {restricted: true}
            });
    })

I have 2 _master_ layouts-one for the the non-CMS routes, and the other for the CMS routes. The reason for keeping them distinct is because they have different UI elements; different enough to justify keeping them in different layouts.

`app.html`

    <div class="app">
    <div class="container">
        <div class="body row">
            <div class="col-md-2">
                <navbar menu-items="ac.navItems" orientation="vertical" logo="true"></navbar>
            </div>

            <div ui-view></div>

            <footer class="col-md-6 col-md-offset-2">
                <span translate="{{'footer.copyright_symbol.fragment'}}"></span>
                {{'footer.copyright_years.fragment' | translate}} {{'colophon.author_name.fragment' | translate}}
            </footer>
        </div>
    </div>
</div>

`admin.layout.html`

    <div>
      <div ui-view></div>
    </div>

The problem I am facing is that whenever I navigate to `/admin/create` or any of the `admin` routes, I see the layout for `app.html` _as well as_ the layout for `admin.layout.html` together.

How do I configure the `ui-view`s such that I can have _distinct_ layouts for the non-CMS routes and the CMS ones?

**Comment by christopherthielen** [comment]
If I understand correctly, when you route to `admin.**` the `admin.layout.html` renders *inside* the `ui-view` in `app.html`?

```
<div class="app">
<div class="container">
    <div class="body row">
        <div class="col-md-2">
            <navbar menu-items="ac.navItems" orientation="vertical" logo="true"></navbar>
        </div>

        <div ui-view>
           <div><!-- admin.layout.html -->
               <div ui-view></div>
           </div>
        </div>

        <footer class="col-md-6 col-md-offset-2">
            <span translate="{{'footer.copyright_symbol.fragment'}}"></span>
            {{'footer.copyright_years.fragment' | translate}} {{'colophon.author_name.fragment' | translate}}
        </footer>
    </div>
</div>
```

How is `app.html`  being rendered when you are in the admin states? Is it loaded as a part of `index.html`?

Generally I'd suggest rendering `app.html` into a `ui-view`.  You can accomplish this by making a parent state for all your `home`, `single`, etc states that uses `app.html` as its view.  Then, when you activate `home`, the top level ui-view is filled by `app.html`, but when you activate `admin.**` it is filled by `admin.layout.html`.

You can add a parent state using the `parent: ` property to the top level "cms states", such as:

```js
  $stateProvider
    .state('cms', {
        templateUrl: 'app.html',
    })    .state('home', {
        parent: 'cms',
        url: '/',
        template: '<home></home>',
        access: {restricted: false}
    })
    .state('single',{
        parent: 'cms',
        url: '/post/:slug',
        params: {id: undefined},
        template: '<single></single>',
        access: {restricted: false}
    })
```

Hope this helps. Let me know if it answers your question.

**Comment by rishighan** [comment]
Thanks @christopherthielen for the prompt reply. You are correct in your understanding that the admin layout was rendering inside the `ui-view` of the app's template.

That said, looking at the code you posted, I wasn't aware of the `parent` key for a state.

I ended up doing this:

I create two abstract states: `main` and `admin` with corresponding `main.layout.html` and `admin.layout.html` Each of these layouts have their own `ui-view` into which, as far as I understand, the child states will plug in their own templates.

Then I created child states for each of these abstract states:

```javascript
.config(($stateProvider, $urlRouterProvider) => {
        $stateProvider
            .state('admin',{
                url: '/admin',
                abstract: true,
                templateUrl: './components/admin/admin.layout.html',
                controller: AdminController,
                controllerAs: 'adc'
            })
            .state('admin.create', {
                url: '/create',
                template: '<createpost></createpost>',
                access: {restricted: false}
            })
            .state('admin.posts', {
                url: '/posts',
                template: '<allposts></allposts>',
                access: {restricted: true}
            })
            .state('admin.edit', {
                url: '/edit/:id',
                template: '<editpost></editpost>',
                access: {restricted: true}
            });
    })
```

and 

```javascript
.config(($stateProvider, $urlRouterProvider) => {
    $urlRouterProvider.otherwise('/');
    $stateProvider
        .state('main', {
            abstract: true,
            templateUrl: './components/home/main.layout.html'
        })
        .state('main.home', {
            url: '/home',
            template: '<home></home>',
            access: {restricted: false}
        })
        .state('main.single',{
            url: '/post/:slug',
            params: {id: undefined},
            template: '<single></single>',
            access: {restricted: false}
        })
        .state('main.work', {
            url: '/work',
            template: '<work></work>',
            access: {restricted: false}
        })
        .state('main.trampoline', {
            url: '/trampoline',
            template: '<trampoline></trampoline>',
            access: {restricted: false}
        })
        .state('main.illustrations', {
            url: '/illustrations',
            template: '<illustrations></illustrations>',
            access: {restricted: false}
        });
})
```

This worked for me to achieve my stated goal of having distinct layouts for CMS and home page routes. Thanks for your reply though, learned something new!
