### ISSUE TITLE
multiple view (master-child) and component refresh

### ISSUE THREAD

**Issue by johnnliu** [angular-ui/ui-router#3351]
Hi,

So I've built out a dashboard using ui-router to pass state of the master-child components, this was a pretty fun exercise.  See this plunker.

https://plnkr.co/edit/OKCOrdrlm8edDNEUXzDw?p=preview

When the Dashboard component (master view) loads - it fetch a list of data.  I simulate this with setTimeout(...,2000).  And then it populates a list.

When different items are selected in the list, I put the ID into the dashboard-selected ui-param.  
(try clicking around the links on the master view)

This is sent to the DetailComponent (child view) below.

The child view has several items as well, as I select them, I store the ID into the detail-selected ui-param.  (try clicking around the links on the child view)

All is good.  

The problem is the data fetching on the master view.  See, I don't want the object to refresh.  But UI Router seems to be recreating that component, even if the dashboard-selected property doesn't change.

What are my options?

**Comment by christopherthielen** [comment]
Usually you would put the master view in a parent state, then put the child view in a child state.

https://plnkr.co/edit/6Y48QtFOHxXviDWupjDl?p=preview

UI-Router approach differs from a lot of the tutorials in that you usually fetch data in a resolve, not from component code.  This allows your components to be ignorant of *how to fetch* the data, potentially making them more re-usable.

You could also use observables to fetch the data which offers some other flexiblilty, but is a nuanced topic.  

Hope this helps!

**Comment by christopherthielen** [comment]
side note, the ng2 repo is at https://github.com/ui-router/ng2
