### ISSUE TITLE
Referencing nested named views only possible with full qualified name

### ISSUE THREAD

**Issue by yanxch** [angular-ui/ui-router#3355]
This issue tracker is for Bug Reports and Feature Requests only.
Please direct requests for help to StackOverflow.  See http://bit.ly/UIR-SOF for details.

This is a:

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: (1.0.0-rc.1)

# Bug Report

#### Current Behavior:

Named nested ui-views have to be referenced with their full qualified name. 

`<ui-view name="outer">
<ui-view name="inner">
</ui-view>
</ui-view>`

Inner ui-view has to be referenced with
` $stateProvider
        .state('home', {
          url: '/home',
          views: {
            'outer.inner': {
              template: '<home></home>'
            }
          }
        });`

#### Expected Behavior:

Reference a nested named ui-view just with its name.

Plunker:
https://plnkr.co/edit/MSEbqC4NMoilPUSg1o3H

**Comment by mischkl** [comment]
Same problem here

**Comment by christopherthielen** [comment]
Thanks for the great bug report. 

This was not intentional, and will be fixed in rc.2

https://plnkr.co/edit/JYnnsrBYHaWzyYK6QhT0?p=preview

**Comment by mischkl** [comment]
We've upgraded to the newest version 1.x and are still getting this issue :cry:
