### ISSUE TITLE
ui-router v1.0.0-rc.1 - uiCanExit/OnBefore/OnStateChanged canceling removes the url history

### ISSUE THREAD

**Issue by MaorZ** [angular-ui/ui-router#3357]
# Bug Report

#### Current Behavior:

When clicking the Back button in the browser and using the uiCanExit/OnBefore Transition event function and returning `false` or if i'm using the legacy state events ([https://ui-router.github.io/ng1/docs/latest/modules/ng1_state_events.html](url))
It will keep me in the same page.
But in the next Back click (when returning `true` so the Transition can pass normally), it will go back 2 times.

For example:
If you go to the plunker below you can reproduce it by doing the following:
1. now you are the `home` state, go to the `home.foo` state.
2. go to the `other` state.
3. click the back browser button (you will see the cancellation event and you should stay in the same page).
4. click the back browser button again.
5. you will be redirected to the home state.

I also noticed that after the first back cancel the browser will remove the previous history url.

#### Expected Behavior:

It should go back to the `home.foo` state.

#### Link to Plunker that reproduces the issue:

http://plnkr.co/edit/i15fdSEL5q632qGxOE91?p=preview

**Comment by christopherthielen** [comment]
thanks for the plunker.  I agree it would be ideal to detect the back button and choose `{location: true}` instead of `{ location: true }`.
