### ISSUE TITLE
Inherit `ui-sref-opts` from parent elements

### ISSUE THREAD

**Issue by mattbrunetti** [angular-ui/ui-router#3359]
This is a: Feature Request

My version of UI-Router is: 1.0.0-rc.1

---

It would be *awesome* if `ui-sref-opts` could be inherited from parent elements.

For example, instead of this...

```html
<ul>
  <li><a ui-sref="home" ui-sref-opts="{reload: true}">Home</a></li>
  <li><a ui-sref="page1" ui-sref-opts="{reload: true}">Page 1</a></li>
  <li><a ui-sref="page2" ui-sref-opts="{reload: true}">Page 2</a></li>
</ul>
```

we could do this...

```html
<ul ui-sref-opts="{reload: true}">
  <li><a ui-sref="home">Home</a></li>
  <li><a ui-sref="page1">Page 1</a></li>
  <li><a ui-sref="page2">Page 2</a></li>
</ul>
```

The menu in our app will have many many many items, and this would reduce the boilerplate quite a bit.

---

This is a similar feature idea to #1473

@christopherthielen Any thoughts on this? Any problems you can think of off-hand? If it's a feature you're interested in I'll look into making a PR (sometime within the next couple months... busy busy)

@TonyWilk Would this feature fit your use-case?

**Comment by christopherthielen** [comment]
Seems reasonable using 'require'. I wonder if somebody would request
support for multiple ui-sref-opts though, on various parent/self elements.

**Comment by mattbrunetti** [comment]
@christopherthielen I'd given some breif thought to what the behavior would be if there are multiple nested `ui-sref-opts`s... I was thinking it would be supported from the get-go, and the children `ui-sref-opts`s would inherit from their ancestors like so...

```html
<div ui-sref-opts="{reload: true}">
  <p ui-sref-opts="{notify: false}">
    <span ui-sref-opts="{reload: false}">
      <a ui-sref="foo">Foo</a> <!-- This element would have options {notify: false, reload: false} -->
    </span>
  </p>
</div>
```

Simple in theory, but I'm not really sure if that would be complicated to implement. If you think it's doable and wouldn't add too much complexity, I'm willing to give it a go!

Also, I'm sorry but I don't know what you mean by "using 'require'"... I did some searching but couldn't find anything.. Do you have a link?

Also, thank you so much, for all of your work! :clinking_glasses:

**Comment by christopherthielen** [comment]
A directive, such as ui-sref communicates with other directives using the require keyword on the directive definition object

**Comment by mattbrunetti** [comment]
Ahhh ok.. you caught me.. I'm an ng-newb :rofl: I've only written one simple directive so far. 

Sounds like it's doable then. We will get around to the PR in the near future.

Thanks again!
