### ISSUE TITLE
RC.1 Url Generation Performance Concerns

### ISSUE THREAD

**Issue by calebeno** [angular-ui/ui-router#3361]
This is a:

- [X] Bug Report
- [ ] Feature Request
- [ ] General Query 

My current version of UI-Router is: 1.0.0-beta.3
I am comparing this with version: 1.0.0-rc.1
My version of Angular is: 1.5.8

# Bug Report

I am working on a large web application and we have been investigating some performance concerns in the client-side.  Among other things, we have some concerns regarding the performance of ui-router, especially when it comes to link generation.  We have parts of our application where we are generating 1000+ links in a list.  These links (going to the same route) can have between 50-100 potential parameters.  Generating this list has caused wait times between 10-20 seconds before successful rendering after stripping the application down to only loading the links without any of the additional content.

I have been doing a comparison between our current version (beta.3) and the newest version (rc.1) to see if the most recent version would have better performance.  Unfortunately, rc.1 added to the load time instead of subtracting.  I built a jsFiddle example and forked it so each used a different version of ui-router.  Here are links to the jsFiddle examples and images taken from Chrome's timeline tools to compare:

Beta.3
[http://jsfiddle.net/r1mm0fja/55/](http://jsfiddle.net/r1mm0fja/55/)
![beta-3 jsfiddle 1000 links](https://cloud.githubusercontent.com/assets/9387933/23712849/1e5a7cf4-03f2-11e7-9c98-1a9ee8fcf681.jpg)

RC.1
[http://jsfiddle.net/r1mm0fja/56/](http://jsfiddle.net/r1mm0fja/56/)
![rc-1 jsfiddle 1000 links](https://cloud.githubusercontent.com/assets/9387933/23712879/31989364-03f2-11e7-89ca-5d4ef7dcf36e.jpg)

UI Router has been a great utility and we are glad to continue using it.  However, I have some concern regarding this performance issue.  We are able to create a workaround at this time by manually forming the link using string templating.  Will there be an effort to address performance concerns like these before the final release of 1.0?

**Comment by samithaf** [comment]
@christopherthielen wonder #3370 is related to this defect as well?

**Comment by 29er** [comment]
Yes it looks to be referring to same issue as #3370 
We have temporarily removed all **StateService.href** calls and used other approaches for now.

**Comment by christopherthielen** [comment]
I've done some optimizing.  Is this level of perf acceptable for your app @calebeno ?

http://plnkr.co/edit/wPox4BWUVRGEtglO6zAH?p=preview

**Comment by calebeno** [comment]
@christopherthielen That is a remarkable improvement!  Thank you!  When do you think rc.2 will be available?

**Comment by christopherthielen** [comment]
I've stopped telling people when I think a release will happen because I'm always horribly wrong :)

**Comment by calebeno** [comment]
That's fair : )

**Comment by samithaf** [comment]
@christopherthielen I modified your [plunker](https://plnkr.co/edit/aBqelRAiDu5ZFJgNV81V?p=preview) to create 1000 states. With RC1 it takes 11918ms to bootstrap the application. But with your new changes it only takes 348ms. That is impressive 👍

**Comment by christopherthielen** [comment]
@samithaf that's actually due to a different optimization:  https://github.com/angular-ui/ui-router/issues/3274#issuecomment-275436957
