### ISSUE TITLE
state reload to the same state doesn't invoke the controller

### ISSUE THREAD

**Issue by HarishRamanathan** [angular-ui/ui-router#3363]
This issue tracker is for Bug Reports and Feature Requests only.
Please direct requests for help to StackOverflow.  See http://bit.ly/UIR-SOF for details.

This is a:

- [x] Bug Report

My version of UI-Router is: 1.0.0-rc.1

# Bug Report

#### Current Behavior:

I am trying to reload the same state. But, the controller doesn't get invoked again. $state.reload($state.current);

I tried using $state.go(...) and $state.transitionTo(..). These lead to infinite loop.

#### Expected Behavior:

On reload of same state, the controller needs to get invoked again.

**Comment by christopherthielen** [comment]
Please provide a plunker which reproduces the issue.  http://bit.ly/UIR-Plunk1

When you have provided a plunker, re-open this issue.
