### ISSUE TITLE
Preserve State, and List of Active Views, instead of name/views

### ISSUE THREAD

**Issue by deadmann** [angular-ui/ui-router#3364]
I know This Issue Has Been Addressed Before, but since it's from years ago, and left unanswered, please let me re-ask this question or address this issue.

is there any possibility to persist list of views, and store them within an array? so for example i can create a list of user opened tabs, store their states, and if for some reason the user did not need it any longer, then close it? otherwise if user clicked on that tab, all data came with their previous state?

**Comment by christopherthielen** [comment]
Although it's rarely necessary for "end users", the views being activated are [available on each transition](https://ui-router.github.io/ng1/docs/latest/classes/transition.transition-1.html#views). You can wire up a hook to keep track of them.

```
onSuccess({}, transition => {
  var activeViews = transition.views("to");
});
```

**Comment by deadmann** [comment]
what the code says?  i call transition.view("<page name>")  instead of ui-serf  once i pressed the key? and it generate a new state in case it doesn't exist or move to if it exists? without reinitializing the whole view? i mean going back really to what it was?
