### ISSUE TITLE
fix(uiSref): use of jQuery Slim cause TypeError on element.bind() function

### ISSUE THREAD

**Issue by mateusleon** [angular-ui/ui-router#3366]
My version of UI-Router is: 1.0.0-beta.1
My version of Angular is: 1.6.2
My version of jQuery is: 3.1.1

# Bug Report

#### Current Behavior:

When jQuery Slim is added, I get a `TypeError: element.bind is not a function`, on file angular-ui-router.js, row 7270, column 26. It is on `ui-sref` directive, when its attach the click handler on the element.

#### Expected Behavior:

Expect to not throw errors on console for each `ui-sref` directive that is rendered on the page.

#### Link to Plunker that reproduces the issue:

It's not necessary, as is a report of a known method deprecation, and its fix is simple: change all `.bind()` related methods (bind, unbind...) to the active set (on, off, one...).

**Comment by christopherthielen** [comment]
[This has already been updated](https://github.com/angular-ui/ui-router/pull/2996/files).  

Note that beta.1 is now 3 releases old.
