### ISSUE TITLE
ui-router rocks!!!

### ISSUE THREAD

**Issue by yjaaidi** [angular-ui/ui-router#3368]
Hi!
I don't mean to be annoying but I guess that issues are negative most of the time so I thought that an encouragement issue would be nice.

So happy to replace stupid ng2 native router with ui-router :D

**Comment by VAchris** [comment]
@christopherthielen thanks for keeping ui-router awesome!

**Comment by christopherthielen** [comment]
Thanks, all :) this really made my day

**Comment by maximilianschmid** [comment]
+1
