### ISSUE TITLE
Issue with performance after upgrade from 0.2.8 to 1

### ISSUE THREAD

**Issue by 29er** [angular-ui/ui-router#3370]
SO long story short, we made a big effort in our Angular 1.5+ app to upgrade to the 1.0 version of ui-router.(  from 0.2.8 to 1.0.0-rc.1 ) Ever since the upgrade we have noticed terrible performance in our grids ( "angular-ui-grid": "3.0.7" )
 After a week of performance testing (Chrome Dev Tools Timeline etc.),  we were able to isolate one of the main issues as being from ui-router and the StateService.href function.
For example, in our datagrid, we create custom cell templates that just generate href routes to 'states' in the app. We use 'this.$state.href'  (StateService.href)  to do this.
There are **a lot** of cells in our grids that do this.

A quick example:
```
myCtorller.$inject = [ '$state', '$stateParams']
....
createCustomCellTemplate( para1, param2 ) {
            return this.$state.href('app.myRoute', {
                param1: para1,
                param2: param2,
            })
    }
```

All browsers ( FF,IE,CHROME ) eventually freeze when we open up these grids. We tested by circumventing the ' this.$state.href' call and just hard coding href routes, and that made the performance MUCH better.  The degradation of performance is so noticeable that we have discussed reverting back to the 0.2.8. , but I wanted to see if anyone else out there had also seen this and if you had any ideas on alternatives.
Thanks!

**Comment by samithaf** [comment]
I am experiencing the same and I have upgraded from 1.0.0-alpha.5 to 1.0.0-rc.1. Application bootstrap jumped from 1152ms to 2252ms.

**Comment by christopherthielen** [comment]
@samithaf  if you have a large number of states, registration is very slow in rc.1.  This is tracked as #3274 which is fixed in master and will be included in rc.2.

**Comment by christopherthielen** [comment]
I'll look into this before next release.  This perf regression is totally unacceptable.

**Comment by 29er** [comment]
thanks @christopherthielen !

**Comment by christopherthielen** [comment]
Closing in favor of https://github.com/angular-ui/ui-router/issues/3361

**Comment by samithaf** [comment]
@christopherthielen thanks for the confirmation.
