### ISSUE TITLE
Is passible to resolve other promise ? 

### ISSUE THREAD

**Issue by greatelv** [angular-ui/ui-router#3372]
My team has used ui router of 1.0.0-beta.3.
Is passible to resolve other promise ? (ex. bluebird promise, es6 promise)

**Comment by christopherthielen** [comment]
promises are "normalized" when you call `.resolve()`.  

If you have a bluebird promise, it can be normalized to an angular promise like:

```js
var bluebirdPromise = someApi.someCall();
var qPromise = $q.resolve(bluebirdPromise);
```

This works the other way too.


```js
var qPromise = $http.get('/foo.json');
var bluebirdPromise = Promise.resolve(qPromise);
```

Note that angular relies on promises being $q promises so the digest is handled properly

**Comment by greatelv** [comment]
Thanks. @christopherthielen
