### ISSUE TITLE
UI-Router 1.0: uiCanExit: de-register the callback

### ISSUE THREAD

**Issue by fabdeceglia** [angular-ui/ui-router#3373]
Hello everyone,

i am using Angular Ui-Router 1.0-RC1 and the new uiCanExit feature.

I created a wrapper of the functionality, with:

- a function that register a callback for the uiCanExit event of the current controller, by passing a function that return a promise (as suggested by the libray's doc)

- a function that de-register the callback, by setting to null the uiCanExit field of the current controller

The register function works fine, but the de-register function not.
The uiCanExit field of the controller is set to null, but every time that a try to load a new state the previous callback is executed.

Is there a way to de-register the event?

I posted the issue also on [stackoverflow](http://stackoverflow.com/questions/42766523/ui-router-1-0-uicanexit-de-register-the-callback) but no response at all.

**Comment by christopherthielen** [comment]
you shouldn't have to register or deregister the uiCanExit hook.  It's defined on your component's controller.  As long as the component is active, the uiCanExit hook will be called.

See the sample app's usage of `uiCanExit`: https://github.com/ui-router/sample-app-ng1/blob/8604ca2c7c7d5ac4db8ed3a96c1f3b8825b722dd/app/mymessages/compose.component.js#L23-L35
