### ISSUE TITLE
child states missing when lazy loading 

### ISSUE THREAD

**Issue by spyro92** [angular-ui/ui-router#3375]
This is a:

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.0-rc.1

# Bug Report

#### Current Behavior:

When lazy loading states, any states registered in modules that are dependencies to the module being lazy loaded will not be registered.

in the example: lazy.foo is being registered, but not lazy.bar

it seems to be a timing issue, if you remove the dependency on lazy.bar from the module 'lazy' the state will be registered.

#### Expected Behavior:

lazy.bar and lazy.foo should be registered

#### Link to Plunker that reproduces the issue:

http://plnkr.co/edit/IfxBMmsZgKVAyxSZ7w0g?p=info

**Comment by christopherthielen** [comment]
Thank you for the excellent bug report with plunker

**Comment by christopherthielen** [comment]
This is the same bug as https://github.com/ui-router/ng2/issues/40 and needs to be fixed in ui-router/core

**Comment by christopherthielen** [comment]
This issue was moved to ui-router/core#46

**Comment by christopherthielen** [comment]
http://plnkr.co/edit/yyiZWGpnRvmsiZdhyceP?p=preview

Fix coming soon.
