### ISSUE TITLE
caseInsensitive is not working

### ISSUE THREAD

**Issue by karensg** [angular-ui/ui-router#3379]
My version of UI-Router is: (version)
1.0 rc.1

# Bug Report

Hi @christopherthielen 

I think that the caseInsensitive flag is not working. I set it in my config block like:
```javascript
$urlServiceProvider.config.caseInsensitive(true);
``` 
--> no error

Then I check it in the app block and in the controller with:
```javascript
console.log($urlService.config.caseInsensitive());
```
 -> returns `true` twice

However, the case insensitivity in the url is not working. Other `$urlServiceProvider` options work fine.
```javascript
$urlServiceProvider.rules.sort(sortByRegistrationOrder);
$urlServiceProvider.rules.otherwise('404');
```

Setting it with the `$urlService` does not work either. Your help is very welcome.

**Comment by christopherthielen** [comment]
Seems to be working in plunker: http://plnkr.co/edit/H9i4VrRfHPkwxPyfMQyu?p=preview

**Comment by karensg** [comment]
Thanks! I will try to find out which particular settings break it and will add it to the plunker during the weekend.

**Comment by karensg** [comment]
I further looked in to it and realized that the function had to be called before the state definitions. My bad that I did not try it immediately. It also works with states whose urls are defined with regex. Very cool!
Thanks for your help!

**Comment by christopherthielen** [comment]
> the function had to be called before the state definitions

Ah.  I should add that to the docs!
