### ISSUE TITLE
Dynamic parameter value from service

### ISSUE THREAD

**Issue by HarpoMarx69** [angular-ui/ui-router#3380]
This is a:

- [ ] Bug Report
- [x] Feature Request
- [ ] General Query 

My version of UI-Router is:  v1.0.0-rc.1

# Feature Request
Hello,
I'm using v1.0.0-rc.1. In my project it would be a great advantage if value of state params could be fetched dynamically from a service.

```
.state('cashbox', {
	url: '/:date/:range',
	templateUrl: Routing.generate('cashbox_list'),
	controllerUrl: 'controllers/CashboxCtrl' + jsTag,
	controller: 'CashboxCtrl',
	controllerAs: 'mainCtrl',
	params: {
		date: [service that resolves to dynamic date]
	},
	resolve: {
		listData: [other service that needs $stateParam.date]
	}
})
```

This is needed because resulting URL should represent resulting params for deeplinking.
Thanks a lot.

**Comment by christopherthielen** [comment]
parameter values must be processed synchronously.  This is due to param values being integral to detecting if a state is being entered or exited.  However, you can probably use a transition hook to asynchronously redirect the transition to use the param values that you want.
