### ISSUE TITLE
Feature request: resolvable page title for each state

### ISSUE THREAD

**Issue by cadilhac** [angular-ui/ui-router#3384]
It would be great to define complex titles that would be reflected in browser history. They could depend on resolvables so that one can put data in the title, even when a param is dynamic.
Feasible?

**Comment by christopherthielen** [comment]
This should be easily done with a transition hook and the `data` property.

```js
{
  name: 'parent',  url: '/parent',  component: 'parent',
  data: { title: 'Some Parent Title' }
},
{ 
  name: 'parent.inheritTitle',  url: '/reuse',  component: 'inheritTitle'
},
{ 
  name: 'parent.childTitle', url: '/child', component: 'child',
  data: { title: 'Child title overrides parent' }
}
...

$transitions.onSuccess({ to: state => state.data.title != null }, transition => {
  document.title = transition.to().data.title;
});
```

**Comment by cadilhac** [comment]
This solution does not work.
1. The title you set this way goes on the previous element in the browser history.
2. With a static title put in 'data', I can't build a dynamic string based on resolvables
3. Note that your onSuccess should be for all transitions, otherwise the current title would remain for states that don't define a title.

**Comment by christopherthielen** [comment]
> The title you set this way goes on the previous element in the browser history.

Oh weird.  I'll reopen then.  

2 and 3 are left as exercise for the developer.  it's a transition hook, so it has access to everything a regular transition hook has including match criteria and resolve data.

**Comment by cadilhac** [comment]
I think that things are happening after the onSucess callback returns, that are necessary to make it work. I can solve this if I set the title inside a $timeout. Can we get rid of this workaround in some manner?
