### ISSUE TITLE
tfs issue with 1.0.0-rc.1

### ISSUE THREAD

**Issue by aline-almeida** [angular-ui/ui-router#3386]
This issue tracker is for Bug Reports and Feature Requests only.
Please direct requests for help to StackOverflow.  See http://bit.ly/UIR-SOF for details.

This is a:

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: (version)
1.0.0-rc.1

# Bug Report

#### Current Behavior:

installed ui.router with npm. Cannot add it to my project because TFS throws the following (although node_modules folder is set to be ignored in a .tfignore file):
```
TF10122: The path '$/$injector.d.ts' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$injector.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$injector.js.map' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$q.d.ts' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$q.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$q.js.map' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$injector.d.ts' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$injector.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$injector.js.map' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$q.d.ts' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$q.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$q.js.map' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$injector.d.ts' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$injector.d.ts' contains a '$' at the beginning of a path component. Remove the '$' and try again.
```

#### Expected Behavior:

add files without problems

#### Link to Plunker that reproduces the issue:
not applicable

# Feature Request

(feature request here)

# General Query

Please direct general implementation questions to StackOverflow: 
http://stackoverflow.com/questions/ask?tags=angularjs,angular-ui-router

Please review the Sample Application which highlights common approaches:
https://github.com/ui-router/sample-app-ng1

- [ ] I have already asked my question on StackOverflow and nobody could answer the question

- [ ] I have already reviewed the sample application for examples of common approaches

- [x] I believe my question can only be answered by the UI-Router maintainers

(general query here)

**Comment by christopherthielen** [comment]
Are you trying to commit the files from node_modules? 

I believe this is really a TFS issue and not a ui-router bug.  However, because it is trivial to rename those source  files in ui-router code, I will do that.

**Comment by aline-almeida** [comment]
Hi Christopher!
No, I'm not trying to commit those files. I have an ignore rule for them. Nonetheless, TFS doesn't let me include them on the project....
I realize it's a TFS limitation and I thank you for your quick response.
