### ISSUE TITLE
Reparse the page 

### ISSUE THREAD

**Issue by gurunadh5** [angular-ui/ui-router#3392]
This issue tracker is for Bug Reports and Feature Requests only.
Please direct requests for help to StackOverflow.  See http://bit.ly/UIR-SOF for details.

This is a:

- [ ] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: (version)

# Bug Report

#### Current Behavior:

(current behavior here)

#### Expected Behavior:

(expected behavior here)

#### Link to Plunker that reproduces the issue:

http://bit.ly/UIR-Plunk

# Feature Request

(feature request here)

# General Query

Please direct general implementation questions to StackOverflow: 
http://stackoverflow.com/questions/ask?tags=angularjs,angular-ui-router

Please review the Sample Application which highlights common approaches:
https://github.com/ui-router/sample-app-ng1

- [ ] I have already asked my question on StackOverflow and nobody could answer the question

- [ ] I have already reviewed the sample application for examples of common approaches

- [ ] I believe my question can only be answered by the UI-Router maintainers

(general query here)

**Comment by gurunadh5** [comment]
I want to add the trustpilot code for each page. But trustpilot is displaying in one page only. Trustpilot team said that problem with ui router. Ui router was not reparse the page. Please let me know how to resolve this issue.

Thanks

**Comment by christopherthielen** [comment]
In order to report a bug, you need to create a minimal reproduction of the issue. Please reproduce the issue in a Plunker:   http://bit.ly/UIR-Plunk
