### ISSUE TITLE
resolvePolicy async NOWAIT impacts synchronous resolve values

### ISSUE THREAD

**Issue by jeanbmar** [angular-ui/ui-router#3393]
This is a: Bug Report

My version of UI-Router is: 1.0.0-rc.1

# Bug Report

#### Current Behavior:

Synchronous values are not properly resolved when async NOWAIT is specified in  StateDeclaration.resolvePolicy property. It looks like post-resolve sync bindings are ~~undefined~~ managed as promises.
Async promises are properly passed to controller.
This is an issue when dealing with both async and sync bindings in a single controller.

Edit: passing a function will also break it.

#### Expected Behavior:

Sync values should be passed to controller.

#### Link to Plunker that reproduces the issue:

https://plnkr.co/edit/7g6tFR0ZU5dn4G6sWUl5?p=preview
Commenting async: 'NOWAIT' will produce the expected behavior.

Edit for broken functions: https://plnkr.co/edit/gCIHjuwVvkmusgXsVNs3?p=preview

**Comment by christopherthielen** [comment]
Thanks for the bug report and plunker!

I think this is a documentation issue. We should state that `NOWAIT` values are always wrapped in a promise.  In fact, during processing, *all resolves are always wrapped in promises* (using something like `$q.when(resolveValue)`, aka `Promise.resolve(resolveValue)`.  If you want unwrapped values injected, you should not use `NOWAIT`.  

Here's another discussion of the same issue: https://github.com/angular-ui/ui-router/issues/3378
