### ISSUE TITLE
$stateParams not behaving as expected

### ISSUE THREAD

**Issue by maurei** [angular-ui/ui-router#3396]
# Bug Report
My version of UI-Router is: 1.0.0-rc.1

When passing objects through `$stateParams`, attributes on arrays disappear. See plunkr.

I like to add functionality to arrays to be able to do stuff like `Blog.articles.add( {..})`. Currently this breaks.

I have tried to capture the objects in a closure in an attempt to preserve the attributes, which doesn't work:
`$state.go('after', {stuff: function(){return someStuff}})`
Binding to a function does:
`$state.go('after', {stuff: function(){return this}.bind(someStuff)})`

https://plnkr.co/edit/tkGHjpXlwiHUSswpyDMw?p=preview

**Comment by mattbrunetti** [comment]
@maurei Why aren't you using 1.0.0-rc.1 ?

**Comment by maurei** [comment]
@mattbrunetti actually I am, bad copy paste. My bad.

**Comment by maurei** [comment]
Just wondering, as there has been no reply; am I misunderstanding this part of UI router?
