### ISSUE TITLE
templateURL issue with 1.0.0-rc.1 (working with 0.4.2)

### ISSUE THREAD

**Issue by aline-almeida** [angular-ui/ui-router#3400]
This issue tracker is for Bug Reports and Feature Requests only.
Please direct requests for help to StackOverflow.  See http://bit.ly/UIR-SOF for details.

This is a:

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: (version)
1.0.0-rc.1

# Bug Report
TemplateURL is not working correctly when using it with adal.js . When using ui.router 0.4.2 it works fine.
Please see sample
[WebApp_ADAL_copy.zip](https://github.com/angular-ui/ui-router/files/902104/WebApp_ADAL_copy.zip)

#### Current Behavior:
doesn't load template and reports error:

> Error: [$compile:tpload] Failed to load template: /app/welcome.html (HTTP status: undefined undefined)
> http://errors.angularjs.org/1.6.3/$compile/tpload?p0=%2Fapp%2Fwelcome.html&p1=undefined&p2=undefined

#### Expected Behavior:

load template correctly

#### Link to Plunker that reproduces the issue:

# Feature Request
# General Query

Please direct general implementation questions to StackOverflow: 
http://stackoverflow.com/questions/ask?tags=angularjs,angular-ui-router

Please review the Sample Application which highlights common approaches:
https://github.com/ui-router/sample-app-ng1

- [ ] I have already asked my question on StackOverflow and nobody could answer the question

- [ ] I have already reviewed the sample application for examples of common approaches

- [x] I believe my question can only be answered by the UI-Router maintainers

(general query here)

**Comment by reneseses** [comment]
Same problem in v1.0.3

**Comment by aline-almeida** [comment]
Any news on this? It remains on 1.0.6 :(

**Comment by xingwen1987** [comment]
Same problem in v1.0.22
