### ISSUE TITLE
A state param seems wrongly propagated in another state when redirecting

### ISSUE THREAD

**Issue by cadilhac** [angular-ui/ui-router#3401]
Hi,

Seems like a bug to me.

Here is a state tree:
A -> B -> C
A -> D -> E
(A is the parent of B and D. B is parent of C. D is parent of E)

B has a param called 'tab'. D has also a param called 'tab'. In both cases, tab is visible in the url.
Current state is B and 'tab' is equal to string 'active' which is visible in the url.
I have a transition from B to C. But in C I have a redirectTo to E. Guess what? 'active' appears in the url once I am in state E.
We are in 2 different branches of a tree here. Even if some params have the same name, I guess that they should not propagate when we redirect to another branch.

**Comment by christopherthielen** [comment]
I think your perspective is valid (that the params are different and shouldn't be inherited, even though they share the same name).  However, this behavior is what I expect, and I suspect there are many apps which currently rely on the behavior.

**Comment by cadilhac** [comment]
ok... so, why not use a switch in the config to change behaviour, and it would be as you say by default.
Otherwise, let's say I have many tabs in different pages. I will have to number the params (tab1, tab2, ...). Oh did I use tab4 already? ;) And of course it's the same issue for any other params that could replicate.
