### ISSUE TITLE
$urlRouterProvider's when function has redirection problems in 1.0.0-rc.1 version

### ISSUE THREAD

**Issue by kotki** [angular-ui/ui-router#3402]
Found same issue as https://github.com/angular-ui/ui-router/issues/2496 in 1.0.0-rc.1 version
https://plnkr.co/edit/jUln1cUtwsQWpW9APTLC?p=preview

**Comment by testos944** [comment]
I have the same problem after updating to 1.0.0-rc.1, "when" does not seem to work properly

**Comment by kmaraz** [comment]
Any update on this issue? I can get it work in the Chrome by using $urlServiceProvider or in the other browsers using $urlRouterProvider but not in all browsers at the same time.
