### ISSUE TITLE
uiCanExit doesn't work as expected with ng-href and "return Promise.reject()"

### ISSUE THREAD

**Issue by weareoutman** [angular-ui/ui-router#3403]
This is a:

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.0-rc.1-artifacts (current master)

# Bug Report

#### Current Behavior:

`uiCanExit`:
- It works with `ui-sref` and `return Promise.reject()`.
- It works with `ng-href` and `return false`.
- It works incorrectly with `ng-href` and `return Promise.reject()`: the transition is canceled, but the current url changed.

#### Expected Behavior:

It should work with `ng-href` and `return Promise.reject()`.

#### Link to Plunker that reproduces the issue:

http://plnkr.co/edit/ObjiHM?p=preview

**Comment by dmitryevseev** [comment]
Seeing the same behaviour. For me it does not work with `ui-sref` and `return Promise.reject()`.
