### ISSUE TITLE
Using same child state for multiple parent states

### ISSUE THREAD

**Issue by shivanisaz** [angular-ui/ui-router#3405]
This query has been posted a lot of times at different places, however, no solution has been provided except that future versions may involve a solution. 

I have a child state that is same across multiple states.

    $stateProvider.state('app.user1.viewProfile1', {
        url: '/:profileURL',
        views: {
            'main@app.user': {
                component: 'profile'
            }
        }
    });
     $stateProvider.state('app.user2.viewProfile1', {
        url: '/:profileURL',
        views: {
            'main@app.user': {
                component: 'profile'
            }
        }
    });
     $stateProvider.state('app.user3.viewProfile1', {
        url: '/:profileURL',
        views: {
            'main@app.user': {
                component: 'profile'
            }
        }
    });

Is there a way to not replicate the viewProfile child and subsequent state definition, any way to append same child to multiple parents?

**Comment by rkingon** [comment]
Anytime you find yourself repeating yourself, there is likely a better way...

I would first suggest having only `app.user` and `app.user.profile` states, then have `:user` be a param...

To your question though, you could also drop states in a loop & iterate over the states.

```javascript
angular.forEach(["parent.state1","parent.state2","parent.state3"], function(parent) {
  $stateProvider.state(parent+".childState", {
      url: '/child',
      ...
  });
});
```

Take a shot at creating the states in a more "scaleable" way...
```javascript
$stateProvider.state("app.user", {
  abstract: true,
  url: "/:user"
});

$stateProvider.state("app.user.profile", {
  url: "/profile",
  views: {...}
});
```

Then to link...
```html
<a ui-sref="app.user.profile({user: 'user1'})">Link to user1</a>
```

And in your controller...
```javascript
var user = $stateParams.user;
```

**Comment by shivanisaz** [comment]
Hey! 
Sorry for a late reply, i implemented the loop approach and it worked perfectly !
Thank you so much !!
