### ISSUE TITLE
Add a way to check if a transition is going to be ignored

### ISSUE THREAD

**Issue by adamreisnz** [angular-ui/ui-router#3408]
This is a:

- [ ] Bug Report
- [x] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.0-rc.1

# Feature Request

I'm not sure if this is viable within the framework built around the new ui-router, but it would be helpful to me if there would be a way to find out if a transition is going to be ignored. In other words, if no transition is going to occur based on the requested `to` state and current `from` state. The most common case would be if the states are the same.

I need to know this in an `onBefore` hook, but I realize it's problematic as other hooks might potentially change the to state/transition.

Use case:

I have some open panels on my page, and when navigating away, I am doing an `onBefore` check to try and close the panels. These panels can either allow to be closed right away, which will allow the transition, or they might ask the user if they are sure they want to navigate away with unsaved changes and only allow the transition after that confirmation.

Now the problem I'm running in to is that this hook is called also when navigating to the same state, e.g. a user clicks on the path in the bread crumb. So what happens is that the panels get closed, but no actual state transition occurs.

You can see my dillema -- I kind of need to know _before_ transitioning if we're allowed to transition, but if we're going to be transitioning to the same state (e.g. the transition is going to be ignored), I need to abort that check altogether.

Current work around is simply to check `to.name === from.name`, but I was wondering if there's a more robust/elegant way.

**Comment by christopherthielen** [comment]
Have you seen this: https://ui-router.github.io/ng1/docs/latest/classes/transition.transition-1.html#ignored

**Comment by adamreisnz** [comment]
Sorry I missed that! It looks like it does exactly what I needed, although I'm still confused as to how it can work in an `onBefore` hook, if other hooks could potentially change the transition.

**Comment by christopherthielen** [comment]
@adamreisnz if another hook "changes" the transition, it's redirecting, which creates a *different* transition
