### ISSUE TITLE
General Query: RC2 release date

### ISSUE THREAD

**Issue by samithaf** [angular-ui/ui-router#3413]
This issue tracker is for Bug Reports and Feature Requests only.
Please direct requests for help to StackOverflow.  See http://bit.ly/UIR-SOF for details.

This is a:

- [ ] Bug Report
- [ ] Feature Request
- [ X] General Query 

My version of UI-Router is: (1.0.0-rc.1)
# General Query

- [ ] I have already asked my question on StackOverflow and nobody could answer the question

- [ ] I have already reviewed the sample application for examples of common approaches

- [x] I believe my question can only be answered by the UI-Router maintainers

Hi @christopherthielen currently I am using RC1 in a fairly large SPA. As you already know that there are couple of performance issues exits in RC1. We have a major release in 2 months time and just wondering that, are you planning to release RC2 in near future? Otherwise I can rollback to beta version which is fully compatible with RC1.

Thanks a lot.

**Comment by christopherthielen** [comment]
Next release will be 1.0.0 final, and I intend to release this weekend.

I just released `@uirouter/core` `@uirouter/angular` and `@uirouter/visualizer`.  `@uirouter/angularjs` is up next 👍 

_Note the npm package change_

**Comment by VAchris** [comment]
@christopherthielen release party this weekend!

**Comment by samithaf** [comment]
@christopherthielen that is a good news ;)

**Comment by christopherthielen** [comment]
All, I missed the release this weekend due to life getting in the way (I'm right in the middle of moving to San Jose).  Sorry, but hopefully I'll have time this week to push it out the door.

**Comment by christopherthielen** [comment]
1.0.0 final is released
