### ISSUE TITLE
named view not resolves component name

### ISSUE THREAD

**Issue by h6784rfg6** [angular-ui/ui-router#3415]
This is a: Bug Report
My version of UI-Router is: 0.4.2

# Bug Report
#### Current Behavior:

Named view does not resolve component using string component name like: "abc":

```
angular.module("test_web")
    .component("abc", new AbcComponent())
    .config(($stateProvider) => {
        "ngInject";
        $stateProvider
            .state("abc.details", {
                url: "/abc",
                views: {
                    "content@abc": "abc" // "abc" doesn't get resolved to component
                }
            });
    });
```

#### Expected Behavior:

Described here: [Link](https://ui-router.github.io/guide/ng1/route-to-component#named-viewsview-targeting)

and a work around from me:

```
angular.module("test_web")
    .component("abc", new AbcComponent())
    .config(($stateProvider) => {
        "ngInject";
        $stateProvider
            .state("abc.details", {
                url: "/abc",
                views: {
                    "content@abc": new AbcComponent() //the constructor of the component is called again
                }
            });
    });
```
BUT: the constructor of the component is been called twice. This is messy.

If I leave just `"abc"` I get:

> Uncaught Error: [$injector:modulerr] Failed to instantiate module test_web due to:
> TypeError: Cannot create property 'resolveAs' on string 'testfalldetails'

- I have already asked my question on StackOverflow and nobody could answer the question

- I have already reviewed the sample application for examples of common approaches

- I believe my question can only be answered by the UI-Router maintainers

**Comment by bebegreen** [comment]
head the same problem, worked around by: 
```
import AbcComponent from './path/to/abc.component.js'
angular.module("test_web")
    .component("abc", new AbcComponent())
    .config(($stateProvider) => {
        "ngInject";
        $stateProvider
            .state("abc.details", {
                url: "/abc",
                views: {
                    "content@abc": AbcComponent
                }
            });
    });```
