### ISSUE TITLE
[1.0] URL changes even though transition failed

### ISSUE THREAD

**Issue by adamreisnz** [angular-ui/ui-router#3416]
This is a:

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: **1.0.0-rc.1**

# Bug Report

#### Current Behavior:

I have a state which I am going to, which fails to load due to a rejected resolve (404).
This triggers the default error handler, and the user doesn't actually go to the page, but the URL **does** change to the (failed) state and the state is also remembered in the history, even though the user never got there.

#### Expected Behavior:

The URL should **not** change when a transition fails.

#### Link to Plunker that reproduces the issue:

http://plnkr.co/edit/zlIo6KSi4SDl7ZidTDRu?p=preview

As you can see, after clicking the test link, the URL changes, but the state remains on 404:

![image](https://cloud.githubusercontent.com/assets/490562/25554053/330c3fa8-2d18-11e7-8eb5-3e2d778ea5b7.png)

I have tried to redirect back to the "from" state that the user was coming from in the `onError` hook but this didn't work. Seems like a genuine bug.

**Comment by smhc** [comment]
I am hitting a similar issue in 1.0.
When 'uiCanExit' returns false the URL still changes. This happens when the URL is modified directly or via a bookmark. It doesn't happen when an attempt is made to change state via a ui-sref.

I think it is related to the fix in 1.0 for an issue I raised in 1.0-rc5.
https://github.com/angular-ui/ui-router/issues/3317

**Comment by dartzki** [comment]
I'm also stuck with this bug

Has anybody found a workaround?

**Comment by adamreisnz** [comment]
I haven't. This is affecting us in production, when users navigate to an item that is no longer there. This results in a 404 and the transition fails, showing them a modal, but then the URL does get added to their history so when they navigate back they are screwed.

Was hoping for @christopherthielen to shed some light on this

**Comment by abhijeetahuja** [comment]
for a workaround, you can do $location.path($stateParams.location); when you abort the transition to have the same url for the state, this even preserves the browser history.

**Comment by dartzki** [comment]
thanks for the hint, I got it to work with a slight alteration for the uiCanExit callback:
```typescript
public uiCanExit(transition: Transition) {
  this.$location.path(transition.$from().url.format(this.$transition$.params()));
  return return this.$q.reject();
}
````

it's using internal api (`$from()`), but it works for now as a workaround.

**Comment by christopherthielen** [comment]
@adamreisnz Here's a transition hook that might help:

When: 
- The transition was started due to a URL change
- The transition errored
Then:
- Reset the URL to the "from" state's URL

http://plnkr.co/edit/80i1fipx0aMXSrswu1Ot?p=preview

**Comment by adamreisnz** [comment]
That hook kind of works yes, thanks! 
It would be good to have this addressed in core though. When is milestone 1.5 expected to land?

**Comment by christopherthielen** [comment]
I can't say with any confidence when 1.5 will land.  I don't have as much time these days to devote to the ui-router projects.  I put this on the 1.5 milestone because it requires some research to determine how to support both back buttons and hrefs.  One particular blocker I have with this bug is how to reliably detect that the back button was pressed when we handle URL changes.

**Comment by adamreisnz** [comment]
The [popstate](https://developer.mozilla.org/en-US/docs/Web/Events/popstate) event should help with that pretty reliably:

> Note that just calling history.pushState() or history.replaceState() won't trigger a popstate event. The popstate event will be triggered by doing a browser action such as a click on the back or forward button (or calling history.back() or history.forward() in JavaScript).

**Comment by christopherthielen** [comment]
If you can figure out how to distinguish between:

- forward button
- back button
- href navigation

Then I can code up a permanent fix for this issue

**Comment by adamreisnz** [comment]
Had a quick look, but it looks like the popstate event is also fired for regular navigation. Not sure if that's caused by ui-router, angular's location service or plunkr. Will see if I can find more.

**Comment by adamreisnz** [comment]
This is still an issue that is affecting us badly.

When a user is logged out, they are sent back to the login page.

If the user then navigates "back" in their browser, the URL changes to whatever their previous page was, despite UI router not taking them there and staying on the login page.
