### ISSUE TITLE
[docs] Menu appears below page content

### ISSUE THREAD

**Issue by adamreisnz** [angular-ui/ui-router#3422]
This is a:

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

See for example https://ui-router.github.io/ng1/docs/latest/modules/transition.html

The menu on this page is displayed at the bottom of the page, after the page contents, instead of next to it:

![image](https://cloud.githubusercontent.com/assets/490562/25644483/906bb3d8-2ffa-11e7-83d2-b2e191b82337.png)

This also happens on other pages, like the state page. Didn't use to happen a while ago.
This page is not affected: https://ui-router.github.io/ng1/docs/latest/classes/state.state-1.html

Using Chrome latest on OS X, on a normal width window.

**Comment by gigadie** [comment]
inverting the order of the two divs make the menu 
```
<div class="row">
    <div class="col-4 col-menu menu-sticky-wrap menu-highlight sticky">...</div>
    <div class="col-8 col-content">...</div>
</div>
```

how can this be related to ui-router?

**Comment by adamreisnz** [comment]
> how can this be related to ui-router?

It's the ui-router docs, isn't it ;)
