### ISSUE TITLE
TemplateFactory.prototype.makeComponentTemplate breaks component-name-based CSS styling

### ISSUE THREAD

**Issue by rafaelhamasaki** [angular-ui/ui-router#3423]
This is a:

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.0

# Bug Report

#### Current Behavior:

When routing to components, the constructed templates are prefixed with "x-". As such, stylings that rely on component names break. I.e: `my-component { color: red; }` won't apply to `<my-component />` because it's been renamed to `<x-my-component />`.

#### Expected Behavior:

The component should not be renamed so that styles apply as expected.

#### Link to Plunker that reproduces the issue:

https://plnkr.co/edit/NKTlKYBCtKG6xg0Oqsgd?p=preview

**Comment by christopherthielen** [comment]
After thinking about this for a bit, I think we should prefix with `x-` only when the component name starts with `x-` or `data-`

**Comment by christopherthielen** [comment]
Closed by https://github.com/angular-ui/ui-router/commit/60b9ef923c701c831c66a145ebae36039782cf68
