### ISSUE TITLE
Add flag to disable 'x-' prefix prepended in makeComponentTemplate

### ISSUE THREAD

**Issue by jordandh** [angular-ui/ui-router#3424]
This is a: Feature Request

My version of UI-Router is: 1.0.0

# Feature Request

Add a flag to disable the 'x-' prefix that is prepended to component elements in makeComponentTemplate. Adding the prefix can interfere with css and dom selectors. Adding a way to opt out of or into using the prefix will make it possible to workaround the problem.

This issue referenced in https://github.com/angular-ui/ui-router/issues/3276

**Comment by CarterLi** [comment]
This flag should be able to be configured globally 👍

**Comment by christopherthielen** [comment]
This will be fixed by https://github.com/angular-ui/ui-router/commit/60b9ef923c701c831c66a145ebae36039782cf68 in 1.0.1
We will only prefixing if the component name requires the prefix (it is named `xFoo` or `dataFoo`)

**Comment by jordandh** [comment]
Thanks for the quick turnaround @christopherthielen. I tried 1.0.1 and the element names are indeed without the 'x-' prefix again. However, the attribute names are still being prefixed with 'x-'. Would it be possible to only add the prefix to the attributes when the component name requires it as well?

**Comment by christopherthielen** [comment]
@jordandh yeah I suppose that would make sense

**Comment by Remco75** [comment]
Ha, I ran into this as well: when will 1.0.1 be available through npm?

**Comment by christopherthielen** [comment]
1.0.1 was released last week.  Note the package changed to `@uirouter/angularjs`: https://unpkg.com/@uirouter/angularjs@1.0.1/

**Comment by christopherthielen** [comment]
@Remco75 1.0.1 was released last week.  Note the npm package changed to scoped package `@uirouter/angularjs` https://github.com/angular-ui/ui-router/issues/3424

Read more: https://ui-router.github.io/blog/uirouter-scoped-packages/

**Comment by Remco75** [comment]
thnx man, great work as usual. I think npm registry cache got the better of me, it wasn't there yet when I checked ;-)
