### ISSUE TITLE
$state.go delay $locationChangeStart  

### ISSUE THREAD

**Issue by frlinw** [angular-ui/ui-router#3427]
This is a:

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: tested on 0.4.2 & 1.0.0

# Bug Report

#### Current Behavior:

When $state.go is called the target url's controller is processed before $locationChangeStart event

#### Expected Behavior:

$locationChangeStart event should be triggered before the processing of the target url controller

**Comment by lnu** [comment]
What did you do in the end?
