### ISSUE TITLE
How to access scope of target state with 1.0?

### ISSUE THREAD

**Issue by seiyata** [angular-ui/ui-router#3429]
In previous version, scope of target state can be accessed through event object like:

```
$rootScope.$on('$stateChangeSuccess', function(event) {
  var scope = event.targetScope;
});
```

Now $stateChangeSuccess is deprecated and recommended to use onSuccess:

```
$transitions.onSuccess({}, function(transition) {
  var scope = ???
});
```

How can I access scope?

**Comment by fedealconada** [comment]
@seiyata have you found out how to do this?

**Comment by FritzHerbers** [comment]
I think you have something similar like I have, watching for $viewContentLoaded:
`
$rootScope.$on('$stateChangeSuccess', function (event, toState) {
    event.targetScope.$watch('$viewContentLoaded', function () {
`
$viewContentLoaded is emitted on the viewScope, and can be captured by the viewScope, its parents up to the $rootScope.

I use the following for the moment:
`
$transitions.onSuccess({}, function (transition) {
     $rootScope.$watch('$viewContentLoaded', function () { 
`

@devs
Is it possible to implement a pointer to the scope created in the transition?

**Comment by seiyata** [comment]
@fedealconada Not yet, I re-enabled $stateChangeSuccess according to https://ui-router.github.io/ng1/docs/latest/modules/ng1_state_events.html for now.

**Comment by seiyata** [comment]
Thanks @FritzHerbers .

```
$rootScope.$watch('$viewContentLoaded', function () {
```

worked on my app. Next is how to access "scope" of the view...

**Comment by christopherthielen** [comment]
> Is it possible to implement a pointer to the scope created in the transition?


Sorry, no, there's no access to scope in 1.0.

What exactly are you accomplishing by accessing scope?  There is probably a different approach that would work

**Comment by seiyata** [comment]
I'm using $stateChangeSuccess event to propagate a message from one controller to another.

```
// Propagate flash message from previous page
var message = FlashService.getMessage();
if (message !== undefined) {
  event.targetScope.alerts.push(message);
}
```

This is useful when I want to display message like "xxxxx registration completed!" after redirecting from registration page, thought not sure this is good manner...

**Comment by blahblehblah** [comment]
> if (message !== undefined) {
  event.targetScope.alerts.push(message);
}

Why don't you create a service and push alerts through it?

**Comment by Assem-Hafez** [comment]
any updates about this?
i need to interpolate some string with the state scope
