### ISSUE TITLE
Transition object from $transitions.onStart does not have documented functions

### ISSUE THREAD

**Issue by Burtan** [angular-ui/ui-router#3430]
This is a:

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.3

# Bug Report

#### Current Behavior:
Transition object misses functions described in documentation, like $to
Internal parameters like _targetState can be accessed to get relevant information, but I guess that is not the way to go.
![transition object](https://cloud.githubusercontent.com/assets/3275473/25800484/d8cb5d48-33e9-11e7-93eb-77d564c95b4e.png)

#### Expected Behavior:
Behaviour as documented

**Comment by christopherthielen** [comment]
Those functions are there; they are on the object prototype. In your screenshot, expand the  __proto__ property

**Comment by Burtan** [comment]
Ah, my bad. Thanks
