### ISSUE TITLE
Change url with no controller reload

### ISSUE THREAD

**Issue by jRichardeau** [angular-ui/ui-router#3436]
This is a:
- [x] General Query 

My version of UI-Router is: 1.0.0-rc1
# General Query

- [x] I have already asked my question on StackOverflow and nobody could answer the question

- [x] I have already reviewed the sample application for examples of common approaches

- [x] I believe my question can only be answered by the UI-Router maintainers

I want to change the browser url without reloading states, to do so I tried this :

`$state.transitionTo($state.$current.name, {param1: "value"}, {

                location: true,
                inherit: true,
                relative: $state.$current,
                reload: false,
                //Seems to be deprecated...
                notify: false
            });`

I just want to change the _param1_ value in url, but _transitionTo_ reloads my current state and so destroy and re-create my controller.

I previously worked with ui-router 0.x and the notify parameter worked for that.

How can I do this with ui-router 1.0.x ?

Thank you !

**Comment by Anber** [comment]
You should define the parameter as a dynamic. https://ui-router.github.io/ng1/docs/latest/interfaces/params.paramdeclaration.html#dynamic

**Comment by jRichardeau** [comment]
That's exactly what I was looking for, thank you very much !
