### ISSUE TITLE
Dynamic parameter interferes with URL reload logic

### ISSUE THREAD

**Issue by FritzHerbers** [angular-ui/ui-router#3437]
- [X] Bug Report

My version of UI-Router is: 1.0.3

# Bug Report

#### Current Behavior:

Having the following definition:
```
  .state('app.order', {
    url: '/order/:id',
    params: {
      id: { value: null, dynamic: true }
  },
```

Using the following code to set the URL to the newly created order id:
```
  $state.go('.', {
     id: someID
  }, { reload: false });
```

Which works for updating the URL in the controller, but now changes to the URL (changing the order id manually) are successfull transitions, but the controller is not reloaded anymore.

With ui-router < 1.0.0 we had the notify=false option and all was fine. Now with dynamic=true we miss the differentiation between a controller and a human action.

#### Expected Behavior:

Having a differentiation between a controller and a human action.

**Comment by christopherthielen** [comment]
Hi,
I'm sorry you miss `notify: false`, but it was a very very broken approach and wreaked havoc with the state machine, causing undefined behavior.  If your primary concern is determining what triggered a Transition, try the (currently internal api): https://ui-router.github.io/ng1/docs/latest/interfaces/transition.transitionoptions.html#source

```
transition.options().source
```

This will return one of `"sref" | "url" | "redirect" | "otherwise" | "unknown"`

Calls to `$state.go()` will be set to `unknown`


(this API is subject to change)


Hope this helps

**Comment by FritzHerbers** [comment]
@christopherthielen 
Sorry not to be clear enough. Not me having a way to determine an URL change but ui-router be able to differentiate between an URL change in a controller ($state.go without Controller reload) and a human browser URL change.

How do I configure ui-router and use $state.go in a Controller to just change an URL (update new orderId), without Controller reload and having a Controller reload when the user provides a new URL with another orderId?

**Comment by christopherthielen** [comment]
Use a transition hook
```
$transitions.onStart({ to: 'app.order', from: 'app.order' }, function ($transition$) {
  var options = $transition$.options();
  var params = $transition$.params();
  if (options.source === 'url' && options.reload === false) {
    var newopts = Object.assign({}, options, { reload: true });
    return $transition$.router.stateService.target('ap.order', params, newopts);
  }
});
```

**Comment by FritzHerbers** [comment]
@christopherthielen 
thx for the snippet.

With the transition hook an explicit reload is requested, therefor the parent states (app) are reloaded and resolves are executed, which is unwanted.
When the URL is manually changed from one state (app.overview) to the other (app.order) no parent state reload and resolves are executed.

Is there a way to have the same behaviour, not reloading the parent?

**Comment by christopherthielen** [comment]
@FritzHerbers If you only want to reload the `app.order` state (and not its parent(s)) use `reload: 'app.orders'`

https://ui-router.github.io/ng1/docs/latest/interfaces/transition.transitionoptions.html#reload
