### ISSUE TITLE
1.0.3 Upgrade from 1.0.0-rc1 creates angular.js:38 Uncaught Error: [$injector:modulerr] 

### ISSUE THREAD

**Issue by f1tech** [angular-ui/ui-router#3438]
Bug Report

My version of UI-Router is: 1.0.3

# Bug Report
1.0.3 Upgrade from 1.0.0-rc1 creates angular.js:38 Uncaught Error: [$injector:modulerr] 

#### Current Behavior:

This morning I replaced UI-Router 1.0.0-rc1 with UI-Router 1.0.3, when I attempt to start my app I receive this error: 

Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.6.4/$injector/modulerr?p0=FTPOrdersApp&p1=Err…oogleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.6.4%2Fangular.min.js%3A42%3A64)

Following the link above displays this:

Failed to instantiate module FTPOrdersApp due to:
Error: State 'customers.customer' has a 'views' object. It cannot also have "view properties" at the state level.  Move the following properties into a view (in the 'views' object):  component
    at mt (https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/1.0.3/angular-ui-router.min.js:11:11745)
    at https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/1.0.3/angular-ui-router.min.js:12:21383
    at t.build (https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/1.0.3/angular-ui-router.min.js:12:21400)
    at t.flush (https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/1.0.3/angular-ui-router.min.js:12:23547)
    at t.register (https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/1.0.3/angular-ui-router.min.js:12:23333)
    at t.register (https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/1.0.3/angular-ui-router.min.js:12:24933)
    at t.state (https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/1.0.3/angular-ui-router.min.js:14:2211)
    at angular.module.config (http://localhost/FTPOrdersoDataService/client/components/customer/customer.state.js:14:14)
    at Object.invoke (https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js:44:171)
    at d (https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js:42:64

This is the code that contains causes the error: 

```
/* customer.state.js */
(function () {
    'use strict'
    angular.module('FTPOrdersApp').config(($stateProvider) => {
        $stateProvider
            .state('customers', {
                url: "/customers",
                component: "customer",
                role: "customers",
                resolve: {
                    ilsList: function (ezo) { return getIlsList(ezo) },
                    list: function (ezo, notification) { return getCustomerList(ezo, notification) }
                }
            })
            .state('customers.customer', {
                url: "/{customerId}",
                component: "customer",
                role: "customers - edit",
                views: { "customerdetail": { templateUrl: "components/customer/customerSetup.html" } },
            })
            .state('customers.customer.generalinfo', {
                url: "/generalinfo",
                role: "customers - edit",
                views: { "customergeneralinfo": { templateUrl: "components/customer/customerGeneralInfo.html" } },
            })
            .state('customers.customer.acknowledgements', {
                url: "/acknowledgements",
                role: "customers - edit",
                views: { "customeracknowledgements": { templateUrl: "components/customer/customerAcknowledgements.html" } },
            })
            .state('customers.customer.importinstructions', {
                url: "/importinstructions",
                role: "customers - edit",
                views: { "customerImportInstructions": { templateUrl: "components/customer/customerImportInstructions.html" } }
            })
            .state('customers.customer.history', {
                url: "/orderhistory",
                role: "customers - edit",
                views: { "customerHistory": { templateUrl: "components/customer/customerOrderHistory.html" } }
            })
            .state('customerhistory', {
                url: "customers/{ID}/orderhistory",
                role: "customers - edit",
                views: { "customerHistory": { templateUrl: "components/customer/customerOrderHistory.html" } }
            })
        function getIlsList(ezo) {
            return ezo.getEntity("ILS").then((entity) => {
                return entity.list({
                    orderBy: 'NAME',
                    select: "ID,NAME,SUPPORTED"
                })
            })
        }
        function getCustomerList(ezo, notification) {
            notification.working = true
            var customerFieldList = {
                select: "ID,SAPID,MSTRSAPID,CUSTNO,ACCOUNT,ACTIVE,ILS_ID,DOCTYPE",
                expand: "CUSTOMER_MASTER($select=MSTRNAME),CUSTOMER($select=NAME;$expand=COUNTRY($select=SALES_ORG)),ILS($select=NAME)"
            }
            return ezo.getEntity("EDI_CUSTOMER").then((entity) => {
                return entity.list(customerFieldList).then((list) => {
                    notification.working = false
                    return list
                })
            })
        }
    })
})()

```
Commenting out the customers.customer state eliminates the error, but then none of my customer routes are navigable. 

#### Expected Behavior:

I expected all of my customer.customer routes to work as they previously did without error.

**Comment by christopherthielen** [comment]
The error message `Move the following properties into a view (in the 'views' object): component` tells how to resolve this.  In your state you have the following:
```
            .state('customers.customer', {
                url: "/{customerId}",
                component: "customer",
                role: "customers - edit",
                views: { "customerdetail": { templateUrl: "components/customer/customerSetup.html" } },
            })
```
You cannot mix a `views: {}` object with other view-related properties at the state level (such as `component:`).  

I see that you already have the `customer` component on the parent state.   Remove the `component: "customer",` line and it should work.

**Comment by f1tech** [comment]
Thank you. You are indeed correct.
