### ISSUE TITLE
Cleaning URL query params breaks routing

### ISSUE THREAD

**Issue by SuperOleg39** [angular-ui/ui-router#3439]
This issue tracker is for Bug Reports and Feature Requests only.
Please direct requests for help to StackOverflow.  See http://bit.ly/UIR-SOF for details.

This is a:

- [ ] Bug Report

My version of UI-Router is: 1.0.3

# Bug Report

#### Current Behavior:

I have a routes like `this:`

`
{
'admin': {
  template: '...'
},
'home': {
  parent: 'admin',
  url: '/',
  template: '...'
},
'orders': {
  parent: 'admin',
  url: '/orders',
  template: '...'
}
}
`

And my project url (dev for exapmle)  -  https://localhost:9000

After i open site with query params  -  https://localhost:9000?token=12345  -  get params and clear it:
`$location.url($location.path());`

Them ui-router stop to change views, change only url.

In ui-router source code:
matchingConfigs in ViewService.sync return always array of 'home' and next route (orders for example), then matchingConfigPair return only 'home'.

And i have only home component on every routes.

#### Expected Behavior:

I know, change url without ui-router is a bad idea, maybe i can get query params on all page and clear it simply and without state change?

# General Query

- [ ] I believe my question can only be answered by the UI-Router maintainers

**Comment by SuperOleg39** [comment]
When i clear query params inside setTimeout, router works fine.

```
setTimeout(() => {
  $location.search({});
});
```

**Comment by christopherthielen** [comment]
If this `tokenId` is a one time process, you can use a transition hook to process the token and then clear it out.

```
$transitions.onBefore({}, function($transition$) {
  var params = $transition$.params();
  if (params.tokenId) {
    // perform token processing
    TokenService.process(tokenId).then(function(result) {
      var tostate = $transition$.to();
      var params = angular.extend({}, $transition$.params());
      var options = $transition$.options();
      delete params.tokenId
      return $state.target(tostate, params, options);
    });
  }
});
```

Either way it sounds like you have a workaround, so closing?

**Comment by SuperOleg39** [comment]
Thx, i dont't know what `$state.target` clear address bar :)

But router behavior still strange.

**Comment by christopherthielen** [comment]
As of [`@uirouter/core@5.0.8`](https://github.com/ui-router/core/releases/tag/5.0.8) and [`@uirouter/angularjs@1.0.7`](https://github.com/angular-ui/ui-router/releases/tag/1.0.7) you can simplify this redirect logic using the factory methods on `TargetState`.


```js
$transitions.onBefore({}, function($transition$) {
  if ($transition$.params().tokenId) {
    // perform token processing then redirect without tokenid
    TokenService.process($transition$.params().tokenId).then(function(result) {
      return trans.targetState().withParams({ tokenid: undefined });
    });
  }
});
```
