### ISSUE TITLE
View targeting results in 404 for templateUrls

### ISSUE THREAD

**Issue by webdobe** [angular-ui/ui-router#3440]
Hello!  I am running into an issue that seems to be a bug, if not my apologies.

I have a $stateProvider config that looks like this (this is stripped down a bit).

```
$stateProvider
.state('home', {
        url: '/',
        templateUrl: 'views/splash.html',
        controller: function($scope, $state, User){
          if (User.current.uid > 0 && $state.is('home')) {
            $state.go("projects");
          }
        },
        resolve: {
          'User': function(User) {
            return User.init();
          }
        },
				ncyBreadcrumb: {
					label: 'Projects'
				}
      })
      // Projects
      .state('projects', {
        url: '^/',
        templateUrl: 'views/projects.html',
        controller: 'ProjectsCtrl as Projects',
				ncyBreadcrumb: {
					label: 'Projects'
				}
      })
.state('project.objectives', {
				url: '/objectives',
				views: {
					'': { templateUrl: 'views/project/layouts/content.html', controller: 'ObjectivesCtrl as Objectives' },
					'contentHeader@project.objectives': { templateUrl: 'views/project/objectives/objectives-header.html'},
					'contentBody@project.objectives': { templateUrl: 'views/project/layouts/burr.html'},
					'contentList@project.objectives': { templateUrl: 'views/project/objectives/objectives-content-list.html'},
				},
				ncyBreadcrumb: {
					parent: 'project',
					label: 'Objectives'
				}
			});
```

The issue is that all files that are using view targeting or "contentHeader@project.objectives" for example are getting 404's these configurations work on my local dev but seem to break when existing in a subdirectory on the server.

I have included the base meta tag and made it html5 but no dice.

When viewing states that do not use view targeting everything works fine.  So I feel like there may be a bug with view targeting and using subdirectories or something?  It may also be nginx on the server as well but since these files are served through a compiled vendor.js file I find that maybe nginx has nothing to do with it.

Any other ideas would be much appreciated!  Thank you!

**Comment by webdobe** [comment]
The 404 file is pointing at an absolute path.  Does view targeting force absolute?  Whereas the other paths are relative?

**Comment by yojlucas** [comment]
Hi. I am following. I am a student and I am having exact same problem.

**Comment by christopherthielen** [comment]
> Does view targeting force absolute? Whereas the other paths are relative?

@webdobe view targeting does not change the templateUrl handling.  In fact, "under the hood" all views use view targeting, even the ones that you declare on the state level.

> since these files are served through a compiled vendor.js file

Does your build bundle your HTML and load the templateCache with them?  Are you using something like webpack and `require()`? Or are you fetching the HTML from the templateUrls at runtime using HTTP (the most basic/standard method of fetching templates)?

> The 404 file is pointing at an absolute path. 

Can you post examples of the GET request made for `templateUrl: 'views/splash.html',` compared to the GET request made for `'contentHeader@project.objectives': { templateUrl: 'views/project/objectives/objectives-header.html'},`

**Comment by webdobe** [comment]
Well sorry, these templates reside in a compiled scripts.js not vendor lol.  But that file contains like all my template files with lines like this:

a.put("views/account/settings.html",'<div class="container-fluid"> <header> <h1><i class="fa fa-cog"></i> Settings</h1> </header> <p>This is the settings view for a user account.</p> </div>'),

with a.put giving the first arg as relative path to the template and then the contents of that template in the second arg.

That same syntax is used for every template file.  No matter if I am view targeting or not.  Which is why it is weird that one works and the other does not.

The only place I am declaring these paths are in the $stateProvider.  The files before compile are in regular html files in the directory structure. 

The more I am thinking about this it probably has everything thing to do with nginx.

**Comment by christopherthielen** [comment]
```
a.put("views/account/settings.html",'<div class="container-fluid"> <header> <h1><i class="fa fa-cog"></i> Settings</h1> </header> <p>This is the settings view for a user account.</p> </div>'),
```
If this is inside your bundle, I think you have a plugin which takes the HTML and adds it to the `$templateCache` (https://docs.angularjs.org/api/ng/service/$templateCache).  Something like this: https://github.com/teux/ng-cache-loader

This should be fine because ui-router implicitly uses the template cache. 

I suggest you look into your build setup.  Turn of minification, rebuild, then debug the portion that fetches templates.

https://github.com/angular-ui/ui-router/blob/f122d788f24f4e2281c8e50b2bd4db5c66138b73/src/templateFactory.ts#L45-L59

**Comment by webdobe** [comment]
Yes so I modified my grunt file to not do:

    ```
ngtemplates: {
      dist: {
        options: {
          module: 'iatfApp',
          htmlmin: '<%= htmlmin.dist.options %>',
          usemin: 'scripts/scripts.js'
        },
        cwd: '<%= yeoman.app %>',
        src: 'views/{,*/}*.html',
        dest: '.tmp/templateCache.js'
      }
    },
```
and copied the views directory over and now the files are getting found.  So whate would you suggest is the likely issue? Is it with ngtemplates?

**Comment by jrbuckeridge** [comment]
@webdobe were you able to figure this one out? I'm running into this issue and haven't been able to find the root cause yet.
