### ISSUE TITLE
Lack of documentation for testing $transitions

### ISSUE THREAD

**Issue by mindmelting** [angular-ui/ui-router#3441]
This is a:

- [ ] Bug Report
- [ ] Feature Request
- [x] General Query 

My version of UI-Router is: 1.0.3 (Angular 1.6)

# General Query

- [x] I have already asked my question on StackOverflow and nobody could answer the question
- [x] I have already reviewed the sample application for examples of common approaches
- [x] I believe my question can only be answered by the UI-Router maintainers

There is a general lack of documentation on testing the new $transitions changes.

I am looking to test that the $transitions.onStart function is called inside my module run block.

I have tried to mock $transitions but to no avail. What is the general approach that should be taken here?

Thanks

**Comment by mindmelting** [comment]
I figured this out, I was mocking and injecting incorrectly.

**Comment by aearanky** [comment]
@mindmelting Can you show an example for mocking and injecting $transitions please?
