### ISSUE TITLE
Transitions with HTTP Errors

### ISSUE THREAD

**Issue by JakeAi** [angular-ui/ui-router#3443]
I'm having an issue with loading partials that have 404/401/500 error codes. If I catch the error in the template provider, UI-Router deems it as a $transitions.onSuccess(). I still need to render the partials even though they are 404 or 401. Which is why they are returned in the catch using a scriptloader (this looks for embedded script tags and loads them with the partial). If I remove the .catch in the template provider than the $transitions.onError() fires but the partial doesn't load. I was using a hacky $broadcast but the $transition gets fired on normal $http requests and anything caught with a 404 becomes a success. Any ideas? I was going to use everything as a success and handle it there but the success event doesn't have http status code with it. 

```
 var templateProvider = ['$http', '$stateParams', '$state', 'scriptLoader', '$q', function ($http, $stateParams, $state, scriptLoader, $q) {
            var url = '';
            if ($stateParams.path == null) {
                url = "Home";
            } else {
                url =
                    ($stateParams.path && $stateParams.path || "") +
                    ($stateParams.folder && $stateParams.folder || "") +
                    ($stateParams.app && "/" + $stateParams.app || "") +
                    ($stateParams.page && "/" + $stateParams.page || "") +
                    ($stateParams.q && "?q=" + $stateParams.q || "");
            }
            return $http({
                method: 'GET',
                url: url,
                headers: {
                    'x-Partial-Request': true
                },
            }).then(function (responseData) {
                return scriptLoader.loadScriptTagsFromData(responseData.data);
            }).catch(function (responseData) {
                return scriptLoader.loadScriptTagsFromData(responseData.data);
            }).finally(function (responseData) {
                return responseData;
            });
        }];
```

```
MM.run(['$rootScope', '$transitions', 'AuthFactory', function ($rootScope, $transitions, AuthFactory) {

    $transitions.onSuccess({}, function ($transitions$) {
        document.body.scrollTop = document.documentElement.scrollTop = 0
    });

    $rootScope.$on('status-code', function (broadcast, data) {
        switch (data) {
            case 401:
                AuthFactory.Reset();
                break;
            default:
                break;
        }
        console.log(broadcast, data);
    });
    $transitions.onError({}, function ($transitions$) {
        console.log("error", $transitions$._error.status);
    });
}]);
```

**Comment by JakeAi** [comment]
I feel like since I am returning HTML in the catch of templateprovider it is becoming a success?

**Comment by christopherthielen** [comment]
> I feel like since I am returning HTML in the catch of templateprovider it is becoming a success?


Yes, we wait for the promise to fetch the template, then continue the transition.  If the promise resolves successfully, we use that as the template.  If the promise is rejected, we reject the transition (and thus call `onError`)

---

It's not clear to me what your code means to do.

> I still need to render the partials even though they are 404 or 401. Which is why they are returned in the catch using a scriptloader (this looks for embedded script tags and loads them with the partial)

Why do you want the transition to error if the (fallback?) partial succeded.  If the transition errors, then the state does not get activated in any way.
