### ISSUE TITLE
Make urls without `#` work

### ISSUE THREAD

**Issue by chengtie** [angular-ui/ui-router#3444]
Hello,

I have developed a mean-stack application. In development, I use `apache2` in mac OS; In production I use `nginx`.

At the moment, `https://localhost:3000/#/home` (ie, development) and `https://www.myapp.io/#/home` (ie, production) work with `#`. Then, I set html5Mode is true, as a result, `https://localhost:3000/#/home` becomes `https://localhost:3000/home` and `https://www.myapp.io/#/home` becomes `https://www.myapp.io/home`. They all work for the first time, but reloading `https://localhost:3000/home` or  `https://www.myapp.io/home` does NOT work.

So I try to follow [this thread](https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-your-server-to-work-with-html5mode), what I don't understand is, I should configure just `express rewrites`, or just `apache rewrites` / `nginx rewrites`, or `express rewrites` + `apache rewrites`/`nginx rewrites`? The FAQ is not very clear.

I tried the provided code for almost all the combination, it does not seem to work. What should I do? Should I try to configure a `.htaccess`?

Thanks

Tie

**Comment by JakeAi** [comment]
I'm using codeigniter 4, with html5mode on apache. I have a rewrite to the root dir of the project. In the <head> I have
```
<meta name="fragment" content="!">
<base href="/">
```

**Comment by christopherthielen** [comment]
The server side rewrites are documented for each server.  We provide the FAQ as a convenience, but you may want to check with your individual server documentation.

apache, nginx, and express are all separate web servers.  It doesn't sound like you're using express at all.

If you're hosting the app using apache, then you use the apache rewrite rules.  If you're hosting the app using nginx then you use the nginx rewrite rules.  You must configure each server separately.


For further troubleshooting, please ask the huge community at StackOverflow: http://bit.ly/UIR-SOF

Thanks for using ui-router!
