### ISSUE TITLE
Cordova Application

### ISSUE THREAD

**Issue by Brenw10** [angular-ui/ui-router#3445]
Hi Everyone !

I'm building a Cordova Application using Phonegap. So, I'm using ui-router, but it is not working.
If a build it and run on mobile it's not working. However, if a run it using my apache server it's working fine.
Can someone here help to solve that?
Here is my repository: https://github.com/Brenw10/Cordova-Angular

Thanks for All :)

**Comment by christopherthielen** [comment]
Hi Brenw10, thanks for using UI-Router

Unfortunately, this issue tracker is reserved for bug reports and feature requests only.  I suggest asking your question to the enormous community at StackOverflow.  

http://UIR-SOF
