### ISSUE TITLE
onError Transition Hook cannot continue when returned a TransitionState

### ISSUE THREAD

**Issue by sean-stanley** [angular-ui/ui-router#3446]
This issue tracker is for Bug Reports and Feature Requests only.
Please direct requests for help to StackOverflow.  See http://bit.ly/UIR-SOF for details.

This is a:

- [1 ] Bug Report

My version of UI-Router is: 1.0.3

# Bug Report

#### Current Behavior:

When returning a transition.target object from the onError transition hook, the target is not transitioned to.

#### Expected Behavior:

returning a transition.target object from any transition hook should transition to that target.

#### Link to Plunker that reproduces the issue:

[https://plnkr.co/edit/FILx0kLzPPhfWzXROuAZ](https://plnkr.co/edit/FILx0kLzPPhfWzXROuAZ)

Thanks for the awesome work on this package everyone.

**Comment by christopherthielen** [comment]
Thanks for the plunker!

The `onError` hooks happen *after* a transition is complete.  As such, they cannot redirect the current transition.  You could instead start a new transition using `$state.go`, however.

See here: https://ui-router.github.io/ng1/docs/latest/classes/transition.transitionservice.html#onerror

specifically the `Lifecyle` section:

> Lifecycle
>
> The onError hooks are chained off the Transition's promise (see Transition.promise). If a Transition fails, its promise is rejected and the onError hooks are invoked. The onError hooks are invoked in priority order.
>
> Since these hooks are run after the transition is over, their return value is ignored.

**Comment by sean-stanley** [comment]
Yep all works fine using transition.router.stateService.go in this case.

I think I got confused in the docs because onError does specify that the return value is ignored but this wasn't mentioned when I read the TransitionHookFn signature section.

Thanks for your help
