### ISSUE TITLE
Get state from location hash helper does not work with query params

### ISSUE THREAD

**Issue by samithaf** [angular-ui/ui-router#3447]
This is a:

- [x] Bug Report

My version of UI-Router is: (1.0.3)

# Bug Report

#### Current Behavior:

Get state from location hash helper does not work when the hash contains url param 

#### Expected Behavior:

Get state from location hash helper should work when the hash contains url param

#### Link to Plunker that reproduces the issue:

https://plnkr.co/edit/D8yZQVRhUrzJsVCL4ToL?p=preview

In the above plunker default state is news has a url param. As you can see when the application started current state is empty. But when you navigate to help state by clicking go to help link, current state get populated. Then when you click on the link to go back to news article again current state becomes empty.

**Comment by christopherthielen** [comment]
@samithaf `UrlMatcher.exec()` takes multiple arguments:  
```
exec(path: string, search?: any, hash?: string, options?: any)
```

Use: `.exec($location.path(), $location.search())` and it should work

https://ui-router.github.io/ng1/docs/latest/classes/url.urlmatcher.html#exec

You can also try the new API in `UrlService` which will give you the *rule* that matches the URL, not just the state.    

https://ui-router.github.io/ng1/docs/latest/classes/url.urlservice.html#match

https://plnkr.co/edit/stWEYu3aHvM2QTw5M71p?p=preview

Hope this helps!

**Comment by samithaf** [comment]
@christopherthielen thanks for the quick feedback. 👍  I should have read the doc's
