### ISSUE TITLE
Set page titles dynamically by passing title in state objects in UI-router for Angular 1.5 with components

### ISSUE THREAD

**Issue by shivanisaz** [angular-ui/ui-router#3453]
I need to set the page titles in my Angular (1.5) application, dynamically. For this, the most common method mentioned everywhere is to pass the title in the state object while routing and bind this to the `$rootScope.title`

But, i am facing a major issue here. In the original UI-router we could attach custom data to state objects. 
Refer : https://github.com/angular-ui/ui-Router/wiki#attach-custom-data-to-state-objects

However, this does not seem to be the case with UI-router for Angular 1.5 components. The `$state.current` object did not show any extra data attached to it when consoled. 

How can I pass custom data in the state objects in UI-router for angular components?

Also, is there any other way to set the page title dynamically?

**Comment by simondrabble** [comment]
You might want to look at the packages  https://github.com/riggerthegeek/ng-page-title and https://github.com/nonplus/angular-ui-router-title (note: untested, YMMV).
