### ISSUE TITLE
guide link is broken?

### ISSUE THREAD

**Issue by zhu711** [angular-ui/ui-router#3457]
Is transition guild been removed? all just the link is broken? 

https://ui-router.github.io/guide/transitions

Thanks,

**Comment by matehat** [comment]
Guys, @christopherthielen, @mrngoitall, please look this up. The Transitions guide page is referenced all over the docs, and they're all broken. Getting documentation is a bit messy for ui-router right now.

**Comment by mrngoitall** [comment]
Any ideas, @christopherthielen? I don't see the Transitions guide in the [documentation repo](https://github.com/ui-router/ui-router.github.io/tree/master/_guide), nor in its history, so I can't tell which file should be served for that route.
