### ISSUE TITLE
How to pass unique state data into a resolver?

### ISSUE THREAD

**Issue by kfroemming** [angular-ui/ui-router#3459]
This issue tracker is for Bug Reports and Feature Requests only.
Please direct requests for help to StackOverflow.  See http://bit.ly/UIR-SOF for details.

This is a:

- [ ] Bug Report
- [ ] Feature Request
- [x] General Query 

My version of UI-Router is: (version) 1.0.1

# Bug Report

#### Current Behavior:

(current behavior here)

#### Expected Behavior:

(expected behavior here)

#### Link to Plunker that reproduces the issue:

http://bit.ly/UIR-Plunk

# Feature Request

(feature request here)

# General Query

Please direct general implementation questions to StackOverflow: 
http://stackoverflow.com/questions/ask?tags=angularjs,angular-ui-router

Please review the Sample Application which highlights common approaches:
https://github.com/ui-router/sample-app-ng1

- [x] I have already asked my question on StackOverflow and nobody could answer the question

- [x] I have already reviewed the sample application for examples of common approaches

- [x] I believe my question can only be answered by the UI-Router maintainers

(general query here)
Hey there, I am currently rebuilding routing from ng-route to ui-router and have a question about loading custom data from a specific state, into that states resolver. 

Example: 
`  {
        url: '/' + locale,
        params: {
          pageStrings: ['data', 'data2', 'data3', 'data4'],
          apiUrl: '/api/home',
        },
        controller: 'ContentPageCtrl',
        name: 'homePageLocale',
        resolve: resolvers.content, //an object containing resolver functions
        templateUrl: `home.html`
      },`

in the snippet above, I am unable to access params:{} inside of the resolvers, however, the data it holds are is required by the resolver in order to obtain the correct content.
I have tried usings $state.params, and $stateParams inside of the resolvers to no avail, including using them inside of the URL.

Any ideas?

**Comment by schester44** [comment]
Chiming in to give you an example of how i'm accessing param data within a resolve. Make sure you pass $stateParam into the resolve function.

```
  params: {
    id: undefined,
  },
  resolve: {
    menu: ['Menus', '$stateParams', (Menus, $stateParams) => Menus.get({ id: $stateParams.id })]
}
```
