### ISSUE TITLE
[1.0.3] Adding a "future state" state at Runtime

### ISSUE THREAD

**Issue by rkingon** [angular-ui/ui-router#3461]
We currently (in 0.4.2) use ui-router-extras to implement some "overlayable" states at runtime. These are basically duplications of states that already exist, but the ability to view them in an overlay for ease of navigation (and so you don't leave the page you're on).

We recently upgraded to 1.0.3, which deprecates the use of ui-router-extras & bakes some of the functionality into the core. awesome!

I see a way of "lazy loading" the states, however, we need the ability to generate a state at runtime (essentially, I listen to a state change and if it has an option of "overlay: true" then I generate the state, stop the immediate transition, and go to the new overlay state which has an onEnter that opens its contents within an overlay.

Does this functionality exist? Or maybe there is a new way I should consider tackling the above goal?

Thanks!

**Comment by christopherthielen** [comment]
Yes, it is possible to generate states at runtime.  You may [register and deregister them using `$stateRegistry`](https://ui-router.github.io/ng1/docs/latest/classes/state.stateregistry.html#register).

However, it sounds like you are trying to build a data driven "modal state" on the fly based on the state's metadata.  This is probably better done during state registration using the ["State Decorator" approach](https://ui-router.github.io/ng1/docs/latest/classes/ng1.stateprovider.html#decorator).

An example might be:

```
$stateProvider.decorator('onEnter', function(state, parentDecoratorFn) {
  // If there is a parent function, call it first to get the actual onEnter
  var realOnEnter = parentDecoratorFn && parentDecoratorFn(state);

  if(state.data.overlay === true) {
    state.onEnter = function() {
      // do modal stuff
      realOnEnter && realOnEnter.apply(null, arguments);
    }
  }
});
```

**Comment by rkingon** [comment]
Thanks @christopherthielen !

We ended up solving it by using our own provider, ie:
```coffeescript
.provider "$ssState", ($stateProvider) ->
  [a bunch of other state stuff we're doing]
  @state = $stateProvider.state
  _.set @, "$get", -> @
```

I used, at one point, predefining the it based off a data attribute like seen in that decorator -- the problem was it was too restrictive. You never know what state may be triggered from the overlay, so you need all, but might not want all states. I essentially just listen to a onStart event and see if one of my custom options are true or if we're already in an overlay stack and it will generate the states on the fly, then transition to them. It actually works very well, surprisingly.

Anyways, do you see any issues with the way we ended up solving above?

**Comment by christopherthielen** [comment]
The idiomatic approach (if you know at app start which states should have overlay) is to use a decorator but I don't see any problem with your approach.
