### ISSUE TITLE
Update the docs to mention @uirouter/angularjs

### ISSUE THREAD

**Issue by maciej-gurban** [angular-ui/ui-router#3468]
This is a:
- [x] Bug Report

The documentation states that we should install angular 1.x library version with:
```
npm install --save angular-ui-router
``` 

But immediately after installing the following will be shown:
```
WARNING! this npm package "angular-ui-router" has been renamed to "@uirouter/angularjs".  Please update your package.json
See https://ui-router.github.io/blog/uirouter-scoped-packages/ for details.
```

**Comment by amirensit** [comment]
It is about update in package.json
You need to replace 
` "dependencies": {
    "angular-ui-router": "latest",
    "ui-router-visualizer": "latest",
  }

by 
`"dependencies": {
    "@uirouter/angularjs": "latest",
    "@uirouter/visualizer": "latest",
  }`


`

**Comment by Toddses** [comment]
Right... but the documentation still says to install `angular-ui-router`. The documentation needs to be updated, which is what @maciej-gurban is reporting.

**Comment by lopezoscar** [comment]
Hi, I can't install ui router

➜  am-packages-manager git:(webpack) ✗ npm set registry https://registry.npmjs.org/
➜  am-packages-manager git:(webpack) ✗ npm i @uirouter/angularjs                                      
npm ERR! code E404
npm ERR! 404 Not Found: @uirouter/angularjs@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/oscar/.npm/_logs/2017-08-09T22_23_39_739Z-debug.log
➜  am-packages-manager git:(webpack) ✗ cat /Users/oscar/.npm/_logs/2017-08-09T22_23_39_739Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '@uirouter/angularjs' ]
2 info using npm@5.3.0
3 info using node@v6.9.1
4 verbose npm-session ac8ed57655eb878a
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@uirouter%2fangularjs 1310ms
8 silly fetchPackageMetaData error for @uirouter/angularjs@latest 404 Not Found: @uirouter/angularjs@latest
9 verbose stack Error: 404 Not Found: @uirouter/angularjs@latest
9 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:41:19)
9 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
9 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
9 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
9 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
9 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
9 verbose stack     at runCallback (timers.js:637:20)
9 verbose stack     at tryOnImmediate (timers.js:610:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:582:5)
10 verbose cwd /Users/oscar/almundo/am-packages-manager
11 verbose Darwin 16.5.0
12 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "@uirouter/angularjs"
13 verbose node v6.9.1
14 verbose npm  v5.3.0
15 error code E404
16 error 404 Not Found: @uirouter/angularjs@latest
17 verbose exit [ 1, true ]
