### ISSUE TITLE
Modify URL without state reload

### ISSUE THREAD

**Issue by inad9300** [angular-ui/ui-router#3470]
This is a feature request.

`reloadOnSearch` is deprecated. Now we are supposed to use "dynamic parameters" -- a much more obscure name than "reload on search". The reasons for this change are beyond my understanding, but both approaches are too rigid.

Once you say "do not reload _x_ state if a parameter changes", you are completely restricted on what you can do. No doubt you will at some point need to add a new parameter for which you do want to reload the state if it changes.

Once you say "do not reload whatever state if _x_ parameter changes", you are equally restricted. No doubt you will sooner or later want to both, in different circumstances, navigate to the state with new parameters, and simply synchronize some internal state with the URL.

So, in my opinion, the ideal approach would be to allow controlling the reload on a per-call basis, i.e. via a parameter on the `go()` function.

If you find the time to implement such a feature, I would be very grateful.

**Comment by ventralnet** [comment]
This would be useful as well if you are in the situation where you want a parameter to be dynamic for one child state, yet non dynamic for other sibling states

**Comment by sarod** [comment]
Looks like a duplicate of  #2679

**Comment by inad9300** [comment]
It might well be, although they refer to very specific use cases and start to bring weird terms. The need is to modify the URL, it cannot be simpler. Anyways, focusing on the original message, @orangesoup's problem could definitely be solved with an extra parameter in the `go()` function, as it was (kind of) possible with the old UI Router.

Feel free to close this issue in favour of #2679, but please, don't overcomplicate things!

**Comment by ventralnet** [comment]
Is there a way to use one of the transition service hooks to stop a state transition but still perform the URL updating?

**Comment by inad9300** [comment]
That is an interesting idea, but still overcomplicated in my view. I'm not sure if it is even possible, though.

**Comment by inad9300** [comment]
Any news on this (or #2679)?

By stopping to use the deprecated `reloadOnSearch()` I start to see duplicated requests all around my application. Using _dynamic parameters_ is not convenient at all for me either -- not because of the reasons I exposed at first, which I believe are enough on themselves, but also because all my states are defined with your syntax `?{paramName:paramPattern}`, which does not support specifying the parameters as _dynamic_, and changing this everywhere is too much work. It's turning into a maintenance nightmare.

**Comment by inad9300** [comment]
Sorry for being so insistent, but are there any updates on this...? Are you planning no implementing a feature like this?

**Comment by inad9300** [comment]
Pop.

**Comment by MartijnWelker** [comment]
@inad9300 @ventralnet I might have created a solution that fits your needs over in #3047
