### ISSUE TITLE
uiOnParamsChanged not firing on consecutive query changes to an object using dynamic param

### ISSUE THREAD

**Issue by rkingon** [angular-ui/ui-router#3475]
This is a:
- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.3

# Bug Report

#### Current Behavior:

Easiest to see in a codepen: https://codepen.io/anon/pen/OgmzwK

When updating the query params, the first one takes then all future edits to the ngModel are being ignored. I am outputting the onError and it is indeed being ignored.

#### Expected Behavior:

uiOnParamsChanged continues to fire on consecutive changes

#### Link to Plunker that reproduces the issue:

https://codepen.io/anon/pen/OgmzwK

**Comment by rkingon** [comment]
I'm pretty sure this might have something to do with the `equals` method on the `ParamTypeDefinition`. I just created my own type to handle this better (creates a hash of the object too) and noticed that when I compare the two arguments on the `equals` method that both arg 1 and arg 2 are the "new" value vs one being the prior.

Maybe this is what is affecting the `json` type as well...

**Comment by lpsBetty** [comment]
I have also a problem with the dynamic json type...

I want to update the URL param `filter`, like this: 

```
search.filter.type = 'changed';
$state.go('.', {filter: search.filter});
```

but it doesn't update the URL and the more important part, it doesn't trigger the `uiOnParamsChanged`.

How can I manually update the URL json param?

**Comment by lpsBetty** [comment]
I got it working by adding a function like below, and using it with `ui-sref`:

```
search.mergeNewFilter = function (filter) {
  var currentFilter = angular.copy(search.filter);

  return angular.extend(currentFilter, filter);
};
```

Using the extended filter method inside ui-sref:
```
<a ng-repeat="year in [2017, 2018, 2019]" 
    ui-sref=".({filter: search.mergeNewFilter({year: year})})">{{year}}</a>
```
🎉

**Comment by denis-n** [comment]
I have a list with emails and sms (parent state) and edit (child) states. On return from child to parent this worked for me:
Parent params:
```
params: {
            refresh: {
                dynamic: true,
                **inherit: false,**
                value: {
                    email: false,
                    sms: false
                }
            }
        }, 
```
So I needed to know if I have to refresh a list and if that is an email or sms list.

`uiOnParamsChanged `works correctly for me when the param has `inherit: false`
