### ISSUE TITLE
ui-router forces products to add @angular/router as a dependency

### ISSUE THREAD

**Issue by zhenya-popov** [angular-ui/ui-router#3476]
This is a:

- [+] Bug Report

My version of UI-Router is: 1.0.0-beta.7

# Bug Report

#### Current Behavior:

I use ui-router in my project. During the compilation I get the following error:
ERROR in Could not resolve module @angular/router

ERROR in ./~/@uirouter/angular/lib/uiRouterNgModule.js
Module not found: Error: Can't resolve '@angular/router' in 'path-to-my-project/node_modules/@uirouter/angular/lib'
 @ ./~/@uirouter/angular/lib/uiRouterNgModule.js 6:0-41
 @ ./~/@uirouter/angular/lib/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

The reason of this error is that ui-router use @angular/router as a dependency, but it is placed at "devDependencies" section.
![screen shot 2017-06-21 at 18 19 33](https://user-images.githubusercontent.com/4255152/27392074-4d0b3804-56ae-11e7-8edb-d280e8a24b26.png)

 To fix this I have to manually add @angular/router as a dependency to my package.json

#### Expected Behavior:

It seems that all packages that are required not only at library compilation stage should go to "dependencies" section

**Comment by tommck** [comment]
This still seems to be the case with the latest @ui-router/angular today
