### ISSUE TITLE
Version Bump (1.0.4) on npm?

### ISSUE THREAD

**Issue by felixwahner** [angular-ui/ui-router#3481]
This is a:

- [ ] Bug Report
- [ ] Feature Request
- [X] General Query 

My version of UI-Router is: 1.0.4

I've tried to include ui-router 1.04 from npm as I'm running into the "Possibly unhandled rejection" error (which was fixed with the latest version). Unfortunately 1.0.4 isn't available on npm yet. Any plans on "bumping the Version" anytime soon?

**Comment by realph** [comment]
+1

**Comment by henriknilson** [comment]
+1

**Comment by t3o** [comment]
+1

**Comment by kjartanvalur** [comment]
@felixwahner 
Try switching to @uirouter/angularjs

**Comment by felixwahner** [comment]
Okay. I'll do!
