### ISSUE TITLE
Deprecate old packages

### ISSUE THREAD

**Issue by adamreisnz** [angular-ui/ui-router#3487]
The warning message is outputted when `npm install`ing the old packages (e.g. angular-ui-router) is output by plain console logs during installation, but all of this gets swallowed by yarn if there is no 1 exit code.

Instead of this log, the package should be deprecated properly:

https://docs.npmjs.com/cli/deprecate

There's many yarn users out there, they will miss out on this warning if it's only being logged. I for one, did not realise the packages had been renamed and was wondering why the npm library was still on 1.0.3 when 1.0.4 was released 2 weeks ago.

**Comment by christopherthielen** [comment]
Thanks for pointing this out. We had deprecated the `angular-ui-router` 1.0.0 release but not 1.0.3.

I've deprecated 1.0.3 as well.

**Comment by adamreisnz** [comment]
Cheers thanks
