### ISSUE TITLE
How can I access PathNode, ResolveContext, RejectType and other inner vairables/classes in my angularjs application?

### ISSUE THREAD

**Issue by Maximaximum** [angular-ui/ui-router#3489]
When I try to run this code in a controller, I get `angular-ui-router.js:6683 ReferenceError: PathNode is not defined` error. How can I access the PathNode constrctor from my application?

    public uiOnParamsChanged(newParams, transition) {
      this.$stateParams = newParams;

      let toState = transition.to().$$state();
      let pathAsNodes = toState.path.map(x => new PathNode(x));
      let resolveContext = new ResolveContext(pathAsNodes);

      resolveContext.resolvePath().then((results: any[]) => {
        let obj = results.reduce((total, current) => { total[current.token] = current.value; return total; });
        this.update(obj);
      });
    };

**Comment by Maximaximum** [comment]
I should add that I install 'angular-ui-router' v.1.0.4 package via bower.

**Comment by Maximaximum** [comment]
Here is a duplicate issue: https://github.com/angular-ui/ui-router/issues/3209

**Comment by musakarakas** [comment]
This worked for me. Maybe it'll help some webpack users:

```javascript
import { RejectType } from "@uirouter/angularjs";

app.run($transitions =>
  $transitions.onError({}, transition =>
    console.log(transition.error().type === RejectType.ERROR)
  )
);
```
