### ISSUE TITLE
url changes even if transition is aborted

### ISSUE THREAD

**Issue by abhijeetahuja** [angular-ui/ui-router#3494]
https://stackoverflow.com/questions/44896070/ui-router-browser-back-button-changes-url-even-abort-transition-is-called

**Comment by smhc** [comment]
Duplicate of:
https://github.com/angular-ui/ui-router/issues/3416

Still a problem with ui router 1.0.5 and angular js 1.6.5.

**Comment by rpoole** [comment]
Still seeing this in 1.0.11. Is there any fix planned?
