### ISSUE TITLE
Ng_from_import may be empty

### ISSUE THREAD

**Issue by salJoker** [angular-ui/ui-router#3495]
`var cfg = data.$cfg || { viewDecl: {}, getTemplate: ng_from_import.noop };`

Here, the Ng_from_import will have an empty value, which occurs when I use AngularJS v1.6.4, RequireJS 2.3.3, and i-ui - router v1.0.5.

**Comment by heniotierra** [comment]
This is happening to me too. Error occurs when using Angular 1.6.4, Require 2.1.22, ui-router 1.0.5. If I switch to older versions of these libs, everything works fine.

**Comment by CoconutTheSlayer** [comment]
@heniotierra which old versions exactly? I have the same problem

**Comment by heniotierra** [comment]
@CoconutTheSlayer I'm using

"angular": "~1.2.16",
 "angular-ui-router": "~0.2.18",
 "requirejs": "~2.1.14"

**Comment by edeye** [comment]
var cfg = data.$cfg || { viewDecl: {}, getTemplate: ng_from_import.noop };

Here, the ng_from_import will have an empty value, which occurs when I use AngularJS v1.6.6, RequireJS 2.3.3, and i-ui - router v1.0.6

**Comment by edeye** [comment]
@salJoker  do you solved this problem?

**Comment by heniotierra** [comment]
@edeye @CoconutTheSlayer 

This issue is duplicate of #3257 , and there christopherthielen mentions that adding that data below to the shim in your requirejs config solves the problem, with no need to use old versions of the libs. I did solve the problem for me.

>     shim: {
>         'angular': { exports: 'angular' },
>         'angular-ui-router': ['angular']
>     },
