### ISSUE TITLE
ui-sref cause redundant state transition 

### ISSUE THREAD

**Issue by buunguyen** [angular-ui/ui-router#350]
I noticed that whenever `ui-sref` is used, a state is transitioned to twice. Upon examining the source code, it looks like the issue is caused by the fact that `$StateRefDirective` not only generates a `href` but also binds `onclick` event. By removing one of those, the issue is solved. 

Is this a bug or by design? Given that the built-in `ng-href` only generates `href`, is there a reason `ui-sref` has to bind the `onclick` event?

**Comment by stoyanvi** [comment]
+1. Including ui-sref="stateName({ "optionalParam": "" })" fixes it, but we cannot rely on this.

**Comment by PeterM88** [comment]
+1 The tips saved me a lot of time :)

PM
www.gastromatic.de

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by itmilos** [comment]
Try to use $locationChangeStart instead of $stateChangeStart

So try calling off as @eupharis, but with locationChangeStart

var off = scope.$on('$locationChangeStart', foo);

**Comment by haynesgt** [comment]
Issue observed in angular-ui-router v0.2.18
To  remove the second click, add a `target='_self'` attribute to the <a> element.
For example, see http://plnkr.co/edit/XiXzGeBasGrxsqyscOTN?p=preview

**Comment by iMomen** [comment]
Issue is still observed in angular-ui-router v0.3.2
any updates ?

**Comment by patrick-99** [comment]
I use angular-ui-router v0.3.1, and register on state change using this code implemented in my controller:
```
$rootScope.$on('$stateChangeStart', function(event, toState, toParams, fromState, fromParams) {
    if (fromState.name === 'home' && toState.name === 'campaigns') {
      // my code to run upon this specific state transition
      clientService.quit();
    }
})
```
The HTML to trigger the state transition is like:
`<a ui-sref="campaigns" target="_self"><img class="logo" src="images/logo_small.png" alt="Logo"></a>`

The whole thing is embedded in a Single Page App.
I noticed the '$stateChangeStart' event listener is first called once, next time twice, and so on, called 5 times the 5th time...

I was suspecting the issue to be the state change listener being registered each time the navigation is routing to this page. So I updated the code to unregister in the callback itself:
```
  var stateChangeListener = $rootScope.$on('$stateChangeStart', function(event, toState, toParams, fromState, fromParams) {
    stateChangeListener();
    if (fromState.name === 'home' && toState.name === 'campaigns') {
      clientService.quit();
    }
  })
```
It now works as expected, as the callback function is only triggered once.

**Comment by nhutdinh** [comment]
@patrick-99 : event.preventDefault()  wont work in this case
