### ISSUE TITLE
Mismatch in type declaration (finally is not a member of Promise, but $q)

### ISSUE THREAD

**Issue by loxy** [angular-ui/ui-router#3500]
This is a:

- [x ] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: (version)
1.0.5

# Bug Report

Please visit: https://stackoverflow.com/questions/44119516/angular-ui-router-1-0-3-with-angular-js-1-6-4-appears-to-be-using-the-wrong-prom

Lily Carpenter described the problem quiet well. No answer was provided there and indeed, it look like a mismatch in the type declarations of the used promise implementation. And didn't found a corresponding issue here...

**Comment by azrazalea** [comment]
FWIW, I worked around this for now with

```
interface IRealTransition extends router.Transition {
  promise: ng.IPromise<any>;
}
```

And using that as the type declaration for the transition argument in my promise function.
