### ISSUE TITLE
Feature: nested states via hashtag

### ISSUE THREAD

**Issue by stasusov** [angular-ui/ui-router#3501]
This is a:

- [ ] Bug Report
- [x] Feature Request
- [ ] General Query 

# Feature Request

It would be a cool feature to implement the state views accessible by hashtag. It is useful when url should be the same, but some content in the page is dynamic, i.e. tabs.

## Current solution
How we are implementing it now:
urls:
* /page/{id}
* /page/{id}/description
* /page/{id}/video

```
$stateProvider
  .state('app.page', {
    url: '/page/{id}',
    title: 'Page',
    templateUrl: 'templates/page/page.template.html',
    controller: 'Page.Controller',
    controllerAs: 'pageCtrl'
  })
  .state('app.page.description', {
    url: '/description',
    title: 'Page description',
    templateUrl: 'templates/page/page.description.template.html',
    controller: 'Page.Description.Controller',
    controllerAs: 'pageCtrl'
  })
  .state('app.page.video', {
    url: '/video',
    title: 'Page video',
    templateUrl: 'templates/page/page.video.template.html',
    controller: 'Page.Video.Controller',
    controllerAs: 'pageCtrl'
  })
```

## Expected
How do I expect this to be used with implemented hashtags:
urls:
* /page/{id}
* /page/{id}#description
* /page/{id}#video

```
$stateProvider
  .state('app.page', {
    url: '/page/{id}',
    title: 'Page',
    templateUrl: 'templates/page/page.template.html',
    controller: 'Page.Controller',
    controllerAs: 'pageCtrl'
  })
  .state('app.page.description', {
    url: '',
    '#': 'description',
    title: 'Page description',
    templateUrl: 'templates/page/page.description.template.html',
    controller: 'Page.Description.Controller',
    controllerAs: 'pageCtrl'
  })
  .state('app.page.video', {
    url: '',
    '#': 'video',
    title: 'Page video',
    templateUrl: 'templates/page/page.video.template.html',
    controller: 'Page.Video.Controller',
    controllerAs: 'pageCtrl'
  })
```

I have tried a lot of approaches to make this but none of them give full functionality (as in first example) and have problems.

**Comment by christopherthielen** [comment]
We support the hash *as a  parameter* but not as a state discriminator. 

The hash is commonly used to "scroll" the page to some anchor tag.  The current implementation allows you to apply the hash as a parameter value (`$state.go('.', {#: 'anchor1'})`); the browser will then scroll to the anchor tag named `anchor1`. 

Why doesn't the path based urls (current solution) work for you?

**Comment by stasusov** [comment]
@christopherthielen, yes, I know about the current possibility of using hashes.
Because it is actually one page, where only one fragment on it will change by visiting this links:
* /page/1/description
* /page/1/video
It is not good for search engines, that may think pages are duplicating each other, and it is a problem because as you can see :id is dynamic part and there can be >100 such pages

**Comment by christopherthielen** [comment]
Yes I understand now.  I don't think we can support your request any time soon.  It would require significant rework of the router core.

Perhaps you can use the hash-as-parameter within a single state, and show the correct content (tab) using components (instead of as a separate state) as a workaround.

**Comment by stasusov** [comment]
@christopherthielen, ok, thank you. Issue can be closed if you will not work on it
