### ISSUE TITLE
Not able to test transitions hooks with karma

### ISSUE THREAD

**Issue by floreks** [angular-ui/ui-router#3502]
This is a:

- [ ] Bug Report
- [ ] Feature Request
- [X] General Query 

My version of UI-Router is: 1.0.5

I have tried to seek for help on [StackOverflow](https://stackoverflow.com/questions/45081326/ui-router-1-x-how-to-test-transition-service-hooks-with-karma) already but there was no answer. Maybe one of devs that know what was changed will know why `$scope.$broadcast()` is not triggering transition hooks.

My post from SO:
```
I'm trying to migrate to ui-router 1.0.5 and have done most of the work but there are no examples of how to test new transition hooks that replaced $stateChangeXXX events listeners.

Code before:

scope.$on('$stateChangeSuccess', this.hideSpinner_.bind(this));

After:

this.transitions_ is a $transitions service exposed by ui-router this.transitions_.onSuccess({}, this.hideSpinner_.bind(this));

Before I was able to test it by using scope.$broadcast($stateChangeSuccess) and then scope.$apply(). This worked with ui-router 0.x:

expect(ctrl.loading).toBe(true);
expect(ctrl.showLoadingSpinner).toBe(true);

// when
scope.$broadcast('$stateChangeSuccess');
scope.$apply();

// then
expect(ctrl.loading).toBe(false);
expect(ctrl.showLoadingSpinner).toBe(false);
Any idea how to rewrite tests to work with new version of ui-router?
```

**Comment by parky128** [comment]
@floreks - did you ever find a way to test the $transitions hooks? I am facing the exact same issue, where I now have custom logic within a hook I want to cover in my tests. I read that the hooks get triggered when calling $state.go(), which I tried in my tests, but it made no difference for me

**Comment by floreks** [comment]
> did you ever find a way to test the $transitions hooks?

Unfortunately not. [Clark.Hsu](https://stackoverflow.com/questions/45081326/ui-router-1-x-how-to-test-transition-service-hooks-with-karma) posted a workaround that works for tests but I have not found a clear way of testing custom logic in the hook.
