### ISSUE TITLE
Redirecting to the same state with redirectTo doesn't reset URL

### ISSUE THREAD

**Issue by bhollis** [angular-ui/ui-router#3503]
This is a:

- [X] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.5

# Bug Report

#### Current Behavior:

If I set up two states like this:

```
  $stateProvider.state({ 
    name: 'home', 
    url: '/home', 
    redirectTo: 'home.foo',
    component: 'home',
  });
  
  $stateProvider.state({ 
    name: 'home.foo', 
    url: '/foo', 
    component: 'foo',
  });
```

And then I start at `/home/foo`, and manually edit the URL to be `/home`, the redirection to the `home.foo` state completes, but the URL remains at `/home`.

#### Expected Behavior:

I would expect that, upon redirecting back to the `home.foo` state, the URL would be `/home/foo`.

#### Link to Plunker that reproduces the issue:

http://plnkr.co/edit/nceC7u9YaxdUSj0BpMrI?p=preview (click the "Go back" button)

**Comment by eve-amandine** [comment]
Same issue for me. Did you find any workaround?
