### ISSUE TITLE
Cannot read property '$$animLeave' of undefined

### ISSUE THREAD

**Issue by abbymrs** [angular-ui/ui-router#3504]
@christopherthielen 
Hi,
I got the error `"Cannot read property '$$animLeave' of undefined"` after upgraded my application from angular version 1.5.0 to 1.6.5 with ui-router version 1.0.5(Original ui-router version 0.2.15).
some routes works well, but some not, could you pls kindly give me some help?

Here is the stackoverflow link with more details: https://stackoverflow.com/questions/45406660/ui-router-error-cannot-read-property-animleave-of-undefined

Thanks a lot!

**Comment by abbymrs** [comment]
After i added `ui-sref-opts="{reload: true}"` to `<a/>` element, it works! But why?

**Comment by abbymrs** [comment]
sorry, my team empty the ui-view ....

**Comment by laxmanrapolu** [comment]
@abbymrs : We recently upgraded our UI-router to 0.4.7 and angularJs to 1.7.5. We started seeing above error after these upgrades. Just wanted to check if adding ui-sref-opts="{reload: true}" fixed your issue? It did not in our case. I coudn't understand the last comment you made.
