### ISSUE TITLE
$transition$.params() cannot assign new value

### ISSUE THREAD

**Issue by abbymrs** [angular-ui/ui-router#3506]
Hi, 

`$transition$.params()` in router 1.0+ is a read only object, but in my application, i do need to rewrite this object, i.e:

`if( $transition$.params().caseId){ $transition$.params().caseId = '';}`

These codes will generate an error `cannot assign to read only property 'caseId' of object '#<Object>'`, is there any way that i can rewrite the params object?
Thanks!

**Comment by gaui** [comment]
I'm trying to achieve something similar as well. According to Chris transition params shouldn't be mutated, but rather create a new transition with the new params. See Twitter convo: https://twitter.com/gauiis/status/897114222404014080

The problem is this is the SAME STATE. Once WITHOUT params and then afterwards WITH params.

I have a state definition and an `onEnter` transition hook which calls API to get dates and assigns those dates as params. I'm not mutating the params, but creating a new transition (TargetState) with the added params. The following:

```
{
    name: 'ready',
    url: '/ready',
    onEnter: ($transition$ : Transition) => {
        'ngInject';

        const toStateParams = $transition$.params('entering');
        if (toStateParams.dateFrom && toStateParams.dateTo)
            return true;

        return APIService.getDates()
            .then((data : any) => {
                const dateFrom = moment(data.ReadyDateFrom).format('YYYY-MM-DD');
                const dateTo = moment(data.ReadyDateTo).format('YYYY-MM-DD');
                const newDate = { dateFrom, dateTo };

                // Don't mutate state transition params object, just create a new one
                // which overrides old one.
                const newStateParams = Object.assign({}, $transition$.params(), newDate);

                // Return the new target transition
                return $uiRouter.stateService
                    .target($transition$.to(), newStateParams, $transition$.options());
            });
    }
}
```

I get the following in TRANSITION $trace output:

```
Transition #6-0: Started  -> "Transition#6( ''{} -> 'ready'{} )"
Transition #6-0: <- Rejected "Transition#6( ''{} -> 'ready'{} )", reason: Transition Rejection($id: 6 type: 2, message: The transition has been superseded by a different transition, detail: 'ready'{"#":null,"dateFrom":"2015-09-23","dateTo":"2017-03-07"})
```

**Comment by gaui** [comment]
If I use `$transition$.targetState().params()` this seems to work.

@abbymrs Do this. Create a new transition with `$transition$.router.stateService.target()` and the new param values. To read them in your controller use `$transition$.targetState().params()`. `$transition$.params()` didn't work.

**Comment by gaui** [comment]
Not sure what the difference is.
According to docs:

https://ui-router.github.io/ng1/docs/latest/classes/transition.transition-1.html#params

> params(pathname?: string): any
> Gets transition parameter values
> Returns any : transition parameter values for the desired path.

Desired path. According to source `to` is default.

https://ui-router.github.io/ng1/docs/latest/classes/transition.transition-1.html#targetstate

> targetState(): TargetState
> Gets the Target State
> Returns TargetState : the TargetState of this Transition

**Comment by christopherthielen** [comment]
This is how you can redirect a transition in an `onEnter` hook:

http://plnkr.co/edit/1w9TiLQ1De4Jx9R8Zqwf?p=preview

**Comment by christopherthielen** [comment]
@gaui `$transition$.params()` and `$transition$.targetState().params()` should effectively be the same values

**Comment by gaui** [comment]
@christopherthielen Why does it reject the transition?

```
Transition #0-0: Started  -> "Transition#0( ''{} -> 'shipments.ready'{} )"
Running onEnter hook for: masterPage.shipments.shipments.ready
Transition params: {"#":null}
Transition #0-0: <- Rejected "Transition#0( ''{} -> 'shipments.ready'{} )", reason: Transition Rejection($id: 0 type: 2, message: The transition has been superseded by a different transition, detail: 'shipments.ready'{"#":null,"dateFrom":"2015-09-23","dateTo":"2017-03-07"})
Transition #1-0: Started  -> "Transition#1( ''{} -> 'shipments.ready'{} )"
Running onEnter hook for: masterPage.shipments.shipments.ready
Transition params: {"#":null}
Transition #1-0: <- Rejected "Transition#1( ''{} -> 'shipments.ready'{} )", reason: Transition Rejection($id: 1 type: 2, message: The transition has been superseded by a different transition, detail: 'shipments.ready'{"#":null,"dateFrom":"2015-09-23","dateTo":"2017-03-07"})
```

Here's my state declaration:

```
{
    name: 'shipments.ready',
    url: '/ready',
    data: {
        roles: [USER_ROLES.SHIP]
    },
    onEnter: ($transition$ : Transition) => {
        'ngInject';

        // Check if we have dates in the state's params
        // If we don't, we have to fetch the dates from API
        // and redirect the transition to the state again
        // with the dates in params.
        console.log(`Running onEnter hook for: ${$transition$.$to()}`);
        console.log(`Transition params: ${JSON.stringify($transition$.params())}`);
        const params = $transition$.params();
        if (!params.dateFrom && !params.dateTo) {
            const user = UserService.getUserProfile();
            if (!user) return;

            const start = moment().startOf('isoWeek')
                .subtract(18, 'weeks').format('YYYY-MM-DD');
            const end = moment().endOf('isoWeek')
                .add(6, 'weeks').format('YYYY-MM-DD');

            return ShipmentService.companyShipments(start, end,
                    user.SelectedCompany.PartnerCode)
                .then((data : any) => {
                    const dateFrom = moment(data.ShipmentsReadyDateFrom).format('YYYY-MM-DD');
                    const dateTo = moment(data.ShipmentsReadyDateTo).format('YYYY-MM-DD');
                    const newDate = { dateFrom, dateTo };

                    // Don't mutate state transition params object, just create a new one
                    // which overrides old one.
                    const newStateParams = Object.assign({}, params, newDate);

                    // Return the new target transition
                    return $transition$.router.stateService
                        .target($transition$.to(), newStateParams);
                });
        }
    }
}
```

**Comment by gaui** [comment]
@christopherthielen  I have a parent state with a controller, then child states that alter dates in that controller (previously $stateParams). Then I'm fetching data from API based on those dates.

Now with these transitions, because the onEnter redirects the transition to the SAME state (just with params), it supersedes that transition and rejects, thus `$transition$.params()` in the controller is always empty.

Do you have a solution?

**Comment by gaui** [comment]
@christopherthielen Is the behavior different when using component vs. controller ?

**Comment by gaui** [comment]
@christopherthielen Here's a plunkr: http://plnkr.co/edit/f45NOF2W4YbPqeZLytfg?p=preview

**Comment by christopherthielen** [comment]
> Why does it reject the transition?

Because a transition redirect _creates new transition ... the original one is discarded._

@gaui I think the problem is that no state has the parameter declared.  Parameter values have to be applied to a state.

Try adding `params: { dateFrom: null, dateTo: null }` to your state (or maybe even put the params in the url)

http://plnkr.co/edit/4oTuKkgY5PCbGmAqq8Xb?p=preview

**Comment by gaui** [comment]
@christopherthielen Of course, such a stupid mistake. Thank you.

**Comment by christopherthielen** [comment]
I think this issue is resolved.  @abbymrs please refer to the above comments on how to redirect with new parameter values

**Comment by abbymrs** [comment]
@gaui thanks a lot!
