### ISSUE TITLE
Update docs about hookResult, as it's not working that way

### ISSUE THREAD

**Issue by dietergeerts** [angular-ui/ui-router#3507]
This is a:

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: @uirouter/angularjs v1.0.3

# Bug Report

#### Current Behavior:

I have an onEnter in my state, and when I return a state, nothing happens. Though it's described in the docs:  `HookResult: true | false | void | TargetState | Promise<true | false | void | TargetState>`

#### Expected Behavior:

That it just works like documented. (a lot of the documentation is really out of date.

Though there is a workaround, but I don't know if that's the way it should be done:

```
$transition$.router.stateService.transitionTo(myStateDefinition);
return false;
```

**Comment by kaidjohnson** [comment]
Not sure this is a bug. Try returning a new TargetState:

```
$transitions.onEnter({}, function (transition) {
  return transition.router.stateService.target(myStateDefinition);
});
```

**Comment by dietergeerts** [comment]
In the meantime I already found out that returning a target state works, but it should still be documented.
