### ISSUE TITLE
Support Vue

### ISSUE THREAD

**Issue by ttonyh** [angular-ui/ui-router#3509]
This issue tracker is for Bug Reports and Feature Requests only.
Please direct requests for help to StackOverflow.  See http://bit.ly/UIR-SOF for details.

This is a:

- [ ] Bug Report
- [X] Feature Request
- [ ] General Query 

# Feature Request

Please consider supporting Vue 2. It is becoming a very popular framework.

**Comment by gaui** [comment]
This would be truly awesome because some people are considering bailing on React because of their stupid patents.

**Comment by maximilianschmid** [comment]
+1

**Comment by Zadvornyi** [comment]
+1
