### ISSUE TITLE
npm 5.3.0 throws 404 Not Found: @uirouter/angularjs@latest

### ISSUE THREAD

**Issue by lopezoscar** [angular-ui/ui-router#3510]
This issue tracker is for Bug Reports and Feature Requests only.
Please direct requests for help to StackOverflow.  See http://bit.ly/UIR-SOF for details.

This is a:

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: latest

# Bug Report

#### Current Behavior:

npm install --save @uirouter/angularjs
npm ERR! code E404
npm ERR! 404 Not Found: @uirouter/angularjs@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/oscar/.npm/_logs/2017-08-10T14_21_37_615Z-debug.log

#### Expected Behavior:

added 1 packages in 1s

Could you please, help me? I want to migrate to npm instead bower

**Comment by jonapoirier** [comment]
I guess it's a duplicate of [#17966](https://github.com/npm/npm/issues/17966)

**Comment by maritaria** [comment]
This just started happening again
