### ISSUE TITLE
Flickering on iOS Safari with swipe gestures

### ISSUE THREAD

**Issue by herna** [angular-ui/ui-router#3511]
Hello,

I am having this quite annoying effect in iOS Safari, you can see in the next video what I mean: https://www.dropbox.com/s/w2unex9pi09epja/ios_flicker.mp4?dl=0

As you can check, when I swipe left or right, the browser briefly displays a snapshot of the current page just before showing the new one. This only happens with swipe gestures, if I push back/forward buttons in the bottom this flickering doesn't show up.

I can see there are other users with this kind of flickering but the problem is always related to some additional animations, in my case I am not doing any kind of animation.

You can check this effect by yourself here with the next data:

- URL: https://www.lavnetremote.com/equipment/91365/equipment-general-view

- user: test@test.com

- password: uirouter

My current version of ui-router is v0.4.2 but I also tested with version 1.0.5 and the results are the same. My AngularJS version is 1.6.4

This is driving me crazy because I don't really now what's the reason for this effect and how can I get rid of it. Could you please point me in the right direction?

Thank you very much.

**Comment by maximilianschmid** [comment]
same here

**Comment by ayedo** [comment]
same here

**Comment by nicolae-olariu** [comment]
@herna Did you ever find a solution to this?

I have the exact same flicker issue but the app I'm working on is built on Angular 10 and their built-in @angular/router.

Thanks!

**Comment by mixail2188** [comment]
@herna @maximilianschmid @nicolae-olariu hi!

Have you found a solution to this problem?

**Comment by herna** [comment]
@maximilianschmid @nicolae-olariu  No, I haven't. I don't know where the problem comes from, just drop some lines here if you ever make it work.

**Comment by redbar0n** [comment]
Explanation and workaround: https://github.com/nolimits4web/swiper/issues/3527

**Comment by herna** [comment]
> [nolimits4web/swiper#3527](https://github.com/nolimits4web/swiper/issues/3527)

I'll give a try. Thank you.
