### ISSUE TITLE
Importing interfaces from @uirouter/angularjs do not match type definitions and are broken (1.0.6)

### ISSUE THREAD

**Issue by mtraynham** [angular-ui/ui-router#3514]
This issue tracker is for Bug Reports and Feature Requests only.
Please direct requests for help to StackOverflow.  See http://bit.ly/UIR-SOF for details.

This is a:

- [X] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.6 (1.0.5 works correctly)

# Bug Report

#### Current Behavior:

`import {StateService} from '@uirouter/angularjs';` returns an `undefined` object.

#### Expected Behavior:

`import {StateService} from '@uirouter/angularjs';` returns the StateService

I believe this a bug with how the *release/ui-router-angular.js* is generated and the issue is exposed by [this particular commit](https://github.com/angular-ui/ui-router/commit/4baa430ad0f5276db2d7edf9d5e2199af9b442c7).

With 1.0.5, the *package.json* `main` path pointed to *lib/index.js*.  Within that (compiled) file, there is a re-export of all `@uirouter/core` objects.

```js
/**
 * Main entry point for angular 1.x build
 * @module ng1
 */ /** */
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
__export(require("./services"));
__export(require("./statebuilders/views"));
__export(require("./stateProvider"));
__export(require("./urlRouterProvider"));
require("./injectables");
require("./directives/stateDirectives");
require("./stateFilters");
require("./directives/viewDirective");
require("./viewScroll");
exports.default = "ui.router";
var core = require("@uirouter/core");
exports.core = core;
__export(require("@uirouter/core"));
//# sourceMappingURL=index.js.map
```

**The important line here being:**
```js
__export(require("@uirouter/core"));
```

Now with 1.0.6, the *package.json* `main` path points to *release/ui-router-angularjs.js*.  This file contains no such line that would have a similar re-export.

```js
/**
 * Main entry point for angular 1.x build
 * @module ng1
 */ /** */
var index = "ui.router";

exports['default'] = index;
exports.core = _uirouter_core;
exports.watchDigests = watchDigests;
exports.getLocals = getLocals;
exports.getNg1ViewConfigFactory = getNg1ViewConfigFactory;
exports.ng1ViewsBuilder = ng1ViewsBuilder;
exports.Ng1ViewConfig = Ng1ViewConfig;
exports.StateProvider = StateProvider;
exports.UrlRouterProvider = UrlRouterProvider;

Object.defineProperty(exports, '__esModule', { value: true });

})));
```

#### Link to Plunker that reproduces the issue:

http://bit.ly/UIR-Plunk

**Comment by itanex** [comment]
I created a simple ASP.NET CORE 2.0 MVC application and started plugging in an NG1 app. This is the first time I encountered the new updates and cannot seem to get the type definitions to resolve. I have been through the closed linked issue attempting what I found there. I searched SO for an Q&A but found nothing.

Typescript just throws the standard TS2307. Cannot find module '@uirouter/core'

* Everything was installed 1/16/2018.
* node_modules folder contains a @uirouter/core path containing files and folder

Please let me know what other details would help.

**Comment by itanex** [comment]
**UPDATE 2018/02/05**

I have updated my project with expectation that this might have been resolved.

**Test 1**
UIRouter 1.0.14
Typescript 2.6.2

**Test 2**
UIRouter 1.0.14
Typescript 2.7.1
