### ISSUE TITLE
TypeError: Cannot read property '$$animLeave' of undefined

### ISSUE THREAD

**Issue by hani647** [angular-ui/ui-router#3516]
I explored a lot but can't find a way out of it. I've been using angular 1.6.4 and ui-router 1.0.0-beta.3.
Please help me how to make a work around it. Moreover I can see 2 ui-views when I call state my html looks like

```
    <div ui-view>

    </div >
```
but then I can see 2 views when calling state i.e. 

```
    <div ui-view>

    </div >
    <div ui-view>

    </div >
```
Any help would be really appreciated. Thanks

**Comment by niamleeson** [comment]
I'm running into the same issue. When the app renders, there are two ui-view's.

**Comment by jorsi** [comment]
I encountered this problem when transitioning from one sibling state to another. My setup is a parent 'admin' state, with many sub-states defined as 'admin.workCenters', 'admin.users', etc. Upon loading the first sub-state, it would load properly, however, transitioning to another sibling would rip out all the html up to the parent's _parent_ ui-view and never re-insert other siblings.

The problem fixed itself when changed the parent ui-view template from <ui-view></ui-view> to <div ui-view></div>. Not sure if this would help yourself, but maybe it would shed light on the issue.

**Comment by vladlep** [comment]
+1

**Comment by ms-dosx86** [comment]
+1
