### ISSUE TITLE
$transitions.onError does not allow redirection by returning TargetState

### ISSUE THREAD

**Issue by Bennit** [angular-ui/ui-router#3519]
My version of UI-Router is: 1.0.6

# Bug Report

#### Current Behavior:

TransitionHookFn returns a TargetState but no transition is made 

#### Expected Behavior:

if TransitionHookFn returns a TargetState, the application is routed towards it.

#### How to reproduce

https://gist.github.com/Bennit/01dc9acacbaa3a119ae2af2f0e1003a1

**Comment by alazzawimahmoud** [comment]
+1

**Comment by Bennit** [comment]
I've seen on https://github.com/angular-ui/ui-router/issues/3331 that they indicate the rejection of a resolve is not supposed to alter a transition; however from the docs it seems like $transitions.onError should be able to - which is truthy?

**Comment by aitrusgit** [comment]
+1 
I managed to workaround this by, instead of returning a TargetState, invoking `$state.go("recovery-state", {})`. However this strategy won't prevent $defaultErrorHandler from being triggered and polluting the console with errors.
