### ISSUE TITLE
Maximum call stack size exceeded error on transition with circular structure

### ISSUE THREAD

**Issue by AnWeber** [angular-ui/ui-router#3521]
This issue tracker is for Bug Reports and Feature Requests only.
Please direct requests for help to StackOverflow.  See http://bit.ly/UIR-SOF for details.

This is a:

- [ x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.6

# Bug Report

#### Current Behavior:

On transition with a parameter which has a circular struture a Maximum call stack size error is thrown. I think it happens in the defaulterrorhandler at json.stringify

#### Link to Plunker that reproduces the issue:

Demo: http://plnkr.co/edit/cHRBgo7JEfaZsfD4KP7Z?p=preview (the error happens on second button click)

**Comment by christopherthielen** [comment]
Fixed by https://github.com/ui-router/core/commit/2f1ae9a2884fc8e0279383d96cfd071235cbe480

**Comment by christopherthielen** [comment]
Apparently that didn't fix it
