### ISSUE TITLE
HTTP issue in $http request https and http

### ISSUE THREAD

**Issue by timyounes** [angular-ui/ui-router#3527]
Hello,

I have a problem in my angularjs $http request. When I send request to the API it was blocked by the browser like:
ERROR IN FIREFOX : Blocked loading mixed active content “http://www.example.com/rest/default/V1/integration/admin/token/”

ERROR IN CHROME: Mixed Content: The page at 'https://www.example.com/load.shtml#/register/pos/docs/2323232221555/new' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.example.com/rest/default/V1/integration/admin/token/'. This request has been blocked; the content must be served over HTTPS.

How can I fixed this problem? Any idea is accepted.

Thanks,
timyounes

**Comment by i23591326** [comment]
How does this relate to the ui-router?

**Comment by singhmohancs** [comment]
{{demoContent}}

**Comment by timyounes** [comment]
I think it is related to the same origin issue

**Comment by FlandersBurger** [comment]
I have the same issue going on but it is only one call to my API that seems to be encountering it, all other $http.post (and there are a lot of them) don't have this issue. CORS is already enabled in web.config
