### ISSUE TITLE
Controller is reloaded on $state.go despite notify set to false. 

### ISSUE THREAD

**Issue by dockinkong** [angular-ui/ui-router#3533]
Hello,

My version of UI-Router is: (1.5)

# Bug Report

#### Current Behavior:
Controller is reloaded with 
$state.go('myApp', { }, {
                        notify: false,
                        reload: false,
                        location: 'replace',
                        inherit: false
                    });

#### Expected Behavior:

Should the controller not reload with this options? I need to change the URL without reloading controller.

**Comment by danidev** [comment]
I have the same issue but I read that notify:false doesn't works anymore.
I didn't find a solution to change the location without reloading the controller.
Could somebody explain a new way to change the path of the page without reload the controller?

**Comment by nkoterba** [comment]
I've been struggling with this for over 2 days myself.  I need to update the URL (as well as the browser history record) without actually re-loading the page/controllers.

I've tried just about every combination possible using both deprecated and "supported" options and methods and have yet to figure out a working solution.

Most of the information I've read says to use 'dynamic' on your state definition params (if that's what's changing or you want to change).

However, I've found that doesn't update the URL *or* add an entry to browser history.

**Comment by Sharondio** [comment]
Never good when you find yourself on a fresh issue thread after fighting with something for the better part of 2 days.

**Comment by Sharondio** [comment]
For those still following along, checkout the comments about the usage of notify: https://github.com/angular-ui/ui-router/issues/1758

**Comment by shaggeh** [comment]
Is there a workaround we can follow?

**Comment by Sunny-Nishan** [comment]
> `$stateRegistry.register({name:state.name,
                                          url:'/'+state.stateUrlValue,
					template:element.content,
					controller:"stateController",
					reloadOnSearch:false								
});`

I too had the same problem in spite adding parameters in $state.go, it was still reloading the controller  Setting the value reloadOnSearch to false did the trick for me.

**Comment by guillaumevincent** [comment]
@shaggeh 

add `reloadOnSearch: false` in your routes as a workaround:

```
.state({
  name: "names",
  url: "names",
  component: "Names",
  reloadOnSearch: false, 
})
```

In your controller `$state.go("names", { param: 'newparams' });`

**Comment by maximilianschmid** [comment]
relates to https://github.com/angular-ui/ui-router/issues/3650

**Comment by maximilianschmid** [comment]
think dynamic parameters is what replaced notify:false option

**Comment by christopherthielen** [comment]
People generally used `notify: false` to stay on the same state, manually fetch different data, and update the URL (usually changing a parameter value).  However, `notify: false` was a bad idea because it introduced many edge cases and bugs that simply couldn't be reasoned about or worked around properly.

Dynamic parameters are intended to implement this most common use case, but in a way that isn't a horrible hack.  Here is the current docs for dynamic parameter which describes what they do: https://ui-router.github.io/ng1/docs/latest/interfaces/params.paramdeclaration.html#dynamic

**Comment by christopherthielen** [comment]
here's a simple dynamic parameter example: https://stackblitz.com/edit/ui-router-angularjs-dynamic-parameter?file=app.js

it uses `uiOnParamsChanged`: https://ui-router.github.io/ng1/docs/latest/interfaces/ng1.ng1controller.html#uionparamschanged

**Comment by dockinkong** [comment]
With so much delay, thanks...
