### ISSUE TITLE
Transitions not fired on initial application/state load

### ISSUE THREAD

**Issue by Adrian10988** [angular-ui/ui-router#3536]
This is a:

- [X] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: (1.0.6) 

# Bug Report

#### Current Behavior:
https://plnkr.co/edit/OwvQS0nErcCwvWEKbtZc?p=preview

If you visit the above plnkr you will see that there is no transition fired on the initial state load. You must select one of the links in order to trigger a transition.
#### Expected Behavior:
According to the docs: https://ui-router.github.io/guide/transitions#transition-triggers

A transition should fire whe "The application has just started, and the initial URL is being processed"
#### Link to Plunker that reproduces the issue:

https://plnkr.co/edit/OwvQS0nErcCwvWEKbtZc?p=preview

# Feature Request

(feature request here)

# General Query

Please direct general implementation questions to StackOverflow: 
http://stackoverflow.com/questions/ask?tags=angularjs,angular-ui-router

Please review the Sample Application which highlights common approaches:
https://github.com/ui-router/sample-app-ng1

- [X] I have already asked my question on StackOverflow and nobody could answer the question

- [X] I have already reviewed the sample application for examples of common approaches

- [X] I believe my question can only be answered by the UI-Router maintainers

(general query here)

**Comment by marcelinhov2** [comment]
Same here... =/

**Comment by rjmohammadww** [comment]
Any workaround for this issue. We are updating our code from ui-router 0.2.18 to ui-router 1.0.11.
For us, the $transition hooks in the controller are not fired on a page refresh, my totally uneducated guess is that the angular state events are fired before the ui-rotuer is done initializing. Because all of our $transition hooks in *.run* are working as expected. Is there any way to make angular wait for ui-router to initialize and then go on its way of firing events?

**Comment by kylemantesso** [comment]
Don't know if this helps, but onSuccess is fired, I just used that instead as it didn't impact my app.

**Comment by jbthoma** [comment]
We're having the same problem.

**Comment by LuisEGR** [comment]
still no solution?

**Comment by adriencohen** [comment]
@LuisEGR The solution is to move your transitions from your controller to .run()

**Comment by senyaak** [comment]
+1
As workaroung - in components run my code in $onInit and in $transition.on...

**Comment by dularion** [comment]
Is there any update for this?

**Comment by dularion** [comment]
We have implemented a workaround where we do 2 things: we register the transition listener and we check the current state. something like this: 

`someService.js`

```js
    function registerTransitionAndLoadListener(route, callback) {
      if(!_.isFunction(callback)){
        console.error('you need to provice a function callback for registerTransitionAndLoadListener. aborting.');
        return;
      }

      var onTransitionToHistorySuccesHook = $uiRouter.transitionService.onSuccess({
        to: route
      }, callback);

      if($state.is(route)){
        callback();
      }

      return onTransitionToHistorySuccesHook;
    }
```

`someController.js`
```js
var onTransitionToHistorySuccesHook = someService.registerTransitionAndLoadListener('multiposting.form.history', onTransitionToHistorySuccess);

function onTransitionToHistorySuccess(){
 //....
}
```

**Comment by qamhiehharri** [comment]
Same issue here.
