### ISSUE TITLE
Allow redirectTo to DI similar to resolve

### ISSUE THREAD

**Issue by mtpultz** [angular-ui/ui-router#3537]
This issue tracker is for Bug Reports and Feature Requests only.
Please direct requests for help to StackOverflow.  See http://bit.ly/UIR-SOF for details.

This is a:

- [ ] Bug Report
- [X] Feature Request
- [ ] General Query 

My version of UI-Router is: v1.0.6

# Feature Report

#### Current Behavior:

use of redirectTo only allows for injection of $transitions, which can then be used to get services via `$transition.injector.get('myService');`.

# Feature Request

It would be useful to be able to just DI into the redirectTo method instead similar to resolve.  This has come up in several applications where processing is required onRoute so that redirection can occur to a specific state within the module based on processing, which can't be done in a resolve since the initial route to be redirected is never rendered and appends an ID or other parameter for the next state (which will be rendered) after processing has occurred.  

```
  {
    name: 'pseudoAbstractState',
    url: '/processing',
    redirectTo: (myService, ...) => {
        'ngInject';
         // ...
        return new Promise((resolve, reject) => {
          resolve({
            state: 'render',
            params: { someId: id }
          });
        })
      }
    }
  },
  {
    name: 'render',
    // ...
  }
```

If done in a resolve you would need to inject $state and use $state.go, and then an error appears in the console saying the transition was superseded.

```
  {
    name: 'pseudoAbstractState',
    url: '/processing',
    resolve: {
      task: ($state, ...) => {
        'ngInject';
        // ...
        $state.go('render');
      }
    }
  },
  {
    name: 'render',
    // ...
  }
```

**Comment by christopherthielen** [comment]
In general we're moving away from injected APIs because ui-router is no longer specific to AngularJS.  The `redirectTo` callback always receives the `Transition` object (it is not injected by angular injector) in all cases.

You have two options to process resolves in a `redirectTo`:

1) Use the `UIInjector` from the `Transition` object to fetch the resolves:

```
trans.injector().getAsync('task').then(task => {
  return { state: render, params: { someId: task.id } };
});
```

2) If the AngularJS injection syntax "sugar" is your main concern, you can create your own `redirectTo`-like key such as `redirectInjected` by adding a state decorator.  The decorator would delegate to the `UIInjector`'s `getAsync` method.

```
app.config(function($uiRouterProvider) {
  $uiRouterProvider.stateRegistry.decorator('redirectTo', (stateObject, parentFn) => {
    const redirectInject = stateObject.self.redirectInject;
    if (!redirectInject) {
      return parentFn(stateObject);
    }
    
     function redirectTo(trans) {
      const uiInjector = trans.injector();
      const $injector = uiInjector.get('$injector'); // native injector
      const $q = uiInjector.get('$q');
      
      const diArgs = $injector.annotate(redirectInject);
      const promises = diArgs.map(diArg => uiInjector.getAsync(diArg));
      return $q.all(promises).then(argValues => {
        return redirectInject(argValues);
      });
    }
    stateObject.self.redirectTo = redirectTo;
    return redirectTo;
  });
})
```

Here's an example http://plnkr.co/edit/cwJMdE174FtIhTehKf9s?p=preview
