### ISSUE TITLE
Add method `has(resolvable)` to UI Injector to check if a resolvable is present or not

### ISSUE THREAD

**Issue by adamreisnz** [angular-ui/ui-router#3541]
This is a:

- [ ] Bug Report
- [x] Feature Request
- [ ] General Query 

I have dynamic modules and it would be nice if we could check if the [UI injector](https://ui-router.github.io/ng1/docs/1.0.0/interfaces/core.uiinjector.html) has a particular resolvable or not, e.g. with something like `transition.injector().has('foo')`. That way the transition won't fail and error if I try to get a non-existing module.

Angular has a similar mechanism in its own injector.

**Comment by adamreisnz** [comment]
Ok I see I had disabled transition logging so that's why I didn't see the error. However, I'll turn this into a feature request instead.

**Comment by deeganz** [comment]
I did the following as a workaround.

```
     $transitions.onSuccess({}, function (trans) {

            var to = trans.to();

            $rootScope.title = to.title || (to.resolve && to.resolve['resolveTitle'] ? trans.injector().get('resolveTitle') : null);

     });
```
