### ISSUE TITLE
Modify global resolve policy

### ISSUE THREAD

**Issue by adamreisnz** [angular-ui/ui-router#3542]
The [documentation](https://ui-router.github.io/ng1/docs/latest/interfaces/resolve.resolvepolicy.html) specifies:

> The policy for a given Resolvable is merged from three sources (highest priority first):
> 1) Individual resolve definition
> 2) State definition
> 3) Global default

But I can't find anywhere in the docs, nor on Stackoverflow, Google, or in this issue tracker, how to modify the global default. Is this possible, e.g. if I want all my resolvables to be EAGER?

**Comment by conor-mac-aoidh** [comment]
@adamreisnz +1

Just had a quick look through the release bundle `angular-ui-router.js` and it includes this block:

```javascript
/**                                                                                            
 * @coreapi                                                                                    
 * @module resolve                                                                             
 */ /** for typedoc */                                                                         
// TODO: explicitly make this user configurable                                                
var defaultResolvePolicy = {                                                                   
    when: "LAZY",                                                                              
    async: "WAIT"                                                                              
};  
```

So I guess its not configurable yet..

**Comment by pawlufelice** [comment]
This seems to still be an issue. Any ideas if/when this will be fixed please?
