### ISSUE TITLE
How to reload parent controller once every times i call it. 

### ISSUE THREAD

**Issue by Yacobus** [angular-ui/ui-router#3549]
I want to call controller once every time i change to tabs view. On first load it worked. But when i get back to opportunities list and load tabsOpp, the controller won't reload. I tried to set cache:false, and its call parent controller every time i change my child (change tabs). 
 I have defined the following states like this:

```js
.state('tabsOpp', {
        url: "/:oppNum",
        abstract: true,
        templateUrl: "templates/tabsOpp.html",
        controller: 'OpportunityCtrl'
    })

    .state('tabsOpp.opportunity', {
        url: "/opportunity",
        views: {
            'masterOpp': {
                templateUrl: "templates/opportunity.html"

            }
        }
    })

     .state('tabsOpp.opp-potential', {
         url: "/opp-potential",
         views: {
             'potentialOpp': {
                 templateUrl: "templates/opp-potential.html"

             }
         }
     })
```

**Comment by christopherthielen** [comment]
Provide `{ reload: true }` as a transition option.  

Using `$state.go`:

```
$state.go('tabsOpp', {}, { reload: true })
```

Using `ui-sref`

```
<a ui-sref="tabsOpp" ui-sref-opts="{ reload: true }>tabsOpp</a>
```

`cache: false` is not a ui-router option.  Perhaps you're using ionic?

**Comment by Yacobus** [comment]
I have try your code before and its not working on my case because parameter will be cleared every times i change my tabs and I don't want to reload my page every times i change my tabs. I solved it by passing my parameter to $rootScope. I'm using ionic. 
Thanks.
