### ISSUE TITLE
Missing EOL in package.json @ 1.0.9 breaks artifactory npm plugin

### ISSUE THREAD

**Issue by RecuencoJones** [angular-ui/ui-router#3550]
This is a:

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.9

# Bug Report

#### Current Behavior: 

Install from artifactory npm plugin fails.

#### Expected Behavior:

Installs correctly in v1.0.9

# Comment

Could you please add new line at the end of package.json in the next release?

It was [removed in 1.0.9](https://github.com/angular-ui/ui-router/commit/1c00ffd74b74c8956b213992356c44fb9dc7faaf#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) release and it might be causing this issue.

**Comment by nateabele** [comment]
This is a reasonable change to make (especially if you'd like to submit a PR), but if you want to consider this a bug, it's a bug in Artifactory.

**Comment by RecuencoJones** [comment]
@nateabele you are right, we are confused by the fact that this has never happened before with any other package, and probably not every package.json ends with new line.

It might be a problem with artifactory indeed, I will try to file an issue there too.

**Comment by christopherthielen** [comment]
Released 1.0.10
