### ISSUE TITLE
Wrong component destroying order

### ISSUE THREAD

**Issue by i23591326** [angular-ui/ui-router#3552]
I have a nested route chain /object/object123/controller/controller456/contrdeviceparam

when i navigate
/object/object123/controller/controller456/contrdeviceparam => /object/object123/controller/controller456
contrdeviceparam's component being destroyed and it triggers $onDestroy event whitch triggers component's onDestroyCallback "&" binding that is processed outside in corresponding router's resolve.

However, when i go
/object/object123/controller/controller456/contrdeviceparam => /object/object123
three components is being destroyed, but order of callbacks is:
controller=>controller456=>contrdeviceparam instead of opposite, i.e. parent component being destroyed earlier then it's child (???), and it breaks internal logic.

By the way i checked router's onEnter/onExit events and they are fires properly (contrdeviceparam =>controller456=>controller), but I had to abandon the use of this approach
because of the too long gap between onExit and onEnter

**Comment by christopherthielen** [comment]
Example http://plnkr.co/edit/w8NTPsTHjPExlm6Jcr36?p=preview

**Comment by YuriMasyanISS** [comment]
home => home.foo.bar =>  home: 

Transition #6-0: Started  -> "Transition#6( 'home'{} -> 'home.foo.bar'{} )"
trace.ts:207 Transition #6-0: <- Success  "Transition#6( 'home'{} -> 'home.foo.bar'{} )", final state: home.foo.bar
_main.js:34 onInit foo
_main.js:34 onInit bar
trace.ts:162 Transition #7-0: Started  -> "Transition#7( 'home.foo.bar'{} -> 'home'{} )"
trace.ts:207 Transition #7-0: <- Success  "Transition#7( 'home.foo.bar'{} -> 'home'{} )", final state: home
_main.js:35 onDestroy foo
_main.js:35 onDestroy bar

http://plnkr.co/edit/geKdD7IpUR2xsPtNhrcI?p=preview

i suppose bar must be destroyed before foo

**Comment by i23591326** [comment]
home => home.foo.bar => home:

Transition #6-0: Started -> "Transition#6( 'home'{} -> 'home.foo.bar'{} )"
trace.ts:207 Transition #6-0: <- Success "Transition#6( 'home'{} -> 'home.foo.bar'{} )", final state: home.foo.bar
_main.js:34 onInit foo
_main.js:34 onInit bar
trace.ts:162 Transition #7-0: Started -> "Transition#7( 'home.foo.bar'{} -> 'home'{} )"
trace.ts:207 Transition #7-0: <- Success "Transition#7( 'home.foo.bar'{} -> 'home'{} )", final state: home
_main.js:35 onDestroy foo
_main.js:35 onDestroy bar

http://plnkr.co/edit/geKdD7IpUR2xsPtNhrcI?p=preview

i suppose bar must be destroyed before foo

**Comment by christopherthielen** [comment]
Hmmm... I'm not sure there's anything that ui-router can do about this.  I wrapped the ui-views inside an `ng-if` and it has the same destroy order.  I guess I'm not sure what guarantees angularjs provides for component destroy order.  Can you do some more research on this?

Here's a forked plunker that shows the nested destroy happens in the same order when destroyed using `ng-if`: http://plnkr.co/edit/HbU3X2Qm4UUBsrBgdh6m?p=preview
