### ISSUE TITLE
Fails to load in Karma

### ISSUE THREAD

**Issue by onlywei** [angular-ui/ui-router#3553]
This issue tracker is for Bug Reports and Feature Requests only.
Please direct requests for help to StackOverflow.  See http://bit.ly/UIR-SOF for details.

This is a:

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.10

I have the following `karma.conf.js`:
```js
module.exports = function (config) {
  config.set({
    singleRun: true,
    browsers: ['ChromeHeadless'],

    files: [
      'node_modules/angular/angular.js',
      'node_modules/@uirouter/angularjs/release/ui-router-angularjs.js',
      'src/**/*.js',
      'test/**/*.js',
    ],

    plugins: [
      'karma-chrome-launcher',
      'karma-jasmine',
    ],

    colors: true,
    frameworks: ['jasmine'],
    reporters: ['progress'],
  });
};
```

# Bug Report

#### Current Behavior:
As soon as I run `karma start` with the above config, I get the following error:
```
INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
INFO [launcher]: Starting browser ChromeHeadless
INFO [HeadlessChrome 0.0.0 (Mac OS X 10.12.6)]: Connected on socket
HeadlessChrome 0.0.0 (Mac OS X 10.12.6) ERROR
  Uncaught TypeError: Cannot convert undefined or null to object
  at node_modules/@uirouter/angularjs/release/ui-router-angularjs.js:2009
```

#### Expected Behavior:

I expect the ui-router code to load and be available in my spec files so I can inject things like `$stateRegistry` to test my code.

**Comment by christopherthielen** [comment]
Hi, thanks for using ui-router.  

It looks like you're using the `@uirouter/angularjs` split bundle in your test harness (`ui-router-angularjs.js`).  The split bundle does not contain the core of uirouter (`@uirouter/core`).  I recommend you either add `'node_modules/@uirouter/core/_bundles/ui-router-core.js'` to your test harness, or use the legacy bundle (`'node_modules/@uirouter/angularjs/release/ui-router-angularjs.js'`) which also bundles the core code.  I recommend using the same bundles as you use in your released code.

**Comment by onlywei** [comment]
@christopherthielen wait, in my test harness code I **am** using the legacy bundle:
```node_modules/@uirouter/angularjs/release/ui-router-angularjs.js```
That's what it says in the original issue report.

This I believe to be the exact same bundle as I am using in the actual browser release code.

**Comment by christopherthielen** [comment]
@onlywei sorry I typed the wrong filename for "legacy bundle". I've now corrected my comment.  The legacy bundle is `angular-ui-router.js`.  My advice still stands that you should add `ui-router-core.js` to your karma setup.
