### ISSUE TITLE
UI-Router not working on Internet Explorer 10

### ISSUE THREAD

**Issue by AlexandreDenis** [angular-ui/ui-router#3555]
I used to work with version 0.2.0 of UI-Router which worked well on IE 10.
However since I updated to 1.0, the routing doesn't seem to work anymore.
I get an empty page. I read a lot of bug reports and SO topics but cannot find any answer.
Is UI-Router 1.0 supposed to work on IE 10?

I wanted to make a plunker to illustrate the bug but the sample app [https://ui-router.github.io/resources/sampleapp/](https://ui-router.github.io/resources/sampleapp/) doesn't work too on IE 10 so you can see the bug here: [https://ui-router.github.io/sample-app-angularjs/](https://ui-router.github.io/sample-app-angularjs/).

It would be good to have some returns about this bug. Is it normal that it doesn't work on IE 10 or is it definitively a bug?

**Comment by christopherthielen** [comment]
We didn't intentionally break IE10.  Looks like it's due to the use of a property named `default`

**Comment by christopherthielen** [comment]
I was able to fix sample app rendering in IE9 by doing the following things:

1) Adding `<!DOCTYPE html>` to the beginning of index.html https://github.com/ui-router/sample-app-angularjs/commit/fddff217ef978cb5b74273f4b36a4bffaa5e4dc7
2) Adding browser polyfills from polyfill.io https://github.com/ui-router/sample-app-angularjs/commit/15b893716d4e3fc1142a757ec62d6c00d39f1109
3) Choosing a babel preset with IE support (`es2015-ie`) https://github.com/ui-router/sample-app-angularjs/commit/4475733c339b8fb802e9042bdd4cc88b3c6adf1e

Note: the sample app uses flexbox, which IE9 does *not* support, so the rendering is quite broken. However, UI-Router itself works.

**Comment by simplyeleza** [comment]
This worked out fine for me. I am thankful.
