### ISSUE TITLE
Type definitions outdated

### ISSUE THREAD

**Issue by klmdb** [angular-ui/ui-router#3558]
This is a:

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: `0.4.2`

# Bug Report

#### Current Behavior:

Using `"@types/angular-ui-router": "1.1.38"` and `"typescript": "2.6.1"`, I can no longer build my project:
```
[tsl] ERROR in ...foobar.ts(7,12)
      TS4023: Exported variable 'foobar' has or is using name 'ui.IStateService' from external module angular but cannot be named.
```

tsconfig:
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "target": "es5",
    "declaration": true,
}
```

#### Cause
In `.../@types/angular-ui-router/index.d.ts`, the 'export type ...' block exports from namespace that has not been defined yet.

#### Fix
When I move the 'export type ...' code block below the namespace declaration (to the end the file), instead of the start, the issue is fixed.

#### Expected Behavior:

The @types/angular-ui-router should not block typescript compilation.

**Comment by christopherthielen** [comment]
This is an issue with the DefinitelyTyped type definitions (which are not maintained by the ui-router team).  Please file this issue here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues
