### ISSUE TITLE
Expose `defaultErrorHandler` from `$state` on `$stateProvider`

### ISSUE THREAD

**Issue by adamreisnz** [angular-ui/ui-router#3559]
This is a:

- [ ] Bug Report
- [x] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.10

# Feature Request
Make the `[defaultErrorHandler](https://ui-router.github.io/ng1/docs/latest/classes/state.stateservice.html#defaulterrorhandler)` method from StateService accessible in the configuration phase of Angular, so that we can apply custom error handling (like capturing errors with Sentry) in one place.

Currently, I need to to it in the config phase for Angular exceptions (using a decorator for `$exceptionHandler`) and then in the run phase for UI-Router, because the `defaultErrorHandler` method is only available on the `$state` injectable it seems, and not on any injectables available during the config phase.

It'd be great if the `defaultErrorHandler` method could be exposed on for example the `$stateProvider` in addition, allowing us to call it from the config phase.

**Comment by christopherthielen** [comment]
The `$stateProvider` facade is mostly still there for backwards compatiblity. You can inject the `$uiRouterProvider` (or `$uiRouter` at runtime) and access all the services through that reference. 


```
.config($uiRouterProvider => 
  $uiRouterProvider.stateService.defaultErrorHandler(...)
);
```

**Comment by adamreisnz** [comment]
Alright, will use that, thanks
