### ISSUE TITLE
Support for angular5

### ISSUE THREAD

**Issue by Finelf** [angular-ui/ui-router#3564]
After updating angular gives error

ERROR in node_modules/@uirouter/angular/lib/uiRouterNgModule.d.ts(4,10): error TS2305: Module '"PATH/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

**Comment by christopherthielen** [comment]
[`@uirouter/angular`](https://github.com/ui-router/angular/issues) supports angular 5 as of `1.0.0-beta.8`

See https://github.com/ui-router/angular/issues/155
