### ISSUE TITLE
http://localhost:63342/Food-Voting-App-FA003/app/index.html#!/login How to remove #! from this url. I used $locationProvider.html5Mode(true).hashPrefix('') in config file and <base href = "/"> in main landing page but it does not work. It shows error like this:  GET http://localhost:63342/assets/libs/angular/angular.js net::ERR_ABORTED  for all dependency files. Any solutions??

### ISSUE THREAD

**Issue by kailashshrestha** [angular-ui/ui-router#3566]
This issue tracker is for Bug Reports and Feature Requests only.
Please direct requests for help to StackOverflow.  See http://bit.ly/UIR-SOF for details.

This is a:

- [ ] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: (version)

# Bug Report

#### Current Behavior:

(current behavior here)

#### Expected Behavior:

(expected behavior here)

#### Link to Plunker that reproduces the issue:

http://bit.ly/UIR-Plunk

# Feature Request

(feature request here)

# General Query

Please direct general implementation questions to StackOverflow: 
http://stackoverflow.com/questions/ask?tags=angularjs,angular-ui-router

Please review the Sample Application which highlights common approaches:
https://github.com/ui-router/sample-app-ng1

- [ ] I have already asked my question on StackOverflow and nobody could answer the question

- [ ] I have already reviewed the sample application for examples of common approaches

- [ ] I believe my question can only be answered by the UI-Router maintainers

(general query here)

**Comment by blahblehblah** [comment]
try setting hashPrefix separately; 

$locationProvider.hashPrefix('');
$locationProvider.html5Mode(true);
while setting  <base href="/"> at the top of your <head>
