### ISSUE TITLE
Why didn't my routing event execute?

### ISSUE THREAD

**Issue by leoshuaige** [angular-ui/ui-router#3569]
$scope.$on('$stateChangeSuccess', function (event) {
               console.log(11111)
            });
console.log(11111)  Not printed on the console，use The version number is 1.0.3

**Comment by christopherthielen** [comment]
AngularJS `$stateChange*` events are deprecated and removed from ui-router 1.0+ in favor of transition hooks.  Read about it on the migration guide: https://ui-router.github.io/guide/ng1/migrate-to-1_0#state-change-events

There is a polyfill you can use to emulate the deprecated events.
