### ISSUE TITLE
why npm install the version is 0.4.3

### ISSUE THREAD

**Issue by Tony1952466760** [angular-ui/ui-router#3571]
I use `npm i -S angular-ui-router` , npm install the version is 0.4.3 . 
![image](https://user-images.githubusercontent.com/11804148/33547041-aea387c8-d91d-11e7-8d1e-9adf27846a2c.png)

I use `bower install angular-ui-router ` bower install the version is 1.0.10.
why npm din't update version.

**Comment by Narretz** [comment]
for npm use `npm install --save @uirouter/angularjs` 
This is in the tutorial

**Comment by christopherthielen** [comment]
Here's the blog  post announcing the change: https://ui-router.github.io/blog/uirouter-scoped-packages/

For some reason the dist-tags were broken.  As of today, I have updated the dist-tag and re-deprecated the npm package.  Users should now get a deprecation warning when installing `angular-ui-router`.

```
$ npm add --save angular-ui-router

npm WARN deprecated angular-ui-router@0.4.3: This npm package 'angular-ui-router' has been renamed to '@uirouter/angularjs'. Please update your package.json. See https://ui-router.github.io/blog/uirouter-scoped-packages/
npm WARN t@1.0.0 No description
npm WARN t@1.0.0 No repository field.
```
