### ISSUE TITLE
onRetain does not not fire

### ISSUE THREAD

**Issue by Mobiletainment** [angular-ui/ui-router#3572]
This is a:

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: uirouter/angularjs@1.0.11

# Bug Report

#### Current Behavior:

I have the following state declaration:

```
const state: Ng1StateDeclaration = {
            url: "/{typeName}/{id}",
            params: {id: null, typeName: null},
            onExit: [() => {
                console.log("onExit");
            }],
            onRetain: [() => {
                console.log("onRetain");
            }],
            views: ...
            reloadOnSearch: false
        };
```

#### Expected Behavior:

I'd expect the `onRetain` transition hook to be called, but it doesn't.
However, `onExit` is triggered just fine.

# General Query

Please review the Sample Application which highlights common approaches:
https://github.com/ui-router/sample-app-ng1

- [x] I have already reviewed the sample application for examples of common approaches

**Comment by christopherthielen** [comment]
Seems to work?  http://plnkr.co/edit/iA2M2WPtsRzUppYMqTbJ

Please provide a [plunker](bit.ly/UIR-Plunk1) or [stackblitz](https://stackblitz.com/edit/ui-router-angularjs) which demonstrates the issue
