### ISSUE TITLE
Upgrading version 1.0.6 to 1.0.11 breaks Karma test runner

### ISSUE THREAD

**Issue by sabousha** [angular-ui/ui-router#3576]
This is a:

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: (version)
1.0.6 & 1.0.11

# Bug Report

#### Current Behavior:
karma test is breaking when trying to upgrade to UI-Router 1.0.11.  Karma test is working fine on UI-Router 1.0.6

### On version 1.0.11 
Karma output:
![image](https://user-images.githubusercontent.com/8964621/33905245-fb88054e-df4b-11e7-95a6-84f1dac51d35.png)

Angular-ui-router function:
![image](https://user-images.githubusercontent.com/8964621/33775037-22f8c198-dc0b-11e7-99cc-de681761ef3c.png)

I do not think the issue is related to Karma.  Just posting it for context.  I think it is a bug in the UI router code.

edit: I've run through the versions backwards from 1.0.11, and 1.0.8 is where it starts to work.  ie 1.0.9 is the first failing version.

**Comment by sabousha** [comment]
Can anyone look at this?

**Comment by christopherthielen** [comment]
The bug isn't in ui-router  (we run tons of unit tests), it's in PhantomJS.  Update your phantomjs package to latest and it should work.  The change is related to using `Function.prototype`, which apparently isn't supported in phantomjs 1.9.8 (Which is pretty old)

**Comment by sabousha** [comment]
@christopherthielen , you were right.  How did you know that?  There was nothing in the log to point out PhantomJS version as the culprit.

**Comment by christopherthielen** [comment]
@sabousha I just happened to remember that phantomjs updated its ecmascript support (to ES5, maybe?) in the 2.x release.  We're using phantomjs 2.x to run the ui-router unit tests and it doesn't have any trouble with `Function.prototype`

**Comment by sabousha** [comment]
Good call. Thanks! Starred!
