### ISSUE TITLE
State's data property not inherited

### ISSUE THREAD

**Issue by EmhyrVarEmreis** [angular-ui/ui-router#3577]
This is a:

- [X] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.0-beta.9 (from uirouter/angular-hybrid: 3.1.7)

# Bug Report
I have the following states:
```javascript
{
    name:     'test',
    data:     {
        param2: 'value2'
    }
},
{
    name:   'test2',
    parent: 'test',
    url:    '/test',
    data:   {
        param1: 'value1'
    },
    views:  {
        '@': {
            component: TestComponent
        }
    }
}
```
And I have also this transition hook:
```javascript
this.transitionService.onSuccess({to: '**'}, transition => {
    console.log(transition.to().data);
});
```
And the problem is that in console I see only `{ param1: 'value1'}` insetad of `{ param1: 'value1', param2: 'value2'}`. As far as i know, the `data` property from parent state should be inherited in child states, but it is not.

**Comment by sabousha** [comment]
This isn't a bug - I'd post to StackOverflow for an answer. most people here won't

**Comment by EmhyrVarEmreis** [comment]
@sabousha I do not understand. It is not a bug? I think that according to docs It should behave as I expected.

**Comment by sabousha** [comment]
@EmhyrVarEmreis , I'm sorry -- it very well might be.  I can't know without looking into it.  I thought you were just being lazy. I've deleted my old post so not to clutter the thread.

**Comment by christopherthielen** [comment]
@EmhyrVarEmreis this `data` property is inherited using prototypal inheritance.  This is working as expected, as far as I can tell.  In the console, expand the proto property of the object and you should see the parent state's data.

Here's a plunker which demonstrates this: http://plnkr.co/edit/5D1qv4u2LCYlacIxByds?p=preview

<img width="597" alt="screen shot 2017-12-20 at 3 44 00 pm" src="https://user-images.githubusercontent.com/2053478/34234187-77868816-e59e-11e7-8ff0-1fa8f28bfa34.png">
