### ISSUE TITLE
Transition with all the data remains in heap - memory leak?

### ISSUE THREAD

**Issue by attrobit** [angular-ui/ui-router#3603]
This is a (check one box):

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: (type version)
1.0.12, but the problem also exists in version 1.0.5

# Bug Report
#### Current Behavior:
When switching between states, the JS-Heap increase and get not garbage collected. See the following screenshot.
![uirouter-leak1](https://user-images.githubusercontent.com/14911994/34826648-b360ff2a-f6d7-11e7-973b-65570c96ea42.png)

For the example above i used the uirouter example in [plunker](https://plnkr.co/edit/6eQV15?p=preview).

As i analyzed the heap in detail i saw that the number of Transition-Objects increase with time.

#### Expected Behavior:
The JS-Heap get garbage collected after switching back to previous state.

#### Link to Plunker or stackblitz that reproduces the issue:
You can reproduce the problem with the uirouter example app in plunker: [example](https://plnkr.co/edit/6eQV15?p=preview)

Just switch multiple times between the state "hello" and "about".

**Comment by attrobit** [comment]
similar issuer: #21

**Comment by attrobit** [comment]
Similar issuer: https://github.com/ui-router/angular/issues/21

**Comment by christopherthielen** [comment]
Please try your experiment again, but this time click the "collect garbage" button before stopping the profiler (it is the small trash can icon next to the "Memory" checkbox in your screenshot).  My tests show that memory use is not increasing significantly.  

Applications (and therefore, ui-router) do not have any control over triggering garbage collection.  It's done completely at the javascript runtime's discretion.

See this comment for more details on reporting memory leak bugs: https://github.com/angular-ui/ui-router/issues/545#issuecomment-277092153

**Comment by attrobit** [comment]
Thanks for your reply.

I looked more in Detail by doing a memory heap dump. When i do a heap dump via memory -> take heap snapshot, chrome do a garbage collection before. I did a heap snapshot on hello state, about state and again hello state. The number of memory increase constantly. And i recognized that for every state change a new "Transition"-Object retains in the heap. See the following screenshots.

1. Hello State:
![state1](https://user-images.githubusercontent.com/14911994/34917808-54e22674-f94b-11e7-95a0-e5d42aa1e045.png)

2. About state:
![state2](https://user-images.githubusercontent.com/14911994/34917812-5b05fff8-f94b-11e7-97c0-5bc34c4297e0.png)

3. Hello State:
![state3](https://user-images.githubusercontent.com/14911994/34917815-6067704e-f94b-11e7-9206-aad45d804171.png)

**Comment by christopherthielen** [comment]
for clarity, did you force a garbage collection between each heap dump?

**Comment by christopherthielen** [comment]
This is an issue in uirouter/core.  Follow this related issue: https://github.com/ui-router/core/issues/55

**Comment by attrobit** [comment]
The leak still exist. Testet with Version 1.0.14 ([example](https://plnkr.co/edit/Z3pswRBJV1rM8zhyCpnw?p=preview))

JS-Heap over time (Switched multiple times between hello and about state):
![uirouter-leak-1014](https://user-images.githubusercontent.com/14911994/35736104-1cc2a760-0827-11e8-9936-6c54f96a3e5e.png)

The number of Transition-Objects still increases. See the foolowing heap-dump.
![uirouter-leak-heap-1014](https://user-images.githubusercontent.com/14911994/35736123-2f33daf4-0827-11e8-8bd9-e4cbfa2599cb.png)

**Comment by christopherthielen** [comment]
reopened https://github.com/ui-router/core/issues/55
