### ISSUE TITLE
$state.go invalid Transition not triggering global error handlers Transition.onError and StateService.defaultErrorHandler

### ISSUE THREAD

**Issue by Noah-Silvera** [angular-ui/ui-router#3610]
This is a (check one box):

- [X] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: (1.0.13)

# Bug Report

#### Current Behavior:

When `$state.go` is passed an invalid state name with invalid state parameters, the rejection does not call the `defaultErrorHandler` or the `Transition.onErrorHandler`

Example - I call `$state.go('invalidStateNameItDoesntExist')`.
If i add a `.then((err)=>{})` handler, this is called, but the global error handlers are NOT called.

#### Expected Behavior:

Since this is a transition error, I expect the global error handlers to be called so I can handle this failed transition globally with a redirect

error message captured from the promise error handler

`Transition Rejection($id: 0 type: 4, message: This transition is invalid, detail: Could not resolve 'invalidState' from state 'home')`

#### Link to Plunker or stackblitz that reproduces the issue:
http://plnkr.co/edit/282gLW90RoRuqUUQGmGH?p=preview

**Comment by adamreisnz** [comment]
May be a duplicate of https://github.com/angular-ui/ui-router/issues/3212

**Comment by silentFred** [comment]
Any movement on this? Also experiencing the same issue
