### ISSUE TITLE
$state.target('login') Not working

### ISSUE THREAD

**Issue by jeprojects** [angular-ui/ui-router#3612]
This is a (check one box):

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.13

# Bug Report

#### Current Behavior:

When issuing $state.target('login'), it isn't redirecting. I have enabled debugging and here is the output:

> Transition #0-0: <- Success  "Transition#0( ''{} -> '/c'{} )", final state: /c

If I used $state.go('login') everything works fine, but there is an error: "The transition has been superseded by a different transition"

#### Expected Behavior:

It should redirect to 'login'

**Comment by jutaz** [comment]
That error is expected, as it’s an internal “error” for UI.router, which tells it to abort current transition target, and switch to the new one.

**Comment by adrianboimvaser** [comment]
How do I differentiate it from a real error, say a resolve being rejected?
