### ISSUE TITLE
tail function returns undefined when an object is expected

### ISSUE THREAD

**Issue by NgMomentum** [angular-ui/ui-router#3620]
This issue tracker is for Bug Reports and Feature Requests only.

Please direct requests for help to StackOverflow.
See http://bit.ly/UIR-SOF for details.

This is a (check one box):

- [ ] Bug Report
- [x ] Feature Request
- [ ] General Query 

My version of UI-Router is: v1.0.12

# Feature Request

The current version of UI-Router has the function tail() being called in places that expect an object to be returned. Apparently, this doesn't happen very often (ever?) since this hasn't been raised before. Anyway, my solution was to add this function:

`	function tail_state(arr) {
		var output;

		if (arr && arr.length) {
			output = arr[arr.length - 1];

			if (isObject(output) && output.state) {
				return output;
			}
		} else {
			console.warn('ui.router - tail_state -> no or empty input array.');
		}

		return { state: {} };
	}`

Now, all calls to "tail" that were expecting an object with a "state", will get one. Not sure this is a good way to clean this up, but it does fix the inconsistency currently in the code.

**Comment by christopherthielen** [comment]
`tail` is general purpose, and doesn't always return an object with a state property.  I'd prefer to fix the code that is calling tail on a 0-length array.  Can you provide details on when this scenario happens?

**Comment by NgMomentum** [comment]
Hi Chris. Not really able to help much with "when" this occurs, as I'm
using a modified version of AngularJS. I do lots of "on demand" loading of
scripts, templates, css and the like, so it is probably just a timing issue
on my side that isn't necessarily std to AngularJS. In some parts of my
code execution, my version is faster, which has revealed problems with
other third party scripts as well. Anyway, at least its documented.

Cheer.
