### ISSUE TITLE
Transitions are not cleared

### ISSUE THREAD

**Issue by WidoBurg** [angular-ui/ui-router#3630]
This issue tracker is for Bug Reports and Feature Requests only.

Please direct requests for help to StackOverflow.
See http://bit.ly/UIR-SOF for details.

This is a (check one box):

- [ x ] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.14

# Bug Report

#### Current Behavior:

Is not cleaning transitions after garbage collect.

#### Expected Behavior:

According to https://github.com/ui-router/core/commit/7f2aed1 which is release in 1.0.14 I would expect that going back and forth between 'Hello' and 'About' the transitions are set to one after the garbage collected has done explicit. But they are not. In my scenario I switched 10 times with a result of 10 Transitions. 
![transitions are not removed](https://user-images.githubusercontent.com/8705247/35679087-19170b50-0756-11e8-94bf-1a049e88f6b5.png)

#### Link to Plunker or stackblitz that reproduces the issue:

https://plnkr.co/edit/ZIgUQodBQ8RiG19w608y?p=preview

**Comment by wawyed** [comment]
Seems to be fixed on version 1.0.15.
