### ISSUE TITLE
Getting TypeError: s.get is not a function on minified file

### ISSUE THREAD

**Issue by halbano** [angular-ui/ui-router#3635]
[Here](https://stackoverflow.com/questions/48604576/problems-with-ui-router-and-its-links-on-heroku/48604958#48604958) I have posted a question in SO. Off course the issue has nothing to do with Heroku, I am suspecting of something wrong on minified file and I was able to reproduce the issue locally using my production setup. 

My version of Angular is: 1.6.8
My version of UI-Router is: 1.0.0

#### Current Behavior:

I have a sidebar with clickable items defined using ui-sref. For any reason the links are not being clickable and when clicked they are launching an error that seems to be related with the router. 

A Screenshot of the console is: 

![screen shot 2018-02-04 at 1 01 09 pm](https://user-images.githubusercontent.com/5341623/35779425-829786c0-09ab-11e8-9a19-3ce0699f203b.png)

**Comment by halbano** [comment]
I have to add that if I remove the ui-sref-active directive from the list items the navigation works. The issue seems to be kind of conflict between the ui-sref-active and ui-sref. Any help is really appreciated

**Comment by christopherthielen** [comment]
Hi @halbano 
That error message is coming from this line: https://github.com/angular-ui/ui-router/blob/78e398e6cb1dd4e63f84f9ba2d88199d3ff38227/src/directives/stateDirectives.ts#L619

Recommend you upgrade to latest `@uirouter/angularjs` which is 1.0.15 and see if you still get the error.  If so, please put a breakpoint in that spot and tell me what is the value of `s` (which is really `$state`).  

I don't see any bug in the source code, but I do recall somebody reported an issue related to minified builds some time in the past, maybe it was version 1.0.0.

**Comment by christopherthielen** [comment]
This is the issue I was thinking of:  https://github.com/angular-ui/ui-router/issues/3287 

It's a bug in uglifyjs, or the gulp plugin for uglifyjs.  Try updating your dependencies, I think it will fix it.  Closing in hopes of that.  Reopen if not!
