### ISSUE TITLE
Transition Hook Firing Multiple Times

### ISSUE THREAD

**Issue by MNguyen1130** [angular-ui/ui-router#3644]
This issue tracker is for Bug Reports and Feature Requests only.

Please direct requests for help to StackOverflow.
See http://bit.ly/UIR-SOF for details.

This is a (check one box):

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: (1.0.3)

# Bug Report

#### Current Behavior:

A Transition Hook is being executed multiple times. Plunker example showcasing this provided.

#### Expected Behavior:

Transition Hook should only execute once.
Should be similar to what's to what's on this Plunker: https://plnkr.co/edit/c6ySScGZFhInrhuj0SFK?p=preview
Open up the devtools console and click between Hello and About.

#### Link to Plunker or stackblitz that reproduces the issue:
https://plnkr.co/edit/YaVCJfGEtPOS5JNSLElR?p=preview

Instructions:
1. Open up dev tools
2. Go to console
3. Click between the Hello and About links several times
4. Look at console logs. Parts will be repeat N times, where N is the number of times the 'Hello' link has been clicked.

#### Other Notes
Not sure if my implementation is incorrect. Differences between two Plunkers:
1. Multiple controllers in the one with issues
2. Controller is provided to the state

Thanks

**Comment by OlofFredriksson** [comment]
Hello! 
I'm pretty sure you need to deregister the transitions once the controller is destroyed to avoid this problem.

```
var deregisterFn = $transitions.onBefore(...)


$onDestroy() {
  deregisterFn()
}
```

Source: https://github.com/angular-ui/ui-router/issues/2930

**Comment by christopherthielen** [comment]
@OlofFredriksson is correct, you need to clean up hooks that are registered inside a controller.  

Here is a forked plunker that demonstrates the difference: https://plnkr.co/edit/iEGFqh8DEpJhMA31sni4?p=preview
