### ISSUE TITLE
State successfully transitions into another state but the template remains de same

### ISSUE THREAD

**Issue by prochafilho** [angular-ui/ui-router#3673]
This issue tracker is for Bug Reports and Feature Requests only.

Please direct requests for help to StackOverflow.
See http://bit.ly/UIR-SOF for details.

This is a (check one box):

- [ ] Bug Report
- [ ] Feature Request
- [x ] General Query 

My version of UI-Router is: (type version)
    @uirouter/angularjs  1.0.1

# Bug Report

#### Current Behavior:

(type current behavior here)
I have a controller method to call another state when a button is pressed. I am using $state.go to transition to a different state programmatically. The template does not change after the call to $state.go. I have attached a Transition Hook, and it says it transitioned successfully but, to no avail. I noticed that the controller for the component that is being rendered does not gets instantiated.

#### Expected Behavior:

(type expected behavior here)
To transit into a different state and the template to reflect the current state. 

#### Link to Plunker or stackblitz that reproduces the issue:

( if you want a response to your issue, provide a way to reproduce it )
( http://bit.ly/UIR-Plunk1 )
( https://stackblitz.com/edit/ui-router-angularjs )

# Feature Request

(type feature request here)

# General Query

Please direct general implementation questions to StackOverflow: 
http://stackoverflow.com/questions/ask?tags=angularjs,angular-ui-router

Please review the Sample Application which highlights common approaches:
https://github.com/ui-router/sample-app-angularjs

- [x ] I have already asked my question on StackOverflow and nobody could answer the question

- [ x] I have already reviewed the sample application for examples of common approaches

- [x ] I believe my question can only be answered by the UI-Router maintainers

(type general query here)

**Comment by christopherthielen** [comment]
Please post a reproduction using the links provided (stackblitz or plunker).  Link to your stackoverflow question.  This issue doesn't provide any details, and will be closed because of that.
