### ISSUE TITLE
could tell me the differences between v1.x and v0.2?

### ISSUE THREAD

**Issue by WilkinWendy** [angular-ui/ui-router#3676]
when I load v1.x to my angularjs project,it throws an error.
I debugged it and found ng_from_import is undefind.
but v0.2 works ok because the implement differs a little.
Can anybody explain it for me? I'm confused with it.

**Comment by christopherthielen** [comment]
Are you using requirejs by any chance?   Here are two (duplicate?) issues I find when searching for `ng_from_import`:

https://github.com/angular-ui/ui-router/issues/3495
https://github.com/angular-ui/ui-router/issues/3257#issuecomment-286504197
