### ISSUE TITLE
stateParams doesn't receive value if it's didn't showed in url

### ISSUE THREAD

**Issue by marcosdefina** [angular-ui/ui-router#3677]
obj = url: '/{a}'
----metaTags:
--------title: stateParams.b
$stateProvider.state('newState',obj)

If I didn't put {b} in url, stateParams.b won't show up.

**Comment by jegesh** [comment]
[This](https://stackoverflow.com/questions/20632255/angularjs-pass-an-object-into-a-state-using-ui-router) might help you

**Comment by christopherthielen** [comment]
If you want to pass params without including them in the URL, use the [`params` property of a state definition](https://ui-router.github.io/ng1/docs/latest/interfaces/state.statedeclaration.html#params):

```
var state = {
  name: 'foo',
  url: '/foo',
  params: { 
    myParam: null
  }
}
```

Now you can use `$state.go('foo', { myParam: someObject })`.
Note that the parameter won't be retained after a  full page reload (or bookmarks).

**Comment by marcosdefina** [comment]
Sorry for the late reply, but thank you for taking the time to see it.
