### ISSUE TITLE
stateParams cannot get current params when using stateful dialog

### ISSUE THREAD

**Issue by cran208** [angular-ui/ui-router#3679]
This is a (check one box):

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.15

# Bug Report

Hi,
I use transitions.onEnter to open a stateful dialog:
```
    let enterDialogCriteria = {
        entering: ($state) =>$state.data.dialog
    };

    let showDialog = ($transition$) => {
    		'ngInject';
        DialogService.open($transition$.$to().data.dialog)
    };
    $transitions.onEnter(enterDialogCriteria, showDialog);
```

However, when I inject the stateParams and state in the target dialog controller, I can not get the params which are passed from previous state.

It seems to be a new bug because it worked before I update the ui-router package.

Or is there another way to open a stateful dialog?

**Comment by sajangurung2015** [comment]
sorry for the delay. issue will be resolved today.
