### ISSUE TITLE
Bug in duplicate state name checking when using 'parent' definitions

### ISSUE THREAD

**Issue by marklagendijk** [angular-ui/ui-router#368]
Currently there are [3 ways](https://github.com/angular-ui/ui-router/wiki/Nested-States-%26-Nested-Views) of defining states:
1. Using 'dot notation'. For example `name: 'contacts.list'`
2. Using the parent property with the parent name as string. For example: `parent: 'contacts'`
3. Using the parent property with the parent object. For example `parent: contacts` (where 'contacts' is an stateObject)

What you would expect is that method 2 and 3 would resolve the name to the 'dot notation'. However, currently this doesn't seem to happen. Because of this the code which checks for duplicate stateNames wrongfully throws errors when 2 children of different parents have the same name.
For example:
``` js
$stateProvider
	.state({
		name: 'contacts',
		templateUrl: 'contacts.html'
	})
	.state({
		name: 'list',
		parent: 'contacts',
		templateUrl: 'contacts.list.html'
	})
	.state({
		name: 'products',
		templateUrl: 'products.html'
	})
	.state({
		name: 'list',
		parent: 'products',
		templateUrl: 'products.list.html'
	});
```
Or object notation:
``` js
var contacts = {
	name: 'contacts',
	templateUrl: 'contacts.html'
};
var contactsList = {
	name: 'list',
	parent: contacts,
	templateUrl: 'contacts.list.html'
};
var products = {
	name: 'products',
	templateUrl: 'products.html'
};
var productsList = {
	name: 'list',
	parent: products,
	templateUrl: 'products.list.html'
};

$stateProvider
	.state(contacts)
	.state(contactsList)
	.state(products)
	.state(productsList)
```
Both throw an error:
```
Error: [$injector:modulerr] Failed to instantiate module `APP_MODULE` due to: State 'list'' is already defined
```
While defining this example using method 1 does work:
```js
$stateProvider
	.state({
		name: 'contacts',
		templateUrl: 'contacts.html'
	})
	.state({
		name: 'contacts.list',
		templateUrl: 'contacts.list.html'
	})
	.state({
		name: 'products',
		templateUrl: 'products.html'
	})
	.state({
		name: 'products.list',
		templateUrl: 'products.list.html'
	});
```

**Comment by christopherthielen** [comment]
I think this ship has long since sailed.

The name used to register the state is the name you use to reference the state (in, e.g., `ui-sref`).

"Dot notation" in a state name implicitly chooses the parent state.  It's now an error to specify a parent using dot notation *and* using the `parent: `property.  You have to use one or the other.

I.e., this is an error:
```js
.state({
  name: 'home.foo',
  parent: 'home'
})
```

It should either be 
```
.state({ name: 'home.foo' })
```
or
```
.state({ name: 'foo', parent: 'home' });
```
