### ISSUE TITLE
What happened to Cloudflare and CDN support after version 1.0.3?

### ISSUE THREAD

**Issue by spiffy2man** [angular-ui/ui-router#3683]
This is a (check one box):

- [ ] Bug Report
- [ ] Feature Request
- [X] General Query 

My version of UI-Router is: (type version)
1.0.3

# General Query

- [ ] I have already asked my question on StackOverflow and nobody could answer the question

- [ ] I have already reviewed the sample application for examples of common approaches

- [X] I believe my question can only be answered by the UI-Router maintainers

Why aren't newer versions of the angular ui router being published to CDNs in cloudflare after version 1.0.3? There is nothing in the changelog to indicate why support for CDNs disappeared for later versions. What changed and why? Was this intentional? Will you please bring back the CDNs?

Support for bower was also dropped. I am fine with this change, but again, the changelog doesn't give a reason for this change, or even indicate that it was going to happen. Was this also intentional?

**Comment by christopherthielen** [comment]
> What changed and why? 

1.0.3 was the last release published using the old npm package `angular-ui-router`.  All subsequent releases are released as `@uirouter/angularjs`.  I don't recall how we initially got added to cloudflare, and I'm not sure how to have them pull from the new package name

> Was this intentional? 

nope, we simply [switched to scoped packages](https://ui-router.github.io/blog/uirouter-scoped-packages/)

> Will you please bring back the CDNs?

It's probably reasonable to publish to both npm packages.  I'll see if we can automate this in our release scripts.

> Support for bower was also dropped.

No, bower is still supported (see this recent bug report https://github.com/angular-ui/ui-router/issues/3687 and all new versions of ui-router are listed).  However, we highly recommend dropping bower yourself ([the bower team recommends the same thing](https://bower.io/)).

**Comment by spiffy2man** [comment]
Thank you, thank you, thank you!!!

Also, we are in the process of moving from bower to npm, but legacy apps aren't finished. :)

Sorry about missing bower. Not sure what I was looking at.
