### ISSUE TITLE
Implementing Route Guards in UI Router states with angular 4

### ISSUE THREAD

**Issue by phanivaranasi** [angular-ui/ui-router#3685]
Hi,
I need assistance in implementing route guards in angular 4 with ui router.

Below is my repo
https://github.com/phanivaranasi/coalmines

**Comment by phanivaranasi** [comment]
Hi 
Any can help me out in fixing.

**Comment by christopherthielen** [comment]
Hi!  Github issues are reserved for bugs and feature requests, not for help requests.

Please read through this guide for how to set up a transition hook: https://ui-router.github.io/guide/transitionhooks#redirecting-a-transition
