### ISSUE TITLE
NOWAIT and "Possibly unhandled rejection"

### ISSUE THREAD

**Issue by Anber** [angular-ui/ui-router#3695]
- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.16
My version of AngularJs is: 1.6.7

# Bug Report

#### Current Behavior:

There is a "possibly unhandled rejection" when a resolvable value with NOWAIT has a crashed dependency.

#### Expected Behavior:

Maybe, the same behavior as a resolvable with WAIT.

#### Link to Plunker that reproduces the issue:

http://plnkr.co/edit/r8ucyvQs9LFYZUNtcCpy?p=preview

**Comment by christopherthielen** [comment]
Hi @Anber  I'm getting a 404 not found for that plunker ID.  Can you find it and post a new URL?

**Comment by Anber** [comment]
It seems to be ok.
Can you try this [one](http://plnkr.co/edit/jYbhhz?p=preview)?

**Comment by Anber** [comment]
Something wrong with plnkr. I've move sample to [stackblitz](https://stackblitz.com/edit/ui-router-angularjs-kiivtw).
