### ISSUE TITLE
Cannot install @uirouter/core@5.0.3 (and pretty much any other version of this package)

### ISSUE THREAD

**Issue by jefim** [angular-ui/ui-router#3701]
This is a (check one box):

- [X] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.3 (type version)

# Bug Report

#### Current Behavior:

When trying to npm install @uirouter/core@5.0.3 it gives me the following:
```
42 verbose type Error
43 verbose stack Error: sha1-4rWx5FGQ4gxnuk4VwBPeXU4MyrM= integrity checksum failed when using sha1: wanted sha1-4rWx5FGQ4gxnuk4VwBPeXU4MyrM= but got sha1-IdCuSGvR9IMYE7qZUP9sS4dIDmM=. (48841 bytes)
43 verbose stack     at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:275:19)
43 verbose stack     at emitNone (events.js:111:20)
43 verbose stack     at Transform.emit (events.js:208:7)
43 verbose stack     at endReadableNT (_stream_readable.js:1056:12)
43 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
43 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
44 verbose cwd /Users/jefimborissov/Work/testnpm
45 verbose Darwin 17.5.0
46 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@uirouter/core@5.0.3"
47 verbose node v8.9.1
48 verbose npm  v5.6.0
49 error code EINTEGRITY
50 error sha1-4rWx5FGQ4gxnuk4VwBPeXU4MyrM= integrity checksum failed when using sha1: wanted sha1-4rWx5FGQ4gxnuk4VwBPeXU4MyrM= but got sha1-IdCuSGvR9IMYE7qZUP9sS4dIDmM=. (48841 bytes)
51 verbose exit [ 1, true ]
```

Trying to install latest also results in same error, but checksums are different. Reproduced on at least two machines. NPM cache cleaning does not help.

#### Expected Behavior:

Package is properly installed

- [ ] I have already asked my question on StackOverflow and nobody could answer the question
- [ ] I have already reviewed the sample application for examples of common approaches
- [X] I believe my question can only be answered by the UI-Router maintainers

**Comment by mitsos1os** [comment]
Same exact issue on a completely clean (Docker container) environment using **Node V10.1.0** and **npm v5.6.0** when trying to install `@uirouter/angularjs` so there must be something going on with whole **uirouter** scope

**Comment by jefim** [comment]
Umm.. ok. I think that this just fixed... itself?.. No idea what happened there but I don't get errors anymore. I have no idea what the issue was, but it is now installing properly... Some NPM internal problem I guess...
