### ISSUE TITLE
is there any way to set params dynamically, not param values but params as params ?

### ISSUE THREAD

**Issue by dharitdesai** [angular-ui/ui-router#3705]
This issue tracker is for Bug Reports and Feature Requests only.

Please direct requests for help to StackOverflow.
See http://bit.ly/UIR-SOF for details.

This is a (check one box):

- [ ] Bug Report
- [ ] Feature Request
- [X] General Query 

My version of UI-Router is: (1.0.18)

# General Query

Please direct general implementation questions to StackOverflow: 
http://stackoverflow.com/questions/ask?tags=angularjs,angular-ui-router

Please review the Sample Application which highlights common approaches:
https://github.com/ui-router/sample-app-angularjs

- [ ] I have already asked my question on StackOverflow and nobody could answer the question

- [ ] I have already reviewed the sample application for examples of common approaches

- [X] I believe my question can only be answered by the UI-Router maintainers

(type general query here)
Is there any way to set params dynamically, not param values but params as params ?
In my case, I have a dynamic form comes from an api, and the fields in the form I want to be a param of the state, so that I don't have to reload whole state and just refresh the contents as we can do right now in dynamic: true in a param in state definition. 
   

so for example 

```
$stateProvider
.state('a', {
    url: '/abc',
    component: 'a',
    resolve: {
       filters: {//backend call for get the filter fields}
    })
.state('a.b', {
    url: '/search', 
    params: { //this object needs to be dynamic based on the filters i received in the parent state
     filter1 : {dynamic : true}, filter2: {dynamic:true}, filter3: {dynamic: true} ..... 
    }
    })
})
```

**Comment by christopherthielen** [comment]
This isn't currently possible.  One feature that I'm interested in exploring (which would probably help with this) is a wildcard param on a state for query params.  The API might be something like `url: '/search?*'`.  For this to work, we'd have to add wildcard support in ui-router core.  There are probably corner cases and gotchas, but I'm open to trying it.  Unfortunately, I don't have as  much time as I'd like to work on ui-router.
