### ISSUE TITLE
uiOnParamsChanged not fired if used with componentProvider

### ISSUE THREAD

**Issue by Maximaximum** [angular-ui/ui-router#3707]
This is a (check one box):

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: (type version)
1.0.5

# Bug Report

#### Current Behavior:

Clicking the "1" and "2" links inside the stackblitz app does not change the displayed param value because component's `uiOnParamsChanged` method is never called. However, if you comment away the lines 22-24 and uncomment line 21 (i.e., use `component` instead of `componentProvider` in the state definition), everything works just as expected.

#### Expected Behavior:
Clicking the "1" and "2" links inside the stackblitz app should change the displayed param value to, respectively, "1" or "2", because the component's `uiOnParamsChanged` is called whenever a state param value changes.

#### Link to Plunker or stackblitz that reproduces the issue:
https://stackblitz.com/edit/ui-router-angularjs-budr1v

**Comment by Maximaximum** [comment]
The reason for the issue seems to be lying in this check: https://github.com/angular-ui/ui-router/blob/5fb93d042d5833514357d6e7956a4cf85be26900/src/directives/viewDirective.ts#L434

**Comment by Maximaximum** [comment]
@christopherthielen sorry to bother you, but are there any news regarding this issue?

**Comment by christopherthielen** [comment]
@Maximaximum thanks for the nice bug report.  will be fixed in the next release.

**Comment by Maximaximum** [comment]
@christopherthielen could you please give a hint on when a new version is going to be released?
