### ISSUE TITLE
Allow empty states (aka: optional ui-sref)

### ISSUE THREAD

**Issue by frapontillo** [angular-ui/ui-router#371]
I have noticed that the `ui-sref` directive is not optional, meaning I have to specify a state. I think this is too much of a constraint, because depending on the bound object on the `a` tag, one would want to bind to `ng-href` OR to `ui-sref`.

Is this somehow possible?

**Comment by dapids** [comment]
+1. I totally quote @guillaume86.

**Comment by lty83** [comment]
+1

**Comment by mrb398** [comment]
+1

**Comment by mvidailhet** [comment]
+1 That would be great !

**Comment by FMCorz** [comment]
+1

**Comment by paulJordaan** [comment]
+1

**Comment by thearsenik** [comment]
+1

**Comment by tabalinas** [comment]
+1

**Comment by nirsmadar** [comment]
+1

**Comment by dheeraj143** [comment]
+1

**Comment by lbayerl** [comment]
+1

**Comment by DmitriyTolkachov** [comment]
+1

**Comment by greeniceparadise** [comment]
+1

**Comment by rllola** [comment]
+1

**Comment by atrain0789** [comment]
+1

**Comment by tausch86** [comment]
+1

**Comment by christopherthielen** [comment]
I believe `ui-state` directive supports this.

**Comment by sbowler** [comment]
Finally a decent solution, thanks Leonix

**Comment by cferriss** [comment]
+1

**Comment by dciq** [comment]
+1

Leonix's solution only works if the relative state reference is not abstract. If the relative state is abstract, ui-router will throw the exception `Cannot transition to asbtract state '.'`

**Comment by dciq** [comment]
+1

Leonix's solution only works if the relative state reference is not abstract. If the relative state is abstract, ui-router will throw the exception Cannot transition to asbtract state '.'
