### ISSUE TITLE
Update AngularJS lazy loading guide

### ISSUE THREAD

**Issue by ViieeS** [angular-ui/ui-router#3717]
This is a (check one box):

- [ ] Bug Report
- [x] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.18

Needs to update the [lazy loading guide](https://ui-router.github.io/guide/lazyloading).

#### Current Behavior:

![lazy loading - ui-router 2018-07-05 15-08-03](https://user-images.githubusercontent.com/8194543/42322457-4aaa6076-8065-11e8-9d72-8697d9b2c7ad.png)

#### Expected Behavior:

AngularJS officially support lazy loading since **v1.6.7**:

![angular js 2018-07-05 15-10-41](https://user-images.githubusercontent.com/8194543/42322564-aced76c4-8065-11e8-9c92-bb740034ba43.png)

[Documentation](https://docs.angularjs.org/api/auto/service/$injector#loadNewModules)

#### Example:
New example based on the old one:
```js
var futureState = {
    name: 'contacts.**',
    url: '/contacts',
    lazyLoad: function ($transition$) {
        var $q = $transition$.injector('$q');
        var $injector = $transition$.injector('$injector');
        var moduleName = "ContactsModule";

        return $q(function (resolve, reject) {
            $.getScript("./contacts.module.js", function () {
                resolve($injector.loadNewModules([moduleName]));
            });

        });
    }
};
```

**Comment by jrencz** [comment]
[StateDeclaration.lazyLoad](
https://ui-router.github.io/core/docs/latest/interfaces/state.statedeclaration.html#lazyload) should return [`Promise<LazyLoadResult>`](https://ui-router.github.io/core/docs/latest/interfaces/state.lazyloadresult.html) but [`$injector.loadNewModules` returns `undefined`](https://github.com/angular/angular.js/blob/26a5779cddf70944b7548e3a6410d35237a516e5/src/auto/injector.js#L745-L747)

**Comment by ViieeS** [comment]
@jakebian yes, you're right. That's why we use `$q` service here.
