### ISSUE TITLE
How can I make angular ui-router work with html5mode=true automatically?

### ISSUE THREAD

**Issue by henrytao-me** [angular-ui/ui-router#372]
Hi all! How can I make angular ui-router work with html5mode=true automatically? I mean:

In angular, you have the link like this href="#/abc". If you set html5mode=true, it automatically redirect to /abc when you click on link abc. If html5mode=false, it keeps #/abc. So, nothing need to change in your html code.

In angular ui-router, if you plan to enable html5mode=true, you need to change all link from html code to something like: <a href="/abc"></a> (without #). If html5mode=false, you need to have # in url. 

So, how to fix it in angular ui-router? Thanks for advice!

**Comment by zaphz** [comment]
@jasonshark, Thank you for your answer.

**Comment by RaviSankarRao** [comment]
@jasonshark Thanks a lot for your answer. Adding <base href="/"> worked to remove those ugly URLs. Was using html5Mode true and hasPrefix as !

**Comment by jasonshark** [comment]
:+1:

**Comment by FurkanArslan** [comment]
@jasonshark , thank you very much for your answer

**Comment by mahesh5b5** [comment]
Hi I'm using html5 url mode to hide hash tag in my angular URL. If i refresh or copy/paste URL to other tab on browser its showing **404 error page not found**
-  Using $stateProvider.
- <base href="/site/index.html" 
- $locationProvider.html5Mode({ enabled: true, requireBase: true }).hashPrefix('!');

Please help me out

**Comment by shardool** [comment]
@mahesh5b5, minutes ago I bumped into the same issue and I realized that it is in fact the expected behavior and here's the explanation:
When you tell the $locationProvider to use the html5 mode, the route URLs look as desired and work fine when you navigate to them by "clicking" the relevant links. 
example:
you can navigate from http://myWebsite/home to http://myWebsite/about by clicking the anchor tag as this navigation is orchestrated by  the angular-ui-router. However once you are on the destination URL http://myWebsite/about, refreshing it will cause the browser to make a fresh "get" request to that URL and is not orchestrated by the angular-ui-router. This fresh request should be served by the server "myWebSite". Hope this explanation helps :)

**Comment by ldynia** [comment]
@shardoo So if I will send somebody a link to  http://myWebsite/home he/she will get 404, because a user did not enter myWebsite from the root location ("/"). Is there a fix for this behavior so angular will recognize request and will generate content?

**Comment by isaiahgrey93** [comment]
This is because when you submit the link it makes a request to that route on the server, when angular is using client side routing. To enable html5 mode, you need to serve the index on all routes for html5 mode. Like this for a node app.

```
// This is a server file
app.get("*", function(req, res) {
    res.render("./index.html");
}
```
Angular UI router html5 mode works by say...
```
// This is in your app module config.
$locationProvider.html5Mode(true);
```
```
// This is in your index.html head.
<base href="/" />
```
This is all you need for the pretty urls essentially, the issue is if you navigate to a route with out the hash prefix and submit a link to the server, it will cause a server request for that route. So like I mentioned about you need to render the index on all routes submitted to the server.

**Comment by ldynia** [comment]
@isaiahgrey93 Thanks for your input. You are very right. I fixed this problem on the server. I render all my urls to index.html page. By doing that angular reads the url, and loads appropriate state. Regards ;)

**Comment by smkamranqadri** [comment]
i had deployed my client on firebase server so didn't make redirect all routes to index.html so what to do?

**Comment by ldynia** [comment]
Have you set in your  apaceh/nginx virtualhost  conf file html5 handling ? Here is my below set up
```
  ### serve index.html as django app
  <Directory /srv/www/compare/htdocs/core/frontend/templates>
    ## link: https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-your-server-to-work-with-html5mode
    ## link: http://stackoverflow.com/questions/869092/how-to-enable-mod-rewrite-for-apache-2-2
    RewriteEngine on
    # Rewrite everything else to index.html to allow html5 state links
    # Don't rewrite files or directories
    #RewriteBase /
    RewriteCond %{REQUEST_FILENAME} -f [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^ - [L]
    RewriteRule ^ index.html [L]
  </Directory>
```

**Comment by smkamranqadri** [comment]
my app hosted on firebase not apaceh/ngix??

**Comment by ldynia** [comment]
Then I cannot help you. I heave no experience with firebase.

**Comment by sonurauniyar** [comment]
@shardool Any suggestion how you solved your problem ?. I am also having the same issue

**Comment by IainCole** [comment]
Does this not help? https://www.firebase.com/docs/hosting/guide/url-redirects-rewrites.html

**Comment by deven003** [comment]
For those who are using Angular JS with Laravel 5 and facing page not found issue after page refresh while implementing @isaiahgrey93 solution, add following line in your route.

    Route::any('{path?}', function()
    {
        return File::get(public_path() . '/angular.html');
    })->where("path", ".+");

source: http://stackoverflow.com/a/28683547/1099229

**Comment by Mimicx** [comment]
i'm working in a ionic application, how i can configure it from the server site?

**Comment by mahesh5b5** [comment]
Thanks :+1:

**Comment by RongBranovate** [comment]
any idea how to make it work with codeigniter?

**Comment by cullsin** [comment]
Hi, 

Seems like  page refresh not working in my url "http://anaoh.com/about" with enabled html5 mode.

Can you please suggest me what I am missing.

Raja K

**Comment by RongBranovate** [comment]
@cullsin, you need to set on you your server routing that all pages will go to the home page(you default one).

Also, tell us what you are using on the server side(framework or language).

**Comment by cullsin** [comment]
Hi, 

I am using Phalcon REST Framework in the backend so it serves only data. I have configured 
apache Rewrite Engine too. 

       <IfModule mod_rewrite.c>
        RewriteEngine On
        # Don't rewrite files or directories
        RewriteCond %{REQUEST_FILENAME} -f [OR]
        RewriteCond %{REQUEST_FILENAME} -d
        RewriteRule ^ - [L]

        # Rewrite everything else to index.html to allow html5 state links
        RewriteRule ^ /index.html [L]
        </IfModule>

**Comment by cullsin** [comment]
Hi, 

This is working greate. I had a code issue in the loading. Sorry for the confusion.

Raja K

**Comment by jetsgit** [comment]
This solution is working
for Rails 4.x.x and AngularJS 1.5.7.

app.coffee
```
angular.module('myApp').config( ($stateProvider, $urlRouteProvider, $locationProvider)  ->
  $stateProvider.state()  # Your states here
  $locationProvider.html5mode true
```
application.html.erb:
```
<head>
  <title>My Wonderful World</title>
  <base href="/">
```
routes.rb:
```
root 'home#angular'
get '*path' => 'home#angular'
```
home_controller.rb:
```
class HomeController < ApplicationController
  def angular
    render 'layouts/application'
  end
end
```
An alternate approach:

application_controller.rb:
```
class ApplicationController < ActionController::Base
  ...
  def index
end
```
routes.rb
```
root 'application#index'
get '*path' => 'application#index'
```

**Comment by DustinJSilk** [comment]
My issue was that my base url looked like this:
`<base href="/">`

So had to add a `/` to my first state url:
 `
$stateProvider
    .state('index', {
      url: "/", ...
`

**Comment by ashwinigawade007** [comment]
Refer this 
http://oneplaceworld.blogspot.in/2016/09/pretty-urls-in-angularjs-removing-Hashtag.html

**Comment by smanners** [comment]
It would seem that from most of the comments, the original question is misunderstood!

I am having the same issue.  The original question is to do with "classic" anchor links, which use hash to link to an ID on the same page.  eg /about#angular.

UI Router using html5 mode = true, strips out the hash, and you get /aboutangular, which doesn't exist.  Would be nice if there was an exclusion rule, so you could still use the anchor links on a page without writing some dirty hack to get around it.

**Comment by smanners** [comment]
UPDATE.  It seems $locationProvider.hashPrefix('!') fixes my issue.   Thanks.

eg
<a href="/#about" target="_self">About Us</a>

**Comment by severus-ebay** [comment]
I am having a problem with the HTML5 and ui.router
If I activate the HTML5 like:  **$locationProvider.html5Mode(true)**; my URLs looks perfect (without #!) but then if I refresh the page, its gets blank.

If I deactivate the HTML5 (just out comment: // $locationProvider.html5Mode(true);) I can refresh and I do not lose the page, but I have the ugly URL like: http://localhost:50895/#!/addcontact

I added the following rewrite method in my Web.config (I am in ASP.NET) but it crash the application:

```
     <rewrite>
    <rules>
      <rule name="RewriteRules" stopProcessing="true">
        <match url=".*" />
        <conditions logicalGrouping="MatchAll">
          <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
          <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
          <add input="{REQUEST_URI}" pattern="^/(api)" negate="true" />
        </conditions>
        <action type="Rewrite" url="/index.html" />
      </rule>
    </rules>
  </rewrite>
```

Any idea?

**Comment by macsermkiat** [comment]
I'm having this problem too. Cannot refresh page with html5Mode(true)
I use Express serving index file like 
```
    app.all('/*', function(req, res, next) {
    res.sendFile('index.html', { root: __dirname });
    console.log("send index");
    });
```
but there was no luck.

**Comment by jetsgit** [comment]
Did you follow steps I outlined above, including:
 ```
root 'your_controller#your_method'
get '*path' => 'your_controller#your_method'
```
in ```routes.rb``` ?

**Comment by macsermkiat** [comment]
No. Actually I use Node and Express, not Rails.

**Comment by smanners** [comment]
have you tried
```
$locationProvider.html5Mode({
        enabled: true,
...
    }).hashPrefix('!');
```

**Comment by macsermkiat** [comment]
Yes. I have hashPrefix('!') for sake of SEO.

**Comment by 1312624** [comment]
I have same problem with macsermkiat. I'm using MEAN Stack, Node for back-end and Angular JS for back-end. I'm also use :
if(window.history && window.history.pushState) {
			$locationProvider.html5Mode({
				enabled : true,
				requireBase : false
			}).hashPrefix('!');
in my app.route.js and <base href="/"> in my home.html. It can remove the hash # but when i try reload i get an error can get/state-name ...
Any solution for this ?? thanks for your help
		}

**Comment by 1312624** [comment]
In my server I have : 
app.get('/', function (req, res) {
	res.redirect('index.html');
});

index.html is just a landing page and i'm not use angular JS on it. In index.html when user click a button it will show a popup sign-in and when user sign-in it will redirect to home.html. And home.html is my angular app.

**Comment by 1312624** [comment]
After 1 day !! Problem Solve :D

**Comment by macsermkiat** [comment]
How?

**Comment by 1312624** [comment]
Back-end : In your app.js :
app.get('/any-thing-you-want/*', function (req, res) {
	res.sendFile(path.join(__dirname, './views', 'home.html')); // change this 
}); 

Front-end : In your home.html ( or index.html ) add this line base href="/any-thing-you-want" (same string with your app.js)
                  In app.route.js 
                  $urlRouterProvider.otherwise('/any-thing-you-want/');
                  .state('app') url : '/any-thing-you-want/'
                  ......
                  ......;
                   
                  if(window.history && window.history.pushState) {
			$locationProvider.html5Mode({
				enabled : true,
				requireBase : false
			}).hashPrefix('');
		}
done.... change ui-sref or href in front-end from #/... to any-thing-you-want/..... or just use $state.go(...)
Sry for my bad English..

**Comment by nicolairobles** [comment]
Awesome @1312624 , I was able to customize your implementation to my scenario and it worked on my local build. 

Unfortunately, this doesn't seem to work when I deploy it to my AWS dev server. The pages fail on refresh. It's very strange because the build is identical. My node version is the same...I'm trying to think what other environment changes might be causing this issue.

Does anyone have any ideas as to what might cause an issue like this?

**Comment by waqas-syed** [comment]
@severus-ebay : This configuration works for me when I deploy the application on IIS. It doesn't work(reason I don't know) when I run this configuration while debugging it in Visual Studio. 

Also, you can try replacing <code><action type="Rewrite" url="/index.html" /></code> with <code><action type="Rewrite" url="/" /></code>

You can also check the answer for this question and try this configuration, may be it will help: https://stackoverflow.com/questions/27749776/angularjs-with-html5modetrue-on-iis-and-default-document

**Comment by abhiramgiri** [comment]
Hi
**index.html**
`<!DOCTYPE html>
<html lang="en"  ng-app="app">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Example : </title>  
        <script src="angular.min.js"></script>
        <script src="angular-ui-router.min.js"></script>        
        <script src="app.js"></script>        
      <base href="/Example/">
    </head>
    
    <body>
       <div ui-view=""></div>
    </body>
</html>`

**home.html**
`<span>Hi This is HOME PAGE</span>`

**module.html**
`<span>Hi This is MODULE PAGE</span>`

**app.js**
`var app = angular.module('app',['ui.router']);
app.config(function ($stateProvider, $urlRouterProvider,$locationProvider) {
    $urlRouterProvider.when("", "/");
    $stateProvider
        .state("/", {
            url: "/",
            templateUrl: "home.html"
        })       
       .state("/module", {
            url: "/module",
            templateUrl: "module.html" 
         });
         $locationProvider.html5Mode(true);
         $locationProvider.hashPrefix('');        
});`

If url is _localhost/Example/_ Its opening home page fine
But if url is _localhost/Example/module_ its showing 404 Not found.
Please help.

>
