### ISSUE TITLE
"$injector:modulerr" Error when updating to 1.0.19

### ISSUE THREAD

**Issue by steel119** [angular-ui/ui-router#3727]
This issue tracker is for Bug Reports and Feature Requests only.

Please direct requests for help to StackOverflow.
See http://bit.ly/UIR-SOF for details.

This is a (check one box):

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.19

# Bug Report

#### Current Behavior:

When updated to 1.0.19 the following error occurs in IE 11. In Chrome and edge it works fine.

[$injector:modulerr] http://errors.angularjs.org/1.7.2/$injector/modulerr?p0=testModule&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.7.2%2F%24injector%2Fmodulerr%3Fp0%3Dui.router%26p1%3DError%253A%2520%255B%2524injector%253Amodulerr%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.7.2%252F%2524injector%252Fmodulerr%253Fp0%253Dui.router.init%2526p1%253DTypeError%25253A%252520Object%252520doesn't%252520support%252520property%252520or%252520method%252520'find'%25250A%252520%252520%252520at%252520de%252520(http%25253A%25252F%25252Flocalhost%25252Ftest%25252Fnode_modules%25252F%252540uirouter%25252Fangularjs%25252Frelease%25252Fangular-ui-router.min.js%25253A11%25253A15578)%25250A%252520%252520%252520at%252520n%252520(http%25253A%25252F%25252Flocalhost%25252Ftest%25252Fnode_modules%25252F%252540uirouter%25252Fangularjs%25252Frelease%25252Fangular-ui-router.min.js%25253A11%25253A15934)%25250A%252520%252520%252520at%252520t.prototype.fromConfig%252520(http%25253A%25252F%25252Flocalhost%25252Ftest%25252Fnode_modules%25252F%252540uirouter%25252Fangularjs%25252Frelease%25252Fangular-ui-router.min.js%25253A11%25253A57215)%25250A%252520%252520%252520at%252520Anonymous%252520function%252520(http%25253A%25252F%25252Flocalhost%25252Ftest%25252Fnode_modules%25252F%252540uirouter%25252Fangularjs%25252Frelease%25252Fangular-ui-router.min.js%25253A11%25253A32400)%25250A%252520%252520%252520at%252520Anonymous%252520function%252520(http%25253A%25252F%25252Flocalhost%25252Ftest%25252Fnode_modules%25252F%252540uirouter%25252Fangularjs%25252Frelease%25252Fangular-ui-router.min.js%25253A11%25253A4151)%25250A%252520%252520%252520at%252520q%252520(http%25253A%25252F%25252Flocalhost%25252Ftest%25252Fnode_modules%25252Fangular%25252Fangular.min.js%25253A8%25253A264)%25250A%252520%252520%252520at%252520ft%252520(http%25253A%25252F%25252Flocalhost%25252Ftest%25252Fnode_modules%25252F%252540uirouter%25252Fangularjs%25252Frelease%25252Fangular-ui-router.min.js%25253A11%25253A4108)%25250A%252520%252520%252520at%252520Anonymous%252520function%252520(http%25253A%25252F%25252Flocalhost%25252Ftest%25252Fnode_modules%25252F%252540uirouter%25252Fangularjs%25252Frelease%25252Fangular-ui-router.min.js%25253A11%25253A32346)%25250A%252520%252520%252520at%252520Anonymous%252520function%252520(http%25253A%25252F%25252Flocalhost%25252Ftest%25252Fnode_modules%25252F%252540uirouter%25252Fangularjs%25252Frelease%25252Fangular-ui-router.min.js%25253A11%25253A32979)%25250A%252520%252520%252520at%252520t.prototype.build%252520(http%25253A%25252F%25252Flocalhost%25252Ftest%25252Fnode_modules%25252F%252540uirouter%25252Fangularjs%25252Frelease%25252Fangular-ui-router.min.js%25253A11%25253A32998)%250A%2520%2520%2520at%2520Anonymous%2520function%2520(http%253A%252F%252Flocalhost%252Ftest%252Fnode_modules%252Fangular%252Fangular.min.js%253A43%253A113)%250A%2520%2520%2520at%2520q%2520(http%253A%252F%252Flocalhost%252Ftest%252Fnode_modules%252Fangular%252Fangular.min.js%253A8%253A74)%250A%2520%2520%2520at%2520g%2520(http%253A%252F%252Flocalhost%252Ftest%252Fnode_modules%252Fangular%252Fangular.min.js%253A42%253A308)%250A%2520%2520%2520at%2520Anonymous%2520function%2520(http%253A%252F%252Flocalhost%252Ftest%252Fnode_modules%252Fangular%252Fangular.min.js%253A42%253A481)%250A%2520%2520%2520at%2520q%2520(http%253A%252F%252Flocalhost%252Ftest%252Fnode_modules%252Fangular%252Fangular.min.js%253A8%253A74)%250A%2520%2520%2520at%2520g%2520(http%253A%252F%252Flocalhost%252Ftest%252Fnode_modules%252Fangular%252Fangular.min.js%253A42%253A308)%250A%2520%2520%2520at%2520Anonymous%2520function%2520(http%253A%252F%252Flocalhost%252Ftest%252Fnode_modules%252Fangular%252Fangular.min.js%253A42%253A481)%250A%2520%2520%2520at%2520q%2520(http%253A%252F%252Flocalhost%252Ftest%252Fnode_modules%252Fangular%252Fangular.min.js%253A8%253A74)%250A%2520%2520%2520at%2520g%2520(http%253A%252F%252Flocalhost%252Ftest%252Fnode_modules%252Fangular%252Fangular.min.js%253A42%253A308)%250A%2520%2520%2520at%2520hb%2520(http%253A%252F%252Flocalhost%252Ftest%252Fnode_modules%252Fangular%252Fangular.min.js%253A46%253A395)%0A%20%20%20at%20Anonymous%20function%20(http%3A%2F%2Flocalhost%2Ftest%2Fnode_modules%2Fangular%2Fangular.min.js%3A43%3A113)%0A%20%20%20at%20q%20(http%3A%2F%2Flocalhost%2Ftest%2Fnode_modules%2Fangular%2Fangular.min.js%3A8%3A74)%0A%20%20%20at%20g%20(http%3A%2F%2Flocalhost%2Ftest%2Fnode_modules%2Fangular%2Fangular.min.js%3A42%3A308)%0A%20%20%20at%20Anonymous%20function%20(http%3A%2F%2Flocalhost%2Ftest%2Fnode_modules%2Fangular%2Fangular.min.js%3A42%3A481)%0A%20%20%20at%20q%20(http%3A%2F%2Flocalhost%2Ftest%2Fnode_modules%2Fangular%2Fangular.min.js%3A8%3A74)%0A%20%20%20at%20g%20(http%3A%2F%2Flocalhost%2Ftest%2Fnode_modules%2Fangular%2Fangular.min.js%3A42%3A308)%0A%20%20%20at%20hb%20(http%3A%2F%2Flocalhost%2Ftest%2Fnode_modules%2Fangular%2Fangular.min.js%3A46%3A395)%0A%20%20%20at%20c%20(http%3A%2F%2Flocalhost%2Ftest%2Fnode_modules%2Fangular%2Fangular.min.js%3A22%3A55)%0A%20%20%20at%20Vc%20(http%3A%2F%2Flocalhost%2Ftest%2Fnode_modules%2Fangular%2Fangular.min.js%3A22%3A363)%0A%20%20%20at%20Anonymous%20function%20(http%3A%2F%2Flocalhost%2Ftest%2Fjs%2Fmain.js%3A203%3A13)

#### Expected Behavior:

The code should work. After downgrading to 1.0.18 my code works.

**Comment by LoveMeWithoutAll** [comment]
Same error occurs on my [issue(#3725)](https://github.com/angular-ui/ui-router/issues/3725)

**Comment by steel119** [comment]
@LoveMeWithoutAll : Awesome thanks !!
