### ISSUE TITLE
Support array state parameters

### ISSUE THREAD

**Issue by jyboudreau** [angular-ui/ui-router#373]
Angular $location [has support](https://github.com/angular/angular.js/commit/8073940) for setting/getting query parameters that are repeated and treat them as arrays. It would be great to have this supported in ui-router.

Some example usage:

``` javascript
var arrayState = {
    // ...
    url: "/index?array"  // or via params
}

// Activating the state
$state.go(arrayState, {array: ["1", "2", "3"]});

// ... would change the location to /index?array=1&array=2&array=3
```

$stateParams.array would also be constructed from the location into an array of course.

**Comment by felixfbecker** [comment]
Is there any way to disable this? I want to encode JSON in query parameters with a custom type handler, but this handling causes arrays to be handled as multiple query params instead of one JSON query param.

**Comment by stolenhead** [comment]
hi is there a way to receive a param join with commas ? like: "?person=5b3ef51a9f929066765bb07e,5b3ef50d9f929066764ec006" 
thanks

**Comment by aisimon** [comment]
Urlencode it then you can receive it right ?
