### ISSUE TITLE
Resolvable async .get() not complete for onExit hook

### ISSUE THREAD

**Issue by adamreisnz** [angular-ui/ui-router#3748]
This is a (check one box):

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is:

"@uirouter/angularjs": "^1.0.20",
"@uirouter/core": "^5.0.21",

# Bug Report

I'm getting a `Resolvable async .get() not complete` error when trying to obtain a resolved value in an `onExit` hook. This strikes me as odd, as the route has already been resolved, and the resolvables are all there. So why are they not available in an `onExit` hook?

E.g:

```js
$transitions.onExit({exiting: 'foo'}, transition => {
    const user = transition.injector().get('user'); //errors
});
```

#### Expected Behavior:

To have all the resolvables of the state available in the `onExit` hook.

#### Link to Plunker or stackblitz that reproduces the issue:
http://plnkr.co/edit/KOClmTCu8ajm5BYP93uM

From playing around with it in Plunkr, it appears that the `onExit` hook is actually trying to get resolvables for the *new* state. How can I get the resolvables for the state I'm exiting?

I need access to them to do some cleanup.

**Comment by adamreisnz** [comment]
I'll leave this open for feedback, but in the end I solved the issue by accessing the resolvables from the `state` object (2nd parameter in the hook).

**Comment by christopherthielen** [comment]
you can access the resolves from an exiting state by getting the injector for the "from" path path:

```
.onExit({ exiting: 'foo.bar' }, trans => {
  // Gets the resolve value of `myResolve` from the state being exited
  var fooData = trans.injector(null, 'from').get('myResolve');
});
```

See: https://ui-router.github.io/ng1/docs/latest/classes/transition.transition-1.html#injector
