### ISSUE TITLE
Transition to sibling state via ui-sref="^.sibling" broken in release 0.2.0

### ISSUE THREAD

**Issue by KilianSSL** [angular-ui/ui-router#375]
With the latest 0.2.0 release, transition to a sibling state seems to be broken:

```
<a ui-sref="^.sibling">go to sibling</a>
```

results in
`Uncaught Error: No such state undefined`

[see the plunkr](http://plnkr.co/edit/nFE30Ex31GuseTNCNYtu?p=preview)

anyone else? or am i missing some point?

**Comment by litera** [comment]
I understand the reasoning behind this, but then I'm having a problem with this situation.

1. (at least) 2 components - master-list and details
1. defined (sub)routing for components - by subrouting I mean that these routes will be registered under specific parent route

**Desktop app** displays master-list to the left and details to the right when item in master is being clicked.  
**Mobile app** displays master-list first and details when user taps an item

On desktop I have a container component as well that defines template to display master-list on the left and routing container to the left that gets populated when details need to be displayed. This means that details is child route of master where master-list is displayed while mobile has master-list and details as sibling routes.

**The problem** is that I can't have relative links in the template if I was to reuse the same templates on both app clients. Putting absolute links wouldn't work as apps may use different parent route for my feature.

**Dow does one solve relative linking in templates?**
