### ISSUE TITLE
General Query : $transitions.onSuccess doesnt fire on browser refresh

### ISSUE THREAD

**Issue by jonbonraki** [angular-ui/ui-router#3767]
```
 $transitions.onSuccess({}, function(trans) {

        });
```

The above event doesn't fire when there is refresh on browser on router > 1.0.
```
  $scope.$on('$stateChangeSuccess', function (event, toState, toParams) {
        });
```
Where as in  
$stateChangeSuccess used to fire even in refresh of browser for router version 0.4, is there a change or can you suggest a workaround to fire a transition event on refresh.

thanks

**Comment by jonbonraki** [comment]
any comments on  above question?

**Comment by nvurgaft** [comment]
I've also encountered it when upgrading to v1.0.23. Explicitly writing the state name in the criteria object didn't help much either.
