### ISSUE TITLE
Using webpack 4，the content-hash is different on version 1.0.22 but 1.0.0 is same

### ISSUE THREAD

**Issue by oliveshell** [angular-ui/ui-router#3771]
This issue tracker is for Bug Reports and Feature Requests only.

Please direct requests for help to StackOverflow.
See http://bit.ly/UIR-SOF for details.

This is a (check one box):

- [1 ] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.22
Webpack: 4.28.4

# Bug Report

#### Current Behavior:
Dear all,
When  I using the webpack to pack my project,I configure the output as the style as contenthash.
I check all the files of my project,then I found the vendor's(node_modules) hash is different every time. 
Finally i found the ui-router 's version is related  to the difference.
If i use the 1.0.22 version,I test 100 times build, nearly 30% is same. If  I change to the version 1.0.0, 100% is same.
However I can't downgrade to 1.0.0,beacuse I use the higher version's feature future state.
Help me please!
#### Expected Behavior:

when I pack all the scripts, if the content is same then I expect the hash is same.

my webpack config:
output: {
            path: helpers.appBuild,
            filename: '[name].[contenthash:8].js',
            sourceMapFilename: '[file].map',
            chunkFilename: '[name].[contenthash:8].js',
            publicPath: helpers.publicServerBase
        },
const NamedChunksPlugin = require('webpack/lib/NamedChunksPlugin');
use the plugin:
       new NamedChunksPlugin(
                chunk => chunk.name || Array.from(chunk.modulesIterable, m => m.id).join("_")
            ),

#### Link to Plunker or stackblitz that reproduces the issue:

( if you want a response to your issue, provide a way to reproduce it )
( http://bit.ly/UIR-Plunk1 )
( https://stackblitz.com/edit/ui-router-angularjs )

# Feature Request

# General Query

Please direct general implementation questions to StackOverflow: 
http://stackoverflow.com/questions/ask?tags=angularjs,angular-ui-router

Please review the Sample Application which highlights common approaches:
https://github.com/ui-router/sample-app-angularjs

- [ ] I have already asked my question on StackOverflow and nobody could answer the question

- [ ] I have already reviewed the sample application for examples of common approaches

- [ ] I believe my question can only be answered by the UI-Router maintainers

(type general query here)

**Comment by oliveshell** [comment]
const NamedChunksPlugin = require('webpack/lib/NamedChunksPlugin');

**Comment by bbrassart** [comment]
Hi all! If anyone still bumps into this issue, I think the "faulty" version of the `@uirouter/angularjs` NPM package is 1.0.19 https://github.com/angular-ui/ui-router/blob/master/CHANGELOG.md#1019-2018-07-20 I suspect this change https://github.com/angular-ui/ui-router/commit/8fc3bb2 to be at the source of it but I'm not entirely sure. So reverting to 1.0.19, the contenthash produced by Webpack should be consistent.
