### ISSUE TITLE
Add support for Angular Ivy

### ISSUE THREAD

**Issue by euangoddard** [angular-ui/ui-router#3780]
This is a (check one box):

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: (type version)

3.0.0

# Bug Report

#### Current Behavior:

I have followed the notes here for enabling the Ivy compiler for Angular here: https://angular.io/guide/ivy

When I run `ng serve` I get a multitude of errors which always start with `"export 'UIRouter' was not found in '@uirouter/angular'`

Some of these errors are followed by `Module not found: Error: Can't resolve './uiRouterConfig' in ...`

I know the way `loadChildren` has changed in the main Angular router to use the `import('path/to/module')` and I wonder whether this is related

#### Expected Behavior:

The UI router functions with the Ivy compiler enabled

#### Link to Plunker or stackblitz that reproduces the issue:

I cannot make a reproduction on StackBlitz as I cannot customize the `tsconfig.app.json` required to enable Ivy.

**Comment by christopherthielen** [comment]
https://github.com/ui-router/angular/releases/tag/6.0.0

https://github.com/ui-router/angular-hybrid/releases/tag/10.0.1

FYI this bug was reported to the AngularJS project.  The Angular project is here: https://github.com/ui-router/angular
