### ISSUE TITLE
Update @uirouter/core

### ISSUE THREAD

**Issue by kosmogradsky** [angular-ui/ui-router#3786]
This is a (check one box):

- [ ] Bug Report
- [x] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.22

# Feature Request

Could `@uirouter/core` dependency please be updated, so we get https://github.com/ui-router/core/pull/430 ?

**Comment by christopherthielen** [comment]
https://github.com/angular-ui/ui-router/releases/tag/1.0.23
