### ISSUE TITLE
$transitions.onSuccess doesnt fire on browser refresh

### ISSUE THREAD

**Issue by tobaleet17** [angular-ui/ui-router#3789]
Hello,
some event that enter when refresh the browser?
Thanks.

**Comment by ajitsinghkaler** [comment]
@tobaleet17 can you please be more detailed

**Comment by tobaleet17** [comment]
> @tobaleet17 can you please be more detailed

Yeah. I try that when reload the page with F5, $transitions detect this refresg.
Exist anyone event for this?
