### ISSUE TITLE
ui-sref does not work until your refresh the page.

### ISSUE THREAD

**Issue by richie50** [angular-ui/ui-router#3803]
This issue tracker is for Bug Reports and Feature Requests only.

Please direct requests for help to StackOverflow.
See http://bit.ly/UIR-SOF for details.

This is a (check one box):

- [x] Bug Report
- [ ] Feature Request
- [x] General Query 

My version of UI-Router is: (type version)
angular version 1.7.9
angular-router 0.4.2

# Bug Report

#### Current Behavior:

(type current behavior here)

#### Expected Behavior:

(type expected behavior here)

#### Link to Plunker or stackblitz that reproduces the issue:

( if you want a response to your issue, provide a way to reproduce it )
( http://bit.ly/UIR-Plunk1 )
( https://stackblitz.com/edit/ui-router-angularjs )

# Feature Request

(type feature request here)

# General Query

Please direct general implementation questions to StackOverflow: 
http://stackoverflow.com/questions/ask?tags=angularjs,angular-ui-router

Please review the Sample Application which highlights common approaches:
https://github.com/ui-router/sample-app-angularjs

- [ ] I have already asked my question on StackOverflow and nobody could answer the question

- [x] I have already reviewed the sample application for examples of common approaches

- [x] I believe my question can only be answered by the UI-Router maintainers

(type general query here)

In the template

```html
<a ui-sref="some-route"> My route</a>
```
route config
state('some-route' , {
url:'/route',
cache:false
view: {
'details': "template.html"
}

That is the basic setup. What happens is , i'm trying to authenticate a user and if the user provides an invalid credentials i basically stay on the same page with a notification message from the back end. But when that happens and the page doesn't refresh i can't click on the <a> tag with the ui-sref directive. Its this a known issue. Because it seems i'm wasting my time. The code was inherited 
})

**Comment by christopherthielen** [comment]
It's not a known issue.  I'd be happy to take a look if you provide a minimal reproduction (as requested in the issue template).

**Comment by richie50** [comment]
@christopherthielen  i'm currently swarmed right now but i will try my best to reproduce via stackblitz or plunkr in the next coming days. Cheers
