### ISSUE TITLE
Installing angular-ui-router not working anymore

### ISSUE THREAD

**Issue by stedda** [angular-ui/ui-router#3818]
- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: (type version)
Hi guys, my current angular-ui-router version that is installed is 1.0.27

```
  "dependencies": {
  ....
    "angular-ui-router": "~1.0.0",
.....
```
When i try to use npm install, it seems that a dependency of angular-ui-router @uirouter/core@6.0.6, is not found in the npm registry. The url that is trying to access to find this package, is: https://registry.npmjs.org/@uirouter%2fcore.

# Bug Report
@uirouter/core is not in registered in npm registry accordingly.
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@uirouter%2fcore - Not found
npm ERR! 404  '@uirouter/core@6.0.6' is not in the npm registry.

#### Current Behavior:
Throws 404 on npm install when trying to install angular-ui-router.

#### Expected Behavior:
Install dependencies of angular-ui-router accordingly.

**Comment by aluk-dev** [comment]
Looks like today I faced the same problem (was not reproducible yesterday):

```
06-Aug-2020 06:01:00 | npm ERR! code E404
-- | --
06-Aug-2020 06:01:00 | npm ERR! 404 Not Found - GET https://registry.npmjs.org/@uirouter%2fangularjs - Not found
06-Aug-2020 06:01:00 | npm ERR! 404
06-Aug-2020 06:01:00 | npm ERR! 404  '@uirouter/angularjs@^1.0.27' is not in the npm registry.
06-Aug-2020 06:01:00 | npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

**Comment by hjort-e** [comment]
Started getting `404  '@uirouter/angularjs@0.3.2' is not in the npm registry.` as well today

**Comment by hjort-e** [comment]
Okay i'm getting it on other packages, seems like it's NPM having issues today

**Comment by stedda** [comment]
> Okay i'm getting it on other packages, seems like it's NPM having issues today

you're right, it seems that npmjs has some issues today https://status.npmjs.org/. I will close this issue.
