### ISSUE TITLE
Multiple parents for a state

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/ui-router#384]
This is more of an RFC.

Lets say I have a child state I want to use in multiple areas of my app. Or perhaps it's more like a mixin, etc. How would you go about doing this? Should I define multiple parent states, or what?

**Comment by guikubivan** [comment]
FWIW, this solution worked for me since I only had two parent states that should both be able to access a child view: https://github.com/angular-ui/ui-router/issues/1323#issuecomment-54134290

**Comment by pocesar** [comment]
the only possible way of doing this at the moment, is to do things "off" angular, like dynamically creating a module. I created a reusable "login" module that could be used in admin, buy and user profile pages by wrapping the `angular.module` inside an init function like this:

```typescript

export function init(namespace: string){
  angular.module('Login', [
    'ui.router',
    'User',
    'Resources'
  ]).config(['$stateProvider', function($stateProvider) {
      $stateProvider.state('login.register', { 
           views:{
                'login': {
                    templateUrl: '/templates/shared/login-register.html'
                }
           }
      });

      $stateProvider.state('login.do', { 
           views:{
                'login': {
                    templateUrl: '/templates/shared/login-do.html'
                }
           }
      });

      $stateProvider.state('login.forgot', { 
           views:{
                'login': {
                    templateUrl: '/templates/shared/login-forgot.html'
                }
           }
      });

      $stateProvider.state('login', { 
         // this act as an abstract, the states are always set to either login.forgot, login.do or login.register
         parent: namespace, // this is the trick
         templateUrl: '/templates/shared/login.html', // has a <div ui-view="login"></div> along with markup
         controller: Controllers.Login,
         controllerAs: 'login'
      });
  }]);
}
```

this way I can still use "login.do" and "login.forgot" without having to resource to namespaced state names, like "buy.login.do" or "admin.login.forgot". constructing the module is straight forward:

```typescript
import Login = require('../shared/login');

Login.init('buy');
//Login.init('admin');
//Login.init('user');

angular.module('Base', [
   'Login'
]).config(['$stateProvider', ($stateProvider) => {
  $stateProvider.state('buy', {
     // the parent
  });
}]);

**Comment by mfoody** [comment]
@pocesar That's a nice solution. I think you might be able to improve it by creating the state inside a constant function. That function can then be injected into the config calls. For example,

```javascript
angular.module('myApp').constant('loginDialog', function ($stateProvider, parent) {
  $stateProvider.state('login', {
    parent: parent,
    url: '/login'
  });
})
.config(['$stateProvider', 'loginDialog', function($stateProvider, loginDialog) {
  loginDialog($stateProvider, 'buy');
  loginDialog($stateProivder, 'admin');
  loginDialog($stateProvider, 'user');
}]);

**Comment by ProLoser** [comment]
Does that work? That generates non-unique state names. You essentially have multiple states in your application called `login` (even though they are located at `buy.login` and `admin.login`). I would think this would cause state resolution bugs.

**Comment by mfoody** [comment]
Good point. Concatenating the parent into the state name should solve that.

```javascript
angular.module('myApp').constant('loginDialog', function ($stateProvider, parent) {
  $stateProvider.state(parent + '.login', {
    url: '/login'
  });
})
.config(['$stateProvider', 'loginDialog', function($stateProvider, loginDialog) {
  loginDialog($stateProvider, 'buy');
  loginDialog($stateProivder, 'admin');
  loginDialog($stateProvider, 'user');
}]);

**Comment by pocesar** [comment]
@ProLoser the point was to be able to use `ui-sref="login.do"` regardless if I'm in admin, user or buy page. I can also do `$state.go('login.register')` when the current state is `user.main.new` without breaking the state or the flow, since I needed slightly different configurable versions of the login screen

**Comment by ProLoser** [comment]
@pocesar I actually am not so sure that makes sense after I thought about it. If you only have 1 module running at a time, why throw it underneath x module? Why not just make it a top-level state?

**Comment by pocesar** [comment]
@ProLoser inheritance plus nested views unrelated to the login, but can still use login related stuff

**Comment by ProLoser** [comment]
Honestly that is starting to sound like a directive or something. I'd be curious to see your setup. Login is sort of a weak example of this design pattern honestly.

**Comment by moander** [comment]
+1 (modal states)

**Comment by eddiemonge** [comment]
@ProLoser can this be closed?

**Comment by ProLoser** [comment]
@eddiemonge uh i don't know, up to you if you're leading the project. I am not super present. I can always reopen if the latest version isn't sufficient.

**Comment by altsanz** [comment]
Hi, I have a user case that maybe rellevant to this scenario:

We have a group of products that are editable with a specific state.
I would like to access to that state from /products/:productId and from /categoryA/:productId, so when user finishes editing that product I can just do $state.go('^') and keep user navigation experience consistent.

Actually I'm working on how this can be achieved, but @mfoody solutions seems the best. I'm just learning how ui-router works, so if there's an alternative and easier solution to this, please tell me. :)

**Comment by louiealmeda** [comment]
It would be great if we have a state that can be appended to any state, haven't thought much though on its implication and detail. But I think it would greatly help

**Comment by nhim175** [comment]
https://christopherthielen.github.io/ui-router-extras/example/stickymodal/index.html#/people/managers

Check this `ui-router-extras` project, I bet what you want is called `sticky state`
