### ISSUE TITLE
Update @uirouter/core dependency to 6.0.9

### ISSUE THREAD

**Issue by nsgundy** [angular-ui/ui-router#3847]
This is a:

- [ ] Bug Report
- [X] Feature Request
- [ ] General Query 

My version of UI-Router is:
```
    "@uirouter/angular": "^11.0.0",
    "@uirouter/angular-hybrid": "^14.0.0",
    "@uirouter/angularjs": "^1.0.30",
    "@uirouter/core": "^6.0.9",
```

# Feature Request
Please update `@uirouter/angularjs` dependency on `@uirouter/core` to `6.0.9`, so that it can be used in an Angular/Angularjs hybrid app with Angular at v15.

Currently `@uirouter/angularjs` depends on `@uirouter/core` version `6.0.8`. This does cause a type mismatch with the `StateDeclaration` interface.

**Comment by wawyed** [comment]
Updated to latest core version also moved to peerDeps so it's easy to change version of core without conflicts.

**Comment by nsgundy** [comment]
I can confirm the issue is now gone using the following versions:
```
    "@uirouter/angular": "^11.1.0",
    "@uirouter/angular-hybrid": "^15.0.2",
    "@uirouter/angularjs": "^1.1.0",
    "@uirouter/core": "^6.1.0",
    "@uirouter/rx": "^1.0.0",
```

Cheers :champagne:

**Comment by wawyed** [comment]
awesome :D
