### ISSUE TITLE
Dynamic ui-sref in directive

### ISSUE THREAD

**Issue by snikch** [angular-ui/ui-router#395]
I've written a breadcrumb directive which takes an array of crumbs, each with a name and sref property. I'm trying to bind the `ui-sref` directive (`$StateRefDirective`) to use the evaluated attribute, but it's not working. When the `ui-sref` directive's `link` function is called, the `attrs.uiSref` value is `undefined`, but immediately after the running of the function becomes available as the correct value.

```coffee
angular.module('myApp').directive 'breadcrumb', ->
  scope: { crumbs: '=' }
  replace: true
  template: '
    <nav class="breadcrumbs">
      <a ui-sref="{{crumb.sref}}" ng-repeat="crumb in crumbs">{{crumb.name}}</a>
    </nav>
  '
```

Inside the `$StateRefDirective` `link` method, logging `attrs` gives

```js
Attributes {… uiSref: undefined …}
```

Running the same log after a 100ms timeout gives: 
```js
Attributes {… uiSref: "apps.show({appId: crumb.app.id})" …}
```

Am I doing something wrong, or are dynamic `ui-sref` attributes not supported?

Note: Running `v0.2.0`

**Comment by nateabele** [comment]
If anyone would like to [implement this](https://github.com/angular-ui/ui-router/issues/395#issuecomment-56884667), please submit a PR and reference this issue, thanks.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
