### ISSUE TITLE
RFC - State Parameter changes without reloading state

### ISSUE THREAD

**Issue by thebigredgeek** [angular-ui/ui-router#397]
I think it would be great to be able to shift state parameters without actually reloading the state.  The use case that I am thinking about (this actually applies to myself):

A developer wants to be able to reproduce a given state via the URL, meaning he wants the user to be able to copy and paste a given URL to another user and the application rebuilds that exact state (same filtering options on tables, same sort order, same items displayed, etc) for inter-user portability.  However, each time a filter is applied, the entire state has to be refreshed in order to accomplish this, which is extremely inefficient.  The developer does not need to re-render all of his various views, he only needs to be able to WRITE to the state parameters so that the parameters are kept in sync with various controller and filter data.

Any thoughts regarding this?

**Comment by amitit** [comment]
Is there an existing solution for this?
