### ISSUE TITLE
any way to cancel or redirect transition?

### ISSUE THREAD

**Issue by legomind** [angular-ui/ui-router#42]
I am trying to protect certain routes/states from users who are not logged in/don't have access to the rest server.

**Comment by syndicatedshannon** [comment]
If you are trying to avoid the $rootScope event, what about immediately cancelling the transition, to prevent the flash, and using go() in an immediate timer, or http promise, whichever your case may be?

**Comment by rcollette** [comment]
It would be nice to have a transition cancelation that does not raise the error.   For now I do:
```
defer.reject('Canceled');
```
And then in my $stateChangeError handler I check if  error==='Canceled` and do nothing in that case. 

I don't like using "magic strings" in this way though and my implementation of a canceled state transition is different from someone elses'.

**Comment by jml6m** [comment]
@rcollette You can mask this error by using $qProvider in your config() block as seen below:

```javascript
app.config(['$qProvider', function ($qProvider) {
    $qProvider.errorOnUnhandledRejections(false);
}]);
```

**Comment by AlexanderTserkovniy** [comment]
Hey @jml6m how to do the same in tests? For instance:

```
beforeEach(function () {
    angular.mock.module('covers');
    inject(function($injector) {
      Covers = $injector.get('Covers');
      httpBackend = $injector.get('$httpBackend');
    });
  });
```

**Comment by soorya02** [comment]
hi friends can u please help me to find a solution ,i am using "angular": "1.6.0","angular-ui-router": "1.0.0-beta.3".  what i want  to do is to reject the current transition and redirected to the 'from' state the user now is at. On  every state change .onStart()  a request sends and response having the value is the user is allowed to enter the  'to' state and  need to reject/cancel  the transition and .onError() have to redirected to the 'from' state he is now at.

      ```
  $transitions.onStart({}, function ($transitions) {
            var toState = $transitions.$to().name;
            return dataService.POST({ State: toState }, 'isStateEnabled').then(function (data) {
                var isUserAllowed = data[0][0].IsStataEnabled;
                if (isUserAllowed) { }
            });
        });

  $transitions.onError({}, function ($transitions) {   
        });
```

**Comment by soorya02** [comment]
hi friends can u please help me to find a solution ,im using "angular": "1.6.0","angular-ui-router": "1.0.0-beta.3".  what i want  to do is to reject the current transition and redirected to the 'from' state the user now is at. On  every state change .onStart()  a request sends and response having the value is the user is allowed to enter the  'to' state and  need to reject/cancel  the transition and .onError() have to redirected to the 'from' state he is now at.

      ```
  $transitions.onStart({}, function ($transitions) {
            var toState = $transitions.$to().name;
            return dataService.POST({ State: toState }, 'isStateEnabled').then(function (data) {
                var isUserAllowed = data[0][0].IsStataEnabled;
                if (isUserAllowed) { }
            });
        });

  $transitions.onError({}, function ($transitions) {   
        });
```

**Comment by michaelcyyuen** [comment]
I didn't have this issue in angular 1.5.5, I just had it after upgrade to 1.6.1. Checking too

**Comment by ashishrp** [comment]
resolve: function (Auth) {
  if (Auth.isLoggedIn()) {
//do something    
}
  else {
   return $state.target('login');
  }
}
it works fine

**Comment by Akaryatrh** [comment]
@ashishrp This solution is only working for the first property:
```js
resolveObject: function (Auth) {
  if (Auth.isLoggedIn()) {
    //do something
  } else {
    return $state.target('login');
  }
}
```

If you have multiple keys, `$state.target()` would just do nothing when returned from a second resolve property. BUT, a `$state.go()` will work without triggering a `transition superseded` error.

```js
resolve: {
  firstResolveObject: ($state, whateverService) => {
    'ngInject';
    return whateverService.getInfo()
      .then(() => {
        return $state.target('app.stateOne');
      })
  },
  secondResolveObject: ($state, firstResolveObject, anotherService) => {
    'ngInject';
    return anotherService.getInfo()
      .then(() => {
        return $state.go('app.stateTwo');
      });
  }
}
```

It just doesn't make sense while the transition is supposed to run until all the `resolve` properties are resolved. Anyone would have a clear explanation about this issue?

**Comment by fatiha-hiit** [comment]
Hi @soorya02 

I am having the same issue as you, did you find any way to prevent default behaviour on transition?
returning $q.reject() does not work for me
