### ISSUE TITLE
Character encoding not UTF-8 in ui-view

### ISSUE THREAD

**Issue by artworkad** [angular-ui/ui-router#421]
Hi,

my project is UTF-8 encoded and characters like ÄÜÖ are displayed well. However in the ui-view section where the templates are loaded into those characters are displayed with Ã¤ .

My templates are UTF-8 too so where is the problem?

**Comment by mrtruko** [comment]
I have this problem

**Comment by vguna** [comment]
Same here.

**Comment by vguna** [comment]
Problem solved. For anyone hitting the same problem, check the following:

- Check encoding of file itself for UTF8
- Also check, whether the webserver, delivering the partials, returns the correct content-type within the header - e.g. utf8 (that was my problem). So maybe you have to configure Apache to return the correct content-type for .html files.

**Comment by AysenZakharov** [comment]
I have this problem.
My http server returns utf-8 by default and my html file encoded as utf-8.

**Comment by AysenZakharov** [comment]
Ok, i solved this problem. If you're have this problem save the template html like "utf-8 with BOM" not "utf-8". Have fun)

**Comment by heavyrick** [comment]
I had the same issue, turns out it was phpstorm codification windows-1252. I changed the project codification to UTF-8 and it's working fine o/
