### ISSUE TITLE
Preventing state reload on URL change

### ISSUE THREAD

**Issue by roryf** [angular-ui/ui-router#427]
I currently use the following code to prevent my route, and therefore controller, being reloaded when I update the $location:

``` javascript
angular.module('Shared').service('location', function($location, $route, $rootScope) {
  $location.skipReload = function () {
    var lastRoute = $route.current;
    var un = $rootScope.$on('$locationChangeSuccess', function () {
        $route.current = lastRoute;
        un();
    });
    return $location;
  };
  return $location;
});
```

along with:

``` javascript
location.skipReload().path("/newpath").replace();
```

Can I achieve the same behaviour with ui-router?

I tried simply replacing `$route` above with `$state` but this still resulted in a state change. My use case is I only have 'new' and 'edit' states which are exactly the same, when a user saves within the 'new' state I want to update the URL to include the saved id but not reload the view.

**Comment by jordangarside** [comment]
@intellix Did you ever find anything out about this issue? I for the life of me can't figure out a way around this.

**Comment by dmarcelino** [comment]
@roryf, your [decorator](https://github.com/angular-ui/ui-router/issues/427#issuecomment-33294859) worked perfectly for me. So far it was the cleanest solution I could find, thank you!

**Comment by vmihailenco** [comment]
@roryf thanks for the decorator. This is fixed version that uses $delegate:

```
locationDecorator = ($delegate, $rootScope) ->
  skipping = false

  $rootScope.$on '$locationChangeSuccess', (event) ->
    if skipping
      event.preventDefault()
      skipping = false

  $delegate.skipReload = ->
    skipping = true
    return this

  return $delegate


mod.config ($provide) ->
  $provide.decorator('$location', locationDecorator)
```

**Comment by mbernath** [comment]
@roryf, thanks for your decorator solution! I can confirm it works with ui-router 0.2.13 and angular 1.2.14.

**Comment by heygrady** [comment]
This seems to be a poorly documented option of the [`$state.go()`](http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$state#methods_go) function. Setting the `notify` options to false seems to keep everything from refreshing.

```js
//change state without refreshing everything
$state.go('my-state', { id: myId }, { notify: false });
```

**Comment by Schlogen** [comment]
@heygrady That worked for me

**Comment by soumak77** [comment]
@heygrady Thanks for the tip, worked great!

**Comment by elfan** [comment]
For some reasons, it didn't work for me.
But after tries and errors, accidentally I found a simple solution that works for me.
    $state.params.id = id;  //updating the $state.params prevents reloading the state
    $location.path('/folders/' + id);
I hope it helps someone.

Note: I'm using angularjs 1.2.7 and ui-router 0.0.1.
I do also have a custom global $stateChangeStart handler somewhere else but most likely not related to this solution (it is for doing some validation whether the target state is allowed or not).

**Comment by intellix** [comment]
This will allow what you're after. You can disable the notify on a link so the URL changes but doesn't reload your controller: https://github.com/angular-ui/ui-router/issues/1875

**Comment by jeremieca** [comment]
Hello, @nateabele 

It seems your code break the replace function

      $location.path('http://...').replace();

Am I wrong ?

**Comment by xaun** [comment]
@roryf legend mate! Worked on angular 1.3.16 & angular-ui-router 0.2.15.

**Comment by nateabele** [comment]
@jeremieca Show me.

**Comment by jeremieca** [comment]
@nateabele Thanks, it solved. I made a mistake :) Sorry.

**Comment by garmoshka-mo** [comment]
@roryf 
This decorator raises Circular Dependency (maybe only in latest angular)
https://github.com/angular-ui/ui-router/issues/427#issuecomment-24518433 

Inside of decoration function must be used `$delegate` argument instead of `$location`:

    angular.module('Shared', []).config(['$provide', function($provide) {
        $provide.decorator('$location', locationDecorator);
        function locationDecorator($delegate, $rootScope) {
            var skipping = false;

            $rootScope.$on('$locationChangeSuccess', function(event) {
                if (skipping) {
                    event.preventDefault();
                    skipping = false;
                }
            });

            $delegate.skipReload = function() {
                skipping = true;
                return this;
            };

            return $delegate;
        }
    }]);

**Comment by garmoshka-mo** [comment]
Though `event.preventDefault();` didn't worked for me. The very first solution was better.

Created lib from that: https://github.com/anglibs/angular-location-update

**Comment by rockallite** [comment]
@garmoshka-mo Great solution! It works like a charm. Back & forward buttons also work as expected. I'm using it in my production project.
@andremendonca Use `$location.path()` or `$location.search()` instead of `$state.go()` to change the URL without state reloading.

**Comment by rockallite** [comment]
@roryf @garmoshka-mo `location.skipReload().search(yourParams)` won't update `$stateParams`. Must be manually updated by `angular.extend($stateParams, yourParams)` afterwards.
