### ISSUE TITLE
Error: No such state undefined

### ISSUE THREAD

**Issue by thebigredgeek** [angular-ui/ui-router#433]
On line 140 of state.js:

    if (state && (isStr || (!isStr && (state === stateOrName || state.self === stateOrName)))) {

This should be:

    if (state && (isStr || (!isStr && (state === stateOrName || state.self === stateOrName.self)))) {

Otherwise, that last case will never pass.  I found this bug several nested child states deep.

I have created a patch and I am submitting a pull request

**Comment by eddiemonge** [comment]
Closing as this is no longer true. Adding that change breaks a lot of things.
