### ISSUE TITLE
CSS3 animation break in Chrome with ui-view/ng-show combination

### ISSUE THREAD

**Issue by dfaivre** [angular-ui/ui-router#458]
See this JSFiddle for the best description: http://jsfiddle.net/dfaivre/KZNf3/6/.

*EDIT*: It looks like the progress bar initially animates.  Click "Run" to re-run and see the described behavior

Specifically, using Bootstrap progress bars and Font Awesome spinner icon animations (as in the JSFiddle), if there is a ui-view anywhere in scope AND one of the animation classes is hidden using ng-show, all other animations in scope won't be active.

If you use developer tools and toggle the animation class, it will animate.

It works in IE (10) and Firefox -- so this may be a chrome bug.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
