### ISSUE TITLE
Throw Error when `resolve` does not find dependency to inject

### ISSUE THREAD

**Issue by frapontillo** [angular-ui/ui-router#469]
Say I have a `factory` called `Config` and there is a state such as:

``` javascript
$stateProvider.state('app', {
  url: '/',
  templateUrl: 'views/main.html',
  controller: 'MainCtrl',
  resolve: {
    config: function(Config) {
      return Config.reloadConfig();
    }
  }
}):
```

The `resolve` function of course fails, but no `Error` is thrown! When the project is minified (which is the only case when you notice something is wrong) finding this error is a pain; I had to go by trial and error through a lot of files to notice this.

**Comment by booybooy** [comment]
Just got bit by this while refactoring from ngRouter to uiRouter. Spent a good chunk of my morning trying to figure why the page is not loading while no errors are showing on console. So +1 for @nicovalencia suggestion.

**Comment by nicops** [comment]
A console.error never hurt anybody and can be easily done. People could find it annoying because the error was actually expected and was actually catched in some cases? Ok, but that annoyance is far less a deal than an error being silently swallowed!

**Comment by AlicanC** [comment]
```javascript
var app = angular.module('myApp', []);

app.run(['$rootScope', function ($rootScope) {
        
    $rootScope.$on('$stateChangeError', function (event, toState, toParams, fromState, fromParams, error) {
        
        throw error;

    });
    
}]);
```

**Comment by demisx** [comment]
@AlicanC :+1: This is a must for any app using ui router.

**Comment by dsulli99** [comment]
@AlicianC that's the jam right there.  Thanks buddy.

**Comment by OndeVai** [comment]
Please, log a console error! I don't care about esoteric arguments regarding promises, this has wasted the time of MANY developers and needs to be addressed!

**Comment by nateabele** [comment]
@OndeVai `$rootScope.$on("$stateChangeError", console.log.bind(console));`

**Comment by blittle** [comment]
It is a cardinal sin for a library to swallow user errors!

**Comment by nateabele** [comment]
Show me a promise-based library that surfaces any kind of errors outside of promise rejection.

**Comment by blittle** [comment]
@nateabele RX.js (reactive extensions) will surface an error if there is no handler to accept it.

**Comment by nateabele** [comment]
Rx.js is observable-based, which has the benefit of being explicit about managing handlers and flow as first-class things. I can't think of a way to detect whether a `$stateChangeError` handler is registered. The hooks system in 1.0 is a little different, so we could possibly address it then.

**Comment by AlicanC** [comment]
People are having this problem since 2013. You either have to fix your library or fix your documentation.

Throwing an error might not be a solution but putting a big fat red box in the documentation which warns users about this is a solution.

Also, does `$rootScope.$on("$stateChangeError", console.log.bind(console));` even work if you put it in your state controller? I think this should be in `app.run()` and if that is the case, that should also be specified.

**Comment by eddiemonge** [comment]
its documented at http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$state#events
they could be more clear though.

**Comment by nateabele** [comment]
> You either have to fix your library or fix your documentation.

I'm open to suggestions on how to do the latter.

**Comment by windmaomao** [comment]
It'll be highly recommend to check $stateChangeError by default, maybe we could just add a listener in the library ?

**Comment by nateabele** [comment]
Yes, 1.0 will have a default error handler.

**Comment by nonplus** [comment]
A missing dependency in a state resolve definition is a **programming mistake** and the library should help us catch these.  This is a different from a resolve that fails (returns a rejected promise) which is a **run-time error**.

I would expect these mistakes to be logged out of the box (and possibly add a config option to suppress this logging for hacks that prefer to ignore errors).  For now, I'm forced to do the following in my apps:
```
$rootScope.$on( '$stateChangeError', function (event, toState, toParams, fromState, fromParams, error) {
	if (error.message.match(/\[\$injector:unpr\]/)) {
		// Log missing 'resolve' dependency
		// See: https://github.com/angular-ui/ui-router/issues/469
		console.error("Invalid resolve in state '" + toState.name + "' - " + error.message);
	}
});
```

**Comment by nonplus** [comment]
I've published my workaround as https://github.com/nonplus/angular-ui-router-resolve-error.

Although I'd still prefer/expect this behavior to be built in...

**Comment by christopherthielen** [comment]
See https://ui-router.github.io/docs/latest/classes/state.stateservice.html#defaulterrorhandler in 1.0

**Comment by moneytree-doug** [comment]
Just wanted to say that this happens still, and that I support a functionality  that throws

**Comment by AldoMX** [comment]
@nonplus 's workaround was still failing silently, so I simply did the right thing to do: explode at any error, no mercy.

```
$rootScope.$on( '$stateChangeError', function (event, toState, toParams, fromState, fromParams, error) {
    throw error;
});
```

**Comment by moneytree-doug** [comment]
@AldoMX That's the correct expected behaviour

**Comment by peterbraden-amana** [comment]
This is a horrible experience - I spent days trying to find an error in an unrelated piece of code because an injection error was swallowed. AldoMX's fix should be the default behaviour.
