### ISSUE TITLE
Parallel state handling

### ISSUE THREAD

**Issue by mateusleon** [angular-ui/ui-router#475]
Sorry to disturb this issue list with this question but I really don't have a clue about it.

It's possible to set the ui-router to change one view without changing any other, without the need to declare them?

For example: when navigating on the app, some actions are pointed to one view: the view A. However, the user can click on one link that is pointed to other view in the application: the view B. What I need is change the view B letting the view A on the same state that the user choosed before clicking on the link that changes the view B.

It's like working with and Frame-Based app, because any frame is navigable independently, however it's possible to exchange info between them. 

If isn't possible to do that on the current release I suggest this implementation, because is realy handy and provides the ability to create dynamic states independently.

Here's the Plunkr with a close behavior: http://plnkr.co/edit/wJXx9R.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
