### ISSUE TITLE
Ability to use Controller As syntax in routing

### ISSUE THREAD

**Issue by DServy** [angular-ui/ui-router#477]
With angular 1.2rc2

```
.state('index',{
  url:"/",
  templateUrl:"views/index.html",
  controller:"IndexCtrl",
  controllerAs:"index",
})
```

<strike>Doesn't seem to want to work, and declaring controllers on the includes of files leads to controller not found issues when using the back button for navigation.</strike> (Edit, this issue was caused by not registering a controller with the app using the app.controller('name', function) )

**Comment by troywray** [comment]
I like the controller as syntax but as parent-child controllers are common, can a child controller set a watch on a parent controller variable without knowing the instance name of the controller? (I don't want to debate the need to use $watch in this instance, the question is probably relevant to other scenarios)

Trying to watch for changes in a parent 'active ID' from the child controller so I could retrieve the relevant child data for a child view, it seems I have to refer to the 'as name' i.e.

$scope.$parent.$watch( 'controllerasname.activeID' )
alternatively this works too:
$scope.$watch( '$parent.controllerasname.activeID' )

So the child needs to know the name used for controller as, limiting its usefulness as a re-usable component?

I tried all other ways I could imagine without using the controllerasname and none of them correctly triggered the watch.
