### ISSUE TITLE
ui-router problem with require js with AMD loading .

### ISSUE THREAD

**Issue by defyjoy** [angular-ui/ui-router#479]
I tried this 

http://stackoverflow.com/questions/19069769/router-not-found-error-in-ui-router-angularjs-with-requirejs/19161654?noredirect=1#19161654

unfortunately the answer didnt solve the problem . Its not able to load the angular ui router . it still shows the same error in both firefox and chrome . Any solution for this ?

**Comment by wishma2013** [comment]
If I want to compress and concat javascript file in requirejs+angular+ui-router project,How should I organize all my scripts file's?

**Comment by rhka** [comment]
Hi,  We are using stateprovider in our application. But, we want to load the controller files dynamically. I dont know how to acheive this. Could you please help me to do that. We are able to load the files dynamically using route provider. But, i want with Stateprovider. Thanks

**Comment by amitguptainn** [comment]
All, I observed that this code works as we use angular.bootstrap. Same does not work with ngApp. Any idea?

**Comment by CheolJeJo** [comment]
@kuma0605 thank you very much :D

**Comment by ejongg** [comment]
Did anyone managed to make this work on ui-router 1.0.0 ?

**Comment by linlak** [comment]
Mine worked ui-router has a dependence for requires all you need to do in your app.js file you need to add angular-ui-router that is all you will be good to go. app.js should be like
define(['angular-ui-router','uirouter', etc],....);
uirouter is your file parth but angular-ui-router is a dependence for AMD that uirouter provides. I have to dig into uirouter and discovered that if you also go to the code in uirouter and you are good in require js you will it. It is at the beginning of the code. Tell me if it works for you. Thanks

**Comment by linlak** [comment]
When using require js you don't have to use the ngApp directive to prevent auto bootstrap because if bootstrap happens before dependence files are loaded it produce errors that is why we have to use angular.bootstrap and not ngApp
