### ISSUE TITLE
Use the same controller for all views in multi-views states

### ISSUE THREAD

**Issue by Neozaru** [angular-ui/ui-router#494]
Given this example from Wiki, when using multiple views in one state, user have to specify a controller for each view

```
$stateProvider
  .state('report',{
    views: {
      'filters': {
        templateUrl: 'report-filters.html',
        controller: function($scope){ ... controller stuff just for filters view ... }
      },
      'tabledata': {
        templateUrl: 'report-table.html',
        controller: function($scope){ ... controller stuff just for tabledata view ... }
      },
      'graph': {
        templateUrl: 'report-graph.html',
        controller: function($scope){ ... controller stuff just for graph view ... }
      },
    }
  })
```

In my own case (I think I'm not alone), for some states, I use the same controller for all my views (example: I have a view for the Left Panel, Top Panel, etc, and sometimes each of these views have to access to the same context).

It would be good to add a parameter in states allowing to add a common controller for all views of this state.

Sample of my code

```
        .state('project' , {
            url: '/projects/{project_id:[0-9]+}',
            views: {
              "page": { templateUrl: PAGES_PARTIALS_FOLDER + 'project.html' },
              "leftMenu":  { templateUrl: LEFT_MENU_PARTIALS_FOLDER + 'project.html' },
              "rightMenu": { templateUrl: RIGHT_MENU_PARTIALS_FOLDER + 'project.html' }
            },
            controller: 'projectCtrl' // Doesn't work, I have to define a controller per view
        })
```

**Comment by verdi327** [comment]
+1

**Comment by oi-sendai** [comment]
+1 for 'non contiguous' @masaeedu  totally agree that this seems a thing you might want to do. Totally get that it might be difficult to impliment or going against the grain, but it's certainly the use case that brought me to this thread

**Comment by Dryymoon** [comment]
How to use sared controller in multi views?

**Comment by asaarnak** [comment]
+1

**Comment by gokussx4** [comment]
+1 

My thought for the time being was putting the controller on the rootscope so I can use that same instance. Thoughts?

**Comment by asaarnak** [comment]
I ended up creating a service and sharing a variable.

    angular
        .module('app.steps')
        .factory('stepsService', stepsService);

    function stepsService() {
        var sharedData = { isInserted: false };

        var service = {
            sharedData: sharedData,
        };

        return service;
    }

**Comment by forcewill** [comment]
+1
Im my case i just have 3 views, sidenab, toolbar, and content view

i just want to show the title on the toolbar based on the model that is being shown on the content view, it seems to me that to have a service just for that use case an overkill

**Comment by masaeedu** [comment]
FWIW, I've decided to stop fighting it and just made a service. It's not like making a service is a lot of code, and you can stick a bunch of odds and ends in the same file.

**Comment by Borodin** [comment]
+1

**Comment by paanoop** [comment]
+1
If there was a single controller of many views there is code reuse. Other-wise it's code duplication/triplication or whatever.

**Comment by spenoir** [comment]
Theres nothing stopping you from using the same controller for each of your views, I do a lot. It makes sense in some situations

**Comment by masaeedu** [comment]
@spenoir I don't know if the behavior has changed in the years since the issue was opened, but string reference to controller didn't work in the past, as shown in the second snippet of the issue.

**Comment by jseta** [comment]
+1

**Comment by Kaz-** [comment]
+1

**Comment by ET-CS** [comment]
+1

**Comment by kidroca** [comment]
If you define a parent state you can render a template and a controller in the  
parent view and it will be available in the child state views:  

Something like this: https://embed.plnkr.co/ovtCMb/

**Comment by vaso2** [comment]
@kidroca You're my savior! Looked for exactly this stuff for months!
