### ISSUE TITLE
Enhanced route syntax

### ISSUE THREAD

**Issue by lrlopez** [angular-ui/ui-router#5]
Discussion on how augment route definition (regexp, optional params, constraints,...)

We should agree in the following, in no particular order:
- [ ] Optional parameters
- [ ] Type definition (restrict to string, to integers, paths, list). Especially important is the path, as it allows using parameters that contain slashes.
- [ ] Min/max length
- [ ] Regexp syntax

We could use the following pull-requests as a guide:
- Pull Request angular/angular.js#918: $route should allow regexps params
- Pull Request angular/angular.js#972: feat($route): regexp support for $route params
- Pull Request angular/angular.js#1402 fix($resource) Route constructor, updated RegExp
- Pull Request angular/angular.js#1560: feat(routeProvider): Add support to catch-all parameters in routes
- Pull Request angular/angular.js#1634: Improved Angular routing in a backwards compatible way.
- And of course, the discussion on #1

**Comment by pranaydutta89** [comment]
:+1:

**Comment by christopherthielen** [comment]
wat
