### ISSUE TITLE
Trailing slash in url breaks state routing

### ISSUE THREAD

**Issue by jbellmore** [angular-ui/ui-router#50]
If the url contains a trailing slash the state routing does not recognize the url and transition to the correct state.

For example, if you define the following state:

<pre>
$stateProvider
       .state('contacts', {
           url: '/contacts',
           templateUrl: '/contacts.html',
           controller: 'ContactsController'
       });
</pre>

When you go to <strong>#/contacts</strong> it routes to the 'contacts' state correctly, however if you go to <strong>#/contacts/</strong> the route is not recognized.

The only workaround I have found is to define a second route which contains the trailing slash with a different name but that is quite cumbersome to have to do for every single state in an application.

Thanks!

**Comment by pasupulaphani** [comment]
I have had an issue with html5mode(true) and has an hash in a url it goes to infinite loop.

http%3A%2F%2Fexample.com%2Fposts%2F
http%25253A%25252F%25252Fexample.com%25252Fposts%25252F
http%252525253A%252525252F%252525252Fexample%252525252Fposts%252525252F

**Comment by alanguir** [comment]
@homerjam your last code snippet in this thread worked great for me!

**Comment by rebelliard** [comment]
The snippet on the [FAQ](https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-make-a-trailing-slash-optional-for-all-routes) breaks when you `html5mode(true)` and try to use a hash on a URL, as pointed by @pasupulaphani [here](https://github.com/angular-ui/ui-router/issues/50#issuecomment-73152559).

[This version](https://github.com/angular-ui/ui-router/issues/50#issuecomment-26133077) from @homerjam works, however.

**Comment by snaikaw** [comment]
If you just want to allow "/" at the end of the URL, then you can use regular expression like this:
```
$stateProvider
       .state('contacts', {
           url: '/contacts{dummyParam:[/]?}',
           templateUrl: '/contacts.html',
           controller: 'ContactsController'
       });
```

**Comment by kbiesbrock** [comment]
Nice, @snaikaw!

**Comment by jgentes** [comment]
I found `$urlMatcherFactoryProvider.strictMode(false)` to be the simple solution I was looking for.

**Comment by pfrankov** [comment]
@jgentes you just saved my day! Thank you so much!

**Comment by jml6m** [comment]
Just want to say @jgentes method did not work for me

**Comment by jgentes** [comment]
@jml6m if you're using Node/Express, this is another approach to remove trailing slashes:
```
// remove trailing slash
app.use(function(req, res, next) {
    if(req.url.substr(-1) == '/' && req.url.length > 1)
        res.redirect(301, req.url.slice(0, -1));
    else
        next();
});
```

**Comment by jml6m** [comment]
I ended up using this method:

```javascript
$urlRouterProvider.rule(function($injector, $location) {

    var path = $location.path();
    var hasTrailingSlash = path[path.length-1] === '/';

    if(hasTrailingSlash) {

      //if last charcter is a slash, return the same url without the slash  
      var newPath = path.substr(0, path.length - 1); 
      return newPath; 
    } 

  });
```

**Comment by stefanotorresi** [comment]
I've found the @jml6m's method to be the simplest at getting rid of the trailing slash.

**Comment by gaui** [comment]
I've found @jgentes solution to be the best.

**Comment by mleanos** [comment]
The solutions that add a `$urlRouterProvider.rule` work fine. However, if you define your UI routes in separate configurations (in their respective module) you are required to define this same logic in each of your module configurations. I wasn't too fond of that idea. If I'm wrong in my assessment of how these *rules* work, then please correct me. I had had no luck adding this to my application configuration. And from what I read, it's just not possible.

Since I didn't want to add this to each module's route configuration, I ended up adding a function that does pretty much what @jml6m's solution does to the beginning of the `$stateChangeStart` event.

```javascript
  // Check authentication before changing state
  $rootScope.$on('$stateChangeStart', function (event, toState, toParams, fromState, fromParams) {
    // Ensure we don't transition to a URL with a trailing slash
    preventTransitionWithTrailingSlash(event);
  ...... // other logic that will execute if no trailing slash is found
  });

  function preventTransitionWithTrailingSlash(event) {
    var path = $location.$$url;

    // Check if the current transition has a trailing slash
    if (path.length > 1 && path[path.length - 1] === '/') {
      event.preventDefault();

      // $location.path() needs an async operation to work
      $timeout(function () {
        $location.path(path.substr(0, path.length - 1));
      });
    }
  }
```

Does anyone see any issues with this approach? I would love a cleaner solution. I find it odd that there isn't an easier way to handle this at an application level.

**Comment by stefanotorresi** [comment]
Hmm I'm not sure I understand why you can't just use the `$urlRouterProvider.rule`. You only have to do that once, there is no need to repeat that in each module.

Also, you can put the snippet in a dedicated module and have all other modules depend on it.

**Comment by mleanos** [comment]
@stefanotorresi You're absolutely right! I was misinterpreting the behavior I was seeing, as the Rule not getting applied to my sub-modules. There seems to be a couple things going on with the issues that I'm having.

1) Nested routes can cause conflicts, when the URL is defined like this: `{ url: '/:parameter' }`
```
For example, the below config will cause conflicts

articles      - { url: '/articles', abstract: true }
articles.list - { url: '' }
articles.view - { url: '/:articleId' }

Is the solution to refactor this route config? The below routes won't have the same conflict

articles      - { url: '/articles', abstract: true }
articles.list - { url: '' }

article       - { url: '/article', abstract: true }
article.view  - { url: '/:articleId' }
```
2) The load order of the angular modules might be causing weird behavior with the `$urlRouterProvider` service.

I'm working with the MEANJS project, and I've pushed a branch up to my fork to demonstrate the behavior I'm experience. The diffs will show you where I'm having issue, and I've added some inline comments to further explain. I apologize if this is a bit much, but at this point, I could use some more eyes on this; been working on this for over 10 hours now.

https://github.com/mleanos/mean/commit/132d23ae721a3a5bc5aaaeb4136f987986285aaa

**Comment by esetnik** [comment]
I found the @jml6m solution didn't work because it seems that the rule is attempted only after a failure to match on an existing state. From @mleanos example above the `articles.view` is still triggered and the the rule is never applied if the user navigates to `/articles/` 😦

**Comment by esetnik** [comment]
Oh nevermind... it turns out that there's a race condition between `$stateProvider.state` and `$urlRouteProvider.rule`. If you set the `$urlRouteProvider.rule` before the `$stateProvider.state` then it is applied on every request, but if you set it after then it is only applied on requests that fail to match any state configs.  @mleanos maybe this is what you were experiencing above.

**Comment by adambuczynski** [comment]
None of the solutions stated here are working for me. As soon as I append a trailing slash, the app shows the 404 page (which is the `otherwise` page).

Tried with the documented `$urlMatcherFactoryProvider.strictMode(false)` as well.

**Comment by javoire** [comment]
@mleanos, your fix works for me, _but_ I need to trigger it on `$locationChangeStart` for it to work fully, i.e. before ui router kicks in. Covering the case of when someone navigates directly (i.e. not clicking a link) to a url with trailing slash. Just wanted to mention that if others run into it. Cheers

**Comment by christopherthielen** [comment]
@javoire ui-router offers [deferIntercept](https://ui-router.github.io/docs/latest/classes/url.urlrouterprovider.html#deferintercept) for doing things before the URL is synchronized.

**Comment by javoire** [comment]
Thanks for the info! I'll try it out

**Comment by tsuz** [comment]
`$urlMatcherFactoryProvider.strictMode(false);` will match `'/path'` and `'/path'/`

**Comment by abhaygarg** [comment]
Hi Now ui-router have strictMode to handle it
You need to set strictMode = false 
**Ex**
$urlMatcherFactoryProvider.strictMode(false); 
You need to set strict mode before initialising the State $stateProvider.state({})

For more details you can refer this [Link](http://www.zippyout.com/blog/58c76355e890296b902966c8/angular-ui-router-trailing-slash-case-sensitive-issue)

**Comment by adamreisnz** [comment]
https://ui-router.github.io/ng1/docs/latest/classes/url.urlmatcherfactory.html#strictmode for the recent docs

**Comment by ginobean** [comment]
IMO, this should be the DEFAULT setting. If a developer is actually doing two different things with a URL based solely on whether the route ends with a slash or not, that seems a bit CRAZY to me..
