### ISSUE TITLE
Url params leaking to unrelated states.

### ISSUE THREAD

**Issue by ADmad** [angular-ui/ui-router#504]
Using the `angular-1.2` branch I have setup states/routes similar to this:

```
$stateProvider.
	state('foo', {
		url: '/foo/:date',
		templateUrl: 'views/foo.html',
		controller: 'FooCtrl'
	}).
	state('bar', {
		url: '/bar/:date',
		templateUrl: 'views/bar.html',
		controller: 'BarCtrl'
	});
```

I have menu links:
```
<a ui-sref="foo">Foo</a> //generates href="/#foo/"
<a ui-sref="bar">Bar</a> //generates href="/#bar/"
```

Assuming I am on url `#/foo/2013` if i clik the link for "Bar" it's takes me to `#/bar/2013` while i expect it to take me to url `#/bar/`. The route param of unrelated states should not be carried over.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
