### ISSUE TITLE
Using $location.hash()

### ISSUE THREAD

**Issue by acroca** [angular-ui/ui-router#510]
Hi everyone,

First of all, thanks for this great project!

Is there any way of sending `$location.hash()` to a state?

I've checked the code and the default `options.location` when going to a new state is `true`, so it rewrites the location getting rid of the hash. Also I tried to create a state with a url like `/:id#:section` but didn't work.

In case this is still not supported what do you think it's the best approach to define a state with hashes in the url?

Thanks

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by mssalnikov** [comment]
As per note, I'm commenting to say I'm still affected by this issue, since I need to match urls like `/{param1:[0-9]+}/{param2:#?[0-9]+}

**Comment by richfergus** [comment]
@mssalnikov,
I got the $state to work in this:

        $scope.flightHours = function() {
            $state.go('app.ops.main',{'#':'red'});
         };

With this anchor tag on the ops.main template:
       
        <div class="row" id="red">

**Comment by mssalnikov** [comment]
@richfergus Hey! 

Yes, I'm aware of that solution, yet it only works from withing angular, when you change the state manually. My case is this: users have to be able to access url https://domain.com/3456/#1234, and $state does not match this to a `/{param1:[0-9]+}/{param2:#?[0-9]+}`. My workaround is therefore ugly AF:

`
.state('catch', {
            url: '/{param1:[0-9]+}/',
            onEnter: /* @ngInject */ ($state) => {

                if (location.hash) {
                    $state.go('state', {param1: $state.params.param1, param2: location.hash})
                }
            }
        })
`
