### ISSUE TITLE
ui-router and android 2.2 browser

### ISSUE THREAD

**Issue by heinij** [angular-ui/ui-router#531]
ui-sref links do not work in the Android 2.2 browser. The problem seems to be in
the parseStateRef function in angular-ui-router.js 

function parseStateRef(ref) {
  var parsed = ref.match(/^([^(]+?)\s*(\((.*)\))?$/);
  if (!parsed || parsed.length !== 4) throw new Error("Invalid state ref '" + ref + "'");
  return { state: parsed[1], paramExpr: parsed[3] || null };
}

parsed always returns null

**Comment by OscarBarrett** [comment]
This problem still affects iOS 4, though I'm not sure if there is any point supporting a mobile OS that is now 5 years old.

**Comment by eddiemonge** [comment]
Yeah IOS 4 support doesn't seem like its needed.

https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
