### ISSUE TITLE
[1.2 branch] Need a way to opt into the old animation behaviour for ui-view

### ISSUE THREAD

**Issue by jonrimmer** [angular-ui/ui-router#534]
In 0.2, animations are applied to the child elements of the ui-view. However, in the 1.2 branch, this has been changed so the animations are applied on the ui-view element itself, which is cloned when the view changes.

Unfortunately, this approach breaks a vital styling requirement: The ability to use the :empty CSS selector to style the ui-view when it contains no child elements, e.g. when it has no view selected, and then transition to a different appearance when a view is selected. 

This plunkr demonstrates how it is done in 0.2: http://plnkr.co/edit/B31D5b?p=preview

As far as I can tell, this example is impossible to replicate using the 1.2 branch. Neither ngAnimate nor a wrapping element can be used to achieve the same effect.

I suggest that ui-view defaults to the new animation behaviour, in order to match Angular 1.2, but provides a switch that replicates the old behaviour if required.

**Comment by eddiemonge** [comment]
This seems like it has been resolved in the PRs or at least it can be worked around.

You can/should/please also try the new [feature-1.0 branch](https://gist.github.com/eddiemonge/f9f8cb0a9dc7f42515db) that is in development to see if it satisfies this. Keep in mind this is still in development but it is the direction the project is heading. If you want to file a ticket against this branch, use the format `1.0: (subject)` for the subject.

Thank you for supporting and contributing to the project.
