### ISSUE TITLE
Unit Testing ui-router

### ISSUE THREAD

**Issue by zdwolfe** [angular-ui/ui-router#537]
I'm having difficulties unit testing on state transition using Karma/Jasmine.
According to ui-router's own [test/stateSpec.js](https://github.com/angular-ui/ui-router/blob/master/test/stateSpec.js#L108), I might test state transition with something like the following:

```
it('should should transition to main.course', inject(function ($state, $q) {
    $state.transitionTo('main.course');
    $q.flush();
    expect($state.current).toBe('main.course');
  }));
```

However I'm getting an error:

```
TypeError: 'undefined' is not a function (evaluating '$q.flush()')
```

Can someone shed some light on this? I'd appreciate it. The error is very cryptic.

My [full test](https://gist.github.com/zdwolfe/7221982) is:

```
'use strict';

describe('Controller: CourseCtrl', function () {

  // load the controller's module
  beforeEach(module('myApp'));

  var CourseCtrl, scope;
  // Initialize the controller and a mock scope
  beforeEach(inject(function ($controller, $rootScope) {
    scope = $rootScope.$new();
    CourseCtrl = $controller('CourseCtrl', {
      $scope: scope
    });
  }));

  it('should should transition to main.course', inject(function ($state, $q) {
    $state.transitionTo('main.course');
    $q.flush();
  }));
});
```

I've recreated a very minimal application that tests this [here](https://github.com/zdwolfe/fooApp).

**Comment by tonylampada** [comment]
@zdwolfe, your "fooApp" repo is missing. Do you still have it somewhere?

My particular problem is that state controllers are not being executed. Let's say that your 'main.course' state had a controller (MainCourseController) attached to it. After transitioning to main.course and $rootScope.$apply() one would expect that MainCourseController would be executed (right?)

Was this supposed to work?

**Comment by zdwolfe** [comment]
@tonylampada Nope! Sorry

**Comment by eddiemonge** [comment]
You could also manually populate $templateCache with dummy data instead of including the views.

**Comment by brutalcrozt** [comment]
how to test the dependencies on the controller?
i have 4 things on state.resolve, sorry i am new on this.

**Comment by nateabele** [comment]
@brutalcrozt Please see StackOverflow for support: http://bit.ly/UIR-SOF — Thanks.
