### ISSUE TITLE
ui-router and bootstrap nav link

### ISSUE THREAD

**Issue by rekna1** [angular-ui/ui-router#570]
I have an angular app with ui-router and bootstrap3. Initialy it shows a search form. When I click on the search button, I transition to the state search.results. In this state, 2 subviews are loaded, one which shows an options menu and one for showing the search results. The options menu is implemented as a bootstrap nav bar. One of the options is a dropdown menu with links for different options, like this:

```
<a href="#" data-ng-click="vm.showOnlyLastMonth()">last month</a>
```

When I click on the link, it seems to change the route ( I see the url changing from #/results to #/ ).. I can see the vm.showOnlyLastMonth() is executed, but the options and search results disappear (I'm back at the base route).

It works when I change all <a href="#"  to <a data-ui-sref="search.results" but I wonder if this is necessary, and the behavior with <a href="#" is the correct behavior ?

**Comment by okigan** [comment]
I think this is a bug, 'a' element shall have href filled in (per spec) and href="#" is commonly used to fulfill that requirement. Hence <a href="#">...</a> shall have expected behavior.
