### ISSUE TITLE
State: onEnter callback executed before template added to DOM

### ISSUE THREAD

**Issue by iandev** [angular-ui/ui-router#575]
A states onEnter callback is executed before the template is added to the DOM.  In the UI router docs, one of the examples shows a modal dialog being triggered in the state onEnter callback.  This is fine, but in the example, the modal doesn't rely on the template being in the DOM already.  So, according to the docs, the onEnter/onExit is a good place to open/close a modal dialog, but the states template should be in the DOM by the time the onEnter callback is fired.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
