### ISSUE TITLE
IE 8 & 9 Index routing issue with angular 1.2.0

### ISSUE THREAD

**Issue by wlingke** [angular-ui/ui-router#576]
We are using ui-router 0.2.0 and we recently upgraded from angular 1.1.4 to angular 1.2.0 and noticed a weird issue. We are using 

```
$locationProvider.html5Mode(true);
$locationProvider.hashPrefix('!');
```

Our index state was defined as such:

```
.state("index", {
            url: "/",
            templateUrl: "/static/partials/general/index-router.html"
        })
```

This work correctly in chrome FF and IE10. However, when navigating to / in IE 9 or 8, it loads a blank page. I added an alert onEnter, and the alert doesn't execute so it seems like I never reach that state. This was not an issue and was properly working before we upgraded to angular 1.2.0.

A work around we used was adding:

```
.state("index2", {
            url: "",
            templateUrl: "/static/partials/general/index-router.html"
        })
```

This solved the problem and we are able to reach / in ie 9 or 8. However, an odd result is that when navigating to / from another state, it executes the state twice (we also added an onEnter alert and it executed twice).

Has anyone else come across a similar issue?

**Comment by nicksloan** [comment]
the $urlRouterProvider.when('', '/'); trick is handy, but breaks down if you have query string parameters in the root state, so I had to do the duplicated state definition. This seems like a breaking change from upstream, so the question is whether it was an intentional feature, or an unintentional bug, and how ui-router should respond to it.

**Comment by nicksloan** [comment]
$urlRouterProvider.when('', '/'); will not fix this if you have state params in the query string on your '/' state. You need to duplicate your state definition in that case.

**Comment by sixinli** [comment]
Is $urlRouterProvider.when('', '/') the only solution here? it feels weird because there's actually an ending "/" in the URL in IE 8 & 9.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
