### ISSUE TITLE
$state.reload() should reinitialize the controller

### ISSUE THREAD

**Issue by ghengeveld** [angular-ui/ui-router#582]
As discussed in #76, $state.reload() does reload the resolves, but doesn't reinitialize the controller with the newly resolved values. Since the whole point of reloading the resolves is to refresh the scope with the new data, reinitializing the controller is a requirement for $state.reload() to be of any use.

Demo: http://plnkr.co/edit/GNr1bN?p=preview

**Comment by softBarbarian** [comment]
Actually I soved differently: basically I fetch data $ionView.loaded lifecycle event

**Comment by hpawe01** [comment]
If you are using the current **ionicframework** (ionic: v1.0.0-beta.14, angularjs: v1.3.6, angular-ui-router: v0.2.13), the problem with the not-reloading-controller could be caused by the [new **caching**-system of ionic](http://ionicframework.com/docs/api/directive/ionNavView/):
>Note that because we are caching these views, we aren’t destroying scopes. Instead, scopes are being disconnected from the watch cycle. Because scopes are not being destroyed and recreated, **controllers are not loading again** on a subsequent viewing.

There are several ways to disable caching. To disable it only for a single state, just add `cache: false` to the state definition.

This fixed the problem for me (after hours of reading, trying, frustration).

For all others not using ionicframework and still facing this problem: good luck!

**Comment by gregor-srdic** [comment]
Thank you very much for this post hpawe01, I lost quite a few hours due to this new feature and cache: false worked perfectly!

**Comment by malixsys** [comment]
@hpawe01 Indeed! +1

    $stateProvider.
      state('home', {
        url: '/',
        cache: false,

**Comment by oozzal** [comment]
Thanks @hpawe01. Certainly saved me few hours. :clock10:

**Comment by munkychop** [comment]
+1 for an official fix please.

The proposed milestone of this issue (at the time of writing) is 0.2.12 and the current release version of ui-router is 0.2.13. Is the issue likely to be fixed anytime soon? If so, when roughly?

ui-router is amazing! But this issue has been open for over a year...

**Comment by christopherthielen** [comment]
This issue was closed 2 months ago

**Comment by munkychop** [comment]
Oh, my apologies, I assumed it needed re-opening due to the posts from a few days ago.

Thanks for the fix :)

**Comment by ehlerskon** [comment]
thanks @hpawe01 - you saved my day!

**Comment by pholly** [comment]
I see that this issue was closed 2 months ago and included in the 0.2.12 release: https://github.com/angular-ui/ui-router/commit/7344342018847902594dc1fc62d30a5c30f01763

Does anyone know if this fix works even when `reloadOnSearch=false` is defined for the state? Based on the comments of @metamatt  in https://github.com/angular-ui/ui-router/issues/582#issuecomment-41454177 and @travisdahl in https://github.com/angular-ui/ui-router/issues/582#issuecomment-56208241 even if `notify` is set to true the controller will not get reinstantiated if `reloadOnSearch` is false.

**Comment by nichthinkof30** [comment]
using ionic framework Thanks @hpawe01 for the fix !

**Comment by dhautot** [comment]
+1 @hpawe01 
thanks !

**Comment by abelorian** [comment]
@hpawe01 thank!

**Comment by brunodb3** [comment]
@hpawe01 Awesome fix!! Thank you very much!

**Comment by esperyong** [comment]
@hpawe01 Thank you! This problem spend me few hours . 

$stateProvider.
  state('some', {
    url: '/some',
    cache: false,

**Comment by steppefox** [comment]
@hpawe01 thank you!

**Comment by liquidcms** [comment]
Can someone tell me if my issue is what is being addressed here?

my default starting state is tied to a controller. (after first install and run of app) this controller draws a map (and does other things). If, while getting data for the map i see there is no internet connection; i simply display a msg stating "no internet" and i return out of the controller (whichleaves msg stuck on the screen and app basically stalled).

the goal is to RERUN the controller after the user goes to his settings and enabled his wifi.

i have added in .run an on resume watch: $ionicPlatform.on('resume', function(){}) and tried dozens of possible methods of rerunning my default controller including everything mentioned in this post and other posts.

- $state.reload()
- $state.go()
- $state.transitionTo($state.current, $state.$current.params, {reload: true, inherit: false, notify: true});
- disabling cache for this state
- adding a broadcast in .run and then watching for it in controller
and many version of all of these.

I can get transtionTo code hit in many different ways; and it returns with $state.current but the first line of my controller is never hit again. and, of course, no errors.

as usual with angular, burned up a day with what should be 2 lines of trivial code... any hints on how to FORCE a page load?

**Comment by dshefchik** [comment]
Ok honestly this is still broken. And none of these workarounds worked at all. I tried all of the following: 

```
$state.reload();
$state.go($state.current, {}, { reload: true  });
$state.transitionTo($state.current, $stateParams, {  reload: true, inherit: false, notify: false  });
$state.transitionTo($state.current, $stateParams, {  reload: true, inherit: false, notify: true  });
$state.transitionTo($state.current, {}, {  reload: true, inherit: false, notify: false  });
$state.transitionTo($state.current, angular.copy($stateParams), {  reload: true, inherit: false, notify: false  });
```

The only thing that has worked to fully reload the route AND controller, is creating a dummy param and setting it randomly. Enjoy:

```
$state.transitionTo( $state.current, {reload : Math.random()}, { reload: true, inherit: true, notify: true } );
```

**Comment by christopherthielen** [comment]
If it's still broken , provide a plunk demonstrating the issue.

**Comment by malixsys** [comment]
Come on! Still?

This works perfectly for me in my Alert device:
        reload: function() {
          var current = $state.current;
          var params = angular.copy($stateParams);
          $rootScope.$emit('reloading');
          return $state.transitionTo(current, params, { reload: true, inherit: true, notify: true });
        },

**Comment by sunild** [comment]
This is the issue that keeps on giving! Sorry for the useless comment, but after a year of following this thread I had to say something before I unsubscribed. This is a great, indispensable project, thank you!

**Comment by wilk** [comment]
+1 @hpawe01! 
thanks!

**Comment by josipbosnjak** [comment]
@hpawe01 

thank you man!!! after hours of looking into this i finally stumbled upon your comment... saved me hours of looking into this!

amazing, thanks :)

**Comment by kamellcuba** [comment]
.state('srtypelist', {
                url: '/list',
                templateUrl: 'templates/tab-srtypelist.html',
                controller: 'srTypeListCtrl',
                cache: false // force reload the controller every time
            })

**Comment by maurei** [comment]
Hi,

I've been following this thread for a couple of days now. I've been trying to force a controller re-initialization on a ui-sref trigger, which works by doing `cache: false`

However, the reason I want to re-initialise my controller is because of some ajax request in the resolve function that precedes this initialization.

The issue I'm facing is that the resolve function won't be re-executed at all when `using cache: false`. Can anyone help me out on this?

Cheers

**Comment by malixsys** [comment]
This thread is 16 months long :)

Do you reload and how?

This works for me:

    function reload() {
        var current = $state.current;
        var params = angular.copy($stateParams);
        return $state.transitionTo(current, params, { reload: true, inherit: true, notify: true });
    }

and calls my resolve:[] again

**Comment by geemang2000** [comment]
@malixsys  This does not work for me. Its incredible this is still an issue. I've tried both go and transition

**Comment by malixsys** [comment]
@geemang2000 can you reproduce in a plunkr/jsfiddle/gist?

**Comment by geemang2000** [comment]
May bad.. this working. Have an asynch issue. I'm updating a record and then going to a list page. The list page loads it data before the update finishes...

**Comment by malixsys** [comment]
Use promises!



    Service.update().then(function(){reload();});





Martin Alix
+1 514 515-3469
sent via mobile

**Comment by geemang2000** [comment]
thanks @malixsys . yep promise fixed my issues. BTW: my resolves are working wtihout any reload etc. Plus I'm using go instead of transitionTo

**Comment by bautistaaa** [comment]
still having an issue with this. my resolve does get executed again but since the controller doesn't initialize my resolve variable never gets re assigned back to my scope

state:

      .state('tab.locations', {
        url: '/locations',
        views: {
          'tab-locations': {
            templateUrl: 'templates/tabs/tab-locations.html',
            controller: 'LocationsCtrl'
          }
        },
        resolve: {
          locationResource: 'Location',
          locations: function(locationResource, $stateParams){
            return locationResource.query().$promise;
          }
        }
      })

controller:

     .controller('LocationDetailCtrl', ['$scope', '$state', 'location',  function($scope, $state, location) {

         $scope.location = location.data; 
         // $scope.location never gets reassigned with the new resolve data. or am I missing something?

     }]);

reload snippet I am using:

    $state.transitionTo('tab.locations', $state.$current.params, { 
      reload: true, inherit: true, notify: true 
    });

**Comment by dshefchik** [comment]
One of these days I'm going to find some time and fix this. And the UI Router Gods will smile. And a child will be born. And this thread will be forever silent...

**Comment by Caramagicadmin** [comment]
@dshefchik prophet on the holy lands of Angular, splitting the waters of $stateprovider to guide the people toward reloaded controllers...

Joking aside, Ionic FW and it's cache handling was the problem for me too, so after a hour going through this interminable thread I wanted to throw in a BIG thank to @hpawe01 for his revelatory post!

**Comment by Caramagicadmin** [comment]
@dshefchik prophet on the holy lands of Angular, splitting the waters of $stateprovider to guide the people toward reloaded controllers...

Joking aside, Ionic FW and it's cache handling was the problem for me too, so after a hour going through this interminable thread I wanted to throw in a BIG thank to @hpawe01 for his revelatory post!

**Comment by Fateicha** [comment]
+1 @hpawe01

**Comment by seanfuture** [comment]
Was having same issue despite setting reload: true in latest version .. @hpawe01's solution worked for me ( setting cache to false in ui-router state settings )

**Comment by ckahle33** [comment]
I am using Ionic and almost every, if not all of my views being populated server data. I want to the ui-router refresh to work, but will turning off caching on all of my states cause performance issues?

**Comment by miguelcrespo** [comment]
@hpawe01's solution works for me!!

**Comment by masterkidan** [comment]
This doesn't seem to be working on IE 11 for me (it does work in chrome and FF).
But, it does seem to reload all controllers and states (including parents). Reading the thread, shouldn't $state.reload() only reload the current state and its children?

**Comment by simpixelated** [comment]
**Bug:** feature / appliance count is not showing up for anything but the exterior "room"

**Status:** investigating

**Comment by odellcraig** [comment]
@masterkidan I'm seeing the same result. Working for Chrome/FF, but not IE11. If I get a chance I'll create a plunker show the issue.

**Comment by quoideneuf** [comment]
@hpawe01 - :+1: Thanks!

**Comment by metamatt** [comment]
I'm trying ui-router 0.2.14 and am noting yet another way that `shouldTriggerReload` breaks this behavior. If I set `reloadOnSearch: false` for a state, then change a $stateParam that's part of the URL path (not a search param), I don't see the controller get reloaded. If I trace through the code, it's `shouldTriggerReload` returning true (which, again, counterintuitively means "skip reload") that causes the problem.

This falls directly out of the coded behavior for `shouldTriggerReload`:

```
  function shouldTriggerReload(to, from, locals, options) {
    if (to === from && ((locals === from.locals && !options.reload) || (to.self.reloadOnSearch === false))) {
      return true;
    }
  }
```

That final "or" clause means that for a state with `reloadOnSearch: false`, the locals check doesn't matter. If you transition to the same state you're already in (`to === from`) and that state has `reloadOnSearch: false`, you won't get a reload, no matter how different the state params are.

My take -- stop me if I'm wrong -- is this makes `reloadOnSearch: false` pretty much unusable. I [maintain](https://github.com/angular-ui/ui-router/issues/582#issuecomment-57508820) that it should be called `shouldSkipReload` and the `reloadOnSearch === false` condition should be applied more locally, though my previous suggestion was incomplete; it doesn't distinguish between path params and search params.

So we want something more like

```
  function shouldSkipReload(to, from, locals, options) {
    if ( !options.reload && to === from && (locals === from.locals || (to.self.reloadOnSearch === false && localsDifferOnlyInSearchParams(locals, from.locals)) ) {
      return true;
    }
```

with a suitable definition of `localsDifferOnlyInSearchParams`.

The reason I haven't just send this as a PR is I suspect there are subtleties I'm missing; I think in terms of URLs instead of states and maybe there are additional wrinkles for states that aren't expressible via URLs, and there are probably other reasons nobody's changed this in years. But please consider that the current behavior of `reloadOnSearch: false` is broken -- it breaks the `reload` flag, it breaks changes to non-search params.

**Comment by metamatt** [comment]
Ah, this last thing I'm complaining about is already filed separately as #1079.

**Comment by jorisw** [comment]
To anyone arriving here googling for re-execution of a controller after using `state.go()`:

If you want some code in your controller to execute every time its state is arrived at (not just the first time), wrap it in `beforeEnter` (before the transition) or `enter` (after the transition finishes):

```
.controller('yourCtrl', function($scope, $rootScope, $other, $depencies) {
 
 	$scope.$on('$ionicView.beforeEnter', 
                       function() {
                               // Code here is always executed when entering this state
                       }
         );

);
```

**Comment by zodiake** [comment]
thanks @jorisw !

**Comment by arafath-mk** [comment]
Thanks @hpawe01
It saved me a lot of time..!

**Comment by gakuba** [comment]
Thx @malixsys. the cache:false fixed my problems.

Cheers.

**Comment by novarac23** [comment]
Setting a cache worked fine for refreshing scope for me. Wondering how that will effect the preformance since data is not cached on a route now.

Was there an official fix for this ?

**Comment by christopherthielen** [comment]
@novarac23 officially this has been fixed for some time...  Most of the recent comments are related to ionic framework, not ui router.

**Comment by LeonanCarvalho** [comment]
:+1: 

@hpawe01 's solution doesn't work for me :cry:

**Comment by georgschlenkhoff** [comment]
Why not use trivial this fix:
```
<a href="javascript:history.go(0)">Reload this page</a>
```

**Comment by brianmyler** [comment]
First off, apologies, I know this is closed, but I cannot get my controller to re-initialise. I have tried everything that has been mentioned in this ticket and am at my wits end trying to get it working 

I have a state that uses a resolve to resolve some data from a resource. I then pass it through to the controller. On initial entry of the state, my resolve is executed and my controller gets the resolved param injected into it, which is as expected. The state displays a  view that is a list of orders in a cart.Each row in the list can be deleted and upon deletion, I would like to reload the page to show the updated list.

When i do this, my resolve gets executed, the service that houses the resource gets executed, but it seems that the result is not injected into the controller as expected

@bautistaaa, did you ever manage to get a solution to your problem? I have the exact same problem, and your code is pretty much identical to mine. 

var ccms_app = angular.module("orders-app", ['ngResource', 'ui.router', 'datatables', 'ui.bootstrap', 'ngAnimate', 'ngCookies', 'pascalprecht.translate']);

app.config(function($stateProvider, $urlRouterProvider) {
    $stateProvider
        .state('orders', {
            url: '/orders',
            templateUrl: 'angular_modules/orders/views/orders.html'
        })
        .state('orders.detail', {
            url: '/detail',
            templateUrl: 'angular_modules/orders/views/order-details.html',
            resolve: {
                userMetaData: function(userMetadataService){
                	return userMetadataService.getUserMetaData().$promise;
                }
            },
            controller: 'orderDetailsController'
        });
    $urlRouterProvider.otherwise('/orders/detail');
     
});

.controller('orderDetailsController', function($rootScope, $scope, $state, $stateParams, $resource, DTOptionsBuilder, DTColumnDefBuilder, ordersService, userMetaData) {
	
	$scope.model = $scope.model || {};
	
	$scope.model.userMetaData = userMetaData;
	
	$scope.model.orderdetails = $scope.model.orderdetails || [];
	
	$scope.getOrderDetails = function(){
		return ordersService.getCurrentOrderDetails().query({ type: 'current', org: $scope.model.userMetaData.orgId, user: $scope.model.userMetaData.id});
	};
	
	$scope.getOrderDetails().$promise.then(
		function(data){ 
			$scope.model.orderdetails=data;
		}, 
	    function(error){ 
			$scope.errormsg = "error"; 
			alert('error');
		}	
	);
	
	var errorCallback = function (e) {
		alert('Something went wrong '+e.data.Message);
    };
    
	var deleteSuccessCallback = function (e, cb) {
		$state.go($state.current, {}, {reload: true, inherit: true, notify: true});
	};
    
	$scope.deleteOrder = function (row) {
		ordersService.getOrderResource().remove({ id: row.id}, deleteSuccessCallback, errorCallback);
    };
    
});

**Comment by malixsys** [comment]
@brianmyler  Plunker or it never happened :)

**Comment by brianmyler** [comment]
@malixsys, you are correct, I should have provided a plunker, in fact, if i had of in the first place, I would have found that my issue was in fact nothing to do with the re-initialisation of my controller.

Turns out the problem was in fact my own stupidity :-). Ther service factory that housed the resource object that gets the user data from a rest endpoint was(well i thought it was) caching the response on the first call to this service. Turns out I had a typo and was in fact caching an empty object, which is why i had the problems 2nd time around. 

Anyway, apologies for wasting your time, plunkers first next time :-0

**Comment by malixsys** [comment]
@brianmyler No worries! I meant it in jest, but plunkers DO make it easier to diagnose and help. 
I am just amazed at this closed issue's longevity, though!

**Comment by kszpirak** [comment]
Super stupid problem. CACHE parameter solves the problem for me... 


.state('test.index', {
            url: '',
            templateUrl: dir + '/test/index.html',
            controller: ctrl + 'List',
            cache: false,
            resolve: {
                service: "ListService",
                resloveData: function(service, $stateParams) {
                    return service.get({
                        listType: 'test'
                    })
                }
            }
        })

**Comment by mgamsjager** [comment]
For the people using Ionic. You can disable the cache per view by adding cache-view="false" to the <ion-view> 

cache:false in the state definition or $state.go with reload parameter didn't help when using the Ionic framework.

**Comment by hirethisdeveloper** [comment]
Thanks mgamsjager, doing this in Ionic worked for me:

<ion-view view-title="Locations" cache-view="false">

**Comment by NaomiN** [comment]
So, what is the current status of this problem and what is the exact fix I need to implement? This is my current code:
if ($scope.searchParameters.categoryId != 0) {
                    window.console && console.log('Going to category state...')
                    $state.go('category', { categoryId: $scope.searchParameters.categoryId, createDaily: createDaily },{ reload: true });
                }

How should I change it to cause the Init of the controller that is associated with that state to fire?

Thanks in advance.

**Comment by NaomiN** [comment]
This is a very long thread and I am not sure what is exactly solution for my problem. On my index page I have two buttons Create Daily and New. Both of them correspond to the same state and should transition to the same view, but I need a server call to get updated model. I found that init of my second controller associated with that view is not firing after I added a new, clicked Add button to save and then clicked on the Create Daily on the index page. I've added cache: false without any effect. I'm using Google Chrome and AngularJS v1.3.13 for Angular.js and State-based routing for AngularJS
 * @version v0.2.8 for ui-router.js. What should be my solution to make sure my API call is happening when I press New/Save then CreateDaily buttons (or other way around)?

**Comment by NaomiN** [comment]
What is the official version of ui-router.js? Nuget only offers 0.2.08

Where and how can I grab the latest?

**Comment by malixsys** [comment]
0.2.15
http://angular-ui.github.io/ui-router/release/angular-ui-router.min.js

**Comment by NaomiN** [comment]
Thanks a lot, what about non-min version as well?

**Comment by IainCole** [comment]
http://angular-ui.github.io/ui-router/release/angular-ui-router.js

**Comment by NaomiN** [comment]
Latest ui-router.js file didn't resolve the issue for me. My code is the following:

  $state.go('category', { categoryId: $scope.searchParameters.categoryId, createDaily: createDaily },
                        { reload: true, inherit: true, notify: true });

The Init of the corresponding controller is not firing and the server's method is not called.

**Comment by NaomiN** [comment]
Looks like the issue I was having was actually related to a bug we had in our directive. Once we commented out 1 line of code (important, though), I didn't have the issue anymore

**Comment by malixsys** [comment]
This thread is undead.

**Comment by martijn-vdm** [comment]
@mgamsjager thank you so much for your hint! After hours of debugging and searching for less-than-optimal alternatives, adding cache-view="false" tom my ionic view for reloading the same view worked!

**Comment by angelxmoreno** [comment]
@mgamsjager I owe you a beer!

**Comment by edgahan** [comment]
Just quickly, in case it helps other: Adding `cache: false` to the state did not work for me, I had to add `cache-view` on the `ion-view` element like this: `<ion-view title="my title" cache-view="false">`

**Comment by iffakhry** [comment]
@hpawe01 thanks, work for me

**Comment by seyfiaslan** [comment]
Solution below worked for me. 
https://forum.ionicframework.com/t/reload-controllers-on-state-change-not-working-in-version-14/17619/2

**Comment by neolectron** [comment]
i lost 4hours on this bug, gg

**Comment by justinmichaels** [comment]
Why was this closed?  I'm using v0.3.1 and this issue still is happening.  I've even tried multiple of these solutions without any luck.

`$state.transitionTo($state.current, angular.copy($stateParams), { reload: true, inherit: true, notify: true });`

I'm still not seeing my controller constructor being hit.

**Comment by eddiemonge** [comment]
It was closed because it was fixed in https://github.com/angular-ui/ui-router/commit/7344342018847902594dc1fc62d30a5c30f01763

If you are still experiencing it, please open a new issue to track it.

**Comment by hhsadiq** [comment]
I was having this issue, able to solve it using solution mentioned in [ui-sref-active](https://github.com/angular-ui/ui-router/wiki/Quick-Reference#ui-sref-active) section of docs.

`<a ui-sref="home" ui-sref-opts="{reload: true}">Home</a>`
