### ISSUE TITLE
$state.go method and inherit option

### ISSUE THREAD

**Issue by mvolkmann** [angular-ui/ui-router#613]
I have a case where the URL of the current page contains query parameters. I want to go to another page, but omit those query parameters. I'm doing it like this:

```
var toParams = {};
var options = {inherit: false};
$state.go(newStateName, toParams, options);
```

The browser goes to the page associated with the new state, but the URL in the address bar still contains the query parameters. Shouldn't the "inherit: false" option prevent that?

**Comment by jusopi** [comment]
@mvolkmann did you get this resolved?  I too am having the same issue.  It seems that the `{inherit:false|true}` is getting ignored altogether
