### ISSUE TITLE
make $state.href hashbang prefix optional

### ISSUE THREAD

**Issue by mbyio** [angular-ui/ui-router#619]
I have found myself using the `$state.href` function to compile URLs for states. For the most part it is great, but I ran into a small issue related to the hash bang prefix when in HTML5 Fallback Mode. 

In HTML5 Fallback Mode `$state.href` returns URLs prefixed with the hash bang prefix, which is inconsistent with AngularJS' convention of hiding the prefix from users. For example, if I wanted to use the output of `$state.href` with the setter mode of `$location.url`, I'd run into an issue since `$location.url` refers to the portion of the absolute URL after the hash bang prefix.

I believe there is an inconsistency here between what a user expects and what actually happens. The documentation also does not help since it uses the following example from HTML5 mode:

```
expect($state.href("about.person", { person: "bob" })).toEqual("/about/bob");
```

This example is incorrect when in HTML5 fallback mode.

My solution to this issue is currently to just remove the prefix with a regular expression (`/^#.*?\//`) but it would be nice if we could choose whether or not to prepend the generated URL with the hash bang prefix.

**Comment by NioTeX** [comment]
+1 same reason

**Comment by muratakbal** [comment]
Do you have any update on this? It would be better to have an option to produce url w/o base prefix.

**Comment by dchacke** [comment]
+1

**Comment by 4ants** [comment]
+1

**Comment by rwngallego** [comment]
I end up using Michael suggestion, adding the ! character and allowing the slash /:

```
let url = this.$state.href(stateName, params);
url = url.replace(/^#!.*?/, "");

Result: /about/bob intead of #!/about/bob
```

**Comment by n-pavlov-devision-bg** [comment]
I decided to create a wrapper method named `$urlService.toUrl()` for `$urlService.url()` which removes the slashes when html5Mode is disabled, as a workaround until this is implemented.

This implementation is for AngularJS:
```js
angular.module('app', ['ui.router'])
  .config(($provide, $urlServiceProvider) => {
    'ngInject';

    $provide.decorator('$urlService', ($delegate) => {
      'ngInject';

      let originalUrlMethod = $delegate.url;

      /**
       * Wrapper method for $urlService.url() which handles hashPrefix, when html5Mode is disabled
       *
       * This wrapper method is created instead of overriding the original $urlService.url(),
       * because at some point UIRouter overrides the decorator, thus making it unusable.
       */
      $delegate.toUrl = (newUrl, ...otherArguments) => {
        if (angular.isDefined(newUrl)) {
          let wholePrefix = '#' + $urlServiceProvider.config.hashPrefix();
          newUrl = newUrl.replace(new RegExp('^' + wholePrefix), '');
        }
      
        return originalUrlMethod.apply($delegate, [url, ...otherArguments]);
      };

      return $delegate;
    });
  });
```
I originally tried to decorate the `$urlService.url()` method, but something was overriding my decorator. Do you have any idea what that might be?
