### ISSUE TITLE
0.3.0 Release 

### ISSUE THREAD

**Issue by btmdave** [angular-ui/ui-router#623]
Hello,

Any idea when 0.3.0 might be released? Are there any specific outstanding tasks I could help contribute to push this out?

Thanks,
Dave

**Comment by just-boris** [comment]
Now already 2015, but still there is no release.
@owners, you have a lot of updates, what about publish new version?

**Comment by ChrisCinelli** [comment]
I have to use "angular-ui-router": "#master" but once it broke the system. Having versioning would be so easy. Is it so difficult to release every now and then?
