### ISSUE TITLE
Optional support for keeping a view around

### ISSUE THREAD

**Issue by coli** [angular-ui/ui-router#63]
Add an option to a state that tells ui-view to keep it around even after route changes (then switch back to the old one instead of re-create it)

Use case is using ui-view for the content section of a tab.

```
<div>
  <tab-headers/>
  <ui-view/>
</div>
```

**Comment by Xeoncross** [comment]
I would also like to mention that DOM heavy renders like like maps or graph visualizations (with a more detailed item/brake-down view) is a very common use-case. Judging by the amount of questions on SO, and elsewhere, it seems like something that is desired.

It seems like you could store the last X ui-view DOM's (if the user enables this feature) and just pop older ones off. The main problem seems to be the un-binding (and rebinding) of scope.

Still, for perceived performance I wouldn't mind keeping X number of previous views in memory so they don't have to be rendered again. Some maps and charts just take a few seconds to render which isn't ok if you have lots of markers or chart entry points to review in more detail.

**Comment by neekey** [comment]
@jeme I'm doing something kind of like the use case you mentioned above。I use url search to navigate the active tabs:

```
/list?type=a&page=1
/list?type=b&page=2
```

and my use case is quite simple, I am rendering a list, including a tab to filter the type of the list and a pagination component follow the list for user to navigate. what I want to implement is when user changes the `type` tabs or navigate to a different page, the url search changes simultaneously . And if user manually type the exact url like `/list?type=c&page=3`, the state refreshes and the `type` tabs active to `c` and pagination component active to `3`.

So the feature required to implement this is quite straight forward, providing a method to change the url search without reload the state, like:

```js
$state.setSearch({ type: 'c', page: 3}, false); // the second parameter indicates the state not reload
```

or for now is there some way to work this around?

**Comment by naorz** [comment]
If you using ionic, try this:
http://ionicframework.com/docs/api/directive/ionNavView
in this page scroll to "cashing"
its works on every view of ionic view
