### ISSUE TITLE
When using "base href" ui-router generates wrong urls 

### ISSUE THREAD

**Issue by drozzy** [angular-ui/ui-router#638]
Proper urls are not generated properly by `ui-sref` when `<base href="/foo/bar/" />` is present.

My angular app is hosted in the `foo/bar` directory.
In my `index.html`:

```
<base href="/foo/bar/" />
```

my routes are like:

```
.state('mystate', {
        url: '/statelocation',
        ... })
```

and here is how I reference the state in the template:

```
<a ui-sref='mystate'>Go to my state!</a>
```

And instead of outputting:

```
<a href="statelocation">Go to my state!</a>
```

I get (note the slash):

```
<a href="/statelocation">Go to my state!</a>
```

**Comment by catazep** [comment]
I am not sure you have the same problem as I do, but this issue ruined my day, and after hours of trying to fix it beautiful I used this workaround http://stackoverflow.com/questions/34211894/angular-ui-router-ui-sref-links-arent-prepending-the-hash-when-filling-in-href/34775725#34775725
