### ISSUE TITLE
$location's url is wrong when navigating backward

### ISSUE THREAD

**Issue by graphicsxp** [angular-ui/ui-router#642]
First, I want to point out that if I use ui-router v0.0.1 (long way to go), I do not have the problem :) 
But I use v0.2.5 and I'm having issues with the $locationProvider while trying to handle navigation history in my SPA.

I have a page with a paginated grid. The URL is:

http://myserver/#/products

If I browse to page 2 of the Product list, the URL is:

http://myserver/#/products?pagingOptions%5BcurrentPage%5D=2

If I browse back to page 1, the URL is:

http://myserver/#/products?pagingOptions%5BcurrentPage%5D=1

Note that the $$absUrl property of the $location service matches the URL of the browser and the $$search property also contains the correct query parameters.

Now I browse to a different page, for example to edit a Product from my list. The URL becomes:

http://myserver/#/products/3/edit

And then I browse back to the list using the back button of the browser. Obviously, the URL becomes:

http://myserver/#/products?pagingOptions%5BcurrentPage%5D=1

However, in the $location service, the $$absUrl is not the one displayed in the browser ! Now the $$absUrl property is http://myserver/#/products. And the $$search property is empty !

What could be the reason(s) for this behaviour ?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
