### ISSUE TITLE
Sample App - Updating Page Title

### ISSUE THREAD

**Issue by Xiot** [angular-ui/ui-router#674]
I noticed an oddity in the sample application when using updating the page title using the current state.  I posted on SO (http://stackoverflow.com/questions/20183222/updating-title-tag-using-angularjs-and-ui-router) with an explanation and re-production steps. 

In short, click on About, and the first item in the history has the title 'about - ui-router' instead of 'home - ui-router'

**Comment by timmaybrown** [comment]
+1 for a fix to this bug.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
