### ISSUE TITLE
reloadOnSearch: false will not change the location url

### ISSUE THREAD

**Issue by mmukarram** [angular-ui/ui-router#677]
I'm trying to use the reloadOnSearch config property (v0.2.7) to disable reloading the state to navigate between multiple pages of a product list. My state is configured as follows:

``` javascript
$stateProvider.
state('app.account.products', {
            url: '/products/preview?page&sort',
            templateUrl: 'products.preview.html',
            reloadOnSearch: false,
            controller: 'ProductsCtrl',
            data: { title: 'Preview' }
        }).
```

Pager links (on ngclick):

``` javascript
$stateParams.page = pageNum;
$state.go($state.current.name, $stateParams, { reloadOnSearch: false });
```

The paging works fine without any reloads, however, it does not refresh the url, i.e. if I'm on app/products/preview and I move to the next page app/products/preview?page=2&sort=asc, the url in the address bar still shows app/products/preview for all subsequent pages. Is this by design? If so, how can I resync the $location based on the search string?

**Comment by Elijen** [comment]
I also just ran into a problem with reloadOnSearch. Here is a plunker: http://plnkr.co/edit/2lgzlKe7E8m56AHLDnou

When you click on any of the links, nothing happens. I don't think this is expected behaviour. The `$stateChangeSuccess` event should be triggered.

**Comment by michalsnik** [comment]
@Elijen +1

**Comment by modikejal10** [comment]
Have found this thing to work for me,
$state.go($state.current, {params},{notify:false,reload:$state.current});

**Comment by yozlet** [comment]
Thanks @modikejal10, that worked for me too!

**Comment by elvisspirjan** [comment]
Thanks @modikejal10 it works  :)

**Comment by cbier1** [comment]
Warning, `{notify: false}` is deprecated
