### ISSUE TITLE
ui-router doesn't run the current state if your ui-view is inside an ng-include

### ISSUE THREAD

**Issue by nickretallack** [angular-ui/ui-router#679]
ng-include a template that has a ui-view in it.  When the page loads, ui-router won't run the current state.  Navigate to a new url and back and the state will run.

**Comment by dallonf** [comment]
Also seeing this issue. Also can report the workaround helps.

For anybody who might be using Jade, here's a quick gotcha: `div(ui-view)` compiles to `<div ui-view="ui-view"></div>`. What you need is `div(ui-view="")`. Not sure if that's useful to anybody else in this thread, but it wasted a good half hour of my time thinking the workaround wasn't helping.

**Comment by carlos-algms** [comment]
+1.
I want to make a dynamic template engine that expose ui-view inside a ng-include.

**Comment by ilyagelman** [comment]
+1

**Comment by nickretallack** [comment]
This is still tripping people up a year later?

**Comment by ilyagelman** [comment]
Well, it only works for me if I inject $state at the run state.

**Comment by theghostbel** [comment]
.run() hack-fix helped us, but "vanilla-angular" support is really needed, so, +1

**Comment by tslater** [comment]
+1

**Comment by nateabele** [comment]
I'll look into this when I have time, but for now, there are plenty of equally-problematic issues that _don't_ have [simple workarounds](https://github.com/angular-ui/ui-router/issues/679#issuecomment-31116942), so I can't logically prioritize this.

If someone else wants to dig into it and report back (or better yet, open a PR), that'd be great.

**Comment by uditalias** [comment]
+1

**Comment by Kaijun** [comment]
same here, but i found a solution as @ilyagelman mentioned:
```
    .run(['$state', function($state){
        
    }]);
```
will fix, but donno why...

**Comment by fithwith** [comment]
+1

**Comment by justechn** [comment]
I am having a similar problem, but adding .run does not fix it 
http://plnkr.co/edit/Na5zkF?p=preview

The xxx button at the top should open a sidenav, just like the big button in the body, and next to the xxx button should be a title. Neither of those are working because they are included in an ng-include

**Comment by ps1dr3x** [comment]
Same here, .run solution not working
