### ISSUE TITLE
State or View Loaded Event?

### ISSUE THREAD

**Issue by udayms** [angular-ui/ui-router#68]
Is there an event that is fired when the view or state is loaded? I want to attach some event listeners after the DOM has loaded. app.run() doesn't help here. Any ideas?

**Comment by dhill-ss** [comment]
Note for some - I had an issue where the map.resize() did not work on $stateChangeSuccess due to a hard to see race condition and a tiny timeout did the trick:
`$scope.$on('$stateChangeSuccess', function() { $timeout(function () { $scope.map.resize(); }, 10); });`
