### ISSUE TITLE
Template loaded, but not shown.

### ISSUE THREAD

**Issue by miraage** [angular-ui/ui-router#683]
https://gist.github.com/miraage/272664028c29c6c27fa2

Script loaded, `$state.go` fired, template loaded but not shown..
I have valid markup with `div[data-ui-view]`..

What I do wrong? Or bug?

// upd

http://plnkr.co/edit/PdlMbjtpWsKg5nEobxFJ

// upd @ 15:00 UTC 17 Dec 2013

Could you please point me to a possible problem? I will try to figure out it and create pull request if will find solution.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
