### ISSUE TITLE
$stateParams always returns an empty object

### ISSUE THREAD

**Issue by dmatteo** [angular-ui/ui-router#691]
This is my whole controller

```
app.controller('ProfileController', 
   function($scope, $rootScope, wsCall, $state, $stateParams) {

    wsCall.getUserProfile(11)
        .then(function(r) {
            $scope.user = r
        })

    $rootScope.$on('$stateChangeSuccess',
        function(event, toState, toParams){
            console.log(toState, toParams)
            console.log( $stateParams )

        })
})
```

Problem is, `console.log( $stateParams )` returns an empty object, even if `console.log(toState, toParams)` works correctly

**output:**

```
Object {url: "/{section}", templateUrl: "parts/profile/profile-info.html", name: "home.profile.details"} Object {section: "groups"}
Object {} 
```

I don't see any problem with the code, but `$stateParams` won't cooperate...

_tested w/ ui-router_0.2.7 && angular 1.2.2, angular 1.2.5_

**Comment by kymtwyf** [comment]
@timkindberg the url you provided was invalid. please check out [the new one]( https://github.com/angular-ui/ui-router/wiki/URL-Routing#important-stateparams-gotcha)
