### ISSUE TITLE
Should state rejection trigger an event?

### ISSUE THREAD

**Issue by chopachom** [angular-ui/ui-router#709]
I'm using https://github.com/voronianski/ngprogress-lite to add a visual feedback for state transitions:

``` javascript
$rootScope.$on('$stateChangeStart', function(){
  ngProgressLite.start();
});

$rootScope.$on('$stateChangeSuccess', function(){
  ngProgressLite.done();
});

$rootScope.$on('$stateChangeError',  function(){
  ngProgressLite.done();
});
```

This works when user is logged in, however, when user isn't logged in I use some code that prevents transition to the states that require authentication, something in the lines of:

``` javascript
 $rootScope.$on("$stateChangeStart", function (event, toState, toParams, fromState, fromParams) {
   if (toState.data.loginRequired !== false && !authService.isAuthenticated()) {
     event.preventDefault();
     $state.go('login');
   }
 });
```

And this breaks the progress loader when user clicks on the links that require authentication, becase it fires `$stateChangeStart` but never fires any event that would indicate that state transition was prevented.
I'm wondering if adding a new event for rejected transition would solve this problem, or maybe i'm just doing it in the wrong way and global progress can implemented using other means.

Edit: of course I added a call to `ngProgressLite.done` to the state-guarding code, but I don't know, that's looks like breaking separations of concerns for the modules.

**Comment by deanapeterson** [comment]
I was able to add a $stateChangeRejected.  Please see the following gist.

https://gist.github.com/deanapeterson/b93b48fd8c258861f26b

This has not been fully tested.  But seems to do the job.  Please let me know of any issues you may find.
