### ISSUE TITLE
Hash bang routing with root path ("/")

### ISSUE THREAD

**Issue by TheSharpieOne** [angular-ui/ui-router#739]
In the sample states.js: `// Use a url of "/" to set a states as the "index".`

When entering the site at the root/index/home level and using hashbangs, the $location.path() will return `""` instead of `"/"`.  When a state's url option is `"/"` to match the root/index/home, it will not match (`"" != "/"`).

If the $location.path() is an empty string (`""`) it should match the root/index/home state (`"/"`)

Here is the `$location` when entering the root/index/home of a site at the time the match is performed.
![angular-hash-problem](https://f.cloud.github.com/assets/664714/1852783/5d851e34-7700-11e3-9ede-eeb231a914c3.png)

*The manual hash was me going directly to the url with the hash already in place.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
