### ISSUE TITLE
How do I pass an expression to ui-sref?

### ISSUE THREAD

**Issue by gigablox** [angular-ui/ui-router#745]
Let's say I need dynamic `ui-sref`

```
<div ng-repeat="panel in panels">
  <a ui-sref="panel.state" class="thumbnail">
    <h2>{{ panel.name}}</h2>
  </a>
</div>
```

Where my panels look like:

```
{
  name:'Contact General',
  state:'contact.general'
},
{
  name:'Contact Other',
  state:'contact.other'
}
```

Is it possible to pass the object property into the `ui-sref` directive?
From the docs it seems like it only accepts strings.

**Comment by SanjanKalsi** [comment]
**Just append '' to the state and voila, its done (works for me :) )"**

## <a ui-sref="panel.state+''" class="thumbnail">
