### ISSUE TITLE
A potential bug - inconsistent behavior to determine state parent

### ISSUE THREAD

**Issue by esakal** [angular-ui/ui-router#811]
Hello,

this issue is relevant for version 0.2.8

I noticed an inconsistent behavior in the code:

line 1152 - function ```$StateProvider.stateBuilder.parent```:
prioritize parent property over state name convention (if defined)

line 1305 - function ```registerState(state)```
prioritize state name convention over explicit parent property

In my understanding explicit parent property should beat naming convention. 

Any thought?
Eran

**Comment by rob3c** [comment]
Hi, I just ran into this issue and wanted to add that the docs in the "Naming Your States" section of the readme contradict the current behavior in the registerState function mentioned above (emphasis added):

_When using dot notation the parent is inferred **if it is not explicitly provided**, but this doesn't change the state name._

Cheers,
Robert

**Comment by rob3c** [comment]
Oops, I said readme, but it's really this [Nested States & Nested Views](https://github.com/angular-ui/ui-router/wiki/Nested-States-&-Nested-Views) page.
Notice it says "When not using dot notation, the parent must be explicitly provided...", which along with the above quote implies it's ok to combine dot notation with an explicit parent.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
