### ISSUE TITLE
Autoscroll confusion -- Want my pages to scroll to 0 when I click around. New behavior in 0.2.8

### ISSUE THREAD

**Issue by scottbaggett** [angular-ui/ui-router#816]
Hi Everyone --- I have a quick question that hopefully is easily answered. After updating to 0.2.8 I'm noticing that as I click around my site, the scroll position on the site stays fixed and not resetting back to 0. I'm expecting the pattern where you click a link, a new page renders and it's scrolled back to 0. Previous to this update that was the behavior I had.  Whats the quickest way to restore this functionality in 0.2.8?

**Comment by just-boris** [comment]
+1 to @Deminetix, new behavior is different from native, so it is a bit surprising

**Comment by EvilJohnny** [comment]
Thanks @Deminetix, this was driving me absolutely crazy

**Comment by nicogarcia** [comment]
:+1:

**Comment by blunatic** [comment]
+1 to @Deminetix

**Comment by esetnik** [comment]
Thanks for the solution guys. I find it a bit silly that this isn't the default behavior.

**Comment by timelf123** [comment]
This worked for me, credits to http://stackoverflow.com/a/29153678/411284
```
.run(function($anchorScroll, $window) {
  // hack to scroll to top when navigating to new URLS but not back/forward
  var wrap = function(method) {
    var orig = $window.window.history[method];
    $window.window.history[method] = function() {
      var retval = orig.apply(this, Array.prototype.slice.call(arguments));
      $anchorScroll();
      return retval;
    };
  };
  wrap('pushState');
  wrap('replaceState');
})
```

**Comment by stephengardner** [comment]
Please, guys.  Use @timelf123's solution.  and.... THANK YOU!

@ashconnell's solution is great, but it will infuriate you to find that the back and forward buttons do not return to where the page was before.

**Comment by ashconnell** [comment]
@stephengardner this is a way better solution. I still can't help but wonder why ui-router even needs this hack in the first place.
