### ISSUE TITLE
Resolver's order of execution

### ISSUE THREAD

**Issue by maharaja-sv** [angular-ui/ui-router#843]
I added resolver in both child state and parent state. When I accessed my child state directly the order of resolver is executed in reverse. First the child state resolver executes then parent state resolver executes, which must b executed in reverse. For ex. Consider there are countries List from which I select state then city, I need to get countries List(COUNTRY State) through my parent resolver and then state list(STATE State) for a specified country through next child resolver which has Country as $stateparam and then city list(CITY State) for the selected state through next child resolver which has state as $stateparam. Now when I access the url with country and state directly i.e /India/TamilNadu then my resolver is executed in reverse.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
