### ISSUE TITLE
0.2.8 prevents animation on elements within a ui-view

### ISSUE THREAD

**Issue by thaoula** [angular-ui/ui-router#849]
Hi Guys,

After switching to 0.2.8, I no longer get any animations on controls contained within ui-views.

Using 0.2.7 and Angular 1.2.10 I was able to utilize some animations on ng-repeat. The animations stopped working after upgrade ui-router.

Anyone got a work around for this issue? 

Regards,
Tarek

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
