### ISSUE TITLE
Add parallell views and deactivated views

### ISSUE THREAD

**Issue by empaempa** [angular-ui/ui-router#863]
Hey!
I'm using Ionicframework (which uses angular-ui-router) to build an app. Native apps usually have parallell views (see the Spotify app, for example, where Search, Browse, Discover etc are parallell) and each of these parallell views have a history. 

For example, if you go into Spotify's Search view, do a search and go on to the Artist view and then back to Search view again the search results are still there. Similarly if you do a search in the Search view then go to the Discover view and back to the Search view again, the search results are still there.

Would be great to be able to use named ui-views to create parallells (suggesting to use | (pipe) prefix):

```HTML
<div ui-view="|search"/>
<div ui-view="|discover"/>
```

When a search-view is active, all other ui-views on the same level get's a "display:none" (or any other way of hiding, whatever is fastest).

The state could be defined as:

```JS
$stateProvider
  .state( "|search", { url: "/search", templateUrl: "search.html", controller: "searchCtrl" } );
  .state( "|discover", { url: "/discover", templateUrl: "discover.html", controller: "discoverCtrl" } ); 
```

And for ancestors (suggesting to use > separator to indicate that parent views are preserved):

```JS
.state( "|search>artist", { url: "/search/artist/:id", templateUrl: "artist.html", controller: "artistCtrl" } );
.state( "|search>album", { url: "/search/album/:id", templateUrl: "album.html", controller: "albumCtrl" } );
```

If you search and select an artist, the artist.html will appended as a child to the "|search" ui-view and the search.html content will be applied with "display:none" to be hidden. When going back, the artist.html will be removed from the DOM and the search.html will be shown again.

Does it sound reasonable? Feedback appreciated! Maybe the state name and the name of the ui-view shouldn't be connected as suggested?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
