### ISSUE TITLE
These nested states + event cause infinite loop in $digest

### ISSUE THREAD

**Issue by rnikander** [angular-ui/ui-router#871]
It looks like a bug to me, but maybe I'm just using it wrong.  I posted some boiled down example code here:

http://stackoverflow.com/questions/21631896/why-does-this-angular-ui-router-code-cause-an-infinite-loop-in-digest

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
