### ISSUE TITLE
Run Time State Setting

### ISSUE THREAD

**Issue by crisward** [angular-ui/ui-router#874]
Not sure if I'm missing something in the docs, but I can't find anyway of doing this. I want to write a directive with a options of passing in a base path, ie

```
<div my-directive basepath="/some/path/"></div>
```

Then have my directive have a ui-router which appends all it's states to this path.

This doesn't seem possible at the moment as the states are created in the config step and there doesn't appear to be anyway of changing these. If the state urls could be looped through and updated, I could do this when the directive is first created and update the states.

Use cases for this are re-usable modules which bring there own routes. They would only really be re-usable if they could be appended to a specific state. 

(I thought this kind of thing maybe possible after listening to Dean Sofer on JS Jabber - excellent module btw..)

**Comment by eddiemonge** [comment]
The module should have its own ng-app right? I feel like setting the `url: ""` to should work to be relative from the current location
