### ISSUE TITLE
Views are rendered twice on route transition

### ISSUE THREAD

**Issue by DorianGrey** [angular-ui/ui-router#881]
My team has recently faced an issue with controllers being instantiated twice on route transition. While trying to find the reason for this, I've recognized that even the corresponding views got rendered twice, which was rather... unlikely.
This problem was detected in v0.2.7 - https://github.com/angular-ui/ui-router/commit/20fcbf8384090a092c7c91a26443e3c818438120 thus I considered moving to v0.2.8 - https://github.com/angular-ui/ui-router/commit/f9ce4dddbe579d215ba84ee9e9ec29249b23ec05 should solve this. But it did not.
### Information

**Angular-version**: 1.2.11
The relevant routes look like this (I cannot post everything, since it's part of a closed project):

``` javascript
$stateProvider
        .state('1ColumnLayout', {
            'abstract': true,
            url: "/1",
            templateUrl: "1ColumnLayout.html"
        })
        .state('login', {
          parent: "1ColumnLayout",
          url: "/login",
          views: {
            "screen-above": {template: ""},
            "screen": { templateUrl: "login.html", controller: "loginController"}
          }
        })
       .state('plantDetails', {
           parent: "2ColumnLayout",
           url: "/plantDetails?plantId",
           views: {
               "screen-above": { templateUrl: "userInfoAndNavigation.html"},
               "screen-left": { templateUrl: "details.left.html", controller: "detailsLeftController"},
                    "screen-right": { templateUrl: "details.right.html", controller: "detailsRightController"}
                },
                resolve: {
                    currentId: getId(false)
                }
            })
```

While using this template in _1ColumnLayout.html_...

``` html
<div id="screen-above" class="clearfix" ui-view="screen-above"></div>
<div class="screen1Column clearfix" id="screen-below">
  <div class="s1cContent" ui-view="screen"></div>
</div>
```

...and this one in _2ColumnLayout.html_

``` html
<div id="screen-above" class="clearfix" ui-view="screen-above"></div>

<div class="screen2Column clearfix" id="screen-below">
  <div id="screen-right" ui-view="screen-right"></div>
  <div id="screen-left" ui-view="screen-left"></div>
</div>
```

In a more-or-less long debugging session, I was able to drag down the issue to the following line in _viewDirective.js_ (in v0.2.7):

``` javascript
initialView = transclude(scope);
```

The call stack mentioned that by calling transclude(...), the compile function is called again, building up the entire view, including controller instantiation. Afterwards, the function went ahead as expected, but destroyed the previously built view completely, building it up once more.
In v0.2.8, this line of code has changed to 

``` javascript
anchor    = angular.element($document[0].createComment(' ui-view-anchor ')),
```

which seems more intuitive. However, moving to v0.2.8 did not fix the issue - seems to be broken on another part.
### The curious thing...

... is primarily related to the _sometimes_ in the topic: After performing all potential route transitions at least once, all views got rendered only once - as expected. 
### Workaround

Anyway, just for testing, I've changed 

``` javascript
initialView = transclude(scope);
```

in v0.2.7 to 

``` javascript
 initialView = angular.element($document[0].createComment(' ui-view-anchor '));
```

(picked from v0.2.8), and injected $document as well. Result: Everything worked as expected (I've added my diff so that the whole change is visible), which is... interesting.

``` diff
diff --git a/public/lib/angular-ui-router/src/viewDirective.js b/public/lib/angular-ui-router/src/viewDirective.js
index efc8930..5e0a9ed 100644
--- a/public/lib/angular-ui-router/src/viewDirective.js
+++ b/public/lib/angular-ui-router/src/viewDirective.js
@@ -1,6 +1,6 @@

-$ViewDirective.$inject = ['$state', '$compile', '$controller', '$injector', '$anchorScroll'];
-function $ViewDirective(   $state,   $compile,   $controller,   $injector,   $anchorScroll) {
+$ViewDirective.$inject = ['$state', '$compile', '$controller', '$injector', '$anchorScroll', '$document'];
+function $ViewDirective($state, $compile, $controller, $injector, $anchorScroll, $document) {
   var $animator = $injector.has('$animator') ? $injector.get('$animator') : false;
   var viewIsUpdating = false;

@@ -15,7 +15,8 @@ function $ViewDirective(   $state,   $compile,   $controller,   $injector,   $an
             name = attr[directive.name] || attr.name || '',
             onloadExp = attr.onload || '',
             animate = $animator && $animator(scope, attr),
-            initialView = transclude(scope);
+            initialView = angular.element($document[0].createComment(' ui-view-anchor '));
+

         // Returns a set of DOM manipulation functions based on whether animation
         // should be performed
```

Even worse, I was not able to reproduce this issue using v0.2.8 with a more simple example, and I'm not sure why it still occurs - wasn't that _easy_ to drag down to a particular line as in v0.2.7 ;)

Maybe some of you have a clue what may cause this, or may check this in a more complex project - rendering views twice, including controller instantiation, is rather unlikely when it comes to performance, or possible side-effects that come along with init-functions.
For the moment, this appears to be a blocking issue in our case which prevents us from moving to v0.2.8 and, as a result, from other fixes / improvements.

**Comment by ikhos** [comment]
I am using 0.2.13 and this is still happening.

**Comment by nateabele** [comment]
@ikhos What version of Angular?

**Comment by ikhos** [comment]
@nateabele I'm using 1.3.15. Since I am using multiple modules I am using angular.bootstrap().

```
'use strict';

angular.module(ApplicationConfiguration.applicationModuleName, ApplicationConfiguration.applicationModuleVendorDependencies);

angular.module(ApplicationConfiguration.applicationModuleName).config(['$locationProvider',
	function($locationProvider) {
		$locationProvider.hashPrefix('!');
	}
]);

angular.element(document).ready(function() {
	if (window.location.hash === '#_=_') window.location.hash = '#!';

	angular.bootstrap(document, [ApplicationConfiguration.applicationModuleName]);
});

```
This is the bootstraping config:
```
'use strict';

var ApplicationConfiguration = (function() {
	var applicationModuleName = 'myApp';
  var applicationModuleVendorDependencies = [
    'ui.router',
    'ui.bootstrap',
    'ngAnimate',
    'ngSanitize',
    'ngTouch',
    'ajoslin.promise-tracker',
    'angular-google-analytics',
    'angular-inview',
    'LocalStorageModule',
  ];

	var registerModule = function(moduleName, dependencies) {
		angular.module(moduleName, dependencies || []);

		angular.module(applicationModuleName).requires.push(moduleName);
	};

	return {
		applicationModuleName: applicationModuleName,
		applicationModuleVendorDependencies: applicationModuleVendorDependencies,
		registerModule: registerModule
	};
})();
```
I just found out that if I comment the angular.bootstrap(...) line, the ui-view renders just once. Any hints on this behaviour will be greatly appreciated.

**Comment by ikhos** [comment]
I feel really dumb now. I was using ng-app="" as well as initialising the app programmatically. I just removed the ng-app directive from my view and everything works perfectly now. Thanks.

**Comment by nateabele** [comment]
:+1: You might feel dumb for having wasted time on it, but those are the best kinds of problems to have. Seriously.

**Comment by roybein** [comment]
I almost missed @edrpls 's answer, just because @nateabele 's bad joke. :smirk:
thank you all.
Maybe silly, but remind again. hey, @edrpls 's answer helps.

**Comment by ionescho** [comment]
This occurs for me with the latest ui-router. I need to use ng-app="app" and angular.bootstrap because I have window.name = "NG_DEFER_BOOTSTRAP!";  .The app is only instantiated once, so why does this occur for me still?

**Comment by Roycohen** [comment]
Hi there,
I'm using Angular 1.3.15 and latest UI-Router (0.2.18) and my root UI-VIEW is always duplicating.
I'm bootstrapping the application by myself and not like @edrpls, I'm not using ng-app :)

How can I fix that? Where are the suspicious places that might make this issue?

**Comment by mathilde-pellerin** [comment]
Hi there,

I'm facing the same issue. Using Angular 1.4.9 and angular-ui-router 0.2.18. 
The application is bootstrap using only the directive ng-app.
On load, no problem, the ui-view directive behave as expected and routes work well. But at some point, I use 
`$state.go('defaultRoute', {}, {reload: true});`
This line reload the page as expected, but during the refresh the ui-view is duplicated for a moment.
This duplication prevent one of my controllers to initialise scroll event on window as it should.

Do someone have any clue of what causes this ?

**Comment by davidsmith242** [comment]
Hi there,
the problem still exists with angular 1.5.3 and angular-ui-router 0.2.18. The directives on my view are initialized a second time when I route to the next view. 
Is there a bug fix available to avoid this problem??

**Comment by alexilyaev** [comment]
Why is this Closed?

This happens to me as well when using Chartist.js (charting library).
Once I add a Pie chart, the root `<ui-view>` is duplicated, the second one is empty.
If I navigate to this state from another state, I can see my previous state at the bottom `<ui-view>` and my current state at the top one.

I'm bootstraping with `angular.bootstrap`, no `ng-app` anywhere.

This hack fixes it:
```js
$rootScope.$on('$stateChangeStart', () => {
  $animate.enabled(false);
});
```

But I'd really like it to be resolved, especially if I'd want to add state change animations later on.

Versions:
```
"angular": "1.5.0",
"angular-animate": "1.5.0",
"angular-ui-router": "0.2.18",
```

**Comment by dgunderson** [comment]
This is still a problem for me too. I'm using ng-animate along with ui-router to animate transitions. I started noticing that my view content was appearing twice on the screen, the bottom of the two look like styled empty templates while the one above is rendered properly. I'm using ng-app, **not** bootsrapping the app in js.

These are my versions:

```
"angular": "1.5.5",
"angular-animate": "1.5.5",
"angular-ui-router": "0.2.18",
```

**Comment by kmaraz** [comment]
For me the solution was to completely remove angular-animate. And it is extremely bad solution I know.

**Comment by chillyistkult** [comment]
It's also an issue for me. Is there any acceptable workaround yet?

**Comment by ebenmoha** [comment]
+1

**Comment by nroma** [comment]
Me too have this problem using the following versions:
`"angular": "^1.4.0",
  "angular-animate": "^1.4.0",`
To solve this issue I disable animation for the view that has effects.

The code for this workaround is the following:
`<div ui-view="theView" class="no-animate">`
and in CSS:
`.no-animate {
   -webkit-transition: none !important;
   transition: none !important;
}`

**Comment by Arkh1** [comment]
+1 
I removed instances of reload:true to get around this on some pages, but I still have other pages that are rendering multiple views for a split second during state transitions.  The rootscope listener that @alexilyaev posted gets around the issue, but I also would like a better solution.  I was hoping I could get around it with absolute view naming, but that doesn't seem to help.
