### ISSUE TITLE
TemplateUrls loaded from different domain throw errors in IE 8/9

### ISSUE THREAD

**Issue by mfrye** [angular-ui/ui-router#885]
I'm hosting my partials on S3 and loading them into ui-router like this.

```
$stateProvider
    .state('home', {
      url: "/",
      templateUrl: "https://s3.amazonaws.com/ambassador-client-dev/pages/home.html",
      data: {
       ...
      }
    })
```

This works fine in the standard angularjs router after you whitelist the urls as so.
```
ambassador.config(['$sceDelegateProvider', '$stateProvider', '$urlRouterProvider', function($sceDelegateProvider, $stateProvider, $urlRouterProvider) {
	
    $sceDelegateProvider.resourceUrlWhitelist([
    'self',
    'http://0.0.0.0**',
    'https://s3.amazonaws.com/**',
	]);
...
```

Using ui-router it will throw an error though - TypeError: Access denied. This is happening in both IE 8 and 9.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by colouredFunk** [comment]
Hello, How did you get this to work with xdomain, as this is for http.gets ? I'm trying to get it to work with -

 $routeProvider
    .when('/', {
        templateUrl: playerURL + 'views/templates/videos.html',
        controller: 'VideosController'
    })
    .when('/contributors', {
        templateUrl: playerURL + 'views/templates/contributors.html',
        controller: 'ContributorController'
    })
    .otherwise( {
        templateUrl:playerURL + 'views/templates/videos.html',
        controller: 'VideosController'
    })
