### ISSUE TITLE
No option to use transitionTo with toState as relative under $stateChangeStart event

### ISSUE THREAD

**Issue by peledkfir** [angular-ui/ui-router#895]
I found out that there is no option to do the following:

$rootScope.$on('$stateChangeStart', function(ev, toState, toParams, fromState, fromParams) {
$state.transitionTo('^', toParams, { relative: toState });
}

As the toState is the self of the state object and not the internal one as expected.

I workaround it in the following way:

$state.transitionTo(_.strLeftBack(toState.name, '.'), toParams);

however it depends that the state name is written under the dot notation.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
