### ISSUE TITLE
Make ui-sref accept objects and not only Strings

### ISSUE THREAD

**Issue by mgonto** [angular-ui/ui-router#900]
Hey,

Sometimes we actually want to link to another state based on a value on scope and not only by text.

I think it might be a good idea to make ui-sref accept values and call `$eval` on it. I created my own directive for this. You may want to use something similar. I can PR this as well to your code if you guys want.

https://github.com/mgonto/mgo-ui-router-goto/blob/master/uiGoto.js

Thanks!

**Comment by christopherthielen** [comment]
Fixed in 3831af1dc71b601351e6694af0665a77297f8f7f
