### ISSUE TITLE
Re-opening issue 890 (Dynamic View Building)

### ISSUE THREAD

**Issue by vb8190** [angular-ui/ui-router#901]
There is no way in the current api to dynamically create named views but instead you have to hard code the names in the state configuration and that is a big bottleneck if somebody is trying to create a reusable module architecture based on ui-router.  Does this make sense?

```javascript
$stateProvider.state('stateName', {
  url: '/xyz',                 
  views: {
    'namedViewA': {
      templateUrl: 'app/tempA.tpl.html'
    },
    'namedViewB': {
      templateUrl: 'app/tempB.tpl.html'
    },
    'namedViewC': {
      templateUrl: 'app/tempC.tpl.html'
    }
  }
});
```

'namedViewA', 'namedViewB', 'namedViewC' have to be hardcoded which is very restricting. There should be a way to define these views on fly i.e. there should be a capability where a list of these viewnames can be sent from external client and the views object above could be built dynamically.

**Comment by nateabele** [comment]
Would being able to register states at runtime solve this?

**Comment by AquilaSagitta** [comment]
Is it possible to change the state object within a resolve?

**Comment by nateabele** [comment]
@AquilaSagitta Nope.

**Comment by AquilaSagitta** [comment]
Is there a way to get a remote configuration before the state object is instantiated?

For example: User 'Foo' and User 'Bar' go to my sites homepage. Server-side User 'Foo' is configured to show view 'A' while User 'Bar' is configured to show view 'B'. Is it possible to request the information from the server prior to creating the state?

**Comment by nateabele** [comment]
Why not have two different states and use the user's configuration to pick which one to go to?

**Comment by AquilaSagitta** [comment]
Because there could be a potentially unlimited amount of user views

**Comment by AquilaSagitta** [comment]
Got a solution!!

```javascript
angular.module('foo', [ 'ui.router' ])
  .config(function($stateProvider) {
    $stateProvider
      .state('home', {
        url: '/',
        template: '<p>Original template</p>'
      });
  })
  .run(function($rootScope, $state){
    // Example for simplicity sake. Exchange code here to get data remotely
    $state.get('home').template = '<div>Alternate Template AHH YEAH!!</div>';
    $state.go('home');
  });
```

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
