### ISSUE TITLE
Proposal for nested states

### ISSUE THREAD

**Issue by marklagendijk** [angular-ui/ui-router#903]
Relates to #346 and #368.

Currently there are [4 ways](https://github.com/angular-ui/ui-router/wiki/Nested-States-%26-Nested-Views) of defining states:
1. Using 'dot' notation. For example `name: 'contacts.list'`
2. Use my [ui-router.stateHelper](https://github.com/marklagendijk/ui-router.stateHelper) to build states from a nested state tree.
3. Using the parent property with the parent name as string. For example: `parent: 'contacts'`
4. Using the parent property with the parent object. For example `parent: contacts` (where 'contacts' is an stateObject)

My proposal is to make the logic of stateHelper a part of ui-router itself, and make sure that all ways of defining nested states give a consistent result:
- A states name is always its full name. This means that it contains the full path of it parents in dot separated form. For example: 'root.contacts.list'. 
- Each (non root level) state gets `parent` property. This parent property contains the state object of its parent.
- Each state which has descendent state gets a `children` property. This property contains all the child states of the state.

This way the different ways of declaring nested states always produce a consistent result. I think this consistency is very important.
We should also consider whether it would still make sense to support al 4 ways. In my opinion way 3 and 4 wouldn't add anything when 1 and 2 are already supported in the way I described above.

@nateabele, @timkindberg, I would like your opinion about this. I would be willing to implement this functionality, including tests.

**Comment by jelling** [comment]
What's the latest thinking on this? I ran into some issues today and have had various issues over the years with nested states being tricky to define. Could be wrong but felt like there were extra wrinkles with lazy-loading, too.
