### ISSUE TITLE
Parent onEnter not firing when child state have to resolve something

### ISSUE THREAD

**Issue by brunomacf** [angular-ui/ui-router#909]
In my code a declare a parent state like: 

$stateProvider.state('parent', {
        abstract: true,
        templateUrl: 'parent/parent.tpl.html',
        controller: 'ParentCtrl',
        resolve: {
                logged: function(service) {
                        return service.logged();
                }
        },
        onEnter: function($state, logged) {
                if(!logged) {
                        $state.transitionTo('login');
                }
        }
});

and a child state like:

$stateProvider.state( 'parent.child', {
        url: "/child",
        views: {
                'main': {
                        templateUrl: 'parent/child/child.tpl.html',
                        controller: 'ChildCtrl',
                        resolve: {
                                something: function(service) {
                                        return service.someFunction()
                                });
                         }
                 }
        }
});

In this case the onEnter function of the parent is not calling!! If i remove the resolve statement in the child state everything works as expected....the issu just happens when the child state has a resolve statement!

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
