### ISSUE TITLE
RFC: Default Query String Params

### ISSUE THREAD

**Issue by meenie** [angular-ui/ui-router#938]
This is something that has plagued me for the last couple of months.  When doing things like pagination, I like to use query strings.  It doesn't matter what order they are in, they are optional, and it's industry standard.  What I don't like is that I can't set a default value for each of the query strings that I register with my state.  So in my `resolve` I have to check if something like `page` is empty, if it is, set it to 1.  Or if `limit` is empty, set it to 25. If I could just pass the current `$stateParams` straight to my XHR call without having extraneous code checking for defaults that would be fantastic.

So have something like this:

``` javascript
$stateProvider.state('products', {
    url: '/products?page&limit&orderBy&direction',
    controller: 'ProductsCtrl as ProductsCtrl',
    templateUrl: 'app/products/template.tpl.html',
    defaultQueryParams: {
        page: 1,
        limit: 25,
        orderBy: 'popular'
    }
});
```

Then if someone landed on `/products`, the `$stateParams` would be:

``` javascript
{
    page: 1,
    limit: 25,
    orderBy: 'popular'
}
```

If the url was `/products?orderBy=price&direction=desc`, the `$stateParams` would be:

``` javascript
{
    page: 1,
    limit: 25,
    orderBy: 'price',
    direction: 'desc'
}
```

I am willing to put in the work to get this done.  I just want to make sure it's something that is needed and will get merged in :).

**Comment by gronel** [comment]
please help me how to set static value in query string this is my code

`.state('160100000027', {
                                     url: '/issues/Response/?modtype=1',
                                     templateUrl: '/Issues/TopicResponse',
                                     controller: 'ctrlTopicResponse as ctrl',
                                     ncyBreadcrumb: {
                                         label: 'Topic'
                                     }
                                 })`
