### ISSUE TITLE
"Back" browser button with $urlRouterProvider.when

### ISSUE THREAD

**Issue by filso** [angular-ui/ui-router#940]
I think it would be useful if it had option of not adding redirection to browser history.
Because when I click "back" button, it immedietely redirects me to new url

For example:
with $urlRouterProvider.when('/route2', '/route3');

I am in /route1, I go to /route2, it immeditely redirects me to /route3
Now I want to go back to /route1, but browser goes back to /route2, which immedietely redirects to /route3

Solution: option to omit '/route2' in browser history

I can create PR if that's something you want to include

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Comment by amera7md** [comment]
i have the same issue when i click back from state have parameters to mian state that is the default statue of UI router
