### ISSUE TITLE
set current name with ui-router in angularjs

### ISSUE THREAD

**Issue by enemijs1** [angular-ui/ui-router#941]
So My problem is when i click on `inventory.name` which sets `setCurrentName`, in my other view `description.tpl.html` it's not showing, the current selected data. I guess i have to add `resolve:` function in `stateProvider`? Can somebody help my out?

In description.tpl.html

     <p class="list-group-item-text">{{currentName.name}}</p> 

In stateProvider

 

    app.config(function config( $stateProvider) {
      $stateProvider.state('inventory',{
        url:'/inventory',
    		views: {
    			"main": {
    				controller: 'InventoryCtrl',
    				templateUrl: 'inventory/main.tpl.html'
    			}
    		},
    		data:{ pageTitle: 'Inventory' }
      }
      ).state('inventory.description',{
        url:'',
    		views: {
    			"main": {
    				controller: 'InventoryCtrl',
    				templateUrl: 'inventory/description.tpl.html'
    			}
    		},
    		data:{ pageTitle: 'DescriptionView' }
      });
    });

in my main.tpl.html

`<div ui-view="main"></div>`

setting my current name

    <div ng-repeat="inventory in info.objects">
    		<a ui-sref="inventory.description" ngclick="setCurrentName(inventory.name)">{{inventory.name}}</a>	

And i have my function in the controller named InventoryCtrl

   

    $scope.currentName = null;
    
    $scope.setCurrentName = function(name) {
    	for(var i = 0; i < $scope.info.objects.length; i++){
     	    if($scope.info.objects[i].name == name){
    	        $scope.currentName = $scope.info.objects[i];
    		break;
    	    } 
    	}
    };

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
