### ISSUE TITLE
Child default state issues with the ui-sref & URL

### ISSUE THREAD

**Issue by CMCDragonkai** [angular-ui/ui-router#948]
In the FAQ https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#wiki-how-to-set-up-a-defaultindex-child-state

For option 1, you can add a default child state by making the parent state abstract and adding a url to the parent state and allowing the default child state an empty url so it can inherit the parent url and match the parent state's url.

The option 2 is redirection.

```
$stateProvider.state(
    'parentState',
    {
        abstract: true,
        url: '/parent/child',
        template: '<p>Parent <ui-view /></p>',
        controller: function() {}
    }
).state(
    'parentState.childState',
    {
        url: '',
        template: '<span>Child</span>',
        controller: function(){}
    }
);
```

However when you go about trying to transition to it such as using ui-sref, it can no longer transition to the parent state anymore. (This is because the parent state is an abstract state).

These things don't work:

```
<a ui-sref="parentState></a>
OR
$state.go("parentState");
```

These however work:

```
<a ui-sref="parentState.childState></a>
$state.go("parentState.childState");
```

It seems non-intuitive to go about setting up a default childstate and then in the process lose the ability to transition to the parent state. If I could just setup a default childstate, and then transition to the parent state, ui-router should be able to just fallback onto the default child state. I shouldn't need to explicitly set the childstate that I want to go to. What if I want to change what my default child state is? Now all my state declarations need to change!

The option 2 of this child state setup opens up possibility of duplicate content. If you combine option 2 with removing `abstract:true` from the parent state, and have the child state have its own url segment, then it is a possible solution to the above problem. But surely hardcoding redirection should not be required.

**Comment by Saucyboy** [comment]
Just hit the wall with abstract parent with default child and ui-sref links. Will this issue see the light or am I out of luck?

**Comment by DonSailieri** [comment]
+1

**Comment by alanmoo** [comment]
+1

**Comment by Vilsepi** [comment]
+1

**Comment by llosimura** [comment]
+1

**Comment by Machiel-B** [comment]
+1

**Comment by AurelioB** [comment]
+1

**Comment by shanesmith** [comment]
+1

**Comment by sumomostudio** [comment]
+1

**Comment by krotkiewicz** [comment]
+1

**Comment by Muhammad-Muneer** [comment]
+1

**Comment by javialon** [comment]
+1

**Comment by rriemann** [comment]
:+1:

**Comment by raphaelluchini** [comment]
+1

**Comment by SamHellawell** [comment]
+1

**Comment by ermakovich** [comment]
Yes, please make it's possible to use abstract states with `ui-sref`

**Comment by ChrisMondok** [comment]
+1

**Comment by eddiemonge** [comment]
Lots of interest in seeing this done. @nateabele @timkindberg is this a feature that you are still willing to accept a PR for?

**Comment by christopherthielen** [comment]
For now, don't declare your state abstract, and use this recipe:
```

 app.run($rootScope, $state) {
    $rootScope.$on('$stateChangeStart', function(evt, to, params) {
      if (to.redirectTo) {
        evt.preventDefault();
        $state.go(to.redirectTo, params)
      }
    });
  }
```
---
```
  $stateProvider.state('parent' , {
      url: "/parent",
      templateUrl: "parent.html",
      redirectTo: 'parent.child'
  });
  $stateProvider.state('parent.child' , {
      url: "/child",
      templateUrl: "child.html"
  });
```

**Comment by eddiemonge** [comment]
@christopherthielen that seems to work pretty well. Why not make that part of ui-router?

**Comment by christopherthielen** [comment]
@eddiemonge something pretty similar will likely make it in

**Comment by wefarrell** [comment]
+1

**Comment by gregbenner** [comment]
@christopherthielen +1 fixed my issue

**Comment by anonomis** [comment]
+1

**Comment by walterjsilva** [comment]
+1

**Comment by SpeedShifter** [comment]
+1

**Comment by alexhoo** [comment]
+1 (@christopherthielen pretty clever )

**Comment by JungmoKang** [comment]
+1 
thanks a lot!

**Comment by mattobee** [comment]
+1

**Comment by fynnfeldpausch** [comment]
+1

**Comment by invernizzie** [comment]
+1

**Comment by diegogurgel** [comment]
@christopherthielen Thanks :+1:

**Comment by amazingandyyy** [comment]
+11

**Comment by aaronlifton2** [comment]
+1
