### ISSUE TITLE
Add `children` option to state configs

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/ui-router#953]
Would be an array of states (strings/objects). This would allow us to attach a child to multiple parents, thereby allowing amazing code reuse (and opening up the opportunity for truly pluggable modules).

If you create a path-relative (agnostic) implementation of an 'edit' module, you could attach it to both a person and project and task module and get some excellent code reuse across the board.

**Comment by eddiemonge** [comment]
Can this be closed or is it still needed?
