### ISSUE TITLE
Trigger state reload from ui-sref

### ISSUE THREAD

**Issue by fynnfeldpausch** [angular-ui/ui-router#960]
Is it possible to add a reload option to the `ui-sref` directive, just like the option within the options of `$state.go(to, params, options)`. The directive would simply check whether the option is set and use it in the internal call of `$state.go`.

**Comment by MelloDredd** [comment]
@fynnfeldpausch i was having same issue as yours ... to trigger force reload of state from ui-sref directive. Couldn't find whether it is possible or not but i used a workaround. Since i am using angular js ... so i just write

ng-click="rootState.go('sendMail',{},{reload : true});" 

in my html element and it is working just fine. Here rootState is the reference of $state. You can define the reference in your controller or app.run as i did. 

hope it helps

**Comment by Javarome** [comment]
For the record, you can use the `ui-sref-opts="{reload:true}"` attribute to achieve that.

**Comment by MelloDredd** [comment]
@Javarome .. yeah thanks.. figured it out later

**Comment by technotip** [comment]
ui-sref-opts="{reload:true}" not working.. please help. It's bit urgent.

**Comment by fabdeceglia** [comment]
Hi, the same for me.

ui-sref="myState({reload: true})"
and also 
ui-sref="myState" ui-sref-opts="{reload:true}"

is not working.
Also for me is urgent ;)

**Comment by irthos** [comment]
+1 on a fix

**Comment by Trial-In-Error** [comment]
I also appear to be having an issue with this, but it may be some other misunderstanding. Any idea if this is still a live issue?

**Comment by PedroGabriel** [comment]
@Trial-In-Error just tried it and worked.
`ui-sref="myState" ui-sref-opts="{reload:true}"` reloaded the current state.

**Comment by bapinney** [comment]
I wanted to chime in and mention I am having this issue, too.

ui-sref="home" ui-sref-opts="{reload: true}" does not work for me.  The data is the same as what I viewed previously, whenever I click on that anchor element.  However, if I force a browser refresh, only then will the newer data show up.

The version of Angular I am using is https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js

**Comment by PedroGabriel** [comment]
Set the same params you don't want to `null` and remove the reload thing
It should work
If you don't want any params, set all as a null value
Em 20 de jun de 2016 21:36, "Branden Pinney" <notifications@github.com>
escreveu:

**Comment by bapinney** [comment]
Hey Pedro,

I appreciate the response.  I did just that and the page still does not reload data when I navigate back to it.  I still have to click the refresh button.  This is what I have:  data-ui-sref="home" data-ui-sref-opts="{location: true, inherit:null, relative:null, notify:true}"

I'll keep working at this and if I find something that works, I'll come back here and post what I did.

**Comment by PedroGabriel** [comment]
actually mine worked like this: `$state.go('app.lista_oferta',{cid:null,empresa:null});`

but I always set my `ui-sref` params like this: `ui-sref="app.lista_oferta({cid:null})"`
never used `data-ui-sref-opts`

**Comment by Trial-In-Error** [comment]
So, my issue was entirely a misunderstanding on my part! The service I was calling in the resolve statement returned a promise, not a function that returned a promise. So, being a singleton and all... Anyways, cleared that up and everything now works as expected! Just thought I'd leave this comment for anyone else that might have the same problem: Make sure that your service returns a function that returns a promise!

**Comment by sandeepmachiraju** [comment]
data-ui-sref-opts="{reload:true}"  is working for me. please try by adding data to  
ui-sref-opts="{reload:true}"
