### ISSUE TITLE
includedByState matching only beginnig of state (?)

### ISSUE THREAD

**Issue by jkarttunen** [angular-ui/ui-router#963]
IncludedByState only seems to match the beginning of a state. This reduces the reusability of views.

It would be useful to be able to write

      li(ng-class="{active: ('.local' | includedByState)}")
        a(ui-sref=".local")

**Comment by stefanotorresi** [comment]
`'.local' | includedByState` is an expression that will be evaluated only once so, unless you use it inside a view, the transition to the current state may not have occurred yet.

**Comment by jkarttunen** [comment]
@timkindberg this was hoping for a cleaner syntax than ```ng-class="{ active: $state.includes('**.local')}"```

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
