### ISSUE TITLE
$stateChangeSuccess event

### ISSUE THREAD

**Issue by fxck** [angular-ui/ui-router#968]
$stateChangeSuccess is(obviously) ran after all states have been changed, but before controllers are initialized. Is there any way to find out when the last child controller had been initialized? Or this is completely outside ui-router's competence?

I think it's somewhat similar to $viewContentLoaded though, which is ran after the controller is initialized, but the problem is that it's ran after each one of them is initialized, not just the last one..

**Comment by FourwingsY** [comment]
I had a same problem.
I solved my problem by changing ng-if to ng-show of the view that controller attached.
