### ISSUE TITLE
ui-sref params is changing in very strange way

### ISSUE THREAD

**Issue by mike1808** [angular-ui/ui-router#971]
I have the following issue.

plunkr: http://plnkr.co/edit/qguCtCScGRAuwWowFRnJ?p=preview
**View**

```html
<a ui-sref='main.gallery(currentParams)'>gallery</a>
```

**Controller**

```javascript
function MyCtrl($scope) {
    $scope.currentParams = { lng: $scope.currentLang };
    $scope.currentLang = 'en-US';
    $scope.$watch('currentLang', function(newLang) {
         $scope.currentParams.lng = newLang;
    };
    // ...
    // some changes with $scope.currentLang when state changes1
}
```
**State Config**

```javascript
$stateProvider
    .state({'main', url: '/:lng', abstract: true})
    .state({'main.gallery', url: '/gallery', template:'gallery', controller: 'MyController'});
```
Now when $scop.currentLang changes to, for example, 'en-CA' the watch handler of uiSref directive is triggered and in the if check

```javascript
if(newVal !=== params) update(newVal);
````
Params is changed to $scope.currentParams **before** it reach to if statement, thus it doesn't update.

I have tried to do this way

```javascript
Object.observe(params, function() { debugger; });
```

to track the params changes, but it called after __if__ statement fails.

P.S. Also, I think that I did something wrong

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
