### ISSUE TITLE
$uiViewScroll firing when ng-if evaluates to false

### ISSUE THREAD

**Issue by mrdbarker** [angular-ui/ui-router#972]
I'm decorating $uiViewScroll and have noticed that when navigating away from a state, even if the ui-view with autoscroll has an ng-if that evaluates to false, $uiViewScroll is called again.

I've set up a plunker so you can take a look: http://plnkr.co/edit/lkh5S8uq3GOA28CFgnux

Could this be related to https://github.com/angular-ui/ui-router/issues/881 ?

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
