### ISSUE TITLE
Shared controller for multiple views

### ISSUE THREAD

**Issue by mfrye** [angular-ui/ui-router#973]
I've seen a couple issues on this already and I understand that we won't be supporting this layout:

```
.state('manage.dash.payouts.history', {
      url: "history/",
      controller: 'PayoutsCtrl',
      views: {
        "stats@manage.dash": { templateUrl: ... },
        "filter@manage.dash": { templateUrl: ... },
        "table@manage.dash": { templateUrl: ... }
      }
    })
```

But why doesn't this work? The PayoutsCtrl controller never gets called. How else can I have one controller to manage all these views?

```
.state('manage.dash.payouts', {
      abstract: true,
      url: "payouts/",
      controller: 'PayoutsCtrl',
    })
.state('manage.dash.payouts.history', {
      url: "history/",
      views: {
        "stats@manage.dash": { templateUrl: ... },
        "filter@manage.dash": { templateUrl: ... },
        "table@manage.dash": { templateUrl: ... }
      }
    })
```

**Comment by miraage** [comment]
Have same question. What is current progress?

**Comment by szexigexi** [comment]
i'm afraid there is no progress.

but +1 on this feature, it would be great!

**Comment by jsancho** [comment]
+1 on this feature, this would be incredibly handy!

**Comment by dietergoetelen** [comment]
Any news? I'm facing the same problem...

**Comment by phamdt** [comment]
+1

**Comment by ploski** [comment]
+1

**Comment by benoror** [comment]
+1

**Comment by ionescho** [comment]
+1

**Comment by devoncloud** [comment]
same issue.. please suggest

**Comment by devoncloud** [comment]
I got my answer and think no change is required

**Comment by rgcr** [comment]
+1

**Comment by ionescho** [comment]
@devoncloud what answer did you get?

**Comment by devoncloud** [comment]
I am not an expert but here is my 2 cents . Coming from a object oriented programming background , I think it is not required to communicate between sibling classes. If sibling classes need to communicate they should do it through the parent.

**Comment by phamdt** [comment]
i originally wanted sharing of controllers, but ended up doing what devoncloud suggested by communicating via the parent.

**Comment by mzvast** [comment]
Why this syntax wouldn't work?Any process currently?
.state('dashboard.info',{
      url:'/:nid',
      css:['styles/dashboard/navtree.css'],
      controller:'DashboardCtrl as dashboard',
      views:{
        'topology':{
          templateUrl:'views/dashboard/topology.html'
        },
        'filter':{
          templateUrl:'views/dashboard/filter.html'
        },        
        'datatable':{
          templateUrl:'views/dashboard/datatable.html'
        },
        'chart':{
          templateUrl:'views/dashboard/chart.html'
        },
        'graph':{
          templateUrl:'views/dashboard/graph.html'
        },
        authenticate:false
      }
    })

**Comment by jgarcia100uniandes** [comment]
+1

**Comment by JasemQabazard** [comment]
same issue here 2 scopes one for header and another for the main view in the same state using the same controller

**Comment by christopherthielen** [comment]
@JasemQabazard We will not be implementing shared scopes for different controllers, nor shared controller **instances** for different views.  

I suggest moving towards a component and services architecture.  Communicate between child/parent, or refactor the common logic out to a service and delegate in each component.

**Comment by rubenswieringa** [comment]
Just wanted to put this out there as an alternative/workaround:

If you don't mind shifting the logic in whatever state with named-views that you want to share a controller for, to a directive, then you could see about using [multi-slot transclusion](https://docs.angularjs.org/api/ng/directive/ngTransclude#multi-slot-transclusion) instead.

It's not ideal, and it doesn't cover all the use-cases for named-views with shared controllers, but it is the closest thing if you somehow really need a shared controller.
