### ISSUE TITLE
IE8 messing up with ui-router

### ISSUE THREAD

**Issue by leog** [angular-ui/ui-router#975]
Hi all,

I've been searching for a while now and I couldn't get any answer, so here I am.

The thing is that I have a page which is something like ```https://localhost/site/``` and I'm defininf the routes like this:

```JavaScript
angular
  .module('SiteModule', deps)
  .config(function ($locationProvider, $stateProvider, $urlRouterProvider, $sceDelegateProvider) {
       $sceDelegateProvider.resourceUrlWhitelist(['path/to/template','self']);
       $locationProvider.html5Mode(true);
       $urlRouterProvider.otherwise('/entity/0');
       $stateProvider.state('entities', {
            url: '/entity/:id',
            templateUrl: 'path/to/template',
            controller: function() {...}
       });
   });
```

Everything works great on any browser except for IE8 (of course).

When you get to the site, and click a link to ```https://localhost/site/entity/``` I'm redirected to ```https://localhost/site/#/entity/0``` which is the root of my site. And by redirect I mean that I see the expected result of the UI being loaded correctly just a second and then the browser refreshes to load ```https://localhost/site/``` content although the URL is ```https://localhost/site/#/entity/0```.

I tried the base meta tag:

```Javascript
document.write('<base href="' + document.location + '" />');
```

but, I need to be able to go to an entity directly, so going to ```https://localhost/site/#/entity/123``` should load correctly the content, which obviously does not.

Any ideas?

Thanks a lot in advance.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
