### ISSUE TITLE
Chrome crashed while setting `reload` option to `true` using method `$state.go`.

### ISSUE THREAD

**Issue by leftstick** [angular-ui/ui-router#982]
See my plunker:
http://plnkr.co/edit/yvUhiD?p=info

The code was very easy based on the sample: 

```javascript
$state.go('route1.list', undefined, {reload:true});
```

While setting `reload` to `false`, it works just fine. But browser just crashed since setting to `true`. It's a bit weird that `doc` didn't describe stuff like this.

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
