### ISSUE TITLE
Can we pass objects these days with transitionTo ?

### ISSUE THREAD

**Issue by Bretto** [angular-ui/ui-router#983]
can we pass objects these days with transitionTo ?

**Comment by kilaka** [comment]
Tried and worked using `transitionTo` . Don't know if works with `go`.

**Comment by shavo007** [comment]
:+1:

**Comment by filipesilva** [comment]
Tried and worked with `go`, but I'm getting some inconsistent behavior depending of the parameter.

The target state seems to only reloaded if the param is different at a shallow level. Example in [this plunker](http://plnkr.co/edit/JLVk4rvwpAU3AM7TTxXO?p=preview).

In that example, I have an array that is filled with random numbers when you click the link. 

If I send that array into `state.go` directly, the child state will not be reloaded (check console for `child loaded` messages). But if I `slice` the array (creating copy of the array reference) then the child state is reloaded.

I would expect the state to be reloaded regardless, since the contents of the parameter changed.

**Comment by christopherthielen** [comment]
I'm pretty sure we don't do deep comparisons by default. I think we do 'a == b' and since you reuse the same array reference they are '=='.  We have support for array-type for url parameters, but I'm not sure how that would work for non URL params ('array: true'). Otherwise, implement your own type with an equals() that deep compares.  Come to think of it, you might be able to set the param type to "json" which does deep compare.

**Comment by filipesilva** [comment]
I can't seem to find the param type 'json' in the documentation, is it a new addition?

**Comment by christopherthielen** [comment]
Your plunk works with 'json' type:   http://plnkr.co/edit/kBmbxyaU8eWVlNKtEHwX?p=preview

Yeah, json parameter type was added here: https://github.com/angular-ui/ui-router/releases/tag/0.2.13  but looks like it never got documented

**Comment by christopherthielen** [comment]
As a followup, I actually created the "any" type for exactly your scenario.  It doesn't encode/decode and uses angular.equals to do a deep compare.  Use that instead of 'json' type.  

However, I also thought that non-url parameters were automatically declared as "any" types, hrm...

**Comment by filipesilva** [comment]
Indeed types 'json' and 'any' solve my issue on my production website, many thanks!

Going over those commits, it seems the whole 'type' section of params is undocumented [here](http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$stateProvider).

Would a PR of mine to document it be welcome, or is this something on the pipeline for later on?

**Comment by christopherthielen** [comment]
Hold up.  I've made a few stupid mistakes while looking at your plunk:

1) non-url parameters do indeed use the 'any' type by default.  Therefore your original plunk was using the 'any' type.

2) Declaring `type: 'any'` or `type: 'json'` is not _currently_ a valid param configuration option.  I thought it was valid, and I think we should make it valid in the future. See my note below:

3) the reason your plunk "works" when I changed it to `type: 'json'` is that:
* It actually passed the string literal 'json' to the `Type` constructor, making a new anonymous type with the default implementation (which, ironically, uses `==` to test equality)
* You are always passing params as a a *new object literal* to state.go(foo, { obj: *{array: blah }* }), and so == is *always* false

So, now with a fresh perspective, the reason ui-router thinks your parameter has *not* changed in your original plunk is as follows:
1) It was indeed using the 'any' type
2) It was doing a deep compare of the object
3) You live-updated the from params when you pushed the new value.  The from params have a *reference* to your array.
4) You create a new object and put a reference to the same array inside it
5) The to params and from params are equal, according to `angular.equals`

The answer you're looking for is to create a copy of the array, before sending it to `$state.go`


Note from above:
We should update getType to get the type from the `$types` registry, if the `config.type` is a string in this block of code: 
```
    function getType(config, urlType, location) {
      if (config.type && urlType) throw new Error("Param '"+id+"' has two type configurations.");
      if (urlType) return urlType;
      if (!config.type) return (location === "config" ? $types.any : $types.string);
      return config.type instanceof Type ? config.type : new Type(config.type);
    }
```

**Comment by filipesilva** [comment]
I think I understand. In fact, that `splice` you found odd in the plunkr was a bug in my attempt to copy the array via 'slice`!

My real world scenario is slightly more complex: I am live-updating several arrays, which then I put inside of an object and send it as parameters for `$state.go`. Thus I can either `slice` all those arrays, or set the type (which will end up being anonymous) on the state params.

**Comment by filipesilva** [comment]
Regarding your note, I believe this should do the trick:

```
    function getType(config, urlType, location) {
      if (config.type && urlType) throw new Error("Param '"+id+"' has two type configurations.");
      if (urlType) return urlType;
      if (!config.type) return (location === "config" ? $types.any : $types.string);
      if ((config.type instanceof String || typeof config.type === 'string') 
        && $types[config.type]) return $types[config.type];
      return config.type instanceof Type ? config.type : new Type(config.type);
    }
```

I need to read up on the tests here on `ui-router` and try to setup my env to run them, afterwards I can do a PR to implement and test.

**Comment by christopherthielen** [comment]
> My real world scenario is slightly more complex: I am live-updating several arrays, which then I put inside of an object and send it as parameters for $state.go. Thus I can either slice all those arrays, or set the type (which will end up being anonymous) on the state params.

I don't think you want to rely on `toParams == fromParams` because that will *always* return false, and your state will always reload.  

Can you instead do `$state.go("foo", angular.copy(paramsObj))`?

**Comment by christopherthielen** [comment]
`npm install && bower install`
`grunt karma:watch` / `grunt karma:unit` / `grunt karma:debug`

While developing a test, find the describe block you're interested in and change `describe` to `ddescribe` (this will cause jasmine to run only that block).

https://github.com/angular-ui/ui-router/blob/master/test/urlMatcherFactorySpec.js#L483-L591

**Comment by nateabele** [comment]
I think you mean `fdescribe`.

**Comment by christopherthielen** [comment]
> I think you mean fdescribe.

0.2.15 is still on an older jasmine version so it uses `iit` and `ddescribe`
