### ISSUE TITLE
If the child state only adds parameters to the parent URL, transition to it fails

### ISSUE THREAD

**Issue by stasgrom** [angular-ui/ui-router#986]
Some time ago I've opened an issue saying that if the child state doesn't have its own URL, transitioning to it will not render its view.

It has been fixed since. However another issue still exists:

if the child state adds only a URL parameter to the parent URL, transitioning to it will not render its view. Seems like the transitioning to parent state is initiated immediately after that.

See this code example: http://plnkr.co/edit/Oz6P2p

**Comment by eddiemonge** [comment]
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb
