### ISSUE TITLE
ui-sref doesn't make new href attr when working with curly braces

### ISSUE THREAD

**Issue by pawsong** [angular-ui/ui-router#995]
When working with angular template like this, 

``` html
    <a ui-sref="{{val}}">Hello</a>
```

after value of 'val' is updated, ui-sref directive does not make href tag to be updated. Is there any way to make ui-sref watch it's value change?

**Comment by ferencrocks** [comment]
If somebody is still wondering how's possible to pass state names or params as expressions, there's an another directive for that: https://ui-router.github.io/ng1/docs/latest/modules/directives.html#uistatedirective

**Comment by jasonc62492** [comment]
> If somebody is still wondering how's possible to pass state names or params as expressions, there's an another directive for that: https://ui-router.github.io/ng1/docs/latest/modules/directives.html#uistatedirective

THANK YOU, 2022 still working on angular 1.4 for a company :[

**Comment by nateabele** [comment]
> THANK YOU, 2022 still working on angular 1.4 for a company :[

TBH 1.x is still the best version...
